### ISSUE TITLE
Optional to use Discord real user token or selfbot

### ISSUE THREAD

**Issue by 3-commerce** [discordjs/discord.js#10006]
### Which application or package is this feature request for?

discord.js

### Feature

Allow an optional variable to use token of Discord real user (selfbot) and Discord bot apps

### Ideal solution or implementation

Add optional vars into client.login for distiguish token bot and token user

### Other context

I need to use Discord real user token for my inventory office rather than Discord bot apps. The urgency is my enterprise team that doesn't allow any additional users join into my office channel Discord.

So, my team decide to use dummy discord account (real user) to be Discord bot rather than registering Discord bot apps.

I know in T.O.S discord to disallow the usage of Discord token user to be bot but i still can use Discord gateway (without SDK) to reach my goals. However, i know it's complicated and hope Discord JS sdk can help me.

**Comment by monbrey** [comment]
The automation of user accounts is not allowed as per Discord's Terms of Service, and will not be supported by discord.js
