### ISSUE TITLE
Updated @discordjs/collection@2.0.0 breaks node16 compatility (EBADENGINE)

### ISSUE THREAD

**Issue by crycode-de** [discordjs/discord.js#10002]
### Which package is this bug report for?

discord.js

### Issue description

When installing recent version of `discord.js` on node 16 an unsupported engine warning will be shown as of the the automatically installed package `@discordjs/collection@2.0.0` requires node >= 18.

```sh
user@host:/tmp/tmp.8sXz0qWtWM$ npm i discord.js
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@2.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@2.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```

As of the `package.json` from `discord.js` it should be compatible with node >=16.11.0 so all depended packages of the discord.js packages should not require a higher version.

This issue breaks for example automated pipeline checks [here](https://github.com/crycode-de/ioBroker.discord/actions/runs/6995107894/job/19029585748#step:2:616) and didn't happen about 3 weeks ago.

### Versions

- discord.js 14.14.1
- Node: 16.20.2

Output of `npm ls @discordjs/collection`:
```
└─┬ discord.js@14.14.1
  ├── @discordjs/collection@1.5.3
  ├─┬ @discordjs/rest@2.2.0
  │ └── @discordjs/collection@2.0.0
  └─┬ @discordjs/ws@1.0.2
    └── @discordjs/collection@2.0.0
```

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

d0aa8d25e

**Comment by kyranet** [comment]
That is intended, Node.js v16 is EOL (End-of-Life) and therefore discouraged from further use. https://nodejs.org/en/about/previous-releases

**Comment by crycode-de** [comment]
I know that node 16 is EOL but such a breaking change should not be done in a minor or patch release as it would break any existing installation. Some users don't want to or can't update node at the moment.

If node 18 is required for discord.js (as it is currently by it's dependencies) this should be a major version increase for discord.js.

In the current situation you are saying "Node.js 16.11.0 or newer is required." but require node 18 by @discordjs/collection dependeny. This makes no sense.

**Comment by vladfrangu** [comment]
Discord.js imports collections@1.x, whereas we've released v2.0 with this requirement. Can you run `npm ls @discordjs/collection` to see where its coming from?

**Comment by didinele** [comment]
Yeah it's unfortunate but it functionally doesn't matter. I doubt there's really anything we could implement to collection to actually cause this to break.

**Comment by insaneMe31** [comment]
zlib-sync

**Comment by dendenmushy** [comment]
this just happened to me on Node 20.0.5 under latest NextJS version at SSR on `routes.ts` file:
apps/webapp dev: Module not found: Can't resolve 'zlib-sync'
apps/webapp dev: https://nextjs.org/docs/messages/module-not-found
apps/webapp dev: Import trace for requested module:
apps/webapp dev: ../../node_modules/.pnpm/discord.js@14.14.1/node_modules/discord.js/src/index.js
apps/webapp dev: ./app/(admin)/admin/api/services/route.ts

Any fix for this ? I'm stuck developing my application with this error...

**Comment by didinele** [comment]
Considering with the latest release we effectively also require node 18, this issue isn't relevant anymore.
