### ISSUE TITLE
Search freezes the page

### ISSUE THREAD

**Issue by Xaliks** [discordjs/discord.js#10029]
### Which application is this bug report for?

Documentation

### Issue description

When I try to search for "InteractionCollector" the page stops responding.

https://github.com/discordjs/discord.js/assets/64866197/2bc412a9-65d3-459d-99f2-7559d75ea9d8

### Steps to Reproduce

1. Click to "Search"
2. Start typing "InteractionCollector"

### Versions

- Windows 10 64-Bit (10.0.19045)
- Also tested on Chrome 119 & Edge 115 via [browserling.com](https://browserling.com)
- Firefox v.122.0

### Issue priority

Low (slightly annoying)

**Comment by Wuemeli** [comment]
Let me fix this
