### ISSUE TITLE
@discordjs/core is missing with_counts on guilds.get

### ISSUE THREAD

**Issue by xPolar** [discordjs/discord.js#10039]
### Which package is this bug report for?

core

### Issue description

guilds.get doesn't have support for with_counts

### Code sample

[Link To Code](https://github.com/discordjs/discord.js/blob/8ace6face82315d7e6453f49ca121663e36bcb1e/packages/core/src/api/guild.ts#L113)

### Versions

@disordjs/core master

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by JMTK** [comment]
Would there be a way to use this to get counts on all guilds at startup or is that not recommended to do?

**Comment by Jiralite** [comment]
To the best of my knowledge, there is no way to get the approximations over the WebSocket. You have to fetch them via REST.

**Comment by arturenault** [comment]
Hi, when is a package containing this fix going to be released?

Thanks

**Comment by vladfrangu** [comment]
You can install `@discordjs/core@dev` or wait for a release

**Comment by arturenault** [comment]
Thanks - just wondering if we have a timeline for the next planned release. We'd rather not depend on dev if possible 😄
