### ISSUE TITLE
Unable to place an image in the bot's image upload box using ctrl+v.

### ISSUE THREAD

**Issue by Kuju29** [discordjs/discord.js#10056]
### Which package is this bug report for?

discord.js

### Issue description

Unable to place an image in the bot's image upload box using ctrl+v. I used to use copy image and paste it into the bot using ctrl+v but currently I can't.

There is a message displayed.
[FetchBlockedDomain] Fetching blocked domain list
[FetchBlockedDomain] Server revision: 264, Client revision: 264

![bandicam-2023-12-26-09-25-14-580](https://github.com/discordjs/discord.js/assets/22098092/3b6b4a3c-63d2-411c-8091-ef770d582802)

### Code sample

```typescript
const command = new SlashCommandBuilder()
  .setName("party")
  .setDescription("Input party-event to google sheet")

command.addAttachmentOption((option) =>
    option.setName("image").setDescription("Image File").setRequired(true)
);
```

### Versions

- discord.js 14.14.1 - node js v18.12.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials, Channel, GuildMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, DirectMessages, MessageContent

### I have tested this issue on a development release

0f1e02b3d

**Comment by monbrey** [comment]
This pretty clearly is a client issue, and has nothing to do with discord.js. Please open a support ticket with Discord if you need assistance.
