### ISSUE TITLE
  Slash command attachment doesn't recognise png/jpeg images

### ISSUE THREAD

**Issue by Khajetav** [discordjs/discord.js#10051]
### Which package is this bug report for?

discord.js

### Issue description

When trying to attach an image to a slash command builder you are met with a "Not a valid value." error:
![Discord_4hLVOcmNCh](https://github.com/discordjs/discord.js/assets/141376657/a4d6c43b-62e5-4ada-9cee-69df28898cac)

Discord:
Stable 254362 (96ecb5b)
Host 1.0.9027 x86 (41465)
Windows 10 64-bit (10.0.19045)

Every dependency was updated to the latest version. Issue is most likely related to Discord itself rather than Discord.js, but still want to put some light on it.

Steps to reproduce:

1. Create a Discordjs bot with a slash command builder that takes an attachment as an option:
`.addAttachmentOption(option => option.setName('image').setDescription('The image file').setRequired(true))`

2. Call the slash command and try to paste a .png or .jpeg file into the image field.
3. Upon trying to send the message the attachment field will light up red and you will get an error saying "Not a valid value."

Tested on three different Discord clients:
Throws an error on Stable 254362 (tested on two different computers)
Works as expected on Stable 254206 (can attach the same image)

### Code sample

```typescript
.addAttachmentOption(option => option.setName('image').setDescription('The image file').setRequired(true))
```

### Versions

- Windows 10
- Discord.js 14.14.1
- Node.js 18.17.0
- Discord Stable 254362

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions

**Comment by Qjuh** [comment]
That is an issue with the discord app, not discord.js.

**Comment by eeropomell** [comment]
how do I fix this?

**Comment by monbrey** [comment]
> how do I fix this?

As per the above comment - an issue with the app, not discord.js. Please reach out to Discord via a support ticket if you need assistance.
