### ISSUE TITLE
BaseClient/Client: Add support for 'using' keyword (Explicit Resource Management)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [discordjs/discord.js#10057]
### Which application or package is this feature request for?

discord.js

### Feature

Right now, as I understand it, the documented way to close out a [`Client`](https://discord.js.org/docs/packages/discord.js/main/Client:Class) after it's done is [`destroy()`](https://discord.js.org/docs/packages/discord.js/main/Client:Class#destroy):

```ts
const client = new Client({ intents: [/* ... */] });

await client.login(/* ... */);

// ... (use the client) ...

await client.destroy();
```

One gotcha is that if the `( use the client )` bit throws, the `await client.destroy()` won't run - unless you `try`/`catch` or `try`/(`catch`/)`finally`). This is a common gotcha in async code.

[Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management) is a TC39 proposal to add explicit syntax for situations where a resource should have some method called upon disposal. It's stage 3 now and [supported in TypeScript >=5.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management).

### Ideal solution or implementation

Proposal: can the `BaseClient` class be given a `[Symbol.asyncDispose]` method that calls `this.destroy()`?

```ts
class BaseClient<Ready extends boolean = boolean> {
  // ... (existing class fields) ...

  async [Symbol.asyncDispose]() {
    await this.destroy();
  }
}
```

That way we'd be able to use clients like:

```ts
await using client = new Client({ intents: [/* ... */] });
```

...and be more assured that the `client`'s `.destroy()` will be called and awaited when done.

### Alternative solutions or implementations

For now, we can somewhat shim this in with:

```ts
class DisposableClient<Ready extends boolean = boolean> extends Client<Ready> {
	async [Symbol.asyncDispose]() {
		await this.destroy();
	}
}
```

```ts
await using client = new DisposableClient({
    intents: [GatewayIntentBits.Guilds],
});
```

### Other context

I made a small standalone package containing this suggested `DisposableClient`: https://github.com/JoshuaKGoldberg/disposable-discord-client -> https://www.npmjs.com/package/disposable-discord-client

**Comment by Renegade334** [comment]
Explicit resource management is [still at the proposal phase](https://github.com/tc39/proposal-explicit-resource-management). Adding language features that don't yet exist in the language doesn't seem like a good idea.

Typescript 5.2 has a polyfill for it, but a) this isn't a Typescript package; b) it requires very specific configuration; and c) it also requires meddling with globals (assigning properties to the Symbol constructor).
