### ISSUE TITLE
docs: Incorrect Use of await Without async Declaration

### ISSUE THREAD

**Issue by Arindam200** [discordjs/discord.js#10053]
### Which application is this bug report for?

Documentation

### Issue description

The provided code appears to use the await keyword without being within an async function. This might lead to unexpected behavior or errors.

### Expected Behavior:
Code using await should be enclosed within an async function to ensure proper execution flow.

### Actual Behavior:
The code uses await outside of an async function, which may lead to issues in certain environments.

![image](https://github.com/discordjs/discord.js/assets/109217591/9d12e84d-7c95-4f39-be6e-8784779265a5)

### Steps to Reproduce

- Go to the [Docs Website](https://discord.js.org/docs/packages/discord.js/main).
- Review the provided code snippet.
- Note the use of await outside of an async function.

### Versions

- Windows 11 (Version: 22H2)

### Issue priority

Low (slightly annoying)

**Comment by Jiralite** [comment]
You are describing CommonJS syntax. This is not CommonJS (old).

**Comment by Arindam200** [comment]
Oh! okay! Thanks for that
