### ISSUE TITLE
channel.sendTyping() should be longer than ten seconds

### ISSUE THREAD

**Issue by sahil-lalani** [discordjs/discord.js#10061]
### Which application or package is this feature request for?

discord.js

### Feature

I wish that the channel.sendTyping() would be longer than ten seconds. I'm building a bot that interacts with the OpenAI API and responses take 15-20 seconds, with which the sendTyping() indicator stops. 

### Ideal solution or implementation

Having a custom duration / removing the ten second limit for the sendTyping() indicator would be ideal.

**Comment by TAEMBO** [comment]
discord.js doesn't control how long the typing indicator lasts for. Discord has it documented at 10 seconds with no option to increase it.
