### ISSUE TITLE
Set voice status

### ISSUE THREAD

**Issue by DinacoStudio** [discordjs/discord.js#10079]
### Which application or package is this feature request for?

discord.js

### Feature

when you in voice channel you can set voice channel status

### Ideal solution or implementation

```js
function setVoiceStatus(channelId, status) {
    return new Promise(async (resolve, reject) => {
        await fetch(`https://discord.com/api/v9/channels/${channelId}/voice-status`, {
            "headers": {
                "accept": "*/*",
                "authorization": `Bot token`,
                "content-type": "application/json"
            },
            "body": JSON.stringify({ "status": status }),
            "method": "PUT"
        })
            .then(e => e.text())
            .then(e => resolve(e))
            .catch(e => reject(e))
    })
}
```

**Comment by monbrey** [comment]
This won't be implemented unless Discord documents it as part of the bot API.

**Comment by Fyphen1223** [comment]
There're features that Discord doesn't officialy document but exist such as voice receiving.
I think this feature is pretty enough to be implemented.

**Comment by monbrey** [comment]
> There're features that Discord doesn't officialy document but exist such as voice receiving. I think this feature is pretty enough to be implemented.

That has nothing to do with it. Undocumented APIs are subject to change without warning, potentially breaking discord.js functionality if we were to implement it.

**Comment by Fyphen1223** [comment]
> > There're features that Discord doesn't officialy document but exist such as voice receiving. I think this feature is pretty enough to be implemented.
> 
> That has nothing to do with it. Undocumented APIs are subject to change without warning, potentially breaking discord.js functionality if we were to implement it.

Ooof, true enough :(
But I don't think this feature will affect the entide core if we implement it, because it's just sending request to Discord API. This is not like other features such as through WS or something like permanent change, so in my opinion, this should be implemented. What do you think?

**Comment by almostSouji** [comment]
Closing for now, until upstream (discord) decides on what to do with voice and/or hang status.
