### ISSUE TITLE
My bot started but shards doesn't connect

### ISSUE THREAD

**Issue by devil54a** [discordjs/discord.js#10074]
### Which package is this bug report for?

discord.js

### Issue description

I have i bot that is being used in 5.5k server and I am trying to start it but i got a problem with shards. Here is the debug logs
![Screenshot_2024-01-06-18-22-52-018_com android chrome-edit](https://github.com/discordjs/discord.js/assets/107383610/b1f12fb9-01f6-4a3e-992e-652a74b4e7b1)
![Screenshot_2024-01-06-17-20-02-277_com android chrome-edit](https://github.com/discordjs/discord.js/assets/107383610/863c8cbe-9bfb-4d2d-a6fa-509be18c78ec)
![Screenshot_2024-01-06-17-14-07-437_com android chrome-edit](https://github.com/discordjs/discord.js/assets/107383610/cd9a8db5-c044-4c6c-9353-51c0f0a886cb)
![Screenshot_2024-01-06-17-07-53-602_com android chrome-edit](https://github.com/discordjs/discord.js/assets/107383610/d2397991-6e4a-472a-8313-4fe5d349eb1b)

### Versions

discord js 14.11
node 16

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Jiralite** [comment]
Can you update to 14.14.1 and try again?

**Comment by devil54a** [comment]
> Can you update to 14.14.1 and try again?

Didn't work :(

**Comment by devil54a** [comment]
nvm it's just back to work idk how
