### ISSUE TITLE
404 link upon opening`ThreadAutoArchiveDuration` from `TextChannel#defaultAutoArchiveDuration`

### ISSUE THREAD

**Issue by PAdventures** [discordjs/discord.js#10080]
### Issue description

1. Go to https://discord.js.org/docs/packages/discord.js/14.14.1
2. In the Serch bar type `TextChannel` and click on `TextChannel` interface
3. Scroll down to `defaultAutoArchiveDuration`
4. Click on `ThreadAutoArchiveDuration`
5. Brings to https://discord-api-types.dev/api/discord-api-types-v10/class/ThreadAutoArchiveDuration which is 404 Page not found

In the discord.js package, the `BaseGuildTextChannel` ThreadAutoArchiveDuration has a `/*unresolved*/ any` type

### Package version

discord-api-types@0.37.67

### Runtime

Node.js

### Runtime version

v21.1.0

### Priority this issue should have

Low (slightly annoying)

**Comment by jaw0r3k** [comment]
Works on the `main` version docs

**Comment by PAdventures** [comment]
I assume you mean the old discord js docs as changing to main didn't solve the issue, but going to the old docs did open the correct link

**Comment by PAdventures** [comment]
@Jiralite Just so you know this is the same issue for `SortOrderType` for the `ForumChannel` class

**Comment by PAdventures** [comment]
> @Jiralite Just so you know this is the same issue for `SortOrderType` for the `ForumChannel` class

Same issue for `VideoQualityMode` in `VoiceChannel` and `StageChannel`.
