### ISSUE TITLE
Add name_localizations on ActivitiesOptions for statuses

### ISSUE THREAD

**Issue by MaitreGEEK** [discordjs/discord.js#10106]
### Which application or package is this feature request for?

discord.js

### Feature

The goal is to display the bot's activity in the user's language like we do for the interaction commands. 

### Ideal solution or implementation

It would work the same way with adding into the [ActivitiesOption class](https://discord.js.org/docs/packages/discord.js/main/ActivitiesOptions:Interface) a property"name_localizations" where we could input different display for different languages 

For example: 
```js
{
   name: "Hello, World!",
   name_localizations: {"fr": "Bonjour, monde !"}
}
```

**Comment by Jiralite** [comment]
You should submit feature requests to Discord over at https://github.com/discord/discord-api-docs.
