### ISSUE TITLE
TextBasedChannels doesn't exist

### ISSUE THREAD

**Issue by mallusrgreatv2** [discordjs/discord.js#10119]
### Which package is this bug report for?

discord.js

### Issue description

In BaseInteraction, `channel` is typed as TextBasedChannels. This class does not exist. This causes the docs to show the not found page.
Item: `TextBasedChannels:Class`

### Versions

Not applicable

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

f401cff

**Comment by Jiralite** [comment]
I am not seeing that: https://discordjs.dev/docs/packages/discord.js/main/BaseInteraction:Class#channel

<img width="1030" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/cf86382a-bb24-472c-828f-d2d8bdd2d80d">

Can you show screenshots, what version you are seeing the documentation in, etc.

**Comment by imnaiyar** [comment]
> I am not seeing that: https://discordjs.dev/docs/packages/discord.js/main/BaseInteraction:Class#channel
> 
> <img alt="image" width="1030" src="https://private-user-images.githubusercontent.com/33201955/302272798-cf86382a-bb24-472c-828f-d2d8bdd2d80d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQwNzQsIm5iZiI6MTcwNzEzMzc3NCwicGF0aCI6Ii8zMzIwMTk1NS8zMDIyNzI3OTgtY2Y4NjM4MmEtYmIyNC00NzJjLTgyOGYtZDJkOGJkZDJkODBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1Yzg5NWFmZjM4ZmMwODY0MjU1MjJkNDk0M2M2NDhhNGEyMmFhNTY0ZmM0ZDM1NTRkMmY0ZTEyYzQwNTUyMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jHOu3HlAvp9IKHtjidpCL7JL8xPgUrAmyugljeX0IsQ">
> Can you show screenshots, what version you are seeing the documentation in, etc.?
 I discovered it on AutoComplete channel properties. Screenshot to be specific
![Uploading Screenshot (65).png…]()

**Comment by mallusrgreatv2** [comment]
https://discord.js.org/docs/packages/discord.js/14.14.1/AutocompleteInteraction:Class#channel
