### ISSUE TITLE
Embeds on CommandInteraction.editReply

### ISSUE THREAD

**Issue by Protected** [discordjs/discord.js#10111]
### Which application or package is this feature request for?

discord.js

### Feature

According to the API documentation, the [Edit Original Interaction Response](https://discord.com/developers/docs/interactions/receiving-and-responding#edit-original-interaction-response) endpoint supports the same options as the [Edit Webhook Message](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) endpoint. If that is true, that means it should currently support editing embeds in the original interaction response.

However, InteractionEditReplyOptions doesn't currently allow for embeds, only attachments (InteractionReplyOptions allows for embeds). Attempting to pass a list of embeds with the options or attempting to pass the embed directly to the method results in exceptions. 

I'm not currently working with Webhooks directly, but glancing at the documentation for discord.js it looks as though they might have the same issue?

### Ideal solution or implementation

It would be great if embed editing was added to editReply, much like it's already possible for regular Messages.

I think this should be accomplished by adding an "embeds" field to InteractionEditReplyOptions, which would function as it does in the other methods that take a list of embeds.

**Comment by Jiralite** [comment]
> However, InteractionEditReplyOptions doesn't currently allow for embeds, only attachments (InteractionReplyOptions allows for embeds). Attempting to pass a list of embeds with the options or attempting to pass the embed directly to the method results in exceptions.

Share the error, code, versions applicable, etc.

**Comment by Protected** [comment]
Sorry, I thought this was a feature request. You're right, there was a mistake in the code. This new documentation is quite difficult to parse and I didn't spot the embeds option several levels down.
