### ISSUE TITLE
Incorrect example description for ApplicationCommandPermissionsManager.has()

### ISSUE THREAD

**Issue by FieryFlames** [discordjs/discord.js#10121]
### Which application is this bug report for?

Documentation

### Issue description

The example description for [ApplicationCommandPermissionsManager.has()](https://discordjs.dev/docs/packages/discord.js/14.14.1/ApplicationCommandPermissionsManager:Class#has) is incorrect

### Steps to Reproduce

1. Visit [ApplicationCommandPermissionsManager.has()](https://discordjs.dev/docs/packages/discord.js/14.14.1/ApplicationCommandPermissionsManager:Class#has)
2. Look at the example code's description vs the documentation's description
3. Look at the actual code and notice that the example description is wrong while the documentation description is right

### Versions

- Safari 17.3 (19617.2.4.11.8)
- macOS 14.3

### Issue priority

Low (slightly annoying)

**Comment by Jiralite** [comment]
Can you show what you are seeing?

**Comment by FieryFlames** [comment]
<img width="794" alt="Screenshot 2024-02-08 at 9 18 11 PM" src="https://github.com/discordjs/discord.js/assets/30497388/73e999f3-b0ca-4cc5-9891-d55b8dc58560">

**Comment by Jiralite** [comment]
You are seeing what I see, but you said the source code is different. They are the same:

<img width="1452" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/5c344fbd-ce16-457d-937b-fb4478f7979e">

Perhaps you misread?

**Comment by FieryFlames** [comment]
The example is incorrect in saying that it checks if a user has permission to use a command, the function only checks if an override exists (and those can be true or false). It should be updated to be more like the description.
