### ISSUE TITLE
Uncidi causes 4 low severity vulnerabilites

### ISSUE THREAD

**Issue by Dustaboy3** [discordjs/discord.js#10132]
### Which package is this bug report for?

discord.js

### Issue description

Which package is this bug report for?
discord.js

Issue description
steps to reproduce:
npm i discord.js
npm audit

this will give you:

# npm audit report

undici  <=5.28.2
Undici proxy-authorization header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-3787-6prv-h9w3
fix available via `npm audit fix --force`
Will install discord.js@14.12.1, which is a breaking change
node_modules/undici
  @discordjs/rest  2.0.1-dev.1690848847-1af7e5a0b.0 - 2.3.0-dev.1707178154-3755e66d4
  Depends on vulnerable versions of undici
  node_modules/@discordjs/rest
    @discordjs/ws  >=1.0.1-dev.1690848792-1af7e5a0b.0
    Depends on vulnerable versions of @discordjs/rest
    node_modules/@discordjs/ws
    discord.js  14.0.0-dev.1640779371.9cdc448 - 14.0.0-dev.1657757514-fe34f48 || 14.12.2-dev.1690891477-7295a3a94.0 - 14.15.0-dev.1707869366-543d61737
    Depends on vulnerable versions of @discordjs/rest
    Depends on vulnerable versions of @discordjs/ws
    Depends on vulnerable versions of undici
    node_modules/discord.js

4 low severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
  
 # Conclusion

undici needs to be bumped to 6.6.2

### Versions

- discord.js: 14.14.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/blob/543d61737e0709b9d88029d01156d48cfcaf3bcc/packages/discord.js/package.json#L79

**Comment by techy2493** [comment]
If this is fixed why was it closed as not planned and tagged as invalid instead of being marked as something resolved in an upcoming release @Jiralite which would let others know it was resolved?

**Comment by Syjalo** [comment]
It's closed as not planned, because there's nothing to fix. It's invalid, because it reports a bug that doesn't exist.
![image](https://github.com/discordjs/discord.js/assets/62868468/4817f1c7-4363-4383-a6ca-272f2c5b4d63)

**Comment by JstnMcBrd** [comment]
I am also receiving this dependabot alert. I eagerly await the next release with this bug fix.

Is it possible to release an expedited patch (`14.14.2`) that fixes this problem quickly? Or is bumping `undici`'s version a breaking change that requires a minor/major release?

**Comment by monbrey** [comment]
There's no need to expedite a patch for this. You can safely ignore it. We are not making cross-origin requests.

**Comment by YasharF** [comment]
Per https://github.com/advisories/GHSA-3787-6prv-h9w3 it is patched in undici v6.6.1
@discordjs/rest has picked up the patch in https://github.com/discordjs/discord.js/commit/ae57d7facbb3b21b5fb57000c56f2f43684828bd
