### ISSUE TITLE
feat(addEventOption) SlashCommandBuilder

### ISSUE THREAD

**Issue by Unfaehig** [discordjs/discord.js#10142]
### Which application or package is this feature request for?

builders

### Feature

**SlashCommandBuilder**
I like to have the same functionality like the `addUserOption `/ `addRoleOption` function for Events (GuildScheduledEvents) also, to simply add it as a dynamic input of a / command option list. 
Current i only see the solution to use auto complete for an input. However this results in a bad user experience due to 3 sec respond limit and i don't want the user to autocomplete and sent multiple requests back. It would be enough to populate the list once you start the / command.

### Ideal solution or implementation

add a similar function like `addUserOption` named like `addEventOption`

### Alternative solutions or implementations

Like mentioned above i have a workaround with autocomplete using the GuildScheduledEventManager and fetch all events with it. Performance is not great and i don't need to repopulate it each time a user inputs a char.

**Comment by monbrey** [comment]
We can only implement features that the Discord API provides.

Feature requests need to be provided to Discord on their repository: https://github.com/discord/discord-api-docs/discussions
