### ISSUE TITLE
Security Issue with dependent package undici

### ISSUE THREAD

**Issue by techy2493** [discordjs/discord.js#10140]
### Which package is this bug report for?

discord.js

### Issue description

I cannot upgrade to 14.14.1 because of an upstream dependency of the latest version adding security vulnerability.

![image](https://github.com/discordjs/discord.js/assets/2701534/3e713f4c-8554-4e73-bc83-172de88a0c4b)

For more info see Github's Dependabot's PR to my repo bumping discord.js to latest. This is the only change in this repo which means this dependency is coming from discord.js somewhere between my current version 14.7.1 and 14.14.1

https://github.com/techy2493/ts-disc-control/pull/35

### Versions

discord.js 14.14.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by toast-ts** [comment]
There's nothing that Discord.js can do at the moment, other than you dismissing the alert.
Also, it was already brought up in another issue:
https://github.com/discordjs/discord.js/issues/10132#issuecomment-1949515813
