### ISSUE TITLE
Discord REST API rejecting valid command "name" properties.

### ISSUE THREAD

**Issue by SedWilliams** [discordjs/discord.js#10158]
### Which package is this bug report for?

discord.js

### Recreate error
* Create a snippet which hits the Discordjs REST API endpoint. Using the ```put()``` method from the REST library pass a request where argument one is ```Routes.applicationCommands(*insert_client_id)```, and argument two is  ```{ body: commands }```.
* The commands I pass are in the form of a Typescript array, which contains two indexes each holding an object with a custom type ```Command```. The custom type Command is an interface with two properties (```name``` and ```description```).
* Set one object's ```name``` property to 'quote' and the Discord REST API will reject the data returning a 400 status code and the error which is copy pasted below.
* Error resolved and commands successfully received by Discord REST API when name property was changed to "q".

__Summary__: The Discord REST API will reject a command with the property "name": "quote" despite quote following the necessary ```name``` property format specified on [Discord Developer Portal](https://discord.com/developers/docs/interactions/application-commands).

Code snippets of what caused the error inlcuded below.

### Code sample

```typescript
//Discord REST API connection

//include necessary imports
dotenv.config({ path: path.join(process.cwd(), '../.env') });

//This class is instantiated in a seperate class, where the updateCommands method is then called
//and passed my commands data
export class DiscordInterface {
    private token: string;
    private clientId: string;

    constructor() {
        this.token = process.env.DISCORD_TOKEN || '';
        this.clientId = process.env.APPLICATIONID || '';
    }

    //called from outside and passed array of custom type, which is holding two objects each
    //with name and description properties
    public async updateCommands(commands: Command[]) {
        const rest = new REST({ version: '9' }).setToken(this.token);

        try {
            await rest.put(
                Routes.applicationCommands(this.clientId),
                { body: commands },
            );

            console.log('Successfully updated commands.');
        } catch (error) {
            console.error('Error updating commands:', error);
        }
    }
}


//Command Data with custom type definition

//imports my custom interface
import { Command } from "../types/Command";


export const CommandsData: Command[] = [
    {
        name: "quote",
        description: "Auto quote formatter for the quotebook"
    },
    {
        name: "dissLogan",
        description: "Diss logan"
    }
]

//THE ERROR INFORMATION
[
  {
    name: 'quote',
    description: 'Auto quote formatter for the quotebook'
  },
  { name: 'dissLogan', description: 'Diss that mf logan' }
]
Error updating commands: DiscordAPIError[50035]: Invalid Form Body
1.name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid
    at handleErrors (D:\dev\js\brianbot\node_modules\@discordjs\rest\src\lib\handlers\Shared.ts:148:10)
    at SequentialHandler.runRequest (D:\dev\js\brianbot\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:410:20)
    at SequentialHandler.queueRequest (D:\dev\js\brianbot\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:168:11)
    at _REST.request (D:\dev\js\brianbot\node_modules\@discordjs\rest\src\lib\REST.ts:211:20)
    at DiscordInterface.updateCommands (d:\dev\js\brianbot\src\SyncAPI\DiscordInterface.ts:23:13) {
  requestBody: { files: undefined, json: [ [Object], [Object] ] },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { '1': [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications/1000167765916786908/commands'
}
```

### Versions

* typescript version 5.3.3
* discord.js verision 14.14.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
The error isn't coming from "quote". It's coming from "dissLogan". No capitals.

**Comment by SedWilliams** [comment]
Got it, user error lol. Thank you for the information.
