### ISSUE TITLE
hasThread property not showed in message and false instead of true

### ISSUE THREAD

**Issue by FreePhoenix888** [discordjs/discord.js#10157]
### Which package is this bug report for?

discord.js

### Issue description

I see [`hasThread` property](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#hasThread) in the message class but for some reasons when handling new messages I do not see such message:
```
{
  message: <ref *1> Message {
    channelId: '1212444477348909096',
    guildId: '739430470345031692',
    id: '1212469139239608340',
    createdTimestamp: 1709145569382,
    type: 0,
    system: false,
    content: '<@1132372313820626944> hi',
    author: User {
      id: '298466999426613268',
      bot: false,
      system: false,
      flags: [UserFlagsBitField],
      username: 'freephoenix888',
      globalName: 'FreePhoenix888',
      discriminator: '0',
      avatar: 'e576f33ac4d16b13d7b0d89201542ae4',
      banner: undefined,
      accentColor: undefined,
      avatarDecoration: null
    },
    pinned: false,
    tts: false,
    nonce: '1212469138149081088',
    embeds: [],
    components: [],
    attachments: Collection(0) [Map] {},
    stickers: Collection(0) [Map] {},
    position: 8,
    roleSubscriptionData: null,
    resolved: null,
    editedTimestamp: null,
    reactions: ReactionManager { message: [Circular *1] },
    mentions: MessageMentions {
      everyone: false,
      users: [Collection [Map]],
      roles: Collection(0) [Map] {},
      _members: null,
      _channels: null,
      _parsedUsers: null,
      crosspostedChannels: Collection(0) [Map] {},
      repliedUser: null
    },
    webhookId: null,
    groupActivityApplication: null,
    applicationId: null,
    activity: null,
    flags: MessageFlagsBitField { bitfield: 0 },
    reference: null,
    interaction: null
  }
}
```

But if I console.log that property I see false value instead of true (I write my message in the thread)
```
console.log('message.hasThread', message.hasThread)
```
```
message.hasThread false
```

### Code sample

```typescript
I am going to add this later, I do not have time right now therefore my pr is draft
```

### Versions

discord.js@14.14.1
Node v18.19.1
Typescript not installed
OS: Ubuntu 22.04

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by FreePhoenix888** [comment]
Sorry I was unable to make my pr draft

**Comment by Jiralite** [comment]
Why would a _new_ message immediately have a thread?

**Comment by monbrey** [comment]
I'm pretty sure this property checks if the message is the starter message for a thread, not just if it's a reply to one.

**Comment by FreePhoenix888** [comment]
> Why would a _new_ message immediately have a thread?

Why would not? I have created a thread and write my messages there, why should not they have a thread?

**Comment by FreePhoenix888** [comment]
> I'm pretty sure this property checks if the message is the starter message for a thread, not just if it's a reply to one.

No, check [thread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#thread)'s documentation: `The thread started by this message This property is not suitable for checking whether a message has a thread, use [hasThread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#hasThread) instead.`

**Comment by Jiralite** [comment]
> Why would not? I have created a thread and write my messages there, why should not they have a thread?

A created message sent over the gateway will not have a thread created from it. Those happen afterwards.

> I have created a thread and write my messages there

Those messages don't have a thread. They are _in_ a thread. If you want to check if a message is sent within a thread, check the channel type it's sent in.

> No, check [thread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#thread)'s documentation: `The thread started by this message This property is not suitable for checking whether a message has a thread, use [hasThread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#hasThread) instead.`

This reply makes it clear that this is a misunderstanding of what you are reading. Dumbing it down:

- `Message#hasThread` checks if the message has a thread, as in, there is a thread created off the message.
- `Message#thread` is the thread created off the message.

**Comment by FreePhoenix888** [comment]
> > Why would not? I have created a thread and write my messages there, why should not they have a thread?
> 
> A created message sent over the gateway will not have a thread created from it. Those happen afterwards.
> 
> > I have created a thread and write my messages there
> 
> Those messages don't have a thread. They are _in_ a thread. If you want to check if a message is sent within a thread, check the channel type it's sent in.
> 
> > No, check [thread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#thread)'s documentation: `The thread started by this message This property is not suitable for checking whether a message has a thread, use [hasThread](https://discord.js.org/docs/packages/discord.js/14.14.1/Message:Class#hasThread) instead.`
> 
> This reply makes it clear that this is a misunderstanding of what you are reading. Dumbing it down:
> 
> * `Message#hasThread` checks if the message has a thread, as in, there is a thread created off the message.
> * `Message#thread` is the thread created off the message.

Now I get you, thank you! I would be glad if we make it more clear about `hasThread` in its description

**Comment by Jiralite** [comment]
> Now I get you, thank you! I would be glad if we make it more clear about hasThread in its description.

Sure, we can welcome improvements and clarity. That would be a pull request we would be interested in.
