### ISSUE TITLE
SequentialHandler.queueRequest does not resolve the promise when the request fails

### ISSUE THREAD

**Issue by AzariasB** [discordjs/discord.js#10150]
### Which package is this bug report for?

rest

### Issue description

1. Create a request that could return a DiscordAPIError response (ex: fetch a channel that does not exist)
2. await for queueRequest to return a value

In the [SequentialHandler](https://github.com/discordjs/discord.js/blob/efa3cac6f223d8781b1ebab857f1da6a25c3e6b4/packages/rest/src/lib/handlers/SequentialHandler.ts#L169), seems to be hanging when returning the error.

### Code sample

```typescript
const client = new Client();

await client.login('token');

const shouldCrashOrReturnNull = await client.channels.fetch('000000000000000000');
```

### Versions

- @discordjs/rest 2.2.0
- discord.js: 14.14.1
- node: 20

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Qjuh** [comment]
I can’t reproduce that with your code. It rejects as it should. Are you sure the login call resolves and that you‘re not rateLimited and the rest call simply queues the request to be sent when the ratelimit passes?

**Comment by AzariasB** [comment]
Sorry, I wasn't looking correctly, indeed it rejects as it should
