### ISSUE TITLE
Unknown interaction (10062) when using a modal after canceling the same modal within the awaitModalSubmit time

### ISSUE THREAD

**Issue by TimGeerts** [discordjs/discord.js#10165]
### Which package is this bug report for?

discord.js

### Issue description

When using a slash command to open a modal, and then using the `awaitModalSubmit` function (with a time set to for instance 10 seconds).
If you're opening the modal, clicking cancel (or closing it), then executing the command again within the time set (in this case, those 10 seconds), if you then submit that new modal, the bot will crash with an "Unknown interaction" error.

### Code sample

```typescript
//in the slash command interaction runner
...
await interaction.showModal(modalObj);
await interaction.awaitModalSubmit({
 filter: someFilter,
 time: 10_000
}).then((modalInteraction) => {
  //do modal submit logic
  ...
  modalInteraction.reply({
    content: 'test',
    ephemeral: true
  });
});
```

### Versions

- "discord.js": "^14.14.1",
- node version 20.11.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/issues/8614#issuecomment-1242989856

**Comment by TimGeerts** [comment]
> [#8614 (comment)](https://github.com/discordjs/discord.js/issues/8614#issuecomment-1242989856)

yup, went for a walk with the dog and then it hit me, I was using the interaction.user.id as part of the modal custom id. But obviously that's not "unique" anymore if the same user opens different ones.

My bad.
(would still be nice to have a close/cancel event as well, but, that's not what this issue is about so feel free to close this)
