### ISSUE TITLE
Add a formatter for "Hide hyperlink embed" markdown sequence

### ISSUE THREAD

**Issue by barrientosvctor** [discordjs/discord.js#10161]
### Which application or package is this feature request for?

formatters

### Feature

I've seen that it's possible to send hyperlinks without embeds within the Discord app, so I'd like there to be a formatter in discord.js for this.

### Ideal solution or implementation

Add formatter functions for the different ways to add a hyperlink without embed. These would be:

- Hyperlink without embed without tooltip: `[Content](<URL>)`
- Hyperlink without embed with tooltip: `[Content](<URL> "Title")`

### Other context

This is a preview of the different ways of hyperlink without embed:

- Hyperlink without embed with no tooltip
![no_tooltip](https://github.com/discordjs/discord.js/assets/113469901/f2aa7125-c4ab-4b7f-a240-2c64302c9c86)

- Hyperlink without embed with tooltip
![with_tooltip](https://github.com/discordjs/discord.js/assets/113469901/98d1b0b7-156a-40d6-a002-c1fcd6e74022)

**Comment by almeidx** [comment]
This already exists. [hyperlink()](<https://discord.js.org/docs/packages/formatters/0.3.3/hyperlink:Function>)

**Comment by barrientosvctor** [comment]
> This already exists. [hyperlink()](https://discord.js.org/docs/packages/formatters/0.3.3/hyperlink:Function)

The problem is that this function allows you to hide them but you would have to explicitly write <> around the URL and it can be a bit tedious to have to write it every time to hide the URL embeds, in case you want them that way.

That's why I was thinking about this implementation.

**Comment by Jiralite** [comment]
Then this is [`hideLinkEmbed`](https://discord.js.org/docs/packages/formatters/0.3.3/hideLinkEmbed:Function)?

**Comment by barrientosvctor** [comment]
> Then this is [`hideLinkEmbed`](https://discord.js.org/docs/packages/formatters/0.3.3/hideLinkEmbed:Function)?

Oh, I didn't realize this feature already existed. My bad!
