### ISSUE TITLE
New Documentation (often) seems to have incorrect default data

### ISSUE THREAD

**Issue by LegendaryEmoji** [discordjs/discord.js#10162]
### Which application is this bug report for?

Documentation

### Issue description

In general, a common issue with the documentation is the fact that it's not up-to-date, or the default values are incorrect. The documentation states that the default value of the `x` property is `true`, while the source code indicates otherwise. However, in the latest documentation update, many default values that were previously correct are now incorrect (weirdly, the descriptions are still the same). Overall, there are significantly more errors in the latest version compared to the previous version.
![image](https://github.com/discordjs/discord.js/assets/60050010/3590b357-b441-4501-b406-bef3e52ab6ac)

### Steps to Reproduce

1. Visit [CommandInteractionOptionResolver:Class#getFocused](https://discord.js.org/docs/packages/discord.js/14.14.1/CommandInteractionOptionResolver:Class#getFocused)
- Documentation is showing `getFull` parameter is, by default, set to `true`.
- In [source code](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/CommandInteractionOptionResolver.js#L301), `getFull` is, by default, set to `false`.
2. Visit [ChatInputCommandInteraction:class#reply](https://discord.js.org/docs/packages/discord.js/14.14.1/ChatInputCommandInteraction:Class#reply)
- Documentation is showing `fetchReply` property is, by default, set to `true`.
- In [source code](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/interfaces/InteractionResponses.js#L101), `fetchReply` is, by default, set to either `false` or never set (`undefined`).

### Versions

- Brave Browser [Version 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)]
- [v14.14.1](https://discord.js.org/docs/packages/discord.js/14.14.1) of Documentation Website, Discord.js package

### Issue priority

Medium (should be fixed soon)

**Comment by Jiralite** [comment]
These are overloads.

Overloads are implementations of a method that will return something different, depending on the input. For [`CommandInteractionOptionResolver#getFocused()`](https://discord.js.org/docs/packages/discord.js/14.14.1/CommandInteractionOptionResolver:Class#getFocused), it states on the first overload that you will get [`AutocompleteFocusedOption`](https://discord.js.org/docs/packages/discord.js/14.14.1/AutocompleteFocusedOption:TypeAlias) with `getFull` set to `true`, and a `string` otherwise.

These are not wrong. If anything, they are more correct and accurate than before.

**Comment by LegendaryEmoji** [comment]
I am not sure what you're getting into. I was not talking about Overloads, but default values of parameters found in the Documentation.

For [`CommandInteractionOptionResolver#getFocused()`](https://discord.js.org/docs/packages/discord.js/14.14.1/CommandInteractionOptionResolver:Class#getFocused) (in Overload 1), `getFull: true` indicates that the `getFull` parameter's default value is `true`.
![image](https://github.com/discordjs/discord.js/assets/60050010/2614150e-751d-4ce4-8e67-84c4865e9f56)

Going into the [source code](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/CommandInteractionOptionResolver.js#L301), we can see that `getFull` is NOT set to `true`.
![image](https://github.com/discordjs/discord.js/assets/60050010/541055d6-309a-4b93-8497-9a11eb2d8097)

**Comment by Jiralite** [comment]
> I was not talking about Overloads, but default values of parameters found in the Documentation.

That is not a default value. That is an overload. The misunderstanding here is not knowing how to read code signatures.

You can try to understand it from your screenshot. From line 304, if `getFull` is `true`, then it returns a focused option:

<img width="571" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/48e47d55-d1c5-401a-96cd-dee7a6dd5cac">

If `getFull` is not `true`, it returns `focusedOption.value`, which is a `string`:

<img width="532" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/87a026dd-9e38-4f16-9dfd-696ba3a27698">

The `?` here indicates no parameter passed, in which case, the source code defaults that parameter to `false`.

Ultimately, there is no flaw in the logic of the documentation here.

**Comment by LegendaryEmoji** [comment]
Thanks for the clarification, I understand now.

This is such a weird way of documentation. Previous versions used normal values to indicate default values while this version suddenly changed it (without clear announcement). In my opinion, the order of Overloads and **Returns** should be changed to align with each other to avoid confusion. I am sure there are better ways to do this, but that's not up to me to decide.
