### ISSUE TITLE
discord.js bot reacts several times on the action. sends multiple messages to the server.

### ISSUE THREAD

**Issue by Crushtests** [discordjs/discord.js#10172]
### Which package is this bug report for?

discord.js

### Issue description

So my code, everytime the thread created in a specific forum, it adds the tag.

Problem is that when you create a post on a forum, it sends to you like 4 messages with same context.

It also applies to voiceStateUpdate - I've put notification if someone joins or leaves voice channel, I received message four times per each action (now three, as I've turned this notification off).

On the image you can see those changes.

I've already numerous times updated the bot's token, removed and added back the js file to pm2. Even restarted the server - it worked for short period of time.

When I edit the code, for example, I write "Tagus" instead of "Tags to messageText variable, it sends three messages with "Tags" and one with updated "Tagus". So I assume that it somewhere caches the file code and runs it in the background. But where and how - idk. I don't run the script file elsewhere, I've seen some problem similar problem, but nothing helped me.

I can add if (message.author.bot) {  return; }, but it won't help with those duplicates, and I've added script that bot creates those posts itself, so I need those tags to be added to all posts on that forum.

I even renamed the js file. reuploaded to server, deleted old one, and result is the same...

And it's not the multiple actions that were sent by discord to my server - I've removed script from pm2, added console.log command and run script using node command - in this case I received 4 messages in discord and only one message in the console. So, either I can't find the issue, or it might be the library issue itself, like [people had here](https://github.com/discordjs/discord.js/issues/2655).

Token was also been reset several times, bot been removed and added back to the server, server was restarted, server even was changed.
![Untitled-1](https://github.com/discordjs/discord.js/assets/20880689/fe89e45b-3853-42f1-b517-bd4a2180b1b6)

### Code sample

```typescript
client.on('threadCreate', (thread) => { 
    if (thread.parentId == global.disrequestforum) {
        const tags = thread.appliedTags.map(tagId => {
            const tag = thread.parent.availableTags.find(t => t.id === tagId);
            return tag ? tag.name : "Unknown";
        });
        let messageText = "Tags:";
        if (tags.includes("Accounting")) {
            messageText = messageText + ' <@' + userid + '>';
        }
        thread.send(messageText);
    }
});
```

### Versions

discord - 14.12.1
node - 21

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages

**Comment by Qjuh** [comment]
This definitely sounds like an issue of your code/server, seeing how a change of code only affects one of the many outputs it‘s definitely old code still running somewhere. Join the discord to get help with that, as it’s not an issue with the library.

**Comment by Crushtests** [comment]
> This definitely sounds like an issue of your code/server, seeing how a change of code only affects one of the many outputs it‘s definitely old code still running somewhere. Join the discord to get help with that, as it’s not an issue with the library.

yes, but with time the update synchronizes and all messages comes with those changes.
again: I've restarted server, changed it, renamed file, updated it. it worked for short period of time - after that - four instances were sent.

**Comment by almostSouji** [comment]
we will re-open this issue, if you can provide a minimal reproducible example (minimal code to reproduce the issue, complete meaning we can plug in a token/variables as you describe and reproduce the issue)

without that, we have currently no reason to believe this is a bug with the library

**Comment by Crushtests** [comment]
> we will re-open this issue, if you can provide a minimal reproducible example[1](#user-content-fn-1-645effad2b95a88a9cadf2f8cc8caf0c) (minimal code to reproduce the issue, complete meaning we can plug in a token/variables as you describe and reproduce the issue)
> 
> without that, we have currently no reason to believe this is a bug with the library
> 
> ## Footnotes
> 1. https://en.wikipedia.org/wiki/Minimal_reproducible_example [↩](#user-content-fnref-1-645effad2b95a88a9cadf2f8cc8caf0c)

I've provided the code when bot reacts on thread creation - this is a full function, except that I have several different tags and I'm adding several tags to the chat if there are several tags on a forum pos. Only difference that instead of `userid` I'm putting the value from object variable.

Again, I'm not accusing the library itself, but... all actions were made trying to determine why it happens... token change, sever change and restart, file rename, bot removed and returned to the server...

**Comment by Crushtests** [comment]
Found an issue - there was a duplication because of process.env file - wheer I also stored the bot token, and because of that function worked twice (I exported function to another file).
