### ISSUE TITLE
collection.sorted is not a function

### ISSUE THREAD

**Issue by Xaliks** [discordjs/discord.js#10187]
### Which package is this bug report for?

discord.js

### Issue description

When I try to set the position of the channel I get an error.
![image](https://github.com/discordjs/discord.js/assets/64866197/b433471f-e912-4503-807f-4526c1867982)

You also need to fix the example
![image](https://github.com/discordjs/discord.js/assets/64866197/b9641fc8-699a-4281-88ed-6da72fd48ed3)

### Versions

- discord.js v14.15.0-dev.1710979853-6cc5fa28e
- discordjs/collection v2.1.0-dev.1710979853-6cc5fa28e
- Node v20.11.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

6cc5fa28e

**Comment by Jiralite** [comment]
Not convinced this is a bug.

You're using the next major version for the discord.js library, but it only (currently) supports 1.x.

**Comment by monbrey** [comment]
Not a bug - the only error here is the example. The method is called "toSorted" as you yourself underlined. We need to update it's example.
