### ISSUE TITLE
Client not responding to deferred replies // await never working on deferring a reply.

### ISSUE THREAD

**Issue by Axodouble** [discordjs/discord.js#10192]
### Which package is this bug report for?

discord.js

### Issue description

Reproducing this bug has been a nightmare.

The issue simply appears as such:
After deferring a reply- be it ephemeral or not, the client does not update the message with the `.editReply(...)` functionality.

This appears cross platform, and appears to also happen on all devices here even for bots I have not modified where it worked prior without issue, however awaiting the interaction edit reply often takes upwards of 15 minutes if not longer.

Speedtest in-case network issues or questions about bandwidth get included:
![image](https://github.com/discordjs/discord.js/assets/53979495/3dcb45a3-86fb-42ff-bab5-78871c982dc7)

I also have a docker container where you can test a local copy of my bot without any issue.
[dockerfile](https://github.com/Axodouble/xdbl-bot)

### Code sample

```typescript
/**
 * @param {import("discord.js").ChatInputCommandInteraction} interaction
 * @param {import("discord.js").Client} client
 */
async executeSlash(interaction, client) {
  await interaction.deferReply({ ephemeral: true });
  let response = await execute(client);
  interaction.editReply(response);
},

async function execute(client) {
  return {content: "Test Example"};
}
```

### Versions

- discord.js - ^14.14.1
- nodejs - v18.14.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Axodouble** [comment]
Forgot to note prior, immediately responding to the message is possible, however obviously less than specifically optimal.

**Comment by Qjuh** [comment]
Judging by the snippet you showed here it appears that your execute function might be the one not resolving and not the editReply after (since you don’t even await that).
If you still believe this to be a bug with djs provide an actual minimal reproducible code sample (especially what command to run to cause it).

**Comment by Axodouble** [comment]
After quite a bit of debugging I have come to the realization that it is not a bug with DiscordJS and a bug with Discord itself, it is currently being fixed on their end.
