### ISSUE TITLE
[BUG] Automod events not working

### ISSUE THREAD

**Issue by craciu25yt** [discordjs/discord.js#10197]
### Which package is this bug report for?

discord.js

### Issue description

When I add an event handler for autoModerationRuleUpdate, autoModerationActionExecution or autoModerationRuleUpdate (I didn't tried autoModerationRuleDelete) it just doesn't work. I trigger the Automod and it isn't executed but the audit log listener does

### Code sample

```typescript
client.on("autoModerationRuleUpdate", (automodRule) => {
    console.log(automodRule)
})
```

### Versions

Discordjs: 14.14.1
nodejs: 20.9.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildPresences, GuildMessages, DirectMessages, MessageContent

**Comment by almeidx** [comment]
You didn't specify the required intents for the automod events to be received.

`GatewayIntentBits.AutoModerationConfiguration` is required for `autoModerationRuleCreate`, `autoModerationRuleUpdate`, and `autoModerationRuleDelete`.
`GatewayIntentBits.AutoModerationExecution` is required for `autoModerationActionExecution`.

**Comment by craciu25yt** [comment]
oh, I didn't know there was some specific intents for that. It is not documented
Anyways, thanks you
