### ISSUE TITLE
PermissionOverwrites#toJSON typing incorrect

### ISSUE THREAD

**Issue by BigBrainAFK** [discordjs/discord.js#10194]
### Which package is this bug report for?

discord.js

### Issue description

The typing of the `toJSON` function for `PermissionOverwrites` instances is typed incorrectly.

As far as I can see according to [the relevant code](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/PermissionOverwrites.js#L88-L95) it should just be typed to return a JSON object.

### Code sample

```typescript
...
JSON.stringify(overwrites.toJSON())
...
```

### Versions

- discord.js 14.14.1
- NodeJS 18.19.0
- Typescript 4.9.5
- macOS 14.3.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/blob/a1a3a95c94194a8ab789d567a778b376e13ea973/packages/discord.js/typings/index.d.ts#L2553

I would not say this is incorrect. Regardless, this is a duplicate of #9432–make sure to search for existing issues!
