### ISSUE TITLE
RoleCreateOptions#position doesn't always work

### ISSUE THREAD

**Issue by phil-flip** [discordjs/discord.js#10199]
### Which package is this bug report for?

discord.js

### Issue description

1. Write a function with `guild.roles.create()`and add the position option
2. Make sure bot has correct permissions and is above position index
3. Loop it through multiple roles.
4. Sometimes sets the correct position, but also reverse index

Workaround is to add a delay, but it shouldn't be random and unfortunately doesn't help all the time. Seems like a race condition.
Discord index is also the other way around. (Top to bottom) Discord.JS does it the other way around.

### Code sample

```typescript
// get correct guild
const targetGuild = await client.guilds.fetch(config.onlyrun);
// get list
const roles = config.aprilFools.roles.addList;
// foreach all entries
roles.forEach(async (roleData) => {
  // add role
  const createdRole = await targetGuild.roles.create({
    name: roleData[0],
    color: randomHexColorCode(),
    position: 47,
  });
  // update position. create function can't do it
  // FIXME: Workaround for position. Use setPositions
  // write role id in console
  console.log([roleData[0], roleData[1], roleData[2], createdRole.id]);
});
```

### Versions

```
npm -v; node -v; grep discord.js package.json
9.6.7
v18.5.0
    "discord.js": "^14.14.1",
```

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by NotSugden** [comment]
your problem is not with discord.js. the foreach function doesnt wait for the previous execution.

Use a for (... of ...) loop

**Comment by phil-flip** [comment]
> your problem is not with discord.js. the foreach function doesnt wait for the previous execution.
> 
> Use a for (... of ...) loop

But... it doesn't have to wait for the previous one. It is all one command: Creating the role and setting it to the right position. But when it runs through the loop. It only creates them, but doesn't put them to the right spot.
Sorry for the late reply @NotSugden
