### ISSUE TITLE
User#avatarDecoration property is always null.

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#10203]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://github.com/discordjs/discord.js/assets/11788894/7b111d11-05ed-4af6-a7b5-218137c870b7)
As you can see my profile has that clown decoration. But User#avatarDecoration is showing `null`. 
https://github.com/discordjs/discord.js/blob/ba6476d07e3325dea573f16b8b957244b69bb05c/packages/discord.js/src/structures/User.js#L131
Looking at the raw data from the gateway. There is no "avatar_decoration" property. Only a "avatar_decoration_data" property. Which is an object of "sku_id" and "asset" properties.

### Versions

v14.14.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

**Comment by BannerBomb** [comment]
Edited the title, as I found another issue about the "banner" being null, but found it isn't null when using `client.users.cache.get('ID').fetch()`

**Comment by monbrey** [comment]
The `avatar_decoration_data` issue may be a valid bug - thank you for reporting.

The banner being null is expected - Discord does not include this data in the user object send with events, and it must be explicitly fetched to retrieve it. This is documented.

![image](https://github.com/discordjs/discord.js/assets/5294381/abd73ea3-cd38-4859-82cd-f15e8fcb8c9d)

**Comment by BannerBomb** [comment]
> The `avatar_decoration_data` issue may be a valid bug - thank you for reporting.
> 
> The banner being null is expected - Discord does not include this data in the user object send with events, and it must be explicitly fetched to retrieve it. This is documented.
> 
> ![image](https://private-user-images.githubusercontent.com/5294381/318599038-abd73ea3-cd38-4859-82cd-f15e8fcb8c9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTgyMDAsIm5iZiI6MTcxMjAxNzkwMCwicGF0aCI6Ii81Mjk0MzgxLzMxODU5OTAzOC1hYmQ3M2VhMy1jZDM4LTQ4NTktODJjZC1mMTVlOGZjYjhjOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDAzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQyNzg1ZDA5MGY2NzEyOTZkYTRjY2RlOTViZDk5NGQ1YzQwMGNmNTAzY2IzMDQ0NmUyN2I3NWE3MjI2ZDU4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bLydoj8gzOj-INAiEoA4S2kk1vVTwKmVtUAqD65BEh4)

yeah, I realized the banner one needed to be force fetched after making the pr. Which is why I removed it from the post.
I could make a pr for fixing the avatarDecoration. But I don't know how y'all would want to handle the object that is provided by the API.

**Comment by Jiralite** [comment]
> The `avatar_decoration_data` issue may be a valid bug - thank you for reporting.

Unfortunately not: Discord renamed the property from `avatar_decoration` to `avatar_decoration_data` (https://github.com/discord/discord-api-docs/pull/6464). Therefore, it being always `null` is correct behaviour.

Since Discord has not merged the change of documentation, there is nothing (yet) to do.

> I could make a pr for fixing the avatarDecoration. But I don't know how y'all would want to handle the object that is provided by the API.

#9888 exists as a draft for when Discord is ready to document the change, but as said above, there's nothing that can be done otherwise.
