### ISSUE TITLE
Scheduled Events missing "location" for entityType: external

### ISSUE THREAD

**Issue by IDootix** [discordjs/discord.js#10204]
### Which package is this bug report for?

discord.js

### Issue description

Try to create an Scheduled Discord Event with an entity type of external dont set a channel because it's external and get invalid from error from the discord api

ERROR: An unhandled promise rejection occurred.
    shardId: 0
    message: "Invalid Form Body\nentity_metadata.location[BASE_TYPE_REQUIRED]: This field is required"
    code: 50035
    statusCode: 400
    method: "POST"
    url: "https://discord.com/api/v10/guilds/1223361272998002758/scheduled-events"
    stack: "DiscordAPIError[50035]: Invalid Form Body\nentity_metadata.location[BASE_TYPE_REQUIRED]: This field is required

### Code sample

```typescript
public async execute(intr: ChatInputCommandInteraction): Promise<void> {
        //create an example Date
        let date = new Date();
        date.setFullYear(2022);

        //create an event
        intr.guild.scheduledEvents.create({
            name: 'example',
            scheduledStartTime: date,
            privacyLevel: GuildScheduledEventPrivacyLevel.GuildOnly,
            entityType: GuildScheduledEventEntityType.External,
        });
    }
```

### Versions

- discord.js 14.14.1
- typescript 5.4.2
- node 18.19.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions

**Comment by almeidx** [comment]
As outlined in the error message, you didn't set the entity metadata location (`entityMetadata.location`), which is required for external events.
