### ISSUE TITLE
[Bug]: Showing the pop-up of ENABLE AUTHENTICATION APP  box even when back button is clicked. 

### ISSUE THREAD

**Issue by anilkr4002** [discordjs/discord.js#10207]
### Which package is this bug report for?

discord.js

### Issue description

Steps to produce:-
1. Go to the profile section within the Discord app and further go to settings.
2. Click on the "Account" option.
3. Click on "Enable Authentication App."
4. A pop-up will appear. You don't need to fill it out; simply click on the back button and observe the experience.

I was attempting to set up multi-factor authentication. When I clicked on "Enable Authentication App" from the account section, a pop-up menu appeared displaying "ENABLE AUTHENTICATION APP." However, since I didn't want to apply it, I clicked on the back button. Despite this, the pop-up menu remained persistent, even as the background kept changing.

![WhatsApp Image 2024-04-06 at 11 21 16 AM](https://github.com/discordjs/discord.js/assets/131806839/833cebf1-69f4-4291-b9d6-9c76fbf53b8d)
![WhatsApp Image 2024-04-06 at 11 21 15 AM (2)](https://github.com/discordjs/discord.js/assets/131806839/49cb44f7-235d-4860-aaf9-e7d3dd5495a3)
![WhatsApp Image 2024-04-06 at 11 21 15 AM (1)](https://github.com/discordjs/discord.js/assets/131806839/4c97e399-4893-48c4-a5cf-fe0ae07ef020)
![WhatsApp Image 2024-04-06 at 11 21 15 AM](https://github.com/discordjs/discord.js/assets/131806839/e67bda08-2b6e-43f9-8f32-fa25332cab56)

### Versions

Versions 223.15 - Stable

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
This is discord.js, an API wrapper for the Discord API. You're in the wrong place!

To report a bug to Discord, go to https://dis.gd/BugReport.
