### ISSUE TITLE
add after and before function to collection

### ISSUE THREAD

**Issue by fiftyy** [discordjs/discord.js#10219]
### Which application or package is this feature request for?

collection

### Feature

Hello, maybe it would be cool to get items before/after key.

like here:
https://discord.js.org/docs/packages/discord.js/main/FetchMessagesOptions:Interface#after
https://discord.js.org/docs/packages/discord.js/main/FetchMessagesOptions:Interface#before

### Ideal solution or implementation

`Collection#after(key: K)`: Should only return messages after the key
`Collection#before(key: K)`: Should only return messages before the key

**Comment by Jiralite** [comment]
The key can be a number, a string, a big integer, an object, an array, a function...

What do you expect `Collection#after()` to do if you receive a collection keyed by functions?

I believe this should be left for users to compare themselves—they will have a better understanding of the data inside a collection they receive.
