### ISSUE TITLE
Support installation_types for slash command builders

### ISSUE THREAD

**Issue by GeekCornerGH** [discordjs/discord.js#10215]
### Which application or package is this feature request for?

builders

### Feature

Discord released [User-installable apps](https://discord.com/developers/docs/tutorials/developing-a-user-installable-app) and Discord.js isn't supporting it. So I'm opening this issue so you can put it into your backlog.

### Ideal solution or implementation

Add 2 properties to the `SlashCommandBuilder` constructor, which are
1. [Integration types (field name: integration_types)](https://discord.com/developers/docs/resources/application#application-object-application-integration-types)
2. [Interaction context (field name:contexts)](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-context-types) 
Per the [Discord Application Command Object docs](https://discord.com/developers/docs/interactions/application-commands#application-command-object)

### Other context

Per [this video](https://youtu.be/FzqIAphRxoc), the standard `ChatInputInteraction` should work with user installed-apps, but I'm not sure about complex uses-cases

**Comment by zastlx** [comment]
+1
