### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by ciumete** [discordjs/discord.js#10221]
### Which package is this bug report for?

discord.js

### Issue description

working until today when i receive the next error:
Unhandled Rejection at: FetchError: request to https://discord.com/api/v7/gateway/bot failed, reason: unable to verify the first certificate
same error i receive when i try to reinstall discord.js
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://registry.npmjs.org/@discordjs%2frest failed, reason: unable to verify the first certificate

### Versions

discord.js@12.5.3
node v20.12.2

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by vladfrangu** [comment]
Well, in no particular order:
- discord.js 12 is deprecated and no longer updated
- https errors are outside our control, sounds like you need to either update your OS or make sure your time is in sync
- If you are using some VPN or DNS that might be blocking things, you might want to disable that too

If you have some repro steps, feel free to follow up and we'll reopen this issue. As it stands tho, this is not a djs issue 👀

**Comment by ciumete** [comment]
discord.js@13.8.1
time is in sync
i don't use VPN, what is the address using discord.js ? to check if is filtered somewhere

**Comment by vladfrangu** [comment]
This goes beyond discord.js, it seems that whatever network config you're using is having HTTPS issues. Try going to `https://discord.com/api/v10/gateway` or `https://registry.npmjs.org` and see what it returns

**Comment by ciumete** [comment]
https://discord.com/api/v10/gateway

Raspuns:

X-Firefox-Early-Data: accepted
X-Firefox-Http3: h3
X-Firefox-Spdy: h2
accept-ranges: bytes
age: 20282
alt-svc: h3=":443"; ma=86400
cache-control: public, max-age=1800
cf-cache-status: HIT
cf-ray: 8767dcbd1c81053b-OTP
content-length: 35
content-security-policy: frame-ancestors 'none'; default-src 'none'
content-type: application/json
date: Thu, 18 Apr 2024 21:49:00 GMT
expires: Thu, 18 Apr 2024 22:19:00 GMT
last-modified: Thu, 18 Apr 2024 16:10:58 GMT
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
....

https://registry.npmjs.org

Raspuns:

X-Firefox-Spdy: h2
cf-cache-status: DYNAMIC
cf-ray: 8767e05ecfd770cf-OTP
content-length: 2
content-type: application/json
date: Thu, 18 Apr 2024 21:51:29 GMT
npm-notice: This endpoint is deprecated. Use https://replicate.npmjs.com instead.
server: cloudflare
vary: Accept-Encoding

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: registry.npmjs.org
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0

Par ca functioneaza ambele linkuri !

**Comment by ciumete** [comment]
so, no solution ?!?!

**Comment by monbrey** [comment]
I've been told that a recent update to ESET antivirus software has been causing this issue for some people. Otherwise, this issue has nothing to do with discord.js, as it's caused by external factors out of our control.
