### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by kevinlul** [discordjs/discord.js#10228]
### Which package is this bug report for?

discord.js

### Issue description

Over the past month, we received three instances of this error event emitted from the Discord.js client:
```
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/app/node_modules/@discordjs/ws/node_modules/ws/lib/receiver.js:213:26)
    at Receiver.startLoop (/app/node_modules/@discordjs/ws/node_modules/ws/lib/receiver.js:159:16)
    at Receiver._write (/app/node_modules/@discordjs/ws/node_modules/ws/lib/receiver.js:98:10)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at TLSSocket.socketOnData (/app/node_modules/@discordjs/ws/node_modules/ws/lib/websocket.js:1303:35)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
```
The occurrences at Eastern Time: 2024-03-13 14:22, 2024-04-19 04:36, 2024-04-24 17:10

Client setup: https://github.com/DawnbrandBots/bastion-bot/blob/master/src/bot.ts#L27-L55

It's not clear if this event is reproducible or an error on Discord's end, e.g. receiving malformed packets from the gateway.

### Versions

- discord.js 14.14.1
- TypeScript 5.4.4
- Node.js 20.12.2 (Docker node:20-bullseye base image)
- Docker version 20.10.2, build 2291f61
- Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-169-generic x86_64)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, MessageContent

**Comment by Qjuh** [comment]
When you say 
> error event emitted from the discord.js client
what event are you referring to? Is it `Client#shardError`? If it is then that is indeed an error about an invalid package received (specifically they sent a compressed package but permessage-deflate was not used). This could either be discord sending that invalid package or your docker container interfering. You could debug this by logging the received data on the underlying socket, but that would need to go deep into private properties of `discord.js`, `@discordjs/ws` and `ws` to get to the `_socket` property of the used WebSocket.

**Comment by kevinlul** [comment]
It is a `shardError`.

**Comment by vladfrangu** [comment]
We've asked Discord about this, waiting on more status updates 🤞

**Comment by Nico-ITA** [comment]
Im also getting this Shard Error Event

**Comment by vladfrangu** [comment]
Several other libraries have encountered similar issues (JDA, dpy to name a few). We're just waiting on more info at this point!

**Comment by SamirMishra27** [comment]
> Several other libraries have encountered similar issues (JDA, dpy to name a few). We're just waiting on more info at this point!

Any response / update from Discord officials yet?

**Comment by Jiralite** [comment]
In the past 36 minutes on the weekend? No. Be patient—this issue will be updated.

**Comment by SamirMishra27** [comment]
> In the past 36 minutes on the weekend? No. Be patient—this issue will be updated.

My bad

**Comment by kevinlul** [comment]
Do you have a link to comment from Discord itself about this?

**Comment by vladfrangu** [comment]
Unfortunately I do not have any public comments about this
