### ISSUE TITLE
`ActionRowBuilder<T>` does not enforce the type of the components to be `T` in the constructor

### ISSUE THREAD

**Issue by Ptitet** [discordjs/discord.js#10259]
### Which package is this bug report for?

builders

### Issue description

When building an ActionRow with `ActionRowBuilder`, the type parameter passed does not seem to enforce the components to be of the type passed.
I tested it in VSCode and got no error from IntelliSense : 
![image](https://github.com/discordjs/discord.js/assets/95184938/ed16b0fa-ef8e-4bfa-a155-690dca5dff62)

### Code sample

```typescript
const actionRow = new ActionRowBuilder<StringSelectMenuBuilder>({
    components: [
        new ButtonBuilder({/* ... */}); // no error from IntelliSense
    ]
});
```

### Versions

- discord.js 14.15.2
- Node.js 20.12.2
- TypeScript 5.4.5
- Linux Mint 21.3

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by monbrey** [comment]
This behaviour only applies to the constructor, which is inherited. We may still be able to address it though.

If you require a solution before a fix is applied, the `.addComponents` method is type-safe:

![image](https://github.com/discordjs/discord.js/assets/5294381/91cc8095-af9b-4674-bed3-3a0782464804)

**Comment by didinele** [comment]
Considering the generic is being removed, this issue is no longer relevant.
