### ISSUE TITLE
addChoices in RoleSelectMenuBuilder or in addRoleOption (SlashCommandRoleOption)

### ISSUE THREAD

**Issue by winvdaking** [discordjs/discord.js#10268]
### Which application or package is this feature request for?

builders

### Feature

Hello ✋ 
I would like us to be able to define the roles we want to display in the drop-down menu or in a slash command.

### Ideal solution or implementation

A new function not necessarily required but which is there if you only want to display specific roles
=> RoleSelectMenuBuilder 
=> SlashCommandRoleOption

### Other context

I'm making a discord bot for an esports structure and they ask me to do a slash command allowing managers to be able to add specific roles to their new player without showing them all the roles.

**Comment by Jiralite** [comment]
discord.js can only implement what Discord provides; Discord does not allow defining a predetermined selection.
