### ISSUE TITLE
Cannot use module due to version upgrading

### ISSUE THREAD

**Issue by tungnnt309** [discordjs/discord.js#10262]
### Which package is this bug report for?

discord.js

### Issue description

1. install `discord.js` lib at version `^14.14.1` then use perfectly
2. but today (07 May 2024), I get this error
![image](https://github.com/discordjs/discord.js/assets/90672512/dd55a5bc-5c83-42a1-9ae0-135a22b6157a)

### Versions

install discord `^14.14.1` using yarn on nodejs version 18 lts

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds

**Comment by almostSouji** [comment]
node.js LTS is v20.12.2 as of writing this, please update node if you wish to use discord.js `v14.15.x`

**Comment by Qjuh** [comment]
`ReadableStream` is part of globals since NodeJS v18.0.0 so I doubt you ran that on NodeJS 18.
