### ISSUE TITLE
Redis ReplyError when pulling with xreadgroup on empty subscribed events

### ISSUE THREAD

**Issue by nizans** [discordjs/discord.js#10273]
### Which package is this bug report for?

brokers

### Issue description

Hey,
First of all, Thanks for this package!

I noticed that `PubSubRedisBroker` errors when it is trying to pull using `xreadgroup` without subscribed events.

The error is a Redis `ReplyError` because the command is incomplete because it has no streams keys in it
Heres the error:
```bash
ReplyError: ERR syntax error
    at parseError (C:\dev\playground\discord-js-redis-broker-reproduce\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\dev\playground\discord-js-redis-broker-reproduce\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'channel',
      '7b60fb0c836ce1d6320712e4b74642c30a9c942d',
      'COUNT',
      '10',
      'BLOCK',
      '5000',
      'STREAMS'
    ]
  }
}
```

The error shows clearly that the command simply missing the stream keys, which at that point don't exists.

Am I doing something wrong here?

If not I think this error can be avoided easily by checking if there's any subscribed events in before the next poll
 
Ill gladly open a PR for that.

Thanks

### Code sample

```typescript
import { PubSubRedisBroker } from "@discordjs/brokers";
import { Redis } from "ioredis";

const broker = new PubSubRedisBroker({ redisClient: new Redis() });

await broker.subscribe("channel", ["event"]);

broker.on("event", (message) => {
  console.log(message);
});

broker.on("error", (error) => {
  // This will be a ReplyError on the next poll
  console.error(error);
});

await broker.publish("event", "message");

// This will make the BaseRedis subscribedEvents empty
// But BaseRedis listen will continue to poll until errors
await broker.unsubscribe("channel", ["event"]);
```

### Versions

- "@discordjs/brokers": "^0.2.2"
- Node 18
- "ioredis": "^5.3.2"

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by didinele** [comment]
> If not I think this error can be avoided easily by checking if there's any subscribed events in before the next poll

yup. odd bug. can I ask what the use case here is? are you dynamically subscribing/unsubscribing to certain keys? I'd never see myself running into this personally

I'll PR a fix soon-ish, this also made me notice the `destroy` method should completely stop polling.

**Comment by nizans** [comment]
Sure, In my case I'm creating a stream per user, subscribing when a user connected via socket and unsubscribing on disconnect. so In this case when last user disconnects this error will occur.

I played around a bit and changing this line https://github.com/discordjs/discord.js/blob/c2432d5704e4e178c044bc0d02f2dabe51450d19/packages/brokers/src/brokers/redis/BaseRedis.ts#L141

to ```while (this.subscribedEvents.size > 0)``` seems to work.. not sure if its enough dough
