### ISSUE TITLE
No definition found for the 'commands' property

### ISSUE THREAD

**Issue by seirdotexe** [discordjs/discord.js#10284]
### Which package is this bug report for?

discord.js

### Issue description

I'm working on registering commands on my bot, but it's very annoying as the `commands` property isn't recognized by JSDOC.

1. Open VSCode
2. Create a new .js file
3. Enter the following code
```js
import { Client, Collection } from 'discord.js';

const client = new Client();

client.commands = new Collection();
```
4. Notice there's no definition for `client.commands`

![image](https://github.com/discordjs/discord.js/assets/80536518/37b8dd06-f8a4-485a-aeea-98903e055cc9)

### Versions

* discord.js v14.14.1
* node.js v20.13.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

No

**Comment by monbrey** [comment]
There's no issue here. `client.commands` is a custom property you're adding to the Client class. It's not documented because it isn't native to discord.js and until you add it, it doesn't exist.

If you'd like it to be recognised by JSdoc, write JSdoc for it.
