### ISSUE TITLE
ClientPresenceStatusData Canary and PTB

### ISSUE THREAD

**Issue by Dyssh04** [discordjs/discord.js#10305]
### Which application or package is this feature request for?

discord.js

### Feature

Currently you can't find any differences in ClientPresenceStatusData. There is no clear option to see if someone is using desktop, desktop canary version or the ptb version.

### Ideal solution or implementation

There are 3 options now for ClientPresenceStatusData. Desktop, Web and Mobile.

I want a desktop to be more extensive. For example if we can use clientStatus.desktop.canary // clientStatus.desktop.ptb which could be true or false.

Also that if a user is logged in on more than 1 desktop versions that this would be shown too.

**Comment by monbrey** [comment]
We cannot provide data that the Discord API doesn't provide us.

You should log this as a feature request for the Discord API
