### ISSUE TITLE
Publish a new release (dev build points to /ws that doesn't include a fix)

### ISSUE THREAD

**Issue by Danielduel** [discordjs/discord.js#10304]
### Which package is this bug report for?

discord.js

### Issue description

Dev release of discordjs (`discord.js@14.15.3-dev.1716768610-d22b55fc8`) points to `@discordjs/ws@1.1.0` instead of `@discordjs/ws@2.0.0-dev.1716768608-d22b55fc8` (most likely it's intended, but it would fix my problem).
`@discordjs/ws@1.1.0` doesn't include fix for invalid protocol value fixed in https://github.com/discordjs/discord.js/pull/10271
I can go around this problem locally, but it's very problematic for "serverless" functions running on deno to go around this problem :/
I am not aware of the current scope for the next release, but I would like to ask for a bugfix publish-release which contains previously-mentioned PR with bumped-up versions

### Versions

As described above

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
This will be a breaking change in discord.js, so it will not happen soon, if anything.

**Comment by Danielduel** [comment]
Thank you for the quick response!

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/releases/tag/14.15.3 includes the compatibility fix for Deno users.
