### ISSUE TITLE
Client is not receiving 'messageCreate' events

### ISSUE THREAD

**Issue by seekcat0** [discordjs/discord.js#10310]
### Which application or package is this feature request for?

discord.js

### Feature

Why does InteractionCreate work with slashcommand but MessageCreate doesn't?
I'll only show this part, it's too long and I don't know if you guys have any idea :<

### Ideal solution or implementation

Why not combine "InteractionCreate" and "MessageCreate" to give two functions "interaction.isCommand", "interaction.isMessage"

### Alternative solutions or implementations

├── node@10.5.2
├── axios@1.7.2
├── discord.js@14.15.2
└── fs@0.0.1-security

### Other context

Code:
if (message.author.bot) return; 
        console.log(message.content)
        const channelid = message.channel.id;
        if (isAutoBypass[channelid]) {
            try {
            const content = message.channel.content;
            if (content.startsWith("https://flux.li/android/external/start.php?HWID=")) {
                if (isDisableCommand("fluxus")) {
                    await interaction.reply({
                        embeds: [
                            {
                                title: 'Access Denied',
                                description: `Sorry its auto fluxus disable by ${madeby}`,
                                color: '15158332',
                                footer: {
                                    text: `Made by ${madeby}`,
                                    icon_url: footer,
                                },
                            }
                        ]
                    });
                    return;
                }
                const userTag = `<@${message.user.id}>`;
                const server = message.guild ? message.guild.name : null;
            
                if (isUserBlacklisted(userTag) || (server && isServerBlacklisted(server))) {
                    await interaction.reply({
                        embeds: [
                            {
                                title: 'Access Denied',
                                description: 'You are not allowed to use this service.',
                                color: '15158332',
                                footer: {
                                    text: `Made by ${madeby}`,
                                    icon_url: footer,
                                },
                            }
                        ]
                    });
                    return;
                }
                await AutoFluxus(message, madeby, footer); 
            }
            } catch (err) { console.log(err) }
        }

**Comment by Jiralite** [comment]
Please use Discord for questions. This issue tracker is for bug reports and feature requests.
