### ISSUE TITLE
`ws` throws `TypeError: Cannot use 'in' operator to search for 'code' in undefined` when with Deno

### ISSUE THREAD

**Issue by NeuroWhAI** [discordjs/discord.js#10327]
### Which package is this bug report for?

ws

### Issue description

1. Use deno, Make a simple Discord bot.
2. Leave the bot running for a long time. (Maybe 1 day?)
3. The bot suddenly throws an error and dies.

Error : `TypeError: Cannot use 'in' operator to search for 'code' in undefined`
Location: https://github.com/discordjs/discord.js/blob/main/packages/ws/src/ws/WebSocketShard.ts#L794

If I manually modify the conditional statement locally as follows, the problem no longer occurs.
But I'm not sure if it's okay to do this.

```js
onError(error) {
  if (error && "code" in error && ["ECONNRESET", "ECONNREFUSED"].includes(error.code)) {
```

I'm not sure if this is due to differences between Deno and Node.js, but I suspect it is.

### Versions

- discord.js 14.15.3
- Deno 1.44.0

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by didinele** [comment]
Hi. Do you have a full stack trace? I'd like to see what invoked `onError`

**Comment by NeuroWhAI** [comment]
I will reproduce and get the trace log.

**Comment by NeuroWhAI** [comment]
Here is a trace log. @didinele 

```
error: Uncaught TypeError: Cannot use 'in' operator to search for 'code' in undefined
    at WebSocketShard.onError (file:///C:/Users/neurobox/AppData/Local/deno/npm/registry.npmjs.org/@discordjs/ws/1.1.1/dist/index.js:1065:16)
    at WebSocket.connection.onerror (file:///C:/Users/neurobox/AppData/Local/deno/npm/registry.npmjs.org/@discordjs/ws/1.1.1/dist/index.js:683:12)
    at WebSocket.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at WebSocket.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:471:16)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by Jiralite** [comment]
If possible, would you be able to log `event` here so we can see what the payload is?

https://github.com/discordjs/discord.js/blob/757bed0b1f345a8963bc4eb680bed4462531fb49/packages/ws/src/ws/WebSocketShard.ts#L259

**Comment by NeuroWhAI** [comment]
@Jiralite It was `{}`... 🤔

**Comment by didinele** [comment]
That's most certainly a deno bug of some sort then, recommend reporting it.

**Comment by keybraker** [comment]
Even now that Deno2 is out and we are on 2.0.6 this is still an issue, and not only that but also voice streams are not full implemented on Deno2.

**Comment by didinele** [comment]
There's nothing we can do about it. Deno2 should fix it for 1.x, complain to them about it.

As per 2.0 usage in `discord.js`, use the dev version, it's not coming to v14.

**Comment by keybraker** [comment]
> There's nothing we can do about it. According to the Deno issue, `@discordjs/ws`@`1.x` should work now as of Deno 2.x
> 
> As per 2.0 usage in `discord.js`, use the dev version, it's not coming to v14.

What do you mean with this? 


_As per 2.0 usage in discord.js, use the dev version, it's not coming to v14._

**Comment by vladfrangu** [comment]
discordjs 14 will not upgrade to discordjs/ws 2.x.x

**Comment by keybraker** [comment]
> discordjs 14 will not upgrade to discordjs/ws 2.x.x

Thanks for the inside, will Yolo it with `15.0.0-dev.1731413115-e2df0e0db` as the deno branch is doomed until this is fixed..

**Comment by blaze-developer** [comment]
> There's nothing we can do about it. According to the Deno issue, `@discordjs/ws`@`1.x` should work now as of Deno 2.x
> 
> As per 2.0 usage in `discord.js`, use the dev version, it's not coming to v14.

What do you mean by, "There's nothing we can do about it"?

Isn't the obvious answer here to update to ws 2.0?

**Comment by didinele** [comment]
Yes, this has been done for v15/dev. It cannot be done for v14 in a non-breaking way.
