### ISSUE TITLE
New Premium Button Style & Deep Linking URL Schemes

### ISSUE THREAD

**Issue by RappyTV** [discordjs/discord.js#10357]
### Which application or package is this feature request for?

discord.js

### Feature

Discord has recently updated the way premium interactions work and it would be great to be able to use it with discord.js.
+ https://github.com/discord/discord-api-docs/pull/6875/files

### Ideal solution or implementation

+ Deprecate or remove `Interaction#sendPremiumRequired`
    https://discord.com/developers/docs/change-log#premium-apps-new-premium-button-style-deep-linking-url-schemes
    > This change deprecates Interaction Response Type 10
+ Add `ButtonStyle#Premium` and a new `skuId` field for buttons and the corresponding methods on the `ButtonBuilder`
(e. g. `#setSkuId`)
    https://discord.com/developers/docs/interactions/message-components#button-object-button-styles
    ![image](https://github.com/discordjs/discord.js/assets/72705182/0298074b-f2a6-472e-882b-6922ffa5c566)
    > Premium buttons must contain a `sku_id`, and cannot have a `custom_id`, `label`, `url`, or `emoji`

    **Example premium button object:**
    ```json
     {
         "type": 2,
         "style": 6,
         "sku_id": "<SKU ID>"
    }
    ```
+ Add `SKU#getUrl` and `ClientApplication#getStoreUrl` (can also be `Client#getStoreUrl`)
    **https://discord.com/developers/docs/monetization/skus#linking-to-your-skus**
    > You can link directly to a specific SKU using our Application Directory Store URL scheme:
    https://discord.com/application-directory/:appID/store/:skuID

    **https://discord.com/developers/docs/monetization/managing-your-store#linking-to-your-store**
    > You can link directly to your Store using our Application Directory Store URL scheme:
    https://discord.com/application-directory/:appID/store

**Comment by Jiralite** [comment]
Hi, be sure to search open issues or pull requests already. It could have saved you writing all this.

**Comment by RappyTV** [comment]
oh I only looked at the issues i'm sorry 💀
