### ISSUE TITLE
ws affected by a DoS when handling a request with many HTTP headers

### ISSUE THREAD

**Issue by Knightplayzz** [discordjs/discord.js#10359]
### Which package is this bug report for?

discord.js

### Issue description

When I push my discordbot to github I get a security allert from dependabot. It comes from an outdated package that discord.js is using. I've coppied over the message from the security allert.

https://github.com/advisories/GHSA-3h5v-q93c-6h6q

### Versions

 "discord.js": "^14.15.3",
"node": "20.14.0"

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

discord.js@14.15.3

**Comment by Jiralite** [comment]
This is already a non-issue because of #10322.
