### ISSUE TITLE
Update bot documentation

### ISSUE THREAD

**Issue by rico345100** [discordjs/discord.js#10369]
### Which application is this bug report for?

Documentation

### Issue description

Doesn't work anything jack shit.

### Steps to Reproduce

Running index go failure

### Versions

Windows 10

### Issue priority

High (immediate attention needed)

**Comment by Jiralite** [comment]
Per #10368, you were told to head to our Discord server for help (even after a resolution). That does not mean creating an issue, let alone the description you wrote.

Familiarise yourself with the [contributing guidelines](https://github.com/discordjs/discord.js/blob/main/.github/CODE_OF_CONDUCT.md) before contributing in the future.
