### ISSUE TITLE
Using A Bot Anywhere with SlashCommandBuilder

### ISSUE THREAD

**Issue by vgthecoder** [discordjs/discord.js#10379]
### Which application or package is this feature request for?

discord.js

### Feature

A good addition to Discord.js would be the ability to set if you can use an app anywhere. It is fairly recent. And this video shows exactly what I mean, but not using the "SlashCommandBuilder". https://www.youtube.com/watch?v=FzqIAphRxo

### Ideal solution or implementation

A new function to SlashCommandBuilder, like `.Anywhere(1)`.

### Alternative solutions or implementations

A attribute somewhere that makes all the commands usable anywhere.

### Other context

![image](https://github.com/discordjs/discord.js/assets/167907693/fc495b12-b755-4f06-9c7c-1ed23afaf2af)

**Comment by Jiralite** [comment]
That video is not available. Additionally, what you are describing has been implemented by #10348.

**Comment by vgthecoder** [comment]
Are there any docs for this?
________________________________
