### ISSUE TITLE
GuildScheduledEvent creator property returns null

### ISSUE THREAD

**Issue by gegelendvay** [discordjs/discord.js#10387]
### Which package is this bug report for?

discord.js

### Issue description

1. Implement logging for the `guildScheduledEventCreate` event in a bot using the code sample provided below.
2. Schedule a new event in the Discord client.
3. Check the console for the event log.
4. Note that the console log returns `null` instead of the expected User object: https://discord.js.org/docs/packages/discord.js/14.14.1/GuildScheduledEvent:Class#creator

### Code sample

```typescript
client.on('guildScheduledEventCreate', (event) => {
    if (!event) return;
    console.log(event.creator);
});
```

### Versions

- discord.js 14.15.3
- Node.js v18.16.1
- macOS Sonoma 14.5

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildInvites, GuildVoiceStates, GuildMessages, MessageContent, GuildScheduledEvents

**Comment by Jiralite** [comment]
The creator is only populated if the respective object is sent or if `creator_id` is known in your user cache. This is not a bug.
