### ISSUE TITLE
Network errors still happening

### ISSUE THREAD

**Issue by AlexDiego123** [discordjs/discord.js#10392]
I tested this on the new dev build that has the fix for the `EAI_AGAIN` error and this error is still happening.

**Logs** (dev build `efa16a609`): https://pastebin.com/F7qmqjMp

_Originally posted by @AlexDiego123 in https://github.com/discordjs/discord.js/issues/10382#issuecomment-2223802925_

**Comment by didinele** [comment]
Hi, so, to be clear, you aren't using discord.js right?

What's your exact `@discordjs/ws` version?

**Comment by didinele** [comment]
Hey, nevermind. It turns out this is an `async_event_emitter` bug, pushed about 3 weeks ago (haven't checked when it was actually released on NPM), @vladfrangu is working on a fix and we should be good to go.

**Comment by didinele** [comment]
`@vladfrangu/async_event_emitter@2.4.4` is now out, so please force it to update and see if it still causes trouble - this goes for everyone in this thread.

I'm not sure what the "proper" way of forcing a non-direct dep like that to update is, but for sure wiping your `node_modules` and lock file and rerunning `npm i`/`yarn`/`pnpm i` will be enough.

**Comment by AlexDiego123** [comment]
This seems to be working for now with `@vladfrangu/async_event_emitter@2.4.4`, I will keep you updated if the error comes back again.
