### ISSUE TITLE
Application Emojis

### ISSUE THREAD

**Issue by J-295** [discordjs/discord.js#10396]
### Which application or package is this feature request for?

discord.js

### Feature

Discord has added Application Emojis and allows them to be managed through the API.
[In Change Log](https://discord.com/developers/docs/change-log#application-emoji)
[In Docs](https://discord.com/developers/docs/resources/emoji#list-application-emojis)

### Ideal solution or implementation

I would like for it to be possible to manage these through discord.js

**Comment by monbrey** [comment]
We know, we're working on it. PR coming soon.

**Comment by J-295** [comment]
I opened the issue as a way for me and others to subscribe to updates on this being implemented. Thanks for the info :)
