### ISSUE TITLE
InteractionWebhook methods crash the app if an invalid token is provided

### ISSUE THREAD

**Issue by rbarneyyy** [discordjs/discord.js#10413]
### Which package is this bug report for?

discord.js

### Issue description

While using the InteractionWebhook class and creating an instance with correct credentails, waiting 15 minutes (as the token expires in that timeframe) and then trying to run any methods, an invalid token error is returned but the whole application crashes. 

I am using version 14.5.3 and the method used (<InteractionWebhook>.editMessage() in my case) was awaited and inside a try block. I am assuming this is a bug, thanks for the help in advance!

### Versions

- discord.js 14.5.3
- Node JS 20.14.0
- MacOS 14.5

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds

**Comment by vladfrangu** [comment]
Do you have any stack traces or similar? What does "it crashes" mean?

**Comment by rbarneyyy** [comment]
Yep, here is the stack trace:

/home/container/node_modules/@discordjs/rest/dist/index.js:730
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[50027]: Invalid Webhook Token
    at handleErrors [90m(/home/container/[39mnode_modules/[4m@discordjs[24m/rest/dist/index.js:730:13[90m)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async SequentialHandler.runRequest [90m(/home/container/[39mnode_modules/[4m@discordjs[24m/rest/dist/index.js:1133:23[90m)[39m
    at async SequentialHandler.queueRequest [90m(/home/container/[39mnode_modules/[4m@discordjs[24m/rest/dist/index.js:963:14[90m)[39m
    at async _REST.request [90m(/home/container/[39mnode_modules/[4m@discordjs[24m/rest/dist/index.js:1278:22[90m)[39m
    at async InteractionWebhook.editMessage [90m(/home/container/[39mnode_modules/[4mdiscord.js[24m/src/structures/Webhook.js:341:15[90m)[39m
    at async addUser [90m(/home/container/[39mcommands/multiGame.js:202:7[90m)[39m {
  requestBody: {
    files: [],
    json: {
      content: [90mundefined[39m,
      tts: [33mfalse[39m,
      nonce: [90mundefined[39m,
      enforce_nonce: [33mfalse[39m,
      embeds: [
        {
          title: [32m'<:guess:1221494870170931230> Multi-Player GeoJourney Game'[39m,
          description: [32m'A new game is starting soon. Check the details of this upcoming game below:\n'[39m +
            [32m'\n'[39m +
            [32m'**Host:** <@1047915850633576448>\n'[39m +
            [32m'\n'[39m +
            [32m'**Game Type:** Public\n'[39m +
            [32m'\n'[39m +
            [32m'**Users Joined:** 5\n'[39m +
            [32m'\n'[39m +
            [32m'**Player List:** <@1047915850633576448>, <@995087374717550714>, <@1115292074372239373>, <@904739598985461771>, <@829419631739273297>'[39m,
          color: [33m6258135[39m,
          thumbnail: {
            url: [32m'https://cdn.discordapp.com/avatars/829419631739273297/336d5030bf80ffb2ebb271910de9a04c.webp'[39m
          }
        }
      ],
      components: [90mundefined[39m,
      username: [90mundefined[39m,
      avatar_url: [90mundefined[39m,
      allowed_mentions: [90mundefined[39m,
      flags: [90mundefined[39m,
      message_reference: [90mundefined[39m,
      attachments: [90mundefined[39m,
      sticker_ids: [90mundefined[39m,
      thread_name: [90mundefined[39m,
      applied_tags: [90mundefined[39m,
      poll: [90mundefined[39m
    }
  },
  rawError: { message: [32m'Invalid Webhook Token'[39m, code: [33m50027[39m },
  code: [33m50027[39m,
  status: [33m401[39m,
  method: [32m'PATCH'[39m,
  url: [32m'https://discord.com/api/v10/webhooks/1225076420980641882/aW50ZXJhY3Rpb246MTI2Njc3NDUxMTQyMDcwNjkzODpEOHdoMEZoMnQ2a1lKYnVEU084eEJWNmRHa3l2VVF1NUpnRXg4eEVGZmVIVDhZdDBVa1QyY1JkUk1PU0oyZkRiVG12V3lGaDdxWVdNQnNvb01WaWJ3Y1JOd3FjUks0THVDZG1ES2ZvTWlPamxMVWNsOHEyNG9JdUhXYzl3Um1yNw/messages/@original'[39m
}

Node.js v20.14.0

**Comment by Qjuh** [comment]
That looks like it should be catchable just fine in your `multigame.js` line 202. can you provide the code where you await and catch rejections from that line please?

**Comment by rbarneyyy** [comment]
I'm so sorry lol, as I was about to paste it I found the issue. Thanks anyways!
