### ISSUE TITLE
Add USE_EXTERNAL_APPS Permission to permissionOverwrites

### ISSUE THREAD

**Issue by KotyaraDev** [discordjs/discord.js#10422]
### Which application or package is this feature request for?

discord.js

### Feature

I would like to see a new permission, `USE_EXTERNAL_APPS` (1 << 50), added to `permissionOverwrites`. This permission would enable more granular control over external applications integration within Discord channels.

### Ideal solution or implementation

Please add the `USE_EXTERNAL_APPS` permission to the `permissionOverwrites` options in Discord.js. This would allow developers to manage permissions related to the use of external applications more effectively.

### Other context

https://discord.com/developers/docs/change-log#june-27-2024-new-use-external-apps-permission

**Comment by Qjuh** [comment]
Already done by #10404 in dev version, so will be in next release.
