### ISSUE TITLE
OAuth2 method for token revoke endpoint 

### ISSUE THREAD

**Issue by Larsundso** [discordjs/discord.js#10439]
### Which application or package is this feature request for?

core

### Feature

Support for Discords OAuth2 Token revokation endpoint 

### Ideal solution or implementation

Added onto of the already existing `<API>.oauth2`

### Other context

https://discord.com/developers/docs/topics/oauth2

https://discord.com/api/oauth2/token/revoke

**Comment by misonomikadev** [comment]
There is already have the libary support OAuth2 for Discord
See here: https://npmjs.com/package/discord-oauth2

**Comment by Larsundso** [comment]
> There is already have the libary support OAuth2 for Discord See here: https://npmjs.com/package/discord-oauth2

Missed the point.
<API>.oauth2 already supports all token requests. It should also support the revoke request for completeness
