### ISSUE TITLE
Error happens when trying to edit a followup message: [Could not find the channel where this message came from in the cache!]

### ISSUE THREAD

**Issue by glink25** [discordjs/discord.js#10441]
### Which package is this bug report for?

discord.js

### Issue description

when I was trying to edit a message which was "followupped" by an interaction, it crashed and tolds an error:
```
Error [ChannelNotCached]: Could not find the channel where this message came from in the cache!
    at Message.edit (/home/glink25/linkbot/node_modules/discord.js/src/structures/Message.js:749:46)
    at Timeout.eval (/home/glink25/linkbot/main.ts:7:1644)
    at <anonymous> (node:internal/timers:246:4663) {
  code: 'ChannelNotCached'
}
```
the code below can reproduce on my environment
```typescript
import {
    REST,
    Routes,
    Client,
    GatewayIntentBits,
    Message,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle,
    Partials,
  } from 'discord.js';
  import { CONFIG } from './config';
  
  const commands = [
    {
      name: 'follow',
      description: 'followup test',
    },
  ];
  
  const registerCommands = async () => {
    const rest = new REST({
      version: '10',
      userAgentAppendix: 'DiscordBot',
    }).setToken(CONFIG.TOKEN);
  
    try {
      console.log('Started refreshing application (/) commands.');
  
      await rest.put(Routes.applicationCommands(CONFIG.CLIENT_ID), {
        body: commands,
      });
  
      console.log('Successfully reloaded application (/) commands.');
    } catch (error) {
      console.error(error);
    }
  };
  
  registerCommands();
  const client = new Client({ intents: [
    GatewayIntentBits.Guilds,
  ]});
  
  client.on('ready', () => {
    console.log(`Logged in as ${client.user?.tag}!`);
  });
  
  client.on("interactionCreate",async(interaction)=>{
    if(!interaction.isChatInputCommand())return
    if(interaction.commandName!=="follow")return
    await interaction.reply("hhh")
    const msg = await interaction.followUp("followup")
    setTimeout(() => {
      msg.edit("new follow") // this will throw an error
    }, 1000);
  })
  
  client.login(CONFIG.TOKEN);
  
```

It seem the `edit()` function is unable to use on a followup message?

### Code sample

```typescript
import {
    REST,
    Routes,
    Client,
    GatewayIntentBits,
    Message,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle,
    Partials,
  } from 'discord.js';
  import { CONFIG } from './config';
  
  const commands = [
    {
      name: 'follow',
      description: 'followup test',
    },
  ];
  
  const registerCommands = async () => {
    const rest = new REST({
      version: '10',
      userAgentAppendix: 'DiscordBot',
    }).setToken(CONFIG.TOKEN);
  
    try {
      console.log('Started refreshing application (/) commands.');
  
      await rest.put(Routes.applicationCommands(CONFIG.CLIENT_ID), {
        body: commands,
      });
  
      console.log('Successfully reloaded application (/) commands.');
    } catch (error) {
      console.error(error);
    }
  };
  
  registerCommands();
  const client = new Client({ intents: [
    GatewayIntentBits.Guilds,
  ]});
  
  client.on('ready', () => {
    console.log(`Logged in as ${client.user?.tag}!`);
  });
  
  client.on("interactionCreate",async(interaction)=>{
    if(!interaction.isChatInputCommand())return
    if(interaction.commandName!=="follow")return
    await interaction.reply("hhh")
    const msg = await interaction.followUp("followup")
    setTimeout(() => {
      msg.edit("new follow") // this will throw an error
    }, 1000);
  })
  
  client.login(CONFIG.TOKEN);
```

### Versions

- discord.js 14.12.1
- Node.js 1v18.20.3
- TypeScript 5.1.6
- macOS Sonoma 14.4

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by imnaiyar** [comment]
Is this on User App? In which case it is understandable as channels might not be cached. Use <Interaction>.editReply(...)

**Comment by glink25** [comment]
> Is this on User App? In which case it is understandable as channels might not be cached. Use .editReply(...)

Is there any other way to make it possible to edit a followup message? Here is my case, I want to make a quiz bot, which gives 5 random questions, and each question will record user's choice after they click the option, but editReply() will override the latest question message while followup create a new one, I want to make all questions shows their answer together

**Comment by monbrey** [comment]
`editReply` accepts a `message` option telling it which reply to edit, which supports followUps

**Comment by glink25** [comment]
> `editReply` accepts a `message` option telling it which reply to edit, which supports followUps

But when I was trying to use `.edit()` function on a followUp message, it throws an error, that's what I am confused about

**Comment by monbrey** [comment]
What's confusing?

We're telling you to use `interaction.editReply()`, which can edit any reply to the interaction, including followUps.

Do not use `message.edit()`.

**Comment by glink25** [comment]
> What's confusing?
> 
> We're telling you to use `interaction.editReply()`, which can edit any reply to the interaction, including followUps.
> 
> Do not use `message.edit()`.

Got it, thanks for answering my question, this issue could be closed

**Comment by glink25** [comment]
followup message should be edit like this:
```javascript
const msg = await interaction.followUp("followup")
await interaction.editReply({ message:msg, content:"new msg" }) // now followup message change to new "msg"
```

**Comment by imnaiyar** [comment]
> followup message should be edit like this:
> ```javascript
> const msg = await interaction.followUp("followup")
> await interaction.editReply({ message:msg, content:"new msg" }) // now followup message change to "new msg"
> ```

Yes, again, you should refer to [docs](https://discord.js.org). It has all the answers
