### ISSUE TITLE
API response with code 30034 should be added as a DiscordAPIError[30034]

### ISSUE THREAD

**Issue by aymanbhrr** [discordjs/discord.js#10458]
### Which application or package is this feature request for?

discord.js

### Feature

I was having some problems deploying my app commands in my server; they weren't deploying at all and I was not getting any prompt (error, message...) and I was losing my mind ngl because I didn't know what was going on. Someone in the djs server suggested me to run a curl request to see what the reponse headers give me but it didn't really work and didn't clarify my confusion as I was not really familiar with curl, so I decided to use axios instead and I finally got a response which was _"Max number of daily application command creates has been reached (200)"_. (status code 429)

### Ideal solution or implementation

Add a DiscordAPIError whose message is "Max number of daily application command creates has been reached (200)" and its corresponding error code (30034)

### Other context

![image](https://github.com/user-attachments/assets/8d8e84f1-06ff-45b2-ae19-4af31769140f)

**Comment by imnaiyar** [comment]
Discord.js queues requests on rate limits. If you want to listen to those limits, you would have to listen to the `rateLimited` event on `REST`. This is by design.

Also, you should not attempt to deploy commands on startup. It should be a separate script that should be run only when you make changes to your commands, precisely because of the error you received.

**Comment by aymanbhrr** [comment]
> Discord.js queues requests on rate limits. If you want to know when that happens, you would have to listen to the `rateLimited` event on `REST`. This is by design.

Actually, before using the axios method, I already was listening to that event and didn't get any prompt either.
`REST.on("reateLimited", () => console.log("rate limited"))`

> Also, you should not attempt to deploy commands on startup. It should be a separate script that should be run only when you make changes to your commands, precisely because of the error you received.

I am aware of that, I'm just saying that it would be nice to have that feature in the library for those who are not aware.
Also, as discord.js queues requests on rate limits, this one could be an exception and actually prompt an error.

**Comment by Qjuh** [comment]
The event is named `rateLimited` and you‘d need to listen to it on the instance of the class `REST`, not the class itself.

**Comment by aymanbhrr** [comment]
> The event is named `rateLimited` and you‘d need to listen to it on the instance of the class `REST`, not the class itself.

Oops, I've made a typo on the name of the event. And I already knew these two things, the "REST" word I wrote was just to make you understand that I use an instance of the `REST` class.
(and yes, I've wrote the event name correctly in my code before creating this issue, I just did a typo in my comment)

**Comment by didinele** [comment]
Hey there, we can't reproduce the ratelimited event not firing. If you're able to provide a minimal code sample used to reproduce the problem, feel free to open a new issue specifically addressing that.

As it stands, it is intended behavior that the library implicitly waits out ratelimits. If you'd like different behavior for specific routes, use the [`rejectOnRatelimit` rest option](https://discord.js.org/docs/packages/rest/main/RESTOptions:Interface#rejectOnRateLimit)
