### ISSUE TITLE
Add support for APIGuildScheduledEventRecurrenceRule

### ISSUE THREAD

**Issue by reteps** [discordjs/discord.js#10473]
### Which application or package is this feature request for?

discord.js

### Feature

- Add support for repeatable events: https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-recurrence-rule-object (types: https://discord-api-types.dev/api/discord-api-types-v10/interface/APIGuildScheduledEventRecurrenceRule)

- Extension of creating/editing events through discord.js

### Ideal solution or implementation

Add the types and updated API calls for this to work.

**Comment by Jiralite** [comment]
Be sure to search existing pull requests and issues! It could have saved you typing this up.

**Comment by reteps** [comment]
oops - looked through issues but not PRs.
