### ISSUE TITLE
Give an Emoji Select Option to Slash Commands.

### ISSUE THREAD

**Issue by OfficialRushO** [discordjs/discord.js#10520]
### Which application or package is this feature request for?

discord.js

### Feature

I'd like to have an option to send emoji select options to slash command users with min and max values. It'll make implementing certain things easier, like Reaction Role commands that we need the user to enter an emoji.

That can be done with a string option, without that emoji select option also, but users can mess with the bot easily.

### Ideal solution or implementation

A slash command option that only accepts emoji inputs.

- Shows the general & custom emoji menus.
- Named something like `addEmojiOption`.
- Ability to set min, max values and required state.

**Comment by monbrey** [comment]
We can only implement features that are provided by the Discord API. Please direct your feature request to Discord.
