### ISSUE TITLE
discord.js (ESM) 

### ISSUE THREAD

**Issue by MAKGAMEROFFICIAL** [discordjs/discord.js#10566]
### Which application or package is this feature request for?

discord.js

### Feature

Kindly rewrite discord.js in esm

### Ideal solution or implementation

rewrite discord.js library in ESM module 

### Alternative solutions or implementations

Convert discord.js from cjs to esm

**Comment by monbrey** [comment]
discord.js will eventually be rewritten in TypeScript like the majority of it's modules, so a rewrite to ESM would not be worth the effort.

It supports being imported into ESM-style JavaScript projects already.

**Comment by MAKGAMEROFFICIAL** [comment]
but still
