### ISSUE TITLE
message.interaction deprecated but message.interactionMetadata does not have commandName property

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [discordjs/discord.js#10659]
### Which package is this bug report for?

discord.js

### Issue description

Not sure what to put here. This isn't really a bug, nor is it a feature. node_modules/discord.js/typings/index.d.ts marks `Message.interaction` as deperacted and instructs you to use `Message.interactionMetadata` instead but `interactionMetadata` does not have the property `commandName`.

### Code sample

```typescript
async messageHandler(message: Message): Promise<boolean> {
        if (!await super.messageHandler(message)) return false;

        const isDisboardBot = message.author.username === 'DISBOARD';
        // message.interaction is deprecated but commandName is not available in interactionMetadata which is the replacement
        const isBumpCommand = message.interaction?.commandName === 'bump';
        // TODO: Review - this seems to be inconsistent, but the new way might not always be correct?
        // const isBumpDone = message.embeds.length > 0 && message.embeds[0].description?.startsWith('Bump done');
        const isBumpDone = isDisboardBot && isBumpCommand;

        if (!message.guildId || !isBumpDone) {
            return false;
        }

        const nextBumpTime = new Date(message.createdTimestamp + TWO_HOURS);

        // Create or update the bump timer for the guild to notify in 2 hours
        await BumpTimer.createOrUpdate({
            guildId: message.guildId,
            channelId: message.channel.id,
            nextBumpAt: nextBumpTime
        });

        return true;
    }
```

### Versions

- discord.js 14.16.3
- discord-api-types 0.37.93
- Node.js 20.10.0
- TypeScript 5.5.3

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by cobaltt7** [comment]
https://github.com/discord/discord-api-docs/pull/6734

**Comment by Jiralite** [comment]
Discord has deprecated the interaction property, so we followed. Discord introduced the `interaction_metadata` property, so we followed. As you said, there is no bug here. You have to figure out a different way to do what you want.
