### ISSUE TITLE
Silent disconnect

### ISSUE THREAD

**Issue by mitsuakki** [discordjs/discord.js#10650]
### Which package is this bug report for?

discord.js

### Issue description

My bot disconnect himself without crash logs. Even if we don't use it, it crash.
Is this a known problem ?

### Versions

- discord.js 14.16.3
- docker.io/denoland/deno:alpine

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildIntegrations, GuildVoiceStates, GuildMessages, GuildMessageReactions

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
