### ISSUE TITLE
`GuildChannelManager#fetch(id)` returns array of all channels when channel is not found

### ISSUE THREAD

**Issue by RappyTV** [discordjs/discord.js#10667]
### Which package is this bug report for?

discord.js

### Issue description

1. Fetch a guild with `GuildManager#fetch`
2. Fetch channels of that guild with `GuildChannelManager#fetch(id)` with an invalid id and a catch clause
3. You won't receive the value from the catch clause but an array of all channels

### Code sample

```typescript
async function fetchGuild() {
    return client.guilds.fetch(config.guildId);
}
async function doSomethingWithChannel(): void {
    const channel = await (await fetchGuild()).channels.fetch('channelID', { force: true }).catch(() => null);
    if(!channel || !channel.isSendable()) return; // Code fails here because channel is an array of all channels and not null
    console.log(channel.id);
}
```

### Versions

- discord.js v14.16.3
- bun 1.1.42
- typescript ^5.0.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by Qjuh** [comment]
I can‘t reproduce that. Did you actually provide the id hardcoded like your example suggests? Or could it be that you actually passed `undefined` as id there, because you passed a variable that didn’t exist? In which case this would be expected behavior.

**Comment by RappyTV** [comment]
oh yea sorry I was using an environment variable which I later corrected. my bad
