### ISSUE TITLE
Discord.js docs need more examples like the old docs

### ISSUE THREAD

**Issue by dylanh724** [discordjs/discord.js#1585]
The old docs had THE best documentation I've ever seen, giving actual-use examples rather than a dictionary.

Which makes more sense:

> "I want to learn Chinese."
**"Here's a dictionary!"** 
_(Current d.js docs)_

> "I want to learn Chinese."
**"Here is a book with common-use examples and and a standard architecture to follow"** 
_(Obsolete d.js docs)_

The latter, of course. The main docs teach us how to .... ping/pong and reply to a message, but nothing else useful. RichEmbed, for example. Why not show something like:

![image](https://user-images.githubusercontent.com/8840024/27009661-95bafd5e-4ec6-11e7-887b-5c246e6063c9.png)

Followed by something like `client.<channelID>.send(embed)`

for a common-use example, just for starters? Anything, really. I've been learning from old discord.js docs, then going through the errors to see what's outdated. Such a simple example like above would've saved me an hour of research+trial+error, simply because all that's presented is nothing more than a dictionary.

Docs with example-use = less questions = less tickets. It's a "win" all around.

**The templates _already_ exist in the old docs --** just need to edit a bit to proper standards.

**Comment by hydrabolt** [comment]
I agree, it's something we'll work on. Thanks for loving the old docs, they took a long time to type out! 😛

**Comment by HaydenMeloche** [comment]
@hydrabolt Are you guys looking for doc contributors? I'm sorta new to Discord.JS but have lots of experience with other discord APIs and I think I could do some examples for various functions.

**Comment by devsnek** [comment]
@HaydenMeloche don't ask, just find things you wanna work on and make PRs, thats the beauty of github

**Comment by hydrabolt** [comment]
@HaydenMeloche that'd be great!
