### ISSUE TITLE
Allow custom execArg when sharding w/ ShardingManager

### ISSUE THREAD

**Issue by pedall** [discordjs/discord.js#1714]
**Please describe the problem you are having in as much detail as possible:**

I am using default discord.js sahrding with the sharding manager, but then I realized I cant use the built in debugger in WebStorm anymore. By searching the internet I found a solution that works for me.

When forking doing the childprocess fork you have to add one argument so that the node inspector runs on different ports.

**Include a reproducible code sample here, if possible:**
so I needed to add the execArgv property when forking the child process:
```js
this.process = childProcess.fork(path.resolve(this.manager.file), args, {
      env: this.env,
      execArgv: ['--inspect-brk=0']
    });
```
Would it be possible to add this to the lib, if maybe other users have this "debug problem" as well? or do you maybe have a different solution for this that I maybe did not find yet :wink:

**Further details:**

- discord.js version: latest master
- node.js version: 8.1.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
you can already do this by setting `options.shardArgs` when creating a new ShardingManager like
```js
const m = new ShardingManager({
  shardArgs: ['--inspect-brk=0'],
});
```

**Comment by pedall** [comment]
sorry, but that won`t work for me. Did I make sth wrong?

```
const manager = new ShardingManager(path.join(__dirname, 'local.js'), {
  token: processLocal.env.botToken,
  shardArgs: ['--inspect-brk=0'],
});
```

**Comment by Gawdl3y** [comment]
We use [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), not fork. And even fork has an `args` arg.

**Comment by pedall** [comment]
yeah, but the `execArgv: ['--inspect-brk=0']`has to be in the `options` not the `args`. Also from the code i would say that you use fork:  (see master branch)

in the `_spawn` method of the ShardingManager class you call "const shard = new Shard(this, id, this.shardArgs);`. In the Shard class actually there is

```
 this.process = childProcess.fork(path.resolve(this.manager.file), args, {
      env: this.env,
    });
```

I am not good in this area, but I can just tell what I see and that my solution works, the one proposed by snek doesn`t. All I want is to debug the sharded bot with my IDE without having to put that line into the Shard.js file everytime I update discord.js :sweat:

**Comment by Gawdl3y** [comment]
`args` and `execArgv` serve two entirely different purposes. `args` get passed to the script, whereas `execArgv` gets passed to the Node executable. Our sharding manager's `args` work exactly as intended. If anything, this should be a feature request for the ability to pass arguments to the executable.

**Comment by 112madgamer** [comment]
Has this issue gone any further or anyway to debug a sharded bot?
