### ISSUE TITLE
Make playOpusStream method support other bitrate

### ISSUE THREAD

**Issue by mmis1000** [discordjs/discord.js#1823]
Audio bitrate support were added in [This commit](https://github.com/hydrabolt/discord.js/commit/4342ed29a845a7caf1b5f22b40c5e1d2d491600a)

However, the `playOpusStream` method isn't changed to support other bitrate in this commit.
The opus packet size to send per tick is hardcoded to `80 * 2` at [Here](https://github.com/hydrabolt/discord.js/blob/4342ed29a845a7caf1b5f22b40c5e1d2d491600a/src/client/voice/VoiceBroadcast.js#L332)

so the following setup just won't work at all if Bitrate isn't 64000

```js
const Discord = require("discord.js");
const ytdl = require('ytdl-core');
const client = new Discord.Client();
const spawn = require('child_process').spawn;
const bitrate = 64;

client.on('message', message => {
	if (message.content.startsWith('++play')) {
		const voiceChannel = message.member.voiceChannel;
		if (!voiceChannel) return message.reply(`Please be in a voice channel first!`);
		voiceChannel.join()
		.then(connnection => { 
			const ffmpeg = spawn('ffmpeg', [
				'-i', 'test.mp3',
				'-vn',
				'-map', '0:a',
				'-acodec', 'libopus',
				'-f', 'data', // No container, clean output
				'-sample_fmt', 's16',
				'-vbr', 'off', // Disable variable bitrate
				'-ar', 48000, // Output sample rate
				'-ac', 2, // Output channels
				'-b:a', bitrate * 1000,  // Bitrate
				'pipe:1' // Output to stdout
			]);
			connnection.playOpusStream(ffmpeg.stdout, {bitrate: bitrate});
		});
	}
});

client.login('BOT_TOKEN');

```

**Comment by mmis1000** [comment]
I made the Pull request #1846 for this issue and VoiceBroadcast bitrate support not finished in #1439

**Comment by FireController1847** [comment]
Assuming this should be closed considering it was fixed via the Voice Rewrite?
