### ISSUE TITLE
Authenticate Failed

### ISSUE THREAD

**Issue by YinglunQ** [discordjs/discord.js#1914]
**Please describe the problem you are having in as much detail as possible:**
It seems like the authenticate failed error is happening again. (b5de89a)
```js
Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/andy/musicbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:256:27)
    at connectTimeout.client.setTimeout (/home/andy/musicbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:280:18)
    at Timeout.setTimeout (/home/andy/musicbot/node_modules/discord.js/src/client/Client.js:422:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.0.1
- Operating system: Linux

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by zfbTony** [comment]
I'm having this exact issues with 11.2.1 and the current master (d8f6198) 

```
{ Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (E:\Development\KuroyukihimeBot\node_modules\discord.js\src\client\voice\VoiceConnection.js:260:27)
    at connectTimeout.client.setTimeout (E:\Development\KuroyukihimeBot\node_modules\discord.js\src\client\voice\VoiceConnection.js:284:18)
    at Timeout.setTimeout (E:\Development\KuroyukihimeBot\node_modules\discord.js\src\client\BaseClient.js:70:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5) [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT' }
```

- Discord Version: 12.0.0-dev
- Node.js Version: v8.1.2
- OS: Windows 10 Pro

I've spent the last 24 hours thinking I made a mistake somewhere. Funny enough @iCrawl I was following your music bot tutorial on youtube when I ran into this.

**Comment by devsnek** [comment]
this error means you have bad internet

**Comment by OkitaSougoo** [comment]
I am not sure if "bad internet" is the only cause of the issue. I mean I have encountered the same error before while I was testing my bot locally (though I couldn't recall the exact combination of commands that I used). And my local PC has a ping of `9ms` @devsnek.

**Comment by zfbTony** [comment]
I'm fairly certain it's not my internet [Speedtest](http://beta.speedtest.net/result/6696240522)

**Comment by iCrawl** [comment]
A speed test does in no way indicate a stable connection.

**Comment by zfbTony** [comment]
Well I can use voice normally on my desktop through discord.. Is there another thing I can test? a port I should frisk?

**Comment by zfbTony** [comment]
So turns out I was having this problem because I had `'VOICE_STATE_UPDATE'` as one of my disabledEvents.. So for anyone else who has this problem.. check there first 😞 

*Didn't intend on my bot having voice functionality when i created it so I disabled that event. I find it a little silly that the bot would ignore it's own voice_state_update though?

**Comment by devsnek** [comment]
@zfbTony i think it would be sillier if we didn't disable events in the disabled events list

**Comment by zfbTony** [comment]
What about a check in voiceChannel.join() for the disabled event to log that as a reason for error? that doesn't seem all that silly, right?

**Comment by iCrawl** [comment]
>An array of disabled websocket events. Events in this array will not be processed, potentially resulting in performance improvements for larger bots. Only disable events you are 100% certain you don't need, as many are important, but not obviously so. The safest one to disable with the most impact is typically TYPING_START.

We pretty much already warn about it.

**Comment by OkitaSougoo** [comment]
I checked my disabled event and it doesn't contain anything. I will include the `TYPING_START` event into the disabled event as the comment suggested. Meanwhile, do you have others suggestions or tips which may help prevent the error? Thanks! @iCrawl

**Comment by hydrabolt** [comment]
I have fixed this in a recent commit, you should now only get this error if it genuinely does take too long to receive anything from Discord.

As this is also an old issue, I will close it.

**Comment by dustwolf** [comment]
For those who might end here via Google, searching for "Error: Connection not established within 15 seconds", I just wanted to save you some time by pointing out that it is possible to get this error if your voice room doesn't have the "View Channel" permission enabled for the bot.
