### ISSUE TITLE
Can't set channel position after setting parent

### ISSUE THREAD

**Issue by Sir-Will** [discordjs/discord.js#1965]
As categories are live now I updated my code to clone the channel into the correct category but since I added the setParent the setPosition is no longer working correctly. 
I set it to 1 while it prints out 3.
```js
voiceChannel.clone({name: 'Channel', withPermissions: true})
		.then(vc => vc.setParent(guildChannels.get(voiceChannel.parentID)))
		.then(vc => vc.setPosition(1)).then(vc => console.log(vc.rawPosition));
```

**Further details:**

- discord.js version: master
- node.js version: 8.2.1
- Operating system: Ubuntu

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: eb591dafbaf1f91a4df90c6001cb0ff343beda07

**Comment by Ev1dentFir3** [comment]
I was about to create the exact same ticket. I'm using Windows.

**Comment by KyeNormanGill** [comment]
I'm not sure if this has anything to do with it but on stable discord moving channels around manually is really buggy and they never go where i drag them. Could be a discord bug?

**Comment by Ev1dentFir3** [comment]
When ordering channels its best to load all of them into an array first and renumber them with a gap, I personally reorder them so positions are set to 2,4,6,8,ect. then every time a new channel is cloned I assign it to 3,5,7,9 ect. then I run the reorder script again basically now making 3 into 4 and 4 into 6 and so on. That fixes any confusion.

also Sir-will I was able to work around the missing promise by just using channel.edit(), you can assign both position and parent at the same time with it.

**Comment by Ev1dentFir3** [comment]
I'll also add that it would be nice to see a channel.clone() automatically clone the parent as well, or at least have another true/false added for it.

**Comment by Sir-Will** [comment]
@Ev1dentFir3 thanks, changed all my `setPosition` to `edit` and it now it works again.

**Comment by Ev1dentFir3** [comment]
Be careful because I also noticed that position is now the order inside the array of child channels, so if you start using more then 1 category for voice channels it breaks order again because the old `position` is now `rawPosition` and the current `position` only apply's to that categories's array of child channels.

**Comment by SpaceEEC** [comment]
Is this still an issue? Seems fixed to me
- `GuildChannel#clone` now respects the current parent
- `GuildChannel#setPosition` seems to work now.
0 sets to the highest, only counting channels inside the category
- `GuildChannel#rawPosition` is just what the discord api provides, we do not modify it on our behalf.
`GuildChannel#position` also prints out the expected result for me now.
