### ISSUE TITLE
SequentialHandler queue is blocked in busy mode: d.js@11.2.0-11.2.1

### ISSUE THREAD

**Issue by maxerbox** [discordjs/discord.js#2110]
### # **Please note:**
That issue is not related with the fixes done on the Sequential RequestHandler  #1949 , since it appears with no edits done to the Sequential.js file.
**It is only related to 11.2.0-11.2.1 release**. The RequestHandler got rewritten in the new release incoming.

### **Please describe the problem you are having in as much detail as possible:**

So I've noticed another problem with the requesthandler sequential queue. My bot isn't sharded and is supporting 1100 guilds, but when the thing comes overloaded, it's looking like there is a problem with the request queue. 

The queue got blocked in busy mode after some time (approximately 24hours).
![Image of Yaktocat](https://i.imgur.com/W0hhhFa.png)
That's a screenshot of a command that debug the current channel handler with the channel's message endpoint. As you can see, 3183 messages are blocked in the message queue and it is busy.

I'm looking for further details, but I'm pretty sure that it's related to Ratelimiting.
If I find a fix, I will post it in comments.

Regards, maxerbox.
**Further details:**

- discord.js version: 11.2.1
- node.js version: v6.11.3
- Operating system:  Linux 4.4.0-57-generic #78-Ubuntu GNU/Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by iCrawl** [comment]
Considering we have released 11.3.1 now can you retry this? @maxerbox
