### ISSUE TITLE
Give error message when IP is banned

### ISSUE THREAD

**Issue by demipixel** [discordjs/discord.js#2151]
If an IP is banned, an error is created however the [error variable](https://github.com/hydrabolt/discord.js/blob/master/src/rest/DiscordAPIError.js#L6) is a buffer (corrected with `error.toString()`). This returns an HTML page. Whether or not to parse the HTML for an error is another thing, but the current situation outputs `DiscordAPIError: undefined` which is unhelpful to the developer.

**Further details:**

Discord version 11.2.1

This issue seems to persist on the master branch.

**Comment by devsnek** [comment]
the errors come from cloudflare, we have no intention of parsing it

**Comment by demipixel** [comment]
Since `String.toString()` returns itself, would it hurt to slip an `.toString()` before the `.join('\n')`?

**Comment by Kashalls** [comment]
There might be a reason to why you were IP Banned.

**Comment by demipixel** [comment]
You're right, there might be. The mistake has since been resolved with Discord and it has been unbanned, however I still recommend this simple quality of life change.

**Comment by iCrawl** [comment]
Maybe, sooner or later down the line. Def not high priority if priority at all. Getting IP banned is an achievement in itself so testing this properly will not be easy.
