### ISSUE TITLE
Suggestion: Custom music clients

### ISSUE THREAD

**Issue by MrJacz** [discordjs/discord.js#2153]
Removed template due to this being a suggestion.

A way to have custom music clients, for example, Lavalink discord.js client because at the moment Client#voiceConnections is read-only meaning you have to make it another variable now I'm not sure if voiceConnections is used internally anywhere but some way to have External music clients would be nice

**Comment by victionn** [comment]
If you need it that bad, just assign it to somewhere else and use it there?

**Comment by MrJacz** [comment]
Not the point

**Comment by Dev-Yukine** [comment]
i mean since discord.js let you choose a custom Ratelimit handler, adding support for a custom voice player would be nice to have your own custom player to use stuff like lavalink etc.

**Comment by ZLima12** [comment]
You could always extend `Client` and add what you need there.

**Comment by Dev-Yukine** [comment]
@ZLima12 thats not what he means, he want a completly own implementation of the voice player used in d.js, or atleast a way of extending it properly.

**Comment by MrJacz** [comment]
@Dev-Yukine Said well, But @ZLima12 At the current moment there isn't a safe method of having our own Voice player considering it wouldn't be hard to add... Extending Client wouldn't actually work as Client#voiceConnections is a getter making it a read-only property so you actually cannot extend it

**Comment by iCrawl** [comment]
Sounds good.

**Comment by iCrawl** [comment]
This should not be needed anymore. Lots of people wanted to use Lavalink with this and because Lavalink handled all the WS it was rather bothersome to use with Discord.js.
With Lavalink v2 released this should not be an issue anymore.
