### ISSUE TITLE
Music Jumping

### ISSUE THREAD

**Issue by jonasjac** [discordjs/discord.js#2181]
**Please describe the problem you are having in as much detail as possible:**
When I pause my bots music and then wait a couple of minutes and then resume it the bot goes wild. It plays a second then skips like 5 and then it continues like that untill it discconnects.

**Include a reproducible code sample here, if possible:**
For the pause:
```js
        message.member.voiceChannel.connection.dispatcher.pause()
```
For the resume
```js
        message.member.voiceChannel.connection.dispatcher.resume()
```
**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 8.9.1
- Operating system: Windows 10 Server
- Priority this issue should have – please be realistic and elaborate if possible: Not top priority.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:
2318812f7f2229e0934a28967b406c4ef7f58073

**Comment by iCrawl** [comment]
We merged a voice rewrite since this issue was reported I believe, can you try again? @jonasjac 
Maybe also consider mentioning if you use node-opus or opusscript.

**Comment by jonasjac** [comment]
@iCrawl can't really use the new voice rewrite because it's super laggy. It's not even music anymore. Either way I'm using node-opus

**Comment by hydrabolt** [comment]
This issue seems to be inactive, if it is still occurring please reopen, but until we get some more details we can't really do anything with this.
