### ISSUE TITLE
Wrong promise thrown

### ISSUE THREAD

**Issue by JamieStivala** [discordjs/discord.js#2235]
**Please describe the problem you are having in as much detail as possible:**
It isn't necessary a problem but;

Let's say I'm using the bulk delete command so message.channel.bulkDelete.  If I try to remove more messages then there actually is the wrong promise is thrown:

UnhandledPromiseRejectionWarning: DiscordAPIError: You can only bulk delete messages that are under 14 days old.

**Include a reproducible code sample here, if possible:**
```js
message.channel.bulkDelete(100);
```
Re-explaining: If i try to delete a 100 messages but there are 50 messages in the specified channel the 14 day warning will be thrown. 

**Further details:**

- discord.js version: 11.2.1
- node.js version: 9.3.0
- Operating system: MacOS and Linux
- Priority this issue should have – please be realistic and elaborate if possible:
Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
Well like the name of the Error indicates this is an Error response discord.js gets from the Discord API so this is more of an DIscord API misleading error than a d.js bug

**Comment by devsnek** [comment]
i would imagine some of those 50 messages are older than 14 days. it just requests the last 100 messages from the api, which returns 50, then it asks all those ids to be deleted, to which discord says some of are older than 14 days.

**Comment by JamieStivala** [comment]
^ No it was inside a channel I 2 days ago to test beta features.  Once the less then the amount of messages or the exact is give the messages are deleted.

**Comment by Lewdcario** [comment]
Cannot reproduce on the same version with all of your claims, you certainly have an older message within.

**Comment by JamieStivala** [comment]
Ill try to reproduce on the latest version (this was 11.2)

**Comment by Lewdcario** [comment]
@JamieStivala, were you able to reproduce on `11.3`? If not, this will be closed.

**Comment by JamieStivala** [comment]
@Lewdcario I will be testing this when I get home tonight and if I'm able to reproduce I'm going to make a GIF and send it

**Comment by Lewdcario** [comment]
@JamieStivala And could you reproduce? If not, this will be closed.
