### ISSUE TITLE
HELP: message.replace

### ISSUE THREAD

**Issue by JellyProg** [discordjs/discord.js#2279]
Hi, i have this: 
client.on("message", (message) => {
	if (message.content.startsWith ('-lis ')) {
		var p1 = message.content.replace("-lis ", "")
		const embed = {
			"title": "<:Lis:404390869576450048> **Life Is Strange**",
			"color": 14396413,

			"fields": [
				{
					"name":  p1 + '´ information',
					"value": "[**Click here to open the character' profile**](http://pt-br.life-is-strange.wikia.com/wiki/" + p1 + ')',
					"inline": true
				}
			]
		}
		message.channel.send({embed});
	}
});
 It send's this: 
![image](https://user-images.githubusercontent.com/35117083/35188579-caccb280-fe2f-11e7-9a10-4a5cc1ed9cee.png)

I want the bot send all character's name but on link just the 1st name, like that: 
![image](https://user-images.githubusercontent.com/35117083/35188617-c7dd1cbc-fe30-11e7-9922-bcd960db6761.png)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
