### ISSUE TITLE
.send multiple messages?

### ISSUE THREAD

**Issue by NoobDoesMC** [discordjs/discord.js#2282]
I know I can `channel.send({ content: "here", ... })` to send one message, is there way, in a single `channel.send`, to send multiple messages?

**Comment by NoobDoesMC** [comment]
My goal: I'm storing messages in json files, I'd like a bot to send to a channel an embed headed with an image.

**Comment by Lewdcario** [comment]
This isn't really the place to ask lib questions. But with the `split` option you can. 
Also storing messages in JSON is a violation of the Discord ToS, so you may want to reconsider doing any of that.
Anyway, to conclude, you should go to our server for questions like this.
