### ISSUE TITLE
@everyone mentions doesn't work properly

### ISSUE THREAD

**Issue by flokol120** [discordjs/discord.js#2285]
**Please describe the problem you are having in as much detail as possible:**

If i try to send messages with @everyone mentions I get the following result: 

> @@everyone

It is also not highlighted like it should be. Am I doing something in the wrong way or is it a bug?

**Include a reproducible code sample here, if possible:**
```js
channel.send("<@&355726997126643732>! " + connectedUser.nickname + " just connected!")
```

**Further details:**

- discord.js version: 11.3.0
- node.js version: 8.9.4
- Operating system: Debian
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
You mention everyone or here with the literal strings `@everyone` or `@here`, not a regular role mention.
This is not a bug, but a discord thing.
