### ISSUE TITLE
Property 'on' does not exist on type 'ReadableStream'

### ISSUE THREAD

**Issue by dcbartlett** [discordjs/discord.js#2286]
**Please describe the problem you are having in as much detail as possible:**

I'm receiving the below error when trying to compile from typescript.

 error TS2339: Property 'on' does not exist on type 'ReadableStream'. 

**Include a reproducible code sample here, if possible:**
```typescript
  private record(caller: Discord.Message) {
    const conn = this.client.voiceConnections.first();
    
    const receiver = conn.createReceiver();
    conn.on("speaking", (user, speaking) => {
      if (speaking) {
        EventBus.emit("sendMessage", {caller: caller , msg: `I'm listening to ${user}`});
        // this creates a 16-bit signed PCM, stereo 48KHz PCM stream.
        const audioStream = <ReadableStream> receiver.createStream(user);
        // when the stream ends (the user stopped talking) tell the user
        audioStream.on("end", () => {
          EventBus.emit("sendMessage", {caller: caller , msg: `I'm no longer listening to ${user}`});
        });
      }
    });
  }
  
```

**Further details:**

- discord.js version: 12.0.0-dev (master)
- node.js version:  v8.5.0 
- Operating system:  Ubuntu 14.04
- Priority this issue should have: Stopping me from building, but its on a feature i can disable for now.

- [x] I found this issue while running code on a __bot account__
- [X] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
I pushed a commit which should fix a compilation error with `VoiceReceiver#createStream`, although I am not sure whether this was the cause of your issue.

If not, what exactly is your `ReadableStream` type?
