### ISSUE TITLE
Cannot react with :one:

### ISSUE THREAD

**Issue by xetrics** [discordjs/discord.js#2287]
messages are able to be reacted to with common emojis like 👌 , but I am not able to get emojis like :one: or :two: to work. 
```js
    message.channel.send(embed)
    .then((newMessage) => {
        newMessage.react("👌")
    })
```
Functions as intended, while:
```js
    message.channel.send(embed)
    .then((newMessage) => {
        newMessage.react("1️⃣")
    })
```
does not. Error:
```(node:21484) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Emoji```

- discord.js version: 11.3.0
- node.js version: 9.3.0
- Operating system: Windows 10 Build 1703

**Comment by gmedeadlystrike** [comment]
Discord does not support those Emojis - Try to paste them into discord directly, doesn't work

**Comment by xetrics** [comment]
Am i missing something? https://vgy.me/66lIFf.png

**Comment by vorion** [comment]
`var reaction_numbers = ["\u0030\u20E3","\u0031\u20E3","\u0032\u20E3","\u0033\u20E3","\u0034\u20E3","\u0035\u20E3",
                        "\u0036\u20E3","\u0037\u20E3","\u0038\u20E3","\u0039\u20E3"]`

This might be what you're looking for. Pass the int you need as an index, ezpz. I spent hours on this problem only to find out the unicode for the numbers. Hope this help!

**Comment by PaulchenHD** [comment]
I had the same problem a few weeks ago. Try to use `newMessage.react('1%E2%83%A3');`.
