### ISSUE TITLE
RESTMethods#createChannel typo causes channel creation overwrites to fail if using role IDs

### ISSUE THREAD

**Issue by Keswiik** [discordjs/discord.js#2291]
**Please describe the problem you are having in as much detail as possible:**
Currently, in stable, you cannot use channel creation overwrites with role IDs due to a typo in `RESTMethods#createChannel`.

```js
const role = this.client.resolver.resolveRole(this, overwrite.id);
```
should instead be
```js
const role = this.client.resolver.resolveRole(guild, overwrite.id);
```
**Include a reproducible code sample here, if possible:**
```js
guild.createChannel('test', 'text', [{
    id: guild.id,
    deny: ['VIEW_CHANNEL']
}]);
```
^ should fail to add overwrites
```js
guild.createChannel('test', 'text', [{
    id: guild.roles.get(guild.id),
    deny: ['VIEW_CHANNEL']
}]);
```
^ should add overwrites

**Further details:**

- discord.js version: 11.3.0
- node.js version: 8.4.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: medium - impact fairly common functionality

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
This has been resolved in the development branch.

**Comment by Keswiik** [comment]
RIP, didn't see that PR.
