### ISSUE TITLE
member.user or member returns mention but doesn't ping on guildMemberAdd event

### ISSUE THREAD

**Issue by iSayCodes** [discordjs/discord.js#2292]
So i am making a Discord Custom Welcome, and when it mentions, it doesn't ping

**My Code**
```js
	const farewellmsg = message.text.replace('%server%', member.guild.name).replace('%usertag%', member.user.tag).replace("%user%", `<@${member.user.id}>`).replace('%username%', member.user.username);

```

**Further details:**

- discord.js version: 11.3
- node.js version: 9.3
- Operating system: Windows 7 32 Bit

**Comment by KingDGrizzle** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.

**Comment by iSayCodes** [comment]
uhm, but i did, they said i should open an issue
