### ISSUE TITLE
Cannot verify if guild is unavailable

### ISSUE THREAD

**Issue by farcaller** [discordjs/discord.js#2296]
**Please describe the problem you are having in as much detail as possible:**

`guildDelete` doesn't provide the availability status of the guild.

**Include a reproducible code sample here, if possible:**
```js
client.on('guildDelete', guild => {
  if (guild.unavailable) {
    // no such property
  }
});

```

**Further details:**

Per [the api](https://discordapp.com/developers/docs/topics/gateway#guild-delete):

> Sent when a guild becomes unavailable during a guild outage, or when the user leaves or is removed from a guild. The inner payload is an unavailable guild object. If the unavailable field is not set, the user was removed from the guild.

Where the unavailable guild object is defined as:

> Example Unavailable Guild
> {
>     "id": "41771983423143937",
>     "unavailable": true
> }

However discord.js returns the Guild object and it's impossible to distinguish between "server became unavailable due to outage" vs. "the bot was kicked out".

- discord.js version: 11.3.0

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devdutchy** [comment]
If you'd have read the docs correctly, you can see that Guild doesn't have an `unavailable` property, but does have an `available` property: https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=available.

**Comment by farcaller** [comment]
Huh, my bad (in my defence I tried searching for "unavailable", as a keyword from the actual api docs, and found nothing).
