### ISSUE TITLE
Cannot read property 'send' of null

### ISSUE THREAD

**Issue by JellyProg** [discordjs/discord.js#2297]
i'm doing a suggesttion command, and I want to the bot send the message from users who are on other servers to a specific server (main server) and to a specific channel. When someone uses the command on the main server the bot sends the message to the specific channel but when the message is from another channel the bot gives error.

client.on("message", (message) => {
	if (message.content.startsWith ('-test')) {
message.guild.channels.find("id", "362638384612638727").sendMessage('test');
}
});

 http://prntscr.com/i6g1zk 
but, if i use the command in another server: http://prntscr.com/i6g3jk

Sorry if the things on print are in portuguese.

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
