### ISSUE TITLE
Error passing login token to json file

### ISSUE THREAD

**Issue by maxsixth** [discordjs/discord.js#2298]
Hello, could someone help me, I'm using HEROKU as host for my bot
I created a config.json where the token is, but when deploying an error appears and the bot does not start, here is the error:

> (node: 4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.
> 2018-01-27T23: 00: 04.026423 + 00: 00 app [worker.1]: (node: 4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

but by the HEROKU variable directly in the client.login () instead of the token json path, I do not have this error, can anyone help / explain what is happening?

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by maxsixth** [comment]
ok, sorry
