### ISSUE TITLE
RichEmbedBuilder constraints are too strict for emoji

### ISSUE THREAD

**Issue by CAC27** [discordjs/discord.js#2299]
*Embed titles, field names, field values etc. are restricted too much when containing emoji due to JavaScript's Unicode nonsense.*

The following code generates an error:

```js
message.channel.send( new Discord.RichEmbed().setTitle(`🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔`) )
```
 => `RangeError: RichEmbed titles may not exceed 256 characters.`

However, because Discord API doesn't consider `🤔` as 2 characters, the title is still valid, since it is 256 emoji. The same embed can be sent as an object without error:

```js
message.channel.send({ embed: { title: `🤔🤔🤔🤔🤔🤔...you get the point` }})
```

There are probably compatibility issues with doing so, but it seems to me you could replace all statements like:
`if (title.length > 256) throw new RangeError('EMBED_TITLE');`
with their equivalents of:
`if (Array.from(title).length > 256) throw new RangeError('EMBED_TITLE');`.

**Further details:**

- discord.js version: 11.2.1
- node.js version: 7.7.4
- Operating system: Windows 10
- Priority: low

**Comment by devsnek** [comment]
cc @Lewdcario we should just remove the checks on our side, they're kinda pointless since the api will catch them for us
