### ISSUE TITLE
Support for video embed object

### ISSUE THREAD

**Issue by Favna** [discordjs/discord.js#2305]
**Please describe the problem you are having in as much detail as possible:**

In the official Discord Developer Documentation it is listed that a [MessageEmbed](https://discordapp.com/developers/docs/resources/channel#embed-object) can have an [Embed Video Structure as seen here](https://discordapp.com/developers/docs/resources/channel#embed-object-embed-video-structure). Presumably this is what Discord uses to display playable videos when linking from sources such as YouTube or Streamable.

Currently this Embed Structure is not supported by DiscordJS, however it would be fantastic if it could be as this greatly enhances the capabilities that bot creators get when having their bots do actions such as YouTube searches or general video linking with extra info inside of the MessageEmbed.

As an example of the use case stated above I will use the following screenshot. This is the result from searching youtube. Currently the image is just an Image Structure of the video thumbnail but in a more ideal case it would be a Video Structure and actually be playable

![example](https://favna.s-ul.eu/IgmWH9uh.png)

**Include a reproducible code sample here, if possible:**
```js
message.channel.send({
    embed: {
        title: 'Awesome Title',
        description: 'Awesome description',
        video: {
            url: 'https://www.youtube.com/watch?v=3c6MWsEE884',
            height: 1080,
            width: 1920
        }
    }
});
```

**Further details:**

- discord.js version: master branch - commit hash 86da7af4f18abc295dccf7535b1ce8c1effd8b6e
- node.js version: 8.9.0
- Operating system: Windows 10 and Raspbian
- Priority this issue should have – please be realistic and elaborate if possible: low

Priority explanation: It would be a cool feature to get but has no real priority. Bot developers have done without for a very long time so I'm sure more time would hardly hurt.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
bots can only send rich embeds, this isn't a limitation of discord.js

**Comment by Lewdcario** [comment]
Your issue belongs with the Discord API, not Discord.js. Including 'clickable' video links is not something you can do- these are read-only properties, so I suggest you take it up to Discord issues.
