### ISSUE TITLE
message.edits / message.editedTimestamp aren't handled properly with image links

### ISSUE THREAD

**Issue by joe27g** [discordjs/discord.js#2307]
When a message contains an image link and the embedded image is loaded, it broadcasts a `messageUpdate`. It seems there are no internal checks for this, thus `message.edits` contains duplicate strings even when `edited_timestamp` (from the API itself) is null.

It would be convenient if discord.js would check whether the message was actually updated according to the timestamp (i.e. `oldMessage.edited_timestamp == newMessage.edited_timestamp`) before pushing to `message.edits`.

Also, `message.editedTimestamp` becomes NaN in this situation (both for posting an image link and editing a message to use a new image link), which I assume is unintended.

![image](https://user-images.githubusercontent.com/20873239/35497273-191e39bc-048f-11e8-876a-c7d88e785832.png)
Above is some quick testing, logging the `messageUpdate` event. (I posted an image link, then edited it to a different image.) The final `edited_timestamp` according to the API was `1517208473489`.

P.S. I don't know if `messageUpdate` is really supposed to fire in this situation... It apparently only fires when the image (or Discord's proxy URL or whatever) is not cached.

**Further details:**

- discord.js version: 11.2.1 / 11.3
- node.js version: 7.7.4

**Comment by SpaceEEC** [comment]
As of 3ba26ad972a315b9c4d6bfdd3a5c3607fb5528c0 the editedTimestamp property will no longer be modified when it's not in the payload.

I don't think not emitting a messageUpdate event would be expected however.
There is an embed update happening after all.
