### ISSUE TITLE
<StreamDispatcher>.time is undefined all the time in v12.0-dev

### ISSUE THREAD

**Issue by CheesyZaem** [discordjs/discord.js#2310]
**Please describe the problem you are having in as much detail as possible:**
`<StreamDispatcher>.time` seems to be undefined all the time, but `<StreamDispatcher>.totalStreamTime` works perfectly.

**Include a reproducible code sample here, if possible:**
```js
<StreamDispatcher>.time
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 8.9.4
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
Can't reproduce on node 8.6.x with example code.

**Comment by CheesyZaem** [comment]
My bad, gave the wrong version

**Comment by Lewdcario** [comment]
A quick check through https://discord.js.org/#/docs/main/master/class/StreamDispatcher reveals that the property has changed to `streamTime`.
