### ISSUE TITLE
Bot crashes when I'm trying to play music from YouTube

### ISSUE THREAD

**Issue by Oocrop** [discordjs/discord.js#2311]
I'm using discord.js v. 11.3.0 and node-opus v. 0.2.7 and Ubuntu 16.04 from MS Store.
The problem is here:
```js
var stream = ytdl(link, { filter : 'audioonly' });
var dispatcher = connection.playStream(stream);
```
Also, it doesn't output an error, even with `dispatcher.on('error', console.error)`.
I tried it with opusscript, but nothing changed.
Thanks in advance.

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
