### ISSUE TITLE
How to list Friends

### ISSUE THREAD

**Issue by Wreeper** [discordjs/discord.js#2316]
How to list Friends with Discord.js in a non-bot account?
I'm new to this domain.

**Comment by EllenFawkes** [comment]
Hi,

in docs is property `friends` in class `ClientUser`

https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=friends

```javascript
console.log(client.user.friends)
```

**Comment by kyranet** [comment]
That's reserved for user accounts, not bots.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by ankitshubham97** [comment]
> Hi,
> 
> in docs is property `friends` in class `ClientUser`
> 
> https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=friends
> 
> ```js
> console.log(client.user.friends)
> ```

This is no longer available in v12. How can we list the friends now in v12?

**Comment by almostSouji** [comment]
Bots cannot have friends and applications running on a user token (which would have friends) are against Discord terms of service and not supported by discord.js

Please do not necro-post on closed issues, if there are no new circumstances that warrant re-opening.
