### ISSUE TITLE
Playing music/videos via ytdl broken

### ISSUE THREAD

**Issue by SyndicateDiscord** [discordjs/discord.js#2318]
Running this code (it's from your website) does not play the music on our bot. There are no errors displayed, and the bot sits idly in the voice channel playing nothing. I don't know if this is a known bug or a new one, but can someone try to find a way to fix this?

```js
const ytdl = require('ytdl-core');
const streamOptions = { seek: 0, volume: 1 };
voiceChannel.join()
  .then(connection => {
    const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', { filter : 'audioonly' });
    const dispatcher = connection.playStream(stream, streamOptions);
  })
  .catch(console.error);
```

**Further details:**

- discord.js version: 11.3.0
- node.js version: 8.9.3
- Operating system: Windows 10 64-bit

**Comment by Bacon1153** [comment]
Can reproduce

**Comment by iCrawl** [comment]
Opussscript or node-opus?
ffmpeg version?

**Comment by Dev-Yukine** [comment]
you should have asked on our [Discord Server](https://discord.gg/bRCvFy9) since there are some common issues with difference sources like a new [npm bug](https://github.com/npm/npm/issues/19394) or issue with dependencies. so please instead asking here move to our discord server for support.
