### ISSUE TITLE
discord api server invite link expired

### ISSUE THREAD

**Issue by jlsjonas** [discordjs/discord.js#2322]
https://www.npmjs.com/package/discord.js#links
[Discord API server](https://discord.gg/rV4BwdK) is invalid

**Comment by SpaceEEC** [comment]
The invite code has been updated with 
11.3-dev: https://github.com/discordjs/discord.js/commit/6e10d258b6773935020a24738135b08d2272d44e#diff-04c6e90faac2675aa89e2176d2eec7d8R71
master: https://github.com/discordjs/discord.js/commit/50ad66f5139b52bf057de0d2745d7ae73e4fa8f8#diff-04c6e90faac2675aa89e2176d2eec7d8R73
and will be reflected there with the next release.
