### ISSUE TITLE
Shards stops from loading when one shard is taking too long to be ready

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2323]
**Please describe the problem you are having in as much detail as possible:**
When starting shards with the sharding manager, if one of the shard is taking too long to be ready, all the next shards won't start.

**Include a reproducible code sample here, if possible:**
```js
const { ShardingManager } = require('discord.js');
const Manager = new ShardingManager('./file.js', {
    totalShards: "auto"
});
Manager.spawn(this.totalShards, 15000);
```

```js
Error [SHARDING_READY_TIMEOUT]: Shard x's Client took too long to become ready.
// Become ready after few seconds, other shards not starting.
```

**Further details:**

- discord.js version: master
- node.js version: 9.4.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by MrJacz** [comment]
When using `"auto"` you need to pass your token so it can fetch recommended shard count

**Comment by Koyamie** [comment]
I pass it, just removed it from the example code.

**Comment by FireController1847** [comment]
Is this not intentional? From the way it's coded and my new PR (Internal Sharding) is coded, it's coded to end when a shard fails to connect.

**Comment by Koyamie** [comment]
I hope no, since the shard is being ready like few seconds after the timeout event, so the others should start after him

**Comment by Deivu** [comment]
```js
const { ShardingManager } = require('discord.js');
const config = require("./botconfig.json");
const manager = new ShardingManager('./corekashima.js', { token: config.token });
console.log("| |/ /__ _ __| |_ (_)_ __  __ _\n| ' </ _` (_-< ' \\| | '  \\/ _` |\n|_|\\_\\__,_/__/_||_|_|_|_|_\\__,_|\n");
const shards = 20;
manager.spawn(shards, 15000, false);
```
This could battle this issue for now. Just supply a reasonable timeout in between spawning the shards, the option on the middle, then put false on waitForReady.

**Comment by Deivu** [comment]
I'm not sure about how to fix this issue other than getting a higher timeout before rejecting the promise like from 30 seconds to 1 minute.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
