### ISSUE TITLE
“Error: FFMPEG not found”: Error with simple Discord Bot

### ISSUE THREAD

**Issue by cherob** [discordjs/discord.js#2326]
I'm using Windows (64-bit) with Node.js and npm installed.
In my project file, I have run the following commands:

```
    npm init
    npm install discord.js --save
    npm install ffmpeg --save
```

Now i just created the code for a basic bot [here ](https://hastebin.com/qarijerara.js)is the main code.
I list here the important:

```
     if (message.content === '!play' && message.member.roles.has(message.guild.roles.find("name", config.role_name).id)) {
        if (!message.member.voiceChannel) return log("?");
           message.member.voiceChannel.join().then(function (connection){      
           });
     }

```
Then, in Discord, I say the following:

```
     [1517932146]  Musik bot loaded
        (node:35760) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: FFMPEG not found
```

I have already tested the following:

- reinstallation of everything
- others of the require names e.t.z.
- simplify the code

So if you have any ideas then let me know. Thank you

  [1]: https://hastebin.com/qarijerara.js

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
