### ISSUE TITLE
v12 NPM Package.json - incorrect version of uws

### ISSUE THREAD

**Issue by davemaltby** [discordjs/discord.js#2327]
**Please describe the problem you are having in as much detail as possible:**
After you install the hydrabolt/discord.js package you are unable to install uws failing with errorcode 1.
This is because the package.json has the uws version listed as 8.14.0 instead of 9.14.0

Easily self fixed by editing package.json

**Further details:**

- discord.js version: 12
- node.js version: 9.4.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by appellation** [comment]
This isn't necessarily a problem with our package.json; it simply means that you should only install version 8 of uws.

**Comment by davemaltby** [comment]
Whilst I'd agree, what would be the reason for discord.js v11.3 using 9.14.0 of uws and v12 using 8.14.0 of uws?
Also the documentation for v12 under optional packages doesn't specify you need a lower version of uws, it just says "npm install uws --save" which would signify the latest version.

This simply looks like a typo to me where someones typed 8 instead of 9 in the package.json

**Comment by iCrawl** [comment]
Because you don't *need* a lower one.
