### ISSUE TITLE
VoiceConnection.speaking returns true after the dispatcher fires finished

### ISSUE THREAD

**Issue by Protected** [discordjs/discord.js#2331]
In the latest master (66c0512de2a3bda5e3ae5f9443425a242987abd5),

I'm playing an mp3 file using VoiceConnection.play and then assigning an event handler to the finished event, which I was told on the discord replaces the end event for this version.

The file plays properly and the event fires successfully, but VoiceConnection.speaking doesn't switch back to false. If the stream is manually ended using dispatcher.end(), VoiceConnection.speaking also doesn't switch back to false.

Also, the VoiceConnection speaking event's callback's first argument being passed is 'true'. I'm led to expect from the master documentation that it should be a user. The event is not firing at all when the dispatcher ends (probably related).

node.js 8.9.1
OS Debian 9 (Stretch)
I'm using node-opus.
Priority: It's in master, so it's not an urgent fix for most users. It should probably definitely be fixed before the voice rewrite goes stable (and hopefully, soon!) I looked into the source code and unfortunately the level seems too high for me to fix it myself.

**Comment by hydrabolt** [comment]
Thanks for bringing this up, fixed as far as I can tell! If it's not then please reopen this issue :smile:
