### ISSUE TITLE
Music Bot problem

### ISSUE THREAD

**Issue by RealKeenGamesYT** [discordjs/discord.js#2333]
I use the play command but when it joins the voice channel it leaves after 2 seconds. It then logs 'undefined' without any errors.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
