### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by FHGDev** [discordjs/discord.js#2334]
# Heyo, I'm having some issues with my bot... 
So, I start my bot, and then it runs smoothly for a while, and then I get an error saying: "Socket Hangup"...
Can I get an answer for this, and how to fix it if possible? Thanks.

**Comment by bdistin** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by FHGDev** [comment]
Welp... This is a bug report.

**Comment by Dev-Yukine** [comment]
well this Error can have different causes and since we dont know if this is even caused by d.js or your own code you should most likely ask in our Discord Server (since you already deleted that template anyway and didn't showed any code that causes that)

**Comment by FHGDev** [comment]
Well you can review my code here: https://github.com/FHGDev/JSHulkbot
