### ISSUE TITLE
client events "messageDelete" and "messageDeleteBulk" do not work

### ISSUE THREAD

**Issue by AmirBeraha** [discordjs/discord.js#2343]
When i try to use one of the events messageDelete or messageDeleteBulk, they do not work, do not even show console.log on the first line inside them

**Include a reproducible code sample here, if possible:**
```js
client.on("messageDelete", msg => { 
    console.log("message deleted");
    msg.guild.channels.find("name","server-logs").send("Message delete test");
    if(msg.channel.name === "daily-advertisement") {
      msg.channel.overwritePermissions(msg.author.id, {"SEND_MESSAGES":true});
    }
});
```

**Further details:** i tried other events like typingStart and it worked perfectly, only these 2 events does not work.

- discord.js version: 11.3.0
- node.js version: 8.x
- Operating system: it's not locally and i'm not the only one with this issue but on the same code
- Priority this issue should have – please be realistic and elaborate if possible: on of the first priorities, since it's an event that doesn't work and can cause a whole block of codes to stop work if it happens to others.

- [x] I found this issue while running code on a **bot** account
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by KingDGrizzle** [comment]
Did you, by chance:
1. Disable the event in the client constructor?
2. Delete a message after restarting the bot? (Meaning the message wasn't cached so the event would never trigger)
