### ISSUE TITLE
forceFetchUsers not working

### ISSUE THREAD

**Issue by Daijobou** [discordjs/discord.js#2347]
**Please describe the problem you are having in as much detail as possible:**

I want make a statistics/history of users on server. So I need data of **all** users on server, but message.guild.members returns only a small part of users. So I read that here is a function to force all users (see https://github.com/discordjs/discord.js/issues/246#issuecomment-205339098) called forceFetchUsers() (I need this function only very rare)

**Include a reproducible code sample here, if possible:**

```js
if (command=='showstats')
{
    bot.forceFetchUsers().then(function()
    {
        var stats = { online: 0, offline: 0, idle: 0, dnd: 0 };
        message.guild.members.forEach(function(member)
        {
            let status = member.user.presence.status;
            if (stats.hasOwnProperty(status))
            {
                stats[status]++;
            }
        });
        message.channel.send('ShowStats - Overall='+message.guild.memberCount+' (Online='+stats.online+', Idle='+stats.idle+', DnD='+stats.dnd+', Offline='+stats.offline+')');
    }).catch(function(error) {
        logger.info('Error: '+error);
    });
}
```
Results in

> TypeError: bot.forceFetchUsers is not a function

Without bot.forceFetchUsers() the code working fine, but with missing many users.

Note: 
`var bot = new Discord.Client({forceFetchUsers: true});`
Not working for me too.

**Further details:**

- discord.js version: 11.3.0
- node.js version: 7.4.0
- Operating system: centOS 7

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

How I can get all users and what is the condition to be a user in message.guild.members?

**Comment by kyranet** [comment]
This option is incredibly old, from pre Discord.js v9, please read the documentation and don't necro old issues from stable/ancient versions of this library, it's not supported.

Also don't check StackOverflow or any other website for doubts. **If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Daijobou** [comment]
Ah, that the reason I found nothing in the documentation. :)

I search in the docu again and with luck I found https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchMembers as solution.
