### ISSUE TITLE
ERR_UNHANDLED_ERROR

### ISSUE THREAD

**Issue by JerryLDev** [discordjs/discord.js#2350]
**Please describe the problem you are having in as much detail as possible:**

Every once in a while (like every 2 or 3 days) my bot disconnect by itself and doesnt auto reconnect.

Nodejs call stack:

events.js:143
      throw err;
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:141:19)
    at WebSocketConnection.onError (/home/wut/LouisBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:371:17)
    at WebSocket.onError (/home/wut/LouisBot/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:160:13)
    at WebSocket.finalize (/home/wut/LouisBot/node_modules/ws/lib/websocket.js:190:41)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Include a reproducible code sample here, if possible:**
```js
const discord = require('discord.js');
const bot = new discord.Client({autoReconnect:true});

const prefix = '$'

bot.login('********** [hidden]');

bot.on("ready", function() {
    console.log(`Ready as: ${bot.user.tag}`);
    var dateNow = new Date();
    console.log('Current date: ' + dateNow);
    bot.user.setActivity('With his bot dick');
});

I have a few bot.on('message' function also but it doesnt happen on that event.. it happens on nothing actually.. it just.. dies randomly.

```

**Further details:**

- discord.js version: Discord.js 11.3.0
- node.js version: NodeJS 9.5.0
- Operating system:  I run it on Debian but used to run it on Windows and the same exact error was happenning every few days.
- Priority this issue should have – please be realistic and elaborate if possible: This is really irritating because I have to manually restart my bot every few days.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
You should handle the error event like:
```js
bot.on('error', err => {
  // handle error somehow
});
```

and you should only have **one** `bot.on('message'` and not more. Maybe 2 if you really know what you are doing.

**Comment by JerryLDev** [comment]
Thank you iCrawl. Yes I didnt say it correctly I only have on bot.on('message').. I have a case inside of it for different functions.
