### ISSUE TITLE
client.joinServer is not a function

### ISSUE THREAD

**Issue by KinanSy** [discordjs/discord.js#2353]
Hello, I'm trying to make my bot join a server by a Invite string. Ex : "Gpq4P5"
**I executed this code:**
```js
client.JoinServer("codehere");
```
It returned to me in the console : client.joinServer is not a function
need help

**Comment by iCrawl** [comment]
Automating a user account is against the ToS.

If it is not a user bot (also called selfbots), bots cannot join servers via a function.

**Comment by hydrabolt** [comment]
This is probably due to reading outdated documentation (see https://discordjs.readthedocs.io/en/latest/docs_client.html#joinserver-invite-callback)

I'm also going to reference https://github.com/rtfd/readthedocs.org/issues/3208 in hopes that the issue isn't forgotten.
