### ISSUE TITLE
Pm the owner

### ISSUE THREAD

**Issue by Jathur95** [discordjs/discord.js#2356]
So when a user run a command. The bot send a pm to a specific user

My code is :
      let Owneruser = client.users.get('name', 'User#2456')
      message.Owneruser.send(`hello ! from <@${message.author.id}>`)

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
