### ISSUE TITLE
Error when sending fetchProp response to master process: Failed to send message to master process.

### ISSUE THREAD

**Issue by Ishidres** [discordjs/discord.js#2357]
**Please describe the problem you are having in as much detail as possible:**
I am trying to "sync" a specific variable to any other shard, so every shard shares the same value of the variable.
To do so I'm using `fetchClientValues` in `broadcastEval`, so all the other shards fetch the values I want to sync. 

**Include a reproducible code sample here, if possible:**
```js
// run.js
const { ShardingManager } = require('discord.js');
const config = require("./config.json");
const manager = new ShardingManager('./index.js', { token: config.token });

manager.on('launch', shard => console.log("Successfully launched shard " + shard.id));

manager.spawn(2, 50).then(() => {
    console.log("Launched " + manager.totalShards + " shards...");
}).catch((err) => {
    console.log(err);
});
```
```js
// index.js
// trying to sync the variable below:
var myVar = 0;
client.myVar = myVar;
client.shard.broadcastEval( "this.shard.fetchClientValues('myVar').then( (results) => { console.log(results) } ).catch(console.error)" );
```
Unfortunately I'm getting this error:
```
unhandledRejection:
Error: Error when sending fetchProp response to master process: Failed to send message to master process.
    at Promise (/home/myBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:43:24)
    at new Promise (<anonymous>)
    at ShardClientUtil.send (/home/myBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:39:12)
    at ShardClientUtil._respond (/home/myBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:123:10)
    at ShardClientUtil._handleMessage (/home/myBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:106:12)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Further details:**
- discord.js version: **11.3.0**
- node.js version: **v8.9.3**
- Operating system: **Raspbian GNU/Linux 8 \n \l**
- Priority this issue should have – please be realistic and elaborate if possible: **Low/Medium**

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

I know, this seems like an issue, which should have been asked and solved on the Discord.JS server.
Anyway, I did so two times and didn't get any answer. Also, I searched for the error message on the server, but only a few people asked about this before and couldn't solve their issue, too.

**Comment by Lewdcario** [comment]
I quite literally copy pasted your code in production and testing (testing on latest master), and was unable to reproduce. Perhaps the issue lies specifically in the actual variable you are dealing with (incorrectly)?
