### ISSUE TITLE
Client.users.size not showing correct number

### ISSUE THREAD

**Issue by motasim1** [discordjs/discord.js#2367]
**Please describe the problem you are having in as much detail as possible:**
Ok, so, I get 1560 outputted when i log `<Client>.users.size`, however tho, it should be something above 7k users.
**Include a reproducible code sample here, if possible:**
```js
console.log(`serving ${bot.users.size} users on ${bot.guilds.size} servers.`)
```

**Comment by iCrawl** [comment]
Without the client option `fetchAllMembers` you will not automatically cache all users in all guilds. Your cache will gradually fill up over time.

**Comment by NeXiGaming** [comment]
:+1:
