### ISSUE TITLE
Undocumnted: User mentions are different for people with a displayName set

### ISSUE THREAD

**Issue by oedze** [discordjs/discord.js#2368]
**Please describe the problem you are having in as much detail as possible:**

The regular expression for USER_PATTERNS works for both member with or without a displayName. the users with a displayname have the pattern <@!id> and the users without a displayname have the pattern <@id> this isn't a problem, but it is not documented [here](https://discord.js.org/#/docs/main/stable/class/MessageMentions?scrollTo=s-USERS_PATTERN)
In my case the .substring(2, 20) didn't work properly giving me weird user id's. 
 
**Include a reproducible code sample here, if possible:**
```js
var string = "<@!123456789123456789>"; 
if(string.match(USER_PATTERN)){
	userID = value.substring(2,20);
	if(message.guild.members.find("id",userID)){
		return userID;
	}else{
		return false;
	}
}
```

**Further details:**

- discord.js version: 11.3.0
- node.js version: 8.9.4
- Operating system: Rasbian 
- Priority this issue should have – please be realistic and elaborate if possibl

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by appellation** [comment]
The documentation shows an example: `like <@81440962496172032>`.  As a developer, it's expected that you understand how a Discord mention is formatted without relying on documentation for a utility property.

**Comment by oedze** [comment]
I agree wit the 'like' but i think all the mention types should be listed somewhere, testing everything would be an option, but kind of wastefull.

**Comment by PassTheMayo** [comment]
You shouldn't rely on the Discord.js docs to tell you everything. Plus this is already documented in the Discord developer docs: https://discordapp.com/developers/docs/reference#message-formatting.
