### ISSUE TITLE
i have an issuie with my Discord.js Bot

### ISSUE THREAD

**Issue by HunterWilson56** [discordjs/discord.js#2372]
So I made a bot and I'm on  line 100 and I got this message

(node:66324) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

Could someone help me?

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
