### ISSUE TITLE
playFile from text file not working

### ISSUE THREAD

**Issue by Valenz68** [discordjs/discord.js#2374]
Hello ! 
I'm trying to read a path in a textfile to play a song but it's not working...
What I have : 
Selfmade Browser that is writing a path to a textfile : 
![image](https://user-images.githubusercontent.com/36960333/36934630-0a57358c-1eed-11e8-83a9-ff57d6c31558.png)

When button is clicked a textfile is created (or content from this textfile is replaced by the path of my selected song)
![image](https://user-images.githubusercontent.com/36960333/36934639-32244e2e-1eed-11e8-867b-785f74512b42.png)

This textfile contains something like this : 
![image](https://user-images.githubusercontent.com/36960333/36934645-493a38b2-1eed-11e8-8812-6560b55925bd.png)

So in my discord bot I did :

![image](https://user-images.githubusercontent.com/36960333/36934657-777cfe94-1eed-11e8-8b91-9db060cc6fc7.png)

It seems like "connection.playFile(chemin)" isn't working because when I write the path instead of my variable "chemin" it works fine like "connection.playFile('D:/Musique/Hardtek/1.mp3')"
Can someone help me fix this please ?

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by Valenz68** [comment]
Ok i'll try there thanks !
