### ISSUE TITLE
how to create countdown

### ISSUE THREAD

**Issue by slehlou** [discordjs/discord.js#2375]
Hello,
I'm trying to create a bot using discord.js that can display a countdown in bot.setGame
Can someone help me do that please?

Thanks.

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
