### ISSUE TITLE
[NPM] Missing Typings

### ISSUE THREAD

**Issue by RumbleFrog** [discordjs/discord.js#2376]
**Please describe the problem you are having in as much detail as possible:**

When adding the Discord.JS dependency, I was not able to pull the typings from package; this seems to occur after **v11.3.1** release, which was mere 4 hours ago of writing this issue.

**Include a reproducible code sample here, if possible:**
```js
yarn add discord.js

```

Also reproducible with npm

**Further details:**

- discord.js version: 11.3.1
- node.js version: 9.5.0
- Operating system: Windows 10 Build 17074.1002
- Yarn version: 1.5.1
- NPM version: 5.6.0
- Priority this issue should have – please be realistic and elaborate if possible: High, affects everyone using typescript

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment]
Seems to be related to [yarnpkg/yarn #1488](https://github.com/yarnpkg/yarn/issues/1488).

**Comment by RumbleFrog** [comment]
Some update:

- I was able to pull typings when I roll back to 11.3.0
- When manually cloning the repo, typings are not complete, which I think is the reason why it's not included with 11.3.1

**Comment by iCrawl** [comment]
- Yarn does not recursively pull/update git modules
- Manual cloning also does not recursively pull/update git modules

**Comment by RumbleFrog** [comment]
What would be the reason behind it working for 11.3.0 and not 11.3.1?

For manual cloning I used `--recurse-submodules`

**Comment by iCrawl** [comment]
Master Branch:
![image](https://user-images.githubusercontent.com/20760160/36941990-c6789406-1f68-11e8-9ef3-18368a6982f0.png)

11.3-dev Branch:
![image](https://user-images.githubusercontent.com/20760160/36941997-f766b6e2-1f68-11e8-9705-dfe24be2238f.png)

Stable Branch:
![image](https://user-images.githubusercontent.com/20760160/36942002-1cb3afc2-1f69-11e8-81ed-096ed934c55b.png)

You are indeed correct that 11.3.1 does not ship with the typings on npm though.

**Comment by RumbleFrog** [comment]
Any estimate on when will it be shipped?

**Comment by iCrawl** [comment]
Shouldn't take too long, but in the meantime you can just install the typings manually via:

`npm i discordjs/discord.js-typings#11.3 --dev`
or
`yarn add -D discordjs/discord.js-typings#11.3`
