### ISSUE TITLE
Bot silently disconnecting on 11.3.1 after ~40 minutes

### ISSUE THREAD

**Issue by Dmitry221060** [discordjs/discord.js#2378]
**Please describe the problem you are having in as much detail as possible:**
Every ~40 minutes after startup, my bot is disconnecting. Without reporting an error, and without removing the handlers. 
In 11.3.0 this problem is not present.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.login('token').then(success);
    
function success() {
    console.log('logged in');
}

setInterval(()=>{console.log(client.status)},60000).unref();
 
client.on('reconnecting', () => {
    console.log('reconnecting'); //[1]
});
```
[1] - After this is called, `console.log(client.status)` will always output "1", and the handlers will not be removed => the script does not restart.

**Further details:**

- discord.js version: 11.3.1
- node.js version: v6.11.2
- Operating system: windows
- Priority this issue should have – please be realistic and elaborate if possible: hight

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by MindBunny** [comment]
I got the same issue, tought i was my vps guess not. I was going to reinstall my hole vps

**Comment by MindBunny** [comment]
Bot just goes offline after 1 hour or so

**Comment by SpaceEEC** [comment]
This should have been fixed with https://github.com/discordjs/discord.js/commit/c8f78b2bf087526ee927e0f00294cd4d8969b7a5, for now install the 11.3-dev branch from github

**Comment by TheUncannyScrub** [comment]
This is freaky, I had the same issue. 33 minutes on the dot.
