### ISSUE TITLE
voiceSessionID is undefined after changing the server region

### ISSUE THREAD

**Issue by JakeGrey** [discordjs/discord.js#2380]
**Please describe the problem you are having in as much detail as possible:**
The client's guild member voiceSessionID is undefined after changing the server region.
Steps to reproduce:
1. Join a voice channel
2. Change the server region
3. voiceSessionID is now `undefined`

**Include a reproducible code sample here, if possible:**
```js
voiceChannel.join();
console.log(client.guilds.get('...').me.voiceSessionID); // normal
// change the server region
console.log(client.guilds.get('...').me.voiceSessionID); // undefined
```

**Further details:**

- discord.js version: master (12.0.0-dev)
- node.js version: 9

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 8b67991

**Comment by hydrabolt** [comment]
Discord.js doesn't yet account for voice regions changing, it will be added soon though.

**Comment by Bacon1153** [comment]
Cannot reproduce this on 11.3.0. No matter how I change the regions it always returns the same voice session ID.

**Comment by hydrabolt** [comment]
Fixed, looks like Discord.js reset the `voiceStates` collection after changing the server region, however there was no new data so it was never filled in again.
