### ISSUE TITLE
RoleStore not updating correctly when Missing Permissions

### ISSUE THREAD

**Issue by JakeGrey** [discordjs/discord.js#2381]
**Please describe the problem you are having in as much detail as possible:**
When attempting to add a role to a member when the bot doesn't have permission still adds the role to the `member.roles` collection.
Steps to reproduce:
1. Remove the manage roles permission from the bot, or move the role you're adding higher than the bots.
2. Attempt to add the role to the member
3. Map the `member.roles` collection

**Include a reproducible code sample here, if possible:**
```js
// remove manage roles permission from the bot
// add the role to the member
GuildMember.roles.add(Role);
// have a look at the roles the bot thinks the member has
console.log(GuildMember.roles.map(role => role.name));
```

**Further details:**

- discord.js version: master (12.0.0-dev)
- node.js version: 9

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 8b67991

**Comment by kyranet** [comment]
[`GuildMemberRoleStore#add();`](https://discord.js.org/#/docs/main/master/class/GuildMemberRoleStore?scrollTo=add) returns `Promise<GuildMember>`, and the roles aren't updated after successful run (with no errors) from the API. Try awaiting it:

```javascript
(async () => {
	// remove manage roles permission from the bot
	// add the role to the member
	GuildMember.roles.add(Role);
	// have a look at the roles the bot thinks the member has
	console.log(GuildMember.roles.map(role => role.name));
})();
```

**Comment by JakeGrey** [comment]
Oh yeah, it was "awaited" as I also ran it in separate evals.
`GuildMemberRoleStore#add();` throws an error when missing permissions.
