### ISSUE TITLE
messageDeleteBulk event running twice

### ISSUE THREAD

**Issue by Terax235** [discordjs/discord.js#2382]
**Please describe the problem you are having in as much detail as possible:**
The "messageDeleteBulk" event is running twice if I bulk delete once.

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 9.7.1
- Operating system: debian
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by zjjpp** [comment]
there are no details
we cannot help you here.
provide more information
and maybe we can determine if this is a bug

**Comment by lloti** [comment]
#2036

**Comment by Dev-Yukine** [comment]
@Terax235 could you test this issue on master for us?

**Comment by Terax235** [comment]
@Dev-Yukine I just tested it on master, seems like it's working there. Thanks.

**Comment by russellg89** [comment]
Having the same issue:

bot.on("messageDeleteBulk", messages => {
    console.log("saw bulk delete")
}
if(command==="prune"){
    if(!args[0]){ message.delete();    } else{ let num=parseInt(args[0])+1; channel.bulkDelete(num); }
}

Result of one command:
![image](https://user-images.githubusercontent.com/20692895/38959934-85777774-4330-11e8-9f1b-c66faf60ffbf.png)

Versions:
discord.js 11.3.2
node.js 9.9.0 and tried 9.11.1
ubuntu 16.04.4

**Comment by SpaceEEC** [comment]
Fixed with 7c37a0d386c38bc07d9b0c23b69c287e6f1550c1.
