### ISSUE TITLE
Discord.js modules keep getting deleted

### ISSUE THREAD

**Issue by AyaxTheKappa** [discordjs/discord.js#2387]
**Please describe the problem you are having in as much detail as possible:**

After installing new modules through npm,the discord.js module keeps getting deleted and I have to redo npm install hydrabolt/discord.js every time
**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version:12.0
- node.js version:9.7.1
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:low
This issue slows everything down for me,it's not something really important since it would also probably be a problem client side

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devdutchy** [comment]
This is a bug related with npm, and is resolved with the v5.7.1 update for npm (this should be the relevant issue: https://github.com/npm/npm/issues/17379)

**Comment by SyntheticGenerations** [comment]
Try deleting your package-lock.json file then delete node-modules folder then try installing the modules again.

**Comment by AyaxTheKappa** [comment]
Now it tells me
`Error: Cannot find module 'C:\Users\Valerio\Desktop\Harmony\node_modules\sqlite3\lib\binding\node-v59-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Valerio\Desktop\Harmony\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)`

**Comment by Dev-Yukine** [comment]
As @devdutchy already stated this issue is not related to Discord.js its rather than a [npm issue](https://github.com/npm/npm/issues/17379) what got fixed in the recent release so you want to update npm. Since this is not related to discord.js i would please you to close this issue
