### ISSUE TITLE
Reaction count not updated properly after bot reacts to message

### ISSUE THREAD

**Issue by Beamanator** [discordjs/discord.js#2389]
https://github.com/discordjs/discord.js/blob/e5bd6ec150baee5ee4ca0830b80753b7c59f4844/src/structures/Message.js#L552

I found a potential issue when getting the count of a certain reaction emoji on a message (i'm not 100% sure what line the issue occurs at). At first I used this to log the count to the console, which is always accurate:

    message.channel.fetchMessage('421952287301435403')
    .then(msg => {
        let downVoteReaction = msg.reactions.filter(rx => rx.emoji.name == '👎');
        console.log(downVoteReaction.first().count);
    }).catch(console.error);

But then I decided I want one extra reaction to count, a reaction from my bot (I don't have multiple user accounts of Discord, so I just wanted to see the +1 extra emoji counted after adding a reaction with the bot) - so I did this:

    message.channel.fetchMessage('421952287301435403')
    .then(msg => {
        // have bot add reaction to specific message
        return msg.react('👎');
    })
    .then(rx => {
        let msg = rx.message;
        let downVoteReaction = msg.reactions.filter(rx => rx.emoji.name == '👎');
        console.log(downVoteReaction.first().count);
    }).catch(console.error);

At first run the count increased to 2, but after running the code more times, surprisingly and unexpectedly, the count now went up to 3 instead of staying at 2. Now each time I run that code I get the count as 3. Looking at the message in the discord channel, I see there are only 2 👎 reactions (1 from me as a user, 1 from my bot), so it seems that the `count` is not being updated properly.

I even added a 5 second `setTimeout` delay before `console.log`ing the count to see if the count was just being updated late, but I got the same result.

Is this expected behavior?

**Comment by SpaceEEC** [comment]
No, it's not.

The count was incorrectly incremented twice for the own user:
- Once when reacted locally
- And the other one when the gateway event fired

The linked commit, closing this issue, avoids doing that.
