### ISSUE TITLE
setActivity command

### ISSUE THREAD

**Issue by TritaxGamer** [discordjs/discord.js#2391]
I want my to set my bot's game(activity) by a setgame command how can i do that

**Comment by devdutchy** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the Discord server instead of opening an issue – you will get redirected there anyway.**

**Comment by BoltCodes** [comment]
<Client>.user.setActivity('GAME NAME');

**Comment by matdesu** [comment]
`client.on("ready", () => {
	console.log (`Bot Online`)
	client.user.setActivity("your activity")
});`

**Comment by ttakkku** [comment]
@matdesu  
```js
client.on("ready", () => { 
console.log (`Bot Online`) 
client.user.setActivity("your activity") 
});
```

**Comment by MGPlayzYT** [comment]
You mean by setting it by commands?
