### ISSUE TITLE
awaitReactions not working properly

### ISSUE THREAD

**Issue by Skuriles** [discordjs/discord.js#2392]
**Please describe the problem you are having in as much detail as possible:**
message awaitReactions does only works sometimes. 
Sometimes the console.log("got reaction"); is called once, sometimes nothing is done at all. After first successful call no other reaction is noticed by the bot anymore. 

**Include a reproducible code sample here, if possible:**
I've tried to do write a bot message, add three reaction emojis, then listen to the reactions clicked by the user. Background would be to add a role to a user if he clicks on a emoji.

``` message.channel.send("I don't want to run anymore").then((myMessage) => {
      myMessage.react("🤠");
      myMessage.react("☠");
      myMessage.react("🤖");
      const filter = (reaction, user) => reaction.emoji.name === "🤠";
      //const filter = (reaction, user) => ({});
      myMessage
        .awaitReactions(filter, { time: 100000 })
        .then((collected) => {
          console.log("got reaction");
        })
        .catch((collected) => {
          console.log("error reaction");
        });
    });

```

I managed to get this to work with:
`client.on("messageReactionAdd", (reaction, user) => {`
 
and check the reaction.message.id and then work with this data. Not the best and a little bit of workaround but it works.

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.9.3
- Operating system: Win 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Keswiik** [comment]
I don't think this is a bug, it looks as though he's incorrectly using `Message#awaitReactions`. The promise returned by this method will **only** be resolved once. Once this happens, the `ReactionCollector` used internally is destroyed and no further reactions will be collected.

If you're wanting something persistent, the cleanest way would be to listen to raw events as you would no longer rely on a) having a reaction collector active and b) having the message(s) cached.

In your snippet, @Skuriles, you're going to collect an unknown number of the '🤠' emoji, then resolve the promise after ~1m40s. Then you'll get nothing. I ran your snipped around 10 times just to make sure.

If you're wanting something more immediate, consider using `Message#createReactionCollector` like this:
```
const filter = (reaction, user) => reaction.emoji.name === "🤠";

let collector = message.createReactionCollector(filter, { time: 5000 });
collector.on('collect', (reaction, collector) => {
	console.log('got a reaction');
});
collector.on('end', collected => {
	console.log(`collected ${collected.size} reactions`);
});

message.react("🤠");
message.react("☠");
message.react("🤖");
```

You can refer to the [ReactionCollector](https://discord.js.org/#/docs/main/stable/class/ReactionCollector) and [ReactionCollectorOptions](https://discord.js.org/#/docs/main/stable/typedef/ReactionCollectorOptions) docs for information about what options and events are available.

For some short examples on using raw events, read this [gist](https://gist.github.com/Danktuary/27b3cef7ef6c42e2d3f5aff4779db8ba) or refer to this [section](https://discordjs.guide/#/popular-topics/reactions?id=listening-for-reactions-on-old-messages) of the Discord.js starter guide.

There _could_ be something weird going on here, as you say you were using a user account, but I have no intention of testing on one as well. You should consider using a proper bot account for further testing / development using Discord.js.
