### ISSUE TITLE
SyntaxError on Ubuntu

### ISSUE THREAD

**Issue by Short-Circuit** [discordjs/discord.js#2393]
**Please describe the problem you are having in as much detail as possible:**
Importing discord.js from any script on Ubuntu results in the following syntax error:
```
/home/desktop/node_modules/discord.js/src/util/Util.js:19
  static splitMessage(text, { maxLength = 1950, char = '\n', prepend = '', append = '' } = {}) {
                            ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/desktop/node_modules/discord.js/src/index.js:1:76)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
The same script is tested and works on Windows 10.
The command I used to run the script on both machines is `node --use_strict my_script.js`

**Further details:**

- discord.js version: 11.3.2
- node.js version: 4.2.6
- Operating system: Ubuntu 16.04.3 LTS
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
You need at least nodejs v6

**Comment by Yamboy1** [comment]
Hmm, maybe you should make an npm preinstall hook, or something else to make sure the user is running node by or higher

**Comment by appellation** [comment]
the minimum node version is already specified in the package.json

**Comment by Yamboy1** [comment]
Well yeah, but a lot of people don't read that package.json

**Comment by iCrawl** [comment]
Thats their own fault. Reading the readme and the package.json should be a give, and node 4 is not even in maint. mode anymore.

**Comment by Yamboy1** [comment]
Good point, I always use nvm, so I don't worry about using an older version. I just hadn't realised how out of date it was a
