### ISSUE TITLE
"bundleDependencies": false. Expected array

### ISSUE THREAD

**Issue by JustAuserOfGitHub** [discordjs/discord.js#2394]
**Description of problem:**
I running a simple code for my bot and getting this (error in   ##discord.js/package.json):

**Issue code:**
```js
"bundleDependencies": false
```

**Further details:**
- discord.js version: 11.3.2
- node.js version: v9.8.0
- Operating system: Windows 10

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:
![image](https://user-images.githubusercontent.com/24772427/37351880-17e9df8a-26ed-11e8-94e6-429379f943df.png)

**Comment by Keswiik** [comment]
If you're going to open an issue, don't be lazy. Run `node -v` in your command prompt / terminal / etc, there's a reason we ask for it.

Likewise, give more details on your issue. I have no clue what your issue is, as you didn't tell us much.

**Comment by JustAuserOfGitHub** [comment]
K, I've installed discord.js again, but
![image](https://user-images.githubusercontent.com/24772427/37354759-7287f0b6-26f3-11e8-8ecc-c09883a2a613.png)

**Comment by iCrawl** [comment]
You do not have a node_modules folder either.

Please educate yourself a bit about node.js before writing code for it.
This isn't the place for general support questions.
If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9)
