### ISSUE TITLE
Transfer ownership api support

### ISSUE THREAD

**Issue by briantanner** [discordjs/discord.js#240]
Support for transfer ownership via api now that bot accounts can't login would be great. :)

**Comment by abalabahaha** [comment]
Kinda there now in indev, you can pass ownerID to the updateServer options (docs soon). Hop on the discord.js Discord channel in the README if you can't wait for this to be documented

**Comment by austinmeiron** [comment]
I was unsuccessful in locating documentation for ownerID, is it still possible to transfer ownership to a user in 2018?

**Comment by almostSouji** [comment]
@austinmeiron If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
