### ISSUE TITLE
MessageEmbed

### ISSUE THREAD

**Issue by ilovetwilight** [discordjs/discord.js#2401]
**Please describe the problem you are having in as much detail as possible:**

Good day, how can I check an embed-type message for content in title "test"?  Which day I bet, but does not come.

```js
client.on('message', message => { 
    if(MessageEmbed.title('test')) {
        message.channel.sendMessage(`embed  ${MessageEmbed.title}`);
     }
});

```

**Further details:**

- discord.js version: last
- node.js version: last
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
