### ISSUE TITLE
Message reaction add and remove events providing wrong count

### ISSUE THREAD

**Issue by Danktuary** [discordjs/discord.js#2404]
**Please describe the problem you are having in as much detail as possible:**
Trying to check for a reaction's count inside the `messageReactionAdd` and `messageReactionRemove` events, and it's unfortunately giving me the wrong count. Upon restart (using the `raw` event to catch reactions on uncached messages), sometimes it'll log the correct count on the first reaction addition, but on subsequent reactions, it'll log 1 number higher than it's supposed to. More info below.

**Include a reproducible code sample here, if possible:**
```js
client.on('messageReactionAdd', (reaction, user) => {
	console.log('Reaction added; current count:', reaction.count);
});

client.on('messageReactionRemove', (reaction, user) => {
	console.log('Reaction removed; current count:', reaction.count);
});

client.on('message', message => {
	if (message.content === '!react') {
		console.log('First reaction incoming.');
		message.react('🤔');
	}
});
```

Gist with `raw` event included, to log after restarts on uncached messages (needed for what I'll be explaining after this): https://gist.github.com/Danktuary/d38691d5a1765c1550be07632f406c4c

**Further details:**
Using the sample code above, if you send `!react`, it'll log "First reaction incoming." and tell you the reaction's count is 0. If you add a reaction to that same emoji, it'll log as 1. Have another user react, it'll log as 2, and etc. Toggling reactions will go according to this count (i.e. after the bot, you, and another user have reacted, it'll log 2. If someone removes their reaction, it'll log 1).

Fun twist: wait for the bot to react, add your own reaction, and then close the process. Remove your reaction, start up the process again, and then react. It should log 2, the correct amount. Remove your reaction and then add it again. It should log 2 after removing, and then 3 after adding it again.

- discord.js version: 12.0.0-dev
- node.js version: 9.7.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: d041cb2460a294b026e73750647647168ce7359a

**Comment by BigBrainAFK** [comment]
The problem for this, as far as I can tell, seems to lie in the fetching of uncached messages. When fetching the API obviously returns the new amount which we then still increase to add the "new" reaction already accounted for in the API response.

NGL this could be completely wrong but from a bit of testing and poking in the lib with console.log thats what I concluded.

**Comment by RizenLord** [comment]
is there a way if a user reatcs with a certain emoji reacted by the bot it will reply with a message.
EX. if the bot reacts with 🤔 and i also react with 🤔 it will say: great minds think alike.

**Comment by robflop** [comment]
Please don't revive old issues for questions and instead use the discord server at https://discord.gg/bRCvFy9 .
