### ISSUE TITLE
Can i use this library in React Native?

### ISSUE THREAD

**Issue by rkzhap123** [discordjs/discord.js#2405]
- discord.js version: "discord.js": "^11.3.2",
- node.js version: 9.3.0
- RN version : "0.54.2"
- Operating system: Windows

I wan't to use Discord.js in React - native But the errors occur when I compile project.

> bundling failed: Error: Unable to resolve module os from  C:\react-native-workspace\discordTest4\node_modules\discord.js\src\util\Constants.js: Module does not exist in the module map

What's the problem? The reason is that I can't use Javascript Libraries in React-native?

**Comment by iCrawl** [comment]
Looking at the errors your console throws more throughout would reveal the following:

```
18:03:00: The package at ".C:\\Users\\crawl\\Coding\\Javascript\\react-native-test\\node_modules\\discord.js\\src\\sharding\\Shard.js" attempted to import the Node standard library module "child_process". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo
```

Which as you can see ends up being a restriction react-native has which we can not circumvent easily.
