### ISSUE TITLE
The promise returned by <VoiceChannel>.join() is sometimes neither resolved nor rejected.

### ISSUE THREAD

**Issue by ghost** [discordjs/discord.js#2406]
**Please describe the problem you are having in as much detail as possible:**
The promise returned by `<VoiceChannel>.join()` is sometimes neither resolved nor rejected. It's probably dependant to Discord's own issues, as this behavior is not stable across different guild locations.

**Include a reproducible code sample here, if possible:**
```js
if (!message.member.voiceChannel) {
    console.log('A');
}
else {
    console.log('B');
    message.member.voiceChannel.join()
    .then(connection => {
        console.log('C');
    })
    .catch(err => {
        console.log('D');
    });
}
```
Only `B` is printed in console when the bug occurs.

**Further details:**
The location of the guild when the problem first occurred was Central Europe. I restarted the Node process and retried at least 10 times. Then I changed the location to somewhere else, then back to Central Europe again. After that, the problem disappeared with no change in code.

- discord.js version: Master
- node.js version: v8.6.0
- Operating system: Linux (Arch 4.11.9-1)
- Priority this issue should have – please be realistic and elaborate if possible: Probably not critical

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: `d041cb2`

**Comment by hydrabolt** [comment]
This should be fixed now, can you test?
