### ISSUE TITLE
"cannot send an empty message" error

### ISSUE THREAD

**Issue by Wreeper** [discordjs/discord.js#2411]
Hello Discord.js creators. Today i'm gonna report a bug. Whenever i type "testzzz" (the code is there)

client.on('message', message => {
  if (message.content === 'testzzz') {
    message.channel.send(client.user.notes);
  }
});

Yes, a selfbot, not matter, it's giving me nothing. There's the same for ALL values from there https://discord.js.org/#/docs/main/stable/class/ClientUser

**Comment by iCrawl** [comment]
First of all we are planning to not support selfbots anymore.

With that out of the way, read the documentation correctly and first check what `.notes` returns you, its not a string but a `Collection` so you either grab something out of it or you don't. Apart from the usual check if its empty.
