### ISSUE TITLE
TypeError when sending a PNG stream in an embed

### ISSUE THREAD

**Issue by Wodki** [discordjs/discord.js#2412]
**Please describe the problem you are having in as much detail as possible:**
I have a canvas instance and I use the pngStream() function to get the stream from it.
I then use that stream in a Discord attachment and I send it using an embed to a channel.
That's when I get a type Error. 

It might be possible I don't use a class right -especially looking at the master's error - if thats the case I apologize before hand.

Error stable:
```
TypeError: Converting circular structure to JSON
at JSON.stringify (<anonymous>)
at APIRequest.gen (\discord.js\src\client\rest\APIRequest.js:44:81)
```

Error master: 
```
TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.
at Function.resolveFile (\node_modules\discord.js\src\util\DataResolver.js:115:27)
at Promise.all.options.files.map.file (\node_modules\discord.js\src\structures\shared\CreateMessage.js:101:20)
at Array.map (<anonymous>)
at createMessage (\node_modules\discord.js\src\structures\shared\CreateMessage.js:100:45)
at Object.sendMessage (\node_modules\discord.js\src\structures\shared\SendMessage.js:8:33)
at TextChannel.send (\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:119:19)
```

**Include a reproducible code sample here, if possible:**
```js

let canvas = new Canvas(10, 10);
let ctx = canvas.getContext('2d', { alpha:false });
let img = new Canvas.Image();

// ...

let image = canvas.pngStream();

// stable
let embed = new Discord.RichEmbed()
.attachFile(new Discord.Attachment(image, 'name.png'))
.setImage("attachment://name.png");

// master
var embed = new Discord.MessageEmbed()
.attachFiles([new Discord.MessageAttachment(image, 'name.png')])
.setImage("attachment://name.png")

msg.channel.send({embed: embed});
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v8.10.0
- Operating system: Win 7
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: d041cb2 (latest right now)

**Comment by SpaceEEC** [comment]
I can reproduce the error you are getting in stable

Stable stringifies the whole embed object, including the circular file property.  
Possible workaround would be to not attach the file to the embed but the message.
```js
let embed = new Discord.RichEmbed()
  .setImage("attachment://name.png");

msg.channel.send({ embed: embed, files: [new Discord.Attachment(image, 'name.png')] });
```  
​  

I can not reproduce the error you are getting in master

Working for me on canvas 1.6.9 and via github installation (https://github.com/Automattic/node-canvas/commit/37d9db1974c00fa93b8a01ae0287a412d364448c)

Can you log the embed and, if possible, what [DataResolver.resolveFile](https://github.com/discordjs/discord.js/blob/85413481edb0d9b5e6bc8d629f2368dfab6b04a7/src/util/DataResolver.js#L85) gets passed?

**Comment by Wodki** [comment]
@SpaceEEC I apologize for taking so long to answer. So indeed I tried what you've shown me and it does work. Also one thing I want to note.

In the above code I treat `pngStream()` like its a sync thing while its a stream and I have to listen to the end event before I send it to discord to avoid sending half-loaded images. I am pointing it out in case anyone sees that and takes its as an example.
