### ISSUE TITLE
Message.reactions always empty

### ISSUE THREAD

**Issue by jeffshaver** [discordjs/discord.js#2413]
**Please describe the problem you are having in as much detail as possible:**
I have a pinned message in a channel. Only the bot has the permission to send messages in that channel. Other users have the read history permission and the ability to react to messages. My bot is listening for a specific command, then finding the pinned message from that channel and trying to look at the reactions to that message. However, the `reactions` property is always an empty collection. I have tried putting in regular emojis and custom uploaded emojis and none of them are on the message object.

**Include a reproducible code sample here, if possible:**
```js
// Inside of onMessage
async function enrollment() {
  // bot is imported from another file
  const guild =  bot.guilds.find('name', 'MyGuildName')
  const channel = guild.channels.find(
    'name',
    'name-of-channel'
  )
  const pinnedMessages = await channel.fetchPinnedMessages()
  const message = pinnedMessages.first()

  console.log('reactions', message.reactions) // ALWAYS EMPTY
}
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 9.4.0
- Operating system: macOS
- Priority this issue should have – please be realistic and elaborate if possible: I guess it depends on how important reactions are to the platform. This is a big issue for me since I'm trying to create a feature where people signup for raids by reacting with their class icon (custom emojis)

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
This is a discord limitation.
Fetching pinned messages does not give you their reactions.

You can fetch pinned messages again via `TextChannel#fetchMessage` or `TextChannel#fetchMessages` to get their reactions (excluding users, those would need to be fetched seperately as well).

**Comment by jeffshaver** [comment]
@SpaceEEC thanks for the reply! Is this documented somewhere? Is there any way for me to have known this? Did I just miss it in the docs?

**Comment by SpaceEEC** [comment]
Not quite, in the documentation from master is a [note](https://discord.js.org/#/docs/main/master/class/MessageStore?scrollTo=fetchPinned), was probably overlooked when backporting from master.

**Comment by jeffshaver** [comment]
@SpaceEEC would you guys accept a PR to add this back into the docs? Seems like it should just be a one line change to add this sentence `The returned Collection does not contain the reactions of the messages. Those need to be fetched seperately.` to the docs right before the `@returns` line here: https://github.com/discordjs/discord.js/blob/11.3-dev/src/structures/interfaces/TextBasedChannel.js#L225
