### ISSUE TITLE
messageDelete Not firing

### ISSUE THREAD

**Issue by sekwah41** [discordjs/discord.js#2415]
**Please describe the problem you are having in as much detail as possible:**
Message delete isnt triggering anything at all if the message is made before the bot has started.

**Include a reproducible code sample here, if possible:**
```js
const fs = require('fs');

//https://discord.js.org/#/docs/main/stable/general/welcome
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.on("messageDelete", function(msg) {
        console.log("MESSAGE", msg);
});
client.on('message', msg => {

});
```

**Further details:**

- discord.js version: 11.3.2
- node.js version:8.9.4
- Operating system: Windows 10
- Priority this issue should have – Low, not needed immediately but its annoying as its not erroring but it just doesn't trigger at all.

I've seen some other info on this where one said the info isnt there in the first place and another saying that it returns undefined however im not sure if this is a different issue or what but it doesn't trigger at all not even with undefined values in it which is possible because eris and others still trigger on the events.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
That is intentional behaviour. The messages must be cached before expecting events from them. You can get around this by fetching them on startup or something of the like.

**Comment by sekwah41** [comment]
Ahh understandable, wouldnt it be useful to put that in the docs saying it doesnt trigger unless the message is cached? Also ive found where to get the logs but how do you actually cache the messages? Im currently looking at how to load the past messages atm.

**Comment by iCrawl** [comment]
No, it should be pretty self-explanatory that you cannot get a message object of a message that you do not have.
What you can do is listen to the `raw` event and pick the message delete event out of there. You still won't get any useful info apart from some very basic things like message id, but if that is all you need.
Other than that, you can fetch the last X messages on start-up if you think this is a better way.

**Comment by sekwah41** [comment]
@iCrawl i already said understandable but that doesnt change the fact that 1 its an event specifically on messages being deleted hence only logically the data not being there other than the message id deleted if not cached makes sense seeing as in the documentation there is no mention of this?

I mean quoting the documentation exactly "Emitted whenever a message is deleted." not "Emitted whenever a cached message is deleted."

**Comment by sekwah41** [comment]
I understand that its the intended functionality but at least update the documentation is what i was saying in my reply to @Lewdcario

**Comment by sekwah41** [comment]
Well apparently if you forget something happened then something happens to it then apparently it never actually happened and that's supposed to be implied ¯\_(ツ)_/¯ good to know

**Comment by sekwah41** [comment]
@BigBrainAFK i never said that, please actually read what i put. I was saying other ones trigger even with empty data because a message has been removed. Nowhere in the documentation does it say the actual event itsself regardless of the data it gives or possible lack of data it could give does it say it only triggers if the message is cached. Its like if in minecraft you didnt trigger an on command data for the terminal just because it doesn't have player data... (terrible example but sorta along the same lines) there is still data there so either it should be added or the documentation should be updated to say it only triggers for cached messages. That was my whole point in response to him just a better clarification and arguing the point that the current description doesn't state that behavior.

**Comment by sekwah41** [comment]
And my point was arguing solely as the intended function was not to have it trigger to just update the documentation
