### ISSUE TITLE
Backport Request: Getting a role's permissions in a GuildChannel

### ISSUE THREAD

**Issue by Ssaely** [discordjs/discord.js#2417]
**Please describe the problem you are having in as much detail as possible:**
Currently on the latest stable version, there is no way to get a role's permissions for a certain channel.
`GuildChannel.permissionsFor()` only accepts a GuildMember and after getting a PermissionOverwrites object from `GuildChannel.permissionOverwrites`, there is no `allowed` or `denied` property like there is on master.

**Include a reproducible code sample here, if possible:**
```js
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.10.0
- Operating system: Windows 10 64 bit
- Priority this issue should have – please be realistic and elaborate if possible:
Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by TeeSeal** [comment]
There is no point opening an issue that requests a feature which is already in the latest master. The fact that it has been implemented means someone was already aware of this, and you opening an issue won't make it reach stable any sooner.

**Comment by BigBrainAFK** [comment]
Those properties exist on stable under the names `alow` and `deny` and just arent documented.

[Check it out here.](https://github.com/discordjs/discord.js/blob/e5bd6ec150baee5ee4ca0830b80753b7c59f4844/src/structures/PermissionOverwrites.js#L30)

**Comment by iCrawl** [comment]
We are not planning for 11.4 currently so a backport request is kind of pointless at the moment.

If 11.4 is ever to happen I will make sure this gets in.
