### ISSUE TITLE
Problem with random websocket error all few weeks

### ISSUE THREAD

**Issue by Daijobou** [discordjs/discord.js#2422]
I not sure I'm here right, but maybe or maybe you can help me here? I get all few weeks this exceptions from somewhere for websocket module:

> .../node_modules/discord.js/src/client/websocket/WebSocketConnection.js","function":"WebSocketConnection.onError","line":371,"method":"onError","native":false

https://jsonblob.com/aadbc611-2e93-11e8-8b65-3b18ca9c8a34

I have changed from node7 to node8, but that not help

https://jsonblob.com/f027a498-2e93-11e8-8b65-aba4b027ccbf

- node.js version: 8.9.3
- Operating system: centOS 7.4
- discord.js version: 11.3.1

`# /opt/plesk/node/8/bin/npm list --depth=0`

> /var/www/vhosts/example.com/discord
> ├── UNMET PEER DEPENDENCY bufferutil@^3.0.3
> ├── discord.js@11.3.1
> ├── UNMET PEER DEPENDENCY erlpack@discordapp/erlpack
> ├── express@4.16.2
> ├── UNMET PEER DEPENDENCY libsodium-wrappers@^0.7.3
> ├── long@3.2.0
> ├── mysql@2.15.0
> ├── UNMET PEER DEPENDENCY node-opus@^0.2.7
> ├── UNMET PEER DEPENDENCY opusscript@^0.0.6
> ├── prism-media@0.0.1
> ├── UNMET PEER DEPENDENCY sodium@^2.0.3
> ├── striptags@3.1.1
> ├── UNMET PEER DEPENDENCY uws@^9.14.0
> └── winston@2.4.0
> 
> npm ERR! peer dep missing: bufferutil@^3.0.3, required by discord.js@11.3.1
> npm ERR! peer dep missing: erlpack@discordapp/erlpack, required by discord.js@11.3.1
> npm ERR! peer dep missing: node-opus@^0.2.7, required by discord.js@11.3.1
> npm ERR! peer dep missing: opusscript@^0.0.6, required by discord.js@11.3.1
> npm ERR! peer dep missing: sodium@^2.0.3, required by discord.js@11.3.1
> npm ERR! peer dep missing: libsodium-wrappers@^0.7.3, required by discord.js@11.3.1
> npm ERR! peer dep missing: uws@^9.14.0, required by discord.js@11.3.1
> npm ERR! extraneous: long@4.0.0 /var/www/vhosts/example.com/discord/node_modules/discord.js/node_modules/long
> npm ERR! extraneous: prism-media@0.0.2 /var/www/vhosts/example.com/discord/node_modules/discord.js/node_modules/prism-media
> npm ERR! extraneous: depd@1.1.1 /var/www/vhosts/example.com/discord/node_modules/http-errors/node_modules/depd
> npm ERR! extraneous: setprototypeof@1.1.0 /var/www/vhosts/example.com/discord/node_modules/express/node_modules/setprototypeof
> npm ERR! extraneous: statuses@1.3.1 /var/www/vhosts/example.com/discord/node_modules/express/node_modules/statuses
> npm ERR! extraneous: statuses@1.3.1 /var/www/vhosts/example.com/discord/node_modules/finalhandler/node_modules/statuses
> npm ERR! extraneous: statuses@1.3.1 /var/www/vhosts/example.com/discord/node_modules/send/node_modules/statuses
> 

Is this a issue in discord websocket module or can anybody give me a hint what to do?

**Comment by SpaceEEC** [comment]
Handle the error event of your client.
Something simple like `client.on('error', console.error);` would do.
