### ISSUE TITLE
opus event

### ISSUE THREAD

**Issue by Beethoven07** [discordjs/discord.js#2431]
**Please describe the problem you are having in as much detail as possible:**
the **opus event some time it works** and some time its't work i don't know why

**Include a reproducible code sample here, if possible:**
```js
voiceChannel.join()
  .then(connection => {
    const receiver = connection.createReceiver();
receiver.on('opus', function(user, data) {
      console.log("its working");
  });
```

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Gawdl3y** [comment]
Please provide more details, don't just ignore the template.

**Comment by hydrabolt** [comment]
Related to #2399, out of our hands while Discord fixes a voice bug.

**Comment by hydrabolt** [comment]
Discord.js voice now uses the v4 protocol which should fix this issue, see commit https://github.com/discordjs/discord.js/commit/08bbbe930144616338fc906ce5fc7a3e5725b670
