### ISSUE TITLE
Collection doesn't change length attribute of map

### ISSUE THREAD

**Issue by Gaugeforever** [discordjs/discord.js#2433]
Collection is supposed to extend map.  Map has a .length property.  Although collection has this property it is always 0.  For the time being converting to an array to get the length is a work around but optimally you would be able to call length on a collection.

While I'm here, a .empty() would be a nice function to have on a collection as well, that returns a boolean.

This was tested using the collection at message.mentions.members.

Gauge

**Comment by FireController1847** [comment]
Map doesn't have .length, it's always had .size?

See [Length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/length) (returns 404) versus [Size](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/size)

**Comment by Gaugeforever** [comment]
Hmm it says on the link that map has a property length, but size works great!  Thanks!  Sorry about such a trivial thing :)
