### ISSUE TITLE
"Websocket was closed before the connection was established"

### ISSUE THREAD

**Issue by MoonbaseInteractive** [discordjs/discord.js#2435]
Hi there,

I am getting a random error that idk how to fix and neither does my co coder. I tried everything and nothing worked, it goes away once i get rid of the dispatcher.on statement and just have it play the music.

Please help me,
Alan Moon

**Comment by Andreybest** [comment]
As i understood you have same issue, its a bug...
https://github.com/discordjs/discord.js/issues/2359

**Comment by hydrabolt** [comment]
Assuming this is indeed the same bug, your issue should be fixed by the above commit.
