### ISSUE TITLE
Issue with Collections when using .array() for Guilds.

### ISSUE THREAD

**Issue by Bioblaze** [discordjs/discord.js#2444]
**Please describe the problem you are having in as much detail as possible:**

I believe the issue is when I do 'client.guilds.array()' when I cycle through the guilds the guild.owner.user.tag I believe is giving a error. Specifically the error for formating a undefined variable.

[2018-04-04T10:29:38.678] [ERROR] Plugin[4] - [Bot]uncaughtException: TypeError: Cannot read property 'format' of undefined

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.6.1
- Operating system: Windows 10 & Ubuntu 4.16
- Priority this issue should have – please be realistic and elaborate if possible: Quite high in my opinion.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Bioblaze** [comment]
After Adding 'unhandledRejection' I was unable to duplicate the Error. i have 5 shards with a average of 2,400+ Servers each. just shy of requiring a 6th Shard. Sometimes it'll appear out of 5 restarts on my bot, i've only seen it happen once. I'm trying my best to replicate it. If It happens again I'll Record it and send the info too this post.

**Comment by Gawdl3y** [comment]
Guild owners are not always cached, and `guild.owner` is just a getter that retrieves from cache. You must fetch the owner user to guarantee it's there.
