### ISSUE TITLE
Unexpected Token >

### ISSUE THREAD

**Issue by LLCOOLTIGHT** [discordjs/discord.js#2445]
I'm making a bot and I can't turn it online because of this error 
![image](https://user-images.githubusercontent.com/19495591/38334083-0bb9fff8-3820-11e8-8cb9-3f8cf3937def.png)

This is the coding:
const Discord = require("discord.js"); ""

const TOKEN = "myToken";

var bot = new Discord.Client();

bot.on("ready", function() {
  console.log("Ready");
});

bot.on("message", function(message) {
    if (message.author.equals(bot.user)) return;

    if (message.content -- "t!Credits") {
      message.channel.sendmessage("Tight#5293 made the bot");
    }
});

bot.login(TOKEN);

**Comment by LLCOOLTIGHT** [comment]
Now a new error popped up, 
![image](https://user-images.githubusercontent.com/19495591/38334204-56970728-3820-11e8-8a83-a58398fe9ff3.png)

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by TacoboiG** [comment]
you put if (message.content -- "t!Credits") {
it shouldn't be -- it should be == (equals)
 if (message.content == "t!Credits") {
