### ISSUE TITLE
message.isMemberMentioned() detects @everyone but it doesn't return true for @role mentions

### ISSUE THREAD

**Issue by georgeravenholm** [discordjs/discord.js#2456]
@georgeravenholm - detected
@everyone - returns true
@moderators - doesnt return true for people in moderators

- discord.js version: stable
- node.js version: 8.11.1
- Operating system: Windows 10
- Priority this issue should have: Low

**Comment by SpaceEEC** [comment]
I can not reproduce, working fine for me.

Used code in my case:
```js
client.on('message', message => {
	console.log([
		`Raw content: ${message.content}`,
		`Mentioned: ${message.isMemberMentioned(message.member)}`
	].join('\n'));
});
```

Prints out for:

#### User mention:
```
Raw content: <@218348062828003328>
Mentioned: true
```

#### Role mention:
```
Raw content: <@&251158405832638465>
Mentioned: true
```

#### Everyone mention:
```
Raw content: @everyone
Mentioned: true
```

**Comment by iCrawl** [comment]
@georgeravenholm Any update on this?

**Comment by iCrawl** [comment]
Been over 2 weeks now since one of our contributors tested the issue now and did not encounter any issues.

If you still encounter this, feel free to reopen the issue.
