### ISSUE TITLE
issue: TextChannel#startTyping never stops typing

### ISSUE THREAD

**Issue by KingDGrizzle** [discordjs/discord.js#2457]
**Please describe the problem you are having in as much detail as possible:**
Whenever startTyping is called, it runs, but never ends. Basically remaining in an infinite loop. Probably forgot to check for the count property of the typing entry and if it reaches 0, resolve the promise.

**Include a reproducible code sample here, if possible:**
```js
msg.channel.startTyping(1);
```

**Further details:**

- discord.js version: 12.0
- node.js version: 9.9.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: Low.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: e84575803702576669eb02c647474430ac0295b8

**Comment by KingDGrizzle** [comment]
Well the bot does send a message and it doesn't stop... Soo /shrug

**Comment by appellation** [comment]
The bot will not stop typing until you tell it to by calling `stopTyping`.

**Comment by neander-squirrel** [comment]
```
try{
	message.channel.startTyping()
	await processCommand(message)
	message.channel.stopTyping()
}catch(e){
	console.log(e)
}
```
My code looks like above and the bot has significant delay between finishing the work and stop typing.
If the message doesn't start with a prefix, `processCommand()` just simply returns without waiting and executes the `stopTyping()` function immediately, yet the bot doesn't stop typing only after 10-15 seconds.
I'm using latest 11.3.2 version.

**Comment by appellation** [comment]
It can take a while to stop typing.

![image](https://user-images.githubusercontent.com/8494131/39854276-e3929224-53db-11e8-98df-90431ec4234e.png)

**Comment by bdistin** [comment]
@neander-squirrel fyi, if processCommand throws an error, the bot won't stop typing in that channel, with the code you have shown. To avoid that, it should be more like:
```js
try{
	message.channel.startTyping()
	await processCommand(message)
}catch(e){
	console.log(e)
}finally{
	message.channel.stopTyping()
}
```
or even just outside of the try-catch blocks, so that you always startTyping() the same number of times you stopTyping().
