### ISSUE TITLE
Client.channelCreate() event is triggered when joining a server

### ISSUE THREAD

**Issue by Marionaise** [discordjs/discord.js#2463]
**Please describe the problem you are having in as much detail as possible:**
When a bot joins a new guild, the channelCreate-Event ist fired

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('guildCreate', async guild => {
	console.log(`Joined: ${guild.name}`)
});

client.on('channelCreate', async channel => {
	console.log(`Channel created: ${channel.name}`)
});

client.login('xxx');
```

**Further details:**

- discord.js version: stable (11.3.2)
- node.js version: v8.9.4
- Operating system: Windows 10 & Linux mint
- Priority this issue should have – please be realistic and elaborate if possible: medium

My Log:
```Logged in as Bot#1234!
Channel created: Text-Kanäle
Channel created: generalChannel created: Sprach-Kanäle
Channel created: AllgemeinChannel created: test
Joined: testServer```

**Comment by hydrabolt** [comment]
Unless I'm missing something, your log shows that both channelCreate and guildCreate are emitted?

**Comment by Marionaise** [comment]
Yes, thats correct. When the bot joins, the channelCreate-Event fires

**Comment by hydrabolt** [comment]
That's because we receive `CHANNEL_CREATE` from Discord when joining a server so we also emit it
