### ISSUE TITLE
Example code on homepage produces UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by lukepighetti** [discordjs/discord.js#2464]
The example code on https://discord.js.org produces an UnhandledPromiseRejectionWarning.

```
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('message', msg => {
  if (msg.content === 'ping') {
    msg.reply('Pong!');
  }
});

client.login('token');
```

Produces

```
(node:98840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.
(node:98840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Lewdcario** [comment]
This is not an issue on our end- it simply means the provided token is wrong. Feel free to discuss farther on the [Discord server](https://discord.gg/bRCvFy9) if you are having difficulty locating the correct token, we can try our best to help.

**Comment by lukepighetti** [comment]
Issue was a result of an incorrect token.

**Comment by lukepighetti** [comment]
He's got fingers of fury! 😄 Thanks for the help.

**Comment by IRobL** [comment]
before moving to a less-persistent discussion form, where do we find the token that is missing in this issue?  For example, I'm getting this error too, and found my token at https://discordapp.com/developers but my token was called a "Client Secret" so I suppose that's not where you get the correct token, but it does demonstrate how to share where the correct token could be found if anyone knows where to find it.

**Comment by iCrawl** [comment]
![image](https://user-images.githubusercontent.com/20760160/43992197-e255089e-9d7b-11e8-86d4-b6fdd1b1e443.png)
