### ISSUE TITLE
Webhook messages cannot be deleted.

### ISSUE THREAD

**Issue by dekuraan** [discordjs/discord.js#2465]
**Please describe the problem you are having in as much detail as possible:**
When I try to delete a message created by a webhook using the `message.delete()` function, it borks out and says that there is no delete function associated with the message object. I think it's because webhook messages are structured differently but they are handled as message objects in Discord.js.

**Include a reproducible code sample here, if possible:**
```js
var async = require('asyncawait/async');
var await = require('asyncawait/await');
const Discord = require("discord.js");
const client = new Discord.Client();
const hook = new Discord.WebhookClient(config.webhook.id, config.webhook.token);
client.on("ready", async () => {
  let initialMsg = await hook.send("test delete", {
      username: "Webhook",
      avatarURL: "http://avatar.com/avatar.png"
  });
  console.log(initialMsg);
  await initialMsg.delete();
});
client.login(config.client.token);
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.10.0
- Operating system: Windows 10 x86-64 WSL (Ubuntu 16.04)
- Priority this issue should have – please be realistic and elaborate if possible: not important

**Comment by OriontheCat** [comment]
So you just can't delete Webhook sent message?

**Comment by Lewdcario** [comment]
I neglected to mention (apologies) - you can get in the promise of a sent webhook message, the `message_id`, and use that (along with a `channel_id`) to grab the message in the channel and delete it, or make a raw api request, whatever you prefer.
