### ISSUE TITLE
voiceStateUpdate event doesn't trigger when leaving guild

### ISSUE THREAD

**Issue by Sir-Will** [discordjs/discord.js#2466]
**Please describe the problem you are having in as much detail as possible:**
If a user leaves the discord server while he is in a voice channel then the `voiceStateUpdate` event doesn't get triggered.

**Further details:**

- discord.js version: master
- node.js version: v8.2.1
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [x] I have also tested the issue on latest master, commit hash: b955a514f6269c6300bbd633481824e9536bfe7b

**Comment by BigBrainAFK** [comment]
Afaik the user doesnt really "disconnect" if they get kicked/banned/leave and they rejoin they will reconnect to the voicechannel iirc

**Comment by iCrawl** [comment]
I'm pretty sure there isn't much we can do but to forcefully remove the user when he leaves the guild.
Unsure if this is desirable though because discord itself doesn't send us an event about it.

**Comment by Sir-Will** [comment]
@BigBrainAFK it didn't reconnect me to the voice channel when I was testing it.

**Comment by iCrawl** [comment]
There's not much we can do, discord doesn't tell us or give us the information and we shouldn't manually tinker with that stuff for obvious reasons.

**Comment by Sir-Will** [comment]
I solved it now by saving users who are in the voice channel and then checking if the user who left the guild is in the list.

**Comment by iCrawl** [comment]
I'll mark this as solved then, not much we can do, and not much we should do if discord doesn't emit those themselves.
