### ISSUE TITLE
Joining Another Server?

### ISSUE THREAD

**Issue by ruchibuchi1** [discordjs/discord.js#2474]
I want to have my bot join another server.  I have the url for the server, but I'm not sure how to do it through the API.  I'm looking at this page:  https://discord.js.org/#/docs/main/stable/class/Client

I can try fetchInvite() method, but I don't see an accept() method on the Invite object.  Any advice?

Thanks

**Comment by iCrawl** [comment]
You can't.

**Comment by ruchibuchi1** [comment]
But according to this post it seems possible:  https://github.com/discordjs/discord.js/issues/233

**Comment by iCrawl** [comment]
You see the date on this?
The API does not allow bots joining invites anymore. The only way to achieve this is have a bot run on a user account, and this goes against TOS so we are not going to support this.
