### ISSUE TITLE
presenceUpdate fired twice, goes through idle

### ISSUE THREAD

**Issue by ashleymoogle** [discordjs/discord.js#2481]
Hello, I'm having a little issue with the presenceUpdate event : 
When I change my status from online to dnd, for example, the event is fired and says I'm passing by an idle status before effectively becoming dnd

```js
export default function presenceHandler (oldMember, newMember) {
        console.log(oldMember.presence.status);
        console.log(newMember.presence.status);
        console.log('---');
}
```

Result is : 
```js
online
idle
---
idle
dnd
---
```

**Further details:**

- discord.js version: ^11.3.2
- node.js version: 9.10.1
- Operating system: OSX High Sierra 10.13.4
- Priority this issue should have – please be realistic and elaborate if possible: not high but slighly annoying

Thanks! Your work is awesome :)

**Comment by SpaceEEC** [comment]
I can not reproduce this.

Is this reliably reproducible for you?
Does it happen for all users, only for specific users, or any other pattern?

**Comment by ashleymoogle** [comment]
Hey, thanks for your reply!
Yeah it happens very often for me but I only tried it with my own user changing my status.

**Comment by iCrawl** [comment]
Your own user being *you* or the bot user?

**Comment by ashleymoogle** [comment]
Being me! Sorry for the wording.

**Comment by Mijago** [comment]
Hi, just wanted you to know that i ran into (almost) the same issue.
It just does not cycle through the idle state but it sends the precense update twice. 
Maybe related? 

Using this simple test script:
```js
const Discord = require("discord.js");

let discordBot = new Discord.Client();

discordBot
    .login("TOKEN")
    .then(() => {
        discordBot.on("presenceUpdate", (oldMember, newMember) => {
            console.log(oldMember.presence.status);
            console.log(newMember.presence.status);
            console.log('---');
        })
    });
```

I got the following result:
```
online
dnd
---
online
dnd
---
dnd
idle
---
dnd
idle
---
idle
offline
---
idle
offline
---
offline
online
---
offline
online
---
```

My actions were:
Online -> dnd
dnd -> idle 
idle -> invisible (took a few seconds till it recognized it)
inbisible -> online


I used:
* node 9.7.0
* newest discordjs from npm repo (release 11.3.2)
* The Bot used a bot account 
* I used a real user to switch the states
* OS: Win10

**Comment by hydrabolt** [comment]
That is not related to the issue, presence updates are specific to members not users.

**Comment by Lewdcario** [comment]
Failed to reproduce as well- so more information (if possible) might be helpful. For the record, ensure you test in as small of a server as possible and log the user whose presence changes (and the guild in which it occurred) as well to be absolutely sure. For me, all appears to be normal - I do not get the cycle of presences.

**Comment by JoshTRN** [comment]
YOOOOOOOOO  JOSH!!!!

So, I was having the EXACT same issue and I couldn't figure it out to save my life... I happened to be _LISTENING TO MY PHONE_ on discord while messing with the code and checking my presence _ON MY LAPTOP!_ So, there were 2 instance of discord going on and it hit that event emmitter twice because of it.

**Comment by royOST** [comment]
This issue also comes up if you are in multiple servers with the bot. You get a presenceUpdate from each server (since your status is updated in both servers). 
Just check for the presence.guild.id to determine which presence you actually care about.
