### ISSUE TITLE
Reaction not updating after changed collection

### ISSUE THREAD

**Issue by mklprudence** [discordjs/discord.js#2483]
**Please describe the problem you are having in as much detail as possible:**
I used the following code to delete a reaction from the message.reactions collector:

message.channel.fetchMessage(args[0])
                        .then(msg => msg.reactions.delete(args[1]))
                        .catch(console.error);

The object in the map is deleted as expected, as i checked that it is removed from the reaction list using the following code:

message.channel.fetchMessage(args[1])
                            .then(msg => message.channel.send(msg.reactions.map(r => r.emoji.name).join('\n')))
                            .catch(console.error);

However, the reactions have not been updated and the reaction is still there.

The following image shows that first there are 3 reactions, then i show all the 3 reactions as a list, then i removed the deer reaction, and it is indeed removed from the list shown at the bottom, but looking at the message at the top, which is the target message, there are still 3 reactions
![image](https://user-images.githubusercontent.com/25664500/38890169-39c8038e-42b3-11e8-8fb1-22ddddfbc524.png)

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 9.9.0
- Operating system: Windows 10
- Priority this issue should have – Medium

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Deleting an entry from the reactions collection won't remove the reaction in discord.
You have to use [`MessageReaction#remove`](https://discord.js.org/#/docs/main/stable/class/MessageReaction?scrollTo=remove) to do so. (`message.reactions.get(args[1]).remove(user)`)

Feel free to join our [Discord server](https://discord.gg/bRCvFy9) if you are having further questions, as the issue tracker is only for bug reports and enhancement suggestions.
