### ISSUE TITLE
Create Role

### ISSUE THREAD

**Issue by Dark-View** [discordjs/discord.js#2494]
I need a comman like this: %createrole NAME  HEXCOLOR , but i can't found any docs about this, you can help me?

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by haykam821** [comment]
```js
// assuming your message is msg
const args = msg.content.split(" ");
msg.guild.createRole({
    data: {
        name: args[1],
        color: parseInt(args[2].replace("#", ""), 16),
    },
    reason: `By ${msg.author} using %createrole`,
});
```
