### ISSUE TITLE
Internal Sharding missing client.ping

### ISSUE THREAD

**Issue by shirtgov** [discordjs/discord.js#2497]
**Please describe the problem you are having in as much detail as possible:**
client.ping does not exist in internal-sharding.

**Include a reproducible code sample here, if possible:**
```js
client.ping
```

**Further details:**

- discord.js version: internal-sharding
- node.js version: 8
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Low priority.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
It can be found [here](https://discord.js.org/#/docs/main/internal-sharding/class/WebSocketManager?scrollTo=ping).

**Comment by devsnek** [comment]
this is intentional. you can get it yourself from client.ws
