### ISSUE TITLE
DiscordJS - Sending a message to a specific server & channel.

### ISSUE THREAD

**Issue by Haizanjs** [discordjs/discord.js#2500]
So I want to cycle through my multidimensional array and select out the server/channel name and then send to that specific server - channel name if joined. 

Note: I'm using Channel IDS but I also tried the normal names and so forth and it still had the same reoccurring issue.

`
  var configuredServers = [
    ["Bit Testing","432657794567503892"],
    ["Test","437885314837774346"]
  ];
  configuredServers.forEach(function(element) {
    
    var channel = bot.servers.get("name", element[0]).channels.get("name",element[1]);
    bot.sendMessage(channel,message.content);
  });

Thanks in Advanced!

`

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
