### ISSUE TITLE
guild.leave is not a function

### ISSUE THREAD

**Issue by ipadpuppydogdude1** [discordjs/discord.js#2516]
**Please describe the problem you are having in as much detail as possible:**
guild.leave() is not a function.

**Include a reproducible code sample here, if possible:**
```js
if(guildblacklist[guild.id], g => {
g.leave()
})
```

**Further details:**
http://prntscr.com/jbd89a
- discord.js version: discord.js@12.0.0-dev
- node.js version: v9.11.1
- Operating system: UNIX 17.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium or High.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
