### ISSUE TITLE
JavaScript error help

### ISSUE THREAD

**Issue by Nekopainz** [discordjs/discord.js#2517]
https://i.imgur.com/iFBLOHk.png I downloaded discord and when it finished installing it had a popup asking me how I wanted to open the file and I clicked on internet explorer so it opened discord up in the browser for like 2 or 3 seconds and closed itself and opened the discord app regularly but now when I restart my computer I get this error and when I click on ok it opens up normally but this error popups on every restart and i've tried deleting the localappdata and appdata files and restarting and reinstalling but it still does it. It doesn't seem like it's effecting anything but the error coming up all the time is annoying and I don't know how to fix it

**Comment by iCrawl** [comment]
This is not discord support. 

This is the issue tracker for a library interacting with the discord api.
