### ISSUE TITLE
member.voiceChannel.parent.children only returns the channel the user is in.

### ISSUE THREAD

**Issue by warhammercasey** [discordjs/discord.js#2518]
**Please describe the problem you are having in as much detail as possible:**
Im trying to create a new voice channel if all channels in a category have a member in them, so when a user joins a channel, I'm using ``newMember.voiceChannel.parent.children`` in a voiceStateUpdate event to get all the channels in the category of the channel the user joined.
The problem is getting the children of its parent only returns the channel the user joined unless the user joined a channel created by the bot.
For example I have a channel called "Strike 1" in a category. When the user joins the channel it creates a new channel in that category called "Strike 2", as it should. If the user then disconnects from Strike 1 and rejoins it, when the bot runs ``newMember.voiceChannel.parent.children``, this only returns with Strike 1, even though both Strike 1 and Strike 2 are in the same category. But if the user joined Strike 2 instead, ``newMember.voiceChannel.parent.children`` will return both Strike 1 and Strike 2, as it should.

**Include a reproducible code sample here, if possible:**
```js
client.on('voiceStateUpdate', (oldMember, newMember) => {
    if (oldMember.voiceChannel == null && newMember.voiceChannel != null) {
        var categoryChannels = newMember.voiceChannel.parent.children.array();
        var emptyChannels = [];
        console.log(categoryChannels.length);
        for (i = 0; i < categoryChannels.length; i++) {
            if (categoryChannels[i].members.array()[0] == undefined) {
                emptyChannels.push(categoryChannels[i]);
            }
        }
        console.log(emptyChannels.length);
        if (emptyChannels.length == 0) {
            var permissions = categoryChannels[0].permissionOverwrites.array();
            categoryChannels[categoryChannels.length - 1].clone(categoryChannels[categoryChannels.length - 1].name.substring(0, categoryChannels[categoryChannels.length - 1].name.lastIndexOf(" ")) + ' ' + (parseInt(categoryChannels[categoryChannels.length - 1].name.split(" ").pop()) + 1).toString()).then(clone => {
                clone.setParent(categoryChannels[categoryChannels.length - 1].parent);
                clone.setUserLimit(categoryChannels[categoryChannels.length - 1].userLimit);
                for (i = 0; i < permissions.length; i++) {
                    clone.overwritePermissions(permissions[i].id, permissions[i]);
                }
            });
        }
    }
});
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.11.1
- Operating system: Its run on heroku so im not sure.
- Priority this issue should have – please be realistic and elaborate if possible: Low - pretty minor and probably possible to find a workaround.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
This is fixed in `master` branch, I also updated your code to work with the master branch so you can test:

```js
client.on('voiceStateUpdate', (oldState, newState) => {
    if ((!oldState || !oldState.channel) && newState.channel) {
        var categoryChannels = newState.member.voice.channel.parent.children.array();
        var emptyChannels = categoryChannels.filter(channel => channel.members.size === 0);

        console.log(categoryChannels.length);
        console.log(emptyChannels.length);

        if (emptyChannels.length == 0) {
            var permissions = categoryChannels[0].permissionOverwrites.array();
            categoryChannels[categoryChannels.length - 1].clone({
                name: categoryChannels[categoryChannels.length - 1].name.substring(0, categoryChannels[categoryChannels.length - 1].name.lastIndexOf(" ")) + ' ' + (parseInt(categoryChannels[categoryChannels.length - 1].name.split(" ").pop()) + 1).toString()
            }).then(clone => {
                clone.setParent(categoryChannels[categoryChannels.length - 1].parent);
                clone.setUserLimit(categoryChannels[categoryChannels.length - 1].userLimit);
                for (i = 0; i < permissions.length; i++) {
                    clone.overwritePermissions(permissions[i].id, permissions[i]);
                }
            });
        }
    }
});
```

**Comment by amishshah** [comment]
If you can still reproduce please reopen open this issue.
