### ISSUE TITLE
Error: socket hang up caused by rate limiting

### ISSUE THREAD

**Issue by njb-said** [discordjs/discord.js#2527]
**Please describe the problem you are having in as much detail as possible:**
Receiving socket hang up error when sending one message to multiple guilds.
My scenario is odd, the bot has a feature which sends a single message to guilds once per day at midnight UTC, all guilds which it sends to have enabled this feature, using a command to set the channel the message ends up in.
So for the first 10 or 20 messages it is absolutely fine, after that though I get an error like this:
```js
[2018-05-02T00:01:20.453Z] ERROR: bot/1 on f0f5ab0e0077: (err.code=ECONNRESET)
    { discordServerId: '[redacted]',
      discordServerName: '[redacted]' }
    --
    Error: socket hang up
        at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
        at Object.onceWrapper (events.js:293:19)
        at emitNone (events.js:91:20)
        at TLSSocket.emit (events.js:188:7)
        at endReadableNT (_stream_readable.js:975:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
        at process.wrappedFunction (/src/node_modules/newrelic/lib/transaction/tracer/index.js:276:51)
```
At the time of writing there are around 100 servers enabled with this feature, but this is growing daily.
When the bot was being developed we tested this feature with a smaller number of guilds (about 15) and it worked fine, however it's harder to test at scale.

I can only assume this is related to rate limiting, and the reason for not getting a 429 HTTP response is Cloudflare kicking in to protect discord and completely closing the connections - a behaviour I haven't seen from Cloudflare before.
I was under the impression discord.js handles 429 errors by queuing the requests to be sent later, I also thought that rate limits were per-guild although I understand there is likely a global rate limit too to prevent flooding.

It is really hard to troubleshoot the issue as I have no way of gauging the actual rate limit (sent in headers iirc) or if I am getting too close.

In Discord I mentioned this issue and was told to add a delay between messages, this is fine by me although it would massively increase as more servers have this feature enabled.
I was also told to come here to report the issue, hopefully a way to retrieve the rate limits could be added to the library?
[This issue](https://github.com/discordjs/discord.js/issues/1176) suggested adding an event with rate limit information, this would be very useful.

**Include a reproducible code sample here, if possible:**
Bit of a shoddy code sample, had to remove lots of application specific things like logging + database connections
```js
// You would need to add a bot variable to test this
// Also will need a logger or remove it and replace with console.log

// This uses bunyan as a logger
// var logger = require('./logger');
var async = require('async');
var fileName = 'image-name.png';
var fullPath = 'path/to/file/' + fileName;

var embed = {
    title: 'Test Message',
    image: {
        url: 'attachment://' + fileName
    }
};

// arr is the array of discord servers with the feature enabled from a database
var arr = [{serverId: 'discord-guild-id', name: 'temporary name', channels: { shop: 'discord-channel-id' } } ];

async.each(arr, function(item, next) {
    if(!item.channels.shop) {
        logger.debug('[BOT] Skipping ' + item.serverId + ' no shop channel defined');
        return next();
    }

    var g = bot.guilds.get(item.serverId);
    if(!g) {
        logger.debug('[BOT] Unable to find server matching ' + item.serverId);
        return next();
    }

    var c = g.channels.get(item.channels.shop);
    if(!c) {
        logger.debug('[BOT] Unable to find channel ' + item.channels.shop + ' in ' + item.serverId);
        return next();
    }

    c.send({embed: new _Discord.RichEmbed(embed), files: [ {attachment: fullPath, name: fileName } ]}).then((msg) => {
        logger.debug('[BOT] Sent message to ' + item.name + ' (c:' + item.channels.shop + ')');
        return next();
    }).catch((err) => {
        logger.error(err, {discordServerId: item.serverId});
        // Commenting out for github issue
        // bugsnag.notify(err, {discordServerId: item.serverId});
        return next();
    });
}, function() {
    logger.debug('[BOT] Finished sending messages');
});
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 7.10.1
- Operating system: Centos 7, node running in Docker
- Priority this issue should have – please be realistic and elaborate if possible: low/medium

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by BigBrainAFK** [comment]
just dont send a message to all guilds the bot is in? if theres more guilds it will not be midnight when messages send out anyway. messages get delayed if theyd hit the ratelimit so if theres roo many servers it wont be midnight.

**Comment by njb-said** [comment]
The purpose of the bot is to send a message at midnight, the bot is in 260 guilds currently, and 100 of those have enabled this feature. So it is entirely opt-in for users of the bot.
When I looked through the code, I saw that the library adds queuing to avoid hitting the rate limit.
As a result then I am confused as to why a socket hang up error is occuring when attempting to send messages, if it is not the rate limits.

**Comment by njb-said** [comment]
I have implemented the work around suggested in Discord, adding a delay of 220ms between sending the messages. 

However, this doesn't really solve this ticket as it would still be very useful to be able to get the rate limit information and get to the bottom of why socket hang up is being thrown rather than the request queued because of a 429 HTTP error 😛

**Comment by BigBrainAFK** [comment]
the delay didnt fix it cause its not the ratelimit

**Comment by MoordMachineYT** [comment]
Just add a delay of 1/s that will be finished under 2 minutes and you will likely not be ratelimited

**Comment by kyranet** [comment]
In a quick research in Google, this issue seems to be more prone to appear in old versions of Node.js, suggesting that it may be fixed in Node.js 8.x or 10.x, your version, 7.10.1, is not supported anymore and reached EOL last year (2017-06-30), check the Node.js release schedule [here](https://github.com/nodejs/Release#release-schedule).

When a Node.js version reaches EOL, it stops getting updates (even security ones), and during a year, there has been many patches and bugfixes for both `http` and `https` modules.

If it's possible for you, can you try upgrading to Node.js 8.11.1 or 10.0.0, and let me know if there is still a issue, please?

**Comment by iCrawl** [comment]
This issue has been pretty stale for a few months now, open a new issue if this still persists please.
