### ISSUE TITLE
Can't change activity of a non-bot client

### ISSUE THREAD

**Issue by TotomInc** [discordjs/discord.js#2541]
**Please describe the problem you are having in as much detail as possible:**

I am trying to make a small userscript that display the current track playing from SoundCloud on Google Chrome, linked to my Discord user account. It works well with a bot-client but the user activity don't change when I'm logged in with a user account.

When testing the script, I am logged from both the Windows Discord client and the SoundCloud tab. Maybe it's because of 2 simultaneous connections on a same _(user?)_ account.

As a side note, I can change the status (from idle to online, DND to idle, ...).

**Include a reproducible code sample here, if possible:**
```js
// retrieve the track title from the soundcloud tab
let track = 'track title from soundcloud tab';

// once track title retrieved, set the new user activity with the track name
client.user.setActivity(track)
	.then((activity) => console.log('[DiscordJS EXTENSION] activity set:', activity));
```

**Further details:**

- discord.js version: [11.3-dev for browser](https://github.com/discordjs/discord.js/raw/webpack/discord.11.3-dev.js)
- node.js version: browser (Google Chrome 66.0.3359.139)
- Operating system: Windows 10
- Priority this issue should have: very low

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
you should use RPC for this: https://github.com/discordjs/RPC

**Comment by TotomInc** [comment]
Alright, thanks!

**Comment by TotomInc** [comment]
Discord RPC is currently in private beta according to [Discord dev-docs](https://discordapp.com/developers/docs/topics/rpc), I get `Invalid Origin` error.

**Comment by TotomInc** [comment]
[Looks like discordjs/rpc is broken with ipc transport type.](https://github.com/discordjs/RPC/issues/31)
