### ISSUE TITLE
Command Random Letters

### ISSUE THREAD

**Issue by OliverBZ** [discordjs/discord.js#2545]
Hi,

I am trying to create a ticket bot, And when you do -new you only get the name ticket but I want every time you do -new the name will go up like first time when you do -new the name of the ticket would be: ticket, the next time = ticket-2 and so further how do you do that?

My code:
`message.guild.createChannel(`Ticket`, "text")
.then(newChannel => newChannel.setParent("PARENT_ID"))
.then(newChannel => newChannel.setTopic(``))
.then(newChannel => newChannel.overwritePermissions(message.author, {VIEW_CHANNEL: true, SEND_MESSAGES: true}))
.then(newChannel => newChannel.overwritePermissions(message.guild.defaultRole, {VIEW_CHANNEL: false}))
.then(newChannel => newChannel.overwritePermissions(message.guild.roles.find("name", "Tester"), {VIEW_CHANNEL: true, SEND_MESSAGES: true}));`

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
