### ISSUE TITLE
[docs] RoleResolvable disappeared

### ISSUE THREAD

**Issue by Favna** [discordjs/discord.js#2552]
**Please describe the problem you are having in as much detail as possible:**

The RoleResolvable Typedef disappeared from the docs, as seen [at the entry for GuildMemberStore.add()](https://discord.js.org/#/docs/main/master/class/GuildMemberRoleStore?scrollTo=add) or the index under the Typedefs header. It used to be there and still is on `stable` but is gone under `master`.

**Include a reproducible code sample here, if possible:**
N.A.

**Further details:**

- discord.js version: master
- node.js version: N.A.
- Operating system: N.A.
- Priority this issue should have – please be realistic and elaborate if possible: minor, docs

- [X] I have also tested the issue on latest master, commit hash: 75ebd5d23cf33ea5da6538a1a4865bea2c58e3d5

**Comment by Kashalls** [comment]
Fix soon ™️
