### ISSUE TITLE
fn.bind() is not a function

### ISSUE THREAD

**Issue by Nekiono** [discordjs/discord.js#2565]
**Please describe the problem you are having in as much detail as possible:**
So, after `npm install`ing discordjs/discord.js, on using guilds.find(), it throws a `TypeError: fn.bind is not a function`.

(additional log output)
at Map.find (\sora-5\node_modules\discord.js\src\util\Collection.js:171:49)

(could be related to dependencies)

**Include a reproducible code sample here, if possible:**
```js
this.client.guilds.find('name', 'guildName');
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 8.11.1 (also tested on 10.1.0)
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: low-med

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by appellation** [comment]
If you'll see the documentation, you'll see that this format is not supported in the development version of discord.js https://discord.js.org/#/docs/main/master/class/Collection?scrollTo=find

**Comment by kyranet** [comment]
Instead, use

```javascript
this.client.guilds.find(guild => guild.name === 'guildName');
```

**Comment by Nekiono** [comment]
ty! :)

**Comment by Lewdcario** [comment]
@FireController1847 There was a PR with its discussion [here](https://github.com/discordjs/discord.js/pull/2511).
To sum it up (as the description of the PR notes), it was due to the method not adding any new functionality, since the same can be accomplished with the callback parameter. It is a similar case for the other methods and parameters that were revoked.

**Comment by Deep461** [comment]
var roless = message.guild.roles.cache.find('name', role);
whats problem? i used var role =
