### ISSUE TITLE
[WebSocket] Issues after outages

### ISSUE THREAD

**Issue by kyranet** [discordjs/discord.js#2569]
**Please describe the problem you are having in as much detail as possible:**

During API outages, sometimes discord.js does not reconnect correctly but instead keep a dead websocket[1] that do not fire the [disconnect](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-disconnect) event, but also sometimes, the session reconnects successfully with unpatched data.

In the last outage, both the bots I have (which run d.js master) got affected by this issue: one went offline with the process still running, and the other had... no channels at all, but was replying to commands. So I took advantage of the situation and decided to investigate what was happening, so I evaluated (via eval) the following code: `msg.guild.channels`. Got as result:

```javascript
GuildChannelStore [Map] { guild: [Guild] }
```

This was evaluated in a guild with 61 channels, but the guild was basically, in an empty state with empty roles, channels...

---

I have been talking with hydrabolt and lewdcario, and both agreed that this should be filed as an issue, since this is hard to reproduce. Additionally, in a month - when I finish exams, I'll be able to push a new project that monitors the state from both bots and can retrieve data via IPC from them, then, I'll be able to investigate what's happening with the ws when any of the unresponsive states occur.

---

1. Unless there's a flaw in how websocket connections are handled in d.js, this should not happen, the bot appears online but it does not receive any events from what I have seen, due to this, I'm unable to investigate as I'd need an external connection (not via Discord) to evaluate in the bot's context while it's idle.

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 10.2.1
- Operating system: Ubuntu 16.04.3 LTS (Xenial Xerus)
- Priority this issue should have – please be realistic and elaborate if possible: Low, it only happens after outages, and 1/4 possibilities (either the events die but the bot remains online, the bot appears offline but the process is still going on, or it's online but with all guilds "empty", or d.js "recovers" from the outage correctly).

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:
  - [`6cde6de`](https://github.com/discordjs/discord.js/commit/6cde6deceee975d76ea3abf40e87bd6ab04655f7) (main bot)
  - [`841b9de`](https://github.com/discordjs/discord.js/commit/841b9de918ea96a902c55414d641de5a0aee3caf) (secondary bot).

**Comment by MerriemWeebster** [comment]
Been experiencing web socket hangups after reinstalling discord.js along with crazy pings, and I host on heroku...

**Comment by kyranet** [comment]
Socket hangups and Discord API/Gateway outages aren't the same thing. I haven't get a socket hangup for months, but Discord has been stable-ish for quite some time, so it's extremely hard to properly reproduce this issue. It's not in the bots' end, it's in Discord's end.

**Comment by MerriemWeebster** [comment]
Sorry for the false report, I ended up finding out that the gc_global flag was causing these hang ups for some reason, solved the issue.

**Comment by kyranet** [comment]
Closing due to the issue being stale, the WS being completely rewritten and fixed, and not having reconnection errors (with them fixed, this issue is literally impossible to reproduce).

It was a funny issue to find, but I doubt this exists nowadays.
