### ISSUE TITLE
voiceConnection.play seek option doesn't work on master

### ISSUE THREAD

**Issue by G0BL1N** [discordjs/discord.js#2572]
**Please describe the problem you are having in as much detail as possible:**

So `connection.playFile(path, { seek: 120 })` works perfectly fine on v11
And `connection.play(path, { seek: 120 })` just doesn't work on master

The problem is, `-ss` argument doesn't get attached to ffmpeg arguments
https://github.com/discordjs/discord.js/blob/stable/src/client/voice/player/AudioPlayer.js#L100
https://github.com/discordjs/discord.js/blob/master/src/client/voice/player/BasePlayer.js#L48
Dirty fix like this
```js
    const args = isStream ? FFMPEG_ARGUMENTS : ['-i', input, ...FFMPEG_ARGUMENTS];
    args.push('-ss', String(options.seek || 0))
```
works, but i don't want to PR it, because there is probably a better way to do it and i don't know if this covers all cases.

**Further details:**

- discord.js version: master
- node.js version: v9.1.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Hi,

Thanks for bringing up the issue, I've reimplemented the seek option using a slightly modified version of your suggestion, as a side note to anyone else coming across this issue, `seek` will only work when you're playing a stream through FFmpeg, which means playing `webm/opus` or `ogg/opus` streams will cause the seek option to be ignored.
