### ISSUE TITLE
MessageReaction.fetchUsers() .after and .before doesn't limit fetched users

### ISSUE THREAD

**Issue by shukriadams** [discordjs/discord.js#2574]
**Please describe the problem you are having in as much detail as possible:**
When I do perform the following three calls I get the same array of users back

    MessageReaction.fetchUsers(100, {  })
    MessageReaction.fetchUsers(100, { after : "someUserId"})
    MessageReaction.fetchUsers(100, { before : "someUserId"})

The results array includes the same user whose id was used as the before or after argument. I would expect, based on the documentation, that the user id specified would be used as the start or end index in the list of data being queried, and therefore not returned as part of the result set. Right now .before and .after appear to have no affect on the results returned.

**Include a reproducible code sample here, if possible:**
```js

let fetchedUsers = await myMessageReaction.fetchUsers(100, {  });
fetchedUsers = fetchedUsers.array(); // fetchuser contains expected user.id= 'x'

fetchedUsers = await myMessageReaction.fetchUsers(100, {  after : 'x' });
fetchedUsers = fetchedUsers.array(); // fetchuser still contains user.id= 'x'

fetchedUsers = await myMessageReaction.fetchUsers(100, {  before : 'x' });
fetchedUsers = fetchedUsers.array(); // fetchuser still contains user.id= 'x'

```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.11.2
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
Can you try the `11.3-dev` branch and see if the results are more desirable?
You may install it by running `npm i discordjs/discord.js#11.3-dev`

**Comment by amishshah** [comment]
This issue seems inactive so I am closing it, if you still face the issues after following the above steps please re-open this issue.
