### ISSUE TITLE
<Voice Channel>.join(); Timeouts and Cache Problems.

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#2578]
**Please describe the problem you are having in as much detail as possible:**
When the bot fails to join the voiceChannel with timeouts, the voiceChannel stays in client.voiceConnection even though the bot isn't really on that voiceChannel, breaking the whole voice part of my bot in that guild. This timeout error also can't be used with .catch also. so I used process.on(error) to catch it. In order to get the voice functionality on the guild to be back, I did a manual checking on client.on(ready) that automatically tries to leave the voice channel then delete the cache of it.
```js
setInterval(() => {
		let connections = client.voiceConnections
		connections.forEach(guilds => {
			let guildID = guilds.channel.guild.id;
			let musicRadio = bot.moeCheck.has(guildID);
			let voiceBox = bot.voiceCheck.has(guildID);
			let musicQueue = bot.queue.has(guildID)
			if (musicRadio || voiceBox || musicQueue) return;
			else {
			    try {
				    guilds.channel.leave();
				    client.voiceConnections.delete(guildID)
			    } catch (e) {
			        console.error(e)
			    }
		    }
		});
	}, 15000);
```

**Include a reproducible code sample here, if possible:**
Additional note, setting something in a map after trying to join the channel can also cause this.
```js
voiceChannel.join().then(voiceConnected => {
     map.set(key, values)
});
```
Actual Stuff 
```js
exports.run = async (client, args, bot, msg, command) => {
	const voicechk = bot.voiceCheck.get(msg.guild.id)
	const voiceChannel = msg.member.voiceChannel;
	const checkerBuild = {voiceChannel: voiceChannel}
	if (voicechk) return msg.channel.send('Teitoku-san, I am currently Playing a Voice Box. **Wait for it to end before invoking another one** Ufufu♪');
		if (!voiceChannel)
			return msg.channel.send('You are **not in the Voice Channel** Teitoku ~');
		bot.voiceCheck.set(msg.guild.id, checkerBuild);
		voiceChannel.join().then(voiceConnected => {
		    let voiceBoxPlay = voiceConnected.playStream('http://kure.kancollewiki.net/images/0/01/Kashima-Construction.mp3', {seek: 0});
		    voiceBoxPlay.once('start', () => {
        	    voiceConnected.player.streamingData.pausedTime = 0;
        	    voiceConnected.player.streamingData.timestamp = 0;
            });
			voiceBoxPlay.setVolumeLogarithmic(5 / 10);
	        voiceBoxPlay.once('end', async () => {
	        try {
	            await voiceChannel.leave()
	            bot.voiceCheck.delete(msg.guild.id);
	        } catch (err) {
	        console.error(error)
	        }
	    });
	}).catch(err => {
	console.error(err)
	});
}
```

**Further details:**

- discord.js version: 11.3-dev
- node.js version: 8.11.0
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Medium, because I'm not sure whether this is a isolated case or not.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Can you try using the master branch and see if the issue persists?

**Comment by Deivu** [comment]
I'll try to do that as soon as I have the time. Thanks for the response

**Comment by hydrabolt** [comment]
Hi, any update on the status of this issue?

**Comment by Deivu** [comment]
Still present on some occassions on 11.3-dev. 

The rewrite on v12 is far from completion so I cannot say yet

**Comment by Deivu** [comment]
Update: Looks like the **Join before setting a map** was Fixed in master.
Code
```
const connection = await msg.member.voiceChannel.join();
const song = await addVideo(msg, video);
queueConstruct.songs.push(song);
client.queue.set(msg.guild.id, queue);
```
I'm not yet sure about the 15 seconds timeout error if its catch-able but since I haven't encountered that yet in my master code.

**Comment by amishshah** [comment]
Ok, in the above commit I think I might have fixed this issue, could you try it out for me?

**Comment by Deivu** [comment]
I'll update once I have tried it out.

**Comment by Deivu** [comment]
Update, this is still happening

The error happens still on when the bot tries to join the Voice Channel. I handle the errors correctly with try catch wrapped around them inside an async function. I also listen for the client.on error event so I think this is an issue with d.js itself. Also I noticed that the more this 'error' happens, the more voice connection cache it leaves and it doesn't get still deleted.

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at VoiceConnection.emit (events.js:171:17)
    at VoiceWebSocket.ws.on.err (/root/KashimaProd/node_modules/discord.js/src/client/voice/VoiceConnection.js:387:32)
    at VoiceWebSocket.emit (events.js:182:13)
    at VoiceWebSocket.onError (/root/KashimaProd/node_modules/discord.js/src/client/voice/networking/VoiceWebSocket.js:149:10)
    at WebSocket.onError (/root/KashimaProd/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (/root/KashimaProd/node_modules/ws/lib/websocket.js:528:10)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
```

Code:
```js
    try {
        client.joinCheck.add(msg.guild.id);
        await msg.member.voice.channel.join();
        await m.edit('\:white_check_mark: Teitoku ♪ **I am now in your Voice Channel**, you can now use the commands **play**, **playmoe** or **voicequote**. But Teitoku, **I will auto leave in 1 minute** if you did not use the Voice Functions.');
        client.joinCheck.delete(msg.guild.id);
    } catch (error) {
        await m.edit(`\:x: Teitoku, I looks like **I cannot join here.** More info: **${error}**. Please wait a bit and Try Again.`);
    };
```

**Further details:**
- discord.js version: Discord.js Master, Commit 'ab0ede0'
- Node.js version: 10.9.0
- Operating system: Ubuntu 16.04 LTS

**Comment by kyranet** [comment]
You're not listening to VoiceConnection#error: https://discord.js.org/#/docs/main/master/class/VoiceConnection?scrollTo=e-error

**Comment by Deivu** [comment]
Thanks for clarifying that, I'm not yet sure about the underlying cache, but I will observe this further and report back if the 'Voice Connection' cache isn't clearing properly like how it supposed to do

**Comment by amishshah** [comment]
Any update on this situation @Deivu?

**Comment by Deivu** [comment]
as of now, the voiceConnection properly rejects now if it do time out. But I haven't tested the latter which is the issue of setting a map after the voice.join() resolves.

**Comment by amishshah** [comment]
If you can still reproduce, please re-open, I'm assuming this issue is fixed due to inactivity.
