### ISSUE TITLE
[Ratelimits] Snekfetch 4.x breaks ratelimits

### ISSUE THREAD

**Issue by kyranet** [discordjs/discord.js#2581]
**Please describe the problem you are having in as much detail as possible:**

After https://github.com/discordjs/discord.js/commit/46af6e3396e94f795c7f539035a36e733139be07 landed, 429 HTTP errors aren't handled as well as before that commit (for example, https://github.com/discordjs/discord.js/commit/c8ecbe6585a615e77deb5f04bf64a9675e73fb41).

I have tested in two bots, my production bot, with commit https://github.com/discordjs/discord.js/commit/6cde6deceee975d76ea3abf40e87bd6ab04655f7, which handled ratelimits correctly, and my test bot, with commit https://github.com/discordjs/discord.js/commit/5071477172053ef9d274aaab16cec0cfbd25b860, which threw a lot of 429 errors to console:

![image](https://user-images.githubusercontent.com/24852502/41027023-5523987a-6976-11e8-9853-844c0dad36e0.png)

Furthermore, I have checked `this.client.rest.handlers`, and got the following:

```javascript
{ '/gateway':
   RequestHandler {
     manager: [RESTManager],
     client: [Smii],
     handle: [Function: bound sequential],
     limit: NaN,
     resetTime: NaN,
     remaining: NaN,
     queue: [],
     busy: false },
  '/oauth2/applications/@​me':
   RequestHandler {
     manager: [RESTManager],
     client: [Smii],
     handle: [Function: bound sequential],
     limit: NaN,
     resetTime: NaN,
     remaining: NaN,
     queue: [],
     busy: false },
  '/channels/339948984351326208/typing':
   RequestHandler {
     manager: [RESTManager],
     client: [Smii],
     handle: [Function: bound sequential],
     limit: 5,
     resetTime: NaN,
     remaining: 4,
     queue: [],
     busy: true },
  '/channels/339948984351326208/messages':
   RequestHandler {
     manager: [RESTManager],
     client: [Smii],
     handle: [Function: bound sequential],
     limit: 5,
     resetTime: NaN,
     remaining: 4,
     queue: [],
     busy: false },
  '/channels/339948984351326208/messages/:id':
   RequestHandler {
     manager: [RESTManager],
     client: [Smii],
     handle: [Function: bound sequential],
     limit: 5,
     resetTime: NaN,
     remaining: 0,
     queue: [],
     busy: false } }
```

**Downgrading to https://github.com/discordjs/discord.js/commit/c8ecbe6585a615e77deb5f04bf64a9675e73fb41 fixes the issue!**

**Include a reproducible code sample here, if possible:**

Install https://github.com/discordjs/discord.js/commit/46af6e3396e94f795c7f539035a36e733139be07 and make your bot send 6 messages in less than a second (to fill the bucket and make it set busy true).

**Further details:**

- discord.js version: master
- node.js version: 10.3.0
- Operating system: Ubuntu 16.04.3 LTS (Xenial Xerus)
- Priority this issue should have – please be realistic and elaborate if possible: High, I'm not the only one who reproduces this issue, several developers with massive bots have experienced this issue and they're currently getting many errors.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: https://github.com/discordjs/discord.js/commit/5071477172053ef9d274aaab16cec0cfbd25b860

**Comment by AdityaTD** [comment]
I was able to replicate this issue on my bot, this should be fixed on priority in my opinion.
