### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])

### ISSUE THREAD

**Issue by AWEFUME** [discordjs/discord.js#2584]
I am getting this error whenever I try to run the bot. I do not know what to do, as I have tried all possible solutions I can think of.

`events.js:143`
`      throw err;`
`      ^`
` `
`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])`
`    at Client.emit (events.js:141:19)`
`    at WebSocketConnection.onError (C:\Users\AWEFUME\Desktop\Shheyld\Shheyld-bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)`
`    at WebSocket.onError (C:\Users\AWEFUME\Desktop\Shheyld\Shheyld-bot\node_modules\ws\lib\event-target.js:128:16)`
`    at WebSocket.emit (events.js:160:13)`
`    at WebSocket.finalize (C:\Users\AWEFUME\Desktop\Shheyld\Shheyld-bot\node_modules\ws\lib\websocket.js:185:12)`
`    at ClientRequest._req.on (C:\Users\AWEFUME\Desktop\Shheyld\Shheyld-bot\node_modules\ws\lib\websocket.js:641:12)`
`    at ClientRequest.emit (events.js:160:13)`
`    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)`
`    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)`
`    at TLSSocket.socketOnData (_http_client.js:439:20)`

**Comment by iCrawl** [comment]
https://github.com/discordjs/discord.js/issues/2523
