### ISSUE TITLE
Direct Message someone

### ISSUE THREAD

**Issue by EGGamer** [discordjs/discord.js#2590]
How can I Direct Message someone through discord.js ? I want for when someone puts a command in # commands , it sends me a message that, a user has wrote that command. And with the message that the user wrote too. IDK if its possible. But I hope so.

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
