### ISSUE TITLE
Emitter In Events

### ISSUE THREAD

**Issue by Skillz4Killz** [discordjs/discord.js#2591]
**Please describe the problem you are having in as much detail as possible:**
When events are emitted there is no way to know who actually emitted that event. For example, `messageDelete` event currenly when emitted is only passing a `Message` argument for the message that was deleted. But who deleted that message? Who caused that event to be emitted.

Currently, the only solution is to have to fetch audit logs for every single type of event. Instead it would be much better if discord.js was to provide this information by default instead of users having to fetch logs. As an example, the messageDelete event would be changed to:

messageDelete(message, emitter) 

Where `message` is the *Message* object that was deleted and `emitter` is the *Member* object of the member that caused the event to be emitted.

**Include a reproducible code sample here, if possible:**
![image](https://user-images.githubusercontent.com/23035000/41196384-cb9e020e-6c0c-11e8-9d8c-bb74a0bdb88f.png)

**Further details:**

- discord.js version: master
- node.js version: 10.0
- Operating system: Mac OS X
- Priority this issue should have – please be realistic and elaborate if possible: Low(its a nice enhancement but not 100% necessary)

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
We would basically be making the call for you and re-emitting the event. We don't do these things when permissions are a factor- it is up to you to do it yourself. It would also terribly slow down every single event as we have to make a slow call to the API. I don't believe we should be assuming you need to fetch things for you, the API should provide it.

**Comment by iCrawl** [comment]
Sounds nice in theory, is bad in practice.

We forward Discord events with minimal processing for the library to function properly. Adding such a feature in there would immensely complicate the whole situation while also not ensure you would get a proper member. 

Audit logs can be fetched and you can do that yourself as you mentioned, but they have no guarantee to show up in time, it could take 1sec or 10sec or even longer. 

How long do you want us to wait for it before emitting that someone has deleted a message? We know as much as you do when it comes to getting events from Discord, so we would have to do all the audit logs fetching for you.

No from me.

**Comment by hydrabolt** [comment]
I also disagree with this for all the reasons Crawl listed above, too much overhead for discord.js, if you really want it I'd suggest making a wrapper around discord.js that adds this.
