### ISSUE TITLE
use streams as message content

### ISSUE THREAD

**Issue by HelloEdit** [discordjs/discord.js#2593]
Hi,

I recently tried to use streams as message content with Discord.js, without success. I asked the question about the server but had not received an answer, I concluded that it was not possible at this time.

index.js
```js
const d = require("discord.js");
const fs = require("fs");

const bot = new d.Client();

bot.login(token);

bot.on("ready", () => {
  const channel = bot.channels.get(id);
  const stream = fs.createReadStream("./hello.txt");
  channel.send(strem).catch(console.log);
});
```

hello.txt
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

The resulting error is as follows:
```
{
DiscordAPIError: Cannot send an empty message
    at item.request.gen.end (/mnt/c/Users/edit/Documents/Project/github/test- 
    stream/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)    at then 
    (/mnt/c/Users/edit/Documents/Project/github/test- 
    stream/node_modules/snekfetch/src/index.js:215:21)    at process._tickCallback 
    (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Cannot send an empty message',
  path: '/api/v7/channels/id/messages',
  code: 50006
}
```

**Comment by YoussefElshemi** [comment]
Can you log 'stream' and show the contents of it? it might not be a string

**Comment by HelloEdit** [comment]
The following code

```js
const d = require("discord.js");
const fs = require("fs");

const bot = new d.Client();

bot.login(token);

bot.on("ready", () => {
  const channel = bot.channels.get(id);
  const stream = fs.createReadStream("./hello.txt");
  stream.pipe(process.stdout);
});
```

log this:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Also, of course a stream is not a string, it's a data stream containing a string. It is one of the most powerful concepts of node js but one of the least understood.

https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93

**Comment by Dev-Yukine** [comment]
First off, Textchannel#send was never supposed to handle streams. You can easily just get all chunks of the stream to an Buffer yourself in less then 10 lines and send the buffer instead. i personally disagree that Textchannel#send should accept streams since that doesn't match the actuall behavior of what you can send in a channel.

**Comment by appellation** [comment]
I tend to agree that streams should be sendable.  Streams are an integral part of asynchronous data transmission in node and can have significant performance buffs when you don't have to cache the entire stream into a buffer in order to send it.

**Comment by HelloEdit** [comment]
for example, if my file was 5 Giga, I would be obliged with the current approach to convert it into a buffer and thus allocate 5 giga of RAM. while the stream of this file would be much lower. After, I know you do not send 5 Giga text files via discord but some have it text would gain to be in stream form

**Comment by lloti** [comment]
Boi the max you can send is 8mb over the Discord API.

**Comment by HelloEdit** [comment]
@Iloti we are talking about stream, no attached file

**Comment by KozalakliKozalak** [comment]
But I don't think it'll work with discord itself since messages are only strings and message attachments are just files. I don't actually get why we'd need to use streams on text channels. Even you got an actual ai with language processing I don't see any point in using streams. Also I don't think I should remind there is character limit by Discord api itself.

**Comment by Dev-Yukine** [comment]
I was never saying that streams are buffers, i was saying that you could create the stream with as example `js
const stream = fs.createReadStream("./hello.txt");
`
and then easily just do 
`js
let data = '';
stream.on('data', chunk => data += chunk)
`
and then 
`js
stream.on('end', () => message.channel.send(data))
`

This is literally 4 lines you need to add to send a stream to a Textchannel so i dont know if Textchannel#send should get *another* overload for this.

**Comment by HelloEdit** [comment]
Streams are a data stream that allows you to use less RAM with great flexibility. I opened this issue to ask the question of the support of the streams by discord.js because no one had answered me on the server.

Also, I would understand perfectly that discord.js does not integrate streams but I think it would be a fracture that many would like, especially since it is part of the asynchronous process as said above

**Comment by HelloEdit** [comment]
@Dev-Yukine But that makes losing the interest of the stream. It amounts to storing the entire file in RAM, where the string uses very little RAM. Your solution actually works but I do not think that's the best approach.

**Comment by Dev-Yukine** [comment]
I understand what you want to achieve but i dont even know if Discords Rest API even support chunked request regarding to sending a Message 🤔.

**Comment by HelloEdit** [comment]
REST cannot support streams. But Discord.js uses websockets to communicate with Discord, based on the same philosophy as streams. I can't say because I'm not an expert in WS but I think the technologies are compatible.

**Comment by lloti** [comment]
Yeah but messages are sent with HTTP POST requests 🤔

**Comment by bdistin** [comment]
Sending messages is over the REST api, not the WebSocket though... We recieve messages over the WebSocket, but not send.

**Comment by HelloEdit** [comment]
I was not aware of that. The stream loses all interest via REST because it must be complete for sending. The only solution would be to go through WS to send a message, wich is not currently the case.
