### ISSUE TITLE
acceptInvite deprecated

### ISSUE THREAD

**Issue by mercxry** [discordjs/discord.js#2597]
Hello,
I just want to warn that _ClientUser.acceptInvite()_ is deprecated as stated on the Discord API Docs: https://discordapp.com/developers/docs/resources/invite#accept-invite

Please add a warning on the docs:
https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=acceptInvite

**Comment by MrJacz** [comment]
This has already been removed in master.
