### ISSUE TITLE
Undefined target in return of audit log when fetching CHANNEL_DELETE

### ISSUE THREAD

**Issue by xonrsoftware** [discordjs/discord.js#2598]
**Please describe the problem you are having in as much detail as possible:**
Undefined target in return of audit log when fetching CHANNEL_DELETE.

**Include a reproducible code sample here, if possible:**
```js
client.guilds.get('GUILDID').fetchAuditLogs({
        type: 'CHANNEL_DELETE',
        limit: 1
    }).then(audit => {
            console.log(audit.entries.first().target);
	}
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.11.2
- Operating system: Debian GNU/Linux 9.4 (stretch)
- Priority this issue should have – please be realistic and elaborate if possible: High.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by queezly** [comment]
The changes do not include the target in any way, however the API does provide target_id with the raw request
```js
{ target_id: '456996543753486338',
  changes: [Array],
  user_id: '83886770768314368',
  id: '456998633175384065',
  action_type: 12 }
```
This would be immensely useful for actionlogs since you could then check for the target_id on `channelDelete` instead of just fetching the last auditlog and hoping for it to actually be the action causing the event to fire

**Comment by xonrsoftware** [comment]
@queezly Code was minimized for test, i already modifed /src/structures/GuildAuditLogs.js to return target_id, with proper checks in code, but i think we need to follow format of other returns. Need to assigment this.target.id to data.target_id if action = CHANNEL_DELETE. High because of missing returning data.

**Comment by appellation** [comment]
There are very tentative plans to re-implement partial structures, which would solve this issue.  In the meantime, it does seem like this is an oversight.

**Comment by Lewdcario** [comment]
Resoled in 886c21223ec63f6a938ee4665ddcd8fdfff64a24
