### ISSUE TITLE
author.dmOpen

### ISSUE THREAD

**Issue by Skillz4Killz** [discordjs/discord.js#2599]
**Please describe the problem you are having in as much detail as possible:**
There is no easy method to tell if a user has DM's open, and this forces sending a request to the API to send a message getting back an error to check if the DM was sent or not.

Currently, i have to send a request to the API to send a message and catch it to see if it failed to know that dm was not able to send to X user. 

Current form
```js
msg.author.send().catch(e => { // dms are blocked do X})
```

Suggested
```js
if (!msg.author.dmOpen) { return // DMs are blocked do X }
msg.author.send()
```

EDIT: Is this missing because there is no way to check this from the discord API directly? Should I send a suggestion to discord API instead?

**Include a reproducible code sample here, if possible:**
```js
N/A
```

**Further details:**

- discord.js version: master
- node.js version: 10.1.0
- Operating system: Mac OS X
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by appellation** [comment]
There is no way to determine whether a DM channel can be opened without first attempting to open one. This is a limitation of the Discord API.

**Comment by Skillz4Killz** [comment]
Thank you. I will try and request this on the API repo.
