### ISSUE TITLE
channel.setPosition(); is fuckin broken

### ISSUE THREAD

**Issue by MomsSpaghetti** [discordjs/discord.js#2616]
OII Cunts, channel.setPosition(); does not fuckin work, has not worked in any others versions that i have used it in either.

**Comment by Tylertron1998** [comment]
This isn't how you open an issue and get things resolved, be civil you primate.

**Comment by MomsSpaghetti** [comment]
Tylertron1998 go and fuck yourself. 😄

**Comment by eponymz** [comment]
Honestly, this should be closed simply due to the disrespect in it. Not to mention i'm pretty sure there are rules for opening issues to this repo.

**Comment by Gawdl3y** [comment]
What a fantastic way to completely discredit yourself. I just tested it, and `Channel#setPosition` appears to be entirely functional. You have not provided an error or description of the issue whatsoever, and have completely disregarded the issue template.
