### ISSUE TITLE
How make "Bot playing in..."

### ISSUE THREAD

**Issue by XomkaShou** [discordjs/discord.js#2617]
NodeJS - 10.5
DiscordJS - 11.3.2

i'm trying:

const Discord = require(`discord.js`);

const client = new Discord.Client();

client.user.setPresence({ game: { name: 'nya', type: 0 } });

but nope

help pls

**Comment by hydrabolt** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
