### ISSUE TITLE
Hanging behaviour when executing a mass operation

### ISSUE THREAD

**Issue by axc450** [discordjs/discord.js#2618]
**Please describe the problem you are having in as much detail as possible:**
I own a large discord server (50k+ members). I am trying to select around 2000 specific members and give them a role. I am aware of rate limitations. However, the following code just hangs every 50 or so members, infinitely stuck waiting for the await which never resolves:

**Include a reproducible code sample here, if possible:**

`users` is an array of `GuildMember`

```js
for (var i = 0; i < users.length; i++)
    {   
        const user = users[i]
        
        if(!user || user.user.bot)
        {
            console.log("Could not process user: " + userID)
            continue
        }
        
        console.log("before")
        await user.addRole(role).then(console.log(i)).catch(e => console.log("Error: " + e))
        console.log("after")
    }
```

Here is the output:

```
before
1495
after
before
1496
after
before
1497
```

The code hangs here

**Further details:**

- discord.js version: 11.3.2 stable
- node.js version: 8.1.3
- Operating system: Tested on macOS laptop and Ubuntu VPS
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by appellation** [comment]
This seems to be related to #2550.  Addtionally, there have been some issues with ratelimiting in discord.js which #2615 will resolve.  In the meantime, can you please try this using a bot account on the latest master version of discord.js?

**Comment by axc450** [comment]
Master seems to fix this 👍

**Comment by MuradKerimli** [comment]
asdasd
