### ISSUE TITLE
Sharding fails because env does not pass.

### ISSUE THREAD

**Issue by CatsMiaow** [discordjs/discord.js#2627]
- discord.js version: master
- node.js version: v8.11.2
- Operating system: Window 10 v1709

https://github.com/discordjs/discord.js/blob/master/src/sharding/Shard.js#L37
`manager.args` is not found of `ShardingManager`

https://github.com/discordjs/discord.js/blob/master/src/sharding/Shard.js#L99
So, by default, this.args is not [], so env is not passed and sharding fails.

```js
this.args = manager.shardArgs;
```
Fixed the code.

**Comment by BigBrainAFK** [comment]
did u try the internal-sharding branch? it has a bit different code

**Comment by CatsMiaow** [comment]
The code changed in https://github.com/discordjs/discord.js/commit/bfbb723f4293c883172d977e4451104b8cfe42b7

**Comment by iCrawl** [comment]
This should be fixed in master again.

**Comment by CatsMiaow** [comment]
Fixed in 6b3bfdd7dede049ba592e94ef1b1acc40a5e37fe
