### ISSUE TITLE
Embed markup not compiling on mobile device

### ISSUE THREAD

**Issue by mpheinze** [discordjs/discord.js#2628]
**Please describe the problem you are having in as much detail as possible:**
I have an object-based embed with a markdown formatted title. The title is formatted with both bold text ** underscores __. The embed compiles the title correct in the laptop application, but not in the Android version where the actual markdown language gets compiled.

**Include a reproducible code sample here, if possible:**
```js
message.channel.send({embed: {
    title: `__**${event_data.event.name}**__`,
}});
```

Here is how it is compiled on the laptop application:
![markup_laptop](https://user-images.githubusercontent.com/14307754/41862029-27c9384e-78a3-11e8-9419-c668a150b772.PNG)

And here is how the android app compiles it:
![markup_mobile](https://user-images.githubusercontent.com/14307754/41862042-32922b82-78a3-11e8-8950-e618478e9183.jpg)

**Further details:**

- discord.js version: 11.3.2
- node.js version: 10.4.1
- Operating system: Win 10/Android 8.0.0
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Thats not something we can change, thats on discords end.

**Comment by mpheinze** [comment]
Okay, that's fair enough. Thank you for the quick reply.

**Comment by PLASMAchicken** [comment]
https://trello.com/c/dpEwySIm/116-bold-isnt-working-in-embed-box
