### ISSUE TITLE
Role object not complete when using Guild constructor

### ISSUE THREAD

**Issue by Ciborn** [discordjs/discord.js#2632]
**Please describe the problem you are having in as much detail as possible:**
When I use the Guild constructor to extend the Guild class of 'discord.js'.Structures, it seems that there is only the Guild object in the first role being built and so the bitfield of the permissions of it is undefined, which causes the following error:
```
(node:15088) UnhandledPromiseRejectionWarning: RangeError [PERMISSIONS_INVALID]: Invalid permission string or number.
    at Function.resolve (C:\Discord\Tranquility\node_modules\discord.js\src\util\Permissions.js:137:11)
    at new Permissions (C:\Discord\Tranquility\node_modules\discord.js\src\util\Permissions.js:17:38)
    at Role._patch (C:\Discord\Tranquility\node_modules\discord.js\src\structures\Role.js:61:24)
    at new Role (C:\Discord\Tranquility\node_modules\discord.js\src\structures\Role.js:21:20)
    at Map.add (C:\Discord\Tranquility\node_modules\discord.js\src\stores\DataStore.js:21:32)
    at Map.add (C:\Discord\Tranquility\node_modules\discord.js\src\stores\RoleStore.js:17:18)
    at Guild._patch (C:\Discord\Tranquility\node_modules\discord.js\src\structures\Guild.js:211:49)
    at new Guild (C:\Discord\Tranquility\node_modules\discord.js\src\structures\Guild.js:73:12)
...
```

**Include a reproducible code sample here, if possible:**
```js
const { Structures } = require('discord.js');
module.exports = Structures.extend('Guild', BaseGuild => {
    return class Guild extends BaseGuild {
        constructor(client, data) {
            super(client, data);
        }
    }
});
```

**Further details:**

- discord.js version: v12.0.0-dev (master)
- node.js version: v10.3.0
- Operating system: Windows 10 v1803
- Priority this issue should have – please be realistic and elaborate if possible: Minor

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: f711aa3

**Comment by bdistin** [comment]
D.JS creates all the instances of that class based on data packets received over the WebSocket connection? The token used is in a couple guilds, with many roles and users.

**Comment by Ciborn** [comment]
The error is throwed in the only case where I extend the class to use it instead of the normal one. There is no problem when using the Guild object as it's given.

**Comment by bdistin** [comment]
That's not how Structures works. When you extend a class with Structures, you are creating a new base class for all guilds to be initiated from. D.JS still initiates all of the guilds itself.

```js
const { Structures } = require('discord.js');
Structures.extend('Guild', Guild => {
    return class MyGuild extends Guild {
        constructor(client, data) {
            super(client, data);
        }
    }
});
```
With that, all guilds in <Client>.guilds are instances of MyGuild, instead of the base Guild from D.JS.

**Comment by Ciborn** [comment]
Ok then, thanks for the help and sorry for bothering you.
