### ISSUE TITLE
"reactions.remove() is not a function", but it is.

### ISSUE THREAD

**Issue by MrRedstonePro** [discordjs/discord.js#2638]
It says: reactions.remove() is not a function. But according to the docs it is. https://discord.js.org/#/docs/main/stable/class/MessageReaction?scrollTo=remove
https://hastebin.com/urizafexum.php

**Comment by SpaceEEC** [comment]
Please fill out the issue template we provide, we can't help you otherwise:
![image](https://user-images.githubusercontent.com/24881032/42084597-66e38758-7b8e-11e8-9e2c-95058785ecd5.png)

**Comment by MrRedstonePro** [comment]
**Please describe the problem you are having in as much detail as possible:**
I am attempting to remove a reaction a user placed with reactions.remove()

**Include a reproducible code sample here, if possible:**

https://hastebin.com/urizafexum.php

**The log of me outputs this:**
// When someone but the message author reacts, it logs:
reactions.remove is not a function

Further details:

discord.js version: 11.3.2
node.js version: 8.11.3
Operating system: Windows

**Comment by SpaceEEC** [comment]
`Message#awaitReactions` returns a promise that resolves with a `Collection`
See [docs](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=awaitReactions).
