### ISSUE TITLE
Throwing WS_CONNECTION_TIMEOUT Error on Linux

### ISSUE THREAD

**Issue by Ciborn** [discordjs/discord.js#2639]
**Please describe the problem you are having in as much detail as possible:**
The bot is throwing the error WS_CONNECTION_TIMEOUT exactly 5 minutes after being started, when on master branch. This only happens on Linux devices.

**Further details:**
- discord.js version: v12.0.0-dev
- node.js version: v9.11.2
- Operating system: Raspbian (Kernel v4.14) (Debian 9)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: bcdb801

**Comment by SpaceEEC** [comment]
What does logging the debug event print to console?
`client.on('debug', console.log);`
If that does not yield anything useful consider also logging the raw event:
`client.on('raw', console.log);`

**Comment by Ciborn** [comment]
It seems that the error was temporary, everything is fine now. Sorry for bothering you.
