### ISSUE TITLE
getaddrinfo EAI_AGAIN while trying to connect via token

### ISSUE THREAD

**Issue by not-idol** [discordjs/discord.js#2642]
**Please describe the problem you are having in as much detail as possible:**
While trying to connect via token, console throws following error:
```
Error: getaddrinfo EAI_AGAIN discordapp.com:443
```
code where error gets logged: 
```
client.login(process.env.BOT_TOKEN).then( () => {
  console.log('')
}).catch( (e) => {
  console.log('error' + e)
});
```
i think its a issue related to discord right? so best bet is to wait?

**Further details:**

- discord.js version:
- node.js version: discord.js@11.3.2
- Operating system: linux. ubunutu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
This isn't a discord.js issue- it appears as the Discord's DNS is having issues with connecting as it's occurring on many bots. As you said, your best bet is to wait.

**Comment by not-idol** [comment]
okay thanks! hope discord fixes that soon :>
