### ISSUE TITLE
client/rest/RESTMethods.js - function createGroupDM passes array instead of dictionary for property "nicks" to backend

### ISSUE THREAD

**Issue by FleshMobProductions** [discordjs/discord.js#2646]
**When the method createGroupDM from RESTMethods.js is called (for example by calling createGroupDM on a ClientUser) a json object is sent to the server that does not conform with the backend API**

**Here is the function code from createGroupDM in RESTMethods.js**
```js
createGroupDM(options) {
    const data = this.client.user.bot ?
      { access_tokens: options.accessTokens, nicks: options.nicks } :
      { recipients: options.recipients };
    return this.rest.makeRequest('post', Endpoints.User('@me').channels, true, data)
      .then(res => new GroupDMChannel(this.client, res));
  }
```

If case the client is a bot, options.nicks get passed for the nicks attribute. This parameter is a string array in the code. Looking at the backend API, the nicks attribute requires to be "a dictionary of user ids to their respective nicknames"

https://discordapp.com/developers/docs/resources/user#create-group-dm

function parameter description from the API documentation of discord: 

JSON Params
Field                | Type                 | Description

access_tokens | array of strings | access tokens of users that have granted your app the gdm.joinscope
nicks                | dict                   | a dictionary of user ids to their respective nicknames

**Further details:**

- discord.js version: ^11.3.2
- node.js version: v9.4.0
- Operating system: Windows 10 x64 Professional

- [x] I found this issue while running code on a bot account
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
This bug was fixed with (f23b61794c8bce64bfc63fb2bcd82849c5416bbe).
Will be available with `11.4` (no ETA) or is already by installing the `11.3-dev` branch from github.
