### ISSUE TITLE
Socket hangs up if you try to reply with an embed

### ISSUE THREAD

**Issue by TechyManTM** [discordjs/discord.js#2651]
**Please describe the problem you are having in as much detail as possible:**
If you'll try to reply with an embed, e.g. message.reply(embed), you'll first get _UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON_
and then the socket will hang up.
**Include a reproducible code sample here, if possible:**
`var embed = new Discord.RichEmbed()
.setTitle("Test")
message.reply(embed)`
**Further details:**

- discord.js version: master
- node.js version: 10.6.0
- Operating system: Windows 10 x32

**Comment by theeighthcow** [comment]
Reproducible

**Comment by SpaceEEC** [comment]
Your code looks like you are running stable (11.3.2), or some commit of 11.3-dev.
I can reproduce it there (11.3-dev [d81441f627efef83a7d3bd125ee2f46c118ccfc9] and stable [11.3.2]).
Not reproducible on latest master however (using MessageEmbed instead of RichEmbed).

**Comment by queezly** [comment]
CR, master (95b2dd3fe63ec9b6c7cec4f63f8276f4d907f228) does not crash but also doesn't mention.
When sent in accordance to docs providing an empty string as first parameter:
```js
var embed = new Discord.RichEmbed() .setTitle("Test") 
message.reply("", {embed: embed})
```
It works on stable and master with the mention in message content

**Comment by SpaceEEC** [comment]
Fixed both queezly's observation about `Message#reply`'s incorrect behavior on master,
as well the initially reported bug on 11.3-dev with the referenced commits.
