### ISSUE TITLE
Code within join().then() not executing

### ISSUE THREAD

**Issue by ShaunodCIT** [discordjs/discord.js#2652]
Hi there. I am having an issue with the `voiceChannel.join().then()` method.

NOTE: All code mentioned is wrapped with the follow `async` function `bot.on("message", async message => {// code here. });`
Here is the code:
```
// The prefix is !
if (cmd === `${prefix}join`) {
  let channel = message.guild.channels.find(`name`, "bot-commands");
  if (message.member.voiceChannel) {
    if (!message.guild.me.voiceChannel) {
      console.log("Before join");
      message.member.voiceChannel.join()
      .then(connection => {
      // Code here doesn't execute, but the bot still joins.
      // All code here should execute when the bot joins a voice channel.
        console.log("Successfully connected.");
      }).catch(e => {
        // This error isn't being thrown when the bot joins.
        console.log(e);
        });
      } else {
        // This will execute when I type !join when the bot is already in the VC.
        console.log("Already connected");
     }
   }
 }
```

If I type `!join` my bot will join the appropriate voice channel as expected.
However, the log statement `console.log("Successfully connected.");` does not execute.
Additionally, the error log `console.log(e);` is not executing.
If you see the 'console.log("Before join");' located before the `message.member.voiceChannel.join()`. That log statement will execute as expected.

It looks like the promise from the `.join().then()` method isn't being fulfilled.

It was suggested to me that I try using `await` but I ran into the exact same problem.

Here is what that code looked like:

```
if (cmd === `${prefix}join`) {
  let channel = message.guild.channels.find(`name`, "bot-commands");
  if (message.member.voiceChannel) {
    if (!message.guild.me.voiceChannel) {
      console.log("Before connection"); //This line is executed.
      let connection = await message.member.voiceChannel.join();
      console.log("After connection"); //This line is not executed.
    } else {
      console.log("Already connected");
      return message.channel.send("Hello! I'm already here!");
    }
  }
}
```

**Further details:**

- discord.js version: 11.3.2
- ffmpeg-binaries version: 3.2.2-3
- opusscript version: 0.0.6
- node.js version: 8.11.3
- Operating system: Windows 10

**Comment by hydrabolt** [comment]
Event after 30 seconds of running this, neither the `.then` or `.catch` code runs?

**Comment by EndBug** [comment]
The author resolved the problem and posted it on [StackOverflow](https://stackoverflow.com/questions/51211434/code-within-join-then-not-executing)
It was a problem with his internet connection

**Comment by amishshah** [comment]
Ah ok, that's great I'll close the issue then
