### ISSUE TITLE
Repeat messages sent while Discord API response times are high

### ISSUE THREAD

**Issue by ParticleBee** [discordjs/discord.js#2655]
**Issue Description**

My bot sends repeat messages during times when the Discord API response time is high.

Over the past several weeks, whenever this has occurred it coincides with spikes in the API Response Time chart at https://status.discordapp.com, and subsides when the response times go back down.

Here's a screenshot showing what I've seen each time this issue has arisen in the Discord API Response time graph (this one is from today's occurrence where my bot acted up again):
![image](https://user-images.githubusercontent.com/41171988/42664764-56d1c56a-85f1-11e8-9cd5-079fb4d7169b.png)

During these high response delay times, the repeat messages seem to appear sporadically. Sometimes they appear fairly regularly at seemingly periodic intervals every few seconds (maybe 5-10 seconds apart going from memory?), and at other times they're more random and sparse, like once a minute or more for some span of time.

What's also noteworthy is that the messages seem to be from other channels, and perhaps even other guilds. For instance, if someone in channel A issues a command, then someone in channel B issues a different command (should get different response), channel B will start getting channel A's response message repeatedly.

I've tried restarting my bot during these times, but it behaves the same.

**Reproducible Sample Code**

This sample code is a reduced form of what my bot does. Basically when a command comes in it does a data fetch and then sends an embed as a response. It's a low-usage bot, only handling one command every couple minutes or so.
```js
const Discord = require("discord.js");
const request = require('request');
const config = require("./config.json");

const client = new Discord.Client();
client.login(config.token);


client.on("message", async (message) => {

  // ignore messages from bots
  if (message.author.bot) {
    return;
  }

  // fetch data
  try {
    var response = await fetch_data_promise('https://baconipsum.com/api/?type=all-meat&sentences=1&start-with-lorem=1');
  }
  catch (error) {
    console.warn('Fetch failure: ' + error);
    return;
  }

  // send embed
  var embed = new Discord.RichEmbed();
  embed.setDescription(response);
  message.channel.send(embed);
});


// fetch data and return promise
function fetch_data_promise(url) {
  return new Promise(function(resolve, reject) {
    request.get(
      {url: url, headers: {'User-Agent': 'request'}},
      function(err, resp, body) {
        if (err) {
          reject(err);
        }
        else {
          resolve(body);
        }
      }
    )
  })
}
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 10.5.0
- Operating system: Linux (Amazon EC2 AMI)
- Priority this issue should have – please be realistic and elaborate if possible:
I would say low to medium priority since this only occurs infrequently, **BUT** there is a potential security risk associated with it since command responses are sent to channels other than those from where they originated. If there's sensitive data in the response, someone outside a privileged channel may be able to view it, so maybe medium-high priority is warranted?

**Comment by devsnek** [comment]
> During these high response delay times, the repeat messages seem to appear sporadically. Sometimes they appear fairly regularly at seemingly periodic intervals every few seconds (maybe 5-10 seconds apart going from memory?), and at other times they're more random and sparse, like once a minute or more for some span of time.

even the discord desktop client has this issue, it just has to do with request retry.

> What's also noteworthy is that the messages seem to be from other channels, and perhaps even other guilds. For instance, if someone in channel A issues a command, then someone in channel B issues a different command (should get different response), channel B will start getting channel A's response message repeatedly.

thats a race condition in your own code. glhf

**Comment by not-idol** [comment]
same issue, message are sent multiple times in a row, any way to prevent that ?

**Comment by ParticleBee** [comment]
@not-idol Glad it's not just me. I don't know how to prevent it except by shutting down my bot until the discord API latency goes back to normal :(

I spoke with Lewdcario#0448 in their discord server and he said it's most likely an issue with discord.js but he doesn't know how to fix it currently.

**Comment by DanudeSandstorm** [comment]
I had to add an admin command to reset the bot when this happens. Keeps repeating the last response it sent when hitting the API response time spike.

**Comment by not-idol** [comment]
i think after u do ``message.author.send()`` discord.js waits for a respsone, which either comes very late or not at all and then retries again which leads to sending the message multiple times (i guess)

**Comment by Dev-Yukine** [comment]
This issue is related to Discord.js retrying on 500 Responses from Discord and after talking to the Devs and discussing this we decided to not remove that feature for various reasons.

**Comment by not-idol** [comment]
@Dev-Yukine totally understandable, hopefully discord fixes that issue soon

**Comment by ParticleBee** [comment]
@Dev-Yukine Could a configuration option or parameter of some sort be added where the retries can be disabled?

If my bot doesn't respond to a user's command it's not a big deal, but when it starts spamming these messages in multiple channels of multiple servers it has been a big deal, especially when I'm not around to shut it down.

**Comment by not-idol** [comment]
@ParticleBee good argument, maybe put a !shutdown command and give trusted members access to it to shutdown bot activity

**Comment by not-idol** [comment]
@Lewdcario good practice, yeah kinda sucks that discord has some problems, lately many issues with them :/

**Comment by ParticleBee** [comment]
I understand you guys are probably in the right regarding the issue itself, but I have multiple servers that are affected by this thing right now. A simple retry disable parameter would at least alleviate this issue for now, and shouldn't impose any negative effects. I was already very near to switching to another library altogether, and now I think I'll have to since I'm getting a lot of grief from my users.

**Comment by not-idol** [comment]
@ParticleBee im changing the code part @Lewdcario send me, so 500 errors wont retry again (until discord fixes that issue) i can send you the Handler file if you like

**Comment by ParticleBee** [comment]
@not-idol Yeah I'd appreciate that as an alternative workaround! However, I'm clueless as to how I would go about utilizing it.

**Comment by ParticleBee** [comment]
@not-idol Would it be as simple as modifying RequestHandler.js wherever it currently resides under node_modules, and then restarting the bot?

If that's the case then can you just post whatever change you make here and I can change it manually on my end?

**Comment by y3tii** [comment]
Couldn't there be a way to unqueue the duplicate messages after the bot has seen its been successfully sent. This lets retrys still exist, and means you don't have to restart the bot if it gets stuck in a chain.

**Comment by not-idol** [comment]
@ParticleBee download the github code and rename it discord.js and put it inside the node_module (the simple npm install discord.js isnt 1:1 the same code asthe github one), i recommend to rename your old discord.js file to discord_old.js or something to swtich back whenenver u like. then u go into src -> rest -> handlers and open RequestHandler.js, i commented out line 99 to 105, see [here](https://github.com/discordjs/discord.js/blob/master/src/rest/handlers/RequestHandler.js#L99-L105)

i added 
``
          parseResponse(res).then(item.resolve, item.reject);
          finish()
          return
``

above the comment, this is basically the same part as it was a response code of 200, so if you get the 502 error code again (or any other 5xx, discord says they are prett rare tho) you treat it like a normal 200 code so it desnt get retried again, if discord fixes their issue defently switch back to the best practise variant, this is only a temporarily solution

**Comment by not-idol** [comment]
@y3tii error code of 502 usually means that your request didnt get through, which means that the messages wasnt send, so you would actually retry to send the message again, problem is, discord sends the message but returns u still a 502 error code it seems

**Comment by ParticleBee** [comment]
@not-idol Like this?
```js
  finish(Number(res.headers.get('retry-after')) + this.client.options.restTimeOffset);
} else if (res.status >= 500 && res.status < 600) {

  parseResponse(res).then(item.resolve, item.reject);
  finish();
  return;

  //if (item.retried) {
  //  item.reject(res);
  //  finish();
  //} else {
  //  item.retried = true;
  //  this.queue.unshift(item);
  //  finish(1e3 + this.client.options.restTimeOffset);
  //}
} else {
  parseResponse(res).then(data => {
```

**Comment by not-idol** [comment]
@ParticleBee yep, im not a JS expert, i just copied the code for the 200 response to treat the 5xx repsonse the same. be aware that this doesnt retry to send messages now on 5xx codes. to be 100% sure, ask one of the main devs

**Comment by y3tii** [comment]
Yea I imagine it'd be something like that, it'd feel pretty hacky to have the bot disconnect and reconnect itself, when it notices it happening. But that's all I can think of at the moment, because restarting the bot seems to stop the repeats going through.

**Comment by ParticleBee** [comment]
Would appreciate your blessing @Lewdcario on the proposed workaround by @not-idol that is posted above if you have a chance! This would suffice for me while we wait for Discord to fix their issue.

**Comment by SirDeadlystrike** [comment]
This might be resolved - There were a solid few weeks where this issue was heavily present - I have not noticed this issue in over a week now

**Comment by ParticleBee** [comment]
@SirDeadlystrike I think the issue only occurs when the Discord API response time is very high, maybe a couple seconds or more (I think the response times were as bad as up to ~5 seconds during the last incident where my bot was affected).

According to this https://status.discordapp.com/#month they haven't had really high response times for the past month, so I don't think we'll be able to conclude anything until we see what happens during the next high response time incident, or perhaps if Discord addresses the issue and documents someplace public like release notes or a bug tracker (I'm not familiar with what they use for sharing that sort of info).
