### ISSUE TITLE
Constant Bot Spam

### ISSUE THREAD

**Issue by ItsLazyMan** [discordjs/discord.js#2659]
**Please describe the problem you are having in as much detail as possible:**
Bassicaly this is happening across all the servers I have een RPBot in. Where someone requests to view a character, and it just constantly spams said character profile.

**Include a reproducible code sample here, if possible:**
N/A

**Further details:**
None required.
- discord.js version: No idea.
- node.js version: No idea.
- Operating system: Windows 10 Home.
- Priority this issue should have – please be realistic and elaborate if possible:
High Priority.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
This is not the place to report issues with bots- such concerns should be taken up with the creator of the bot. This is the place for issues with the library- and should follow the format provided to you when you open an issue.
