### ISSUE TITLE
Using MessageEmbed errors out

### ISSUE THREAD

**Issue by Xyvyrianeth** [discordjs/discord.js#2660]
When I try to do this:
```javascript
let embed = new Discord.MessageEmbed();
```

This happens:
```
TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (/app/node_modules/discord.js/src/structures/MessageEmbed.js:13:60)
```

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by Xyvyrianeth** [comment]
How is this not a bug report? I found an error in your code and I put it here, what else can I do?

**Comment by Lewdcario** [comment]
Your code does not match up with your version. That is for master branch, not stable branch. You should use the support server first usually to confirm whether or not it is a library issue.
