### ISSUE TITLE
Current Github code -> overwritePermissions doesnt change the permission

### ISSUE THREAD

**Issue by not-idol** [discordjs/discord.js#2662]
Currently using the current github code, overwritePermissions() doesnt work. 
The npm version does work

my code; 

```javascript
const changePermChannel = async (roles, channel, bool) => {
  for (let i=0; i<roles.length; i++) {
    let role = await channel.guild.roles.get(roles[i]);
    await channel.overwritePermissions(role, {SEND_MESSAGES: bool});
  }
}
```
also, no error is thrown

**Comment by SpaceEEC** [comment]
I'd look at the documentation for the method you are using:
https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=overwritePermissions

It does something different on "master", the github version.

**Comment by not-idol** [comment]
@SpaceEEC oh right the master branch, im so sorry for this silly issue

**Comment by Lewdcario** [comment]
Additionally, please do not ignore the issue template provided to you- it contains crucial information that would be helpful in scenarios like this- such as the version. However, it is ideal to ask in the server first to confirm whether or not it is a library issue.
