### ISSUE TITLE
Keeping track of cache predictions when events from discord comes trough

### ISSUE THREAD

**Issue by SimplyLinn** [discordjs/discord.js#2664]
**Is your feature request related to a problem? Please describe.**
Related to #2653 and #2661
It seems like the core of the issue in the above issue and bugfix PR is that DJS predicts changes to its internal cache prior to actually getting a response event from Discord itself. Most of the time, things are linked to ID's without persistent parameters that are not included in the response. These can continue to work as is. But things like the reaction count needs to have some handling for awaiting the discord API, since the count is not included in the ReactionRemove event, and since we are predicting the count decrementation prior to the response.

**Describe the solution you'd like**
I'd like to propose that we go trough and identify areas that are affected by persistent changes like this, and add ways to identify when the change already got taken care of trough prediction and not alter the cache twice.

**Describe alternatives you've considered**
I considered waiting for responses from discord for every request which produces one before modifying the cache, but this could make awaiting code overly sluggish. I also considered just "staging" the changes in the cache and later commit these changes once the event got received from discord. This however felt like over engineering something that's only an issue in limited situations, and would require a rewrite in every aspect of the cache, and require a lot of timers, to keep track of whether an event just never fired and ways to deal with situations when a request didn't get a response in time.

**Additional context**
I'm honestly unsure what would be the best way to implement this. I opted for the "only when necessary" approach as my main suggestion, since I feel like that's the most feasible solution, but it's not exactly general and would need a case-by-case fix. Depending on how widespread this issue is, the general solution that will require rewriting a lot of how events are handled and predicted might be a better idea, it will be more future proof, as if we require the events from discord to come trough before committing any persistent changes to the cache this issue will not arise with future API features that may include similar problems. It will also allow bot-developers to search the "verified" cache as well as the predicted cache, if they, for some reason, need to know how the cache actually verified by events from discord looks. I'm imagining that staged changes will look just like verified ones from the standard DJS API, both to keep backward compatibility and because most bot devs won't care about whether something actually got verified by an event from discord yet or not, but just want the most recent data even if said data is "future" data.

I could try and implement any of these changes, but I need some discussion on which one of the approaches is preferable, or if my entire reasoning is completely bonkers and I should get burned at the stakes for even suggesting a change in how caching works 😛

**Comment by Susdevlmao** [comment]
THis has been here since 2018 but heres a way u can contribute https://www.youtube.com/watch?v=xvFZjo5PgG0

**Comment by iCrawl** [comment]
This won't happen before a complete rewrite of the library, so I'm going to close this as we move forward and decide how we will implement this.
