### ISSUE TITLE
.hasPermission is undefined

### ISSUE THREAD

**Issue by tom-barnes** [discordjs/discord.js#2665]
Line of Script:

` if (message.member.hasPermissions("ADMINISTRATOR")) return message.channel.send("You need the ADMINISTRATOR permission to run this comamnd!")`

Error Code:

> (node:3016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasPermissions' of undefined
>     at Object.exports.run (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\commands\announce.js:4:27)
>     at Client.bot.on (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\bot.js:40:29)
>     at Client.emit (events.js:182:13)
>     at MessageCreateHandler.handle (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
>     at WebSocketPacketManager.handle (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
>     at WebSocketConnection.onPacket (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
>     at WebSocketConnection.onMessage (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
>     at WebSocket.onMessage (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\ws\lib\event-target.js:120:16)
>     at WebSocket.emit (events.js:182:13)
>     at Receiver._receiver.onmessage (C:\Users\corro\Desktop\Desktop Storage\Sandwich Station\node_modules\ws\lib\websocket.js:137:47)
> (node:3016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:3016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tom-barnes** [comment]
Hi, could someone please help? Thank you.

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
