### ISSUE TITLE
Discord Music Bot Won't Play Anything

### ISSUE THREAD

**Issue by MilkLegend** [discordjs/discord.js#2667]
This is my GitHub page : https://github.com/MilkLegend/OverRealm-Music-Bot

The bot joins the voice channel but won't play music, it leaves thinking the music has stopped.

This is my cmd : 
![image](https://user-images.githubusercontent.com/40525094/43031624-c5330882-8c6a-11e8-8199-f7cc1e13104f.png)

And this is my command : 
![image](https://user-images.githubusercontent.com/40525094/43031628-dae82400-8c6a-11e8-84eb-b0f0b4a4f814.png)

**Comment by MilkLegend** [comment]
Also I really don't know GitHub that well and I don't know where the "Reopen Issue" button is.

**Comment by iDroid27** [comment]
This is not a place to be helped. Go on the [official discord.js server](https://discord.gg/bRCvFy9) and ask for help in **#other-js-question** (since you're using ytdl).

**Comment by PLASMAchicken** [comment]
There is a issue template too for a Reason!

**Comment by Lewdcario** [comment]
Please use the `issue template` when opening up an issue. Do not post your entire bot and ignore it.
