### ISSUE TITLE
playFile not working on Ubuntu

### ISSUE THREAD

**Issue by cruderustle** [discordjs/discord.js#2674]
**Please describe the problem you are having in as much detail as possible:**

I'm having an issue with playFile on Ubuntu, it works fine on the Windows computer I'm using but on that one it doesn't? Everything functions correctly except it doesn't play any sound. It joins the voice channel though, the green circle just doesn't come up. No errors either.

Also, apologies for posting this here instead of the Discord. I just haven't been able to get any help there.

**Include a reproducible code sample here, if possible:**
```js
client.on("voiceStateUpdate", (oldMember, newMember) => {
	if(newMember.user != client.user) {
		//User joins the voice channel
		if(oldUserChannel === undefined && newUserChannel !== undefined) {
			playFile(newUserChannel, "./default/neutral_connection_connected_currentchannel.wav");
		}
	};
});

function disconnect(connection) {
	connection.disconnect();
}

function playFile(channel, file) {
	channel.join()
		.then(connection => {
			connection.playFile(file);
			setTimeout(function(){disconnect(connection);}, 2000);
		});
}
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v8.11.3
- Operating system: Ubuntu 18.04 LTS x64
- Priority this issue should have – please be realistic and elaborate if possible:
Medium-high. This seems like it's been plaguing other people and I haven't been able to find any 

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Can you firstly try installing ffmpeg-binaries and node-opus, if that doesn't work please try using the master branch of discord.js

**Comment by cruderustle** [comment]
Doesn't work on the master branch, I already have ffmpeg and nope-opus installed.

**Comment by PLASMAchicken** [comment]
Are u using the right path  for the file
And it github repo is 404

**Comment by cruderustle** [comment]
Oh I forgot I deleted it. Added code sample instead

**Comment by PLASMAchicken** [comment]
Still not very good to reproduce
Wich file are u playing
Send how u play it in code and the path to it

**Comment by hydrabolt** [comment]
When you tried it on the master branch did you make sure to use .play instead of .playFile

**Comment by cruderustle** [comment]
Yeah, I used .play instead of .playFile

**Comment by hydrabolt** [comment]
That's... really strange. It should work on Node 8+
