### ISSUE TITLE
user.presence.game.assets === undefined

### ISSUE THREAD

**Issue by Umberghost** [discordjs/discord.js#2680]
When i do: user.presence.game.assets i retrieve "undefined" while i'm using spotify on the background. What would be the way to retrieve the spotify info?

**Comment by queezly** [comment]
What's your discord.js version? the addition of activity properties to the Game class is a backport from master and only available on 11.3-dev, if you have the regular discord.js stable branch (11.3.2) installed those won't be accesible <https://discord.js.org/#/docs/main/stable/class/Game> vs <https://discord.js.org/#/docs/main/11.3-dev/class/Game>
