### ISSUE TITLE
uws seems to be unmaintained

### ISSUE THREAD

**Issue by Shinobu1337** [discordjs/discord.js#2685]
I was installing uws, and ran into a deprecation notice:
```
npm WARN deprecated uws@99.0.0: stop using this version
```

Upon looking on the package's [NPM page](https://www.npmjs.com/package/uws), I was greeted with this:
> ![image](https://user-images.githubusercontent.com/31580218/43351036-6548b8ac-91da-11e8-803e-87a7df42c355.png)

It seems that something has occurred and uws is no longer maintained. Should uws be removed as an optional dependency? If so, what alternatives could be used instead of uws?

**Comment by hydrabolt** [comment]
Hi, we're still looking into what action we could take here

**Comment by devcat** [comment]
seems new bindings for node.js are moving to [[WIP] uNetworking/uWebSockets-node](https://github.com/uNetworking/uWebSockets-node)
uws module can be replaced by github link which npm will install

**Comment by hydrabolt** [comment]
We'll check back on it, I honestly wouldn't be surprised if the repo remains in its empty state :stuck_out_tongue:

**Comment by Shinobu1337** [comment]
The last "normal" publish of the module was version 10.148.1 — we could change the dependency to `uws@10.148.1`, but one would still see the depreciation notice upon install. 

Additionally, the project's [license](https://cdn.jsdelivr.net/npm/uws@10.148.1/LICENSE) would allow for a fork to be made and we could have a `discordjs/uws` GitHub repo as the dependency.
