### ISSUE TITLE
GUILD_ROLE_CREATE event

### ISSUE THREAD

**Issue by kendinikertenkelebek** [discordjs/discord.js#2690]
**Please describe the problem you are having in as much detail as possible:**
Whenever disabled `GUILD_ROLE_CREATE` event, `roleDelete` doesn't emitted anymore.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client({
    disabledEvents: [
      'GUILD_ROLE_CREATE'
    ]
  });

client.on('roleDelete', () => {
    console.log('Hello World');
});

client.login('token');
```

**Further details:**

- discord.js version: #master
- node.js version: 10.7.0
- Operating system: Darwin
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Disabling the create event will stop roles from being cached and also stop the delete event from working for that reason.
