### ISSUE TITLE
cannot communicate with master process when using shardclientutil.

### ISSUE THREAD

**Issue by RTK99** [discordjs/discord.js#2700]
**Please describe the problem you are having in as much detail as possible:**
So I believe I updated my Node modules about a month ago, and when I run any command on any shard that isn't shard 0, I am immediately thrust with this error:

```js
Error [SHARDING_PARENT_CONNECTION]: Failed to send message to master process.
    at Promise (/home/rich/Fox/node_modules/discord.js/src/sharding/ShardClientUtil.js:49:24)
    at new Promise (<anonymous>)
    at ShardClientUtil.send (/home/rich/Fox/node_modules/discord.js/src/sharding/ShardClientUtil.js:45:12)
    at Promise (/home/rich/Fox/node_modules/discord.js/src/sharding/ShardClientUtil.js:72:12)
    at new Promise (<anonymous>)
    at ShardClientUtil.fetchClientValues (/home/rich/Fox/node_modules/discord.js/src/sharding/ShardClientUtil.js:64:12)
    at HelpCommand.run (/home/rich/Fox/commands/core/help.js:25:49)
```
every time you run a command on shard 1 that uses shardclientutil, I get that error. The commands that don't reference shardclientutil execute twice..
I've been facing this issue for months, it just doesn't seem to want to go away. My whole shard is suffering the wrath of this issue and it's causing many people to simply kick the bot. Any help would be much appreciated, thanks.

**Include a reproducible code sample here, if possible:**
```js
 const res = (await this.client.shard.broadcastEval(`this.guilds.size`)).reduce((prev, val) => prev + val, 0);
```

**Further details:**

- discord.js version: 12.0-dev
- node.js version: v8.11.3
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Very high, since almost a thousand guilds are unable to use the bot to its full potential, and it's driving me and all of the server owners crazy.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: #4ae58f66f4b46e789b3eb050f1dca9e09db71e0a

**Comment by RTK99** [comment]
So it seems like updating my node version to latest indeed fixed the issue, weird. Issue closed.

**Comment by iDroid27** [comment]
It isn't supposed to throw that error on a compatible version. There is still a problem somewhere.
