### ISSUE TITLE
Not well handled error when discord api is acting wierd

### ISSUE THREAD

**Issue by ImUrX** [discordjs/discord.js#2701]
**Please describe the problem you are having in as much detail as possible:**
While i was trying to send a message, discord was having problems (some messages werent being sent) and while doing a command that just sends a message and calculates the ping and expecting a result like this:
https://i.imgur.com/BW0HkzT.png
it didnt sent that but instead sent [[object Response]](https://i.imgur.com/rQagUws.png) and as we know, [object Response] is actually from Response of node-fetch which I don't use but the library discord.js does use.

**Include a reproducible code sample here, if possible:**
```js
msg.channel.send("test").then(msg => msg.edit("test"));
```

**Further details:**

- discord.js version: 12.0.0 - 9796489cbfa68a230bec46be8b05b3cb143953dc
- node.js version: 8.11.3
- Operating system: Ubuntu 16.04.4
- Priority this issue should have – please be realistic and elaborate if possible: Honestly, it's something that cant usually happen but its related on how discord.js should handle errors, so it would be Low or Medium.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by gloss-water** [comment]
for what it's worth, i'm so far unable to reproduce this after a couple attempts -- i tested it by messing with what gets returned to edit / patch / the api request itself at various places in the call stack to match what my guess at an error like that would look like, and have yet to see it just straight send a response object where content should be

**Comment by Lewdcario** [comment]
(Supposedly) resolved as of 13f46b924be15371f377d3c5f128ac75ac98e4b4, as retried 5xx errors are properly handled now, with `HTTPError` rejections. Feel free to reopen if the issue persists.
