### ISSUE TITLE
Unexpected token  in JSON at position XXXX

### ISSUE THREAD

**Issue by JustAnotherUser0** [discordjs/discord.js#2706]
**Please describe the problem you are having in as much detail as possible:**
My bot is sharded and I emit the reactions from DMs to all the shards. Using the raw event I check if its the shard 0 and then emit the reaction add event. Sometimes at random the parsing line crashes and with it my whole process.

**Include a reproducible code sample here, if possible:**
```js
client.on('raw', async event => {

	if (event.t !== 'MESSAGE_REACTION_ADD' || client.shard.id !== 0) return null;

	const { d: data } = event;
	const message_id = data.message_id;
	const user_id = data.user_id;

	if(user_id === client.user.id) return null;

	const user = client.users.get(user_id) || await client.fetchUser(user_id);
	const channel = client.channels.get(data.channel_id) || await user.createDM();
	const message = await channel.fetchMessage(message_id);

	const emojiKey = (data.emoji.id) ? `${data.emoji.name}:${data.emoji.id}` : data.emoji.name;
	const reaction = message.reactions.get(emojiKey);

	client.shard.broadcastEval('this.emit(\'messageReactionAdd\', '+CircularJSON.stringify(reaction)+', '+CircularJSON.stringify(user)+')');

	return null;
});
```

Error log:
```
undefined:1
{"_sEval":"this.emit('messageReactionAdd', {\"message\":{\"channel\":{......",\"verificationLevel\

SyntaxError: Unexpected token  in JSON at position 356518
    at JSON.parse (<anonymous>)
    at Pipe.channel.onread (internal/child_process.js:470:28)
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v8.11.3
- Operating system: CentOS
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RumbleFrog** [comment]
You should join the Discord to ask questions

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
