### ISSUE TITLE
Feature: InternalSharding via ShardingManager

### ISSUE THREAD

**Issue by SirDeadlystrike** [discordjs/discord.js#2708]
**Feature Request:** Support Internal Sharding via the Sharding Manager
If a 15,000 guild bot runs on a 2 core system, It would be ideal to have the sharding manager create two processes, each managing 4 shards rather then 8 processes each managing 1 shard.

A recent PR to  the internal-sharding branch saw additions to the Sharding Manager that now allow for you to spread your shards out across multiple boxes. I think this is the logical next step to truly round out internal sharding support.

A possible implementation using existing constructor options
`
new Discord.ShardingManager('./bot.js' {
totalShards: 8,
shardList: [[0,1,2,3], [4,5,6,7]]
});
`

**Comment by KevinNovak** [comment]
Have there been any updates to this? Ideally I would want to spread the load among cores, but continue to use internal sharding as well for the memory usage benefit because of the shared cache.

**Comment by Poly-Pixel** [comment]
Is this feature still needed?

**Comment by meister03** [comment]
> Is this feature still needed?

I made my own package. So I would not need it. But when someone wants it, I can create a PR for it.

**Comment by KevinNovak** [comment]
In case anyone in the future is looking, the package is called [https://www.npmjs.com/package/discord-hybrid-sharding](https://github.com/meister03/discord-hybrid-sharding).
