### ISSUE TITLE
A code for member count in voice channels (Discord.js)

### ISSUE THREAD

**Issue by BlaGro** [discordjs/discord.js#2713]
I would like to create a code that will be shown live on the voice channels as there are online users, all users, bots, etc.
Idk how to start .-.

**Comment by eponymz** [comment]
You should join the support server. This is fire reporting issues, not seeking help.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by BlaGro** [comment]
Ok
