### ISSUE TITLE
On Guild Create - Incorrect permissions

### ISSUE THREAD

**Issue by KyleBoyer** [discordjs/discord.js#2716]
**Please describe the problem you are having in as much detail as possible:**
After inviting my bot to my server(with correct permissions to include MANAGE_MESSAGES), on the guildCreate event, the guild's permissions are wrong, and do not include MANAGE_MESSAGES.

**Include a reproducible code sample here, if possible:**
```js
client.on("guildCreate", guild => {
    console.log("Joined a new guild: " + guild.name);
    client.guilds.forEach((gld) => {
    	if(gld.id == guild.id){
    		console.log("It's here!");
    		if(gld.me.missingPermissions(['SEND_MESSAGES','MANAGE_MESSAGES','ATTACH_FILES','VIEW_CHANNEL','EMBED_LINKS']).length == 0){
    			console.log("All good permissions!");
    		}else{
    			console.log(gld.me.missingPermissions(['SEND_MESSAGES','MANAGE_MESSAGES','ATTACH_FILES','VIEW_CHANNEL','EMBED_LINKS']));
    		}
    	}
    });
    console.log("What is there?");
    updateGuildsAndStatus();
});
```

**Further details:**

- discord.js version: Latest
- node.js version: Latest
- Operating system: Ubuntu 18
- Priority this issue should have – please be realistic and elaborate if possible: Medium 

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by NbOpposite** [comment]
It's probably, I haven't checked and verified, because discord sends out 2 events to the client:
1st the client joins the guild, and ``guildCreate`` event is sent
2nd the client gets their role, and a ``roleCreate`` event is sent

These two probably happen simultaneously on discords servers, but in order to communicate this to the client, discord must send 2 events. Of course discord can't send a ``roleCreate`` on a server the client is unaware of, so it first sends ``guildCreate`` and then sends ``roleCreate``

**Comment by KyleBoyer** [comment]
@NbOpposite I just tested checking the permissions after roleCreate, and it still says I'm missing that perm... Here is my console.log() of the role created:
```
Role {
  guild:
   Guild {
     members:
      GuildMemberStore [Map] {
        '211823944775368705' => [GuildMember],
        '446065295334047744' => [GuildMember],
        guild: [Circular] },
     channels:
      GuildChannelStore [Map] {
        '476813239565680644' => [CategoryChannel],
        '476813239565680646' => [TextChannel],
        '476813239565680648' => [CategoryChannel],
        '476813239565680650' => [VoiceChannel],
        '476813331743768591' => [TextChannel],
        '476813366296313856' => [TextChannel],
        guild: [Circular] },
     roles:
      RoleStore [Map] {
        '476813239565680642' => [Role],
        '476848346699661323' => [Circular],
        guild: [Circular] },
     presences:
      PresenceStore [Map] {
        '211823944775368705' => [Presence],
        '446065295334047744' => [Presence] },
     deleted: false,
     name: 'Kyle\'s Monstacord Test',
     icon: null,
     splash: null,
     region: 'us-central',
     memberCount: 2,
     large: false,
     features: [],
     applicationID: null,
     afkTimeout: 300,
     afkChannelID: null,
     systemChannelID: '476813239565680646',
     embedEnabled: undefined,
     verificationLevel: 0,
     explicitContentFilter: 0,
     mfaLevel: 0,
     joinedTimestamp: 1533759905299,
     defaultMessageNotifications: 'ALL',
     id: '476813239565680642',
     available: true,
     ownerID: '211823944775368705',
     voiceStates: VoiceStateCollection [Map] { guild: [Circular] },
     emojis: GuildEmojiStore [Map] { guild: [Circular] } },
  id: '476848346699661323',
  name: 'Monstacord',
  color: 0,
  hoist: false,
  rawPosition: 1,
  permissions: { [Number: 388161] bitfield: 388161 },
  managed: true,
  mentionable: false,
  deleted: false }
```

**Comment by KyleBoyer** [comment]
When I go to:
https://discordapp.com/oauth2/authorize?client_id={CLIENT_ID}&permissions=388161&scope=bot
It shows MANAGE_MESSAGES. Is this maybe a Utility role calculator issue?

**Comment by NbOpposite** [comment]
Well, try listening for a guildMemberUpdate event, targeting your bot-member, giving it new roles

**Comment by KyleBoyer** [comment]
@NbOpposite That does the trick!
