### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by SparxoGit** [discordjs/discord.js#2722]
While coding using discord.js, there is always a syntax error at the end of my code.

``const { Client } = require('discord.js', 'async');
const bot = new Client();
const cfg = require('./config.json');

bot.on('ready', () => {
    console.log(`Bot Ready on ${bot.guilds.size} servers`);
    bot.user.setActivity('the member list', {type: 3})

bot.on('message', msg => {
    if (msg.author.bot || !msg.content.startsWith(cfg.prefix)) return;
    const args = msg.content.slice(cfg.prefix.length).split(' ')
    const command = args.shift().toLowerCase();

    bot.on(guildMemberAdd, member => {
        console.log('User ' + member.user.username + 'has joined the server, adding role')

    var role = member.guild.roles.find('name', 'New Member')

    member.addRole(role)
    
    console.log(`Args: ${args}\nCommand: ${command}`)
    });

    bot.login(cfg.token);``

This is supposed to log a members info and grant them a New Member role. Though this error is thrown whenever the terminal is run

``C:\Users\Sparxo\Desktop\AutoRole\app.js:30
});
  ^

SyntaxError: Unexpected end of input
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[nodemon] app crashed - waiting for file changes before starting...``

This is clearly an error with my closing syntax. Any help?

**Comment by amishshah** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
