### ISSUE TITLE
connection play stream/file doesn't have audio.

### ISSUE THREAD

**Issue by GrishaDev** [discordjs/discord.js#2730]
The connection.playfile or playstream seems to work, as it will show the bot with green circle as playing, and it will finish and auto disconnect when it has finished playing the file, but it doesn't have any volume.

The bot has admin permissions and not muted, and other bots/people do have volume, so it's  just my bots issue.

I have the basic bot.on("message") with some commands, and here the "voice" command:

    `           if(!message.guild.voiceConnection)
                {
                    message.member.voiceChannel.join().then(function(connection)
                    {
                        play(connection,message);
                    });
                }`

play function:

>  function play(connection, message)
> {
>     //const dispatcher = connection.playStream(ytdl('https://www.youtube.com/watch?v=UsnRQJxanVM&t=',{filter:"audioonly"}));
>     const dispatcher = connection.playFile(path.resolve(__dirname, 'trash.mp3'));
> 
>     dispatcher.on("end",function()
>     {
>         connection.disconnect();
>     });
> 
> } 

both playstream with ytdl and playfile seems to work, as they will finish depending on length of the song, i also made sure the path for trash.mp3 is fine, and the ytdl is fine.

i got ffmpeg on PATH and installed:
 [screenshot](http://prntscr.com/khcwhy)

dependencies: (i dont use half i tried them for testings, shouldn't cause issue or does it? ;o )

>  "dependencies": {
>     "discord.io": "github:woor/discord.io#gateway_v6",
>     "discord.js": "^11.4.0",
>     "express": "^4.16.3",
>     "ffmpeg": "0.0.4",
>     "fluent-ffmpeg": "^2.1.2",
>     "opusscript": "0.0.6",
>     "ytdl-core": "^0.24.0"
>   }

**Further details:**

- discord.js version: 11.4.0
- node.js version: 8.10.0
- Operating system: Win7 64bit
- opusscript: 0.0.6

Really hoping to fix it! Thanks

**Comment by amishshah** [comment]
My initial thought would be that this issue is due to a bug with `ffmpeg-binaries` loading in 11.4.0, but since you have ffmpeg in your path, it can't be that. Can you try `npm i node-opus` and just for the sake of making sure, check that your bot isn't muted.

**Comment by GrishaDev** [comment]
@amishshah node opus doesn't seem to work for me, it just gives error on install, i read it's not working well with windows, thats why i started with occusscript.

**Comment by amishshah** [comment]
Can you send a screenshot of your play function? If you're redeclaring the dispatcher twice that would be the issue.

**Comment by GrishaDev** [comment]
@amishshah [pic](http://prntscr.com/khd33s)

**Comment by amishshah** [comment]
can you add `error` and `debug` listeners to console.log, to both the connection and dispatcher and tell me what the output is?

**Comment by GrishaDev** [comment]
@amishshah I'm so confused, i added 

> dispatcher.on('error', error => 
>     {
>         console.log(error)
>     });

And suddenly it's working, like it got scared of error debug lol
I'm afraid it's not stable and won't work all the time, gona test more and tell.

**Comment by GrishaDev** [comment]
@amishshah  hello-express@0.0.1 D:\MangoBot
`-- (empty)

**Comment by GrishaDev** [comment]
It seems to work now, no idea why honestly, could actually be that 

> dispatcher.on('error', error =>
> {
> console.log(error)
> });

has to be there.
