### ISSUE TITLE
Typings not included in NPM package

### ISSUE THREAD

**Issue by TheBITLINK** [discordjs/discord.js#2743]
**Please describe the problem you are having in as much detail as possible:**

The 11.4.1 package doesn't include typings:

https://unpkg.com/discord.js@11.4.1/typings/

11.4.0 does:

https://unpkg.com/discord.js@11.4.0/typings/

**Further details:**

- discord.js version: 11.4.1
- node.js version: N/A
- Operating system: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Now included with 11.4.2:
https://unpkg.com/discord.js@11.4.2/typings/
