### ISSUE TITLE
Link Embeds Displayed as RichEmbeds?

### ISSUE THREAD

**Issue by Jyguy** [discordjs/discord.js#2757]
**Please describe the problem you are having in as much detail as possible:**

I noticed that if embeds generated by links have fields, it will be considered as a "rich embed", instead of a link embed. I check if it's the same with link embeds without fields, and it displays as link embed. Is this problem with Discord.js or just Discord API? The situation I'm having is with the messageDelete event, and links that include embeds with fields are being detected as "rich embeds", as shown down below. This is also done with `eval`, I fetch the message with the link, and check the embed type, and it shows as "rich". Without fields, they are "link". One example with a field embed is https://store.steampowered.com/app/211820/Starbound/
An example without field values: https://www.google.ca/

**Include a reproducible code sample here, if possible:**
```js
client.on("messageDelete", message => {
    if (message.embeds.find(emb => emb.type === "rich")) {
        // Logs when there's a field in the link embed
        console.log("rich embed deleted");
    } else if (message.embeds.find(emb => emb.type === "link")) {
        // Logs when there is no field in the link embed
        console.log("link embed deleted");
    }
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.11.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Those are the embeds discord sends us:
The first has type "link":
```json
{
    "url": "https://www.google.ca/",
    "type": "link",
    "description": "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
     "title": "Google"
}
```
And the second "rich"
```json
{
    "description": "You’ve fled your home, only to find yourself lost in space with a damaged ship. Your only option is to beam down to the planet below and gather the resources you need to repair your ship and set off to explore the vast, infinite universe…In Starbound, you create your own ...",
    "title": "Starbound",
    "url": "https://store.steampowered.com/app/211820/Starbound/",
    "fields": [
        {
            "inline": true,
            "name": "Price",
            "value": "$14.99"
        },
        {
            "inline": true,
            "name": "Recommendations",
            "value": "78061"
        },
        {
            "inline": true,
            "name": "Metacritic",
            "value": "81"
        }
    ],
    "video": {
        "url": "https://steamcdn-a.akamaihd.net/steam/apps/256686729/movie_max.webm?t=1496932824",
        "width": 460,
        "proxy_url": "https://images-ext-1.discordapp.net/external/lD3c26b-tJAyPkLJC7cHl9Het6L51aC6sDVAp63i__A/%3Ft%3D1496932824/https/steamcdn-a.akamaihd.net/steam/apps/256686729/movie_max.webm",
        "height": 215
    },
    "provider": {
        "url": "https://store.steampowered.com/",
        "name": "Steam"
    },
    "type": "rich",
    "thumbnail": {
        "url": "https://steamcdn-a.akamaihd.net/steam/apps/211820/header.jpg?t=1496932831",
        "width": 460,
        "proxy_url": "https://images-ext-1.discordapp.net/external/k3cdyhfdGZClD2mUukY_nkpyZ32pvtT7PBsY7_ol1Z0/%3Ft%3D1496932831/https/steamcdn-a.akamaihd.net/steam/apps/211820/header.jpg",
        "height": 215
    }
}
```

**Comment by Jyguy** [comment]
Is there any reason this is?

**Comment by SpaceEEC** [comment]
I don't know discord's reasoning behind that.

**Comment by Jyguy** [comment]
Alright, thanks for the reply.
