### ISSUE TITLE
Invite documentation seems inconsistent with source code

### ISSUE THREAD

**Issue by sjoerd108** [discordjs/discord.js#2769]
**Please describe the problem you are having in as much detail as possible:**
The discord.js documentation states:

> The only guaranteed properties are code, guild and channel. Other properties can be missing.

(https://discord.js.org/#/docs/main/stable/class/Invite)

However, when looking at the source code of `Invite`, you can see that `url` is a getter property that simply returns the result of ``Constants.Endpoints.inviteLink`` using ``this.code`` which is guaranteed to be present. Shouldn't the documentation therefore also guarantee that the `url` property is always present? 

Part of invite.js:
```js
  /**
   * The URL to the invite
   * @type {string}
   * @readonly
   */
  get url() {
    return Constants.Endpoints.inviteLink(this.code);
  }
```
`Constants.Endpoints.inviteLink` Is in turn a function that just concats the discord.gg base url to the invite code, so I don't see how the library wouldn't be able to guarantee the presence of the property.

**Further details:**
- discord.js version: 11.3.2
- Node.js version: n/a
- Operating system: n/a
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by SpaceEEC** [comment]
Fixed with the referenced commit / PR.
