### ISSUE TITLE
Error While Installing Discord.js

### ISSUE THREAD

**Issue by EMREOYUN** [discordjs/discord.js#2784]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session 2bc51d97b6d3b8b5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for discord.js@github:hydrabolt/discord.js#indev-old Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/hydrabolt/discord.js.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData undefined
7 silly fetchPackageMetaData No git binary found in $PATH
8 timing stage:rollbackFailedOptional Completed in 5ms
9 timing stage:runTopLevelLifecycles Completed in 764ms
10 verbose stack Error: No git binary found in $PATH
10 verbose stack     at checkGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:246:17)
10 verbose stack     at spawnGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:204:10)
10 verbose stack     at pinflight (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:131:12)
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:303:9)
10 verbose stack     at Promise._resolveFromExecutor (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
10 verbose stack     at new Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
10 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
10 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
10 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
10 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose cwd C:\Users\emre\Desktop\musicbot-master
12 verbose Windows_NT 6.2.9200
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js"
14 verbose node v10.9.0
15 verbose npm  v6.2.0
16 error code ENOGIT
17 error Error while executing:
17 error undefined ls-remote -h -t ssh://git@github.com/hydrabolt/discord.js.git
17 error
17 error undefined
17 error No git binary found in $PATH
18 error Failed using git.
18 error Please check if you have git installed and in your PATH.
19 verbose exit [ 1, true ]

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
