### ISSUE TITLE
VoiceConnection.play() can't play streams from SoundCloud

### ISSUE THREAD

**Issue by CheesyZaem** [discordjs/discord.js#2786]
**Please describe the problem you are having in as much detail as possible:**
I have no direct idea about this issue, but I am pretty sure it is a *bug* because I tested it on both stable and master, only works on stable.
When you try to play a stream from SoundCloud, it just does nothing but it returns a dispatcher that's normal but just won't start the stream.
**Include a reproducible code sample here, if possible:**
```js
// master
const req = require("request");
const stream = req({
    url: "https://api.soundcloud.com/tracks/257504021/stream",
    followAllRedirects: true,
    qs: {
        client_id: "nope"
    },
    encoding: null
});
connection.play(stream));

// stable
const req = require("request");
const stream = req({
    url: "https://api.soundcloud.com/tracks/257504021/stream",
    followAllRedirects: true,
    qs: {
        client_id: "nope"
    },
    encoding: null
});
connection.playStream(stream));
 
```

**Further details:**
- discord.js version: master
- Node.js version: 8.11.2
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
This is a fault with `request`, the `stream` variable you create above for whatever reason is not an instance of a [`Readable`](https://nodejs.org/api/stream.html#stream_readable_streams) so Discord.js will rightfully refuse to play it. I'd switch to a HTTP library such as [node-fetch](https://www.npmjs.com/package/node-fetch) and raise the issue with the request library maintainers.
