### ISSUE TITLE
VoiceConnection Events aren't firing?

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#2798]
**Please describe the problem you are having in as much detail as possible:**
So I decided to use events to signal my code that the bot is actually with the VoiceChannel, but to my surprise, Nothing is firing. I used then traditional .then on making it also, nothing gets fired. I tried logging every events from the documentation of VoiceConnection, even debug isn't logging anything.

I will include the orignal code that I used to help as well.

**Include a reproducible code sample here, if possible:**
```js
    const voice = await msg.member.voice.channel.join();

    voice.on('authenticated', () => console.log('Voice Authenticated'));
    voice.on('failed', (r) => console.log(r));
    voice.on('debug', (d) => console.log(d));
    voice.once('ready', () => {
        m.edit('\:white_check_mark: Teitoku ♪ **I am now in your Voice Channel**, you can now use the commands **play**, **playmoe** or **voicequote**. But Teitoku, **I will auto leave in 1 minute** if you did not use the Voice Functions.').catch(e => client.cannons.fire(client, e));
    });
    voice.once('error', (err) => {
    	if (client.voiceConnections.has(msg.guild.id)) voice.disconnect();
    	if (client.voiceConnections.has(msg.guild.id)) client.voiceConnections.delete(msg.guild.id);
    	client.cannons.fire(client, err);
    	msg.channel.send(`:x: Uuuu.. Teitoku, I encountered a problem with the **Voice Connection** Module. Here is the status report.\`\`\`${err}\`\`\``).catch(e => client.cannons.fire(client, e));
    });
```

**Further details:**
- discord.js version: Discord.js Master Commit "9b329a4"
- Node.js version: 10.9.0
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: I think medium due to almost all / all the events aren't even firing. 

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: "9b329a4"

**Comment by amishshah** [comment]
This should be clarified in our documentation, but ready, failed, and authenticated are all private events. By the time you've awaited `voice`, the connection is ready to go so you won't get any ready events. Please try moving the code inside the ready event handler outside of the event handler and deleting the handler.

**Comment by Deivu** [comment]
so what are the events that we can listen on? so that I know what I can check for just incase

**Comment by amishshah** [comment]
All of the ones listed in the documentation minus the 3 I mentioned above, if you want to double check events are firing I'd suggest listening to the speaking event and then try speaking in the same voice channel as the bot to see if it triggers

**Comment by Deivu** [comment]
Ok got it thanks for the support. Closing this now. But I do hope it can be considered in future, since I prefer to check it at least with events.

**Comment by amishshah** [comment]
For sure I will clarify this in the documentation, it's important to keep in mind that by the time the join resolves, the connection is fully ready to use and you'd have missed any debug events
