### ISSUE TITLE
Deprecation warnings for Collection#find

### ISSUE THREAD

**Issue by rag4214** [discordjs/discord.js#2808]
**Please describe the problem you are having in as much detail as possible:**
Upgraded to node 10.9.0, now when I run my bot I get about 50 `(node:10647) DeprecationWarning: Collection#find: pass a function instead` warnings. I've converted them to arrow functions, but it only gets rid of about a third of the errors.

**Include a reproducible code sample here, if possible:**
```js
//BEFORE
client.on('channelUpdate', (oldChannel, newChannel) => {
    if (newChannel.type === 'text') {
        const MutableChannelID = newChannel.guild.roles.find('name', 'MutableChannel').id;
        ...
    }
});
// AFTER
client.on('channelUpdate', (oldChannel, newChannel) => {
    if (newChannel.type === 'text') {
        const MutableChannelID = newChannel.guild.roles.find(role => role.name === 'MutableChannel').id;
        ...
    }
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.9.0
- Operating system: macOS Mojave 10.14 Beta (18A371a)
- Priority this issue should have – please be realistic and elaborate if possible: Not high, it's just a warning

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment]
Are you sure you don't have other instances of `Collection#find`? The code looks fine to me:

https://github.com/discordjs/discord.js/blob/cd58599caf9de08597ad76c473253f68f0d5112f/src/util/Collection.js#L496-L512

**Comment by rag4214** [comment]
I did an entire search of my codebase and only found a few (6 to be exact) instances of .find() and get exactly 29 errors (I exaggerated about the 50). After I replace all of them with arrowfunctions, I get 15 errors of

`(node:10647) DeprecationWarning: Collection#find: pass a function instead`

**Comment by SpaceEEC** [comment]
There still are references to `Collection#find` using a property and value in the code somewhere.
Start node with `--trace-warnings` to get stacktraces.
For example: `node --trace-warnings index.js`

**Comment by rag4214** [comment]
Ahhh, thank you. Apparently .exists() uses find as well

**Comment by SpaceEEC** [comment]
Alright, closing this then!
