### ISSUE TITLE
Can't get a bot to work

### ISSUE THREAD

**Issue by JammyWaffles** [discordjs/discord.js#2815]
I can't enter the bots name or token and keep getting the same thing in the .exe, somebody please help.

![blerp](https://user-images.githubusercontent.com/19975472/44921891-bc61c580-ad3b-11e8-843e-179295b42524.png)

**Comment by SpaceEEC** [comment]
Looks like go errors to me.
This has nothing to do with this library.

**Comment by PLASMAchicken** [comment]
Are you sure you wanted to contact discord.js. Especially if you have a .exe you might be using something else.
