### ISSUE TITLE
Node.js 10.9.0 - Dispatcher playFile Issue

### ISSUE THREAD

**Issue by JeeZeh** [discordjs/discord.js#2820]
**Please describe the problem you are having in as much detail as possible:**
On the latest Node release 10.9.0, when using `connection.playFile()` the audio will be somewhat distorted, as though it's struggling to play the file. The main issue however is that the dispatcher will always end the playback before the sound has finished playing. On Windows, this early cut-off was observed to be ~1s. However, on Ubuntu 18.04, the audio instead cuts off just a second or two into playback, issuing a `'end'` event to the dispatcher.

I'm not sure at exactly what version this issue started. I was on Node 10.x.0 and the dispatcher was working as normal, but the issue is certainly present on the latest Node 10.9.0 .

The file type (mp3/ogg) did not affect it, nor did the opus package used.

**Include a reproducible code sample here, if possible:**
The example dispatcher code provided in the documentation is enough to cause the issue.

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.9.0
- Operating system: Windows 10 1803/Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Probably high, it should be recommended to users that they do not install the latest Node.js version it seems.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Can you try using the master branch? Voice was basically rewritten in master and hopefully this fixes your issue. We have a few changes, e.g. `playFile('song.mp3') is now just `play('song.mp3')` and stuff like `member.voiceChannel` is now `member.voice.channel` (you'll have to consult the docs)

**Comment by JeeZeh** [comment]
@amishshah Can I use npm to pull the latest master branch, or do I git clone into node-modules? Sorry, I'm a little new to this.

**Comment by kyranet** [comment]
Run `npm i discordjs/discord.js`, or `yarn add discordjs/discord.js` if you use yarn.

**Comment by JeeZeh** [comment]
@kyranet thank you very much, I'll test this now and get back to you with results asap!

**Comment by JeeZeh** [comment]
Okay. So it seems as if the latest master branch has resolved the issue. I believe you should still try to reproduce the issue on the current branch and the latest Node.js. If you have the same problem then maybe add a warning until the v12 is released.

Thanks a lot for your help, I hope this bug report is of some benefit and that the issue can be reproduced.

**Comment by PLASMAchicken** [comment]
When the end event is emmited it should also give a reason can you try logging it

**Comment by JeeZeh** [comment]
Alright so I've corrected the code and it's now reproducing the original error.

The code from above is now playing a different file of length 1300ms.

However, the output is as follows:

```
Joined voice channel!
File: D:\Documents\GitHub\Playground\Alexa\sounds\dsl\Daniel Here you need some meat.mp3
Playing
Finished
Playtime: 727ms
End: stream
```

As you can see, the stream is only playing for 700ms, much shorter than the actual file.

The reason for ending is just `stream` ?

@PLASMAchicken
