### ISSUE TITLE
TypeScript Typings: Message Constructor Doesn't Match Implementation

### ISSUE THREAD

**Issue by ctsstc** [discordjs/discord.js#2825]
**Please describe the problem you are having in as much detail as possible:**
The Message constructor doesn't seem to match up with the typings
https://github.com/discordjs/discord.js/blob/master/src/structures/Message.js#L20
https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L627

In the Message constructor it seems you should be able to either omit data, or pass in a falsy value for it, but in the type definition it's a required object.
As seen from the line: `if (data) this.setup(data);` in the Message Class constructor.

Right now I'm trying to mock up some tests and I'm hoping I don't have to mock up the whole data object. I'm using Typescript so if I try to pass in a falsy value for it it'll go against the definition and won't transpile.

**Comment by ctsstc** [comment]
I'm realizing that passing over a whole message object is overkill for what my method needs to do. If I simplify that then I won't have to worry about this. Still might be good to handle this.

**Comment by appellation** [comment]
There is virtually no reason for users to construct message objects.  There should also never be a situation where you need to construct a message object without data: that line is probably just there to prevent strange errors in case that ever happens.

**Comment by SpaceEEC** [comment]
A valid usecase for accessing the constructors (or knowing their signatures) would be [`Structures.extend`](https://discord.js.org/#/docs/main/master/class/Structures?scrollTo=s-extend).

Regarding the optional data parameter:
Passing `null` should work without errors, otherwise casting it to any type should also work.
