### ISSUE TITLE
Deleting roles

### ISSUE THREAD

**Issue by legowerewolf** [discordjs/discord.js#2826]
**Is your feature request related to a problem? Please describe.**
I've got a bot that assigns users in games to roles that match the game so you can @mention everyone in a game. The problem is that there's a bunch of leftover roles when nobody is playing and you can't delete roles through the library. There is [API functionality](https://discordapp.com/developers/docs/resources/guild#delete-guild-role) for it, though.

**Describe the ideal solution**
Add a method to guilds for deleting roles.

**Comment by iCrawl** [comment]
https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=delete
