### ISSUE TITLE
Trying to set an user's status make they go offline instead, but the correct status shows up on the next login

### ISSUE THREAD

**Issue by ghost** [discordjs/discord.js#2836]
**Please describe the problem you are having in as much detail as possible:**
When setting the user status both with `client.user.setPresence({ status: status })` and `client.user.setStatus(status)`, the user goes offline to the other users on the server and contacts. If the user ends the session and starts over, they will appear with the correct status that was set on the previous session. Using `.catch` seems to catch no errors.

**Include a reproducible code sample here, if possible:**
```js

arg = "idle"
client.user.setStatus(arg)
  .catch ( err => { console.log(err) } );

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.11.2
- Operating system: Debian GNU/Linux testing, 4.17.0-3-amd64
- Priority this issue should have – please be realistic and elaborate if possible:low

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by PLASMAchicken** [comment]
The code u sent worked perfectly for

**Comment by NismoGraphics** [comment]
I found a workaround that I have no doubt will get removed/patched some time soon:
`client.user.settings.update('status','online');`
