### ISSUE TITLE
ShardingManager event when all shards are ready

### ISSUE THREAD

**Issue by pizzafox** [discordjs/discord.js#2837]
**Is your feature request related to a problem? Please describe.**
I need to grab properties from all clients across shards. This is done when shard 0 is ready. If all other shards aren't ready, this throws an error.

**Describe the ideal solution**
An event emitted from the ShardingManager class that is emitted when all shards spawned have emitted the ready event.

**Describe alternatives you've considered**
Waiting 45 or so seconds before running my code, hoping the other shards are ready.

**Comment by Lewdcario** [comment]
-1 from me. Supporting waiting for all shards is something that is bad practice as none of your code should ever be reliant on all shards being ready, as they are all independent processes. Furthermore, using `broadcastEval` will not error regardless of the number of shards being ready- as I suggested to use before. I also suggested you could even check the `Shard#id` to see if its the highest one. It seems as if my suggestions were for naught.

**Comment by pizzafox** [comment]
In my case I used `fetchClientValues` when shard 0 was ready, which caused this:
```
Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
```

**Comment by Lewdcario** [comment]
I did say to use `broadcastEval` instead, since you need your code ran in the ready event.

**Comment by pizzafox** [comment]
Your other suggestion would work but would be harder to implement as I don't have an easy way to dynamically get the total number of shards (at least from shard 0). I am working on adding that to my project.

**Comment by Dev-Yukine** [comment]
How About [ShardClientUtil#count](https://discord.js.org/#/docs/main/master/class/ShardClientUtil?scrollTo=count)? this might be the dynamic solution you want

**Comment by pizzafox** [comment]
Huh.
