### ISSUE TITLE
[11.4.2] bug? or what

### ISSUE THREAD

**Issue by bit0r1n** [discordjs/discord.js#2849]
i made spotify command, he is working, but when in my status there is nothing, bot is crashing
how to fix this? if at all possible

> bot.on('message', message => {
    let msg = message.content.toUpperCase();
    if(msg.startsWith(prefix + 'SPOTIFY')){
        var user = message.mentions.users.first() || message.author;
        if(user.bot) return message.channel.send("bots cant listen music :cry:");
        if(user.presence.game.type == 2 && user.presence.game.name == 'Spotify') {
            try {
                var trackImg = user.presence.game.assets.largeImageURL;
                var trackUrl = `https://open.spotify.com/track/${user.presence.game.syncID}`;
                var trackName = user.presence.game.details;
                var trackAlbum = user.presence.game.assets.largeText;
                var trackAuthor = user.presence.game.state;
                const embed = new Discord.RichEmbed()
                    .setAuthor('Spotify info')
                    .setColor(embedcolor)
                    .setThumbnail(trackImg)
                    .setDescription(`
                    \`🎵\` **Track name :**  \`${trackName}\`
                    \`📀\` **Album :**  \`${trackAlbum}\`
                    \`🎤\` **Author(s) :**  \`${trackAuthor}\`
                    \`🕐\` **Start listen at: ** \`${user.presence.game.timestamps.start.getHours()}:${user.presence.game.timestamps.start.getMinutes()}:${user.presence.game.timestamps.start.getSeconds()}\`
                    `)
                    .addField('Listen this track :', `[${trackAuthor} — ${trackName} (Spotify link)](${trackUrl})`, false);
                return message.channel.send(embed);
            }catch(error){
                return message.channel.send(`\`[Err ❌]\`, ${user.username} listen local music`);
            }
        }else{
            message.channel.send(`${user.username} dont listen music on Spotify`);
        }
    }

 });

![image](https://user-images.githubusercontent.com/30700800/45916773-0be76d00-be74-11e8-9fee-90daede30a23.png)

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
