### ISSUE TITLE
message.channel_id returns undefined always

### ISSUE THREAD

**Issue by DrZed** [discordjs/discord.js#2854]
```js

client.on("message", async message => {
  if(message.author.bot) return;

  var d = new Date();
  var time = d.toLocaleString();
  console.log("[" + time + "] " + message.channel_id + " -> " + message.author.username + " #" + message.author.id + " : " + message.content);
});

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.12.0 LTS
- Operating system: Windows 10 Pro 1803 17134.285
- Priority this issue should have – please be realistic and elaborate if possible: Low priority.

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Unsure where you got the idea that it is `message.channel_id`
It should be `message.channel.id`

**Comment by DrZed** [comment]
![image](https://user-images.githubusercontent.com/5124544/45924575-c5286000-bed1-11e8-92f9-2eca8d776077.png)
From here

**Comment by iCrawl** [comment]
https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=channel

**Comment by DrZed** [comment]
(人''▽｀)ありがとう☆
米の際
