### ISSUE TITLE
voiceStateUpdate and setRoles

### ISSUE THREAD

**Issue by OpakoDev** [discordjs/discord.js#2856]
Hi,

When I try to setRoles for a member, it doesn't work. I don't really know why and I'm not a pro when it's about JS then, I would like to know if it's a bug or if it's just my bad ahah...

Here's the code:
```js
bot.on('voiceStateUpdate', function (oldMember, newMember) {
	if(oldMember !== undefined)
    {
        let channelID = oldMember.d.channel_id;
        let userRoles = oldMember.d.member.roles;

        if(channelID)
        {
        	if(userRoles.indexOf(roleID) == -1)
                userRoles.push(roleID);
        }
        else
        {
        	if(userRoles.indexOf(roleID) !== -1)
                userRoles = userRoles.splice(userRoles.indexOf(roleID)-1, 1);
        }

        oldMember.setRoles(userRoles);
    }
});
```

Either, I don't know why but newMember is undefined...

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.12.0
- Operating system: Debian 9.5
- Priority this issue should have – please be realistic and elaborate if possible:
I think it's a medium priority issue but don't really know ^^

Thanks for your time!

**Comment by Deivu** [comment]
Refer to this https://discord.js.org/#/docs for Official Discord.JS Documentation.

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
