### ISSUE TITLE
Bot can not create channel

### ISSUE THREAD

**Issue by Yegor141** [discordjs/discord.js#2862]
i'm trying to create a command that makes the bot create a channel with  the person that wrote the command.
```
function makeChannel(message){
	var server = message.guild;
	var name = message.author.username;

	server.createChannel(name, "text");
}


if(isAdmin || isSeller) {
	if(command === "test") {
		client.makeChannel(`yeet`);
		return;
	}
}
```

Admin and Seller are roles in the server

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
