### ISSUE TITLE
Wrong return type on userNoteUpdate

### ISSUE THREAD

**Issue by rag4214** [discordjs/discord.js#2863]
**Please describe the problem you are having in as much detail as possible:**
The userNoteUpdate event returns a userResolvable and not a User while the docs say it returns a Discord.User

**Include a reproducible code sample here, if possible:**
```js

// Place your code here
client.on('userNoteUpdate', (user, oldNote, newNote) => {
    plugins.forEach(plugin => {
        plugin.userNodeUpdate(user, oldNote, newNote); //[ts] Argument of type 'UserResolvable' is not assignable to parameter of type 'User'.
    });
});

//plugin looks like
class plugin {
    public async userNodeUpdate(user: Discord.User, oldNote: string, newNote: string): Promise<void> {
        //...
    }
}
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10
- Operating system: macOS Mojave 10.14
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by PLASMAchicken** [comment]
By the way Bot accounts do not have accses to notes anyways and User Bots are against the Discord Tos, this is also why this event doesnt exist in master anymore.

**Comment by kyranet** [comment]
That's right, it's fixed in master, we removed it, so there's nothing to fix. And those events should at bare minimum be marked as deprecated.

**Comment by rag4214** [comment]
I'm going to close this for now, but should I make a PR to add `@deprecated` to the docs or will that be sorted out elsewhere?
