### ISSUE TITLE
Constants in Typings

### ISSUE THREAD

**Issue by ChrisTalman** [discordjs/discord.js#2864]
The Discord module exports a `Constants` object. However, this does not seem to be declared in `index.d.ts`. It would be useful if it were.

I have a fork in which I have done this. Although, I've only declared two of the objects within `Constants` so far: `APIErrors` and `Status`.

I can submit a pull request for that, unless someone else would prefer to handle this.

**Comment by amit3992** [comment]
Hey, I think I can work on this. Can I pick this?

**Comment by ChrisTalman** [comment]
Fine with me.

**Comment by SpaceEEC** [comment]
I think most of the contents in there are already declared.
This should be mostly just putting them together in an object exported as `Constants`.
I am fine with adding that.

**Comment by amit3992** [comment]
Okay sure. I'll work on it!
