### ISSUE TITLE
Add explanation to Presence's activity type

### ISSUE THREAD

**Issue by SimonNitzsche** [discordjs/discord.js#2865]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the ideal solution**
Elaboration for the activity type integer in the docs.

**Describe alternatives you've considered**
None.

**Additional context**
Url to doc page: https://discord.js.org/#/docs/main/stable/class/Game?scrollTo=type
Full list:
```
Type 0 = Playing
Type 1 = Streaming
Type 2 = Listening to
Type 3 = Watching

**Comment by appellation** [comment]
This has already been implemented in the development version.  https://discord.js.org/#/docs/main/master/class/Activity?scrollTo=type

**Comment by SpaceEEC** [comment]
Added a note in the documentation in 11.4-dev with the referencing commit for the next release.
