### ISSUE TITLE
GuildChannel.lockPermissions wipes permissions

### ISSUE THREAD

**Issue by venrob** [discordjs/discord.js#2866]
**Please describe the problem you are having in as much detail as possible:**
When I attempt to sync a channel's permissions to its' parent category, instead of copying the permissions over as it should, it copies over what roles should have permissions, but leaves all of the permission settings blank (grey, between allow and deny)

**Include a reproducible code sample here, if possible:**
```js

channel.setParent(parentID).then(channel => {
    channel.lockPermissions();
});

```

**Further details:**
- discord.js version: latest from "npm install discord.js"
- Node.js version: latest
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible:
5/10, fairly important, but not completely program-breaking for all bots; just bots that move categories.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by html-programmer** [comment]
#2800 should solve this
