### ISSUE TITLE
How to overwrite channel permissions with bitfield using discord.js

### ISSUE THREAD

**Issue by Gwerbyn** [discordjs/discord.js#2867]
I tried to get my bot to save channel permissions but it only saves its bitfield. Can I somehow overwrite channel permissions for a specific role only using the bitfield?

i tried doing something like this:
            channel.overwritePermissions(role, {
              permissions: perms
            });

and then tried changing it to:
            channel.overwritePermissions(role, {
              bitfield: perms
            });

but it just puts / for every permission.

**Comment by didinele** [comment]
First of all follow the issue format.

Second of all, this will get closed and get thr Question label, you should ask this in the support server.

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
