### ISSUE TITLE
Username characters aren't escaped

### ISSUE THREAD

**Issue by aqua-rar** [discordjs/discord.js#2877]
**Please describe the problem you are having in as much detail as possible:**
When sending a message with a username or nickname: special characters in that username aren't escaped. So if a user has a display name that contains a single asterisk it can mangle your formatting later in the message.

**Include a reproducible code sample here, if possible:**
```js
const discord = require('discord.js')
const client = new discord.Client()

client.login(token)

client.on('message', message => {
  if (message.author.id === client.user.id) return
  message.guild.fetchMember(message.author).then(guildUser => {
    message.channel.send(`${guildUser.displayName} test* test`)
  })
})
```

If the user has a name like `hi *hello` the sent message will look like this:
hi *hello test* test
Instead of
hi \*hello test* test

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 9.7.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Not very urgent at all. Only assholes like me have usernames with unescaped characters.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Gawdl3y** [comment]
This isn't the library's job, as there are more uses for the username/nickname/displayName than just displaying them in a message. This is what the [escapeMarkdown](https://discord.js.org/#/docs/main/stable/class/Util?scrollTo=s-escapeMarkdown) utility function is for.

**Comment by aqua-rar** [comment]
I didn't realise there was a Util class. Thanks very much, it looks very useful.
