### ISSUE TITLE
Emoji creation ratelimiting is not catched

### ISSUE THREAD

**Issue by towerofnix** [discordjs/discord.js#2885]
Discord's API documentation [states](https://discordapp.com/developers/docs/resources/emoji) that there are rate limits placed on creating emoji per guild, and that rate limiting information the API returns may not be accurate regarding emoji (since the limit is per guild instead of per bot):

> Routes for controlling emojis do not follow the normal rate limit conventions. These routes are specifically limited on a per-guild basis to prevent abuse. This means that the quota returned by our APIs may be inaccurate, and you may encounter 429s.

I recently ran into this issue while developing a game which automatically creates emoji as part of its user interface. This could in itself be considered "emoji abuse", but that's besides the point. Particularly, I encountered this rate limiting and could not upload emoji. However, Discord.js did not tell me I couldn't: Instead it just hanged. The `Guild.createEmoji` function never returned anything.

Do note that I tested uploading the exact same emoji via the same code but onto a different server, and it successfully uploaded, and I am certain that there was always available slots for emojis.

Unfortunately there's no particularly reliable (and brief) code that produces this; I expect you'd encounter the issue by uploading many emotes to a server within a brief time, as was being done in the code of the game I mentioned.

**Further details:**
- discord.js version: `^11.4.2`
- Node.js version: 10.3.0
- Operating system: Debian (linux)
- Priority this issue should have: Well, not particularly high. This is a niche issue and one most won't encounter. Unless emotes are automatically created at a high frequency, this is never a problem. That said, one *would* expect the `Guild.createEmoji` function to throw an error, and it does not, which can make debugging very difficult (since you don't have an error to base off of - your program just doesn't work from the point of creating the emoji onwards).

- [ ] I found this issue while running code on a __user account__ (I'm using a Bot for my app, but I think that's different)
- [ ] I have also tested the issue on latest master, commit hash: (Haven't)

**Comment by SpaceEEC** [comment]
"Instead it just hanged" sounds like we handled the ratelimit, as we queue up requests before (or after) encountering a 429 and wait until the `X-RateLimit-Reset` (or `retry-after`) elapsed.

That waiting is probably the "hanged" part.

I am not sure what a good solution for this would be (if any).
You can listen to the [`rateLimit`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-rateLimit) event, it's probably a bit of work to match that to your request however.
And even then, there is no way to cancel the request and return an error to the user (or do whatever).
