### ISSUE TITLE
Shards Goes Offline without notice.

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#2889]
**Please describe the problem you are having in as much detail as possible:**
This issue is around the shards going 'offline' but doing a broadcastEval of the status of the client connection, on a guild that has not yet gone offline yielded me a result of all in `0`. 
No Events, either on disconnect or reconnect fired. 

Here is the BroadcastEval (client.status) I did before I restarted the bot due to the shard that gone offline
https://cdn.discordapp.com/attachments/466511182061240325/498413394756370453/Untitled1.jpg

**Further details:**
- discord.js version: Master
- Node.js version: 10.11.0
- Operating system: Ubuntu 18.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Medium Because you need to restart the whole bot when this happens, and thats bad specially when you run a lot of shards.

- [ ] I found this issue while running code on a __user account__
- [x ] I have also tested the issue on latest master, commit hash: `00a62a93e4b36ea3f31d31e8a9e966137c3f77a8`

**Comment by Deivu** [comment]
Update: This happens if you don't use uws, It seems like with uws, shards are able to reconnect properly.

**Comment by amishshah** [comment]
Fixed in https://github.com/discordjs/discord.js/commit/793341dbb401f2956d60fd6b9f94a611cf539126
