### ISSUE TITLE
Wrong return type in jsdoc of ReactionUserStore.fetch

### ISSUE THREAD

**Issue by Splingush** [discordjs/discord.js#2895]
Hello!

It is documented that the promise that is returned resolves to a **ReactionUserStore**, but instead it resolves to a **Collection**.

See: 
https://github.com/discordjs/discord.js/blob/master/src/stores/ReactionUserStore.js#L21
and
https://github.com/discordjs/discord.js/blob/master/src/stores/ReactionUserStore.js#L28
https://github.com/discordjs/discord.js/blob/master/src/stores/ReactionUserStore.js#L34

That's it, thank you for your time!

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 73b9b0e62b46144d0a0e834f600f53a7efbe27ed

**Comment by PLASMAchicken** [comment]
Well:
ReactionUserStore extends DataStore
DataStore extends Collection

**Comment by KinectTheUnknown** [comment]
But that's like Person A promising Person B a Ham sandwich, but instead, giving Person B a piece of bread.

**Comment by Splingush** [comment]
Plasma, it's the wrong way around in the inheritance-chain. What it returns does not offer the methods of the store.
