### ISSUE TITLE
Detecting Invites

### ISSUE THREAD

**Issue by MrScopes** [discordjs/discord.js#2900]
Currently, it is very easy to detect invites; but you need to be using java to do this. 
```
if (Chat.hasInvite(message)) {
```
 - the primary method with java to detecting invites. I really think something like this should be added. There isn't really a very efficient way to detect invites with discord.js; hence why I am making this.

**Comment by Monbrey** [comment]
Is `channel.fetchInvites((string, invite) => {})` not a good enough equivalent to this?

**Comment by appellation** [comment]
Invite detection isn't in the scope of this library, as none of its functions depend on doing so. I recommend using an existing package or making a new one.

**Comment by SpaceEEC** [comment]
The method you are referencing seems to be a simple regex [see here](https://github.com/Minehut/MinehutBOT/blob/39d2d70045606fa772cdedf2da4dd484e45526bf/src/main/java/com/minehut/discordbot/util/Chat.java#L29-L31).
We do have a similar method yet different but private [here](https://github.com/discordjs/discord.js/blob/e189c1b728d8fd2742acc4d807e7559e807814fd/src/util/DataResolver.js#L29-L34).

Implementing one of the both regexes in your code should be a trivial thing to do.
