### ISSUE TITLE
brodcast message to a channel

### ISSUE THREAD

**Issue by muscaiu** [discordjs/discord.js#2904]
Spent 3 hours building and tweaking a nodejs web scraper and over 4 hours to find a freaking way to broadcast a message to a channel. I have lost all hope at this time...

This is the code i have, and some parts work, like replying to a message. But  i can't find any possible way to just send a message, without that message being a reply.

Plase help me. Thank u!

    const discord = require('discord.js');
    const bot = new discord.Client();
    const cfg = require('./config.json')

    bot.on('ready', () => {//this works
      console.log(`Logged in as ${bot.user.tag}(${bot.user.id}) on ${bot.guilds.size} servers`)
    });

    bot.on('message', (msg) => {
      switch (msg.content) {
        case '/epicinfo':
          msg.channel.send('w00t'); //this works
      }
    });

    console.log(bot.users.get("id", "504658757419270144")) //undefined
    console.log(bot.channels.get("name", "testbot")) //undefined
    console.log(bot.users.find("id", "504658757419270144")) //undefined
    console.log(bot.channels.find("name", "testbot")) //undefined
    console.log(bot.guilds.get("504658757419270144")); //undefined
    console.log(bot.channels.get(504658757419270144)) //undefined
    bot.send((discord.Object(id = '504658757419270144'), 'Hello')) //discord.Object is not a function

    bot.login(cfg.token);

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
