### ISSUE TITLE
Cannot read property "add" of undefined

### ISSUE THREAD

**Issue by Texlo-Dev** [discordjs/discord.js#2907]
**Please describe the problem you are having in as much detail as possible:**
When trying to play a stream from YTDL, I seem to get an error with the play() function.
```js
TypeError: Cannot read property 'add' of undefined
0|Fox      |     at AudioPlayer.playBroadcast (/home/rich/mr.fox-master/node_modules/discord.js/src/client/voice/player/AudioPlayer.js:20:27)
0|Fox      |     at VoiceConnection.play (/home/rich/mr.fox-master/node_modules/discord.js/src/client/voice/util/PlayInterface.js:64:26)
0|Fox      |     at FoxMusic.play (/home/rich/mr.fox-master/util/music/FoxMusic.js:85:51)
0|Fox      |     at FoxMusic.handleVideo (/home/rich/mr.fox-master/util/music/FoxMusic.js:130:22)
0|Fox      |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Include a reproducible code sample here, if possible:**
This is my handleVideo function: https://hastebin.com/fefuyotija.js
This is my play function: https://hastebin.com/mapomeciza.js

The stream is valid, I tested. Everything in my code seems to be lining up. This happens both locally and on my production server.

**Further details:**
- discord.js version: Latest
- Node.js version: 10.11.0
- Operating system: Linux Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: 
High: Cannot stream anything whatsoever.

- [ ] I found this issue while running code on a __user account__
- [ X] I have also tested the issue on latest master, commit hash:

**Comment by RTK99** [comment]
Update: So after tinkering around with things, I removed this condition at `node_modules/discord.js/src/client/voice/util/PlayInterface.js:64:26`
```js
if (resource instanceof Broadcast) {
      if (!this.player.playBroadcast) throw new Error('VOICE_PLAY_INTERFACE_NO_BROADCAST');
      return this.player.playBroadcast(resource, options);
    }```
Now I guess my new issue is, Why does this condition get triggered for the above code?

**Comment by TomSputz** [comment]
I'm not managing to reproduce this using that function alone, is it still a problem?

```js
const Discord = require('discord.js')
const ytdl = require('ytdl-core')

const client = new Discord.Client()
client.on('message', message => message.guild.channels.find(channel => channel.type === 'voice').join().then(conn => conn.play(ytdl('https://www.youtube.com/watch?v=y6Sxv-sUYtM', { filter: 'audioonly' }), { bitrate: 'auto' })))
client.login('TOKEN')
```

If it still is, would you mind making a reproducible sample to test with?

**Comment by amishshah** [comment]
Assuming this is resolved due to inactivity, if it's not then please reopen the issue
