### ISSUE TITLE
Replace snekfetch with a supported module

### ISSUE THREAD

**Issue by gunnerwolf** [discordjs/discord.js#2921]
**Is your feature request related to a problem? Please describe.**
[Snekfetch](https://www.npmjs.com/package/snekfetch), the NPM module used by Discord.js to handle making HTTP requests, has been deprecated by its author, who now recommends using the much more popular [node-fetch](https://www.npmjs.com/package/node-fetch) instead.

This deprecation results in a warning on `npm install`, and means that future issues/security concerns within snekfetch will not be addressed.

**Describe the ideal solution**
As mentioned above, the author recommends using [node-fetch](https://www.npmjs.com/package/node-fetch) instead, which is another lightweight requests module that works on a simple promise-based system (`fetch('url').then(doThing)`) and is directly based on the browsers' `window.fetch` function.

**Describe alternatives you've considered**
node-fetch, of course, is designed for browser-side use, rather than server-side, hence mimicking `window.fetch` closely. Another alternative would be [superagent](https://www.npmjs.com/package/superagent), whose syntax is near identical to snekfetch (as snekfetch is based on superagent). This would hopefully, for the most part, be a drop-in replacement due to the syntax similarity (`request.get('url').send(someData).then(doThing)`). However, superagent is not as lightweight as the other options.

It is still fast though, and its size (snekfetch's main selling point over superagent) shouldn't be an issue as Discord.js is not a browser library.

**Comment by Dev-Yukine** [comment]
This is already adressed in our master branch and will probaly be adressed in any minor release in the future if any will come before our next Major release.
