### ISSUE TITLE
Typings for Message incorrect

### ISSUE THREAD

**Issue by Sorunome** [discordjs/discord.js#2923]
The type for Message includes member as `public readonly member: GuildMember;` though, according to the doc, it is nullable: https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=member

Thus it should be `public readonly member: GuildMember | null;`

**Comment by Dev-Yukine** [comment]
This is already adressed in our master branch and will be backported by either the next patch or Major release we do.
