### ISSUE TITLE
MessagePort and Worker not defined in typings

### ISSUE THREAD

**Issue by jasonhaxstuff** [discordjs/discord.js#2924]
**Please describe the problem you are having in as much detail as possible:**
Okay, so basically: Whenever trying to compile a project with tsc I run into these errors every single time:
```bash
node_modules/discord.js/typings/index.d.ts:924:18 - error TS2304: Cannot find name 'Worker'.
924     public worker: Worker;
                       ~~~~~~

node_modules/discord.js/typings/index.d.ts:957:22 - error TS2304: Cannot find name 'MessagePort'.
957     public parentPort: MessagePort;
                           ~~~~~~~~~~~
```

Neither `Worker` nor `MessagePort` types are defined in the typings, so this needs to be done.

**Include a reproducible code sample here, if possible:**
```js
import * as Discord from 'discord.js'
```

**Further details:**
- discord.js version: Latest master (ab3a43919890f0a45812fd91788ea911a106f937)
- Node.js version: v8.11.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Probably a medium priority, because this doesn't prevent the build from finishing. It does spam my console everytime I compile, but it isn't fatal. It is pretty inconvenient, though.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: ab3a43919890f0a45812fd91788ea911a106f937

**Comment by devcat** [comment]
you will have to wait for node typings update to support node 10 or 11 as those are only versions that support workers
