### ISSUE TITLE
user.setActivity shows "Playing" instead of "Streaming" for ActivityType 1

### ISSUE THREAD

**Issue by guidojw** [discordjs/discord.js#2925]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js

client.user.setActivity("how to tie a tie", {type:1})

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v8.9.0
- Operating system: Raspbian GNU/Linux
- Priority this issue should have – please be realistic and elaborate if possible: Low: it's not critical, just annoying.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by bdistin** [comment]
https://discord.js.org/#/docs/main/11.4.2/class/ClientUser?scrollTo=setActivity

**Comment by jasonhaxstuff** [comment]
ClientUser#setActivity takes in parameters `name` and `options`, `options` containing `url` and `type`. So, a proper way to do this would be:

```js
client.user.setActivity("how to tie a tie", { type: 1 })
```

**Comment by guidojw** [comment]
Excuse me I guess I rushed the reproducible code, updated it.

**Comment by SpaceEEC** [comment]
You need to specify a syntactically correct twitch channel url as well.
See the already linked documentation.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by guidojw** [comment]
I thought this was a bug, the documentation doesn't explicitly state that you need to give a URL for when you want use the Streaming ActivityType, I expected it to work with just a string so it would show "**Streaming** [string]".
My apologies.
