### ISSUE TITLE
Leaving from guild without leaving voice, not updating list of members in voice

### ISSUE THREAD

**Issue by AymanDev** [discordjs/discord.js#2928]
If someone leaving server without leaving voice channel, and we trying to get list of users in this voice channel, discord.js not removing him from list. 

**Code:**
```js

const members = voiceChannel.members; 
// For example member A and B in voice channel.
// Member A leaving server without leaving voice channel before it
console.log(members); // Logging what member A and B still in voice channel
```
**How I'm fixing it:**
```js

// To fix it, just need to sort it
let members = voiceChannel.members;
// Filtering users by containing in guild members
members = members.filter(member => message.guild.members.has(member.id));
// And if member A leave like before, we'll don't have this problem
console.log(members); //Logging what member B still in voice channel
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.11.1
- Operating system: Microsoft Windows [Version 10.0.17134.345]
- Priority this issue should have: low

**Comment by amishshah** [comment]
The above commit should fix the issue, please test it!

**Comment by AymanDev** [comment]
Tested it with creating simple bot, with simple command.

Joined with friend in voice, writing `test`, bot replying this:
![image](https://user-images.githubusercontent.com/3704793/47989594-7be54600-e0f6-11e8-9592-ed164ffb471b.png)

Friend leaved server without leaving voice and bot replying this:
![image](https://user-images.githubusercontent.com/3704793/47989622-8dc6e900-e0f6-11e8-9b39-78f3b33243c1.png)

Friend joined again and bot replying this:
![image](https://user-images.githubusercontent.com/3704793/47989649-9d463200-e0f6-11e8-9b0e-884c4a9f6730.png)


@amishshah Thanks for fixing this problem ヾ(＾∇＾)
