### ISSUE TITLE
Why are there 2 different GuildChannels with a few different methods?

### ISSUE THREAD

**Issue by stuyy** [discordjs/discord.js#2938]
```
message.guild.channels.array().forEach(channel => {
        if(channel.type == 'text' && flag)
        {
            channel.updateOverwrite(member, {
                'SEND_MESSAGES': false,
                'EMBED_LINKS' : false,
                'ATTACH_FILES' : false,
                'MENTION_EVERYONE' : false
            });
            console.log("Muted user in " + channel.name);
        } else {
            channel.updateOverwrite(member, {
                'SEND_MESSAGES': true,
                'EMBED_LINKS' : true,
                'ATTACH_FILES' : true
            });
        }
    });
```

I'm trying to use the updateOverwite method on the channel object, but it says updateOverwrite is not a method. In the docs, there are two different GuildChannel classes?

https://discord.js.org/#/docs/main/stable/class/GuildChannel

This is the other GuildChannel, https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=updateOverwrite

How do you go about getting the 2nd GuildChannel object to use the updateOverwrite method?

**Comment by ansonfoong** [comment]
> The first one is the stable release on the npm, the second one is the master branch (development branch on GitHub)
> 
> You get the latter one by doing `yarn add discordjs/discord.js` but since its a major version upgrade chances are a lot of your existing code will break/not work anymore.

I tried installing the new master one but I think it's still on 11.4? I used npm, do I need to use yarn?
