### ISSUE TITLE
Docs listing incorrect Node version

### ISSUE THREAD

**Issue by jesusbibieca** [discordjs/discord.js#2940]
On `https://discord.js.org/#/docs/main/stable/general/welcome` the Node version showing as required is 6.0.0 or newer and in the project's README it shows 8.0.0 or newer. 

Not sure where the `json` doc is to open a PR.

**Comment by iCrawl** [comment]
Our stable branch does not require Node 8.

**Comment by jesusbibieca** [comment]
@iCrawl in this readme it clearly says that 8 is required. Not saying it is. Just that the docs are outdated/incorrect/not `required but maybe suggested` wording. :man_shrugging:

**Comment by iCrawl** [comment]
https://github.com/discordjs/discord.js/tree/stable
https://github.com/discordjs/discord.js/blob/stable/docs/general/welcome.md

You are looking at the wrong branch.
