### ISSUE TITLE
MessageDeleteBulk not being emitted

### ISSUE THREAD

**Issue by RighteousPotato** [discordjs/discord.js#2943]
**Please describe the problem you are having in as much detail as possible:**
The `MessageDeleteBulk` event isn't being emitted. Checked the library code and found there is no `if (response.message) client.emit(...);` line as found in the other event handlers.

**Include a reproducible code sample here, if possible:**
```js

client.on('MessageDeleteBulk', msg=>console.log('beep'));

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.9.3
- Operating system: Win7-64
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RighteousPotato** [comment]
I'm an idiot, sorry.

**Comment by jasonhaxstuff** [comment]
For people seeing this issue in the future -- it's 
```js
client.on('messageDeleteBulk', msg => console.log('deleted bulk')
```
, not `MessageDeleteBulk`.
