### ISSUE TITLE
Incorrect shard count 

### ISSUE THREAD

**Issue by DonovanDMC** [discordjs/discord.js#2945]
**Please describe the problem you are having in as much detail as possible:** No matter the shard count [`ShardClientUtil#count`](https://discord.js.org/#/docs/main/stable/class/ShardClientUtil?scrollTo=count) returns 1,[`ClientOptions#totalShards`](https://discord.js.org/#/docs/main/stable/typedef/ClientOptions) does return the correct shard count.
**Include a reproducible code sample here, if possible:**
```js
//index.js
const token = "";
const Discord = require("discord.js");
const manager = new Discord.ShardingManager(`main.js`, {token: token, respawn: true, totalShards: 2});

manager.on('shardCreate', (shard) => {
    console.log(`Successfully launched shard #${shard.id} (${+shard.id+1}/${shard.manager.totalShards})`);
});
// Successfully launched shard #0 (1/2)
// Successfully launched shard #1 (2/2)

manager.spawn();

//main.js
const token = "";
const Discord = require("discord.js");
const client = new Discord.Client();
client.on("ready",async()=>{
    console.log(`Shard #${client.shard.id} (${+client.shard.id+1}/${client.shard.count}) is ready.`);
});
client.login(token);
// Shard #0 (1/1) is ready.
// Shard #1 (2/1) is ready.
```
**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: v10.9.0
- Operating system: Windows Server 2012
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 3418b5a

**Comment by Koyamie** [comment]
Can confirm, also <Client>.status returns undefined.

**Comment by kyranet** [comment]
> ```js
> <Client>.status
> ```
> 
> returns undefined.

It's `<Client>.ws.status` now.

**Comment by Koyamie** [comment]
> 
> 
> > ```js
> > <Client>.status
> > ```
> > 
> > 
> > returns undefined.
> 
> It's `<Client>.ws.status` now.

Thank you, didn't know ^^
