### ISSUE TITLE
SHARDING_READY_TIMEOUT causing to create a duplicated instance.

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2955]
**Please describe the problem you are having in as much detail as possible:**
The `SHARDING_READY_TIMEOUT` error causes pm2 to **restart** the App without closing the first instance so it creates a duplicated instance of the bot.

I'll try to explain myself : 
- Starting the bot with `pm2 start X` (Sharding Manager with 42 shards).
- Bot is starting, every shards connect and are ready.
- One of the shards restart itself for a specific reason but is taking more than 30 seconds to be ready, the error `SHARDING_READY_TIMEOUT` drops.
- pm2 interprets it as a restart of the App so the Sharding Manager is starting again.
- Bot is now duplicated, Shards from the first instance + Shards of the new instance, doing `pm2 stop X` is only closing the first instance so the bot is always running on the instance somewhere on the server, having to kill processes to really have it closed.

So this is a complicated and hard to understand issue because this was not happening before, I already had few months ago this error when one of my shard was too long to be ready and it was only stopping the sharding manager to load shards, now I do not know why it is restarting the whole pm2 app.

**Include a reproducible code sample here, if possible:**
```js

// Place your code here

```

**Further details:**
- discord.js version: lastest master
- Node.js version: 10.9/12/13.0 - 11.1/2.0 (Tested with all of those versions)
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by rumblefrog** [comment]
So this is a compatibility issue with pm2? Because I personally never had this happen to me and I use pm2 as well.

**Comment by Koyamie** [comment]
> So this is a compatibility issue with pm2? Because I personally never had this happen to me and I use pm2 as well.

I think so, as it only happens on a specific issue.

**Comment by Gamercord-CEO** [comment]
Having same issues

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
