### ISSUE TITLE
Send opus to website with socket.io

### ISSUE THREAD

**Issue by IcedElect** [discordjs/discord.js#2966]
Hello, i have problem. I try get opussteram and send with socket.io to webpage.

    //server
    connection.on('speaking', (user, speaking) => {
        if(speaking) {
            const audioStream = receiver.createOpusStream(user);

            audioStream.on('data', (chunk) => {
                for(var i in SOCKET_LIST){
                    var socket = SOCKET_LIST[i];
                    socket.emit('voice', chunk);
                }
                console.log(`Received ${chunk.length} bytes of data.`);
            });

            audioStream.on('end', () => {

            })
        }
    });

    // client
    var audioCtx = false;
    document.querySelector('button').addEventListener('click', function() {
        audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        var socket = io.connect("http://127.0.0.1:2000");
        socket.on('voice', function (arrayBuffer) {
            playAudio(arrayBuffer);
        });
    })

    function playAudio(buffer){
        var started = false;
        if(!audioCtx) {
          audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }

        source = audioCtx.createBufferSource();
        audioBuffer = audioCtx.createBuffer( 2, 3840 * 2, audioCtx.sampleRate );
        audioBuffer.getChannelData( 0 ).set( buffer );
        source.buffer = audioBuffer;
        source.connect( audioCtx.destination );
        source.start(0);
        console.log(buffer);
    }

The browser shows that there is sound, but in fact only silence. Could you show a better way or help solve this problem? Thank you in advance

![console_screen](https://user-images.githubusercontent.com/23154788/48962817-cc81ed80-ef96-11e8-9ff8-721e60690ac0.png)

**Comment by cloudrex** [comment]
@devsnek socket.io is not "always the wrong choice" that clearly sounds like your opinion.

**Comment by BadCoder1337** [comment]
@IcedElect 
0) Migrate to discord.js from master branch
1) Decrypt/decode raw opus stream (idk how do this, change [receiver mode](https://discord.js.org/#/docs/main/master/class/VoiceReceiver?scrollTo=createStream) to pcm)
2) If you using browser only for listening voice, try [native](https://www.npmjs.com/package/speaker) sound output
3) Pray to Crawl#0002. Voice receiving documentation still sucks. 
![image](https://user-images.githubusercontent.com/16510197/49472730-32853500-f821-11e8-9af3-fff565071a81.png)

**Comment by amishshah** [comment]
Hi, we're unable to help with this because the issue tracker is just for Discord.js bugs. You can ask more about your problem on [our server] (https://discord.gg/bRCvFy9)
