### ISSUE TITLE
Client.guilds is Array[0] even if a bot is in 2 servers

### ISSUE THREAD

**Issue by someone0010** [discordjs/discord.js#2969]
**Please describe the problem you are having in as much detail as possible:**
I have been trying to do a rainbow role function for my friend's Discord server using a bot. I couldn't do it, because Client.guilds.get() - whenever an ID is correct (in string) returns null.

Client.guilds.keyArray() returns Array[0] and Client.guilds.first() returns null.

**Include a reproducible code sample here, if possible:**
```js
// ...
var r = client.guilds.get("493432486148177923").roles.get("501752627709870080"); // the error is here
setInterval(()=>{
  r.setColor([Math.floor(Math.random() * 255), Math.floor(Math.random() * 255), Math.floor(Math.random() * 255)]);
}, 15000);
// ...
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.0.0
- Operating system: Windows 10 1803 compilation 17134.112
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
First off "rainbow roles" are against Discord ToS since its API Abuse to spam request for chaning a role color, second if you are sure the id is correct then you probaly try to access Client#Guilds before your Client is ready make sure to wait until the Client emits the ready event

**Comment by MrScopes** [comment]
> First off "rainbow roles" are against Discord ToS since its API abuse to spam request for changing a role color, second if you are sure the id is correct then you probaly try to access Client#Guilds before your Client is ready make sure to wait until the Client emits the ready event

once every 15 seconds isn't against tos?

**Comment by Dev-Yukine** [comment]
it is, thats still abusing the api

**Comment by iCrawl** [comment]
Has been answered as above, apart from the ToS violation you probably access it before the ready event. 

Either way this needs more information and less ToS violation.
