### ISSUE TITLE
RichEmbed constructor don't accept MessageEmbed argument

### ISSUE THREAD

**Issue by antoine-pous** [discordjs/discord.js#2970]
**Please describe the problem you are having in as much detail as possible:**
`RichEmbed` constructor don't accept `MessageEmbed` argument.

**Include a reproducible code sample here, if possible:**
```typescript
const embeds: MessageEmbed[] = message.embeds;
const newEmbed: RichEmbed = new RichEmbed(embeds[0])
// error TS2345: Argument of type 'MessageEmbed' is not assignable to parameter of type 'RichEmbedOptions'.
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.6.0
- Operating system: Ubuntu (18.04)
- Priority this issue should have – please be realistic and elaborate if possible: Medium, we can bypass this issue by rewriting manually the whole `RichEmbed` properties instead of passing `MessageEmbed` as argument.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Should be fixed with the referenced commit.
In the meantime as a workaround you can cast the MessageEmbed to any before passing it to the constructor to not have to manually rewrite the whole thing.

**Comment by antoine-pous** [comment]
Now i use the master branch, the issue is fixed on it by moving RichEmbed to MessageEmbed :)
