### ISSUE TITLE
Rename Util to DiscordUtil

### ISSUE THREAD

**Issue by antoine-pous** [discordjs/discord.js#2973]
**Please describe the problem you are having in as much detail as possible:**
When we need to use `Util` from discord.js i have regulary a conflict with NodeJS Util module during autocompletion. Rename it to `DiscordUtil` fix the problem and improve the code readability when we use the two components into the same file.

**Further details:**
- discord.js version: 12
- Node.js version: 10.6
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
What exactly keeps you from doing `const nodeUtil = require('util');` or `const { Util: DiscordUtil } = require('discord.js')`

Thats what variables are here for, right?

**Comment by antoine-pous** [comment]
I'm using typescript, my bad i've missed to say it.

Currently when i import Util, my IDE import natively the NodeJS module instead of DiscordJS module, which is normal. Rename the Util class to DiscordUtil will avoid that, i know how to manage conflicts, this ticket is just a request to avoid it.

**Comment by iCrawl** [comment]
Is that because you type `Util.method` and Typescripts auto-import then proceeds to import Node.js' Util module?
VSCode I assume?

**Comment by antoine-pous** [comment]
Nope, i just use `Util.parseEmoji(cmd.args[0])` and IntelliJ import the NodeJS module, that's all. Using a strong typed name for this class seem a good way to avoid this kind of problems, Util is related to discord, then `DiscordUtil` seem better.

**Comment by iCrawl** [comment]
Ah, well yea thats exactly what I was talking about. Maybe I should have phrased that better 🤔

**Comment by antoine-pous** [comment]
Sorry i misread your message ^^'
