### ISSUE TITLE
cannot build my application by using  this in my visual studio c++application

### ISSUE THREAD

**Issue by gurmani11** [discordjs/discord.js#2975]
I have a C++ console application source code. i want to send a message at a required time through my application. is it possible to make Java script work with the C++ scripts?

**Comment by jasonhaxstuff** [comment]
Yo, this sounds like a question for the Discord server. [Check it out.](https://discord.gg/bRCvFy9) GitHub issues are meant to be for issues with the source code, not to ask questions about the library.

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
