### ISSUE TITLE
message.member is sometimes null

### ISSUE THREAD

**Issue by SenkJu** [discordjs/discord.js#2984]
**Please describe the problem you are having in as much detail as possible:**
My problem is as follows: Messages from certain users do not seem to have a member property (it is null). 
I have been developing Discord bots using Discord.js for quite some time but have experienced this problem before. Re-joining the server did not solve it. It does not occur when using the same code with the same bot account on a different server.

GIF of my problem: https://img.liquidbounce.net/uxc/2018-12-09_20-44-49.gif

**Include a reproducible code sample here, if possible:**
```js
const discord = require("discord.js");

const client = new discord.Client();

client.on("ready", () => {
    console.log("Ready!");
});

client.on("message", (message) => {
    let member = message.member;

    console.log(member);
});

client.login()
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v9.8.0
- Operating system: Windows 10 Home x64 Version 1809
- Priority this issue should have – please be realistic and elaborate if possible: Not very high.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by VonFriedricht** [comment]
do you mean message.author?

**Comment by xDimGG** [comment]
This is simply how caching works. Member's aren't guaranteed to be sent by the gateway if they're offline and should be fetched manually using [Guild#fetchMember](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchMember) when they're not available and needed.

**Comment by SenkJu** [comment]
Thanks, @xDimGG. Solved my problem.
