### ISSUE TITLE
My bot uncontrollably(even when isnt  running) spams about some new policies

### ISSUE THREAD

**Issue by BeaRRRRR** [discordjs/discord.js#2990]
**My bot(Alexa) recently started spamming about some new policies,and I cant make it stop,bot spams even when its not running.But when I click the link(http://bit.ly.com/2QwsEMq
) to accept the changes my browser says that there is no such site.I havent changed my code for a few wekks and my bot started spamming just recently,so i suppose there is no connection between my code and this error**

Here is what my bot spams
> @everyone
BOT Alexa received some changes! Please accept the new policies here:
http://bit.ly.com/2QwsEMq

**Further details:**
- discord.js version:11.4.2
- Node.js version:8.11.1
- Operating system: Windows 10

- [x ] I have also tested the issue on latest master, commit hash:

**Comment by izexi** [comment]
If you have nothing like that nowhere in your code then someone else has managed to get your bot's token, so you should regenerate your bot's token as soon as possible!
**Resetting your token**
- Head over to `https://discordapp.com/developers/applications/BOT_ID/bots`  (replacing "BOT_ID" with the ID of your bot)
- Click the "Regenerate" button and then "Yes, do it!" on the popup.

If you don't know how to get your bot's ID, then do the following:
- Go to <https://discordapp.com/developers/applications> and then click on the application that corresponds with your bot
- Click "Bot" on the left side 
- Click the "Regenerate" button and then "Yes, do it!" on the popup.

![](https://i.imgur.com/XtQsR9s.png)

*Make sure you never share your new token with anyone...*

**Comment by BeaRRRRR** [comment]
I regenerated my token, and it seems like it stopped spamming, thanks.
