### ISSUE TITLE
client.off is not a function

### ISSUE THREAD

**Issue by SpaceboyRoss01** [discordjs/discord.js#2991]
**Please describe the problem you are having in as much detail as possible:**
Trying to remove an event callback

**Include a reproducible code sample here, if possible:**
```js

  const onResponse = message => {
    if(message.channel.id == msg.channel.id) {
      responses.push(message);
      if(anwser.indexOf(message.content.toLowerCase()) > -1) {
        clearTimeout(timeout);
        msg.channel.send(msg.author.toString()+" got that one correct, +1 point");
        if(points[msg.author.id]) points[msg.author.id]++;
        else points[msg.author.id] = 1;
        client.off("message",onResponse);
        onEnd();
      }
    }
  };
  client.on("message",onResponse);
  timeout = setTimeout(() => {
    client.off("message",onResponse);
    msg.channel.send("Nobody got that right, the correct anwser is: \""+anwser+"\".").then(message => {
      responses.push(message);
      onEnd();
    }).catch(err => msg.channel.send(err.toString()));
  },6000);
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.12.0
- Operating system: Arch Linux
- Priority this issue should have – please be realistic and elaborate if possible: medium

Note: this is part of the Lordgenome discord bot's quiz code and this only happens when it's running through `pm2`, I've never got this issue while just running the index.js file without `pm2`.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by harmdhast** [comment]
```
emitter.off(eventName, listener)
Added in: v10.0.0
```
Upgrade your Node.js version ;)
