### ISSUE TITLE
Receiver stops capturing data after 5 minutes

### ISSUE THREAD

**Issue by E0HH** [discordjs/discord.js#2992]
**Please describe the problem you are having in as much detail as possible:**
If the bot creates a receiver and remains in the voice channel for more than 5 minutes, the receiver stops captures voice data. I've checked PCM and OPUS events, both stop capturing.

I've tried logging every client event (warn, error, debug and raw), every connection event (warn, error, debug and raw), as well as the warn event on the receiver, and nothing is emitted as an event to state why it loses functionality. 

If the bot is summoned into the voice channel, and it is kicked within 5 minutes, there is no issue. As stated below in the priority area, if its left in the voice channel for any longer, you must completely destroy the client and reinstate it in order to regain receiver functionality. 

Ive tried many, many ideas before bringing this up. Everything from creating the receiver after the speaking event is emitted, then detroying it once the the speaking event ends, to setting an interval for the dispatcher to play silence every minute, thinking maybe some sort of consistent action must happen due to like a hidden AFK event im not aware of. Nothing seems to keep the receiver active longer than 5 minutes.

The console log below is just a strongly minimal example to show whats happening. I have let it log in a channel with multiple members talking, where the receiver is constantly being used (emitting the PCM event over 50,000 times) and at 5 minutes it still goes dark. 

**Include a reproducible code sample here, if possible:**
```js

require('dotenv').config();
const { CLIENT_TOKEN } = process.env;
const Discord = require('discord.js');
const client = new Discord.Client();
const winston = require('winston');
const path = require('path');
const logger = winston.createLogger({
	transports: [new winston.transports.Console()],
	format: winston.format.combine(
		winston.format.timestamp({ format: 'MM/DD/YYYY HH:mm:ss' }),
		winston.format.printf(log => `[${log.timestamp}] [${log.level.toUpperCase()}]: ${log.message}`)
	)
});

var times = 0;

function countTimes() {
  times = times + 1;
}

client.on('ready', async () => {
const voiceChannel = client.channels.get('channel-ommited');
try {
	const connection = await voiceChannel.join().then(connection => {

		const dispatcher = connection.playFile(path.join(__dirname, 'audio', 'silence.mp3'));
		const receiver = connection.createReceiver();
		receiver.on('pcm', () => { countTimes(); });


		connection.on('speaking', (user, speaking) => {
		  if (speaking) {
		    logger.info('Emitted speaking event');
		  }
		  if (!speaking) {
		    logger.info(`Emitted PCM ${times} times`);
		  }
		});  //end speaking events
	});  //end voice connection
} catch (error) { console.log(error) }
});  //end client ready event

client.login(CLIENT_TOKEN);


////////////////////////////////////////////////////////////////////////////////////

console log:
[12/17/2018 14:01:12] [INFO]: Emitted speaking event
[12/17/2018 14:01:13] [INFO]: Emitted PCM 43 times
[12/17/2018 14:01:28] [INFO]: Emitted speaking event
[12/17/2018 14:01:33] [INFO]: Emitted PCM 285 times
[12/17/2018 14:01:33] [INFO]: Emitted speaking event
[12/17/2018 14:01:35] [INFO]: Emitted PCM 380 times
[12/17/2018 14:01:37] [INFO]: Emitted speaking event
[12/17/2018 14:01:38] [INFO]: Emitted PCM 406 times
[12/17/2018 14:01:50] [INFO]: Emitted speaking event
[12/17/2018 14:01:50] [INFO]: Emitted PCM 439 times
[12/17/2018 14:06:04] [INFO]: Emitted speaking event
[12/17/2018 14:06:06] [INFO]: Emitted PCM 527 times
[12/17/2018 14:06:24] [INFO]: Emitted speaking event    ///this is where it stops capturing
[12/17/2018 14:06:25] [INFO]: Emitted PCM 536 times
[12/17/2018 14:06:25] [INFO]: Emitted speaking event
[12/17/2018 14:06:26] [INFO]: Emitted PCM 536 times
[12/17/2018 14:08:02] [INFO]: Emitted speaking event
[12/17/2018 14:08:04] [INFO]: Emitted PCM 536 times
[12/17/2018 14:09:15] [INFO]: Emitted speaking event
[12/17/2018 14:09:16] [INFO]: Emitted PCM 536 times
[12/17/2018 14:09:24] [INFO]: Emitted speaking event
[12/17/2018 14:09:24] [INFO]: Emitted PCM 536 times
[12/17/2018 14:09:29] [INFO]: Emitted speaking event
[12/17/2018 14:09:29] [INFO]: Emitted PCM 536 times
[12/17/2018 14:09:33] [INFO]: Emitted speaking event
[12/17/2018 14:09:33] [INFO]: Emitted PCM 536 times
[12/17/2018 14:09:57] [INFO]: Emitted speaking event
[12/17/2018 14:09:57] [INFO]: Emitted PCM 536 times
[12/17/2018 14:10:36] [INFO]: Emitted speaking event
[12/17/2018 14:10:36] [INFO]: Emitted PCM 536 times

```

**Further details:**
- discord.js version: Stable 11.4.2
- Node.js version: Tried on 9.10.1, 10.12 and 11.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible:
HIGH. The client must be completely destroyed and reinstated in order to regain voice data again. This obviously creates huge complications on bots connected to more than one server. 

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Sorry about this issue, could you try 2 things and tell me if either of them work? First, try playing some silent audio on voice channels you're connected to, there's a Discord bug where connected bots can't receive audio unless they're playing audio. If that doesn't work, can you try using the latest master version? In master the internals are different so hopefully that will fix it.

**Comment by E0HH** [comment]
> Sorry about this issue, could you try 2 things and tell me if either of them work? First, try playing some silent audio on voice channels you're connected to, there's a Discord bug where connected bots can't receive audio unless they're playing audio. If that doesn't work, can you try using the latest master version? In master the internals are different so hopefully that will fix it.


Hello amishshah,

As for your first suggestion, that was indeed done within the original snippet above. I went through pages and pages of previously related voice issues to validate there isn't anything I could possibly be missing. If I didnt do this, I wouldnt receive a PCM event at all, so beginning the connection with a silent sound is always incorperated into my code until Discord can fix the issue on their end.

As for the second suggestion, here is the code below. I changed my node version to the newest LTS version (10.12.2), and completely cleaned out every other version to validate Node related issues. I started with a new folder and installed the Master (12.0.0-Dev) with every dependency (UWS, Node-Opus, BufferUtil, Zlib-Sync, erlpack and the newest Sodium 3.0.2). 

As you can see, the issue still persists. The receiver continues to stop capturing voice data after the 5 minute mark. I ran it three times just for validation purposes. 

```javascript
require('dotenv').config();
const { CLIENT_TOKEN } = process.env;
const Discord = require('discord.js');
const client = new Discord.Client();
const winston = require('winston');
const path = require('path');
const logger = winston.createLogger({
	transports: [new winston.transports.Console()],
	format: winston.format.combine(
		winston.format.timestamp({ format: 'MM/DD/YYYY HH:mm:ss' }),
		winston.format.printf(log => `[${log.timestamp}] [${log.level.toUpperCase()}]: ${log.message}`)
	)
});

var times = 0;

function countTimes() {
  times = times + 1;
}

client.on('ready', async () => {

const voiceChannel = client.channels.get('channel-removed');
try {
  const connection = await voiceChannel.join().then(connection => {

    const dispatcher = connection.play(path.join(__dirname, 'silence.mp3'));

    dispatcher.on('end', () => {
      console.log('Audio played, connection is now fully established.')
    });


    connection.on('speaking', (user, speaking) => {

      const receiver = connection.receiver.createStream(user, { mode: 'pcm', end: 'silence' });

      receiver.on('data', () => { countTimes(); });

      if (speaking.bitfield === 1) {
        logger.info('Emitted speaking event');
       }

      if (speaking.bitfield === 0) {
        logger.info(`Emitted PCM ${times} times`);
      }

		});  //end speaking events
	});  //end voice connection
} catch (error) { console.log(error) }
});  //end client ready event

client.login(CLIENT_TOKEN);


//////////////////////////////////////////////////////////////////////////////////////////////////////////////
console log:

Audio played, connection is now fully established.
[12/18/2018 13:36:37] [INFO]: Emitted speaking event
[12/18/2018 13:36:38] [INFO]: Emitted PCM 68 times
[12/18/2018 13:36:43] [INFO]: Emitted speaking event
[12/18/2018 13:36:44] [INFO]: Emitted PCM 128 times
[12/18/2018 13:39:34] [INFO]: Emitted speaking event
[12/18/2018 13:39:35] [INFO]: Emitted PCM 152 times
[12/18/2018 13:39:35] [INFO]: Emitted speaking event
[12/18/2018 13:39:36] [INFO]: Emitted PCM 200 times
[12/18/2018 13:40:45] [INFO]: Emitted speaking event
[12/18/2018 13:40:45] [INFO]: Emitted PCM 245 times
[12/18/2018 13:40:46] [INFO]: Emitted speaking event
[12/18/2018 13:40:47] [INFO]: Emitted PCM 278 times
[12/18/2018 13:41:16] [INFO]: Emitted speaking event
[12/18/2018 13:41:18] [INFO]: Emitted PCM 351 times
[12/18/2018 13:41:32] [INFO]: Emitted speaking event
[12/18/2018 13:41:33] [INFO]: Emitted PCM 419 times
[12/18/2018 13:41:34] [INFO]: Emitted speaking event
[12/18/2018 13:41:34] [INFO]: Emitted PCM 426 times
[12/18/2018 13:42:09] [INFO]: Emitted speaking event
[12/18/2018 13:42:10] [INFO]: Emitted PCM 426 times
[12/18/2018 13:42:35] [INFO]: Emitted speaking event
[12/18/2018 13:42:36] [INFO]: Emitted PCM 426 times
[12/18/2018 13:43:05] [INFO]: Emitted speaking event
[12/18/2018 13:43:06] [INFO]: Emitted PCM 426 times
[12/18/2018 13:43:53] [INFO]: Emitted speaking event
[12/18/2018 13:43:54] [INFO]: Emitted PCM 426 times
[12/18/2018 13:44:15] [INFO]: Emitted speaking event
[12/18/2018 13:44:17] [INFO]: Emitted PCM 426 times
[12/18/2018 13:44:17] [INFO]: Emitted speaking event
[12/18/2018 13:44:18] [INFO]: Emitted PCM 426 times
[12/18/2018 13:44:20] [INFO]: Emitted speaking event
[12/18/2018 13:44:21] [INFO]: Emitted PCM 426 times
[12/18/2018 13:44:22] [INFO]: Emitted speaking event
[12/18/2018 13:44:22] [INFO]: Emitted PCM 426 times
[12/18/2018 13:44:24] [INFO]: Emitted speaking event
[12/18/2018 13:44:25] [INFO]: Emitted PCM 426 times

```

**Comment by amishshah** [comment]
Could you try creating the receiver only if the user is actually speaking?

**Comment by E0HH** [comment]
Sorry for the delay, here is what I came up with. I already was creating the receiver on a speaking event, I had to since no "user" is defined until a speaking event happens. But I assume you mean create the receiver on actual voice data, so I moved it inside the actual voice event. Because I also assume what you are trying to check is only create a receiver on voice data, I am lead to believe you would like to see it nulled out to "destroy" it at the end of a speaking event. Since V12 has no destroy option, I THINK if my programming knowledge is correct im nulling the receiver out when the speaking event ends. I am not a master at JS like you yourself are, so please dont judge me if this is hacked together. If I declared the receiver with a const I couldnt redeclare it, or in a sense null it out, so I turned it into a var to I could hoist it with the speaking events. 

If the code below is acceptable to you and is more or less what you were aiming to test, then the issue still persists. 5 minutes and it still breaks. It seems no matter what I do, the minute you create a receiver, you have 5 minutes of usefulness and its gone. Again, pardon the code if its not clean. 

I did not include a console log below but you can look at it here: [console.txt](https://github.com/discordjs/discord.js/files/2697607/console.txt) I didnt add it because I was reading the receiver itself, so it produced the whole object when voice was being read, and then changed to null at the end of every speaking event. I was just logging the validation that receiver was hoisting itself to null and "destroying".

All code from V12 example above is the same except for this change you requested:
```javascript
connection.on('speaking', (user, speaking) => {

   var receiver;

 switch (speaking.bitfield) {

	case(1):
	   receiver = connection.receiver.createStream(user, { mode: 'pcm', end: 'silence' });
	   receiver.on('data', () => { countTimes(); });
	break;

	case(0):
	    logger.info(`Emitted PCM ${times} times`);
	    receiver = null;
	break;
   }

console.log(receiver);

});  //end speaking events

```

**Comment by amishshah** [comment]
Thanks for testing this out, I'll try and have a look today

**Comment by E0HH** [comment]
Hello! is there any update on the status of this?

**Comment by E0HH** [comment]
Just some info here, after reading about the ongoing issues in regards to the Discord API issue about having to play audio in order to receive audio [here](https://github.com/discordjs/discord.js/issues/2929)
And the JDA reference about it [here](https://github.com/DV8FromTheWorld/JDA/issues/789)
One of comments stated to "saturate the channel with silence". From the beginning of my issue I was only playing audio after the connection was established with a short 2 second silent clip, which granted me voice receiver access for exactly 5 minutes. Since reading the thread above for JDA, I tried saturating the channel with a silent audio clip longer than 5 minutes and it keeps the receiver alive for as long as the audio plays. It seems as though as long as I maintain consistent playback of audio, I keep the receiver in an active state. If the playback ends after the 5 minute mark, I lose the receiver. Examples:

4 minute, 30 second clip, I will lose the voice receiver 30 seconds later.
10 minute clip, I keep the receiver until the clip ends. Upon ending, I lose the receiver with it.
1 hour long clip(what I currently am choosing to do), keeps the receiver alive until ending. 

I know you stated you had trouble reproducing, but for me and some others, the issue has persisted. I understand it must be difficult to fix something with little to no documentation so hopefully referencing this to other voice issues across languages can help with alleviating all of these issues. Or I may have to deal with this issue for quite some time, we will see

**Comment by amishshah** [comment]
It's reassuring to see that you've been able to fix it by playing the audio for longer, it makes me think that this issue is definitely related to the recent breaking changes to voice.

As we're _still_ without any documentation or communication of any of these changes made by Discord, I think the best approach would be to just wait for Discord to finally address the issue and fix the bugs themselves rather than try to build some workarounds into Discord.js itself.

Sorry you're facing this issue, I'll leave this open until it's resolved. Out of curiosity, could you try running this on a Central European voice server without any workarounds implemented and tell me if you can still reproduce the issue? Thanks!

**Comment by amishshah** [comment]
Also, if you want a temporary workaround this is the way I would recommend "playing silence":

```js
const { Readable } = require('stream');

const SILENCE_FRAME = Buffer.from([0xF8, 0xFF, 0xFE]);

class Silence extends Readable {
  _read() {
    this.push(SILENCE_FRAME);
  }
}

// play silence indefinitely, this should allow you to continue receiving audio
voiceConnection.play(new Silence(), { type: 'opus' });
```

**Comment by amishshah** [comment]
This is now essentially the same issue as #2929, so I'm closing this issue and will post any updates there!
