### ISSUE TITLE
roleUpdate event fires twice

### ISSUE THREAD

**Issue by steven4547466** [discordjs/discord.js#2995]
**Please describe the problem you are having in as much detail as possible:**
Whenever I update a role, the event "roleUpdate" fires twice. So it sends 2 messages instead of one.

**Include a reproducible code sample here, if possible:**
```js

bot.on('roleUpdate', async (oldRole, newRole) => {
 	var guild = newRole.guild
 	var logs = guild.channels.find('name', "audit-logs")
	logs.send(newRole.name);
});

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: Unknown
- Operating system: Hosted on Heroku, I'm unsure what it is.
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by SpaceEEC** [comment]
Could this maybe be related to https://github.com/discordjs/discord.js/issues/2959?
If you got the role actually updated and the everyone role (in any order), it's the case.

---

#### If it's the same role in both updates

Do you get in both updates the old and the new role as expected? (Aside the event firing twice)
If not in what states are you getting the roles? (old, new, something else)

Do you actually receive two updates / packets from Discord?
Check the raw event: `client.on('raw', event => console.log(event.t));`
  > Will log a lot, you might want to filter that to just `ROLE_UPDATE`s
