### ISSUE TITLE
Heartbeat Acknowledge Timeout

### ISSUE THREAD

**Issue by rumblefrog** [discordjs/discord.js#3004]
**Is your feature request related to a problem? Please describe.**
As per heart beating spec <https://discordapp.com/developers/docs/topics/gateway#heartbeating>, the library should terminate with non-1000 ws close frame, reconnect and attempt to resume whenever the client does not receive a heartbeat acknowledgment from Discord in between heartbeats.

**Describe the ideal solution**
if lastAck + (2 * heartBeatInterval) < currentTime
- closeWithNon1000 ws
- reconnect
- identify with last session id

**Additional context**
This might resolve some people's hitting the token reset limit, as it gives a better chance to resume rather than starting a new session, in which it counts towards the daily session start limit. In addition to terminating zombie connections.

**Comment by rumblefrog** [comment]
@Lewdcario mentioned he would implement this in his #2996 PR. So this issue merely serves as a reference.

**Comment by vladfrangu** [comment]
This was already implemented as of https://github.com/discordjs/discord.js/commit/793341dbb401f2956d60fd6b9f94a611cf539126
