### ISSUE TITLE
Incorrect GuildMember fetch example

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#3007]
**Please describe the problem you are having in as much detail as possible:**
Incorrect GuildMember fetch example on line [87](https://github.com/discordjs/discord.js/blob/master/src/stores/GuildMemberStore.js#L87).

**Include a reproducible code sample here, if possible:**
Within the GuildMember.js file on line [87](https://github.com/discordjs/discord.js/blob/master/src/stores/GuildMemberStore.js#L87) shows this example, which is wrong. I have tried it and it doesn't fetch a single user because it says the UserResolvable is a part of the options object which it shouldn't be.
```js
guild.members.fetch({ user, cache: false })
   *   .then(console.log)
   *   .catch(console.error);
```
I played around with it and found it should really be like this.
```js
guild.members.fetch(user, { cache: false })
   *   .then(console.log)
   *   .catch(console.error);
```
Because the UserResolvable shouldn't be apart of the options. I tried it the way the example shows and it just returns a whole list of the guilds members within a map object.
```js
h!eval const usr = this.client.users.get('315169774688534530');
msg.guild.members.fetch({ usr, cache: true }).then(async(user) => {
	return user.map((member) => member.id);
}).catch(console.error);
```
and the one below worked as intended and returned only that one user like it was supposed to.
```js
h!eval const usr = this.client.users.get('315169774688534530');
msg.guild.members.fetch(usr, { cache: true }).then(async(user) => {
	return user.id
}).catch(console.error);
```

**Further details:**
- discord.js version: `12.0.0-dev`
- Node.js version: `Node v11.5.0`
- Operating system: `Linux x64`
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
The example says `// Fetch a single member without caching`
To achieve that it uses GuildMemberstore#fetch with <https://discord.js.org/#/docs/main/master/typedef/FetchMemberOptions>, an object with user and cache properties. If a User instance is bound to "user"
```js
const user = message.author
{ user:user, cache: false }
```
and
```js
const user = message.author
{ user, cache: false }
```
will result in the exact same object. You can read more about the use of Object initializer shorthands [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015)
