### ISSUE TITLE
Text formatting error in documentation

### ISSUE THREAD

**Issue by GabrielMar** [discordjs/discord.js#3009]
**Please describe the problem you are having in as much detail as possible:**
The code complement in the IDE has the wrong language, different from the site documentation

**Include a reproducible code sample here, if possible:**
```js
// ERRORS complemented
message.guild.setExcplicitContentFilter(0)
message.guild.setDefaultMessageNotification("ALL")
// RIGHT
message.guild.setExplicitContentFilter(0)
message.guild.setDefaultMessageNotifications("ALL")
// The error is in the "Excplicit" in the additional "c";
// No "Notification" in the "s" that is missing
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v10.15.0
- Operating system: Linux Mint 19.1
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:
![error3](https://user-images.githubusercontent.com/38334104/50564751-dbcf2600-0d0e-11e9-9530-7139e103468d.png)
![error2](https://user-images.githubusercontent.com/38334104/50564752-dbcf2600-0d0e-11e9-9c5b-333ab0faa586.png)
![error](https://user-images.githubusercontent.com/38334104/50564753-dbcf2600-0d0e-11e9-9c19-cd38583bc250.png)

**Comment by SpaceEEC** [comment]
Should be fixed with the referenced commit.
