### ISSUE TITLE
bot embed line break

### ISSUE THREAD

**Issue by blockyTj995** [discordjs/discord.js#3012]
I'm trying to get it were each "command" seperates for my help message.

heres my code:

case "help":
            var embed = new Discord.RichEmbed()
                .setTitle("**JiinxBot.**")
                .setDescription("Made By **Conundrum2k**.")
                .addField("?~help", "Brings Up This Message.")
                .addField("?~ping", "Tells You The Ping Of The Bot")
                .addField("?~8ball", "Tells You Your Fortune!")
                .addField("?~play", "Plays Music!")
                .addField("?~stop", "Stops Music.")
                .addField("?~skip", "Skips Music")
                .setColor(0x9370DB)
            message.channel.sendEmbed(embed);
            break;

**Comment by tipakA** [comment]
This is not place for basic help. It's for actual issues with library.

For basic help with lib's functionality, please go [official support server](https://discord.gg/bRCvFy9)

**Comment by CT-NickTheDev** [comment]
Hello blockyTj995, When you are creating a embed like that, you put the break at the last line.
For you this would be `.setColor(0x9370DB)` just change this to `.setColor(0x9370DB);`

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
