### ISSUE TITLE
discord events are based on the audit log

### ISSUE THREAD

**Issue by Luk3HD** [discordjs/discord.js#3013]
Currently some events do not have all the information that is of interest to the people on the server. An example is those of Channel and Role, that when being updated / created / deleted does not contain who executed the action.

sorry my english I hope you understood :+1:

**Comment by almostSouji** [comment]
The issue template is there for a reason - which is not for you to ignore it
"Who did something" can be found in `GuildAuditLogsEntry#executor` in all recent versions
I tested all three cases and could not get it to malfunction on 11.4.2/ -dev / v12

**Comment by SpaceEEC** [comment]
Discord does not provide who executed the action in the packets they send via the gateway.
Those bits are only available in the Audit Log, which you have to manually fetch.
