### ISSUE TITLE
Shard 0 gateway timing out after a few seconds

### ISSUE THREAD

**Issue by pizzafox** [discordjs/discord.js#3021]
**Please describe the problem you are having in as much detail as possible:**

Ever since updating to a recent version of master branch, my shard 0 has been timing out with the gateway after a few seconds of functioning fine. I can reproduce this reliably each time I turn the bot on.

**Include a reproducible code sample here, if possible:**

My code hasn't changed other than updating dependencies. Here's the testing I did for each hash since a working version and the latest version:
```
BROKEN  8230255c68b94d68a4e8ffc559a98d08d1a08a7c
WORKING 28db5273708af039ef6a5387273d4407d55f178c
WORKING 840d22f8920f7648f97109d3df6f8a9b1da9f20f
WORKING 0bde9ca2c58785f2e1093698268aa9bdc525f5a5
WORKING 8a76cc5c725ffcfe8131c652de3d16be1f51439a
WORKING 8286d1a0fc3e86a10b7d5f977836b0e0fe611c27
....... 21ec03140f182b93ddc151e9edbdb6da8d8ae703
....... 5cbdf380289f0fd1d16330325dab71f8815396fc 
WORKING b5d5c699e65bf14a77065a75aabd24e4972988a9
```
There a few (>5) times where results were inconsistent, but that might be me screwing up my tests. If you really care about code, [this is my bot's code](https://github.com/dice-discord/bot/commit/02f59339cfa6c2364daa4c3b429c52ff1ea9be04) where I can confirm the problem was occurring.

Here are logs with debug mode on of my bot: https://hastebin.com/podokozise.log.

**Further details:**
- discord.js version: master
- Node.js version: `10.15.0`
- Operating system: Debian 9.5
- Priority this issue should have – please be realistic and elaborate if possible: low (I seem to be the only person experiencing it)

I've tried the following:
- deleting node_modules
- turning it off and on again
- switching computers
- resetting token

All of which had no effect. The only thing that seems to have any impact on the problem is changing which Discord.js version I use.

This issue has had me wracking my brain for the last few days, any help would be greatly appreciated.

- [x] I have also tested the issue on latest master, commit hash: 8230255c68b94d68a4e8ffc559a98d08d1a08a7c

**Comment by pizzafox** [comment]
The same thing is happening on the latest commits. Can someone take a look at this please? It's really annoying to not be able to update to the latest version of Discord.js.

**Comment by kyranet** [comment]
Maybe try #2976/#2996? It should fix your issue (and anybody else's)

**Comment by amishshah** [comment]
#2976 has been merged into master in commit https://github.com/discordjs/discord.js/commit/793341dbb401f2956d60fd6b9f94a611cf539126, can you try that out and see if it helps? Thanks

**Comment by amishshah** [comment]
Also, if you're able to collect debug information that would greatly help:
```js
client.on('debug', console.log);
```

**Comment by pizzafox** [comment]
Sorry for not responding earlier. I'm pretty sure I'm running the hash you specified. Same issue is occurring. Logs are available [here](https://gist.github.com/pizzafox/94d25eb5c3ef561923bcc2f9a6abd9a1).

**Comment by pizzafox** [comment]
#3140 fixes this issue.
