### ISSUE TITLE
site code error

### ISSUE THREAD

**Issue by Luk3HD** [discordjs/discord.js#3022]
**Please describe the problem you are having in as much detail as possible:**
The documentation has a typo, at https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=fetchInvite

**Include a reproducible code sample here, if possible:**

`` `js
client.fetchInvite('https://discord.gg/bRCvFy9')
  .then(invite => console.log(`Obtained invite with code: ${invite.code}`) // I should have one here)
  .catch(console.error);
`` `

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v10.12.0
- Operating system: win7
- Priority this issue should have – please be realistic and elaborate if possible: minimum

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
Would you mind to elaborate on said typo?
Because i honestly can not find it.

**Comment by Darqam** [comment]
The .then isn't closed properly actually.
