### ISSUE TITLE
fetchApplication() Error

### ISSUE THREAD

**Issue by Luk3HD** [discordjs/discord.js#3029]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to use the fetchApplication () method, but it results in the Error of the Discord API
  `` `name: 'DiscordAPIError',
   message: 'Bots can not use this endpoint'
   path: '/ api / v7 / oauth2 / applications / @ me',
   code: 20001,
   method: 'GET'``

**Include a reproducible code sample here, if possible:**
```js

client.appInfo = await client.fetchApplication (). then (application => console.log (`Obtained application with name: $ {application.name}`))
.catch (console.error)
setInterval (async () => {
client.appInfo = await client.fetchApplication (). then (application => console.log (`Obtained application with name: $ {application.name}`))
     .catch (console.error)
}, 60000);

```

**Further details:** 
- discord.js version: 11.4.2
- Node.js version: v10.12.0
- Operating system: win7
- Priority this issue should have – please be realistic and elaborate if possible: median

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment]
Related to https://github.com/discordapp/discord-api-docs/issues/815

**Comment by zeroidentidad** [comment]
> Discord has resolved that issue, see the referenced issue ^

where?
