### ISSUE TITLE
Embed column limit is fixed at 40 characters

### ISSUE THREAD

**Issue by Alchete** [discordjs/discord.js#3030]
There appears to be no way to combine triple-backticks for monospace font, with "embed" and exceed 40 columns.  (There's no such column width restriction (or auto wordwrap) when not using embed.)

This makes it impossible to create tables of data wider than 40 columns while also using embed for rich formatting.

Ideal solutions include:
-  The presence of triple backticks automatically removing the 40 column restriction.  
-  Alternatively, having a switch in the embed option list to remove the 40 column limit (disable word-wrap).

This is what currently happens when trying to create a monospace table with "embed".
![image](https://user-images.githubusercontent.com/4705189/51424956-8bc3e080-1ba3-11e9-9479-747e54eecdb0.png)

**Comment by kyranet** [comment]
This is not something discord.js does, but Discord itself (at least, the client), it's just some client-side CSS doing word wrapping.
