### ISSUE TITLE
message.guild.emojis.array(c => c).length ? message.guild.emojis.array(c => c).length > 25 : "trop d'emojis" is returning false or true

### ISSUE THREAD

**Issue by pafad** [discordjs/discord.js#3034]
I'm trying to make a condition if the embed field is too long because of roles or emojis it will replace it by "too many" roles or emojis

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
