### ISSUE TITLE
Support for HTTP agents to make this work through proxies

### ISSUE THREAD

**Issue by rednnnno** [discordjs/discord.js#3039]
**Is your feature request related to a problem? Please describe.**
It has been asked in Issue#489 to add support for proxies. I've dealt with this because I'm stuck behind one with and have lot of software with such issues... so I took the time to actually make this work with this project since I wanted it to work and not build my own... :)

I'm sorry I can't make a proper diff or a proper merge for you guys however I'm not certain how you would wish to approach this

Here are the 2 edits I "hacked in" to get this to work behind a SOCKS5 proxy (on the main stable build):
*src\client\rest\APIRequest.js(38)*:
```JavaScript
    const opts = {agent: new require('socks-proxy-agent')('socks://<server>:<socket>')};
    const request = snekfetch[this.method](`${API}${this.path}`, opts);
```
and *src\client\websocket\WebSocketConnection.js(254)*:
```JavaScript
    const opts = {agent: new require('socks-proxy-agent')('socks://<server>:<socket>')};
    const ws = this.ws = new WebSocket(gateway, undefined, opts);
```
**Describe the ideal solution**
Normally we wouldn't be instantiating that twice, so the user should do it prior to the creation of the object and probably be passed as an optional parameter in the constructor? If set, creates the options object when needed with the agent property passed along to the ws/snekfetch libraries.

Didn't test with uws.

**Describe alternatives you've considered**
Hacked above code in...

**Additional context**
If you need me to test anything I'm willing!

**Comment by rednnnno** [comment]
Is there a way to get this in? I don't mind coding it; I just need someone to take a stance on how to do it: in my query: in which Object to store the **opts** constant; and just agree that it should be a constructor option!

**Comment by bohrasd** [comment]
I don't know much about javascript but I tried your code and it worked very well, and it saved my day. Thx!

**Comment by devsnek** [comment]
does something like https://www.npmjs.com/package/global-agent work? doing this at the library level seems like the wrong place.

**Comment by encloinc** [comment]
src\client\websocket\WebSocketConnection.js(254) <- This script is no longer present

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.

**Comment by Dorian-Grim** [comment]
Updating this for 13.6:

1. _node_modules\discord.js\src\rest\APIRequest.js(78)_

```js
, agent: new require('proxy-agent')('hostname:port')

```
2. _node_modules\discord.js\src\client\websocket\WebSocketShard.js(256)_

```js
const ws = (this.connection = WebSocket.create(gateway, wsQuery, {agent: new require('proxy-agent')('hostname:port')}));
```

**Comment by rlog** [comment]
> Updating this for 13.6:
> 
> 1. _node_modules\discord.js\src\rest\APIRequest.js(78)_
> 
> ```js
> , agent: new require('proxy-agent')('hostname:port')
> ```
> 
> 2. _node_modules\discord.js\src\client\websocket\WebSocketShard.js(256)_
> 
> ```js
> const ws = (this.connection = WebSocket.create(gateway, wsQuery, {agent: new require('proxy-agent')('hostname:port')}));
> ```

this tips work fine, But also a hack way

Is there any official way to do this?
