### ISSUE TITLE
impossible d'installer avec la commande NPM

### ISSUE THREAD

**Issue by MatazoxGaming** [discordjs/discord.js#3041]
C:\Users\USER-MASQUER\Desktop\AntiRaid\node_modules\integer>if not defined npm_config_node_gyp (node "D:\Installation\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Installation\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Les projets sont g▒n▒r▒s individuellement dans cette solution. Pour activer la g▒n▒ration en parall▒le, ajoutez le commutateur "/m".
MSBUILD : error MSB4025: Impossible de charger le fichier projet. ▒l▒ment racine manquant.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Installation\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Installation\\nodejs\\node.exe" "D:\\Installation\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USER-MASQUER\Desktop\AntiRaid\node_modules\integer
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord.js@12.0.0-dev requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN enmap@4.7.0 requires a peer of better-sqlite-pool@github:eslachance/better-sqlite-pool but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER-MASQUER\AppData\Roaming\npm-cache\_logs\2019-02-01T17_26_02_676Z-debug.log

voici mon erreur

**Comment by benftwc** [comment]
Salut, premièrement, t'aura plus de support si tu poste en anglais tes tickets :)

Ensuite, essaie en ajoutant les build tools sur Windows, en passant par PowerShell en admin et en ajoutant les outils de compilation de Windows VS 2005 que tu trouvera chez [Microsoft directement](https://www.microsoft.com/en-us/download/details.aspx?id=5553)

`npm i -g --add-python-to-path --vs2015 --production windows-build-tools`

Si besoin d'aide, ping moi : `Larry Potter#9153`

**Comment by MatazoxGaming** [comment]
ok je vais essayer merci :)
