### ISSUE TITLE
Missing name property in GuildCreateChannelOptions

### ISSUE THREAD

**Issue by nycex** [discordjs/discord.js#3050]
Im using discord.js with typescript and i have a problem with GuildCreateChannelOptions from index.d.ts, because it doesnt contain the property 'name' like it does in the js code. Because of that is always throws a error on compiling.

**Include a reproducible code sample here, if possible:**
```ts
someChannel.clone({ 'name': '123' ) }
```

[GuildCreateChannelOptions](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L1779)

[Clone Function](https://github.com/discordjs/discord.js/blob/master/src/structures/GuildChannel.js#L469)

**Further details:**
- discord.js version: latest master ( 75e264da5744b7258d92865856f5f238947c1f47 )
- Node.js version: v11.9.0
- Operating system: Arch Linux
- Priority this issue should have: Medium

- [x] I have also tested the issue on latest master, commit hash:
75e264da5744b7258d92865856f5f238947c1f47

**Comment by bademo** [comment]
it appears that you're doing ```someChannel.clone({ 'name': '123' ) }``` instead of ```someChannel.clone({ 'name': '123' })```
