### ISSUE TITLE
Null avatarURL for server members that have the default avatar

### ISSUE THREAD

**Issue by rahulserver** [discordjs/discord.js#3055]
**Please describe the problem you are having in as much detail as possible:**

Provided code works fine if its a user that has just joined the server and has setup an avatar which is different from discord's default avatar. But for users that have the discord's default avatar, both avatar and avatarURL is null.

So how do I get this working for such users?
**Include a reproducible code sample here, if possible:**
```js

// Place your code here
Client.on("guildMemberAdd", newMember => {
    console.log("Welcomed member avatar: " + newMember.user.avatar);
    console.log("Welcomed member avatarURL: " + newMember.user.avatarURL);
});

```

**Further details:**
- discord.js version: 11.3.2
- Node.js version: 9.1.0
- Operating system: Ubuntu 16.4
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Darqam** [comment]
<user>.displayAvatarURL is probably what you are looking for. I recommend you go to the [Discord server](https://discord.gg/bRCvFy9) for future questions of the sort

**Comment by rahulserver** [comment]
Yeah this works. Thanks!!

**Comment by Wertzui123** [comment]
How to use it in this context?

embed.setAuthor(message.author.username, "https://cdn.discordapp.com/avatars/"+message.author.id+"/"+message.author.avatar+".png");
