### ISSUE TITLE
string.containsInvite

### ISSUE THREAD

**Issue by MrScopes** [discordjs/discord.js#3065]
**Is your feature request related to a problem? Please describe.**
have like `string.containsInvite` in the library, would be helpful like
```js
if (message.content.containsInvite) message.delete();
```
 for an easy anti advertisement.

**Describe the ideal solution**
Have it check the regex for if the content matches a discord invite, maybe like `(https?:\/\/)?(www\.)?(discord\.(gg|io|me)|discordapp\.com\/invite)\/.+[a-z]`

**Describe alternatives you've considered**
Well I've done this myself, but it would be easier if it was in the lib

**Comment by iCrawl** [comment]
No, not really.

**Comment by devcat** [comment]
This would add useless bloat to the library and this doesn't really fit into library purpose
