### ISSUE TITLE
channel.search not limiting by author

### ISSUE THREAD

**Issue by nickvorie** [discordjs/discord.js#3089]
**Please describe the problem you are having in as much detail as possible:**

Using a self-bot to run channel.search, the results are not correctly filtered by user. Any suggestions?

**Include a reproducible code sample here, if possible:**
```js

bot.on("message", message => {
    if (message.content.startsWith(".test")) {
        const user = message.author;
                
        message.channel.search({
            author: user
        }).then(result => {
            result.messages.forEach(chunk => {
                chunk.forEach(message => {
                    if (message.author.id != user.id) {
                        console.log("INVALID USER", message.author.id, user.id)
                    }
                });
            });
      }
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.15
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by tipakA** [comment]
Selfbots are against Discord TOS, you will not receive any actual help.
