### ISSUE TITLE
Docs: GuildMember

### ISSUE THREAD

**Issue by Jisagi** [discordjs/discord.js#3090]
**Please describe the problem you are having in as much detail as possible:**
[GuildMember](https://discord.js.org/#/docs/main/master/class/GuildMember) is missing the User property in the online docs. The docs-bot in discord seems to have it though.

**Include a reproducible code sample here, if possible:**
```js

// Place your code here

```

**Further details:**
- discord.js version: latest master branch docs
- Node.js version: ---
- Operating system: ---
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Thank you for reporting!
