### ISSUE TITLE
client.user.lastMessage().id return wrong id

### ISSUE THREAD

**Issue by RenardFute** [discordjs/discord.js#3092]
`` let msg = await message.channel.send(embed);
        //TODO pas le bon id

        let lastmsg = await client.user.lastMessage;
        if (lastmsg == undefined) {
            console.log('lastmessage == null')
            const collector = new Discord.MessageCollector(message.channel, m => m.author.id === client.user.id, { time: 10000 });
            collector.on('collect', message => {
                lastmsg = message;
                console.log(message.content);
                collector.stop("Got my message");
            })
        }``
this return this id: 545910208879132700
But when on discord i make copy the id its return 545910208879132692
But it's the same message :/
So later when i make message.channel.fetchMessage(id) it s return me `Unknow Message`

**Comment by tipakA** [comment]
Personally can't see something that would return that here.
It looks like you use id as an integer somewhere, looking at endings.

Please ask in discord server for more info.

**Comment by amishshah** [comment]
Please [join our Discord server](https://discord.gg/bRCvFy9) to discuss this issue there.
