### ISSUE TITLE
client.ping return me an undefined

### ISSUE THREAD

**Issue by AnatoleLucet** [discordjs/discord.js#3104]
So i'm just trying to get my client ping but when i do a `client.ping` he return me an `undefined`.

I do not know what else to say, this is not a problem with my code, i've tested on a freshly new bot and it's still happening, i'm using the latest master branch.

Does discordjs has recently changed his method to get the ping ?

**Comment by bdistin** [comment]
Yes, now it's client.ws.ping

**Comment by AnatoleLucet** [comment]
@bdistin Thanks you !
