### ISSUE TITLE
Channels sorted wrong on `setPosition` but right on `edit`

### ISSUE THREAD

**Issue by exapsy** [discordjs/discord.js#3110]
## Problem
It seems like `guildChannel.setPosition(position)` and `guildChannel.edit({position})` work differently.

With the difference that `edit` works as expected while `setPosition` not. And it's really strange since the two codes at [edit()](https://github.com/discordjs/discord.js/blob/master/src/structures/GuildChannel.js#L306) and [setPosition()](https://github.com/discordjs/discord.js/blob/master/src/structures/GuildChannel.js#L403) seem to be alike.

**Using `edit({position})`:**
https://media.giphy.com/media/4TbihFm55thv4QkbXZ/giphy.gif
```js
if(typeof(position) === 'number') {
  category.edit({position});
}
```

**Using `setPosition(position)`:** *(everything gone wrong)*
https://media.giphy.com/media/ywjLKdqVnTZouLwYIt/giphy.gif
```js
if(typeof(position) === 'number') {
  category.setPosition(position);
}
```

**Further details:**
- discord.js version: Master efbbfbcec6d9b090eb7053bbb39acea50c46c517
- Node.js version: 10.10.0
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: Small

- [x] I have also tested the issue on latest master, commit hash: efbbfbcec6d9b090eb7053bbb39acea50c46c517

**Comment by Jonyk56** [comment]
hello @Eksapsy the position in setPosition is via integer, you would have to make the position into a parse integer, edit will do that for you, i would suggest using edit if you cannot make the position to a parse integer

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
