### ISSUE TITLE
How to do a discord bot wich store user's audio voice in a buffer ?

### ISSUE THREAD

**Issue by AnatoleLucet** [discordjs/discord.js#3111]
So i want to record the user's voice with a discord bot and store it in a buffer with (for exemple) [node-lame](https://www.npmjs.com/package/node-lame) so i can use this buffer for other things later.
Also i've didn't find any recent guide / blog about recording voice with discord.js.

For the moment i've tried to save the audio as an mp3 file (by the way this isn't working because the audio file sizzles) but this is not what i really want to do.

```Javascript
function generateOutputFile(channel, member) {
  const fileName = `./recordings/${channel.id}-${member.id}-${Date.now()}.pcm`;
  return fs.createWriteStream(fileName);
}

// ...

const receiver = connection.receiver;

connection.on('speaking', (user, speaking) => {
  if (speaking) {
    msg.channel.sendMessage(`I'm listening to ${user}`);
    const audioStream = receiver.createStream(user);
    const outputStream = generateOutputFile(voiceChannel, user);
    audioStream.pipe(outputStream);
    outputStream.on('data', console.log);
    audioStream.on('end', () => {
      msg.channel.sendMessage(`I'm no longer listening to ${user}`);
    });
  }
});

```

[Credit for this code](https://gist.github.com/eslachance/fb70fc036183b7974d3b9191601846ba)

**Comment by amishshah** [comment]
This issue tracker is for bugs only, if you have any questions please ask them on our [Discord Server](https://discord.gg/bRCvFy9).
