### ISSUE TITLE
Discordjs music bot issue

### ISSUE THREAD

**Issue by ThomasJorde** [discordjs/discord.js#3115]
**Code:**

_voicechannel.join()
    .then(connection => {
        console.log("joined channel");
        const dispatcher = connection.playStream(ytdl('https://www.youtube.com/watch?v=668nUCeBHyY',{filter:"audioonly"}));
        dispatcher.on("end", end => {
            console.log("done");
        });
    })
.catch(console.error);_

Bot joins channel but does not play anything.

The console debug messages does not appear in the terminal.

Error that appears after 20 seconds: https://pastebin.com/Umv8Ufqh

I can see that there is some kind of timeout. What could be the reason?

**Other detalis:**
Operating system: CentOS
node version: v11.10.0

**Comment by devcat** [comment]
This issue tracker is for bugs only, if you have any questions please ask them on [Discord Server](https://discord.gg/bRCvFy9).
