### ISSUE TITLE
rateLimitInfo.requestLimit is undefined

### ISSUE THREAD

**Issue by niekcandaele** [discordjs/discord.js#3131]
**Please describe the problem you are having in as much detail as possible:**

When trying to log info about the rateLimit event, rateLimitInfo.requestLimit is undefined.

**Include a reproducible code sample here, if possible:**
```js

client.on('rateLimit', info => {
    console.log(`Discord API rateLimit reached! ${info.requestLimit} max requests allowed`);
});

```

Which results in this log line: `Discord API rateLimit reached! undefined max requests allowed`

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 11.10.0
- Operating system: Ubuntu 18.10
- Priority this issue should have – please be realistic and elaborate if possible: low

Not sure how I should test rate limit locally, happy to do so if someone can tell me the best method

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
The data is emitted as `data.limit`:
https://github.com/discordjs/discord.js/blob/b5df8603e8768b9b50ece24f94e455c3410ef9a2/src/client/rest/RequestHandlers/Sequential.js#L97-L102
But documented as `data.requestLimit`, probably mixed up the naming from the this context:
https://github.com/discordjs/discord.js/blob/b5df8603e8768b9b50ece24f94e455c3410ef9a2/src/client/rest/RequestHandlers/Sequential.js#L88-L96

This is correctly documented on the master docs, I will PR the doc fix for 11.4-dev shortly

**Comment by niekcandaele** [comment]
Ahhh thank you very much! :)

**Comment by SpaceEEC** [comment]
Fixed with the referenced commit ^
