### ISSUE TITLE
(typings) Missing "manageable" in type GuildChannel

### ISSUE THREAD

**Issue by leRisen** [discordjs/discord.js#3135]
Using the type "GuildChannel", which is declared in the declaration file, there is no description of the "manageable" property, although this is in the [documentation](https://discord.js.org/#/docs/main/stable/class/GuildChannel?scrollTo=manageable).

**Further details:**
- discord.js version: 11.4.2
- Priority: Small

**Comment by vzwGrey** [comment]
Well of course there's going to be descrepencies between stable's typings and master's docs. They're two very different branches; stable the current release, while master is under heavy development. Things are going to be different between them.

**Comment by leRisen** [comment]
@vzwGrey I meant that the types described in the documentation for the stable version are missing in typings 11.4.2. So when should we expect an update or how can I solve the problem with the fact that the described property is present in the documentation, but not described in "typings"?

**Comment by leRisen** [comment]
By the way, sorry for my incomprehensible description, but there I wanted to emphasize that the “manageable” property should be present, but it is not described.

**Comment by kyranet** [comment]
Between 11.4.2 and master (12.0.0), we did not only change the documentation or the typings, but also almost the entirety of the source code. If something is documented in master but not in stable, it might either not exist in stable, or it's private.

**Comment by SpaceEEC** [comment]
This should be fixed with 12e041bc2b88e01d925a42296ee8a4c186772b76, thank you for reporting!
