### ISSUE TITLE
Custom ffmpeg args

### ISSUE THREAD

**Issue by johann-lr** [discordjs/discord.js#3139]
Is it simply possible to edit or redefine the ffmpeg arguments for a stream dispatcher?
That feature would be really useful to add audio effects to your stream f.ex. when building music streaming bots.

Currently the args are defined as a constant and passed into the play functions that create a dispatcher so it would be nice if they were editable ;)

**Comment by Deivu** [comment]
I also thought this was the case but the answer for what you want is in here #2894

**Comment by johann-lr** [comment]
Thanks, I‘ll try it
