### ISSUE TITLE
Ubuntu Linux Memory Leak

### ISSUE THREAD

**Issue by CDVoidwalker** [discordjs/discord.js#3143]
System: Ubuntu 18.04.1 LTS
CPU: i3-6006U 
RAM: 4Gb
GPU: something integrated into laptop

Discord keeps on increasing RAM usage untill it crashes if I keep GPU acceleration on (which is on by default)

**Comment by iCrawl** [comment]
Opening this issue with that little information provided feels like a bad joke.

First, we have an issue template which you shouldn't, under any circumstances, delete.
Second, this needs waaaaaaaay more information:
- How long has the bot been running for
- How fast does it increase
- Are you sure its not just cache increasing it (members, users, etc.)

Just to name a few things.

**Comment by CDVoidwalker** [comment]
Actually sorry for that, I'm kinda tired rn and thought it's place where I could upload discord client issues and I guess here's api only, gotta talk with support
