### ISSUE TITLE
ReferenceError: bbot is not defined

### ISSUE THREAD

**Issue by noqit** [discordjs/discord.js#3149]
I am receiving the following error:
ReferenceError: bbot is not defined
at Object.<anonymous> (/app/index.js:39:1)

This is my index.js
`const botconfig = require("./botconfig.json");
const tokenfile = require("./token.json");
const Discord = require("discord.js");
const fs = require("fs");
const bot = new Discord.Client({disableEveryone: true});
bot.commands = new Discord.Collection();

fs.readdir("./commands/", (err, files) => {

  if(err) console.log(err);

  let jsfile = files.filter(f => f.split(".").pop() === "js")
  if(jsfile.length <= 0){
    console.log("Couldn't find commands.");
    return;
  }

  jsfile.forEach((f, i) =>{
    let props = require(`./commands/${f}`);
    console.log(`${f} loaded!`);
    bot.commands.set(props.help.name, props);
  });

});

bot.on("ready", async () => {
  console.log(`${bot.user.username} is online on ${bot.guilds.size} servers!`);

  bot.user.setActivity("REEEE", {type: "WATCHING"});

//  bot.user.setActivity("On drugs");
});

bot.on('message', msg => {
  if (msg.content === 'Hi bot') {
    msg.reply('Hello <3');
  }
});
bbot.login(process.env.SECRET);`

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
