### ISSUE TITLE
playStream ignores 0 as a volume although 0 volume can be set

### ISSUE THREAD

**Issue by 2colours** [discordjs/discord.js#3150]
I don't think it needs much elaboration. 0 is a legitimate value setVolume can accept but playStream still ignores it. This inconsistency is only good for extra workarounds, ie not using playStream parameters at all and set the right values anyway.

Not a crucial change but I don't think it would take much effort to change and I don't see any reasons to keep.

**Further details:**
- discord.js version:11.4.2
- Node.js version:8.11.1
- Operating system:Ubuntu 16.04 LTS

**Comment by amishshah** [comment]
Fixed in the above commit

**Comment by 2colours** [comment]
Thank you. :)
