### ISSUE TITLE
client.emojis return empty collection

### ISSUE THREAD

**Issue by WebDeg-Brian** [discordjs/discord.js#3156]
**Please describe the problem you are having in as much detail as possible:**
I tried `console.log(client.emojis)` which returned an empty collection. As far as I understand, the bot should have access to all the emojis in all the servers it's in, but it's not the case here

**Include a reproducible code sample here, if possible:**
```js
import { Client } from 'discord.js';

const client = new Client();

client.on('ready', () => {
  console.log('Ready!');
}); 

client.on('message', () => {
  console.log(client.emojis) // Return empty collection
});

```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.11.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Fyk0** [comment]
Works for me! https://hastebin.com/uxasurixih.js 🤔

**Comment by SpaceEEC** [comment]
I can not reproduce this on 11.4.2 and 11.4-dev (be2f78851f55b6e3e9a5dfcfa7af78e039ba3954)

My code, although trivial:
```js
const Discord = require('discord.js');

const client = new Discord.Client();

client
    .on('ready', () => console.log('ready'))
    .on('message', () => console.log(client.emojis))
    .login();
```

---

* Does the collection stay empty even after some time passed?
* Is `Guild#emojis` populated for you?

Maybe also double check whether you are starting the correct bot / token.

**Comment by WebDeg-Brian** [comment]
@SpaceEEC I'm think I'm a bit confused about `client.emojis` in the first place. Does it just return the custom emoijis or both custom and default? I joined a server and added some emojis and it returns only the ones I've added

**Comment by bdistin** [comment]
only custom server emojis.

**Comment by WebDeg-Brian** [comment]
@bdistin what if I want a default emoji like "joy". Do this: `\:joy:`?

**Comment by bdistin** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by Fyk0** [comment]
If you look at the Hastenin I attached, the title of the collection is GuildEmojiStore.

**Comment by WebDeg-Brian** [comment]
@Fyk0 Oh yeah cheers. Is it in the docs as well? Been digging for the whole weekend but never seen that class lol. My bad. Closing this now
