### ISSUE TITLE
Support for presence object partials

### ISSUE THREAD

**Issue by vadremix** [discordjs/discord.js#3158]
**Is your feature request related to a problem? Please describe.**
In my usage, I don't need presence.activity or presence.clientStatus. I was originally sweeping this data, until I realized it was interfering with presence updates.

**Describe the ideal solution**
Support for partial presence objects. In my use case, I only need presence.status.

**Describe alternatives you've considered**
Using less shards per VPS and scaling more horizontally, although this leads to higher monthly costs.

**Comment by appellation** [comment]
Partials are designed to be used when the library receives partial data from the Discord API: message update, reaction add, etc. I'm unaware of any instance where the library would receive a partial presence.

**Comment by amishshah** [comment]
This will not be an in-built feature of Discord.js in the foreseeable future, but you can always implement this yourself by [extending the Presence structure](https://discord.js.org/#/docs/main/master/class/Structures?scrollTo=s-extend) to only store the status:

```js
const { Structures } = require('discord.js');

Structures.extend('Presence', Presence => {
  class PartialPresence extends Presence {
    patch(data) {
      this.status = data.status || this.status || 'offline';
    }
  }

  return PartialPresence;
});
```

This should prevent activity from also being cached.
