### ISSUE TITLE
setThumbnail of Embed on messageDelete not working

### ISSUE THREAD

**Issue by danielsartor** [discordjs/discord.js#3162]
I have an event of messageDelete that send some logs to a specific channel. I'm trying to add the attached images to the log, but it won't work
``` 
var dAttachment = (msg.attachments).array();
if (dAttachment.length > 0)
     embed.setThumbnail(dAttachment[0].url);
```

If I add the image, edit the content, then delete it, the thumnail works, but if I just add the image and delete it, the thumbnail won't show.

**Comment by dxvns** [comment]
It's because maybe because when it copies the url of the image and set it as the thumbnail, it is deleted before it can copy it. Therefore, it won't show. It will show sometimes.

**Comment by danielsartor** [comment]
It copies the URL properly, because I could add it as a text url on the embed and log it on Console, also I've uploaded the image on the log channel. Also if I edit the the text with the attachment and delete it it shows the thumbnail. It just don't set as thumbnail or image on the embed without editing.

I've tried setImage too on the Embed instead of thumbnail and I have the same issue.

**Comment by dxvns** [comment]
If you are still having the issue, please join the support server as the support team members will be at your service.

**Comment by Fyk0** [comment]
When accessing the [MessageAttachment Collection[(https://discord.js.org/#/docs/main/stable/class/MessageAttachment), you are provided many links. When you delete a message, the `attachment` (the one starting with `cdn`) because inaccessible and you must use [MessageAttachment#proxyURL](https://discord.js.org/#/docs/main/stable/class/MessageAttachment?scrollTo=proxyURL).

**Comment by danielsartor** [comment]
I will test it and updated/close the issue when I have it done. Thank you! (:
