### ISSUE TITLE
Discord server invite expired?

### ISSUE THREAD

**Issue by justablob** [discordjs/discord.js#3163]
The Discord.js server invite link seems to have expired, I atleast don't seem to be able to join, and i don't remember getting banned. My Discord username is Blob#6466, if anyone wants to check.

**Comment by Darqam** [comment]
It's not expired and I see no one by that tag banned. Maybe you are just at your 100 guild cap or smth. Either way not an issue that belongs on this github repo.

**Comment by justablob** [comment]
I'm sorry for posting it here but i couldn't find any other place to ask. And i haven't hit my guild cap either.
