### ISSUE TITLE
News Channel Causing All Bots To Crash

### ISSUE THREAD

**Issue by Skillz4Killz** [discordjs/discord.js#3164]
**Please describe the problem you are having in as much detail as possible:**
Every single bot that I had on my server just crashed when I used the News channel. 

Luckily, the bot's were mine and my friends and it was fairly easy to bring it back up. 

The concern however, is that ANYONE can simply invite my bot(or any bot) to a server with a news channel(which only costs $25 to get) and crash every single bot on that server. This is a massive issue that really needs an URGENT fix in my opinion.

https://github.com/discordapp/discord-api-docs/issues/881

**Include a reproducible code sample here, if possible:**
```js

// N/A

```

**Further details:**
- discord.js version: Latest
- Node.js version: 10.5
- Operating system: Ubuntu and OSX
- Priority this issue should have – please be realistic and elaborate if possible: TOP! High! Top Priority!

- [ ] I have also tested the issue on latest master, commit hash: #8230255c68b94d68a4e8ffc559a98d08d1a08a7c

**Comment by devsnek** [comment]
got an error message? unknown types become generic `GuildChannel`, which wouldn't crash anything.

**Comment by Skillz4Killz** [comment]
@devsnek This is from my friends bots whose bots were also crashing whenever I did something in the news channel. I can't access my VPS for a few days to send my logs.

![image](https://user-images.githubusercontent.com/23035000/55189659-c4200600-5174-11e9-92ec-2157461bf530.png)
