### ISSUE TITLE
[Docs] Describe events

### ISSUE THREAD

**Issue by KaKi87** [discordjs/discord.js#3174]
Hello,

**Is your feature request related to a problem? Please describe.**
For example, I would like to know which properties of the `Message` object, when changed, fires the `Client.messageUpdate` event ?
Or, more precisely : is the `Client.messageUpdate` event fired when `Message.pinned` changes ?
Answers like `test for yourself` on the Discord server are unacceaptable.

**Describe the ideal solution**
Precise in the event descrption which properties could have changed.

**Describe alternatives you've considered**
Precise in the property description which events are fired when it changes ?

**Additional context**
Search `test for yourself` in Discord.JS' Discord server.

**Comment by vladfrangu** [comment]
We cannot document literally every value that can change on, say message update, as they can change whenever (as in properties be added or removed), and we'd need to update the docs every time.

While I personally see how saying `test for yourself` can be bad or not helpful, it's still a valid answer in my opinion. Edit the message! See what happens. console.log(old, new).

> is the Client.messageUpdate event fired when Message.pinned changes ?

Not that I'm aware of. channelPinsUpdate is, iirc.

**Comment by KaKi87** [comment]
> we'd need to update the docs every time

Why would that change more often than properties ?

**Comment by appellation** [comment]
Discord does not provide us users a very complete description of when they fire their various update events. For example, [the description for the message update event](https://discordapp.com/developers/docs/topics/gateway#message-update) simply says that it's fired when a message is updated.

This behavior is relatively undefined and documenting it on our end would be providing a guarantee to our users that we have no control over. Discord could change this behavior at any time and stay consistent with the very little documentation they provide themselves. While I think this is unlikely, it's still possible and, ultimately, documenting these scenarios would provide relatively little benefit that users can determine themselves simply by doing some basic testing.

**Comment by KaKi87** [comment]
It's a shame.
