### ISSUE TITLE
Discord.RichEmbed should have a .clearFields()

### ISSUE THREAD

**Issue by MichaelXF** [discordjs/discord.js#3176]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I want to re-use Rich Embeds but have to construct a whole new object to clear the fields.

**Describe the ideal solution**
RichEmbed should have a .clearFields() so you can easily re-use RichEmbed objects.

**Describe alternatives you've considered**
I could make a seperate function to remake my object but I have a lot of requirements and thus, its easier to not.

**Additional context**
.clearFields would be easy to add. I want do a message.channel.send(richEmbed)
then change some attributes but I wan't to clear the fields to send it again.

**Comment by Monbrey** [comment]
The `<RichEmbed>.fields` property is just an array, you can clear the fields using `<RichEmbed>.fields = []`

**Comment by devsnek** [comment]
you don't need to worry about creating lots of embed objects

**Comment by jsmiith** [comment]
I guess it would still be a cool feature to have - it doesn't take much work. I was thinking more of a reset method. The one I referenced resets everything by default but you can pass an object in it to disable and enable resetting certain things - such as fields.

**Comment by Skillz4Killz** [comment]
Is this something desired in the library i can work on this if we need and send a PR for it. Something to note:
`embed.spliceField(0, 25)` might already do what this needs.

**Comment by Deivu** [comment]
embed.fields is already an array, you can just do embed.fields.slice()

**Comment by Monbrey** [comment]
`spliceFields()` exists on master already, which is what Skillz was referencing.
Otherwise yes, you're right and you can use Array methods on the array directly or reset it as I showed... almost three months ago.

This issue should probably just be closed, unless someone *really* wants this method to exist.

**Comment by Androz2091** [comment]
I think that for most people, they don't know that fields are an array and, for them, the clearFields() function should exist. If the RichEmbed() class is made to easily build an embed using methods why not add this one? At that point ask them to push into the array embeds.fields and remove the addField() method? In my opinion, the more the RichEmbed() class will include a method to facilitate the use of the embeds, the better. After that, it remains my opinion as not api creator ^^

**Comment by iCrawl** [comment]
>I think that for most people, they don't know that fields are an array

They should read the docs.

Builders don't really need methods to "un-build" themselves.
