### ISSUE TITLE
Could MessageEmbed become extendable using Structures?

### ISSUE THREAD

**Issue by Purpzie** [discordjs/discord.js#3177]
**Is your feature request related to a problem? Please describe.**
Kind of? I've often found myself starting to use `util.splitMessage` along with `MessageEmbed.addField()` just in case the content in case the field content is too long (for example, from a roles list command or an emoji list command).

**Describe the ideal solution**
Instead of using a separate function to do this though, it would be super useful to be able to just extend `MessageEmbed`. Plus it would help a lot of other people out if they have their own things they'd want to add to it.

**Describe alternatives you've considered**
Using a separate function - but it's much less clean than just extending `MessageEmbed`

**Additional context**
None needed 👍

**Comment by bdistin** [comment]
You don't need Structures to extend MessageEmbed. You can already do this on your own by simply extending MessageEmbed.

**Comment by Purpzie** [comment]
For sending an embed sure, but not for getting an embed from an existing message (unless I'm mistaken)

**Comment by izexi** [comment]
You can extend the Message structure and override Message#embeds to use your own extended MessageEmbed class.
https://github.com/discordjs/discord.js/blob/bb92289e45b4d9d576a4277d0bfa082814d2bc20/src/structures/Message.js#L93
Which can be done by replacing the `Embed` with your extended MessageEmbed class in the line above.

**Comment by Purpzie** [comment]
Thank you! 👍

**Comment by Purpzie** [comment]
Wait no, I just realized that would require me to extend the entire `_patch` method. It would be much more practical to be able to simply extend MessageEmbed using Structures.

**Comment by bdistin** [comment]
>__entire__ _patch method...

Uh, I am not sure you understand how easy it is to extend methods based on your use of that qualifying word. It's really only this which is not arduous at all:
```js
_patch(data) {
  super._patch(data);
  this.embeds = (data.embeds || []).map(e => new CustomEmbed(e)); 
}
```

**Comment by Purpzie** [comment]
Oh, my bad. Thanks for the explanation.
