### ISSUE TITLE
WebhookClient.send() not sending content

### ISSUE THREAD

**Issue by KartulUdus** [discordjs/discord.js#3179]
**Please describe the problem you are having in as much detail as possible:**
Seems that WebhookClient when sending content and embeds in the same message, content is not sent

https://discord.js.org/#/docs/main/stable/class/WebhookClient?scrollTo=send 

However, when only a string is sent, it is sent as content

**Include a reproducible code sample here, if possible:**
```js

                        const hook = new WebhookClient(webhookId, webhookToken)
                        hook.send("some content", {
                            embeds: [{ "description": "Some embed description"}],
                        })
```

Does not send "some content", but `hook.send('some Content')` does

**Further details:**
- discord.js version: 11.3.0
- Node.js version: v10.15.0
- Operating system: Ubuntu 18 / OSX / Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash: 089f65fd2acb284fa741f4faf302ec34660026b6

**Comment by SpaceEEC** [comment]
I am unable to reproduce this bug on:
- 11.4.2 (latest stable release)
- 11.4-dev [831f988fe2258bbdd5b3459bfbe830e4a5510a6c]
- master [bb92289e45b4d9d576a4277d0bfa082814d2bc20]

Since you are stating that you are using 11.3.0, I suggest to update to 11.4.2.
