### ISSUE TITLE
Sharding manager spawns 2 shards at a time

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#3181]
**Please describe the problem you are having in as much detail as possible:**
Sharding Manager spawns 2 shards at the same time when waitForReady disabled.

**Include a reproducible code sample here, if possible:**
```js
const { ShardingManager } = require('discord.js')
const config = require("./botconfig.json")

const manager = new ShardingManager('./corekashima.js', { respawn: true, execArgv: ['--always_compact', '--optimize_for_size', '--max_old_space_size=460'], token: config.token })
/*
// spawn a folder watcher for rebooting / killing shards
new (require('./src/functions/devInterface.js'))(manager, './dev')
*/
manager.spawn(config.shards, 12500, false).catch(console.error)
```
reimu at d.js support server suggested the following 

Relevant Code
https://github.com/discordjs/discord.js/blob/master/src/sharding/ShardingManager.js#L197
```
its like i want 3 shards so this.shards.length = 3
create shard, this.shards.size = 1, is this.shards.size !== this.shardList.length - 1 (1 !== 2)? no, so we'll wait
wait
create another shard this.shards.size = 2, this.shards.size !== this.shardList.length - 1 (2 !== 2)? no, so we won't wait
no wait
create another shard this.shards.size = 3, this.shards.size !== this.shardList.length - 1 (3 !== 2)? yes, so we'll wait
but it doesnt matter since we already made the three shards
```
**Further details:**
- discord.js version: Master @ bb92289e45b4d9d576a4277d0bfa082814d2bc20
- Node.js version: 10.12.0
- Operating system: Ubuntu 18.10
- Priority this issue should have – please be realistic and elaborate if possible: Medium due to the fact that it spawns two shards at the same time and hits the ratelimit of spawning shards. Could be CPU intensive as well

- [x] I have also tested the issue on latest master, commit hash: bb92289e45b4d9d576a4277d0bfa082814d2bc20

**Comment by SpaceEEC** [comment]
This bug should be fixed with the referenced commit, thank you for reporting!
