### ISSUE TITLE
Last commit broke fetching audit logs.

### ISSUE THREAD

**Issue by xonrsoftware** [discordjs/discord.js#3183]
**Please describe the problem you are having in as much detail as possible:**
https://github.com/discordjs/discord.js/commit/5e9bd786d13f2da11544e45e4ac9622269259789 Broke fetching audit logs without userid.

 message: 'Invalid Form Body\nuser_id: Value null is not snowflake.',

**Include a reproducible code sample here, if possible:**
```js

await client.guilds.get('').fetchAuditLogs({
            type: 'CHANNEL_UPDATE',
            limit: 100
        })

```

**Further details:**
- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:
bfab203934395ebd8884b3fb6360d2d44a0778dd

**Comment by SpaceEEC** [comment]
Thank you for the bug report, this issue should be fixed with the referenced commit!
