### ISSUE TITLE
shardResumed & resume event doesn't seem to emit.

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#3191]
**Please describe the problem you are having in as much detail as possible:**
I tested both, "shardResumed" and "resume" event in Master Commit `00eb7e3`, left both the bot online for 1 1/2 day and they do fire "shardReconnecting" event but not the shardResumed and resume event.

**Include a reproducible code sample here, if possible:**
```js
client.on('resume', () => console.log('A shard resumed'))
client.on('shardResumed', () => console.log('A shard resumed'))
```

**Further details:**
- discord.js version: Master Commit `00eb7e3`
- Node.js version: 10.12.0
- Operating system: Ubuntu 18.10
- Priority this issue should have – please be realistic and elaborate if possible: 

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by vladfrangu** [comment]
Hey. Thanks for reporting this issue!

The `resume` event is going to be replaced by the `shardResumed` event, with parameters (shardID). The fact that neither get emitted however, sounds like an odd bug, that I will look into!

Also, one last thing. `shardResumed` is only emitted if a shard was able to RESUME not IDENTIFY as a new session. This should generally be doable, but at times, it isn't. You can also listen to the `shardReady` event which is emitted when the shard identifies successfully.

**Comment by Deivu** [comment]
@vladfrangu I think this was not firing due to it never resumes the session properly, as I monitored from my shards, everytime reconnecting fires, it will reset the `client.uptime`, and this behavior is kinda not desired because it causes a lot of issues on voice part of lib
