### ISSUE TITLE
VoiceBroadcast#end is not working properly

### ISSUE THREAD

**Issue by thomasxd24** [discordjs/discord.js#3193]
**Please describe the problem you are having in as much detail as possible:**

when i create a VoiceBroadcast with createBroadcast and then end it with client.voice.broadcasts[0].end(), this error comes out:
`TypeError: Cannot read property 'broadcasts' of undefined`
also it doesnt remove the VoiceBroadcast from client.voice.broadcasts

**Include a reproducible code sample here, if possible:**
```js

var broadcast = client.voice.createBroadcast()
broadcast.play("https://radio.truckers.fm/");
console.log(client.voice.broadcasts); // [ [VoiceBroadcast] ]
client.voice.broadcasts[0].end(); //error: TypeError: Cannot read property 'broadcasts' of undefined
console.log(client.voice.broadcasts); // [ [VoiceBroadcast] ] still there
```

**Further details:**
- discord.js version: master
- Node.js version: 11.13.0
- Operating system: Linux Debian
- Priority this issue should have – please be realistic and elaborate if possible:
Moderate

- [x] I have also tested the issue on latest master, commit hash: 89e27e5

**Comment by thomasxd24** [comment]
Edit: it seems that in `VoiceBroadcast.js`, in the end method, this.client.voice.broadcasts was undefined, it was because this.client is clientVoiceManager and it doesnt need `voice` to get to `broadcasts`, i am filing a PR for this

**Comment by thomasxd24** [comment]
#3194

**Comment by amishshah** [comment]
PR has been merged so closing this issue, if you can still reproduce the issue then please reopen the PR.
