### ISSUE TITLE
close FFMPEG to save performance in VoiceBroadcast

### ISSUE THREAD

**Issue by thomasxd24** [discordjs/discord.js#3195]
**Is your feature request related to a problem? Please describe.**
Everytime i create a VoiceBroadcast, it spawns a ffmpeg process, but when i end the VoiceBroadcast, the ffmpeg process is still there eating cpu.
**Describe the ideal solution**.
when we end the VoiceBroadcast, the ffmpeg would end
**Describe alternatives you've considered**

**Additional context**

**Comment by FerLuisxd** [comment]
This would work only if the bot is only one server, but in the cases of multi server bots, it would kill any other VoiceBroadcast that is currently streaming voice using ffmpeg

**Comment by thomasxd24** [comment]
yea but 1 voiceBroadcast has 1 ffmpeg, so if there are multiple voiceBroadcast there will be multiple ffmpeg process

**Comment by Deivu** [comment]
You can just "pause" the voicebroadcast when no one is tuned in that shard to save performance, then resume it once someone subscribes to it. I don't think this needs to be a feature.

```js
const stream = some_internet_radio;
const subscriptions = new Set();
const broadcast = client.voice.createBroadcast();
broadcast.play(stream);
broadcast.on('subscribe', (disp) => {
  if (disp.paused) disp.resume();
})
broadcast.on('unsubscribe', (disp) => {
  if (subscriptions.has(disp.channel.guild.id)) subscriptions.delete(disp.channel.guild.id);
  if (!subscriptions.size && disp.paused) disp.pause();
})

// somewhere in your bot
<voice_channel>.join().then((con) => {
  con.play(broadcast);
  subscriptions.add(con.channel.guild.id);
})
```
I hope you get the gist
