### ISSUE TITLE
User.displayAvatarURL()

### ISSUE THREAD

**Issue by PancakeLord** [discordjs/discord.js#3197]
**Is your feature request related to a problem? Please describe.**
I guess you could call it a problem, since master `User.displayAvatarURL` has changed to `User.displayAvatarURL()`, and you can change the format of the avatar by doing `User.displayAvatarURL({format: "png" | "jpg" | "gif" | "webp"})` however, if you change it it changes gifs to that as well. If you dont change it then it chooses webp for non animated and gif for animated however webp doesn't support clear backgrounds and png does and because of that to have it as png for non animated and gif for animated you have to do `User.displayAvatarURL().replace('webp','png')` which can be quite annoying if you have to do it a lot of times.

**Describe the ideal solution**
Instead of just format as an option in ImageURLOptions add animatedformat as well or something along those lines.

**Describe alternatives you've considered**
You could do
```javascript
Structures.extend('User', User1 => {
    class User extends User1 {
        constructor(client, data) {
            super(client, data);
            this.url = this.displayAvatarURL().replace('webp','png')
        }
    }

    return User;
});
```
but I think it should be implemented into discord.js itself
**Additional context**
N/A

**Comment by iCrawl** [comment]
>webp doesn't support clear backgrounds

This statement is just plain wrong though?
https://developers.google.com/speed/webp/gallery2

Additionally you can just detect by checking with something silly as `startsWith('a_')` to see if it is animated.

**Comment by PancakeLord** [comment]
Hmm, that's odd. I could swear it would use a white background for webp avatars when I tried it a few weeks back. I guess not, sorry. You can ignore this.
