### ISSUE TITLE
Aktif Olan Kullanıcıları Gösterme /  Showing Active Users

### ISSUE THREAD

**Issue by EmirhanSarac** [discordjs/discord.js#3202]
tr:
Ben Sunucudaki Tüm Kullanıcı Sayısını Şu Kodla Gösteriyorum `${client.guilds.reduce((a, b) => a + b.memberCount, 0).toLocaleString()}`
Ama Ben Çevrimdışı Olanları Göstermek İstemiyorum Sadece Sunucuda Online Olanları Rahatsız Etmeyin,Boşta Olanlarıda Dahil Edecek Bu Kod Bana Çok Lazım Yardım Ederseniz Sevinirim.

En:

I am showing the total number of users on the server with the following code `$ {client.guilds.reduce ((a, b) => a + b.memberCount, 0) .toLocaleString ()}`
But I don't want to show off the offline ones.

**Comment by Monbrey** [comment]
The GitHub is not for asking for help. Please go to the discord server to ask for assistance with your code.

**Comment by UtkuAyazUzun** [comment]
Tamam ÇomAre Sahibi Emirhancım
