### ISSUE TITLE
Ubuntu deployments seems not playing audio correctly.

### ISSUE THREAD

**Issue by Seia-Soto** [discordjs/discord.js#3205]
I am one of user using Discord.JS well, but there is few problem in use. I made simple code that plays YouTube video url(dispatches stream as ytdl-core), and yes, it worked well. However, after I uploaded to my Ubuntu deployment, I checked the log that all codes are ok and passed, and  method ``playStream``, it continued without error, but there was no output to voice channel. I though this was my code's fault, but I can see it worked well on only Windows environment(I don't have Mac OS). I tried all methods that I can do, (``playStream``, ``playFile``, ETC), but there is no sounds on voice channel. Also I could find a few people who have same issue in Discord.JS server.

```js
const fs = require('fs')
const path = require('path')
const ytdl = require('ytdl-core')

const InPath = path.join(__dirname, '../assets/videos/')

const VideoStreamIndicator = url => {
  return new Promise((resolve, reject) => {
    if (!ytdl.validateURL(url)) {
      reject('YouTubeDownloader: URL is not valid.')
    }

    console.log('Get Info:', url);

    ytdl.getInfo(url).then(video => {
      const path = `${InPath}${video.video_id}`

      console.log('Start:', path);

      resolve(ytdl(url, { filter: 'audioonly' }))
    }).catch(error => {
      console.error('Error:', error)

      reject(error)
    })
  })
}

...

// NOTE: Message processing part.

message.member.voiceChannel.join().then(c => {
    VideoStreamIndicator(YOUTUBE_URL).then(f=>{
      console.log('End:StreamInputReceiver');
      c.playStream(f)
    })
  })
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v10.15
- Operating system: Ubuntu 18.04 LTS
- Priority this issue should have – Need more info before continue

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Seia-Soto** [comment]
Additional: Latest master branch didn't catch voice channel well.

**Comment by iCrawl** [comment]
I don't know how to reproduce this honestly, are you using any specific host?

**Comment by Seia-Soto** [comment]
I am using Vultr, JP. Playing ytdl's readable stream(from ytdl function) is not working.

**Comment by Zargith** [comment]
I got the same type of problem since some days and there is no error or other reason why it wont work :/
I'm on Ubuntu on my home's computer and on Fedora on my woking computer.

I've everythink updated and/or upgraded. I've tried some debug but I didn't see any problem...
I wanted to try on my Windows but, ffmpeg errors are incredibly horrible to correct, so I gave up ._.

**Comment by amishshah** [comment]
Can I see the code you tried to use on master/v12?

**Comment by Seia-Soto** [comment]
@amishshah I couldn't try with latest version, it won't detect voice channel, I'll try few day later due to school exam. Code is common and simple like example on Discord.JS documentation, use ytdl.

Even ``.playFile``(save video with ytdl-core and play it) won't worked for me with ``stable`` branch. Also with Node.JS ``v10`` on Ubuntu.

```js
const Discord = require('discord.js')
const ytdl = require('ytdl-core')

const client = new Discord.Client()

client.on('message', message => {
  if (message === '[prefix]play') {
    message.author.voiceChannel.join()
      .then(connection => {
        connection.playStream(ytdl(VIDEO_URL))
      }
  }
}
client.login(TOKEN)
```

**Comment by amishshah** [comment]
Hi @Seia-Soto, have you had chance to try your bot out on master?

**Comment by Seia-Soto** [comment]
Checked that working with `node-opus` well! +Also ``master`` branch and released one on NPM too, solved.
