### ISSUE TITLE
oldPresence is undefined if member was offline (since new presence update)

### ISSUE THREAD

**Issue by moonstar-x** [discordjs/discord.js#3221]
**Please describe the problem you are having in as much detail as possible:**
Since the presence update done in https://github.com/discordjs/discord.js/pull/3214, the old presence object is undefined when the member who's presence changed was offline. It seems this happens only when the client first sees this change (meaning if the client never saw the members being online in the first place), then it seems like the presence updates are correct afterwards.

It doesn't seem too 'game-breaking' but I thought that maybe this wasn't intended.

**Include a reproducible code sample here, if possible:**
```js

client.on('presenceUpdate', (oldPresence, newPresence) => {
    console.log(JSON.stringify(oldPresence));
    console.log(JSON.stringify(newPresence));
});

```

**Further details:**
- discord.js version: master
- Node.js version: 10.13
- Operating system: macOS Mojave 10.14.4
- Priority this issue should have – please be realistic and elaborate if possible: low

- [x] I have also tested the issue on latest master, commit hash: cde955c7660d753fc1b51c5f94b4f51c6b0d8533

**Comment by amishshah** [comment]
This is intended to help you differentiate between users who were definitely offline and cases where Discord.js never had their presence in the first place.
