### ISSUE TITLE
Re-joining Users cache is not being updated during guildMemberAdd event

### ISSUE THREAD

**Issue by tiritto** [discordjs/discord.js#3225]
User cache is not being correctly patched when User is joining the Guild. I found out about this issue while making a feature that was auto-kicking all joining members with default discord avatars. I've noticed that even when Users update their avatars, they are still being kicked by my bot when they rejoin. It turns out that when guildMemberAdd gets triggered on member who was previously on the server but left (or got kicked), its GuildMember.user data are not being updated but rather their last pre-exit cached data are used.

**I have tested this problem using following code:**
```js
client.on('guildMemberRemove', (GuildMember) => {
   console.log(GuildMember.user.avatarURL());
   // Line below is used in 2nd test and was absent in 1st test
   client.users.delete(GuildMember.id);
});

client.on('guildMemberAdd', (GuildMember) => {
   console.log(GuildMember.user.avatarURL());
});
```

**Test 1**
1. User is present on the server without profile picture.
2. User leaves the server. User.avatarURL() returns null.
3. User changes his avatar to non-default one.
4. User joins back to the server. User.avatarURL() returns null (old cache).

**Test 2**
1. User is present on the server without profile picture.
2. User leaves the server. User.avatarURL() returns null. User cache is deleted.
3. User changes his avatar to non-default one.
4. User joins back to the server. User.avatarURL() returns correct avatar URL.

**Further details:**
- discord.js version: Master, but apperantly it happens on Stable as well
- Node.js version: 11.14.0
- Operating system: Debian 9.7
- Priority this issue should have – please be realistic and elaborate if possible: Medium. A lot people might not even realize that this is happening, thinking that everything works fine. At the same time I doubt that many people do operations so heavily dependent on User data in guildMemberAdd event, therefore Medium priority sounds like the best option, especially since there is a way to overcome this issue (manually clear User cache).

**Comment by amishshah** [comment]
Fixed in the above commit
