### ISSUE TITLE
messageReactionAdd event doesn't work properly

### ISSUE THREAD

**Issue by Paultje52** [discordjs/discord.js#3232]
**Please describe the problem you are having in as much detail as possible:**
When my bot sends a message, I can react to it, for example: I react to a message with 😂 .
And then the event `messageReactionAdd` will be called correctly.
But, when I restart my bot and then react to a message that it allready send, the `messageReactionAdd` event won't be called. 

**Include a reproducible code sample here, if possible:**
```js
const discord = require("discord.js");
const client = new discord.Client();
client.login("TOKEN");

client.on("ready", () => {
  console.log("Online!");
});

client.on("message", async (message) => {
	if (message.author.bot) return;
	message.channel.send("Hello!");
});

client.on("messageReactionAdd", () => {
	console.log(1);
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.15.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Normal

- [x] I have also tested the issue on latest master.

**Fix:**
I think that you can simply fix this by adding an event named `messageReactionAddNoCach` and call that event when the event `MESSAGE_REACTION_ADD` is called with the discord gateway, but the message isn't cached

**Comment by appellation** [comment]
This has already been addressed in the development version of discord.js. If you enable partial emojis, you will receive messageReactionAdd events on messages that are not available in cache. Additionally, #3159 is aiming to provide full raw event access in a documented API.

**Comment by PyroTechniac** [comment]
This is due to the fact that d.js will ignore events that occur on uncached message, what you're looking for is the raw event

you can read more [here](https://anidiots.guide/coding-guides/raw-events)
