### ISSUE TITLE
PermissionOverwrites.default

### ISSUE THREAD

**Issue by withmask** [discordjs/discord.js#3235]
**Is your feature request related to a problem? Please describe.**
I wanted to get default permissions for a role|user on a channel
**Describe the ideal solution**
A property called.default that returns all the default permissions of a role or user in a channel

**Comment by anandre** [comment]
What do you mean by "default permissions"?  Is this different than what `guildChannel#permissionFor` returns?

**Comment by withmask** [comment]
![image](https://user-images.githubusercontent.com/44925389/56824007-46bbe400-684d-11e9-9911-0727c88577a3.png)
This is a default permission (i think),it will take the role permission if it's on the middle

**Comment by almostSouji** [comment]
This symbol denotes that no overwrite, neither allow ✔ nor deny ❌ is specified for this user or role meaning it will use the value the "base" permissions have.

For roles the "base" set of permissions is exactly what's set in the guild for this specific role.
For members it's the permissions of __all__ roles this member has combined (`@everyone` is a role as well).

To get all permissions that do not have an overwrite for this user or role on this specific channel you could start with the full set of permissions and remove everything that's referenced as either deny or allow overwrite.

```js
// const Discord = require("discord.js")
const o = channel.permissionOverwrites.get("id")
const default = Discord.Permissions(Discord.Permissions.ALL)
        .remove(o.allow.bitfield)
        .remove(o.deny.bitfield)
```
- https://discord.js.org/#/docs/main/stable/class/PermissionOverwrites
- https://discord.js.org/#/docs/main/stable/class/Permissions?scrollTo=s-ALL
- https://discord.js.org/#/docs/main/stable/class/PermissionOverwrites?scrollTo=allow
- https://discord.js.org/#/docs/main/stable/class/PermissionOverwrites?scrollTo=deny

This does not yet mirror the view you get in the Discord client though as the displayed flags are also limited by the type of channel they are placed on (for example `MANAGE_MESSAGES` is not present on text channels)

I'm not entirely sure what your usecase for this would be, but that should provide you with enough of an idea how to go about it.

For further elaboration on Permissions and how to use them and Overwrites with Discord.js have a look at the community guide:
- <https://discordjs.guide/popular-topics/permissions.html> 
- <https://discordjs.guide/popular-topics/permissions-extended.html>
