### ISSUE TITLE
Can't compile @discordjs/uws

### ISSUE THREAD

**Issue by mmiszy** [discordjs/discord.js#3249]
I get the following errors whe trying to install `@discordjs/uws`:

```
> @discordjs/uws@11.149.1 install /usr/home/app/node_modules/@discordjs/uws
> node-gyp rebuild

gmake: Entering directory '/usr/home/app/node_modules/@discordjs/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
  CXX(target) Release/obj.target/uws/src/Networking.o
  CXX(target) Release/obj.target/uws/src/Hub.o
../src/Hub.cpp:175:13: error: cannot use 'try' with exceptions disabled
            try {
            ^
1 error generated.
gmake: *** [uws.target.mk:107: Release/obj.target/uws/src/Hub.o] Error 1
gmake: Leaving directory '/usr/home/app/node_modules/@discordjs/uws/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System FreeBSD 11.2-RELEASE-p8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/app/node_modules/@discordjs/uws
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/uws@11.149.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/uws@11.149.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-06T10_43_41_283Z-debug.log
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.15.3
- Operating system: FreeBSD 11.2-RELEASE-p8
- Priority: low

**Comment by jsmiith** [comment]
I haven't got much knowledge of this type of stuff, but, asumming you are running Windows, have you got all of the windows build tools installed? They are required for all node-gyp operations.

If you haven't, launch an elevated command prompt and run the following command and try installing it again:
 **npm i -g windows-build-tools**

**Comment by mmiszy** [comment]
I'm not running Windows.
`Operating system: FreeBSD 11.2-RELEASE-p8`

**Comment by jsmiith** [comment]
> I'm not running Windows.
> `Operating system: FreeBSD 11.2-RELEASE-p8`

Sorry about that, I did a goof. I was tired last night and didn't realize that the OS was already listed.
In that case, have you got the following installed on your system?

- python 2.7
- make
- GCC

**Comment by iREDMe** [comment]
egg

**Comment by Monbrey** [comment]
Worth noting that uws had some serious compatibility issues with the `master` branch anyway, see #3014

**Comment by iCrawl** [comment]
I'd advise against using uWs from this point on. It's not worth maintaining an old version of it anymore.

So for anyone that reads this, just don't use uWs anymore, especially not on newer node versions.
