### ISSUE TITLE
GuildAuditLogsEntry: Overwritten Entity Type in Extras

### ISSUE THREAD

**Issue by ChrisTalman** [discordjs/discord.js#3260]
**Is your feature request related to a problem? Please describe.**
For channel overwrites, the `GuildAuditLogsEntry` can populate `extras` in different ways. If the overwritten entity is available, `extras` will be set to be an instance of the relevant entity class. If the entity is unavailable, `extras` will be populated with `id`, and if the entity is a role, `name`. However, if my reading of [the source code is correct](https://github.com/discordjs/discord.js/blob/d7f8fd1ae0a56e3fee7d87c75e4cdfab5f785604/src/structures/GuildAuditLogs.js#L309), the entity `type` is _not_ included in `extras`. This seems to have the effect of there being no clean manner by which to determine the entity type.

**Describe the ideal solution**
Overwritten entity `type` should be populated in `extras` of `GuildAuditLogsEntry` when appropriate.

**Describe alternatives you've considered**
The existence of `name` could be checked, but this would not be clean.

**Comment by SpaceEEC** [comment]
This has been added to the `11.5-dev` branch with #3760 (dbdb49ee1cc1540e25808534f34a291705250555).
And for the `master` branch: Hopefully with #3602
