### ISSUE TITLE
client.addFriend() returns 405 when using a bot account

### ISSUE THREAD

**Issue by AquaticFish** [discordjs/discord.js#3264]
Hey, making a complicated bot that needs private userbot features, so I made it, only to realize that calling 'message.author.addFriend' returns a warning which is a 405, meaning it won't work

```
(node:30832) DeprecationWarning: User#addFriend: userbot methods will be removed
(node:30832) UnhandledPromiseRejectionWarning: DiscordAPIError: 405: Method Not Allowed
```

Any way you could fix this?

**Comment by almostSouji** [comment]
Userbots (no matter for what cause) are against discord developer terms of service.
In accordance the support for them has been removed from the library and the methods in question are just present for semver reasons.

semver: <https://semver.org/>
source: <https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots->
