### ISSUE TITLE
messageReactionRemove firing twice

### ISSUE THREAD

**Issue by TheLearneer** [discordjs/discord.js#3268]
**Please describe the problem you are having in as much detail as possible:**

When I run the code below the `messageReactionRemove` event fires twice incorrectly. Sample test screenshots below where the reaction count goes to zero as per the code, but the reaction by first user is still available.

Its happening when I include the code:
```js
if (reaction.count > 1) await reaction.users.remove(user);
```

![image](https://user-images.githubusercontent.com/23402178/57673993-a08a1f80-763d-11e9-8dd3-57399b274a0d.png)

![image](https://user-images.githubusercontent.com/23402178/57674068-d0d1be00-763d-11e9-93c9-a65bdbdb4f54.png)

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('messageReactionAdd', async (reaction, user) => {
  if (reaction.emoji.name !== '⭐') return;
  console.log(`Reaction added by ${user.tag}! New star count ${reaction.count}`);
  if (reaction.count > 1) await reaction.users.remove(user);
});

client.on('messageReactionRemove', (reaction, user) => {
  if (reaction.emoji.name !== '⭐') return;
  console.log(`Reaction removed by ${user.tag}! New star count ${reaction.count}`);
});

client.login('TOKEN');
```

**Further details:**
- discord.js version: [Master#72dd872](https://github.com/discordjs/discord.js/commit/72dd872fce70754b0f7616f3d31b5616a48c7188)
- Node.js version: **10.15.3**
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible: :confused: Not sure

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Supernalboot** [comment]
Seems like the first use add a star `star = 1` which doesn't trigger `if (reaction.count > 1) await reaction.users.remove(user);`. but if a second user reacts `star = 2` it triggers `if (reaction.count > 1) await reaction.users.remove(user);` making `star = 1` and then triggers.

`client.on('messageReactionRemove', (reaction, user) => {
  if (reaction.emoji.name !== '⭐') return;
  console.log(`Reaction removed by ${user.tag}! New star count ${reaction.count}`);
});`

making `star = 0`

**Comment by TheLearneer** [comment]
@Supernalboot I guess you are not getting my point.

The issue I am having is, when I call `reaction.users.remove(user)` It should be firing the `messageReactionRemove` event once.

But as seen in the screenshot below its firing twice and for the same user.
The last two lines in the screenshot are fired by the codes itself i.e. `reaction.users.remove(user|)` code.
![image](https://user-images.githubusercontent.com/23402178/57673993-a08a1f80-763d-11e9-8dd3-57399b274a0d.png)

And again the screenshot below shows that the reaction from first user is still there (**as for discord**) but there is no reaction (**as for discord.js**)
![image](https://user-images.githubusercontent.com/23402178/57674068-d0d1be00-763d-11e9-93c9-a65bdbdb4f54.png)

**Comment by KhooHaoYit** [comment]
I think it has the same issue as #3252.
