### ISSUE TITLE
Missing class 'Attachment' and functions of 'GuildMember'

### ISSUE THREAD

**Issue by MrShoopa** [discordjs/discord.js#3270]
**Please describe the problem you are having in as much detail as possible:**
Rewriting my bot for TypeScript, I've noticed a few things were missing in the scripts of the package and the TS declarations (Even though they were included in the documentation):

- '_Attachment_' class and its' member functions/variables
- '_GuildMember_' missing _addRole()_, _removeRole()_, and related functions mentioned in discord.js documentation.

**Include a reproducible code sample here, if possible:**
```js
// 'member' in this context is a GuildMember instance 
// 'restricted_role_id' in this context is a string of an id

member.addRole(restricted_role_id)
                    .then(() => {
                        console.log(
                            `Adding ${member.displayName} to the role: ${restricted_role_id}`)
                    })
```

**Further details:**
- discord.js version: 'github:discordjs/discord.js#72dd872fce70754b0f7616f3d31b5616a48c7188'
- Node.js version: v10.14.1
- Operating system: Windows 10 May 2019
- Priority this issue should have – please be realistic and elaborate if possible:
Documentation issue; minor issue since the role manipulation methods were very easy to use

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Based on the commit you put in the discord.js version, I see no "Attachment" class.
<https://discord.js.org/#/docs/main/master> (left hand side obviously)

And addRole does not exist on v12 either.
<https://discord.js.org/#/docs/main/master/search?q=addRole>

What you are really looking for is how to convert your v11 code to v12 code, which is outlined here: <https://github.com/discordjs/discord.js/wiki/Data-Stores>
