### ISSUE TITLE
Can't detect if user is streaming unless they are playing a valid game

### ISSUE THREAD

**Issue by digimbyte** [discordjs/discord.js#3278]
There is no `presence.streaming` 
instead, it is tied to `presence.game.streaming`
which means it is only possible to detect if a person is playing a game and streaming together.

Currently, it is not possible to work with a person who is streaming anything else unless it's specifically a detectable game by discord.

**Include a reproducible code sample here, if possible:**
```js

// if (data.before.presence.game || data.after.presence.game) {
      console.error("GAME CHANGE DETECTED");
      if (data.after.presence.game.streaming) {
        channel.send(`${data.after.presence.game.name}`);
        console.error("ADD ROLE");
      }
      else {
        console.error("REMOVE ROLE");
      }
// }
```

**Further details:**
- discord.js version: 11.5
- Node.js version: 10.7
- Operating system: windows 10 64bit
- Priority this issue should have – High

https://www.twitch.tv/videos/426199121
I was clearly streaming in this video, but the `console.error "ADD ROLE"` never triggered

tested on latest discord.js 11.5.0
- [ ] I have also tested the issue on the latest master, commit hash:

**Comment by iCrawl** [comment]
This has been inactive for quite some time and I can't reproduce it, reopen if this issue still persists (on master branch).
