### ISSUE TITLE
Update multiple role positions at once

### ISSUE THREAD

**Issue by sleziak** [discordjs/discord.js#3280]
Discord has an API to update multiple role positions at once [`PATCH /guilds/{guild.id}/roles`](https://discordapp.com/developers/docs/resources/guild#modify-guild-role-positions)

It would be great if that API could be implemented within DiscordJS.

I'm currently integrating my RBAC system on my website with Discord and it's quite error prone when it comes to keeping roles in a correct order, setting multiple role positions in a single call would fix that.

![image](https://user-images.githubusercontent.com/17406493/57973600-b3895080-79ab-11e9-96bf-2130a73dc9d3.png)

Changing the order of a role causes a cascade of updates, I've done my best to calculate the least amount of reposition calls, but there is always the chance that something goes wrong.

**Comment by brxxn** [comment]
Added in #3317. Can this be closed now? Thanks!

**Comment by sleziak** [comment]
Much appreciated! This can be closed now.
