### ISSUE TITLE
Wrong role position returned

### ISSUE THREAD

**Issue by Thornsnake** [discordjs/discord.js#3286]
**Discord JS Version 11.5.0**

I am trying to move a specific role right underneath the bots current highest role. When I am trying to get the bots highest role position, it tells me it is 22. When I'm checking the list of roles in Discord however, the position of the bots highest role is 20, not 22. When I then try to move a role to position 21, the attempt fails with the following error.

> DiscordAPIError: Missing Permissions
>     at item.request.gen.end (/home/dev/nodejs/spectrum/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
>     at then (/home/dev/nodejs/spectrum/node_modules/snekfetch/src/index.js:215:21)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Moving some unrelated roles around and back seems to fix the issue, but only for a while. The part of my code that throws this error would be this one.

```
//#region Check if the bot does have access (his highest role is higher) to the role.
const bot_role = bot_user.highestRole;
const bot_is_higher = bot_role.comparePositionTo(role) > 0;
//#endregion

if (bot_is_higher) {
	//#region If role is not beneath bot role, move it there.
	if (role.position !== bot_role.position - 1) {
		await role.setPosition(bot_role.position - 1);
	}
	//#endregion
}
```

The bot does have admin rights, so it shouldn't be a permission issue. Before I'm trying to move the role, I'm checking whether I can (bot role is higher) move it. When it then executes the **setPosition()** command, it throws the error above, because **bot_role.position** returns **22** instead of the correct **20** and it then is trying to move a role to position **21**, which it can't.

**Comment by Fyk0** [comment]
If this helps, when you calculate the position of the top-most role on the Role manager, it is equal to the size of the RoleStore itself. 
![image](https://user-images.githubusercontent.com/45381083/58217979-10417f80-7cba-11e9-8614-ad99a9173731.png)

**Comment by Thornsnake** [comment]
Yes, I know. The role @everyone is at position 0 and the roles pos 1 to pos 3 from your screenshot have the indices 1-3.

The problem is, that when I'm asking the role position of the **pos 2** role, the index position returned is sometimes **3** or **4**, instead of **2**.

This is not always happening, but when it does, it gets stuck with that wrong information and will not update it until I manually move a role. Not even restarting my bot will fix it, but when I - let's say - move **pos 1** somewhere else or any other role and move it back, the problem will fix itself and **pos 2** will return **2** as its position.

I do not know what is causing this. I was thinking that Discord JS maybe has a role cache that is not updated correctly, but restarting the bot should clear any caches, shouldn't it?

![dmkESo1RRT_oRg23TyHV7Q](https://user-images.githubusercontent.com/43046258/58276081-d4c8b300-7d96-11e9-81f0-ebdd0e4902d6.png)

Here is an example. When I am trying to get the role position of the role **:Spectrum:**, it'll return **22** as position. Looking on this list, the role is actually on position **20** though. Now if I move any role around, this wrong position information will update and I'll get **20** returned correctly. But after the bot is moving around and ordering new roles for a while, eventually it'll get stuck again on wrong role position informations.

**Comment by devsnek** [comment]
use computedPosition

**Comment by Thornsnake** [comment]
Hmm I see, I'll try to go with **calculatedPosition** then and see if that works. I'm confused though. Why is the position returned from the API wrong sometimes?

**Comment by devsnek** [comment]
@Thornsnake roles that haven't changed position are sorted by id because they happen to exist in order of creation.

**Comment by Thornsnake** [comment]
I see, so no bug, just a lack of understanding on my part. Thank you a lot for your explanation.
Issue should be resolved then, I'll be using **calculatedPosition** now.
