### ISSUE TITLE
ETIMEDOUT Error

### ISSUE THREAD

**Issue by vicdum** [discordjs/discord.js#3287]
**Please describe the problem you are having in as much detail as possible:**

I always get an "ETIMEDOUT" error. The bot, which worked properly before, started to give this error for a few months. According to others, this is only happening in the TR location and when using Discord.js
```
[2019-05-20 22:31:09]: ERROR Unhandled rejection: Error: connect ETIMEDOUT 104.1
6.58.5:443
[2019-05-20 22:31:09]: ERROR Unhandled rejection: Error: connect ETIMEDOUT 104.1
6.58.5:443
```

**Further details:**
- discord.js version: Latest
- Node.js version: 10.15.3
- Operating system: Windows Server 2012 R2
- Priority this issue should have – please be realistic and elaborate if possible: High

- [x] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
"Latest" isn't helpful, can you specify the version you have installed? You can check with `npm list discord.js`

**Comment by vicdum** [comment]
> "Latest" isn't helpful, can you specify the version you have installed? You can check with npm list discord.js

11.5.0

**Comment by amishshah** [comment]
From what you've said, this sounds like a network issue and unfortunately we won't be able to help. You can try joining our server (https://discord.gg/bRCvFy9) to get some support.

**Comment by Eagle-42** [comment]
Did you manage to fix it ? I'm occuring the same issue
