### ISSUE TITLE
Playfile Stuttering and early cut

### ISSUE THREAD

**Issue by Goubeling** [discordjs/discord.js#3288]
Hello everyone.

I started to make a bot to entertain my discord.

But I have some issues with playing mp3 files. At start they stuttering, and they cut earlier at the end  too earlier.

I tried the branch master, but it didin't fix.

My code with branch master :

```js

	if ((msg.content.toLowerCase()).includes("poke") && !bPlaying) {
		if(msg.member.voice.channel) {
			//if(!connection) {
				//console.log(sUsul.indexOf(msg.content));
				msg.member.voice.channel.join()
					.then(connection => {
						const dispatcher = connection.play('./sound/risipoke.mp3'); // INSUPPORTABLE
						bPlaying = true;
						dispatcher.on("end", end => {msg.member.voice.channel.leave(); bPlaying = false;});
					})
					.catch(console.error);
			//};
		};
	};

```

If anyone have an idea, thanks in advance.

**Further details:**
{
  "name": "watchbot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "discord.js": "github:discordjs/discord.js",
    "ffmpeg": "0.0.4",
    "opusscript": "0.0.6",
    "xmlhttprequest": "^1.8.0",
    "ytdl-core": "^0.29.2"
  },
  "devDependencies": {
    "nodemon": "^1.18.11"
  }
}

- [X] I have also tested the issue on latest master, commit hash:

**Comment by Goubeling** [comment]
And with 2-3 secs long mp3, i can't even hear them, it's too fast

**Comment by Goubeling** [comment]
Nobody ?

**Comment by Fyk0** [comment]
Please join the [Support Server](https://discord.gg/bRCvFy9) and ask your question there in its respective channel. *probably #djs-voice-not-ytdl*

**Comment by amishshah** [comment]
See @Fyk0's comment
