### ISSUE TITLE
Undefined old VoiceState for left or banned members

### ISSUE THREAD

**Issue by BadCoder1337** [discordjs/discord.js#3289]
Usual disconnect from Voice Channel: 
![image](https://user-images.githubusercontent.com/16510197/58165279-191d5b80-7c90-11e9-8c24-86f544180df5.png)
Disconnect with leave or ban:
![image](https://user-images.githubusercontent.com/16510197/58165332-36eac080-7c90-11e9-9bfc-65ad3efb9ce9.png)
Old state fields remains undefined even if bot recently catch new state from join event

**Further details:**

- discord.js version: master#b3060ea

- Node.js version: 10.15.3

- Operating system: Microsoft Windows [Version 10.0.17763.503]

**Comment by amishshah** [comment]
Can you see if https://github.com/discordjs/discord.js/commit/db56e0cbae67f221db9265f6889ae2b4f5c987d4 fixes your issue?

**Comment by BadCoder1337** [comment]
No, @amishshah.
But I've found why old VoiceState is undefined for removed members. Discord sends `guildMemberRemove` event before `voiceStateUpdate`. So discord.js uncaches member and its voice before firing `voiceStateUpdate`. Idk if this is a bug or feature, but handling incomplete event a bit puzzling me.
![image](https://user-images.githubusercontent.com/16510197/58435899-7750a100-80cb-11e9-9c2a-b86141fc7468.png)

**Comment by amishshah** [comment]
So as I understand, the issue is that voiceStateUpdate is emitted when a member in a voice channel leaves the guild?

**Comment by BadCoder1337** [comment]
I mean, if the member has cached VoiceState, `guildMemberRemove` handler should temporarily keep it for the `voiceStateUpdate` event to avoid `undefined` in these fields 
![image](https://user-images.githubusercontent.com/16510197/58441895-a62c3e80-80ee-11e9-9899-2f1d9e5fc212.png)

**Comment by amishshah** [comment]
I understand your point, but there's not much we can do. In the past, I'm pretty sure that `VOICE_STATE_UPDATE` wasn't sent sometimes when a member left the guild, so we need to delete the voice state on the `GUILD_MEMBER_REMOVE` event to ensure it's actually deleted.

However, https://github.com/discordjs/discord.js/commit/b5aff6d12006697d77dd10cd49cfca591065d9b3 should fix your problem - in the `guildMemberRemove` event, `member.voice` should still be immediately intact. I hope this helps you! Please reopen this issue if you have any more concerns.
