### ISSUE TITLE
Incorrect typings for Guild

### ISSUE THREAD

**Issue by DasCodeMonster** [discordjs/discord.js#3293]
**Please describe the problem you are having in as much detail as possible:**
typings export a `voiceConnection` property :

![image](https://user-images.githubusercontent.com/28789417/58328876-7ef61880-7e33-11e9-9951-876bef4cebec.png)
but `Guild` has a `voice` property of type `VoiceState`:

![image](https://user-images.githubusercontent.com/28789417/58328976-c4b2e100-7e33-11e9-9e70-eeb80481c3d0.png)

Docs are correct though

**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: 10.4.0
- Operating system: Win 10 Pro 1809
- Priority this issue should have – please be realistic and elaborate if possible: low

- [x] I have also tested the issue on latest master, commit hash: b3060ea229e5a5395f7fb67291ead0440e6c55ca

**Comment by SpaceEEC** [comment]
Thank you for the info, that should be fixed with the referenced commit!

**Comment by DasCodeMonster** [comment]
Yes thank you this is fixed but i just noticed that the `VoiceState` typings should also export a `connection` property which now holds the VoiceConnection of the client

**Comment by bdistin** [comment]
Yeah, there is a pr open for that #3292

**Comment by DasCodeMonster** [comment]
Oh, OK did not see that thanks!
