### ISSUE TITLE
If a member joins a voice-channel then will the bot send a dm

### ISSUE THREAD

**Issue by JuuzouSchuschuya** [discordjs/discord.js#3300]
Hey Guys, I need help^^ 

My problem is, i dont know how the bot send a direct message if the player go in a Support channel. It should only send him a message when he go in this one channel. 

Pls help me ^^

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
