### ISSUE TITLE
[BUG] stream = receiver.createPCMStream(user)

### ISSUE THREAD

**Issue by iMegaMaximus2** [discordjs/discord.js#3304]
`stream = receiver.createPCMStream(user)`

stream not emit 'data' event

discord.js 11.5 version

**Comment by amishshah** [comment]
Per #2929, Discord doesn't support receiving audio. You might have better luck with this on master branch, which I believe works at the moment.

**Comment by iMegaMaximus2** [comment]
> Per #2929, Discord doesn't support receiving audio. You might have better luck with this on master branch, which I believe works at the moment.

Master branch has 12 version, buut 12 version has no docs(

**Comment by iMegaMaximus2** [comment]
@amishshah  ### ingenious <3
