### ISSUE TITLE
A way to get users connected accounts

### ISSUE THREAD

**Issue by EGGamer** [discordjs/discord.js#3306]
I would like to check if a user has XBOX connected to its account, and if it has XBOX connected to Discord, I would like to change his nickname to the XBOX Gamertag.

It would be great if there was a method to get all the user connected (and visible) accounts to do something with them.

**Comment by Darqam** [comment]
This would require user profiles, which are not accessible to bots.

**Comment by appellation** [comment]
This is only possible through OAuth with the `connections` scope. https://discordapp.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes

Discord.js doesn't do much in the way of supporting OAuth, but we do support some endpoints so I'm not sure what the criteria is.
