### ISSUE TITLE
Role List After roleUpdate Has Roles with Same Position

### ISSUE THREAD

**Issue by rag4214** [discordjs/discord.js#3308]
**Please describe the problem you are having in as much detail as possible:**
Sometimes after a roleUpdate event is called (moving roles, not creating / deleting), the role list from a guild will have roles that have the same position.

**Include a reproducible code sample here, if possible:**
```js

// Place your code here

// I have this in my code just image it is a legit bot role that is stored

botRole = some managed bot role

client.on('roleUpdate', (newRole, oldRole) => {
    if (newRole.id === botRole.id) {
        newRole.guild.roles.sort((a, b) => b.position - a.position).forEach(role => {
            console.log(`{role.name} : ${role.position}`);
        }
    }
}

```

**Further details:**
- discord.js version: 11.5.0
- Node.js version: 10.15.3
- Operating system: macOS Mojave 10.14.5
- Priority this issue should have – please be realistic and elaborate if possible:

Not a super high priority. I have a not optimal patch in my code to fix the issue, but it was still annoying to debug.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Roles will only change the position when actually moved. In other words: If you create multiple roles they will have the same position.

You can use [`Role#calculatedPosition`][RoleCalculatedPosition] to get around that.

[RoleCalculatedPosition]:https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=calculatedPosition

**Comment by rag4214** [comment]
Sorry, should have put in there when moving the role, it's updated now
