### ISSUE TITLE
Audio not playing and keeps play re-enter sound (linux, windows)

### ISSUE THREAD

**Issue by ktjd123** [discordjs/discord.js#3311]
**Please describe the problem you are having in as much detail as possible:**

the bot doesn't play the file of mp3 and keeps re-enter the voice channel

**Include a reproducible code sample here, if possible:**

```js

let voiceChannel = await bot.channels.get(notification.voiceChannel)
      .connection;
    if (!voiceChannel) {
      return;
    }
    let dispatcher = undefined;

    if (notification.type === "boss") {
      dispatcher = voiceChannel.play(
        path.join(resPath, notification.voice + ".mp3")
      );
    }else ~~~
```

**Further details:**
- discord.js version: master branch
- Node.js version: v10
- Operating system: linux, windows
- Priority this issue should have – please be realistic and elaborate if possible: high

- [v ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Can you add the following:
```js
client.on('debug', msg => {
  if (msg.includes('VOICE')) console.log(msg);
});
```
and send the output?

**Comment by ktjd123** [comment]
I can't use this code for the server because test server(Mac) works perfect with new commits but only live server(Windows)s don't say anything. I restored to previous update with live server.

**Comment by ktjd123** [comment]
is there any update for this issue? 

always appreciate your works 👍

**Comment by amishshah** [comment]
Sorry, I'm not going to be available to work on the issue for a week and a half yet. After that I'll try to fix it!

**Comment by ktjd123** [comment]
@amishshah curious if there is any updates!!

**Comment by seohoyoung94** [comment]
> Sorry, I'm not going to be available to work on the issue for a week and a half yet. After that I'll try to fix it!

As I am also, I hope to solve this problem quickly.

**Comment by iCrawl** [comment]
3362
