### ISSUE TITLE
Music ends abruptly without log

### ISSUE THREAD

**Issue by JMTK** [discordjs/discord.js#3314]
I checked [this](https://github.com/discordjs/discord.js/issues/1387) before opening this. It seems to be the similar, but the dispatcher doesn't seem to fire any more events.

**Please describe the problem you are having in as much detail as possible:**
This code has remained largely unchanged, but I used to be on https://github.com/discordjs/discord.js/commit/132788937a61490b5003117006f9e28164c14608 
 when it was first checked in and did not get latest src for a while. Once I got the current build(hash below), I had a couple of code updates to do with changing `voiceConnection` -> `voice.connection` etc. However some songs abruptly stop without error/debug log. A video it happened to was https://www.youtube.com/watch?v=penvn9VL32Y. However I restarted the bot and queued it again and it finished without stopping so it isn't consistent from my testing.

If I call my skip command to go to the next song in queue, it begins playing the next song as if nothing was wrong.

**Include a reproducible code sample here, if possible:**
```js
//in another file
mybot.on('debug', (e) => {
    var err = e.toString().toLowerCase();
    if (err.includes("voice")) util.log("DEBUG>", e);
});

//in music file
let ytstream = ytdl(nextSong.url, {
  filter: "audioonly",
  quality: "highestaudio"
});

ytstream.on("error", err => {
  util.log("ytdl err: ", err.toString().split("\n")[0]);

  ytstream.destroy();

  musicReply(message, "There was an issue playing this track");
  moveToNextSongInQueue();
});

ytstream.on("info", async o => {
  let ts =
    nextSong.timestamp && !isNaN(nextSong.timestamp) ? nextSong.timestamp : 0;
  let volume = Config.AudioVolume;
  try {
    let l = o.loudness; //yt volume equalization
    volume = Number(((60 + (l && l < 0 ? l : -40)) / 100).toFixed(2));
  } catch (ex) {
    volume = Config.AudioVolume;
  }
  if (isNaN(volume)) {
    volume = Config.AudioVolume;
  }
  util.log("Intent Info", ts, volume); //this is usually something like 0, 0.2
  let intent = vCon.play(ytstream, {
    seek: ts,
    volume: volume
  });

  intent.on("debug", util.log);

  intent.once("error", e => {
    try {
      util.log("ERROR> Playing YouTube", e);

      if (e.toString().includes("ERR_STREAM_DESTROYED")) return;
      musicReply(message, "There was an issue playing this song.");
    } catch (ex) {
      util.log(ex);
    }
  });

  intent.once("finish", () => {
    try {
      ytstream.destroy();

      queue.splice(0, 1);
      playNextSong();
    } catch (ex) {
      util.log(ex);
    }
  });
});
```

Log output
![image](https://user-images.githubusercontent.com/877114/58749952-2d184880-845a-11e9-9354-945b469cd784.png)

**Further details:**
- ffmpeg version: **v4.1.3** (I also tried compiling it myself from source)
- node-opus version: **v0.3.2**
- discord.js version: **v12 ([github:hydrabolt/discord.js#97de79bd5e34ab043a75db1f4fdb738bd20f21c3](https://github.com/discordjs/discord.js/commit/97de79bd5e34ab043a75db1f4fdb738bd20f21c3))**
- Node.js version: **v10.15.3**
- ytdl-core version: **v0.29.2**
- Operating system: **Debian GNU/Linux 8.11 (jessie)**

The only optional package I have is `zlib-sync`.

I'm happy to provide more code/versions if needed.

- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:
I can get latest but it didn't look like any major voice changes happened.

**Comment by deitux123** [comment]
looking at the source, I think the end event is not being triggered by dispatcher

**Comment by hickleydonate** [comment]
Try to remove all ffmpeg modules/packages, and use command `npm i ffmpeg`

**Comment by JMTK** [comment]
This seems mostly resolved by upping the highWaterMark value. I don't know if that's considered an acceptable solution though.

https://github.com/fent/node-ytdl-core/issues/402

**Comment by iCrawl** [comment]
#3362
