### ISSUE TITLE
Fetching bans on stable doesn't include reasons

### ISSUE THREAD

**Issue by n3oney** [discordjs/discord.js#3318]
**Please describe the problem you are having in as much detail as possible:**

When on stable, fetching bans while including the variable withReasons as true, still returns a collection of just users, while on 11.5-dev it also includes reasons.

**Include a reproducible code sample here, if possible:**
```js

message.guild.fetchBans(true).then(bans => console.log(bans)) //Collection of users

```

**Further details:**
- discord.js version:  stable
- Node.js version: 12.3.1
- Operating system: Raspbian Stretch
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
Please specify your version by the actual version number not some tag please, when opening an issue.
You can find out your version with `npm ls discord.js` if you are unsure on how to do so.

I checked this on the currently supported stable version as of writing this (11.5.1) and can not reproduce the described behaviour.
`guild.fetchBans(true).then(b => b.first())`
returns a ban object, not a user, same applies for the entire collection.:
```js
{ reason: 'by Souji#0001 | 83886770768314368 | testing',
  user: [User] }
```
If no reason was set the collection still contains objects, not User instances and the `reason` property is `null`

**Comment by saintss** [comment]
how to get banned people amount

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
