### ISSUE TITLE
Yarn: Use node-fetch instead of snekfetch

### ISSUE THREAD

**Issue by IngwiePhoenix** [discordjs/discord.js#3319]
During installation of `discord.js`, this appears quite frequently:

```
warning discord.js > snekfetch@3.6.4: use node-fetch instead
```

Can this safely be ignored?

**Comment by Pharaoh2007** [comment]
snekfetch is just deprecated and may be removed in upcoming versiond just use node-fetch it is easy to use. 
this is the link for package  :https://www.npmjs.com/package/node-fetch
and this is a tag from our server
Read about how to interact with data from all different kinds of sites through the use of APIs, using HTTP requests:
https://discordjs.guide/#/additional-info/rest-api
this link uses node fetch too
 btw it is preferred to use node fetch but you can ignore it as well

**Comment by Pharaoh2007** [comment]
@IngwiePhoenix

**Comment by kyranet** [comment]
Yes, you can safely ignore that. `discord.js@11.x` uses `snekfetch` as its change would be semver-major, that's why master (`discord.js@12.x`) uses `node-fetch` instead.

**Comment by IngwiePhoenix** [comment]
I see, good to know!

When will discord.js@12 be available on NPM?

**Comment by Deivu** [comment]
> I see, good to know! When will discord.js@12 be available on NPM?

Soon™
