### ISSUE TITLE
VoiceChannel.join() never returning a connection

### ISSUE THREAD

**Issue by pacojq** [discordjs/discord.js#3320]
I'm trying to connect a bot to a voice channel to play some audio. The channel returs true when calling ```channel.joinable```, and when I call ```channel.join()``` the bot appears as joined in the Discord server. However, the ```join()``` method never goes past the ```await``` part, and kind of gets stuck in an infinite loop.

Other samples of code I'm taking as refference don't seem to have this problem, so I wonder if this might be a configuration or permissions issue.

Here's my code:
```js

    play: async function(url, message) {
        
        // Validate
        let validate = await this.ytdl.validateURL(url);
        if (!validate) {
            message.channel.send("Sorry, please input a **valid** URL.");
            return;
        }

        // Fetch the info
        console.log("Getting info...");
        let info = await this.ytdl.getInfo(url);
        console.log("Connecting...");
        let connection = await message.member.voiceChannel.join();

        // Play song
        console.log("Playing...");
        let dispatcher = await connection.play(this.ytdl(url, {filter: 'audioonly'}));
        message.channel.send("Now playing: " + info.title);
        dispatcher.on('finish', () => {
            console.log('Finished playing!');
          });
        
    },

```

**Further details:**
- discord.js version: ^11.5.1
- Node.js version: 10.15.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by deitux123** [comment]
do a .catch on the connection function, you could be getting a 403 error

**Comment by pacojq** [comment]
Thanks for helping, @deitux123 , but I'm affraid that's not fixing the problem.

I've just tried your solution and the execution of the function still hangs at the same point, and no error is prompted. The execution doesn't stop neither, I just keeps waiting for the conection, with no result or error to catch.

Anyway, thanks for your help!

**Comment by Deivu** [comment]
As far as I remember, .join() timeouts after 15 seconds of no response, this could be an issue.

**Comment by m-shevtsov** [comment]
I have exact same problem. Did not change actual code just updated all my modules and got this issue.
Bot still does connect to the voice channel but connection object is never returned. I use callbacks instead of async/await, but neither .then() nor .catch() is ever executed

**Comment by maxymoo22** [comment]
What if you try to use message.guild.voiceConnection to get a connection object instead ?

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
