### ISSUE TITLE
Run voice call from electron window

### ISSUE THREAD

**Issue by iMegaMaximus2** [discordjs/discord.js#3328]
![image](https://user-images.githubusercontent.com/49617181/58932413-4972f880-876c-11e9-9f84-90de3d67a11f.png)
![image](https://user-images.githubusercontent.com/49617181/58932417-4d067f80-876c-11e9-8746-911f3e808649.png)

but it is electrron window, not a browser. electron window have assecc to opus codec e.t.c. electron window its like nodejs

i use hack andeverything began to work =)
![image](https://user-images.githubusercontent.com/49617181/58932467-86d78600-876c-11e9-87c6-64eb6ab7c88a.png)

Electron window is detected like this:

![image](https://user-images.githubusercontent.com/49617181/58932513-b9817e80-876c-11e9-8abf-a737e41b7306.png)

**Comment by iMegaMaximus2** [comment]
помогите кто нибудь, я не могу доделать проект  

![image](https://user-images.githubusercontent.com/49617181/59150710-a9012a80-8a30-11e9-981b-38ddd5433309.png)

**Comment by iMegaMaximus2** [comment]
![image](https://user-images.githubusercontent.com/49617181/59151061-b836a700-8a35-11e9-8677-750c3be00df1.png)

**Comment by iCrawl** [comment]
You are not supposed to run the voice stuff from the electron window, it simply doesn't work that way.
For this to work you have to communicate with the backend code of your electron app.
How? Well, sadly this isn't really in the scope of this library of issue tracker.
