### ISSUE TITLE
.setDiscriminator() function

### ISSUE THREAD

**Issue by dhBxnny** [discordjs/discord.js#3329]
### Add a `.setDiscriminator()` function.

In my point of view, all the bot programmers who use discord.js as their common library would love to see a function such as `.setDiscriminator()` which sets the discriminator of the bot user.

An example of how it would look like (being utilized on a bot code) is:
```
.setDiscriminator('1000').then(newDiscriminator () => {
      console.log('Set the new bot discriminator to ' + newDiscriminator);
}
```

**Comment by almostSouji** [comment]
This is not possible, as the API does not allow free setting of discriminators for bots.
While for users this might be possible using a user token for your bot is against discords terms of service and the library does not plan on adding any client user functionality based on this (even removed all prior functionality regarding user tokens with the new version 12)

reference: <https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots->
