### ISSUE TITLE
Cannot read property 'username' of null

### ISSUE THREAD

**Issue by dhBxnny** [discordjs/discord.js#3334]
**Issue Description**
I defined footer to set it on all the embeds with an easier way:
```
const Discord = require('discord.js');
const bot = new Discord.Client();
const footer = `${bot.user.username} | 2019`
```

I get an error which is:
```
const footer = `${bot.user.username} | 2019`
                           ^
TypeError: Cannot read property 'username' of null
```

I tried to fix this error but I am not sure what to do. Please help me.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
