### ISSUE TITLE
Attachment names are incorrectly parsed, preventing file sending

### ISSUE THREAD

**Issue by MysteryPancake** [discordjs/discord.js#3341]
**Please describe the problem you are having in as much detail as possible:**
Discord.js does not correctly deal with special characters (such as `\n`) in attachment file names, causing the API error "Cannot send an empty message", and failing to send the attachment.

**Include a reproducible code sample here, if possible:**
```js
// DEFAULT BEHAVIOR (BROKEN):

message.channel.send({
	files: [{
		attachment: "anyfile.png",
		name: "test\ntest.png"
	}]
})

// POSSIBLE FIX:

message.channel.send({
	files: [{
		attachment: "anyfile.png",
		name: "test\ntest.png".replace(/[^a-z0-9]/gi, "_")
	}]
})

```

**Further details:**
- discord.js version: latest (master)
- Node.js version: v10.6.0
- Operating system: macOS Mojave
- Priority this issue should have – please be realistic and elaborate if possible:
Somewhat important, as this completely stops the file from being sent

- [x] I have also tested the issue on latest master, commit hash: https://github.com/discordjs/discord.js/commit/19ef45130b8d3a226500a0ccd69f7d90aaa02430

**Comment by Monbrey** [comment]
You could always _not_ put a special character in the filename though.
I don't think it's the responsibility of Discord.js to sanitize your filenames for the API

**Comment by MysteryPancake** [comment]
I agree - I noticed that the filenames are also cut to a certain length, and I thought this was a feature of Discord.js rather than Discord's API itself.
