### ISSUE TITLE
Discord Voice API for browser

### ISSUE THREAD

**Issue by nsmith1024** [discordjs/discord.js#3354]
Does discord have voice chat API capability from a browser?

I have a browser based game in unity/WebGL, and i wanted to have discord voice chat for the game that also runs in the same browser. I thought maybe i could call the discord voice javascript API from the Unity game also running in the same browser, to enable/disable the voice, set up voice channels etc. Then have a discord server running on my own computer which my gamers would use to voice chat with each other.

So i wanted to know if this is possible, or maybe some other alternative for voice in a browser game? The browser has mic capability, the browser can play movies and other advanced features so i cant see why voice wouldnt work in the browser too.

Thanks

**Comment by cfanoulis** [comment]
No, d.js doesn't expose a voice API in the browser. And that is because, if I recall correctly, there is no (easy) was to use the voice modules that discord.js includes in the browser
