### ISSUE TITLE
client.guildBoosted event

### ISSUE THREAD

**Issue by Firefaul** [discordjs/discord.js#3359]
Currently it's impossible to check when a guild is boosted via nitro; it would be pretty neat to write custom notifications or do certain things whenever a user boosts a guild.

**Comment by devsnek** [comment]
boosts notifications are a type of message. you can check `message.type`.

**Comment by Firefaul** [comment]
> boosts notifications are a type of message. you can check `message.type`.

If the boost notifications are disabled, it's impossible to tell when a server is boosted via discord.js.

**Comment by devsnek** [comment]
if boost notifications are disabled then they're disabled, nothing a library can do about it.

**Comment by Firefaul** [comment]
> if boost notifications are disabled then they're disabled, nothing a library can do about it.

That's essentially saying that if member notifications are disabled, then there shouldn't be a way to detect when a member joins. My point still stands; we need an event for when a user boosts a server.

**Comment by Tylertron1998** [comment]
You could listen to guildMemberUpdate and check for a role with managed: true and Nitro Booster as the name.

**Comment by devsnek** [comment]
you can also listen for member updates with the previous premium since being null and the new one being not null

**Comment by Monbrey** [comment]
> > if boost notifications are disabled then they're disabled, nothing a library can do about it.
> 
> That's essentially saying that if member notifications are disabled, then there shouldn't be a way to detect when a member joins. My point still stands; we need an event for when a user boosts a server.

So tell Discord that. There's nothing any library can do about it unless the Discord gateway sends an event.

**Comment by SpaceEEC** [comment]
I think @devsnek's suggestion with listening to [`guildMemberUpdate`] and checking whether [`GuildMember#premiumSince`] was, but not is, `null`, is the way to go.

[`guildMemberUpdate`]:https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-guildMemberUpdate
[`GuildMember#premiumSince`]:https://discord.js.org/#/docs/main/master/class/GuildMember?scrollTo=premiumSince
