### ISSUE TITLE
nitroBoost event

### ISSUE THREAD

**Issue by dhBxnny** [discordjs/discord.js#3363]
When someone boosts a server, the bot sends a message to a channel.

**Example:**
```js
client.on('nitroBoost', (booster) => {
   bot.channels.get('1234567890').send(`${booster} boosted the server!`)
   booster.addRole(booster.guild.roles.find(a => a.name === 'Nitro Booster'))
})
```

**Comment by appellation** [comment]
This information is available in the `messageCreate` event with the various types of Nitro boost. https://discord.js.org/#/docs/main/master/class/Message?scrollTo=type

**Comment by vladfrangu** [comment]
You can do what appellation suggested, or you should listen to the `guildMemberUpdate` event, as the newMember's [premiumSinceTimestamp](https://discord.js.org/#/docs/main/master/class/GuildMember?scrollTo=premiumSinceTimestamp) will be non-null once a member boosted and null if they didn't boost. That will also account for if the server has disabled the Nitro Boost System messages.

Also, next time, please fill in the template you deleted next time..
