### ISSUE TITLE
polish: mobile app notifications for embedded image buffer should show title/description

### ISSUE THREAD

**Issue by jamboj** [discordjs/discord.js#3365]
When using an image buffer like in code snippet below, desktop notifications display title/description as expected: 
![image](https://user-images.githubusercontent.com/36251521/60763456-24132c00-a043-11e9-8740-b40bc72096ba.png)

however mobile notifications display less than informative name of the proxy attachment instead:
![image](https://user-images.githubusercontent.com/36251521/60763460-38572900-a043-11e9-9c4e-82424421a45f.png)

I suspect this is something that can be addressed on the discord.js side by straightening out the way images are embedded from a buffer?

```
var img = await Jimp.read('https://i.imgur.com/wSTFkRM.png');
var imgStripe = await img.getBufferAsync(Jimp.AUTO);

const discordEmbed = new Discord.RichEmbed()
	.setTitle('item auction 1 → 0.5 🕓10 days')
	.setDescription('meaningful description')
	.attachFiles([{name: "imgStripe.png", attachment:imgStripeBuf}])
	.setImage('attachment://imgStripe.png');

discordChannel.send(discordEmbed);
```

**Comment by iCrawl** [comment]
That's not really how it works.

All we do is interact with the REST API and the WebSockets.
We have no choice in how Discord chooses (or not for that matter) display the messages in their apps/notifications.

**Comment by jamboj** [comment]
yeah sure I understand it might or might not be smth outside of discord.js control, still thought it was worth mentioning.. maybe that is smth in the *way* you interact with the API ;)

**Comment by Monbrey** [comment]
It definitely isnt

**Comment by jamboj** [comment]
ok :(
thanks for looking into it though!

**Comment by jamboj** [comment]
I guess I could've taken a look at the API myself before posting this.. I see it does say 'url or attachment only' for embed img obj
