### ISSUE TITLE
Hello people so i have this problem 

### ISSUE THREAD

**Issue by Feelingloved** [discordjs/discord.js#3366]
const discord = require("discord.js");

module.exports.run = async (bot, message, args) => {
    if(!message.member.hasPermission("ADMINISTRATOR")) return message.channel.send("This command is for staff only!");

    var splitser = "//";
    if (args[0] == null) {

        var useMessage = new discord.RichEmbed()
        .setTitle("announce a message!")
        .setColor("#c90a0a")
        .setDescription(`Make an announcement!`);
        return message.channel.send(useMessage);
    }
args = args.join(" ").split(splitser);

if(args[2] == undefined) args[2] = "#a07ae4";
if (args[3] == undefined) args[3] = "announcements";

var options = {
    title: args[0] ||"notification",
    message: args[1] || "",
    color: args[2].trim(),
    channel: args[3].trim()
    

}

var announceEmbed = new discord.RichEmbed()
.setTitle("Announcement")
.setColor("#c90a0a")
.setDescription(` \n\n ${options.title} \n\n ${options.message} \n`)
.setFooter(`${message.author.avatarURL} ${message.author.username}#${message.author.discriminator}`)
.setTimestamp();
message.delete();

var announcechannel = message.guild.channels.find(`name`, options.channel);
if(!announcechannel) return message.channel.send("unable to find announcement channel!");

announcechannel.send(announceEmbed);

}

module.exports.help = {
    name: "ann"
  }

And when i try to use it it does this i dont know how to fix it please help me screenshot: http://prntscr.com/obtsrb
I want it to show the author image like this one http://prntscr.com/obtxw9

**Comment by Feelingloved** [comment]
Please help me

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
