### ISSUE TITLE
GuildAuditLogsEntry: Inaccessible Target ID

### ISSUE THREAD

**Issue by ChrisTalman** [discordjs/discord.js#3372]
**Is your feature request related to a problem? Please describe.**
In Audit Log entries, `target_id` is usually specified. In `GuildAuditLogsEntry`, if `target_id` entity exists at runtime, `target` will expose that entity. However, if the entity does not exist, the value will be `undefined`. In that case, it would still be useful to access the `target_id`, but unfortunately `GuildAuditLogsEntry` does not seem to expose it.

I have been encountering this issue with `CHANNEL_OVERWRITE_*` action types. It may or may not affect other types.

I'm using discord.js@11.5.1.

**Describe the ideal solution**
The `target` value could be the `target_id` string if the entity does not exist. However, this would be a breaking change, as the value has hitherto always been an `object` or `undefined`.

Thus, the non-breaking solution could be to introduce a new property, `targetId`, always available and assigned the value of the `target_id` string.

I could create a pull request for this latter solution, if it were deemed to be appropriate.

**Describe alternatives you've considered**
None.

**Comment by ChrisTalman** [comment]
Looking into the source code, it seems as though this may have been fixed, [here](https://github.com/discordjs/discord.js/blob/master/src/structures/GuildAuditLogs.js#L369). However, it does not seem to have been released yet.

**Comment by vladfrangu** [comment]
The fix you linked is on the master branch, which is version 12.0 of discord.js. I don't think there's any ETA for its release just yet, but I'm sure a fix similar to it could be done in 11.5-dev!

**Comment by ChrisTalman** [comment]
Oh, nice. For the time being, I created a branch of a fork with the fix. It didn't cross my mind that it could be backported. Thanks for the help. 😄
