### ISSUE TITLE
voiceChannel.join() is not a function

### ISSUE THREAD

**Issue by Slasherss1** [discordjs/discord.js#3377]
**Please describe the problem you are having in as much detail as possible:**
When I execute the function by typing in the command I get an error in console:
`Underlying error: vc.join is not a function`

**Include a reproducible code sample here, if possible:**
```js
//msg = message
//vc = voiceChannel
exports.sconnect = function (msg, vc) {
  console.log(vc);
  vc.join()
  .then(connection => {
      global.connection = connection;
      msg.reply('Connected to voice')
    }).catch(function(e) {
      console.error(e);
      console.log('[' + Date.now() + ']', "Error during voice connection")
    });
}
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.6.0
- Operating system: Windows 10 V1903
- Priority this issue should have: Medium

- [ ] I have also tested the issue on latest master, commit hash:
- [x] I am in voice channel

**Comment by almostSouji** [comment]
Seeing that you log `vc` there, what does the log produce, you can write `// vc = voiceChannel` all you want it does not change the fact that it very likely is not one.
For future reference:

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by Slasherss1** [comment]
Log says:
`Collection {
  type: 'voice',
  deleted: false,
  id: '546242227404537872',
  name: 'General',
  position: 0,
  parentID: null,
  permissionOverwrites: Collection {},
  bitrate: 64,
  userLimit: 0,
  guild:
   Collection {
     members: Collection {},
     channels: Collection {},
     roles: Collection {},
     presences: Collection {},
     deleted: false,
     available: true,
     id: '546242227404537867',
     name: 'Slasherss\'s Test Server Beta',
     icon: null,
     splash: null,
     region: 'eu-central',
     memberCount: 9,
     large: false,
     features: [],
     applicationID: null,
     afkTimeout: 300,
     afkChannelID: null,
     systemChannelID: null,
     embedEnabled: undefined,
     verificationLevel: 0,
     explicitContentFilter: 0,
     mfaLevel: 0,
     joinedTimestamp: 1563027826075,
     defaultMessageNotifications: 'ALL',
     ownerID: '300275260517777410',
     _rawVoiceStates: Collection {},
     emojis: Collection {} },
  members: Collection {} }`

**Comment by almostSouji** [comment]
This is a [Collection ](https://discord.js.org/#/docs/main/stable/class/Collection)of (potentially multiple) channels, which itself does not have a `.join` method. Each `VoiceChannel` instance inside it does have one though.

For a solution based on your personal use case please join the discord server above and provide more of your code. The Github is only for bug reports, not usage assistance based around misconceptions.

**Comment by Slasherss1** [comment]
I have fetched voice channel using: `let vc = message.member.voiceChannel;`

###Off-topic:
I have asked about this yesterday on discord but got like no response covering my question.

**Comment by Slasherss1** [comment]
I have built my app on electron. File `Main.js`:
```js
const { app, BrowserWindow } = require('electron')
const Discord = require('discord.js');
const client = new Discord.Client();


exports.sconnect = function (msg, vc) {
  console.log(vc);
  vc.join()
  .then(connection => {
      global.connection = connection;
      msg.reply('Connected to voice')
    }).catch(function(e) {
      console.error(e);
      console.log('[' + Date.now() + ']', "Error during voice connection")
    });
}

function createWindow () {
  // Create the browser window.
  let win = new BrowserWindow({ width: 800, height: 600 })

  // and load the index.html of the app.
  win.loadFile('index.html')
}

app.on('ready', createWindow)

```
`app.js`:
```js
const Discord = require('discord.js');
const client = new Discord.Client();
client.login('token');

client.on('message', message => {
  if (!message.guild) return;
  if (message.content == "/select") {
    if (message.author.id == "300275260517777410") {
      global.channel = message.channel;
      message.reply("Selected.")
    }
  }
  if (message.content == "/sselect") {
    if (message.author.id == "300275260517777410") {
      global.channel = message.channel;
      message.delete()
    }
  }
  if (message.content == "/sound") {
    if (message.author.id == "300275260517777410") {
      let vc = message.member.voiceChannel;
      if (message.member.voiceChannel) {
        require('electron').remote.require('./main').sconnect(message, vc)
      }
    }
  }
})

function dbg(onoff) {
  global.dbgm = onoff;
}

function dobrze() {
  if (connection) {
    const dispatcher = connection.playFile('./dobrze.mp3')
  }
  channel.send("Dobrze! http://i.imgur.com/jaRkZnQ.gif")
}

function tak() {
  const embed = new Discord.RichEmbed().setColor('GREEN').setTitle('Poprawna odpowiedź.')
  channel.send(embed)
}

function send() {
  const popodp = document.getElementById('popodp')
  const szan = document.getElementById('szan')
  const popodpv = popodp.value.split(' ')
  if (popodpv.includes('{1}')) {
    popodpv[popodpv.indexOf('{1}')] = szan.value
  }
  if (popodpv.includes('{anie}')) {
    popodpv[popodpv.indexOf('{anie}')] = "Albo nie"
    if (connection) {
      const dispatcher = connection.playFile('./anie.mp3')
    }
  }
  popodpv1 = popodpv.join(" ")
  const embed = new Discord.RichEmbed().setColor('BLUE').setTitle('Wiadomość od operatora:').setDescription(popodpv1)
  channel.send(embed)
}

function nie() {
  const popodp = document.getElementById('popodp')
  const szan = document.getElementById('szan')
  const embed = new Discord.RichEmbed().setColor('RED').setTitle('Niepoprawna odpowiedź.').setDescription(popodp.value).setFooter("Masz jeszcze " + szan.value + " szanse.")
  channel.send(embed)
}
```

**Comment by iCrawl** [comment]
That's now how you communicate with your back-end and your front-end in electron.

You should brush up on that first, also creating 2 instances of the Discord.JS client isn't gonna make things better, you aren't sharing a cache this way. Apart from that... assigning to a global variable in hopes to grab a channel this way is not good either.

What you want to do is import your app.js into your main.js and handle things from there. And communicate with the front-end via the IPCRenderer.
