### ISSUE TITLE
Add an event for when someone comes online in a server

### ISSUE THREAD

**Issue by lexmark66** [discordjs/discord.js#3382]
Add an event feature for when someone goes from online to offline status (and vice versa), you can make the bot do something. (This would be useful for a notification bot or something where when someone comes online the bot says {User} ‘is online!’)

**Comment by jpbberry** [comment]
You can already use the events given to you to do this. It's not djs' responsibility to make this for you, and this event isn't coming from the Discord gateway so it's not the wrappers responsibility to make it for you.

**Comment by lexmark66** [comment]
What events?

**Comment by almostSouji** [comment]
<https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-presenceUpdate>
Emits with the GuildMember prior to and after the update. (emits with the Presence on master - v12)

Sidenote: will emit for each server the bot shares with this user.

**Comment by lexmark66** [comment]
Can I do this for anyone on the server?

**Comment by almostSouji** [comment]
The event emits for every GuildMember your bot has contact to once per guild the bot shares with them whenever the users presence changes (you do need to filter out the events that do not include a status change, as other presence updates are also possible)

If you need more help with discord.js usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
