### ISSUE TITLE
fetchClientValue gives an error as if child is null.

### ISSUE THREAD

**Issue by jpbberry** [discordjs/discord.js#3384]
**Please describe the problem you are having in as much detail as possible:**
Whenever running Shard#fetchClientValue it throws an error and according to the line it came from, is treating this.process || this.worker as null.

Error:
```
(node:4716) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of null
    at Promise (C:\Workspace\node_modules\discord.js\src\sharding\Shard.js:209:13)
    at new Promise (<anonymous>)
    at Shard.fetchClientValue (C:\Workspace\node_modules\discord.js\src\sharding\Shard.js:200:21)
    at ShardingManager.fetchClientValues (C:\Workspace\node_modules\discord.js\src\sharding\ShardingManager.js:240:67)
    at Shard._handleMessage (C:\Workspace\node_modules\discord.js\src\sharding\Shard.js:295:22)
    at ChildProcess.emit (events.js:193:13)
    at emit (internal/child_process.js:848:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:4716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 153)
```
[Jump to line where error came from](https://github.com/discordjs/discord.js/blob/master/src/sharding/Shard.js#L209)

**Include a reproducible code sample here, if possible:**
```js
client.shard.fetchClientValue("literally anything");
```

**Further details:**
- discord.js version: v12 
- Node.js version: v11.15.0
- Operating system: Windows 10 and Windows Server 2016
- Priority this issue should have – please be realistic and elaborate if possible:
It's not, SUPER high, because you can just use broadcastEval, but it's a real inconvenience. I'd say moderate

- [x] I have also tested the issue on latest master, commit hash: 651ff81bd522c03b5c9724a3a8c14eeb88dcd6b9

**Comment by jpbberry** [comment]
Issues seems to have been fixed. Not sure why because there were no changes but 🆗

**Comment by Noxillio** [comment]
I'm having the same problem. Tried updating discord.js, but no dice.

**Comment by ati0ns** [comment]
Same problem.
When I try to log a shard it works but not when I use a functions on it.
So I guess that the shard isn't loaded.

**Comment by ati0ns** [comment]
I found that child is null when I use shardingManager.spawn("auto") but it works when I use an integrer.

**Comment by nodbloxdev** [comment]
` const promises = [
	client.shard.fetchClientValues('guilds.cache.size'),
	client.shard.broadcastEval('this.guilds.cache.reduce((prev, guild) => prev + guild.memberCount, 0)'),
];

Promise.all(promises)
	.then(results => {
		const totalGuilds = results[0].reduce((prev, guildCount) => prev + guildCount, 0);
		const totalMembers = results[1].reduce((prev, memberCount) => prev + memberCount, 0);
    return;
	})
	.catch(console.error);`
Doesn't work :(

**Comment by Fyko** [comment]
@nodbloxdev cannot reproduce on:
*  Discord.js commit https://github.com/discordjs/discord.js/commit/1330e2d246cf4e1b9e7f13a5f941ff086117a3fc
* Node.js version v12.16.1

dare I say because you're returning undefined in your Promise.all then block?
