### ISSUE TITLE
Update ffmpeg-binaries to ffmpeg or ffmpeg-static

### ISSUE THREAD

**Issue by xXQuantumSoulXx** [discordjs/discord.js#3391]
More of a Heroku hosting thing, ffmpeg-binaries is deprecated and doesn't work in Heroku. This is a problem with music bots as when they join the voice channel, they leave and declare the song has ended. The npm page suggests using ffmpeg or ffmpeg-static. However, ffmpeg-binaries does work elsewhere like windows

- discord.js version: 11.5.1
- Node.js version: LTS
- Operating system: Unknown
- Priority this issue should have – Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Seia-Soto** [comment]
+ I think this need to be second option because of stability.

Already, there was many voice issues and many library method changes. I think adding ffmpeg as additional option to handle ffmpeg will be better.

**Comment by amishshah** [comment]
This isn't a bug, ffmpeg-binaries is deprecated and shouldn't be used at all, use ffmpeg-static as a replacement as advised.

**Comment by xXQuantumSoulXx** [comment]
> This isn't a bug, ffmpeg-binaries is deprecated and shouldn't be used at all, use ffmpeg-static as a replacement as advised.

I used it, it doesnt work

**Comment by EBruchet** [comment]
Hi @xXQuantumSoulXx, have you tried installing FFmpeg itself using your Heroku CLI?

**Comment by xXQuantumSoulXx** [comment]
I've decided to not use ffmpeg, it was making things complicated and a music feature was unnecessary.

**Comment by atoasty** [comment]
To make ffmpeg binaries work on Heroku, simply just create repistory with .gitignore as Node, it will just ignore whole node_modules. Move your code into that new repistory.

After that just recreate an application on Heroku and move your new repistory into that new application.

Problem shall be solved.
