### ISSUE TITLE
send private message to a mentionned user ?

### ISSUE THREAD

**Issue by jbraczyk** [discordjs/discord.js#3392]
**HI!**

**Describe the ideal solution**
i just want to send a private message to a mentionned user, exemples :
if i do that : ` *command @MentionnedUser` my bot have to send à pm to @MentionnedUser

i know how to send a private message but i dont know how to select the @MentionnedUser in my command

Excuse my english guys :(:( (and have a good day)

**Comment by tipakA** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
