### ISSUE TITLE
Add "content" parameter to MessageOptions

### ISSUE THREAD

**Issue by NKN1396** [discordjs/discord.js#3400]
Currently, messages containing both regular text and an embed have to be passed two parameters like this:
```javascript
let content = "lorem ipsum"
let embed = {"embed": { "title": "dolor", "description": "sit amet"}}
TextChannel.send(content, embed)
```

Allowing a content parameter would allow messages containing both, regular text and an embed, to be sent with only a single object passed as a parameter. Example:
```javascript
let payload= {"content": "lorem ipsum", "embed": { "title": "dolor", "description": "sit amet"}}
TextChannel.send(payload)
```

**Comment by kyranet** [comment]
First of all, please don't delete the template!

And also, do I assume this is for 11.x? Since this feature is already available in master for months:

![image](https://user-images.githubusercontent.com/24852502/61780191-5cb45300-ae02-11e9-9db4-7e53d38c782b.png)

**Comment by NKN1396** [comment]
I thought I had attempted this in v12 today.

Turns out the bot I was using for the eval command was still running v11.

My fault, sorry!
