### ISSUE TITLE
Trying to overwrite users property

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#3403]
**Please describe the problem you are having in as much detail as possible:**
If you attempt to overwrite the client's user store then the client will throw errors, the users property should not be allowed to be overwritten.
![image](https://user-images.githubusercontent.com/11788894/61849440-51533d00-ae7f-11e9-8990-31ceb8c2028f.png)

**Include a reproducible code sample here, if possible:**
```js
this.client.users = null; // null can be anything
```

**Further details:**
- discord.js version: master v12
- Node.js version: any
- Operating system: any
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash: `651ff81bd522c03b5c9724a3a8c14eeb88dcd6b9`

**Comment by Monbrey** [comment]
This is kinda universally true for all of its properties. I see people doing this by mistake all the time when they think they're adding a custom property, but actually replacing one that already exists.

**Comment by Monbrey** [comment]
This is kinda universally true for all of its properties. I see people doing this by mistake all the time when they think they're adding a custom property, but actually replacing one that already exists.

**Comment by amishshah** [comment]
See @Monbrey's response
