### ISSUE TITLE
GuildMemberStore.fetch() will return an empty Collection if all members are cached, and a query or limit option is provided

### ISSUE THREAD

**Issue by Monbrey** [discordjs/discord.js#3414]
**Please describe the problem you are having in as much detail as possible:**
Credit to onerisK for raising this issue.

[GuildMemberStore._fetchMany](https://github.com/discordjs/discord.js/blob/master/src/stores/GuildMemberStore.js#L195) is the cause of this bug.
```js
if (this.guild.memberCount === this.size) {
    resolve(query || limit ? new Collection() : this);
    return;
}
```
The ternary in `resolve` checks if `query` or `limit` are truthy, then returns an empty Collection() if they are. Pretty sure it shouldn't do that.

I'm not going to PR this because it does some stuff with sharding I don't understand.

**Include a reproducible code sample here, if possible:**
```js
// Make sure the cache is full
await <GuildMemberStore>.fetch()
// Check that the condition will be met
console.log(<GuildMemberStore>.size === <Guild>.memberCount) // Expected: true
// Perform a query fetch
console.log(await <GuildMemberStore>.fetch({ query: "Monbrey" })) // Expected: Collection [Map] {}
// Clear the cache
<GuildMemberStore>.clear()
// Perform a query fetch
console.log(await <GuildMemberStore>.fetch({ query: "Monbrey" })) // Expected: GuildMember {}
```

**Further details:**
- discord.js version: master
- Node.js version: v12.5.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: medium?

- [x] I have also tested the issue on latest master, commit hash: e562564123912f09725a6e03ecf4ba44d85de35a

**Comment by amishshah** [comment]
Fixed in https://github.com/discordjs/discord.js/commit/cc488a8bd3dc39354967d132e34f63ff51e92b79
