### ISSUE TITLE
TypeError when calling GuildChannel.delete as argument of setTimeout.

### ISSUE THREAD

**Issue by Dionysusnu** [discordjs/discord.js#3416]
**Please describe the problem you are having in as much detail as possible:**
TypeError when calling GuildChannel.delete as argument of setTimeout.
Presumably caused by wrong `this` usage.

**Include a reproducible code sample here, if possible:**
Throws error:
```js
const newchannel = await message.channel.clone(undefined, true, true, 'purged all');
message.channel.send(`Please move to ${newchannel}, this channel will be deleted`);
message.client.setTimeout(message.channel.delete, 3000, ['Purged']);
```
Workaround, doesn't error: 
```js

const newchannel = await message.channel.clone(undefined, true, true, 'purged all');
message.channel.send(`Please move to ${newchannel}, this channel will be deleted`);
message.client.setTimeout(() => message.channel.delete('Purged'), 3000);

```
Error, presumably caused by referencing the function in the `setTimeout`:
```js
/app/node_modules/discord.js/src/structures/GuildChannel.js:440
     return this.client.rest.methods.deleteChannel(this, reason);
                        ^
TypeError: Cannot read property 'rest' of undefined
     at Timeout.delete [as _onTimeout] (/app/node_modules/discord.js/src/structures/GuildChannel.js:440:24)
     at ontimeout (timers.js:438:13)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)
```

**Further details:**
- discord.js version: 11.5.1, upgraded after being told to do so [here](https://github.com/discordjs/discord.js/issues/2944)
- Node.js version: v10.16.0
- Operating system: heroku cloud
- Priority: medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dionysusnu** [comment]
Just noticed `Client.setTimeout()` is better than `setTimeout()`, but I've tested it and the error still occurs.

**Comment by Monbrey** [comment]
Not sure there's anything the library can do about this because the `this` scope issue is caused by setTimeout, which gets called in the global scope, which is a core JavaScript "feature"

Arrow functions are the correct way to fix this particular JavaScript issue.

**Comment by appellation** [comment]
This is expected behavior. You can mitigate it as you did by using an arrow function or you can also bind the function to the correct scope. Personally, I find arrow functions to be much cleaner but that's more of a style choice. Either way, this is a language issue not a library issue.
