### ISSUE TITLE
Can't leave voice channel if rebooted

### ISSUE THREAD

**Issue by WilsontheWolf** [discordjs/discord.js#3417]
Failure to leave a vc when rebooted. Code works fine if the bot isn't rebooted. 

![image](https://cdn.discordapp.com/attachments/260400743020756993/606667045165072404/Magic.gif)
```js

let vc = message.guild.members.get(client.user.id).voiceChannel
  if(!vc){
    message.channel.send('I need to be in a voice channel to leave')}
  else{
    message.channel.send(`Leaving \`${vc.name}\``)
    vc.leave()}

```

**Further details:**
- discord.js version:11.5.0
- Node.js version:v9.11.2
- Operating system: linux ([glitch](https://glitch.com))
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Fyk0** [comment]
Can reproduce on the [lastest master hash](https://github.com/discordjs/discord.js/tree/5af8cb8e6e7591e81f758a8b0f6748db7c2f12f1).

In your `reboot` command, please do [`Client#destroy`](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=destroy) before you `process.exit()`. Doing so will terminate all voice connections and safely destroy the websocket.

**Comment by amishshah** [comment]
This isn't a bug, if you reboot your bot without destroying it first or leaving any voice channels (as @Fyk0 said) then Discord will not know that your bot has been disconnected and assume it is still in the voice channel for about 40 seconds. The only way to get around this is to destroy your client before rebooting, or by leaving the channel before rebooting.

**Comment by WilsontheWolf** [comment]
oh will do
