### ISSUE TITLE
Kicking bot from Voice Channel doesn't allow it to rejoin

### ISSUE THREAD

**Issue by PLASMAchicken** [discordjs/discord.js#3418]
**Please describe the problem you are having in as much detail as possible:**
When you let your Bot join a Voice Channel and somebody uses the `Disconnect` ![image](https://cdn.discordapp.com/attachments/584434837562195968/606758529407385600/unknown.png) Button on the Bot, he will Disconnect but after evaling `message.member.voice.channel.join()` again it will not come back.

**Include a reproducible code sample here, if possible:**
```js
// Join with your Bot into a Voice Channel eg:
message.member.voice.channel.join()
// Then use the Voice Disconnect Button, notice how the Bot leaves but after doing
message.member.voice.channel.join()
// again he will not rejoin

```

**Further details:**
- discord.js version: discord.js@12.0.0-dev  (github:discordjs/discord.js#5af8cb8e6e7591e81f758a8b0f6748db7c2f12f1)
- Node.js version: v12.2.0
- Operating system: Windows x64 Pro
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [X] I have also tested the issue on latest master, commit hash: (github:discordjs/discord.js#5af8cb8e6e7591e81f758a8b0f6748db7c2f12f1)

**Comment by Fyk0** [comment]
Can reproduce.

**Comment by amishshah** [comment]
https://github.com/discordjs/discord.js/commit/c6e8fccbf07a2ba2ac80d7e13f967eaa07c881f8 should fix your issue!

**Comment by eybbus** [comment]
has this fix been merged into the master branch? I'm still experiencing this problem.

**Comment by almostSouji** [comment]
Yes, the commit mentioned by amish above was commited into master on August 17th
Please check your lockfile and make sure you are on this or a later commit.
