### ISSUE TITLE
Bot gets crashed when delete a voice channel

### ISSUE THREAD

**Issue by GameofTurkey** [discordjs/discord.js#3423]
Hello, I found a bug. I don't think it will make a big problem but I just want to report. When I delete a channel while I am in a channel and bot listening this the bot crashes. I am making a bot to decrease the channel count. If you join a channel a channel will be created and you will be redirected to it. This code is not finished.
Code:
```js
const Discord = require("discord.js");
const client = new Discord.Client();
const fs = require("fs")
const discord_token = process.env.TOKEN;
const prefix = process.env.PREFIX;

client.on("ready", () => {
  console.log("Connected!");
});

//FUNCTIONS
var c1 = 0;
var c2 = 1;
var d = 0;

client.on('voiceStateUpdate', (oldMember, newMember) => {
  let newUserChannel = newMember.voiceChannel
  let oldUserChannel = oldMember.voiceChannel

  if(oldUserChannel === undefined && newUserChannel !== undefined) {
    const pubgS = oldMember.guild.channels.find('id', '606887490879619091')
    if (newUserChannel == pubgS) {
      oldMember.guild.createChannel("PUBG Squad #"+c1+c2, "voice");
      const pubgSN = oldMember.guild.channels.find('name', 'PUBG Squad #'+c1+c2)
      function createPUBG() {
        setInterval(function(){ oldMember.setVoiceChannel(pubgSN); }, 2500);
      }
      c2=c2+1;
      if (c2>=10) {c1=c1+1; c2=0;}
      createPUBG()
    }

  } else if(newUserChannel === undefined){
    console.log('User left')
  }
})
//END

client.login(discord_token);
```

**Further details:**
- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by GameofTurkey** [comment]
NodeJS: Latest
Discord.js: Latest
Operating System: Debian 8 LTS

**Comment by iCrawl** [comment]
"Latest" is a very bad metric here.

Also you did not post what error you are getting, "crash" alone won't tell us much.

**Comment by GameofTurkey** [comment]
I think that was just a code error. Sorry for making you busy.
