### ISSUE TITLE
Webhook#send errors if channel doesn't exist in Client#channels

### ISSUE THREAD

**Issue by ShayBox** [discordjs/discord.js#3424]
**Please describe the problem you are having in as much detail as possible:**
If a webhook sends a message to a channel that's not in the clients channel store it will error:
```
(node:10016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'messages' of undefined
    at client.api.webhooks.post.then.d (/home/shaybox/Documents/Javascript/Shays-Bots/Hex/node_modules/discord.js/src/structures/Webhook.js:150:52)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Include a reproducible code sample here, if possible:**
```js
const webhook = await this.client.fetchWebhook(DISCORD_WEBHOOK_ID, DISCORD_WEBHOOK_TOKEN);
await webhook.send('Content');
```

**Further details:**
- discord.js version: master
- Node.js version: v11.15.0
- Operating system: Linux
- Priority: Low - Send still succeeds, it just fails to cache and logs an error.

- [x] I have also tested the issue on latest master, commit hash: d14db521585f2b6b1a6c50d3a9acecc73bea25a3

**Comment by amishshah** [comment]
Why would the channel not be in the cache?
