### ISSUE TITLE
RangeError: Color must be within the range

### ISSUE THREAD

**Issue by leRisen** [discordjs/discord.js#3427]
**Please describe the problem you are having in as much detail as possible:**
My color `120853340` is out of range, this behavior normal or not? If not, why not expand the range?

**Include a reproducible code sample here, if possible:**
```js
const { Util } = require('discord.js')
Util.resolveColor(120853340) // throws RangeError
```

**Further details:**
- discord.js version: master
- Node.js version: 10.16.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: LOW

- [x] I have also tested the issue on latest master, commit hash: 9e76f233143f2f0fe0ff9a9e645f32dc8db44b26

**Comment by tipakA** [comment]
This is expected behavior.
`RangeError [COLOR_RANGE]: Color must be within the range 0 - 16777215 (0xFFFFFF).`
This is because this is valid RGB color space.

**Comment by leRisen** [comment]
> 
> 
> This is expected behavior.
> `RangeError [COLOR_RANGE]: Color must be within the range 0 - 16777215 (0xFFFFFF).`
> This is because this is valid RGB color space.

Ok, received color from the site `https://embedbuilder.nadekobot.me` is considered not valid. But it displays correctly there... 😢
