### ISSUE TITLE
.premium property for RoleStore

### ISSUE THREAD

**Issue by ManuelFte** [discordjs/discord.js#3435]
**Is your feature request related to a problem? Please describe.**
There's currently no way to automatically find the Nitro Booster (premium) role of a given guild.

**Describe the ideal solution**
A `.premium` property for RoleStore that returns the Nitro Booster role of the guild would be very helpful.

**Describe alternatives you've considered**
As of now, I've found no reliable alternative besides including a setting in the bot for the user to introduce the premium role manually.

**Comment by SpaceEEC** [comment]
I don't think there is a reliably way to get the nitro booster / premium role of a guild.

There is no field in the [role structure] indicating what kind of managed role it is. (Only that it is managed)
Neither is there anything in the [guild structure].

If Discord adds some indicator or I overlooked a solution for this, it shouldn't be an issue to implement this.

[role structure]:https://discordapp.com/developers/docs/topics/permissions#role-object-role-structure
[guild structure]:https://discordapp.com/developers/docs/resources/guild#guild-object-guild-structure

**Comment by ManuelFte** [comment]
The closest I've come to accomplish it is with a function like this to find a managed role that only members with `.premiumSince` have:

```js
const getPremiumRole = guild => {
  const lists = {
    premium: [],
    no_premium: []
  }

  guild.members.forEach(member => {
    const rolesIDs = member.roles.filter(role => role.managed).map(role => role.id)
    const cat = member.premiumSince ? 'premium' : 'no_premium'

    lists[cat] = [...new Set([...lists[cat], ...rolesIDs])]
  })

  const premiumRoleID = lists['premium'].find(role => !lists['no_premium'].includes(role))

  return guild.roles.get(premiumRoleID)
}
```


But this fails if the guild happens to have another managed role exclusive for Nitro Boosters (although this'd be an extremely rare case).

**Comment by iCrawl** [comment]
> But this is slow and fails if the guild happens to have another managed role exclusive for Nitro Boosters (although this'd be an extremely rare case).

Aren't all invited bots that have fixed permissions (if you don't remove them before you let them join) managed roles?
I don't think thats very rare at all.
