### ISSUE TITLE
Termination of my community involvement

### ISSUE THREAD

**Issue by appellation** [discordjs/discord.js#3440]
While I was on vacation last week, Discord suspended my account citing concerns that I was under the age of 13 and therefore breaking their Terms of Service. They gave me the steps to appeal that decision, but I will not be doing so; I do not want to submit a copy of my photo/ID to Discord for their convenience.

While I understand that Discord needs to protect themselves against underage users, I'm disappointed that they clearly did not do a holistic evaluation of my account. For those of you who have or will joke about being underage or otherwise breaking Discord ToS, consider yourselves warned that they will not take those jokes in context.

I apologize to the Discord.js community for such an abrupt departure, but I will still make an effort to be involved on GitHub as best I can. I am always available via email if anyone needs to reach out to me privately.

Edit: clarification of what Discord requested.

**Comment by therightest** [comment]
make a new discord account 🤷‍♂

**Comment by appellation** [comment]
I don't believe that breaking ToS further will help my case.

**Comment by therightest** [comment]
we still love you bb

**Comment by therightest** [comment]
come back

**Comment by tipakA** [comment]
Can't you use photo you have on github? that gives as much proof as sending any other one, as long as they don't want it in specific conditions like your tag and date

**Comment by appellation** [comment]
![image](https://user-images.githubusercontent.com/8494131/63312070-18a75780-c2b5-11e9-86da-7d71ee511a61.png)

Here is the relevant text of the email they provided to me.

**Comment by therightest** [comment]
just make a new discord acc bb

**Comment by Fyk0** [comment]
Sad to hear about this on such short notice. Thank you appell for all you've done to support and contribute to this community.

**Comment by Fyk0** [comment]
![erm](https://user-images.githubusercontent.com/45381083/63312388-a6d40b80-c2be-11e9-97de-51b033a038a6.png)

**Comment by ShayBox** [comment]
:sob: appel

**Comment by DiscoTiger** [comment]
Bans with no evidence monkas. Hopefully discord changes this practice in the future, though I can understand as a business how important it is to protect minors. Discord should just have more resources than this.

**Comment by appellation** [comment]
To be clear, they did not *ban* my account. It is disabled pending the submission of evidence which I am not willing to provide.

**Comment by tipakA** [comment]
So it will "naturally" expire after a month or whatever that period is?
Or it will be hanging there for indefinite time

**Comment by AndrewGitt** [comment]
Sad to see you gone appell, you were the best appell a guy could ask for.

**Comment by appellation** [comment]
I'm unsure what will happen, but at this point it doesn't really matter and they can do whatever they want with it.

**Comment by jgoralcz** [comment]
wtf

**Comment by onerisc** [comment]
Unbelievable lmao

**Comment by jgoralcz** [comment]
when we playing overwatch

**Comment by didinele** [comment]
what. the. fuck.

Does this shit actually still happen? I swear to god, this has been on reddit for months now. They can't just take messages that say "i'm 12" and consider them viable proof, this is goddamn unacceptable.

**Comment by TrueBoxGuy** [comment]
Bye appel 😢

**Comment by MrJacz** [comment]
@didinele I mean they can, they're a private company but still, you're right and from a community stand point you should not be getting your account flagged for stupid things like this. Why would anyone want to stay on a platform that will ban them for saying they're 11 as a joke? thats just stupid. I hope discord fixes this issue and implements better systems for ensuring their terms of service and guidelines. End of the day, they can do whatever they want but if they want to stay the best they need to fix there shit. Appel, while we might not get along you're a very intelligent person and I hope you succeed whereever you end up in the future

**Comment by didinele** [comment]
Im about to rant about this shit on Reddit, hope y'all got my back with some upvotes, I wanna make it on the frontpage and get some official response, and not just for appel, but for anyone who was falsely flagged like this.

**Comment by ShayBox** [comment]
I would agree but ultimately if discord gets any report that someone is under age they have to get legal ID to verify, it's just how the legal system works, just be glad websites don't require an I'd to sign up, they're allowed to take the users word for their age unless reported otherwise.

**Comment by victionn** [comment]
mad, rip appell - how come you dont just make a new account though

**Comment by didinele** [comment]
me n appel might've had a neutral relationship, but he's a amartass, and I admire his work, on spectacles, lavalibs etc.

Stream more often bud, and you will be missed, maybe one day, you shall return

**Comment by GamesProSeif** [comment]
Ohnoo Appel ;-; the only one who could spell my name correctly on stream. Best mod ever. Hardworking, and so much to say.

Is there anything we could to help in removal of the termination?
Like talking to them, reporting or anything?

Hope you come back soon.

**Comment by Fyk0** [comment]
> They gave me the steps to appeal that decision, > but I will not be doing so; I do not want to submit > a copy of my photo/ID to Discord for their convenience.

**Comment by GamesProSeif** [comment]
No I meant that *WE* could do.
They shouldn't ask for such personal information wth. And under what proof do they count him as underage?

**Comment by ShayBox** [comment]
There is no proof, that's the problem, they assume everyone is of age until someone's age comes into question, then they have to get an id to prove your age, it's just how most websites work, it's to avoid having to comply with coppa, discord doesn't want the support tickets that come from the underage rule, but it's a requirement, and this is too, there's nothing discord is doing wrong, appel doesn't want to give discord id and that's perfectly fine.

**Comment by JjTheHusky** [comment]
I was interested in this thread, then I saw this on the server, saying you stated on multiple occasions that you were 12 https://i.imgur.com/mri052H.jpg 

Looking at the surrounding messages, I'm unable to see any 'jokes' about the age, so I don't think this is a context issue, but that's besides the point. Discord's Trust & Safety has to step in because of Legal reasons, and they can be severely fined for not taking action.

You are given the option to prove that you are of age, but declined, so I'm unsure what the point of this is. You can create another account if you want instead of that method. 
Just my few cents on this.

**Comment by nomsi** [comment]
@JjTheHusky We've been all saying it since 2015-2017. The entire staff would be deactivated at this point if they felt set to do so. You weren't here long enough to understand the context of the joke, so to explain it I will let you know I can't, because I am after all, 12.

**Comment by maqtiah** [comment]
@JjTheHusky "I'm 12 btw" is such a popular meme and it's obviously a joke. It's also quite funny considering the Discord team often praises games and memes on their social media, they should know that as well.

Regardless, they're still a business and need to enforce some rules so I get where they are coming from. This is just really petty.

**Comment by GamesProSeif** [comment]
My opinion is, if you have such a rule in the ToS. You should somehow confirm first that you are above 13 when making an account. But dude, don't terminate an account mid usage.

**Comment by JjTheHusky** [comment]
@maqtiah I get it's generally a joke, but unfortunately this is one where it's a legal issue. I believe they call it COPPA (Children's online privacy protection act).

**Comment by JjTheHusky** [comment]
@GamesProSeif Yes, it's the button you tick when signing up for a service, generally named "I agree to the Terms of Service". They reserve the right to suspend or terminate your account if they find you to be underaged.

**Comment by Gawdl3y** [comment]
As pointed out in other places, COPPA doesn't place a legal obligation on companies to investigate underage cases unless their parent contacts them. Additionally, it permits using credit card transactions as a verification method for being over 13, regardless of the "kid stealing their parents' credit card" situation. Discord is overreaching dramatically in both how they react to these cases and what they require for verification of age.

**Comment by amishshah** [comment]
Updating this thread so everyone can see. Less than a week after @appellation's account was incorrectly disabled, Discord have now deleted his account. This is very disappointing, especially given that myself and other library developers had made Discord staff aware of this issue.
