### ISSUE TITLE
Not receiving all GUILD_CREATE events when using zstd compression

### ISSUE THREAD

**Issue by Mstrodl** [discordjs/discord.js#3452]
**Please describe the problem you are having in as much detail as possible:**
On startup the client doesn't appear to handle all the `GUILD_CREATE` events when using zstd compression, it stalls with about 3% of guilds never becoming available.

**Include a reproducible code sample here, if possible:**
```js
const client = new (require("discord.js").Client)();
client.on("debug", dbg => console.log(dbg));
client.login("your token here");
```
* output: https://mystb.in/yahipaqamu.js
* demo environment: https://repl.it/@Mstrodl/djs-demo

**Further details:**
- discord.js version: Latest master: 2a3fb705d0296266e3cd7e9976a47459c69653a9
- Node.js version: 12.9.0
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible: Somewhat high as the README recommends that users install `zucc` for the fastest packet inflation. This has the potential to catch a lot of people... Perhaps in the meantime we should remove that line from the README?

- [x] I have also tested the issue on latest master, commit hash: 2a3fb705d0296266e3cd7e9976a47459c69653a9

**Comment by vladfrangu** [comment]
This is a known issue with zucc, we recommend you switch to zlib-sync for the time being.

**Comment by iCrawl** [comment]
Zucc is not being used anymore.
