### ISSUE TITLE
Webpack master.min.js: TypeError: c.DecompressStream is not a constructor

### ISSUE THREAD

**Issue by AseCoder** [discordjs/discord.js#3453]
**Please describe the problem you are having in as much detail as possible:**
I downloaded `master.min.js` from `discord.js/webpack`, used it in an Electron application and got the error:
```markdown
TypeError: c.DecompressStream is not a constructor
    at master.min.js:1
    at new Promise (<anonymous>)
    at WebSocketShard.connect (master.min.js:1)
    at WebSocketManager.createShards (master.min.js:1)
    at WebSocketManager.connect (master.min.js:1)
    at async Client.login (master.min.js:1)
```

**Include a reproducible code sample here, if possible:**
html:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <script src="./master.min.js"></script>
    <script src="./app.js"></script>
  </head>
</html>
```
app.js:
```js
const client = new Discord.Client();
client.login('the token');
```

**Further details:**
- discord.js version: `webpack/master.min.js`
- Node.js version: I am not using Node.js
- Electron version: 6.0.7
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: High, the current `webpack/master.min.js` is unusable and emits an error when I try to do `client.login('the token')`

- [x] I have also tested the issue on latest master, commit hash: 89d9b0f

**Comment by MrJacz** [comment]
If you're using electron why dont you just use the discord.js module and not the webpack build?
