### ISSUE TITLE
presenceUpdate fires twice per change

### ISSUE THREAD

**Issue by sjd4322** [discordjs/discord.js#3459]
**Please describe the problem you are having in as much detail as possible:**
The presenceUpdate event is firing more than once every time it is fired, with the exact same oldUser and newUser in each instance. For more detail, I've started a StackOverflow question about it https://stackoverflow.com/questions/57794090/exclude-mobile-updates-from-presenceupdate-event/57795438?noredirect=1#comment102026921_57795438

**Include a reproducible code sample here, if possible:**
```
client.on("presenceUpdate", (oldUser, newUser) => {
    //Exclude title changes and typing
    if(oldUser.presence.game != null && oldUser.presence.game.streaming 
        && oldUser.presence.clientStatus !== newUser.presence.clientStatus) return;
    
    if(oldUser.displayName === "Test" && newUser.presence != null){
        if(newUser.presence.game != null && newUser.presence.game.streaming){
            client.channels.get("serverid").send("@everyone Test has started streaming!");               
        }
    }
});
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.7.0
- Operating system: win10 x64
- Priority this issue should have – please be realistic and elaborate if possible: 

- [x ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
I've tested this on both stable and master - Discord is emitting two PRESENCE_UPDATE events for each device, as per the discussion in the StackOverflow article. You can watch this by listening to the raw event and checking `data.t`.

discord.js is just passing those events on to the handler

**Comment by sjd4322** [comment]
I suppose I don't understand then. if that were true, why doesn't the suggested answer work as intended?

**Comment by Monbrey** [comment]
The suggested answer implies that the client status is changing, which is isn't. You'd get one PRESENCE_UPDATE where `clientStatus === "mobile"` on both, and one PRESENCE_UPDATE where `clientStatus === "desktop"` on both.

If you want to listen specifically for streaming presences, I'd add a check for `desktop` and ignore the others.

**Comment by sjd4322** [comment]
`    if(oldUser.presence.game != null && oldUser.presence.game.streaming 
        && newUser.presence.clientStatus !== "desktop"
        && oldUser.presence.clientStatus !== "desktop") return;`

So I ran the code again, and attempted to trigger the event. In both cases, the clientStatus was listed with a desktop property as "online". No mobile one.

**Comment by sjd4322** [comment]
For clarity, I mean that both newUser and oldUser had clientStatus as desktop, both times.

**Comment by Monbrey** [comment]
This was my mistake sorry - clientStatus is an object of statuses per-device, eg
```js
OLD: { mobile: 'idle', desktop: 'online' }
NEW { mobile: 'online', desktop: 'online' }
```
But it will still fire per-device. It was also pointed out to me that `presenceUpdate` actually emits GuildMember objects, not User objects, so you should also expect to receive an event from Discord per-guild that a user shares with your bot.

Either way, a lot of duplication is expected in the events received from Discord.

**Comment by sjd4322** [comment]
> But it will still fire per-device. It was also pointed out to me that presenceUpdate actually emits GuildMember objects, not User objects, so you should also expect to receive an event from Discord per-guild that a user shares with your bot.

!!! Thank you, this actually is the problem. I'm using the bot for more than 1 server and it's posting because it's being hit there twice. I think mobile will actually be excluded, but this was the piece I was missing. I will close the issue, thank you for your patience :)
