### ISSUE TITLE
Embed for Bot not working

### ISSUE THREAD

**Issue by xspo-oky** [discordjs/discord.js#3460]
When I start my bot and then open it and then type .han, it does nothing

`
if (msg.content === '.han') {
    const hanHelpEmbed = new Discord.RichEmbed()
      .setTitle('Han Help:')
      .setDescription('{1} - Member Commands \n {2} - Moderator \n {3} - Admin Commands')
      .setColor('#000001')
    msg.channel.send(hanHelpEmbed);
  }
`

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
