### ISSUE TITLE
message.guild.roles.find is null

### ISSUE THREAD

**Issue by NightfallAlicorn** [discordjs/discord.js#3475]
**Please describe the problem you are having in as much detail as possible:**

I'm unable to add roles. After going through different code snippets on the web it appears message.guild.roles.find and message.member.addRole should be adding the role but catch keeps saying the role doesn't exist since it's null. I've manually added the role and it does exist. The loop function role.name does appear true with matching name. I've set modify roles and send messages as bot minimum required permissions.

**Include a reproducible code sample here, if possible:**
```js
bot.on('message', (message) => {
  // Check for command symbol.
  if (message.content.substring(0, 1) !== COMMAND_SYMBOL) {
    return
  }

  let args = message.content.substring(COMMAND_SYMBOL.length).split(' ')

  if (args[0] === 'joinclan') {
    if (!args[1]) {
      message.reply('Please enter the clan name.')
      return
    }

    let property

    for (property in CLANS) {
      console.log(property)
      console.log(args[1])
      if (args[1].toLowerCase() === property) {
        var role = message.guild.roles.find((role) => {
          role.name === "Great Role" // CLANS[property]
        })
        console.log(role) // null here even though it's true
        message.member.addRole(role).catch((error) => {
          message.reply('Error: ' + error)
        })
      }
    }
    return
  }
})

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.10.0
- Operating system: Termux on Andriod
- Priority this issue should have – please be realistic and elaborate if possible: Normal, unable to make a change role bot.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
The function supplied to `roles.find()` isn't returning anything:
```js
var role = message.guild.roles.find((role) => {
    role.name === "Great Role" // CLANS[property]
})```
By adding the `{}` and creating a function block, there's no implicit return - you would have to manually return the boolean value:
```js
var role = message.guild.roles.find((role) => {
    return role.name === "Great Role" // CLANS[property]
})```
or remove the `{}`
```js
var role = message.guild.roles.find((role) => role.name === "Great Role")
```

This is why the issue template recommends that you first seek help in our Discord support server first - https://discord.gg/bRCvFy9

If you have more questions please follow up there.

**Comment by NightfallAlicorn** [comment]
I appreciate the help, thank you. I be sure to join Discord chat if I have any more problems in the future.
