### ISSUE TITLE
Erlpack Error: Reading a byte passes the end of the buffer

### ISSUE THREAD

**Issue by Tenpi** [discordjs/discord.js#3482]
**Please describe the problem you are having in as much detail as possible:**

I recently updated from stable to master, however I am getting the following errors right after the client logs in, before the ready event is emitted: 
```
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:60] Reading two bytes passes the end of the buffer.
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:50] Reading a byte passes the end of the buffer.
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:117] List doesn't end with a tail marker, but it must!
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:50] Reading a byte passes the end of the buffer.
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:117] List doesn't end with a tail marker, but it must!
[Error f:\documents\tenpi's stuff\programming\discord-bots\kisaragi\node_modules\erlpack\js\decoder.h:28] Bad version number.
```

The error comes from the package discordapp/erlpack - erlpack@0.1.0  (github:discordapp/erlpack#a41fd5be3bec579bbb72dd0f29235ef1a025f2a1)

My token is correct, I reset it multiple times. 
I still get the error with the most bare minimum code (creating a client and logging in):

**Include a reproducible code sample here, if possible:**
```js

// Place your code here
import {Client} from "discord.js"

const client = new Client()

client.login(process.env.TOKEN)
```

Thanks for any help!

**Further details:**
- discord.js version: 12.0.0
- Node.js version: 10.16.1
- Operating system: Windows 10 Home 64-Bit
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [X] I have also tested the issue on latest master, commit hash: discord.js@12.0.0-dev  (github:discordjs/discord.js#60f89bd96f7e110617af021642a810e7fb71e694)

**Comment by vladfrangu** [comment]
Erlpack is probably outdated, and/or broken. For now, I'd personally recommend removing it, and installing zlib-sync

**Comment by Tenpi** [comment]
> Erlpack is probably outdated, and/or broken. For now, I'd personally recommend removing it, and installing zlib-sync, while they aren't doing the same, at least your bot will work 😅😅

After much experimenting, I fixed the issue by removing the package "zucc". It seems like there are incompatibility issues between zucc and erlpack. Anyway, I will close this issue since I fixed it.
