### ISSUE TITLE
Voice error events don't get handled properly

### ISSUE THREAD

**Issue by Clemens-E** [discordjs/discord.js#3487]
**Please describe the problem you are having in as much detail as possible:**
around twice a day I get  [Error [VOICE_CONNECTION_TIMEOUT]](http://i.am.being-a.fail/ure/nEQM) as an error event.
And because unhandled error events cause a node process to immediately exit, it gets pretty annoying.
It seems as discord.js doesn't listen on the error event (only when the client authenticated).
https://github.com/discordjs/discord.js/blob/master/src/client/voice/ClientVoiceManager.js#L101

I then manually added a listener (to test) on the error event:
```js
connection.on('error', e => {
    console.log(`[ERROR EVENT]:  status: ${connection.status}`, e);
    reject(e);
});
```
After some hours I finally got an error, and the status was 1, meaning it wasn't authenticated, meaning there wouldn't have been a listener on the error event
(see screenshot)
![image](https://i.am.being-a.fail/ure/7vci)

**Include a reproducible code sample here, if possible:**
```js
// you can't reliably reproduce this, because it doesn't happen often
voiceConnection = await member.voice.channel.join().catch((): null => null);
```

**Further details:**
- discord.js version: https://github.com/discordjs/discord.js/pull/3393 (vlads branch, because I had problems with sharding)
- Node.js version: 10.16.0
- Operating system: Ubuntu 18.04 (also happens on 16.04)
- Priority this issue should have – please be realistic and elaborate if possible:
medium.
its not really a major issue, but it gets annoying

- [x] I have also tested the issue on latest master, commit hash:
(not needed, its the same code)

**Comment by robotboy655** [comment]
Basically duplicate of https://github.com/discordjs/discord.js/issues/3476

**Comment by Clemens-E** [comment]
Yes, sorry I didn't see it.
I can try to pr a fix (handling the event)

**Comment by Clemens-E** [comment]
My PR was merged and hopefully fixed this.
I'm guessing that it only fixed the symptoms but not the much deeper lying cause, but I will rather have a failed connection twice a day than a complete node crash twice a day.
