### ISSUE TITLE
Multiple response when given a command

### ISSUE THREAD

**Issue by zhiyan114** [discordjs/discord.js#3489]
**Please describe the problem you are having in as much detail as possible:**
When a command is sent (in DM), the bot supposes to response once in DM, instead it response 5 times every 3 seconds. Only occurs in bot DM, server channel doesn't have this issue.

**Include a reproducible code sample here, if possible:**
```js

const Discord = require('discord.js');
const client = new Discord.Client();
var mysql = require('mysql');
var Raven = require('raven');

client.on('message', msg => {
//  Raven.context(function () {
  if(msg.channel.type != "dm" && msg.content.startsWith(';')) {
    SendMsg(msg.channel,"Invalid Channel",'The bot will only function if it called in DM',0xFF0000);
    return;
  } else if(msg.channel.type == "dm" && msg.content != ";verify") {
    SendMsg(msg.channel,"Invalid Command",'The bot will only handle verification, no other command can be used. To verify, type ;verify',0xFF0000);
    return;
  }
  if (msg.content === ';verify') {
    SendMsg(msg.channel,"Valid Command","Command is valid but the function isn't.",0x00FF00);
   return;
    // Do the stuff
    var dbconn = mysql.createConnection({
      host: "localhost",
      user: "yourusername",
      password: "yourpassword",
      database: "mydb"
    });
    dbconn.connect(function(err) {
      if(err) throw err;
      dbconn.query("Query", function(err, result) {
        if(err) throw err;
      });
    });
}
//});
});

client.login("Code")
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.11
- Operating system: Raspberry Pi
- Priority this issue should have – please be realistic and elaborate if possible:
High, the bug is causing the bot DM to be unusable.

- [X] I have also tested the issue on latest master, commit hash: [Installed from npm so unsure]

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
