### ISSUE TITLE
Undefined bitfield if invalid permission flag is parsed to Permissions constructor

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#3490]
**Please describe the problem you are having in as much detail as possible:**

If an invalid permission flag, like "foo" in this example is passed, the value is accepted and a valid Permissions instance with a `undefined` bitfield instantiated instead of the `RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number.` being thrown.

**Include a reproducible code sample here, if possible:**
```js
const { Permissions } = require("discord.js");
const perms = new Permissions("foo");
console.log(perms);
// Permissions { bitfield: undefined }
console.log(perms.bitfield);
// undefined

```

**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: 12.8.0
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible: med, high if other core functionality could possibly be affected

- [x] I have also tested the issue on latest master, commit hash: ea8b4e73559d118a826ac3b242c1a3626b4f6d29

**Comment by Maksim990** [comment]
Почему эта ошибка возникает при коде `if(message.member.hasPermission("KICK_MEMBERS")) return message.channel.send("Вы не можете кикать");`?
