### ISSUE TITLE
Message object with type undefined

### ISSUE THREAD

**Issue by Miky88** [discordjs/discord.js#3514]
**Please describe the problem you are having in as much detail as possible:** The message generated when you add a webhook of a follow a channel has type undefined and system = false.

**Include a reproducible code sample here, if possible:**
```js
message.channel.fetchMessage("here goes the id of the message")
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 8.15.1
- Operating system: Linux based
- Priority this issue should have – please be realistic and elaborate if possible: 5/10

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
I can not reproduce this behavior.
The type of a message sent by a webhook follow is type `'DEFAULT'` in all my tests and
`system = false` is the correct information, as these are based on the webhook engine, which do not count as system messages. System messages are messages like "pinned a message", "joined the server" or "boosted the server"

tested on version: `11.5.1`

**Comment by Miky88** [comment]
oh ok nice thank you

**Comment by SpaceEEC** [comment]
Relevant PR implementing this on master https://github.com/discordjs/discord.js/pull/3388
I suppose this is something that should be backported.
