### ISSUE TITLE
Discord mention sometimes not working in embed message

### ISSUE THREAD

**Issue by iElsha** [discordjs/discord.js#3527]
**Please describe the problem you are having in as much detail as possible:**
I'm working on a bot which will mentions user in a discord embed message.

Everything works fine except the mentions things:
[https://media.discordapp.net/attachments/627237231677145100/630182211689250816/unknown.png](url)

The user are not mentioned directly but we see there discordId.

The expected result would be : 
[https://cdn.discordapp.com/attachments/618890162352685066/630327635129663488/unknown.png](url)

**Include a reproducible code sample here, if possible:**

It's a simple mention of an user in an embed message. It's maybe a discord bug a

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: When you have a chance.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Androz2091** [comment]
Yes, it's a discord bug. Discord.js can't do anything about that, it's from your client.

**Comment by GamesProSeif** [comment]
Mentions will be viewed as IDs if your client doesn't have that member cached. So this behaviour changes from one client (human account) to another.
Also keep in mind that mentions inside embeds do not trigger a mention notification like it would happen in a regular text message.

**Comment by Monbrey** [comment]
> restriction from the API that your client can't fetch "unkown" users

Not really true. There's no restriction on the API to prevent fetching any user. The desktop/mobile clients just _dont_ fetch users to display mentions - it would be a waste of API calls.

As Seif pointed out, resolving mentions into usernames uses the client's cache.

**Comment by iElsha** [comment]
Thanks you for your answers.
