### ISSUE TITLE
Invalid Permission Checks

### ISSUE THREAD

**Issue by kyranet** [discordjs/discord.js#3529]
**Please describe the problem you are having in as much detail as possible:**

Consider the case where you have a bot with `MANAGE_ROLES` permission, the following code works as intended:

```javascript
message.guild.me.hasPermission('MANAGE_ROLES'); // true
```

However, in a channel, things can go a little weird when we check with any of the following methods:

```javascript
message.channel.permissionsFor(this.client.user).missing('MANAGE_ROLES', false) // [ 'MANAGE_ROLES' ]
message.channel.permissionsFor(this.client.user).has('MANAGE_ROLES', false) // false
```

Turns out, `MANAGE_ROLES` is defined as `0b0010000000000000000000000000000` here:

https://github.com/discordjs/discord.js/blob/a8f06f251f1af87650711d4c163ed32d909d4e18/src/util/Permissions.js#L107

However, this conflicts with another permission that is per-channel: `MANAGE_PERMISSIONS`.

So when using any of the last two checks (which is often used so we can check channel and guild permissions), this fails when for example, you set a permission overwrite (e.g. `@everyone`) with this denied:

![image](https://user-images.githubusercontent.com/24852502/66438543-42673a00-ea2d-11e9-843a-b6a87fe440ef.png)

And to do so, the API sends us `deny: 0b0010000000000000000000000000000`, which by surprise, is the same bitfield as the one used by `MANAGE_ROLES`.

**Include a reproducible code sample here, if possible:**

Give a bot the role permission `MANAGE_ROLES` permission, then create a permission overwrite denying the `MANAGE_PERMISSIONS` permission, it will tell you that the `MANAGE_ROLES` permission in said channel is missing.

**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: v12.10.0
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: High, this is affecting my bot in very large servers, and I rely on permission checks a lot.

- [x] I have also tested the issue on latest master, commit hash: a8f06f251f1af87650711d4c163ed32d909d4e18

**Comment by Monbrey** [comment]
`MANAGE_ROLES` doesn't exist as a channel permission at all.

What would the expected return value be if there were no conflicting permissions at the channel level, just checking `MANAGE_ROLES`, given that it doesn't exist as channel permissions anyway?

**Comment by almostSouji** [comment]
> Note that these internal permission names may be referred to differently by the Discord client. For example, **"Manage Permissions" refers to MANAGE_ROLES**, "Read Messages" refers to VIEW_CHANNEL, and "Use Voice Activity" refers to USE_VAD.
src: https://discordapp.com/developers/docs/topics/permissions#permissions

`MANAGE_PERMISSIONS` does not exist
the deprecated flag was called `MANAGE_ROLES_OR_PERMISSIONS`, now `MANAGE_ROLES` and applies for both cases.

The user/bot can change permissions if (after applying all overwrites) it has `MANAGE_ROLES` in the bitfield (does include slowmode as well)
`MANAGE_CHANNEL` refers to topic, name, audio stuff
