### ISSUE TITLE
Position option in ChannelStore.create is ignored 

### ISSUE THREAD

**Issue by evilpauwse1** [discordjs/discord.js#3534]
**Please describe the problem you are having in as much detail as possible:**
Creating a voice channel using the "position" option seems to ignore the set position and place the voice channel at the bottom of other voice channels.

To reproduce, you need at least two channels, we will be putting the channel in between "channelA" and "channelB"
**Include a reproducible code sample here, if possible:**
```js
console.log(channelA.position);
channelA.guild.channels.create("channelB", {parent: channelA.parentID, type: 'voice', position: channelA.position + 1}).then(chan => console.log(chan.position));
/*
Assuming channelA's position outputs as 0, and channelB's position is 1 [this is before the creation]
Then the new channel will be created and output a position of 2, thus ignoring the position. */
```

**Further details:**
- discord.js version: master
- Node.js version: 10.15.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: Low Priority

- [x] I have also tested the issue on latest master, commit hash: a60f8b3

**Comment by Jiralite** [comment]
There is already a channel at that position, so it just places it on the end of all the other channels with the same position. Also, the code you provided would create a text channel. If you want to keep an order of the voice channels, consider doing `Guild#setChannelPermissions()`.

If you'd like it so the position would insert it at the position specified and push all other channels down, you could ask for a feature.

The support Discord would probably yield a quicker response too.
