### ISSUE TITLE
message.guild.createRole is not a function

### ISSUE THREAD

**Issue by NFellGill** [discordjs/discord.js#3536]
**message.guild.createRole is not a function**

```js
msg.guild.createRole({
      name: name,
      color: color
    });
```

**Further details:**
- discord.js version: github:discordjs/discord.js#master
- Node.js version: v10.15.3
- Operating system: Windows

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
