### ISSUE TITLE
TypeError: users is not iterable

### ISSUE THREAD

**Issue by Zerumi** [discordjs/discord.js#3544]
**Please describe the problem you are having in as much detail as possible:**
TypeError: users is not iterable at new MessageMentions

**Include a reproducible code sample here, if possible:**
```js

const discord = require("discord.js");
module.exports = {
...
    async execute(messag, args){
        var message = new discord.Message(messag.channel,messag, messag.client)
        var arrmessages = [];
        var messagesid = [];
        fetched = await message.channel.fetchMessages({limit: 100});
...

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.11.1
- Operating system: Windows 7 x64
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Why do you create/instantiate a new `Message` from a message you received?

**Comment by Zerumi** [comment]
Because my IDE does not support types in a js file, and a tip for writing a particular function is a good bonus in writing speed..

**Comment by DevYukine** [comment]
Message is an class you should not create/instantiate on your own. if you want Intellisense then i would recommend either using JSDocs or switching to Typescript :)

**Comment by iCrawl** [comment]
You simply can not do that to "force" some kind of types.

Use a "proper IDE/Editor" like VSCode or something that supports Typescript types.
