### ISSUE TITLE
Add "reason" to Guild's createChannel object overload in the documentation

### ISSUE THREAD

**Issue by roncli** [discordjs/discord.js#3548]
**Is your feature request related to a problem? Please describe.**
#2888 added an object overload to the Guild's createChannel method.  Unfortunately, it did not add the ability to include a reason for the audit log.  I am requesting that the audit log reason be added to this overload.

**Describe the ideal solution**
Currently the object overload on the createChannel method only accepts the name of the channel and an object of channel parameters.  The reason is unable to be passed.  In order to pass a reason while creating a channel, I must use the deprecated overload.

**Describe alternatives you've considered**
The deprecated overload is a current workaround.

**Additional context**
n/a

**Comment by almostSouji** [comment]
If you add `reason` to the ChannelData options object it does work (v11.5.1), seems like it was just not properly documented in the ChannelData typedef, apparently.

**Comment by roncli** [comment]
Oh, oops!  Good that it works anyway!  I'll modify the request accordingly.
