### ISSUE TITLE
How can i set custom status in discord bot according to new update

### ISSUE THREAD

**Issue by RootAndroid58** [discordjs/discord.js#3551]
according to new update u can set your own custom status without playing or listening this ist added in documentation yet  what can i do here
there is no option to set custom activaty in [/stable/src/util/Constants.js](https://github.com/discordjs/discord.js/blob/stable/src/util/Constants.js#L364) here too 
![Screenshot (118)](https://user-images.githubusercontent.com/28777412/67614876-df71f300-f7e1-11e9-851e-eef211a160ce.png)

**Comment by tipakA** [comment]
Reply from a moderator on r/discordapp
https://www.reddit.com/r/discordapp/comments/dm47sv/at_least_something_regarding_custom_status/f508crt?utm_source=share&utm_medium=web2x

**Comment by iCrawl** [comment]
Merge into #3552
