### ISSUE TITLE
ShardingManager: fetch is not a function

### ISSUE THREAD

**Issue by legowerewolf** [discordjs/discord.js#3563]
**Please describe the problem you are having in as much detail as possible:**
Alright! Here we go. When I try to run my bot using the ShardingManager, I get this (linkified for reference):

(node:20052) UnhandledPromiseRejectionWarning: TypeError: [fetch](https://github.com/discordjs/discord.js/blob/master/src/util/Util.js#L226) is not a function
    at [Function.fetchRecommendedShards](https://github.com/discordjs/discord.js/blob/master/src/util/Util.js#L224-L233)
    at [ShardingManager.spawn](https://github.com/discordjs/discord.js/blob/master/src/sharding/ShardingManager.js#L165-L203)

Note that [node-fetch is imported correctly](https://github.com/discordjs/discord.js/blob/master/src/util/Util.js#L4), as [recommended by the node-fetch docs.](https://www.npmjs.com/package/node-fetch#loading-and-configuring-the-module)

**Include a reproducible code sample here, if possible:**
My bot's open source. [Here's the branch](https://github.com/legowerewolf/discordbot.ts/tree/dependabot/npm_and_yarn/discord.js-3a9eb5b) where I'm working on the update. The readme describes how to configure and provides a minimum viable configuration.

**Further details:**
- discord.js version: 38d370fb18fdbf079b1c91793c0550e77667eccd (latest master)
- Node.js version: 13.0.1
- Operating system: Windows 10 Education Edition v1903, build 18362.418
- Priority this issue should have – please be realistic and elaborate if possible: Pretty high. I can't be the only one using the ShardingManager, nor the only one having issues.
- I use TypeScript and Webpack, neither of which complain when building.

**Comment by legowerewolf** [comment]
[Here's where I asked about this problem in the Discord...](https://discordapp.com/channels/222078108977594368/223867697312694272/639152627564675084) not that I got anything out of it.

**Comment by iCrawl** [comment]
This is why you don't use webpack for the backend, it has no purpose but makes everything a tad more complicated.

node-fetch, when used with webpack, just boils down to this https://github.com/bitinn/node-fetch/blob/master/browser.js

Fetch not being a global thing outside of browsers makes this whole thing blow up.

**Comment by legowerewolf** [comment]
I use webpack because I build to deploy via Docker. This is a recent thing - it was working (and still is, using the same settings) on the 11.5.1 release on NPM.

**Comment by iCrawl** [comment]
You don't need webpack to deploy via Docker, if you would no one would use Docker.

Regardless of that, stable does not use node-fetch, it uses snekfetch a now deprecated http library.

**Comment by legowerewolf** [comment]
"Last publish: 5 months ago."

I use webpack because I want to minimize image size. Regardless, in my config, Webpack is setup to build for Node targets.

**Comment by iCrawl** [comment]
The last publish of the v11 version, which is not what the master branch reflects.

The master branch is v12 with quite a few breaking changes, nothing to do with the last publish.

Again, this is a webpack issue. From researching this is the only thing I found that could help alleviate the problem on your side:
https://github.com/bitinn/node-fetch/issues/450#issuecomment-494475397

**Comment by legowerewolf** [comment]
Ah. Thanks!

**Comment by greysonn** [comment]
I was able to fix by going down to discord.js@11.4.2

**Comment by iShibi** [comment]
@greysonn You shouldn't be using discord.js v11. It's going to create more problems for you than it will solve. Here is what djs discord server has to say about it:

> We no longer provide support for v11 and it will not get any bug fixes or new features. Please update at earliest convenience.
The API domain change was postponed to early 2021 (bots using v11 will no longer work)

**Comment by greysonn** [comment]
For my use-cases v11.4.2 works fine. I understand your point, but just downgrading is a quick-fix that most will be able to integrate.

> @greysonn You shouldn't be using discord.js v11. It's going to create more problems for you than it will solve. Here is what djs discord server has to say about it:
> 
> > We no longer provide support for v11 and it will not get any bug fixes or new features. Please update at earliest convenience.
> > The API domain change was postponed to early 2021 (bots using v11 will no longer work)

**Comment by almostSouji** [comment]
> but just downgrading is a quick-fix that most will be able to integrate.

11 is officially no longer supported or maintained _(with 11.6.4 being the last version - you're using an old version of an old version here)_. it will break further down the line and rather than going back people should upgrade. we have had many bugs fixed since then which will persist on outdated versions.

please do not recommend downgrading as a solution, even if it's quicker and works for you.
