### ISSUE TITLE
Sharding for the webpack version

### ISSUE THREAD

**Issue by Earu** [discordjs/discord.js#3565]
Hello, I am currently using discord.js in a browser context, and I just noticed that there was simply no way for me to use the `ShardingManager` as every time I try to instantiate it, it tells me that the constructor does not exist. Is that intended? If so what are the reasons behind it? 

My code as of now (ts):
```ts
import * as Discord from 'discord.js'

const manager: Discord.ShardingManager = new Discord.ShardingManager('./shard.js', { token: 'my_token' });
manager.spawn()
```

The error I'm getting:
![err](https://i.imgur.com/u8ZvbCw.png)

Note: I stripped my other imports away this is why it says line 14 in the stacktrace.

**Comment by iCrawl** [comment]
Yes it is intended.

The ShardingManager inherently relies on concepts that do not exist in the browser (process(es)/worker threads, fs)

**Comment by Earu** [comment]
What about web workers?

**Comment by iCrawl** [comment]
This still wouldn't solve the reliance on all the other ones.

By all means you are free to try it out and put up a PR.
We just haven't had the need to allow this behavior in browsers.

**Comment by Earu** [comment]
I see, I might PR something if I find out how to make it work inside discord.js. Thanks for your time.

**Comment by vladfrangu** [comment]
Do note that sharding *is* doable in web via using internal sharding... Should you *need* it.

**Comment by iCrawl** [comment]
Latest: Web builds won't be continued and are discouraged by discord itself.
