### ISSUE TITLE
Cannot add two emojis to the embed message!

### ISSUE THREAD

**Issue by kaan1karaman** [discordjs/discord.js#3568]
`const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {

let thumbnail = message.author.avatarURL
let bug = args.join(" ").slice(0);
  if(bug.length < 1) return message.reply("herhangi bir yazı yazmadınız!");
let user = message.author.username;
let userid = message.author.id;
let kanal = message.channel.name;
let mesajid = message.id;
let channel = bot.channels.get("642359555199860750")//bug repot kanal id
let embed = new Discord.RichEmbed()
let mesaj = channel.send(embed)

.setTitle("Bildiri")
.setThumbnail(thumbnail)
.addField("İçerik:", bug)
.addField("Yazar", user, true)
.addField("Yazar (ID)", userid, true)
.addField("Kanal", kanal, true)
.addField("Mesaj (ID)", mesajid, true)
.setColor("GREEN")

message.channel.send(":white_check_mark:  | Bildiriniz başarıyla iletildi. Lüzumsuz kullananlar cezalandırılır!")
channel.send(embed)

}
exports.conf = {
  enabled: true,
  guildOnly: true,
  aliases: ["report"],
  permLevel: 0  
};

exports.help = {
  name: 'bildir',
  description: 'Herhangi bir şeyi bildirirsiniz.',
  usage: '%bildi}r <mesaj içeriği>'
}`

This is my command.
After the embed message sent to the channel, I want to add ✔ and ❌ emoji's to the embed message. But I tried every way and now I can see that is not possible on discord.js (probably). It maybe a bug too, I'm not sure. If that's possible, can you please post the command?

**Comment by almostSouji** [comment]
Seeing that no part of this code even attempts to react (assuming that's what you mean by " I want to add ✔ and ❌ emoji's to the embed message") I don't quite understand how this is filed as a bug report. [Message#react](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react) works as detailed. To react with multiple emojis you need to do multiple calls, that's an API (discord) limitation.

Our issue templates tell you very clearly where to go to receive answers for general library questions ("How to add a reaction to a message the bot just sent" or similar in this case):
>  **Question / General support request**
Ask for help in Discord instead - https://discord.gg/bRCvFy9

**Comment by kaan1karaman** [comment]
> Seeing that no part of this code even attempts to react (assuming that's what you mean by " I want to add ✔ and ❌ emoji's to the embed message") I don't quite understand how this is filed as a bug report. [Message#react](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react) works as detailed. To react with multiple emojis you need to do multiple calls, that's an API (discord) limitation.
> 
> Our issue templates tell you very clearly where to go to receive answers for general library questions ("How to add a reaction to a message the bot just sent" or similar in this case):
> 
> > **Question / General support request**
> > Ask for help in Discord instead - https://discord.gg/bRCvFy9

I'm sorry. It's my first ticket on GitHub. I won't do the same mistake again.

And also, I know there is no attempt to react because I couldn't do it. I just removed them after my failured tries because they didn't work.
