### ISSUE TITLE
GuildChannel.overwritePermissions() return value non-deterministically reflects permissions changes

### ISSUE THREAD

**Issue by pianiststickman** [discordjs/discord.js#3570]
**Please describe the problem you are having in as much detail as possible:**
This came about when I was trying to clear a flag from the `allow` field of a PermissionsOverwrite object and delete the overwrite if that action resulted in no flags being set in either the `allow` or `deny` fields, for which I wrote the code sample below. Running the code sample below with an existing overwrite on `channel` for `member` with `allow == SEND_MESSAGES` and `deny == 0` will *sometimes* result in the overwrite being deleted, and *sometimes* result in an overwrite remaining with no flags set.

Digging a little deeper, I suspect the reason for this is that `GuildChannel.overwritePermissions` results in the "Edit Channel Permissions" REST call, which returns an empty 204 Success response - d.js therefore doesn't update the channel object until the ChannelUpdate event fires, which may or may not happen before the REST call returns and d.js resolves the promise.

**Include a reproducible code sample here, if possible:**
```js
channel = await channel.overwritePermissions(member.id, { SEND_MESSAGES: null })
let overwrite = channel.permissionOverwrites.get(member.id)
if (overwrite.allow === 0 && overwrite.deny === 0) {
  // there were no other permissions in this overwrite. Delete it.
  await overwrite.delete()
}
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.13.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: I have a workaround for the above sample (instead of clearing the flag and then deleting if no flags are set, just delete the overwrite if the flag to be cleared is the only one set) but this could result in data consistency issues if the calling code makes decisions based on what it thinks are the state of the permissions.
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
