### ISSUE TITLE
Cannot read property 'bot)' of undefined

### ISSUE THREAD

**Issue by GreepTheSheep** [discordjs/discord.js#3574]
**Please describe the problem you are having in as much detail as possible:**
When I starts the process (my shard script), the process stops because of shardClientUtil.js:

```
/mnt/c/Users/matt2/Documents/GitHub/CoronaLanterns/node_modules/discord.js/src/sharding/ShardClientUtil.js:107
      for (const prop of props) value = value[prop];
								^
TypeError: Cannot read property 'bot)' of undefined
    at ShardClientUtil._handleMessage (/mnt/c/Users/matt2/Documents/GitHub/CoronaLanterns/node_modules/discord.js/src/sharding/ShardClientUtil.js:107:46)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 10.16.0
- Operating system: Debian sub-system for Windows 10 
- Priority this issue should have – please be realistic and elaborate if possible: Max because my process stop and restarts every time

**Comment by Monbrey** [comment]
I recommend that you go to the Discord server for help, and be prepared to share your shard script for assistance.

https://discord.gg/bRCvFy9

**Comment by GreepTheSheep** [comment]
Reopened because I checked all my files of my project and found nothing with this mistake

**Comment by GreepTheSheep** [comment]
Ok after hours and hours of searching, I found the bug on my project. sorry for disturbing you.

**Comment by Tarcros** [comment]
> Ok after hours and hours of searching, I found the bug on my project. sorry for disturbing you.

what was it? pls
