### ISSUE TITLE
addRole() timeout vs. addRoles() without timeout

### ISSUE THREAD

**Issue by zap2zero** [discordjs/discord.js#3575]
**Please describe the problem you are having in as much detail as possible:**
I am working on a bot with the purpose to manage the role for members where a webapp keeps track on who should have the role and who not.
So I have a setInterval() job which every some minutes syncs the current members vs. the data of the website adding and removing the role.
This has been working perfectly fine for about 70 members but constantly failed for the same 2 members over the duration of several days. When the bot tried to add the role via addRole(), I got this error:
```
2019-11-12 07:38:39 error: member.addRole Adding the role timed out. Error: Adding the role timed out.
    at /node_modules/discord.js/src/client/rest/RESTMethods.js:551:16
    at Timeout._onTimeout (/node_modules/discord.js/src/client/Client.js:436:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

After checking the rateLimit event and a lot of other ways to debug this issue I finally tried to replace addRole(role.id) with addRoles([ role.id ]) and this did the trick and it started working like magic.

**Include a reproducible code sample here, if possible:**
```js

// the code was really trivial
                member.addRole(role.id)
                    .then(function (log) {
                    })
                    .catch(function (error) {
                        logger.error('member.addRole ', error);
                    });
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.11.1
- Operating system: MacOS and Linux
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
With the upcoming v12 release I see this as fixed.
