### ISSUE TITLE
How to change port

### ISSUE THREAD

**Issue by Aman83770** [discordjs/discord.js#3577]
I am trying to deploy a discord bot on Heroku. And By default, Heroku binds the port itself, that's why we define like `port = process.env.port || 80`. So How can I edit that port in discordJS so Heroku can look for the port in env? This is the reason my Heroku app is crashing after 60 second
![Screenshot from 2019-11-14 02-27-29](https://user-images.githubusercontent.com/19190611/68804207-394e3600-0687-11ea-8dbe-6817086a7bbe.png)

**Comment by iCrawl** [comment]
Discord.js does not expose any kind of port nor a http server.

**Comment by jsmiith** [comment]
Either way, you're using the web dyno. Go into the dynos panel of your Heroku project, disable the web dyno, and enable the worker dyno. That should work for you - if it doesn't, feel free to contact me on Discord at newt#1234, as this isn't really the place to discuss this.

**Comment by N8WM** [comment]
I can confirm that the suggestion @newtykins has works for me. Make sure you have a file called "Procfile" (with no extention) that contains "worker: npm start" then restart your dynos, turn off the web dyno and turn on the worker one you just made.
