### ISSUE TITLE
users/members from id

### ISSUE THREAD

**Issue by lukaskabc** [discordjs/discord.js#3598]
Hi, recently my js discord bot start having problems with getting users and memebers from thier id.

I am using methods such as:
var id = some user id
var user = client.users.get(id)
var member = guild.members.get(id)
var m = guild.member(user)
etc...

and sometimes (recently it is really common) happednd that bot throw error that these methods return null and he cant operate that.
For example i try to add role, so I used
guild.member(user).addRole(role) etc
and error say that this (guild.member(user)) is null and cant call function (.addRole(role)) on it.

Most interesting is, that it happend really random, sometimes it work and sometimes it throw error.

Can someone explain me where can be problem?

(sorry for my bad english)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
