### ISSUE TITLE
GuildMemberStore.fetch() triggers fetching everyone in the guild if passed value is undefined

### ISSUE THREAD

**Issue by tiritto** [discordjs/discord.js#3600]
Hello everyone, master branch user here.

While I was working on my bot earlier today, I've accidentally made a mistake and caused an **undefined** value to be passed into **GuildMemberStore.fetch(xyz)** method. My intention was to fetch a single member and I was really surprised when I realized that I accidentally just caused my bot to fetch everyone in the guild.

While there is no doubt that this mistake is fully my fault and it's not DiscordJS fault in any way, I believe that there should be some kind of guard that prevents this from happening. When this kind of mistakes happen, usually we learn about it right away as there is an error being throw at our faces informing us about invalid type or about the fact that passed value is not an object.

In case of **GuildMemberStore.fetch()** however, the same kind of mistake is not only not causing any errors, but also causes quite unexpected action - fetching every single person in a guild - that is even discouraged in official docs. Maybe it wouldn't be a bad idea to either make separate method for fetching everyone (`.fetchAll()`) or just guard it with an additional option (`.fetch({all: true})`)?

And again, I am aware that this is not really an issue of DiscordJS itself but an issue of people doing mistakes with their own code but yet I was thinking it might be worth putting some light at this situation.

**Comment by tipakA** [comment]
> but also causes quite unexpected action - fetching every single person in a guild - that is even discouraged in official docs.

Uhh, not sure where did you see that, but that's actual way of fetching all members in the guild.
This is method for fetching all members, unless you pass `UserResolvable`, `FetchMemberOptions` or `FetchMembersOptions`, as per documentation.

**Comment by tiritto** [comment]
> > but also causes quite unexpected action - fetching every single person in a guild - that is even discouraged in official docs.
> 
> Uhh, not sure where did you see that, but that's actual way of fetching all members in the guild.
> This is method for fetching all members, unless you pass `UserResolvable`, `FetchMemberOptions` or `FetchMembersOptions`, as per documentation.

That's the feeling I got from reading `fetchAllMembers` option description from `ClientOptions`.
> Whether to cache all guild members and users upon startup, as well as upon joining a guild (should be avoided whenever possible)

**Comment by iCrawl** [comment]
Those are very different use cases.

Sometimes you want to fetch all members of a certain guild, and maybe sweep them away afterwards.
This is very different from fetching all members of every single guild after start up.
