### ISSUE TITLE
New Method

### ISSUE THREAD

**Issue by DeathHound6** [discordjs/discord.js#3604]
**Describe the ideal solution**
Add a possible `canSend()` method to the user object. It would allow the bot to check if messages can be sent to the user's DMs (i.e: A bool type for the "Allow direct messages from server members" option in the `user settings>privacy&safety` settings

**Comment by almostSouji** [comment]
Discord does not expose this user setting through the api.
There is currently no way to find out if a user is able to receive a DM before trying to send it (the promise returned by `send()` will reject)

**Comment by SpaceEEC** [comment]
We can't implement something like that without Discord exposing such information somehow.
It also does not look like Discord is going to do so.

Relevant issues on Discord's repository on that:
- https://github.com/discordapp/discord-api-docs/issues/1066
- https://github.com/discordapp/discord-api-docs/issues/612
