### ISSUE TITLE
Webhook#token returns undefined

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/discord.js#3605]
**Please describe the problem you are having in as much detail as possible:**

- Below is a code sample I am attempting to use to either create a webhook in a channel if one doesn't exist, or get the first existing one using Channel#fetchWebhooks.
- According to the discord.js docs, Webhook#token cannot be null/undefined ~~(and it wouldn't make sense for it to be, as you can't use a webhook without it)~~.
- I've tested and confirmed that webhook **is** a valid Webhook, the output of a console.log can be found at https://hatebin.com/cksbyekoec
- The bot has administrator permissions, no errors are thrown.

**Include a reproducible code sample here, if possible:**
```js
let webhook = await message.channel.fetchWebhooks();
if(webhook.size) {
    webhook = await webhook.first().edit({ name: message.author.username, avatar: message.author.displayAvatarURL() });
} else {
    webhook = await message.channel.createWebhook(message.author.username, { avatar: message.author.displayAvatarURL() 
}
console.log(`https://discordapp.com/api/webhooks/%s/%s`, webhook.id, webhook.token);
// ... /webhooks/id/undefined
```

**Further details:**
- discord.js version: master, 12.0.0-dev
- Node.js version: v10.16.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low priority, I am attempting to re-create a command another bot has on a different server. I could get around this, but I would like to use the author's avatar + name in the message.

- [x] I have also tested the issue on latest master, commit hash: 1b1289b35e2f8cd21341351549e6ac52fd08cb34

**Comment by MBR-0001** [comment]
> According to the docs, Webhook#token cannot be null/undefined (and it wouldn't make sense for it to be, as you can't use a webhook without it).

This used to be true until Discord added server announcement following, webhooks that are used for following don't have the token and have type 2 (images below)

![image](https://user-images.githubusercontent.com/55142207/69906169-7cb2df00-13bf-11ea-9965-9090b06973dc.png)

![image](https://user-images.githubusercontent.com/55142207/69906176-9eac6180-13bf-11ea-838d-cdf550e6bf50.png)

[This](https://github.com/discordjs/discord.js/pull/3585) PR should solve this

**Comment by almostSouji** [comment]
> According to the docs, Webhook#token cannot be null/undefined (and it wouldn't make sense for it to be, as you can't use a webhook without it).

This information is wrong, according to discords documentation `.token` can be undefined, and that will be the case for the "webhooks" generated from following an announcement channel. You can not utilize these with a bot, and should filter them out.
`webhooks.filter(hook => hook.token)` or a similar approach should do.

Nonetheless this needs to be edited in 11.5-dev and 12.0.0-dev and typings.

**Comment by KhafraDev** [comment]
@almostSouji this issue occurs when creating or getting an existing webhook (as shown in my code above). When getting the URL manually, it shows a token, and the ID is the same as the Webhook object shown in the output. I'm not using an announcement channel but a textChannel, which I check for earlier in the code (irrelevant to this issue)
When referring to the "docs" I was referring to the discord.js.org docs, my bad - https://discord.js.org/#/docs/main/master/class/Webhook?scrollTo=token

@MBR-0001 Thanks for the info, last time I was active in bot development that announcement hadn't came out yet. I'll check out the PR!

Thank you both for the quick responses
