### ISSUE TITLE
Official Web Page's Documentation Does Not Load

### ISSUE THREAD

**Issue by Daniihh** [discordjs/discord.js#3609]
Going to the [official discord.js's web page's documentation](https://discord.js.org/#/docs/main/stable/general/welcome) reports this message: `TypeError: Failed to fetch`.

![msedge_r9opguh9CJ](https://user-images.githubusercontent.com/39541871/70091367-f6c6ac00-15e9-11ea-8a0f-0faa5d4ca3b7.png)

Using a browser extension to disable the Cross-Origin Resource Sharing protection system resolves the issue.

Affected Browsers
--------------------
- Microsoft Edge (Chromium) Build 80.0.334.4 Developer 64-bit on Windows 10 1809

This could be an issue with the browser, but I thought I'd bring it to your attention either way.

**Comment by kyranet** [comment]
Works on my machine:

![image](https://user-images.githubusercontent.com/24852502/70095224-88530f80-1624-11ea-801c-3e3840261313.png)

Microsoft Edge: `80.0.334.4 (Official build) dev (64-bit)`.
OS: `Windows 10 OS Version 1903 (Build 18362.239)`.

**Comment by Daniihh** [comment]
That's a bit odd. I'm going to assume this is a problem with my browser and close this issue for now. Thanks, have a great day.
