### ISSUE TITLE
channelCreate() event is triggered when joining a server

### ISSUE THREAD

**Issue by RootAndroid58** [discordjs/discord.js#3610]
extension of this issue Client.channelCreate() event is triggered when joining a server #2463
```
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('guildCreate', async guild => {
	console.log(`Joined: ${guild.name}`)
});

client.on('channelCreate', async channel => {
	console.log(`Channel created: ${channel.name}`)
});

client.login('xxx');
```

is there any way to not to emmit channelCreate() event when joining a guild?

**Comment by Monbrey** [comment]
No. As per the response on the other issue we linked, both events are received from Discord and so both events are emitted.

discord.js should not be making its own decisions on which events to emit.

**Comment by RootAndroid58** [comment]
i am not asking discord.js to make changes to code but what can we do to prevent the event from emitting

**Comment by Monbrey** [comment]
You can disable events completely when constructing your Client in ClientOptions#disabledEvents

https://discord.js.org/#/docs/main/stable/typedef/ClientOptions

If you have further questions, please ask them on the Discord server rather than opening an issue.
