### ISSUE TITLE
client.fetchUser function does not exist

### ISSUE THREAD

**Issue by colbymchenry** [discordjs/discord.js#3612]
### **Inside index.js**
![image](https://user-images.githubusercontent.com/18431132/70204549-02e86180-16ef-11ea-877c-7bb8d64eae46.png)

### **Inside SocketHandler.js**
![image](https://user-images.githubusercontent.com/18431132/70204533-f3691880-16ee-11ea-843b-ae3c95ccb509.png)

![image](https://user-images.githubusercontent.com/18431132/70204521-e9dfb080-16ee-11ea-9a3e-07cb19796af8.png)

### **Error**
![image](https://user-images.githubusercontent.com/18431132/70204473-a9803280-16ee-11ea-889e-714ae07ea4f8.png)

**Comment by NightYoshi370** [comment]
You don't use client.fetchUser. You use client.users.fetch instead

**Comment by colbymchenry** [comment]
That worked. Thank you!
