### ISSUE TITLE
Sharding + 2x/3x/4x posting

### ISSUE THREAD

**Issue by saeho** [discordjs/discord.js#3614]
Hello, this may be a support issues. But I was told to post here when I asked for help in Discord.

I've had this strange issue for an entire year, ever since I started sharding the Discord bot (it's used in almost 10,000 servers now), the bot will eventually 2x/3x/4x post for each command.

This happens because after a lot of use (or after about 24 to 72 hours), each single request somehow gets sent to 2 or more shards, thus all those shards responds to the command and it causes a 2x/3x/4x posts.

This is a persisting issue for almost an entire year. Only way I can stop it is by shutting down the instance and restarting it. I tried to fix it last year but I couldn't figure out a way, so I've been manually restarting the instance every 1 to 3 days.

Please help.

**Comment by JMTK** [comment]
Can you post code samples of your message handler?

**Comment by saeho** [comment]
Setting up shards
```
import Discord from 'discord.js';

...

const Manager = new Discord.ShardingManager(entryPoint, {
  token: process.env.TOKEN
});

Manager.spawn(7);

Manager.on('launch', shard => {
  console.log(`[SHARD] Shard ${shard.id}/${shard.manager.totalShards}`);
});
```


Listening to messages

```
Bot.on('message', msg => {
  if (shouldListenToMessage(msg)) {
    resolveMessage(msg, 'discord', 'petbot');
  }
});
```

**Comment by saeho** [comment]
Solved by the kind soul Vladdy in the Discord server.
It was caused by a Koa server.
