### ISSUE TITLE
cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by hansputera** [discordjs/discord.js#3616]
const { RichEmbed } = require("discord.js")

// some code express app get
let embed = new RichEmbed()
.setTitle("Someone was visited")
.addField("IP", //some code ip tracking)
.addField("Time", new Date())

client.channels.get("id").send(embed)

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
