### ISSUE TITLE
(node:9276) UnhandledPromiseRejectionWarning: Error: ./node_modules/discord.js/src/structures/PermissionOverwrites.js

### ISSUE THREAD

**Issue by stevemarksd** [discordjs/discord.js#3623]
ts-loader: Using typescript@3.7.2 and ....\tsconfig.server.dev.json
(node:9276) UnhandledPromiseRejectionWarning: Error: ./node_modules/discord.js/src/structures/PermissionOverwrites.js
Module parse failed: Unexpected token (171:15)
You may need an appropriate loader to handle this file type.
|     if (overwrite instanceof this) return overwrite.toJSON();
|     if (typeof overwrite.id === 'string' && ['role', 'member'].includes(overwrite.type)) {
|       return { ...overwrite,
|         allow: Permissions.resolve(overwrite.allow),
|         deny: Permissions.resolve(overwrite.deny),

node: v12.9.1
discord: latest

I think the proble is that the module is not exported properly `...overwrite` is not correct es5

**Comment by SpaceEEC** [comment]
From the readme: **Node.js 10.2.0 or newer is required.**

**Comment by stevemarksd** [comment]
@SpaceEEC from my description: `node: v12.9.1` Is not that newer than 10?

**Comment by SpaceEEC** [comment]
That requirement also applies to your target.

**Comment by stevemarksd** [comment]
even with target ES2019 same error.

**Comment by stevemarksd** [comment]
![image](https://user-images.githubusercontent.com/58653359/70823000-c9fc6b00-1e19-11ea-8c41-badf9be333aa.png)
// tsconfig.base.json
![image](https://user-images.githubusercontent.com/58653359/70823020-d7b1f080-1e19-11ea-9cb8-a91ba7c81422.png)

**Comment by tipakA** [comment]
Quick question, have you considered joining [Discord support server](https://discord.gg/bRCvFy9)? it will make things a bit easier and faster

**Comment by stevemarksd** [comment]
ok, I will do it for next issue if ok?

**Comment by stevemarksd** [comment]
Ok, I created a new account, but I need to wait 10 minutes to ask any questions there.
