### ISSUE TITLE
`yarn add discordjs/discord.js` creates this in package.json `"discord.js": "discordjs/discord.js",`

### ISSUE THREAD

**Issue by stevemarksd** [discordjs/discord.js#3624]
yarn 1.19.2
node v12.9.1

**Comment by stevemarksd** [comment]
I have no idea why by default it's installing 12.0.0-dev version or similar, when the version in npm is 11.5.1 https://www.npmjs.com/package/discord.js

**Comment by PyroTechniac** [comment]
You're prefixing the install path with a repository, which tells yarn to look at GitHub instead of the npm repository, and seeing as default branch is master, that's the branch that will be installed unless otherwise specified.

**Comment by stevemarksd** [comment]
I'm just following the instructions on the home page of the repo. I don't think that's a good default.

**Comment by PyroTechniac** [comment]
The home page of the repo is automatically the master branch, if you want install instructions to a different branch you should switch to the appropriate branch and read the install instructions provided.

**Comment by iCrawl** [comment]
The master branch is our development branch, like in so many other projects.

The official "homepage" reflects what you should do rather correct https://discord.js.org/#/

I guess some kind of notice in the README can be arranged, but its not something that has a very high priority.
