### ISSUE TITLE
Allow editing a message to surppress embeds

### ISSUE THREAD

**Issue by NotSugden** [discordjs/discord.js#3627]
**Is your feature request related to a problem? Please describe.**
About 3-4 weeks ago ish the discord api documentation was updated, you can now edit a messages flags to suppress embeds
**Describe the ideal solution**
Allow Message#edit to go through without an error if you're editing the flags and the message hasnt been sent by the bot
**Describe alternatives you've considered**

**Additional context**
https://discordapp.com/developers/docs/resources/channel#edit-message

> Edit a previously sent message. The fields content, embed, and flags can be edited by the original message author. __Other users can only edit flags and only if they have the `MANAGE_MESSAGES` permission in the corresponding channel__. When specifying flags, ensure to include all previously set flags/bits in addition to ones that you are modifying. Only flags documented in the table below may be modified by users (unsupported flag changes are currently ignored without error).

**Comment by vladfrangu** [comment]
This should be doable! It'll first go on the master branch tho, FYI!
