### ISSUE TITLE
Add "waitForReady" argument to ShardingManager.spawn(), like ShardingManager.respawnAll()

### ISSUE THREAD

**Issue by KevinNovak** [discordjs/discord.js#3630]
**Is your feature request related to a problem? Please describe.**
No, this is for consistency between spawn() and respawn() methods.

**Describe the ideal solution**
Add "waitForReady" argument to [ShardingManager.spawn()](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=spawn), like [ShardingManager.respawnAll()](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=respawnAll). The respawnAll() method has the ability to wait for a shard to become ready before spawning the next shard, I think this should also be possible when spawn() is called for the first time.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by appellation** [comment]
Since this isn't related to a problem, I'm not really seeing why this should be something we need to consider. Consistency for the sake of consistency is fine but doesn't seem like something worth prioritizing. You're welcome to implement this and PR if it bothers you that much.

**Comment by KevinNovak** [comment]
It seems like this is sort of resolved in the master branch [with the delay and spawnTimeout parameters](https://discord.js.org/#/docs/main/master/class/ShardingManager?scrollTo=spawn). Closing this issue.
