### ISSUE TITLE
problems with installing

### ISSUE THREAD

**Issue by aleUrwal** [discordjs/discord.js#3631]
when i try to install discord.js this happens:
`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`
can someone help me

**Comment by Monbrey** [comment]
You need to have git installed for npm to install the master branch.

If you have any further questions, please use the Discord server.
