### ISSUE TITLE
roleUpdate emits for every single role when a new role is created.

### ISSUE THREAD

**Issue by Twocoolguy** [discordjs/discord.js#3633]
**Please describe the problem you are having in as much detail as possible:**
The client on event roleUpdate emits for every single role when one new role is created.

**Include a reproducible code sample here, if possible:**
```js

bot.on("roleUpdate", (oldRole, newRole) => {
  var oldbase10color = oldRole.color;
  var oldhexcolor = oldRole.hexColor;
  var olddiffpos = oldRole.hoist;
  var oldmen = oldRole.mentionable;
  var oldname = oldRole.name;
  var oldperms = oldRole.permissions;
  var newbase10color = newRole.color;
  var newhexcolor = newRole.hexColor;
  var newdiffpos = newRole.hoist;
  var newmen = newRole.mentionable;
  var newname = newRole.name;
  var newperms = newRole.permssions;
  var time = getTime();
  //https://finitereality.github.io/permissions-calculator/?v=
  var rc = new Discord.RichEmbed()
    .setTitle("A new role has been updated!")
    .setDescription("Old name:\n```" + oldname + "```\nOld base 10 color:\n```" + oldbase10color + "```\nOld hex color:\n```" + oldhexcolor + "```\nOld display seperately from other roles:\n```" + olddiffpos + "```\nOld mentionable:\n```" + oldmen + "```\nOld perms:\n```" + oldperms + "```\nNew name:\n```" + newname + "```\nNew base 10 color:\n```" + newbase10color + "```\nNew hex color:\n```" + newhexcolor + "```\nNew display seperately from other roles:\n```" + newdiffpos + "```\nNew mentionable:\n```" + newmen + "```\nNew perms:\n```" + newperms + "```\nUpdated at:\n```" + time + "```")
    .addField("Old Permissions:", "https://finitereality.github.io/permissions-calculator/?v=" + oldperms)
    .addField("New Permissions:", "https://finitereality.github.io/permissions-calculator/?v=" + newperms)
    .setColor(0x00AE86);
  var guild = oldRole.guild;
  guild.channels.find("name", "logs").send(rc).catch(console.error);
});


```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 8.x
- Operating system: I do not know currently, the bot is running off of glitch.com
- Priority this issue should have – please be realistic and elaborate if possible: Not that huge but would be very nice to be fixed soon.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by PyroTechniac** [comment]
This is expected behavior, as when a role is created it updates the position of every other role.

**Comment by Twocoolguy** [comment]
> 
> 
> This is expected behavior, as when a role is created it updates the position of every other role.

But then why doesn't it do the same thing when you delete the role? When you delete the role it does not emit it every time like when it is created. If this is the case though, how would you make it stop doing this?

**Comment by Monbrey** [comment]
Either way, this really isn't a discord.js issue - it just emits the events it receives from Discord.

It's up to you to check what actually changed when the event is fired, and decide if you want to process it or not.

**Comment by SpaceEEC** [comment]
From a bit of testing it looks like Discord only ever updates positions of roles when it is necessary (role moved up or down).
Creating a role should not emit role updates, setting a position however will.
In case of discord.js, creating a role with a position will simply change it after creating, so an update occurs ([source]).

To avoid sending messages when nothing you care about changed, simply ensure that something you care about changed.
If you only cared about name changes, that could look like this:
`if (oldRole.name === newRole.name) return;`

[source]:https://github.com/discordjs/discord.js/blob/11.5-dev/src/client/rest/RESTMethods.js#L444
