### ISSUE TITLE
Add support for events MEMBER_MOVE (26) and MEMBER_DISCONNECT (27)

### ISSUE THREAD

**Issue by jasonkhanlar** [discordjs/discord.js#3634]
re: December 19, 2019 update:  **Audit Log got some love.** We added a ton of new Audit Log events to make moderation easier:
- MEMBER_MOVE, for when users are moved into move channels
- MEMBER_DISCONNECT for when users are kicked from a voice channel
- MESSAGE_BULK_DELETE
- MESSAGE_PIN
- MESSAGE_UNPIN
- BOT_ADD
- INTEGRATION_CREATE, INTEGRATION_UPDATE, and INTEGRATION_DELETE for server integrations like Twitch
- NOT_AGAIN_RYAN for when Ryan falls asleep on voice for the 10th time and you have to move him to another channel

related: <https://support.discordapp.com/hc/en-us/community/posts/360029502492-Extended-Audit-Logs-Log-Channel-Moving-Who-added-what-Bot-Who-moved-who-ect-?flash_digest=71b8e3c41f6522ee8e5e18f955b6a254f412913a&page=6>

related: https://github.com/discordapp/discord-api-docs/blob/master/docs/resources/Audit_Log.md

Mentioned in the official Discord.js server here:
https://discordapp.com/channels/222078108977594368/223867697312694272/657790131545309211

-

I'm interested in capability specifically for MEMBER_MOVE and MEMBER_DISCONNECT as a priority

**Comment by duckthecuck** [comment]
There was already a PR adressing this, #3584

**Comment by jasonkhanlar** [comment]
Ah, thanks!
