### ISSUE TITLE
crash on WebsocketShard.onOpen

### ISSUE THREAD

**Issue by NotSugden** [discordjs/discord.js#3641]
**Please describe the problem you are having in as much detail as possible:**
Seemingly at random, the bot crashed and i checked the error log and saw [this](https://cdn.discordapp.com/attachments/223867697312694272/658777384249589790/unknown.png), no idea how it happened, (im bad at describing so yell at me if i need to provide more info)

[WebsocketShard.js:252](https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketShard.js#L252)
**Include a reproducible code sample here, if possible:**
dont have a reproduicble code sample

**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: v12.14.0
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: maybe between moderate and high

- [x] I have also tested the issue on latest master, commit hash: 710101c5805935d7804fc8e53fa130541f248c54

**Comment by vladfrangu** [comment]
Can you please run `npm ls ws` and tell me what version you have?

**Comment by NotSugden** [comment]
> Can you please run `npm ls ws` and tell me what version you have?

7.2.1

**Comment by vladfrangu** [comment]
Soo, since this completely defeats me, I'm gonna have to ask you to do a couple of minor things and report back if this ever happens again!

1. Please follow the instructions here on [this](https://github.com/discordjs/discord.js/issues/3201) issue to enable debug logs that are NOT spammy
2. Monitor your bot. If it ever crashes again with that error, please provide logs of the crash error stack as well as the logs before it

If you cannot reproduce this anymore... Let us know too! Thanks <3

**Comment by BannerBomb** [comment]
I would like to say I have had this same issue a twice, it gets emitted from the `shardError` event. The first and last time the issue occurred for me was December 27 2019 which happened twice that day.
```assembly
TypeError: Cannot read property 'url' of null
    at WebSocketShard.onOpen (/opt/highlight/node_modules/discord.js/src/client/websocket/WebSocketShard.js:252:47)
    at WebSocket.onOpen (/opt/highlight/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:210:5)
    at WebSocket.setSocket (/opt/highlight/node_modules/ws/lib/websocket.js:172:10)
    at ClientRequest.<anonymous> (/opt/highlight/node_modules/ws/lib/websocket.js:646:15)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketOnData (_http_client.js:492:11)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:325:12)
    at readableAddChunk (_stream_readable.js:300:11)
```
Running `npm ls ws` for me shows
```console
highlight-improved@1.2.0 /opt/highlight
+-- discord.js@12.0.0-dev (github:discordjs/discord.js#50ed3293a57aeb0f9c094f00d49ed9874dc5d87a)
| ​`-- ws@7.2.1 
​`-- jsdom@15.2.1
  ​`-- ws@7.2.1  deduped
```
But I haven't had this issue since then.

**Comment by vladfrangu** [comment]
@BannerBomb Hi! Can you do what I suggested in https://github.com/discordjs/discord.js/issues/3641#issuecomment-568799365, and report back if this ever occurs again?

**Comment by BannerBomb** [comment]
yes
