### ISSUE TITLE
RichEmbed url property not accepting steam url

### ISSUE THREAD

**Issue by BosskHF** [discordjs/discord.js#3646]
**Please describe the problem you are having in as much detail as possible:**
Trying to use a steam launch url, eg: `steam://rungameid/730` as url property in a RichEmbed, but it throws this error: 

> UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.url: Not a well formed URL.

The DiscordAPIError part makes me fear that this has to do with Discord's API and not discord.js, but I'm hoping that this is not the case. Steam urls should be accepted by the API since Discord is/was primarily aimed towards the gaming community.

**Include a reproducible code sample here, if possible:**
```js

const launchGameEmbed = new Discord.RichEmbed()
		  .setColor('#0099ff')
		  .setTitle('Launch game')
		  .setURL("steam://rungameid/730");
		  message.channel.send(launchGameEmbed);
```

**Further details:**
- discord.js version: discord.js@11.5.1

**Comment by duckthecuck** [comment]
the Discord API only supports http(s) for its URLs

**Comment by BosskHF** [comment]
> the Discord API only supports http(s) for its URLs in embeds

Damn, thanks for the info. I'll have to redirect to the steam url or something then.
