### ISSUE TITLE
Question : command setting Language.

### ISSUE THREAD

**Issue by GongGu** [discordjs/discord.js#3647]
**Is your feature request related to a problem? Please describe.**

Hello , I am a Korean who develops in Korea.
I want other commands besides English.

```
//ENG Example It works normally
client.on('message', message => {
    if(message.content === 'ping') {
        message.channel.send('pong');
    }
});

//KOR Example It Not working
client.on('message', message => {
    if(message.content === '핑') {
        message.channel.send('퐁');
    }
});
// * '핑' is 'ping' , '퐁' is 'pong'


* * * * * * * * * * * * * * * * * * * * * * * * *
// prefix ('!');
else if (command === 'args-info') {
	if (!args.length) {
		return message.channel.send(`You didn't provide any arguments, ${message.author}!`);
	}

	message.channel.send(`Command name: ${command}\nArguments: ${args}`);
}
// In discord channel
//User : !args-info 안녕 하세요
//Bot : Command name: args-info
//        Arguments: 안녕,하세요

But Commands KOR
// prefix ('!');
else if (command === '명령') {
	if (!args.length) {
		return message.channel.send(`You didn't provide any arguments, ${message.author}!`);
	}

	message.channel.send(`Command name: ${command}\nArguments: ${args}`);
}
// In discord channel
//User : !명령 안녕 하세요
//Not Working.
```

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by duckthecuck** [comment]
Disclaimer: im not korean, but i cannot reproduce this issue, trying your exact code, it works perfectly fine using what you ask it to check for, besides, what would discord.js do? i dont see any way or reason to cater to korean developers, strings support korean characters, and checking for them works fine, on my end at least.
As you can see using 
```js
client.on('message', message => {
    if(!message.content.startsWith("!")) return;
    const args = message.content.slice(1).split(" ")
    const command = args[0]
    args.shift();
    if (command === '명령') {
        if (!args.length) {
            return message.channel.send(`You didn't provide any arguments, ${message.author}!`);
        }
    
        message.channel.send(`Command name: ${command}\nArguments: ${args}`);
    }
});
```
it works perfectly fine for me http://prntscr.com/qft0og

**Comment by GongGu** [comment]
Thank you for your kind answers and testing :)
![image](https://user-images.githubusercontent.com/37791550/71541000-cb8b6e80-2995-11ea-865e-263da95eabd9.png)

You tested the code.
I used your code.
But it is the same problem.

![image](https://user-images.githubusercontent.com/37791550/71541024-186f4500-2996-11ea-93f7-3d12c98e7b8b.png)


EX ) only change Command '명령' to 'abc Test
![image](https://user-images.githubusercontent.com/37791550/71541036-3341b980-2996-11ea-9549-f35c03ad1abc.png)
![image](https://user-images.githubusercontent.com/37791550/71541038-4785b680-2996-11ea-8406-343bdd279605.png)

**Comment by GongGu** [comment]
I changed the development OS.
window OS 10 to macos
Confirmed that Hangul is recognized.
I don't know why Windows OS doesn't work.
