### ISSUE TITLE
Add guild and channel id parameters to messageDeleteBulk event

### ISSUE THREAD

**Issue by zfbx** [discordjs/discord.js#3658]
**Is your feature request related to a problem? Please describe.**
Yes, In the event messageDeleteBulk is triggered and the messages weren't cached there's no way to grab the guild or channel that triggered the delete. since the snowflake is of a deleted message

**ideal solution**
The discord api seems to pass guild id and channel id in the event https://discordapp.com/developers/docs/topics/gateway#message-delete-bulk so adding those to the parameters (guild at least) would make it so you can at least log that a bulk delete happened to the proper guild

**Comment by Monbrey** [comment]
Is this in relation to stable (v11.5.1) or master? Have you tested this with Partials enabled on the master branch?

While you're right in that you wouldn't be able to fetch the deleted message, I'd just like to confirm that the partial data doesn't provide this already.

**Comment by zfbx** [comment]
it was in relation to master and I didn't know about Partials so after looking into them and playing with them, they're a great addition but wonky to deal with in this case since you have to check if it's a partial or if it's cached it triggers the event twice.. having guild and channel included in the parameters would be a lot more useful.

**Comment by Monbrey** [comment]
Partials don't (or at least shouldn't) trigger the event twice - if they are it's a bug. Are you also implementing `raw` handling somewhere - that could potentially trigger a second event.

**Comment by zfbx** [comment]
I have 
```js
async exec(messages) {
    const msg = messages.first();
    const channel = await this.client.guilds.get(msg.guild.id).channels.find((ch) => ch.name === 'logs');
    if (!channel || !msg.partial) {
        return null;
    }
    const embed = this.client.util.embed()
        .setColor('#cbdb15')
        .setAuthor('Bulk Of Messages Deleted', 'https://cdn.discordapp.com/attachments/662798521967181825/662805901362724891/deleted_message.png')
        .addField('Channel', `<#${msg.channel.id}>`, true)
        .addField('Messages Deleted', `${messages.size}`, true)
        .setFooter(`${utils.datetimestamp()}`);

    return channel.send({ embed }).catch(console.error);
}
```

and if I remove `!msg.partial` it sends twice the code i had in `raw` is commented out

**Comment by Monbrey** [comment]
It looks like this might be a bug which I've been able to replicate, `messageDeleteBulk` is firing twice in my code - once with no messages marked as partial, and once with them all marked as partial. Tested with various combinations of cached/uncached messages.

Will look into this further.

**Comment by Monbrey** [comment]
Looks like I wasn't testing on latest master - could you update yours and confirm if the issue still persists?
