### ISSUE TITLE
'connection' is not defined.

### ISSUE THREAD

**Issue by HappyFone** [discordjs/discord.js#3659]
trying to make a music discord bot but when i put this into my glitch code editor it said 
**"'connection' is not defined."**
is there something that I am missing?

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
