### ISSUE TITLE
Bot does not notice he has been disconnected after manual disconnecting from VoiceChannel

### ISSUE THREAD

**Issue by Jony635** [discordjs/discord.js#3662]
When you right click and disconnect a bot from the voice channel, any join attempt would asume there is already a connection set. It wont work until you disconnect through the VoiceConnection disconnect method first.

**Comment by almostSouji** [comment]
The issue templates are there for a reason, please don't just ignore them.

I remember these symptoms as they appeared for the master branch (version 12; developer build) in #3418 .The commit c6e8fccbf07a2ba2ac80d7e13f967eaa07c881f8 fixed this.

Should you still be able to reproduce it __after__ updating to after the referenced commit please provide your version `npm ls discord.js` (if master the exact commit you are using).
