### ISSUE TITLE
Issue with typings relating to @discordjs/collection.

### ISSUE THREAD

**Issue by sustained** [discordjs/discord.js#3701]
**Please describe the problem you are having in as much detail as possible:**

```
node_modules/discord.js/typings/index.d.ts:13:29 - 
  error TS2307: Cannot find module '@discordjs/collection'.

13  import BaseCollection from '@discordjs/collection';
                               ~~~~~~~~~~~~~~~~~~~~~~~
```

**Include a reproducible code sample here, if possible:**

https://github.com/sustained/i-hate-typescript

**Further details:**
- discord.js version: master
- Node.js version: 12.14.1
- Operating system: Fedora x86_64
- Priority this issue should have – please be realistic and elaborate if possible: I don't know how to prioritise your issues? Probably low.

- [x] I have also tested the issue on latest master, commit hash: 7f99be739aa7f11b6323a08d9435acb784aeb011

**Comment by iCrawl** [comment]
You should not install typescript globally and have it listed in your devDependencies.

Additionally your error is actually from not specifying:
```json
"module": "CommonJS",
"moduleResolution": "node",
```
inside of your `compilerOptions`

**Comment by sustained** [comment]
What? I never set any of those things in my tsconfig.json.

**Comment by sustained** [comment]
Never mind. Long day, already. I'll try that. Thank you very much!

**Comment by sustained** [comment]
That doesn't fix the issue...

**Comment by iCrawl** [comment]
```
{
  "compilerOptions": {
    "target": "es2020",
	"module": "CommonJS",
	"moduleResolution": "node",
    "outDir": "./dist",
    "baseUrl": ".",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "types": ["node", "discord.js", "klasa"]
  },
  "include": ["./**/*", "./data/**/*"],
  "exclude": ["**/node_modules"]
}
```

This is what is should look like.

**Comment by sustained** [comment]
Yeah, it started working after I force-reloaded the window, my apologies. Thank you, this issue plagued me for hours.
