### ISSUE TITLE
custom status for bots

### ISSUE THREAD

**Issue by VincetoDorito** [discordjs/discord.js#3702]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
I wish there was a command to change any discords bot status to custom.

**Describe alternatives you've considered**
The only things we can do right now are setgame and watch. There is no way to make a custom status.

**Additional context**
None

**Comment by iCrawl** [comment]
https://github.com/discordapp/discord-api-docs/issues/1160#issuecomment-546549711

Not yet possible anyway.
