### ISSUE TITLE
guildMember.addRole is not a function

### ISSUE THREAD

**Issue by juspitt** [discordjs/discord.js#3704]
Hello i am having an issue to assign a role to an user. 
here is my code

const guildMember = jsonContent.discord_id2;
guildMember.addRole('660040471900323860');
//guildMember.roles.add('660040471900323860');

i have tried both and either of them work.
value of guildMember is: <@439939747306012694>

can you please tell me what i am doing wrong?

Thanks.

**Comment by amishshah** [comment]
This issue tracker is for bug reports, if you have a question please ask on our [Discord server](https://discord.gg/bRCvFy9)
