### ISSUE TITLE
MessageCollector: max and maxMatches being treated as maxMatches

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#3717]
**Please describe the problem you are having in as much detail as possible:**

This should probably be added to <https://github.com/discordjs/discord.js/projects/5> to keep it in mind, since it should be fixed before the next release.

After a report on discord I did some research to find out what was going on with [MessageCollector](<https://discord.js.org/#/docs/main/stable/class/MessageCollector>) treating both max and MaxMatches exactly the same on both stable and 11.5-dev (on 12.0.0-dev the issue is not present due to a general overhaul)

The `max` option should end the collector regardless of the amount of messages that passes the filter as per its description, whereas `maxMatches` counts only messages passing the filter.
If both are present either condition should be able to end the collector.

So i started digging:
<https://github.com/discordjs/discord.js/blob/11.5-dev/src/structures/MessageCollector.js#L39-L41> causes the following:

- input: options.max is provided as 1 
- maxProcessed <- 1
- max -> 1
- max -> 1 (still!)

max however is supposed to replace maxMatches, as can be seen in line 41
this thus results into "max" causing both options to be set.

Now this part could be fixed, I attempted to do so while debugging:
```js
if (this.options.max && this.options.maxMatches) {
      this.options.maxProcessed = this.options.max;
      this.options.max = this.options.maxMatches;
    } else if (this.options.max) {
      this.options.maxProcessed = this.options.max;
      delete this.options.max;
    } else if (this.options.maxMatches) {
      this.options.max = this.options.maxMatches;
    }
```

The breakpoint after now results in the state as I expected it
- input options.max as 1
- maxProcessed -> 1
- max -> undefined

However the result is not that providing a non-filter-compliant input will just not trigger an end event at all. So why might that be the case...

[`postCheck` ](https://github.com/discordjs/discord.js/blob/11.5-dev/src/structures/MessageCollector.js#L82-L87 )never emits.
<https://github.com/discordjs/discord.js/blob/11.5-dev/src/structures/interfaces/Collector.js#L82> prevents this inherently from happening and emitting as expected.

Now I'm not too sure yet how this could be handled better without changing the entire Collector structure or might be blind enough to not see a very simple solution. If I did this would be a PR rather than an issue

However i am quite fascinated that this did not surface earlier and it should be fixed before another stable release.

**Include a reproducible code sample here, if possible:**
```js
const filter = msg => msg.content.toLowerCase() === 'a' && msg.author.id === message.author.id
message.channel.createMessageCollector(filter, {
        time: 1000000,
        max: 1
    })
    .on('end', (collected, reason) => {
        if (reason === 'time') return message.reply('the time is up!')
        message.reply('the answer got collected!' + reason)
    })
```

- send `a` => ends
- send `foo` => does not end

**Further details:**
- discord.js version: 36c0496ea5e0716a041fb85140e1351abab5c93a (11.5-dev) and 11.5.1
- Node.js version: 13.6.0
- Operating system: windows 10 V1909 OS Build 18363.592
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [x] I have also tested the issue on latest master, commit hash: 7f99be739aa7f11b6323a08d9435acb784aeb011
The problem does not exist on v12 due to the changed handling

**Comment by Monbrey** [comment]
> postCheck never emits

I'd suggest inverting the boolean logic so it doesn't return, set the collected value if it's valid, then perform a post check no matter what happened.
So this:
```js
_handle(...args) {
    const collect = this.handle(...args);
    if (!collect || !this.filter(...args, this.collected)) return;

    this.collected.set(collect.key, collect.value);

    /**
     * Emitted whenever an element is collected.
     * @event Collector#collect
     * @param {*} element The element that got collected
     * @param {Collector} collector The collector
     */
    this.emit('collect', collect.value, this);

    const post = this.postCheck(...args);
    if (post) this.stop(post);
  }
```
Would change to this:
```js
_handle(...args) {
    const collect = this.handle(...args);
    if(collect && this.filter(...args, this.collected)) {
        this.collected.set(collect.key, collect.value);

        /**
         * Emitted whenever an element is collected.
         * @event Collector#collect
         * @param {*} element The element that got collected
         * @param {Collector} collector The collector
         */
        this.emit('collect', collect.value, this);
    }
    const post = this.postCheck(...args);
    if (post) this.stop(post);
  }
```
Thoughts?

**Comment by Monbrey** [comment]
So I somehow managed to get the solution right while being too tired to realise Space had already fixed it.

At least my suggestion was the same lmao
