### ISSUE TITLE
voiceStateUpdate destroyes channel on user selfmute or selfdefean

### ISSUE THREAD

**Issue by ch3rn1k** [discordjs/discord.js#3721]
**Please describe the problem you are having in as much detail as possible:**
Got a problem with creating bot with feature of creating private rooms on joining specific voice channel. Bot creates room with permission overrides and moving user to it, thats ok. BUT, when this "admin" selfmutes of selfdefeans - room automatically destroyes. Hope someone can explaing or help!

**Include a reproducible code sample here, if possible:**
```js
bot.on('voiceStateUpdate', async (oldMember, newMember) => {
  let oldUserChannel = oldMember.voiceChannel;
  let newUserChannel = newMember.voiceChannel;

  /** On user join voice channel. Creating new voice with his name. */
  if (!oldUserChannel && newUserChannel) {
    if (newMember.voiceChannel.name !== channelToJoinName) return;

    let channel = await buildChannel(newMember);

    /** If channel created moving user into it. */
    if (channel)
    newMember.setVoiceChannel(channel);
  }
});
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.14.1
- Operating system: Ubuntu 18.01
- Priority this issue should have – please be realistic and elaborate if possible: idk

**Comment by SpaceEEC** [comment]
I assume with "destroy" you mean "delete".

This sounds more like you are handling something incorrectly in your code (which is not part of your sample here).

You are probably better off asking about this in the [Discord server](https://discord.gg/bRCvFy9) as our issue tracker is only for bug reports and enhancement suggestions.
