### ISSUE TITLE
guild.createdAt and guild.joinedAt doesnt return the correct time.

### ISSUE THREAD

**Issue by galoncyryll** [discordjs/discord.js#3724]
**Please describe the problem you are having in as much detail as possible:**
the properties createdAt and joinedAt doesn't show the correct time/date.

**Include a reproducible code sample here, if possible:**
```js
// returns 1 year after the guild was created.
console.log(message.guild.createdAt);

```

**Further details:**
- discord.js version: ^11.5.1
- Node.js version: v12.14.1
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iDroid27** [comment]
Values are correct on my end using the same discord.js/node version.
How do you use these values in your code ?
