### ISSUE TITLE
voiceChannel.disconnect()

### ISSUE THREAD

**Issue by YeetbenderDamB** [discordjs/discord.js#3725]
**Please describe the problem you are having in as much detail as possible:**
Bot will not disconnect from voice channel when prompted to using the .disconnect() function.

**Include a reproducible code sample here, if possible:**
```js
case "stop": //Stop command for music
            var server = servers[msg.guild.id];
            if(msg.guild.voiceConnection) {
                for(var i = server.queue.length -1; i <= 0; i--) {
                    server.queue.splice(i, 1);
                }
                server.dispatcher.end();
                msg.channel.send('Stopping all playback and deleting the queue.');
                console.log('Stopped the queue.');
            }
            if(msg.guild.connection) msg.guild.voiceConnection.disconnect();
            break;
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 0.0.0
- Operating system: Windows 10 64-bit
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
You are checking `msg.guild.connection` instead of `msg.guild.voiceConnection` - there doesn't exist a connection property on Guild.

**Comment by YeetbenderDamB** [comment]
Even after changing, the bot still won't leave.
