### ISSUE TITLE
webhookUpdate event fires twice when creating a new webhook

### ISSUE THREAD

**Issue by VC-Semih** [discordjs/discord.js#3730]
The webhookUpdate even fires once when pressing create webhook and then fires again when clicking Save
![Code](https://user-images.githubusercontent.com/55637588/72800871-9a2a5980-3c48-11ea-95bf-654bf254afaa.png)
![Pressed Create](https://user-images.githubusercontent.com/55637588/72800883-9dbde080-3c48-11ea-88a0-8dcb11ed4ebf.png)
![Pressed Save](https://user-images.githubusercontent.com/55637588/72800888-a1516780-3c48-11ea-9f57-c3f4273bc802.png)

**Comment by Monbrey** [comment]
Please don't ignore the issue template, it exists for a reason.

However, this is expected behaviour. I've checked, Discord emits WEBHOOK_UPDATE events at both creation and save, therefore discord.js does also.
