### ISSUE TITLE
ClientUser#verified and ClientUser#mfaEnabled don't get set correctly

### ISSUE THREAD

**Issue by NotSugden** [discordjs/discord.js#3732]
**Please describe the problem you are having in as much detail as possible:**
When checking [ClientUser#mfaEnabled](https://github.com/discordjs/discord.js/blob/stable/src/structures/ClientUser.js#L68) (and [ClientUser#verified](https://github.com/discordjs/discord.js/blob/master/src/structures/ClientUser.js#L23)), mfaEnabled is null and verified is undefined, so, i restarted the process with a raw event listener, which logged this
```js
{
  v: 6,
  user_settings: {},
  user: {
    verified: true,
    username: '<bot username>',
    mfa_enabled: true,
    id: '<bot id>',
    email: null,
    discriminator: '<bot discrimnator>',
    bot: true,
    avatar: '<bot avatar>'
  }
```
which has the `verified` and `mfaEnabled` properties in the user object,
which is passed into the ClientUser constructor [here (src/client/websocket/handlers/READY.js Line 10)](https://github.com/discordjs/discord.js/blob/877577badcaa17b0221b75d79c55b6de3eff4e3a/src/client/websocket/handlers/READY.js#L10), and then the `_patch` function called [here (src/structures/User.js Line 35)](https://github.com/discordjs/discord.js/blob/877577badcaa17b0221b75d79c55b6de3eff4e3a/src/structures/User.js#L35)

[ClientUser#_patch](https://github.com/discordjs/discord.js/blob/877577badcaa17b0221b75d79c55b6de3eff4e3a/src/structures/ClientUser.js#L16)
**Include a reproducible code sample here, if possible:**
No reproducible code sample

**Further details:**
- discord.js version: master
- Node.js version: 12.14.1
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: low

- [x] I have also tested the issue on latest master, commit hash: 877577badcaa17b0221b75d79c55b6de3eff4e3a

**Comment by Monbrey** [comment]
This appears to be because like any other User, the ClientUser gets patched with any gateway event that would do so, however these properties aren't actually defined in regular user payloads as far as I can tell.

As a result, as soon as a second patch comes in (mine received three before even becoming ready) `ClientUser#_patch` replaces them with undefined/null

```js
// ClientUser.js
  _patch(data) {
    console.log("Patching", data);
    super._patch(data);

    /**
     * Whether or not this account has been verified
     * @type {boolean}
     */
    this.verified = data.verified;

    /**
     * If the bot's {@link ClientApplication#owner Owner} has MFA enabled on their account
     * @type {?boolean}
     */
    this.mfaEnabled = typeof data.mfa_enabled === 'boolean' ? data.mfa_enabled : null;

    if (data.token) this.client.token = data.token;
  }
```
Output:
```js
Patching {
  verified: true,
  username: 'Kauribot [DEV]',
  mfa_enabled: true,
  id: '554558672085450752',
  email: null,
  discriminator: '8669',
  bot: true,
  avatar: null
}
Patching {
  username: 'Kauribot [DEV]',
  id: '554558672085450752',
  discriminator: '8669',
  bot: true,
  avatar: null
}
Patching {
  username: 'Kauribot [DEV]',
  id: '554558672085450752',
  discriminator: '8669',
  bot: true,
  avatar: null
}
```
