### ISSUE TITLE
Magnet URI support in Embeds

### ISSUE THREAD

**Issue by rajatpundir** [discordjs/discord.js#3738]
Hi,

I want to be able to set and open magnet links from within embeds.

You can find details on format of magnet links [https://en.wikipedia.org/wiki/Magnet_URI_scheme](url) .

Thanks.

**Comment by iCrawl** [comment]
We are only a wrapper around the discord-api and not Discord itself. 

For feature requests use: https://support.discordapp.com/hc/en-us/community/topics

**Comment by Monbrey** [comment]
Discord.js doesn't define URL support for embeds - it's entirely up to what the Discord API will accept.

You can try asking them over here: https://github.com/discordapp/discord-api-docs
