### ISSUE TITLE
Discord.js error

### ISSUE THREAD

**Issue by Diclozaur** [discordjs/discord.js#3739]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js

// Place your code here

const Discord = require("discord.js");
const bot = new Discord.Client({disableEveryone: true});

bot.on("ready", async () => {
    console.log(`${bot.user.username} este online`)
    bot.user.setActivity("=help | Pixel-Craft", {type: "STREAMING"});

})

bot.on(message, async message => {
    if (message.author.bot || message.channel.type === "dm") retrun;

    let prefix = botconfig.prefix;
    let messageArray = message.content.split("")
    let cmd = messageArray[0];
    let args = messageArray.slice(1);

    if(cmd === `${prefix}Hey`){
        return message.channel.send("Buna")
    }

})

bot.login(botconfig.token);
```
bot.on(message, async message => 
{        ^  ReferenceError: message is not defined

This is the error given, but i can't figure it out.

**Further details:**
- discord.js version: 11.5.1
- Node.js version: v 12.14.1
- Operating system: Windows 10 
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by RDambrosio016** [comment]
The issue tracker is for issues with the actual library, please use the discord server for things like this:
https://discord.gg/bRCvFy9.
Also, your issue is the event name should be a string, `”message”`
