### ISSUE TITLE
client.channels.get().setName(``); works worst

### ISSUE THREAD

**Issue by EVgenyGP** [discordjs/discord.js#3748]
If the user changes their status between "online" and "offline" very often, the bot stops changing the channel name, but continues to register the number of people correctly.
I also noticed that he registers one specific user 2 times, that is:
CONSOLE: ```
1 (ME) precenceUpdate > Offline (~11 people)
2 (ME) precenceUpdate > Online (~12 people)
3 (HE) precenceUpdate > Offline (~11 people)
4 (HE) precenceUpdate > Offline (~11 people)
5 (HE) precenceUpdate > Online (~12 people)
6 (HE) precenceUpdate > Online (~12 people)
```

```js
client.on("presenceUpdate", () => {
    client.channels.get("Channel ID").setName(`Online: ${OnlineUsers()}`);
});

function OnlineUsers (users) {
    var users = client.guilds.first().members.filter(m => m.user.presence.status === 'online').size
    users += client.guilds.first().members.filter(m => m.user.presence.status === 'idle').size
    users += client.guilds.first().members.filter(m => m.user.presence.status === 'dnd').size
    return users;
}
```

**Further details:**
- discord.js version: latest
- Node.js version: latest
- Operating system: Windows 10

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by RDambrosio016** [comment]
PresenceUpdate is emitted a LOT (its 90%+ of events received), you should not be doing this, the reason it cannot set that fast is because of ratelimiting, discord does not want you to do this, so it limits you. Eitherways you should definitely **not** do this
