### ISSUE TITLE
Caching audio stream for reuse?

### ISSUE THREAD

**Issue by LordRampantHump** [discordjs/discord.js#3750]
I i want to make a radio station bot how can i cache the audio stream so that its not downloading and encodeing it for each instance?

Lets pretend something like this:

`let cachedAudioStream = cacheArbitraryInput('http://philae.shoutca.st:8950/live', {});`

then for every instance outgoing:
```
connection1.playArbitraryInput(cachedAudioStream, { volume: 0.5 });
connection2.playArbitraryInput(cachedAudioStream, { volume: 0.8 });
connection3.playArbitraryInput(cachedAudioStream, { volume: 1 });
```
Can this be done? 

StackOverflow:
https://stackoverflow.com/questions/59919510/discord-js-playing-audio-on-multiple-servers

**Comment by Androz2091** [comment]
And if you already posted your question on StackOverflow less than an hour ago, why are you posting it here?

**Comment by LordRampantHump** [comment]
> And if you already posted your question on StackOverflow less than an hour ago, why are you posting it here?
