### ISSUE TITLE
connection.playFile() not working

### ISSUE THREAD

**Issue by SudhanPlayz** [discordjs/discord.js#3755]
.playFile() is not working. No Errors too

My Code Below
```
    const voicechannel = message.member.voiceChannel
    
    if (voicechannel) {
       
      const connection = await voicechannel.join().then(async connection =>{
        const dispatcher = await connection.playFile('https://cdn.glitch.com/0c2bdbfc-5fce-47cd-a82f-7460fce155b2%2FAlexa_joins.mp3', {
          volume: "5"
        });
      }).catch(err => {
        console.log(err)
               message.channel.send("Error: "+err)
      });
      message.channel.send(emoji.alexaloading + " Connected to <#"+voicechannel.id+">")
      
    }else {
      message.reply('You need to join a voice channel first to make me Speak');
    }
```

**Comment by SpaceEEC** [comment]
[`VoiceConnection#playFile`](https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=playFile) uses the [`file](https://ffmpeg.org/ffmpeg-protocols.html#file) protocol of FFmpeg and thus can not play anything remote.

You either want to download the file and use the local version or use [`VoiceConnection#playArbitraryInput`](https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=playArbitraryInput).
