### ISSUE TITLE
Support for upcoming gateway intents

### ISSUE THREAD

**Issue by Neuheit** [discordjs/discord.js#3764]
**Is your feature request related to a problem? Please describe.**
This issue is related to the upcoming intents that will be need to be specified by bots when interacting with the gateway. In the future, rather than receiving all WS events by default, Discord will be implementing a subscription system based on entered bitwise flags regarding which events to receive.

**Describe the ideal solution**
These intents will be needed to be added as a property in the client configuration. 

**Additional context**
More details can be found here: https://github.com/discordapp/discord-api-docs/pull/1307
Issue regarding `Privileged Intents`: https://github.com/discordapp/discord-api-docs/issues/1363

**Comment by Monbrey** [comment]
Thanks for the issue - several members of the dev team are already aware and have been working on / testing the changes to the gateway.

**Comment by Neuheit** [comment]
Ah gotcha. Want me to close this issue then?

**Comment by advaith1** [comment]
Intents can already be set as `intents: int` in `ws` in `ClientOptions` (since discord.js doesn't check the ws options, it just sends the raw data to Discord), however, it would be useful for a system to make them easier to set (maybe like how disabledEvents is handled?)
