### ISSUE TITLE
Error: Members didn't arrive in time.

### ISSUE THREAD

**Issue by ndaniel10** [discordjs/discord.js#3774]
Discord bot not caching all members and giving wrong member count

**Comment by RDambrosio016** [comment]
This has been a recurring issue the past few days, it is not a library problem. There seems to be issues with the guild members chunk event not working properly. It is an API issue out of our control.

P.S.: you should not ignore the issue template 👀

**Comment by SpaceEEC** [comment]
It looks like Discord sends those packets (again), at least for me.

**Comment by encloinc** [comment]
Same thing happening here

**Comment by Hey** [comment]
Same thing here

**Comment by ToxicFrog** [comment]
This has been happening consistently to me for a while now.

If it is a problem at Discord's end, I wonder if they broke something when rolling out intent support -- I know intents are meant to be optional right now, but maybe they're not as optional as they should be.

**Comment by Monbrey** [comment]
Given that fetching all members was the one intent that they planned on restricting, I don't think this is "broken" but we'd definitely need more information from you all to try to help determine a real cause. Probably most notably - how many guilds is your bot impacted by this issue in?

Of course, if you're all logging in with user tokens, then A) you shouldn't be anyway since its against ToS and B) this is expected behaviour for user accounts

**Comment by KevinNovak** [comment]
When I do
```typescript
await guild.members.fetch();
```
I'm getting the following error message:
`[GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.`

My bot is connected to ~5,000 guilds, and this always happens on the same 3 guilds. I read this might have to do with large guilds, however they're not particularly large at 134, 632, and 1078 members (logging with `guild.memberCount`). Any ideas what might be causing this and what I can do?

**Comment by scottbucher** [comment]
I tend to get this error a lot when fetching all the guild members but when it fails I fall back to the cache. However, I did notice something interesting.

Whenever I am getting this error (I print out the `guild.memberCount()` and the `guild.members.cache.size`) the difference between the member count and cache size is almost always 1 (highest I have seen is 3-4). This makes me feel like the fetch() isn't fully failing, and it might only be failing to fetch one or a few members.
![image](https://user-images.githubusercontent.com/47844014/87080823-54614d80-c1f6-11ea-9890-488aab7efef5.png)

**Comment by Kotosif** [comment]
Hitting the same issue today

**Comment by Thornsnake** [comment]
Dito, hitting the same issue today.

**Comment by Extroonie** [comment]
As of *27/10/2020* (warned since October 7, 2020), Discord has started enforcing intents and developers are required to enable them for receiving certain gateway events. Read the guide on [intents](https://discordjs.guide/popular-topics/intents).

**Comment by DarkMatterMatt** [comment]
Extrapolating on Extroonie's comment above, this can be resolved by requesting the `GUILD_MEMBERS` intent.

Steps:
1a. Go to https://discord.com/developers/applications
1b. Select your application, move to the Bot tab in the sidebar
1c. Enable "server members intent"
2a. Import `Intents` from `discord.js`
2b. Pass custom intents as websocket options when creating the client.

Code (before):
```js
const { Client } = require("discord.js");
const client = new Client();
```
Code (after):
```js
const { Client, Intents } = require("discord.js");
const intents = new Intents([
    Intents.NON_PRIVILEGED, // include all non-privileged intents, would be better to specify which ones you actually need
    "GUILD_MEMBERS", // lets you request guild members (i.e. fixes the issue)
]);
const client = new Client({ ws: { intents } });
```

References:
https://discordjs.guide/popular-topics/intents.html#privileged-intents
https://discord.js.org/#/docs/main/stable/class/Intents

**Comment by almostSouji** [comment]
> 2. Make code changes

No code changes needed. You don't need to necessarily provide the intents for version 12 of discord.js.
If you provide no intents to the Client constructor discord will just send all events for all intents (privileged intents require the toggle or explicit grant in case of bot verification (100+ servers). This will change in v13 where intents will be required.

**Comment by JosefBud** [comment]
> As of _27/10/2020_ (warned since October 7, 2020), Discord has started enforcing intents and developers are required to enable them for receiving certain gateway events. Read the guide on [intents](https://discordjs.guide/popular-topics/intents).

Thank you @Extroonie ! I could not figure this out this morning, you're a life saver!

**Comment by kiyokodyele** [comment]
This happened to my discord server after having 1500+ members.

**Comment by monbrey** [comment]
> This happened to my discord server after having 1500+ members.

Well then since this already has a solution, please follow it.

**Comment by bala41288** [comment]
>As of 27/10/2020 (warned since October 7, 2020), Discord has started enforcing intents and developers are required to enable them for receiving certain gateway events. Read the guide on intents.

It took me several days to reach here. I wish I had found this long back. Thank you @Extroonie

**Comment by MDxWARRIORxOP** [comment]
i am still getting this error in discord.js v14, i have my intents on (in both the dev portal and the code) but im still getting this error, none of the above answers seemed to help

**Comment by JRTMediaUK** [comment]
Also having this issue, not an intents problem as all enabled on the dev portal and all intents added.

**Comment by bala-techguy** [comment]
> i am still getting this error in discord.js v14, i have my intents on (in both the dev portal and the code) but im still getting this error, none of the above answers seemed to help

I had the problem in v14 and it was resolved by adding the below: 

```
const { Client, GatewayIntentBits, Partials } = require('discord.js');

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.DirectMessages, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent],
  partials: [Partials.Channel],
});

client.login(config.token);

```

After I added `GatewayIntentBits.GuildMembers`, I did not get this error message.

**Comment by almostSouji** [comment]
This issue is by now very outdated and originally was happening for very different reasons.
If you still run into this error, please fill out a new issue, as we are currently supporting both v13 and v14 the treatment varies.

Generally speaking, the reasoning is still the same I outlined in https://github.com/discordjs/discord.js/issues/3774#issuecomment-717826819 , but with applying new enums or at least PasCase flag names, as shown in https://github.com/discordjs/discord.js/issues/3774#issuecomment-1228161816
