### ISSUE TITLE
Remove actions/handlers or refactor them to have a clearer distinction of their purpose

### ISSUE THREAD

**Issue by RDambrosio016** [discordjs/discord.js#3790]
Discord.js master has introduced the concept of Actions, which are defined as:
> Actions are similar to WebSocket Packet Handlers, but since introducing the REST API methods, in order to prevent rewriting code to handle data,"actions" have been introduced. They're basically what Packet Handlers used to be but they're strictly for manipulating data and making sure that WebSocket events don't clash with REST methods.

However, the distinction between what is supposed to do what has been lost and ignored. Take for example `GUILD_BAN_ADD` and `GUILD_BAN_REMOVE`. This is the corresponding code for handling each event:
```js
  const guild = client.guilds.cache.get(data.guild_id);
  const user = client.users.add(data.user);

  /**
   * Emitted whenever a member is banned from a guild.
   * @event Client#guildBanAdd
   * @param {Guild} guild The guild that the ban occurred in
   * @param {User} user The user that was banned
   */
  if (guild && user) client.emit(Events.GUILD_BAN_ADD, guild, user);
```
And
```js
    const client = this.client;
    const guild = client.guilds.cache.get(data.guild_id);
    const user = client.users.add(data.user);
    /**
     * Emitted whenever a member is unbanned from a guild.
     * @event Client#guildBanRemove
     * @param {Guild} guild The guild that the unban occurred in
     * @param {User} user The user that was unbanned
     */
    if (guild && user) client.emit(Events.GUILD_BAN_REMOVE, guild, user);
```
Nearly identical, right? the issue is that one is a handler and one is an action. the only clue being the access of the client in the GuildBanRemove action. As you can see there is no amount of distinction of what a handler should do, and what an action should do. This is evidenced by the fact that:

- Some handlers only call an action, e.g. `CHANNEL_DELETE`, and `CHANNEL_CREATE`.
- Some handlers do not call actions at all (despite not using any websocket properties), e.g. `CHANNEL_PINS_UPDATE`.
- Some handlers call actions AND have their own logic but do not use any websocket data, e.g. `CHANNEL_UPDATE`.
- Some handlers call actions but pass websocket properties into it! e.g. `GUILD_MEMBER_REMOVE`.
- Some handlers do not call actions but do not interact with cache at all. e.g. `RESUMED`

This is confusing for maintainers, it brings about uncertainty of where the logic for an event should go. The distinction should be made clearer or one or the other must handle all of the logic.

**Describe the ideal solution**
Remove Actions and have a handler do everything, packets should not be bouncing around between two places and should just be handled in one central spot. However, other places rely on calling actions by themselves, such as Guild.

**Describe alternatives you've considered**
Make the distinction between what a handler should do and what an action should do clearer and rework existing mistakes. In my opinion the ideal distinction would be:
- The logic of getting cache data from packet data or creating new cache data should go on an Action
- Logic which interacts with websocket concepts such as the shard and the websocket's state go on the handler

The issue with this is some handlers must interact with cache throughout the handler function, and the cache changes cannot be applied in a single function.

**Comment by appellation** [comment]
I think actions are leftover from a long time ago. While we've done numerous rewrites on the WS itself or the resulting data structures, we haven't really touched the actual event handling logic since it's "just worked" relatively flawlessly.

In this case, I feel like there's relatively little to be gained from doing a rewrite of this area and a significant amount to lose by doing this wrong. You are technically correct and the actions/handlers implementation is not in-line with our current design; that being said, I would be hesitant to mess with something that's currently working well (especially since we have absolutely no unit tests to verify that any changes produce the same results).

**Comment by iCrawl** [comment]
This won't happen before a complete rewrite of the library, so I'm going to close this as we move forward and decide how we will implement this.
