### ISSUE TITLE
(node:4840) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.

### ISSUE THREAD

**Issue by CyberTailsDiscord** [discordjs/discord.js#3796]
I have an error happening unknown why. Incorrect login details were provided as I know it is due to an invalid token or it is missing. I even tried to generate a new token, insert it on a new one, but in the end, as I enter node.js, this error pops up. What am I doing wrong that this error appears when the token is correct and there are no errors in the code?

Load 1 command('s)
1.help.js loaded
(node:10680) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\user\Desktop\MyBot\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:428:26)
    at WebSocketConnection.emit (events.js:321:20)
    at WebSocketConnection.onClose (C:\Users\user\Desktop\MyBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\user\Desktop\MyBot\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.emitClose (C:\Users\user\Desktop\MyBot\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\user\Desktop\MyBot\node_modules\ws\lib\webs    at TLSSocket.emit (events.js:333:22)
    at net.js:668:12
(node:10680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on 
unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

botconfig.json:
{
    "token": "(Well, you know what the correct token is.)",
    "prefix": "!"
}

bot.js:
const Discord = require('discord.js');
const bot = new Discord.Client();
bot.commands = new Discord.Collection();
const fs = require('fs');
let config = require('./botconfig.json');
let token = config.token;
let prefix = config.prefix;

fs.readdir('./cmds/',(err,files)=>{
    if(err) console.log(err);
    let jsfiles = files.filter(f => f.split(".").pop() === "js");
    if(jsfiles.length <=0) console.log("Commands not found");
    console.log(`Loaded ${jsfiles.length} command('s)`);
    jsfiles.forEach((f,i) =>{
        let props = require(`./cmds/${f}`);
        console.log(`${i+1}.${f} loaded`);
        bot.commands.set(props.help.name,props);
    })
})

bot.on('ready', () => {
  console.log(`Bot ${bot.user.username} started`);
  bot.generateInvite(["ADMINISTRATOR"]).then(link =>{
      console.log(link);
  })
});

bot.on('message', async message => {
    if(message.author.bot) return;
    if(message.channel.type == "dm") return;
    let user = message.author.username;
    let userid = message.author.id;
    let messageArray = message.content.split(" ");
    let command = messageArray[0].toLowerCase();
    let args = messageArray.slice(1);
    if(message.content.startWith(prefix)) return;
    let cmd = bot.commands.get(command.slice(prefix.length));
    if(cmd) cmd.run(bot,message,args);
});

bot.login('token');

help.js:
const Discord = module.require("discord.js");
const fs = require("fs");
module.exports.run = async (bot,message,args) => {
    message.channel.send('I don't have a command yet((');
};
module.exports.help = {
    name: "help"
};

**Comment by vladfrangu** [comment]
Firstly, please reset your bot token! 

Secondly, please fill in the template you deleted... What discord.js version are you running? If 12.0, what commit?

**Comment by CyberTailsDiscord** [comment]
> Firstly, please reset your bot token!
> 
> Secondly, please fill in the template you deleted... What discord.js version are you running? If 12.0, what commit?

I had to specify the version of discord.js when node install discord.js?

**Comment by tipakA** [comment]
No, when you opened this issue.
No one here is a mind reader to know exactly what is the problem you're experiencing, so you should fill the issue template you deleted, so we could have at least any idea on what could be happening.
Simply saying "it doesn't work" will not magically make it work.
Additionally, you might want to take this issue to [support server](https://discord.gg/bRCvFy9) for faster and easier communication.

**Comment by markokajzer** [comment]
Your login details are incorrect mate.

You need this ClientID

![Anmerkung 2020-02-16 213252](https://user-images.githubusercontent.com/9379317/74612256-ec558200-5103-11ea-8806-7a2ce0531847.png)

and this token

![Anmerkung 2020-02-16 213228](https://user-images.githubusercontent.com/9379317/74612266-055e3300-5104-11ea-92e9-dfb6a4cec352.png)
