### ISSUE TITLE
Suggestion: Ability to add/set ffmpeg arguments

### ISSUE THREAD

**Issue by noftaly** [discordjs/discord.js#3803]
Hi, I'd like to have the possibility to add or set Ffmpeg arguments (which are set in [BasePlayer.js](https://github.com/discordjs/discord.js/blob/master/src/client/voice/player/BasePlayer.js))

**Is your feature request related to a problem? Please describe.**
I wanted to make a bass-boost command, which requires to change the encoder's arguments, but it is currently not possible with discord.js.

**Describe the ideal solution**
There are multiple options of which I thought, all pretty user-friendly, so it is up to you to see the one which is easier to implement and ideal:
- add a method to idk-which-class (AudioPlayer?) to set or add Ffmpeg arguments,
- just to make the array FFMPEG_ARGUMENTS property of the class, instead of an external constant.
- pass the arguments into the .play() method, as Eris:
```js
client.voiceConnections.get(guildId).voiceConnection.play(URL, {
    encoderArgs: ['-af', `equalizer=f=40:width_type=h:width=50:g=${gain}`],
});
```
Thanks !

**Comment by INEX07** [comment]
Check #2894

```js
let FFmpegArgs = [
        "-analyzeduration", "0",
        "-loglevel", "0",
        "-f", "s16le",
        "-ar", "48000",
        "-ac", "2",
        // your -af equalizer
    ];
    let transcoder = new prism.FFmpeg({
        args: FFmpegArgs
    });
    let inputStream = ytdl(url, options); // ytdl
    let output = inputStream.pipe(transcoder);
    <voiceChannelConnection>.playConvertedStream(output);
```

**Comment by noftaly** [comment]
Yes, I saw that, and I manage to make it work.
But I still think it should be added as a feature of discord.js, because apparently multiple people needed it, and it would be cool 🤷‍♂ (yeah I don't really have any other arguments...)

**Comment by iCrawl** [comment]
I would argue this is a good enough compromise, no reason to put this directly into the library.
