### ISSUE TITLE
Update Prism-media Dependency 1.0.0 => 1.2.0

### ISSUE THREAD

**Issue by dyontaistaton** [discordjs/discord.js#3817]
**Having a Dockerized Bot, which joins a voice channel, is near impossible**
Currently, running a docker contained bot on a system that needs different binaries than those provided in "ffmpeg-binaries". These ffmpeg binaries are not compatible with Linux systems and possibly other systems & making a work-around for this is hard as hell.

**Solution - Update Prism-media Dependency 1.0.0 => 1.2.0**
prism-media 1.2.0 has added support for "ffmpeg-static" instead of "ffmpeg-binaries" allowing for ffmpeg binaries to built on "npm install" depending on the current machine, making Discordjs support dockerized applications.

**Other Solution - Add ability to plugin ffmpeg binaries in runtime**
Add the possibility of changing the current ffmpeg binary path doing runtime. These binaries would be install outside of prism-media, ffmpeg-binaries, and any other npm package. 

**Conflicts of Changes**
Doing this might cause current BasePlayer Class to break, due to prism-media 1.0.0 => 1.2.0 function name changes, but this should be easily fixed by reflecting these updates in the current BasePlayer Class

**Comment by iCrawl** [comment]
If you are running a dockerized container, whether that be some debian/ubuntu image (slimmed down or not) OR an alpine image, you have full control over the environment so natively installing `ffmpeg` on the Docker image (via the Dockerfile) should be very easy.

So I don't quite understand how it is making "discord.js" support dockerized applications this way.
`ffmpeg-binaries` (old) and `ffmpeg-static` (new) is mainly there for users who do not understand how to install `ffmpeg` on windows or linux or in a development enviroment (again windows or linux with barely any experience)
