### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by dhBunny** [discordjs/discord.js#3818]
Some discord.js files are returning the error of `Unexpected token {`

Some of the files doing so can be found [here](https://i.imgur.com/rRnbSUj.png) and [here](https://i.imgur.com/fNKMHc8.png) -- Both are screenshots.

As far as I know JavaScript, I think it should be replaced with this:
```js
} catch (e) {
```

(as part of the `trycatch` method)

**Comment by NotSugden** [comment]
you need to update your node version, seems your version is lower than the required version (iirc, 8.0.0 for stable and 10.2.0 for master)
