### ISSUE TITLE
ColorResolvable includes "WHITE" as an option

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#3840]
**Please describe the problem you are having in as much detail as possible:**
Hi, I notice that "WHITE" is an acceptable `ColorResolvable`, but Discord itself doesn't support embeds with a int of 16777215 (which is #FFFFFF) and Discord reverts it to the default embed colour on desktop... should this be removed?

Here is a bug report made about this change: https://trello.com/c/RjoeLmJB, which is listed as not a bug.

**Include a reproducible code sample here, if possible:**
```js
const { MessageEmbed } = require("discord.js");
const embed = new MessageEmbed();
embed.setTitle("White");
embed.setColor("WHITE");
client.channels.resolve("id").send(embed);
```

**Further details:**
- discord.js version: Master
- Node.js version: 12.6.0
- Operating system: macOS
- Priority this issue should have – please be realistic and elaborate if possible: Low.

- [x] I have also tested the issue on latest master, commit hash: c4bda74

**Comment by uhKevinMC** [comment]
It's left in on purpose so the library doesn't error whenever someone uses **WHITE** as a colorResolvable. I'd rather have it in place in case discord does make that addition, so people don't have to recommit **WHITE** as a colorResolvable.

**Comment by Jiralite** [comment]
At the very least it should be removed from the docs... I see white there, I use it, I don't get white?

**Comment by Darqam** [comment]
If currently using WHITE yields nothing, it might be more interesting to make WHITE yield a virtually-white color instead.

**Comment by NotSugden** [comment]
> If currently using WHITE yields nothing, it might be more interesting to make WHITE yield a virtually-white color instead. (i.e : 16777214 instead of 16777215)

i think thats a better idea than removing it, also as a sidenote the embeds still render normally on mobile, its just desktop that defaults the color

**Comment by Jiralite** [comment]
Actually, looking closer, it seems the docs don't reference DARK_NAVY, BLURPLE, GREYPLE, DARK_BUT_NOT_BLACK & NOT_QUITE_BLACK too! I think these should be added in somewhere!

**Comment by iCrawl** [comment]
This is in fact a discord bug that they labeled as "not a bug", despite both mobile clients (1 funnily built with react native, so they reuse components from their desktop client) rendering it correctly.
