### ISSUE TITLE
V12 migration issue: channel.lockPermissions() crash

### ISSUE THREAD

**Issue by KM0KA** [discordjs/discord.js#3851]
**Please describe the problem you are having in as much detail as possible:**

Migrating code to V12. Smooth for the most part. However experienced an issue after creating a new channel. I attempt to move the newly created channel into a parent Category Channel and then lock the permissions and then it blows up. I attempted to find any documentation pertaining to the "lockPermissions()" channel function to see if this was impacted but could not.

**Include a reproducible code sample here, if possible:**
```js

guild.channels.create(member.nickname, { type: 'voice' })
  .then(voiceChannel => {
       voiceChannel.edit({ parent: categoryChannel.id})
            .then(() => {
            voiceChannel.lockPermissions()
              .then (() => {
.
.
.

results in this error:

Error [GUILD_CHANNEL_ORPHAN]: Could not find a parent to this guild channel.
    at VoiceChannel.lockPermissions (/home/centos/discord/v12/node_modules/discord.js/src/structures/GuildChannel.js:265:45)
    at /home/centos/discord/v12/addMember.js:40:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  [Symbol(code)]: 'GUILD_CHANNEL_ORPHAN'
}

// Place your code here

```

**Further details:**
- discord.js version: 12
- Node.js version: 13.9
- Operating system: CENTOS 7
- Priority this issue should have – please be realistic and elaborate if possible:

This is very important. I use it in the DISCORD Authorization/AddMember routines so this impacts the flow big time.

- [ ] I have also tested the issue on latest master, commit hash: 

I have installed latest V12: "discord.js": "github:discordjs/discord.js",

**Comment by KM0KA** [comment]
The Edit function is not working here. The Channel is getting created, then the Edit function is supposed to move the channel under the Parent Category Channel, and it is not. When the lock permissions is attempted, it blows up because there is no parent becuase the Edit function fails, even though it returns as if it is successful. 

Has the syntax on the edit function changed?

thanks

**Comment by NotSugden** [comment]
it seems that you are supposed to pass `{ parentID: "channel id" }` rather than `{ parent: "id" }`, i think a better option would be to use `voiceChannel.setParent("channel id")`, this will both set the parent and sync the permissions, so there would be no need to call lockPermissions afterwards

or you could pass a category channel / id into the `parent` property of the options object when calling GuildChannelManager.create

**Comment by KM0KA** [comment]
@NotSugden refreaking resolved! Thanks man! Took me all of two minutes to implement that and test it! Was this available on V11 cuz I totally spaced it? I completely ripped out the lock permissions code. This was such a simple solution.

Thanks again!

**Comment by KM0KA** [comment]
Followup:

In order for this to work as I needed it to, I had to assign the Category ID inside the create() Channel Object:

 { parent: categoryChannel.id,  type: 'text' }

and then perform an updateOverwrite() call. 

Creating the Channel without the Parent, then setting the parent ID, did not synchronize the permissions. 

Calling create(), then SetParent(), then lockPermissions() in sequence caused a crash.

More background: The Category Channel is completely locked down. The goal was to create a DM like channel that only two people would have interaction capabilities on. The Server Owner can see all the Channels under the Category but the owner of the Channel can only see their own.

.channels.create(member.nickname, { parent: categoryChannel.id,  type: 'text' })
     .then(textChannel => {
          textChannel.updateOverwrite(member.id, { VIEW_CHANNEL: true })
         .then (() => {

thanks,

MOKANA
