### ISSUE TITLE
awaitMessage doesn't not work

### ISSUE THREAD

**Issue by RunyardHartley** [discordjs/discord.js#3854]
**Please describe the problem you are having in as much detail as possible:** Good evening, a big problem is essential with this version, it is the awaitMessage which does not work any more at all ... it takes care of the first message which arrives whereas it should not be the case.  It works well with v11.5.1 but not on this version ...

**Include a reproducible code sample here, if possible:**
```js
		const msgs = await msg.channel.awaitMessages(res => res.author.id === msg.author.id, {
			max: 1,
			time: 30000
		});

```

**Further details:**
- discord.js version: 11.5-dev
- Node.js version: 11.15.0
- Operating system: Linux Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: Very Hight

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RunyardHartley** [comment]
I updated my nodejs 12.16.1, but doesn't not work

**Comment by anandre** [comment]
Please don't ignore the templates.  Come to the Discord server for help with issues like this.

**Comment by RunyardHartley** [comment]
Thank you, replace just max with maxMatches
