### ISSUE TITLE
Some function of Webhook doesn't work

### ISSUE THREAD

**Issue by ThumusLive** [discordjs/discord.js#3869]
Hi, I use webhook in discord but when I check the doc it's litteraly not the same thing. In the doc [here](https://discord.js.org/#/docs/main/stable/class/WebhookClient), we need to use a Webhook client but when i use it, it's litteraly not the same thing : ![image](https://user-images.githubusercontent.com/42680097/75618537-15e4c380-5b70-11ea-8552-183c8b34b8ce.png)
But in my code it return : 
![image](https://user-images.githubusercontent.com/42680097/75618649-a96ac400-5b71-11ea-99ec-ad8194edf14d.png)

Is not litteraly a bug but it's a problem

- discord.js version: lastest
- Node.js version: 
![image](https://user-images.githubusercontent.com/42680097/75618612-31040300-5b71-11ea-805c-c66bfbf3502c.png)
- Operating system: Windows 64x

**Comment by tipakA** [comment]
If you are judging if something is indeed a specific something by just `console.log()`'ing it, you should look on name of the object you logged.
Not every property will be logged, as properties added with `Object.defineProperty()` are not enumerable, thus will not show when you are console.logging the object. For example:
![image](https://user-images.githubusercontent.com/31581159/75618762-234f7d00-5b73-11ea-88f0-5a72ca8c2e0d.png)
Additionally, some of the properties are getters, which return data from other properties, like for example `createdAt` and `createdTimestamp`. One returns data the other one has.

If you would actually access the property that is listed in documentation, it would be returned to you.

**Comment by ThumusLive** [comment]
But how can i get the createdTimestamp or something else ?

**Comment by tipakA** [comment]
By literally accessing it from the WebhookClient object you have

For example:
```js
const webhook = new WebhookClient('id', 'token');
webhook.createdTimestamp //returns 1583033187
```

**Comment by ThumusLive** [comment]
Okay, but why it doesn't work for me ? 
This is my code : 
![image](https://user-images.githubusercontent.com/42680097/75618926-36fbe300-5b75-11ea-873d-afb8e79fde5d.png)
And it returns :
![image](https://user-images.githubusercontent.com/42680097/75618929-424f0e80-5b75-11ea-868a-2bc7eed54f6e.png)
I don't understand

**Comment by ThumusLive** [comment]
I found the problem, I didn't have the right version, i has the v11.5.0 and not the lastest and in the lastest version it's working. Thanks tipakA ! And sorry taking your time for nothing
