### ISSUE TITLE
Deprecation warnings for v11 methods

### ISSUE THREAD

**Issue by ItsRauf** [discordjs/discord.js#3876]
**Is your feature request related to a problem? Please describe.**
With the recent release of v12 of the discord.js library and people updating to it, many methods have been just outright removed which ends up breaking many bots which rely on such methods

**Describe the ideal solution**
My solution would be to add deprecation warnings to v12 urging users to switch to the new methods.

**Comment by Darqam** [comment]
Considering to get the warnings people would need to update to the version with the warnings, I don't quite see how this would work.

You'd want a V11.7 just to get extra warnings for breaking things in V12? Considering the scope of all the changes, the console would be massively flooded since basic things like <client>.guilds.forEach() would not be ok anymore.

This is basically the reason for: https://discordjs.guide/additional-info/changes-in-v12.html#updating-from-v11-to-v12

**Comment by ItsRauf** [comment]
I was thinking for more of a 12.0.1 which would give you warnings for using the old methods

**Comment by Darqam** [comment]
That would mean re-implementing non-existing methods though

**Comment by ItsRauf** [comment]
I think it was a bad practice to remove them in the first place without having the deprecation warnings

**Comment by RDambrosio016** [comment]
This does not make sense, it would be a huge and pretty pointless change to add those methods back in just to give them a warning, frankly, users should have already known, v11 has deprecation warnings and notes on the docs. Additionally, many are user methods which v12 will not ever reinstate

**Comment by didinele** [comment]
If you really want to give programmatic warnings you might as well give a single one with info a single time on startup

**Comment by ItsRauf** [comment]
I just think the warnings would help the users know exactly what old method they are still using so they aren't just updating and their bot and it's now broken and they have to go through the whole bot to find what changed

**Comment by ItsRauf** [comment]
only alternative I could think of is throwing the guide link in the post install script of the npm package

**Comment by iCrawl** [comment]
We had warnings all through v11 and additionally you have https://discordjs.guide/additional-info/changes-in-v12.html#updating-from-v11-to-v12 as a guideline to follow and look up changes (yes I'm aware its long, but its a big update, you can't expect to update your medium/big bot in 20min and call it done.)
