### ISSUE TITLE
ShardingManager not working with 'auto' shard count

### ISSUE THREAD

**Issue by MattIPv4** [discordjs/discord.js#3879]
**Please describe the problem you are having in as much detail as possible:**

When using the ShardingManager with a token provided and calling the #spawn method with `'auto'` for the shard count, it throws an error that would seem to indicate it tried to spawn zero shards (the token should result in about 4 shards).

If I replace the `'auto'` value with a hard-coded value for the shard count (eg. `4`), it works just fine!!

**Include a reproducible code sample here, if possible:**

```js
const { ShardingManager } = require('discord.js');
const path = require('path');
const { token } = require('../config');

const run = async () => {
    const manager = new ShardingManager(path.join(__dirname, 'bot.js'), { token });
    try {
        console.log(manager.totalShards);
        await manager.spawn(manager.totalShards, 1500, -1);
    } catch (e) {
        console.log(`Failed to spawn shards: ${e} ${Object.entries(e)}`);
    }
};

run();
```

Output:

```
auto
Failed to spawn shards: [object Response] size,0,timeout,0
```

**Further details:**

- discord.js version: 12.0.0
- Node.js version: 12.15.0
- Operating system: Windows server 2016
- Priority this issue should have – please be realistic and elaborate if possible: P3, easy monkeypatch by hardcoding a value, or using internal sharding instead.

**Comment by advaith1** [comment]
setting shardCount to `auto` for internal sharding also stopped working a while ago (it says it now needs a number), not sure if that's intentional or related

**Comment by vladfrangu** [comment]
In 12.0, you set `shards` to `auto`, not `shardCount`, so I think that's your issue @advaith1

I can probably look into this issue later today

**Comment by advaith1** [comment]
@vladfrangu i've always used v12 and it worked before, does `shards` also apply to internal sharding? it's not well documented imo

**Comment by vladfrangu** [comment]
Well, hold on, you're confusing me. Matt has an issue with the ShardingManager, which I'll look into soon! You said you were having an issue with internal sharding? That's what I understood from your replies, but please correct me if wrong

**Comment by MattIPv4** [comment]
`new Client({ shards: 'auto' })` worked just fine for me -- I just would rather be using ShardingManager than internal sharding personally, hence the report.

**Comment by vladfrangu** [comment]
@MattIPv4 yep, I got that, I was referring to @advaith1's comment 😅

**Comment by advaith1** [comment]
sorry for the confusion: yes I'm talking about internal sharding, setting `shardCount: 'auto'` and not setting `shards` used to work on v12 but then stopped working, I wasn't sure if it's related to Matt's ShardingManager issue.

**Comment by vladfrangu** [comment]
@advaith1 Well, that's cause since PR https://github.com/discordjs/discord.js/pull/3393, you set `shards` to `auto`, not `shardCount`. If you still encounter issues after that, hit me up on Discord (Vladdy#0002) and I'll help you out debugging it and such

**Comment by advaith1** [comment]
Ah so that was an intended change, thanks

and sorry for hijacking your issue Matt 😄

**Comment by Blessedwasnotfat** [comment]
i still get issues, however it's a different error i think for the same issue
`const client = new Discord.Client({ shards: 'auto' });`
My error:
`throw new TypeError('CLIENT_INVALID_OPTION', 'shardCount', 'a number greater than or equal to 1');`
idk if this is a dead thread or not but i don't know
i'm trying to do internal sharding

**Comment by azbaron** [comment]
@Blessedwasnotfat because you use `new Client({ shards: 'auto' })`, not shardCount.

**Comment by kyranet** [comment]
`shardCount` is not longer a valid option in v13's ShardingManager's [options](https://discord.js.org/#/docs/main/master/typedef/ShardingManagerOptions), so this is fixed in master.

Since we're not releasing new versions of `v12`, please upgrade to `v13` (master or `discord.js@dev` in npm), and if the issue persists (once adapting the code), please open a new issue.
