### ISSUE TITLE
property 'name' does not exist on 'TextChannel'

### ISSUE THREAD

**Issue by net8floz** [discordjs/discord.js#3880]
**Please describe the problem you are having in as much detail as possible:**

Using typescript and the "message" event `message.channel.name` is claimed to not be a property. Debugging `message.channel.name` shows that it is clearly a valid property with a valid value. 

The docs say that `TextChannel` object is the owner of the `name` property. After inspecting the relevant typings in this repos source I definitely see no `name` property defined. 

**Include a reproducible code sample here, if possible:**

```ts
import * as Discord from 'discord.js';
const client = new Discord.Client();

client.on('message', async msg => {
  // a valid property, but contains no type
  console.log(msg.channel.name);
}
```

**Further details:**

- discord.js version: "discord.js": "^11.5.1"
- Node.js version: "12"
- Operating system: "windows"

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by net8floz** [comment]
Turns out I just typescript bad. Sorry about that.

**Comment by adam-devel** [comment]
why did you close this issue?
it's true that property 'name' does not exist on 'TextChannel'
`TextChannel` extends `GuildChannel`, it should inherit the `text` property
