### ISSUE TITLE
Embed Problem

### ISSUE THREAD

**Issue by SharlockAvci** [discordjs/discord.js#3883]
```js
const embed = new Discord.MessageEmbed()
.setAuthor("Help", client.user.avatarURL)
.setDescription("This is a help command.")
.setColor("#fff")
message.channel.send(embed)
```
I am take an error. The error message is;

`TypeError: fields.flat is not a function`

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
