### ISSUE TITLE
(node:4786) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function.

### ISSUE THREAD

**Issue by DarkVessel** [discordjs/discord.js#3887]
When using MessageEmbed, an error occurs.
```js
client.on("ready", () => {
  client.channels.cache.get("589391966484037654").send(Discord.MessageEmbed().setAuthor("Test"))
})
client.login("token");
```

**Further details:**
- discord.js version: ^12.0.1
- Node.js version: v10.15.3
- Operating system: Linux.

- [x] I have also tested the issue on latest master, commit hash.

**Comment by iCrawl** [comment]
Readme says:

*Node.js 12.0.0 or newer is required.*
