### ISSUE TITLE
Guilds.size returns undefined

### ISSUE THREAD

**Issue by STOPSHARINGTHISORBAN** [discordjs/discord.js#3889]
I recently updated Discord.js on my discord bot and now when I try to call the event it returns Undefined. This is my code ```console.log("The bot is online in " + bot.guilds.size + " servers.");```
This worked before the update. Here is my console when its ran: ```The bot is online in undefined servers.```

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by Asgarrrrr** [comment]
Discord V12 : `client.guilds.cache.size`.
