### ISSUE TITLE
Opusscript Error: cannot convert "null" to int

### ISSUE THREAD

**Issue by qazxsw1240** [discordjs/discord.js#3895]
**Please describe the problem you are having in as much detail as possible:**
After updating discord.js to version 12, when bot try to join into the voice channel, the code throws the error "cannot convert null to 'int'" in opusscript. I checked it works properly on @discordjs/opus, but it doesn't sounds clear.
**Include a reproducible code sample here, if possible:**

```js
let commandJoin = {
    cmd: /\bjoin\b|\bj\b/i,
    async exec(_client, msg, _param) {
        let voiceChannel = msg.member.voice.channel;
        if (msg.guild.me.voice.channel) {
            if (msg.guild.me.voice.channel.equals(voiceChannel)) {
                await send(msg.channel, new Discord.MessageEmbed()
                    .setTitle(':notes: Already joined!')
                );
            } else {
                await voiceChannel.join();
            }
        } else {
            await voiceChannel.join();
        }
    }
};
```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: 12.16.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by mymonsterdk** [comment]
I got the same error. On node 10 and on 12.

**Comment by iCrawl** [comment]
> I checked it works properly on @discordjs/opus, but it doesn't sounds clear.

This makes no sense at all and is only placebo. `opusscript` and `@discordjs/opus` use the identical opus version, which means there can not be a degrade in audio quality.

**Comment by BannerBomb** [comment]
Just to supply more details on the issue, The `null to int` conversion error is only thrown when attempting to play an audio like I did with the following.
```js
msg.member.voice.channel.join().then((c)=>c.play(`http://www.hochmuth.com/mp3/Bloch_Prayer.mp3`))
```

The exact error that is thrown is
```console
! TypeError: Cannot convert "null" to int
✓ TypeError: Cannot convert "null" to int
TypeError: Cannot convert "null" to int
! abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.
/opt/rookiebotelite/node_modules/opusscript/build/opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]
abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.
```
I am using nodejs v13, discord.js `master` branch v12.0.2. However when I install `@discordjs/opus` I do not experience any degraded performance with the audio.

**Comment by PanSzelescik** [comment]
I have the same problem but with opusscript 0.0.7 on Node v12.15.0 on Debian with discord.js 12.0.2, but with @discord.js/opus no. With @discord.js/opus music on Linux freezes, but on Windows no

**Comment by superVoja** [comment]
Did you find a solution? I am having the same problem, and I can not install @discrodjs/opus or node-opus for some reason

**Comment by Impalez** [comment]
Same error here, is there a fix? I haven't found anything..

TypeError: Cannot convert "null" to int
TypeError: Cannot convert "null" to int

D:\Documentsz\DISCORD BOT\node_modules\opusscript\build\opusscript_native_wasm.js:8  
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versioVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locate
abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.

**Comment by superVoja** [comment]
Try using node-opus instead of opusscript or @discordjs/opus, I
used @discordjs/opus and it's working for me.
Make sure to look at the documentations od discord.js because the tutorials
on youtube are outdated.

**Comment by Impalez** [comment]
Its working with @discordjs/opus !! Thank you very very much.

**Comment by Dash11235** [comment]
@discordjs/opus works. Thank you guys! 😃

**Comment by clementcolter** [comment]
@superVoja 
Thank you OMG thank you so so so so so so so much!!!! for the @discord/opus command my day is made!

**Comment by kSt4rz** [comment]
I cannot install @discordjs/opus nor node-opus.

**Comment by clementcolter** [comment]
> I cannot install @discordjs/opus nor node-opus.

Sorry to hear that, you might be typing in wrong, try npm install - - save @discordjs/opus make sure you have downloaded discord.js and npm init(I’m sure you have) if you need more help just comment back! Best of luck

**Comment by kSt4rz** [comment]
"npm install - - save @discordjs/opus" didn't work for me.

**Comment by clementcolter** [comment]
Hmm... what kinda error are you getting? Like will it download and the program just isn’t working that may help?

**Comment by Monbrey** [comment]
Please do not comment on old closed issues.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
