### ISSUE TITLE
Collection methods are no longer shown in the documentation

### ISSUE THREAD

**Issue by FM-96** [discordjs/discord.js#3896]
The [`Collection` documentation for v12.0.1](https://discord.js.org/#/docs/main/12.0.1/class/Collection) (and as of now, [the one for master](https://discord.js.org/#/docs/main/master/class/Collection)) no longer shows any of its methods. The methods aren't just moved to another class either; when using the search feature they don't come up anymore at all.

**Comment by MattIPv4** [comment]
These got moved into their own package and docs: https://discord.js.org/#/docs/collection/master/class/Collection

**Comment by FM-96** [comment]
I see. In that case the links to "Collection" in the main docs should point to the new docs, otherwise people will not find those.

**Comment by tipakA** [comment]
They already do. You can click on `extends BaseCollection` and jump there

**Comment by FM-96** [comment]
That leads to the "Welcome" tab, rather then the tab where the actual methods are. Given that this is apparently literally the only instance of this behaviour in the entire docs, this was understandably confusing for me.

If you are in (for example) [the `ChannelManager` documentation](https://discord.js.org/#/docs/main/12.0.1/class/ChannelManager) and you click on the `Collection` under `.cache`, that should lead you directly to the collection methods. Everything else in the docs works this way, so that's what users will expect.
