### ISSUE TITLE
Request some VoiceBroadcast/ Dispatcher Event handling clarity

### ISSUE THREAD

**Issue by KM0KA** [discordjs/discord.js#3899]
**Please describe the problem you are having in as much detail as possible:**

Firstly, let me say that the V12 version of Voice handling is majestic. It took me a while to comprehend the flow, but once I did, I believe I was able to create something that blew away all doubts.

The typical flow is for a member to connect to a voice channel, and then initiate the connection protocols and establish playback after VoiceChannel verification. All initiated with some keyboard key sequence after the member is connected to the Voice Channel.

What I did was make it so that all the member had to do was click on a Voice Channel and they were instantly greeted with audio playback. No Keyboard interactions. No hot keys. Just click and join the voice channel.

However, this method appears to not "subscribe" the member and add them to the "subscribers" array within the VoiceBroadcast object. It also does not fire the "subscribe" event.

From the discord guide:

```js
broadcast.on('subscribe', dispatcher => {
	console.log(`Broadcast playing in ${dispatcher.player.voiceConnection.channel.name}`);
});

// Emits the subscribe event on the broadcast
connection.play(broadcast);
```

I have the Client object join the desired channel for broadcast during the VoiceBroadcast and dispatcher setup. This flow does fire the broadcast.on('subscribe'... event. But I am only getting it to fire one time as further explained below. I console.log the Broadcast object during this "event" and can see that the "subscribers" array is now populated (with the Client information), where it was empty before.

I maintain the events on the Dispatcher and at the end, on the Dispatcher "end" event, I am able to restart from the beginning. This comes the closest to simulated a real radio broadcast where everything simply loops.

**Include a reproducible code sample here, if possible:**

```js
// Place your code here

// I have the voiceChannel 

if (voiceChannel) {
  
 broadcast = client.voice.createBroadcast();
  
 dispatcher = broadcast.play(file);

// all the events fire as expected
  
 broadcast.on('subscribe', dispatcher => {  });

dispatcher.on('finish', dispatcher => {  });

dispatcher.on('start', dispatcher => {   });

dispatcher.on('error', dispatcher => {  });

voiceChannel.join()
.then(connection => {
    connection.play(broadcast);
});

}
```

This code above allows me to have the functionality most suitable to my audience. All a member has to do is click and join the channel.

So here is the million $ question. No events fire when a member simply joins a channel. No subscriber information is added to the "subscribers" array in the VoiceBroadcast object. The 

```js
broadcast.on('subscribe', dispatcher => {  });
```

never fires agains after the first time.

How can I gain access to the event handler for when a member joins the channel? I had five devices playing perfectly synced audio, it was like being in a concert, but not one of these listeners where in the subscriber array and I could there fore never get a listener count.

With regards!

**Further details:**

- discord.js version: 12
- Node.js version: 13.9
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible:
Pretty important to me!

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Hi, to check if a member has joined a voice channel, you should use the `guildMemberUpdate` event, i.e.:

```js
client.on('guildMemberUpdate', (oldMember, newMember) => {
  if (oldMember.voice.channelID !== newMember.voice.channelID) {
    // user has just joined the channel given by newMember voice state
  }
});
```

The `subscribe` event on a broadcast will emit whenever there is a new `StreamDispatcher` playing that broadcast.

Hope this helps!

**Comment by iCrawl** [comment]
This seems to be rather stale, if there's anymore help or questions, open a new issue please.
