### ISSUE TITLE
Remove Reaction from User dont work

### ISSUE THREAD

**Issue by Shiirroo** [discordjs/discord.js#3906]
Hello everybody,
does anyone know if message reaction, remove a reaction (from user) does not work? In version 11.5.1 I was able to remove some. Now the `remove()` function has been set for all removed reactions. Previously you could `remove(DiscordID).` Now I tried `_remove(User),` but couldn't remove any reactions

const User = `msg.guild.member(msg.guild.members.cache.find(x` => x.id === `discordid));`

https://prnt.sc/rcr776 - Discord JS MessageReactions.js
https://prnt.sc/rcrf91  My code check if reaction is number then remove user reaction or remove all reaction from this number

**Further details:**

- discord.js version: discord.js@12.0.1
- Node.js version: v13.7.0
- Operating system: Win 10 64 Bit

<!--

- [x ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
