### ISSUE TITLE
fields.flat is not a function (Embeds)

### ISSUE THREAD

**Issue by 770grappenmaker** [discordjs/discord.js#3913]
**Please describe the problem you are having in as much detail as possible:**
When updated to Discord.js v12, I faced an issue with creating an embed. Everything worked fine except for that it gave me an error. The JS Code below gives me the following error: `fields.flat is not a function`

**Include a reproducible code sample here, if possible:**

```js
const { MessageEmbed } = require("discord.js")
message.channel.send(new MessageEmbed().setTitle("Test Embed in v12"));
```
I could fix it with an workaround:
```js
Object.defineProperty(Array.prototype, 'flat', {
    value: function(depth = 1) {
      return this.reduce(function (flat, toFlatten) {
        return flat.concat((Array.isArray(toFlatten) && (depth>1)) ? toFlatten.flat(depth-1) : toFlatten);
      }, []);
    }
});
```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: v10.16.3
- Operating system: Win7 Professional
- Priority this issue should have – please be realistic and elaborate if possible: No high priority

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
Discord.js v12 requires a minimum Node version of v12

**Comment by 770grappenmaker** [comment]
Thanks for letting me know, I forgot to run `npm i -g node` before submitting the issue. Sorry for the disturption.

**Comment by Monbrey** [comment]
That is not how Node should be installed or updated.

Please go to nodejs.org and download an installer or follow instructions for your platform.

**Comment by 770grappenmaker** [comment]
You are right, i found out that you have 2 options:
- Install nodejs with the windows installer
- Run ```
npm install -g npm-windows-upgrade
npm-windows-upgrade
```

**Comment by isuckatprogram** [comment]
I had the same error but my nodejs version was v10.22.0 so I'm gonna try and fix that

**Comment by sewek333** [comment]
> I had the same error but my nodejs version was v10.22.0 so I'm gonna try and fix that

Did you fix it? 
I have the same problem
@isuckatprogram

**Comment by ALabre0** [comment]
i have this problem when i upload files in the server.
any solution?

**Comment by SpaceEEC** [comment]
The first comment is the solution:
> Discord.js v12 requires a minimum Node version of v12

**Comment by SrIzan10** [comment]
Can I use LTS?

**Comment by Keke27210** [comment]
> Can I use LTS?

Use any version that's 12.x or higher, that includes current LTS and latest releases

**Comment by SrIzan10** [comment]
ok thanks
