### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by StevenRafft** [discordjs/discord.js#3921]
Hello there,
I've recently was trying to make my discord bot play an .mp3 audio file but whenever the bot joins it shows that the bot is playing the .mp3 file but he isn't anyways heres the code:

```js
if (msg.member.voiceChannel) {
msg.member.voiceChannel.join()
.then(connection => { // Connection is an instance of VoiceConnection
msg.reply('I have successfully connected to the channel!');
const dispatcher = connection.playFile('K:/audios/audio.mp3');
})
.catch(console.log);
 } else {
 msg.reply('You need to join a voice channel first!');
}
```
my discordjs version is v11.4.2
my node.js version is v12.14.1
my OS is win7 64bit

Priority this issue should have – please be realistic and elaborate if possible: high
[ ] I have also tested the issue on latest master, commit hash:

**Comment by Blogshot** [comment]
Have you verified that FFMPEG is installed? This is  requirement for mp3-playback as mp3 must be decoded before being transmitted.
A lack of FFMPEG might lead to "empty" playback, I believe.

**Comment by StevenRafft** [comment]
Yes. i did

**Comment by Blogshot** [comment]
Could you provide a snippet of relevant log output?

What exactly does `.catch(console.log);` do? I can not find a descriptive example anywhere. Is it possible that this swallows any error messages?

Based on a project of my own, this is a snippet that worked for me:
```
voiceChannel.join().then(connection => {
  connection.playFile(file);
}).catch(error => {
  console.log(error);
});
```

You should also consider moving to DiscordJS 12. A migration guide is available at https://discordjs.guide/additional-info/changes-in-v12.html.

**Comment by StevenRafft** [comment]
```.catch(console.log);``` outputs if there is any errors i think, i'm not an expert at these kind of things and i don't get anything in the logs

**Comment by Naim2000** [comment]
`.catch()` Happens when the promise rejected. By putting `console.log` in place of the first argument, the error is printed to console. `.catch(e => console.log(e))` works as well.

**Comment by StevenRafft** [comment]
I will take a look

**Comment by StevenRafft** [comment]
I'm going to take a look later

**Comment by iCrawl** [comment]
Please upgrade to v12 if you use audio, v11 is unsupported.
