### ISSUE TITLE
Passing a created stream to connection#play results in nothing

### ISSUE THREAD

**Issue by SpeedyCraftah** [discordjs/discord.js#3926]
**Please describe the problem you are having in as much detail as possible:**

Creating an audio stream using `connection.receiver.createStream(user)` and then passing it to `connection.play` results in no playback, finish event does not fire at all as well, even if the stream has some buffer already in it.

**Include a reproducible code sample here, if possible:**

```js
message.member.voice.channel.join().then(async connection => {
      console.log("Connected to vc");

      const audio = connection.play("./ding.mp3");
      audio.on("finish", async () => {
        connection.on("speaking", async (user, speaking) => {
          if (user.id === client.id) return;

          if (speaking) {
            const stream = connection.receiver.createStream(user, {
              end: "silence"
            });

            stream.on("end", async () => {
              connection.play(stream, { mode: "opus" });
            });
          } else {}
        });
      });
    });
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Clueless, isn't a library-breaking bug so priority shouldn't be high

- [x] I have also tested the issue on latest master, commit hash:

**Comment by SpeedyCraftah** [comment]
@discordjs/opus: "0.1.0"

**Comment by shackhorn** [comment]
I experience this, too. I even tried a test command. Bot showed green indicator as if it were transmitting something, however, no audio actually came out.



![image](https://user-images.githubusercontent.com/25649775/79128901-41afb780-7d72-11ea-94bf-e5a29cf71361.png)

```javascript
if (command === "debug") {
    // +debug [userToListenTo]
    const voiceChannel = message.member.voice.channel;
    const userToListenTo = args[1];
    try {
      voiceChannel.join().then((connection) => {
        const audio = connection.receiver.createStream(userToListenTo);
        audio.on("data", (chunk) => {
          console.log(`Received ${chunk.length} bytes of data.`);
        });
        connection.play(audio, { end: "manual" });
      });
    } catch (error) {
      console.log(error);
    }
  }
```

**discord.js version:** v12.1.1
**@discordjs/opus version:** 0.1.0
**Node Version:** v12.0.0
**Operating System: ** Windows 10 Pro, Powershell

**Comment by Keke27210** [comment]
That's quite funny I've been trying myself to get that working in the same time.
I guess it's broken, Discord does not actually provide documentation to properly receive voice data so libraries have to "guess the way to do".

Anyway, I can confirm this is broken.
**discord.js**: 12.2.0
**node.js**: 12.16.2
**opus**: djs fork 0.1.0
**OS**: Debian 10 x64

**Comment by Clemens-E** [comment]
If I see this correct there are multiple issues with both of those codes:
@shackhorn: Discord now requires you to send data (so send voice) before you are able to receive data

@SpeedyCraftah: As far as I know, it makes no sense to play from a stream that has just ended
See [Readable#end](https://nodejs.org/api/stream.html#stream_event_end):
> The 'end' event is emitted when there is no more data to be consumed from the stream.

I'm not on the latest d.js version, still on some older master commit, but for me receiving voice works fine. I did not try to directly pipe the stream into connection#play, but the received data is valid.

**Comment by shackhorn** [comment]
> 
> 
> If I see this correct there are multiple issues with both of those codes:
> @shackhorn: Discord now requires you to send data (so send voice) before you are able to receive data
> 
> @SpeedyCraftah: As far as I know, it makes no sense to play from a stream that has just ended
> See [Readable#end](https://nodejs.org/api/stream.html#stream_event_end):
> 
> > The 'end' event is emitted when there is no more data to be consumed from the stream.
> 
> I'm not on the latest d.js version, still on some older master commit, but for me receiving voice works fine. **I did not try to directly pipe the stream into connection#play, but the received data is valid.**

If you didn't try to pipe the stream directly into connection#play yet, do you think you could attach a code snippet for us to try where it *should* work in theory, or try it yourself? I'll try to do the stream with my code, maybe play a file before actually starting the stream, however I do not know if it'll work. I'll update this reply accordingly.

**Comment by Clemens-E** [comment]
FYI you put the `{ end: "manual" }` as option for the play method when it should be in the createStream method

**Comment by Clemens-E** [comment]
[Reproducible and Working Code Example](https://gist.github.com/Clemens-E/42a8905f02c2007c1f9aabd8bd8a801e)
As it seems, playing from `channel a => channel b` works fine,
but playing from `channel a => channel a` only works with a timeout.

While some quick debugging I got it working with the setTimeout. Somehow, that made it work
I wonder if the ^ case is caused by discord or by the library, either way, hope this helps

**Comment by shackhorn** [comment]
It worked. It was the setTimeout issue. Running play before the stream is even initialized.

**Comment by Clemens-E** [comment]
@SpeedyCraftah 
did the above fix it for you?
If yes, please close this issue.

**Comment by SpeedyCraftah** [comment]
Can confirm this worked
