### ISSUE TITLE
Client Token Broken

### ISSUE THREAD

**Issue by carterdacat** [discordjs/discord.js#3930]
When regenerating a token after the bot token was auto deleted by disco when leaked, the new regned token dose not work.
```
UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
``` It was regened, and tested many times

**Comment by warstrolo** [comment]
check if your token is not public viewable

**Comment by carterdacat** [comment]
i was using the app token, not the bot token. Please add something for all apps that have bot enabled so they know its not the bot token

**Comment by HarmoGlace** [comment]
Discord.js is not affiliated with Discord
