### ISSUE TITLE
Invalid regex in non-chrome browsers

### ISSUE THREAD

**Issue by lduv1** [discordjs/discord.js#3932]
The regexes used in the referenced section of code (src/util/Util.js:L130 in case it didn't work...) are not supported in non-chrome browsers.

I tried importing via the following methods, there were no differences between the working methods in terms of browser functionality, they all didn't work.

```js
// the following compiled
const Discord = require('../../node_modules/discord.js/webpack/discord.min.js');
import {Client} from "../discord.js";
import Discord from "../discord.js";

// these didn't compile
// import Discord from "../discord.js/browser";
// const Discord = require("discord.js");
// const Discord = require("discord.js/browser");

```

I looked in to it a little and it seems that only chrome and edge support regex lookbehind assertions, here's a relevant stackoverflow post to go off of: https://stackoverflow.com/questions/50011366/javascript-regex-negative-lookbehind-not-working-in-firefox

**Further details:**

- discord.js version: 12.0.1
- Node.js version: v12.15.0
- Operating system: Browser (tried on windows and osx)
- Priority this issue should have – please be realistic and elaborate if possible: High, it disables use on several major browsers.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by lduv1** [comment]
I can't see the code I selected as a reference when making the issue, so here's the line numbers:
src/util/Util.js Lines 130, 169, 179, and 184

**Comment by advaith1** [comment]
This isn't really a discord.js issue, it's an issue with the browsers that don't support it, as it's in the spec. There's an implementation bug for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1225665
