### ISSUE TITLE
Running Guild.emojis.create() without any parameters ends with the process crashing due to heap out of memory 

### ISSUE THREAD

**Issue by TimoAardappel** [discordjs/discord.js#3933]
**Please describe the problem you are having in as much detail as possible:**
While running the below code my RAM usages spikes from ~100MB to 8GB and then crashes the process with this message:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Include a reproducible code sample here, if possible:**
```js
Guild.emojis.create() // Without any parameters
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Ubuntu 18.04.4 LTS x86_64 
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by lumap** [comment]
Can reproduce | node 13.1,djs v12.0.0
