### ISSUE TITLE
If you are using the token of a user account it cannot establish websocket with it (INVALID_TOKEN_ERROR)

### ISSUE THREAD

**Issue by xXTurnerLP** [discordjs/discord.js#3937]
**Please describe the problem you are having in as much detail as possible:**
When i use Client.login(TOKEN) on version 12.0.2 it says its invalid token, but on version 11.5.1 its totaly valid and working

**Include a reproducible code sample here, if possible:**

```js
const api = require("discord.js");

const client = new api.Client();

client.on("ready", () => {
    console.log(`logged in as: ${client.user.username}#${client.user.discriminator}`);
});

client.login(USER_ACCOUNT_TOKEN);
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible: Moderate

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RDambrosio016** [comment]
This is expected, v12 completely drops support for user tokens, as they are **against the TOS**. You should be using bot tokens, not user tokens.

**Comment by xXTurnerLP** [comment]
Then im sticking to v11 lol

**Comment by HarmoGlace** [comment]
It is against the TOS, you can't negotiate.

**Comment by xXTurnerLP** [comment]
in the tos it says its not allowed to be used for **AUTOMATION** im not automating anything it doesnt say its not allowed at all

**Comment by HarmoGlace** [comment]
Tell this to discord and show us their answer lmao

**Comment by iCrawl** [comment]
This counts as automation.
