### ISSUE TITLE
Custom Emoji Remove MessageReaction Partial error on fetch every time

### ISSUE THREAD

**Issue by LylaCupcake** [discordjs/discord.js#3946]
Using Partials. Having MESSAGE and REACTION enabled.
- Inside of the messageReactionAdd event, when partial, it fetches normally.
- Inside of the messageReactionRemove event, when partial, it fetches normally if the emoji is an unicode that was removed.
- Inside of the messageReactionRemove event, when partial, it always returns an error when it is a guild emoji that was removed.

Error: `"TypeError: Cannot read property '_patch' of undefined at ReactionManager._fetchReaction (/home/asd/asd/node_modules/discord.js/src/managers/ReactionManager.js:84:30)"`

```js
await messageReaction.message.fetch(); //Works
await messageReaction.fetch(); //Returns the error
//I did let the ifs out to check if they are partial.
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Ubuntu server
- Priority this issue should have – please be realistic and elaborate if possible: Med? It seems that fetching is a bit oofed.

**Comment by Monbrey** [comment]
Looked into this one the other day.

`MessageReaction#fetch` calls `this.message.reactions._fetchReaction(this.emoji, true);`
`this.emoji` is a getter, which can return either a `GuildEmoji` (custom) or `ReactionEmoji` (unicode)
`ReactionEmoji#reaction` exists, but `GuildEmoji#reaction` doesn't.
