### ISSUE TITLE
"guilds.get()" don't work with the last update

### ISSUE THREAD

**Issue by GamingFR91** [discordjs/discord.js#3947]
**Please describe the problem you are having in as much detail as possible:**the function "guilds.get()" is detected as not a function

**Include a reproducible code sample here, if possible:**const Discord = require('discord.js');
const client = new Discord.Client();
client.login('Bot Token');

client.on("ready", function() {

    client.user.setActivity('!test', {type: "STREAMING"});

console.log(`${client.user.username} is ready`);
});

client.on('message', message => {
    if (message.content === !test) {
      message.channel.send(client.guilds.get(message.guild.id).memberCount);
    }
});

```js
// Place your code here
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Visual Studio Code on Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: This Function is used by famous bots

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
**Regarding breaking changes in version 12 and updating:**
- Major versions are prone to breaking changes as per [semantic versioning](https://semver.org/#spec-item-8)
- We have an extensive guide on updating from version 11 to version 12 at [discordjs.guide](https://discordjs.guide/additional-info/changes-in-v12.html?v=12)
- Should you wish to restore your bots functionality immediately without updating your code base please un-and re-install the library in the previous non-breaking version, 11.6.2
```
$ npm remove discord.js
$ npm install discord.js@11.6.2
$ npm list discord.js
```
The last command should print `-- discord.js@11.6.2` if your installation was successful

---

If you still have questions about discord.js installation or usage please visit the Discord server at <https://discord.gg/bRCvFy9>. This issue tracker is just for bug reports and enhancement suggestions.

**Comment by almostSouji** [comment]
For this specific case see <https://discordjs.guide/additional-info/changes-in-v12.html#managers-cache>
