### ISSUE TITLE
Create role doesnt work

### ISSUE THREAD

**Issue by ManysekLP** [discordjs/discord.js#3948]
Hello, I am quite new to coding in Discord js and I've ran into this problem. I wanted to created a role called "LMFAO" with administrator, and make it give it to me afterwards. The bot gave me the role (tested earlier) so that was working. It created the role but didn't name it neither did it give any permission. Here is the code:

`
bot.on("message", async message => {
    if(message.content.startsWith(`${prefix}report`)) {
        message.guild.createRole({
            data: {
              name: 'LMFAO',
              permissions: ['ADMINISTRATOR'],
            },
          });
        var role = message.guild.roles.find(role => role.name === "LMFAO");
        message.member.addRole(role);
    }
})
`

I was testing it on the latest version of Visual Studio Plus. Thanks in advance

**Comment by ItsPapaia** [comment]
It is `message.guild.roles.create` in v12.
https://discordjs.guide/additional-info/changes-in-v12.html

**Comment by ManysekLP** [comment]
> It is `message.guild.roles.create` in v12.
> https://discordjs.guide/additional-info/changes-in-v12.html

So I have to update my Discord.Js?
I dont understand that well..

**Comment by LxveFades** [comment]
Which version of Discord.js are you running? What's the actual issue? You might want to move over to the [Discord Server](https://discord.gg/bRCvFy9) instead, where you're intended to ask for help concerning your issues with Discord.js. From where you can be redirected over to the issue tracker if necessary.

**Comment by ManysekLP** [comment]
I accidently removed the response but I was using the wrong command, thanks anyways and I will next time use the discord
