### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource (discord.js.org/#/docs)

### ISSUE THREAD

**Issue by Blend3rman** [discordjs/discord.js#3968]
**Please describe the problem you are having in as much detail as possible:**
The documentation webpage is unable to load data when any links are opened in a new tab. It shows an error message that says "Couldn't load documentation data."
~~**Include a reproducible code sample here, if possible:**~~ Not applicable

I have narrowed it down to a problem with the docs site's cookies or cache, as clearing cookies and site data eliminates this issue.

**Further details:**
- Browser version: Mozilla Firefox 74.0 (64-bit)
- Operating system: Windows 10 release 1909
- Priority this issue should have – please be realistic and elaborate if possible: Low/Moderate

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Fyko** [comment]
Cannot reproduce this. 

![image](https://user-images.githubusercontent.com/45381083/77093466-9d379100-69d0-11ea-9e24-34ff2c7cc075.png)

**Comment by iCrawl** [comment]
This is usually an error with github, not much we can do.
