### ISSUE TITLE
smoother embed updates

### ISSUE THREAD

**Issue by sojohnnysaid** [discordjs/discord.js#3969]
When I edit embeds and use any method (setTitle, spliceFields etc) the embed flickers or glitches out just before the embed updates itself.

This is obviously not a huge deal, am I doing something wrong or is that just what happens when you update an embed?

this is a piece of code I modified from the discord.js.org site:
https://discordjs.guide/popular-topics/embeds.html#attaching-images-2

```js
const receivedEmbed = test.embeds[0];
    const embed = new Discord.MessageEmbed(receivedEmbed)
      .setTitle('New title')
      .setDescription('Description after the edit')
      .spliceFields(0,1,[{name: 'name changed', value: 'value changed', inline: false}])
    
      test.edit(embed);
```

Thanks!

**Comment by LxveFades** [comment]
This doesn't appear to be an issue with the library. It's more likely that it's your connection to Discord, or Discord being weird. Either way, I was unable to reproduce this "bug".

**Comment by sojohnnysaid** [comment]
awesome thanks for your fast reply!
