### ISSUE TITLE
I want to send group of people which has certain role and not located in certain voicechannel

### ISSUE THREAD

**Issue by Ferdik-sirniysause** [discordjs/discord.js#3973]
I want to send message, which content is:

group of people, which has certain role (in example, roleID = '1234512345') and not located in certain voicechannel (in example, voicechannelID = '5432154321').

pls help.

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
