### ISSUE TITLE
replacing emojis in Message.cleanContent

### ISSUE THREAD

**Issue by iiPanda** [discordjs/discord.js#3974]
**Is your feature request related to a problem? Please describe.**
Message.cleanContent gives the text with all mentions replaced with equivalent text, but emojis aren't replaced

**Describe the ideal solution**
Message.cleanContent could also replace emojis with equivalent text

**Comment by iCrawl** [comment]
We will not change the behavior of cleanContent for this.

A new util method for this is most likely also not going to happen.
