### ISSUE TITLE
GuildChannel.setParent() permissions do not sync

### ISSUE THREAD

**Issue by MilSci** [discordjs/discord.js#3976]
**Please describe the problem you are having in as much detail as possible:**
During the creation of a channel in a guild, there is the method GuildChannel.setParent(), the parameter 'option.permissionsLock' is set to 'true' by default, where it should sync with the parent's permissions accordingly. This does not happen. I tested as well with the options.parent parameter in GuildChannel.create(), it also does not sync to the parent's permissions when doing this.

On top of that with some extra testing, GuildChannel.lockPermissions() does not work either (permissions don't sync), same with overwriting permissions after establishing the parent and locking permissions.

**Include a reproducible code sample here, if possible:**
```js
await guild.channels.create(`{message.author.username}`, {
                    type: 'text',
                    permissionOverwrites: [
                        {
                            id: message.author.id,
                            allow: ['VIEW_CHANNEL', 'SEND_MESSAGES', 'EMBED_LINKS', 'ATTACH_FILES', 'READ_MESSAGE_HISTORY']
                        },
                    ],
                    reason: 'Channel created',
                }).then(async chan => {
        
                    chan.setParent(guildinfo.ticketCategory, { lockPermissions: true, reason: 'Channel moved' })
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.14.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:
It is important due to the ability of not syncing permissions upon channel creation.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by LxveFades** [comment]
You're **overwriting** the permissions, try updating them after you create the channel & set the parent.
Snippet which inherits the permissions of the parent:
```js
        const channel = await message.guild.channels.create("test-channel", {
            parent: '690657800958902344',
            reason: "Created channel for test"
        });
```
whilst overwriting the permissions won't.

**Comment by MilSci** [comment]
I found a fix to it. Version 12 updating permissions instead of overwriting permissions.
