### ISSUE TITLE
Library failing on Ubuntu server

### ISSUE THREAD

**Issue by 220ish** [discordjs/discord.js#3977]
**Please describe the problem you are having in as much detail as possible:**
![image](https://user-images.githubusercontent.com/26344980/77220440-49e45080-6b40-11ea-84a8-107fc10ef6fe.png)
I'm not able to run Discord.js on Ubuntu servers for some reason, it crashed two days ago and I didn't even touch the code since then and it stopped working. It works if I build the code to an executable but doesn't work as an normal javascript file.
**Include a reproducible code sample here, if possible:**

```js
const mongo = require('mongodb').MongoClient
var discord = require('discord.js')
var bot = new discord.Client()

bot.on('message', (message) => {
    if (message.channel.id == 622105194716725258 || message.channel.id == 636601060932452352){
        console.log(message.content)
    }
})

bot.on('ready', () => {
    console.log('Bot is ready')
})

bot.login('TOKEN')
```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: 12.6.1
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible:

- [ x] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
You've updated to Discord.js v12, but haven't updated Node to the minimum requirement of v12 also.

Please do so - you made need to refer to https://github.com/nodesource/distributions since the version in `apt` is outdated.
