### ISSUE TITLE
GuildChannelManager#create supposedly ignore position 0 option

### ISSUE THREAD

**Issue by T3NED** [discordjs/discord.js#3982]
**Please describe the problem you are having in as much detail as possible:**
I've performed numerous tests and I've concluded that specifying a position with the value of 0 is ignored. Possibly something to do with falsy values because specification of all other positions work as intended.

**Include a reproducible code sample here, if possible:**

```js
// Works as intended 
guild.channels.create("example", {
    parent: "689970956730368023",
    position: 1
});

// Ignores channel position 
guild.channels.create("example", {
    parent: "689970956730368023",
    position: 0
});
```
This bug does not have a high priority.

**Comment by LxveFades** [comment]
I believe that when providing `position` property to `GuildChannelManager#create()`, it's not 0-indexed. At least that's what I concluded from my testings.
```ts
message.guild.channels.create(`test-${message.guild.channels.cache.size}`, {
   type: 'text',
   parent: 'id',
   position: 0
});
```
would look like channels test `11-14`

However, when doing the following,
```ts
message.guild.channels.create(`test-${message.guild.channels.cache.size}`, {
   type: 'text',
   parent: 'id',
   position: 0
});
```
the created channel is more like `test-15`.

![test1](https://user-images.githubusercontent.com/61620747/77259171-0a248280-6c80-11ea-8a1a-15d6b7f229cb.png)

**Comment by iCrawl** [comment]
This looks rather stale as of now, if this is still problematic after the last comment, please open a new issue.
