### ISSUE TITLE
Problem adding roles to new users via Discord.js bot

### ISSUE THREAD

**Issue by a-lp** [discordjs/discord.js#3985]
**Please describe the problem you are having in as much detail as possible:**
I can't manage to add new roles to users via Discord.js bot. I've been trying adding the role using the _ID_ or searching them from _guild.roles_, but noone of them worked. The problem is that it doesn't return feedback, positive ones or errors.
**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js');
const bot = new Discord.Client();
var roles = {};  // {id: Role}
var inviteLink = {};  // {code: [role_id, role_id, ... ]}
var storic = {}; // {invite_code: number_use}

bot.on('guildMemberAdd', member => {
        var inviteLinkFound = -1;
        // .... searching for the correct invitationLink
        if (inviteLinkFound != -1) {
            console.log("Found", inviteLink[inviteLinkFound]);
            // add all the roles for that kind of invitation
            inviteLink[inviteLinkFound].forEach(id => {
                console.log("Adding", id);
                // ** here does nothing **
                member.roles.add(id).then(m => {
                    console.log("Done");      // ** no messages
                }).catch(e => console.error); // ** no errors
            });
            console.log("End");
        }
    });
})
```

**Further details:**

- discord.js version: ^12.0.02
- Node.js version: v13.3.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: LOW

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ItsPapaia** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.

That said, it doesn't wok because the condition inside of the if statement is false, as you set `inviteLinkFound` to -1 in the first line of the listener.

**Comment by a-lp** [comment]
The if control goes correctly because inviteLink is modified here:
 `// .... searching for the correct invitationLink`
With an older version of discord.js (11.6.3), i could manage to use [method ](https://discord.js.org/#/docs/main/11.6.3/class/GuildMember?scrollTo=addRole)`.addRole`, while working with latest version of discord.js (12.0.2), this method doesn't exist anymore, instead it must be used [method](https://discord.js.org/#/docs/main/12.0.2/class/GuildMemberRoleManager?scrollTo=add) `.add` (the one I used in the example above with problems).

**Comment by Jyguy** [comment]
Assuming that `console.log("Adding", id);` is actually running and you are sure, the `.catch()` of the `.add` won't do anything since the error function is not running. Nevertheless, as @ItsPapaia mentioned you should head to the [Discord Server](https://discord.gg/bRCvFy9) for questions.

**Comment by PanSzelescik** [comment]
I have the same problem with adding 2 roles using Collection<Snowflake, Role>. And also no message and no errors

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
