### ISSUE TITLE
connection.dispatcher.end()

### ISSUE THREAD

**Issue by hansputera** [discordjs/discord.js#3987]
I tried the message message.member.voice.channel.join (). dispatcher but I did not find to end speaking from my bot .. please help in the version of discord.js v11 I found `dispatcher.end ()` to end speaking but what is it replaced now?

**Comment by Fyko** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead: https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by amishshah** [comment]
You can listen for the `finish` event to see when the stream ends, and use `dispatcher.destroy();` to end the stream.

Please use the Discord server next time for questions like Fyko has said above!
