### ISSUE TITLE
User.locale returns undefine

### ISSUE THREAD

**Issue by raziEiL** [discordjs/discord.js#3988]
**Please describe the problem you are having in as much detail as possible:**
I always get undefined when tried to get user locale but User class has [property](https://github.com/discordjs/discord.js/blob/stable/src/structures/User.js#L69) to do it . Why?
**Include a reproducible code sample here, if possible:**

```js
client.on("message", msg => { console.log(msg.author.locale); });
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: win 10

- [ ] I have also tested the issue on latest master, commit hash: f2fdb9331895da59546107efe245a2e0137ef2e7

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Keke27210** [comment]
You can notice on the documentation, next to the type of `User#locale`, a **?** which means a lot. This symbol is here to tell you this value can be undefined in some circumstances.
Actually, you can only get a user's locale through an OAuth2 authorization with the _IDENTIFY_ scope which is the reason why you can't access this information in your case.

**Comment by SpaceEEC** [comment]
This property seems to have incorrectly slipped in at some point, it's not available to bots.

`locale` is only populated in the response to `GET /users/@me`, i.e. fetching the currently logged in user.
The intended use-case for this is [oauth2](https://discordapp.com/developers/docs/topics/oauth2) and not bots.

I suppose you will see it getting populated as a side effect of #4060, however only for the currently logged in user (that's your bot); It always will be `en-US`, so not useful here either.

---

There isn't really anything we can do about this I suppose, so I'm closing this issue as "won't" fix.
