### ISSUE TITLE
DiscordAPIError: Invalid from body limit

### ISSUE THREAD

**Issue by SwedenGuy4933** [discordjs/discord.js#3989]
I get this error when i try to use my Purge

`Couldn't delete messages because of: DiscordAPIError: Invalid Form Body
limit: Value "#bot-test" is not int.`

I get this error in Discord

what do i do?

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
