### ISSUE TITLE
My bot can't start because he is getting ratelimited

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#3991]
**Please describe the problem you are having in as much detail as possible:**
Again and again, the ratelimit issue is not fixed an now, I am at the point that I can't even start my bot without getting ratelimited for one hour.

I reported this issue months ago and nothing is done.

Is discord.js made for small bots only ? Can I get a hope for a fix ? 

I am about to give up for real.

**Further details:**

- discord.js version: latest master
- Node.js version: 12.6.1
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Keke27210** [comment]
Can you give more details?
Are you making specific requests during your bot's startup? How many guilds is your bot in?

**Comment by Koyamie** [comment]
> Can you give more details?
> Are you making specific requests during your bot's startup? How many guilds is your bot in?

Thanks for the fast answer.

Not much, I only create my Client and do .login() when all my local stuff is ready.
My bot is in around 324000 guilds.

**Comment by iCrawl** [comment]
#3560 #3891 #3890

The first one is already from you, so I don't see how opening a new one is going to change anything regarding this situation.

The reason why it doesn't get much "attention" is simply because we have nothing to go off. People really don't like hearing that, and I understand but its simply not an "easy" fix or an easy issue either.

**Comment by Fyko** [comment]
Thought I might add, per the [Discord Documentation](https://discordapp.com/developers/docs/topics/gateway#sharding-for-very-large-bots), you should reach out to them if you're running into login errors. 
> If you own a bot that is in over 250,000 guilds, there are some additional considerations you must take around sharding.

**Comment by TheMonsters29** [comment]
i have same problem i have 130k guilds
