### ISSUE TITLE
Incompatible with node ECMAScript Modules

### ISSUE THREAD

**Issue by duncte123** [discordjs/discord.js#3992]
**Please describe the problem you are having in as much detail as possible:**
When using this project with the experimental ECMAScript modules you're not able to destruct imports.
There is a workaround by just destructuring the main export but that is just ugly.

**Include a reproducible code sample here, if possible:**

```js
import { Client } from "discord.js";

const client = new Client();

client.login("TOKEN");
```

**Working example code:**

```js
import Discord from "discord.js";
const { Client } = Discord;

const client = new Client();

client.login("TOKEN");
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 13.11.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Low to medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by chroventer** [comment]
I am able to reproduce the error:
```javascript
import { Client } from 'discord.js';
const client = new Client();

client.login('token');
```

The following error is thrown in the terminal:
```bash
import { Client } from "discord.js";
         ^^^^^^
SyntaxError: The requested module 'discord.js' does not provide an export named 'Client'
←[90m    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)←[39m
←[90m    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)←[39m
←[90m    at async Loader.import (internal/modules/esm/loader.js:167:24)←[39m
```

**Comment by chroventer** [comment]
After digging for a while, I can across the following comment:
> --experimental-modules doesn't support importing named exports from a commonjs module (except node's own built-ins).

There is an alternative solution the author added to the comment.
Source: [stackoverflow:54302557/12293009](https://stackoverflow.com/a/54302557/12293009)

**Comment by duncte123** [comment]
> After digging for a while, I came across the following comment:
> 
> > --experimental-modules doesn't support importing named exports from a commonjs module (except node's own built-ins).
> 
> There is an alternative solution the author added to the comment.
> Source: [stackoverflow:54302557/12293009](https://stackoverflow.com/a/54302557/12293009)

I assume that the same thing holds for using `"type": "module"` in the package.json

**Comment by chroventer** [comment]
Right, Node.js treat the following as ES modules when passed to node as the initial input, or when referenced by import statements within ES module code:
- Files ending in .mjs.
- Files ending in .js when the nearest parent package.json file contains a top-level field "type" with a value of "module".
- Strings passed in as an argument to --eval or --print, or piped to node via STDIN, with the flag --input-type=module.
