### ISSUE TITLE
send image fail

### ISSUE THREAD

**Issue by baanloh** [discordjs/discord.js#3994]
**Problem**
Images sent via the "files" property are not rendered properly. But work when send in embed message.

![screen](https://user-images.githubusercontent.com/33934311/77571289-629c8f80-6ecd-11ea-8811-23441e0aac34.png)

**Code:**

```js
const url = "https://cdn2.thedogapi.com/images/BJ2Wq664X.gif";
const embed = new Discord.MessageEmbed().setThumbnail(url).attachFiles(url);
await msg.channel.send({ embed });
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.x
- Operating system: glitch.com

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
This is working fine for me.

Did you perhaps disable previews for uploaded images? (Second checkbox)
![image](https://user-images.githubusercontent.com/24881032/77571895-5fee6a00-6ece-11ea-9b42-c6fcdfa1bb7b.png)

**Comment by baanloh** [comment]
> 
> 
> This is working fine for me.
> 
> Did you perhaps disable previews for uploaded images? (Second checkbox)
> ![image](https://user-images.githubusercontent.com/24881032/77571895-5fee6a00-6ece-11ea-9b42-c6fcdfa1bb7b.png)

That's not seems to be the problem. When I click on link, I get this :

![screen](https://user-images.githubusercontent.com/33934311/77573627-400c7580-6ed1-11ea-9135-d19fd28979da.png)

By the way, the problem seems occur only with certain image.

**Comment by advaith1** [comment]
Your code seems to work for me:
![](https://advaith.is-in-hyper.space/e5e9dc1c48.gif)

**Comment by YoonSuhyeok** [comment]
![image](https://user-images.githubusercontent.com/26738250/77615427-ba410680-6f72-11ea-9496-7fff87ed10da.png)
![ezgif-2-5370b3a26bb2](https://user-images.githubusercontent.com/26738250/77615757-74387280-6f73-11ea-89be-e146575103bd.gif)
I tested. It works fine.

**Comment by baanloh** [comment]
I re-test it today and now it seems to work fine.
