### ISSUE TITLE
<BaseManager>.cacheSize to reduce confusion

### ISSUE THREAD

**Issue by QSmally** [discordjs/discord.js#4003]
**Is your feature request related to a problem? Please describe.**
On v12, I see most people run into a problem where they want to do (for example) `<Guild>.members.size` and that throws an error.

**Describe the ideal solution**
Having a getter `.cacheSize` or `.size` that just simply returns `this.cache.size` would reduce the number of issues people are having, while still applying the format the BaseManager has with the `cacheType`.

**Comment by Monbrey** [comment]
You're literally suggesting that for some reason `.cacheSize` should exist instead of people doing `.cache.size`.

People can just do it properly. This is utterly pointless.
