### ISSUE TITLE
[Error] 

### ISSUE THREAD

**Issue by NightcoreRYT** [discordjs/discord.js#4004]
**Please describe the problem you are having in as much detail as possible:**
Trying to upgrade my music module to Discord.js v12 and I'm getting this error from discord.js itself.
**Include a reproducible code sample here, if possible:**
Not possible, as its within discord.js itself.
```js
Not possible.
```

**Further details:**

- discord.js version: v12
- Node.js version: Latest
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible:
Top priority

- [ ] I have also tested the issue on latest master, commit hash:
![image](https://user-images.githubusercontent.com/31454793/77836102-1e1e2780-714b-11ea-8a73-b0e6cb6dd50a.png)

**Comment by tipakA** [comment]
Please update Node to version 12.0.0 or newer, as per README.

**Comment by vzwGrey** [comment]
> Node.js version: Latest
You are not on the latest version. Otherwise you would not be getting this error.
