### ISSUE TITLE
Embed values may not be empty

### ISSUE THREAD

**Issue by Tricky-Ricky** [discordjs/discord.js#4010]
**Please describe the problem you are having in as much detail as possible:**
I have an embed generator class (A file with all embeds on to reduce clutter across scripts), although not tested on the same script, I believe this will still happen.

During a ban command, I have a user input a reason, and the reason gets outputted to an embed when the offender is successfully banned, However, it will ask for the reason a little further down the script after checking if a user has been tagged, and that the role comparison check has been done.

Through testing each process: 
/ban (To ensure the script asks for the user to be tagged)
/ban (user) (To ensure the script asks for a reason)
/ban <user> (reason) (before banning the member)
See Image below:
![image](https://user-images.githubusercontent.com/36576579/77955564-4d0dd800-72c8-11ea-81c3-0d4b22e82dca.png)

Notice the double /ban command to start with, On the first one it errored out with:

> RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values may not be empty.

It pointed to this line in the embed:
`.addField('__Reason:__', `${reason}`)`

Ultimately it isn't empty, It's just the reason field hasn't been filled out yet by the user, but it errors out and DC's the bot.

However, If you add:
`.addField('__Reason:__', `\u200b${reason}`)`

It won't error and kill the bot.

**Include a reproducible code sample here, if possible:**

```js
run(bot, message, args) {
        // Get the logs Channel
        const modLogs = message.guild.channels.cache.find(ch => ch.name === 'modlogs');

        // Define User
        const user = message.author;

        // Define Offender
        const offender = message.mentions.members.first();
        
        // Guild roles
        const guildRoles = message.member.roles.cache.map(r => r.name);
        
        // Check to see if user has staff role
        if(!guildRoles.some(name => preRoles.roleName.includes(name.toLowerCase()))){
            return message.channel.send('This command is only for staff!');
        }
        // Define args for reason
        const reason = args.slice(1).join(' ');

        // Generate embed
	const embedGen = new embGen();
        const banMsg = embedGen.generatebanEmb(user, message, offender, reason);
        const deniedBan = embedGen.generatebanDenyEmb(user, message, offender);

        // Check if the offender has been tagged
        if(!offender){
            message.reply('You need to tag the offender!');
        } // Check if the offender is bannable by the message author            
        else if(message.member.roles.highest.comparePositionTo(offender.roles.highest) > 0 ){  
            if(reason.length === 0){
                message.reply("Please give a reason to ban the user! `/ban (user) (reason)`");
            }else {
            // If offender has been tagged, ask to confirm
                const filter = m => m.content.includes('yes') && m.author.id === message.author.id;
                    message.reply('Are you sure you want to ban ' + offender.user.username).then(() => {
                        message.channel.awaitMessages(filter, {max: 1, time: 5000, errors: ['time']})
                        .then(collected => {
                        // If confirmed ban
                        offender.ban();
                        modLogs.send(banMsg).catch(console.error);
                        }).catch(collected => {
                            message.reply("You didn't ban " + offender.user.username)
                        });
                    })
                }
        }else {
        message.reply("You are unable to ban this member")
        modLogs.send(deniedBan).catch(console.error)
        }
    }

// Embed is linked at the top of the script:
const embGen = require('../Classes/embedGenerator.js');
// Embed code is:
generatebanEmb(user, message, offender, reason){
            const banMsg = new Discord.MessageEmbed()
            .setColor(color.Alert)
            .setTitle('===  Member Ban  ===')
            .addField('__Author:__', `${user}`, true)
            .addField('__Channel:__', `${message.channel.name}`, true)
            .addField('__Offender:__', `${offender} has been banned!`)
            .addField('__Reason:__', `${reason}`)
            .setThumbnail(message.author.displayAvatarURL())
            .setTimestamp()
            .setFooter(`©️ ` + `Contender Bot 2020`);
            return banMsg
        }
```

**Further details:**

- discord.js version: v12.1.1
- Node.js version: v12.13.1
- Operating system: Win 10
- Priority this issue should have – please be realistic and elaborate if possible:
Low, easily resolvable, but still unexpected behaviour

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
Unless I'm missing something this is in no way a bug.
You are trying to add a field to the embed structure that is not valid, due to the field value being empty. 

"It's not really empty, the user just hasn't yet provided the necessary information" is not really a good argument for this being a bug either.

In the end you are trying to enter an invalid field, which the library chooses to reject before the API does so after receiving invalid data.

The simple solution to this is to just add the field (generate the embed) after you actually have the information necessary at hand and can construct a valid embed from it. The other solution of course is to handle missing input and fill in a place holder if needed.

**Comment by Tricky-Ricky** [comment]
The issue being, just running /ban - before the embed is even triggered or sent, kills the bot this way.
It shouldn't kill the bot off, perhaps another "soft error" pointing to the issue to be rectified, rather than a full process kill.

The embed shouldn't be fired before it is sent, which is where the field values should be checked, at the time of sending - Not before, so ultimately it shouldn't matter in the hierachy where you are defining the embed, or the values, untill it is being sent.

Which is why I have reported this as a bug.

**Comment by iCrawl** [comment]
> Ultimately it isn't empty, It's just the reason field hasn't been filled out yet by the user

Which ultimately means... its empty.

What is the suggested path we as a library should take here? Its the developers duty to properly sanity check this.

**Comment by Monbrey** [comment]
This is a bug in your code, in which you don't properly handle empty user inputs.

You also don't properly handle the error thrown by not properly handling empty user inputs, which is why the Node process terminates.

This is all expected behaviour.

**Comment by Tricky-Ricky** [comment]
> What is the suggested path we as a library should take here? Its the developers duty to properly sanity check this.

As stated in the above comments:
Placeholder `\u200b` to input a blank space (Similar to `.addField('\u200b', '\u200b') similar to the old `.addBlankField()`)
Or restructure the code layout to ensure the embed does not generate until all other fields are ready.

I'm not sure how the developers can combat this specifically, other than ensuring it doesn't kill the bot, unless they can restructure the embed checks until the time it is actually called / used.

**Comment by Monbrey** [comment]
> As stated in the above comments:
> Placeholder `\u200b` to input a blank space (Similar to `.addField('\u200b', '\u200b') similar to the old `.addBlankField()`)
We should not be providing custom placeholders that are hidden from users.
> Or restructure the code layout to ensure the embed does not generate until all other fields are ready.
It's *your* code that generates the embed before the fields are ready, not the library. *You* are the one calling/using it. Do the reason check before calling your `generatebanEmb` function.

**Comment by tipakA** [comment]
Your `reason` variable is literally empty in your code. doing
```js
const reason = args.slice(1).join(' ');
```
on empty `args` makes it an empty string. Which is the only value that when passed to embed title or value returns error that you are getting.

Since you know that that is not possible to put empty string there, make the variable have at least any non-empty value, if not from `args`, add a placeholder. Which you yourself mentioned that it solves the issue.

**Comment by Tricky-Ricky** [comment]
> It's _your_ code that generates the embed before the fields are ready, not the library. _You_ are the one calling/using it. Do the reason check before calling your `generatebanEmb` function.

That is all well and good, I understand the embed is generated before, but it is not called / used until AFTER the checks, which is a library issue at the point of the embed checks.

Is it checked when created, or checked when called?
`result` is not checked when created, but is when called,
The embeds are created within a variable, reason is created within a variable.

Reason throws no errors until called
banMsg throws errors before it is called

So the bug is at the time of checking the embeds, not being done at the time of calling, but rather at time of creation, It shouldn't matter where it is generated, but it hould matter where it is being called

**Comment by appellation** [comment]
I understand what your concern is, but personally I disagree with the concept. Lazily validating embeds doesn't really achieve anything other than allowing poor code practices. In your case, you're generating an embed regardless of whether you intend to send one, which is considered poor practice and can result in such errors even outside the context of message embeds.

**Comment by Tricky-Ricky** [comment]
My apologies this is down to my understanding between instantiation and usage. This is user error
