### ISSUE TITLE
Property 'end' does not exist on type 'VoiceBroadcast'.

### ISSUE THREAD

**Issue by kuskoman** [discordjs/discord.js#4014]
**Please describe the problem you are having in as much detail as possible:**

broadcast does not have end method declared in types, but it is existing in documentation

**Include a reproducible code sample here, if possible:**

```ts
const broadcast = client.voice.createBroadcast();
broadcast.end(); // Property 'end' does not exist on type 'VoiceBroadcast'. ts(2339)
```

**Further details:**
End method is declared in documentation: 
https://discord.js.org/#/docs/main/stable/class/VoiceBroadcast?scrollTo=end

- discord.js version: 12.1.1
- Node.js version: 12.6.0
- Operating system: windows
- TypeScript version: 3.8.3
- Priority this issue should have – please be realistic and elaborate if possible: mid-important for typescript users

**Comment by uhKevinMC** [comment]
Where is this file located? Is this in a typescript file or a javascript file? Is this issue replicable on any other bots/folders?

**Comment by Monbrey** [comment]
Thanks for raising this, PR will incoming to fix this shortly.

**Comment by amishshah** [comment]
Fixed in https://github.com/discordjs/discord.js/commit/0e44ecd420ba94b490c2cba1f7a30d1fa5878183
