### ISSUE TITLE
Discord Bot streaming music dies abruptly 

### ISSUE THREAD

**Issue by Clydeston** [discordjs/discord.js#4027]
**Hello, the Discord bot I've been updating recently is having some major issues streaming music, I can't tell if it's Discord JS or ytdl-core. The bot will begin playing music but then sometime during any stream, the quality degrades and the stream starts rubber banding (repeating itself), then eventually ends.  I have a debug log of the connection when the audio degrades, and when the bot eventually leaves, but it contains sensitive information some I'm reluctant to show it.**

**Include a reproducible code sample here, if possible:**

```js
let music_stream = ytdl(data.queue[0].url, { filter: 'audioonly'});
data.dispatcher = await data.connection.play(music_stream);
  data.dispatcher.guildID = data.guildID;

  data.dispatcher.on('error', console.error);

  data.dispatcher.once("finish", function() {    
    end(bot, ops, this);
  });
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 12.16.1
- Operating system:  Win10 1903 & Winserver2016 1607
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment]
Try adding `, highWaterMark: 1<<25` after `filter: 'audioonly'`

**Comment by Clydeston** [comment]
> Try adding `, highWaterMark: 1<<25` after `filter: 'audioonly'`

Thank you very much, this appears to fix this issue!
