### ISSUE TITLE
Unable to make a RichEmebd

### ISSUE THREAD

**Issue by luke110206** [discordjs/discord.js#4030]
When running
`
let ErrorEmbed = new Discord.RichEmbed()
.setTitle("~~ERROR~~ " + ver)
.setColor("#b3ada1")
.addDescription("An ERROR has occured");
message.channel.send(ErrorEmbed);`
I receive
`(node:11592) UnhandledPromiseRejectionWarning: TypeError: Discord.RichEmbed is not a constructor`

**Comment by tipakA** [comment]
`RichEmbed` was merged into `MessageEmbed`. [Here are the changes](https://discordjs.guide/additional-info/changes-in-v12.html#richembed-constructor)
