### ISSUE TITLE
guildMemberUpdate oldMember.nickname : null

### ISSUE THREAD

**Issue by woutfeys** [discordjs/discord.js#4032]
Hey guys! 

I am making a discord bot with discord.js but stumbled uppon a problem : when someone changes his nickname, the bot needs to send a message in #logging. But i keep getting null as nickname. The odd thing is sometimes i get null with the oldMember, and sometimes with the newMember. I also have this issue with userUpdate, then the avatar is sometimes null.

**Comment by Monbrey** [comment]
Please don't remove the issue template, it's there for a reason.

It's entirely valid for nicknames and avatars to be null, as people can add and remove them.

**Comment by woutfeys** [comment]
Sorry for asking, but what is the issue template?
And if it is valid for them to be null, howcan i log something like this was the avatar before change, and this is the avatar now.

**Comment by almostSouji** [comment]
if there is no avatar on the old user but on the new they just didn't have one before - you have to check these cases and adapt your logical accordingly.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by woutfeys** [comment]
Really thanks!

now I understand!
