### ISSUE TITLE
Leave voice channel command no long working since port to V12

### ISSUE THREAD

**Issue by 8cy** [discordjs/discord.js#4064]
I recently switched from v11.6.4 to V12 and due to the changes of discord.js v12, I can no longer use `msg.guilds.voiceChannel.leave()` and call it from an external file. I have to use `connection.disconnect()`. This doesn't work tho because if I run the command `foo!leave`, then connection is undefined because it's in an external file.

How would I go about fixing this, do I have to grab the connection constant somehow?

**Comment by ItsPapaia** [comment]
Please don't ignore the issue template.
The issue tracker is for bugs, not support, for support head to [the discord server](https://discord.gg/bRCvFy9).

Quick answer:
You still could use [`guild.voice.channel.leave()`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=voice).

**Comment by 8cy** [comment]
> Please don't ignore the issue template.
> 
> The issue tracker is for bugs, not support, for support head to [the Discord server](https://discord.gg/bRCvFy9).
> 
> 
> 
> Quick answer:
> 
> You still could use [`guild.voice.channel.leave()`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=voice).

Real sorry, I am on GitHub mobile and it's still pretty scuffed so many features are missing, thank you though.

**Comment by ravinath-akalnka** [comment]
Try This: `message.member.voice.channel.leave()`
