### ISSUE TITLE
ReactionCollector event issues for onCollect and OnRemove events

### ISSUE THREAD

**Issue by KM0KA** [discordjs/discord.js#4065]
**Please describe the problem you are having in as much detail as possible:**

Upon start up of a bot, I fetch a series of messages and establish ReactionCollector(s) on them. I then start listening to the onCollect and OnRemove events.

The onCollect event ALWAYS works fine. The onRemove event will only work if I perform a onCollect event first.

A deeper example: The Bot starts up. A user performs a onCollect action and the OnCollect Event fires and all the counts are updated. Then the Bot is shut down and restarted. After fetching the message and displaying the contents, all the correct counts are there. On DISCORD, all the counts are correct. The User then performs a onRemove action, performing a "un-react" action. Visually everything works as expected on DISCORD, but the onRemove event never fires. The User then performs a onCollect action, every thing works as expected. Then the user is able to perform a onRemove action and the OnRemove event will fire.

I have tried this with PARTIALS. I have even pulled the message in and stored it in memory.

I have set the options object to {dispose: true). Without this set, the onRemove event will never fire.

In summary the issue is that the onRemove event is never available on Bot startup. This is an issue because a User may perform an "un-react" action on a message and the Bot will never catch it, throwing all the counts off.

**Include a reproducible code sample here, if possible:**

```js
// I have tried PARTIALS on startup:

Client( { partials: ['MESSAGE', 'CHANNEL', 'REACTION'] } );

// I create the ReactionCollecter(s) as normally done but add the dispose option:
// The filter simply returns true so I catch everything no matter what.

ReactionCollector(message, filter , {dispose: true}); 

//I then fire off the listeners:

collector.on('collect', (reaction, user) => {

 });

 collector.on('remove', (reaction, user) => {

 });
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 13.10.1
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:

Pretty important, at least to me.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by DayColor** [comment]
This is the intended behavior. 
As seen in [ReactionCollector.js#121](https://github.com/discordjs/discord.js/blob/master/src/structures/ReactionCollector.js#L121) the collector will first check if the emoji has been collected, and only then call the `remove` event.

**Comment by StickieBE** [comment]
Also intrigued by this behavior.
What would be the correct way to account for removed reactions if the bot was offline during that period?
I have tried multiple solutions without success.

KR

**Comment by KM0KA** [comment]
I punted away from my original plan.

I built up ReactionCollectors that start on start up. For certain channels, I restrict it to Read Only and assign a predetermined set of reactions to a particular message. In all other read/write channels I allow members to use what ever reaction they want as I do not track those reactions . . . I needed some way to allow members to rate a Podcast without losing the integrity of such a rating system. This is what i built and it is solid.

I balance everything out when a Reaction Event is fired. I only allow a user to select one of Five predetermined reactions assigned to a specific Message Type (something I control by channel assignment).

So in short, I grab the user that fired the event, then go through each reaction collection and check if that user is in any other reaction and remove them. Key note: A lot of things changed to function calls under version 12 . . . that is what I am using . . . also . . . these function calls seem to work without being limited to cached only users . . . 

I created a Class called ReactionManager that handles all of this. It has been in test mode for a month and is pretty solid . . . 

Here is the Class . . . you have to parse out what does not apply to you . . . start with createReactionCollectors...

Also . . . I built a routine that makes all roles Read Only when I need to go into Maintenance mode. . . so none of the Reactions can be messed with when the Bot is offline . . . . 




class ReactionManager {

    constructor (controller) {

        this.controller = controller;
        this.reactionCollectorMap = new Map();
        this.arrayOfEpisodeReactionEmojis = [this.controller.reactions.one,this.controller.reactions.two,this.controller.reactions.three,this.controller.reactions.four,this.controller.reactions.five];
        
        this.controller.console.log("[ReactionManager]: Reaction Manager initialized...");

    }

    updateReactionCounts (controller, identifier, category, episode, member) {

        return new Promise ((resolve, reject) => {

            controller.console.log (`[ReactionManager][updateReactionCounts]:... `);

            let channel = controller.getChannelObject( controller.ShowTimeChannelID );
    
            if (channel) {
    
                channel.messages.fetch(episode.showtimeMessageID)
                .then(message => {
    
                    let reactions = message.reactions.cache;

                    let reactionCountOne    = 0;
                    let reactionCountTwo    = 0;
                    let reactionCountThree  = 0;
                    let reactionCountFour   = 0;
                    let reactionCountFive   = 0;

                    if (reactions) {
    
                        if (reactions.has(controller.reactions.one)) {

                            reactionCountOne = reactions.get(controller.reactions.one).count;
                        
                        }
                        if (reactions.has(controller.reactions.two)) {

                            reactionCountTwo = reactions.get(controller.reactions.two).count;
                        
                        }
                        if (reactions.has(controller.reactions.three)) {

                            reactionCountThree = reactions.get(controller.reactions.three).count;
                        
                        }
                        if (reactions.has(controller.reactions.four)) {

                            reactionCountFour = reactions.get(controller.reactions.four).count;
                        
                        }
                        if (reactions.has(controller.reactions.five)) {

                            reactionCountFive = reactions.get(controller.reactions.five).count;
                        
                        }

                    }

                    controller.console.log(`REACTION COUNT 1: ${reactionCountOne}`  );
                    controller.console.log(`REACTION COUNT 2: ${reactionCountTwo}`  );
                    controller.console.log(`REACTION COUNT 3: ${reactionCountThree}`);
                    controller.console.log(`REACTION COUNT 4: ${reactionCountFour}` );
                    controller.console.log(`REACTION COUNT 5: ${reactionCountFive}` );
    
                    resolve( { one: reactionCountOne, two: reactionCountTwo, three: reactionCountThree, four: reactionCountFour, five: reactionCountFive } );
   
                })
                .catch(error =>{
    
                    reject (`[updateReactionCounts]: ${error}`);
    
                });
                
    
            } else {
    
                reject (`[ReactionManager]:[updateReactionCounts]: Episode Channel did not initialize...` );
    
            }
        
           
        
        });
    
    }

    createReactionCollectors (arrayOfEpisodes) {

        return new Promise((resolve, reject) => {

            let arrayOfPromises     = new Array();

            for (let i = 0; i < arrayOfEpisodes.length; i++) {

                if ( !(this.reactionCollectorMap.has(arrayOfEpisodes[i].identifier)) ) {

                    arrayOfPromises.push ( () => createReactionCollectorForMessage (this.controller, arrayOfEpisodes[i]));
                
                }

            }

            if (arrayOfPromises.length > 0) {

                let promises = arrayOfPromises.map(task => task());

                Promise.all(promises)
                .then (arrayOfCollectors => {

                    for (let i = 0; i < arrayOfCollectors.length; i++) {

                        this.reactionCollectorMap.set(arrayOfCollectors[i].identifier, arrayOfCollectors[i].collector);

                        arrayOfCollectors[i].collector.on('collect', (reaction, user) => {

                            reactionAddEvent (this.controller, this.arrayOfEpisodeReactionEmojis, reaction, user); 

                        });

                    }

                    this.controller.console.log (`[ReactionManager]:[createReactionCollectors] Reaction Collectors loaded...`);

                    // console.log(this.reactionCollectorMap);

                    resolve ()

                })
                .catch (error =>{

                    reject (error);

                });

            } else {

                resolve ();

            }
           

        });


    }


}

module.exports = ReactionManager; 

/* ******************************************** PRIVATE FUNCTIONS ********************* */



 
function createReactionCollectorForMessage (controller, episode) {

    return new Promise((resolve, reject) => {

        // console.log (episode)
        // console.log (messageID)

        let filter = (reaction, user) => {

            return true; 

        }; 

        let channel = controller.getChannelObject(controller.ShowTimeChannelID);

        if (channel) {

            channel.messages.fetch(episode.showtimeMessageID)
            .then(message => {
               
                let collector = new controller.Discord.ReactionCollector(message, filter , {dispose: true}); 

                resolve( { identifier: episode.identifier, collector: collector } );

            })
            .catch(error =>{

                reject (error);

            });

        } else {

            reject (`[ReactionManager]:[createReactionCollectors]: Episode Channel did not initialize...` );

        }
        

    });


}


function reactionAddEvent (controller, arrayOfEpisodeReactionEmoji, reaction, user) {

    for (let i = 0; i < arrayOfEpisodeReactionEmoji.length; i++) {

        if (arrayOfEpisodeReactionEmoji[i] !== reaction.emoji.name) {

            let messageReaction = reaction.message.reactions.cache.get(arrayOfEpisodeReactionEmoji[i]);

            messageReaction.users.fetch()
            .then (users => {

                if (users.has (user.id)) {

                    messageReaction.users.remove(user.id)
                    .then (() => {

                        controller.console.log (`[ReactionManager]:[reactionAddEvent] User [ ${user.id} ] removed from Message [ ${messageReaction.message.id} ] Reaction { ${arrayOfEpisodeReactionEmoji[i]} }...`);

                    })
                    .catch (error => {
                        console.log(error);
                    })

        
                }

            })
            .catch (error => {
                console.log(error);
            })
        
        }

    }


}
