### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by Xavier-Labarbe** [discordjs/discord.js#4072]
**Please describe the problem you are having in as much detail as possible:**
When ever your running the bot, the error says: ```js

C:\Users\Xavier\Desktop\JeanDJ21\node_modules\discord.js\src\client\BaseClient.js:83
      fn(...args);
      ^

TypeError: fn is not a function
    at Timeout._onTimeout (C:\Users\Xavier\Desktop\JeanDJ21\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Include a reproducible code sample here, if possible:**
None, something isn't a function in discord js!

**Further details:**

- discord.js version: v12.1.1
- node.js version: v12.16.1
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible: ```js
fn();``` not being a function.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by Xavier-Labarbe** [comment]
ho ok sorry
