### ISSUE TITLE
TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by KamikariCat** [discordjs/discord.js#4073]
https://github.com/discordjs/discord.js/blob/828640ca263db2c95ed21e7353a2746fe6ac9fb8/src/structures/APIMessage.js#L278

TypeError: Cannot read property 'pipe' of undefined

when send gif sometimes

**Comment by iCrawl** [comment]
What happened to the issue template?

This is not here to be skipped, fill it out if you want us to look into the problem.



**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:



- [ ] I have also tested the issue on latest master, commit hash:
