### ISSUE TITLE
Send() function creating loop

### ISSUE THREAD

**Issue by Pixelmal** [discordjs/discord.js#4076]
There is a problem with Send() function.All events i tested are creating loop when it calls Send().
So bot sending one message infinitely.
```js
const Discord = require('discord.js');
const client = new Discord.Client();
client.on('message', function(msg){
client.channels.cache.get(<some_id>).send(msg);
});
client.login('<token>');
```

**Further details:**

- discord.js version: latest( 12.1.1 )
- Node.js version: 12.16.2 LTS
- Operating system: Win 10
- Priority this issue should have: It would be great,to solve this problem as fast, as you can.
Sorry in advance for my bad english.

**Comment by vzwGrey** [comment]
The message event fires for the bot's own messages too.

**Comment by Pixelmal** [comment]
Oh,really. Thanks for explanation.
