### ISSUE TITLE
Support crossposting

### ISSUE THREAD

**Issue by bsian03** [discordjs/discord.js#4089]
Crosspost endpoint is available for bots, see [here](https://github.com/discord/discord-api-docs/issues/1510)
Endpoint location/method is `POST /channels/:id/messages/:id/crosspost`

I tried figuring out how to include this within the library but I can't get my head round the rest manager so couldn't make a PR :P

**Comment by CyberiumShadow** [comment]
I’ve started an attempt to implement this as of 4f7f6ae0532c94c07d2350a831bae72921f44517
on my fork
