### ISSUE TITLE
Bot loses connection to discord and cant reconnect after

### ISSUE THREAD

**Issue by DELUUXE** [discordjs/discord.js#4096]
**Please describe the problem you are having in as much detail as possible:**

i've recently upgraded my bot to v12 and also moved to docker.

when i use it in production as part of a 70 shards bot, it will eventually disconnect from discord and not restart or reconnect.
_after forcefully restarting the docker container, it works for a few hours and then the same thing happens_

Sharding: I currently use a custom sharding method and i provide each docker container with a shard id and a shard count and pass those to the discord.js client options. I spread the shards over multiple servers.

i was able to catch the following logs, i have no idea what the problem could be seeing this.
the internet connection at that time seems fine as i can still ping 8.8.8.8 just fine when that happens.

It seems to be related to some websocket issue.

Logs / error output: 
https://gist.github.com/DELUUXE/e19ae15a6874947e2c6ea04ab6984a93

**Include a reproducible code sample here, if possible:**
I currently do not have any sample code i can provide here, since testing this issue takes a while before it occurs, its also inconsistent, but around a few hours after starting.

**Further details:**

- discord.js version: 12.1.1 
- Node.js version: v13.11.0 (node:latest (docker image hub))
- Operating system: debian based docker image (node:latest ( v13.11.0))
``Linux 2cd4bc2ad366 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux``
- Priority this issue should have – please be realistic and elaborate if possible:

Since this issue is kind of annoying, i'd give it a 7/10

- [ ] I have also tested the issue on latest master, commit hash:

Due to the time it takes before this issue happens, i have not been able to test it on the lastest commit on master.

**Comment by advaith1** [comment]
I also get this (with the same "WebSocket was closed before the connection was established" message) sometimes, using internal sharding on v12

**Comment by vladfrangu** [comment]
From your logs, there are a LOT of voice related errors (which I have myself, and are not in my territory), and from the looks of things, attempting to connect to a voice channel while the shard isn't authenticated, causing it to reset again (which I haven't tested but it shouldn't lock up; I will give this a test soon)

Can you setup your debug log collection like in #3201 and come back with the new logs? Specifically, looking for WebSocket closes and attempts to reconnect 😄

**Comment by DELUUXE** [comment]
I setup my debugging to only show logs including the WS keywords: 
``if(debug.includes('WS') && !debug.includes('VOICE')) {`` 
what should i filter for exactly?

**Comment by DELUUXE** [comment]
I'd also like to add that the voice connection errors are mostly cause by my rejoining process which only happens once after starting the bot, during normal operation it doesnt generate that many voice error.

**Comment by DELUUXE** [comment]
Is there any update on this? 😅

**Comment by vladfrangu** [comment]
> Can you setup your debug log collection like in #3201 and come back with the new logs? Specifically, looking for WebSocket closes and attempts to reconnect 😄

Did you catch this part of my message? 👀 
Otherwise, I literally have no issues with it as a whole.. The reconnects might be cause of Discord's new reconnect request but otherwise.. even that shouldn't break

**Comment by DELUUXE** [comment]
Just to be sure, you want me to filter out the heartbeats and voice errors?

**Comment by vladfrangu** [comment]
Yep, yep! Since the former is very spammy, and the latter shouldn't have anything to do with this issue. I'm mostly interested in the API close codes and such

**Comment by DELUUXE** [comment]
Im back with some more logging, i tried to filter out most voice related stuff, i did play "..." in between 2 parts that where hours appart.

note that if you see ``[27-4-2020 23:12:23] uncaughtException`` for example, it indicates that the above line or lines where an uncaughtException which was caught.

https://gist.github.com/DELUUXE/56de43108e91ab6d535ec291469bac8c

**Comment by DELUUXE** [comment]
Today i woke up to this, the bot was offline or not responding from what i heard from reports
and the logs where filled with this, over and over again.
https://gist.github.com/DELUUXE/b8d9d366e0fc66fe602db5a47b9da250

**Comment by uhKevinMC** [comment]
Hey there @DELUUXE, I've had this issue on a smaller scale before. My issue was fixed by re-installing the library.

**Comment by DELUUXE** [comment]
Ill try, though its in a docker container, and i have multiple different builds running with each a different version or newly build discord.js 
The versions i send the logs of are the latest v12.2.0, which i also rebuild/installed a few days ago

**Comment by vladfrangu** [comment]
I..am extremely concerned that it takes that long for your shards to get their GUILD_CREATE payloads that the heartbeat interval runs SEVERAL TIMES OVER. 1.5+ minutes to get guild packets (even at their max of 2.5k) sounds wrong (and I've never encountered it even on my old VERY OLD CPU), check your container settings and whatnot to make sure you're not choking its bandwidth (is that even possible?)

**Comment by DELUUXE** [comment]
well, thats very concerning indeed, i dont edit any network related setting on my docker images.
the host claims to have a 1gbps bandwidth, and they are okay servers when viewing the spec sheet.
ill see if i can try a different server/host and see if the problem persists 🤷‍♂️

**Comment by DELUUXE** [comment]
Quick update; 
I moved to a kubernetes cluster a few days after my last comment, since then i have not had this issue within the same time as i had it before.
Though i have not yet been able to run it for more than 2 consecutive days, due to other issues.
I think its safe to close this issue as others don't seem to have this issue.
Thanks for your help and sorry for taking your time 😅
