### ISSUE TITLE
Property on roles for integrations (bots)?

### ISSUE THREAD

**Issue by Naim2000** [discordjs/discord.js#4110]
**Is your feature request related to a problem? Please describe.**
I'm making a serverinfo command and it lists all the roles. However, I want to make it so that it doesn't list roles that are made __specifically__ for each individual bot.

**Describe the ideal solution**
Make a boolean property on `Role` probably named something like `bot`.

**Describe alternatives you've considered**
I've tried to filter all roles by:
1. The amount of members are `1`
2. The first member is a bot

**Additional context**
![image](https://user-images.githubusercontent.com/44107089/79771279-30c3f080-82f4-11ea-91d0-e1b43fe23813.png)

**Comment by NotSugden** [comment]
this already exists, [Role#managed](https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=managed) (will apply for the bot-managed roles, as well as the server booster role and any other roles managed by an integration)

**Comment by Naim2000** [comment]
okay right now i cannot believe myself
i'm just gonna filter out the everyone role as well which i believe it's id is the guild
![image](https://user-images.githubusercontent.com/44107089/79772267-80ef8280-82f5-11ea-862e-c8f596ed4d0b.png)
 id
