### ISSUE TITLE
Cant find discord channel

### ISSUE THREAD

**Issue by CorruptedCube** [discordjs/discord.js#4113]
Hi, 

So im coding an 'ideabot' that makes an embed and send that idea to the channel called idea.
Now the thing is that i am 99% sure i wrote the name correct, but my bot keeps saying that it couldn't find the channel (like i coded). I have no idea what i did wrong, pls help.

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js');
var client  = new Discord.Client();

module.exports.run = async (bot, message, args) => {


var idea = args.join(' ');
if(!idea) return message.channel.send('no idea was given please type your idea.');

var ideaEmbed = new Discord.MessageEmbed()
.setTitle('New idea')
.setColor('#ffff00')
.addField('idea', idea)
.addField('Suggested by', message.author);

const ideaChannel = message.guild.channel && find(channel => channel.name ==='idea');
if (!ideaChannel) return message.channel.send('Channel was not found');

ideaChannel && send(ideaEmbed).then(embedMessage => {
    embedMessage.react('👍');
    embedMessage.react('👎');
});

}

module.exports.help = {
    name: 'idea',
    description:'Do you have an idea? Then type !idea and we will look into it!'
}
```
I Also have a other script but i don't think that the problem has anything to do with it.
**Further details:**

- discord.js version:12.2.0
- Node.js version: 12.16.1
- Priority this issue should have – please be realistic and elaborate if possible: i think 7/10?

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
