### ISSUE TITLE
Feature Request: "Go Live" Video Streaming

### ISSUE THREAD

**Issue by mmmeff** [discordjs/discord.js#4116]
I'm looking for a way to add functionality to my bot to allow it to "Go Live" like a user can and share its screen. Being able to stream a video data buffer to the Discord API would be ideal.

I can't see anything in the official API docs in regards to the availability or unavailability of this feature, so I'm assuming it may not be available on the public API yet. Just double checking with y'all.

**Additional context**
I'm looking to build a video DJ/youtube-party style bot for my discord channel and want to avoid the current need for one of the users to have to share their screen.

**Comment by uhKevinMC** [comment]
Discord currently doesn't allow bots to use Video functionality as users would. This would be a Discord API/Discord feature request.

**Comment by mmmeff** [comment]
Dang, I figured as such. I'll close this.

Do you have any links to more reading or sites where myself and others can voice our request for this feature?

**Comment by uhKevinMC** [comment]
If you wish to submit a feature request, you can do so on Discords feedback submission form, or at the [official DAPI repo](https://www.github.com/discordapp/discord-api-docs).

**Comment by chez14** [comment]
Here's the issue: https://github.com/discord/discord-api-docs/issues/1386

**Comment by Java2107** [comment]
Just joining in to express my support for the addition of video capabilities for Discord bots. I believe it would highly expand the possibilities that Discord bots currently have. At the moment I am having to use an account for video output of an application which is controlled by a bot.
