### ISSUE TITLE
Bot can't login

### ISSUE THREAD

**Issue by bitt0008** [discordjs/discord.js#4119]
**Please describe the problem you are having in as much detail as possible:**

The bot won't login. I did `curl -I https://discordapp.com/api/v7/gateway`, and it returns `200 OK`.

It can't login on server nor on local machine, so it has something to do with Discord.js (if I'm wrong - sorry)

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.0.0
- Operating system: Linux Ubuntu 4.4.0-1085-aws
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
