### ISSUE TITLE
"CHANNEL_UPDATE" audit log problem

### ISSUE THREAD

**Issue by GoldSaw0** [discordjs/discord.js#4120]
Hi! When changing the category of any channel, the audit log does not read as "CHANNEL_UPDATE" or even the audit log does not read at all.

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.16.2
- Operating system: Windows 8.1 Pro 64 Bit
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by almostSouji** [comment]
That's got nothing to do with the library and neither is it a bug.
Discord does simply not create audit logs when channels are moved.

If you wish for new features <https://support.discordapp.com/hc/en-us/community/topics> is usually the place to go.
