### ISSUE TITLE
Add a .dmable property to the user class.

### ISSUE THREAD

**Issue by tobiO0310** [discordjs/discord.js#4129]
I would really want to see a (user).dmable property.

This would make it easy to say:
`if(user.dmable){
 user.send("Blah blah blah")
}else{
 msg.channel.send("I can't dm you! Please turn your dms on!")
}`
Instead of:
`user.send("Blah blah blah")
.catch(msg.channel.send("I can't dm you! Please turn your dms on!"))`

**Comment by iCrawl** [comment]
#4122
