### ISSUE TITLE
Error [TOKEN_INVALID]: An invalid token was provided.

### ISSUE THREAD

**Issue by muhajirdev** [discordjs/discord.js#4131]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
client.login('my_token');
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version:v12.16.2
- Operating system: MacOS
- Priority this issue should have – please be realistic and elaborate if possible:

- [] I have also tested the issue on latest master, commit hash:

For some reason I get this error on discord 12. 
```
Error [TOKEN_INVALID]: An invalid token was provided.
```

But it's fine on discord 11.

**Comment by HarmoGlace** [comment]
Are you sure that you are providing a bot token and not a user token ?

**Comment by Keke27210** [comment]
Support for user accounts was dropped in v12 as they do not respect Discord Terms of Service.
You must use a bot account token in order to use the library.

**Comment by dirt3009** [comment]
😋👢
