### ISSUE TITLE
Issue with client.on() event callback

### ISSUE THREAD

**Issue by ilCollez** [discordjs/discord.js#4132]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
client.on("message", message => console.log(message.cleanContent))
//or any other event
```
Using Intellij, VSCode or any IDE, the arguments of the client.on() callback result as type "any"
![problem](https://user-images.githubusercontent.com/49919202/80365159-6c783080-8887-11ea-9981-83fc13ec33df.jpg)

but if i downgrade to discord.js 12.0.1, this problem disappear
![no_problem](https://user-images.githubusercontent.com/49919202/80365157-6bdf9a00-8887-11ea-8e76-3e7c4d90f3b7.jpg)
this causes an high rate of warning in the IDE and compromises the code completion
**Further details:**

- discord.js version: 12.2
- Node.js version: 12.16.1
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
![image](https://user-images.githubusercontent.com/20760160/80367953-3b4e2f00-888c-11ea-9dbc-9333fd2e7253.png)

![image](https://user-images.githubusercontent.com/20760160/80367979-4acd7800-888c-11ea-91da-bab44f47eb2a.png)

![image](https://user-images.githubusercontent.com/20760160/80367996-4f922c00-888c-11ea-894b-7212191bf50b.png)

I can't seem to reproduce this?

**Comment by ilCollez** [comment]
Uh, that's strange, i'm using 2 different IDEs and all of them gives me this problem, i'll try to download the package from the repository and see if the problem persists

**Comment by iCrawl** [comment]
This is pure JS too, not using TS. But I'd assume using TS it would yield the same result then.

**Comment by kuskoman** [comment]
TS user here, everything is working ![image-of-types-working](https://user-images.githubusercontent.com/15456923/81475935-62ebb280-920f-11ea-9ace-7e6cb53da885.png)

**Comment by ilCollez** [comment]
Okay, i resolved that's a Jetbrains IDE's problem, so i will open a ticket to them to resolve this.
Thank you and specially @samuele794 for for the help.
