### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by IceeyzYT** [discordjs/discord.js#4137]
I've made a music bot and my Terminal says this:

(node:8348) UnhandledPromiseRejectionWarning: TypeError: connection.playStream is not a function
    at play (C:\Users\***\index.js:50:48)
    at C:\Users\***\index.js:84:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 

The Bot joins my channel and the green outline is there too but I don't hear anything pls help

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
