### ISSUE TITLE
RoleResolvable#setColor does not work

### ISSUE THREAD

**Issue by NotAGoodCoderS** [discordjs/discord.js#4141]
When I try to set a role color, it returns `Promise { <pending> }` and does nothing. The role is below my bot's highest role and the bot has administrator permissions.

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by NotAGoodCoderS** [comment]
But it's a bug?

**Comment by almostSouji** [comment]
I can not reproduce this behavior with discord.js version 12.2.0. The role color is set to red as expected.

Please provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) based on the [boilerplate](https://discord.js.org/#/docs/main/stable/examples/ping) on the documentation as well as your discord.js version in use `npm list discord.js` in your console if unsure.

The [issue template](https://paste.nomsy.net/renucuxosa.xml) that pops up when you create a bug report (which you deleted) asks for all that information for a reason, please do not delete it but fill it out instead.

**Comment by SketchyLxve** [comment]
I don't see any behavior, or should I say no behavior at all, as you've provided nothing for us to even remotely understand what it's doing vs. what it's suppose to do. Furthermore, as Souji already redirected you, you should ask in the support server if you have any issues and you will be redirected to the issue tracker if necessary. _This is not a bug._ 
Your client can't change the properties of a role that's it's highest role or the specified role is higher than previously mentioned highest role.

- [Discord Support Server](https://discord.gg/bRCvFy9)

**Comment by SpaceEEC** [comment]
Listen do [`Client#rateLimit`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-rateLimit) and [`Client#debug`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-debug), you are likely being rate limited.

There is a rather large bucket for role updates (1000/24h), which you might have exhausted.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
