### ISSUE TITLE
An option to not mention automatically while replying/quoting a message

### ISSUE THREAD

**Issue by vv7v7** [discordjs/discord.js#4145]
**Is your feature request related to a problem? Please describe.**
There are a lot of servers which prohibit a mentioning without a really important issue which might happen very rare. So they kick/ban people who frequently mention someones.

**Describe the ideal solution**
There's an option to disable mentioning while replying/quoting someone's message. 
If option to automention is disabled, then when clicking on `Quote` button(https://i.imgur.com/3ARRlzR.png), the Discord would copy message's content as it is doing right now, but without mentioning an author.

**Describe alternatives you've considered**
Clicking on `Quote` button, but removing an author each time manually ...

**Additional context**
https://i.imgur.com/3ARRlzR.png

**Comment by almostSouji** [comment]
This is the issue tracker for discord.js, a Discord API wrapper, not Discord itself
If you want a change in behavior for discord this is the place to bring ask for it: <https://support.discordapp.com/hc/en-us/community/topics>

**Comment by vv7v7** [comment]
Created, but nothing appeared at this page after request's submission. Is that okay?
