### ISSUE TITLE
DND not working with intents

### ISSUE THREAD

**Issue by cxllm** [discordjs/discord.js#4150]
Hello. I have recently been verified with my bot and whitelisted for the two intents GUILD_MEMBERS and GUILD_PRESENCES. On my bot, without intents, it will use the status dnd and idle just fine but when I use intents, the bot will not get on dnd. I am really confused by this because as soon as I remove intents, dnd works again. I am very confused. There is no error or anything, it just doesn't work.

```js
const Discord = require('discord.js')
const client = new Discord.Client({
  fetchAllMembers: false,
  disableMentions: "everyone",
  messageCacheMaxSize: 0,
  presence: { status: "dnd" },
  ws: {
    intents: ["GUILDS", "GUILD_MEMBERS", "GUILD_BANS", "GUILD_VOICE_STATES", "GUILD_PRESENCES", "GUILD_MESSAGES", "DIRECT_MESSAGES"],
  }
});
```

- discord.js version: v12.2.0
- Node.js version: v12.16.1
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: Not very important but I would like to fix it

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
I'm unable to replicate this on v12.2.0 - it works for my bot both with and without the GUILD_PRESENCE intent enabled.

**Comment by cxllm** [comment]
That's weird, I keep restarting my bot and it still won't work

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
