### ISSUE TITLE
Orphan Shards

### ISSUE THREAD

**Issue by MrAugu** [discordjs/discord.js#4151]
**Please describe the problem you are having in as much detail as possible:**
If the parent of the shards crashes due to a fatal error (e.g. running out of heap space because of a broadcastEval returning too much data, any other error that crashes that process) shards are left alive daemonized without any other communication to other shards and if you are running the bot with any process manager that restarts the application upon exit, the process manager will respawn other shards resulting in multiple instances of the same shards and only way to shut off the daemon shards it's to manually shut them off or reboot the machine.

**Further details:**

- discord.js version: Master (6367f603f611e9dec2d5365225102fd7758f0e90)
- Node.js version: 12.16.3 LTS
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Low to Medium (it can cause bot to respond multiple times, depending on how often the ShardManager process crashes)

One fix would consist of shards exiting upon the parent process death.

- [x] I have also tested the issue on latest master, commit hash: 6367f603f611e9dec2d5365225102fd7758f0e90

**Comment by uhKevinMC** [comment]
It seems like the library itself does not have shards listen for the `disconnect` event on their respective child process. Implementing the disconnect event will theoretically fix the issue by establishing an IPC channel between the parent and child process, and thus closing the shard if the child process does not have an active IPC channel (channel closes when the parent dies/exits). 

A temporary solution would be to poll the parent process every **X** seconds, but that wouldn't solve the underlying issue.

For now, you can use this chunk that's in this issue in the nodejs repo. [boop](https://github.com/nodejs/help/issues/1790)

**Comment by JMTK** [comment]
I have something like this in my shardmanager process:
```js
async function killAll() {
    try {
        sharder.shards.forEach(shard => {
            shard.kill();
        });
    }
    catch(ex) {
        master.log(ex);
    }

    process.exit(1);
}

process.on('SIGABRT', killAll);
process.on('SIGINT', killAll);
```

Not sure if it's the 100% correct way to do it but it has solved this issue for me. Previously if I didn't do this, the shardmanager might restart and some/all shards might double post messages because the child process was still alive.

**Comment by MrAugu** [comment]
> I have something like this in my shardmanager process:
> 
> ```js
> async function killAll() {
>     try {
>         sharder.shards.forEach(shard => {
>             shard.kill();
>         });
>     }
>     catch(ex) {
>         master.log(ex);
>     }
> 
>     process.exit(1);
> }
> 
> process.on('SIGABRT', killAll);
> process.on('SIGINT', killAll);
> ```
> 
> Not sure if it's the 100% correct way to do it but it has solved this issue for me. Previously if I didn't do this, the shardmanager might restart and some/all shards might double post messages because the child process was still alive.

That is not a fix at all, I'm talking about abrupt crashes of the `ShardingManager` process, which is the root cause of this issue. (You probably misread the original post.)

A dirty walk around for the issue looks somewhat like this:
```js
setInterval(() => {
  if (!client.shard.parentPort) {
    process.exit(0);
  }
}, 400);
```
This would shut off the process when a parent port doesnt exists, in orphan shards the parentPort is `null`.

It isn't ideal but it does its job until it gets fixed.

**Comment by uhKevinMC** [comment]
@MrAugu I've done a PR to fix child process issues. It doesn't seem like workers have this severe of an issue but I'll be working on finding a fix for both.

**Comment by MrAugu** [comment]
Great, only thing left is to wait for #4153 to be merged into master and I'll be closing the issue once that's done.

**Comment by uhKevinMC** [comment]
Would you be willing to test the PR? I have tested it myself but I wanted to make sure it works just fine with you.

You can create your own custom output for it by listening on the `parentDeath` event on the shard, not the client or ShardingManager.

**Comment by MrAugu** [comment]
I will be testing 46035c656f4389a58bfb26ff6352819db251d564 as soon as I get a chance to.

**Comment by MrAugu** [comment]
Okay, my bot is running discord.js 46035c656f4389a58bfb26ff6352819db251d564, if the problem doesn't occur again in 12 to 36 hours, we can say for sure that it's fixed.

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
