### ISSUE TITLE
Role Mention

### ISSUE THREAD

**Issue by a2biR** [discordjs/discord.js#4152]
Hi!

As I was trying to make my bot mention a role (that, btw, was mentionable by everyone, and my bot had all the perms), something unusual happened:

At first glance, the role was mentioned: the blue-text-layout-ui-stuff was here, but the thing is that the role itself wasn't truly mentionned, nobody was pinged. Moreover, the blue text wasn't hoverable or clickable. Just like a classic text. [Here is a screenshot](https://ibb.co/yk0SfcH) of this sort of 'semi-mention'. Keep in mind that on this screenshot, I was hovering the mention, it wasn't clickable, and I wasn't mentioned (despite the fact that I had the admin role). When I asked the API if the role was mentionable (with <role>.mentionable), it returned true. This issue only works with roles, users are easily mentionable. 
Is that the library that made an mistake by sending a wrong `allowed_mentions` whitelist to the API? Is this a bug or a feature?

Here is the part of my code I'm talking about: a simple mention, it doesn't have much interest.
```js
msg.channel.send(`<@&ROLE-ID-HERE>`)
```

Thank you in advance for your answer,

**Further details:**

- **discord.js version:** v12.1.1
- **Node.js version:** v12.16.3
- **Operating system:** Linux
- **Priority this issue should have:** I may have done a mistake, but if I didn't, this may be important

- [ ] I have also tested the issue on latest master

**Comment by ItsPapaia** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by tipakA** [comment]
The permission was forbidden for bot accounts from allowing to mention every role there is, for 60 days after the PR to discord documentation got merged, to allow developers to get used to new feature. Today is day 59, so most likely tomorrow permission will work.

**Comment by a2biR** [comment]
Thanks for your help!
