### ISSUE TITLE
Embed GUI Error

### ISSUE THREAD

**Issue by NightRich** [discordjs/discord.js#4155]
**
Please describe the problem you are having in as much detail as possible:
When I click on the message writing section of the message embeds I sent, it becomes like this. I'm not sure if it's discord error or discordjs error. Related images:

Normally should be on android:
https://cdn.discordapp.com/attachments/701953758543872091/706561174849847336/mobil.jpg

Anormally GUI Examples:
https://cdn.discordapp.com/attachments/701953758543872091/706556818838650940/Screenshot_20200503-050550_Discord.jpg
https://cdn.discordapp.com/attachments/701953758543872091/706498633981493298/Screenshot_20200503-163310_Discord.jpg
**

**Include a reproducible code sample here, if possible:**

```js
const embed = new MessageEmbed()
            .addField('Para Sorgulama Hizmeti', `Paranız: **${result.data.balance} ${server.currency}**`)
            .setColor('PURPLE');

await message.channel.send(embed);
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 10.20.1
- Operating system: Windows & Linux (tested on both)
- Priority this issue should have – please be realistic and elaborate if possible: Middle

- [x] I have also tested the issue on latest master, commit hash:

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.

---

This isn't a d.js issue, but an Android app one. Scrolling up and down fixes it

**Comment by NightRich** [comment]
Oh okey, thank u
