### ISSUE TITLE
Message suppressEmbeds removes message content

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#4170]
**Please describe the problem you are having in as much detail as possible:**
When using <Message>.supressEmbeds() my message content is also removed. I only want embeds to be supressed.

**Include a reproducible code sample here, if possible:**
If it can help, I am editing the message right before supressing embeds.
```js
await message.edit('A new content');
await message.suppressEmbeds();
```

**Further details:**

- discord.js version: latest master 
- Node.js version: v12.16.3
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by anandre** [comment]
If that's your actual code, could possibly be a race condition due to not resolving promises?

**Comment by Koyamie** [comment]
> If that's your actual code, could possibly be a race condition due to not resolving promises?

Sorry edited the example to the actual situation. I've also tried both with and without waiting for promises to resolve and it does the same.

**Comment by ItsPapaia** [comment]
Could it possibly be because `suppressEmbeds` calls `edit` with not content?

**Comment by NotSugden** [comment]
https://github.com/discordjs/discord.js/blob/a6510d6a6185b0b589e3aecb1b22b97bdf50fd04/src/structures/APIMessage.js#L147 
https://github.com/discordjs/discord.js/blob/a6510d6a6185b0b589e3aecb1b22b97bdf50fd04/src/structures/APIMessage.js#L95

i don't currently have time to test this, but could these sections (specifically the 2nd) be causing the issue, passing an empty string when the patch endpoint is called?

**Comment by ItsPapaia** [comment]
> perhaps a fix would be to directly call the patch endpoint in suppressEmbeds

or have `edit` only look at supplied options
