### ISSUE TITLE
guildMemberRemove DiscordAPIError: Unknown Member

### ISSUE THREAD

**Issue by danrleylfd** [discordjs/discord.js#4264]
**Please describe the problem you are having in as much detail as possible:**

https://hasteb.in/utewekej.log

**Include a reproducible code sample here, if possible:**

```js
class GuildMemberRemove {
  constructor(client) {
    this.client = client;
  }
  async run(member) {
    if(!member) return;
    if(member.guild.id !== "693232547160784927") return;
    if(member.user.bot) return;
    const roles = await member.guild.roles.fetch();
    const [role] = roles.cache.array().filter(role => role.id == "704320175318761513");
    await member.roles.add(role);
    const channel = await member.client.channels.fetch("704329147253653635");
    const embed = member.client.getMessage()
      .setAuthor(member.user.tag, member.user.avatarURL)
      .setColor(member.displayHexColor || process.env.EMBEDCOLOR)
      .setTitle(`Adeus ${member.displayName}!`);
    return await channel.send(embed);
  }
}

module.exports = GuildMemberRemove;
```

**Further details:**

- discord.js version: v12.2.0
- Node.js version: v12.16.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
