### ISSUE TITLE
Embed When i type my commands my bot always crash

### ISSUE THREAD

**Issue by MrChocolat25** [discordjs/discord.js#4265]
if (message.content.startsWith(prefix + "serveur")){
let sEmbed = new Discord.RichEmbed()
.setColor(colours.red)
.setTitle("Informations du serveur")
.setAuthor(`${message.guild.name} `, message.guild.iconURL)
.addField("**Votre Nom**", `${message.author.username}`, true)
.addField("**Fondateur  **", `${message.guild.owner}`, true)
.addField("**Membres**", `${message.guild.memberCount}`, true)
.addField("**Nombre de slots**", `50`, true)
.addField("**Se connecter**", `vliferp.fr`, )
.setFooter("Le serveur recherchant la qualité et non la quantité !", client.user.displayAvatarURL);
message.channel.send({embed: sEmbed});
}
if (message.content.startsWith(prefix + "avatar")){
    let sAvatar = new Discord.RichEmbed()
    .setColor(colours.red)
    .setTitle("__**Votre Avatar**__")
    .setAuthor(`${message.guild.name} `, message.guild.iconURL)
    .addField("**Votre Nom** **:**", `${message.author.username}`, true)
    .setImage(message.author.avatarURL)
    .setFooter("Ceci est votre avatar", client.user.displayAvatarURL);
    message.channel.send({embed: sAvatar});
}
if (message.content.startsWith(prefix + "social")){
let sSocial = new Discord.RichEmbed()
    .setColor(colours.red)
    .setTitle("__**Nos réseaux sociaux :**__")
    .addField("__**Notre Twitter**__ :", `__**https://twitter.com/VLifeRP1**__`)
    .addField("__**YouTube**__ :", "__**https://youtu.be/M0zUZKBn0Hk**__")
    .addField("__**Invitation Discord**__ :", "__**https://discord.gg/HKsrZG7**__")
    .addField("__**Voté pour le serveur :**__", "__**https://gta.top-serveurs.net/vote/vlife-5cdda0f71cef6**__")
    .addField("__**Mail**__", "__**v.life.fivem@gmail.com**__")
    .setImage("https://cdn.discordapp.com/attachments/587752877741834272/588127270384697415/logo11.png")
    .setFooter("Pour toute autres informations MP Bot VLife", client.user.displayAvatarURL);
    message.channel.send({embed: sSocial});
}

**Comment by Darqam** [comment]
This issue page is for discord library concerns, not bug fixing of your own code. Kindly go to the support server (https://discord.gg/bRCvFy9) in order to get support.
