### ISSUE TITLE
LimitedCollection

### ISSUE THREAD

**Issue by TheNoob27** [discordjs/discord.js#4274]
**Is your feature request related to a problem? Please describe.**
There are scenarios where I would actually want to use the Limited Collection class, but you cannot import the LimitedCollection class from discord.js, unless you do something like the following: 
```js
const LimitedCollection = require(require.resolve("discord.js").replace("index.js", "util/LimitedCollection.js"))
```
In the discord.js docs, it's listed as Private, but it says that you can initiate the class with 
```js
new Discord.LimitedCollection(maxSize, iterable);
``` 
but this isn't true as its not in the `src/index.js` file and doesn't get imported when you require the library.

**Describe the ideal solution**
I suppose it would make sense to simply add it to the `src/index.js` file, or even add it in the `@discordjs/collection` package in some way.

I guess it would be easy to recreate it or just use the alternative way of getting the class but it'd be so much more simple if it was added to the index file and/or made public.

**Comment by ItsPapaia** [comment]
you could also do `require('discord.js/src/util/LimitedCollection')`.

Also, there was a PR to remove docs and exporting for the limited collection.

**Comment by TheNoob27** [comment]
Last time i tried something like that it didn't work, maybe i did something wrong

**Comment by Poly-Pixel** [comment]
Is there a reason why `LimitedCollection` isn't in the src/index.js file?

If there is a valid reason, the docs should mention that you have to import them separately.
