### ISSUE TITLE
Uncached channels if structures used.

### ISSUE THREAD

**Issue by Satont** [discordjs/discord.js#4275]
**Please describe the problem you are having in as much detail as possible:**
I has very simple bot, for listening `message` event.

My problem is, bot not receiving that event from some guilds.

**Include a reproducible code sample here, if possible:**

```ts
import { Client, Strutures } from 'discord.js'
Structures.extend('Guild', Guild => {
  class CoolGuild extends Guild {
    constructor(client, data) {
      super(client, data);
      this.load()
    }
    async load() {
      // async stuff here //
      this.cool = true
    }
  }

  return CoolGuild;
})

const client = new Client({ 
  partials: ['MESSAGE', 'GUILD_MEMBER'],
  ws: { intents: ['GUILDS', 'GUILD_MESSAGES', 'GUILD_VOICE_STATES', 'GUILD_MEMBERS'] }
})

client.on('message', async (msg) => {
  console.log(msg)
})

client.login(process.env.DISCORD_TOKEN)
```

**Further details:**

- discord.js version: 12.2
- Node.js version: 14.2
- Operating system: Tried on debian, Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: middle
- Tried without partials - same behavior.
- Tried without intents - same behavior.
- Tried:
```ts
client.on('ready', () => {
 console.log(client.channels.cache.size)
})
```
W/ structures it has smaller size of channels.

So, problem in structures.

- [x] I have also tested the issue on latest master, commit hash: 2583ad5da7db5ab92dfa357909f9c713db0a2981

**Comment by SpaceEEC** [comment]
I can not reproduce this with the given code.

I also tried it using:
- No intents
- No partials
- No structures
- 11.6.3

The behavior was always the same: Same amount of channels and message events being emitted.

**Comment by Satont** [comment]
Thats strange. I'm actually doing some async stuff and set guild prop on this result, like 

```ts
Structures.extend('Guild', Guild => {
  class CoolGuild extends Guild {
    constructor(client, data) {
      super(client, data);
      this.load()
    }
    async load() {
       const request = await db().get(this.id)
       this.cool = request.cool
    }
  }

  return CoolGuild;
})
```
But w/o that structure it's working fine

**Comment by SpaceEEC** [comment]
Please edit your code in your issue template to actually reproduce this issue, otherwise there isn't much we can do.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
