### ISSUE TITLE
 DiscordjsError: Request to use token, but token was unavailable to the client.

### ISSUE THREAD

**Issue by ShaneCooke** [discordjs/discord.js#4276]
Hello all,

I have been wrapping my head around a pole for a few hours trying to figure this out.

I'm quite positive now that i'm not being an idiot, but something may be wrong.

More so, because this works in V11 of DiscordJS but seems to cause problems with V12 of DiscordJS (Note: with the change from Promise on client.destroy())

This error is created by logging in with client.login('Token') and then waiting for the ready event (Obviously) and then actioning client.destroy(), at which point I noticed the client did not destroy so I added a message event into the mix to see if the client was still responsive to discord messages etc.

At which point, the console starts to produce the same recurring error every time a message is received to the client, even knowing the client was previously 'destroy'ed.

Console Log:
`(node:2570095) UnhandledPromiseRejectionWarning: DiscordjsError: Request to use token, but token was unavailable to the client.
    at RequestHandler.execute (/daemon/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at RequestHandler.push (/daemon/node_modules/discord.js/src/rest/RequestHandler.js:41:19)
    at /daemon/node_modules/discord.js/src/rest/RESTManager.js:41:10
    at new Promise (<anonymous>)
    at RESTManager.push (/daemon/node_modules/discord.js/src/rest/RESTManager.js:39:12)
    at RESTManager.request (/daemon/node_modules/discord.js/src/rest/RESTManager.js:60:17)
    at Proxy.<anonymous> (/daemon/node_modules/discord.js/src/rest/APIRouter.js:30:19)
    at TextChannel.send (/daemon/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:174:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2570095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`

Cheers! :)

**Comment by 1s3k3b** [comment]
According to the stack trace, sending a message causes the error, not recieving it, that does not require a token. The client should not recieve messages though, as `<Client>.destroy()` ends the websocket connection. Do all messages get emitted?

**Comment by ShaneCooke** [comment]
I have not tried emitting a message, as obviously shouldn't be possible.

However, when receiving events and messages, it outputs that error which is obviously not supposed to the case, as... it's suppose to end the WebSocket.

From my tests, all messages events were causing that error repeatedly.

**Comment by vladfrangu** [comment]
A couple of things

1. Please fill in the template 
2. Can you get us a code sample that repros the issue?
3. Can you log the debug event and see what it logs? Check #3201 how to add logging without log spam! :D

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
