### ISSUE TITLE
ShardingManager --inspect-brk debugging

### ISSUE THREAD

**Issue by phosphene47** [discordjs/discord.js#4277]
**Is your feature request related to a problem? Please describe.**
AFAIK it is currently still not possible to debug sharded bots and place breakpoints. In a related issue #1714, it allows me to pass `--inspect-brk` to the shard process. This is better than nothing, but [VSCode can't use it](https://github.com/microsoft/vscode/issues/52373).

**Describe the ideal solution**
1. ShardingManager should automatically add `--inspect-brk={unique random port}` to shard process's execArgv if the host process has a debugger attached.
2. Make `execArgv` config of ShardingManager accept `string[] | () => string[]` allowing consumers to compute args (i.e. unique random port) for each shard.

**Describe alternatives you've considered**
To not debug sharded bots(...)

**Additional context**

**Comment by JMTK** [comment]
I was able to when I manually did a `debugger;` statement. It might have been in `worker` mode where they all share the same ProcessID
