### ISSUE TITLE
presenceUpdate not working when a user has started streaming.

### ISSUE THREAD

**Issue by YaroslavMolchan** [discordjs/discord.js#4280]
I trying to use presenceUpdate:

`client.on('presenceUpdate', (oldMember, newMember) => {
	console.log(oldMember);
	console.log(newMember);
});`

It's working good with Spotify and I can see that it triggered when someone is playing, and i see status `CUSTOM_STATUS` but when I start streaming on Twitch (Turning on OBS), status changed on Discord, but event presenceUpdate not working, can it be a bug?

Discord.js version: 12.2.0

**Comment by 1s3k3b** [comment]
Discord.js seems to always emit presenceUpdate events recieved through the gateway, so if it does not emit for something, it probably isn't recieved from Discord.

**Comment by IanMitchell** [comment]
I'm also running into this - the activity array lists custom status and game currently being played but doesn't record streaming (whether it be Discord streaming or some other service like Twitch)

**Comment by Shompi** [comment]
Could it be that you don't have the presence intent allowed in your bot? Check it in discordapp.com developers page -> Bot

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.

**Comment by RedTn** [comment]
is this still an issue? i turned on intents and theres no event fired for streams, but seems to fire an event when a user starts playing a game
