### ISSUE TITLE
client.on('messageReactionAdd') is firing twice for reactions added by BOTs

### ISSUE THREAD

**Issue by MidSpike** [discordjs/discord.js#4284]
The 'messageReactionAdd' event fires twice for reactions added by bots

```js
client.on('messageReactionAdd', (messageReaction, user) => {
  console.log('test');
});
// 'test' logs twice in the console
// that is the only listener in all of my code for 'messageReactionAdd'
```

**Further details:**
- discord.js version: 12.2.0
- Node.js version: 14
- Operating system: Windows 10
- Priority: idk
- [] I have also tested the issue on latest master, commit hash:

**Comment by MidSpike** [comment]
![image](https://user-images.githubusercontent.com/22574513/81770578-b7f92400-94ae-11ea-8d05-cc56ed94b301.png)

**Comment by NotSugden** [comment]
https://github.com/discordjs/discord.js/blob/2583ad5da7db5ab92dfa357909f9c713db0a2981/src/structures/Message.js#L479-L484

this seems to be what's causing the issue, the handler/action is called, then the event is recieved and thus emitted twice, not sure of the best way to fix this at the moment

**Comment by MidSpike** [comment]
sorry about closing and reopening.
GitHub app on Android is weird

**Comment by arthur-lchl** [comment]
I'm having the same issue.
Tried with two different bots; using `discord.js@12.2.0`.

```js
require('dotenv').config()
const Discord = require('discord.js');

const client = new Discord.Client();

client.once('ready', () => console.log(`Logged in as ${client.user.tag}.`));

client.on('message', (message) => {
  console.log(`${client.user.tag} will react.`)
  message.react('🤔');
});

client.on('messageReactionAdd', (reaction, user) => {
  console.log(`${user.tag} reacted ${reaction.emoji.name} on message ${reaction.message.id}.`);
});

client.login(process.env.TOKEN);

```

The following output is produced when I send a message on Discord.
```
Logged in as Somebot#8206.
Somebot#8206 will react.
Somebot#8206 reacted 🤔 on message 740579311504982017.
Somebot#8206 reacted 🤔 on message 740579311504982017.
```

**Comment by ryandury** [comment]
Also experiencing this issue.

**Comment by BannerBomb** [comment]
This seems to still be reproducible if the bot has just started up, then you have the bot send a message, clear the message cache then react to that message while using partials it'll fire twice.

 I know the code is there to resolve the information into a reaction emoji but removing these lines https://github.com/discordjs/discord.js/blob/2583ad5da7db5ab92dfa357909f9c713db0a2981/src/structures/Message.js#L477-L485 did fix the issue while keeping the normal functionality of the event listener.

The first time the event is emitted, the partial value on the reaction is false, but the second time it's emitted it is true.

**Include a reproducible code sample here, if possible:**

## Steps to reproduce:
1. Start-up the bot.
2. Execute the following code.
```js
// The `message` variable is from the `message` event.
const msg = await message.channel.send('this is a message');
msg.channel.messages.cache.clear();
await msg.react(':smile:');
```

**Further details:**

- discord.js version: 12.5.0
- Node.js version: v14.10.0
- Operating system: Ubuntu 18.04.2 LTS

**Relevant client options:**

- partials: ['MESSAGE', 'REACTION', 'USER', 'GUILD_MEMBER']
- gateway intents: ['GUILD_MEMBERS', 'GUILDS', 'GUILD_MESSAGES', 'GUILD_MESSAGE_REACTIONS', 'GUILD_VOICE_STATES']
- other: none

- [x] I have also tested the issue on latest master, commit hash: [`9f3c3e0`](https://github.com/discordjs/discord.js/commit/9f3c3e091844d22793cfd2880ffc2936ce41feab)
