### ISSUE TITLE
client/shard is null during fetchClientValues call

### ISSUE THREAD

**Issue by MattIPv4** [discordjs/discord.js#4286]
**Please describe the problem you are having in as much detail as possible:**

During a call to `client.shard.fetchClientValues` from one of my shards, an unhandled error is thrown internally by the library which appears to suggest one of the shards/clients is null:

```
Error [TypeError]: Cannot read property 'on' of null
    at <bot>\node_modules\discord.js\src\sharding\Shard.js:239:13
    at new Promise (<anonymous>)
    at Shard.fetchClientValue (<bot>\node_modules\discord.js\src\sharding\Shard.js:230:21)
    at ShardingManager.fetchClientValues (<bot>\node_modules\discord.js\src\sharding\ShardingManager.js:250:67)
    at Shard._handleMessage (<bot>\node_modules\discord.js\src\sharding\Shard.js:326:22)
    at ChildProcess.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  name: 'TypeError'
}
```

**Include a reproducible code sample here, if possible:**

Unable to reliably reproduce, no idea what's causing client/shard to be null.

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.10.0
- Operating system: macOS 10.14
- Priority this issue should have – please be realistic and elaborate if possible: P2 - definitely breaking but a workaround can be made for now

**Comment by ObliviousDonkey** [comment]
Discord.js sucks. My bot was in 2.4K guilds. I switched to discord.py before too long.

**Comment by MattIPv4** [comment]
After much digging through the logic in ShardingManager and Shard, I think Ive found the cause.

If the user calls `eval` or `fetchClientValue` on a shard whilst it is in the process of respawning, where a delay was set between `kill` and `spawn`, then the `eval` will happen with both `worker` & `process` being `null`. This on the face of it is fine, it'll throw an error which is to be expected given the shard is respawning. However, d.js caches promises generated from `eval` and `fetchClientValue` calls, which will cache the `null` state of `worker` & `process` forever in that call, resulting in subsequent calls to the same `eval`/`fetchClientValue` prop throwing the same error even if the start has since spawned.

Will make a PR to fix this in two ways:

1. Throw a custom error if `eval` or `fetchClientValue` is called whilst a shard is respawning, without caching the promise.
2. Clear cached `eval`/`fetchClientValue` promises at the point a new shard process is created.
