### ISSUE TITLE
channel.nsfw returns undefined if the channel is not nsfw

### ISSUE THREAD

**Issue by AlexDiego123** [discordjs/discord.js#4296]
Hello,i was wondering because if a channel is not nsfw it returns undefined

this is a code sample

```js
module.exports = {
	name: 'channel-info',
	execute(message, args) {
               let channel = message.guild.channels.cache.find(channel => channel.name === 'Public Channel')

               message.channel.send(`Nsfw: ${channel.nsfw}`)
		}
```

this is my code:

```js
const Discord = require('discord.js')
module.exports = {
	name: 'channel-info',
	execute(message, args) {
		if (!message.member.hasPermission('MANAGE_CHANNELS')) return message.channel.send(`${message.author.username} Non Hai Il Permesso Di Fare Il Comando __**channel-info**__`)
		
		if(!message.guild.me.hasPermission('MANAGE_CHANNELS')) return message.channel.send('Non Ho Il Permesso Di Vedere Le Informazioni Di Un Canale')

		let Nomecanale = message.content.substring(message.content.indexOf(' ')+1)

		let canale = message.guild.channels.cache.find(channel => channel.name === (Nomecanale))

		if(!canale) return message.channel.send('Canale Non Trovato')

        const channelinfo = new Discord.MessageEmbed()
	.setColor('ff0000')
	.setTitle(`Ecco Le Informazioni Del Canale: ${canale.name}`)
	.setDescription(`**Nome: ${canale.name}\nDescrizione: ${canale.topic}\nCategoria: ${canale.parent}\nTipo: ${canale.type}\nPosizione: ${canale.position}\nID: ${canale.id}\nSlowmode: ${canale.rateLimitPerUser}\nNsfw: ${canale.nsfw}\nVelocità Di Trasmissione: ${canale.bitrate}**`)
	.setTimestamp()
	.setFooter(`Comando Eseguito Da: ${message.author.username}`);
		

message.channel.send(channelinfo);
		}
	}
```

discord.js version: v12.2.0

node.js version: v12.16.2

operating system: Windows 7

**Comment by almostSouji** [comment]
The NSFW feature (and accordingly the `.nsfw` property is only ever present on a TextChannel (where it returns `true` or `false`)

The property is not present on non-textchannels, as such will return `undefined`

reference:
- <https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=nsfw>
- <https://discord.js.org/#/docs/main/stable/class/GuildChannel> (and its more specific subclasses apart from TextChannel) - no nsfw

**Comment by AlexDiego123** [comment]
No even if its a text channel it returns undefined

**Comment by almostSouji** [comment]
I can not reproduce this behavior.

However looking into your code sample:
As you are searching for the name "Public Channel" and seem to get a valid channel from it, it can not really be a TextChannel. Text channels follow a naming convention of only lowercase letters and no spaces, which would never be found with this predicate, it'd be "public-channel".

**Comment by almostSouji** [comment]
After some more considerations and tests I can indeed find channels of type "text" where the `.nsfw` property returns undefined - I'm unsure yet what the exact circumstances are that cause this behavior. I tested manually removing a channel from the cache and fetching it from the API, which returns the proper `false` value for the `.nsfw` property

**Comment by AlexDiego123** [comment]
ok now i close this issue

**Comment by almostSouji** [comment]
me being able to reproduce this does not lead to the issue being resolved, please keep it open so we can actually keep track of it

**Comment by NotSugden** [comment]
this seems to be caused by
https://github.com/discordjs/discord.js/blob/2583ad5da7db5ab92dfa357909f9c713db0a2981/src/structures/TextChannel.js#L44

my guess is some channel packet is being sent causing an update, but it doesn't include the 'nsfw' property, this may also apply to other properties too

**Comment by NotSugden** [comment]
done some checks, and it seems that the `nsfw` property isn't even sent sometimes on the initial GUILD_CREATE packets, seems like this could be a problem with the API?

**Comment by AlexDiego123** [comment]
> me being able to reproduce this does not mean that the issue is resolved, please keep it open so we can actually keep track of it

ok i reopened the issue
