### ISSUE TITLE
Suggestion: property to have the escaped username/nickname/displayname of a User/GuildMember

### ISSUE THREAD

**Issue by noftaly** [discordjs/discord.js#4304]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to show a username/displayname without mentionning the member, and if the "context" supports markdown, then it parses the markdown and will bold/underline/etc the name...

**Describe the ideal solution**
What would be nice is to have a property on a User and a GuildMember to have the escaped username/nickname/displayname

**Describe alternatives you've considered**
Well i don't see any other alternatives

**Additional context**
None

**Comment by tipakA** [comment]
[`Util.escapeMarkdown`](https://discord.js.org/#/docs/main/master/class/Util?scrollTo=s-escapeMarkdown) is a thing already.

**Comment by noftaly** [comment]
Yes but we have to use it manually. The point of my feature request is to have a property directly in the GuildMember/User objects

**Comment by tipakA** [comment]
You can implement that in your code using [`Structures.extend`](https://discord.js.org/#/docs/main/stable/class/Structures?scrollTo=s-extend)

**Comment by noftaly** [comment]
Yes but I'm proposing a new feature to add to the discordjs library itself because it could be useful to multiple people. It is the same as `GuildMember.displayName`: a simple thing that everyone could have done himself, but it is useful and could profit to anyone so it is a thing. For me, `Structures.extend` is what you should use to add things that have nothing to do in discordjs. For instance, I used it to create custom methods on TextChannel to send an Error embed. But I'm suggesting something that multiple people might need.

**Comment by tipakA** [comment]
Except that doing so is extremely easy using aforementioned `Util.escapeMarkdown`, in literally one line. Additionally, even if someone would implement such getter to member and/or user object, it would do exactly that - use `Util.escapeMarkdown`.

If going by that logic - having a very easy to implement on your own thing implemented in the library itself - why is there no `notBotMessage` event that would only emit for messages sent by users that are not bots?

**Comment by iCrawl** [comment]
For the reasons mentioned this is most likely not going to happen.
