### ISSUE TITLE
Type declarations lacking

### ISSUE THREAD

**Issue by Pwuts** [discordjs/discord.js#4305]
**Please describe the problem you are having in as much detail as possible:**
I'm working on a Discord bot, and of course my IDE uses `index.d.ts` to autocomplete a lot of things. The problem is that the available TypeScript types are lacking the actual functionality of the library.

Example:
```TS
/* in index.d.ts */

interface ActivityOptions {
    name?: string;
    url?: string;
    type?: ActivityType | number;
    shardID?: number | number[];
}
```
vs
```JS
/* in Presence.js */

class Activity {
  constructor(presence, data) {
    /* condensed for pasting */
    this.name = data.name;
    this.type = ActivityTypes[data.type];
    this.url = data.url || null;
    this.details = data.details || null;
    this.state = data.state || null;
    this.applicationID = data.application_id || null;
    this.timestamps = data.timestamps
      ? {
          start: data.timestamps.start ? new Date(Number(data.timestamps.start)) : null,
          end: data.timestamps.end ? new Date(Number(data.timestamps.end)) : null,
        }
      : null;
    this.party = data.party || null;
    this.assets = data.assets ? new RichPresenceAssets(this, data.assets) : null;
    this.syncID = data.sync_id;
    this.flags = new ActivityFlags(data.flags).freeze();
    this.emoji = data.emoji ? new Emoji(presence.client, data.emoji) : null;
    this.createdTimestamp = new Date(data.created_at).getTime();
  }
}
```

I'm sure some of these properties are not intended to set externally, but I can now figure out how to set a custom status from neither the [documentation](https://discord.js.org/#/docs/main/master/typedef/ActivityOptions) nor the TypeScript declarations.

**Further details:**

- discord.js version: v12.2.0
- Node.js version: v14.x
- Operating system: Windows / Ubuntu
- Priority this issue should have: high

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
That's because you cannot set a custom status for bots, which is why those properties are not part of the `ActivityOptions` type definition for setting activities.

You can, however, read the custom status of Users, which is why those properties are part of the definition of an Activity. These are constructed from `PRESENCE_UPDATE` events received from the gateway.

No functionality or typings here are incorrect.

**Comment by Pwuts** [comment]
Thanks for the clarification.

**Comment by Pwuts** [comment]
I thought it would be in there after this comment 7 months ago https://github.com/discord/discord-api-docs/issues/1160#issuecomment-546549711
