### ISSUE TITLE
High Memory Cache Usage

### ISSUE THREAD

**Issue by AppEternal** [discordjs/discord.js#4306]
**Please describe the problem you are having in as much detail as possible:**
I've been having a memory problem with my bot for the last month or so and after trying to locate memory leaks in my own code I decided to run discord.js on its own and logging cache info every few minutes; after 5 days I noticed that about 20 out of 180 of the shards have 3gb+ memory usage while the other 160 have 600mb or less for no reason I can find.

**cache.size checked:**
emoji, messages, members, channels, users and presence (always empty)

**Screenshots:**
highest 10 shards: https://i.imgur.com/jIdUWIK.png
lowest 10 shards: https://i.imgur.com/ZPozRzv.png
(there's a number of shards in the 400-600mb range with over 90k messages)

**Include a reproducible code sample here, if possible:**
```js
const client = new Discord.Client({
	messageCacheMaxSize: 1000,
	messageCacheLifetime: 43200,
        messageSweepInterval: 3600,
    ws:{
        intents:[
            "GUILDS",
            "GUILD_MEMBERS",
            "GUILD_BANS",
            "GUILD_EMOJIS",
            "GUILD_INVITES",
            "GUILD_MESSAGES",
            "GUILD_MESSAGE_REACTIONS",
            "DIRECT_MESSAGES",
            "DIRECT_MESSAGE_REACTIONS",
        ]
    },
});
const init = async () => {
    client.on("ready",(event)=>{
        console.log(`Logged into Shard: ${client.shard.ids[0]}`);
        //cache logging setInterval
    });
    client.login("--Token--");
};

init();
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 12.14.1
- Operating system: Ubuntu 18.04.3
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by navi1995** [comment]
Have you had any luck with some fixes with this? My cache also seems to grow to quite unreasonable numbers (I have client options as 
```
messageCacheMaxSize: 100,
messageCacheLifetime: 7300, 
messageSweepInterval: 600,
```

Currently I have 4 days uptime with memory usage around 580mb with 2.3k servers. Would love some way to disable cache for any elements that I might not need.

**Comment by bdistin** [comment]
You guys do realize that messageCacheLifetime and messageSweepInterval are in seconds right?
<https://github.com/discordjs/discord.js/blob/master/src/client/Client.js#L161>
<https://github.com/discordjs/discord.js/blob/master/src/client/Client.js#L310>
If you are keeping messages for 2hrs @navi1995 and 12hrs @AppEternal ... you are likely maxing out your 100 messages * how many text channels you have.

**Comment by navi1995** [comment]
> You guys do realize that messageCacheLifetime and messageSweepInterval are in seconds right?
> https://github.com/discordjs/discord.js/blob/master/src/client/Client.js#L161
> https://github.com/discordjs/discord.js/blob/master/src/client/Client.js#L310
> If you are keeping messages for 2hrs @navi1995 and 12hrs @AppEternal ... you are likely maxing out your 100 messages * how many text channels you have.

Yup, unfortunately, I need to store the message for 2 hours as my bot runs polls where any previous 'reacts' from a user must be removed to ensure one vote per person. With the message being swept, the collector no longer works.

**Comment by Fyko** [comment]
> With the message being swept, the collector no longer works.

Word of advice here, using collectors in the long term is not the best idea. You *should* be created a document/row in your database for each "poll" and listen on the Client#messageReactionAdd event. 

> Yup, unfortunately, I need to store the message for 2 hours as my bot runs polls where any previous 'reacts' from a user must be removed to ensure one vote per person.
Why do you need to remove the reaction? You can just fetch the reaction when its time to "close the poll" and read the `count` property.

**Comment by bdistin** [comment]
My point is, the figures you are sharing, and the sweep strategy you are using, are not out of line for the massive number of messages you are almost certainly storing.

**Comment by AppEternal** [comment]
> 
> 
> Have you had any luck with some fixes with this? My cache also seems to grow to quite unreasonable numbers (I have client options as
> 
> ```
> messageCacheMaxSize: 100,
> messageCacheLifetime: 7300, 
> messageSweepInterval: 600,
> ```
> 
> Currently I have 4 days uptime with memory usage around 580mb with 2.3k servers. Would love some way to disable cache for any elements that I might not need.

I was not able to locate what part part of the script is causing the high memory usage on some shards vs others.
I don't believe message cache is actually the issue, I've tested reducing the limit to only 10 max size with a lifetime of 30s and it still had the issue..

(All tests were preformed on a fresh install and only used the bare minimum to start the bot and monitor it's usage.)

My current "fix" is on shardResume it checks the bots current memory usage and restarts itself if the shard is over x amount of memory. 130 of my shards never restarts while the last 50 restart every 2-3 days.

**Comment by navi1995** [comment]
> Word of advice here, using collectors in the long term is not the best idea. You _should_ be created a document/row in your database for each "poll" and listen on the Client#messageReactionAdd event. Query your database (or some sort of cache, you do you) on each reaction and handle it from there.

> Why do you need to remove the reaction? You can just fetch the reaction when its time to "close the poll" and read the `count` property.

@Fyko Thanks I'll look into implementing that! Essentially I need to remove the reaction to ensure there is no inflation of the results as the polls taking place. When you go to the polling booths IRL and you tick every name instead of one, they're not just going to take your first tick right?

>My point is, the figures you are sharing, and the sweep strategy you are using, are not out of line for the massive number of messages you are almost certainly storing.

@bdistin Yup absolutely agree, was just wondering if there's other parts of the library I could tap into in order to reduce memory usage some other way
