### ISSUE TITLE
[Stryker] TypeError: TextDecoder is not a constructor

### ISSUE THREAD

**Issue by C0ZEN** [discordjs/discord.js#4312]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

Having the error `TypeError: TextDecoder is not a constructor` when using it with Stryker.

**Further details:**

This is not a high priority at all since this is related to testing.
I just want to know which is the culprit.
You can checkout [this issue](https://github.com/stryker-mutator/stryker/issues/2220) I opened on the Stryker repository which contains a lot of information.

**Comment by uhKevinMC** [comment]
Can you please provide a chunk of code relative to where the error is? The issue you linked isn't exactly providing something djs related.

**Comment by C0ZEN** [comment]
@uhKevinMC at the bottom of the [linked issue](https://github.com/stryker-mutator/stryker/issues/2220) a [stryker.log](https://github.com/stryker-mutator/stryker/files/4672465/stryker.log) was provided containing a stack trace.

The error seems to happen just with:

```javascript
const discord_js_1 = require("discord.js");
```

**Comment by uhKevinMC** [comment]
What engine are you using to run the code? Node.js afaik is the supported engine for djs.

**Comment by C0ZEN** [comment]
@iCrawl why close it?

**Comment by iCrawl** [comment]
Because I don't know what you expect us to fix here. This is not an issue in Node.js or Webpack.

Here is something you can do when you use Jest to make sure you are in the correct environment https://github.com/discordjs/discord.js/issues/3971#issuecomment-602010271

**Comment by C0ZEN** [comment]
ok well I am still waiting a response from Stryker but honestly at this point this is frustrating that after two months nobody can tell me if this is a problem with the exports from Discord or from Stryker and I am waiting for more than two months now.
And the configuration being quite simple I am also wondering if this is an issue that I have only in my project or if this is something not working at all for every project but simply nobody uses Strycker with Discord. 😢

**Comment by ghostdevv** [comment]
@C0ZEN Are you still having this issue? I am having it with jest

**Comment by ghostdevv** [comment]
I managed to fix this by setting the test environment to node with jest

**Comment by C0ZEN** [comment]
@ghostdevv thank you for the replay and sadly yes I already have this in my config.
