### ISSUE TITLE
Fetching a large amount of specific guild members will always timeout

### ISSUE THREAD

**Issue by SpeedyCraftah** [discordjs/discord.js#4313]
**Please describe the problem you are having in as much detail as possible:**

When attempting to fetch a large amount of specific guild members by passing user IDs in `<guild>.members.fetch`, it will **always** result in a timeout error. Keep in mind just fetching every guild member by passing no options resolves with them in about a second with a 30k member guild. I tested this with 200 IDs of unique members which caused this, small amounts work just fine.
I have also attempted to set an even larger timeout time (20 minutes) and the same occurred.

**Include a reproducible code sample here, if possible:**

```js
await message.guild.members.fetch({ user: [array of 200 unique user IDs (all in the server)] });
```
> Resulted in: (eval)
![image](https://user-images.githubusercontent.com/45142584/82740502-36708400-9d41-11ea-9ffa-4510c56b3458.png)

**Further details:**

- discord.js version: V12.2.0 Master Branch
- Node.js version: 12
- Operating system: Ubuntu 19
- Priority this issue should have – please be realistic and elaborate if possible: Not certain, in my personal case it should be high as the bot relies on fetching multiple guild members in one/minimal calls.

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Keke27210** [comment]
This seems to be more of an issue on the Discord side. In the case of a server with about 5000 members, from the 192nd user ID Discord simply stops sending chunks as if the request becomes invalid.
I think this is a limit that grows over time (why choose such a number arbitrarily).

**Comment by SpeedyCraftah** [comment]
> This seems to be more of an issue on the Discord side. In my case, from the 192nd user ID onwards chunks are no longer sent. I don't know if it's a bug (why such a number as a limit) but it's not on the discord.js side.
> 
> From the official documentation:
> Requesting `user_ids` will continue to be limited to returning 100 members
> 
> Which means you should restrict to 100 members max (not sure if that 100-191 is intended).

Oh so it's like reactions, I just have to make multiple calls. Great, thank you for the information.
