### ISSUE TITLE
Message.react method's returned promises resolves before the reaction is placed on the message

### ISSUE THREAD

**Issue by RafRunner** [discordjs/discord.js#4316]
When you await the promises returned by the Message.react method (Promise<MessageReaction>) the promise resolves before the message is actually reacted to.

This can be shown by creating a message collector and listening for the 'collect' event just after waiting for the Promise<MessageReaction> to resolve. If the collector is listening for the same emoji as the bot is reaction, the event will trigger even tho the collect is only created after the reaction is resolved.

Sample code to replicate this bellow:

```js
'use strict';

const Discord = require('discord.js');

const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged as: ${client.user.tag}`);
});

client.on('message', async (msg) => {
  if (msg.content !== '?test') {
    return;
  }

  await msg.react('▶️');

  const filter = (reaction) => reaction.emoji.name === '▶️';
  const collector = msg.createReactionCollector(filter, { time: 120 * 1000, max: 1000 });

  collector.on('collect', (reaction) => console.log(reaction));
});

client.login('put any bot`s token here');
```

Running this and using the ?test commend in any channel with the bot you will notice the bot's own reaction gets logged into the console.

I know this is fixable by just checking is the reaction is coming from the bot itself, but it's a bug nonetheless, it should not need to be checked. But since it has a easy workaround the priority is low.

**Further details:**

- discord.js 12.2.0:
- Node.js 14,1,0:
- Operating system: Windows 10
- Priority this issue should have: low

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
