### ISSUE TITLE
ReactionCollector`s 'remove' event is never called

### ISSUE THREAD

**Issue by RafRunner** [discordjs/discord.js#4317]
First I'd like to say that I googled this problem before opening this issue and I saw another issue here about this that was already closed like 2 years ago, but the bug persists in the new version so I'm opening this.

To be short, the 'remove' event of the ReactionCollector is never called, not when a reaction is removed not when a reaction is disposed.

Yes, I tried not listening to other events and I tried changing the filter and configurations of the MessageCollector (even tho it should work in this case).

The error can be replicated with the code bellow:

```js
'use strict';

const Discord = require('discord.js');

const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged as: ${client.user.tag}`);
});

client.on('message', async (msg) => {
  if (msg.content !== '?test') {
    return;
  }

  await msg.react('◀️');
  await msg.react('▶️');

  const filter = (reaction) => reaction.emoji.name === '▶️' || reaction.emoji.name === '◀️';
  const collector = msg.createReactionCollector(filter, { time: 120 * 1000, max: 1000 });

  collector.on('collect', (reaction) => console.log(reaction));
  collector.on('remove', (reaction) => console.log(reaction));
});

client.login('put any bot`s token here');
```

Just run the bot in any server, use the ?test command and try reacting and then removing the reaction in the command message. You will see that the 'collect' event works just fine, but the 'remove' one doesn't. You will also notice another problem pointed by me in issue #4316 

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.1.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium, there are workarounds, but they are ugly involving setting up timers and counting reactions.

- [x ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
The `Collector#remove` and `Collector#dispose` events need to be enabled by providing `dispose: true` as a CollectorOption.

**Comment by RafRunner** [comment]
Oh, I see, guess this slipped by when I was reading the documentation, sorry, I'll close the Issue
