### ISSUE TITLE
Can't Send Anything by WebHooks

### ISSUE THREAD

**Issue by Sardonyx78** [discordjs/discord.js#4319]
**Please describe the problem you are having in as much detail as possible:**
I am executing the code below. It throws an error.
The error trace:
```
TypeError: Cannot read property 'disableMentions' of undefined
     at APIMessage.makeContent (/app/node_modules/discord.js/src/structures/APIMessage.js:95:38)
     at APIMessage.resolveData (/app/node_modules/discord.js/src/structures/APIMessage.js:149:26)
    at Webhook.send (/app/node_modules/discord.js/src/structures/Webhook.js:146:62)
```
**Include a reproducible code sample here, if possible:**

```js
  const { Webhook, MessageEmbed } = require("discord.js")
  const wh = new Webhook("15108731800649728", "webhooktoken")
  wh.send('hi')
```

**Further details:**

- discord.js version: v12.2.0
- Node.js version: v12.17.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:

- [ x ] I have also tested the issue on latest master, commit hash: b0b62d63cf5545034a65bcf7ce0d80d2bf716354

**Comment by NotSugden** [comment]
https://github.com/discordjs/discord.js/blob/stable/src/structures/Webhook.js#L13
the webhook class needs `client` and `data` parameters to be initialized, not and ID and a token, perhaps you are looking for the WebhookClient class

**Comment by Sardonyx78** [comment]
oh sorry
