### ISSUE TITLE
Memory leak on internal buffers

### ISSUE THREAD

**Issue by Golorio** [discordjs/discord.js#4320]
**Please describe the problem you are having in as much detail as possible:**
I seem to be having a memory leak coming from internal buffers. 

I have taken multiple heapshots (showing no increase in heap size) and monitored the memory throughout a period of time. The reasons I believe it's internal buffers are three:

1) `process.memoryUsage()` shows the same heapTotal while the rss keeps on rising. I checked if d.js used TypedArrays (eg: Uint16Array) and it seemed like it does.

2) I was able to create a small snippet of code replicating that behavior. (provided below).

3) While running that snippet I waited for a lot of garbage collections and left it running even for a day but it did not decrease the rss.

Running the code below produced a leak in the rss of about 50mb for ~2k images.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();
client.login(TOKEN).catch(console.error);

// Any kind of buffer. I used canvas.toBuffer() after creating a test image.
// Size probably matters but in my case I used one around 100kb.
// Run only once on startup eg: after the ready event or triggered by a specific message.
 testfunction(buffer);

function testfunction(buffer)
{
	client.guilds.cache.get(GUILD_ID).channels.cache.get(CHANNEL_ID)
	.send({files: [new Discord.MessageAttachment(buffer, 'test.png')]})
        .then(() => testfunction(buffer))
	.catch(console.error);
}
```

**Further details:**

- discord.js version: v12.2.0(LTS)
- Node.js version: v12.16.3 (LTS)
- Operating system: Should not matter /  Windows (replicated) / CentOS 7,8 (replicated) 
- Priority this issue should have – please be realistic and elaborate if possible: Medium
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Jade3375** [comment]
so like does this happen when images are being sent or something?

**Comment by LeManock** [comment]
I have same problem. Your bot is crashing?
