### ISSUE TITLE
channel.fetchMessages()?

### ISSUE THREAD

**Issue by GingkathFox** [discordjs/discord.js#4323]
**Is your feature request related to a problem? Please describe.**
I would like my bot to be able to fetch messages in a specific channel, for things like reaction roles, confirmation messages, and the like. Partials are out of the question because the massive overhaul required would (imho) not be worth it for something like that.
**Describe the ideal solution**
I saw on some stackoverflow posts that there used to be a `channel.fetchMessages` function to get all the messages in a channel? I dont know anything about it except for what it does.

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by GingkathFox** [comment]
this is a feature request, im requesting that `channel.fetchMessages` be added back to the API.

**Comment by qwright10** [comment]
Is there any reason why? TextChannel#messages#fetch still exists

**Comment by GingkathFox** [comment]
🤔 now why the hell did i think that was something else

**Comment by NotSugden** [comment]
>  now why the hell did i think that was something else

possibly because you did not read the docs thoroughly?

**Comment by qwright10** [comment]
@NotSugden I also believe the switch to managers was very well documented

**Comment by GingkathFox** [comment]
> > now why the hell did i think that was something else
> 
> possibly because you did not read the docs thoroughly?

possibly so, and also possibly cause im a idiot xD
