### ISSUE TITLE
Server Video for bots

### ISSUE THREAD

**Issue by Will3126** [discordjs/discord.js#4326]
**Is your feature request related to a problem? Please describe.**: My feature request is not related to a problem.
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**
A clear and concise description of what you want to happen.: It would be cool if bots could server video what they are playing (music, videos)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.: None

**Additional context**

**Comment by iCrawl** [comment]
https://github.com/discordjs/discord.js/issues/4325#issuecomment-636347176
