### ISSUE TITLE
Add "Go Live" options to Discord API + Discord js

### ISSUE THREAD

**Issue by avivgood** [discordjs/discord.js#4328]
I would like to suggest adding the "Go Live" this feature. It is widely requested among many devs (I have seen many ask for it in different forums)  and there is no reason for bots not to be able to share their screen while normal users can.

**Comment by RDambrosio016** [comment]
Go ask discord, there is nothing discord.js can do if it is not possible through the public API.

**Comment by NotMoni** [comment]
Facts Broooo.

**Comment by iCrawl** [comment]
> and there is no reason for bots not to be able to share their screen while normal users can.

This is not our concern. We have no control over this.
