### ISSUE TITLE
channel.edit() does not always resolve or reject.

### ISSUE THREAD

**Issue by patrix87** [discordjs/discord.js#4330]
**Please describe the problem you are having in as much detail as possible:**

When using channel.edit() or channel.setname() after 3 to 5 changes to the same channel at a rate of less than 1 per minute. The function will not resolve or reject, it will remain pending indefinitely.

Also, the client does not receive a rateLimit event even though this is probably the reason why the promise is dropped.

**Include a reproducible code sample here, if possible:**

```js
const testFunction = async (channel) => {
	const names = ["testName1", "testName2", "testName3", "testName4", "testName3"]
	for (const name of names) {
		try {
			console.log(`Old Name: ${channel.name}`)
			console.log(`New Name: ${name}`)
			const updatedChannel = await channel.setName(name, "Naming a channel for a test.")
			console.log(`Actual Updated Name: ${updatedChannel.name}`)
		} catch (e) {
			console.error("Error: Unable to rename a channel.", e)
		}
		await snooze(60000)
	}
}

client.on("rateLimit", (rateLimitInfo) => {
    console.error(`Client -> is being rate limited. Timeout: ${rateLimitInfo.timeout}ms | Limit: ${rateLimitInfo.limit} | Method: ${rateLimitInfo.method}
    Path: ${rateLimitInfo.path}`)
})

const snooze = (ms) => new Promise(resolve => setTimeout(resolve, ms))
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.3.0
- Operating system: Windows 10 (1909) x64
- Priority this issue should have – please be realistic and elaborate if possible: Fairly important as it could be hiding something bigger about promises being randomly drop when silently being rate limited.

- [ x ] I have also tested the issue on latest master, commit hash: b0b62d6

**Comment by anandre** [comment]
This is a duplicate of issue #4327 . Discord has changed the rate limits of editing channel names and topics.

**Comment by patrix87** [comment]
Yes it seems like it is the same issue. I understand that the "rateLimit" event is currently not being triggered. Do you know if the promise actually gets dropped or will it eventually resolve or reject. Or are you going to make changes so that it will reject if it is being rate limited ?  This will deeply influence how I will modify my code to work with the new limits.

**Comment by keybraker** [comment]
So they basically executed my bot that generates channels and would update channel names on presence change.

**Comment by keybraker** [comment]
So there is basically cannot be bypassed. We will have to work around it correct ?

**Comment by patrix87** [comment]
I've coded a workaround in about 30 minutes, it's not that bad, but you have to deal with the 2 name changes every 10 minutes *(just go with 1 every 5 minutes it's a lot simpler to code and it works better)

**Comment by keybraker** [comment]
I am going with newchannel on presence update, which ironically will put a higher strain on discords server, they very thing they want to prevent with this update.

**Comment by patrix87** [comment]
Just limit the name update to once every five minute by saving the Date.now() of the last change in an object exterior to the function and verifying that it's been 5 minutes before changing the name again. It's not that complicated and it will prevent your bot from being disconnected.

**Comment by keybraker** [comment]
My bots whole purpose was based around the fact that i could change it unlimited times, so I will either do the channel switch or limit the features of my bot.

**Comment by almostSouji** [comment]
Well, that's very sad to hear, however
1) you're not the only person that has to deal with this now
2) circumventing this limit by spamming another endpoint will over a short or long period only result in heavier limitations on that endpoint if all people go that route
3) in discord developer terms (which you agree to in order to have a bot on this platform) you agree to not try and circumvent API limitations (which you are essentially doing)

and lastly:
please do not discuss the matter of how you plan to do the above on our issue tracker any further. It serves the purpose to report and discuss issues with or feature requests for discord.js in alignment with what the API offers and what discord allows.
