### ISSUE TITLE
SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by kpetrone-accela** [discordjs/discord.js#4337]
**Please describe the problem you are having in as much detail as possible:**
This is a new issue for me, I've been using the same code for little over a year now. I get this error when I try to launch my app:

node_modules\discord.js\src\util\Util.js:584
      str = str.replace(/@([^<>@ ]*)/gmsu, (match, target) => {

But this has not been an issue in the past and as far as I know, I don't think any code changes I made caused this issue. I'm wondering if there is a version issue somewhere.
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
const Discord = require('discord.js');
//Logging into Discord
client.on('ready', () => {
    console.log(`Discord: Logged in as ${client.user.tag}!`);
});
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 8.9.4
- Operating system: Windows 10 (64 bit)
- Priority this issue should have – please be realistic and elaborate if possible:
Medium priority. The bot is still running as it is deployed now, but I am unable to continue any development work.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RDambrosio016** [comment]
djs v12 requires minimum node version 12, update node

**Comment by kpetrone-accela** [comment]
Ah, that did the trick. Thank you!
