### ISSUE TITLE
Add the self_video VoiceState property

### ISSUE THREAD

**Issue by jojoxd** [discordjs/discord.js#4340]
**Is your feature request related to a problem? Please describe.**
Hi, I noticed that discord.js is masking the response properties of the VoiceState API, and as such, I can't get to the undocumented `VoiceState.self_video` boolean.

**Describe the ideal solution**
Add a `selfVideo` boolean property to `VoiceState`, just like `selfStream`.

**Additional context**
discord.js 12.2.0
node 12.16.1

**Comment by uhKevinMC** [comment]
Your ideal solution would mean adding documentation to discord.js for an **undocumented**, probably non-existent, property in the [voice state object](https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure).

It's probably better to wait until it is PR'ed in the API docs repo to consider making a PR for this issue.

**Comment by jojoxd** [comment]
It falls under the Voice v5 API, I've already opened an issue, where I got referenced to this one:

https://github.com/discord/discord-api-docs/issues/1647

**Comment by jojoxd** [comment]
a PR has been merged concerning this property,

see https://github.com/discord/discord-api-docs/pull/1729

**Comment by uhKevinMC** [comment]
Seems like it is, ill make the PR.

**Comment by uhKevinMC** [comment]
Spoke too soon, seems like the property was already documented.

https://discord.js.org/#/docs/main/master/class/VoiceState?scrollTo=streaming

**Comment by geniusjam** [comment]
That's for streaming, self_video is different. https://github.com/discordjs/discord.js/blob/master/src/structures/VoiceState.js#L60

**Comment by uhKevinMC** [comment]
ah, i see, ill go add it once more
