### ISSUE TITLE
<message>.member property missing and <message>.webhookID: null

### ISSUE THREAD

**Issue by aya1337** [discordjs/discord.js#4344]
**Please describe the problem you are having in as much detail as possible:**
The bot is sometimes returning errors (like: cant read prop _roles of null) that are linked to main properties. It's a very weird behaviour since I make a condition for every single thing.
The thing is, `!message.webhookID && !message.member` returns **true** when this behaviour happens

**Include a reproducible code sample here, if possible:**

```js
client.on('message', async message => {
if(message.channel.type !== "test" || message.type !== "DEFAULT" || m.system) return;

	if(!message.webhookID && !message.member) { 
console.log("no member property and webhookID is null")
message.member = await message.guild.members.fetch(message.author.id)
	}
})
```
After "no member property and webhookID is null" is logged, the bot returns **DiscordAPIError: Unknown Member** due to the fetching line.

**Further details:**

- discord.js version: v12
- Node.js version: 12.18
- Operating system: Ubuntu 18
- Priority this issue should have – please be realistic and elaborate if possible:

- [X ] I have also tested the issue on latest master, commit hash: 1c275afd7cee4b3663a04f77b0271ac80e927a5e

NOTE: The bot is in 20k servers, I don't sweep any collection and this issue happens like 5 times an hour. (And if the same author keeps sending messages, the error persists meaning that the member is not being cached at all)

**Comment by SpaceEEC** [comment]
What kind of user (`message.author`) are we talking about here?
Did you confirm that this is actually a regular user and not any other user-like entity? (Webhook, or who knows, maybe a system user)

- Can you verify that the id (`message.author.id`) is actually correct? (Use another bot's `user` command or make a manual request to `GET /users/:id`)
- Can you verify that `message.author.id === message.client.users.cache.findKey(user => user === message.author)` evaluates to `true`?
- If the above evaluates to `false`, is the obtained key in the `GuildMemberManager`'s cache?
`message.guild.members.cache.has(message.client.users.cache.findKey(user => user === message.author))`

---

Probably just a typo in the template here (quite terrible for a "reproducible code sample"):
> `message.channel.type !== "test"`

This should have been `"text"`.

**Comment by aya1337** [comment]
@SpaceEEC It is a regular user and not something else (the code above actually checks for that)

1) The user is correct and requesting does return the user
2) It returns false 
3) It returns false

Yes, it was a typo when making the issue

**Comment by SpaceEEC** [comment]
This means that you overwrote the id of the user somewhere.
Check all instances of the  `=` operator (as well as all `Object.assign`s if you use it) for potential offenders.

---

If you did not already, I suggest enabling the [`no-cond-assign`](https://eslint.org/docs/rules/no-cond-assign) rule as that is usually the reason for these issues.

**Comment by aya1337** [comment]
Im not overwriting anything though. There is no mistake with the operators anywhere. And the issue happens intermittently and randomly.
