### ISSUE TITLE
createReactionCollector error

### ISSUE THREAD

**Issue by Tazi0** [discordjs/discord.js#4347]
**Please describe the problem you are having in as much detail as possible:**
When i try to create a reaction collector it doesn't collect any reactions

**Include a reproducible code sample here, if possible:**

```js
const filter = (reaction, user) => {
	return !user.bot && user.id === message.author.id
}
const collector = message.createReactionCollector(filter, { time: 15000 })
collector.on('collect' r => {
        console.log(r)
})
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.17.0
- Operating system: Windows 10
- Priority this issue should have: normal?

**Comment by SpaceEEC** [comment]
> Include a reproducible code sample here, if possible:

The code there is not syntactically valid, it's not going to reproduce this behaviour.
After adding the missing comma, it was logging the collected reactions just fine.

---

You might want to update your code sample with something you verified to **independently** reproduce this behavior.
