### ISSUE TITLE
messageUpdate event missing informations

### ISSUE THREAD

**Issue by Zargith** [discordjs/discord.js#4351]
**Please describe the problem you are having in as much detail as possible:**
I'm wanting to catch when someone edit his message and check if the content of the message contain some words but I don't care if the message is from a bot. for that I did the following code

```js
bot.on("messageUpdate", (oldMessage, message) => {
	try {
		// if the author of the message is a bot, we don't need to treat it
		if (message.author.bot)
			return;

		// check if in the content of the message updated there is some banned words that are defined into the config file
		// if yes, it report them to an embed message into the report log channel (if defined)
		checkBannedWords(message, true);
	} catch (exception) {
		sendError(message, exception, bot);
	}
});
```

But i got an error that says the author doesn't exist. I tried with the old and the nex message but I got the same problem.

Theses object messages be like:
```
Message {
  channel: TextChannel {
    type: 'text',
    deleted: false,
    id: 'xxx',
    name: 'test',
    rawPosition: 2,
    parentID: 'xxx',
    permissionOverwrites: Collection [Map] {},
    topic: '',
    nsfw: undefined,
    lastMessageID: 'xxx',
    rateLimitPerUser: 0,
    lastPinTimestamp: xxx,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: 'xxx',
      shardID: 0,
      name: 'xxx',
      icon: 'xxx',
      splash: null,
      region: 'eu-west',
      memberCount: 12,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: 'xxx',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'MEDIUM',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: xxx,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: 'xxx',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  deleted: false,
  id: 'xxx',
  type: undefined,
  content: 'update message test',
  author: null,
  pinned: false,
  tts: false,
  nonce: undefined,
  system: true,
  embeds: [],
  attachments: Collection [Map] {},
  createdTimestamp: NaN,
  editedTimestamp: xxx,
  reactions: ReactionManager {
    cacheType: [Function: Collection],
    cache: Collection [Map] {},
    message: [Circular]
  },
  mentions: MessageMentions {
    everyone: false,
    users: Collection [Map] {},
    roles: Collection [Map] {},
    _members: null,
    _channels: null,
    crosspostedChannels: Collection [Map] {}
  },
  webhookID: null,
  application: null,
  activity: null,
  _edits: [
    Message {
      channel: [TextChannel],
      deleted: false,
      id: 'xxx',
      type: undefined,
      content: undefined,
      author: null,
      pinned: undefined,
      tts: undefined,
      nonce: undefined,
      system: true,
      embeds: [],
      attachments: Collection [Map] {},
      createdTimestamp: NaN,
      editedTimestamp: null,
      reactions: [ReactionManager],
      mentions: [MessageMentions],
      webhookID: null,
      application: null,
      activity: null,
      _edits: [Circular],
      flags: [MessageFlags],
      reference: null
    }
  ],
  flags: MessageFlags { bitfield: 0 },
  reference: null
}
```

As you can see, some value are missing... (exept those with value xxx that i've replaced)

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.16.2
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
> But i got an error that says the author doesn't exist.

Since you mention it I assume it's relevant: Can you actually include said error and stacktrace here too, please?

> As you can see, some value are missing...

I don't see any on first glance, care to elaborate about what values exactly are missing here?
Note that some properties might not be enumerable, these include, but are not limited to getters.

**Comment by Zargith** [comment]
> Since you mention it I assume it's relevant: Can you actually include said error and stacktrace here too, please?

```
console.log(`ERREUR\nL\'utilisateur ${message.author.username}${(!message.channel.guild ? "" : `, sur le serveur ${message.channel.guild.name}`)} a envoyé la commande :\n${message.content}\n\nL\'erreur suivante s\'est produite :\n${exception.stack}`);
                                                             ^

TypeError: Cannot read property 'username' of null
    at consoleErrorMessage (path/to/my/project/sendError.js:11:55)
    at module.exports (path/to/my/project/sendError.js:4:2)
    at Client.<anonymous> (path/to/my/project/Bot.js:168:3)
    at Client.emit (events.js:310:20)
    at Object.module.exports [as MESSAGE_UPDATE] (path/to/my/project/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_UPDATE.js:14:12)
    at WebSocketManager.handlePacket (path/to/my/project/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (path/to/my/project/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (path/to/my/project/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (path/to/my/project/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:310:20)
```

> I don't see any on first glance, care to elaborate about what values exactly are missing here?
Note that some properties might not be enumerable, these include, but are not limited to getters.

Missing values here are:
- author (with value null);
- nonce (with value undefined);
- createdTimestamp (with value NaN);

But I think the most important value is the author but its value is not in the old message either ...

**Comment by zmontgo** [comment]
I find the same issue.
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of undefined
message.channel.id and message.channel.send don't work. Those are the only ones I've tested.

**Comment by Monbrey** [comment]
> I find the same issue.
> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of undefined
> message.channel.id and message.channel.send don't work. Those are the only ones I've tested.

Your issue is not the same. `undefined` suggests that your `message` object is not an instance of Discord.Message.

Most likely this is because your event parameters are wrong, eg binding client to the function, but not receiving it.

**Comment by SpaceEEC** [comment]
This looks like you enabled the partial type `'MESSAGE'`, since Discord may send you incomplete message updates (e.g. only fields that actually updated), updated messages may still be partial.

You probably want to guard yourself with something like this:
```js
if (message.partial) {
  await message.fetch();
}
```

---

If you do not have partials enabled, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to investigate further.

**Comment by GoldenretriverYT** [comment]
> This looks like you enabled the partial type `'MESSAGE'`, since Discord may send you incomplete message updates (e.g. only fields that actually updated), updated messages may still be partial.
> 
> You probably want to guard yourself with something like this:
> 
> ```js
> if (message.partial) {
>   await message.fetch();
> }
> ```
> 
> If you do not have partials enabled, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to investigate further.

I have the same problem, but when I try to fetch the old message it always returns the content of the new message, so I am completely unable to log message edits because I have partial messages enabled

**Comment by almostSouji** [comment]
Discord just provides the new, updated content with message update events. We provide the old content from a frozen earlier instance from the cache, before we update the cache accordingly. If you fetch you will of course receive the updated message. Discord has already updated it on their end and the previous content is lost. (The message history we provide is also solely based on cache, discord does not expose previous content or changes through their rest API)
