### ISSUE TITLE
idk why but my server is not alowing me to download the discord.js file

### ISSUE THREAD

**Issue by Taylortomlinson07** [discordjs/discord.js#4354]
![image](https://user-images.githubusercontent.com/66884662/84577262-d80b5400-ad88-11ea-8035-ccf20babcc38.png)
 my server is not alowing me to  install discord.js it has alot of errors and im confused as to why

**Comment by Shane4368** [comment]
Why do you have a space in discord.js?

**Comment by iCrawl** [comment]
`npm install discord.js` not `discord .js`

**Comment by Taylortomlinson07** [comment]
ummm
