### ISSUE TITLE
Client.guilds.array doesn't work

### ISSUE THREAD

**Issue by ScorpionTeam1** [discordjs/discord.js#4361]
Hello, I trying to lunch my bot and i have this error:

Error:

TypeError: Cannot read property 'array' of undefined
    at Timeout.setActivity [as _onTimeout] (c:\Users\Acer\Desktop\discord-bot\index.js:14:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

Code : 

bot.on('ready', async () => {
    bot.user.setStatus('dnd')
    function setActivity()  { 
    var servers = bot.guilds.array().map(g => g.name).join(',');
   var Gameinfo = [`FunDeads | By SCORPION-Brian `,'FunDeads | f!help',`FunDeads | ${bot.guilds.size}  servers`,`FunDeads | ${bot.users.size} Utilisateurs`,`FunDeads | Version Final `]
   var info = Gameinfo[Math.floor(Math.random() * Gameinfo.length)]
   bot.user.setPresence({ game: { name: (info), type: "streaming", url: "https://www.twitch.tv/bot"}});
            
    }
setInterval(setActivity, 3000 * 30 * 0.30)
});

**Comment by NotSugden** [comment]
you should ask this in the [Discord Server](https://discord.gg/bRCvFy9), your question is more suited there

**Comment by ScorpionTeam1** [comment]
ok merci !
