### ISSUE TITLE
Connection Speaking event sometimes emits Undefined user 

### ISSUE THREAD

**Issue by henrymxu** [discordjs/discord.js#4364]
**Please describe the problem you are having in as much detail as possible:**

Sometimes user parameter for a specific user is undefined when attempting to receive speaking events.  This happens infrequently (5-10% of the time) and when it happens, the user will remain undefined until the user leaves the channel and rejoins. 

DiscordJS is able to continually determine that that the user is speaking, but is unable to provide a defined user object.

**Include a reproducible code sample here, if possible:**

```js
connection.on('speaking', (user, speaking) => {
            if (user === undefined) {
                console.log('User is undefined')
                return
            }
})
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version:12.16.3
- Operating system: MacOS, Linux
- Priority this issue should have – please be realistic and elaborate if possible:

Low priority, feature works most times, but few times it doesn't causes inconsistency in bot performance.

**Comment by tyliec** [comment]
Having the same issue.

**Comment by tyliec** [comment]
Seems to be related to moving people/the bot in and out of voice channels.

**Comment by tyliec** [comment]
Seems like the no user_id is being set or received by the websocket on people opening or closing their connections.
