### ISSUE TITLE
cacheType change or implementation.

### ISSUE THREAD

**Issue by rubybb** [discordjs/discord.js#4365]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

https://github.com/discordjs/discord.js/blob/1c275afd7cee4b3663a04f77b0271ac80e927a5e/src/managers/BaseManager.js#L11
cacheType = Collection

I don't see an easy way for changing the implementation used for Collections, as I'd like to implement my own way, this is a problem, and after asking on the Discord, I didn't find any existing methods or solutions aside from just directly overriding the methods.

**Describe the ideal solution**

Perhaps some form of way to declare the reference to a file or something, like in the options, that extends BaseCollection.
https://github.com/discordjs/discord.js/blob/1c275afd7cee4b3663a04f77b0271ac80e927a5e/src/util/Collection.js#L6

**Describe alternatives you've considered**

I've taken a look at directly forking Discord.js, but that'd be quickly unmaintainable, I've tried just going like `client.users.cache.set = () => {}` for example, but that's not friendly.

**Additional context**

**Comment by RDambrosio016** [comment]
when implementing managers i specifically looked for an interface which easily allowed for dependency injection down the line, and its the whole reason why:

 these arguments to basemanager are included
```js
cacheType = Collection, ...cacheOptions
```

this is not hardcoded as collection
```js
this.cache = new cacheType(...cacheOptions);
``` 

this is a thing
```js
this.cacheType = cacheType;
```

However, with that being said, v12 was released before any thought of implementation for custom cache was done. The implementation should be relatively simple, just do something similar to structures.extend, managers grab the class which should be used, and feed that, plus additional optional arguments to BaseManager. However there were disagreements, some maintainers feel structures is already bad enough, and this would be even worse of an interface.

it could *probably* be done in a way that is not breaking, but i personally feel this is more of a v13 thing, and this will benefit a lot from typescript.

**Comment by rubybb** [comment]
I don't think changing the cacheType will reliably work, because instances of it are created before I'm able to change the cacheType, but I'll need to take a further look.

And something like this would be lovely in v13.
