### ISSUE TITLE
[Repl.it] Voice connection not established within 15 seconds

### ISSUE THREAD

**Issue by North-West-Wind** [discordjs/discord.js#4369]
**Please describe the problem you are having in as much detail as possible:**
Recently, I switched the host of my bot from glitch.com to repl.it. Before changing the host, my bot can join a voice channel with no problem. However, when I started hosting on repl.it, things just go wrong on their way. I'm quite sure it is the problem of repl.it because I've tested it locally but I want to know how can I fix this issue?

**Include a reproducible code sample here, if possible:**

```js
client.on("message", message => {
  var args = message.content.split(" ");
  switch(args[0]) {
    case "?play":
      const voiceChannel = message.member.voice.channel;
      var connection = await voiceChannel.join();
    break;
});
//yup thats all
//also you may not be able to reproduce this as I think it is an issue of repl.it. I'm just looking for workarounds.
```

**Further details:**

- discord.js version: master
- Node.js version: 12.16.1
- Operating system: Repl.it
- Priority this issue should have – please be realistic and elaborate if possible:
Medium. By creating some try catch blocks I can handle the error without crashing the bot, but the thing is still annoying and it makes all my music commands unusable.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by aabbccsmith** [comment]
This may be repl.it blocking these inbound/outbound packets on purpose. If you are looking for free hosting I'd recommend AWS EC2 free tier (not an ad). If you've tested local & on glitch then you can infer that the issue is to do with repl.it and not something with d.js.

Although, on that note, maybe d.js should be more verbose about this letting us know if it can't do something. Thoughts?

**Comment by North-West-Wind** [comment]
I know it is not a problem of d.js, but the repl.it community is just too small and inactive so I came here to ask.

Anyway, thanks for the suggestion of another free hosting service. I'm closing it now.
