### ISSUE TITLE
Role management is extremely broken

### ISSUE THREAD

**Issue by GDColon** [discordjs/discord.js#4374]
**Please describe the problem you are having in as much detail as possible:**
Using roles.add and roles.remove in succession can lead to extremely strange and unintended results

**Include a reproducible code sample here, if possible:**

```js
let oldRoles = ['12345678']  // Use a role ID that you currently have
let newRoles = []
message.member.roles.remove(oldRoles, "roles.remove").catch(() => {})
message.member.roles.add(newRoles, "roles.add").catch(() => {})
// Audit log shows the role being removed, then being readded with the reason "roles.add"
```

**Further details:**

- discord.js version: v12.2.0
- Node.js version: v12.6.1
- Operating system: Windows 10
- Priority this issue should have – Medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
Given that you're
- not handing Promises to ensure that these execute in order
- ignoring that `roles.set` exists to avoid needing to make multiple API calls at all to achieve this
- silently dismissing errors instead of logging them

I find it pretty difficult to consider this a bug

**Comment by GDColon** [comment]
I avoid using `roles.set` because as soon as the bot lacks permission to manage a role, the whole array gets thrown out the window. This makes it painstakingly difficulty to work with. Promises would also require adding the rest of the code to both .then() and .catch(). Either way, I suppose I'll work with it if it gets around this weird bug.

**Comment by Monbrey** [comment]
I suggest using async/await for resolving Promises, it will avoid the nested callback issue you refer to.

**Comment by GDColon** [comment]
I decided to make a function that runs .set but filters out the non-manageable roles. Either way, I'll be sure to keep your comments in mind. Thank you!
