### ISSUE TITLE
Wrong return type for event handler

### ISSUE THREAD

**Issue by Igorgro** [discordjs/discord.js#4376]
**Please describe the problem you are having in as much detail as possible:**
When I use discord.js with TypeScript, I can not use async function as `Client` event handler because it it is required that function returns void. I think it can be fixed by replacing `void` with `void|Promise` in `index.d.ts`
**Include a reproducible code sample here, if possible:**

```js
const bot = new Client();
bot.on('message', async (msg) => {
    await msg.channel.send('test');
});
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18
- Operating system: Any OS
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by didinele** [comment]
One sec, going to PR a fix for most of the listeners.

**Comment by Papaia** [comment]
I'm having trouble to reproduce this, could you show your tsconfig and the full snippet?

**Comment by Igorgro** [comment]
![Screenshot_20200623_134659](https://user-images.githubusercontent.com/22894169/85395320-9af94b80-b558-11ea-920c-1fb3c1f5921d.png)
As you can see the return value of async function (which is a Promise) doesn't correspond with wxpected return value (declared in index.d.ts)

**Comment by iCrawl** [comment]
Rewriting all our typings for an eslint rule is a bit much I think.

```json
{
  "@typescript-eslint/no-misused-promises": [
    "error",
    {
      "checksVoidReturn": false
    }
  ]
}
```

This should work fine.

**Comment by puf17640** [comment]
> Rewriting all our typings for an eslint rule is a bit much I think.
> 
> ```json
> {
>   "@typescript-eslint/no-misused-promises": [
>     "error",
>     {
>       "checksVoidReturn": false
>     }
>   ]
> }
> ```
> 
> This should work fine.
> 
> https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

I totally agree. 👍
