### ISSUE TITLE
[TypeError]: AbortController is not a constructor when bundling code

### ISSUE THREAD

**Issue by TylerEisenhauer** [discordjs/discord.js#4596]
**Please describe the problem you are having in as much detail as possible:**

When running a bundled version of a discord.js project client login fails because of an error thrown in the APIRequest class when instantiating an AbortController

```
HTTPError [TypeError]: AbortController is not a constructor
    at RequestHandler.execute (/mnt/c/Source/AbortControllerError/build/index.js:23440:21)
    at RequestHandler.push (/mnt/c/Source/AbortControllerError/build/index.js:23374:19)
    at /mnt/c/Source/AbortControllerError/build/index.js:21987:10
    at new Promise (<anonymous>)
    at RESTManager.push (/mnt/c/Source/AbortControllerError/build/index.js:21985:12)
    at RESTManager.request (/mnt/c/Source/AbortControllerError/build/index.js:22006:17)
    at Proxy.<anonymous> (/mnt/c/Source/AbortControllerError/build/index.js:23303:19)
    at WebSocketManager.connect (/mnt/c/Source/AbortControllerError/build/index.js:28778:43)
    at Client.login (/mnt/c/Source/AbortControllerError/build/index.js:23741:21) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
```

**Include a reproducible code sample here, if possible:**

I created a small project with webpack already configured, and scripts defined to run it, that reproduces the issue, this was functioning properly before version 12
https://github.com/TylerEisenhauer/AbortControllerError

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.1
- Operating system: Ubuntu 18.04 (Running as a subsystem in Windows 10)

**Comment by vladfrangu** [comment]
Bundled versions are meant for browsers only; I'm fairly certain that makes it use the global AbortController in browsers, something that is lacking on a nodejs environment

**Comment by TylerEisenhauer** [comment]
From what I can tell from digging through the bundle it appears to be including and referencing the dependency correctly

```js
const AbortController = __webpack_require__(425);
```

Then further down in the file

```js
/* 425 */
/***/ (function(__webpack_module__, __webpack_exports__, __webpack_require__) {

"use strict";
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, "AbortController", function() { return /* binding */ AbortController; });
__webpack_require__.d(__webpack_exports__, "AbortSignal", function() { return /* binding */ abort_controller_AbortSignal; });
```

Which references this implementation of AbortController also found in the bundle

```js
class AbortController {
    /**
     * Initialize this controller.
     */
    constructor() {
        signals.set(this, createAbortSignal());
    }
    /**
     * Returns the `AbortSignal` object associated with this object.
     */
    get signal() {
        return getSignal(this);
    }
    /**
     * Abort and signal to any observers that the associated activity is to be aborted.
     */
    abort() {
        abortSignal(getSignal(this));
    }
}
```

So it doesn't seem to me that it would be trying to make use of the browser implementation

**Comment by tabarra** [comment]
Any solution?  
I'm required to webpack my node package.

**Comment by TylerEisenhauer** [comment]
> Any solution?
> I'm required to webpack my node package.

I've yet to find any kind of workaround, though I found this issue that has hung open since March with no response on the abort-controller repo https://github.com/mysticatea/abort-controller/issues/20

**Comment by EvanDarwin** [comment]
> @vladfrangu Bundled versions are meant for browsers only; I'm fairly certain that makes it use the global AbortController in browsers, something that is lacking on a nodejs environment

This is an incorrect assumption. Webpack is one of the most popular transpilers, used in a variety of situations. Just because it is packed with webpack does not mean that it's running outside of a node.js environment?

**Comment by devsnek** [comment]
If you're bundling your Node.js code you're doing it wrong

**Comment by TylerEisenhauer** [comment]
@devsnek Care to elaborate on why? If it is widely accepted as bad practice and this issue will not be investigated so be it, but webpack includes a setting to target node https://webpack.js.org/configuration/target/ and its much nicer to deploy a single file that includes all dependencies with a size of about 3MB to my server instead of an entire folder structure of around 150MB

**Comment by tabarra** [comment]
> If you're bundling your Node.js code you're doing it wrong

@devsnek Not everyone is a level 10 code wizard that have the luxury of choosing the architecture of the _environment_ our codes run on.  
Please try to be more considerate instead of "hurr durr you doing it wrong".

**Comment by devsnek** [comment]
You shouldn't deploy dependencies with your source code, you should just send your source code and then use `npm ci` or similar.

**Comment by tabarra** [comment]
You are very good at repeating yourself.  
Congratulations, now read my message.

**Comment by EvanDarwin** [comment]
@devsnek How are your "best practices" related to the issue topic? 

There is a clear issue with the use case of Webpack + Discord.js, but your suggestion is that the use case is supposedly _wrong_ (in your opinion). That does not stop it from existing, where it clearly already does for some people.

I'd rather focus on finding a quick solution instead of starting a war in the GitHub comments.

**Comment by devsnek** [comment]
I'd rather focus on finding a correct solution, which seems to me to be "stop bundling discord dot js browser edition into your deployments"

**Comment by EvanDarwin** [comment]
> You are very good at repeating yourself.
> Congratulations, now read my message.

**Comment by tabarra** [comment]
> I'd rather focus on finding a correct solution, which seems to me to be "stop bundling discord dot js browser edition into your deployments"

I absolutely would as well!    
And I did, for very long time.  
But **unfortunately** is just not possible when you have to make it run it instantly, without previous setup and in an environment that doesn't even have npm or yarn.  
  
... it is just not possible.
Not every project is a cute CI/CD deployable thing, or something that you could just add to the docs "please run npm i before".

**Comment by iCrawl** [comment]
We have a webpacked version of Discord.js on the webpack branch of this repo constantly updated.

It seems to work fine in browsers. I don't exactly know what we should do to "fix" this, as AbortController is an established API in the browser, but for non-browser environments its listed as a dependency.

Maybe look into a different webpack configuration for your use-case, if running a webpacked version on node is at all necessary.

This doesn't look like something thats our fault or something we can just "fix".
