### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]:

### ISSUE THREAD

**Issue by MX199** [discordjs/discord.js#4597]
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent { target: WebSocket { _events: [Object: null prototype] { message: [Function], open: [Function], error: [Function], close: [Function] }, _eventsCount: 4, _maxListeners: undefined, readyState: 2, protocol: '', _binaryType: 'nodebuffer', _finalize: [Function: bound finalize], _closeFrameReceived: false, _closeFrameSent: false, _closeMessage: '', _closeTimer: null, _finalized: true, _closeCode: 1006, _extensions: {}, _isServer: false, _receiver: Receiver { _binaryType: 'nodebuffer', _extensions: null, _maxPayload: 0, _bufferedBytes: 0, _buffers: null, _compressed: false, _payloadLength: 438, _fragmented: 0, _masked: false, _fin: true, _mask: null, _opcode: 1, _totalPayloadLength: 0, _messageLength: 0, _fragments: null, _cleanupCallback: null, _isCleaningUp: false, _hadError: false, _loop: false, add: [Function: bound add], onmessage: null, onclose: null, onerror: null, onping: null, onpong: null, _state: 0 }, _sender: Sender { _extensions: {}, _socket: [TLSSocket], _firstFragment: true, _compress: false, _bufferedBytes: 0, _deflating: false, _queue: [] }, _socket: TLSSocket { _tlsOptions: [Object], _secureEstablished: true, _securePending: false, _newSessionPending: false, _controlReleased: true, _SNICallback: null, servername: 'gateway.discord.gg', alpnProtocol: false, authorized: true, authorizationError: null, encrypted: true, _events: [Object], _eventsCount: 5, connecting: false, _hadError: false, _handle: null, _parent: null, _host: 'gateway.discord.gg', _readableState: [ReadableState], readable: false, _maxListeners: undefined, _writableState: [WritableState], writable: false, allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: undefined, _server: null, ssl: null, _requestCert: true, _rejectUnauthorized: true, parser: null, _httpMessage: null, timeout: 0, [Symbol(res)]: [TLSWrap], [Symbol(asyncId)]: 28, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBytesRead)]: 97096296, [Symbol(kBytesWritten)]: 3421, [Symbol(connect-options)]: [Object] }, _error: null, url: 'wss://gateway.discord.gg/?v=6&encoding=json', _req: null }, type: 'error', message: 'read ECONNRESET', error: { Error: read ECONNRESET at TLSWrap.onStreamRead (internal/stream_base_commons.js:162:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }) at Client.emit (events.js:186:17) at WebSocketConnection.onError (C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17) at WebSocket.onError (C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot\node_modules\ws\lib\event-target.js:128:16) at WebSocket.emit (events.js:197:13) at _receiver.cleanup (C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot\node_modules\ws\lib\websocket.js:211:14) at Receiver.cleanup (C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot\node_modules\ws\lib\receiver.js:557:13) at WebSocket.finalize (C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot\node_modules\ws\lib\websocket.js:206:20) at TLSSocket.emit (events.js:197:13) at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) at processTicksAndRejections (internal/process/next_tick.js:76:17) C:\Users\GAMER\Desktop\web for Run Script\discord run script\BOT\Arabic play bot>pause Press any key to continue . . .

**Comment by Monbrey** [comment]
Firstly, the issue template exists for reason, please don't ignore it.

Second, this is nothing more than a connection issue, not a discord.js bug.
