### ISSUE TITLE
Sending a DM to a user throws an exception even if the message is sent successfully.

### ISSUE THREAD

**Issue by fbarda** [discordjs/discord.js#4606]
**Please describe the problem you are having in as much detail as possible:**
I was testing DM functionality of the bot, and I tried to send myself a message via the "message" event.
The message sent to me without any problem on Discord end; however, it tries to send the same message for a second time and discord.js throws an error.
**Include a reproducible code sample here, if possible:**

```js
var token= "<your bot token>", Discord = require("discord.js");
var discordClient= new Discord.Client();
discordClient.on("message", message => {
    message.author.createDM()
        .then(dm=>dm.send("Hey!")
}).login(token);

//Assume someone sent an message.
//UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send messages to this user
//  at RequestHandler.execute (<app folder>\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
//  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v14.4.0
- Operating system: Windows 10 x64 Build: 1909 (Education version)
- Priority this issue should have – please be realistic and elaborate if possible: Low
*but it's annoying to see.*

- [ ] I have also tested the issue on latest master, commit hash:
---
**Currently testing it on the latest commit, will update if it's fixed on a later commit or not.**

**Comment by Papaia** [comment]
The bot tries to send a message to itself in a DM, and it can't.

Why?:
 - You send a message
 - Message event is triggered (author: you, channel: in server)
 - Bot sends you a message
 - Message event is triggered (author: bot, channel: dm with you)
 - Bot tries to send a message to a DM with itself, which is not possible.

**Comment by fbarda** [comment]
Hold up, I forgot to ignore the message if the bot sent the message 🤦

**Comment by fbarda** [comment]
Yep that's the case.
