### ISSUE TITLE
voiceStateUpdate trigger several times when joining a channel on web

### ISSUE THREAD

**Issue by Beancake12** [discordjs/discord.js#4607]
When joining a channel from the app, the voiceStateUpdate event triggers once, but when usering web app it triggers 3 times when joining channel

```js
client.on('voiceStateUpdate', (oldState, newState) => {
    console.log('test')
}
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.2
- Operating system: Windows 10
 - Browser: Firefox 77.0.1 64-bit

**Comment by almostSouji** [comment]
I can not reproduce this behavior

discord.js: 12.2.0
firefox: 78.0.1 (64-bit)

**Comment by Beancake12** [comment]
Thank you for your fast response.

I've tested again. On my own computer I still get 3 triggers, but when I join from another pc there is no problem...

I'll test from another computer in the future then.

**Comment by almostSouji** [comment]
If you can reliably reproduce this from a certain machine, please log the corresponding event values, from both the websocket as well as the client event and provide the full console output.

<details>
<summary>minimal bot for logging</summary>

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log('I am ready!');
});

client.on('voiceStateUpdate', (oldMember, newMember) => {
	console.log("-- voiceStateUpdate:")
	console.log("MEMBER OLD: ", oldMember);
	console.log("MEMBER NEW: ", newMember);
	console.log("------------------")
})

client.ws.on('VOICE_STATE_UPDATE', data => {
	console.log("-- VOICE_STATE_UPDATE:")
	console.log("WS-DATA: ", data)
})

// Log our bot in using the token from https://discordapp.com/developers/applications/me
client.login('your token here');
```

based on our[ ping-pong example](https://discord.js.org/#/docs/main/stable/examples/ping)

</details>

**Comment by Beancake12** [comment]
I've tried to reproduce it now both with your code and with my old code, but with no luck.

Maybe I've not closed nodemon --inspect correctly, and it had stacked several bots, if that's even a thing.

**Comment by BeaudeneVa** [comment]
I'm confident the event you are referring to triggers when a person begins to speak too.

**Comment by almostSouji** [comment]
I'm rather sure that that's not the case. [VOICE_STATE_UPDATE](https://discord.com/developers/docs/topics/gateway#voice-state-update) is a websocket event, which includes a [voice-state](https://discord.com/developers/docs/resources/voice#voice-state-object) payload, there is no information about speaking status in this.

<details>
<summary>voice-state object</summary>

```
guild_id? | snowflake | the guild id this voice state is for
channel_id | ?snowflake | the channel id this user is connected to
user_id | snowflake | the user id this voice state is for
member? | guild member object | the guild member this voice state is for
session_id | string | the session id for this voice state
deaf | boolean | whether this user is deafened by the server
mute | boolean | whether this user is muted by the server
self_deaf | boolean | whether this user is locally deafened
self_mute | boolean | whether this user is locally muted
self_stream? | boolean | whether this user is streaming using "Go Live"
suppress | boolean | whether this user is muted by the current user
```

</details>

Whereas [guildMemberSpeaking](https://github.com/discordjs/discord.js/blob/stable/src/client/voice/VoiceConnection.js#L513) is internally synthesized and emitted when received from [voice connection](https://discord.com/developers/docs/topics/voice-connections#establishing-a-voice-websocket-connection) payloads (op 5)

**Comment by DraeRamsey** [comment]
I'm experiencing a similar issue: whenever I update the voice state, the triggers increase by one each time. 

```
client.on('voiceStateUpdate', (oldState, newState) => {
    console.log('test')
}

```
The first time the event is triggered it logs 'test' once, the second time it logs twice, then three times,  and so on and so fourth.

**Comment by almostSouji** [comment]
That does not sound related to this issue at all. If the amount of logs increases with each execution it's highly likely that you attach the listener inside a scope that executes when something else happens (that regularly happens). For example, being nested in a `"message"` event listener would cause one attachment (and by extension execution) of the listener per message the bot has received.

**Comment by DraeRamsey** [comment]
Wow yup, this is what happens when I forget to drink my coffee. I am annoyed by my own question. 
¯\_(ツ)_/¯

**Comment by almostSouji** [comment]
If you have further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead. the repository serves as feature- and bug tracker
