### ISSUE TITLE
internally sharded bot loses connection to some shards and goes offline on some servers

### ISSUE THREAD

**Issue by unek** [discordjs/discord.js#4610]
**Please describe the problem you are having in as much detail as possible:**
the bot lost connection to discord. it uses internal sharding. looks like only some shards are stuck in either reconnecting or disconnected state. they are not reconnecting. shouldn't they automatically reconnect? if no, how do i force them to?
![image](https://user-images.githubusercontent.com/1358551/86532233-902fa680-bec8-11ea-8374-4394d4a7c681.png)

noting pops up in the debug log after the disconnection. did not log any debug information before.

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.16.2
- Operating system: ubuntu 18.04 lts
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by unek** [comment]
just restarted with full debug logs and looks like its a hell of 4009 shard disconnected happening over and over

**Comment by unek** [comment]
don't know how relevant this is and i hope this is not just my (DO's) bad connection but
![image](https://user-images.githubusercontent.com/1358551/86536343-0511d900-bee7-11ea-95d8-4e3bde4d73e0.png)
after this happens all the shards are destroyed with closecode 1000 a few times, then with closecode 4009.

**Comment by unek** [comment]
looks like it's just connectivity issues.

**Comment by pauldb09** [comment]
> looks like it's just connectivity issues on the machine causing all the shards to drop out.

I dont think, I have this issue vert frequently and my server is located in Frankfurt, and the discord datacenter too

**Comment by unek** [comment]
> > looks like it's just connectivity issues on the machine causing all the shards to drop out.
> 
> 
> 
> I dont think, I have this issue very frequently and my server is located in Frankfurt, and the discord datacenter too

could be your event loop getting so slowed down that it cannot send heartbeats in time. lots of synchronous operations happening behind the scenes.
