### ISSUE TITLE
Guild members are getting mixed up

### ISSUE THREAD

**Issue by TheBigerGamer** [discordjs/discord.js#4612]
**Please describe the problem you are having in as much detail as possible:**
Sometimes ```message.guild.members``` corrupt and mix up users.

**Include a reproducible code sample here, if possible:**

```js
console.log(message.guild.members.cache.get('user1 ID').id)
Log: different user ID
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 12.18.2
- Operating system: Raspbian GNU/Linux 10 (buster) (Also had this problem with Ubuntu 16.04)
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by NotSugden** [comment]
are you sure you aren't just doing something along the lines of
```js
if (message.member.id = "...") ...```
rather than
```js
if (message.member.id === "...") ...```
this is the only thing i can think of that would cause this

**Comment by TheBigerGamer** [comment]
I don't think so, but it only happens to certain users, and even if another user repeat the same process, they don't get mixed up.

**Comment by almostSouji** [comment]
With "mixing up" you mean that a GuildMember instance is stored in the member cache at `<Guild>.members.cache` under a key that's not its actual ID?

That should under no circumstance be possible. If you can still reproduce this please try to run an isolated bot instance with minimal code (but on the a equally potent token to get the same coverage) and see if the issue persists.

<details>
<summary>Suggested minimal reproducible code sample</summary>

if you say the key `const mem = members.get("id")` diverges from the members id `mem.id` the below sample reduces the guild cache by members where this is the case. Please also manually run the `!check` command after some time so the member caches had time to properly build up.

```js
/**
 * Get the amount of global cached members for which the key in the member collection diverges from the members id
 * @returns {number}
 */
function check() {
	return client.guilds.cache.reduce((a, guild) => {
		// required availability check, if unavailable count this guild as not affected (0)
		if (!guild.available) return a;
		// if available reduce member cache
		return a + guild.members.cache.reduce((acc, member, key) => {
			if (key !== member.id) return acc + 1;
			return acc;
		}, 0);
	}, 0);
}

client.on('ready', () => {
	console.log('I am ready!');
	console.log(check());
});

client.on('message', message => {
	// manually re-doing after cache is filled some more
	if (message.content === '!check') {
		console.log(check());
	}
});

// Log our bot in using the token from https://discordapp.com/developers/applications/me
client.login('token');
```

</details>

I can not reproduce the behavior you describe. If i understood the issue wrong please elaborate what precisely you mean by "mixed up". In regards to the code sample above: i always get `0` logged (inverting the condition as sanity check results in the expected amount of members).

discord.js: 12.2.0
node.js: v13.7.0

**Comment by almostSouji** [comment]
Forgot to mention: please also update to the latest stable version (12.2.0) we had multiple bug fixes since 12.1.1

**Comment by TheBigerGamer** [comment]
@almostSouji I ran the instance and some times and it gave me 7.

**Comment by almostSouji** [comment]
with __just__ that code? no additional functionality? and on v12.2.0?

**Comment by TheBigerGamer** [comment]
With just that code, I haven't tested yet, but in the main bot it gave me 7.

**Comment by almostSouji** [comment]
Please do. As said this should not be possible, please run it in an isolated bot setup (see proposed code) without any other functionality. If you can not reproduce it with that there is some part of your other code messing up, meaning it's not a issue with the library. If you can we will have to look into what might be causing this.

The behavior of your full bot does not fulfill the "minimal" criteria needed for this to be verified as a library bug, since no one but you can reproduce this for now.

**Comment by TheBigerGamer** [comment]
Alright. I'll start the test now.

**Comment by TheBigerGamer** [comment]
I think I found the error. I found this line while reviewing my code for the 3rd time: ```const filter = m => {return m.author.id = msg.author.id;}```.

Sorry for the inconvenience I may have caused you.

May I close this issue in 24h just to check if that was the problem?

**Comment by almostSouji** [comment]
To prevent this going forward i suggest using eslint with the rule [`no-return-assign`](<https://eslint.org/docs/rules/no-return-assign#top>) and similarly [`no-cond-assign`](https://eslint.org/docs/rules/no-cond-assign#top)
We explain the basic setup of a linter for multiple editors on [this guide page](https://discordjs.guide/preparations/setting-up-a-linter.html) as well

**Comment by TheBigerGamer** [comment]
Seems like that line was the problem. Thank you all for helping me.

I'm closing this issue now.
