### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by yuto0214w** [discordjs/discord.js#4613]
**Please describe the problem you are having in as much detail as possible:**
Whenever I try to loop through all the guilds and display their acronym it displays this error:

```js
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Guild.get nameAcronym [as nameAcronym]
```

![image0](https://user-images.githubusercontent.com/46196561/86537716-32cd4100-bf2c-11ea-9afb-938e53e8db89.png)

(Occurs on node_modules/discord.js/src/structures/Guild.js)

When I try to loop through guilds and just display their name it displays some of them as undefined

While just looping through them there is no error

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js')
const client = new Discord.Client()

client.on('ready', () => {
    console.log('Acronyms')
    // Gives out an error
    client.guilds.cache.forEach(g => {
        console.log(g.nameAcronym)
    })

    console.log('Names')
    // Displays some of the names as undefined
    client.guilds.cache.forEach(g => {
        console.log(g.name)
    })

    console.log('Nothing')
    // No errors as expected
    client.guilds.cache.forEach(g => {})
})

bot.login('token')
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v14.5.0
- Operating system: Windows 10 v2004
- Priority this issue should have – please be realistic and elaborate if possible: High

- [x] I have also tested the issue on latest master, commit hash:

**Comment by NotSugden** [comment]
from a quick look this looks like one of the guilds is unavailable, `Guild#_patch` sets the name, however its only called if the guild is available (and the name and such is also only sent on an available guild)

**Comment by baanloh** [comment]
As mentioned [here](https://discord.js.org/#/docs/main/stable/class/Guild), you must check `Guild#available` before reading data.

**Comment by yuto0214w** [comment]
As a result, that is a server outage or something.
Sorry for my mistake

**Comment by MidSpike** [comment]
> As mentioned [here](https://discord.js.org/#/docs/main/stable/class/Guild), you must check `Guild#available` before reading data.

I ran into this issue today...

```js
Trace: TypeError: Cannot read property 'replace' of undefined
    at Guild.get nameAcronym [as nameAcronym 
 (C:\Users\MidSpike\Desktop\project_x\node_modules\discord.js\src\structures\Guild.js:524:8)
    at Function.flatten (C:\Users\MidSpike\Desktop\project_x\node_modules\discord.js\src\util\Util.js:39:26)
    at Guild.toJSON (C:\Users\MidSpike\Desktop\project_x\node_modules\discord.js\src\structures\Base.js:35:17)
    at Guild.toJSON (C:\Users\MidSpike\Desktop\project_x\node_modules\discord.js\src\structures\Guild.js:1532:24)
    at JSON.stringify (<anonymous>)
```

In cases of outputting a guild object via `JSON.stringify` for instance; the error above will occur.

---

To prevent `JSON.stringify` from causing headaches for others, I suggest the following fix:

```js
if (!this.name) return null;
```

placed directly before: https://github.com/discordjs/discord.js/blob/c4c817116f868cedb4ec20bcbf90b9b3d382621e/src/structures/Guild.js#L521-L524

**Comment by almostSouji** [comment]
<https://discord.js.org/#/docs/main/stable/class/Guild>
> It's recommended to see if a guild is available before performing operations or reading data from it. You can check this with `guild.available`.
