### ISSUE TITLE
parentID in channel creation not working, channel needs to be moved to the parent later

### ISSUE THREAD

**Issue by fakita1** [discordjs/discord.js#4614]
**Please describe the problem you are having in as much detail as possible:**
parentID option is not working, so I need to move the channel to category after creation, and that does not look good for users, since a channel is spawned on top and then it gets moved, causing all channels to change position.

**Include a reproducible code sample here, if possible:**

```js
            var channel = await reaction.message.guild.channels.create(`ticket-${tNumber}`, {
                type: 'text',
                parentID: config.TicketsCategoryID,
                permissionOverwrites: [
                    {
                        id: reaction.message.guild.id,
                        deny: ['VIEW_CHANNEL'],
                    },
                    {
                        id: user.id,
                        allow: ['VIEW_CHANNEL'],
                    },
                    {
                        id: staffRole,
                        allow: ['VIEW_CHANNEL'],
                    },
                ],
            });


            try {
                await channel.setParent(config.TicketsCategoryID); // Need to do this because parent is not working in channel creation.

            } catch (e) { channel.send('The channel category where this ticket should be moved to was not found.') }
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.16.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Normal, I could really make a good use of this feature but not sure how many people would too!

**Comment by fakita1** [comment]
GIF of how this visual problem looks.

![githubissue](https://user-images.githubusercontent.com/50811499/86537966-472c2200-bec9-11ea-8860-b50b1f195bc8.gif)

**Comment by NotSugden** [comment]
https://discord.js.org/#/docs/main/stable/class/GuildChannelManager?scrollTo=create the option you're looking for is called `parent` not `parentID`

**Comment by fakita1** [comment]
Oh, I'm so sorry! I was looking at https://discord.js.org/#/docs/main/stable/typedef/ChannelData

Issue closed.
