### ISSUE TITLE
Partialize is adding 'deleted' on PartialUser

### ISSUE THREAD

**Issue by Fyko** [discordjs/discord.js#4615]
**Please describe the problem you are having in as much detail as possible:**
[Partialize](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2834) applies an invalid `deleted` property on PartialUser.

**Include a reproducible code sample here, if possible:**
```ts
async function handleReaction(reaction: MessageReaction, user: User | PartialUser): Promise<void> {}

function init() {
    /**
     * Argument of type 'import("discord.js").User | import("discord.js").PartialUser' is not assignable to parameter of type 'User | import("discord.js").PartialUser'.
     * Type 'User' is not assignable to type 'User | PartialUser'.
     * Property 'deleted' is missing in type 'User' but required in type 'PartialUser'.ts(2345)
     *	index.d.ts(2818, 5): 'deleted' is declared here.
     */
    this.client.on('messageReactionAdd', (r, u) => this.handleReaction(r, u));
}
```

**Further details:**

- TypeScript version: `3.9.6`
- discord.js version: `12.2.0_6654e116f35a749c9e625e33223ad548`
- Node.js version: `v14.4.0`
- Operating system: `Manjaro Linux`
- Priority this issue should have – please be realistic and elaborate if possible: minor, can just use ts-ignore for the time being

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by baanloh** [comment]
Are you sure that the `User` type in `async function handleReaction(reaction: MessageReaction, user: User | PartialUser): Promise<void> {}` is the Discord.js User type ?
This line `Argument of type 'import("discord.js").User | import("discord.js").PartialUser' is not assignable to parameter of type 'User | import("discord.js").PartialUser'.` seems to indicate that the argument type `User` is not imported from `discord.js`.
