### ISSUE TITLE
TypeScript Error in <Base>.client when it is instantiated from an extended Client class

### ISSUE THREAD

**Issue by Assfugil** [discordjs/discord.js#4618]
**Please describe the problem you are having in as much detail as possible:**
Same as title
**Include a reproducible code sample here, if possible:**

```ts
import { Client,ClientOptions } from 'discord.js'
class MyClient extends Client {
  foo:string
  constructor(options?:ClientOptions) {
    super(options)
    this.foo = 'bar'
  }
}
const client = new MyClient()
client.on('message',message => {
  console.log(message.client.foo) 
  // Property 'foo' does not exist on type 'Client'.
})
client.login('')
```

**Further details:**

- discord.js version:12.2.0
- Node.js version: 14.5.0
- Operating system: Ubuntu 20.04 LTS, Linux 5.4.0-40-generic 
- Typescript version: 3.9.5
- Priority this issue should have – please be realistic and elaborate if possible: medium 

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Vaporox** [comment]
This is the expected behaviour. `Base#client` (which `Message` extends) is given the type `Client` [here](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L87) and that doesn't get changed when using an extended class. Instead, you can assert its type manually:
```js
console.log((message.client as MyClient).foo)
```

**Comment by kyranet** [comment]
You should use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) for this, that way you don't need to make casts.
