### ISSUE TITLE
random status didn't work properly

### ISSUE THREAD

**Issue by sinkaroid** [discordjs/discord.js#4621]
hello, after i upgrade node => 14.5.0
my random status from array didnt work

```js
function heystats() {
  
            let status = [
                "test",
                "test1",
                "test2"
            ]
        
            let statusR = Math.floor(Math.random() * status.length);
            client.user.setActivity(status[statusR] , {type : "Playing" , status : "Idle"});
          }
          setInterval(heystats, 10000);
```
the main function and prefix is work fine, only bot status did't revealed.
but if i change to single status its work as well
my thanks sir
- discord.js :12.2.0
- Node.js :14.5.0
- OS:Win10 64

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
