### ISSUE TITLE
createStream sometimes does, sometimes does not return a readableStream that emits data

### ISSUE THREAD

**Issue by zaida04** [discordjs/discord.js#4623]
Currently, my code below joins a voice channel, and creates a stream for the message author. However, on multiple attempts of identical execution of this, the data event **doesn't reliably/predictably emit**, making me think that an audio receiving stream isn't being created? Any solutions for this? I looked into the issues log, and found a couple other issues that also referenced this issue, but the solutions provided there do not have an impact (specific being the solution of playing silence on voice channel join, Ref: https://github.com/discordjs/discord.js/issues/2929#issuecomment-435699346)

```js
let connection = await message.member.voice.channel.join();
let stream = connection.receiver.createStream(message.author.id, {"mode": "pcm", "end": "manual"});
stream.on("data", (data) => {
	console.log(data);
});
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v12.16.0
- Priority this issue should have: minor

**Comment by shimahaucks** [comment]
I have the same problem.

**Comment by zaida04** [comment]
Solution provided in referenced PR ended up working. Just need to play a silent frame before creating stream

**Comment by shreyasajj** [comment]
Sorry what was the solution?

**Comment by zaida04** [comment]
The aforementioned solution in the linked issues was to play a silent frame, then create the stream. After trial and error, that seemed to be the most reliable solutions
