### ISSUE TITLE
A new event

### ISSUE THREAD

**Issue by ThumusLive** [discordjs/discord.js#4624]
**Is your feature request related to a problem? Please describe.**
Yeah, my problem is I want to listen all events of my bot to create a event handler, like a command handler

**Describe the ideal solution**
I think a event like " * " who can listen all events can be very helpful

**Describe alternatives you've considered**
I don't know, on the paper it's simple 

**Additional context**
It can be like that 
![image](https://user-images.githubusercontent.com/42680097/87065088-df4f4180-c210-11ea-9831-b694f298d326.png)

**Comment by Papaia** [comment]
You can extend the client for this.
I believe something like the following should work.
```js
class MyClient extends Client {
  emit(event, ...args) {
    super.emit(event, ...args);
    return super.emit('*', event, args);
  }
}
```

**Comment by ThumusLive** [comment]
Oh okay thank you I didn't know that I will try it !
