### ISSUE TITLE
.addField error

### ISSUE THREAD

**Issue by FirezzzZ** [discordjs/discord.js#4634]
**Please describe the problem you are having in as much detail as possible:**
the fields are not showing the data as expected, side by side

**Include a reproducible code sample here, if possible:**
![image](https://cdn.discordapp.com/attachments/723388665304186920/733305850772455464/Screenshot_20200716-182458.jpg)

```js
.addField('Alternative Names', `🇯🇵 ${v1Data.names[0].name}\n🇫🇷 ${v1Data.names[4].name}\n🇩🇪 ${v1Data.names[5].name}`)
                .addField('Base Stats', `**${body.stats[0].stat.name.toUpperCase()}: **${body.stats[0].base_stat}\n**${body.stats[1].stat.name.charAt(0).toUpperCase() + body.stats[1].stat.name.slice(1)}: **${body.stats[1].base_stat}\n**${body.stats[2].stat.name.charAt(0).toUpperCase() + body.stats[2].stat.name.slice(1)}: **${body.stats[2].base_stat}\n**${body.stats[3].stat.name.replace('special-', 'Sp.')}: **${body.stats[3].base_stat}\n**${body.stats[4].stat.name.replace('special-', 'Sp.')}: **${body.stats[4].base_stat}\n**${body.stats[5].stat.name.charAt(0).toUpperCase() + body.stats[5].stat.name.slice(1)}: **${body.stats[5].base_stat}`, true)
                .addField('Height', `${parseFloat(body.height / 10).toFixed(2)}m`, true)
                .addField('Weight', `${parseFloat(body.weight / 10).toFixed(2)}kg`, true)
                .addField('Type', body.types.map(r => r.type.name.toString().charAt(0).toUpperCase() + r.type.name.slice(1)).join(',\n'), true)
                .setFooter(`Displaying Info On  Pokemon - ${body.name.split('-')[0].charAt(0).toUpperCase() + body.name.split('-')[0].slice(1)}`)
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12x
- Operating system: dk
- Priority this issue should have – please be realistic and elaborate if possible: medium
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
This is not an error (by definition) and not a bug with the library either, but a design choice by discord. The "inline" option is merely a suggestion as to what you think how fields should align. The Discord client then decides if it wants to follow that. General cases where it simply doesn't care:

1) The field title or value is too long
2) You are viewing the embed from a mobile device

In both situations fields will not be displayed inline. And there is nothing anyone (including you, including us - as a library) can do against that.
