### ISSUE TITLE
AuditLogs (type:24) : Wrong executor for mute/deaf

### ISSUE THREAD

**Issue by Lucasgood5** [discordjs/discord.js#4635]
Hi, i'm having trouble when trying to find who just muted or deaf me (or anyone).
Using the auditLogs : executor is wrong, when someone else mute/deaf me, the executor is still me(=target)

```js
client.on('voiceStateUpdate', async (ov, nv) => {
    if (nv.member.id == "158312532522565633")
        if (nv.serverMute || nv.serverDeaf)
            if (!ov.serverMute && !ov.serverDeaf) {
                let guild = nv.guild
                let log = await guild.fetchAuditLogs({ limit: 1, user: nv.member.user, type: 24 })
                log = log.entries.first()
                console.log(log) // .executor is wrong ( returning the same of target )
            }
})
```
- discord.js version: 12.2.0
- Node.js version: 6.14.4
- Operating system: Win 10 (x64)
- Priority this issue should have – please be realistic and elaborate if possible: Low (but shouldn't be hard to fix)

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
That's a misconception on your end.
The "user" query in audit logs is the __executing__ user, so of course if you query for yourself (the person being muted) you will receive a log for when you muted someone. (If you are confused by this look at what the user interface allows you, you can to query for targets, this uses the exact same endpoint.)

As another side note: Audit logs are not guaranteed to have arrived when the websocket event (and by extension the discord.js client event) emits.

**Comment by Lucasgood5** [comment]
Nop this is not that, if anyone mute anyone else , executor is still the target i tested it with 3 friend. executor still is same as target

**Comment by Lucasgood5** [comment]
Okay nevermind, i gatcha my error.
