### ISSUE TITLE
Deleting a message with "reason" parameter does not display the reason in audit logs

### ISSUE THREAD

**Issue by JasperLorelai** [discordjs/discord.js#4637]
**Please describe the problem you are having in as much detail as possible:** When using `Message#delete` to delete a message **with a reason**, the `reason` property returns null in fetched `MESSAGE_DELETE` audit logs.

**Reproducible code sample:**
```js
await message.delete({reason: "botIntent"});
```
```js
const log = (await guild.fetchAuditLogs({type: "MESSAGE_DELETE", limit: 1})).entries.first();
console.log(log.id + ": " + log.reason) // log.reason returns null
```

**Further details:**
- discord.js version: master (commit hash below)
- Node.js version: 12.18.0
- Operating system: Unrelated (Win 10 64bit)
- Priority this issue should have: LOW

- [x] I have also tested the issue on latest master, commit hash: `f9f36610907e12b6a1d515aac4728a0f675162aa`

**Comment by NotSugden** [comment]
i believe this is a bug / missing feature for the API

**Comment by JasperLorelai** [comment]
Thank you for the explanation!
