### ISSUE TITLE
GuildMember.nickname has incorrect typings

### ISSUE THREAD

**Issue by octylFractal** [discordjs/discord.js#4640]
**Please describe the problem you are having in as much detail as possible:**
I am trying to avoid saving a nickname if it is not set, but the typings incorrectly claim `string | null` when it is actually `string | undefined`.

**Include a reproducible code sample here, if possible:**

```js
    const nickname = member.nickname;
    if (nickname !== null) {
        console.log(memTag, 'Saving name:', nickname);
        setUserName(member.user.id, member.guild.id, nickname);
    }
```

This code will log "Saving name: undefined" when someone has no nickname, rather than not logging a message at all.

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.1.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: High priority, causes unexpected bugs due to undeclared branch possibilities that the compiler cannot know

- [x] I have also tested the issue on latest master, commit hash: f9f36610

**Comment by almostSouji** [comment]
"member" seems to not refer to a GuildMember instance then.

We receive a member presence from discord in the form 
```js
{
  user: [Object],
  roles: [Array],
  nick: null,
  premium_since: null,
  mute: false,
  deaf: false,
  joined_at: '2017-08-10T23:07:00.313000+00:00'
}
```
If there is no nickname this property will be `null`
https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/src/structures/GuildMember.js#L79

This check updates the members nickname, if it's not undefined (undefined meaning it's not present in the update data, discord only sends partial data on updates). In the initial payload it will be `null`, null is not `undefined` so will get initialized with `null`

---

- User (e.g. `<Message>.author`): global discord user (avatar, username, tag)
- GuildMember (e.g. `<Message>.member`): user data associated with a specific server (guild, nickname, roles, permissions, voice channel, etc.)
- converting User to GuildMember:  you need to fetch it from the guild you need the information for (`<Guild>.members.fetch(<User>)`)
- converting GuildMember to User: `<GuildMember>.user`

**Comment by octylFractal** [comment]
I'm not sure how that could be possible ("member" seems to not refer to a GuildMember instance then), here is how I fetch the member:
```js
async function onJoinGuild(guild: Guild) {
    console.log('Joined guild', guild.name, `(${guild.id})`);
    const members = await guild.members.fetch();
    members.forEach(m => {
        console.log("Nickname", m.nickname);
    });
}
```
With this, I still log `undefined` nicknames. Do you mean to tell me that the `fetch()` method _also_ has incorrect typing?

**Comment by almostSouji** [comment]
I guess i was a bit quick to dismiss this, i feel reminded of #4593 where we had `undefined` for NSFW channels and can indeed reproduce having both `undefined` and `null` nicknames on servers. I will look further into causes for this, thanks for the report!

**Comment by almostSouji** [comment]
This is not a matter of incorrect typings but a bug of the library not handling the initial data correctly. The field is simply not present (access will return `undefined`) if the member in question has no nick name, causing this value to be inserted. The wanted, documented and typed behavior is `null`.
