### ISSUE TITLE
GuildMember.user missing many properties

### ISSUE THREAD

**Issue by Dave395PC** [discordjs/discord.js#4644]
**Please describe the problem you are having in as much detail as possible:**

When fetching a GuildMember with `message.channel.guild.members.fetch()`, the user property is [missing many properties](https://cdn.discordapp.com/attachments/223867697312694272/734555226148700180/unknown.png), and only includes the following: `id`, `username`, `discriminator`, `avatar`, `bot`, `lastMessageID`, `lastMessage`.
After asking on the Discord server, it works fine for someone else, but after changing the installed discord.js module, bot, user, and version (stable in npm and 12.0.2), I get the same exact results.

Edit: 12 of User's 19 properties are missing: `client` `createdAt` `createdTimestamp` `defaultAvatarURL` `dmChannel` `flags` `lastMessageChannelID` `locale` `partial` `presence` `system` `tag`

**Include a reproducible code sample here, if possible:**

```js
message.channel.guild.members.fetch("182663633480712201").then(guildmember => {
    message.channel.send(guildmember.user.fetch());
});
```

**Further details:**

- discord.js version: 12.2.0 & 12.0.2 (As tested)
- Node.js version: 14.5.0
- Operating system: Arch Linux 5.7.9-arch1-1
- Priority this issue should have – please be realistic and elaborate if possible: **Low**, only seems to apply to me and used for random small command

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: `2b6e6d8`

**Comment by tipakA** [comment]
What exactly is missing again?

**Comment by Dave395PC** [comment]
12/19 properties
`client` `createdAt` `createdTimestamp` `defaultAvatarURL` `dmChannel` `flags` `lastMessageChannelID` `locale` `partial` `presence` `system` `tag`

**Comment by Monbrey** [comment]
How are you checking these properties for their existence? Using `console.log` The only one I can see here that should definitely be "defined" is `client`.

- `createdAt` `createdTimestamp` `defaultAvatarURL` `dmChannel` `partial` `presence` and `tag` are all getters that won't appear when using `console.log` to look at the object.
- `flags` doesn't exist on 12.0.2, and requires manual fetching on 12.2.0: `User#fetchFlags()`
- `lastMessageChannelID` is nullable, does not come from API
- `locale` is nullable and is not provided to bots
- `system` can be undefined

**Comment by Dave395PC** [comment]
After some experimentation with your information, I have narrowed down the issue to using `user.fetch()` instead of simply `user`. I also did not know `GuildMemberManager.fetch()` is async as it is not said in the docs.

Sorry for my ignorance, thanks for the help.
