### ISSUE TITLE
Add ability to set "Display role members separately from online members" on a role from discord.js

### ISSUE THREAD

**Issue by DeanBilotti** [discordjs/discord.js#4648]
There doesn't seem to be any ability to effect the "Display role members separately from online members" property on a role from discord.js.

It would be great to be able to set this on a role in a similar way to "Allow anyone to @mention this role" via the .mentionable property: https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=mentionable.

**Comment by iCrawl** [comment]
Are you talking about https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=hoist?
