### ISSUE TITLE
Message Reactions

### ISSUE THREAD

**Issue by entres999** [discordjs/discord.js#4649]
Is there a way for the bot to count the reactions of a message? 
![image](https://user-images.githubusercontent.com/67271715/88085821-aacf7400-cb86-11ea-8b98-74e929483bec.png) 
I have this message and I want to count the reactions to decide which game wins

**Comment by Fyko** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
