### ISSUE TITLE
Add disable roles mention 

### ISSUE THREAD

**Issue by KurokuTetsuya** [discordjs/discord.js#4650]
**Is your feature request related to a problem? Please describe.**
When I just disable everyone mentions in client options, and if I have a say command, a user can mention a role (if the bot has mention role permission). So, can you change the disable mentions option to an array and add disable roles on disable mentions option

**Describe the ideal solution**
Change the disable mentions option to an array and add disable roles on disable mentions option

**Comment by Monbrey** [comment]
This is already possible via the `allowedMentions` options.

**Comment by advaith1** [comment]
Maybe it would be a good idea to deprecate `disableMentions`?
