### ISSUE TITLE
Idea: Server templates

### ISSUE THREAD

**Issue by ItsADerpyTurtle** [discordjs/discord.js#4651]
It would be really helpful for developers of security bots (like me) to be able to create and update server templates in a guild to create backups of servers - similar to how discordpy offers [discord.Template](https://discordpy.readthedocs.io/en/latest/api.html#template).

**Comment by Monbrey** [comment]
The API endpoints for this are not yet documented. Discord.js will implement the feature when API documentation is available.

**Comment by advaith1** [comment]
Bots cannot create or edit server templates, or get a specific server's template.

They can read and use templates (if given the template code), however that is not documented yet (discord/discord-api-docs#1712)

**Comment by advaith1** [comment]
Updates:
> Bots cannot create or edit server templates, or get a specific server's template.

they can now, docs pr: https://github.com/discord/discord-api-docs/pull/2144

> They can read and use templates (if given the template code), however the docs PR for that (discord/discord-api-docs#1712) hasn't been merged yet.

has been merged now, so discord.js can implement it
