### ISSUE TITLE
[typings] Message#partial is typed as "false"

### ISSUE THREAD

**Issue by Fyko** [discordjs/discord.js#4654]
**Please describe the problem you are having in as much detail as possible:**
[Message#partial](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L948) is strictly typed as `false`, although I can be true.

**Include a reproducible code sample here, if possible:**

```ts
import { Client, Intents, MessageReaction } from 'discord.js';

const bot = new Client({
	partials: ['MESSAGE', 'REACTION', 'USER'],
	ws: {
		intents: [
			Intents.FLAGS.GUILDS,
			Intents.FLAGS.GUILD_MESSAGES,
			Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
			Intents.FLAGS.GUILD_MEMBERS,
		],
	},
});

bot.on(Constants.Events.CLIENT_READY, () => console.log(`${bot.user!.tag} is ready!`));
bot.on(Constants.Events.MESSAGE_REACTION_ADD, (reaction: MessageReaction) => console.log(reaction.message.partial));

bot.login('token');
```
1) start bot
2) react to a message that was sent before the bot was started
3) observe

**Further details:**

- discord.js version: `12.2.0_f7fc7d34a07c9bd503fed5a408e179ce`
- Node.js version: `v12.18.2`
- Operating system: `Ubuntu 18.04.4 LTS on Windows 10 [WSL2]`
- Priority this issue should have – please be realistic and elaborate if possible: low

- [x] I have also tested the issue on latest master, commit hash: https://github.com/discordjs/discord.js/commit/2b6e6d86310a9f9fc4293c2f76f37690db9003e4

**Comment by monbrey** [comment]
I believe this is intentional - partial is strictly typed as false on all classes. The `Partialize<T>` typing then strictly types it to true when applied: https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2839

**Comment by NotSugden** [comment]
the example you provided uses `Reaction#partial` not `Message#partial`, but assuming thats a typo and meant to be `Reaction#message#partial`, this could be fixed with a `PartialMessageReaction` type

**Comment by Fyko** [comment]
> the example you provided uses `MessageReaction#partial` not `Message#partial`, but assuming thats a typo and meant to be `MessageReaction#message#partial`, this could be fixed with a `PartialMessageReaction` type

Oops! But yea - the problem is with Reaction#message#partial, I've edited issue to reflect that
