### ISSUE TITLE
Can't delete guild emojis

### ISSUE THREAD

**Issue by bernzrdo** [discordjs/discord.js#4658]
**Is your feature request related to a problem? Please describe.**
I was trying to make a function that creates and deletes guild emojis when I quickly found out you can't delete guild emojis even though [it's on the Discord Developer Portal](https://discord.com/developers/docs/resources/emoji#delete-guild-emoji)

**Describe the ideal solution**
The ideal solution would be to use `message.guild.emojis.delete(emoji.id)` to delete an emoji!

**Describe alternatives you've considered**
I tried using axios to send a delete request to Discord, but sometimes it gave a 429 (Too many requests) error.

**Comment by anandre** [comment]
It exists on the [GuildEmoji](https://discord.js.org/#/docs/main/stable/class/GuildEmoji?scrollTo=delete) class directly.

**Comment by bernzrdo** [comment]
@anandre Thank you!
