### ISSUE TITLE
Dispatcher resume doesn't work

### ISSUE THREAD

**Issue by d4sein** [discordjs/discord.js#4659]
That's pretty much it, dispatcher.pause() works fine, but dispatcher.resume() doesn't do anything, it doesn't even error out.
I double checked the docs and seems like it should work.

This is the app's [file](https://github.com/d4sein/Speech-Recognition-Bot/blob/master/app.js) if the sample isn't enough.
```js
  switch (command.action) {
    case 'Play':
      await addToQueue()
      await playQueue()
      break
    
    case 'Add':
      await addToQueue()
      break

    case 'Stop':
      server.queue = []
      server.dispatcher.destroy()
      break
    
    case 'Pause':
      if (!server.dispatcher.paused) server.dispatcher.pause()
      break
    
    case 'Resume':
      if (server.dispatcher.paused) server.dispatcher.resume()

    case 'Skip':
      if (server.dispatcher) server.dispatcher.destroy()
      break

    default:
      break
  }
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.2
- Operating system: Windows 10
- Priority this issue should have: Low, probably

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Jonathanzhao02** [comment]
If I can jump in, it seems you're missing a `break` in `case 'Resume'`, so it may be moving on to the next case and destroying the dispatcher.

**Comment by d4sein** [comment]
Yeah, I'm retarded, thank you for taking the time to point out the mistake.
