### ISSUE TITLE
Can't install discord.js (npm i discord.js)

### ISSUE THREAD

**Issue by Advanced10** [discordjs/discord.js#4664]
I am unable to install any packages while using GitHub. I do not get an error message, however it gets stuck in between installing any packages.
![image](https://user-images.githubusercontent.com/29985412/88621860-13c35a00-d067-11ea-8dd7-85aebdec5336.png)

**Comment by alhassanv** [comment]
I used to have that issue, there is nothing discord.js maintainers can do to "fix" it.
It got fixed by clearing my dns cache.
