### ISSUE TITLE
Native error - Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by buckette-off** [discordjs/discord.js#4665]
Hello, I don't know why, but my Discord Client has this error :
```
/Users/----/Discord-Bots/KillerQueen/node_modules/discord.js/src/client/websocket/handlers/READY.js:12
    client.users.cache.set(clientUser.id, clientUser);
                       ^

TypeError: Cannot read property 'set' of undefined 
```
It's a error with the code of Discordjs, and I don't know how to fix it. Thanks for helping me

**Comment by monbrey** [comment]
Most likely you are manually redefining `client.users` somewhere in your own code.

**Comment by buckette-off** [comment]
No, i didn't do this

Le mar. 28 juil. 2020 à 13:24, Ryan Munro <notifications@github.com> a
écrit :

**Comment by monbrey** [comment]
Well since you've ignored the issue template and haven't provided your Discord.js version, Node version or a reproducible code sample there's very little I can do to assist further.

**Comment by SpaceEEC** [comment]
You can find the above mentioned issue template here: https://raw.githubusercontent.com/discordjs/discord.js/master/.github/ISSUE_TEMPLATE/bug_report.md

Please make sure that the provided reproducible code sample alone reproduces this error.

**Comment by buckette-off** [comment]
Hello, sorry for the late, but i've fixed it :
With Enmap, I created this ```this.users = new Enmap(...)```, so, it interfered with the native code of DJS, thanks for helping me.
