### ISSUE TITLE
Catching Error Fails to Load due to a code error in discord.js-master/src/client/Client.js at Line 41 

### ISSUE THREAD

**Issue by eeeeEEEEEtttt** [discordjs/discord.js#4666]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
 { catch {
// do nothing
}
```

The code should be replaced with:

```js
{ catch (err) {
// do nothing


}
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: I'm not sure
- Operating system: MAC OS (Using Glitch.com)
- Priority this issue should have – please be realistic and elaborate if possible: Should be fixed ASAP

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

![Screenshot 2020-07-28 at 10 48 43](https://user-images.githubusercontent.com/67335237/88654116-d392c480-d0c4-11ea-9c1b-477619a5f8c9.png)

**Comment by almostSouji** [comment]
Discord.js v12 requires node version 12.0.0 or later. updating min version with v12 was a conscious decision, not a bug, should not be replaced. This is clearly documented <https://discord.js.org/#/docs/main/stable/general/welcome> | <https://github.com/discordjs/discord.js> README.md line 44.

> Node.js 12.0.0 or newer is required.
