### ISSUE TITLE
Extending Discord.Structures do not work as expected when using ES6 modules.

### ISSUE THREAD

**Issue by radiantly** [discordjs/discord.js#4670]
**Please describe the problem you are having in as much detail as possible:**

When using ES6 modules, extending the user structure does not set clientUser as an instance of the new class which leads to errors.

**Reproducible code**

```js
import { Client, Structures, User } from "discord.js";

class coolUser extends User {
  constructor(client, data) {
    super(client, data);
    this.cool = true;
  }
}

Structures.extend("User", () => coolUser);

const client = new Client();

client.once("ready", () => {
  console.log("Ready!");
});

client.on("message", message => {
  console.log(message.author instanceof coolUser); // true
  
  // true if CommonJS
  // false if ES6 module
  console.log(client.user instanceof coolUser); 

  // This returns TypeError if the above statement is false
  message.deletable;
});

// login client
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.5.0
- Operating system: Manjaro Linux
- Priority this issue should have: Medium-low

**Relevant client options:**

- partials: none
- gateway intents: does not matter -- error occurs with intents off or on
- other: none

- [x] I have also tested the issue on latest master, commit hash: fb1dd6b53aee68722b057f9a460eb618c61dd1c6

**Comment by NotSugden** [comment]
the ClientUser export is a getter so it properly extends any custom User class, https://github.com/discordjs/discord.js/blob/master/src/index.js#L66-L68, however the the ESM export is not a getter, https://github.com/discordjs/discord.js/blob/fb1dd6b53aee68722b057f9a460eb618c61dd1c6/esm/discord.mjs#L54 this seems to be the problem, im not sure how exactly to go about resolving it.
