### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by csfvb** [discordjs/discord.js#4672]
Guys i was making a bot but when i am done coding and run it shows me this 
![bandicam 2020-07-30 18-47-44-274](https://user-images.githubusercontent.com/52194715/88988299-60f63480-d2d0-11ea-90ef-c6d5cf8088eb.jpg)
the token is correct but it keeps showing me this pls guys help

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by dokblack** [comment]
You must do something with >
