### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CodeDisease** [discordjs/discord.js#4673]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
I thought it would be a good idea to have functions like Channel.on("delete", callback) or User.on("message", callback)

**Comment by monbrey** [comment]
Channel and User structures are not EventEmitters, which makes this very difficult to provide directly in the library.

You could however look at extending the Collector class to achieve similar functionality in the same way MessageCollector and ReactionCollector allow you to listen to specific message and reaction events respectively.
