### ISSUE TITLE
setName for Channel doesnt always work

### ISSUE THREAD

**Issue by C0kkie** [discordjs/discord.js#4674]
**Please describe the problem you are having in as much detail as possible:**
If i use the code below the channel name doesnt update every 30 like more after few minutes, but i get every 30 seconds the console.log output

**Include a reproducible code sample here, if possible:**

```js
setInterval(async () => {
        let stats = await queryAsync(`SELECT * FROM tb_server_stats ORDER BY id DESC LIMIT 1`);
        if (stats.length == 1) {
            serverData = stats[0];

            if (serverData.online == 1) {
                client.channels.cache.get("658665501467344926").setName(serverData.players + " von " + serverData.slots + " online");
               console.log("Update name")
            } else client.channels.cache.get("658665501467344926").setName("Server-ist-offline");
        }
}, 30000);
```

**Further details:**

- discord.js version: 12.2
- Node.js version: 14.7.0
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: Middle

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [] I have also tested the issue on latest master, commit hash:

**Comment by HarmoGlace** [comment]
The channel name can only be edited twice every 10m. You should not edit it so often

**Comment by C0kkie** [comment]
Is there a reason? With the old discordjs it was working very well

**Comment by C0kkie** [comment]
Hm okay i am pretty sure it was working with v11, but i will test again befor i talk bullshit here

**Comment by almostSouji** [comment]
For more information please refer to #4327
This limit is imposed by the discord API rather recently, it used to work when v11 was still stable, it will have the exact same behavior now, rate limits by the API are not library version sensitive.
