### ISSUE TITLE
Add the ability to fetch the server of a emoji if the emoji's guild is public

### ISSUE THREAD

**Issue by asdfugil** [discordjs/discord.js#4679]
**Describe the ideal solution**
Add a `Emoji.fetchGuild()` method.
**Describe alternatives you've considered**
Use `client.api.emojis("1234").guild.get()`
**Additional context**
The endpoint is https://discord.com/api/v7/emojis/:emoji_id/guild

I tested and bots can use it.

**Comment by TheNoob27** [comment]
wait this EXISTS? man i should read the api docs a bit more i guess

**Comment by advaith1** [comment]
not documented yet, it's still a client experiment and may be removed

**Comment by TheNoob27** [comment]
oh okay that makes more sense

**Comment by Assfugil** [comment]
The guild must have community enabled, but it does not need to be in discovery.

**Comment by advaith1** [comment]
incorrect, it has to be in discovery

**Comment by nkzren** [comment]
Hey, I can work on this. Can I?

**Comment by Chr1s70ph** [comment]
`client.api.emojis("1234").guild.get()` no longer works with the latest version of the API. 

`DiscordAPIError: Bots cannot use this endpoint`
