### ISSUE TITLE
Add custom status to bots

### ISSUE THREAD

**Issue by thanked** [discordjs/discord.js#4681]
Is it possible for you to add so we can set custom status in bots, instead of those WATCHING and PLAYING?

**Comment by monbrey** [comment]
Discord has not documented APIs to support this, so discord.js will not implement this as of yet.

**Comment by thanked** [comment]
When do you think they will add it?

**Comment by anandre** [comment]
You would have to ask discord, not us.

**Comment by thanked** [comment]
Ah alright, thanks
