### ISSUE TITLE
Bring back MessageEmbed#addBlankField method.

### ISSUE THREAD

**Issue by m-Phoenix852** [discordjs/discord.js#4684]
You should consider bringing back the old addBlankField method. That was quite simple and useful and also didn't need long codes.

**Comment by reashetyrr** [comment]
You know you can send a zero width space r8ght

**Comment by m-Phoenix852** [comment]
> You know you can send a zero width space r8ght

wdym zero width space

**Comment by sanikava** [comment]
lol

**Comment by reashetyrr** [comment]
> > You know you can send a zero width space r8ght
> 
> wdym zero width space

A zero width space is a character that is a space but is 0px wide just as the name suggests

**Comment by m-Phoenix852** [comment]
> > > You know you can send a zero width space r8ght
> > 
> > 
> > wdym zero width space
> 
> A zero width space is a character that is a space but is 0px wide just as the name suggests

leave it... I am out.

**Comment by Papaia** [comment]
A [Zero Width Space](https://wikipedia.org/wiki/Zero-width_space) was the character used in `addBlankField`, and you can have it in JS with `'\u200b'`, and a "blank field" can still be added with `embed.addField('\u200b', '\u200b')`.

**Comment by m-Phoenix852** [comment]
> A [Zero Width Space](https://wikipedia.org/wiki/Zero-width_space) was the character used in `addBlankField`, and you can get it in JS with `'\u200b'`, and a "blank field" can still be added with `embed.addField('\u200b', '\u200b')`.

Considering not all of the users will know what a blank space is just like I didn't, that method was handy. Please add it.

**Comment by tipakA** [comment]
It was mentioned in guide page about changes in v12. Namely, [here](https://discordjs.guide/additional-info/changes-in-v12.html#messageembed-addblankfield).

Also note that there is not much reason to use it, as "empty" fields leave gaps on devices that don't support inline displaying.
