### ISSUE TITLE
I have a problem when send message channel

### ISSUE THREAD

**Issue by BANDi2** [discordjs/discord.js#4700]
[https://cdn.discordapp.com/attachments/734687298586935347/743895543704715404/Desktop_Screenshot_2020.08.14_-_21.15.08.75.png](url)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
