### ISSUE TITLE
12.3.0 broke the User.bot property to only be `null | true` not `false | true` like in 12.2.0

### ISSUE THREAD

**Issue by MidSpike** [discordjs/discord.js#4702]
**Please describe the problem you are having in as much detail as possible:**
A `User`'s `.bot` will never be false for a non-bot (unlike in v12.2.0) but it can be `null | true`.

**Include a reproducible code sample here, if possible:**
```js
%eval
const my_user_id = `163646957783482370`;
const my_user = await client.users.cache.get(my_user_id).fetch();
console.log(`my_user.bot`, my_user.bot);
// Expectation is for it to be `false` (it ends up being `null`)

const my_bot_id = `550423785795223627`;
const my_bot = await client.users.cache.get(my_bot_id).fetch();
console.log(`my_bot.bot`, my_bot.bot);
// Expectation is for it to be `true` (it meets this expectation)
```

**Further details:**
- discord.js version: 12.3.0
- Node.js version: 14.3.0
- Operating system: Windows 10
- Priority this issue should have – Moderate: this broke some of my bot after the 12.3.0 update... that's why I noticed.

**Relevant client options:**
- partials: MESSAGE, CHANNEL, REACTION
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Will3126** [comment]
I am glad I am not the only one having this issue, I was about to go insane over this lol.

**Comment by iCrawl** [comment]
In v12 we introduced "Partials".

`User.bot` being initially as false was a bug that was fixed in this version.

While I agree that it is unfortunate this wasn't already in v12 and had to be fixed later, this is in-range of semver and counts as a bug fix, since its a direct result of us introducing "Partials" into the library in the first place.

**Comment by Vaporox** [comment]
The problem here is that (for whatever reason) Discord sends `undefined` instead of `true` for `User#bot` if it's a regular user, so the library thinks that it is a partial object and sets it to `null` instead.

**Comment by MidSpike** [comment]
I think that there should be a notice [in the docs](https://discord.js.org/#/docs/main/12.3.0/class/User?scrollTo=bot) for this behavior or any nullable value for `user.bot` should be considered `true` as a cheeky work-around.
