### ISSUE TITLE
on version 12.3.0 it is not possible to output anything to the console using sharding

### ISSUE THREAD

**Issue by Mirdukkk** [discordjs/discord.js#4703]
**Please describe the problem you are having in as much detail as possible:**
after installation discord.js v12.3.0 output to the console stopped working if using sharding. for example, if I try to write console.log('test') on shard 0, the console will remain empty. but if I do the same on the ShardingManager process, 'test' will appear in the console. the shards are launched and worked correctly.

**Include a reproducible code sample here, if possible:**

```js
// index.js
const { ShardingManager } = require('discord.js')
const manager = new ShardingManager('./bot.js', {
    token: 'token',
    totalShards: 'auto',
    mode: 'process'
})
manager.spawn(this.totalShards, 500, 60000).catch(console.error)
manager.on('shardCreate', shard => console.log(`launched shard ${shard.id}`))
```

```js
// bot.js
const { Client } = require('discord.js')
const client = new Client()
console.log('some log...')

client.on('ready', () => console.log(`shard(s) ${client.shard.ids} ready!`) )
client.login('token')
```
**Further details:**

- discord.js version: 12.3.0
- Node.js version: 14.8.0
- Operating system: Ubuntu server 20.04
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
This might be a regression of: #4308

**Comment by Markus-Rost** [comment]
#4308 hardcoded shards to be silent, this change is not mentioned in the release changelog for 12.3.0.

I think such a change should only be added as an option, would be great if this could be resolved fast.

**Comment by TakeFy** [comment]
hey it's still not solved ? because silent option is not in 12.5.1

**Comment by Hugovidafe** [comment]
I'm having the same problem with Discord v13.3.1

**Comment by ImRodry** [comment]
Please open a new issue, this is over a year old
