### ISSUE TITLE
remove message.reply

### ISSUE THREAD

**Issue by TheMoksej** [discordjs/discord.js#4704]
please remove message.reply it's annoying and I swear most of the newbie d.js guys don't know that message.channel.send exist..

**Comment by anandre** [comment]
That's a breaking change and thus cannot be implemented in v12, you'd have to bring it up on d.js next when it's built.

**Comment by TheMoksej** [comment]
Can't you addit to v13 milestone? 😕

**Comment by qwright10** [comment]
First, message.reply and message.channel.send do two different things. Additionally, there have been no good arguments against message.reply. If you're annoyed by message.reply, you can choose not to use it. If other people choose to use it, that's fully their decision.

**Comment by TheMoksej** [comment]
> First, message.reply and message.channel.send do two different things. Additionally, there have been no good arguments against message.reply. If you're annoyed by message.reply, you can choose not to use it. If other people choose to use it, that's fully their decision.

did I say they are the same? I've said: d.js guys don't know message.channel.send exists

**Comment by iCrawl** [comment]
I'm sure enough people know `message.channel.send` exists and `message.reply` is a convenient short-cut.
