### ISSUE TITLE
wrong typescript definition bot.channels.cache.get

### ISSUE THREAD

**Issue by Trickfilm400** [discordjs/discord.js#4708]
**Please describe the problem you are having in as much detail as possible:**

* **Typescript definitions on property Channel is wrong, or function returns not TextChannel / VoiceChannel object.**
* My plan is to fetch an channel via the channel ID, which is saved in a mongoDB database.
* the only way i found to fetch the Channel object was "bot.channels.cache.get(<ID>)
* this function returns an object of type "Channel", but i want to have "VoiceChannel", to update the Name of the Channel (https://discord.js.org/#/docs/main/stable/class/VoiceChannel?scrollTo=edit)
* https://discord.js.org/#/docs/main/stable/class/Channel does not have property .edit, so typescipt is correct, but the code is working, so the channel name is updating, **only typescipt is wrong**
* the point is, I dont know how to get a channel on any other way, is there an other function to do so?

**Include a reproducible code sample here, if possible:**

```js
let channel = bot.channels.cache.get(<channel id via mongoose>); //returns object of type 'Channel'
//@ts-ignore <-- need this, otherwise "tsc" compiler prints: TS2339: Property 'edit' does not exist on type 'Channel'
channel.edit({name: 'All Members: ' + <integer from mongoose>);
```

**Further details:**

- discord.js version: 12.3.0
- Node.js version: 12.17.0
- Operating system: Linux Debian Buster LXC & Windows 10 1903 WSL (Debian)
- Priority this issue should have – please be realistic and elaborate if possible: **not really important, but anoying**

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

Please ask further questions if i forgot something
#badenglisch sorry

**Comment by monbrey** [comment]
`Channel` is the shared parent class from which all channels in `bot.channels.cache` inherit.

If you're using Typescript, you'll need to cast the `Channel` object returns to the required type, eg `as TextChannel`

**Comment by Trickfilm400** [comment]
thanks for the response

i changed the code:
`let channel = <VoiceChannel>bot.channels.cache.get(<ID>)`

now i am getting the VoiceChannel object

thank you very much
sadly, there is no really nice typescript documentation for this, or I dont know where

have a nice day ;)

**Comment by tipakA** [comment]
That was already answered in issues #4357 and (slightly outdated by now) #3622

**Comment by Trickfilm400** [comment]
Oh yes, thanks, now i know how to search for these types of issues, because i searched for the edit property and found nothing
thanks and sorry for this unnessesarry issue
