### ISSUE TITLE
manager.fetchClientValues('guilds.cache') does not output an array of Collection objects

### ISSUE THREAD

**Issue by KunalsDatabase** [discordjs/discord.js#4712]
**Please describe the problem you are having in as much detail as possible:**
On an application that uses the ShardingManager, using `fetchClientValues` to fetch `client.guilds.cache` on each shard does not return an array of Collection objects. 

As per the documentation, the output of fetchClientValues is ` Promise<Array<*>>`. Doing client.guilds.cache where client is a Discord.Client, would normally return a Collection object according to the documentation, which states it returns a  `Collection<Snowflake, Guild>`, which contains all the guilds in that particular client. However, doing manager.fetchClientValues on the shard's Manager does not return an Array of Collection objects containing the guilds, but instead will return an Array of Arrays containing the guilds. 

Edit: It appears this problem still exists for `manager.broadcastEval('this.guilds.cache')` as well

**Include a reproducible code sample here, if possible:**

### manager.js
```js
const { ShardingManager } = require('discord.js')
const manager = new ShardingManager('./shard.js', {
    token: 'TOKEN',
    totalShards: 'auto',
    mode: 'process'
})
manager.spawn().then(async ()=>{
	const results = await manager.fetchClientValues('guilds.cache')
	console.log(results)
})

```
### shard.js
```js
const { Client } = require('discord.js')
new Client()
.login('TOKEN')
```

Here is the output:

```js
[
  [
    {
      members: [Array],
      channels: [Array],
      roles: [Array],
      deleted: false,
      id: 'id',
      shardID: 0,
      name: 'name',
      icon: null,
      splash: null,
      discoverySplash: null,
      region: 'us-west',
      memberCount: 24,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 3600,
      afkChannelID: 'id',
      systemChannelID: 'id',
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: timestamp,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: 0,
      vanityURLCode: null,
      vanityURLUses: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      preferredLocale: 'en-US',
      ownerID: 'id',
      emojis: [],
      createdTimestamp: timestamp,
      nameAcronym: 'n',
      iconURL: null,
      splashURL: null,
      discoverySplashURL: null,
      bannerURL: null
    },
    {
      members: [Array],
      channels: [Array],
      roles: [Array],
      deleted: false,
      id: 'id',
      shardID: 0,
      name: 'name',
      icon: null,
      splash: null,
      discoverySplash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: 'id',
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: timestamp,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: 0,
      vanityURLCode: null,
      vanityURLUses: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      preferredLocale: 'en-US',
      ownerID: 'id',
      emojis: [],
      createdTimestamp: timestamp,
      nameAcronym: 'n',
      iconURL: null,
      splashURL: null,
      discoverySplashURL: null,
      bannerURL: null
    }
  ]
]
```
As you can see here, the output is simply and array within an array that contains all of the guilds the bot is in, which in this case is two. 

**Further details:**

- discord.js version:  discord.js@12.3.1 (github:discordjs/discord.js#56e8ef2d38633154540748acb64f4c1305fcc6d3)
- Node.js version: v12.16.2
- Operating system: Microsoft Windows 10 build 1909
- Priority this issue should have – please be realistic and elaborate if possible: medium
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ x] I have also tested the issue on latest master, commit hash: bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc

**Comment by monbrey** [comment]
This is expected behaviour. In order to transmit the data between processes it needs to be transformed into a serialisable format. This is why what you receive is primitives, objects and arrays - not Guild classes, and no Collections or Managers

**Comment by KunalsDatabase** [comment]
Oh I see, that explains the behaviour, since it is communicating using the process listeners. Thank you, I will close the issue
