### ISSUE TITLE
Invalid bitfield flag or number

### ISSUE THREAD

**Issue by ZachGaming** [discordjs/discord.js#4713]
**Please describe the problem you are having in as much detail as possible:**
So, I am trying to create a warn command for my Discord Bot and I keep running into this one particular error.

**Include a reproducible code sample here, if possible:**
Code:
  if(cmd === `${prefix}warn`){

    let wUser = message.guild.member(message.mentions.users.first() || message.guild.members.cache.get(args[0]));
    if(!wUser) return message.channel.send("That user couldn't be found.");
    let wReason = args.join(" ").slice(22);
    if(!message.member.hasPermission("MANAGE_MEMBERS")) return message.channel.send("You do not have the required permissions to perform this act.");
    if(wUser.hasPermission("MANAGE_MEMBERS")) return message.channel.send("This person has stopped this action with a forcefield of permissions.");

    let warnEmbed = Discord.MessageEmbed()
    .setDescription("Warn a User.")
    .setColor("RANDOM")
    .addField("Warned User", `${wUser} with ID: ${wUser.id}`)
    .addField("Warned By", `<@${message.author.id}> with ID: ${message.author.id}`)
    .addField("Warned In", message.channel)
    .addField("Warned At", message.createdAt)
    .addField("Reason", wReason);

    let warnChannel = message.guild.channels.cache.find(channel => channel.name === "punishments");
    if(!warnChannel) return message.channel.send("Couldn't find punishments channel.");

    return warnChannel.send(warnEmbed);
  }

**Comment by ZachGaming** [comment]
Error Message: (node:54016) UnhandledPromiseRejectionWarning: RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number.

**Comment by advaith1** [comment]
seems to be the same as #4696

can you narrow your code down to the part causing the error?

**Comment by flamelessdev** [comment]
See [here](https://discord.js.org/#/docs/main/stable/class/Permissions?scrollTo=s-FLAGS) for all valid permission flags - note that `MANAGE_MEMBERS` isn't one of them.
Generally, you should try and get support in the discord.js support server before creating an issue here.

**Comment by lukas-studio-tv** [comment]
Got the same issue, using a valid flag.

**Comment by ImRodry** [comment]
This issue is a year and a half old. You likely did not use a valid flag but if you really believe you did, please open a new one and don't reply to issues that were invalid and closed a long time ago.
