### ISSUE TITLE
ban command returning internal error

### ISSUE THREAD

**Issue by Tjabooo** [discordjs/discord.js#4715]
**Please describe the problem you are having in as much detail as possible:**

It's the problem that makes my bot not fully working. It's the fact that i can't use the ban command, it sends everything such as the ban message but it doesn't execute the ban command. I added some new code to implement it so when a member gets banned, they get a dm saying they have been banned and why they have been banned.

**Include a reproducible code sample here, if possible:**

```js
        const mentionMember = message.mentions.members.first();
        mentionMember.ban(banReason)
```
(this is just the line that doesnt work and the const of the string i use to define the member which is being banned so there's no misunderstandings)

**Further details:**

- discord.js version: v^12.3.1
- Node.js version: v14.8.0
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible: For me, pretty high since it's the problem that makes my bot not fully working. It's the fact that i can't use the ban command, it sends everything such as the ban message but it doesn't execute the ban command. You can decide for yourself if this is a high priority.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by anandre** [comment]
You don't provide the actual error from the code provided.  In addition, this sort of problem should be brought to the Discord server for support, this is not a bug with the library.

**Comment by Tjabooo** [comment]
> 
> 
> You don't provide the actual error from the code provided. In addition, this sort of problem should be brought to the Discord server for support, this is not a bug with the library.

What do you mean? I brought this up in the #developer in the top.gg discord and they told me to open an issue on here.

**Comment by qwright10** [comment]
Please join the official Discord.js server at https://discord.gg/bRCvFy9 and ask in either of the #djs-help support channels.

**Comment by monbrey** [comment]
I believe this may be a result of #4370 causing a different error to be thrown, however your usage of the `.ban()` method is incorrect. Unlike `.kick()` which only takes a string, `.ban()` accepts an options object.

**Comment by Newplan1** [comment]
try doing this: " msg.guild.members.ban(Banmember, { reason: reason }).catch(err => console.log(err));"

**Comment by Tjabooo** [comment]
> 
> 
> I believe this may be a result of #4370 causing a different error to be thrown, however your usage of the `.ban()` method is incorrect. Unlike `.kick()` which only takes a string, `.ban()` accepts an options object.
> 
> https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=ban

Yes, I changed it up now but I found that it says I have to input a reason which I did. So I tried to change it back but still gave the same error. I use the version 12.2.0 so when I changed back I shouldn't have received any errors?

**Comment by Tjabooo** [comment]
> 
> 
> try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> and replace "members" with "users"

Did it, gave the same response as in my latest reply and it didn't log any errors.

**Comment by Newplan1** [comment]
> > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > and replace "members" with "users"
> 
> Did it, gave the same response as in my latest reply and it didn't log any errors.

did it punished?

**Comment by Tjabooo** [comment]
> 
> 
> > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > and replace "members" with "users"
> > 
> > 
> > Did it, gave the same response as in my latest reply and it didn't log any errors.
> 
> did it punished?

No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.

**Comment by Newplan1** [comment]
> > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > and replace "members" with "users"
> > > 
> > > 
> > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > 
> > 
> > did it punished?
> 
> No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.

yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty

**Comment by Tjabooo** [comment]
> 
> 
> > > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > > and replace "members" with "users"
> > > > 
> > > > 
> > > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > > 
> > > 
> > > did it punished?
> > 
> > 
> > No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.
> 
> yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty
> if it's true it will but the text you putted in the second "reason:"

What? I don't really understand, I made it so if you don't input a reason then the punishment it returns the ban and stops it so it doesn't get executed.

**Comment by Newplan1** [comment]
> > > > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > > > and replace "members" with "users"
> > > > > 
> > > > > 
> > > > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > > > 
> > > > 
> > > > did it punished?
> > > 
> > > 
> > > No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.
> > 
> > 
> > yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty
> > if it's true it will but the text you putted in the second "reason:"
> 
> What? I don't really understand, I made it so if you don't input a reason then it returns the ban and stops it so it doesn't get executed.
                                                    
you replace the "{ reason: banReason }" with "{ reason: banReason ? reason: "Your text" }", explaning what "?" means it means that if the "banReason" var is empty it will replace it with "Your text".

**Comment by Tjabooo** [comment]
> 
> 
> > > > > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > > > > and replace "members" with "users"
> > > > > > 
> > > > > > 
> > > > > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > > > > 
> > > > > 
> > > > > did it punished?
> > > > 
> > > > 
> > > > No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.
> > > 
> > > 
> > > yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty
> > > if it's true it will but the text you putted in the second "reason:"
> > 
> > 
> > What? I don't really understand, I made it so if you don't input a reason then it returns the ban and stops it so it doesn't get executed.
> 
> you replace the "{ reason: banReason }" with "{ reason: banReason ? reason: "Your text" }", explaning what "?" means it means that if the "banReason" var is empty it will replace it with "Your text".

That didn't fix it, the ban works but the reason message it completely fucked. If I input a reason, in the ban confirmation embed message it doesn't say anything under the "Ban reason:" and in the audit log it gives the reason that no reason was given.

**Comment by Newplan1** [comment]
> > > > > > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > > > > > and replace "members" with "users"
> > > > > > > 
> > > > > > > 
> > > > > > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > > > > > 
> > > > > > 
> > > > > > did it punished?
> > > > > 
> > > > > 
> > > > > No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.
> > > > 
> > > > 
> > > > yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty
> > > > if it's true it will but the text you putted in the second "reason:"
> > > 
> > > 
> > > What? I don't really understand, I made it so if you don't input a reason then it returns the ban and stops it so it doesn't get executed.
> > 
> > 
> > you replace the "{ reason: banReason }" with "{ reason: banReason ? reason: "Your text" }", explaning what "?" means it means that if the "banReason" var is empty it will replace it with "Your text".
> 
> That didn't fix it, the ban works but the reason message it completely fucked. If I input a reason, in the ban confirmation embed message it doesn't say anything under the "Ban reason:" and in the audit log it gives the reason that no reason was given.

did you putted "{ Ban reason: something }" ?
that will break the ".ban" instead use "reason:"

**Comment by Newplan1** [comment]
it will probably fix your problem

**Comment by Tjabooo** [comment]
> 
> 
> > > > > > > > > try doing this: " message.guild.members.ban(mentionMember, { reason: banReason }).catch(err => console.log(err));"
> > > > > > > > > and replace "members" with "users"
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Did it, gave the same response as in my latest reply and it didn't log any errors.
> > > > > > > 
> > > > > > > 
> > > > > > > did it punished?
> > > > > > 
> > > > > > 
> > > > > > No, it just returned with the message "@Tjabo ⭐🤡🩸 you have to put a reason for the ban. h.help for more information" which is the reply it gives when not inputting a reason.
> > > > > 
> > > > > 
> > > > > yes because when you punish it you need a reason but you can change by doing { reason: banReason ? reason: "Nothing or the text you want" } the "?" checks if it's empty
> > > > > if it's true it will but the text you putted in the second "reason:"
> > > > 
> > > > 
> > > > What? I don't really understand, I made it so if you don't input a reason then it returns the ban and stops it so it doesn't get executed.
> > > 
> > > 
> > > you replace the "{ reason: banReason }" with "{ reason: banReason ? reason: "Your text" }", explaning what "?" means it means that if the "banReason" var is empty it will replace it with "Your text".
> > 
> > 
> > That didn't fix it, the ban works but the reason message it completely fucked. If I input a reason, in the ban confirmation embed message it doesn't say anything under the "Ban reason:" and in the audit log it gives the reason that no reason was given.
> 
> did you putted "{ Ban reason: something }" ?
> that will break the ".ban" instead use "reason:"

I copied your message: { reason: banReason ? reason: "Your text" } and just replaced the "Your text"

**Comment by Tjabooo** [comment]
> 
> 
> it will probably fix your problem

        message.guild.members.ban(mentionMember, { reason: banReason ? reason: `${message.member} you have to put a reason for the ban. h.help for more information <:hisokasmile:744282907597865020>`}) this is my line completely just copied and pasted into here, what's wrong? Tell me what to change.

**Comment by Newplan1** [comment]
> > it will probably fix your problem
> 
> ```
>     message.guild.members.ban(mentionMember, { reason: banReason ? reason: `${message.member} you have to put a reason for the ban. h.help for more information <:hisokasmile:744282907597865020>`}) 
> ```
> 
> this is my line completely just copied and pasted into here, what's wrong? Tell me what to change.

it misses a "}"
and there's an ` floating in no where

**Comment by Tjabooo** [comment]
> 
> 
> > > it will probably fix your problem
> > 
> > 
> > ```
> >     message.guild.members.ban(mentionMember, { reason: banReason ? reason: `${message.member} you have to put a reason for the ban. h.help for more information <:hisokasmile:744282907597865020>`}) 
> > ```
> > 
> > 
> > this is my line completely just copied and pasted into here, what's wrong? Tell me what to change.
> 
> it misses a "}"
> and there's an ` floating in no where

where? also i changed it to this: 

        message.guild.members.ban(mentionMember, { reason: banReason ? reason: "No reason given."})

**Comment by Newplan1** [comment]
> > it will probably fix your problem
> 
> ```
>     message.guild.members.ban(mentionMember, { reason: banReason ? reason: `${message.member} you have to put a reason for the ban. h.help for more information <:hisokasmile:744282907597865020>`}) 
> ```
> 
> this is my line completely just copied and pasted into here, what's wrong? Tell me what to change.

i have an ideia make 
try doing
if(banReason == null)
{
     <message>.channel.send("Your message")
}
else
{
    message.guild.members.ban(mentionMember, { reason: banReason}) 

}

**Comment by Tjabooo** [comment]
> 
> 
> > > it will probably fix your problem
> > 
> > 
> > ```
> >     message.guild.members.ban(mentionMember, { reason: banReason ? reason: `${message.member} you have to put a reason for the ban. h.help for more information <:hisokasmile:744282907597865020>`}) 
> > ```
> > 
> > 
> > this is my line completely just copied and pasted into here, what's wrong? Tell me what to change.
> 
> i have an ideia make
> try doing
> if(banReason == null)
> {
> .channel.send("Your message")
> }
> else
> {
> message.guild.members.ban(mentionMember, { reason: banReason})
> 
> }

Will this work:

if(!banReason) {
  message.channel.send('My message');
  return;
} else {
          message.guild.members.ban(mentionMember, { reason: banReason})

**Comment by Newplan1** [comment]
Yes it will

**Comment by Tjabooo** [comment]
> 
> 
> Yes it will

No, it doesn't work. It just gives me the message 'You have to input a reason' which I am..

**Comment by Newplan1** [comment]
> > Yes it will
> 
> No, it doesn't work. It just gives me the message 'You have to input a reason' which I am..

Hmmm, i think made a mistake somewhere

**Comment by vzwGrey** [comment]
These GitHub issues are not for support. Especially not basic JavaScript support.
Please move into the [Discord.js Official](https://discord.gg/bRCvFy9) server for Discord.js support and somewhere else for JavaScript support.

**Comment by anandre** [comment]
Please come to the Discord.js official server for support with code, this is not a library issue and would be better suited for support there.  https://discord.gg/bRCvFy9
