### ISSUE TITLE
converted buffer streams have a massive latency without a workaround since v12

### ISSUE THREAD

**Issue by FMS-Cat** [discordjs/discord.js#4722]
I'm using converted 16bit int stream on my bot and that is intended to be used for realtime synthesis purpose.
I've been troubled by a massive latency since I updated the discord.js to v12.
I've seen your source code and found this:

https://github.com/discordjs/discord.js/blob/05c9e301639848121dda27ab1f8a643f465be502/src/client/voice/player/BasePlayer.js#L59-L62

I doubted that the code makes it weird, and that was correct.
Here, you're using `options.volume === false` . I have tried to put a explicit `false` to `StreamOption.volume` and it has been resolved.

Is this intended to be put `false` explicitly? I just want to leave this undefined if I don't have to care about the volume.

I'm not sure why this affected since v12 though (it's my first time reading this code).

**Comment by FMS-Cat** [comment]
Should I make a PR by my own?

**Comment by kyranet** [comment]
I assigned @amishshah as this is his territory 👍🏼

**Comment by amishshah** [comment]
Hi! This is intended, but there was talks about changing this later on. At the moment, if you play an opus stream it is also decoded to PCM before re-encoding to play it to allow for volume adjustments; that is, volume modification is opt-out. This is the reason for the high latency as you discovered. Setting volume to false will opt-out and not try to modify the input stream at all.

This is vaguely discussed in the [documentation](https://discord.js.org/#/docs/main/stable/typedef/StreamOptions). I hope this helps, feel free to reopen the issue if that didn't answer your question.
