### ISSUE TITLE
GuildAuditLogsEntry target can be a Channel

### ISSUE THREAD

**Issue by MCMrARM** [discordjs/discord.js#4728]
When creating a text channel and then fetching the audit logs, in the `CHANNEL_CREATE` event, the `target` is a `TextChannel` which is not reflected by the TypeScript bindings:
```
  class GuildAuditLogsEntry {
    constructor(logs: GuildAuditLogs, guild: Guild, data: object);
    public action: GuildAuditLogsAction;
    public actionType: GuildAuditLogsActionType;
    public changes: AuditLogChange[] | null;
    public readonly createdAt: Date;
    public readonly createdTimestamp: number;
    public executor: User;
    public extra: object | Role | GuildMember | null;
    public id: Snowflake;
    public reason: string | null;
    public target: Guild | User | Role | GuildEmoji | Invite | Webhook | Integration | null;
    public targetType: GuildAuditLogsTarget;
    public toJSON(): object;
  }
```
Probably GuildChannel should be added to the target possible types.

Example `console.log` of a `CHANNEL_CREATE` `GuildAuditLogsEntry`:
```
GuildAuditLogsEntry {
  targetType: 'CHANNEL',
  actionType: 'CREATE',
  action: 'CHANNEL_CREATE',
  reason: null,
  executor: User {
    id: '406368483148824577',
    bot: false,
    username: 'mrarm',
    discriminator: '2392',
    avatar: 'c426fc3adc8e1ba9894b64810990968f',
    flags: UserFlags { bitfield: 64 },
    lastMessageID: null,
    lastMessageChannelID: null
  },
  changes: [
    { key: 'name', old: undefined, new: 'test' },
    { key: 'type', old: undefined, new: 0 },
    { key: 'permission_overwrites', old: undefined, new: [Array] },
    { key: 'nsfw', old: undefined, new: false },
    { key: 'rate_limit_per_user', old: undefined, new: 0 }
  ],
  id: [redacted],
  extra: null,
  target: <ref *1> TextChannel {
    type: 'text',
    deleted: false,
    id: [redacted],
    name: 'test',
    rawPosition: 59,
    parentID: [redacted],
    permissionOverwrites: Collection(5) [Map] {
      [redacted]
    },
    topic: null,
    nsfw: false,
    lastMessageID: null,
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      [redacted]
    },
    messages: MessageManager {
      cacheType: [class LimitedCollection extends Collection],
      cache: [LimitedCollection [Map]],
      channel: [Circular *1]
    },
    _typing: Map(0) {}
  }
}
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v14.6.0
- Operating system: Arch Linux
- Priority this issue should have – low

**Relevant client options:**

- partials: ['MESSAGE', 'REACTION']
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by tguichaoua** [comment]
The target can also be a `Message`.
https://github.com/discordjs/discord.js/blob/05c9e301639848121dda27ab1f8a643f465be502/src/structures/GuildAuditLogs.js#L29-L41
Or be a object with only the `id` property
https://github.com/discordjs/discord.js/blob/05c9e301639848121dda27ab1f8a643f465be502/src/structures/GuildAuditLogs.js#L478

So this line
https://github.com/discordjs/discord.js/blob/05c9e301639848121dda27ab1f8a643f465be502/typings/index.d.ts#L751

must be changed to something like this:
`public target: Guild | GuildChannel | User | Role | GuildEmoji | Invite | Webhook | Message | Integration | { id: string } | null;`
