### ISSUE TITLE
Playlist problem 

### ISSUE THREAD

**Issue by RickOrnichons** [discordjs/discord.js#4729]
Hello !! 

I've got a little issue with that command play :
https://paste.slywork.io/B1JqG9Dp

-> If I listen only one music, no problem. 

-> If I put 2 or 3 musics in the queue, i've got an issue. At the end of the first, the URL of the second is logged (just like in the console.log), but she wasn't play. She is just skip and the bot disconnect like the queue is empty.

A little idea ?

I think, I have to change the structure of the function play, but i don't know how

Thanks for help !

**Comment by mrtnpwn** [comment]
This is definitely your fault and shouldn't be here labeled as a bug in the first place.

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements related to discord.js.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
