### ISSUE TITLE
Message.channel.bulkDelete() doesn't exist

### ISSUE THREAD

**Issue by owoNUB** [discordjs/discord.js#4731]
I'm using Typescript 4.0.2, the error is with the Typescript typings from what I can see. The error is:
```
error TS2339: Property 'bulkDelete' does not exist on type 'TextChannel | DMChannel | NewsChannel'. Property 'bulkDelete' does not exist on type 'DMChannel'.
```

```ts
client.on("message", async(msg: discord.Message) => {
if (msg.content == "!delete") {
let messages = await msg.channel.messages.fetch({ limit: 100 });
msg.channel.bulkDelete(messages);
}
})
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.5.0
- Operating system: Windows 8.1
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by OmgImAlexis** [comment]
@owoNUB any chance on a code example? New to `discord.js` and stuck on the same issue.

**Comment by cursorsdottsx** [comment]
i literally went into the index.d.ts and slapped it there myself. probably not a good practice owo

**Comment by cursorsdottsx** [comment]
```ts
if (message.channel.type === "dm") return;
```
anyways I think they meant this, didn't work for me, though

**Comment by monbrey** [comment]
The correct was to handle this in TypeScript is to cast the channel to the correct type, eg `TextChannel` or `NewsChannel` on which `bulkDelete` does exist.

**Comment by OmgImAlexis** [comment]
@monbrey that’s a hack. The types should be updated to ensure when we do the check listed above it resolves correct. Type guarding and such should work.

**Comment by monbrey** [comment]
> @monbrey that’s a hack. The types should be updated to ensure when we do the check listed above it resolves correct. Type guarding and such should work.

The entire typing file is "a hack" given that the code is written in JavaScript. We've tried before to resolve the issue of Channel typeguards but it causes issues in edge-cases.

When the library is eventually rewritten in TypeScript as the primary language, the issue (should) be resolved.

**Comment by ksvls** [comment]
Hello, sorry for necroposting but here is what work for me:
```ts
const amount = 100
if (message.channel.type === 'text') message.channel.bulkDelete(amount)
```

**Comment by FedericoGregori** [comment]
Hey guys, I want to share how It worked for me (based on this thread suggestions). Thanks

```javascript
const messages = await message.channel.messages.fetch({ limit: 100 });
if (messages) {
  if (message.channel.type === "GUILD_TEXT") {
    message.channel.bulkDelete(messages);
  }
}
```

```javascript
  "dependencies": {
    "discord.js": "^13.1.0"
  },
  "devDependencies": {
    "typescript": "^4.4.3"
  }
```

**Comment by jebediah47** [comment]
> Hey guys, I want to share how It worked for me (based on this thread suggestions). Thanks
> 
> ```js
> const messages = await message.channel.messages.fetch({ limit: 100 });
> if (messages) {
>   if (message.channel.type === "GUILD_TEXT") {
>     message.channel.bulkDelete(messages);
>   }
> }
> ```
> 
> ```js
>   "dependencies": {
>     "discord.js": "^13.1.0"
>   },
>   "devDependencies": {
>     "typescript": "^4.4.3"
>   }
> ```

This worked for me too, thanks a lot!
