### ISSUE TITLE
How do I appeal my ban in the discord

### ISSUE THREAD

**Issue by thetayloredman** [discordjs/discord.js#4732]
I was banned in the discord a while back and I can't DM the person because I don't have a mutual server

How do I get back in? I was banned about a year ago

**Comment by thetayloredman** [comment]
Didn't mean to add the bug label, wrong button :(

**Comment by iCrawl** [comment]
You just send a friend request then.

**Comment by thetayloredman** [comment]
I don't remember who it was

**Comment by thetayloredman** [comment]
Oh nvm
