### ISSUE TITLE
Simpler way to get array of guild members

### ISSUE THREAD

**Issue by thetayloredman** [discordjs/discord.js#4733]
**Is your feature request related to a problem? Please describe.**
Yes, I'm struggling to get an array of guild members. I'm trying `.map` of `client.guilds.cache.get('xxxx').members.cache`.

**Describe the ideal solution**
A way for me to easily do something like `let membersArray = client.guilds.cache.get('xxxx').membersarr`

**Describe alternatives you've considered**
I know there is a way to do it but it confuses me, so this or any simple syntaxes would help.

**Additional context**
When using the `.map()` method I get an array like this:
```
[
1,2,3,4,5,6,7,8,9,10,11,length
]
```
Where expecting:
```
[
123456789012345678, 123456789012345679, 123456789012445678, 123456789012645678, 123456789012345679, 123456889012445678, 123456735712345678, 123456789025345679, 123456780835445678, 123456789642255678, 123579435012345679
]
```

**Comment by qwright10** [comment]
Collection has the method #array(), returning an array of all the values it contains. Similarly, Collection#keyArray() returns an array of the keys it contains.

**Comment by LiamTownsley** [comment]
guild.members.cache.array()

**Comment by thetayloredman** [comment]
> Collection has the method #array(), returning an array of all the values it contains. Similarly, Collection#keyArray() returns an array of the keys it contains.

Oml how did i forget

> guild.members.cache.array()

how did i forget aaa
