### ISSUE TITLE
Discord bot seems to use different emoji encoding than Discord

### ISSUE THREAD

**Issue by MasonStooksbury** [discordjs/discord.js#4739]
So, in trying to tag a channel that has an emoji in it, I am able to replicate this on my end as a user by simply typing the emoji (The format where a word is surrounded by colons on either side)

However, when I mimic this in discord.js, the bot seems to send a differently-encoded emoji that what native discord uses. My only reasoning for thinking this is that they look different, and they tend to look different based on the platform (while the emoji code may be the same, it looks different on Twitter vs Google vs iOS vs etc.) "Encoding" is probably the wrong word, but I can't think of what else would cause it to have the platform-dependent look.

```
else if (msg.content.startsWith(prefix + 'fixcrash')) {
		msg.channel.send('If you still need help, ask in #help (or #patron:sos:help for patrons)');
	}
```

Running the above code causes it to look [like this](https://imgur.com/a/PQH7WcI), but I also have examples where I just used the emoji Discord provided and it's different.
**Further details:**

- discord.js version: 11.5.1
- Node.js version: 12.13.1
- Operating system: Windows 10
- Priority this issue should have: Meh

**Comment by tguichaoua** [comment]
It's because in channel's name the emoji is an character, but in you message you use the colons format that is interpreted by discord as an emoji. If you want to mention a channel you must use this format: `<#xxxxxxxxxxxxxxxxxx>` where `xxxxxxxxxxxxxxxxxx` is the id of the channel.

**Comment by MasonStooksbury** [comment]
Do I have to use the ID? Because I'm able to use the chat box to type out the channel name and use the colon format and it work just fine. How come it doesn't work when discord.js tries to do that?

**Comment by tguichaoua** [comment]
It's because when you submit a text in the chat box, discord replace all mentions (#channel, @user) by the id format (<#xxxxxxxxx>, <@xxxxxxxxxxxx>). The chat box can recognize the emoji that correspond to the colon format and find the correct channel.

**Comment by MasonStooksbury** [comment]
Ohhhh I got you, now. So discord.js doesn't do the same sort of translation that native discord does on the fly. So I'll need to hardcode the ID of the channel in order for it to work, right?

**Comment by tguichaoua** [comment]
Yes, if you bot will be use only in 1 guild you could hardcode the ID.

**Comment by MasonStooksbury** [comment]
Sounds good. Thanks for the help!

**Comment by almostSouji** [comment]
The `:name:` notation is a shortcut which the client transforms into either the unicode emoji or the `<a:name:id>`/`<:name:Id>` format before sending it off to the API. The viewing client then may convert it back to the emoji image (unicode -> [twemoji ](https://github.com/twitter/twemoji)font, custom -> image from the discord [CDN](https://discord.com/developers/docs/reference#image-formatting))

For future reference: please use discord for questions or to verify bugs if you are unsure if it even is one.
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
