### ISSUE TITLE
Extending Presence doesn't affect all members?

### ISSUE THREAD

**Issue by ObscuritySRL** [discordjs/discord.js#4742]
**Please describe the problem you are having in as much detail as possible:**
If you extend `Presence` with, say, `PresenceExt`, some members will have `Presence`, some will  have `PresenceExt`. It seems like they will always have `PresenceExt` after a legitimate `presenceUpdate`.

**Include a reproducible code sample here, if possible:**

```js
//Formatting helps with my bad eyes. Don't shoot.

//Extend the Presence structure...
Discord.Structures.extend(
    'Presence',
    Presence => class PresenceExt extends Presence {
        //Give it a simple method to test...
        get isTwitchStreaming( ) {
            return this.activities.some( ( { name, type } ) => name === 'Twitch' && type === 'STREAMING' );
        }
    }
);


//Initialize the client...
const bot = new Discord.Client( {
    //I know, not recommended. I only use it for small, private bots...
    fetchAllMembers: true
} );


bot.on( 'ready', ( ) => {
    //Get a random guild...
    const guild = bot.guilds.cache.random( );;

    //Add up the PresenceExt and Presence...
    const results = guild.members.cache.reduce(
        ( results, { presence: { constructor: { name } } } ) => ( { ...results, [ name ]: 1 + ( results[ name ] ?? 0 ) } ),
        { }
    );

    //{ PresenceExt: 241, Presence: 2065 }...
    console.log( results );
} );


//These will all be PresenceExt...
bot.on( 'presenceUpdate', ( _, { constructor: { name } } ) => console.log( name ) );
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.4.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: `[ 'CHANNEL', 'GUILD_MEMBER', 'MESSAGE', 'REACTION', 'USER' ]`
- gateway intents: none
- other: none

**Comment by SpaceEEC** [comment]
This is due to [`GuildMember#presence`](https://github.com/discordjs/discord.js/blob/stable/src/structures/GuildMember.js#L158) and [`User#presence`](https://github.com/discordjs/discord.js/blob/stable/src/structures/User.js#L159) returning `new Presence(...);` when no presence is available for the member (or user), which does not account for extensions.

This should be fixable by returning something like `new (Structures.get('Presence'))(...)` instead.

**Comment by NotSugden** [comment]
> This should be fixable by returning something like `new (Structures.get('Presence'))(...)` instead.

shouldn't it be `this.client.presences.add(...)`?
