### ISSUE TITLE
embed

### ISSUE THREAD

**Issue by konoashi** [discordjs/discord.js#4747]
embed2 = {
        "title": "konoashi's Skills on Grapes",
        "description": "Average skill level: 19.75",
        "color": 16106588,
        "author": {
          "name": "Request - ",
          "icon_url": "https://cdn.discordapp.com/avatars/365106065106272256/c55a1389037221e135611897ef15876b.png?size=128"
        },
        "fields": [
          {
            "name": ":ear_of_rice: Farming Level",
            "value": "**LEVEL 19**\n408,794XP total\n113,631XP to next level    ",
            "inline": true
          },
          {
            "name": ":pick: Mining Level",
            "value": "**LEVEL 20**\n536,620XP total\n285,805XP to next level",
            "inline": true
          },
          {
            "name": ":crossed_swords: Combat Level",
            "value": "**LEVEL 21**\n838,011XP total\n384,414XP to next level",
            "inline": true
          },
          {
            "name": ":deciduous_tree: Foraging Level",
            "value": "**LEVEL 21**\n838,011XP total\n384,414XP to next level",
            "inline": true
          },
          {
            "name": ":fishing_pole_and_fish: Fishing Level",
            "value": "**LEVEL 16**\n99,528XP total\n47,897XP to next level",
            "inline": true
          },
          {
            "name": ":book: Enchanting Level",
            "value": "**LEVEL 17**\n188,826XP total\n33,599XP to next level",
            "inline": true
          },
          {
            "name": ":alembic: Alchemy Level",
            "value": "**LEVEL 21**\n1,062,931XP total\n159,494XP to next level",
            "inline": true
          },
          {
            "name": ":rabbit2: Taming Level",
            "value": "**LEVEL 18**\n302,700XP total\n19,725XP to next level",
            "inline": true
          },
          {
            "name": ":chair: Carpentry Level",
            "value": "**LEVEL 26**\n4,556,602XP total\n165,823XP to next level",
            "inline": true
          },
          {
            "name": ":yin_yang: Runecrafting Level",
            "value": "LEVEL 24\n185,948XP total\n0XP to next level",
            "inline": true
          }
        ]
      };

       
      
    
        client.channels.cache.get(`477416126561910804`).send({ embed2 })

this is dont work

**Comment by NotSugden** [comment]
use the [discord server](https://discord.gg/bRCvFy9) for these types of issues
