### ISSUE TITLE
channel.setName often takes very long to respond when called under different commands

### ISSUE THREAD

**Issue by HariShyamU** [discordjs/discord.js#4748]
**Issue:**
setName command takes too long to respond after calling it (multiple hours), making it hard to deploy functionalities involving renaming channels on command. It works instantly under some events but not for others

![aa](https://user-images.githubusercontent.com/29952418/91394488-3b6d3400-e858-11ea-9a02-9f1e07181394.png)

The action above was done within reasonable interval, around 10-20 seconds between each command, and the ones which don't work right away, completes the command after couple of hours.

```js
        message.channel.setName('cgbot-verified-'+name)
          .then(channel => {
            channel.send('verified and confirmed.') // This codeblock often takes 20 mins to 2 hours to reach
          })
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.3
- Operating system: windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by tipakA** [comment]
Duplicate of #4327 and #4674

**Comment by HariShyamU** [comment]
> Duplicate of #4327 and #4674

Understood. Closing this issue
