### ISSUE TITLE
CollectorOptions#idle: Sometimes, the Collector stops before time passes.

### ISSUE THREAD

**Issue by RaknaXTR** [discordjs/discord.js#4751]
As I mentioned in the title, sometimes CollectorOptions#idle closes the Collector instantly even if there is a response to.
Code:
```js
<Message>.createReactionCollector(filter, { idle: 10000 })
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.1
- Operating system: CentOS 7

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
"Sometimes" is rather hard to reproduce without clear steps.

If by "if there is a response" you mean a message is sent in the channel the collector is started in: that's not going to delay the idle timeout in this case. We are talking about a __Reaction__Collector here, its idle time accounts for reactions being collected (that pass the filter), not messages being sent to the channel (again, if that is what you mean with "response" here)

**Comment by RaknaXTR** [comment]
Usually after 30th reactions the Collector stops before time passes.
I dont mean message, i mean reaction.

**Comment by almostSouji** [comment]
I can not reproduce this behaviour. Do note that the idle timeout is just reset if the "collect" event emits - meaning the reaction has to pass the provided filter.


```
--- new collector ---
"end" | at 10.008s
```
collector ends after roughly 10s as specified

```
--- new collector ---
"collect" | ♥️ by Souji#0001 at 4.688s
"end" | at 14.694s
--- new collector ---
"collect" | <:yes:581918948803477514> by Souji#0001 at 6.773s
"collect" | ✅ by Souji#0001 at 13.812s
"collect" | <:this:470903994118832130> by Souji#0001 at 23.427s
"collect" | ♥️ by Souji#0001 at 32.585s
"end" | at 42.595s
```
collector is delayed by both custom and standard unicode emoji

```
--- new collector ---
"collect" | ❤️ by Souji#0001 at 4.968s
"collect" | ❤️ by AlsoSouji#4945 at 11.577s
"end" | at 21.582s
```
collector also resets if reaction is not added as new reaction but to an existing "stack of reactions

<details>
<summary>Test code</summary>

```js
const filter = () => true;
const start = Date.now();
const rc = msg.createReactionCollector(filter, { idle: 10000 });
console.log('--- new collector ---');
rc.on('collect', (r, u) => {
	console.log(`"collect" | ${r.emoji} by ${u.tag} at ${(Date.now() - start) / 1000}s`);
});
rc.on('end', () => {
	console.log(`"end" | at ${(Date.now() - start) / 1000}s`);
});
```

</details>


<details>
<summary>a longer example (and i have no reason to believe that this will change at any higher capacity)</summary>

```
--- new collector ---
"collect" | ✅ by Souji#0001 at 6.037s
"collect" | ✅ by AlsoSouji#4945 at 12.106s
"collect" | <:tag:631846293970354186> by AlsoSouji#4945 at 20.644s
"collect" | <:tag:631846293970354186> by Souji#0001 at 27.846s
"collect" | <a:ameowdab:455032619114037249> by Souji#0001 at 31.767s
"collect" | <a:ameowdab:455032619114037249> by AlsoSouji#4945 at 35.866s
"collect" | <:online:401146192135847936> by AlsoSouji#4945 at 40.011s
"collect" | <:online:401146192135847936> by Souji#0001 at 44.592s
"collect" | ❤️ by Souji#0001 at 48.952s
"collect" | ❤️ by AlsoSouji#4945 at 53.58s
"collect" | <:SmartBOYE:341017064661581835> by Souji#0001 at 58.339s
"collect" | <:SmartBOYE:341017064661581835> by AlsoSouji#4945 at 64.187s
"collect" | <:SmartBOYE:341017064661581835> by Souji#0001 at 72.456s
"collect" | <:SmartBOYE:341017064661581835> by Souji#0001 at 82.171s
"collect" | <:SmartBOYE:341017064661581835> by Souji#0001 at 84.729s
"collect" | <:SmartBOYE:341017064661581835> by Souji#0001 at 89.08s
"collect" | <:pg:718954091757437058> by AlsoSouji#4945 at 94.171s
"collect" | ❤️ by AlsoSouji#4945 at 99.335s
"collect" | <:tag:631846293970354186> by AlsoSouji#4945 at 105.121s
"collect" | <:online:401146192135847936> by AlsoSouji#4945 at 109.7s
"collect" | <:online:401146192135847936> by AlsoSouji#4945 at 112.494s
"collect" | ✅ by AlsoSouji#4945 at 118.151s
"collect" | <:tag:631846293970354186> by Souji#0001 at 123.628s
"collect" | 👍 by Souji#0001 at 127.112s
"collect" | <:default:454932831890571264> by Souji#0001 at 131.712s
"end" | at 141.714s
```

</details>

**Comment by arantesxyz** [comment]
It is hard to reproduce, it happens to me sometimes and i have no idea what's causing it.

idk if this is memory issue, a filter issue or something else..
