### ISSUE TITLE
My Discord Bot Shut Down

### ISSUE THREAD

**Issue by K1at3s** [discordjs/discord.js#4759]
My Discord Bot Shuts Down By Itself It opens at 12 am and closes in the evening without error, what's the problem?

discord.js Version: V12.3.1

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
