### ISSUE TITLE
Cant Login into Client

### ISSUE THREAD

**Issue by tayron1** [discordjs/discord.js#4763]
**Please describe the problem you are having in as much detail as possible:**
I just fresh installed Discord.js (Newest Version) and now i'm getting this error everytime:

_http_agent.js:444
      options = req[kRequestOptions];
                   ^

TypeError: Cannot read property 'Symbol(requestOptions)' of undefined
    at Agent.removeSocket (_http_agent.js:444:20)
    at Agent.<anonymous> (_http_agent.js:171:10)
    at Agent.emit (events.js:314:20)
    at TLSSocket.onFree (_http_agent.js:362:11)
    at TLSSocket.emit (events.js:314:20)
    at emitFreeNT (_http_client.js:725:16)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
**Include a reproducible code sample here, if possible:**

```js
client.login(config.token)
```

**Further details:**

- discord.js version: Newest (12.3.1)
- Node.js version: v14.9.0
- Operating system: Debian 
- Priority this issue should have – please be realistic and elaborate if possible: 

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ x] I have also tested the issue on latest master, commit hash: f973163

**Comment by tayron1** [comment]
okay with node v12 it works idk why

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this issue given your, quite small, code sample.

---

However while looking at [the offending line of code](https://github.com/nodejs/node/blob/v14.9.0/lib/_http_agent.js#L444) I spotted another [suspicious line of code](https://github.com/nodejs/node/blob/v14.9.0/lib/_http_agent.js#L438) that likely caused this error.

I was able to reproduce this error after adding any enumerable property to the object prototype (e.g. `Object.prototype.foo = 'bar';`).

---

Please make sure that the reproducible code sample you provide actually reproduces the error.
(Test the provided sample alone, without any other code running)

---

The, probably, solution to this issue: Don't mess with the prototypes of built-ins.
If a dependency of yours does that, it probably should no longer be one.
