### ISSUE TITLE
TypeError: (data.name || this.name).trim is not a function

### ISSUE THREAD

**Issue by NotII** [discordjs/discord.js#4764]
` c.setName(client.guilds.cache.get("749603147814535242").memberCount)`
The above code seems to be setting off this error 
`(node:16920) UnhandledPromiseRejectionWarning: TypeError: (data.name || this.name).trim is not a function
    at VoiceChannel.edit (C:\Users\NotII\IdeaProjects\facade-antinuke\node_modules\discord.js\src\structures\GuildChannel.js:356:40)
    at VoiceChannel.setName (C:\Users\NotII\IdeaProjects\facade-antinuke\node_modules\discord.js\src\structures\GuildChannel.js:386:17)
    at Timeout._onTimeout (C:\Users\NotII\IdeaProjects\facade-antinuke\index.js:83:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Comment by almostSouji** [comment]
Please do not ignore the issue template and provide the information it asks for:

```
<!--
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.
-->

**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

<!--
If this applies to you, please check the respective checkbox: [ ] becomes [x].
You don't have to modify the text to suit your particular situation – if you want to
elaborate, please do so in the description.
While it's not a requirement to test your issue on the master branch, it would make fixing
the problem a lot easier for us, so please do so if possible.
-->

- [ ] I have also tested the issue on latest master, commit hash:

```

**Comment by NotII** [comment]
**Please describe the problem you are having in as much detail as possible:** Setting channel name to just numbers causes a error.
**Include a reproducible code sample here, if possible:** 
`c.setName(client.guilds.cache.get("749603147814535242").memberCount)`
**Further details:**
- discord.js version: 12.3.1
- Node.js version: v12.18.3.
- Operating system: Win10

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Vaporox** [comment]
`GuildChannel#setName()`expects a string as the first argument, but you're passing a number; Those don't have a `.trim()` method, hence the error. Just convert the returned number to a string before using it as a parameter

**Comment by almostSouji** [comment]
Additionally you might encounter other issues with this feature as outlined in #4327
