### ISSUE TITLE
405 Error on Raspbian, but NOT windows

### ISSUE THREAD

**Issue by Sleepingtree** [discordjs/discord.js#4765]
**Please describe the problem you are having in as much detail as possible:**
Getting a 405 error when calling `client.guilds.fetch(${SERVER_SNOWFLAKE});` on Raspbian10, but **not** windows.
attached is the stack trace

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js');
const bot = new Discord.Client();
bot.login(process.env.DISCORD_BOT_KEY);

setInterval(() => checkUsersInDisc(bot), 5000);

function checkUsersInDisc(bot){
    bot.guilds.fetch(process.env.SERVER_SNOWFLAKE_KEY)
       .then(server =>{
        console.log('here');
    });
}
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: v12.18.3
- Operating system: Raspbian GNU/Linux version 10
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none
[405 error.txt](https://github.com/discordjs/discord.js/files/5147511/405.error.txt)

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Can you catch the rejection and log the full error?
Especially the path and the method properties are interesting.

**Comment by Sleepingtree** [comment]
Logged error, here's what I got
`DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/home/pi/nodeDiscord/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'get',
  path: '/guilds?with_counts=true',
  code: 0,
  httpStatus: 405
}
`

**Comment by SpaceEEC** [comment]
This looks like you are passing an empty string, `undefined`, or `null` to the method, try a literal string to eliminate this possibility.

**Comment by Sleepingtree** [comment]
User error, did not have environment variable defined
