### ISSUE TITLE
TypeError: Object.entries(...).filter(...).flatMap is not a function when using Webhook.send

### ISSUE THREAD

**Issue by ciencia** [discordjs/discord.js#4769]
**Please describe the problem you are having in as much detail as possible:**

When using `Webhook.send(string)` ([doc](https://discord.js.org/#/docs/main/stable/class/Webhook?scrollTo=send)) the following error is thrown:

```
TypeError: Object.entries(...).filter(...).flatMap is not a function
    at new APIRequest (/home/jesus/apps/discord/CienciaBot/node_modules/discord.js/src/rest/APIRequest.js:23:10)
    at RESTManager.request (/home/jesus/apps/discord/CienciaBot/node_modules/discord.js/src/rest/RESTManager.js:52:24)
    at Proxy.options (/home/jesus/apps/discord/CienciaBot/node_modules/discord.js/src/rest/APIRouter.js:30:19)
    at Webhook.send (/home/jesus/apps/discord/CienciaBot/node_modules/discord.js/src/structures/Webhook.js:155:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Include a reproducible code sample here, if possible:**

```js
		const messageText = 'Text message';
		channel.fetchWebhooks()
			.then(hooks => {
				const hook = hooks.find(hook => hook.name == "TEST HOOK NAME");
				if (!hook) {
					message.channel.send('Hook does not exist');
					return;
				}
				console.log(`Send message mensaje "${messageText}" to web hook ${hook.id}, with URL ${hook.url}...`);
				hook.send(messageText)
					.then(hook => {
						message.channel.send('Message sent');
					}).catch(error => {
						console.error(error);
						message.channel.send('Error.');
					});
			})
			.catch(error => {
				console.error(error);
				message.channel.send('Error');
			});
```
The line console.log(`Send message mensaje "${messageText}" to web hook ${hook.id}, with URL ${hook.url}...`); is actually executed, and printed in console.

**Further details:**

- discord.js version: discord.js@12.3.1 (downloaded an hour ago)
- Node.js version: v10.16.3
- Operating system: Linux 4.12.14-lp150.12.82-default #1 SMP Tue Nov 12 16:32:38 UTC 2019 (c939e24) x86_64 x86_64 x86_64 GNU/Linux
- Priority this issue should have – N/A

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by vladfrangu** [comment]
Update node, d.js requires at least nodejs v12
