### ISSUE TITLE
.setMessageAttachment()

### ISSUE THREAD

**Issue by Alexander1414x** [discordjs/discord.js#4775]
Hello everoyne.

I send embed  message : 

```
const embed = new Discord.MessageEmbed()
    .setColor("RANDOM")
    .setTitle("Achoo | ")
    .setMessageAttachment('./img/test.png')
```

So it is not working , bot cant with message image.     Example : 
![image](https://user-images.githubusercontent.com/28537900/91931367-ec0d8480-eceb-11ea-82d4-e822180eda7c.png)

Sending  message with + image embed.  How add?

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Alexander1414x** [comment]
@monbrey 
![image](https://user-images.githubusercontent.com/28537900/91931512-5aeadd80-ecec-11ea-906d-3d0bef030e75.png)

I cant unlock it.

**Comment by Alexander1414x** [comment]
But Experimental .

1) `const embed = new MessageAttachment('./img/test.png)`  -working


2)  const embed = new Discord.MessageEmbed()
     .setMessageAttachemnt()  - this is new (future , but still cant working, this is alternative to .attachFile)  -cant working.

Do you maybe future add? 

latest version D.JS

Node later 14.9.0 .

**Comment by almostSouji** [comment]
There is no reason to have an alternative to a well established and working method. You have to send the attachment alongside the embed and reference the attachment from the embed, as explained here <https://discordjs.guide/popular-topics/embeds.html#attaching-images>. If you don't want it to display inside the embed (or it's not an image) you can simply just attach it and omit the referencing inside the embed, of course.

as <https://discordjs.guide/additional-info/changes-in-v12.html#messageembed-attachfiles> explains #attachFile has been merged into #attachFiles, where you can easily provide an array literal with one attachment data structure.
