### ISSUE TITLE
channel#startTyping does not resolve.

### ISSUE THREAD

**Issue by webmail** [discordjs/discord.js#4776]
**Please describe the problem you are having in as much detail as possible:**
`Message#channel#startTyping` does not resolve.

**Include a reproducible code sample here, if possible:**

```js
client.on('message', async message => {
  await message.channel.startTyping();
  console.log('Look, Mom! I resolved!');
  await message.channel.send('Hello, world.');
});
```

**Further details:**

- discord.js version: `discordjs/discord.js#stable`
- Node.js version: **14.6.0**
- Operating system: **Big Sur (20A5354i)**
- Priority this issue should have – please be realistic and elaborate if possible: **Medium**

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by webmail** [comment]
Extra info: I am using [cookiecord/cookiecord](https://github.com/cookiecord/cookiecord), which is using `discordjs/discord.js#stable` under the hood.

**Comment by boon-cpu** [comment]
can reproduce on latest

**Comment by tipakA** [comment]
Quoting Souji from `#library-discussion` channel in the [Discord server](https:discord.gg/bRCvFy9):  
[Message 1](https://canary.discordapp.com/channels/222078108977594368/682166281826598932/746503534324744202)
> The promise will resolve once the typing has ended.  
Awaiting it like this will wait for the typing to end before continuing, consequently never continuing. [...]  

[Message 2](https://canary.discordapp.com/channels/222078108977594368/682166281826598932/746506324023705660)
> If you pass 1 the exact same happens, it stars the typing indicator and the promise resolves when the adequate count (1) of stopTyping has been called [...]  

[Message 3](https://canary.discordapp.com/channels/222078108977594368/682166281826598932/)
> I'm not too sure what you mean there with the count parameter not working?
.startTyping(1) -> .stopTyping() 
.startTyping(2) -> .stopTyping() x2
.startTyping(3) -> .stopTyping() x3
and so on. i tested that up to 5 the other day, could not see any misbehaviour in the counts.

> Discord.js heavily diverges from how typing works api wise, we keep the typing indicator alive as long as not all typing "instances" are resolved (the count is decremented through stopTyping to the point where none are left) and sending a message does not resolve the call, but has to be done manually.

> And as was pointed out above you can't await the start call as is right now, since it resolves only after the typing is fully resolves (has stopped)
