### ISSUE TITLE
Using the ShardManager, if the token is invalid, it will return an error that doesnt describe at all what is happening.

### ISSUE THREAD

**Issue by S0LDR** [discordjs/discord.js#4778]
```
using ShardManager, very basic
```

**Further details:**

Returns an error:
(node:10640) UnhandledPromiseRejectionWarning: #<Response>
Running base index.js (my sharder is in sharder.js) returns invalid token error.

- discord.js version: 12.3.1
- Node.js version: 12.18.2
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: No priority

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
Please provide your code and reproducible (minimal) code sample.

Which location has the wrong token? I tried altering either as well as both locations where a token is usually provided and received the expected ` Error [TOKEN_INVALID]: An invalid token was provided.` or (if i completely mess my code up `rror [TOKEN_MISSING]: Request to use token, but token was unavailable to the client.`)
