### ISSUE TITLE
add "blank" embed bar to ColorResolvable

### ISSUE THREAD

**Issue by asportnoy** [discordjs/discord.js#4783]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
It's hard to remember random hex codes, so when I use an embed with a blank bar (same border color as background), I have to either google the hex, inspect element, or look at some other files.

**Describe the ideal solution**
Add `#2f3136` to `ColorResolvable` since you already have some discord colors (blurple, greyple, etc.) in there

**Describe alternatives you've considered**
Googling the hex, inspecting element, looking at old files. Would be much easier to just remember `BLANK_BAR` or something of the sort.

**Additional context**
https://discord.js.org/#/docs/main/stable/class/ColorResolvable

**Comment by advaith1** [comment]
well whats "blank" in one theme won't be blank in another theme
