### ISSUE TITLE
12.3.0 - Permissions applied when creating a text channel are reset by `channel.setParent`

### ISSUE THREAD

**Issue by roncli** [discordjs/discord.js#4787]
Since PR #4627, permissions applied to a text channel (and possibly other types of channels, have not tested that) on creation are unset by `channel.setParent`.

```js
guild.channels.create("#3q-sc-1874", {type: "text", permissionOverwrites: [
  {id: "468945632380321813", deny: ["VIEW_CHANNEL"]},
  {id: "736016537181225031", allow: ["VIEW_CHANNEL"]},
  {id: "736016540469821562", allow: ["VIEW_CHANNEL"]}
], reason: "3Q challenged SC."});
```

Followed by:

```js
channel.setParent(challengesCategory);
```

Notes:
* 468945632380321813 is my guild's ID.
* 736016537181225031 and 736016540469821562 are two role IDs within the guild.
* Intention is to allow only those two roles to have access to see the channel.
* `challengesCategory` is the category that newly created channels end up in.

Prior to this PR (using `"discord.js": "discordjs/discord.js#bd2bb0e1c7ae150d78d2b6b08cbb86debfef42cf",`) this code worked correctly, adding the permissions to the channel.

After this PR (using `"discord.js": "discordjs/discord.js#599cde3627a19e954caa9a803378c17feaac66fb",`) this code creates the channel and applies the permissions, but then the permissions get immediately reset by the `setParent` method.

**Further details:**

- discord.js version: 12.3.0/12.3.1
- Node.js version: 12.8.3/14.8.0
- Operating system: Windows Server 2012 R2/Windows 10 Enterprise version 2004
- Priority this issue should have – Mid to high - breaks existing functionality

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: 77b6a7d5bd7463f9f397179f5897ec0d00706749

**Comment by almostSouji** [comment]
I can not reproduce this behavior. Tested on 77b6a7d5bd7463f9f397179f5897ec0d00706749 as well as 12.3.1 with node 13.10.0  this exact code applies overwrites to the newly created channel as long as i provide a valid user and role id (for testing purposes i switched those around into any constellation i could think of). 

"Valid" in this context also includes that the role still exists and the users (should they be referenced) needing to be on the server while this is executed. Leaving a server or deleting a role will also remove any overwrites created for the respective target.

I'm not quite sure how the changes to #edit could have any effect on #create either.

**Comment by roncli** [comment]
Aha, your comment about `#edit` led me to the actual source of the problem.  This is part of a script that does a number of things.  I went ahead and dissected that script step by step, and the actual step that *removes* the permissions is the very next step, `channel.setParent`.  Moving the channel to a category is what removes the channel's permissions, even if the category is not setup to override permissions for its child channels.

The channel is landing in the correct category, but the action of moving it to that category is what is resetting the permissions.

Sorry for the confusion!  I can still confirm that the above mentioned PR is the source of the trouble... before that PR this flow worked as expected, and set permissions were not unset by `channel.setParent`.

**Comment by almostSouji** [comment]
I can not find any unexpected behavior with `message.channel.setParent()` either (i used the channels i created before to make sure i have somewhat unique overwrites)

Note that the `options.lockPermissions` flag defaults to `true` (meaning to lock the permissions) [#setParent](https://discord.js.org/#/docs/main/stable/class/GuildChannel?scrollTo=setParent), if you do not want this behavior you have to explicitly set the flag to false. The referenced PR fixed this options not being applied but did not change the intent of this being the default.

It "working" like this for you was indeed a bug the PR fixed.

```js
message.channel.setParent("category_id", {lockPermissions: false})
```

**Comment by roncli** [comment]
Aha, that was it!  Thanks for the clarification, adding the `lockPermission: false` option gave me back the old behavior.

Sorry for the trouble, when I filed the issue I did not even imagine that `setParent` would've been what was triggering it.  Thanks a ton for your help!!
