### ISSUE TITLE
Bot Goes Offline For No Reason

### ISSUE THREAD

**Issue by GeodesicDragon** [discordjs/discord.js#4795]
This is a bit strange, but let me try to explain it as best I can.

I've created my own bot using Discord.JS that I host via a Raspberry Pi 4. I have it on one of my servers, where it listens for a !dl command, at which it provides the user with a download link depending on which channel the command was used in.

The problem began a couple of months ago, when the bot would suddenly go offline for seemingly no reason. At first I thought that maybe my Internet had failed, but a quick check revealed this wasn't the case. Then I heard from someone that apparently a bot gets forced offline if it is inactive for a while, so I set up a small script that would make the bot send a random message to a channel (that only it could access) every ten minutes. What happened there was that the bot would go offline anyway, but the messages would still get sent, meaning I had no idea when it actually went offline.

My attempts to find a solution have failed, as any code I find either no longer works, or is intended to be used with a bot platform that is not Discord.JS.

If anyone can give me some help as to why this keeps happening and how to prevent it, that would be great. I am a complete novice at this whole JavaScript thing, so I am probably doing something obviously wrong, but can't see it.

If you need more information, then let me know.

**Comment by GeodesicDragon** [comment]
Additional Information

I put the bot online after submitting my ticket; it's just gone offline again, with no errors reported in the log. My Internet is working, as I am playing WoW Classic, so that can't be the issue.

I had this code which, I assume, is meant to report any issues to my console, but it didn't work.

`bot.on('shardDisconnect', function (evt, id) {
	console.log('Lost connection: ' + evt + ' (' + id + ')');
});

bot.on('shardError', function (error, shardid) {
	console.log('Connection Error: ' + error + ' (' + shardid + ')');
});

bot.on('shardReady', function (error, unavail) {
	console.log('Connection Ready: ' + id + ' (' + unavail + ')');
});`

Here you can see that the bot is offline (bonus points if you get some of the references in the messages it's been sending):

![GeoBot_Offline](https://user-images.githubusercontent.com/28545521/92304314-d52d9300-ef74-11ea-80f2-948ecf07dae9.jpg)

And here you can see that the console isn't reporting any errors.

![GeoBot_Console](https://user-images.githubusercontent.com/28545521/92304318-d8288380-ef74-11ea-8fd6-da7ae7f38186.jpg)

**Comment by almostSouji** [comment]
The bot is offline but still responds? Then a connection error is quite unlikely if not to say impossible. Can you reproduce this on a fresh boilerplate bot with your token and system setup? Does the debug event log anything unusual (I heavily doubt so, seeing that the bot still responds implying that the websocket connection should be fine)

<details>
<summary>Debug boilerplate proposal</summary>

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log('I am ready!');
});


client.on('message', message => {
  if (message.content === 'ping') {
    message.channel.send('pong');
  }
});

client.on("debug", console.log)
      .on("warn", console.log)

// Log our bot in using the token from https://discordapp.com/developers/applications/me
client.login('your token here');
```

</details>

>  Then I heard from someone that apparently a bot gets forced offline if it is inactive for a while

No, this might be a misunderstanding of the following:
discord re-connects bots (or rather connections) regularly to balance long-lived connections to dynamically scale nodes on their end. <https://discord.com/developers/docs/topics/gateway#reconnect>. This is usually __not__ noticeable (in the form of your bot displaying offline, for example, as is the case here)

**Comment by GeodesicDragon** [comment]
At the time of posting this comment, the debug script was running and the bot was still online; I will post a new comment if and when it goes offline and provide the log.

**Further details:**

- discord.js version: Unsure, don't know how to check.
- Node.js version: 10.21.0 (I know there is a newer version, but my Pi won't update to it for some reason)
- Operating system: Raspberry Pi 4 (Raspian)
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash: N/A

**Comment by almostSouji** [comment]
I can't reproduce this on my end at all, had bots running for days now without being displayed online.

You can try to get the presence data of the bot when this happens (preferably from the API) and see if the status is actually offline or if your user client is screwing up and just displays it as such.

We do no longer maintain v11 (neither new features nor bug fixes), meaning unless you can reproduce this on v12 we will consider it fixed (note that v12 also require node 12.0.0+ to be installed).

**Comment by qwright10** [comment]
My bot just starting doing the same thing. This is the second consecutive day my bot has been going "offline." All I have to do is manually update my bot's status.

**Comment by GeodesicDragon** [comment]
I've got another problem now whereby I get an error message whenever a message is sent in the server, so I'll need to get that fixed before I even attempt to see if I can replicate the problem on v12 (once I update to it).

**Comment by GeodesicDragon** [comment]
I've updated to v12 and fixed the problems I was having; my bot is now online, and I will see if it goes offline again while I am at work. I have `bot.on("warn", console.log)` in the code, so I should be told about any problems that cause the bot to go offline.

**Comment by GeodesicDragon** [comment]
The bot has been online without any issues; it really was just a simple matter of updating a few things.

**Comment by almostSouji** [comment]
I will consider this resolved then, if anyone can reproduce this on stable feel free to re-open, comment or reference in a new issue as you wish.

**Comment by qwright10** [comment]
I'd have to agree, I don't think this is a problem with the library at all.

**Comment by benjamonnguyen** [comment]
@qwright10 Hey! Did you ever figure out conclusively what the problem was? My bot is going offline without logging any errors.

**Comment by diablo** [comment]
@benjamonnguyen The problem happens because you're sending to many requests through the API

It usually originates within the bot's activity, for Example:

    setInterval(function() {
        client.user.setActivity(`${client.users.cache.size} users`)
        })
    
The setInterval statement is calling setActivity every few milliseconds making the API disconnect you. 
   
How to Fix:
    
    setInterval(function() {
        client.user.setActivity(`${client.users.cache.size} users`)
        }, 10000)
        
Add time so it calls the API every few seconds/minutes
