### ISSUE TITLE
Reaction Collector & awaitReactions don't emit collect

### ISSUE THREAD

**Issue by zThana** [discordjs/discord.js#4801]
**Please describe the problem you are having in as much detail as possible:**
Reaction collectors nor awaitReactions collect reactions

**Include a reproducible code sample here, if possible:**

Reaction Collector:
```js
msg.react("➡").then(() => {
    const filter = (reaction, user) => reaction.emoji.name === '➡' && user.id === message.author.id;
    const collector = msg.createReactionCollector(filter, {
        time: 15000
    });
    collector.on('collect', r => console.log(`Collected ${r.emoji.name}`));
    collector.on('end', collected => console.log(`Collected ${collected.size} items`));
});
```

Await Reactions:
```js
message.channel.send("Test test test await reaction").then(async msg => {
    msg.react('➡').then(async () => {
        console.log("1"); // triggers properly

        const filter = (reaction, user) => ['⬅', '➡'].includes(reaction.emoji.name) && user.id === message.author.id;
        msg.awaitReactions(filter, {
            max: 1,
            time: 60000,
            errors: ["time"]
        }).then(reactions => {
            console.log("2");
        }).catch(() => msg.reactions.removeAll());
    });
});
```
Having no filter doesn't change the result.

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.1
- Operating system: Debian 10
- Priority this issue should have: Medium. Doesn't halt development

**Relevant client options:**

- partials: Message, channel, reaction
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master

**Comment by monbrey** [comment]
I couldn't figure this out but just to clarify - enabled Intents in the Developer Portal have no relevance unless you're specifying Intents in your Client constructor (which you aren't).

**Comment by zThana** [comment]
> I couldn't figure this out but just to clarify - enabled Intents in the Developer Portal have no relevance unless you're specifying Intents in your Client constructor (which you aren't).

Updated main post, thank you

**Comment by VoltrexMaster** [comment]
The first one as the `reaction collector` worked for me which i showed in the support server of discord.js, this issue is only related to your filter that the user id you're comparing may not be correct, however it doesn't work on your case so what can i say

**Comment by zThana** [comment]
> The first one as the `reaction collector` worked for me which i showed in the support server of discord.js, this issue is only related to your filter that the user id you're comparing may not be correct, however it doesn't work on your case so what can i say

I turned off the filter and it still didn't appear to work for me. I changed `author.id` to `message.author.id` like you did, despite of `author` being a reference to `message.author` but that also still did not work

**Comment by Jiralite** [comment]
I am unable to reproduce this issue with the same discord.js version and Node.js 12.18.2. I copied and pasted both code samples which worked fine.

If using `() => true` as your filter still didn't work, I assume a file inside of discord.js has been modified by you. Try a fresh installation?

Might also be other modules installed that inteferes with discord.js, but that's a longshot.

**Comment by zThana** [comment]
I copy / pasted both code samples on a fresh installation and it still did not work for me, without any other modules

I did spot something else however, both named ":arrow_right:"
![image](https://user-images.githubusercontent.com/8803519/92341903-7c1e4600-f0bf-11ea-884c-d81cfc1e1a4f.png)

**Comment by zThana** [comment]
> I can not reproduce the issue or spot anything else off when running this exact code sample (both back to back) in the boilerplate code from https://discord.js.org/#/docs/main/stable/examples/ping with only adding a line to ignore the bots answers in order to make it not spam (and credentials logic).
> 
> ![demo](https://user-images.githubusercontent.com/26532370/92362423-46458580-f0f0-11ea-9684-021b4ccf5335.gif)
> 
> The first snippet does react on removing and re-applying the reaction, after all it is the event driven collector acting here, thus 1 and 2 log (both once).
> 
> The second snippet does not react to re-reacting, as is expected. The promise resolves when exactly `max = 1` reactions have passed the filter.
> 
> The code is running on [dfd63bd](https://github.com/discordjs/discord.js/commit/dfd63bdb6b73c39bd071689561f42dce3827fc14) with node.js 13.10.0
> 
> Running code
> ```js
> require('dotenv').config();
> /**
>  * A ping pong bot, whenever you send "ping", it replies "pong".
>  */
> 
> // Import the discord.js module
> const Discord = require('discord.js');
> 
> // Create an instance of a Discord client
> const client = new Discord.Client();
> 
> /**
>  * The ready event is vital, it means that only _after_ this will your bot start reacting to information
>  * received from Discord
>  */
> client.on('ready', () => {
> 	console.log('I am ready!');
> });
> 
> // Create an event listener for messages
> client.on('message', message => {
> 	const msg = message;
> 	if (msg.author.bot) return;
> 	// If the message is "ping"
> 	if (message.content === 'ping') {
> 		msg.react('➡').then(() => {
> 			const filter = (reaction, user) => reaction.emoji.name === '➡' && user.id === message.author.id;
> 			const collector = msg.createReactionCollector(filter, {
> 				time: 15000
> 			});
> 			collector.on('collect', r => console.log(`Collected ${r.emoji.name}`));
> 			collector.on('end', collected => console.log(`Collected ${collected.size} items`));
> 		});
> 	}
> 	// two
> 	message.channel.send('Test test test await reaction').then(async msg => {
> 		msg.react('➡').then(async () => {
> 			console.log('1'); // triggers properly
> 
> 			const filter = (reaction, user) => ['⬅', '➡'].includes(reaction.emoji.name) && user.id === message.author.id;
> 			msg.awaitReactions(filter, {
> 				max: 1,
> 				time: 60000,
> 				errors: ['time']
> 			}).then(reactions => {
> 				console.log('2');
> 			}).catch(() => msg.reactions.removeAll());
> 		});
> 	});
> });
> 
> // Log our bot in using the token from https://discord.com/developers/applications
> client.login(process.env.TOKEN);
> ```

Thank you for your input, something else on my side must for some reason be conflicting then.

**Comment by leo-2323** [comment]
@zThana I ma having same/similar issue as you. The 'collect' is not emitting if the reactor is not the author. I have the same code as you as I got it from the discord.js help docs.

Did you mange to figure this out?

**Comment by zThana** [comment]
@leo-2323 I think I mixed up the msg and message variables. Try respectively renaming them to "message" and "botmessage" to avoid confusion, try it out

**Comment by leo-2323** [comment]
That was quick thanks:

`js
exports.run = async (bot, message, args) => {
  message.channel.send('This is a test message:').then( async msg =>{
    await msg.react('👍');
  const filter = (reaction) => {
    return (reaction.emoji.name === '👍');
  };
  const collector = msg.createReactionCollector(filter, { time: 15000 });
  collector.on('collect', (reaction, user) => {
    console.log(`Collected ${reaction.emoji.name} from ${user.tag}`);
  });
    collector.on('end', collected => {
    console.log(`Collected ${collected.size} items`);
  });
});
};
`

**Comment by almostSouji** [comment]
@leo-2323 Your issue sounds much more like https://github.com/discordjs/discord.js/issues/4980#issuecomment-723519865 - which was not yet the case when this issue was opened.

**Comment by DMNight6** [comment]
Sorry for the necropost, it seems like mine won't work as well.
here is the code:
`exports.run = async({message, args}) => {
    let timeout;
    const options = [`Yes`, `No`];
    const msg_channel = client.channels.cache.get(config.channels.votes);
    var main_text = '';
    
    const defEmojiID = [
        config.emojis.yes,
        config.emojis.no,
    ];

    const emojiList = [];

    for (const emName of defEmojiID) {
        const emoji = client.emojis.cache.get(emName)
        emojiList.push(emoji)
    }

    const emojiInfo = {};

    for (const option of options) {
        const emoji = emojiList.splice(0, 1);
        emojiInfo[emoji] = {option: option, votes: 0};
        main_text += `${emoji} : \`${option}\`\n\n`;
    };
    
    
    const afterEmojiList = Object.keys(emojiInfo);

    const poll = await msg_channel.send(embed(`BLUE`, `${args[1]}`, `${main_text}`));
    for(const emojis of afterEmojiList) await poll.react(emojis);

    const reactionCollector = await poll.createReactionCollector(
        (reaction, user) => afterEmojiList.includes(reaction.emoji.name) && !user.bot,
        timeout === 0 ? {} : {time: args[0] * 10000}
    );

    const voterInfo = new Map();

    reactionCollector.on('collect', (reaction, user) => {
        if (afterEmojiList.includes(reaction.emoji.name)) {
            if (!voterInfo.has(user.id)) voterInfo.set(user.id, {emoji: reaction.emoji.name});
            const votedEmoji = voterInfo.get(user.id).emoji;
            if (votedEmoji !== reaction.emoji.name) {
                const lastVote = poll.reactions.get(votedEmoji);
                lastVote.count -= 1;
                lastVote.users.remove(user.id);
                emojiInfo[votedEmoji].votes -= 1;
                voterInfo.set(user.id, {emoji: reaction.emoji.name});
            }
            emojiInfo[reaction.emoji.name].votes += 1;
        }
    });

    reactionCollector.on('dispose', (reaction, user) => {
		if (afterEmojiList.includes(reaction.emoji.name)) {
			voterInfo.delete(user.id);
			emojiInfo[reaction.emoji.name].votes -= 1;
		}
	});

    reactionCollector.on('end', async () => {
		var end_text = `Time's up for [this vote](${poll.url})!\n Results are in,\n\n`
		for (const emoji in emojiInfo) end_text += `\`${emojiInfo[emoji].option}\` - \`${emojiInfo[emoji].votes}\`\n\n`;
        await poll.reply(embed(`YELLOW`, `Vote Ended`, `${end_text}`));
	});
}`
