### ISSUE TITLE
The ChannelManager.fetch() method does not return an object of type Channel.

### ISSUE THREAD

**Issue by cristianireyes** [discordjs/discord.js#4803]
Hi!

I am testing discord.js to interact on my server with my bot.
When wanting to recover a channel and use the characteristics of typescript, I realized that the return type in the .fetch method of the ChannelManager object is wrong.
The [official documentation](https://discord.js.org/#/docs/main/stable/class/ChannelManager?scrollTo=fetch) indicates that it returns an object of type **Channel**, but it is not what really happens.    
![no return channel](https://user-images.githubusercontent.com/34529231/92550561-24541c00-f232-11ea-85cf-44c0df5a0f0a.png)

This error prevents us from declaring the type of object received and then accessing its properties.

The following type declaration returns a typescript error:
```
// Fetch a channel by its id
const channel: TextChannel = await this.discordClient.channels.fetch('CHANNEL_ID');
```
![error_typescript](https://user-images.githubusercontent.com/34529231/92550568-261ddf80-f232-11ea-9a13-d64f647b1284.png)
![error_props](https://user-images.githubusercontent.com/34529231/92550572-274f0c80-f232-11ea-9f33-ba4eb1db262f.png)

Changing the return type would fix this error?
https://github.com/discordjs/discord.js/blob/56e8ef2d38633154540748acb64f4c1305fcc6d3/src/managers/ChannelManager.js#L78

Thanks!

**Comment by monbrey** [comment]
`Channel` is the common ancestor of all types which can be fetched using that method. However tighter inference of types is not possible due to some quirks in the way the classes are written.

To use this with TS you'll need to force typecasting with `as TextChannel` or similar.

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.

**Comment by cristianireyes** [comment]
> If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
> https://discord.gg/bRCvFy9
> This issue tracker is only for bug reports and enhancement suggestions.

I posted here because I thought it was a mistake.
