### ISSUE TITLE
When Using Channel.overidePermissions, Permissions not Changing

### ISSUE THREAD

**Issue by kidsonfilms-python-rules** [discordjs/discord.js#4804]
**Please describe the problem you are having in as much detail as possible:**
When I try to override the `Channel` Permissions, it does not change the permissions (checking through [Discord](discord.com)) with no error in the console.

**Include a reproducible code sample here, if possible:**

```js
var ticketChannel = message.guild.channels.create(name, 'text').then((c) => {
ticketChannel = client.channels.cache.find(channel => channel.name === name)
ticketChannel.overwritePermissions(message.guild.roles.cache.find('name', '@everyone'), {
     'VIEW_CHANNEL': false
})
ticketChannel.overwritePermissions(message.guild.cache.roles.find('name', 'Moderator'), {
     'VIEW_CHANNEL': true
})
ticketChannel.overwritePermissions(message.author.id, { 'VIEW_CHANNEL': true, 'SEND_MESSAGES': true, 'MENTION_EVERYONE': false })
```

**Further details:**

- discord.js version: **^12.3.1**
- Node.js version: **v12.18.3**
- Operating system: **Windows 10**
- The priority this issue should have – please be realistic and elaborate if possible:
This is for a ticket system so, it is a high priority for the feature.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on the latest master, commit hash:

**Comment by monbrey** [comment]
That would throw an error in console as you're using the method incorrectly (it changed in v12).

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
