### ISSUE TITLE
this.client.guilds.map is not a function 

### ISSUE THREAD

**Issue by jahs000** [discordjs/discord.js#4808]
Creating bot bans file...
Creating command logs file...
(node:3064) UnhandledPromiseRejectionWarning: TypeError: this.client.guilds.map
is not a function
    at module.exports.run (C:\Users\PC\Desktop\bot\events\ready.js
47:24)

**Comment by almostSouji** [comment]
<https://discordjs.guide/additional-info/changes-in-v12.html#managers-cache>

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
