### ISSUE TITLE
Attachment after embed edit dont work

### ISSUE THREAD

**Issue by E2Ghibli** [discordjs/discord.js#4810]
Here is my probleme i send a new embed and after some time i edit it to a new embed white attachment but the attachment dont work. I test it white a new embed and attachment it works but if i use .edit(embed) and have .attachFiles(attachment) in it it dont work

**Comment by iCrawl** [comment]
This doesn’t work for the same reason as editing a normal message and trying to attach a file doesn’t work.

Discord doesn’t allow edits to contain files after being posted.
