### ISSUE TITLE
How can i update to discord.js V12

### ISSUE THREAD

**Issue by qw1324** [discordjs/discord.js#4811]
how can i update to discrod.js V12

**Comment by NotSugden** [comment]
you can see the [v12 changes](https://discordjs.guide/additional-info/changes-in-v12.html?v=12) section of the guide to see the changes in v12, or to actually install v12 you can use `npm update discord.js` to update the existing module if you're still on v11

**Comment by qw1324** [comment]
> first off: this is not a feature request, read the damn buttons you press man!
> 
> 
> 
> you can see the [v12 changes](https://discordjs.guide/additional-info/changes-in-v12.html?v=12) section of the guide to see the changes in v12, or to actually install v12 you can use `npm update discord.js` to update the existing module if you're still on v11
> 
> 
> 
> In future, use the [discord server](https://discord.gg/bRCvFy9) for these types of questions

thx
