### ISSUE TITLE
Unable to run the whole Discord.js module on Firefox-like browsers due to a small regex issue!

### ISSUE THREAD

**Issue by iMrDJAi** [discordjs/discord.js#4815]
Regex lookbehind is a new standard, and not fully supported by all browsers yet, these lines need some quick edits:
https://github.com/discordjs/discord.js/blob/01ceda5b0cd6a14a49862a91b14c714bca4898a9/src/util/Util.js#L129
https://github.com/discordjs/discord.js/blob/01ceda5b0cd6a14a49862a91b14c714bca4898a9/src/util/Util.js#L168
https://github.com/discordjs/discord.js/blob/01ceda5b0cd6a14a49862a91b14c714bca4898a9/src/util/Util.js#L178
https://github.com/discordjs/discord.js/blob/01ceda5b0cd6a14a49862a91b14c714bca4898a9/src/util/Util.js#L183
Keep in mind that this small issue causes the inability to use the whole djs module on Firefox-like browsers, that's a mess!

**Comment by almostSouji** [comment]
duplicate of https://github.com/discordjs/discord.js/issues/3932
