### ISSUE TITLE
Documentation inconsistencies for methods involving files

### ISSUE THREAD

**Issue by Fyko** [discordjs/discord.js#4819]
**Please describe the problem you are having in as much detail as possible:**

I've noticed an inconsistency regarding the documentation for methods that involve setting or updating files or images. For example, the `avatar` option of [`Webhook#edit`](https://discord.js.org/#/docs/main/stable/class/Webhook?scrollTo=edit) is documented as `BufferResolvable` where the `banner` parameter of [`Guild#setBanner`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=setBanner) is documented as ` Base64Resolvable|BufferResolvable`. Is there a reason for the varying documenting for these methods? I'd like some input before I PR a fix for this.

**Comment by NotSugden** [comment]
from what i can tell by looking at the typings, `Base64Resolvable` is used in the case said attachment is an image of some kind, whereas BufferResolvable is used where it can be just any attachment

https://github.com/discordjs/discord.js/blob/56e8ef2d38633154540748acb64f4c1305fcc6d3/typings/index.d.ts#L562-L564
https://github.com/discordjs/discord.js/blob/56e8ef2d38633154540748acb64f4c1305fcc6d3/typings/index.d.ts#L246

aswell as the description for the `Base64Resolvable` type says
> typically for image uploading
