### ISSUE TITLE
More friendly Typescript with send()

### ISSUE THREAD

**Issue by c0ncentus** [discordjs/discord.js#4820]
hi,

I really love tyspescript, but with discord for sending message : is Hell

cannot send message with discord
![image](https://user-images.githubusercontent.com/25374826/93130611-10496800-f6d3-11ea-9233-3e352380a7bd.png)

typescript with discord is not up to date ?

**Comment by kyranet** [comment]
Duplicate of #4746. You can reach us on the Discord guild for further support.
