### ISSUE TITLE
Some channels that extend GuildChannel improperly inherit setTopic

### ISSUE THREAD

**Issue by zaida04** [discordjs/discord.js#4831]
VoiceChannels, CategoryChannels, and other channels that extend GuildChannel inherit the setTopic method, which isn't right because topic related things only exists on TextChannel and NewsChannel. 

A solution would be to just remove it from GuildChannel and put it only on TextChannel, and since NewsChannel inherits from TextChannel, it would inherit the method.

Links: 
https://discord.js.org/#/docs/main/master/class/CategoryChannel?scrollTo=setTopic
https://discord.js.org/#/docs/main/master/class/VoiceChannel?scrollTo=setTopic
https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=setTopic

**Comment by ImRodry** [comment]
This bug is still present to this day and I think it should be fixed before v13 is out. A good way to fix this and future issues would be to create a BaseGuildTextChannel that would hold all the common properties of TextChannel and NewsChannel to hopefully also fix the issue with rateLimitPerUser

**Comment by iCrawl** [comment]
PRs welcome.

**Comment by monbrey** [comment]
As I said in the linked issue, there's a lot more to it than just `setTopic`. If you do want to restructure the channel inheritance, there's probably other methods to look at too like createInvite.

**Comment by ImRodry** [comment]
I was thinking of making a PR but not with the BaseGuildTextChannel class since I'm not entirely sure how to handle that and may end up breaking stuff so I just wanted to move things to the right place. Do you think it's worth making a PR just to do this or should we wait for someone more experienced with the library to do the full restructure?
