### ISSUE TITLE
Blank page on Safari and Chrome on MacOS

### ISSUE THREAD

**Issue by Quimy** [discordjs/discord.js#4847]
**Please describe the problem you are having in as much detail as possible:**

Hello,

We use this library in Vue app. We build our app with Webpack and it is only client side SPA. We have problem with MacOS related browsers. The problem was that it was showing blank page and throwing javascript errors. There were 2 problems:

- catch syntax error - missing parenthesis ()
https://github.com/discordjs/discord.js/blob/1e63f3756e814d6b1a2a9c17af9c2b28ce37e472/src/client/websocket/handlers/index.js#L7-L11

- incorrect regex in multiple places, but in the same file:
https://github.com/discordjs/discord.js/blob/1e63f3756e814d6b1a2a9c17af9c2b28ce37e472/src/util/Util.js#L128-L141

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.3
- Operating system: MacOS
- Priority this issue should have – please be realistic and elaborate if possible: Moderate - possibly this library doesn't work in major browsers on MacOS and mobile

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
You are supposed to use the webpacked version we provide and not build your own from the node_modules.

Additionally, yes Safari might actually not work well with those Regex, neither does Firefox really because of an implementation bug on their end.

**Comment by Quimy** [comment]
I didn't build anything. I just installed it like any other npm package.

It's well known bug. Shouldn't library be prepared for this? I'm sure there are ways to implement this without using such regex. And what about catch problem, this seems to be a bug in code.

**Comment by iCrawl** [comment]
Again, your webpack configuration builds whatever you import, this is not how you use this library in the browser. Use the provided browser builds on the `webpack` branch.

The catch binding is not a bug, ES2019 supports that syntax which is what we operate on here with Node 12+ but is also not an issue on the builds we have on the `webpack` branch.

**Comment by Quimy** [comment]
Okey, so I should use that build and ignore that it will not work on Safari due to regex?

**Comment by iCrawl** [comment]
Latest: Web builds won't be continued and are discouraged by discord itself.
