### ISSUE TITLE
Issue with getting user avatar url

### ISSUE THREAD

**Issue by wajwuz** [discordjs/discord.js#4850]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to get link of user avatar and on the end it has ".0" on the end

![Code_2020-09-25_21-40-03](https://user-images.githubusercontent.com/51962721/94309029-b751bd80-ff77-11ea-9c01-fae6a3a44e7c.png)

**Include a reproducible code sample here, if possible:**

```js
app.get("/user/:id", async (req, res) => {
    try {
        const user = await client.users.fetch(req.params.id);
        res.send(`${user.username}#${user.discriminator}
        <br>
        <img src="${user.displayAvatarURL({ dynamic: true, format: 'webp' | 'png' | 'jpg' | 'jpeg' | 'gif', size: 128 })}" width="128" height="128">`); // causes .0 format 
        console.log(`${user.displayAvatarURL({ dynamic: true})}`) // displaying as .webp
    } catch {
        res.send("Unknown user specified, check user id and try again.");
    };
});
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.4
- Operating system: Windows 10 (2004, Build 19041.508)
- Priority this issue should have – please be realistic and elaborate if possible: emmm, low?

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash

**Comment by HarmoGlace** [comment]
Can you send us the exact link it returns ? (btw your format option will always return webp)

**Comment by wajwuz** [comment]
nvm fixed
