### ISSUE TITLE
bot.user.setPresence not changing status

### ISSUE THREAD

**Issue by LostAndDead** [discordjs/discord.js#4853]
**Please describe the problem you are having in as much detail as possible:**
Setting the bots status and activity doesn't work, the activity updates but the status does not. It is not timed or client caching of status as it never updates even after a few hours

```js
bot.user.setPresence({
    status: "dnd",
    activity: {
      name: "To Music As I Go To Sleep. (◡ ꒳ ◡)",
      type: "LISTENING"
    }
  });
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.12.0
- Operating system: AWS EC2 (idk what exactly)
- Priority this issue should have – Its really annoying me but not like its breaking my life apart:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by LostAndDead** [comment]
Addition: i have 2 bots running into the same client, one does verification only, doesnt touch the bots status or anything, it just needs to be online more to avoid losing peoples codes, its separate so it doesn't have to keep restarting while im working on the main commands bot. so this might not be a bug, but any workaround for this?

**Comment by iCrawl** [comment]
Yes. Have only one bot run on that token.

**Comment by aydonlol** [comment]
late but use .setActivity

**Comment by almostSouji** [comment]
Not only late but also wrong and not the solution to the issue.
`.setActivity` wraps `.setPresence` and has the exact same issue if used as detailed above.

**Comment by aydonlol** [comment]
> Not only late but also wrong and not the solution to the issue. `.setActivity` wraps `.setPresence` and has the exact same issue if used as detailed above.

It didn't work for me using setPrescence and did using setActivity, you might be right but I don't know it fixed my issue
