### ISSUE TITLE
Couldn't load the documentation data.  TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by BotTest298** [discordjs/discord.js#4859]
When i go to https://discord.js.org/#/docs/main/stable/general/welcome, it shows an error that says:https://discord.js.org/#/docs/main/stable/general/welcome. I'm not sure what's causing it, but everything was working yesterday. I don't think its my PC/software, but I'm not sure.

**Comment by almostSouji** [comment]
duplicate of #4860
