### ISSUE TITLE
dispatcher.pause seams to destroy insted of pause

### ISSUE THREAD

**Issue by Pomdre** [discordjs/discord.js#4862]
dispatcher.pause seams to destroy insted of pause the voice. 

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.16.1
- Operating system: Windows 10 home 1903
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [X] I have also tested the issue on latest master.

**Comment by amishshah** [comment]
Can you provide some more info? E.g. example code, a more detailed description of the issue, why exactly you think it is being destroyed

**Comment by Pomdre** [comment]
Sorry was a mistake on my part.
Thanks!
