### ISSUE TITLE
StreamDispatcher#setVolume is acting weird

### ISSUE THREAD

**Issue by North-West-Wind** [discordjs/discord.js#4864]
**Please describe the problem you are having in as much detail as possible:**
I had a code which use `request-stream` to get an mp3 file online. After getting the stream, I concat it with a silence audio file with `concat-stream` and put it into `VoiceConnection#play` with options `{ type: "unknown", highWaterMark: 1 << 25 }`. However, when I tried to use `StreamDispatcher#setVolume` **while the music is playing**, the volume didn't change at all. I then tried removing the options and things work perfectly. No idea what was going on.

(I know it is unnecessary to get a stream of the file since we can just put an URL into `VoiceConnection#play`, but I need it to manipulate the stream)

**Include a reproducible code sample here, if possible:**

The following code failed:

```js
const requestStream = url => {
  return new Promise((resolve, reject) => {
    request(url, (err, res) => err ? reject(err) : resolve(res));
  });
};
const StreamConcat = require('stream-concat');
try {
  var requestedStream = await requestStream(song.url);
  var silence = await requestStream("https://raw.githubusercontent.com/anars/blank-audio/master/1-second-of-silence.mp3");
  var stream = new StreamConcat([silence, requestedStream], { highWaterMark: 1 << 25 });
} catch (err) {
  console.error(err);
  return await skip();
}
dispatcher = connection.play(stream, { type: "unknown", highWaterMark: 1 << 25 });
dispatcher.setVolume(0.5);
// Volume didn't change
```

The following code succeeded:

```js
const requestStream = url => {
  return new Promise((resolve, reject) => {
    request(url, (err, res) => err ? reject(err) : resolve(res));
  });
};
const StreamConcat = require('stream-concat');
try {
  var requestedStream = await requestStream(song.url);
  var silence = await requestStream("https://raw.githubusercontent.com/anars/blank-audio/master/1-second-of-silence.mp3");
  var stream = new StreamConcat([silence, requestedStream], { highWaterMark: 1 << 25 });
} catch (err) {
  console.error(err);
  return await skip();
}
dispatcher = connection.play(stream);
dispatcher.setVolume(0.5);
// Volume changed
```

**Further details:**

- discord.js version: `master`
- Node.js version: `12.18.4`
- Operating system: `Heroku-18`

**Comment by amishshah** [comment]
By setting such a large watermark, you could be loading a large amount of the stream into memory with the default volume, at which point the volume cannot be changed.

See https://discordjs.guide/voice/optimisation-and-troubleshooting.html#using-highwatermark
