### ISSUE TITLE
Add `VoiceState.setMuteDeaf` function

### ISSUE THREAD

**Issue by jftanner** [discordjs/discord.js#4865]
**Is your feature request related to a problem? Please describe.**
The `VoiceState.setMute()` and `VoiceState.setDeaf()` functions have to be called separately, requiring two requests against the rate-limit if trying to mute and deafen a user.

**Describe the ideal solution**
Since they use the same API call, a combined `setMuteDeaf` function would allow both changes to be made in the same request, thus making more efficient use of the rate limit.

**Describe alternatives you've considered**
My current approach is to check the voice state of users before hand, and only make the request when required:
```Node.js
        const { voice } = await this._guildMember.fetch();

        // Don't waste rate limits on duplicate requests.
        const requests = [];
        if (voice.serverMute !== mute) requests.push(voice.setMute(mute, finalReason));
        if (voice.serverDeaf !== deaf) requests.push(voice.setDeaf(deaf, finalReason));
        await Promise.all(requests)
```

However, this doesn't help in cases where both updates are required.

**Additional context**
I would be more than happy to attempt a pull-request for this feature, if desired.

**Comment by Vaporox** [comment]
You can make use of a GuildMember's edit method, i.e. `<GuildMember>.edit({ mute: true, deaf: true })` to edit both properties at once. I personally wouldn't be in favor of another helper method.

**Comment by jftanner** [comment]
Closing, along with #4866
