### ISSUE TITLE
CategoryChannel#parentID is sometimes undefined

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#4868]
**Please describe the problem you are having in as much detail as possible:**
The `.parentID` property of a category is sometimes `undefined`, but it should always be `null`.

I tested in all guilds my bot was in and I was surprised to see a mixture of `undefined` and `null` values.

**Include a reproducible code sample here, if possible:**

```JavaScript
const client = new (require("discord.js").Client)();

client.on("ready", () => {
  const results = [];

  client.guilds.cache.forEach(({ channels: { cache } }) => {
    results.push(cache.filter(({ type }) => type === "category").map(({ parentID }) => parentID));
  });

  console.log(results);
});

client.login("token");
```
`results` resulted as:
```JavaScript
[
  [ undefined, undefined, undefined ],
  [ undefined, undefined ],
  [
    null, null, null,
    null, null, null,
    null, null, null
  ],
  [
    null,      undefined,
    undefined, null,
    undefined, null,
    undefined, null
  ],
  [ undefined, undefined, null ],
  [ undefined, undefined ],
  [ null, null, null, null, null ],
  [ null, null ],
  [ undefined, undefined ]
]
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.10.0
- Operating system: macOS 10.15.6
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:** N/A

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: d234165

**Comment by almostSouji** [comment]
seems to be yet another case of https://github.com/discordjs/discord.js/pull/4593 | https://github.com/discordjs/discord.js/pull/4706
where discord simply doesn't send fields at all instead of as null values
