### ISSUE TITLE
Can't use `client.users.fetch()` => 404

### ISSUE THREAD

**Issue by thetayloredman** [discordjs/discord.js#4871]
**Please describe the problem you are having in as much detail as possible:** `404 Not Found` when trying to fetch all users. When you use `client.users.fetch()`, you get back a `Promise<rejected>` in my case.

**Include a reproducible code sample here, if possible:**

```js
client.users.fetch().then(() => {
  // do something
}).catch(console.log);
```

<details>

<summary>Full log</summary>

```
[INFO 01/09/2020 19:30:20] Loading command test
(node:934) UnhandledPromiseRejectionWarning: DiscordAPIError: 404: Not Found
    at RequestHandler.execute (/home/runner/dnsbot/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Further details:**

- discord.js version: latest
- Node.js version: `v12.18.2`
- Operating system: macOS Catalina 10.15.2
- Priority this issue should have – please be realistic and elaborate if possible: moderate, prevents fetching users

**Relevant client options:**

- partials: none
- gateway intents: all
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by anandre** [comment]
You *cannot* fetch all users, there is no method to do so.  You need to provide an ID to fetch a single User.  Your result is not a bug, it is expected behavior.

**Comment by thetayloredman** [comment]
Oh, sorry, I'll use `GuildMemberManager#fetch()` then

**Comment by advaith1** [comment]
would probably be good to throw an error though? instead of sending an invalid request to Discord

**Comment by monbrey** [comment]
> 
> 
> would probably be good to throw an error though? instead of sending an invalid request to Discord

50/50 on this, any non-valid user ID is also an invalid request to Discord. The documentation shows that it's a required parameter though.
