### ISSUE TITLE
Document the available events

### ISSUE THREAD

**Issue by fjeddy** [discordjs/discord.js#4873]
Where would I find a list of events I can listen too on Discord.js? No condecending replies please, I did google, I did look at Discord.js documentation, it's not my faulth everything is so incredibly poorly structured.

**Comment by Fyko** [comment]
> it's not my faulth everything is so incredibly poorly structured.  

The events can be viewed in the "Events" column here: https://discord.js.org/#/docs/main/master/class/Client

For future reference, this issue tracker is primarily for bugs and suggestions. Please bring general functionality questions to the Discord server linked in the README.
