### ISSUE TITLE
GuildAuditLogsEntry contains wrong target

### ISSUE THREAD

**Issue by ACertainCoder** [discordjs/discord.js#4878]
**Please describe the problem you are having in as much detail as possible:**
I'm currently updating to Discord.js v12 and tried recreating my previous logging system. It's purpose is to give moderators the ability to read deleted messages and see which user actually deleted it.
The targetType of the GuildAuditLogsEntry is correct ("MESSAGE"), but the actual target ais a user (the one that deleted it), not the message itself.
I checked the extras too but there was only the channel it was sent in.
You can find some screenshots of my debugging proccess down below.

Breakpoint (I checked the content within "logentry":
![2020-10-01_23-07-14](https://user-images.githubusercontent.com/47316898/94923596-66345300-04bc-11eb-860b-20e3cb1e0bd7.png)

All entries:
![2020-10-01_23-07-45](https://user-images.githubusercontent.com/47316898/94923760-aabfee80-04bc-11eb-8f09-45341b3d9a67.png)

First entry:
![2020-10-01_23-07-42](https://user-images.githubusercontent.com/47316898/94923784-b4e1ed00-04bc-11eb-8883-34af0b1e7695.png)

First entry target (last part of it) and it's targetType:
![2020-10-01_23-07-38](https://user-images.githubusercontent.com/47316898/94923792-b9a6a100-04bc-11eb-89c7-29b7e3dc8c6b.png)

**Include a reproducible code sample here, if possible:**
I simplified my code from above a bit to make it better usable.

```js
client.on('messageDelete', async msg => {
    //Check if it isn't alright to execute the event
    if(msg.author.bot) return;

    //Check if the message was on the own server
    if(msg.guild.id == 'OWN_SERVER_ID') {
        //Get the log channel
        var logchannel = msg.guild.channels.cache.get('LOG_CHANNEL_ID');
        //Search for a matching audit log entry
        var logentries = (await msg.guild.fetchAuditLogs({type: 'MESSAGE_DELETE', limit: 10})).entries;
        var logentry = logentries.size > 0 ? logentries.find(entry => entry.target.id == msg.id) : null;

        //Send a log embed
        var embed = new Discord.MessageEmbed()
        .setAuthor(`${msg.author.username} - Message deleted`, msg.author.displayAvatarURL({format: 'png', dynamic: true}))
        .setDescription(`${msg.channel} - ${msg.id}`)
        .addField('Content', msg.content.length > 1000 ? `${msg.content.slice(0, 1000)}\n...` : msg.content)
        .addField('Deleted by', logentry ? logentry.executor : 'Unknown');//This will always be unknown becaus the entry couldn't be found
        await logchannel.send(embed);
    }
});
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.4
- Operating system: Windows 10 Pro 2004
- Priority this issue should have – please be realistic and elaborate if possible: normal

**Relevant client options:**

- partials: none
- gateway intents: Presence, Server Members (I have them for other stuff enabled)
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
We can only pass on information which discord provides. A message deletion log does not include the message body or even message id. Below is a raw audit log entry as fetched with a raw API call. Both `user_id` (author) as well as `target_id` (executor) are user ids, `id` is the audit logs id, `channel_id` the channel id the message was deleted from.

```js
{
  id: '763013134453178398',
  user_id: '83886770768314368',
  target_id: '175179625880616960',
  action_type: 72,
  options: { channel_id: '345507437865861130', count: '1' }
}
```

> GuildAuditLogsEntry contains wrong target

Is accordingly a misconception on your end.
