### ISSUE TITLE
Discord.JS sharding with dashboard

### ISSUE THREAD

**Issue by AktilaCengiz** [discordjs/discord.js#4885]
Hello to everyone! I have a bot and I have to start the bot as shard but my bot has a dashboard and we cannot run it with the shard I wonder if there is no event like ready event in shardingManager? Where can ı load dashboard. if ı put ready.js dashboard file get a error "adress already used." it is basic error because website working on many shard.

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by AktilaCengiz** [comment]
Since I couldn't find the necessary answer when I go to the Discord server, I would like to reiterate the problem here. How can I get a client from manager or shardManager? I want to leave a sample shard.js at the bottom:

`const ayarlar = require("./Settings/settings.json")

const { ShardingManager } = require('discord.js');
const manager = new ShardingManager('./index.js', { token:  ayarlar.token });


manager.on("shardCreate", shard => {
    shard.on("ready", async() => {
        const client = blalababal

        client.website = require("./website/dashboard")

        await client.website.load(client)

        console.log(`[TheFunt/Venosa] Shard ${shard.id + 1 } Başarı ile bağlandı.`)
    })

})

manager.spawn(5);`

**Comment by kyranet** [comment]
As @monbrey said, the issue tracker is for bug reports and enhancement suggestions. What you're showing here looks like a question, please move to the [Discord server](https://discord.gg/bRCvFy9) for further help.
