### ISSUE TITLE
messageDelete: user

### ISSUE THREAD

**Issue by PN-Cryptid** [discordjs/discord.js#4891]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

[event:messageDelete](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-messageDeletel)
The client messageDelete Event does not provide a user/member who deleted the message. This is an alternative route to establishing that variable.

**Describe the ideal solution**
Using the audit logs and two stored variables, it is still possible to determine if the deletion was by the author or a guild moderator. The two variables required to be stored would be a member's most recent messageDelete audit log entry ID, as well as the count for that audit log entry.

This method should be worked into the library, if there is no better alternative.

**Describe alternatives you've considered**
The API does not offer any other solid solutions.

**Below is the code I've used to verify that a message has been deleted by someone other than the author.**
The variable "jsonMemoryObject" represents the currently functioning JSON object that is stored in a local file.

https://hatebin.com/kmngajqeiw

**Comment by almostSouji** [comment]
We can only implement the features discord offers. The question about "who" did something always relies heavily on audit logs. Discord simply does not provide the action executor in the MESSAGE_DELETE payload <https://discord.com/developers/docs/topics/gateway#message-delete>.

Since there is no "audit log creation" event discord sends I'm not too sure how your solution is supposed to work. Fetching audit logs whenever something happens and risking to thread into permission errors is not feasibly to do for the library.

**Comment by PN-Cryptid** [comment]
> We can only implement the features discord offers. The question about "who" did something always relies heavily on audit logs. Discord simply does not provide the action executor in the MESSAGE_DELETE payload https://discord.com/developers/docs/topics/gateway#message-delete.
> 
> Since there is no "audit log creation" event discord sends I'm not too sure how your solution is supposed to work. Fetching audit logs whenever something happens and risking to thread into permission errors is not feasibly to do for the library.'
> 
> We explain a [best effort approach to finding out who deleted a message on our guide](https://discordjs.guide/popular-topics/audit-logs.html#who-deleted-a-message). However this does have some caveats which generally come with audit logs and are also listed there.

You store variables for a person's most recent audit log entry ID (for message deletion), and the count for it.

If the most recent log is for a message deletion, the deletion target's ID is the same as the messageDelete author's ID, and the audit log is either a new ID for that member OR the count has increased for that audit log, you know with certainty that the executor mentioned in the audit log is the person who deleted this message. Otherwise, the user is the author.

**Comment by almostSouji** [comment]
> You store variables for a person's most recent audit log entry ID (for message deletion), and the count for it.
Audit log information is not accessible without specifically fetching it. And if you are specifically fetching it caching random information just for one use case is not really feasible to do on a library level either.

Enhanced tracking mechanisms like this should be implemented by the developer, not the library.
