### ISSUE TITLE
Sometimes bot doesn't triger when someone changes their name

### ISSUE THREAD

**Issue by DuBeAl** [discordjs/discord.js#4892]
https://youtu.be/KIO_3e0BcVw

**client.on('guildMemberUpdate', (oldMember, newMember) => {
  if(newMember.nickname && oldMember.nickname !== newMember.nickname) {
    const channel = newMember.guild.channels.cache.get('706601933066076190');
channel.send(`++ ${newMember}`);
      }
});**

**Comment by IDjinn** [comment]
It's ok, if you clear nickname, it trigger nickname as null. You've checking nonnull new nickname...

**Comment by IDjinn** [comment]
Well, if you clear member nickname, it trigger nickname as null. You've checking nonnull new nickname...

**Comment by DuBeAl** [comment]
if you check 0:23 you can see a new nickname (Yunusisyan)

**Comment by IDjinn** [comment]
Your bot doesn't send any message in this time 🤔 it's just discord app update view

**Comment by IDjinn** [comment]
Every nickname update all mentions update

**Comment by DuBeAl** [comment]
Doesnt mention the user as seen in the video
