### ISSUE TITLE
channel.send does not exist in typescript

### ISSUE THREAD

**Issue by ELI7VH** [discordjs/discord.js#4893]
the typing seems off for `channel.send` 

```
  const testChannel = bot.channels.cache.get(DISCORD_TEST_CHANNEL_ID)
  testChannel.send('WTFF')
```

![image](https://user-images.githubusercontent.com/11658002/95142586-4194e100-0731-11eb-85d0-6033514dd975.png)

**Comment by monbrey** [comment]
Channels retrieved from cache need to be cast to `TextChannel`.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by ELI7VH** [comment]
@monbrey can this code not be updated to just return `TextChannel` from .cache.get()? 

I'm confused why this issue is closed. 

hard casting types is not typescript.

**Comment by kyranet** [comment]
From the same `.cache.get()` you can also get `VoiceChannel` and `CategoryChannel`, both of which have no `send` method.

**Comment by ELI7VH** [comment]
from what i see in the code, it's all done from a specific concern, thus the typing (or casting if need be) should take place within that concern.

unless i'm misreading the code.

**Comment by monbrey** [comment]
I don't know what you mean by "concern" but no, previous attempts to use implied/dynamic typing for channels in these Collections were not successful. It is unlikely to be possible until the TypeScript rewrite version reaches stability.

**Comment by ELI7VH** [comment]
ty for the follow up. I appreciate it
