### ISSUE TITLE
bot crashes with uncatchable error from members.fetch

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#4896]
**Please describe the problem you are having in as much detail as possible:**
When running `message.guild.members.fetch({ user: [] })` with an invalid snowflake like `a`
ex `message.guild.members.fetch({ user: ['a', '1'] })` it seems to crash the node process without any errors. Even a catch doesn't handle it since there's no error thrown. Then after exactly 120 seconds the bot makes a successful connection to the gateway in which it then throws the error but the node process is still in a crashed state in which the bot never fully reconnected. I do use PM2 so pm2 is configured to restart a crashed node process. Though the process isn't fully crashed. The only thing that's emitted in the console is from the Shard reconnect event right when the bot goes offline.

You can view the video I recorded of it happening here https://streamable.com/f3y0mm once you reach the 11 second mark you can skip the video to the 2 minute mark, everything between that is just untrimmed video of it showing it's still offline. But at the 2:11 mark you can see the bot throws the error but is still offline.

With the debug logs enabled this is all that's emitted
```
[2020-10-08 17:03:12] [WS => Shard 0] [INVALID SESSION] Resumable: false.
[2020-10-08 17:03:12] [SHARD RECONNECTING] Shard 0
```

**Include a reproducible code sample here, if possible:**

```js
message.guild.members.fetch({ user: ['a', '1'] })
```

**Further details:**

- discord.js version: master
- Node.js version: v14.12.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: medium-high.  Medium since you shouldn't be providing invalid snowflakes anyways and high since it causes a crash/delay that has no way of handling it.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: d234165

**Comment by russellmwolf** [comment]
I am running into a similar issue as well, just set up a new simple Discord Bot and installed the latest Discord.js in a new project. I'm just trying to fetch a list of all users in a Server (guild):

```js
const Discord = require('discord.js')

const client = new Discord.Client()
client.login(process.env.DISCORD_BOT_TOKEN)

const server = await client.guilds.fetch(process.env.DISCORD_SERVER_ID)
const members = await server.members.fetch()
```

Results in an error message of:

```
Cannot read property 'send' of undefined
```

Referencing `src/managers/GuildMemberManager.js:276:24`, which is calling 

```js
this.guild.shard.send
```

And of course `this.guild.shard` is `undefined`.

**Comment by AryaveerSR** [comment]
Looks Legit

**Comment by Murgator** [comment]
discord.js is a totally buggy library I stopped using it there are too many concerns and the community does not have the skills.

**Comment by TeeSeal** [comment]
I did some debugging.

The main problem here is that the Shard does not reconnect upon receiving opcode 9 (`INVALID_SESSION`).

- https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketShard.js#L421
- https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketManager.js#L237

I'll look into fixing that.

As for the reason why we receive opcode 9: no idea.
When opcode 8 (`REQUEST_GUILD_MEMBERS`) is sent with invalid user_ids, the gateway hangs for about 3 seconds, after which invalid session is sent. I'm assuming this is because this edge-case is not handled on Discord's end and it kind of explodes. During those 3 seconds the shard cannot send other messages to the gateway because of our queue mechanism. And since the `INVALID_SESSION` pretty much resets the shard, any packets that were queued during those 3 seconds are lost.

I did some poking around and noticed that this only happens when the sent user_ids are not snowflakes. If they are snowflakes but not belonging to users the gateway responds just fine. So I guess the solution here would be to make sure that the sent user_ids are valid snowflakes. I'm not sure what class would be best to delegate that responsibility to, but I think we could patch the BaseManager and make `resolveID` enforce snowflake format for strings. The way string are handled currently is kind of meh: https://github.com/discordjs/discord.js/blob/master/src/managers/BaseManager.js#L72

**Comment by TeeSeal** [comment]
@BannerBomb it seems while my PR was open Discord managed to fix this on their end. Fetching members/users with non-numeric IDs is now handled correctly on their end and should, in turn, fix your situation. Please confirm that you no longer see the described behavior.

**Comment by BannerBomb** [comment]
@TeeSeal I updated my bot today but am still noticing the same issue.
![image](https://user-images.githubusercontent.com/11788894/97367792-20cb3180-1880-11eb-8f78-fd5638966695.png)

The bot still goes offline and doesn't come back online. Still sends the timed out message after 120 seconds while offline, and debug event is still printing
```
[2020-10-27 22:00:48] [WS => Shard 0] [INVALID SESSION] Resumable: false.
[2020-10-27 22:00:48] [SHARD RECONNECTING] Shard 0
```

At the time of writing this my specs are now
Partials: None
Intents: None
Other: None
Node.js: v14.14.0
Discord.js: 12.4.1 [master] (Branch Commit: 7ec0bd9)
Operating system:
Main OS: Ubuntu 18.04.3 LTS
OS in docker (where the node process is): Debian GNU/Linux 9 (stretch)

Did they fix it for the api version that discordjs is using currently or did they perhaps just fix it on v8?

**Comment by TeeSeal** [comment]
🤔 That's weird, I tested today and didn't see the same behavior.

**Comment by BannerBomb** [comment]
If it helps this is my client options.
```js
const client = new Client({
	autoReconnect: true,
	retryLimit: 10,
	disableEveryone: true,
	disabledEvents: [
		'CHANNEL_PINS_UPDATE'
	],
	fetchAllMembers: true,
	presence: {
		activity: {
			name: '...Powering up',
			type: 0
		}
	},
	restTimeOffset: 0
});
```

**Comment by BannerBomb** [comment]
To get more information, I did some testing on a completely new stock bot environment and I am still getting the issue. The code I used is provided below.

```js
const { Client } = require('discord.js');

const client = new Client({
	autoReconnect: true
});

client.on('message', async(message) => {
	if (message.guild) {
		if (message.content === 'r!test') {
			console.log('one'); // this is printed
			await message.guild.members.fetch({ user: ['a'] }).catch((error) => {
				console.error(error);
			}); // this is thrown after 120 seconds
			console.log('two'); // this is printed after 120 seconds (after the members timed out error is thrown)
		} else if (message.content === 'r!ping') {
			await message.channel.send('PONG!');
		}
	}
});

client.once('ready', () => {
	console.log('BOT READY!!!!!!!!!!');
});

client.on('debug', (debug) => {
	console.log(debug);
});

client.on('error', (code) => {
	console.error(code);
});

process.on('exit', (code) => {
	console.log(code);
});

process.on('uncaughtException', (error) => {
	console.error(error);
});

process.on('unhandledRejection', (error) => {
	console.error(error);
});

client.login('...');
```

Without filtering the debug logs, the client crashes but is still sending heartbeats then 120 seconds later the members timed out error is thrown.

debug logs show
```ts
Provided token: ***************************.***************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 955
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 6
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 141ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1
[WS => Shard 0] [READY] Session ***************************.
[WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
BOT READY!!!!!!!!!!
[WS => Shard 0] Heartbeat acknowledged, latency of 399ms.
one
[WS => Shard 0] [INVALID SESSION] Resumable: false.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 39ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 45ms.
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /mnt/c/Users/Admin/Desktop/testbpt/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16
    at Timeout._onTimeout (/mnt/c/Users/Admin/Desktop/testbpt/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
}
two
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 30ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 31ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 30ms.
```
while the client is offline it's still sending heartbeats but not reconnecting. Without PM2 being used the client didn't reconnect at all. Even with `autoReconnect: true` specified.

While trying your PR branch on the stock code the bot did reconnect automatically but it still throws the members timed out error after 120 seconds also. If I use the `autoReconnect: true` client option with this branch the bot does go offline then reconnects, but if I don't provide the option it re-connects without going offline. But either way the error isn't thrown until 120 seconds after it crashed.

**Comment by TeeSeal** [comment]
@BannerBomb, understood. I might have used the wrong branch when testing myself. Now I'm getting the same behavior you do, without any changes.

If you try my PR branch now it should prevent the client from getting an invalid session completely. Though, the changes are a bit out of place tbh so we're a bit skeptical about them. The main problem lies with the Discord gateway, which explodes upon receiving a non-numeric ID when fetching members/users. =/

**Comment by BannerBomb** [comment]
@TeeSeal No problem, I have just tested the pr branch and can confirm the issue is fixed with it.

**Comment by zimmermanw84** [comment]
Running v12.4.1 on Windows 10 every time I run `await guild.members.fetch()` I get the same error as above.
```Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.```

For additional context, I've been using `guild.members.cache.map...` to locate channel users. However, I removed and readded my bot from a channel a few times to test a different feature. After readding my `guild.members.cache` on has 2 members. I went down the path of `members.fetch()` to refresh the cache but I am getting this timeout now :/

**Comment by Extroonie** [comment]
Seems like an intents issue, see the guide regarding [gateway intents](https://discordjs.guide/popular-topics/intents.html).

**Comment by CypElf** [comment]
Same issue here. Members didn't arrive in time when fetching members.

**Comment by TeeSeal** [comment]
Members not arriving in time is not what this issue is about. Please stop posting about this here. As @Extroonie mentioned you're most likely having an intents issue.

**Comment by BannerBomb** [comment]
I am commenting to provide an update on this issue since the last update was ~5 months ago and since then the gateway version has changed for the master branch. Just so users won't say that it is an issue with intents, it's still reproducible with intents. The result still results in, After making the fetch request the client instantly goes offline, then after 120 seconds throws the error and finished executing the code under the fetch method (in my example code it prints the word `two` to the console after the error is thrown while the client stays offline (I am not using any process managers while testing), the client also continues to send heartbeats while the error is waiting to be thrown and after the error is thrown.

```ts
[3/15/2021, 7:03:57 PM] Preparing to connect to the gateway...
[3/15/2021, 7:03:57 PM] [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[3/15/2021, 7:03:57 PM] [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 997
[3/15/2021, 7:03:57 PM] [WS => Manager] Spawning shards: 0
[3/15/2021, 7:03:57 PM] [WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 8
    Encoding   : json
    Compression: none
[3/15/2021, 7:03:57 PM] [WS => Shard 0] Setting a HELLO timeout for 20s.
[3/15/2021, 7:03:58 PM] [WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=8&encoding=json in 129ms
[3/15/2021, 7:03:58 PM] [WS => Shard 0] Clearing the HELLO timeout.
[3/15/2021, 7:03:58 PM] [WS => Shard 0] Setting a heartbeat interval for 41250ms.
[3/15/2021, 7:03:58 PM] [WS => Shard 0] [IDENTIFY] Shard 0/1
[3/15/2021, 7:03:58 PM] [WS => Shard 0] [READY] Session ********************************.
[3/15/2021, 7:03:58 PM] [WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[3/15/2021, 7:03:58 PM] [WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[3/15/2021, 7:03:58 PM] BOT READY!!!!!!!!!!
[3/15/2021, 7:03:58 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 35ms.
[3/15/2021, 7:04:04 PM] one
[3/15/2021, 7:04:08 PM] [WS => Shard 0] [INVALID SESSION] Resumable: false.
[3/15/2021, 7:04:39 PM] [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[3/15/2021, 7:04:39 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 32ms.
[3/15/2021, 7:05:20 PM] [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[3/15/2021, 7:05:20 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 43ms.
[3/15/2021, 7:06:01 PM] [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[3/15/2021, 7:06:01 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 37ms.
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /mnt/c/Users/Admin/Desktop/testbot/node_modules/discord.js/src/managers/GuildMemberManager.js:318:16
    at Timeout._onTimeout (/mnt/c/Users/Admin/Desktop/testbot/node_modules/discord.js/src/client/BaseClient.js:82:7)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
}
[3/15/2021, 7:06:04 PM] two
[3/15/2021, 7:06:43 PM] [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[3/15/2021, 7:06:43 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 75ms.
[3/15/2021, 7:07:24 PM] [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[3/15/2021, 7:07:24 PM] [WS => Shard 0] Heartbeat acknowledged, latency of 37ms.
```

Note: I used the same code that I listed here https://github.com/discordjs/discord.js/issues/4896#issuecomment-717628426 to test again except with the intents option being present.

My specs as of this update are.
Partials: None
Intents: `GUILDS`, `GUILD_MEMBERS`, `GUILD_MESSAGES`
Other: None
Node.js: v15.7.0
Discord.js: 12.5.0 [master] (Branch Commit: d744e51)
Operating system: Ubuntu18.04.3 LTS

**Comment by kyranet** [comment]
IMHO this is basically user error - we require users to always pass `Snowflake`s (numeric strings) to the entire library, and since `members.fetch` relies on on WS, it's a lot harder for errors to be caught.

If you want this error to not persist, we recommend you validate your user input, specially since Discord can restrict your bot's access to the API if it gets too many errors in a brief period of time.
