### ISSUE TITLE
DiscordjsError: Request to use token, but token was unavailable to the client.

### ISSUE THREAD

**Issue by kaplego-fr** [discordjs/discord.js#4899]
Hello, when I execute a command with my Discord Bot, I have this error : `DiscordjsError: Request to use token, but token was unavailable to the client.`

There is my code :
```
const Discord = require('discord.js');

const client = new Discord.Client();

module.exports = {
    name: 'idée',
    execute(message, args) {
      const embed = new Discord.MessageEmbed()
        .setAuthor('Idée', message.guild.icon_url)
        .setDescription(args)
        .setFooter(message.author.tag, message.author.avatarURL())
        .setColor('#121640');
      client.channels.fetch('CHANNEL_ID')
        .then(channel => channel.send(embed));
    }
};
```

Can you please help me ?

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
