### ISSUE TITLE
Crosspost method suggestion

### ISSUE THREAD

**Issue by SerenModz21** [discordjs/discord.js#4900]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
No. This is a feature request to suggest something

**Describe the ideal solution**
It would be cool if Message#crosspost() or something like that to publish a message in a new channel.

The Discord API docs link:
https://discord.com/developers/docs/resources/channel#crosspost-message

Its a POST request with Authorization of `Bot <theBotsToken>` and the URL for this is:
https://discord.com/api/v7/channels/CHANNEL_ID/messages/MESSAGE_ID/crosspost

where the API URL and version has come from ClientOptions#http

**Describe alternatives you've considered**
The main one would be Message#crosspost() but there could also be NewsChannel#crosspost(messageId) or anything that the developers could come up with

**Additional context**
Here is an image of me using the eval command to try this feature to see if it worked or not using a post request to the API
![image](https://user-images.githubusercontent.com/41450647/95692727-cb581900-0c1f-11eb-959f-7f4ae90d5125.png)

**Comment by monbrey** [comment]
#4105 has been merged and will be in the next release of discord.js

**Comment by SerenModz21** [comment]
> #4105 has been merged and will be in the next release of discord.js

Thank you!
