### ISSUE TITLE
oldGuild.iconUrl is not a function when server is deleted

### ISSUE THREAD

**Issue by codeWorth** [discordjs/discord.js#4901]
When I listen to the `guildUpdate`  event, and a guild is deleted, the `guildUpdate` event is triggered. Once it's triggered, the functions `oldGuild.iconUrl` and `newGuild.iconUrl` result in a "not a function" error. Both `newGuild.available` and `oldGuild.available` are true.

```js
client.on("guildUpdate", (oldGuild, newGuild) => {
    oldGuild.iconUrl();
}
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.13.1
- Operating system: Ubuntu 20.04.1
- Priority this issue should have – please be realistic and elaborate if possible: Low, guilds are rarely deleted

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by monbrey** [comment]
Correct, it isn't a function. JavasScript is case-sensitive and the method is `<Guild>.iconURL()`

**Comment by codeWorth** [comment]
@monbrey Oops. However, why is this event being triggered at all? I feel that only `guildDelete` should be triggered

**Comment by monbrey** [comment]
We can't control which events Discord emits.

Again, **the issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by codeWorth** [comment]
I was unaware that discord.js was merely forwarding the events that Discord emits, my bad. Thanks for your help
