### ISSUE TITLE
Coding beginner - bot won't respond to trigger?

### ISSUE THREAD

**Issue by fidelefauna** [discordjs/discord.js#4905]
**Hi there, I feel quite bad asking for help with this as I am a skiddie (apparently that's what it's called when you have absolutely no idea what you're doing) and I have found several sources for different parts of this code. My brother and I have been trying to put together our own code for a project I have been working on for my best friend, just a simple Discord bot that responds to a trigger word in any part of a sentence. However, his coding knowledge is limited and mine is non-existent. The code I have shown below seems to run as the online message appears in PowerShell, but the bot does not repond to the trigger word, likely because I have made several errors in my code. We thought that we did have it up and running not long ago with very similar code, but we realised that the bot was responding to every message that was being sent rather than only to messages with the specific trigger word. Any help whatsoever would be greatly appreciated, but I would appreciate it if you could offer some explanation as to what I am doing so wrong as I would like to get better at this in the future. I have done my best to understand all of the keywords that I have come across and I would like to understand them further. Thank you for taking a look and be as harsh as you'd like!**

```js
const Token = "Token";
const Discord = require("discord.js");
const myBot = new Discord.Client();
const botResponses = ["Reply 1", "Reply 2", "Reply 3", "and so on"];

myBot.on('ready', function () {
    console.log(`I am online!`);
});

myBot.on('message', function (message) {
	
    if (message.author.bot) return;
	
    var args = message.content.includes == ("Trigger" || "trigger");
	
    switch (args[0]) {
        case (message.content.includes == ("Trigger" || "trigger")) :
            var response =botResponses [Math.floor(Math.random()*botResponses.length)];

            message.channel.send(response).then().catch(console.error);
			
            break;
        default:
            break;
    }
});

myBot.login("Token").then().catch(`Error logging in: ${console.error}`);

```

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
