### ISSUE TITLE
The `finish` event is not mentioned in the StreamDispatcher events

### ISSUE THREAD

**Issue by A1-exe** [discordjs/discord.js#4908]
**Please describe the problem you are having in as much detail as possible:**
I have spent hours trying to figure out how to detect when the audio play has finished.. It is not mentioned anywhere in the documentation. It looks like you guys changed from `end` to `finish` and forgot to update the documentation for it.

**Further details:**
Can you guys add this to the documentation?

- discord.js version: 6.9.0
- Node.js version: 12.4.0

- [X] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment]
discord.js version... 6? are you sure that's right? that's really old

**Comment by A1-exe** [comment]
> discord.js version... 6? are you sure that's right? that's really old

I think I was looking at the wrong package, but my report is based on the documenation website.

**Comment by JMTK** [comment]
It was removed I believe since it inherits from Stream now:
https://nodejs.org/api/stream.html#stream_event_finish

**Comment by A1-exe** [comment]
Considering it is the only way to detect when the play stream ends, I think it is important to include in the discordjs documentation.

**Comment by almostSouji** [comment]
Inheritance from base Node or JS structures is not documented explicitly but through the inheritance chain, as is the case for Client#on, Client#once etc. <https://discord.js.org/#/docs/main/12.3.1/class/StreamDispatcher>

![image](https://user-images.githubusercontent.com/26532370/96248121-5f710a00-0fab-11eb-8371-b305c1e5b59b.png)

If we want to include this it'd need to happen on a larger scale, where then the question is where we end. Which methods are important enough to document them on discord.js? Which are just clutter for the user? At this point it becomes unfeasible to document everything, but making the call as to what is important enough to be shown is majorly opinionated. 

Looking at the base parent classes to see which methods they offer is standard procedure for development in basically any language. We have also listed the change on [the v12 update guide](https://discordjs.guide/additional-info/changes-in-v12.html#streamdispatcher-end).
