### ISSUE TITLE
Joining a voicechannel resets some of the client attributes

### ISSUE THREAD

**Issue by JasperSurmont** [discordjs/discord.js#4913]
As a part of my music bot, I included the different queues of different Guilds as an attribute of the client (client.queues). 
At first my code looked like this:

```js
if (!message.guild.voice || message.guild.voice.channelID == null) {
      message.client.queues[message.guild.id].push(args[0]);
      const connection = await voiceChannel.join();
      play(connection, message);
} 

function play(connection, message) {
  const id = message.guild.id;
  const client = message.client;
  const song = client.queues[id].shift();

  ...
}
```
The line `song = client.queues[id].shift()` gave an error because the queue was empty, even though I just added the song. After debugging I found out that, whenever the client connects to a voiceChannel, the attribute queues changed. The weird thing is that queues still had all the guildID's as keys, but the values were empty arrays. I'm not sure if this behavior is as expected, but it seems really weird and wrong to me.

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.13.1
- Operating system: Win 10
- Priority this issue should have: not high

**Relevant client options:**
- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by monbrey** [comment]
I don't really understand why you believe this is a discord.js bug.

`client.queues` is a completely custom implementation of your own, not something discord.js would manipulate internally.

**Comment by almostSouji** [comment]
Since `client.queues` seems to be a custom implementation asking on the discord server as the label suggests is not really applicable here.
