### ISSUE TITLE
Sometimes bot doesnt triger when anybody change nickname

### ISSUE THREAD

**Issue by DuBeAl** [discordjs/discord.js#4924]
client.on('guildMemberUpdate', async (oldMember, newMember) => {
    if(oldMember.guild.remove && newMember.guild.add) return;
    let onlem = oldMember.displayName == newMember.displayName
    const kanal = client.channels.cache.get('706601933066076190');
if (!onlem) { kanal.send(`**ID:** \`${newMember.user.id}\`**İsim Değiştiren:** <@${newMember.user.id}>`) }
}); 

https://www.youtube.com/watch?v=XFv9fFnSlhw&feature=youtu.be

bot tagged saitsarp but didnt tag furkanuskanus
and sometimes mention irrelevant people like the first person I checked his logs

**Comment by almostSouji** [comment]
`<Guild>.remove` will never be truthy, the first return will trigger. No idea what you are trying to achieve with this line either.

**Comment by DuBeAl** [comment]
I know, there is no software problem here. The code is working well. I tested I tried it on 2 different servers(1100 people and 130.000 people). It is working well on first server but it did not work on second server like video

**Comment by manuel-di-iorio** [comment]
This is the same issue as https://github.com/discordjs/discord.js/issues/4959. 
Please refer to this https://support-dev.discord.com/hc/en-us/articles/360056426994

**Comment by almostSouji** [comment]
No it is not, this was posted __before__ the cache change applied.

**Comment by SpaceEEC** [comment]
Could this maybe be related to #4986? I am not too sure what exactly is happening in the video, but if the member for which the event is not being emitted is uncached, that would seem plausible.

**Comment by FomaFomitch** [comment]
> Could this maybe be related to #4986? I am not too sure what exactly is happening in the video, but if the member for which the event is not being emitted is uncached, that would seem plausible.

I think I have an issue with the cache. Works just fine 2months ago, now there is no update when a user react to my message unless he "speak" on the channel. How to uncache a user?
