### ISSUE TITLE
The guildMemberRemove event is not thrown when there is no GUILD_PRESENCES indents.

### ISSUE THREAD

**Issue by CatsMiaow** [discordjs/discord.js#4925]
- Node.js v12.19.0
- discord.js v12.4.0

**cause**
When the `GUILD_PRESENCES(PRESENCE_UPDATE)` indents is not set on the client

**situation**
1. When a member enters the guild, the `GUILD_MEMBER_ADD` event occurs, caches the member and passes the event to the client.
https://github.com/discordjs/discord.js/blob/250c3ae3c1f025c092383e4661bbb386e89a3c23/src/client/websocket/handlers/GUILD_MEMBER_ADD.js#L8-L9
2. When a member leaves the guild, the `GUILD_MEMBER_REMOVE` event occurs, and if there is a cached member, the event is passed to the client.
https://github.com/discordjs/discord.js/blob/250c3ae3c1f025c092383e4661bbb386e89a3c23/src/client/actions/GuildMemberRemove.js#L12-L14

**problem**
If a member enters the guild and leaves the guild while the bot is running, the `guildMemberRemove` event will work normally.
However, after the bot is rebooted and the cache is initialized, if an existing member leaves the guild, the `guildMemberRemove` event does not come over.
This seems to be a problem because there is no `PRESENCE_UPDATE` event, so existing members are not cached.

djs discord server tells me to set GUILD_MEMBER partial, which is unnecessary because it affects the entire source and only the `guildMemberRemove` event has problems.

The `GUILD_MEMBER_REMOVE` event is actually occurring regardless of the cache and the data below is passed.
```js
{
  guild_id: 'xxxx',
  user: {
    avatar: null,
    discriminator: '1234',
    id: 'xxxx',
    public_flags: 0,
    username: 'test'
  }
}
```
If there is no `GUILD_PRESENCES` indents, how about passing some data to the `guildMemberRemove` event of the client without checking the cache when the `GUILD_MEMBER_REMOVE` event occurs.

**Comment by monbrey** [comment]
To clarify this issue, have you enabled the `GUILD_MEMBER` partial and re-tested this? Because the functionality you describe
> how about passing some data to the guildMemberRemove event of the client without checking the cache
is exactly what Partials are for

**Comment by CatsMiaow** [comment]
Yes, if enable the `GUILD_MEMBER` partial, can receive the `guildMemberRemove` event.

When the `GUILD_MEMBER` partial is set, the member is cached with data from the `GUILD_MEMBER_REMOVE` event.
https://github.com/discordjs/discord.js/blob/eeb4c1475493c1cde00eb6128f2d0cf8159fbea2/src/client/actions/GuildMemberRemove.js#L12
https://github.com/discordjs/discord.js/blob/250c3ae3c1f025c092383e4661bbb386e89a3c23/src/client/actions/Action.js#L26-L32

I had to write code to check partial when they were `GUILD_MEMBER` partial enabled, so I wanted to know how to receive events while disabled the partial.
```ts
if (message.member?.partial) {
  // message.member.fetch();
}
```

**Comment by monbrey** [comment]
Thanks for confirming - this is the intended behaviour then. The same applies to other "removal" events like `messageReactionRemove` and `messageDelete`. Partials for those must be enabled for events to be received on uncached entities.

**Comment by CatsMiaow** [comment]
Thanks for the explanation.
I created an issue because the `guildMemberRemove` event doesn't work consistently depending on the indents setting.
This is the intended behavior, so let's enable the partial.
