### ISSUE TITLE
Handling global discord rate limits across shards and servers

### ISSUE THREAD

**Issue by AppEternal** [discordjs/discord.js#4926]
**Please describe the problem you are having in as much detail as possible:**
I've been running into problems using discord.js when it comes to Discords global rate messages per second limit.
From what I can tell d.js doesn't handle these global limits across shards, resulting in my other shards spamming discords with 429 rate limit errors, and if the shards are active enough to have 10k events in that time we get a 1 hour CF ban where the bot will then spam discord with dozens of `429 /gateway/bot` errors until this is fixed.

1. How should the global rate limits be handled across shards? (And across servers if global limits are not per IP)
2. How do I prevent the shards from spamming discord with `429 /gateway/bot` if multiple servers are connecting at the same time after a discord outage? Sometimes this will spam about 30+ `429 /gateway/bot` per second and count towards the 10k limit.. and often hits this..

**Further details:**

- discord.js version:
- Node.js version:14.3.0
- Operating system: Unbuntu
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
There are already lots of open issues for this, if you have useful insights please contribute to those threads instead of spreading the discussion further:

<https://github.com/discordjs/discord.js/search?q=429&type=issues>
