### ISSUE TITLE
I'm trying to change the status of my bot to idle, but it doesn't work, when I see client.user.presence, the status appears as idle, but there is another

### ISSUE THREAD

**Issue by aff1mars** [discordjs/discord.js#4938]
```js
client.user.setPresence({ status: 'idle' });
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: the last
- Operating system: linux

**Comment by NotchedDeveloper** [comment]
Does
```js
client.user.setStatus('idle');
```
work for you? (Also, are you running a sharded client?)

**Comment by almostSouji** [comment]
> Does
> 
> ```js
> client.user.setStatus('idle');
> ```
> 
> work for you? (Also, are you running a sharded client?)


This will just call #setPresence with a subset, the behavior will accordingly be the exact same.

If the API accepts and propagates the status it might take some time for the status to be displayed by the viewing client. If you changed status or activity (subsets of presence) quite a lot recently this might also indicate that you are being rate limited and should not send presence updates as regularly as you do.

Also note that running multiple bots on the same token with conflicting presences is not a supported use case of the presence API and can (and reportedly will) result in unexpected behavior.

I can not reproduce this behavior with consideration of above caveats.
