### ISSUE TITLE
GuildMemberManager#cache only includes author and bot

### ISSUE THREAD

**Issue by axpdc** [discordjs/discord.js#4940]
**Please describe the problem you are having in as much detail as possible:**
When I use GuildMemberManager#cache, it only returns a collection with 2 values: the author of the message and the bot.

**Include a reproducible code sample here, if possible:**

```js
const Discord = require("discord.js");
const bot = new Discord.Client();

bot.once("ready", () => {
  console.log("Bot is online!");
});

bot.on("message", (msg) => {
  console.log(msg.guild.members.cache);
});

bot.login("token");
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.19.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment]
you need to enable intents in the dev portal - read https://s.advaith.io/intents 

you need the members intent to fetch all members
note that if you want to get all members in the server, you need to use `msg.guild.members.fetch()`

you can enable the presence intent to get an initial member list without fetching, but note that then the list will not include offline members with no roles (and that code wouldn't have worked for those members before anyway)
