### ISSUE TITLE
Status Error and broken counting because of it and problem with owner displaying on other server unless mine

### ISSUE THREAD

**Issue by AkumaKitty** [discordjs/discord.js#4942]
Today morning everything was okay. When I restarted my bot to apply changes the status  always show Offline no matter someone change it on server. I didn't change status displaying code so this shouldn't be problem with my code:

My UserInfo Command Code:

const Discord = require('discord.js')
const moment = require('moment')
module.exports.run = (client,message, args) => {
    let user = message.mentions.users.first() || message.author;
    
    if (user.presence.status === "dnd") user.presence.status = "Do Not Disturb";
    if (user.presence.status === "idle") user.presence.status = "Idle";
    if (user.presence.status === "offline") user.presence.status = "Offline";
    if (user.presence.status === "online") user.presence.status = "Online";
    
    function game() {
      let game;
      if (user.presence.activities.length >= 1) game = `${user.presence.activities[0].type} ${user.presence.activities[0].name}`;
      else if (user.presence.activities.length < 1) game = "None"; 
      return game;
    }
    
    let x = Date.now() - user.createdAt;
    let y = Date.now() - message.guild.members.cache.get(user.id).joinedAt;
    let created = Math.floor(x / 86400000); // 5 digits-zero.
    let joined = Math.floor(y / 86400000);
    
    const member = message.guild.member(user);
    let nickname = member.nickname !== undefined && member.nickname !== null ? member.nickname : "None";
    let createdate = moment.utc(user.createdAt).format("dddd, MMMM Do YYYY, HH:mm:ss");
    let joindate = moment.utc(member.joinedAt).format("dddd, MMMM Do YYYY, HH:mm:ss");
    let status = user.presence.status
    let avatar = user.avatarURL({size: 2048});
    
    const embed = new Discord.MessageEmbed()
    .setAuthor(user.tag, avatar)
    .setThumbnail(avatar)
    .setTimestamp()
    .setColor('RAMDOM')
    .addField("ID", user.id, true)
    .addField("Nickname", nickname, true)
    .addField("Created Account Date", `${createdate} \nsince ${created} day(s) ago`, true)
    .addField("Joined Guild Date", `${joindate} \nsince ${joined} day(s) ago`, true)
    .addField("Status", status, true)
    .addField("Game", game(), true)
    
    message.channel.send(embed);
    }
module.exports.help = {
            name: "userinfo",
        }

My ServerInfo Command Code

const Discord = require('discord.js')
const dateformat = require('dateformat')
module.exports.run = (client, message, args) => {
    let icon = message.guild.iconURL({size: 2048}); // Server Avatar
    
    let region = {
      "brazil": "Brazil",
      "eu-central": "Central Europe",
      "singapore": "Singapore",
      "london": "London",
      "russia": "Russia",
      "japan": "Japan",
      "hongkong": "Hongkong",
      "sydney": "Sydney",
      "us-central": "U.S. Central",
      "us-east": "U.S. East",
      "us-south": "U.S. South",
      "us-west": "U.S. West",
      "eu-west": "Western Europe"
    }
    
    // Members
    let member = message.guild.members;
    let offline = member.cache.filter(m => m.user.presence.status === "offline").size,
        online = member.cache.filter(m => m.user.presence.status === "online").size,
        idle = member.cache.filter(m => m.user.presence.status === "idle").size,
        dnd = member.cache.filter(m => m.user.presence.status === "dnd").size,
        robot = member.cache.filter(m => m.user.bot).size,
        total = message.guild.memberCount;
    
    // Channels
    let channels = message.guild.channels;
    let text = channels.cache.filter(r => r.type === "text").size,
        vc = channels.cache.filter(r => r.type === "voice").size,
        category = channels.cache.filter(r => r.type === "category").size,
        totalchan = channels.cache.size;
    
    // Region
    let location = region[message.guild.region];
    
    // Date
    let x = Date.now() - message.guild.createdAt;
    let h = Math.floor(x / 86400000)
    let created = dateformat(message.guild.createdAt);
    
    const embed = new Discord.MessageEmbed()
    .setColor('RAMDOM'  )
    .setTimestamp(new Date())
    .setThumbnail(icon)
    .setAuthor(message.guild.name, icon)
    .addField("Region", location)
    .addField("Date Created", `${created} \nsince **${h}** day(s)`)
    .addField("Owner", `**${message.guild.owner.user.tag}**`)
    .addField(`Members [${total}]`, `Online: ${online} \nIdle: ${idle} \nDND: ${dnd} \nOffline: ${offline} \nBots: ${robot}`)
    .addField(`Channels [${totalchan}]`, `Text: ${text} \nVoice: ${vc} \nCategory: ${category}`)
    message.channel.send(embed);
        }
module.exports.help = {
            name: "serverinfo",
        }

In ServerInfo command Statuses count wrong because of that error it show 1 Online 0 Idle 0 DND 1 Offline 1 Bot everytime and now there are problem with ServerInfo Command in other servers cause this error:

(node:9476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of null
    at Object.module.exports.run (D:\DiscordBot\commands\serverinfo.js:53:49)
    at Client.<anonymous> (D:\DiscordBot\main.js:118:17)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (D:\DiscordBot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\DiscordBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\DiscordBot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
(node:9476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I also didn't change anything and everything was fine in the morning. Exactly on my server ServerInfo work properly without any errors, this only didn't work in other servers. 

Version of Discord.js : discord.js@12.4.1

**Comment by TheOfficialDevJosh** [comment]
Thats the same problem I have

**Comment by SpaceEEC** [comment]
This is due to Discord now turning off the intents `GUILD_MEMBERS` and `GUILD_PRESENCES` by default.
You can read more about that on their [Gateway Update FAQ](https://support-dev.discord.com/hc/en-us/articles/360056426994), those also includes a link to our [Intents Guide Page](https://discordjs.guide/popular-topics/intents.html).

Reading those should give you all info you need.
