### ISSUE TITLE
fetchAuditLogs() showing bot as false when should be true

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#4943]
On 10/21 I noticed my role logs showing bot entries when I was using if (executor.bot) return;

Iv'e been using the same logs for months and never had this issue. Did some logging and noticed 
GuildAuditLogsEntry {
  targetType: 'USER',
  actionType: 'UPDATE',
  action: 'MEMBER_ROLE_UPDATE',
  reason: 'Reaction Roles - User added or removed their reaction.',
  executor: ClientUser {
    id: '696870234262339614',
    username: 'Sx Bot',
    bot: false,
    discriminator: '8364',
    avatar: '8d9248ee2749a9dcef67ef9432535294',
    flags: UserFlags { bitfield: 65536 },
    lastMessageID: null,
    lastMessageChannelID: null,
    verified: true,
    mfaEnabled: true,
  },
Bot is showing as false when in fact it's true. I tried the fetch on another bot, same issue 
executor: <ref *2> KlasaUser {
    id: '696870234262339614',
    system: false,
    locale: null,
    flags: UserFlags { bitfield: 65536 },
    username: 'Sx Bot',
    bot: false,
    discriminator: '8364',
    avatar: '8d9248ee2749a9dcef67ef9432535294',
    lastMessageID: null,
    lastMessageChannelID: null,

I tested by doing a RAW api request, and it shows true as expected 
 {
      id: '696870234262339614',
      username: 'Sx Bot',
      avatar: '8d9248ee2749a9dcef67ef9432535294',
      discriminator: '8364',
      public_flags: 65536,
      bot: true
    }

**Comment by almostSouji** [comment]
First of all: please do not delete the issue template but fill it out instead, it exists for a reason.

You seem to be using a bot framework, please check if this still happens with stable vanilla discord.js version 12.4.1. We will only investigate bugs that can be reproduced on discord.js without any additions on minimal reproducible code samples.

**Comment by pkdev08** [comment]
Hi, Sorry I never saw the template when I clicked in. I did some troubleshooting, on fresh install of discord 12.4.1 and have isolated the issue to when you enable the "USER" partial.



**Please describe the problem you are having in as much detail as possible:**
bot is showing as false instead of true when "USER" partial is enabled.
GuildAuditLogsEntry {
  targetType: 'USER',
  actionType: 'UPDATE',
  action: 'MEMBER_ROLE_UPDATE',
  reason: 'Reaction Roles - User added or removed their reaction.',
  executor: User {
    id: '696870234262339614',
    system: null,
    locale: null,
    flags: UserFlags { bitfield: 65536 },
    username: 'Sx Bot',
    bot: false,
    discriminator: '8364',
    avatar: '8d9248ee2749a9dcef67ef9432535294',
    lastMessageID: null,
    lastMessageChannelID: null
  },

**Include a reproducible code sample here, if possible:**

const Discord = require('discord.js');
const client = new Discord.Client({ partials: ['USER'] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('guildMemberUpdate', async (oldMember, newMember) => {

      const roleUpdate = await newMember.guild
      .fetchAuditLogs({ type: "MEMBER_ROLE_UPDATE" })
      .then((audit) => audit.entries.first());
      console.log(roleUpdate)
});

**Further details:**

- discord.js version: 12.4.1 ( Latest )
- Node.js version: v14.14.0
- Operating system: ubuntu 20.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Medium priority

**Relevant client options:**

- partials: "USER"
- gateway intents: none
- other: none



- [x] I have also tested the issue on latest master, commit hash:
