### ISSUE TITLE
guildMemberAdd event not emitted on guild member join

### ISSUE THREAD

**Issue by NobUwU** [discordjs/discord.js#4945]
guildMemberAdd event not emitted on join.
The event will emit manually, but will not emit on a member joining

discord.js: ^12.4.1
node: v14.5.0

code

guildMemberAdd.js
```js
module.exports = class
{
  constructor(client)
  {
    /**
     * Client
     * @type {import("../base/Client")}
     */
    this.client = client;
  }
  /**
   * @param {import("discord.js").GuildMember} member Discord message object
   */
  async run(member)
  {
     console.log("A member joined");
  }
};
```

**Comment by iShibi** [comment]
It's because discord forced some new changes yesterday. From now on to get events like 'guildMemberAdd', you need to have intents turned on in the dev portal.

**Comment by NobUwU** [comment]
smh discord, thankyou so much

**Comment by vladfrangu** [comment]
Take a read at Discord's article: https://dis.gd/gwupdate
