### ISSUE TITLE
Discord.js (show bots, users)

### ISSUE THREAD

**Issue by xHyroM** [discordjs/discord.js#4946]
**Please describe the problem you are having in as much detail as possible:**
When I put the code to show how many robots there are on the server / people, it doesn't work properly for me. It does not show a good number.

**Include a reproducible code sample here, if possible:**

```js
message.guild.members.cache.filter(member => member.user.bot).size
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12x
- Operating system: Linux (Debian)
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by vladfrangu** [comment]
Either you are affected by the recent intents changes (available at https://dis.gd/gwupdate), or your cache isn't filled (and as such, the number might be inaccurate)

**Comment by alide123321** [comment]
> **Please describe the problem you are having in as much detail as possible:**
> When I put the code to show how many robots there are on the server / people, it doesn't work properly for me. It does not show a good number.
> 
> **Include a reproducible code sample here, if possible:**
> 
> ```js
> message.guild.members.cache.filter(member => member.user.bot).size
> ```
> 
> **Further details:**
> 
> * discord.js version: 12.3.1
> * Node.js version: 12x
> * Operating system: Linux (Debian)
> * Priority this issue should have – please be realistic and elaborate if possible:

Im having the same problem except I have discord.js version 12.4.1 and it gives me a value of 1 instead of 0 (not sure of the value it gives you)

**Comment by almostSouji** [comment]
same issue, same solution, here is the full FAQ post from the server:

> :gear:  **Events for privileged intents are not sent if not enabled:**
• Discords FAQ on this change: <https://dis.gd/gwupdate>
• your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
• your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
• you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: **update to v12**, we no longer support v11.
> 
> **Symptoms you might be experiencing with discord.js**:
• member caches are empty     *(or only have very few entries)*
• user cache is empty      *(or has only very few entries)*
• fetching members times out
• login times out if you try to fetch all members on startup
• The client events `"guildMemberAdd"`, `"guildMemberRemove"`, `"guildMemberUpdate"` do not emit
• `Guild#memberCount` returns count as of ready
