### ISSUE TITLE
client.on("guildMemberAdd")

### ISSUE THREAD

**Issue by xHyroM** [discordjs/discord.js#4949]
Not working client.on("guildMemberAdd", async(member) => {console.log(member.id)})

**Comment by almostSouji** [comment]
> :gear:  **Events for privileged intents are not sent if not enabled:**
• Discords FAQ on this change: <https://dis.gd/gwupdate>
• your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
• your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
• you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: **update to v12**, we no longer support v11.
>
> **Symptoms you might be experiencing with discord.js**:
• member caches are empty     *(or only have very few entries)*
• user cache is empty      *(or has only very few entries)*
• fetching members times out
• login times out if you try to fetch all members on startup
• The client events `"guildMemberAdd"`, `"guildMemberRemove"`, `"guildMemberUpdate"` do not emit
• `Guild#memberCount` returns count as of ready
