### ISSUE TITLE
guildMemberUpdate is only triggered if it is the bot itself

### ISSUE THREAD

**Issue by philw95** [discordjs/discord.js#4952]
**Please describe the problem you are having in as much detail as possible:**
The Event "guildMemberUpdate" is only triggered if it is the bot itself. All other clients do not trigger the event.

**Include a reproducible code sample here, if possible:**

```js
bot.on('guildMemberUpdate', (oldUser, newUser) => {
    console.log('Test')
})
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: v12.18.3
- Operating system: Windows / Debian
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
> :gear:  **Events for privileged intents are not sent if not enabled:**
• Discords FAQ on this change: <https://dis.gd/gwupdate>
• your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
• your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
• you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
• If you are on v11 and experience issues: **update to v12**, we no longer support v11.
>
> **Symptoms you might be experiencing with discord.js**:
• member caches are empty     *(or only have very few entries)*
• user cache is empty      *(or has only very few entries)*
• fetching members times out
• login times out if you try to fetch all members on startup
• The client events `"guildMemberAdd"`, `"guildMemberRemove"`, `"guildMemberUpdate"` do not emit
• `Guild#memberCount` returns count as of ready

**Comment by philw95** [comment]
Thanks :)
