### ISSUE TITLE
Doesn't check permissions properly for admins

### ISSUE THREAD

**Issue by Snowflake107** [discordjs/discord.js#4954]
**Please describe the problem you are having in as much detail as possible:**
It doesn't check correct permission flag for the members with `ADMINISTRATOR` permission.
It throws error to normal members if the permission flag provided is invalid whereas it always returns true for administrators.

**Include a reproducible code sample here, if possible:**
```js
message.guild.members.cache.get("SOME_ADMIN").hasPermission("SOME_INVALID_PERMISSION"); // should return true
message.guild.members.cache.get("NORMAL_MEMBER").hasPermission("SOME_INVALID_PERMISSION"); // should throw error
```
![image](https://user-images.githubusercontent.com/46562212/97530494-626fef80-19da-11eb-8538-2e436b248391.png)

**Further details:**
- discord.js version: 12.4.0
- Node.js version: 12.18.3
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible: no priority

**Relevant client options:**
- partials: none
- gateway intents: none
- other: none

**Comment by zaida04** [comment]
I'm 9 days late on this, but I believe this is caused by 
https://github.com/discordjs/discord.js/blob/master/src/util/Permissions.js#L44 (which is used by GuildMember#hasPermission)

```js
  has(permission, checkAdmin = true) {
    return (checkAdmin && super.has(this.constructor.FLAGS.ADMINISTRATOR)) || super.has(permission);
  }
```
in which if the person has admin, the return short circuits to returning true. 

If a solution to this is needed (in which I'm not sure why you wouldn't just use the correct permission names) you can do:
`hasPermission("SOME_INVALID_PERMISSION");` => `hasPermission("SOME_INVALID_PERMISSION", {checkAdmin: false});`

**Comment by ryry6** [comment]
Getting the same issue
Having a user that is admin but has permissions overridden on the channel is getting incorrect results

```
const channel = await client.channels.fetch(player.channelId) as Discord.TextChannel;
const hasPermission = channel.permissionsFor(channel.guild.me).has('USE_EXTERNAL_EMOJIS', false)
```
`hasPermission` is true but it shouldn't be because the channel is restricting the user permission for `USE_EXTERNAL_EMOJIS`.

Open to ideas if I'm mistaken

**Comment by NotSugden** [comment]
> Getting the same issue
> Having a user that is admin but has permissions overridden on the channel is getting incorrect results
> 
> ```
> const channel = await client.channels.fetch(player.channelId) as Discord.TextChannel;
> const hasPermission = channel.permissionsFor(channel.guild.me).has('USE_EXTERNAL_EMOJIS', false)
> ```
> 
> `hasPermission` is true but it shouldn't be because the channel is restricting the user permission for `USE_EXTERNAL_EMOJIS`.
> 
> Open to ideas if I'm mistaken

this isnt the same issue, this issue is about passing an invalid permission

> a user that is admin

does this mean they have the `Administrator` permission? because this bypasses all channel overrides, and is probably your problem

**Comment by ryry6** [comment]
Yeah my bad different issue.
Yes the user has the administrator permission but shouldn't passing false as the second argument stop the override and check only 
channel permissions?

**Comment by zaida04** [comment]
Well, GuildMember#hasPermission's second param should be an **object**, I would suggest reading the documentation regarding it https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=hasPermission

**Comment by zaida04** [comment]
> `* * `ADMINISTRATOR` (implicitly has *all* permissions, and bypasses all channel overwrites)`

from https://github.com/discordjs/discord.js/blob/stable/src/util/Permissions.js#L51
