### ISSUE TITLE
Crosspost does not throw error on encountering rate limits

### ISSUE THREAD

**Issue by CodemonkeyOSS** [discordjs/discord.js#4956]
Discord enforces a limit of 10 publishes per server per hour. When using the Discord UI, this manifests as an error message in the UI to wait for X minutes. When using discord.js, if you encounter this rate limit, the promise from message.crosspost() just hangs out indefinitely. It would be much cleaner to just throw an error when the post() receives a rate limit response instead of hanging out.

To reproduce, simply `crosspost()` messages 10 times quickly and then an eleventh time to encounter the issue.

**Further details:**

- discord.js version: 12.4.1
- Node.js version:14.8.0
- Operating system: MacOS
- Priority this issue should have – please be realistic and elaborate if possible:

Probably a QoL thing, but I can see a situation where a developer would want to be able to catch this case and notify themselves or a user.

**Comment by almostSouji** [comment]
> message.crosspost() just hangs out __indefinitely.__

Are you sure about that? We generally delay calls as the rate limit dictates, meaning this should resolve after an hour. The distinction is an important one to make! I can definitely see how this would benefit from aborting the call if this limit is hit (1h is tremendously long after all) however:

- indefined: bug, needs to be fixed
- resolves as the rate limit backoff is over: working as intended, feature request

**Comment by CodemonkeyOSS** [comment]
> > message.crosspost() just hangs out **indefinitely.**
> 
> Are you sure about that? We generally delay calls as the rate limit dictates, meaning this should resolve after an hour. The distinction is an important one to make! I can definitely see how this would benefit from aborting the call if this limit is hit (1h is tremendously long after all) however:
> 
>     * indefined: bug, needs to be fixed
> 
>     * resolves as the rate limit backoff is over: working as intended, feature request

Yeah, my apologies. I did not validate if it clears after the rate limit opens up. If this is as intended, that's fine with me and I would close.

**Comment by almostSouji** [comment]
definitely something we can consider, just moves it from bug to feature request

**Comment by NotSugden** [comment]
> just moved it from bug to feature request

what type of implementation would we go with for this? a client option to throw an error if the rate limit is over x amount of time?

**Comment by SpaceEEC** [comment]
I'd say #5659 resolves this, as you can configure discord.js to throw if an error occurs while crossposting a message in any/a sepcific news channel.
