### ISSUE TITLE
Error occuring on leaving a guild

### ISSUE THREAD

**Issue by nceon** [discordjs/discord.js#4960]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to make a guild blacklist system on my bot, Saturne, but while attempting to leave it returns an error:
I'll leave a link to the error: 
http://saturne.rf.gd/archives/30102020.png

**Include a reproducible code sample here, if possible:**

```js
client.on('guildCreate', guild => {
  client.user.setActivity(`${client.users.cache.size} members [!]`, { type: 'WATCHING' });
  if (guild.id === "--") {
    const blembed = new discord.MessageEmbed()
     .setTitle('Uh Oh.')
     .setDescription(`Your guild with the ID: \`--\` is banned from using Saturne services with the reason of:\n$// reason here`)
     .setFooter('You cannot appeal this ban.')
    guild.owner.send(blembed)
    setTimeout(console.log(guild.client.user), 3000) <<<<< ISSUE IS HERE
  }
});
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 14.13.1
- Operating system: WIN10 BUILD 19041
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: all
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by MattIPv4** [comment]
`setTimeout(() => console.log(guild.client.user), 3000)` setTimeout expects a function

**Comment by almostSouji** [comment]
Not a bug with the library, setTimeout requires a function to execute (callback) as first parameter, you currently provide undefined
