### ISSUE TITLE
Getting 403 even though action was successful

### ISSUE THREAD

**Issue by zlyfer** [discordjs/discord.js#4962]
**Please describe the problem you are having in as much detail as possible:**
I try to move a user to another voice channel and I get 403 even though it worked.
The bot has following global permissions: Manage Channel, Read Text Channels & See Voice Channels, Connect, Move Members and there are no permissions set in the voice channel nor the category the voice channel is in.
The bot is on the lowest spot of the role list (above @everyone).

**Include a reproducible code sample here, if possible:**

```js
// Let member be any member.
// Let voiceChannel be any voice channel within a category.
console.log(true);
member
  .edit({ channel: v }, "Moved to their dynamic channel.")
  .then(() => {
    console.log(false);
  })
  .catch(console.warn);
console.log("1");
```
**Output**
```bash
true
1
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\zlyfla\Documents\GitHub\DynChan\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'patch',
  path: '/channels/771734542091943987',
  code: 50013,
  httpStatus: 403
}
false
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v12.16.3
- Operating system: Windows 10, Version 1909 (OS Build 18363.1139)
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

This is the first time that I create an issue here (I think) and English is not my native language, so I please you to bear with me.

**Comment by zlyfer** [comment]
I did some testing and it appears that the error doesn't show up anymore when the bot has the permission "Manage Roles".

**Comment by SpaceEEC** [comment]
Your error indicates that you are trying to edit a _channel_ and not a member, which implies you are using something involving `Channel#edit` too, somewhere in your code.

Update to 12.4 and above to get more useful stacktraces for api errors pointing back to your code.
With that new and better stacktraces you should see from where you are trying to edit a channel.
Or, if this is from somewhere on our end, I will know where to look, as I am currently unable to reproduce this error.

**Comment by PanSzelescik** [comment]
I have also this error on latest version when adding/removing roles to member:
`DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/user/bot/bot-main/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/user/bot/bot-main/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildMember.edit (/home/user/bot/bot-main/node_modules/discord.js/src/structures/GuildMember.js:312:5) {
  method: 'patch',
  path: '/guilds/369033953023098881/members/213786437835948042',
  code: 50013,
  httpStatus: 403
}`
Bot has Administrator permission
