### ISSUE TITLE
Proxy connection

### ISSUE THREAD

**Issue by kayotimoteo** [discordjs/discord.js#4963]
Hi

I would like to propose a resource, the application accept **proxy** connection, because I researched a lot, tried in various ways to succeed and nothing, and as today it is a widely used application and with great potential I think it is cool.

I know issue #489 and I know how difficult it is, but I think we should resume the discussion, since the application and tools have lost a lot in 4 years.

This is my simple request for interesting functionality.

Thanks!

**Comment by lio-fan** [comment]
I don't think proxies would be a good idea considering people are rate limited and API banned, and having a proxy makes blocking users just that much harder.

**Comment by kayotimoteo** [comment]
> I don't think proxies would be a good idea considering people are rate limited and API banned, and having a proxy makes blocking users just that much harder.

I understand your side did not know this, but I will use it in something that will help our team of 5 people, but I am in a corporate environment, and we have a proxy.

**Comment by lio-fan** [comment]
Although you are in a corporate environment and you would be using it for a noble reason, there will sadly be other users who abuse this method to bypass rate limits. Your best bet would be setting up a local proxy on your hosting platform.

**Comment by kayotimoteo** [comment]
> Although you are in a corporate environment and you would be using it for a noble reason, there will sadly be other users who abuse this method to bypass rate limits. Your best bet would be setting up a local proxy on your hosting platform.


I will really check with the infrastructure staff, if it is possible to disable the proxy in the environment for me. Thanks

**Comment by advaith1** [comment]
from the previous issue, it looks like the reasoning for it not working is just technical incompatibilities with upstream software that discord.js cannot do anything about, rather than anyone actually opposing its implementation.

**Comment by kayotimoteo** [comment]
> da edição anterior, parece que o raciocínio para não funcionar é apenas incompatibilidade técnica com software upstream que o discord.js não pode fazer nada, em vez de alguém realmente se opor à sua implementação.


I will really check with the infrastructure staff, if it is possible to disable the proxy in the environment for me.

**Comment by kayotimoteo** [comment]
> da edição anterior, parece que o raciocínio para não funcionar é apenas incompatibilidade técnica com software upstream que o discord.js não pode fazer nada, em vez de alguém realmente se opor à sua implementação.

Can I reopen then? or even today it is incompatible

**Comment by advaith1** [comment]
I don't know if the status has changed, you can reopen it if you want

**Comment by Poly-Pixel** [comment]
There has not been any activity on this issue for 8 months, and I am unable to find anything that would allow the use of proxies. For this reason, I recommend that this issue be closed - if new information regarding this topic is found, the issue can be reopened. @kayotimoteo

**Comment by iCrawl** [comment]
This likely isn't going to happen until the rewrite of the whole library, I will close this for now 👍
