### ISSUE TITLE
user.presence.status

### ISSUE THREAD

**Issue by AVMG20** [discordjs/discord.js#4965]
the user.presence.status only returns 'offline' even tho I'm online.

I have been having my bot online for around 2 months without any problems or changes.
suddenly a part of the bot stops working and after investigating I noticed the bot returning my status as 'offline' even tho I'm online.

![image](https://user-images.githubusercontent.com/45005889/97785767-76b51780-1ba7-11eb-97f5-abf9f7bf1d5b.png)
![image](https://user-images.githubusercontent.com/45005889/97785776-80d71600-1ba7-11eb-9b13-8faacf99768b.png)
![image](https://user-images.githubusercontent.com/45005889/97785779-87658d80-1ba7-11eb-9fcc-a7e31f7e25a4.png)
![image](https://user-images.githubusercontent.com/45005889/97785799-a2d09880-1ba7-11eb-9c38-638c13d36434.png)

**Comment by tipakA** [comment]
Caused by API intents - #4961.
