### ISSUE TITLE
ReactionCollector only collects reactions from Users that have already sent a message in the Channel.

### ISSUE THREAD

**Issue by Volterium** [discordjs/discord.js#4968]
I'm setting up a `ReactionCollector` on a message like this:
```
const filter = (reaction, user) => {
    return true; 
};
const collector = msg.createReactionCollector(filter);
collector.on('collect', (reaction, user) => {
    console.log('Callback - User:' + user.id)
});
```
I would expect that this would print `Callback - User: foo` when a user with the UserID `foo` reacts to `msg`. 
However, this only happens if the User has already sent a message in the Channel after `msg` was sent.

**Comment by tipakA** [comment]
Caused by API intents - #4961.

**Comment by Volterium** [comment]
Thanks for the reply. It's not obvious to me which of my functions requires those privileges. Could you elaborate?

**Comment by vthemelis** [comment]
I also have the same issue. I don't see how that's related to privileges though . . .

**Comment by advaith1** [comment]
You don't need privileged intents for that, you just need to enable necessary [partials](https://discord.js.org/#/docs/main/stable/topics/partials) in ClientOptions.

**Comment by vthemelis** [comment]
I see, so I would imagine that in this particular scenario, the `"REACTION"` string needs to be added to the array in the `partials` attribute of the `Client`. Thanks a lot!

**Comment by ayezinzu** [comment]
"You don't need privileged intents for that, you just need to enable necessary partials in ClientOptions."
Hi can someone tell me how I do this

**Comment by almostSouji** [comment]
> "You don't need privileged intents for that, you just need to enable necessary partials in ClientOptions."
> Hi can someone tell me how I do this

See the link provided by advaith above (https://discord.js.org/#/docs/main/stable/topics/partials)
