### ISSUE TITLE
Option to enable all Intents on DiscordJS initialization

### ISSUE THREAD

**Issue by NLDev** [discordjs/discord.js#4974]
**Is your feature request related to a problem? Please describe.**
Since the last Discord API changes, a lot of bots broke / stopped working. For some bots (e.g. "private" and unverified bots which are only present one one server) it's just not worth re-coding the entire thing because of those changes. You could just go to the Discord Developer Portal and flick the two switches, and then tell DiscordJS to just go with all Intents. 

**Describe the ideal solution**
An approach like DiscordPy did it would be pretty convenient: 

```python
intents = discord.Intents.all()
client = discord.Client(intents=intents)
```

or as JS version:

```javascript
let Discord = require("discord.js");

// ...

const allIntents = Discord.Intents.all();
const client = new Discord.Client({ intents: allIntents });

// ...
```
That way people (including me) wouldn't have to go through the hassle and re-code the entire bot. 
FWIW, I tried passing the intents like in Issue https://github.com/discordjs/discord.js/issues/3924 - unfortunately to no avail.

**Comment by advaith1** [comment]
In discord.js v12, setting intents in ClientOptions is **not necessary**; you can do it if you want but by default, Discord will just send events **for all intents you qualify for** (all non-privileged intents + privileged intents you are whitelisted for/enable in the dev portal).

In discord.js v13, you will have to specify the intents you need.

You technically can request all intents with `intents: Discord.Intents.ALL`, however you really **should not** do this because that removes the whole point of intents; not sending the bot events it doesn't need to reduce bandwidth, CPU, and RAM consumption.

**Comment by almostSouji** [comment]
> You could just go to the Discord Developer Portal and flick the two switches, and then tell DiscordJS to just go with all Intents.

You should definitely not. no.

The entire point behind intents is for developers to carefully think about what kind of data they need to provide the functionality they aim to, and which can be left out under the viewpoint of data minimization. If you do not require privileged intents you should not just blindly flick switches and hope it works. You should re-think your approach instead.

We will shortly provide a guide page with examples regarding this topic and bring more light to ways to get around without privileged intents and when you do in fact need them.

That being said this exists at [`Intents.ALL`](https://discord.js.org/#/docs/main/stable/class/Intents?scrollTo=s-ALL).

**Comment by shxrkyy** [comment]
Thank you so much! This really helped me out! I had to change a few things, but this is the code I used to make it work:

const allIntents = new Discord.Intents();
const client = new Discord.Client({ intents: allIntents });

**Comment by ledlamp** [comment]
enabling all intents is useful when u have a bot for just one small server

**Comment by iCrawl** [comment]
No.
