### ISSUE TITLE
guildMemberAdd and guildMemberRemove does not work

### ISSUE THREAD

**Issue by XNexusPrimeX** [discordjs/discord.js#4976]
**a few days ago, I made an invite tracker, but it stopped working a few days later.
I tried to see what was going on and realized that when someone came in and out of the server, json did not appear with the information.
I thought it could be a bug in my code, but trying on other projects wasn't going to either.
Today I heard that there was an update to the discord API and I'm wondering if this was not the update that bugged everything (The part that is bugging is only guildMemberRemove and guildMemberAdd)..**

ps. my native language is not english

**Code:**

```js
client.on('guildMemberAdd', async dados => {
    console.log(dados);
});
// I put this code ultra simple ._.
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.18.3
- Operating system: Windows 10 Pro
- Priority this issue should have – not so urgent

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
see #4961
