### ISSUE TITLE
role.members.cache is undefined

### ISSUE THREAD

**Issue by iwiedenm** [discordjs/discord.js#4977]
**Please describe the problem you are having in as much detail as possible:**
I am trying to list the members of a role. After getting the mentioned role of a message, I attempt to access the cache but it is undefined.

**Include a reproducible code sample here, if possible:**

```js
const role = message.mentions.roles.first();
let msg = '';
if (role) {
  msg = `Members of the ${role} role\n`;
  role.members.cache.each((member, i) => {
    msg += `${member}\n`;
  });
  return msg;
} else {
  return new Error('Please mention a role.')
}
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.x
- Operating system: Mac
- Priority this issue should have – please be realistic and elaborate if possible: Standard

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
<https://discord.js.org/#/docs/main/stable/class/Role?scrollTo=members> returns a Collection, not a manager. 

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by iwiedenm** [comment]
Sorry for wasting your time I should read more carefully. Thank you.
