### ISSUE TITLE
messageReactionAdd does not fire on cached messages

### ISSUE THREAD

**Issue by skeddles** [discordjs/discord.js#4978]
This is a simplified version of the code from here: [https://github.com/discordjs/guide/blob/master/code-samples/popular-topics/reactions/12/uncached-messages.js](https://github.com/discordjs/guide/blob/master/code-samples/popular-topics/reactions/12/uncached-messages.js)
and here
[https://discordjs.guide/popular-topics/reactions.html#listening-for-reactions-on-old-messages](https://discordjs.guide/popular-topics/reactions.html#listening-for-reactions-on-old-messages)

```
const Discord = require('discord.js');
const client = new Discord.Client({ partials: ['MESSAGE', 'CHANNEL', 'REACTION'] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('messageReactionAdd', async (reaction, user) => {
	console.log('reaction added');
});

client.on('messageReactionRemove', async (reaction, user) => {
	console.log('reaction removed');
});

client.login(token);
```
The code has more to it, with awaiting the "partial", but it never gets called in the first place no matter what because messageReactionAdd only gets called for cached messages.

If I force it to cache the message like this:

```
	var channel = client.channels.cache.get('553806751808487434');
	channel.messages.fetch('676828136771551243')
		.then(message => {
			console.log('fetched message',message.content);

		})
		.catch(console.error);
```

then the `messageReactionRemove` event fires, but still no `messageReactionAdd`.

Both of these events fire when un/reacting to messages sent after the bot started.

**Comment by NotSugden** [comment]
seems like it could be a problem with your intents, try enabling the Guild Members privileged intent in the dev portal

**Comment by advaith1** [comment]
you don't need the members intent to get reactions, and it won't be granted for that

@skeddles try enabling the USER partial?

**Comment by NotSugden** [comment]
i was thinking along the lines of the members (with the user data too) being cached, as only the user IDs are sent with the gateway event, but yea now you think about it enabling the users partial would work, my bad

**Comment by advaith1** [comment]
The members intent wouldn't make it much more likely for the member to be cached anyway.

BTW Discord does send the member object on this event when it occurs in a server, but Discord.js doesn't currently use that data iirc.

**Comment by ayezinzu** [comment]
Use USER and REACTION partials and it will be fixed. I was facing the same issue.

**Comment by Proantagonist** [comment]
I had to use user, reaction, and message on 12.4.1

```js
const client = new Client({
  partials: ['USER', 'REACTION', 'MESSAGE']
});
```

**Comment by SpaceEEC** [comment]
See my comment here: https://github.com/discordjs/discord.js/issues/4980#issuecomment-723519865
