### ISSUE TITLE
Unicode characters in message.reply

### ISSUE THREAD

**Issue by JaredTurck** [discordjs/discord.js#4981]
**Is your feature request related to a problem? Please describe.**
I would like to be able to send Unicode characters in a message

`bot.on("message", msg => {
    if (msg.content == "-test_bot") {
        msg.reply("𝖇𝖔𝖙 𝖔𝖓𝖑𝖎𝖓𝖊!");
    }
})`

when I run the `-test_bot` command, the bot sends questions marks like this
`@Jared, ?????? ????????????!`
![discord js unicode chars](https://user-images.githubusercontent.com/21154480/98408937-e6c11300-2069-11eb-9861-2901bc1941be.png)

**Describe the ideal solution**
I would like the bot to send the Unicode characters, `"@Jared, 𝖇𝖔𝖙 𝖔𝖓𝖑𝖎𝖓𝖊!"` instead of `@Jared, ?????? ????????????!`.

**Describe alternatives you've considered**
I have had a read through the Discord documentation [here](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=reply), and it does not show how to send Unicode characters in message replys.

**Comment by SpaceEEC** [comment]
I am unable to reproduce this behavior, I am getting the expected response just fine.

You might have not saved the file with the correct encoding (read: utf-8).

**Comment by JaredTurck** [comment]
I'm using notepad++ to edit the file, and I have saved it with the UTF-8 encoding https://stackoverflow.com/questions/7256049/how-do-i-convert-an-ansi-encoded-file-to-utf-8-with-notepad
what program are you using to edit your js file?

**Comment by SpaceEEC** [comment]
I am using [Visual Studio Code](https://code.visualstudio.com/), but notepad++ should be able to deal with that just fine.

**Comment by JaredTurck** [comment]
ok thank you, I used a different source code editor and it works now.
