### ISSUE TITLE
User#bot erroneously changing into false when fetching audit logs when using user partial

### ISSUE THREAD

**Issue by Majoramari** [discordjs/discord.js#4985]
**Please describe the problem you are having in as much detail as possible:**

I'm using `messageReactionAdd` event and I'm fetching some entries from the audit log, If it happened to add a reaction at the same time that an Audit log fetching process happening, it masses up something I'm not sure what it is but it loses track if the user is a bot or not in messageReactionAdd event

**Include a reproducible code sample here, if possible:**

the fetch code something like 
```js
var fetchedLogs = await newState.guild.fetchAuditLogs({
                limit: 1,
            });
            const Logs = fetchedLogs.entries.first();
```

**note:** my bot add reaction when it starts up

```js
//without fetching
ClientUser {
  id: '594320405523857448',
  username: 'Morino',
  bot: true, // <-- pay attention here
  discriminator: '4849',
  avatar: '84a30bdb5c4b1878a3266354a586707b',
  lastMessageID: '774506721787379793',
  lastMessageChannelID: '771458315795300383',
  verified: true,
  mfaEnabled: true,
  _typing: Map {},
  data: {
    language: 'ar-MA',
    playlist: [],
    _id: 5f9b12e2a354594975f883de,
    id: '594320405523857448',
    __v: 0
  },
  flags: UserFlags { bitfield: 0 }
}

// with fetching
ClientUser {
  id: '594320405523857448',
  username: 'Morino',
  bot: false,  // <-- pay attention here
  discriminator: '4849',
  avatar: '84a30bdb5c4b1878a3266354a586707b',
  lastMessageID: null,
  lastMessageChannelID: null,
  verified: true,
  mfaEnabled: true,
  _typing: Map {},
  data: {
    language: 'ar-MA',
    playlist: [],
    _id: 5f9b12e2a354594975f883de,
    id: '594320405523857448',
    __v: 0
  },
  flags: UserFlags { bitfield: 0 }
}
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.14.0
- Operating system: Windows 10 pro N version 2004 build 19041.572
- Priority this issue should have – please be realistic and elaborate if possible: not so important

**Relevant client options:**

- partials: 'CHANNEL', 'GUILD_MEMBER', 'MESSAGE', 'REACTION', 'USER'
- gateway intents: none
- other: none

- [x] I have also tested the issue on the latest master, commit hash: 7ec0bd9

**Comment by SpaceEEC** [comment]
#### What I could gather

- This bug occurs if you fetch audit logs where the executor or target is a cached bot and you have the USER partial enabled.
- The symptom is the `bot` property erroneously turning into `false`.
- It's unrelated to `messageReactionAdd` or any other events, it's just about fetching audit logs.


### Some code
One starting point, the other would be the target property:
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/src/structures/GuildAuditLogs.js#L323-L325

Then the already existing bot will be patched with empty data here:
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/src/managers/BaseManager.js#L46

And there is the unguarded assignment to the bot property:
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/src/structures/User.js#L52

 `Boolean(undefined)` is `false` and voilà.

#### The solution?

This bug (the unguarded bot assignment) was introduced with #4706, which ironically was fixing exactly this property having an invalid state.

Maybe we should go back to before #4636? I do not have looked into what this entails exactly yet however.

**Comment by NotSugden** [comment]
it seems that when #4706 reverted the change in #4636, the author of that PR still kept the assignment in _patch, rather than in the constructor as it was initally (unsure why this was even moved to _patch in #4636 anyway)
