### ISSUE TITLE
voiceStateUpdate is the other way around

### ISSUE THREAD

**Issue by XNexusPrimeX** [discordjs/discord.js#4988]
**Please describe the problem you are having in as much detail as possible:** I'm doing a check to see if someone has called, or if someone has left.
a few days ago it was working, but today i went to update it i realized it was working a little strange, so i went to take a look, and realized something very funny, instead of showing the id of the room i entered, it returns undefined and when I leave the room, he returns the id .... WHAT ???
is this a bug or is it an error in my code?

ps. I'm remaking the code from scratch, so there is little

**Include a reproducible code sample here, if possible:**

```js
const config = require('../config.json');
const db = require('../db.json');

module.exports = (client, dados) => {
    console.log(dados)
    if (dados.channelID === null) {
        console.log('saiu!')
    } else if (dados.channelID === '707717743788687433') {
        const guild = client.guilds.cache.get(dados.guild.id);
        const user = guild.members.cache.get(dados.id);

        db.waitCall.push({id: user.user.id, roles: user._roles});
        console.log('alguém entro ' + db.waitCall)
    } else {}
}
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.3
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by tipakA** [comment]
`voiceStateUpdate` gives *two* parameters, one for state before the event, one for after.
your `dados` is simply state before you joined the VC.

**Comment by XNexusPrimeX** [comment]
so how do i get the data after entering?

**Comment by XNexusPrimeX** [comment]
> `voiceStateUpdate` dá _dois_ parâmetros, um para o estado antes do evento, um para depois.
> seu é simplesmente estado antes de se juntar ao VC, ou antes de você sair dele.`dados`

Então, como consigo os dados depois de entrar?

**Comment by XNexusPrimeX** [comment]
> `voiceStateUpdate` dá _dois_ parâmetros, um para o estado antes do evento, um para depois.
> seu é simplesmente estado antes de se juntar ao VC, ou antes de você sair dele.`dados`

So, how do I get the data after I log in?
