### ISSUE TITLE
messageReactionAdd triggers only after user message

### ISSUE THREAD

**Issue by MorganPicavet** [discordjs/discord.js#4989]
**Please describe the problem you are having in as much detail as possible:**

If the user has not posted any message. The event is never triggered for this person.
The objective is to put an automatic message when connecting the Bot. (Functional)
Then the Bot adds the reaction itself (Functional + triggers the event)
When a user adds the reaction, no detection is made if he has not previously posted a message in any channel

**Include a reproducible code sample here, if possible:**

```js
File : ready.js

const { MessageEmbed } = require('discord.js');
module.exports = (client, message) => {
            const embed = new MessageEmbed()
            .setColor('#7cfc00')
            .setTitle("")
            .setDescription(`
		Test messageReactionAdd
            `)
            channel.send({embed}).then(embed => {
                embed.react('☑')
            })
        })
}
```
```js

File : messageReactionAdd.js

module.exports = (client, messageReaction, user) => {
    return console.log("Reaction Add")
}
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 14.5.0
- Operating system: Windows 10 2004
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
known, see https://github.com/discordjs/discord.js/issues/4980#issuecomment-723519865
