### ISSUE TITLE
Separate VoiceStateUpdate into VoiceChannelJoin and VoiceChannelLeave

### ISSUE THREAD

**Issue by JustAPieOP** [discordjs/discord.js#4993]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
I'm very confuse when trying to figure how to deal with VoiceStateUpdate system as i don't know which state is available each time a member joins or leaves

**Describe the ideal solution**
Simple. Just separate VoiceStateUpdate into two events like: VoiceChannelJoin and VoiceChannelLeave

**Describe alternatives you've considered**
Like the above. In more details, just divide oldState and newState to two different events like above

**Additional context**
No

**Comment by tipakA** [comment]
`voiceStateUpdate` emits two parametera, `oldState` is state from before the event, `newState` is state for what caused the event to be emitted.
If oldState has no channel, and new state has it, someone was not in a VC before, and now is one, same goes the other way - vc in old, no vc in new = someone was in vc, now isn't.

**Comment by almostSouji** [comment]
as the [event description](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-voiceStateUpdate) states:
> Emitted whenever a member changes voice state - e.g. joins/leaves a channel, mutes/unmutes.

It emits with two parameters 

oldState | VoiceState | The voice state before the update
-- | -- | --
newState | VoiceState | The voice state after the update

```js
client.on('voiceStateUpdate', (oldState, newState) => {
   // ...
})
```

Representing the VoiceState before and after the respective update. From these you can derive what happened.

- `oldState.voice.channelID && newState.voice.channelID` moved channels
- `oldState.voice.channelID && !newState.voice.channelID` left a channel (no new channel joined directly)
- `!oldState.voice.channelID && newState.voice.channelID` joined a channel (no old channel before joining this one)
- `oldState.voice.channelID === newState.voice.channelID` Something else happened (mute, unmute, servermute, serverunmute, deafen, etc.

> Simple. Just separate VoiceStateUpdate into two events like: VoiceChannelJoin and VoiceChannelLeave

It is unfortunately not that simple, there are many reasons why this event may emit, not just join and leave, and discord might add one at any point, leaving us to refactor the internals to support that.
