### ISSUE TITLE
[Bug]: Member role cache not updated properly 

### ISSUE THREAD

**Issue by Thellior** [discordjs/discord.js#4994]
**Please describe the problem you are having in as much detail as possible:**
When assigning a role to a user through a message the member.role.cache is not updated properly.
I tried to set the cache my self by doing `message.roles.cache.set` but that is also not reflected.

**Include a reproducible code sample here, if possible:**
Set "type": "module", in package.json
```js
import { Client } from 'discord.js';

const TOKEN = ''
const startApplication = async () => {
    const client = new Client();

    client.on('message', (message) => {
        if(message.content.includes('!add-role')) {
            const member = message.member;
            const role = message.guild.roles.cache.get('671720036347674662')

            // First run false
            // Second run false
            // etc run false
            console.log(member.roles.cache.has(role))

            member.roles.add(role)

            // First run false
            // Second run false
            // etc run false
            console.log(member.roles.cache.has(role));
        }
    })

    await client.login(TOKEN)
}

startApplication()
  .then(() => console.log('Discord server connected'))
  .catch((e) => {
    console.error(e);

    process.exit(1)
});
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: v12.18.3
- Operating system: Windows / Arch Linux
- Priority this issue should have – please be realistic and elaborate if possible:
It can have a low priority because there is a workaround

```js
// Workaround
// Refetch the member because the role cache should be updated
await member.fetch(true)
```

**Extra details:**
I can try to fix the issue myself and make a pull request but i first want to have a confirmation if this is really a bug.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by zaida04** [comment]
I would resolve the promise that GuildMember#roles#add returns first before checking the cache the second time.

**Comment by Thellior** [comment]
This is not what i ment. If you message !assign-role. Wait 1 day and do it again the old cache is still there. Thus cache is not updated properly @zaida04

**Comment by zaida04** [comment]
Have you tried doing the second check with the GuildMember object that is returned when you resolve the promise from the role add?

In addition to this, If you need help with discord.js usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions

**Comment by Thellior** [comment]
@zaida04 I edit the comment by explaining the issue. I understand that you can use the GuildMember object. But i was expecting that if a user made another message that the message.member.roles to be updated.

**Comment by zaida04** [comment]
One thing is, you’re passing the Role object into the has, but Collection#has only takes in a key, in this case the role id. Which would explain why it always returns false

**Comment by almostSouji** [comment]
This is not a bug but multiple levels of handling the checks and logging wrongly.

The second log executes before the call is gone through. Handle the promise #add returns properly to make sure you access after the call and corresponding update are completed. Additionally [Map#has](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has) is a key lookup, the key is the role id, not the entire role object, this will always return false.

```js
console.log(msg.member.roles.cache.map(r => r.name)); // [ '@everyone' ]
msg.member.roles.add('464734450857541634'); // Muted
.log(msg.member.roles.cache.map(r => r.name)); // [ '@everyone' ]
```
```js
// async context, alternatively use a #then callback
console.log(msg.member.roles.cache.map(r => r.name)); // [ '@everyone' ]
await msg.member.roles.add('464734450857541634'); // Muted
console.log(msg.member.roles.cache.map(r => r.name)); // [ 'Muted', '@everyone' ]
```

Resources:
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises>
- <https://discordjs.guide/additional-info/async-await.html>
- <https://javascript.info/async-await>
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has>
