### ISSUE TITLE
members.fetch() does not update the member roles list

### ISSUE THREAD

**Issue by snake-scaly** [discordjs/discord.js#4997]
**Problem description:**

There are two symptoms. I feel they're related so here they are in the order they manifest during testing:

1. When my bot connects it does not receive any reaction notifications until I post at least one message to a channel. After that the bot receives reaction notifications only from that channel, but not from other channels on the same server. Each channel where I post one message becomes "enabled." I don't know if a post by one user enables reaction notifications for other users in the same channel. This also means that the bot will never receive any reactions from a read-only channel.
2. My bot fetches the member who added the reaction. Then it adds or removes a role depending on whether the reaction was added or removed. However the list of roles in `member.roles.cache` stays the same even though the actual roles on the server change.
3. Posting any message in any channel on a connected server refreshes the roles list. Fetching a member after this retrieves the correct, up-to-date list of roles.

Maybe related: it seems like my bot also stopped receiving the `guildMemberAdd` notifications. I didn't test this thoroughly.

Note that this worked before. So this must be some change on the Discord API side.

**Code sample:**

Here is a fully functional bot reproducing this problem:

```js
const discord = require('discord.js')
const client = new discord.Client()
const someRole = '***'
const token = '***'

client.on('warn', msg => console.error('Warning:', msg))
client.on('error', msg => console.error('Error:', msg))
client.on('invalidated', () => console.log('Shutting down'))
client.on('shardError', (msg, shard) => console.error('Shard error:', msg, shard))

client.on('messageReactionAdd', (reaction, user) => {
    reaction.message.guild.members.fetch(user)
        .then(member => {
            console.log('User roles:', member.roles.cache.map(r => r.name))
            member.roles
                .add(someRole)
                .catch(msg => console.error('Error: Add role:', msg))
        })
        .catch(msg => console.error('Error: Member fetch:', msg))
})

client.on('messageReactionRemove', (reaction, user) => {
    reaction.message.guild.members.fetch(user)
        .then(member => {
            console.log('User roles:', member.roles.cache.map(r => r.name))
            member.roles
                .remove(someRole)
                .catch(msg => console.error('Error: Remove role:', msg))
        })
        .catch(msg => console.error('Error: Member fetch:', msg))
})

client.once('ready', () => console.log('Ready'))

client
    .login(token)
    .catch(msg => console.error('Error: Login:', msg))
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.19.0
- Operating system: 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
- Priority this issue should have – please be realistic and elaborate if possible: This is pretty major to me. My role assigning bot does not work in the current situation, and I'm not aware of any work-arounds.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Vaporox** [comment]
Correct, this is a change on the Discord API side. Discord now requires you to enable privileged intents¹ in the developer portal² and you probably haven't done that, so those events are missing. The intent required for 2. and 3. is `Guild Members`. For 1., you may want to enable partials³, otherwise you won't be getting any `messageReactionAdd` events and thus the collector won't work properly.

1) https://dis.gd/gwupdate
2) https://discord.com/developers/applications
3) https://discordjs.guide/popular-topics/partials

**Comment by snake-scaly** [comment]
@Vaporox thank you for your help! This explains my problems. However I don't quite understand how partials work. Maybe documentation is incomplete or I'm reading it incorrectly but here is a specific question.

E.g. I need to receive the `messageReactionAdd` event. This event has two parameters, a reaction and a user. So according to documentation I enable `['USER', 'REACTION']` partials. However with this I only receive events for cached messages. This kind of suggests that I also need the `MESSAGE` partial and indeed it works when I add it. But how do I tell beforehand? Is there any documentation on which partials are needed for which events?

Then documentation strongly insists that partial objects only contain IDs and nothing else. However when I enable `['USER', 'REACTION', 'MESSAGE']` and receive `messageReactionAdd` I get a partial `MessageReaction` which contains a partial `Message` which contains a valid `Guild` which contains a valid `GuildMemberManager` which I can use to successfully fetch a guild member. This seems to be intended because of the `MESSAGE` requirement. But goes contrary to documentation which insists that a partial objects needs to be fetched before use. Which is correct?

**Comment by Vaporox** [comment]
The partials you need depend on which structures you want to receive when they are uncached. `['USER', 'REACTION']` is theoretically enough to get reactions from uncached users, however if the message you are reactiong to is *also* not in the cache, you need to provide that `MESSAGE` partial accordingly.

Coming from Discord, partial messages only have `id`, `channel_id` and `guild_id` properties (i.e. the least amount of info you need to fetch the full structure). The reason why your partial message now has a full guild object is that per default, discord.js keeps all guilds in cache and so the guild can be assigned to the partial message. The documentation says that only IDs are *guaranteed* to be there – In fact, there are some more properties that could appear on a partial structure.

If you have any further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9).
