### ISSUE TITLE
presenceUpdate, guildMemberRemove seem to be not triggered anymore since 2 november

### ISSUE THREAD

**Issue by Identity-labs** [discordjs/discord.js#4998]
Hi, event seem to not be triggered since 2 nobember
I put simple console.log in presenceUpdate, guildMemberAdd, guildMemberRemove 

presenceUpdate was use to retreive twitch stream notification.

I'm still on version 11 of discordjs, with node 10, debian 10

**Comment by almostSouji** [comment]
see https://github.com/discordjs/discord.js/issues/4961
