### ISSUE TITLE
Failed to fetch all members before ready!

### ISSUE THREAD

**Issue by Vonjoll** [discordjs/discord.js#5004]
Please describe the problem you are having in as much detail as possible:

When using `fetchAllMembers` i am getting errors and constant WS disconnects and connects.

Errors:
`[WS => Manager] Failed to fetch all members before ready! Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
|     at /root/dismail/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16
|     at Timeout._onTimeout (/root/dismail/node_modules/discord.js/src/client/BaseClient.js:83:7)
 |     at listOnTimeout (internal/timers.js:549:17)
|     at processTimers (internal/timers.js:492:7)
`

`[WS => Shard 0] [CONNECT]
|     Gateway    : wss://gateway.discord.gg/
 |     Version    : 6
 |     Encoding   : json
 |     Compression: none
 | [WS => Shard 0] Setting a HELLO timeout for 20s.
| [WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 65ms
| [WS => Shard 0] Clearing the HELLO timeout.
 | [WS => Shard 0] Setting a heartbeat interval for 41250ms.
| [WS => Shard 0] [IDENTIFY] Shard 0/1
| [WS => Shard 0] [READY] Session 9f0a393dfcf3aafbf42ebfd4beddbd75.
 [WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
 [WS => Shard 0] Heartbeat acknowledged, latency of 270ms.
| [WS => Shard 0] Shard received all its guilds. Marking as fully ready.
| [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
| [WS => Shard 0] [CLOSE]
  |     Event Code: 1000
 |     Clean     : true
 [WS => Shard 0] Clearing the heartbeat interval.
 [WS => Shard 0] WS State: CLOSED
| [WS => Manager] Session Limit Information
|     Total: 1000
|     Remaining: 975
`

Include a reproducible code sample here, if possible:

`const client = new Discord.Client({ fetchAllMembers: true });`

Further details:

    discord.js version: ^12.4.1
    Node.js version: 14.12.0
    Operating system: Linux
    Priority this issue should have – High

Relevant client options:

    partials: none
    gateway intents: Guild Members
    other: none

    I have also tested the issue on latest master, commit hash:

**Comment by ArtanisTheOne** [comment]
I am also having this error,  and I realized that if I or someone else speaks it fetched those members but not those who havent spoken.

**Comment by almostSouji** [comment]
this is commonly caused by the changes outlined in #4961 , note that you don't need to provide the intents to the constructor (yet, you will with v13) but do have to be eligible for receiving the events (toggle in application settings or discord bot verification)

**Comment by Vonjoll** [comment]
> this is commonly caused by the changes outlined in #4961 , note that you don't need to provide the intents to the constructor (yet, you will with v13) but do have to be eligible for receiving the events (toggle in application settings or discord bot verification)

I have GUILD_MEMBER intent enabled, yet still receive this these errors.

Is this a current bug and will be fixed in an upcoming version?

Currently I am fetching all members per guild, in a delayed loop on READY to avoid these errors.

**Comment by iCrawl** [comment]
Going forward we are going to remove `fetchAllMembers`, so there will be no fix to this. Use different ways to get members if you need them that don't rely on this setting.

**Comment by zMelihStrqfe** [comment]
If your bot is verified and has intents, I am not recommend using `fetchAllMembers`.
