### ISSUE TITLE
message.reply doesn't tag user starting in v12.3.0

### ISSUE THREAD

**Issue by camprevail** [discordjs/discord.js#5005]
I encountered an issue where this code stopped tagging people with message.reply.
`await message.reply({files: ["image.png"]});`
I fixed it by adding an empty string like so:
`await message.reply("", {files: ["image.png"]});`

This change seems to have been introduced starting in discord.js@12.3.0. Not sure if this is a bug or not, so please advise.
Thanks.

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 14.15.0
- Operating system: Windows 10/Ubuntu 20
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: b8fd3f6

**Comment by monbrey** [comment]
Thanks for raising this, however given that `message.reply` is intended to be removed and replaced with Discord's upcoming inline replies feature, I don't see this as a bug that will be fixed.

**Comment by camprevail** [comment]
Ah okay, thanks for the heads up.

**Comment by auscompgeek** [comment]
Is there a tracking issue for inline replies support? I see Discord are rolling it out to more guilds now.

**Comment by advaith1** [comment]
Replies support is in PR #4874 and will be released in v13. (you can use the PR now but it changes `.reply` which is a breaking change)
