### ISSUE TITLE
.setImage(client.users.cache.find(client.user.id).displayAvatarURL({size: 2048, dynamic: true}))

### ISSUE THREAD

**Issue by Alexander1414x** [discordjs/discord.js#5006]
}else{
            const emb= new Discord.MessageEmbed()
            .setTitle(`${client.users.tag} avatar`)
            .setDescription(`Links:\n[png](${client.user.displayAvatarURL({format: "png", size: 2048})}) | [jpg](${client.user.displayAvatarURL({format: "jpg", size: 2048})}) | [gif](${client.user.displayAvatarURL({format: "gif", size: 2048, dynamic: true})}) | [webp](${client.user.displayAvatarURL({format: "webp", size: 2048})})`)
            .setColor(0x8b0000)
            .setTimestamp()
            .setFooter(client.users.tag)
            .setImage(client.users.cache.find(client.user.id).displayAvatarURL({size: 2048, dynamic: true}))
            message.channel.send(emb)
        }
}})

error 

```C:\Users\User\Desktop\tester\node_modules\@discordjs\collection\dist\index.js:161
            if (fn(val, key, this))
                ^

TypeError: fn is not a function
    at Map.find (C:\Users\User\Desktop\tester\node_modules\@discordjs\collection\dist\index.js:161:17)
    at Client.<anonymous> (C:\Users\User\Desktop\tester\command\moderate\avatartest.js:30:42)
    at Client.emit (node:events:339:22)```


version later version.

**Comment by almostSouji** [comment]
Collection#find, as per [documentation](https://discord.js.org/#/docs/collection/master/class/Collection?scrollTo=find) takes a function akin to Array#find of base JS, not a single value, hence that error.

That line is also completely obsolete, Client#user returns a ClientUser, which extends User, which has a `.displayAvatarURL()`, no need to circularly retrieve it from cache.

This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
