### ISSUE TITLE
Reaction collector does not collect custom emoji reactions

### ISSUE THREAD

**Issue by azbaron** [discordjs/discord.js#5007]
When using reaction collectors with custom server emoji's, on collect the reaction is not collected. It will react with custom, but not collect. Using unicode emoji's work perfectly.
Here is an example
```js
    let em = new MessageEmbed()
        .setDescription("Please select the reaction below: **on**.");
    let sentMsg = await message.channel.send(em);
    await sentMsg.react('<:On:771990310704250900>');

    const onFilter = (reaction, user) => {
    if (user.bot) return;
    return ['<:On:771990310704250900>'].includes(reaction.emoji.name) && user.id === message.author.id;
    };

    const onweek = sentMsg.createReactionCollector(onFilter, {max: 1, time: 60000});
    onweek.on('collect', async (r) => {
    message.channel.send("I see that");
    });
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 14.15.0
- Operating system: Windows 64bit
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by almostSouji** [comment]
custom emojis are of the format `<:name:id>`, you compare name against the entire emoji identifier, rather than its name. in your filter compare `reaction.emoji.name` against the name, or `reaction.emoji.id` against the id portion.
