### ISSUE TITLE
GuildMemberRoleManager typings incorrectly inherit from BaseManager

### ISSUE THREAD

**Issue by MitchTalmadge** [discordjs/discord.js#5009]
**Please describe the problem you are having in as much detail as possible:**
In [`index.d.ts`](https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/typings/index.d.ts), [`GuildMemberRoleManager`](https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/typings/index.d.ts#L1962) inherits from `OverridableManager`, which inherits from `BaseManager`, which implements functions such as `resolve` and `resolveID`. This causes these functions to be suggested while writing TypeScript bots. However, [the definition](https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/src/managers/GuildMemberRoleManager.js#L9) does not appear to inherit from anything, and in fact an error is thrown if the `BaseManager` methods are used:

```
TypeError: discordMember.roles.resolve is not a function
```

**Include a reproducible code sample here, if possible:**

Reproducing this is simple. Just get a `GuildMember` and name it `discordMember`. Begin typing `discordMember.roles.` and the following suggestions will appear:

![image](https://user-images.githubusercontent.com/8848080/99144928-6c732e80-2627-11eb-9ceb-7cdde70957b2.png)

As you can see, many of them are invalid. If you try to use a `BaseManager` method, it will throw an error at runtime.

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 15.2.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low, just an annoyance

**Relevant client options:**

- partials: N/A
- gateway intents: N/A
- other: N/A

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
This has been fixed with #5497. 🎉
