### ISSUE TITLE
unban me from the discord

### ISSUE THREAD

**Issue by HHServers** [discordjs/discord.js#5010]
i joined the discord for help and was immediately insulted by someone then got banned for responding?

blvxr#0420

**Comment by almostSouji** [comment]
Friend request and DM `Crawl#0002` or `Souji#0001` with an actual appeal and we will discuss it internally.
This issue tracker is only for bug reports and enhancement suggestions.

**Comment by HHServers** [comment]
still waiting for accept request 4 days later
