### ISSUE TITLE
roles.size issue (writing here as banned from Discord for no reason)

### ISSUE THREAD

**Issue by HHServers** [discordjs/discord.js#5011]
this code used to kick anyone who ONLY had 1 role (@everyone) now it does not - why?

https://gist.github.com/HHServers/e0fe5fa8510427595035d12959702a0d

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
