### ISSUE TITLE
Move ChannelType typings to within discord.js module

### ISSUE THREAD

**Issue by MitchTalmadge** [discordjs/discord.js#5015]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

The `ChannelType` enum typings are declared at the top of `typings/index.d.ts`, outside of the `discord.js` module. Thus, they appear at the root of all TypeScript projects which have discord.js in their packages. 

Type Definition:
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/typings/index.d.ts#L1-L10 

For example, if I import `discord.js` as follows:

```
import * as Discord from "discord.js";
```

then I would expect to access `ChannelType` as such:

```
let myType = Discord.ChannelType.text;
```

Instead, `ChannelType` appears at the root:

```
let myType = ChannelType.text;
```

and gives an error at runtime:

```
ReferenceError: ChannelType is not defined
```

**Describe the ideal solution**

Move `ChannelType` typings into the `discord.js` module.

**Describe alternatives you've considered**

I need to use this for `GuildCreateChannelOptions` as seen here:
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/typings/index.d.ts#L2562-L2565

So for now I just use the `any` type and assign `"text"` or `"voice"` as needed.

**Additional context**

I've noticed a near duplicate inside `Constants`:

https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/typings/index.d.ts#L556-L564

Not sure what to do with this.

**Comment by SpaceEEC** [comment]
As of #5456, you can now access the enum through `Constants.ChannelTypes`:
https://github.com/discordjs/discord.js/blob/a1f763ee75a7d906bbe727f616e33206dcc6792c/typings/index.d.ts#L663
