### ISSUE TITLE
Online Roles / Offline Roles status.

### ISSUE THREAD

**Issue by Alexander1414x** [discordjs/discord.js#5016]
I add special to guildMember.<roles>.status .

.addField('Status Roles', `${guildMember.roles.status}`) 
![image](https://user-images.githubusercontent.com/28537900/99229427-b2322180-27f6-11eb-84ba-e1673bbaad64.png)

But it doesnt identifying status Online Roles / Offline Roles.

**Comment by almostSouji** [comment]
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
