### ISSUE TITLE
Change RoleManager#create parameter

### ISSUE THREAD

**Issue by anandre** [discordjs/discord.js#5017]
**Is your feature request related to a problem? Please describe.**
The `data` object for the method is the only named parameter among the various `create` methods (for `GuildChannel`s, `Emoji`s, etc).  This inconsistency can lead to confusion for users - "why doesn't my code create a role with the specified name/color/etc?"

**Describe the ideal solution**
Change the parameter to be a single, unnamed object.  This may require putting the `reason` parameter into the object, like it is with `Guild#channels#create`.

**Comment by ManEatingTapir** [comment]
Looking at the docs, it seems that the parameter for `RoleManager#create` is a single object.

**Comment by anandre** [comment]
I meant the data object within it, wasn't very clear in the first post.

**Comment by ManEatingTapir** [comment]
Can you give an example of a situation where this inconsistency would cause confusion? From what I'm seeing the code is slightly different in `RoleManager#create`, but in actual use shouldn't have difference from what the `create` methods look like in other classes.
