### ISSUE TITLE
NewChannel#addFollower doesn't catch if client doesn't have Manage Webhooks

### ISSUE THREAD

**Issue by Fyrlex** [discordjs/discord.js#5018]
**Please describe the problem you are having in as much detail as possible:**
Of course I am not sure if this is intentional, but catching NewChannel#addFollower doesn't seem to detect if the client doesn't have Manage Webhooks. When I run this code when my client doesn't have Manage Webhooks, it still runs "Yo" but sends in console that the client doesn't have permissions.

**Include a reproducible code sample here, if possible:**
```js
announcementschannel.addFollower(channel.id, 'reason').then(() => {
  console.log("Yo")
}).catch(e=>{
  console.error("No")
})
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.x
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:
Not a huge issue, just instead the way to catch a permissions issue is manually checking the client permissions.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this, I am able to catch the rejection just fine.

<details><summary>The code I used</summary>

```js
const { Client } = require('discord.js');

const client = new Client();

client
    .on("message", message => {
        if (!message.author.bot && message.content === "follow") {
            client.channels.resolve("news channel id").addFollower("normal text channel id", "reason")
                .then(() => console.log("Worked"))
                .catch(error => console.log("Failed", error));
        }
    });


client.login("token");
```
</details>
