### ISSUE TITLE
guild.members.cache returning only one member, the bot

### ISSUE THREAD

**Issue by ChezCoder** [discordjs/discord.js#5023]
**Please describe the problem you are having in as much detail as possible:**
This just suddenly stopped working. In the `on ready` event, theres this line: `server = bot.guilds.cache.first();`. In a function, theres this line:
```javascript
function getMember(memberName) {
    let find;

    server.members.cache.each((member) => {
        if (member.user.username.toLowerCase() == memberName.toLowerCase()) {
            find = member;
        }
    });

    return find;
}
```
It used to return a user's member object, like so, `getMember("a_user")`, but now it just returns undefined :< this suddenly stopped working around last week, I thought my code was just buggy, turns out it's not because I didn't change a single thing in code.

**Further details:**

- discord.js version: latest version dw
- Node.js version: latest version dw
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by monbrey** [comment]
**Events for privileged intents are not sent if not enabled:**
- Discords FAQ on this change: <https://dis.gd/gwupdate>
- your bot is verified? <https://dis.gd/contact> (and tell them which privileged intents you need and why)
- your bot is __not__ verified? toggle the switches in <https://discord.com/developers/applications> (image)
- you do __not__ need to provide intents in client options, discord sends all events if no intents are provided.
- If you are on v11 and experience issues: **update to v12**, we no longer support v11.

**Comment by almostSouji** [comment]
for some more info see https://github.com/discordjs/discord.js/issues/4961
