### ISSUE TITLE
Fetching users from role without cache

### ISSUE THREAD

**Issue by BaptisteDeporte** [discordjs/discord.js#5028]
**Fetch users from role**
I'm using my discord bot to fetch all users from a specific role and I can't fetch all those users from the Role object without using the cache which is incomplete

**Same system as GuildMemberManager**
I already use the fetch on this class with the force input for without checking the cache. I think it would be a great idea to have this class instead of a Map of GuildMember. For exemple :

```js
role.members.fetch({ force: true })
  .then(console.log)
  .catch(console.error)
```

**Comment by advaith1** [comment]
This isn't a Discord feature so there isn't anything for discord.js to add, you would have to fetch all the guild members

(looks like Discord might be working on this but it's not released/documented)

**Comment by BaptisteDeporte** [comment]
Oh, ok thank you for your response !
