### ISSUE TITLE
Add raw data to 'DiscordAPIError'

### ISSUE THREAD

**Issue by antoine-pous** [discordjs/discord.js#5032]
**Is your feature request related to a problem? Please describe.**
Actually `DiscordAPIError` lack of the original payload submitted (excluding sensitive data). Including them will allow us to perform actions on specific errors depending of the context which would be incredibly useful.

**Describe the ideal solution**
The solution would simply to add the raw payload and letting us dealing with it if we want

**Additional context**
Start a bot, block him and request an action which send PM. The bot will encounter a 403 error from Discord APIs, with the raw payload we can make a generic system on top of our app painless to notify the user that the bot is blocked by the dest where the command was sent from.

There's a lot of use cases where having the raw payload would be incredibly useful, maybe you should consider adding an option during the client instantiation to don't add the payload by default on all `DiscordAPIError`.

**Comment by SpaceEEC** [comment]
This has been implemented with #5701 🎉
