### ISSUE TITLE
FATAL ERROR with NAPI extension

### ISSUE THREAD

**Issue by Roguyt** [discordjs/discord.js#5036]
Hello everyone,

I'm having troubles finding out why this error keeps popping randomly in some really rare occasions.
What happens is that my Bot is creating a createWriteStream with a manual createStream and then out of nowhere the bot crashes with this error which isn't even logged in the error event: `FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw`.

My guess is that it is related to the native part of @discord/opus but I'm a bit lost on how to debug it / fix it since it's out of the scope of my project and it doesn't provide any meaningful logs.
The fact it appears randomly is even more bothersome to debug.

**Further details:**

- discord.js version: ^12.4.1 / Opus: ^0.3.3
- Node.js version: lts / 14.15.1-stretch
- Operating system: Debian / Docker
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: @typeit/discord: ^4.0.8

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Could you include a code sample so we can see how you are creating the stream and what you do with the stream afterwards?

**Comment by Roguyt** [comment]
Sure thing

```ts
channel.join().then(async (connection) => {
    // Play some mute sound to get sounds from players
    await VoiceChannelUtils.playSilence(connection);

    connection.on('speaking', (user, speaking) => {
        if (user && speaking && !BotRecorder.users[user.id]) {
            const outputPath = FileUtils.generateFileName(
                channel.name,
                BotRecorder.startTime,
                user.username
            );
            FileUtils.createFolders(outputPath);

            // Doing it this way since the end event of fluent-ffmpeg doesn't work
            if (!BotRecorder.toConvert[user.id]) BotRecorder.toConvert[user.id] = [];
            BotRecorder.toConvert[user.id].push(outputPath.fullPath);

            const audio = connection.receiver.createStream(user, { mode: 'pcm', end: 'manual' });
            audio
                .pipe(fs.createWriteStream(`${outputPath.fullPath}.pcm`))
                .on('error', (e) => Index.logger.error(e));
            BotRecorder.users[user.id] = audio;
            Index.logger.info(`Starting to record ${user.username}`);
        }
    });
});
```

And the stream are destroyed whenever the user leave the channel using the voiceStateUpdate event:

```ts
const oldUserChannel = oldMember.channelID;
const oldUsername = oldMember.member.user.username;
const oldUserId = oldMember.member.user.id;

// The user left the channel so we're stopping the recording
if (oldUserChannel === BotRecorder.channelId) {
    if (BotRecorder.users[oldUserId]) {
        BotRecorder.users[oldUserId].destroy();
        delete BotRecorder.users[oldUserId];

        Index.logger.info(`Stopped a recording because ${oldUsername} left`);
    }
}
```

After that the PCM are stored and queue to be converted later on by another worker.
