### ISSUE TITLE
Docs for Guild#joinedTimestamp and GuildMember#joinedTimestamp say they return a "timestamp" when they actually return the number of milliseconds since the Unix epoch

### ISSUE THREAD

**Issue by aimorris** [discordjs/discord.js#5042]
**Is your feature request related to a problem? Please describe.**
The documentation entries of [GuildMember#joinedTimestamp](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=joinedTimestamp) [Guild#joinedTimestamp](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=joinedTimestamp) are, respectively,
<img src="https://user-images.githubusercontent.com/1687121/100156286-59e4d900-2ef4-11eb-8c99-eb33a2051171.png" width="300" />
and
<img src="https://user-images.githubusercontent.com/1687121/100156318-623d1400-2ef4-11eb-9c12-9854ab63b300.png" width="300" />

Does it make sense to say that `.joinedTimestamp` returns "The timestamp the member joined the guild at" (while returning a number) when it actually returns the number of milliseconds since the Unix epoch that the member joined the guild at?

**Describe the ideal solution**
Reword the documentation so that it doesn't say that it returns a timestamp when it actually returns the number of milliseconds since the Unix epoch.

**Describe alternatives you've considered**
`.joinedTimestamp` returns an object:
```js
{
    day: 05,
    month: 03,
    year: 2020,
    hour: 14,
    minute: 13
}
```

**Comment by tipakA** [comment]
Timestamp *is* literally a number. Why would it be object? `joinedAt` gives you `Date` object, and you can always use the timestamp to create one as well.
