### ISSUE TITLE
GuildMember.send docs actually TextChannel.send docs

### ISSUE THREAD

**Issue by GingkathFox** [discordjs/discord.js#5043]
**Please describe the problem you are having in as much detail as possible:**
The GuildChannel.send method documentation is actually the documentation for the TextChannel.send method.

![Screen Shot 2020-11-24 at 6 05 44 PM](https://user-images.githubusercontent.com/33764485/100161555-ad690f80-2e7f-11eb-8a22-f5a30c22643b.png)

[Link to relevant section](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=send)

**Comment by tipakA** [comment]
![image](https://user-images.githubusercontent.com/31581159/100167533-93e7b800-2ebf-11eb-83be-961a23ad05a1.png)  
That is not `GuildChannel`. That is `GuildMember` which has a `send` method implemented from the `TextBasedChannel` class, as the page heading suggests:  
![image](https://user-images.githubusercontent.com/31581159/100167630-c7c2dd80-2ebf-11eb-99a7-8d18a3d2d264.png)

**Comment by GingkathFox** [comment]
@tipakA Sorry, i mixed myself up. @almostSouji why close this? shouldn't the example have `GuildMember.send` rather than `channel.send`?

**Comment by monbrey** [comment]
It's closed because the documentation comes from a single place, because the method is only written in a single place in the source-code: `TextBasedChannel#send()`

GuildMember does not have its own different send method, and therefore does not get its own docs.

**Comment by GingkathFox** [comment]
ah ok, thanks!
