### ISSUE TITLE
11/25/2020 - Random User Presence Issue

### ISSUE THREAD

**Issue by devlemire** [discordjs/discord.js#5044]
discord.js version 12.5.0

Hey team,

Out of the blue my bot stopped working, no code changes on my end, and upon investigation I've found something strange in the User.presence.status value. Even if my client is set to online it is returning "offline" for all users. 

Not sure if this a hiccup on Discord's side or not. Like I said, I haven't made any code changes and out of the blue it stopped reading the online status correctly. 

Basically my bot skips its internal logic if the User.presence.status === 'offline'

**_Is any one else seeing this behavior?_**

```js
bot.on('message', (eventObj) => messageHandler(eventObj, botUser))

messageHandler = (eventObj, botUser = { id: undefined }) => {
  const msg = eventObj.content.trim().toLowerCase()
  const type = eventObj.channel.type
  const isCommand = msg.startsWith('!')
  const authorId = eventObj.author.id
  const commonLogCheck = debugLogs === 'true' && authorId !== botUser.id

  if (eventObj.author.presence.status === 'offline') {
    if (commonLogCheck) {
      console.log('The user is offline, disregarding message')
    }

    return
  }

  ........other code below..............
}
```

**Comment by almostSouji** [comment]
Discord has recently changed how presences are distributed and require you to be granted an intent in order to do so. for now you don't need to provide intents in the Client constructor, though that will change with version 13.

see https://github.com/discordjs/discord.js/issues/4961 for more information.
