### ISSUE TITLE
get all users boost from the server

### ISSUE THREAD

**Issue by SnaffX** [discordjs/discord.js#5045]
**Is your feature request related to a problem? Please describe.**
The lack of booster information on the server

**Describe the ideal solution**
Addition of an Object on the server with all booster users and the amount of boost

**Comment by Fyko** [comment]
There is no way to determine how many boosts a user has to any specific guild. The only information Discord gives us is how long they've been boosting.
```ts
const members = await <guild>.members.fetch();
const boosters = members.filter(m => m.premiumSinceTimestamp);
```

**Comment by SpaceEEC** [comment]
There is an issue on discord's api docs issue tracker for the amount of boosts per user: https://github.com/discord/discord-api-docs/issues/1182

**Comment by SnaffX** [comment]
in the future could be added the amount of boost per user on the server?

**Comment by SpaceEEC** [comment]
That is on Discord to do, see the issue I linked.
Once they expose that data somehow, we can add support for that.
