### ISSUE TITLE
Improve documentation for TextChannel#startTyping and TextChannel#stopTyping

### ISSUE THREAD

**Issue by Ayfri** [discordjs/discord.js#5058]
**Is your feature request related to a problem? Please describe.**
I needed to ask in the discord.js server how to use these methods because the docs don't help to understand these, having trouble to understand the `typing count` concept.

**Describe the ideal solution**
Explain what it is doing internally and when to put the `typing count` argument.

**Describe alternatives you've considered**
Remove the `typing count` concept (as it is not that used).

**Additional context**

**Comment by JS00001** [comment]
https://i.imgur.com/GPpIuYH.png

I believe it has been updated

**Comment by almostSouji** [comment]
I'm not too sure how we could improve the documentation? It quite clearly states that it starts a typing indicator which resolves after this indicator has stopped gracefully or rejects when an error occurs. The documentation for stopTyping shows how to stop them and details that it needs to be called as often as start has been called (alternatively the force can be passed to stop regardless of count). The examples in each section are comprehensively showing the usage of the method, with comments explaining what they do.

What exactly did you not understand in the docs as they are? Just saying "they didn't help" unfortunately doesn't really help us to improve it either.

**Comment by Ayfri** [comment]
The problem is, what are typing counts, and what is their use?

**Comment by almostSouji** [comment]
Start one per message received, stop one per message answered -> in the end you're done typing when all answers are out. But I'm not sure how we could make that clearer than what's already there - so if you do have an idea about how to improve the documentation do let us know!

**Comment by Ayfri** [comment]
You could add something like this: _"You can also send a message to stop one typing count."_

**Comment by almostSouji** [comment]
I think you misunderstood. It's not that sending a message automatically resolves a typing instance. I was trying to outline an example of when this system of starting instances and resolving them separately might come in handy to keep typing while "things are still happening".

You will still have to call `.stopTyping()`
