### ISSUE TITLE
Implementation of new Replies functionality

### ISSUE THREAD

**Issue by tinfoilboy** [discordjs/discord.js#5071]
**Is your feature request related to a problem? Please describe.**
Discord has released the new replies feature for servers I believe about a week ago. I was looking to use that feature for my bot, however it does not seem like this library supports it yet, nor is there an issue/PR for it (I could actually most likely contribute the PR for this, just was making sure that it's not already in progress or the way that it should be done more than anything).

**Describe the ideal solution**
Adding a reply function for messages that leverages the new Reply flow, either off of the existing `Message.reply` method or making a new one like `Message.threadReply`.

**Describe alternatives you've considered**
There is the `Message.reply` function, however it looks messier compared to an actual threaded reply.

**Comment by almostSouji** [comment]
inline replies will be introduced in version 13 with https://github.com/discordjs/discord.js/pull/4874

**Comment by tinfoilboy** [comment]
Ah, I must have missed that issue 😆. Looks like in the issue the author of the original PR was looking to backport it themselves, however if that's not the case anymore definitely contribute towards that. Noted on the `thread` terminology as well. Would `replyInline` be a better function name in that case?

**Comment by kylerchin** [comment]
idk why but that PR has been sitting there for the last 2 weeks with no one working on it. I'm sure many bot devs are itching for it now...

**Comment by tipakA** [comment]
The PR that adds replies cannot be merged into v12, as it *replaces* current `message.reply()`.  
If you want to test it / need it so badly, no one stops you from installing the fork and using it.

**Comment by kylerchin** [comment]
thanks @tipakA! Will it be merged into 13 or something? And is there like a timeline for it?

**Comment by tipakA** [comment]
Yes, inline replies will arrive with v13, as Souji said in comment above (https://github.com/discordjs/discord.js/issues/5071#issuecomment-736886138).  

There is no timeline for v13 though.
