### ISSUE TITLE
Client#api queries casts "null" and "undefined" to their actual value instead of counting them as a string

### ISSUE THREAD

**Issue by VoltrexMaster** [discordjs/discord.js#5072]
**Please describe the problem you are having in as much detail as possible:**

So i've been trying to play around with `<client>.api` and noticed the weird behavior of the query value changing in an unexpected way if given "null" and "undefined" as their value, as you see on the screenehot:
![Screenshot_20201202-061204_Discord](https://user-images.githubusercontent.com/62040526/100828730-071b9c00-3475-11eb-92a4-ffb536b5b191.jpg)
first i tried null as a string and it causes a `DiscordAPIError` instead of returning the expected array of members, also tried with multiple other values as you see on the screenshot:
![Screenshot_20201202-063240_Discord](https://user-images.githubusercontent.com/62040526/100828833-48ac4700-3475-11eb-99d7-cea79fa3b7df.jpg)
as "null", "undefined" and "voltrex" and as you see, both of the "null" and "undefined" were casted to their original value and not considered a string while "voltrex" did work, however, doing a raw api request using `node-fetch` as you see on the screenshot:
![Screenshot_20201202-072228_Discord](https://user-images.githubusercontent.com/62040526/100828926-83ae7a80-3475-11eb-838e-1e8e91224ad0.jpg)
with the same values, all are successful without returning an error

**Include a reproducible code sample here, if possible:**

```js
// Using <client>.api
<client>.api.guilds(<ID>).members.search.get({
query: {
query: "null",
limit: 1
}
}); // DiscordAPIError: Invalid Form Body query: This field is required

// Using node-fetch
<node-fetch>("https://discord.com/api/guilds/<ID>/members/search?query=null&limit=1", {
headers: {
Authorization: "Bot <Your bot token here>"
}
}).then(res => res.json()); // Returns an array of members as expected
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: v14.9.0
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: 1935
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by BannerBomb** [comment]
I found the issue to be that here, the string form of null and undefined are being filtered out.
https://github.com/discordjs/discord.js/blob/9f3c3e091844d22793cfd2880ffc2936ce41feab/src/rest/APIRequest.js#L23
