### ISSUE TITLE
Ability to disable caching users & members

### ISSUE THREAD

**Issue by GamingGeek** [discordjs/discord.js#5074]
**Is your feature request related to a problem? Please describe.**
Yes. discord.js member & user caching is causing issues with CPU & memory usage for me with memory usage starting ~50-65mb but then will start climbing to ~250mb then presumably gets gc'd back down to ~60mb and CPU usage starting at ~2-10% but then goes up to anywhere from 20-250% (yes, you read that correctly. I'm assuming it's a combined count across all cores)

**Describe the ideal solution**
The ability to disable user & member caching (ideally excluding the client user & corresponding members so permission checks are easier). Discord are pushing a more stateless approach for Discord bots and d.js can happily operate without it so I see no reason why there can't be a boolean in the client options to disable both/just one of user & member caching.

**Describe alternatives you've considered**
Sweeping the caches every so often. This still causes some spikes here and there but on a much smaller scale but it'd be nicer to just disable it completely.

**Additional context**
6 hour overview of CPU & memory usage:
![image](https://user-images.githubusercontent.com/29981918/100955961-6fb75700-350f-11eb-8af8-a90cb7b53f05.png)

5 minute overview:
![image](https://user-images.githubusercontent.com/29981918/100955976-78a82880-350f-11eb-975c-c252849da30e.png)

Sweeping both member & user caches caused CPU usage to return to normal
![image](https://user-images.githubusercontent.com/29981918/100955981-7ba31900-350f-11eb-8f78-dba5d30bd022.png)

CPU Usage at it's highest:
![image](https://user-images.githubusercontent.com/29981918/100956174-d177c100-350f-11eb-9ec6-9d1d5880a386.png)

**Comment by BannerBomb** [comment]
Just a small suggestion to add to this, what about the option to disable the emoji cache also? I'm not sure how much memory the emoji cache takes up on large bots, but emojis aren't necessarily used for anything crucial afaik except for getting information on the emoji, modifying it or checking if a server has an emoji.
And if needed emojis can be fetched from `GET /:guildID/emojis/:emojiID` to fetch a single one and leave out the `/:emojiID` to fetch all of the servers emojis.

**Comment by mozartrafi** [comment]
Isn't that already what it does?

**Comment by GamingGeek** [comment]
> Isn't that already what it does?

No? You can't disable user or member cache. The only cache you can disable (afaik) is the message cache by setting messageCacheMaxSize to 0.

**Comment by iCrawl** [comment]
I doubt this can be implemented in any useful or proper way in the current iteration.

Might be worth considering for djs-next.

**Comment by GamingGeek** [comment]
> I doubt this can be implemented in any useful or proper way in the current iteration.

What about using LimitedCollection just like in MessageManager? You could then have the same options for sweeping, lifetime etc. as messages or just an all or nothing approach

**Comment by iCrawl** [comment]
Maybe.

The all or nothing approach is not gonna happen though. There is no point in doing this and breaking half of the library.

**Comment by sysollie** [comment]
There is [a cacheless fork of Discord.JS on NPM](https://www.npmjs.com/package/discord.js-light). Although, I have only used it a bit so can't recommend it.

**Comment by GamingGeek** [comment]
> There is [a cacheless fork of Discord.JS on NPM](https://www.npmjs.com/package/discord.js-light). Although, I have only used it a bit so can't recommend it.

Can't use this with a framework like discord-akairo

**Comment by Sazzo** [comment]
Just to comment, the same problem here, the use of Memory goes up and down all the time, the bot starts with 40mb and can go down and up to 200mb

**Comment by Deivu** [comment]
For now, You could theoretically mess with Discord.JS internal caches by just tapping in the class structures yourselves and do your thing there. The main drawback is, when they make a breaking change on the part you modified, you may need to implement or think about it yourself to fix it. Also I didn't try nor dare to uncache channels as that might just bring more problems in Vanilla D.JS implementation

**Comment by bound2** [comment]
Cache also seems to not update when user changes his nickname. Since I needed to fetch up to date data from discord, I added following hack, to circumvent stale data in the cache.
```
const guild = await this.client.guilds.fetch(serverId);
if (guild.members.cache.has(userId)) {
    guild.members.cache.delete(userId);
}
const member = await guild.members.fetch(userId);
```
NB! This doesn't fix high memory usage reported in the original issue. Posting it here as it's top result in Google.

**Comment by Sazzo** [comment]
> Cache also seems to not update when user changes his nickname. Since I needed to fetch up to date data from discord, I added following hack, to circumvent stale data in the cache.
> 
> ```
> const guild = await this.client.guilds.fetch(serverId);
> if (guild.members.cache.has(userId)) {
>     guild.members.cache.delete(userId);
> }
> const member = await guild.members.fetch(userId);
> ```
> 
> NB! This doesn't fix high memory usage reported in the original issue. Posting it here as it's top result in Google.

I imagine that for this case (which looks like a bug), it is good to open a separate issue.

**Comment by 1Computer1** [comment]
I told you dummies that Managers would be useful one day 🚀🚀🚀🚀🚀🚀🚀
