### ISSUE TITLE
TypeError: Discord.VoiceChannel.join is not a function

### ISSUE THREAD

**Issue by DayvTV** [discordjs/discord.js#5077]
<! -
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.
->

** Please describe the problem you are having in as much detail as possible: **
Hi, I'm kind of new to programming and I'm making a music bot for discord. However, I am getting the following error: TypeError: Discord.VoiceChannel.join is not a function

** Include a reproducible code sample here, if possible: **

`` js
// Place your code here
``
const Discord = require ("discord.js");
const bot = new Discord.Client ();
const ytdl = require ("ytdl-core");
const streamOptions = {seek: 0, volume: 1};
const token = "////////////////////////////////";

bot.login (token);

bot.on ("ready", () => {
  console.log ("I'm ready to be used!");
});

bot.on ("message", (msg) => {
  if (msg.author.bot) {
    return;
  }

  if (
    msg.content.indexOf ("youtube")! == -1 &&
    msg.content.toLowerCase (). startsWith ("? play")
  ) {
    let CompleteMessage = msg.content.split ("");
    let youtubeLink = CompleteMessage [1];
  }

  let VoiceChannel = msg.guild.channels.cache.find (
    (channel) => channel.id === "731304807192592538"
  );

  if (VoiceChannel == null) {
    console.log ("Oops! Channel not found!");
  }

  if (VoiceChannel! == null) {
    console.log ("Channel found !!!");

    Discord.VoiceChannel.join ()

      .then ((connection) => {
        const stream = ytdl (youtubeLink, {filter: "audioonly"});

        const DJ = connection.playStream (stream, streamOptions);

        DJ.on ("end", (end) => {
          VoiceChannel.leave ();
        });
      })
      .catch (console.error);
  }
});

** Further details: **

- discord.js version: 12.5.1
- VS Code version: 14.15.1
- Operating system: Windows 10
- Priority this issue should have - please be realistic and elaborate if possible:

** Relevant client options: **

- partials: none
- gateway intents: none
- other: none

<! -
If this applies to you, please check the respective checkbox: [] becomes [x].
You don't have to modify the text to suit your particular situation - if you want to
elaborate, please do so in the description.
While it's not a requirement to test your issue on the master branch, it would make fixing
the problem a lot easier for us, so please do so if possible.
->

- [] I have also tested the issue on latest master, commit hash:

**Comment by DayvTV** [comment]
and i regenerated the token of my bot

**Comment by anandre** [comment]
You should not be using the structures from the library itself, but instead the ones from the cache as you define in your code, `let VoiceChannel = ...` that one.  Please join the server if you need more support.

**If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.**

**Comment by DayvTV** [comment]
> You should not be using the structures from the library itself, but instead the ones from the cache as you define in your code, `let VoiceChannel = ...` that one. Please join the server if you need more support.
> 
> **If you need help with discord.js installation or usage, please go to the discord.js Discord server instead: https://discord.gg/bRCvFy9 This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.**

Ah, sorry... I didn't understand it so well
