### ISSUE TITLE
Unable to fetch >1300 invites and receiving no invite events

### ISSUE THREAD

**Issue by sysollie** [discordjs/discord.js#5088]
**Please describe the problem you are having in as much detail as possible:** My bot is unable to receive any invite events from large servers and only receives around 1300 invites when using `<Guild>.fetchInvites()`. The server that is having the issue has upwards of 200000 members. Could this be a Discord limitation or is Discord.JS breaking somewhere?

**Include a reproducible code sample here, if possible:**
```js
var Discord = require('discord.js');
var client = new Discord.Client();

client.on('ready', async() => {
    var invites = await client.guilds.cache.get('452237221840551938').fetchInvites();
    console.log(invites.size); // never returns over 1300
});

client.on('inviteCreate', (invite) => {
    console.log(invite); // never fired in a server with over 200000 members
});
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.15.1
- Operating system: Ubuntu Server 20.04.1 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Low - doesn't effect many Discord.JS users

**Relevant client options:**

- partials: none
- gateway intents: Tried explicitly subscribing for invite events and without any at all
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
> // never fired in a server with over 200000 members

As per [documentation](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-inviteCreate): 

> This event only triggers if the client has MANAGE_GUILD permissions for the guild, or MANAGE_CHANNEL permissions for the channel.

Please verify that this is the case. The event emitting should not be affected by server size. If you are providing intents to the Client constructor do make sure that you have specified `GUILD_INVITES` - not providing any is also valid, as long as the `GUILD_INVITES` endpoint is not restricted.

--- 

As for the fetched amount: That seems strange, as per  [`GET /guilds/{guild.id}/invites`](https://discord.com/developers/docs/resources/guild#get-guild-invites)  I can't find any restriction in terms of amount. Unfortunately an issue that just arises in servers of that magnitude is rather hard to reproduce and verify for us.

You can try to log `inviteItems.length` after l. 804, though I can't find any room for library error here.

https://github.com/discordjs/discord.js/blob/8a7abc9f06d44bf693e35a615bb6ba2c3eb1d6e7/src/structures/Guild.js#L800-L812

The daunting looking

```
this.client.api
      .guilds(this.id)
      .invites.get()
```

really just calls the [`GET /guilds/{guild.id}/invites`](https://discord.com/developers/docs/resources/guild#get-guild-invites) endpoint

**Comment by almostSouji** [comment]
As per nights answer in the linked issue on discord-api-docs there is a soft limit of ~1000 meaning those will be all invites.
