### ISSUE TITLE
bulkDelete seems to have changed

### ISSUE THREAD

**Issue by dcsan** [discordjs/discord.js#5089]
This maybe a Discord API change, but not sure so I'm 

I'm using the master branch (before release) and `channle.bulkDelete(count)` appears to have changed

to basically delete a conversation, I've been running `bulkDelete(100)` on a large number 
previously it would delete everything it could, and then throw an API error, for example "you can't delete messages over 14 days old"
but all the *other* messages up to the fail point would get deleted.

now it seems if there's a single fail at the API then everything fails.

updated code below will just keep iterating, but it's really slow deleting one message at a time
(ha, not "bulkDelete") but doing bulkDelete just fails out so ...

```ts
  // --------- admin commands ----------
  async clearChannel() {
    if (!this.isAdmin()) {
      await this.sendText('you need to be an admin to use that!')
      logger.warn("blocked admin clearChannel")
      return
    }
    const message = this.lastEvent
    if (message.channel.type !== 'text') {
      return logger.warn('cannot clear channel type', message.channel.type)
    }
    let c
    try {
      // FIXME - the error isn't throwing properly it exits the loop instead and doesnt catch
      const count = 1
      const ch = message.channel as TextChannel
      logger.log('clear for channel', ch.name)
      for (c = 0; c < 250; c++) {
        logger.log('delete.c=', c)
        const deleted = await ch!.bulkDelete(count)
          .catch(console.error) // FIXME - breaks to "done" if this isn't here?
          .then((result) => console.error('clear result', result))

        logger.log('deleted', c, deleted)
        // if (deleted?.size < 1) {
        //   logger.log('no more to clear at c =', c)
        //   break
        // }
      }
      // message.delete();
    } catch (err) {
      logger.warn('clear exit at c=', c, err)
    }
    logger.log('clear done at c=', c)
  }
```

**Further details:**

- discord.js version:      "discord.js": "git+https://github.com/discordjs/discord.js.git#master",

installed with 
	npm i -S "https://github.com/discordjs/discord.js#master"

- Node.js version: 13.x 
- Operating system: macox
- Priority this issue should have – please be realistic and elaborate if possible:
low

**Relevant client options:**

- [x] I have also tested the issue on latest master, commit hash:

```json
    "discord.js": {
      "version": "git+https://github.com/discordjs/discord.js.git#2685b960d7bbf47d7884545ad06aec8160907342",
      "from": "git+https://github.com/discordjs/discord.js.git#master",
```

**Comment by tipakA** [comment]
👀
![image](https://user-images.githubusercontent.com/31581159/101588235-363a8c00-39e6-11eb-83fe-362817487a83.png)
