### ISSUE TITLE
List of Users

### ISSUE THREAD

**Issue by entres999** [discordjs/discord.js#5093]
I would like to get a list of all users in a specific Discord Server. I would really need an example of code if there is a way of how to get the list I'm looking for.

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
