### ISSUE TITLE
Voice receive not working for audio from browser clients

### ISSUE THREAD

**Issue by henrymxu** [discordjs/discord.js#5105]
**Please describe the problem you are having in as much detail as possible:**

- Discord JS is causing a crash due to attempting to decode corrupt compressed data from voice receiving.  I believe it is due to users connecting from browser (as opposed to client).  

- discordjs/opus is being used

**Error Log:**

```js
/evebot/node_modules/prism-media/src/opus/Opus.js:64
    return this.encoder.decode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
                        ^
TypeError: The compressed data passed is corrupted
    at Decoder._decode (evebot/node_modules/prism-media/src/opus/Opus.js:64:25)
    at Decoder._transform (evebot/node_modules/prism-media/src/opus/Opus.js:189:20)
    at Decoder.Transform._read (_stream_transform.js:191:10)
    at Decoder.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Decoder.Writable.write (_stream_writable.js:318:11)
    at Readable.ondata (_stream_readable.js:695:22)
    at Readable.emit (events.js:310:20)
    at Readable.EventEmitter.emit (domain.js:482:12)
```

[Receiver](https://github.com/discordjs/discord.js/blob/master/src/client/voice/receiver/Receiver.js) is the source of the issue.

```
  createStream(user, { mode = 'opus', end = 'silence' } = {}) {
    user = this.connection.client.users.resolve(user);
    if (!user) throw new Error('VOICE_USER_MISSING');
    const stream = this.packets.makeStream(user.id, end);
    if (mode === 'pcm') {
      const decoder = new prism.opus.Decoder({ channels: 2, rate: 48000, frameSize: 960 });
      stream.pipe(decoder);
      return decoder;
    }
    return stream;
  }
}
```

Error originates from [discordjs/opus](https://github.com/discordjs/opus/blob/d2df1ca5ee0bd4a9f3bf4f929327f0d002d5e6ac/src/node-opus.cc#L15)

```
if (decodedSamples < 0) {
	Napi::TypeError::New(env, getDecodeError(decodedSamples)).ThrowAsJavaScriptException();
}
```

**Further details:**
Not sure if it is fixable (i.e allowing browser packets), but it should not crash the bot

- discord.js version: 12.5.1
- Node.js version: 14.15.1
- Operating system: MacOS
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by henrymxu** [comment]
Leaving this here as a potential fix? https://stackoverflow.com/questions/21771220/error-handling-with-node-js-streams.  Allowing the user to pass an error handler to the `createStream` function instead of having DiscordJS throw the exception, since errors are not propagated through pipes.  I can implement this if you believe it is a valid solution.

**Comment by henrymxu** [comment]
A temporary work around would be to set the `mode` parameter in the `createStream` to `opus` and then manually decode the stream to `pcm` in order to handle the error

**Comment by Wahat** [comment]
Another developer also had this issue as well and it seems to be only on Chrome: https://github.com/discordjs/discord.js/issues/5019#issuecomment-734709305

**Comment by henrymxu** [comment]
In prism media, the exception thrown while [decoding](https://github.com/amishshah/prism-media/blob/0dea3cb80f8a9e4c9fec166d666e84b8506ad81e/src/opus/Opus.js#L203) is not caught.  I think added a try catch around the decoding will resolve the crash.  Passing the error to the transform stream callback will allow the developer to be notified of the error as well. [Reference](https://nodejs.org/api/stream.html#stream_transform_transform_chunk_encoding_callback)

**Comment by Scraayp** [comment]
Got this issue too!

**Comment by PaulBernhardt** [comment]
I just ran into this issue as well, definitely seems to be from browser users. Obviously it would be ideal if this could handle streams from the browser with no problem, but being able to either handle the error and not crash, or a way to detect a browser user and opt out of handling their voice entirely would be helpful.

**Comment by amishshah** [comment]
Hi everyone,

As you're aware voice receive isn't officially documented for bot accounts by Discord. So far, I've made changes where possible to allow for voice receive to still function as the changes required were fairly minor.

This seems a little more involved than previous breakages. I can't really justify spending the time needed to fix this issue given that voice receiving is undocumented and there is nothing to stop this from breaking again in the future. For now, I will leave the issue open in case anyone is willing to look into a fix for this.

Sorry that I'm unable to fix the issue at this moment!

**Comment by Silverwolf90** [comment]
I am also experiencing this error (just with Chrome).

With a bit of stabbing in the dark I got it working with Chrome by commenting out [line 76  in `PacketHandler.js`](https://github.com/discordjs/discord.js/blob/master/src/client/voice/receiver/PacketHandler.js#L76). But the clients that were previously working now cause discord.js to crash.

So perhaps it has to do with this "undocumented Discord byte" and it's presence/absence? Don't really know, I was just throwing shit at the wall, but maybe this information could help someone.
