### ISSUE TITLE
only 1 shard working

### ISSUE THREAD

**Issue by Akurejs** [discordjs/discord.js#5107]
I would like to use this function, to activate a command for members who are on my support server with a specific role, for them to use on their server, they need to have a role on my server, but it only works in 1 shard, which is the fragment where my server is and the other fragments don't work, can someone help me work on all fragments?

```
function isSupporter(user) {
  const homeGuild = bot.guilds.cache.get('761296886907797515');
  if (!homeGuild) return console.error('Couldn\'t find the bots guild!');

  const member = homeGuild.member(user);
  if (!member) return false;

  const role = member.roles.cache.find(role => role.name === 'Patreon');
  if (!role) return false;

  return true;
}
     
if (!isSupporter(message.author)) {
  return message.channel.send(':x: This command is restricted to Patreon supporters.')
    .catch(console.error);

```

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
