### ISSUE TITLE
Discord.js musicbot doesn't work, help me 

### ISSUE THREAD

**Issue by Condorucci** [discordjs/discord.js#5109]
my musicbot of discord doesn't work, please help me
this is the code and commands:

const Discord = require("discord.js"),
client = new Discord.Client(),
settings = {
prefix: "!",
token: "censored my token"
};

const { Player } = require("discord-player");
const player = new Player(client);
client.player = player;
client.player.on('trackStart', (message, track) => message.channel.send(Now playing ${track.title}...))

client.on("ready", () => {
console.log("I'm ready !");
});

client.on("message", async (message) => {

const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
const command = args.shift().toLowerCase();
if(command === "play"){
    client.player.play(message, args[0], message.member.user);
    // as we registered the event above, no need to send a success message here
}
});

client.login(settings.token);

PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato>
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato>

**Comment by Condorucci** [comment]
const Discord = require("discord.js"),
client = new Discord.Client(),
settings = {
    prefix: "!",
    token: "censored my token"
};
 
const { Player } = require("discord-player");
const player = new Player(client);
client.player = player;
client.player.on('trackStart', (message, track) => message.channel.send(`Now playing ${track.title}...`))
 
client.on("ready", () => {
    console.log("I'm ready !");
});
 
client.on("message", async (message) => {
 
    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();
    if(command === "play"){
        client.player.play(message, args[0], message.member.user);
        // as we registered the event above, no need to send a success message here
    }
 
});
 
client.login(settings.token);

PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato>
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato> node .
PS C:\Users\xWolf\OneDrive\Desktop\musicbotzato>

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
