### ISSUE TITLE
SyntaxError: Unexpected token '.'  in /voice/VoiceConnection

### ISSUE THREAD

**Issue by GRob27** [discordjs/discord.js#5117]
**Please describe the problem you are having in as much detail as possible:**
Just deleted my node modules (for an unrelated issue), when reinstalling it grabbed the latest version on master and now i get this error.

![image](https://user-images.githubusercontent.com/45238094/102038549-8d00e680-3d95-11eb-88de-857ee959215d.png)

**Include a reproducible code sample here, if possible:**

```js
const Discord = require("discord.js");
```

- [x] I have also tested the issue on latest master, commit hash:

**Comment by zaida04** [comment]
This is due to the [Node.js requirement of discord.js being bumped to v14.0.0](https://github.com/discordjs/discord.js/pull/5067) to make use of optional chaining and other features. You can solve this by updating your Node.js version

**Comment by GRob27** [comment]
oh cool! did not even know this was a thing :)
