### ISSUE TITLE
[WS => Manager] Failed to fetch all members before ready! Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.

### ISSUE THREAD

**Issue by taksumaki** [discordjs/discord.js#5123]
When trying to start my bot, I need to get all the users from the guilds, so I set the "fetchAllMembers" option in the Discord client configuration, but I always get the same problem, I don't know what else to do.

I made several corrections that I found on the internet that work but nothing, I leave my code on how I have configured the discord client.

**Include a reproducible code sample here, if possible:**
```js
    new Discord.Client({
      fetchAllMembers: true,
      retryLimit: 10,
      restRequestTimeout: 18e5,
      ws: {
        intents: new Intents([Intents.NON_PRIVILEGED, 'GUILD_MEMBERS'])
      },
    });
```

**Error**
```console
discordBot Bot [WS => Manager] Failed to fetch all members before ready! Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /home/node-apps/DiscordBot/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16
    at Timeout._onTimeout (/home/node-apps/discordBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) 
```

**Intents**
![image](https://user-images.githubusercontent.com/56084970/102158110-546d1580-3e46-11eb-82ac-3cf31beff974.png)

**Log**
https://anotepad.com/notes/irgcxit6

**Further details:**
- discord.js version: 12.5.1
- Node.js version: 12.19.0
- Operating system: Windows 10 and Linux (Ubuntu 18.04)
- Priority this issue should have – please be realistic and elaborate if possible: It should have medium priority, since it is not a fatal problem, but I cannot start the bot since it always gives me that error

**Relevant client options:**
- partials: ['MESSAGE', 'CHANNEL', 'REACTION']
- gateway intents: 'GUILD_MEMBERS'
- other: NON_PRIVILEGED

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by BannerBomb** [comment]
I notice that the intents toggles are greyed out in the image you attached. So I assume they have been disabled due to the bot surpassing 100 servers, if this is true then you will need to get the bot verified before you can access the Presence and Guild Members intents.

**Comment by taksumaki** [comment]
@BannerBomb The bot is already verified, this is how the controls were when discord told me that the bot has been verified and the intesiones have been activated

I can no longer move the controls, discord so I leave them

**Comment by macedonga** [comment]
@taksumaki you need to have the "Server members intent" enabled, or you won't be able to do fetch all members. I had the same issue once, and I had to contact Discord and send them a snippet of the code that used that intent

**Comment by ArtanisTheOne** [comment]
I am having this problem too with Discord.js version 11 and my bot is nowhere near 100 servers. Just a testing bot

**Comment by taksumaki** [comment]
@macedonga Again, I have already activated the Intents, my bot was already verified and the Intents were also verified.

**Comment by wallopthecat** [comment]
I can verify this on 12.5.1

Bot in 2 servers. Intent activated on panel.

```
const intents = new Intents([
  Intents.NON_PRIVILEGED,
  "GUILD_MEMBERS",
]);
....
ws: {intents}
....
await guild.members.fetch(); // update cache

```
`Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.`

**Comment by ArtanisTheOne** [comment]
Do you have the discord guild thing turned on in discord.developers.com for your bot?

**Comment by wallopthecat** [comment]
> Intent activated on panel.
Yep
![image](https://user-images.githubusercontent.com/28909747/103014020-b9d69b80-4503-11eb-9620-a70201ac653a.png)

**Comment by iCrawl** [comment]
Going forward we are going to remove `fetchAllMembers`, so there will be no fix to this. Use different ways to get members if you need them that don't rely on this setting.
