### ISSUE TITLE
User cache isn't updating

### ISSUE THREAD

**Issue by chxlls** [discordjs/discord.js#5127]
The user cache isn't updating

This returns as '1' which is the bot
```js
let users = bot.users.cache.size
console.log(users)
```

```js
let users = bot.users.cache.size
```

**Further details:**

- discord.js version: v12.1.1
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by tipakA** [comment]
Version 12.1.1 is *very* outdated. Please update to 12.5.1.

For the issue, it's caused by intents - #4961
