### ISSUE TITLE
Too long timeout for retrying a connection

### ISSUE THREAD

**Issue by zero734kr** [discordjs/discord.js#5134]
**Please describe the problem you are having in as much detail as possible:** 
I'm unable to login with my specific discord bot, but other bot is running perfectly without any problems.
I tried everything I know to solve the problem and lastly, I tried to log in with the debug event and the result is:

```js
Provided token: NjgxMjE5OTkzOTExOTUxMzYw.XlLRjw.***************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 0
[WS => Manager] Spawning shards: 0
[WS => Manager] Exceeded identify threshold. Will attempt a connection in 23712871ms
```

After this I calculated the duration of this milliseconds and the result was approximately 6 hours and 30 minutes.
I think this is too long and also, any suggestions to try to solve the problem? Or is this a bug of Discord API again and I need to wait for the API to stabilize?

A few months ago I already opened an issue to the same problem and that time it solved itself after some time passed.

**Include a reproducible code sample here, if possible:**

```js
const { Client } = require("discord.js")
const client = new Client()

client.on("debug", console.log)
client.on("ready", () => console.log("ready"))

client.login(TOKEN)
```

**Further details:**

- discord.js version: v12.5.1
- Node.js version: v14.15.1
- Operating system: Ubuntu 18.04 (production) and Linux Mint 20 (dev)
- Priority this issue should have – please be realistic and elaborate if possible: idk, because I think this is a very rare problem

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: b8be723

**Comment by monbrey** [comment]
You've used your 1000 logins for the day. This is a Discord imposed limitation.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by zero734kr** [comment]
Ok in the next time I’ll message my question in discord server

**Comment by advaith1** [comment]
This isn't exactly a Discord limitation or a bug, this is a(n annoying) design choice in discord.js to delay connecting instead of allowing Discord to properly notify the bot owner and reset the token and login limit.

**Comment by monbrey** [comment]
While it's correct that Discord.js doesn't throw an error when the login limit is reached (has been discussed for changing in v13) the limit of 1000 logins per day is very much a Discord limitation.

**Comment by advaith1** [comment]
Why throw an error? Just let it attempt to connect as normal and let it do the correct behavior:

> Upon hitting this limit, all active sessions for the bot will be terminated, the bot's token will be reset, and the owner will receive an email notification. It's up to the owner to update their application with the new token.

**Comment by iCrawl** [comment]
I'm not sure what you are proposing? All of the mentioned quote still happens. Thats entirely on discords side.

**Comment by advaith1** [comment]
It doesn't when using discord.js, because discord.js prevents the final connection which would trigger the resets and notification from happening, waiting it out instead.

**Comment by iCrawl** [comment]
Could have been a lot clearer about that in the initial message. Feel free to open a separate issue with this then.
