### ISSUE TITLE
Discord.js not accepting a string even though docs say it supports it.

### ISSUE THREAD

**Issue by damagicalcat** [discordjs/discord.js#5135]
**Please describe the problem you are having in as much detail as possible:**
I get the error "The Amount of shards option must be a number." when I set the option totalShards for ShardingManager
I know that this is a simple fix and all I have to do is change "2" to 2
but the docs say that this option can be a string or a number: https://discord.js.org/#/docs/main/stable/class/ShardingManager
**Include a reproducible code sample here, if possible:**

```js
const { ShardingManager } = require('discord.js');
const manager = new ShardingManager('./bot.js', { totalShards: "2" });

manager.on('shardCreate', shard => console.log(`Launched shard ${shard.id}`));
manager.spawn();
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.3
- Operating system: Repl.it???
- Priority this issue should have – please be realistic and elaborate if possible: Low priority, it's just a tiny problem for developers.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by anandre** [comment]
The only string it accepts is `'auto'`, which the library docs state.

> Number of total shards of all shard managers or "auto"
