### ISSUE TITLE
BAN DATE?

### ISSUE THREAD

**Issue by rjworks** [discordjs/discord.js#5136]
Feature request: add ban date of the users

current code: 

                          message.guild.fetchBans(true).then(bans => console.log(bans)) //Collection of users
doesn't say ban date or anything

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by tipakA** [comment]
Unfortunately, you missed the part where Discord's API does not send ban dates, so it is pretty much impossible for the lib to even try to implement such thing.

**Comment by Papaia** [comment]
This is not something the API gives you.
`fetchBans` is a wrapper for [`Get Guild Bans`](https://discord.com/developers/docs/resources/guild#get-guild-bans), which returns [Ban objects](https://discord.com/developers/docs/resources/guild#ban-object), AKA [`BanInfo`](https://discord.js.org/#/docs/main/master/typedef/BanInfo) in discord.js.
Those object have just the `reason` and `user` fields, and the library fully supports those.

**Comment by JMTK** [comment]
Closest you could do is get the audit logs for the server and look for the createdAt entry for the ban creation:
```js
{
  "targetType": "USER",
  "actionType": "DELETE",
  "action": "MEMBER_BAN_ADD",
  "reason": null,
  "executor": "82988288729681920",
  "changes": null,
  "id": "790316790857203742",
  "extra": null,
  "target": "689927946743578649",
  "createdTimestamp": 1608496606316
}
```

**Comment by anandre** [comment]
The above solution is not reliable because audit logs only go back 90 days.
