### ISSUE TITLE
Wrong Guild Count Shown in DM List with Discord.js Bot

### ISSUE THREAD

**Issue by zredrum** [discordjs/discord.js#5137]
Hi, I'm currently using Discord.js v12 with its built-in shard manager. I took this issue to the Discord server at first, and it seems as if there's no known fix. I have this in my bot.js file, which sets its status. It grabs the total guild count fine in servers, but when shown in DMs it returns 1,146. An image is below of what DMs look like with the bot in the list [here.](https://imgur.com/77D1XL2)

**Evaluation**
```js
client.shard.fetchClientValues('guilds.cache.size').then(results => {
  message.reply(results);
      return results.reduce((acc, guildCount) => acc + guildCount, 0)
   })
```

Returns values 1,146 and 1,216. I use 2 shards, so it means in the DM list it only returns shard 0's count. Therefore, this issue is most likely also happening to any servers in shard 0.

**Reprodubible Code:**

```js
let guildsamount = await client.shard.fetchClientValues('guilds.cache.size').then(results => results.reduce((acc, guildCount) => acc + guildCount, 0)).catch(console.error);

   const activities = [`;;help`, `the sunset`, `${guildsamount} servers`];

   // set random activity first
   let activity = activities[Math.floor(Math.random() * activities.length)];
   client.user.setActivity(activity, { type: "WATCHING" });

   setInterval(() => {
      let activity = activities[Math.floor(Math.random() * activities.length)];
      client.user.setActivity(activity, { type: "WATCHING" });
   }, 15000);
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.8.1
- Operating system: Heroku/MacOS
- Priority this issue should have:  Medium priority. This is a significant issue for users with large Discord bots, and returning an incorrect guilds result may lead to their functions not working properly either.

**Relevant client options:**

- gateway intents: server members

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by HarmoGlace** [comment]
It is because it is not refreshed on each activity edit, you need to recount the number of guilds in the setInterval. Also please not that you should avoid spamming the API in a such way. For others questions, please go on the discord server

**Comment by tipakA** [comment]
What is the issue exactly? Bot displays `1400` when you open DMs in Discord, but `2600` when you look on member list in guilds?

Not exactly sure, but i suspect the issue being that you use `fetchClientValues`, and shard 0 will call that while shard 1 is still starting, making overall result not including any other shard.

Additionally, as it was said, there is *absolutely* no reason to update presence every 15 seconds, and it's pretty much spam at that point.

**Comment by beasleeps** [comment]
> What is the issue exactly? Bot displays `1400` when you open DMs in Discord, but `2600` when you look on member list in guilds?
> 
> Not exactly sure, but i suspect the issue being that you use `fetchClientValues`, and shard 0 will call that while shard 1 is still starting, making overall result not including any other shard.
> 
> Additionally, as it was said, there is _absolutely_ no reason to update presence every 15 seconds, and it's pretty much spam at that point.

It's switching between statuses, but I'm happy to change the interval if you think that's the issue. The issue is exactly what you said. The correct amount is around 2600, not the 1400.

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
