### ISSUE TITLE
GuildMemberManager#fetch returns User

### ISSUE THREAD

**Issue by nopeless** [discordjs/discord.js#5146]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
const id = `id of a user that is not in the guild`;
const guild.members.fetch(id);
// returns `User` object
```

- discord.js version: 12.5.1
- Node.js version: 14.13.1
- Operating system: windows
- Priority: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

I think the documentation should mention that it returns a User object if the member is not present, or return null.

**Comment by monbrey** [comment]
I'm unable to replicate this on 12.5.1.
Calling `guild.members.fetch` with the ID of a User not in the Guild throws `DiscordAPIError: Unknown Member`

I should also point out that your reproducible code sample is incorrect - `const guild.members.fetch(id);` is an invalid line. If you can provide correct code which does cause this behaviour I can attempt to replicate again.

**Comment by nopeless** [comment]
Apologies for the clumsy issue report

I'll make sure to send a full testable code in a few days.

The user should be present in the cache and not in the guild for what I was testing originally 

I'll post an update comment soon.

**Comment by nopeless** [comment]
I found a fall-back code that assigns a User object if #member returned a falsy value.
The code works fine sorry

Here is the test code that I used anyway.

```js
const Discord = require("discord.js");

require("dotenv").config({ path: __dirname + "/.env" });

var client = new Discord.Client();

client.on("ready", async () => {
  console.log(`I am in ${client.guilds.cache.size} guilds`);
  let guildIds = [...client.guilds.cache.keys()];
  // fetch all users
  await Promise.all(
    [...client.guilds.cache.values()].map(async (v) => v.members.fetch())
  );
  for (let i = 0; i < guildIds.length; i++) {
    let guildOne = client.guilds.cache.get(guildIds[i]);
    for (let j = i; j < guildIds.length; j++) {
      let guildTwo = client.guilds.cache.get(guildIds[j]);
      for (const userId of [...guildOne.members.cache.keys()]) {
        if (!guildTwo.members.cache.get(userId)) {
          console.log(
            `Found user ${userId} that is present in guild ${guildOne.name} but not in ${guildTwo.name}`
          );
          let user = await client.users.fetch(userId);
          console.log(`Now I will fetch the user in ${guildOne.name}`);
          console.log(await guildOne.members.fetch(user).catch(console.log));
          console.log(guildOne.member(user));
          console.log("===================================");
          console.log(await guildTwo.members.fetch(user).catch(console.log));
          console.log(guildTwo.member(user));
          console.log("===================================");
          return;
        }
      }
    }
  }
  return console.error(
    "UNABLE TO FIND A USER THAT IS PRESENT ON ONE GUILD AND NOT ON OTHER"
  );
});

client.login(process.env.TOKEN);
```
