### ISSUE TITLE
Bot can still send messages if they dont have the send messages permission, if a "slash command" is used

### ISSUE THREAD

**Issue by Assassin-1234** [discordjs/discord.js#5149]
**Please describe the problem you are having in as much detail as possible:**
- if A bot doesnt have permissions to see / send a message in a channel and is reauthorized using application.commands scope, it can send messages if a "slash command" is used

**Include a reproducible code sample here, if possible:**

not applicable

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.16.3
- Operating system: not applicable
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none

- other: none

- [ x] I have also tested the issue on latest master, commit hash: b8be723
![💭┆chill-lounge - Discord 2020-12-25 18-33-11](https://user-images.githubusercontent.com/68866924/103136012-af262d00-46e2-11eb-8b39-675714f670c2.gif)

**Comment by iCrawl** [comment]
https://github.com/discord/discord-api-docs/issues/2342

**Comment by almostSouji** [comment]
Closing because this has nothing to do with discord.js.  Slash commands will get their own permission system as noted here: <https://github.com/discord/discord-api-docs/issues/2490>
