### ISSUE TITLE
Allow IPv4/IPv6 Selection for Discord.js Client

### ISSUE THREAD

**Issue by studiokeywi** [discordjs/discord.js#5158]
**Is your feature request related to a problem? Please describe.**
Some IPv6-only server configurations cannot make API calls to Discord as they do not directly support IPv6, and often times a workaround is required such as passing the `family: 6` property to the underlying Node.js `http.request` object. However, this is not an option for Discord.js as there are no configuration options for the Discord.js Client to allow specifying IPv4/IPv6 when required.

**Describe the ideal solution**
The dependency `node-fetch` does not support passing in such a property directly, but the effect can be achieved with the usage of an `https.agent`. There should be an option that can be passed into the constructor for the Discord.js Client that would enable adding the `family` property onto the `https.agent` object used in the APIRequest class

**Describe alternatives you've considered**
Alternate options would require extensive knowledge or access to server configuration that may not be available to every consumer of this library, and it seems a good fit for a new configuration parameter.

**Additional context**
The server space I'm using is provided by https://www.mythic-beasts.com/ and, in their words:
> ...only have IPv6 connectivity. This should be fine for anything connecting to a hostname as our NAT64 servers will translate IPv4-only services so they work fine, but any attempt to connect directly to an IPv4 address will not work. (...) but it's possible that a library or any code that's ignoring IPv6 connectivity and trying IPv4 only then failing will cause problems

I discovered that utilizing the `family: 6` option in requests I made to external APIs (Discord, Facebook, GitHub, and Tumblr) was the only way for my code to work the same on the server as when in development from my home instead of getting ECONNREFUSED immediately. Moving on to trying to host my Discord.js bot on this server space, I saw the same ECONNREFUSED on attempting to log in.

**Comment by Fyko** [comment]
relevent: https://github.com/discord/discord-api-docs/issues/1280 https://github.com/discord/discord-api-docs/issues/2431
