### ISSUE TITLE
TS: noImplicitAny throws due to missing typings for ws in discordjs' typings

### ISSUE THREAD

**Issue by noftaly** [discordjs/discord.js#5162]
**Please describe the problem you are having in as much detail as possible:**
When enabling `compilerOptions.noImplicitAny` in `tsconfig.json`, I get the following **compilation** error (so no `@ts-ignore` possible):
```
Bot/node_modules/discord.js/typings/index.d.ts(18,30): error TS7016: Could not find a declaration file for module 'ws'. '/Bot/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
```

I shouldn't get this error because I have `ws` listed nowhere in my package.json, so I feel like I shouldn't have to install types for a dependency of a dependency.

**Include a reproducible code sample here, if possible:**
Here is my tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "checkJs": true,
    "esModuleInterop": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "./build",
    "pretty": false,
    "removeComments": true,
    "resolveJsonModule": true,
    "sourceMap": false,
    "target": "es2019"
  },
  "include": ["src/**/*.ts"],
  "exclude": ["gulpfile.js", "node_modules/"]
}
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.0
- Operating system: macOS 11
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash: I have not, but just by browsing the commit history, I can't find any commit that seems to fix this.

**Comment by iCrawl** [comment]
Welcome to the typescript ecosystem.

https://github.com/discordjs/discord.js/pull/3200
