### ISSUE TITLE
Membership screening and pending property

### ISSUE THREAD

**Issue by qpn6ph9q** [discordjs/discord.js#5163]
I see the new Discord membership screening feature mentioned as not implemented yet in a recent comment. Is there a timeframe for implementing this yet? My bot deals with large communities of 60K+ users and this feature will allow the bot to avoid role assignments for members with the pending status so as to not break the new functionality.

> If they have membership screening enabled, this would be why you are receiving those events, after a member finishes the screening, the `pending` property updates, which isn't implemented quite yet in djs.

_Originally posted by @ckohen in https://github.com/discordjs/discord.js/issues/5139#issuecomment-751536298_

Discord API reference:

https://discord.com/developers/docs/resources/guild#guild-member-object

**Comment by zaida04** [comment]
Member gating is most likely going to be in v13 as there aren’t any more planned releases for v12. In the mean time, you *can* use Structures.extend and implement the needed properties on your own or you can install the WIP pr

**Comment by OmgImAlexis** [comment]
@qpn6ph9q something like this.

Typescript version.
```ts
import { Client, GuildMember as DiscordGuildMember, Structures } from 'discord.js';

Structures.extend('GuildMember', GuildMember => class GuildMemberWithPending extends GuildMember {
    pending = false;

    constructor(client: any, data: any, guild: any) {
        super(client, data, guild);
        this.pending = data.pending ?? false;
    }

    _patch(data: any) {
        // @ts-expect-error
        super._patch(data);
        this.pending = data.pending ?? false;
    }
});

const client = new Client();

type GuildMember = DiscordGuildMember & {
    pending: boolean;
};

client.on('guildMemberUpdate', async (oldMember, newMember) => {
    // Member passed membership screening
    if ((oldMember as GuildMember).pending && !(newMember as GuildMember).pending) {
        const role = newMember.guild.roles.cache.find(role => role.name.toLowerCase() === 'member');
        if (role) {
            await newMember.roles.add(role);
        }
    }
});
```

Js version should be something like this.
```js
const { Client, Structures } = require('discord.js');

Structures.extend('GuildMember', GuildMember => {
    class GuildMemberWithPending extends GuildMember {
        pending = false;
    
        constructor(client: any, data: any, guild: any) {
            super(client, data, guild);
            this.pending = data.pending ?? false;
        }
    
        _patch(data: any) {
            super._patch(data);
            this.pending = data.pending ?? false;
        }
    }
    return GuildMemberWithPending;
});

const client = new Client();

client.on('guildMemberUpdate', async (oldMember, newMember) => {
    // Member passed membership screening
    if (oldMember.pending && !newMember.pending) {
        const role = newMember.guild.roles.cache.find(role => role.name.toLowerCase() === 'member');
        if (role) {
            await newMember.roles.add(role);
        }
    }
});
```

**Comment by kyranet** [comment]
@OmgImAlexis I edited your comment to use [TypeScript's module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), which is preferred over casting all the types over and over.

**Comment by ckohen** [comment]
The relevant PR (#5121) has been merged to master.
