### ISSUE TITLE
A valid token is being considered invalid

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/discord.js#5165]
**Please describe the problem you are having in as much detail as possible:**
I can't login to the client and the ready event is never fired. Here's the error I'm getting
```
(node:689) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/runner/<project>/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/home/runner/<project>/index.js:2222:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js')
const client = new Discord.Client()

client.on('ready', () =>{
console.log('It works!') // Never fires :/
})

client.login('<token>') // yes, I have double checked many times that it is correct
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: Latest stable
- Operating system: Repl.it
- Priority this issue should have – please be realistic and elaborate if possible: Not sure, but it happens at random
- This happens randomly, and only for one instance of my bot. The other instance works just fine, even with the same token.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Extroonie** [comment]
As you already stated:
> The other instance works just fine, even with the same token.
At this point, we can't really consider this as a discord.js bug, nor can reproduce. If one instance works just fine and one doesn't, I'd have to assume the issue is somehow related to the end of your operating system.

**Comment by YodaLightsabr** [comment]
> As you already stated:
> 
> > The other instance works just fine, even with the same token.
> 
> At this point, we can't really consider this as a discord.js bug, nor can reproduce. If one instance works just fine and one doesn't, I'd have to assume the issue is somehow related to the end of your operating system, or you're generally just missing something.

But here's the thing: In the instance having the issue, the only variable that changes is time

**Comment by Peppy8651** [comment]
Are you using "node ." or something like "node something.js" in your code? This causes a bug with repl.it that I don't really get either. However, you can use the run button and it should be able to fix the issue if you can figure things out.

**Comment by TypicalIllusion** [comment]
![right tokwn](https://user-images.githubusercontent.com/70919038/103388970-19bbdc00-4ada-11eb-94ca-b3ab2b792679.PNG)
are you using this token?

**Comment by YodaLightsabr** [comment]
> Are you using "node ." or something like "node something.js" in your terminal? This causes a bug with repl.it that I don't really get either. However, you can use the run button and it should be able to fix the issue if you can figure things out.

Yeah, I configured the run button instead of using `node index.js`.


> ![right tokwn](https://user-images.githubusercontent.com/70919038/103388970-19bbdc00-4ada-11eb-94ca-b3ab2b792679.PNG)
> are you using this token?

Of course lol! I said the only thing I changed between the two images is time

**Comment by almostSouji** [comment]
We've had this claim countless times, every single time so far it could in the end be tracked down to either the way the token is provided, it actually being the client secret, or having cutoff or unwanted additional characters.

Log the token, log its length, make sure it looks like this `NzkyNzE1NDU0MTk2MDg4ODQy.X-hvzA.Ovy4MCQywSkoMRRclStW4xAYK7I` and not like this `kxbsDRU5UfAaiO7ar9GFMHSlmTwYaIYn`.

> Of course lol!

This phrase implies heavily that you are so sure of what you did and have that you did in fact not check (and that it's not unlikely the cause)

**Comment by YodaLightsabr** [comment]
> We've had this claim countless times, every single time so far it could in the end be tracked down to either the way the token is provided, it actually being the client secret, or having cutoff or unwanted additional characters.
> 
> Log the token, log its length, make sure it looks like this `NzkyNzE1NDU0MTk2MDg4ODQy.X-hvzA.Ovy4MCQywSkoMRRclStW4xAYK7I` and not like this `kxbsDRU5UfAaiO7ar9GFMHSlmTwYaIYn`.
> 
> > Of course lol!
> 
> This phrase implies heavily that you are so sure of what you did and have that you did in fact not check (and that it's not unlikely the cause)

I'm not as stupid as you think, ok? I have double checked many times. An hour ago, my bot was responsive. Right now, it's unresponsive and after restarting the ready event never fires. My bot is used by hundreds of people, and it works just fine until it stops responding. I go to restart it and the ready event never fires. This is the format of my token, where `A` is an uppercase letter, `a` is a lowercase letter, and `0` is a number:
`AaaaAaAaAaa0AAAaAaa0Aaa0.A0aA0a.aa0aaAaaAAAAaaaaa0AAaAaAaAA`

**Comment by almostSouji** [comment]
Well, the only other reason I know for a token to suddenly become invalid is it being voluntarily (in the developer dashboard) or involuntarily (through an upload on a public GitHub repository or gist document or exceeding rate limits or otherwise abusing the API in one way or another).

**Comment by monbrey** [comment]
If the ready event isn't firing, please add a listener to the debug event and log it's output.

`client.on("debug", console.log)` will do

**Comment by YodaLightsabr** [comment]
> If the ready event isn't firing, please add a listener to the debug event and log it's output.
> 
> `client.on("debug", console.log)` will do

Ok I'll try that next time it's having the issue

**Comment by YodaLightsabr** [comment]
This issue hasn't happened again recently. I'm really confused.

**Comment by YodaLightsabr** [comment]
First of all, don't close my issue @almostSouji. Second, here's the console output using `client.on('debug',console.log);`.

**Comment by YodaLightsabr** [comment]
Now, I know this might seem like a rate limit, but since the music portion of my bot is on another instance using the same token, why would that function? Also, since my bot is only in 92 servers, how would I be getting that much activity?

**Comment by zaida04** [comment]
I feel compelled to point out you forgot to include your console output portion of your debug event.

**Comment by YodaLightsabr** [comment]
> I feel compelled to point out you forgot to include your console output portion of your debug event.

Huh huh, wdym? 
![image](https://user-images.githubusercontent.com/76178582/103488871-2afc3580-4dc5-11eb-99cc-0599cccf98b1.png)

**Comment by monbrey** [comment]
Your images weren't loading. Yes, it looks like you've hit the global rate limit - something that could easily be caused by two different scripts sharing the same token as they aren't able to communicate rate limits to each other. This is generally bad practice.

The issue was closed because you said you hadn't been able to reproduce it. Standard procedure for triage in a repository.

**Comment by KatieIsAKitty** [comment]
> Now, I know this might seem like a rate limit

it definitely does, that *is* the ratelimited response code, possibly because of you restarting your bot to implement changes, or because of relp.it restarting your instance, but if you insist it's not then I see no reason for this to be happening

**Comment by YodaLightsabr** [comment]
> Your images weren't loading. Yes, it looks like you've hit the global rate limit - something that could easily be caused by two different scripts sharing the same token as they aren't able to communicate rate limits to each other. This is generally bad practice.
> 
> The issue was closed because you said you hadn't been able to reproduce it. Standard procedure for triage in a repository.
> 
> **The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

Okay, then please meet me on the discord server so we can talk about it.

**Comment by almostSouji** [comment]
> First of all, don't close my issue @almostSouji. [...]

The issue is not caused by discord.js but a continuous restart loop depleting max login attempts caused by something on your host system (be it "reload on type" or other crash-loops).

Our GitHub is just for feature requests or issues with the library itself, this is not an issue of a valid token being rejected "as invalid", hence I closed it.
