### ISSUE TITLE
type: 'error', message: 'WebSocket was closed before the connection was established'

### ISSUE THREAD

**Issue by muhimur9049** [discordjs/discord.js#5169]
This happens randomly out of nowhere for my music bot, and even crashes the entire bot (aka 1 shard) which isn't good. The error comes from node_modules in the discord.js files and no one has yet to know the answer in any support servers on a fix.

**Comment by iCrawl** [comment]
Don't ignore the issue template. Reopen if this still happens with the proper template filled out.
