### ISSUE TITLE
Failed to send a packet - Error [UDP_SEND_FAIL]: Tried to send a UDP packet, but there is no socket available.

### ISSUE THREAD

**Issue by sanchir2011** [discordjs/discord.js#5178]
I have a discord music bot using discord.js and ytdl. When sometimes user plays a music, on console log shows this error: **Failed to send a packet - Error [UDP_SEND_FAIL]: Tried to send a UDP packet, but there is no socket available.** It spams a lot that I cant even see my console logs. Also, I am not really familiar with UDP packet. I am hosting my bot on Vultr.

Here is my music play function:
```js
let player = await ytdl(song.url, {filter: 'audioonly', quality: 'highestaudio', highWaterMark: 1 << 25, opusEncoded: true, encoderArgs: ['-af', 'bass=g=0']});
    const dispatcher = serverQueue.connection.play(player, { type: 'opus', highWaterMark: 1, bitrate: 'auto', fec: true, volume: false })
      .on("finish", () => {
        serverQueue.songs.shift();
        play(guild, serverQueue.songs[0], message);
      })
      .on("error", error => {
        console.error("Dispatcher aldaa " + errorData + error);
      })
      .on("debug", deb => {
        console.log(deb);
      });

      dispatcher.setVolumeLogarithmic(serverQueue.volume / 5);
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.20.0
- Operating system: Ubuntu 18.04 x64

Any ideas what's the problem?

**Comment by MidSpike** [comment]
This can be caused by a few things:
- bot is disconnected by user
- bot is moved to a new voice channel
- bot loses connection (or packet loss)

**Comment by sanchir2011** [comment]
> This can be caused by a few things:
> 
> * bot is disconnected by user
> * bot is moved to a new voice channel
> * bot loses connection (or packet loss)

Sorry for late reply. I figured out that user has moved the bot to another voice channel. That was the main reason of this issue. Thank you so much!
