### ISSUE TITLE
Incorrect GuildChannel Sorting 

### ISSUE THREAD

**Issue by KinectTheUnknown** [discordjs/discord.js#5179]
Discord.js is [improperly sorting guild channels](https://github.com/discordjs/discord.js/blob/v12/src/util/Util.js#L456-L457) when the only difference between two channels is the increment of the id (last 12 bits).
Code
```js
const {Client} = require("discord.js")
const client = new Client()
client.once("ready", async () => {
  const guild = await client.guilds.create("Test", {
    channels: [{
      name: "text-1",
      type: "text"
    }, {
      name: "text-2",
      type: "text"
    }]
  })
  console.log("Created Guild " + guild.id)
  displayChannels(guild)

  const channel = guild.channels.cache.find(chnl => chnl.name === "text-2")
  await editChannel(channel.id, {position: 0})
  displayChannels(guild)

  const invite = await channel.createInvite({temporary: false})
  console.log("\n".repeat(5), invite.url)
})
function displayChannels(guild) {
  return console.table(
    guild.channels.cache.reduce((acc, channel, id) => {
      acc[id] = {
        type: channel.type,
        rawPosition: channel.rawPosition,
        position: channel.position,
        name: channel.name
      }
      return acc
    }, {})
  )
}
function editChannel(id, data) {
  return client.api.channels(id).patch({
    data,
    headers: {"content-type": "application/json"}
  })
}
client.login()
```
My logs:

Inital guild creation

| index | type | rawPosition | position | name |
|:-----:|:-----:|:-----------:|:--------:|:----:|
| 795804993269399574 | 'text' | 0 | 0 | 'text-1' |
| 795804993269399575 | 'text' | 1 | 1 | 'text-2' |

After channel update

| index | type | rawPosition | position | name |
|:----:|:---:|:-----------:|:-------:|:----:|
| 795804993269399574 | 'text' | 0 | 1 | 'text-1' |
| 795804993269399575 | 'text' | 0 | 0 | 'text-2' |

The expected position after the update should be `0` for `#text-1` and `1` for `#text-2`  as shown in the following screenshot taken after the update occurred
![Screen Shot 2021-01-04 at 2 27 43 PM](https://user-images.githubusercontent.com/34723558/103593145-1a1cf400-4e99-11eb-973e-6d38aeacc95c.png)

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.17.0
- Operating system: macOS Big Sur v.11.0.1
- Low, it's a rare edge case

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

Note: I know I'm using `client.api`, which is a private api. However, I tried to reproduce the issue by creating a guild using the templates provided by Discord, but I was unable to get two channels that had the same `rawPosition`. So, I manually made an api call to recreate the situation. In order to provide reproducible code, I had to manually call `client.api` to get around the inbetween code used to set channel positions.

Originally encountered by StrikerIV#4517
[Picture of Channels](https://discordapp.com/channels/222078108977594368/223867697312694272/795753948363489311)
[Logs of channel info](https://discordapp.com/channels/222078108977594368/223867697312694272/795754429935910972)

**Comment by ICE7777777** [comment]
Hm...

**Comment by Poly-Pixel** [comment]
What is the difference between `position` and `rawPosition`? In issue #5379, it was stated that this could be a Discord API bug. However, I tried to reproduce this issue with the provided code and succeeded - even though it was stated that the Discord API bug would've been fixed by now (https://github.com/discord/discord-api-docs/issues/2640). However, all seems to work fine when using the `channel#edit` function.

**Comment by DTrombett** [comment]
This should have been fixed by Discord in the last API version (which actually djs supports).
Are still there any problems?

**Comment by KinectTheUnknown** [comment]
Yea, I can no longer reproduce the bug. Closing issue
