### ISSUE TITLE
Styled components in MessageEmbed

### ISSUE THREAD

**Issue by mstanciu552** [discordjs/discord.js#5185]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
I was trying to add a status component that showed whether or not a show was _ongoing_ or _finished_  and I thought that a Styled Component in Discord would be cool.

**Describe the ideal solution**
I think it would be cool if there was a way to add a styled css component to a MessageEmbed. Like adding markdown to the description or a special function `setComponent() for adding something like JSX`.

**Describe alternatives you've considered**
Adding markdown to the MessageEmbed or even making a new function StyleEmbed maybe.

**Additional context**
Something like this.
![Screenshot (34)](https://user-images.githubusercontent.com/34579048/103827733-5495b500-5082-11eb-8718-d8fc9f9f703a.png)
Does anyone think it is even remotely possible to add this feature? Share your thoughts please.

**Comment by monbrey** [comment]
Discord.js has no control over the visual representation of a MessageEmbed. This should be raised as a feature request to Discord.

https://support.discord.com/hc/en-us/articles/213490807-Where-can-I-submit-Feature-Requests-Feedback-and-Suggestions-
