### ISSUE TITLE
[Suggestion] Allow embedding of videos.

### ISSUE THREAD

**Issue by Dragonizedpizza** [discordjs/discord.js#5186]
**Is your feature request related to a problem? Please describe.**
I find it quite annoying how you cannot embed videos. I was trying to embed a YouTube video into my Discord music bot's embed, only to find out you can't.

**Describe the ideal solution**
Perhaps allow a function called `.addVideo()`, or allow videos to be set as the image in `.setImage()`.

**Describe alternatives you've considered**
Using a video sharing platform, and letting Discord automatically create the embed when sending the link.

**Additional context**

**Comment by almostSouji** [comment]
We can only implement what the discord API offers.
Feature requests go to <https://support.discord.com/hc/en-us/community/topics>
