### ISSUE TITLE
Shard 0's Client took too long to become ready.

### ISSUE THREAD

**Issue by sinkaroid** [discordjs/discord.js#5187]
**Please describe the problem you are having in as much detail as possible:**
when *fetchAllMembers* enabled the shard will not launched, but when i disable it the shard is logged properly  

**Include a reproducible code sample here, if possible:**
Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.  

```js
spawnTimeout: -1, //won't help at all
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.5.0
- Operating system: Ubuntu 18.04.5 LTS
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by sinkaroid** [comment]
or this is a problem with service? bcs i still hosted in heroku and contains 2,4k guilds

**Comment by advaith1** [comment]
`fetchAllMembers` is **not recommended** to be used and fetches all members from each server one at a time; if you have too many servers on a shard then d.js will hit its time limit before it fetches from all of them and it will error.

**Comment by iCrawl** [comment]
Going forward we are going to remove `fetchAllMembers`, so there will be no fix to this. Use different ways to get members if you need them that don't rely on this setting.
