### ISSUE TITLE
Unable to create new Discord.ClientApplication()

### ISSUE THREAD

**Issue by KifoPL** [discordjs/discord.js#5189]
**Please describe the problem you are having in as much detail as possible:**

I have attempted to create _!error_ command for my discord bot that would immediately DM me with issue description. I wanted to use `ClientApplication.owner.createDM()` method, but after adding `const clientApp = new Discord.ClientApplication();` an error is given `TypeError: Cannot read property 'id' of undefined` at `discord.js\src\structures\interfaces\Application.js:24:20`. I have very recently started learning Js, so I wasn't able to fix the error by myself. If it is my error, I'd really appreciate a brief explanation of how to fix this myself :)

**Include a reproducible code sample here, if possible:**

```js
const clientApp = new Discord.ClientApplication();
```

Also, have a look at screenshot:
 ![Discord js error](https://user-images.githubusercontent.com/57945116/104038568-8f5c3200-51d5-11eb-8cb2-37cef64f96b8.png)

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.3
- Operating system: Windows 10 Pro OS build 18363.1256, version 1909
- Priority this issue should have – please be realistic and elaborate if possible: semi-high, considering I cannot use any of ClientApplication() functions as the error gets thrown just by attempting to use it.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none
/\
|
|
don't know what's this, I've just started learning js, I know C#, C++ and a bit of Java, and this type of programming is very new to me.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
You are not supposed to instantiate this class yourself, you should use [`Client#fetchApplication`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=fetchApplication) instead.
