### ISSUE TITLE
message.reply("") with embeds

### ISSUE THREAD

**Issue by muhimur9049** [discordjs/discord.js#5190]
When using message.reply(embed) with a Discord.MessageEmbed(), it does not ping the message author by default, unlike regular messages that are non-embeds. Instead, I have to do something like message.reply("", embed) or message.channel.send(message.author, embed) to make it actually ping the user.

Any reason as to why it doesn't ping by default?

**Comment by tipakA** [comment]
Most likely because mention has to be in content, which you do not include when you do `reply(MessageEmbed)` or `reply(MessageAttachment)`. In other cases there is actual content you yourself have put in into what has to be sent, so it can be prepended with the mention.

**Comment by ckohen** [comment]
While this might be considered a bug, v13 (highly likely the next release) replaces the reply functionality with discords inline replies, which will fix this.

**Comment by almostSouji** [comment]
There won't be another v12 release unless for severe bugs and the current state of the development branch has already fully replaced this functionality.
