### ISSUE TITLE
Can we please have the new discord reply system?

### ISSUE THREAD

**Issue by TheHandyUser** [discordjs/discord.js#5192]
The current discord.js reply system just pings the people, but i think the new reply system would be awesome.

**Comment by ckohen** [comment]
This is already on master, feel free to use that if you want. Or wait for the v13 release which will contain this.

**Comment by almostSouji** [comment]
There won't be another v12 release, this has already landed in the development branch with the merge of #4874 and will be released with v13.0.0, replacing the old Message#reply method.

**Comment by TheHandyUser** [comment]
> This is already on master, feel free to use that if you want. Or wait for the v13 release which will contain this.

Please tell me how to, i know this isnt much of a problem but please tell.....
