### ISSUE TITLE
client.channels.cache.get("channel_id").send method not found

### ISSUE THREAD

**Issue by rahultrivedi180** [discordjs/discord.js#5193]
```javascript
const Discord = require("discord.js");
const client = new Discord.Client();

const token = "token";

client.login(token);

client.channels.cache.get("channel_id").send("Hello!");

```

![Screenshot from 2021-01-09 20-40-58](https://user-images.githubusercontent.com/32861078/104095137-38c92380-52bb-11eb-9632-5f4021d01c70.png)

I can not see the send method even in the code suggestion.

**Comment by Snowflake107** [comment]
`client.channels.cache.get("channel_id")` is undefined because channel with id is not in cache. It isn't a bug

**Comment by rahultrivedi180** [comment]
@Snowflake107 Is there any other way to send a message?

**Comment by PyroTechniac** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the Discord server instead of opening an issue – you will get redirected there anyway.**
