### ISSUE TITLE
"guildMemberAdd" breaks my bot

### ISSUE THREAD

**Issue by Gary50613** [discordjs/discord.js#5197]
Hello, I've found that my bot will go down after a few hour and working slowly, after I debug for a LONG time, I noticed that if I remove 

> ```bot.on("guildMemberAdd", async m => {//more})```

lister, everything goes great!

while the bot doesn't working, I tried this code
> ```
bot.on('message', m => {
    if(m.content != "&ping") return
    console.log('received')
    m.channel.send("pong").then(() => console.log("sent"))
})
```

and I only see "received" in console, the message didn't sent, any way can help me plz?

discord.js - 12.5.1
nodejs - 12.x

**Comment by breftejk** [comment]
Using return in this case terminates the function on the console log. Change return to { }

**Comment by Gary50613** [comment]
> Using return in this case terminates the function on the console log. Change return to { }

I tried this code can receive message and reply but when "guildMemberAdd" exist, this code broken, I can only receive message but I can't send messages

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
