### ISSUE TITLE
Discord.js Doesn't find @discordjs/opus

### ISSUE THREAD

**Issue by ThumusLive** [discordjs/discord.js#5207]
**Please describe the problem you are having in as much detail as possible:**
When I try to play something in a voice channel, this error appear :
```
Error: Error: Cannot find module 'd:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-unknown\opus.node'
Require stack:
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\@discordjs\opus\lib\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\util\loader.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\Client.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\exemples\latest.js
Error: Cannot find module 'node-opus'
Require stack:
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\util\loader.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\Client.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\exemples\latest.js
Error: Cannot find module 'opusscript'
Require stack:
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\util\loader.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\Client.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\index.js
- d:\Users\NAME\Documents\All\Programmation\IMBRICATION\exemples\latest.js
    at Object.loader [as require] (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\prism-media\src\opus\Opus.js:149:5)
    at AudioPlayer.playPCMStream (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\player\BasePlayer.js:53:17)
    at VoiceConnection.play (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at Music.loadMusic (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\src\class\Music.js:82:29)
    at Music.Play (d:\Users\NAME\Documents\All\Programmation\IMBRICATION\src\class\Music.js:135:27)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {stack: 'Error: Error: Cannot find module 'd:\Users\Th…ions (node:internal/process/task_queues:93:5)', message: 'Error: Cannot find module 'd:\Users\NAME\D…Programmation\IMBRICATION\exemples\latest.js'}
```
He just don't know where is discord opus or something like that
Screen of my discordjs/opus 
![image](https://user-images.githubusercontent.com/42680097/104256386-72e12380-547b-11eb-8488-b942c6904fbb.png)

**Include a reproducible code sample here, if possible:**

I don't know, just a simple vocal player
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.login('token here');

client.on('message', async message => {
  // Voice only works in guilds, if the message does not come from a guild,
  // we ignore it
  if (!message.guild) return;

  if (message.content === '/join') {
    // Only try to join the sender's voice channel if they are in one themselves
    if (message.member.voice.channel) {
      const connection = await message.member.voice.channel.join();
      const ytdl = require('ytdl-core');
      connection.play(ytdl('https://www.youtube.com/watch?v=ZlAU_w7-Xp8', { filter: 'audioonly' }));
    } else {
      message.reply('You need to join a voice channel first!');
    }
  }
});
```

**Further details:**

- discord.js version: 12.5.1
- discord/opus version : 0.3.3

- Node.js version: 15.5.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: A little important because opusscript isn't the best solution of that : I have a tons of problems with it and for now I can't run my bot with a vocal connection.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ThumusLive** [comment]
In the error we can see it's trying to get the `node-v88-napi-v3-win32-x64-unknown-unknown` or in the discordjs opus of my node_modules, it's `node-v72-napi-v3-win32-x64-unknown-unknown`

**Comment by ThumusLive** [comment]
I've just delete the folder and redo a `npm i` and it work fine, if someone have this probleme just delete @discordjs and do `npm i`

**Comment by buraktabn** [comment]
Having the same issue and I'm using discord.js in the docker image. `Error: Error: Cannot find module '@discordjs/opus'`

docker build command:
```bash
docker build --no-cache -t neko-chan/bot:v0.2.2 .
```

<details>
<summary>Detailed Logs</summary>
<br>
(node:1) UnhandledPromiseRejectionWarning: Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- /usr/src/neko-chan/node_modules/prism-media/src/util/loader.js
- /usr/src/neko-chan/node_modules/prism-media/src/opus/Opus.js
- /usr/src/neko-chan/node_modules/prism-media/src/opus/index.js
- /usr/src/neko-chan/node_modules/prism-media/src/index.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/Client.js
- /usr/src/neko-chan/node_modules/discord.js/src/index.js
- /usr/src/neko-chan/checkMessage.js
- /usr/src/neko-chan/bot.js
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/src/neko-chan/node_modules/node-opus/build/Release/node-opus.node)
Error: Cannot find module 'opusscript'
Require stack:
- /usr/src/neko-chan/node_modules/prism-media/src/util/loader.js
- /usr/src/neko-chan/node_modules/prism-media/src/opus/Opus.js
- /usr/src/neko-chan/node_modules/prism-media/src/opus/index.js
- /usr/src/neko-chan/node_modules/prism-media/src/index.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /usr/src/neko-chan/node_modules/discord.js/src/client/Client.js
- /usr/src/neko-chan/node_modules/discord.js/src/index.js
- /usr/src/neko-chan/checkMessage.js
- /usr/src/neko-chan/bot.js
    at Object.loader [as require] (/usr/src/neko-chan/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/usr/src/neko-chan/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/usr/src/neko-chan/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/usr/src/neko-chan/node_modules/prism-media/src/opus/Opus.js:149:5)
    at AudioPlayer.playPCMStream (/usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/usr/src/neko-chan/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/usr/src/neko-chan/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at soundCommand (/usr/src/neko-chan/checkMessage.js:157:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>
