### ISSUE TITLE
Uncatchable Message Send Error

### ISSUE THREAD

**Issue by tonestrike** [discordjs/discord.js#5210]
**Please describe the problem you are having in as much detail as possible:**

Because of the queuing process when sending messages, it is impossible to catch message send errors if the shard is currently busy. This results in an uncaught error, crashing the shard.

I believe this is the culprit of the issue in the RequestHelper

```js
  async execute(item) {
    // Insert item back to the beginning if currently busy
    if (this.busy) {
      this.queue.unshift(item);
      return null;
    }
```

In the event that the shard is busy, the request is simply queued and null is returned.

**Include a reproducible code sample here, if possible:**

In many cases with many requests being queued, this will result in an uncaught error. There is no way to check if you have permissions to send a DM to a user with sending the message, making this function more or less useless.

```js
      return member.send(data)
        .catch(() => false)
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 13.4
- Operating system: MacOS

**Comment by kyranet** [comment]
discord.js v12.1.1 is not longer supported, please upgrade to v12.5.1.

**Comment by tonestrike** [comment]
My mistake! I have updated, and receiving the code, it seems like this should have been resolved in the latest update. I will close this out. Thanks!

**Comment by tonestrike** [comment]
@kyranet I have updated to the latest version of Discord and am still facing the same issue. I check to see if I have the ability to EMBED_LINKS and SEND_MESSAGES prior to sending to a particular channel this embed:
```
    const data = new MessageEmbed()
      .setColor(color)
      .setThumbnail(thumbnail)
      .setTitle(guild.welcome_message || `**Welcome to ${discordGuild.name}**`)
      .setDescription("Some description")
      ```
      
     And yet I get an uncaught missing access error. Any thoughts?

**Comment by kyranet** [comment]
You most likely did not check for `VIEW_CHANNEL`.

**Comment by tonestrike** [comment]
Thanks @kyranet I will give that a shot. I'm still confused why this library has uncatchable errors. It seems like a huge design flaw to have to know to check all of the permissions first prior to making a request like this. The ramifications are literally the crashing of the applications since uncaught errors are not permitted.

**Comment by kyranet** [comment]
> I'm still confused why this library has uncatchable errors.

What uncatchable error? You have not provided reproducible code other than an embed which does no operation on REST.

Besides, if you look the code since v12.4.0, the errors are bubbled up, which makes a huge difference and is the reason why async stack traces work.

**Comment by tonestrike** [comment]
Here is the code: 
```
client.on('guildMemberAdd', async (member) => {
  try {
    const discordGuild = member.guild
    const guild = await Guild.findOne({ where: { discord_id: discordGuild.id.toString() } })
    if (!guild) return
    const data = new MessageEmbed()
      .setColor(color)
      .setThumbnail(thumbnail)
      .setTitle(guild.welcome_message || `**Welcome to ${discordGuild.name}**`)
      .setDescription(`Description`)
    if (guild) {
      // This now checks VIEW_CHANNEL, SEND_MESSAGES and EMBED_LINKS
      const channel = await getSendableChannel(discordGuild)
      if (channel) {
        return channel.send(data)
      }
    }
  } catch (error) {
   /// never gets called
    console.error(error)
  }
})
```

**Comment by kyranet** [comment]
`return` moves the async execution out of the scope, yes, that includes the `catch` handler. You need `return await` (or just `await`) here.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by tonestrike** [comment]
Thank you! My mistake!
