### ISSUE TITLE
Unexpected user mention format from iOS device in message event

### ISSUE THREAD

**Issue by chozzz** [discordjs/discord.js#5213]
When client posts a message, [message.content](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=content) has different format for iOS platform.

E.g.
Considering `RandomUser` has an ID of `700000000000000001`, and the following criteria;
- User says `Hi @RandomUser - How are you?`

For PC and Android, the `message.content` will contain the following;
- `Hi <@!700000000000000001>- How are you?`

However, for iOS - It shows as following;
- `Hi <@700000000000000001>- How are you?`

Note that it's missing `!` in the mentions for iOS.
I am not sure if this is the expected result, but I am expecting a consistency across platforms, as this sometimes confuses developers who need to parse the mentions, or suspecting different formats when outputting user mentions from the bot.

```js
client.on('message', function (message: Message) {
    console.log(message.content);
});
```

**Further details:**
- discord.js version: 12.5.1
- Node.js version: 12.18.3
- Operating system: Ubuntu

- [x] I have also tested the issue on latest master, commit hash:

**Comment by zaida04** [comment]
I think the issue can just be chalked up to the discord client not having the User cached.

**Comment by vaporox** [comment]
1. The different mention formats can be found at https://discord.com/developers/docs/reference#message-formatting-formats
2. We cannot decide how mentions are formatted anyway, if you want more consistency you need to ask Discord.

**Comment by didinele** [comment]
This does seem like an iOS issue - the `!` is supposed to represent that the user has a nickname in the given server, however, as stated, I don't think this is something the library should hot-glue as a fix.

This is on Discord to fix.

**Comment by chozzz** [comment]
@vaporox Thanks for the link, it seems like @didinele point is valid that this is actually for Discord instead of here.
I am going to close it for now and admins can eventually re-open it if it needs triage.
