### ISSUE TITLE
GuildEmojiRoleManager does not remove role restrictions to GuildMember upon adding role

### ISSUE THREAD

**Issue by Klassien** [discordjs/discord.js#5216]
**Please describe the problem you are having in as much detail as possible:**
GuildEmojiRoleManager does not remove a GuildMember's role restrictions on emojis to members granted the role(s) added/set to the emoji.
Upon `guildEmoji.roles.add()` (or `guildEmoji.roles.set([roles])`), all GuildMembers with the role(s) are able to use the emoji upon promise returns successful.
Adding the role to a GuildMember, _after the promise is fulfilled and successful_, they will still not be able to use the emoji.

To reproduce:
1. Create a role -- copy RoleID for 'RoleID'
2. Create an emoji -- copy EmojiID for 'EmojiID'
3. Plug in respective IDs into reproducible sample below and run it.
4. Try to use the emote in a text channel (you will not be able to use it after promise )
5. Add the role to yourself.

Expected result:
You will now be able to use the emoji.

Actual result:
You cannot use the emoji.

If you pull the collection in GuildEmojiRoleManager, you will see the map of the role(s) to the emoji you just added.
```js
          await guildEmoji.roles.add('RoleID')
          console.log(guildEmoji.roles.cache)
```

**Include a reproducible code sample here, if possible:**

I am using message parameter to call on Guild in this sample.

```js
    let guildEmoji = message.guild.emojis.cache.get('EmojiID') 
        try {
          guildEmoji.roles.add('RoleID')
          //OR guildEmoji.roles.set(['RoleID'])
          console.log('Success')
        } catch (error) {
          //handle error
        }
```

**Further details:**

- discord.js version: _12.5.1_
- Node.js version: _15.4.0_ (edit, listed wrong node installment on this project)
- Operating system: Windows 10, 64-bit
- Priority this issue should have – please be realistic and elaborate if possible: Low
Does not effect any central requirements that I know of and there is not a feasible work around.

**Relevant client options:**

- partials: MESSAGE, CHANNEL
- gateway intents: GUILD_MEMBERS
- other: N/A

- [x] I have also tested the issue on latest master, commit hash: `c4c817116f868cedb4ec20bcbf90b9b3d382621e`

**Comment by almostSouji** [comment]
This likely has to do with the user client not reloading the cached emojis/updating the list of emojis one can use/are autocompleted when typed. I suspect this effect to subside once you reload the app. Should that be the case there isn't anything we can do to prevent this.

**Comment by Klassien** [comment]
> This likely has to do with the user client not reloading the cached emojis/updating the list of emojis one can use/are autocompleted when typed. I suspect this effect to subside once you reload the app. Should that be the case there isn't anything we can do to prevent this.

This seems to be it, precisely. Oddly enough at times, restarting the client does not cause the effect to subside which led me to believe this might be a discord.js issue. Seems to be a hit or miss with client reloading. Thank you 👍
