### ISSUE TITLE
messageUpdate event spams console

### ISSUE THREAD

**Issue by tovade** [discordjs/discord.js#5219]
**Please describe the problem you are having in as much detail as possible:**
Hello im getting an error spammed and it has to do with Object.hasPermission
**Include a reproducible code sample here, if possible:**
I cant cuz i dont know what makes it do honestly :/
**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14
- Operating system: windows
- Priority this issue should have – please be realistic and elaborate if possible:
This is annoying me and scaring me at the same time its eating all the cpu
**Relevant client options:**

- partials: MESSAGE, REACTION, USER, GUILD_MEMBER, CHANNEL,
- gateway intents: - MESSAGE_UPDATE

<!--
If this applies to you, please check the respective checkbox: [ ] becomes [x].
You don't have to modify the text to suit your particular situation – if you want to
elaborate, please do so in the description.
While it's not a requirement to test your issue on the master branch, it would make fixing
the problem a lot easier for us, so please do so if possible.

**Comment by tovade** [comment]
Please my host is madd at me

**Comment by tovade** [comment]
![image](https://user-images.githubusercontent.com/66245404/104847459-68da7d00-58e0-11eb-805e-de264c8ac716.png)

**Comment by tovade** [comment]
there is no OwnerID defined anywhere
or none asked

**Comment by iShibi** [comment]
You should provide more info and use the [Discord Server](https://discord.gg/bRCvFy9) to get help for these kinds of issues.

**Comment by zaida04** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
 https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here

**Comment by tovade** [comment]
Ishibi i asked the discord server but its nothing to do with my code its with the lib itself

**Comment by tovade** [comment]
heres my code
![image](https://user-images.githubusercontent.com/66245404/104847597-44cb6b80-58e1-11eb-94a6-0bb5452ffd79.png)

**Comment by tipakA** [comment]
If it's from discord.js, what exactly stops you from asking there?

**Comment by tovade** [comment]
they dont know whats the issue

**Comment by tipakA** [comment]
Who, where and when

Also, this is definitely not the place to discuss help you got or didn't get in the server, so please move to the server

**Comment by tovade** [comment]
this is also using all my cpu

**Comment by almostSouji** [comment]
Both SERVER_MEMBER as well as PRESENCE are not valid gateway intents. That subsequently makes me doubt `partials: all` is true either. This definitely requires more information and a __minimal__ reproducible code sample we can use to analyze the issue, should it still persist when moved out of the full code context.

--- 

Please provide a minimal reproducible code sample so we can attempt to reproduce and verify your issue. This means isolating the erroneous behavior to a fresh bot, or stripping away functionality until you can be sure the code is minimal. Also include a manual with the steps you take interacting with the code in question which results in the behavior you outlined.

Please try to reproduce the issue yourself on a fresh bot. If you can't reproduce it, it's very likely that we can't either and the code sample in question is not enough.

Boilerplate: https://discord.js.org/#/docs/main/stable/examples/ping
Minimal Reproducible sample: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by tovade** [comment]
@almostSouji sorry with all partials i mean all partials you can use when initiating the client
