### ISSUE TITLE
Bot stuck at login. Not listening to on ready event

### ISSUE THREAD

**Issue by rahultrivedi180** [discordjs/discord.js#5221]
Don't know what is going on but my bot stopped working.

![Screenshot from 2021-01-18 12-09-29](https://user-images.githubusercontent.com/32861078/104880689-0b007080-5986-11eb-8567-7599204ae7c2.png)

It stucks at login. I regenerated the bot token but still not working. It doesn't even throw any error

**Comment by psibean** [comment]
Call login _after_ setting up your event listeners....

**Comment by niklr** [comment]
Have you been able to locate the error? I'm facing the exact same problem right now.

**Comment by almeidx** [comment]
@niklr Discord is having an outage. https://discordstatus.com/incidents/pllv57603svq
