### ISSUE TITLE
bot.js with process.on

### ISSUE THREAD

**Issue by zeteticl** [discordjs/discord.js#5224]
Hello, i have a problem about process.on.
My discord bot is using sharding-file.

https://discordjs.guide/sharding/#getting-started-2
Just like the sample, i have index.js file and bot.js file.

now  the problem is  bot.js  cant use process to listen event.
but in index.js  or other files is fine to listen event.......
code like 
process.on('beforeExit', (code) => {
    console.log('Process beforeExit event with code: ', code);
  });

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
