### ISSUE TITLE
Message#deleted is never set to true

### ISSUE THREAD

**Issue by psibean** [discordjs/discord.js#5227]
**Please describe the problem you are having in as much detail as possible:**

Using `!message.deleted` or `message.deletable` to guard against multiple calls to `message#delete` doesn't work because `message#deleted` is never set to true.

**Include a reproducible code sample here, if possible:**

```js
do {
  await message.delete();
} while(!message.deleted);
```

**Further details:**

The loop will run and throw an unknown message error. `Message#deletable` will also falsely return true if the message has been deleted.

My specific use case is a message reaction collector is collecting reactions and doing certain things based on the reaction, in one case it deletes the message, then if someone reacts before the message is actually deleted, it fires another collect event where I have a call which attempts to do `reaction.users.remove(user.id);` and this hits an unknown message error as the message is deleted shortly thereafter.

- discord.js master:
- Node.js 15:
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: High, it's problematic and easy to fix.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ x] I have also tested the issue on latest master, commit hash: c4c817116f868cedb4ec20bcbf90b9b3d382621e

I'd propose updating `Message#delete` to this, but this still doesn't really solve my particular use case described above. 

```
  async delete() {
    await this.channel.messages.delete(this.id);
    this.deleted = true;
    return this;
  }
```
Not sure if something like this would be appropriate instead:
```
  async delete() {
    this.deleted = true;
    await this.channel.messages.delete(this.id).catch(error => {
      this.deleted = false;
      throw error;
    );
    return this;
  }
```
Or some other kind of "marked for deletion flag" to determine the intermediate state.

**Comment by NotSugden** [comment]
the code sample you provided works fine for me, no error is returned, even just
```js
const delete = () => {
  await message.delete();
  return message.deleted;
}
```
is returning `true`

**Comment by psibean** [comment]
> the code sample you provided works fine for me, no error is returned, even just
> 
> ```js
> const delete = () => {
>   await message.delete();
>   return message.deleted;
> }
> ```
> 
> is returning `true`

Interesting, where does it get set though because I couldn't track that down in the discord.js code. Or is it happening implicitly somewhere via some default listeners?

Either way, in this case, I'll try to debug what's going on a little bit more and I'll come back with bare minimum reproducible repo if I can narrow it down out of my code.

**Comment by didinele** [comment]
> Interesting, where does it get set though because I couldn't track that down in the discord.js code. Or is it happening implicitly somewhere via some default listeners?

I have just brought this up in the #library-discussion channel of the Discord server.

The `MessageManager#delete` method that is being called never sets this state. It runs the HTTP request which causes Discord to fire a `MESSAGE_DELETE` packet, which is what actually updates the state internally in discord.js.

**Comment by psibean** [comment]
As per the discussion on discord, feel free to close this unless there's still an argument for some sort of underlying issue here.

**Comment by almostSouji** [comment]
Relying on the websocket event is coherent with how the Discord client handles message deletion. The use case presented on the discord server should be handled otherwise.
