### ISSUE TITLE
TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by jramosss** [discordjs/discord.js#5229]
when trying to send an embed message with the queue, i use my function make_embed_fields, which builds an array of dicts `{name : x, value : x}` , but when i do 
```js
const embeds = await make_embed_fields(queue,current_song);
const message = new Discord.MessageEmbed()
.addFields(embeds)
```

my compiler throws the title error,

**Comment by almostSouji** [comment]
version 12.0.0+ requires node 12.0.0+ to run.
