### ISSUE TITLE
Message Replies

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/discord.js#5233]
**Is your feature request related to a problem? Please describe.**
Users can reply to messages, and there is a [`.reference`](https://discord.js.org/#/docs/main/stable/typedef/MessageReference) property on the message object, to see what message it is a reply to. However, there is no way to send a reply to a message (other than the [`.reply()`](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=reply) method, which is pretty much useless. Even though it is built into the Discord API, at the [Create Message](https://discord.com/developers/docs/resources/channel#create-message) endpoint ([`message_reference` field](https://discord.com/developers/docs/resources/channel#message-object-message-reference-structure)), I can't find it anywhere in the Discord.js docs.

**Describe the ideal solution**
A way to reply to messages built into the [MessageOptions](https://discord.js.org/#/docs/main/stable/typedef/MessageOptions) typedef. Here is the code that I worked out using `client.api`:
```js
client.api.channels[message.channel.id].messages.post({
   data: {
      "content": "This is a reply!",
      "tts": false,
      message_reference: {
         message_id: message.id,
         guild_id: message.guild.id,
         channel_id: message.channel.id
      }
   }
})
```

**Describe alternatives you've considered**
Making a direct request to the Discord API.

**Additional context**
Here's a screenshot of the result:
![image](https://user-images.githubusercontent.com/76178582/105251653-c9f88f80-5b30-11eb-957a-382f79bb28a9.png)

**Comment by monbrey** [comment]
`Message.reply()` has been repurposed for this on the master branch, and it's also possible via `TextChannel.send()` MessageOptions as you suggested.

It will be released into the stable version with v13

**Comment by vBread** [comment]
Inline replies will be added in v13. The PR for replies (#4874) was already merged into the master branch, so you can install directly from there you want the feature early.

**Comment by YodaLightsabr** [comment]
Oh okay, thanks.

**Comment by YodaLightsabr** [comment]
> `Message.reply()` has been repurposed for this on the master branch, and it's also possible via `TextChannel.send()` MessageOptions as you suggested.
> 
> It will be released into the stable version with v13

Also, please unban me from the server or look at my appeal.

**Comment by almostSouji** [comment]
Discord ban appeals do not belong on GitHub. The only thing this might net you is removal from the repository.
