### ISSUE TITLE
message.content is a number when the message is empty and has an attachment

### ISSUE THREAD

**Issue by itsgaryk** [discordjs/discord.js#5235]
**Please describe the problem you are having in as much detail as possible:**
As the title states the value type of message.content is seen as a number when the message is empty and has an attachment.

**Include a reproducible code sample here, if possible:**
```js
const fs = require('fs');
const Discord = require('discord.js');
const client = new Discord.Client();
client.on('message', async message => {

console.log("Content: ",message.content,");
console.log("Is not a number? ", isNaN(message.content);
console.log(Number attachments: ", message.attachments.size);
})
```

**Further details:**
No further details

- discord.js version:  12.5.1
- Node.js version: 14.15.3
- Operating system: Win 10 x64
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
The attachment is not relevant. We supply the content as it arrives from the API - an empty string if there is none. `isNaN("")` returning false, thus suggesting it is indeed a number is a JavaScript "issue", there is nothing we can do. You should probably also check the length of the string.
