### ISSUE TITLE
onready is executed several times

### ISSUE THREAD

**Issue by Dealcraft** [discordjs/discord.js#5240]
**Please describe the problem you are having in as much detail as possible:**
When the bot is online, part of the onready event is triggered several times. The log call is executed once, but the message is sent several times and at least once a day even though the bot does not go offline

**Include a reproducible code sample here, if possible:**

```js
bot.on('ready', async () =>{
  console.log(`Logged in as ${bot.user.username}...`);
  bot.user.setActivity(`${config.prefix}commands`, {type: "WATCHING"});
  bot.channels.fetch('<channelid>').then(channel => embed.info(channel, `Ich bin wieder online\nFür eine Commandübersicht steht dir ${config.prefix}commands zur Verfügung`, "Bot online"));
})
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.18.3
- Operating system: online(repl.it)
- Priority this issue should have – please be realistic and elaborate if possible: low to medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
Use once instead <https://nodejs.org/api/events.html#events_emitter_once_eventname_listener>
