### ISSUE TITLE
oldMember object of guildMemberUpdate event doesn't reference the old User if it's what changed

### ISSUE THREAD

**Issue by ledlamp** [discordjs/discord.js#5249]
**Please describe the problem you are having in as much detail as possible:**
Say for example, there's an avatar change; the "userUpdate" event will emit with the old and new avatar info as desired, and the "guildMemberUpdate" event will emit for each guild they're in, _however_, the oldMember from this event doesn't reference the old User object, so oldMember.user.avatar is the same as newMember.user.avatar.

Presumably it's just a getter that gets it from cache so it's understandable why this happens, but it's not the behavior you might expect. I wanted to detect avatar changes from guildMemberUpdate, but found that both oldMember.user.avatar and newMember.user.avatar were always the same (the new one). I used userUpdate event instead, which is fine, but considering that this event _does_ have the old User object, I think the oldMember from guildMemberUpdate could be made to reference this same User object, if it's what changed. (only if it didn't change (i.e. nickname change and no userUpdate event), it should be the same object)

**Include a reproducible code sample here, if possible:**

```js
var Discord = require("discord.js");
console.log(process.version, Discord.version);
var client = new Discord.Client();
client.login("token");
client.on("guildMemberUpdate", (oldMember, newMember) => console.log("guildMemberUpdate", oldMember.user == newMember.user)); // always logs true, even if an accompanying userUpdate is emitted with it
client.on("userUpdate", (oldUser, newUser) => console.log("userUpdate", oldUser == newUser)); // always logs false
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: v15.6.0  or v14.15.4
- Operating system: Windows 10 19042.746 or CentOS 8
- Priority this issue should have – please be realistic and elaborate if possible: Low, you can just use userUpdate instead. 

**Relevant client options:**

- partials: none (idk what this is)
- gateway intents: presence, members
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
is this maybe an extension of #4800 ?

**Comment by ckohen** [comment]
This behavior is at least noted for the time being in #5161 and indeed seems like an extension of #4800
