### ISSUE TITLE
No selfbot?

### ISSUE THREAD

**Issue by Haizanjs** [discordjs/discord.js#5252]
When did the support for self-bot get removed as per discords tos.

**Comment by zaida04** [comment]
https://github.com/discordjs/discord.js/pull/2559

**Comment by Haizanjs** [comment]
> #2559

any way i can npm install discord.js@old version with it in

**Comment by anandre** [comment]
We do not support self-bots in any way, shape or form since Discord stopped permitting them on the platform.  Please do not keep asking here, as the issue tracker is not suited for questions such as this in the first place.

**Comment by Haizanjs** [comment]
Closed.
