### ISSUE TITLE
Attempting to delete specific user reactions deletes the entire reaction

### ISSUE THREAD

**Issue by HexDevv** [discordjs/discord.js#5255]
**Please describe the problem you are having in as much detail as possible:**
Whenever I attempt to delete a reaction, it deletes the entire reaction, rather than just the users reaction.
![yFmrtcVy7y](https://user-images.githubusercontent.com/17961641/105622590-96f11d00-5e0a-11eb-948d-4d2e2a0180a5.gif)

**Include a reproducible code sample here, if possible:**
The following below is literally the only part where it deletes a reaction.
I have also tweaked the restTimeOffset to 200, however this has previously not had issues, and pushing it back upto defaults reproduces the same problem.
```js
const reactionsCollection = await m.awaitReactions(profilefilter, {time:60000, maxEmojis: 1});
if (reactionsCollection.has('❌')) {msg.delete(); i_ = true; client.temp[msg.author.id].p = false; return m.delete();}
if (reactionsCollection.has('▶️')) {if (i <= profiles.length-2) {i++}; i_ = true; await m.reactions.resolve('▶️').users.remove(msg.author.id);}
if (reactionsCollection.has('◀️')) {if (i >= 0) {i--}; i_ = true; await m.reactions.resolve('◀️').users.remove(msg.author.id);}
```

**Further details:**

- discord.js version: ^12.5.1
- Node.js version: v14.15.4
- Operating system: Windows 10 Pro 20H2
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: f95f5dcd791b39c6a4d60dc8d64b0287e06ed768

**Comment by HexDevv** [comment]
I did a bit more digging and it turns out that it does the same issue both when the bot is online (obviously) and offline

Bot Online
![](https://i.imgur.com/eokHN4P.gif)
Bot Offline
![](https://i.imgur.com/uRC44XN.gif)

**Comment by iShibi** [comment]
If the bot is offline, how is the command even working?

**Comment by HexDevv** [comment]
> If the bot is offline, how is the command even working?

Thats my bad on that one, didn't explain it properly. I turn on the bot to run the command, I wait for it to run, then I turn off the bot. I think I also messed up which way they went so thats my bad and I'll edit it now

**Comment by SpaceEEC** [comment]
If the whole emoji is removed while the bot is offline another bot is removing it. (Or the bot is not actually offline).

**Comment by HexDevv** [comment]
> If the whole emoji is removed while the bot is offline, another bot is removing it. (Or the bot is not actually offline.)

I actually cannot believe I didn't think of this. Has a rogue bot in the server. Cheers for the help 👍
