### ISSUE TITLE
Consistent async/await api for client ready status

### ISSUE THREAD

**Issue by circa10a** [discordjs/discord.js#5258]
**Is your feature request related to a problem? Please describe.**
It would be much cleaner to have a method that returns a promise for the client ready status to make code easier to read when using async/await.

**Describe the ideal solution**

Current:

```javascript
const client = new Discord.Client();
await client.login(freeDevShit.token);
client.once('ready', () => {
  postToDiscordGuilds(client);
});
```

Ideal:

```javascript
const client = new Discord.Client();
await client.login(freeDevShit.token);
await client.ready();
postToDiscordGuilds(client);
```

**Describe alternatives you've considered**

Some gross `setTimeout()` promises

**Comment by wasdennnoch** [comment]
You can also already do this:
```js
await new Promise((resolve, reject) => {
	client.once("error", reject);
	client.once("ready", () => {
		client.off("error", reject);
		resolve();
	});
});
```

**Comment by iCrawl** [comment]
We most likely won't do this.

Promisifying or "waiting" for discords event to have promises resolve manually just doesn't seem great.

You can either do this by doing what @wasdennnoch posted or use a library for it: https://github.com/sindresorhus/p-event
