### ISSUE TITLE
tsdoc for typings

### ISSUE THREAD

**Issue by MrScopes** [discordjs/discord.js#5262]
**Is your feature request related to a problem? Please describe.**
I feel like it could be super useful if all (or most) of the typings were documented with tsdoc. This wouldn't be a full alternative to the docs but would help.

**Describe the ideal solution**
something around these lines, we would simply edit the existing typings to add the tsdoc / jsdoc lines
```ts
  export class Channel extends Base {
    /** Indicates whether this channel is text-based. */
    public isText(): this is TextChannel | DMChannel | NewsChannel;
  }
```
works perfectly fine in testing
![image](https://user-images.githubusercontent.com/29683770/105788298-35d26200-5f4e-11eb-9e8e-b49cc9b4dd7e.png)
we could also include examples
```ts
    /** 
     * When concatenated with a string, this automatically returns the channel's mention instead of the Channel object.
     * @example
     * // Logs: Hello from <#123456789012345678>!
     * console.log(`Hello from ${channel}!`);
     */
    public toString(): string;
```
![image](https://user-images.githubusercontent.com/29683770/105788407-77630d00-5f4e-11eb-8c73-beaa0674cd1b.png)

**Describe alternatives you've considered**
Checking the docs each time I've needed it.

**Additional Context**
I know this would take a decent amount of time. I'm down to help if this is approved.\
Here's an example for `Channel` copied directly from the docs:
```ts
  export class Channel extends Base {
    constructor(client: Client, data?: object);
    /** The time the channel was created at */
    public readonly createdAt: Date;
    /** The timestamp the channel was created at */
    public readonly createdTimestamp: number;
    /** Whether the channel has been deleted */
    public deleted: boolean;
    /** The unique ID of the channel */
    public id: Snowflake;
    /**
     * The type of the channel, either:\
     * `dm` - a DM channel\
     * `text` - a guild text channel\
     * `voice` - a guild voice channel\
     * `category` - a guild category channel\
     * `news` - a guild news channel\
     * `store` - a guild store channel\
     * `unknown` - a generic channel of unknown type, could be Channel or GuildChannel
     */
    public type: keyof typeof ChannelType;
    /** 
     * Deletes this channel. 
     * @example
     * // Delete the channel
     * channel.delete()
     *  .then(console.log)
     *  .catch(console.error); 
     */
    public delete(reason?: string): Promise<Channel>;
    /** Fetches this channel. */
    public fetch(force?: boolean): Promise<Channel>;
    /** Indicates whether this channel is text-based. */
    public isText(): this is TextChannel | DMChannel | NewsChannel;
    /** 
     * When concatenated with a string, this automatically returns the channel's mention instead of the Channel object.
     * @example
     * // Logs: Hello from <#123456789012345678>!
     * console.log(`Hello from ${channel}!`);
     */
    public toString(): string;
  }
```
![image](https://user-images.githubusercontent.com/29683770/105789195-fd338800-5f4f-11eb-8207-218ba7747609.png)

**Comment by advaith1** [comment]
While this would be useful, it will not happen in the current js version so the docs will not be duplicated. In the planned ts rewrite in the -next repo, this will not be necessary because the typings will not be separate from the code and docs.

**Comment by MrScopes** [comment]
> the typings will not be separate from the code and docs.

the typings could still technically be tsdoc'd for explanation
