### ISSUE TITLE
Problem with the premiumTier

### ISSUE THREAD

**Issue by JustClefory** [discordjs/discord.js#5264]
![unknown (8)](https://user-images.githubusercontent.com/71458126/105875786-37426f80-5fcc-11eb-9c2e-94eeede47151.png)
Problem with the premiumTier

**Comment by zaida04** [comment]
Please do not disregard the issue template.

> 
> **Please describe the problem you are having in as much detail as possible:**
> 
> **Include a reproducible code sample here, if possible:**
> 
> ```js
> // Place your code here
> ```
> 
> **Further details:**
> 
> - discord.js version:
> - Node.js version:
> - Operating system:
> - Priority this issue should have – please be realistic and elaborate if possible:
> 
> **Relevant client options:**
> 
> - partials: none
> - gateway intents: none
> - other: none
> 
> 
> 
> - [ ] I have also tested the issue on latest master, commit hash:

**Comment by iShibi** [comment]
@JustClefory What even is the problem here? `Guild#premiumTier` gives you the premium tier of the guild, which in your case is `1`.  

Using the template and providing more context would have helped.

**Comment by SadMap** [comment]
> @JustClefory What even is the problem here? `Guild#premiumTier` gives you the premium tier of the guild, which in your case is `1`.
> 
> Using the template and providing more context would have helped.

guild has 0 boost and this is tier 0

**Comment by SadMap** [comment]
> ![unknown (8)](https://user-images.githubusercontent.com/71458126/105875786-37426f80-5fcc-11eb-9c2e-94eeede47151.png)
> Problem with the premiumTier

CNR
`client.on('ready',() => {
	client.guilds.cache.forEach(g => {
		console.log(g.premiumTier,g.premiumSubscriptionCount)
	})
})`
output
`0 0`
