### ISSUE TITLE
Discord.js .get undefined error

### ISSUE THREAD

**Issue by CodeTyper06** [discordjs/discord.js#5265]
idk why this is happing but there is the cmd:
const memberTarget = message.member.cache.get(member.id);
and console's error img:
![err](https://user-images.githubusercontent.com/50835924/105889818-a8f7d900-601f-11eb-81fe-4f176af9c45f.PNG)

**Comment by vBread** [comment]
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the Discord server instead of opening an issue – you will get redirected there anyway.
