### ISSUE TITLE
Not sending messages.

### ISSUE THREAD

**Issue by ati0ns** [discordjs/discord.js#5268]
**Please describe the problem you are having in as much detail as possible:**
When my bot ask to send a message, the promise stills pending forever.
**Include a reproducible code sample here, if possible:**

```js
message.channel.send("some string")
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.5.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
That's not a reproducible sample. I can't see anything any my bot on 12.5.1 can send messages without any issues. Provided you can actually reproduce this after some time (API outages can occasionally happen) enable debugging and listen to the "rateLimit" event and provide the logs.

```js
client.on('debug', console.log)
      .on('warn', console.log)
      .on('rateLimit', console.log)
```

**Comment by ati0ns** [comment]
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 996
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 6
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 260ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1
[WS => Shard 0] [READY] Session c5d32136ab47b2c9c1f0c49bfb9e547d.
[WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[WS => Shard 0] Heartbeat acknowledged, latency of 112ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 117ms.

**Comment by almostSouji** [comment]
Nothing out of the ordinary in what you show. What makes you think the promise never resolves?

I can not reproduce this behavior with our ping-pong sample: https://discord.js.org/#/docs/main/stable/examples/ping

**Comment by ati0ns** [comment]
```js
export default async message => {
    console.log(await message.channel.send("some string"))
```
It's never logged.

**Comment by ati0ns** [comment]
I tried the ping-pong sample and it worked so I guess my handler is wrong, yet it shouldn't be but so it is not a bug from djs.
