### ISSUE TITLE
Error using GuildChannel.setTopic()

### ISSUE THREAD

**Issue by PanSzelescik** [discordjs/discord.js#5273]
**Please describe the problem you are having in as much detail as possible:**
I have a bot which changes topic, but today after update to latest commit from master (5ac3b57f9bd53d1c20549a70942b023826f6f726) I have an Error:
```js
DiscordAPIError: Invalid Form Body
type: Value "text" is not int.
    at RequestHandler.execute (C:\Git\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:152:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Git\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:37:14)
    at async TextChannel.edit (C:\Git\bot-main\node_modules\discord.js\src\structures\GuildChannel.js:357:21) {
  method: 'patch',
  path: '/channels/769946367970902066',
  code: 50035,
  httpStatus: 400
}
```
I also tested on latest version 12.5.1 and topic is changing **without Error**.
I think this is after this commit: 5ac3b57f9bd53d1c20549a70942b023826f6f726

**Include a reproducible code sample here, if possible:**

```js
client.channels.cache.get('769946367970902066').setTopic('Test').then(console.log).catch(console.error)
```

**Further details:**

- discord.js version: commit 5ac3b57f9bd53d1c20549a70942b023826f6f726
- Node.js version: 14.15.3
- Operating system: Debian 10 and Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
I can't change TextChannel topic.

**Relevant client options:**

- partials: none
- gateway intents: NON_PRIVILEGED
- other: none

I have also tested the issue on latest master, commit hash: 5ac3b57f9bd53d1c20549a70942b023826f6f726

**Comment by almostSouji** [comment]
known and going to be fixed with #5251
