### ISSUE TITLE
Unable to solely edit allowedMentions

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#5277]
**Please describe the problem you are having in as much detail as possible:**
#4269 introduced a bug: utilising `<message>.edit()` and supplying _only_ `allowedMentions` no longer does anything.

Since `typeof content === 'undefined'` is present, `allowedMentions` are not considered and will always result in `undefined` if no content is present.

**Include a reproducible code sample here, if possible:**

```js
(async () => {
  const a = await <channel>.send(`${<role>}`);
  
  a.edit({
    allowedMentions: {
      parse: []
    }
  });
})();
```

**Further details:**

- discord.js version: 12.5.0
- Node.js version: 15.6.0
- Operating system: macOS Big Sur 11.0.1
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: None
- gateway intents: None
- other: None

- I have also tested the issue on latest master, commit hash: cee6cf7

**Comment by NotSugden** [comment]
afaik theres no benefit to editing out a mention, what would be the point in this?

**Comment by Jiralite** [comment]
> afaik theres no benefit to editing out a mention, what would be the point in this?

Benefit or not, the point is that this is not functioning in discord.js correctly.

**Comment by iCrawl** [comment]
I don't quite understand.

If editing in/out mentions does nothing, why would it even need to function?
If it comes down to it, you use an API call for a noop.

**Comment by ckohen** [comment]
There is actually a use case this affects now, a message that is a reply with only an embed. You currently have to pass allowed_mentions every time you edit to avoid "mentioning" the author due to https://github.com/discord/discord-api-docs/issues/1864

The same issue describes the other use case, suppressing embeds.

**Comment by Jiralite** [comment]
> I don't quite understand.
> 
> If editing in/out mentions does nothing, why would it even need to function?
> If it comes down to it, you use an API call for a noop.

Hi there, I don't believe you understand the issue! Let me try to make it clear and possibly use an example too!

Let's say a message is sent to a channel as such:
```JavaScript
// Where `message` is a an instance of `Message`:
message.channel.send("hi hello <@618976181026422814> here are your amazing things", {
  embed: {
    title: "Amazing things",
    fields: [
      {
        name: "Amazing thing #1",
        value: "!"
      }
    ]
  },
  allowedMentions: {
    parse: []
  }
});
```
For whatever reason, another "amazing thing" has appeared out of nowhere, and that message is now going to be edited:
```JavaScript
// Where `message` is the aforementioned message object:
message.edit({
  embed: {
    title: "Amazing things",
    fields: [
      {
        name: "Amazing thing #1",
        value: "!"
      },
      {
        name: "Amazing things #2",
        value: "!!"
      }
    ]
  },
  allowedMentions: {
    parse: []
  }
});
```
The message has now been edited. However, since there was no message content provided, `allowedMentions` is ignored by discord.js. This means that upon refreshing the client (as the client does not update edited `allowed_mentions`), the mention border will appear.

To further add to the problem, there is a [Discord issue](https://github.com/discord/discord-api-docs/issues/1864) which states editing a message simply wipes `allowed_mentions` on it. This means other methods in discord.js will wipe `allowed_mentions`, such as `<Message>.suppressEmbeds()`. This isn't a discord.js issue, but you may find users mitigating this Discord problem by passsing solely `allowedMentions` as an edit to a message in the meantime. This however will not work which is the result of this issue.

I hope this helps your understanding!

**Comment by imconnorngl** [comment]
While this may be a necropost until this is fixed if there's no content on your message simply add "\u200b" which will create blank content and thus fix your issue.

**Comment by Jiralite** [comment]
@almostSouji - this isn't a Discord bug! This is an issue with the library. If I remove the check discord.js has in place here, it works fine!

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
