### ISSUE TITLE
Typescript Channel.send definition missing

### ISSUE THREAD

**Issue by weslyo** [discordjs/discord.js#5280]
The `Channel` class' `send()` method is missing from the Typescript definition files. I also see it is not in the documentation so I may be referencing an older way to send messages to channels.

The following code wont compile as "Property send does not exist on type Channel".
```js
import Discord from 'discord.js';
//....
let channel = await this.discordClient.channels.fetch(<channelId>);
channel.send('test');
```
Switching away from Typescript, the same code will work.
```js
let Discord = require('discord.js');
//....
let channel = await this.discordClient.channels.fetch(<channelId>);
channel.send('test');
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.4
- Operating system: Windows 10

**Comment by almostSouji** [comment]
Channels in this category can be any type of channel (news, voice, category, store...) not just text. if you retrieve by id chances are you know what type you are expecting and can assert or guard it accordingly. If you want to make sure it's a text-like channel [#isText](https://discord.js.org/#/docs/main/stable/class/Channel?scrollTo=isText) is available as guard.
