### ISSUE TITLE
Throw when identify limit is fully depleted instead of delaying

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#5282]
**Is your feature request related to a problem? Please describe.**

Client stalls indefinitely when identify limit is depleted. To find the source of the misbehavior users currently have to go great length (adding a listener for the `"debug"` event) to find out what's stalling their bot

**Describe the ideal solution**

Instead of just preventing going over the limit, throw an error

**Describe alternatives you've considered**

(maybe optionally restore the old behavior with explicit opt-in, the default should be throwing - noone wants to wait for 24h for a successful login, let's be real)

**Additional context**

**Comment by iCrawl** [comment]
This should be on fast track for v13
