### ISSUE TITLE
bug: Message#deletable throws

### ISSUE THREAD

**Issue by RealShadowNova** [discordjs/discord.js#5284]
**Please describe the problem you are having in as much detail as possible:**

I'm having issues when running `Message#deletable`, where it throws an error pointing to [this line](https://github.com/discordjs/discord.js/blob/cee6cf70ce76e9b06dc7f25bfd77498e18d7c8d4/src/structures/Message.js#L392).

![image](https://user-images.githubusercontent.com/46537907/106534603-7851ec80-64c2-11eb-9894-bf4d62040f18.png)

**Include a reproducible code sample here, if possible:**

```js
// Have access to a message object: e.g. "message" event
message.deletable;
```

![image](https://user-images.githubusercontent.com/46537907/106534657-961f5180-64c2-11eb-8131-abe7934241ff.png)

**Further details:**

- discord.js version: v12.5.1
- Node.js version: v15.5.1
- Operating system: Windows Pro 19042.782
- Priority this issue should have – please be realistic and elaborate if possible:
Not extremely important if you prefer to use `Channel.permissionsFor(ClientUser).has(Permissions.FLAGS.MANAGE_MESSAGES)` over `Message.deletable` for `Message.delete()` checks

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by zaida04** [comment]
Already fixed in https://github.com/discordjs/discord.js/pull/5066
