### ISSUE TITLE
[TOKEN_INVALID] 

### ISSUE THREAD

**Issue by pistaszeq** [discordjs/discord.js#5286]
i'm writing a discord bot, and i have a token invalid error
i'm using this code
const Discord = require('discord.js');

const client = new Discord.Client();

const prefix = '-';

client.once('ready', () =>{
    console.log('bot_online');
});

client.on('message', message =>{
    if(!message.content.startsWith(prefix) || message.author.bot) return;

    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase();
    
    if(command === 'ping'){
        message.channel.send('pong!');
    } else if (command == 'yt'){
      message.channel.send('https://www.youtube.com/channel/UCqreLW8yrT-ZLmUZg1yINCg');
    }else if (command === 'webeye'){
        message.channel.send('https://webeye.ivao.aero');
    }
});
client.login('my token from discord developer potral');

pls help

**Comment by adrifcastr** [comment]
Please make sure to _actually_ use the token and **not** the client secret.

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by pistaszeq** [comment]
i'm an idiot thanks
it worked
