### ISSUE TITLE
messageReactionAdd doesn't give Guild Member object if it happened in a guild 

### ISSUE THREAD

**Issue by Rubenennj** [discordjs/discord.js#5291]
Hello, I'm here to suggest something that'd maybe make things easier to work with. 
So as we all know the discord api provides a message reaction add event, this event gives user id, guild id, partial reaction... BUT, it also gives a member object if it happened in a guild
This is what I wanted to talk about, discord.js' messageReactionAdd event gives MessageReaction and User objects, but none of these give the member object given by discord api if it happened in a guild.
May I know why? It's annoying when you have to fetch the member yourself when the api already gives it in the event, it's something that would be really appreciated.

**Comment by tipakA** [comment]
PR #5177 exists, and was closed.

**Comment by monbrey** [comment]
> it appears that library doesn't make use of emitted member object

Not true - #4969 added member caching to `Action#getUserFromMember`, which is used by the event handler.

**Comment by almostSouji** [comment]
The member object is cached as of 8b91ac5  and you can retrieve it from the `<MessageReaction>.message.guild.members` cache via the emitted User objects id.  Emitting `User|GuildMember` was rejected before, as outlined in #5177, making this a duplicate.
