### ISSUE TITLE
message.reply breaks with embeds & allowed mentions

### ISSUE THREAD

**Issue by Landrover100435** [discordjs/discord.js#5297]
When using message.reply on the master branch, if you reply with text and set allowedmentions-repliedUser to false, it works fine. However if you do the same with an embed, it sends `[object Object]` to the channel.
```js
message.reply(new Discord.MessageEmbed().setTitle("Testing"), {allowedMentions: {repliedUser: false}})
```

- discord.js version: github:discordjs/discord.js#cee6cf70ce76e9b06dc7f25bfd77498e18d7c8d4
- Node.js version: 14.15.1
- Operating system: Windows 10 
- Priority this issue should have – please be realistic and elaborate if possible: Medium
- partials: `MESSAGE`, `CHANNEL`, `REACTION`
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
This isn't a bug in Message#reply - TextChannel#send functions the same way in v12.

`.send(MessageEmbed, options)` is not a valid combination of parameters. The correct way to do this is `.send({ embed: <MessageEmbed>, <other options> })`

**Comment by Landrover100435** [comment]
Ahh, sorry. Ty for the help :)
