### ISSUE TITLE
WebhookEvents do not work

### ISSUE THREAD

**Issue by NorteX-dev** [discordjs/discord.js#5305]
**Please describe the problem you are having in as much detail as possible:**
This:
```js
client.ws.on("ANY_RAW_EVENT", async data => {});
```
code is supposed to listen to a websocket event. However, when initialized this error is being thrown:
**DiscordAPIError: Invalid Form Body
CONTENT_TYPE_INVALID: Expected "Content-Type" header to be one of {'application/json'}.**
I was unable to locate an error in my code and just commenting out this line removes the error completely.

**Reproducible sample:**
```js
const Discord = require("discord.js");

const client = new Discord.Client();

client.ws.on("MESSAGE_CREATE", async interaction => {});

client.login();
```
**Stacktrace:**
```js
(node:10524) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
CONTENT_TYPE_INVALID: Expected "Content-Type" header to be one of {'application/json'}.
    at RequestHandler.execute (C:\Users\piom2\Desktop\Projects\JS\Slash commands\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\piom2\Desktop\Projects\JS\Slash commands\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
```

**Further details:**

- discord.js version: 12.5.1 (@latest)
- Node.js version: 14.15.3
- Operating system: Win10 x64
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this.

<details><summary>The code I used</summary>

```js
const { Client } = require("discord.js");

const client = new Client();

client.ws.on("MESSAGE_CREATE", async data => {
    console.log(data);
});

client.login();
```

</details>

Please update your issue to contain a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example). (That you verified to actually reproduce this error independently of your other code.)
Also please add the stacktrace of your error.

**Comment by NorteX-dev** [comment]
> I'm unable to reproduce this.
> 
> The code I used
> ```js
> const { Client } = require("discord.js");
> 
> const client = new Client();
> 
> client.ws.on("MESSAGE_CREATE", async data => {
>     console.log(data);
> });
> 
> client.login();
> ```
> 
> Please update your issue to contain a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example). (That you verified to actually reproduce this error independently of your other code.)
> Also please add the stacktrace of your error.

Edited to fit the requirements. The code is pretty much the same as yours, I don't know why that error keeps appearing.

**Comment by NorteX-dev** [comment]
Oops, so, I've discovered that the issue was not caused by this listener... Sorry for making the issue, I really was sure it was this after 1 hour of trying, I don't know what's with me today...
