### ISSUE TITLE
message.channel.send

### ISSUE THREAD

**Issue by ITWolfHypixel** [discordjs/discord.js#5308]
**Please describe the problem you are having in as much detail as possible:*When u type the same strings bot will repeat it again and again, like u sent 123 and bot send 123 123 123 123 123 etc.*

**Include a reproducible code sample here, if possible:**

```js
onion.on('message', message => {
    if (message.content === '123') {
      message.channel.send('123');
    }
  });
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.4
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: -

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Darqam** [comment]
Your bot is replying to itself, you check for `123` and send `123`.
