### ISSUE TITLE
Documentation missing destroy method on dispatcher

### ISSUE THREAD

**Issue by DaliborTrampota** [discordjs/discord.js#5313]
I couldnt find a way to make a change for discordjs docs but I spent good hour finding how to stop playing music without actually kicking the bot out of vc then I found in source code destroy method which should be in the docs along with "finished" event

**Comment by almostSouji** [comment]
This is documented through "extends", same as Client#on or other native node APIs.
![image](https://user-images.githubusercontent.com/26532370/107570112-65899700-6be9-11eb-9b0d-296976411df5.png)
<https://nodejs.org/api/stream.html#stream_class_stream_writable>

**Comment by DaliborTrampota** [comment]
> This is documented through ["extends"](https://discord.js.org/#/docs/main/12.5.1/class/StreamDispatcher), same as Client#on (for EventEmitter) or other native node APIs.
> ![image](https://user-images.githubusercontent.com/26532370/107570112-65899700-6be9-11eb-9b0d-296976411df5.png)
> <https://nodejs.org/api/stream.html#stream_class_stream_writable>
> 
> Documenting any and all methods and properties from all extended structures even from outside the library isn't really feasible and would result in major clutter.

Ok buy just those two wouldn't hurt anyone they are really important for music features and they should be seen in the documentation. When I was trying to detect when the song ends few years back it took me over a day asking everywhere and some users saying it's "end" event or "finish" when it's "finished". But whatever just I'd be happy to see it there.

**Comment by amishshah** [comment]
To be consistent, those methods aren't included in the API documentation for the reason Souji gave. However, we understand their importance which is why they're listed in the voice topic on the documentation itself ([see here](https://discord.js.org/#/docs/main/stable/topics/voice)) as well as the official voice guide ([see here](https://discordjs.guide/voice/))
