### ISSUE TITLE
Bot unable to login for 24hrs

### ISSUE THREAD

**Issue by atomheartother** [discordjs/discord.js#5315]
This is the strangest bug I've ever encountered, and I would like some help. I'm the owner of a fairly large (~7k guilds) bot using `discord.js`. I have been using discord.js in production for over a year now. This bug started occuring last week on Wednesday around noon (GMT +1). This bug caused an outage for almost 24 hours, until it apparently resolved itself.... Until today, Wednesday, noon, where the bug occured again. As of right now I am 10 hours into trying to debug this and I cannot for the life of me figure out what is causing it.

**Please describe the problem you are having in as much detail as possible:**
The bot runs fine for a bit, then it starts spitting out `MaxListenersExceededWarning`s repeatedly (see logs here
[log_1.txt](https://github.com/discordjs/discord.js/files/5961774/log_1.txt)
). At that point, the bot can still *receive* Discord events but it is unable to *respond* to them in any way (you can see the commands being executed in that log, but the bot is unresponsive).

Restarting the bot then causes it to be absolutely unable to spawn any shards - instead the bot fails immediately with an UnhandledPromiseRejection error:

<details>
<summary>UnhandledPromiseRejection error:</summary>

```
qtweet_1    | 10/02/2021, 22:52:10 Spawning shards...
qtweet_1    | UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".
qtweet_1    | 10/02/2021, 22:52:16 Spawning shards...
qtweet_1    | UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".
```

</details>

When this happens, it lasts between a few minutes and an hour, and no amount of restarts will fix it. After that time, the bot can then spawn again, everything is fine... Until the `MaxListeners` message spam occurs again, and the whole process repeats. 

As far as I know, this goes on until Thursday, around noon, GMT+1, and then everything's fine, the bot is completely stable for another week. I'll know for sure in 12 hours if this behavior is consistent compared to last week.

I should note I have try/catch blocks around **every single call** on my bot, the UnhandledPromiseRejection is happening inside `discord.js`'s ShardingManager as far as I can tell (see the reproducible code sample later).

**Include a reproducible code sample here, if possible:**

While these complete outages are happening, I tried to reduce my bot's code to the barest minimum possible, see if any part of the code could be causing this error... And this bug *keeps happening* when my code is nothing but this:

```js
// index.js
import log from './log';
import { ShardingManager } from 'discord.js';

const manager = new ShardingManager('dist/src/shard/bot.js', { token: process.env.DISCORD_TOKEN, execArgv: ['-r', 'esm'] });

const start = async () => {
  try {
    log("Spawning shards...");
    manager.spawn('auto', Number(process.env.SHARD_SPAWN_DELAY || 15000), Number(process.env.SHARD_SPAWN_TIMEOUT || 60000));
  } catch (e) {
    log("Can't spawn shard:");
    log(e);
  }
};

start();

```
```js
// shard/bot.js
console.log("Shard process created")
```

^ The above code does NOT fail with "Shard 0's process exited before its Client became ready.", which is how it __should__ fail. It fails with this message:

```
qtweet_1    | 10/02/2021, 23:10:50 Spawning shards...
qtweet_1    | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
qtweet_1    |   code: 'ERR_UNHANDLED_REJECTION'
qtweet_1    | }
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 15.7.0 (also 12.18.2)
- Operating system: Alpine Linux inside docker (Also in Ubuntu Server 20.10 directly)
- Priority this issue should have – please be realistic and elaborate if possible: Very low, this only happens to me.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by atomheartother** [comment]
**Update:** I just tried running the above code sample outside Docker and it still fails. Docker is __not__ the problem.

I also tried it with different Discord bot tokens, that is also not it.

**Comment by atomheartother** [comment]
<details>
<summary>My current test setup</summary>
```sh
ubuntu@LizServ:~/QTweetProd$ ls test/
bot.js  index.js
ubuntu@LizServ:~/QTweetProd$ cat test/index.js 
// index.js
import { ShardingManager } from 'discord.js';

const manager = new ShardingManager('test/bot.js', { token: process.env.DISCORD_TOKEN, execArgv: ['-r', 'esm'] });

const start = async () => {
  try {
    manager.spawn('auto', Number(process.env.SHARD_SPAWN_DELAY || 15000), Number(process.env.SHARD_SPAWN_TIMEOUT || 60000));
  } catch (e) {
    console.log(e);
  }
};

start();
ubuntu@LizServ:~/QTweetProd$ cat test/bot.js 
console.log("Shard spawned);
ubuntu@LizServ:~/QTweetProd$ DISCORD_TOKEN=[CENSORED] node -r esm test/index.js 
(node:42093) UnhandledPromiseRejectionWarning: #<Response>
(node:42093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:42093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ubuntu@LizServ:~/QTweetProd$
```
</details>

**Comment by atomheartother** [comment]
__So I had a breakthrough.__

**This is my bot being rate-limited by Discord**, I still don't understand why the hell `discord.js` isn't  rate-limiting properly, but the error that is causing  this HAS to be an uncaught `429: Too Many Requests` error in the ShardingManager.

I found this out because, persuaded that the only cause left was my server provider, I decided to host my bot on my personal PC at least until I figure out what's wrong... Well, after a minute or two, *no one on my network* could access Discord, and trying to login on the web interface finally provided me with proof I am not insane: a 429 error.

![image](https://user-images.githubusercontent.com/10134879/107586893-1e0f0500-6c01-11eb-869f-19a54a94d795.png)

**Comment by atomheartother** [comment]
Closing this as it's directly related to #3560

**Comment by kyranet** [comment]
> but the error that is causing this HAS to be an uncaught `429: Too Many Requests` error in the ShardingManager.

In fact, that error is from your code, `manager.spawn` [returns a Promise](https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=spawn) which you're [not awaiting](https://github.com/discordjs/discord.js/issues/5315#issuecomment-777080765)

**Comment by advaith1** [comment]
what's the response body you're getting?
