### ISSUE TITLE
slash commands required fields can be bypassed by mobile client

### ISSUE THREAD

**Issue by Assassin-1234** [discordjs/discord.js#5329]
**Please describe the problem you are having in as much detail as possible:**
if a slash command's content is set to required, mobile users can bypass that on android client
**Include a reproducible code sample here, if possible:**

```js
        if(command == "8ball") {
            const description = args.find(arg => arg.name.toLowerCase() == "content").value;
            const pronouns = ['silly', 'mommy', 'dad', 'mom', 'master', 'nii-san', 'onee-san', 'love', 'ma\'am', 'sir', 'friend', 'b-baka', 'honey'];
            const randompronoun = pronouns[Math.floor(Math.random() * (pronouns.length - 1 + 1) + 1)];
            const answer = ['nu', 'yus', 'yes', 'no', 'never', 'of course', 'hell yeah', 'hell no', 'negative', 'positive', 'not today', 'only today', 'sadly yes', 'sadly no', 'maybe', 'you bet', 'not a chance', 'it\'s a secret', 'only for today'];
            const randomanswer = answer[Math.floor(Math.random() * (answer.length - 1 + 1) + 1)];
            const ye = new discord.MessageEmbed()
                .setTitle(description)
                .setColor('RANDOM')
                .setDescription(`${randompronoun}, ${randomanswer}`);

            client.api.interactions(interaction.id, interaction.token).callback.post({
                data: {
                    type: 4,
                    data: await createAPIMessage(interaction, ye)
                }
            });
        }
```
**Further details:**

- discord.js version:12.5.1
- Node.js version:14.15.3
- Operating system:win32
- Priority this issue should have – please be realistic and elaborate if possible:
p2
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

![image](https://user-images.githubusercontent.com/68866924/107993458-79c1ff80-7000-11eb-947f-1b4832437e9c.png)

**Comment by monbrey** [comment]
We are unable to do anything about Discord's bugs and features - you should raise this in https://github.com/discord/discord-api-docs
