### ISSUE TITLE
Store.forEach is not a function

### ISSUE THREAD

**Issue by BloxyGH** [discordjs/discord.js#5333]
I'm trying to make a discord bot that lists the current Fortnite store. I'm using https://www.npmjs.com/package/fortnite for the bot. When I try to use .forEach for the store, it throws an error (Store.forEach is not a function).
`const Store =  fortnite.store()

        const Embedsz = new Discord.MessageEmbed()
        .setColor('#f47fff')
        
        Store.forEach(el => {
            Embedsz.addField(el.name, stripIndents`**- Rarity:** ${el.rarity}
            **- Price:** ${el.vbucks} V-Bucks
            **- Image:** [Click Me](${el.image})`, true)
        });`
Heres the code that defines 'fortnite' 
`const FNClient = require('fortnite')
const fortnite = new FNClient("MyApiKey")`

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
