### ISSUE TITLE
GuildMemberManager.fetch throws TypeError when run on different shard

### ISSUE THREAD

**Issue by seriallos** [discordjs/discord.js#5335]
**Please describe the problem you are having in as much detail as possible:**

In a sharded bot, trying to fetch guild members for a guild on a different shard throws an error. It is able to fetch other information like the guild and guild roles.

The specific use case for my bot is being able to have an HTTP API that can query/act on any guild from a web UI. My bot is large and needs to be able to run on multiple machines so `broadcastEval` and `fetchClientValues` aren't sufficient.

**Include a reproducible code sample here, if possible:**

index.js (Shard manager):
```js
const path = require('path');

const { ShardingManager } = require('discord.js');

const token = 'token goes here';

const manager = new ShardingManager(path.join(__dirname, 'bot.js'), {
  token,
  // make sure we have at least two shards
  totalShards: 2,
});

manager.on('shardCreate', (shard) => {
  console.log('Launching shard', shard.id);
});

manager.spawn();
```

bot.js:
```js
const { Client } = require('discord.js');

const token = 'token goes here';

const testGuildId = 'test guild id goes here';

const client = new Client();

const log = (...msg) => console.log(`  [shard-${client.shard.ids}]`, ...msg);

client.on('ready', async () => {
  log('Ready, shard', client.shard.ids);

  if (client.guilds.cache.find(g => g.id === testGuildId)) {
    log('shard', client.shard.ids, 'has the test guild');
  } else {
    log('shard', client.shard.ids, 'does not have the test guild');
  }

  try {
    log('test guild is not in this shard, force fetch');
    const guild = await client.guilds.fetch(testGuildId);
    log('test guild name:', guild.name);

    log('fetch roles');
    const roles = await guild.roles.fetch();
    log('guild has', roles.cache.size, 'roles');

    log('fetch members');
    const members = await guild.members.fetch();
    log('guild has', members.size, 'members');
  } catch (error) {
    log('Encountered an error:', error.message);
    log(error);
  }
});

client.login(token);
```

Here's example output showing the error. Guild and role fetching works, member fetching does not.

```
$ node index.js
Launching shard 0
  [shard-0] Ready, shard [ 0 ]
  [shard-0] shard [ 0 ] does not have the test guild
  [shard-0] test guild is not in this shard, force fetch
  [shard-0] test guild name: discordjs-test
  [shard-0] fetch roles
  [shard-0] guild has 8 roles
  [shard-0] fetch members
  [shard-0] Encountered an error: Cannot read property 'send' of undefined
  [shard-0] TypeError: Cannot read property 'send' of undefined
    at /[snip]/node_modules/discord.js/src/managers/GuildMemberManager.js:279:24
    at new Promise (<anonymous>)
    at GuildMemberManager._fetchMany (/[snip]/node_modules/discord.js/src/managers/GuildMemberManager.js:272:12)
    at GuildMemberManager.fetch (/[snip]/node_modules/discord.js/src/managers/GuildMemberManager.js:124:31)
    at Client.<anonymous> (/[snip]/bot.js:30:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Launching shard 1
  [shard-1] Ready, shard [ 1 ]
  [shard-1] shard [ 1 ] has the test guild
  [shard-1] test guild is not in this shard, force fetch
  [shard-1] test guild name: discordjs-test
  [shard-1] fetch roles
  [shard-1] guild has 8 roles
  [shard-1] fetch members
  [shard-1] guild has 4 members
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.18.0
- Operating system: macOS 10.15.7, debian 9
- Priority this issue should have – please be realistic and elaborate if possible: Medium/High - this is preventing me from porting an existing python bot to discord.js. It's a potentially significant impediment for a large bot to be able to build an API layer used for sophisticated web/bot management that needs to run on multiple machines.

**Relevant client options:**

See the code example, only fancy thing going on is sharding.

**Comment by monbrey** [comment]
This is expected. Fetching GuildMember's in discord.js uses the websocket rather than HTTP APIs. For this, the Guild object needs to have an assigned shard to make the websocket calls. This gets populated when Discord.js caches the guilds in the identify payload, on each individual shard.

Because you've instead fetched the Guild via the HTTP API, the `guild.shard` data isn't defined and the method will error.

As a workaround you could try a manual API call to https://discord.com/developers/docs/resources/guild#list-guild-members

**Comment by seriallos** [comment]
Gotcha, that makes sense. I think the other approach that might work is to have a slimmed down instance of the bot that connects to all shards but only does the small amount of API work without worrying about responding to messages or watching other events.

Thanks!
