### ISSUE TITLE
After v8 gateway PR, bot doesn't initially receive DMs

### ISSUE THREAD

**Issue by JMTK** [discordjs/discord.js#5337]
**Please describe the problem you are having in as much detail as possible:**
After [this ](ee5bc1a5c4e218ea1f16992694a2bff86c86d2d2) was merged, my bot user is unable to initially receive DMs. If I send myself a message using an eval command from the bot, then it will start receiving messages. Is this expected given the bullet point `channelCreate events are no longer emitted for DMs`?

**Include a reproducible code sample here, if possible:**

```js
client.on('message', console.log);
```

**Further details:**

- discord.js version: ee5bc1a5c4e218ea1f16992694a2bff86c86d2d2
- Node.js version: 15.9
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents:  ```[
        "GUILDS",
        "GUILD_MEMBERS",
        "GUILD_BANS",
        "GUILD_VOICE_STATES",
        "GUILD_PRESENCES",
        "GUILD_MESSAGES",
        "DIRECT_MESSAGES"
    ]```
- other: none

I sent myself "hi" from a Guild channel instead `client.users.cache.get(message.author.id).send('hi')`. After that, I received message events from my user.
![image](https://user-images.githubusercontent.com/877114/108464491-3eb50b80-724e-11eb-9d90-5d00220019d3.jpeg)

@advaith1 mentioned:
> you can fix it by enabling the CHANNEL partial; we should make that always on (should have been in this pr)

_Originally posted by @JMTK in https://github.com/discordjs/discord.js/issues/4879#issuecomment-781848908_

**Comment by MrMachi9** [comment]
hahahahahahahahahahahahahahahahahahahahahahhahahahahahahahahahahahahahahahahahahahahahahahahahahhahahahahahahahahahaahahahahahahahahahhhahahahahhhhhahhhahhahhhhhahhahhahahhahahhaaaaaahahahahahahhhhhahahahhahahahahahhhahahahahahahahahahahahahahhahahahahhahahahahahahahahahahahahahahahahahahahaha

**Comment by killer069** [comment]
Can you add this as an extra parameter in Client ?? and then test your method once again.

```js
partials : ['CHANNEL', 'MESSAGE']
```

**Comment by iCrawl** [comment]
Closing because stale, open a new issue if this is still a problem.
