### ISSUE TITLE
channel.send is not documented

### ISSUE THREAD

**Issue by qwelias** [discordjs/discord.js#5338]
`.send` method is implemented, but not documented on a `Channel` instance.
Neither [official docs](https://discord.js.org/#/docs/main/master/class/Channel) nor [TS definition](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L187) documents it, yet it seems like the only way to send a message to an arbitrary channel.

```js
console.log(client.channels.cache.get('channel_id').send)
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.0
- Operating system: Arch
- Priority this issue should have – please be realistic and elaborate if possible: Haeyy, that's a nice to have

**Comment by tipakA** [comment]
You need to cast it to a type that actually has possibility of messages being sent to it. [`TextChannel`](https://discord.js.org/#/docs/main/stable/class/TextChannel) for example.

Eventually, there is [`Channel#isText()`](https://discord.js.org/#/docs/main/stable/class/Channel?scrollTo=isText) that acts as a type guard for channels that can have messages.

**Comment by qwelias** [comment]
Fair enough
