### ISSUE TITLE
inviteCreate event not triggering

### ISSUE THREAD

**Issue by vitorsantos98** [discordjs/discord.js#5342]
Today i have notice the inviteCreate is not getting triggered when a user or bot creates a invite

```js
client.on('inviteCreate', invite =>{

console.log("invite: " + invite);

});

```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: v14.15.3
- Operating system: windows 10 home
- Priority this issue should have – normal

**Relevant client options:**

- partials: none
- gateway intents: none
- other:
Bot with Administrator permissions and the user

**Comment by adrifcastr** [comment]
To receive this event you application must subscribe to the `GUILD_INVITES` gateway intent. As you did not show the intents you're subscribing to, this is likely just your own fault and not related to the lib at all.

**Comment by WickedWizard3588** [comment]
I have the same problem, and I have all the intents from A-Z turned on..... even in dev portal

Bot has all the perms

**Comment by vitorsantos98** [comment]
> 
> 
> To receive this event your application must subscribe to the `GUILD_INVITES` gateway intent. As you did not show the intents you're subscribing to, this is likely just your own fault and not related to the lib at all.

i have enable the intens on the bot app and still does the same thing.

**Comment by monbrey** [comment]
Im unable to replicate this on 12.5.1.

Please include the code for your client constructor so we can see how you're specifying intents.

**Comment by WickedWizard3588** [comment]
Ok, I did some testing, and what I found was it only and only emitted if the invite was created by my bot only.....

I'll just link my Events Handler, Main File, and my Event file

<details>
    <summary>Main File</summary>
    <br>
        <pre>
            <code>
            require('module-alias/register');

const { owner, prefix, invite, token } = require('@root/config.json');
const { CommandoClient } = require('discord.js-commando');
const client = new CommandoClient({
	ws: {
		intents: [
			'GUILDS',
			'GUILD_MEMBERS',
			'GUILD_BANS',
			'GUILD_EMOJIS',
			'GUILD_INTEGRATIONS',
			'GUILD_WEBHOOKS',
			'GUILD_INVITES',
			'GUILD_VOICE_STATES',
			'GUILD_PRESENCES',
			'GUILD_MESSAGES',
			'GUILD_MESSAGE_REACTIONS',
			'GUILD_MESSAGE_TYPING',
			'DIRECT_MESSAGES',
			'DIRECT_MESSAGE_REACTIONS',
			'DIRECT_MESSAGE_TYPING',
		],
	},
	owner: owner,
	commandPrefix: prefix,
	invite: invite,
	partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],
	disableMentions: 'everyone',
	nonCommandEditable: true,
});
const blacklistedUsers = ['0', '1'];
const loadFeatures = require('@src/Features/load-features');
const loadEvents = require('@src/Events/load-events');
const setProvider = require('@handlers/sqlite');
const { join } = require('path');

client.dispatcher.addInhibitor(msg => {
	if(blacklistedUsers.includes(msg.author.id)) return { /* eslint-disable-line */
		reason: 'BlackListed',
	};
});

setProvider(client);
loadEvents(client);
loadFeatures(client);
	client.registry
		.registerDefaultTypes()
		.registerDefaultGroups()
		.registerGroups([
			['economy', 'Economy'],
			['fun', 'Fun'],
			['misc', 'Misc'],
			['moderation', 'Moderation'],
			['music', 'Music'],
			['owner only', 'Owner Only'],
			['util', 'Util'],
		])
		.registerCommandsIn(join(__dirname, '../Commands'));

client.login(token);
            </code>
        </pre>
    </br>
</details>

<details>
    <summary>Events Handler</summary>
    <br>
        <pre>
            <code>
            const { readdirSync, lstatSync } = require('fs');
const { join } = require('path');

module.exports = (client) => {
    client.on('debug', console.log);
	const readEvents = (dir) => {
		const files = readdirSync(join(__dirname, dir));
		for (const file of files) {
			const stat = lstatSync(join(__dirname, dir, file));
			if (stat.isDirectory()) {
				readEvents(join(dir, file));
			}
			else if (file != 'load-events.js') {
				const event = require(join(__dirname, dir, file));
				const evtName = file.split('.')[0];
				console.log(`Loading Event: ${evtName}`);
				client.on(evtName, event.bind(null, client));
			}
		}
	};

	readEvents('.');
};
            </code>
        </pre>
    </br>
</details>

<details>
    <summary>inviteCreate Event</summary>
    <br>
        <pre>
            <code>
                module.exports = (client, invite) => {
                    console.log('New Invite has been created');
                };
            </code>
        </pre>
    </br>
</details>

**Comment by WickedWizard3588** [comment]
This is surprising..

I did not start my bot for two days now, and surprisingly, the `inviteCreate` event fires now.....

I don't know what happened in between those two days, I just did not start my bot....

**Comment by Bulkmrslasher** [comment]
Im getting this issue now any fixes?

**Comment by Bulkmrslasher** [comment]
its on discordjs v14

**Comment by Jiralite** [comment]
Make a new issue if you have found a bug.
