### ISSUE TITLE
Webpack is being blocked

### ISSUE THREAD

**Issue by DrMeepso** [discordjs/discord.js#5346]
**Please describe the problem you are having in as much detail as possible:**

when trying to use the webpack I get this error in the console
`Access to fetch at 'https://discord.com/api/v7/gateway/bot' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
nothing I do seems to help it

**Include a reproducible code sample here, if possible:**

```js
<script type="text/javascript" src="discord.js"></script>
<script>
console.log("Starting Bot")
const bot = new Discord.Client();
bot.login("<Bot Token>");
bot.on('ready', () => {
  console.log("Bot Is Ready")
});
</script>
```

**Further details:**

- `discord.stable.min.js`
- Webbuild
- Windows
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by zaida04** [comment]
The webpacked versions are no longer supported:
https://github.com/discord/discord-api-docs/issues/2078#issuecomment-697829305
https://github.com/discordjs/discord.js/issues/4710#issuecomment-743762394
