### ISSUE TITLE
Creating webhook / from channel

### ISSUE THREAD

**Issue by Reza-PC** [discordjs/discord.js#5347]
Bug: 
**C:\Users\rtofi\OneDrive\دسکتاپ\Bot\node_modules\@discordjs\collection\dist\index.js:161
            if (fn(val, key, this))
                ^

TypeError: fn is not a function**

**Include a reproducible code sample here, if possible:**

```js
client.on('message', message =>{
  if (message.content == 'y'){
    const w = message.guild.channels.cache.find('general')

    w.createWebhook('Playerly')

  }
})
Im just testing
```

**Further details:**

- discord.js version: v12
- Node.js version: v14.15.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by chris9740** [comment]
The `Collection#find` method expects a function as the first argument, not a channel name https://discord.js.org/#/docs/collection/master/class/Collection?scrollTo=find
