### ISSUE TITLE
prism-media and tweetnacl should not be required dependencies

### ISSUE THREAD

**Issue by Fyko** [discordjs/discord.js#5351]
I believe both `prism-media` (pm) and `tweetnacl` should not be required dependencies.

### Why?
Well, for the same reason `sodium` and `libsodium-wrappers` are optional -- not all discord.js users use voice.
Especially `tweetnacl`, because it's ran through the try...catch block within [Secretbox.js](https://github.com/discordjs/discord.js/blob/d2341654fe6ef87c6048bb5bf74c394062f3f618/src/client/voice/util/Secretbox.js). 

### What do I propose?
I suggest both `prism-media` and `tweetnacl` be removed from `dependencies`.
`prism-media` should be documented as a required installation under the [Installation](https://github.com/discordjs/discord.js#installation) part of the README and an error should be thrown if a user attempts to work with voice without pm installed.
Perhaps a whole other section for installation with voice support under the Installation section and moving `sodium` and `libsodium-wrappers` out of [Optional Packages](https://github.com/discordjs/discord.js#optional-packages) and into that new section.

**Comment by amishshah** [comment]
Not sure if this will still be relevant for prism, as the next version of discord.js will use @discordjs/voice

**Comment by TheRamann** [comment]
Yeah, it would use <a href = "https://www.npmjs.com/package/@discordjs/voice"> @discordjs/voice </a> in next update.

https://www.npmjs.com/package/@discordjs/voice

**Comment by Fyko** [comment]
Very true, unsure how I forgot about voice :p
