### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/discord.js#5355]
**Please describe the problem you are having in as much detail as possible:**
I'm getting this error:
![image](https://user-images.githubusercontent.com/76178582/109363861-61dd4d80-7842-11eb-9709-ee53dd7fd759.png)
But it still works fine
![image](https://user-images.githubusercontent.com/76178582/109364690-30fe1800-7844-11eb-8a94-f0c493f459be.png)

**Include a reproducible code sample here, if possible:**
![image](https://user-images.githubusercontent.com/76178582/109363868-673a9800-7842-11eb-9eae-51ca1df5ba47.png)

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.16.1
- Operating system: Repl.it Linux
- Priority this issue should have – please be realistic and elaborate if possible: It doesn't impact the actual bot, but it's annoying to get this console message

**Relevant client options:**
- partials: none
- gateway intents: none
- other: none

edit: spelling
edit 2: DM me on Discord (YodaLightsabr#6565) and I'll invite you to the repl if you want fully-reproduceable source code.

**Comment by almostSouji** [comment]
`<Client>.api` is a private and unsupported API. We will support interactions officially after the release of v13. The current state of the PR can be viewed at https://github.com/discordjs/discord.js/pull/5106.
