### ISSUE TITLE
Addin support for video streaming in VC and DM

### ISSUE THREAD

**Issue by Kirill-iceland** [discordjs/discord.js#5356]
The current **API** only has support for audio streaming. 

**Why?**
It would open many new possibilities to interact with bots like playing **videos** from youtube and creating new types of games.

**Comment by advaith1** [comment]
Discord intentionally doesn't support video streaming for bots due to its complexity, nothing d.js can do about that

**Comment by vBread** [comment]
Bots can't stream videos.

**Comment by TheRamann** [comment]
There would be many movie streaming bots which would be pretty much illegal and discord could be in some trouble because of that.

**Comment by kyranet** [comment]
Duplicate of #4116.
