### ISSUE TITLE
Discord.js Bot Shards Instantly Die for No Reason

### ISSUE THREAD

**Issue by cobsidian-crim** [discordjs/discord.js#5360]
Hello, around maybe 2 minutes after my bot launches it automatically kills a shard and then the shard respawns and this repeats for a few hours until I hit the 1000 login limit. I double-checked my code and nothing I can find causes this, the only errors that show up are handled errors.

EDIT: when i use the debug mode, it says that it is a invalid session.

EDIT 2: heres the console log:
```js
0|index  | [WS => Manager] Session Limit Information
0|index  |     Total: 1000
0|index  |     Remaining: 50
0|index  | [WS => Shard 1] An open connection was found, attempting an immediate identify.
0|index  | [WS => Shard 1] [IDENTIFY] Shard 1/18
0|index  | [WS => Shard 8] Shard received all its guilds. Marking as fully ready.
0|index  | I am online, how amazing!! HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAH
0|index  | Launched shard 9
0|index  | Provided token: TOKEN***************************
0|index  | [WS => Shard 1] [INVALID SESSION] Resumable: false.
0|index  | [WS => Shard 1] Failed to connect to the gateway, requeueing...
0|index  | [WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
```

heres my sharding file if this helps:

```js
const { ShardingManager } = require('discord.js');
const botsettings = require('./botsettings.json')
const manager = new ShardingManager('./bot.js', { 
    token: botsettings.token,
    respawn: true,
});

manager.on('shardCreate', shard => console.log(`Launched shard ${shard.id}`));
manager.spawn(this.totalShards, 5500, -1)
```

- discord.js version: v12.5.1
- Node.js version: v14.15.4
- Operating system: Ubuntu
- Priority this issue should have: this issue has been affecting my bot for around one month now and has been causing slowdowns due to how many restarts the bot does automatically, I would like this issue to be fixed but not the main priority, since I seem to be the only one experiencing this.

**Comment by MaximKing1** [comment]
Im getting this aswell, i login the bot and get this
```js
StriderM   | Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
```
same code as yours, using the v12.15.1 and node v14.15.4 and Ubuntu, were having the exzact same issue i think and i asked discord API and they have said something to do with the client is getting ready fast enough...

**Comment by cobsidian-crim** [comment]
> Im getting this aswell, i login the bot and get this
> 
> ```js
> StriderM   | Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
> StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
> ```
> 
> same code as yours, using the v12.15.1 and node v14.15.4 and Ubuntu, were having the exzact same issue i think and i asked discord API and they have said something to do with the client is getting ready fast enough...

it didn't work for me, but try adding this to your code
```js
process.on('unhandledRejection', function(reason, p){
  console.log("Possibly Unhandled Rejection at: Promise ", p, " reason: ", reason);
  // application specific logging here
});
```

**Comment by MaximKing1** [comment]
> > Im getting this aswell, i login the bot and get this
> > ```js
> > StriderM   | Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
> > StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
> > ```
> > 
> > 
> > same code as yours, using the v12.15.1 and node v14.15.4 and Ubuntu, were having the exzact same issue i think and i asked discord API and they have said something to do with the client is getting ready fast enough...
> 
> it didn't work for me, but try adding this to your code
> 
> ```js
> process.on('unhandledRejection', function(reason, p){
>   console.log("Possibly Unhandled Rejection at: Promise ", p, " reason: ", reason);
>   // application specific logging here
> });
> ```

yeah i have tried i get undefiend? you working..

**Comment by cobsidian-crim** [comment]
> > > Im getting this aswell, i login the bot and get this
> > > ```js
> > > StriderM   | Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
> > > StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
> > > ```
> > > 
> > > 
> > > same code as yours, using the v12.15.1 and node v14.15.4 and Ubuntu, were having the exzact same issue i think and i asked discord API and they have said something to do with the client is getting ready fast enough...
> > 
> > 
> > it didn't work for me, but try adding this to your code
> > ```js
> > process.on('unhandledRejection', function(reason, p){
> >   console.log("Possibly Unhandled Rejection at: Promise ", p, " reason: ", reason);
> >   // application specific logging here
> > });
> > ```
> 
> yeah i have tried i get undefiend? yours working?

mine works but i still get the same error in the end

**Comment by cobsidian-crim** [comment]
still a major issue, so close to quitting

**Comment by cobsidian-crim** [comment]
fixed by removing unused node packages
