### ISSUE TITLE
Shard 0's process exited before its Client became ready.

### ISSUE THREAD

**Issue by MaximKing1** [discordjs/discord.js#5364]
**Please describe the problem you are having in as much detail as possible:**
I start the bot, when it starts using the ShardingManaer i get this error.

```
StriderM   | Error [SHARDING_IN_PROCESS]: Shards are still being spawned.
StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
```
then after it crashes with no other data, somethimes i get this

```
StriderM   | (node:1) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
StriderM   |     at Shard.onDeath (/usr/src/Strider/node_modules/discord.js/src/sharding/Shard.js:158:16)
StriderM   |     at Object.onceWrapper (events.js:422:26)
StriderM   |     at Shard.emit (events.js:315:20)
StriderM   |     at Shard._handleExit (/usr/src/Strider/node_modules/discord.js/src/sharding/Shard.js:384:10)
StriderM   |     at ChildProcess.emit (events.js:315:20)
StriderM   |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Include a reproducible code sample here, if possible:**

Sharding Manager:
```js
// Import All The Packages
require("dotenv").config();
const { ShardingManager } = require("discord.js");

// Create Your ShardingManger Instance
const manager = new ShardingManager("./index.js", {
  execArgv: ['--trace-warnings'],
  token: process.env.TOKEN,  
  shardArgs: ["--color"]
});

// Spawn The Shards
manager.spawn();
```

index file:
```js
const { Client } = require("discord.js");
const client = new Client({
  ws: { intents: 32511 },
  restTimeOffset: 0,
  rateLimitAsError: true,
  disableMentions: "everyone",
}); // Require The Bot Client

// Get Our Packages
const glob = require("glob");

// Command & Event Files Using Glob
const commandFiles = glob.sync("./Helpers/commands/**/*.js");
for (const file of commandFiles) {
  const command = require(file);
  client.commands.set(command.name, command);
}
const eventFiles = glob.sync("./Helpers/events/**/*.js");
for (const file of eventFiles) {
  const event = require(file);
  const eventName = /\/events.(.*).js/.exec(file)[1];
  client.on(eventName, event.bind(null, client));
}

// Login To The Discord API
client.login(process.env.TOKEN).catch(console.error);
```

**Further details:**

- discord.js version: v12.15.1
- Node.js version: v14.15.4
- Operating system: Ubunte
- Priority this issue should have – please be realistic and elaborate if possible: Urgent, i have 3 friends getting this issue... my bot has been down for 3 days now and my friends have been down a week...

**Relevant client options:**

- partials: none
- gateway intents: 32511 (Everything except Presence Intent, yes i do have the Members Intent)
- other: verified bot

**Comment by cobsidian-crim** [comment]
similar error here

**Comment by vyPal** [comment]
Started getting this also

**Comment by thebigwolfy** [comment]
i have the error

**Comment by SpaceEEC** [comment]
This error occurs when the spawned process (the shard), died for whatever reason before its client emitted ready.

If it crashed due to an error, it'll be printed to stderr as usual before exiting (so above that error).
If the process exited naturally or by calling `process.exit` (which all of your dependencies can do too), there won't be anything in the output about that.

It would be helpful if you could update your [reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) to be minimal too. Without the command and event handling part, as that's not discord.js. (While still making sure the reported behavior is still happening!)

---

On an unrelated note: There is no `rateLimitAsError` option, it will just be ignored.

**Comment by phamleduy04** [comment]
I also got this error on master branch but not latest version!

**Comment by tonestrike** [comment]
This was troubling me for quite some time. In order to catch these types of errors, or errors that occur during respawn, you must add an error event listener to the shard as it's being created:

```
manager.on('shardCreate', async (shard) => {
  console.log('Shard Launched')
  shard.on('error', (error) => {
     console.error(error)
  })
})
```

This should prevent the uncaught error in the parent process. If `respawn: true` is set on the manager, the child process will restart automatically.

**Comment by kyranet** [comment]
Are you able to reproduce this issue with discord.js v13.3.1? I'm rewriting the sharder so it'd be helpful to know if the issue still persists.

**Comment by vyPal** [comment]
I have absolutely no clue, but I'll try it when I have some free time and notify you with the results

**Comment by pab14567** [comment]
I am currently also experiencing this issue on the lastest stable release of Discord.js V13. 
I have 8-9 shards with my bot being in 8-9k servers. 

Shard 4 is consistently taking too long to become ready and is causing all of my other shards to not launch and spawn. 


I get the error : 
Error [SHARDING_READY_TIMEOUT]: Shard 4's Client took too long to become ready.
    at Timeout.onTimeout (C:\Users\Administrator\desktop\newsnipebot\node_modules\discord.js\src\sharding\Shard.js:164:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  [Symbol(code)]: 'SHARDING_READY_TIMEOUT'
}

Then afterwards, 3 seconds afterwards, the shard is ready to go and is connected. 
I've tried every solution listed in : https://github.com/discordjs/discord.js/issues/3956
But to no avail and shard 4 is consistently running into this issue.

**Comment by 7ijme** [comment]
Does anyone know how to fix this?

**Comment by didinele** [comment]
> discord.js version: v12.15.1

If this issue continues to exist, please open a new one.
