### ISSUE TITLE
あ

### ISSUE THREAD

**Issue by kumashacho** [discordjs/discord.js#5374]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kyranet** [comment]
Please fill in the information, do not send the template without modifications.
