### ISSUE TITLE
Split Embeds

### ISSUE THREAD

**Issue by Shamil-FD** [discordjs/discord.js#5376]
**Is your feature request related to a problem? Please describe.**
Channel.send() has `split` option for splitting texts, but why doesn't it split of embeds? It's very annoying to find a way to split embeds without losing any words or letters

**Describe the ideal solution**
I think the `split` option should also split embeds, just like it does for texts

**Comment by almostSouji** [comment]
> It's very annoying to find a way to split embeds without losing any words or letters

And that is precisely why it doesn't. There are tons of ways to split embeds - do you want to overflow into fields, other embed descriptions? Should it carry over other fields, to mimic the style of the former`? What about attachments if necessary?...

You can use [Util#splitMessage](https://discord.js.org/#/docs/main/stable/class/Util?scrollTo=s-resolveString) to chunk your content and provide it into various fields/embeds as you deem fit.
