### ISSUE TITLE
Channel/Category positioning is broken.

### ISSUE THREAD

**Issue by aSashaaa** [discordjs/discord.js#5379]
**Please describe the problem you are having in as much detail as possible:**
I want to create a category on the top of the server. But it is placing the category to under the last category.
The position is 0.
**Include a reproducible code sample here, if possible:**

```js
message.guild.channels.create('Verify', {
                                        type: 'category',
                                        position: 0,
                                        permissionOverwrites: [{
                                            id: guild.id,
                                            deny: ['VIEW_CHANNEL'],
                                        }]
                                    })
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 15
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible:
Medium - High.
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by aSashaaa** [comment]
Yes. It doesn't work with text channels either.

**Comment by Jiralite** [comment]
This is a Discord bug!
https://github.com/discord/discord-api-docs/issues/2640
