### ISSUE TITLE
Wrong Channel Type On "channelCreate" Event

### ISSUE THREAD

**Issue by Elior2739** [discordjs/discord.js#5386]
**Please describe the problem you are having in as much detail as possible:**

Wrong channel type on "channelCreate" event.
If you mark the channel (see the code below) its writes to you "discord.Channel" Instand Of "discord.GuildChannel"

![image_2021-03-11_152553](https://user-images.githubusercontent.com/50843891/110794116-11bcad00-827e-11eb-8809-b08cc6583bac.png)

**Include a reproducible code sample here, if possible:**
```js
client.on("channelCreate", (channel) => {
    console.log(channel.guild.name) // TEST SERVER
});
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 15.3.0
- Operating system: Windows 10 (Build: 19042)
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by zaida04** [comment]
channelCreate is emitted for the creation of both DMChannels and GuildChannels. If you are using TypeScript, you can use type guards or casting in order to ensure what you have is a GuildChannel if that's what you need.
