### ISSUE TITLE
guildMemberUpdate sending the same data for newMember and oldMember

### ISSUE THREAD

**Issue by xAtsuUC** [discordjs/discord.js#5387]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
client.on('guildMemberUpdate', async (oldMember, newMember) => {
    	if(oldMember.guild.id !== '714444297776398369') return;
          client.users.cache.get('573991320897716224').send(`\`\`\`${JSON.stringify(oldMember.user)}\`\`\``)
          client.users.cache.get('573991320897716224').send(`\`\`\`${JSON.stringify(newMember.user)}\`\`\``)
});
```

**Further details:**

- discord.js version: Master
- Node.js version: v14.15.3
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible:
Medium, this issue is affecting the guildMemberUpdate event, and its sending the same data for the new member and the old member

**Relevant client options:**

- partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER']
- gateway intents: Presence, Server Members
- other: (Screenshot that is sending the same data, I changed username two times and profile picture once
![image](https://user-images.githubusercontent.com/67171928/110795649-d7d7b080-8255-11eb-9489-a2ffdde2cbff.png)

**Comment by almostSouji** [comment]
That looks like an extension or variant of #4800 to me
