### ISSUE TITLE
Presence status is offline when users are online

### ISSUE THREAD

**Issue by DaliborTrampota** [discordjs/discord.js#5388]
all users appear to be offline while some of them are online.
The code below outputs array of 'offline' strings

```js
message.guild.members.cache.array().map(m => m.presence.status)
```

- discord.js version: 12.5.1
- Node.js version: 14.15.4
- Operating system: win 10 64bit
- Priority this issue should have – please be realistic and elaborate if possible: quite important

- partials: 
```json
"clientSettings": {
        "disableMentions": "everyone",
        "messageCacheMaxSize": 50,
        "messageCacheLifetime": 60,
        "messageSweepInterval": 120,
        "messageEditHistoryMaxSize": 1,
        "restTimeOffset": 350,
        "partials": [
            "MESSAGE",
            "CHANNEL",
            "REACTION",
            "USER"
        ]
    },
```
- gateway intents: both enabled on my beta bot but its happening on my main as well where I have only members intent enabled

- I have also tested the issue on latest master, commit hash: sorry but I do not understand what youre asking me to do. I installed discord js using npm not some hash

**Comment by VoltrexMaster** [comment]
You require the `GUILD_PRESENCES` intent to receive events for presences and also access presence data of users/members (https://discordjs.guide/popular-topics/intents.html)

**Comment by DaliborTrampota** [comment]
@VoltrexMaster thanks but im confused why the server members intent and presence intent is enabled in developer portal and others using client option?

**Comment by VoltrexMaster** [comment]
Please use the discord server for further discussion (https://discord.gg/bRCvFy9)
