### ISSUE TITLE
Glitch DiscordJS installation Opus compilation issue

### ISSUE THREAD

**Issue by healzer** [discordjs/discord.js#5389]
I have several users for [our Open-Source bot](https://github.com/healzer/DiscordEarsBot) who experience issues on [Glitch](https://glitch.com/) (and probably some other Linux machines as well).

The problem starts at the installation of `discordjs/opus`, which is required for audio connections. As you can see it's using the earlies v0.1.0 of opus which isn't even available (v0.4.0 already has releases). 

The compilation for opus works well for node v12+, but all lower versions crash/fail.

It's okay to make v12+ mandatory, but Is there a way to prevent the compilation by using pre-built bins?

```
node v14.15.2, npm 6.14.9

Installing...

> @discordjs/opus@0.1.0 install /app/node_modules/@discordjs/opus

> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 

node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.1.0/opus-v0.1.0-node-v83-linux-x64.tar.gz 

node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.1.0 and node@14.15.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 

make: Entering directory '/app/node_modules/@discordjs/opus/build'
```

**Comment by kyranet** [comment]
Maybe try upgrading your [dependencies](https://github.com/healzer/DiscordEarsBot/blob/3e340b28fe699329c10397bab370f86e55390abe/package.json#L21), you're installing `0.1.0`, not `0.4.0`.

**Comment by PyroTechniac** [comment]
Glitch isn't meant for a discord bot in the first place, and isn't meant to install native binaries like opus.
