### ISSUE TITLE
For loop loses track of entry when comamnd is run multiple times at the same time

### ISSUE THREAD

**Issue by Zebiano** [discordjs/discord.js#5392]
**Please describe the problem you are having in as much detail as possible:**
A `for (i of array)` loop inside a command with any type of `timeout` or waiting time loses track of `i` when the command is run at the same time.  A `for (let i = 0; i < array.length; i++)` does not lose track of `array[i]`.

**Include a reproducible code sample here, if possible:**
This is an example command file. To test it, you have 5 seconds to quickly run the command `bug 1` and `bug 2` (and more if you want, always incrementing the number).
```js
// Exports
module.exports = {
    name: 'bug',
    async execute(message, args) { // args is expected to be an array
        // Iterate args
        for (i of args) {
            console.log('Before:', i, args)

            // Timeout
            setTimeout(() => {
                console.log('After:', i, args)
            }, 5000)
        }

        // Iterate args
        /* for (let i = 0; i < args.length; i++) {
            console.log('Before:', args[i], args)

            // Timeout
            setTimeout(() => {
                console.log('After:', args[i], args)
            }, 5000)
        } */
    }
}
```
Basically, the bot iterates over `args` and logs twice while inside the loop. The first log is immediate, the second log happens only after 5 seconds. Since you quickly issued the same command twice (with a different number), the second command will run before the first command runs the log inside the 5 second timeout. Notice how the `for (i of array)` loop loses track of `i` and picks `args` from the last command issued. However, using `for (let i = 0; i < array.length; i++)` fixes this.

Example output by running `bug 1` and `bug 2` in quick succession. First, with the `for (i of array)` loop:
```
<when>: <i> <array>
Before: 1 [ '1' ]
Before: 2 [ '2' ]
After: 2 [ '1' ]
After: 2 [ '2' ]
```
And now with `for (let i = 0; i < array.length; i++)`:
```
<when>: <array[i]> <array>
Before: 1 [ '1' ]
Before: 2 [ '2' ]
After: 1 [ '1' ]
After: 2 [ '2' ]
```

**How does this affect Discord.js?**
I stumbled onto this bug by testing various users running a command at the same time. And since I needed to ask for user input, I was working with functions like `awaitMessages()` and `awaitReactions()`. I quickly realised that if two commands were waiting for user input, whenever one of the users input their data, it would be used for the other user as well. This, of course, is not ideal nor expected.

**Further details:**
- discord.js version: `12.5.1`
- Node.js version: `14.15.5`
- Operating system: `Windows`
- Issue priority: `Probably low`

**Relevant client options:**
- partials: `irrelevant`
- gateway intents: `irrelevant`
- other: `irrelevant`

I have **tried** to test the issue on latest master (commit hash ee5bc1a) by installing with `npm i https://github.com/discordjs/discord.js.git`, but I kept getting a `TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.` error, even when defining intents with
```js
const client = new Client({ ws: { intents: ['GUILDS', 'GUILD_MESSAGES'] } });
```
I don't mind at all testing this issue on the latest master release if someone guides me in the right direction!

**Comment by almostSouji** [comment]
`i` isn't scoped in the first approach, but it is in the second, accordingly, the outcome varies. This has nothing to do with discord.js, however

**Comment by vBread** [comment]
And in regards to your intents error, the intents options aren't located under the WebSocketOptions on master, they're under [ClientOptions](https://discord.js.org/#/docs/main/master/typedef/ClientOptions).

**Comment by Zebiano** [comment]
Thank you for the quick responses and explanations! Problem solved.
