### ISSUE TITLE
Discord.js not working 2021

### ISSUE THREAD

**Issue by realhackcraft** [discordjs/discord.js#5397]
**Please describe the problem you are having in as much detail as possible:**
so discord.js doesn't work for me. it says that at util/Util "throw e" doesn't work
**Include a reproducible code sample here, if possible:**

```js
// no code since its library's problem
```

**Further details:**

- discord.js version: newest
- Node.js version: newest
- Operating system: mac os x 15.7
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by realhackcraft** [comment]
No. This doesn't work fundamentally. It says that that the problem is of
discord.js. please try is for your self.


Thank you, Hackcraft_


Noel ***@***.***> 于 2021年3月13日周六 11:44写道：

**Comment by anandre** [comment]
"newest" is not a valid version when trying to debug anything.  Your issue is 99% due to outdated Node version.
