### ISSUE TITLE
settopic errr

### ISSUE THREAD

**Issue by ntloff** [discordjs/discord.js#5398]
i tried
```
let channel3 = client.channels.cache.find(channel3 => channel3.name === 'ilovediscord')
if(!channel3) return;
channel3.setTopic("my favourite channel topic")
```
error
```
channel3.setTopic("my favourite channel topic")
             ^
TypeError: Cannot read property 'setTopic' of undefined
```

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
