### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by frozen-mitko** [discordjs/discord.js#5399]
Is the guildMemberAdd event changed or removed, because I can't make a welcome message?

**Comment by iShibi** [comment]
#4961

**Comment by frozen-mitko** [comment]
I have to make my bot verifed or no?
Or is it some technical issue?

**Comment by vladfrangu** [comment]
No, verification is something Discord asks for when your bot grows in guilds. Read more here: https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by frozen-mitko** [comment]
So I have to enable the bot intents or something?

**Comment by almostSouji** [comment]
Please read the resources provided, they detail what you need to do both in case your bot requires verification (at 100+ guilds) and in case it does not. 

If you have further questions about the verification process see [discord's help article](https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting) or [developer server verification faq channel](https://discord.gg/discord-developers).
