### ISSUE TITLE
Bot presence: no custom app

### ISSUE THREAD

**Issue by gXLg** [discordjs/discord.js#5404]
In `discord.js`, neither normal bots nor selfbots are able to set custom picture for the game they are playing. I know it's possible, because it works with `discord.py`.

 The code I am trying to use for node:
```
  bot.user.setPresence ( { activity : {
    name : "GGame",
    type : "PLAYING",
    applicationID : [app_id here],
    details : "Some details",
    state : "In the lobby",
    assets : {
      largeImage : [id of picture here]
    }
  }, status : "dnd" })
```

For a normal bot it only sets PLAYING GGame
(details, state and assets are completely ignored)

For a selfbot it sets everything except the assets.

Also on both the `applicationID` field is `null` when checking.

Versions:
- Discord.js v12.5.1
- Node v14.15.4

Also, for all those who would want to warn me about selfbots: I am totally aware of the ToS and using selfbot only for testing the API.

**Comment by vaporox** [comment]
"Bots are only able to send `name`, `type`, and optionally `url`." ([Source](https://discord.com/developers/docs/topics/gateway#activity-object))

**Comment by gXLg** [comment]
Well, does that mean, that `discord.py` has a better coverage of the API?

**Comment by vaporox** [comment]
No, this means that it is not even possible for `discord.py` to add assets to bot activities.

**Comment by gXLg** [comment]
@vaporox okey, I see, did not try to setup a bot with `discord.py`, only selfbot.
@almostSouji yeah, I also wanted to close it right now.

**Comment by almostSouji** [comment]
You might want to look into https://discord.com/guidelines then. Selfbots are not permitted and we do not support their use in discord.js.

**Comment by gXLg** [comment]
@almostSouji I am aware of that. But thank you.
As a programmer I was wondering about possibilities of a selfbot, and well, it met my expectations. I am not using a selfbot for collecting some data or to automate my account, but to see, what is possible to do with the API (though it still is not allowed :) )
