### ISSUE TITLE
Mentionable role

### ISSUE THREAD

**Issue by Gekki-beep** [discordjs/discord.js#5409]
Hello,

I tried to disable the mentions of a role, with the .setMentionable(false).
However, it also prohibits the use of shlash commands...

`message.guild.roles.cache.forEach(r => {
        if(r.mentionable == true) r.setMentionable(false, "test");
});`

**Comment by almostSouji** [comment]
Discord requires a role to be mentionable by the user in order to supply it as role argument type. This has nothing to do with our library.
