### ISSUE TITLE
Auto-hang up the call if there is only one participant for more than 2 minutes

### ISSUE THREAD

**Issue by omarbelkady** [discordjs/discord.js#5411]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by xAtsuUC** [comment]
Please fill the feature request template or your issue is probably going to be closed

**Comment by Fyko** [comment]
This is out of the scope of the Discord.js library. Additionally, please bring future voice-related issues, requests, etc. to https://github.com/discordjs/voice

**Comment by omarbelkady** [comment]
Instead of having the call remaining open in case someone leaves the voice call and you're the only one left there meaning only 1 participant. The call should end automatically.

**Comment by omarbelkady** [comment]
> Please fill the feature request template or your issue is probably going to be closed
How can I do that?

**Comment by omarbelkady** [comment]
> Please fill the feature request template or your issue is probably going to be closed

@xAtsuUC how can I do that?

**Comment by xAtsuUC** [comment]
> > Please fill the feature request template or your issue is probably going to be closed
> 
> @xAtsuUC how can I do that?

Editing the template before publishing the request.
