### ISSUE TITLE
Editing a message rather than sending a new embed breaks images

### ISSUE THREAD

**Issue by jlsajfj** [discordjs/discord.js#5415]
**Please describe the problem you are having in as much detail as possible:**

I created an embed, and edited a previously sent message to have this embed. No images would display. If I send a whole new message with this embed, there are no issues.

**Issue only exists with attached images. Normal images linked via URL have no issue.**

**Include a reproducible code sample here, if possible:**

```js
cnl.send('temp_message').then( new_msg => {
  const prayer_embed = new MessageEmbed()
    .setColor('#FFECAC')
    .setTitle('Tribute')
    .setDescription(`+1 prayer\n<@${id}>, you have ${val} prayer!`)
    .attachFiles(['./assets/hands.png'])
    .setThumbnail('attachment://hands.png')
  cnl.send(prayer_embed)
  new_msg.edit(prayer_embed)
}
```

Broken code example [here](https://github.com/jlsajfj/MentalBot/blob/Example_Broken_Embed/commands/stock.js#L26).

Functional code example [here](https://github.com/jlsajfj/MentalBot/blob/main/commands/stock.js#L26).

**Further details:**

- discord.js version: v12.5.1
- Node.js version: v12.20.1
- Operating system: KALI on WSL2
- Priority this issue should have – please be realistic and elaborate if possible:

My code uses my own send function, however the basis of which is [still the default send function](https://github.com/jlsajfj/MentalBot/blob/main/send.js#L29).

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by jlsajfj** [comment]
Below is an example, the first embed being sent, second embed being edited.
![image](https://user-images.githubusercontent.com/7155643/111668270-f73d8300-87eb-11eb-992e-12fae5af56c8.png)

**Comment by advaith1** [comment]
are you trying to attach an image while editing a message? Discord doesn't support attaching files when editing normal messages (only when editing a webhook or interaction response message)

**Comment by jlsajfj** [comment]
Yup, interesting
