### ISSUE TITLE
Ready event does not refire upon regaining internet connection

### ISSUE THREAD

**Issue by TheSecondDiaryKeeper** [discordjs/discord.js#5416]
**Please describe the problem you are having in as much detail as possible:**

I host my bots on a VPS and occasionally, they lose internet for short periods of time. Upon regaining internet connection, my bots do not fire the ready event (Discord.py bot hosted on the same VPS does fire ready event when regaining connection). This causes them to be stuck in a "limbo" state of not responding to messages, having no activities, and just appearing as Online until I forcefully restart them. 

**Include a reproducible code sample here, if possible:**

```js
const Discord = require("discord.js");
const fs = require("fs");
const { disconnect, uptime } = require("process");
const client = new Discord.Client();

const token = "(My bot's token)"

const version = "0.3.0";
const bot_name = "Calliope";
const program_name = "calliope";
const events = "2";
const loops = "0";
const error_report = "808849065512796182"; // Can be replaced with any channel for testing purposes

client.on("ready", async () => {
    console.log(
        `BOT ${client.user.tag} (${client.user.id}) started successfully. Hooking into error reporting channel.`
    );

    const embed = new Discord.MessageEmbed()
        .setColor(colors["green"])
        .setTitle("Hooked into error reporting channel!")
        .setDescription(
            `\`\`\`yaml\nRunning: ${program_name}\nVersion: ${version}\n\nCommands: ${Object.keys(commands).length}\nEvents: ${events}\nLoops: ${loops}\n\`\`\``
        );

    error_reporting_channel = await client.channels.fetch(error_report);
    await error_reporting_channel.send(embed);

    await client.user.setPresence({
        activity: { name: db["status"] },
        status: db["visibility"],
    });
    console.log(
        `BOT ${client.user.tag} (${client.user.id}) hooked into error reporting channel. Good to go.`
    );
});

client.login(token);
```

**Further details:**

- discord.js version: Discord.js 12.5.1
- Node.js version: Node.js v14.15.5
- Operating system: ubuntu-20.04-x86_64
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: All
- other: none

**Comment by vladfrangu** [comment]
We emit the `ready` event ONCE, when the client turns fully ready. Shards will automatically reconnect and continue as usual, and we emit events for those (such as [`shardReady`](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-shardReady) or [`shardResume`](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-shardResume) for example). Are you sure the bot doesn't reply to messages after? What intents are you providing? More information is required, but as it stands, this doesn't sound like a bug but rather like intended functionality. If you believe it IS a bug still, please add a listener to the `debug` event, and follow up this issue with the logs, and reproduction sample/steps, and I'll reopen it. 👍
