### ISSUE TITLE
On Ready event refiring whenever internet connection is regained

### ISSUE THREAD

**Issue by TheSecondDiaryKeeper** [discordjs/discord.js#5417]
**Is your feature request related to a problem? Please describe.**
If a bot is being hosted and loses connection to the internet for one reason or another, it will get stuck in a limbo state upon getting reconnected to the internet in which it will have no presence, no ability to respond to messages, and will just be stuck appearing online until manually restarted by the bot's developer.

**Describe the ideal solution**
The ready event should fire again once connection to the internet is restored so that Discord will recognize the bot as powered on again, as currently it does not. 

**Describe alternatives you've considered**
I considered programming in a command to kill the bot and force restart it but I can not do that as the bot cannot respond to any messages. I also considered having the bot continually try to check if it was connected to the internet and if it ever disconnect repeatedly try to reconnect and fire the on ready manually via different code upon reconnection but the bot stops functioning properly upon internet loss.

**Additional Context**
None

**Comment by TheSecondDiaryKeeper** [comment]
An alternative solution to the one proposed above would be adding a separate event for when the bot regains connection to Discord, perhaps client.on("reconnect"), that would also fire in the same way mentioned above.

**Comment by DiscordCatto** [comment]
Event [shardReconnecting](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-shardReconnecting) exists.. 

Also read the reply vladfrangu sent in [here](https://github.com/discordjs/discord.js/issues/5416#issuecomment-802271701)

**Comment by FarishIrfan** [comment]
This is normal. That's why you should use `once` instead of `on`
```js
client.once('ready', () => {
        // code
});
```

**Comment by DiscordCatto** [comment]
@FarishIrfan They *want* the `ready` event to emit again once the internet connection is back... so what you put makes no sense for this. Read the full message they posted lol.

> "Describe the ideal solution
> The ready event should fire again once connection to the internet is restored so that Discord will recognize the bot as powered on again, as currently it does not."

**Comment by FarishIrfan** [comment]
Oh didn't read that. Sorry

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
