### ISSUE TITLE
Method on if someone boosted the server and who boosted

### ISSUE THREAD

**Issue by thepwrtank18** [discordjs/discord.js#5418]
**Is your feature request related to a problem? Please describe.**
Every tutorial I see are hacky workarounds that always have problems.

**Describe the ideal solution**
The ideal solution should be this:
```
client.on(guildBoosted){
    client.channels.cache.get("id").send(`${boostedMember} just boosted the server!`)
    }
```
**Describe alternatives you've considered**
I've considered having it check for the role, but that will send a message to everyone that boosted the server.

**Comment by almostSouji** [comment]
[Client#guildMemberUpdate (e)](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-guildMemberUpdate) fires where the old member does not have a [premiumSince(Timestamp)](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=premiumSinceTimestamp).

If you want to make this your own event feel free to [emit](https://nodejs.org/api/events.html#events_emitter_emit_eventname_args) it on your client instance .
