### ISSUE TITLE
NODE.JS / DISCORD.JS | Online member count also counts bots. > Only want members to be count it

### ISSUE THREAD

**Issue by Devcode101** [discordjs/discord.js#5421]
Read titel ^

Is there a way that i can also filter out the bots in couting output?

code:

module.exports = async (client) =>{ 
const guild = client.guilds.cache.get('GUILD-ID'); 
setInterval(async() =>{ 
onlineCount = guild.members.cache.filter(members => members.presence.status === 'online' && 'dnd').size; 
const channel = guild.channels.cache.get('CHANNEL-ID');
channel.setName(Online Members: ${onlineCount} ); 
console.log(onlineCount);
 } 10000);
 }

**Comment by vaporox** [comment]
You already received an answer at nodejs/help#3276.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9
) instead of opening an issue – you will get redirected there anyway.
