### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by ygasaino1** [discordjs/discord.js#5423]
[This package](https://www.jsdelivr.com/package/npm/discord.js) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by advaith1** [comment]
bots cannot do api requests from the browser anyway; what exactly are you trying to do?

**Comment by kyranet** [comment]
> bots cannot do api requests from the browser anyway; what exactly are you trying to do?

While we don't, the `main` isn't exactly completely valid:

https://github.com/discordjs/discord.js/blob/d744e51c1bdb4c7a26c0faeea1f2f45baaf5fd3c/package.json#L5

The linked PR adds the missing extension, and that's something I approve.
