### ISSUE TITLE
TypeError: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by RaphaelTouze** [discordjs/discord.js#5426]
So i recently added a footer command to my embed (line 105) and have been getting undefinied errors. if i remove the footer everything works fine.
Here's the full code https://sourceb.in/uGCX65tsgu

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
