### ISSUE TITLE
Cant start bot. guildDelete event emits on start. ready event wont

### ISSUE THREAD

**Issue by DaliborTrampota** [discordjs/discord.js#5430]
**Please describe the problem you are having in as much detail as possible:**
Whenever I start a bot guildDelete event emits with this guild
```js
<ref *1> Guild {
  members: GuildMemberManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  channels: GuildChannelManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  roles: RoleManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  presences: PresenceManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {}
  },
  voiceStates: VoiceStateManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  deleted: true,
  available: false,
  id: '822132835544596551',
  shardID: 0
}
```
then it won't emit ready event
I think it might be caused by my bot being verified but I really dont know and why it emits an event of a guild that has been already deleted? 

**Further details:**

- discord.js version: 12.5.1
- Node.js version:  14.15.4
- Operating system: Windows 10 and ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: Quite big as I cant start the bot

**Relevant client options:**

```js
"clientSettings": {
        "disableMentions": "everyone",
        "messageCacheMaxSize": 50,
        "messageCacheLifetime": 60,
        "messageSweepInterval": 120,
        "messageEditHistoryMaxSize": 1,
        "restTimeOffset": 350,
        "partials": [
            "MESSAGE",
            "CHANNEL",
            "REACTION",
            "USER"
        ],
        "ws": {
            "intents": ["GUILDS", "GUILD_MESSAGES", "GUILD_MEMBERS", "GUILD_VOICE_STATES", "GUILD_MESSAGE_REACTIONS", "GUILD_EMOJIS"]
        }
    },
```

**Comment by DaliborTrampota** [comment]
any way to fix this? its still occuring

**Comment by DaliborTrampota** [comment]
the problem is that i use mongo db and it takes like 30seconds till the ready event fires because of this bug. and mongo fails to connect

**Comment by SpaceEEC** [comment]
Can you attach a listener to [`Client#debug`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-debug) and show the output?

**Comment by DaliborTrampota** [comment]
> Can you attach a listener to [`Client#debug`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-debug) and show the output?

That was the first thing I did. It logs over 10000 lines and i cant copy it. But all I see is the client reference so all the channels and my variables along with config and all the things i binded to it. if theres a way to filter out the client references from the output please let me know how

**Comment by DaliborTrampota** [comment]
actually this worked

```js
const Client = require('../Structures/Discord/Client')

module.exports = (string) => {
    if(string instanceof Client)
        return console.log('client')
}```

```js
client
client
client
client
client
client
client
STATUS > Paladins API Connected
client
client
client
client
STATUS > 200 - OK. Log in successful.
client
client
<ref *1> Guild {
  members: GuildMemberManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  channels: GuildChannelManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  roles: RoleManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  presences: PresenceManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {}
  },
  voiceStates: VoiceStateManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  deleted: true,
  available: false,
  id: '822132835544596551',
  shardID: 0
}
client
client
STATUS > Connected to lavalink
STATUS > Starting Twitter monitor
STATUS > KokNut is online!
STATUS > The Dashboard server is up and running!
STATUS > Connected to mongodb
STATUS > Twitter Connected
client
client```

**Comment by DaliborTrampota** [comment]
@SpaceEEC is this what you wanted? is it helpful?

**Comment by SpaceEEC** [comment]
Not quite, you are logging your client whenever the (I assume) debug event is emitted.
You want to log the actual string being emitted there.

I assume you are using some kind of event logic which prepends the client to the argument list of the event handler.
You want to log the second parameter then (basing on my assumption).

**Comment by DaliborTrampota** [comment]
oh yeah that is so true. I completely forgot about that. I had debug event in my bot since the creation of the bot and never really used it it was always commented out so I never suspected it wasnt properly setup anyway here is the actual log

```js
Provided token: part of my token.***************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 993
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 6
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
STATUS > Paladins API Connected
[WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 200ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1
STATUS > 200 - OK. Log in successful.
[WS => Shard 0] [READY] Session e7b9e4c753077dc15309dd9dbea23b9f.
[WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
<ref *1> Guild {
  members: GuildMemberManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  channels: GuildChannelManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  roles: RoleManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  presences: PresenceManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {}
  },
  voiceStates: VoiceStateManager {
    cacheType: [class Collection extends Collection],
    cache: Collection(0) [Map] {},
    guild: [Circular *1]
  },
  deleted: true,
  available: false,
  id: '822132835544596551',
  shardID: 0
}
ERROR > guildDelete > Guild Error
[WS => Shard 0] Heartbeat acknowledged, latency of 604ms.
[WS => Shard 0] Shard did not receive any more guild packets in 15 seconds.
  Unavailable guild count: 1
STATUS > Connected to lavalink
STATUS > Starting Twitter monitor
STATUS > KokNut is online!
STATUS > The Dashboard server is up and running!
STATUS > Connected to mongodb
STATUS > Twitter Connected
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 118ms.

**Comment by SpaceEEC** [comment]
This looks like the shard (and then the client, assuming it's the only shard) did ready there.
The STATUS lines below the `Shard did not receive [...]` lines suggest that too.

**Comment by DaliborTrampota** [comment]
What does that mean? And I'm not sharding yet. So there is no way to get rid of the guildDelete emit at startup? Should I contact discord support?

**Comment by DaliborTrampota** [comment]
should I contact discord support for them to clear the cache or whatever the issue is?

**Comment by nerdthatnoonelikes** [comment]
I'm encountering the same issue. Have you found a fix for this yet?

**Comment by NachoToast** [comment]
Getting the same issue here, ready event not firing.

**Comment by DiscordKiller** [comment]
I think you can but i don't know though

**Comment by DaliborTrampota** [comment]
still getting the error whenever i launch the bot. Any update?

**Comment by ObscuritySRL** [comment]
Until it's fixed, before initializing your client add:
```
process.on( 'uncaughtException', console.error )
    .on( 'unhandledRejection', console.error );

const bot = new Client( {
//...
```

Don't rely on this as a lazy way to not properly handle your errors. It'll ateast get you to where you can fire the bot up and debug.

**Comment by SpaceEEC** [comment]
What error is this catching? As far as I am aware all that's happening is that guild delete unexpectedly emits.

**Comment by DaliborTrampota** [comment]
> Until it's fixed, before initializing your client add:
> ```
> process.on( 'uncaughtException', console.error )
>     .on( 'unhandledRejection', console.error );
> 
> const bot = new Client( {
> //...
> ```
> 
> Don't rely on this as a lazy way to not properly handle your errors. It'll ateast get you to where you can fire the bot up and debug.

I'm using this for a long time. That's not the problem. The problem is that it takes much much longer for ready event to fire. Without this issue in the past the ready event emitted as soon as my handler loaded the events, now it takes 2-4 minutes. Can I contact discord support to clean the cache for my bot or something? So I'm not recieving this unavailable guild? Or how that works?

**Comment by ObscuritySRL** [comment]
> 
> 
> > Until it's fixed, before initializing your client add:
> > ```
> > process.on( 'uncaughtException', console.error )
> >     .on( 'unhandledRejection', console.error );
> > 
> > const bot = new Client( {
> > //...
> > ```
> > 
> > 
> > Don't rely on this as a lazy way to not properly handle your errors. It'll ateast get you to where you can fire the bot up and debug.
> 
> I'm using this for a long time. That's not the problem. The problem is that it takes much much longer for ready event to fire. Without this issue in the past the ready event emitted as soon as my handler loaded the events, now it takes 2-4 minutes. Can I contact discord support to clean the cache for my bot or something? So I'm not recieving this unavailable guild? Or how that works?

I figured the problem was `guildDelete` was being fired off before a guild was cached, causing a TypeError `'replace' of undefined`. This is unhandled rejection is preventing the shard from readying.

**Comment by ObscuritySRL** [comment]
> 
> 
> What error is this catching? As far as I am aware all that's happening is that guild delete unexpectedly emits.

`guildDelete` emitting before the guild is cached, or when the guild is unavailable, causes an unhandled rejection: `TypeError 'replace' of undefined`

**Comment by GingkathFox** [comment]
can confirm, using Discord.JS v12.5.3.

**Comment by DaliborTrampota** [comment]
any update? if I contact discord support will  they be able to clear the guild out of my bots cache or something so it doenst happen?

**Comment by almostSouji** [comment]
> What error is this catching? As far as I am aware all that's happening is that guild delete unexpectedly emits.

Still unanswered. And no, discord support can not help you with this

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.

**Comment by jacc** [comment]
This is still happening to me on `v13` - I have a guildDelete event that is firing when my ready event is also firing, causing a message to be sent for an undefined guild. 

![image](https://user-images.githubusercontent.com/6956351/129458218-b9fd5574-93b0-45f0-ba99-4c1475646944.png)
