### ISSUE TITLE
erela.js is not connecting, discord.js music bot

### ISSUE THREAD

**Issue by dionsyran2** [discordjs/discord.js#5431]
Hello, I am using erela.js (LavaLink) for my bot, I used the access details from something.host : https://support.something.host/en/article/lavalink-hosting-okm26z/
I am getting this error: `Node "default" encountered an error: connect ECONNREFUSED 127.0.0.1:2333`
My  erela.js code:

```
client.Music = new Manager({
    host: "lavalink.something.host",
    port: 80,
    password: "youshallnotpass",
    send: (id, payload) => {
        const guild = client.guilds.cache.get(id);
        if (guild) guild.shard.send(payload);
      }
})

client.Music.on("nodeConnect", node => {
    console.log(`Node "${node.options.identifier}" connected.`)
})
client.Music.on("nodeError", (node, error) => {
    console.log(`Node "${node.options.identifier}" encountered an error: ${error.message}.`)
})



client.on("ready", (msg) => {
    client.user.setActivity(`${client.guilds.cache.size} Servers | ^help`, { type: "WATCHING" })
    client.Music.init(client.user.id);
    console.log(`logged in as ${client.user.username}`)
})
```

How can I fix it, i have never used erela.js before?

**Comment by almostSouji** [comment]
We only offer support for discord.js, not other people's libraries. You can find causes for this specific errors through the search engine of your choice.
