### ISSUE TITLE
stream dispatcher is stopping before it even starts

### ISSUE THREAD

**Issue by Gobert123** [discordjs/discord.js#5432]

**Comment by Gobert123** [comment]
const Discord = require(`discord.js`)
const config = require(`../config.json`)
module.exports = {
    commands: 'play',
    callback: async (message, arguments, text, client) => {
        if (message.member.voice.channel) {
            const connection = await message.member.voice.channel.join()
        
const dispatcher = connection.play(`../joy.mp3`);

dispatcher.on('start', () => {
	console.log('audio.mp3 is now playing!');
});

dispatcher.on('finish', () => {
	console.log('audio.mp3 has finished playing!');
});

// Always remember to handle errors appropriately!
dispatcher.on('error', console.error);
connection.play(`joy.mp3, {volume: 0.5 }`)
    }}}



my code

**Comment by jerardoauiniga** [comment]
Born with the king owner l

**Comment by aboody8007** [comment]
Explain, dear, what do you mean
