### ISSUE TITLE
Make MessageEmbed types (rich, image, video, etc) an enum, type, or constants.

### ISSUE THREAD

**Issue by KevinNovak** [discordjs/discord.js#5433]
**Is your feature request related to a problem? Please describe.**
I use TypeScript for my bots and I have a case where I need to filter MessageEmbeds to just those that are a "rich" type of embed :
```typescript
let richEmbeds = msg.embeds.filter(embed => embed.type === 'rich');
```
The issue here is that you could put any string here and it would compile. This could break at runtime if **"rich"** is renamed to something else. It also requires looking at the codebase or documentation to determine the available options.

**Describe the ideal solution**
It would be nice if the different types of embeds were constants like the ChannelType's are, instead of allow any string:
![image](https://user-images.githubusercontent.com/11231402/112189614-90004400-8bda-11eb-8c8f-79c17f257877.png)

(I'm not sure if this is specific to just TypeScript or would apply to the library in general)

**Comment by iShibi** [comment]
The [documentation](https://discord.com/developers/docs/resources/channel#embed-object-embed-types) says that these types are "loosely defined" and will be deprecated.

**Comment by KevinNovak** [comment]
Thanks for the information. Looks like I'll have to redesign this for my use case. Closing.
