### ISSUE TITLE
Sending webhooks seem to be able to hit 429s

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#5434]
**Please describe the problem you are having in as much detail as possible:**
Sending a few webhook messages within a short time causes 429s to be hit instead of delaying to avoid the 429.

![image](https://user-images.githubusercontent.com/11788894/112359618-d4a5e100-8ca7-11eb-8b63-6407bc3d114a.png)
The screenshot only shows 1 of the 429s but the client hit about 4 while it was sending to a webhook. I used webhooks for logs such as for user-leave and user-join logs which is why the client was sending a lot of webhook messages in the first place.

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: v12.5.0
- Node.js version: v15.10.0
- Operating system: Ubuntu 18.04.3 LTS
- Priority this issue should have – please be realistic and elaborate if possible: medium as https://github.com/discordjs/discord.js/blob/master/src/rest/RequestHandler.js#L138 says it should never happen.
**Relevant client options:**

- partials: none
- gateway intents: ```[
	Intents.FLAGS.GUILDS,
	Intents.FLAGS.GUILD_PRESENCES,
	Intents.FLAGS.GUILD_MEMBERS,
	Intents.FLAGS.GUILD_EMOJIS,
	Intents.FLAGS.GUILD_BANS,
	Intents.FLAGS.GUILD_MESSAGES,
	Intents.FLAGS.GUILD_MESSAGE_TYPING,
	Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
	Intents.FLAGS.DIRECT_MESSAGES,
	Intents.FLAGS.DIRECT_MESSAGE_TYPING,
	Intents.FLAGS.DIRECT_MESSAGE_REACTIONS
]```
- other: none

- I have also tested the issue on latest master, commit hash: `f469402`

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
