### ISSUE TITLE
channelUpdate event fires twice when repositioning channel

### ISSUE THREAD

**Issue by derXge** [discordjs/discord.js#5439]
**Please describe the problem you are having in as much detail as possible:**
`channelUpdate` event fires twice when repositioning a channel.
E.g. moving channel from position `1` to `3`:
`1.` `oldChannel.position = 1` & `newChannel.position = 1`
`2.` `oldChannel.position = 3` & `newChannel.position = 3`

**Include a reproducible code sample here, if possible:**
```js
client.on("channelUpdate", (oldChannel, newChannel) => {

    console.log("oldChannel.position", oldChannel.position);
    console.log("newChannel.position", newChannel.position);

});
```
oldChannel and newChannel will have the same position but the event will fire twice with the second having the new position.

**Further details:**

- discord.js version: master
- Node.js version: 15.11.0
- Operating system: Debian 10

- I have also tested the issue on latest master, commit hash: `#5424`

**Comment by almostSouji** [comment]
This is expected API behavior. Repositioning a channel can potentially change the position of other channels by proxy. These changes will also be emitted as CHANNEL_UPDATE (`"channelUpdate"`) events.

**Comment by derXge** [comment]
How to check at which position a channel got moved then?
