### ISSUE TITLE
guild.members.cache.get won´t find guildMember unless that user was mentioned before

### ISSUE THREAD

**Issue by Ontros** [discordjs/discord.js#5441]
**NOT WORKING CODE:**
```js
var id = args[0]
if (id[0] === '<') { //if input is mention
    id = id.substring(3, id.length - 1) //remove mention brackets
}
const member = message.guild.members.cache.get(id)/*null*/
if (!member) { 
   message.channel.send('Member not found!');
   return
}
```

**WORKING CODE:**
```js
var id = args[0]
if (id[0] === '<') { //if input is mention
    id = id.substring(3, id.length - 1) //remove mention brackets
}
else {
   var mes = await message.channel.send('<@!'+id+'>') //mention the ID
   mes.delete()
}
const member = message.guild.members.cache.get(id)/*guildMember*/
if (!member) {
   message.channel.send('Member not found!');
   return
}
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12.18.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by iShibi** [comment]
This isn't an issue with the lib. Not all `GuildMembers` are cached, if you want an uncached member just [fetch](https://discord.js.org/#/docs/main/stable/class/GuildMemberManager?scrollTo=fetch) it using the id. You should have used the [Disocrd Server](https://discord.gg/bRCvFy9) for this.

**Comment by Ontros** [comment]
Alright, thanks.
