### ISSUE TITLE
TS - Property 'api' is private and only accessible within class 'BaseClient'

### ISSUE THREAD

**Issue by Esporia** [discordjs/discord.js#5444]
Typescript :

I get this type error `Property 'api' is private and only accessible within class 'BaseClient'.ts(2341)` when I try to register slash commands.

```ts
import Discord from 'discord.js';

const client = new Discord.Client();
const BOT_TOKEN = 'XXXX',
	GUILD_ID = 'XXXX';

client.on('ready', () => {
	console.log(`The bot is now working !\n\n`);

	client.api // Property 'api' is private and only accessible within class 'BaseClient'.ts(2341)
		.applications(client.user!.id)
		.guilds(GUILD_ID)
		.commands.post({
			data: {
				name: 'hello',
				description: 'hello world command',
				// possible options here e.g. options: [{...}]
			},
		});
});

client.login(BOT_TOKEN);

```

**Further details:**

- discord.js version: "^12.5.1"
- Node.js version: v15.8.0
- Operating system: win10

**Comment by iShibi** [comment]
Because it is set as `private` in typings as it should be. Also, this isn't an issue with the lib as you're using unexposed methods when the API is still in dev.

**Comment by kyranet** [comment]
This is intentional and is a deliberate decision by us. Please refer to this comment: https://github.com/discordjs/discord.js/pull/5150#issuecomment-751306243
