### ISSUE TITLE
Add client option to disable automatic queueing of requests if rate limit is hit and to reject instead

### ISSUE THREAD

**Issue by Vendicated** [discordjs/discord.js#5449]
**Is your feature request related to a problem? Please describe.**
My bot creates a lot of emotes, which eventually leads to hitting the emoji create rate limit. This rate limit is insanely long from experience (up to an hour) resulting in the `GuildEmojiManager.create` Promise to take an hour to resolve. This is super annoying and forces me to use `Promise.race` to time out after a while in order to not get stuck

**Describe the ideal solution**
- new Client Option disableRatelimitQueue, which takes an array of routes, so in my case `[ "emojis" ]`
- On disabled routes, requests will no longer be queued, instead reject the Promise with info on when the ratelimit ends

I could implement this if approved

**Describe alternatives you've considered**
As mentioned above I use Promise.race to time out after a while

**Additional context**
Related to https://github.com/discordjs/discord.js/issues/2885

**Comment by tandpfun** [comment]
Another use case: #5473

**Comment by doinkythederp** [comment]
Adding onto the `disableRatelimitQueue` suggestion, maybe it could take a filter function?
```js
new Client({ disableRatelimitQueue: function(info) { 
    if (isVeryImportant(info)) {
      return false; // Is critical, put on the queue!
    } else {
      return true; // Not critical, just cancel.
    }
  }
});
```
