### ISSUE TITLE
Bot is not caching any guilds

### ISSUE THREAD

**Issue by SirArchibald97** [discordjs/discord.js#5450]
**Please describe the problem you are having in as much detail as possible:**
I have some code which is supposed to loop through all the channels in a server, however I cannot fetch the guild object of the server from my bot's cache. I logged the value of `client.guilds` and it returned an empty map, however the bot is 100% in a server. The bot can detect messages and other events from the server, however the server object along with all its properties cannot be found anywhere in the bot's cache.

**Include a reproducible code sample here, if possible:**
```console.log(bot.guilds.cache);```

```js
console.log(bot.guilds.cache);
for (let channel of bot.guilds.cache.first().channels.cache) {
        // do stuff
}
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.3
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Low (the error seems to only happen in this one specific server)

**Relevant client options:**

- partials: none
- gateway intents: presence and server members
- other: none

**Comment by almostSouji** [comment]
You are likely doing this in a scope that executes before the client is ready. Note that the [`GUILDS`](https://discord.com/developers/docs/topics/gateway#gateway-intents) intent is required in order to receive guilds. (the intents you list are vague at best)
