### ISSUE TITLE
where can i learn this

### ISSUE THREAD

**Issue by DiscordFanBoi** [discordjs/discord.js#5453]
idk how to do this

**Comment by DiscordFanBoi** [comment]
@almostSouji yeah i need help!

**Comment by almostSouji** [comment]
The issue tracker is for bug reports and feature requests. We also generally don't help with malicious intent.
"Spamming your friend's dm" falls under that.

**Comment by DiscordFanBoi** [comment]
@almostSouji oh, where can i get help for general issues?

**Comment by almostSouji** [comment]
- To get started with discord.js you can find our guide here: <https://discordjs.guide/>
- Questions about he library are answered on our discord server: https://discord.gg/bRCvFy9
- Bots running on user accounts are against discord terms of service.
- We will not help you with spamming people.
