### ISSUE TITLE
suddenly Exceeded identify threshold after weeks of no issues

### ISSUE THREAD

**Issue by eyooooo** [discordjs/discord.js#5455]
all of the sudden my bot has been getting this error
```
debug -> Provided token: myToken42069
debug -> Preparing to connect to the gateway...
debug -> [WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
debug -> [WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 0
debug -> [WS => Manager] Spawning shards: 0
debug -> [WS => Manager] Exceeded identify threshold. Will attempt a connection in 20516803ms
```
I have a script that runs once a minute that logs in to discord and sends a few alerts then spins down. This script ran for weeks with no issues. suddenly yesterday i am getting the above error and getting 6+ hour bans.

I cannot find any documentation around this error so I am at a total loss as to why its happening or how to fix it. 

Thanks so much

**Comment by vBread** [comment]
This isn't an issue with the library.

> I have a script that runs once a minute that logs in to discord

Doing this will consume all 1000 of your [identify](https://discord.com/developers/docs/topics/gateway#identifying) calls within ~16.6 hours. Solution? Don't do whatever you're doing. You'll have to wait about 5.5 hours until your limit refreshes according to the debug message.

**Comment by xAtsuUC** [comment]
> I have a script that runs once a minute that logs in to discord

Just a suggestion, don't do this, a better way to do it, is checking if a property like client.user exists, and if not login (client.user only exists when your client is logged in)
