### ISSUE TITLE
Some mentions do not work

### ISSUE THREAD

**Issue by marcelo-mb** [discordjs/discord.js#5464]
**INFO**
- discord version 12 (nodejs)

My bot has a string like this: `<@673505037123956753> \n<@122305034723956753> \n<@122302834723979853>`. He writes this into a message.

**The problem:**
This works well most time, but sometimes it just displays the id, instead of displaying the username.
![Inkedproblem_LI](https://user-images.githubusercontent.com/69599080/113319506-c728d080-9311-11eb-8930-d26eb2f376f2.jpg)  

```
var userString = "<@673505037123956753> \n<@122305034723956753> \n<@122302834723979853>";

var testEmbed= new Discord.MessageEmbed().setTitle("TESTMSG").setDescription(userString);

//channel is defined
channel.send("TEST"), {
      embed: testEmbed,
});
```
**WARNING!** The showed user ids are fictional. The user ids, where the id is shown instead of a mention are in my case: 
- 492992891241889792
- 673505037128957953
_But those are normal user accounts, so it should work. I also can fetch them to get the user object with discord.js_   

Best regards,
marc.

**Comment by SadMap** [comment]
this is not a problem with discord.js your client don't heave that user in its cache and shows the id it's a visual bug not discord.js releated (mentikn still works as normal)

**Comment by marcelo-mb** [comment]
@SadMap
I already thought of this, BUT: 
Here is more of the snippet. I already cache all members contained by the message every time before sending the msg and it still does not work.

```
cacheUsers(districtsObj).then(results => {
   //send message
});

function cacheUsers(user_ids) {
  let promises = [];

  for (var i = 0; i < user_ids.length; i++) {
      promises.push(client.users.fetch(user_ids[i]));
    }

  return Promise.all(promises);
}

```

**Comment by zaida04** [comment]
The issue isn't the users not being cached on the bots end, it's the user not being cached on the Discord CLIENTs end.

**Comment by marcelo-mb** [comment]
@zaida04 Oh, ok. And how would I cache the users on the clients end or is this not possible and I have to work for another way.?

**Comment by zaida04** [comment]
You cannot control whether the end user has the user cached afaik.
