### ISSUE TITLE
Make Channel Ratelimits Error

### ISSUE THREAD

**Issue by tandpfun** [discordjs/discord.js#5473]
**Please describe the problem you are having in as much detail as possible:**
When editing a channel, (setting name, topic, etc), there's a 10 minute ratleimit. If you edit a channel while you are ratelimited, DiscordJS does what it's supposed to, handle the ratelimit by waiting and sending the request again. The problem is that with such a high ratelimit, it would be better for it to be possible to error or a way to tell if the bot is getting ratelimited so that commands aren't just unresponsive for 10 minutes, or users think that a command isn't working and is stuck loading and all of a sudden channel names change. I know that this is intended behavior but I think that since the ratelimit is so high, it should be handled differently.

**Include a reproducible code sample here, if possible:**
```js
await message.channel.setName("a").catch(err => { // No Ratelimits
    console.log("Errored")
})
await message.channel.setName("b").catch(err => { // No Ratelimits
    console.log("Errored")
})
await message.channel.setName("c").catch(err => { // Gets Ratelimited and runs this after 10 minutes with no logs
    console.log("Errored") // Never logs
})
```

**Further details:**

- discord.js version: 12.5.1, 12.4.1
- Node.js version: v14.16.0
- Operating system: MacOS, Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: Not very high, custom cooldowns can be put in place by the bot developer

**Relevant client options:**

- partials: none
- gateway intents: Not Relevant
- other: none

**Comment by NotSugden** [comment]
i believe this is a duplicate of #5449

**Comment by tandpfun** [comment]
> i believe this is a duplicate of #5449

👍
