### ISSUE TITLE
Message Reference Error when using Promise.all()

### ISSUE THREAD

**Issue by Vercidium** [discordjs/discord.js#5477]
**Please describe the problem you are having in as much detail as possible:**
When using `Promise.all()`, the returned Message objects from `message.channel.send` will all reference the same Message object instance.

To replicate this issue, I made a simple bot that repeats what the user says, then edits its message every 3 seconds with a UTC timestamp so we can visually see it's getting edited.

This video shows that the most recent message will receive all edits:

https://user-images.githubusercontent.com/12014138/113511728-b04ddc80-95a4-11eb-9996-86bd7d8e4bc7.mp4

This issue only happens when using `Promise.all()`.

**Include a reproducible code sample here, if possible:**

```js
client.on("message", async message => {

    // Don't handle messages from ourselves
    if (message.author.id == OUR_ID)
        return undefined;

    // Only handle messages from this one channel
    if (message.channel.id != LISTEN_CHANNEL)
        return undefined;

    // Get a copy of the message's content
    let originalContent = message.content;

    [ replyMessage ] = await Promise.all([
        message.channel.send({ content: "Repeat: " + originalContent })
    ]);

    // Edit the message every 3 seconds
    setInterval(() =>
    {
        // Include Date.now() to visually show when the message updates
        replyMessage.edit("Repeat: " + originalContent + " [EDITED] " + Date.now());
    }, 3000);    
});
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 12.18.2
- Operating system: Windows 10
- Priority this issue should have: Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by vaporox** [comment]
This is because you're doing `[replyMessage] = ...` instead of `const [replyMessage] = ...`, thus making it a global variable, and not a bug within the library.

**Comment by Vercidium** [comment]
Oh! Thank you so much, I wasn't aware of that syntax.
