### ISSUE TITLE
guild.members.fetch() not working

### ISSUE THREAD

**Issue by MaxMiddendorp** [discordjs/discord.js#5478]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
client.on('message', message => {
message.guild.members.fetch()
        .then(console.log)
        .catch(console.error);
});
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v14.16.0
- Operating system: Windows 10 20H2
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

I'm trying to get all members in a server but the cache does not work, then I tried the promise but it does not resolve.

**Comment by almostSouji** [comment]
Sounds like it's related to privileged intents:
- https://github.com/discordjs/discord.js/issues/4961
- https://discordjs.guide/popular-topics/intents.html

**Comment by MaxMiddendorp** [comment]
Thank you, did not see that 😅
