### ISSUE TITLE
Error: Client (NodeJS)

### ISSUE THREAD

**Issue by thebigwolfy** [discordjs/discord.js#5479]
(in french sorry)

Le bogue apparait lorsque je redémarre mon bot Discord, cela depuis que j'ai mis à jour NodeJS (actuellement je suis en version 14.16.0).

Lien de l'erreur : [image - imgur](https://i.imgur.com/mnwHgrO.png)

[Link the package to code of fix bug !](https://github.com/discordjs/discord.js/blob/67025e63e4e8306a2b3ff62ae1067acf4b468a6a/src/client/Client.js#L41)

**Comment by zaida04** [comment]
You need to use node v12+ per https://github.com/discordjs/discord.js/issues/1386

**Comment by thebigwolfy** [comment]
I use the version +v12 node 
.

I used v14.16.0 actuality.

**Comment by almostSouji** [comment]
Je ne suis pas sûr de l'origine de ces `()` ici. Notre code de base n'en dispose pas.

Vous pouvez essayer une installation propre et voir si cela résout le problème :
```
npm rm discord.js
npm i discord.js
```
using <https://www.deepl.com/translator>

**Comment by thebigwolfy** [comment]
je l'ai est mises pour essayer, voir si cela changer quelques choses. Mais effectivement cela n'est pas de le code de base.

Cela n'a pas pour autant changer grand chose sur l'erreur, au lieu que cela soit les `()`, c'est `{`, qui se trouve celui-ci dans le code de base !

**Comment by almostSouji** [comment]
La seule raison que je vois pour que cela se produise est que votre version de node.js n'est pas à jour (puisque les structures catch sans paramètre ont été introduites après la version 12).

Make sure the work space of your bot project runs on this version with `node --version`

**Comment by thebigwolfy** [comment]
Nous utilisons bien une version au dessus de 12, actuellement nous utilisons la version 15.13.0 !

**Comment by almostSouji** [comment]
veuillez faire une nouvelle installation
```
npm rm discord.js
npm i discord.js@latest
```
et fournissez la sortie de ces fonctions :
```
npm list discord.js
node --version
```
Après cela, essayez de redémarrer votre application, et fournissez l'erreur exacte qu'elle affiche (sans modifier le code source ou essayer de corriger l'erreur).

L'erreur que vous avez montrée précédemment doit provenir d'une modification personnalisée du code source de discord.js. Le code semble différent de celui que nous utilisons réellement dans la bibliothèque de codes.

**Comment by thebigwolfy** [comment]
En faisant quelques étapes j'ai eu sa :

`npm rm discord.js` : https://i.imgur.com/TLIyWK0.png

https://i.imgur.com/D0bJ3Zq.png

**Comment by almostSouji** [comment]
Post mortem:

OP was using nvm to set node version and pm2 to start the project. The pm2 daemon was started with outdated node, which it passed over to the child processes. OP used `pm2 stop <pid>` to "kill" the process but never touched the daemon.

Solution: kill the pm2 daemon process, set node version, restart.

```
pm2 kill
nvm use node
pm2 start index.js
```

--- 

Post mortem :

L'OP utilisait nvm pour définir la version du noeud et pm2 pour démarrer le projet. Le démon pm2 a été lancé avec un noeud périmé, qu'il a transmis aux processus enfants. OP a utilisé `pm2 stop <pid>` pour "tuer" le processus mais n'a jamais touché le daemon.

Solution : tuer le processus démon pm2, définir la version du nœud, redémarrer.

```
pm2 kill
nvm use node
pm2 start index.js
```
