### ISSUE TITLE
CLIENT_MISSING_INTENTS Throwing even with correct intents

### ISSUE THREAD

**Issue by xAtsuUC** [discordjs/discord.js#5488]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client({ 
    partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],
    intents: Discord.Intents.ALL,
    fetchAllMembers: true
});
```

**Further details:**

- discord.js version: `discordjs/discord.js#599f0f5cef3fc3038db4de654f8035976df3c991`
- Node.js version: `14.15.3`
- Operating system: `docker.io/jensjeflensje/discord_egg:latest (Docker)`
- Priority this issue should have – please be realistic and elaborate if possible: Low/Medium

**Relevant client options:**

- partials: `'MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'`
- gateway intents: `Discord.Intents.ALL`
- other: 
    - Privileged Gateway Intents: `Presence, Guild Members`

Remove the comment and fill out the commit hash if this applies to you:
(While it's not a requirement to test your issue on the master branch, it would make fixing the problem a lot easier for us, so please do so if possible.)

- I have also tested the issue on latest master, commit hash: `599f0f5cef3fc3038db4de654f8035976df3c991`

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this error.

**Comment by xAtsuUC** [comment]
I'm unable too, i'll try re-installing the container and see, thanks

**Comment by xAtsuUC** [comment]
Update:

I'm pretty confused, I changed my code to ```js
const Discord = require('discord.js');
const client = new Discord.Client({ 
    partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],
    intents: Discord.Intents.ALL,
    fetchAllMembers: true
});

console.log('[Discord] ' + typeof Discord)
console.log('[Intents] ' + typeof Discord.Intents)
console.log('[Intents | All] ' + typeof Discord.Intents.ALL)
console.log('[Client] ' + typeof client)
```

And it's loggin
```

**Comment by xAtsuUC** [comment]
I'm pretty confused, I changed my code to ```js
const Discord = require('discord.js');
const client = new Discord.Client({ 
    partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],
    intents: Discord.Intents.ALL,
    fetchAllMembers: true
});

console.log('[Discord] ' + typeof Discord)
console.log('[Intents] ' + typeof Discord.Intents)
console.log('[Intents | All] ' + typeof Discord.Intents.ALL)
console.log('[Client] ' + typeof client)
```

And it's loggin
```

**Comment by xAtsuUC** [comment]
I'm pretty confused, I changed my code to ```js
const Discord = require('discord.js');
const client = new Discord.Client({ 
    partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],
    intents: Discord.Intents.ALL,
    fetchAllMembers: true
});

console.log('[Discord] ' + typeof Discord)
console.log('[Intents] ' + typeof Discord.Intents)
console.log('[Intents | All] ' + typeof Discord.Intents.ALL)
console.log('[Client] ' + typeof client)
```

And it's loggin
```
[Discord] object
[Intents] function
[Intents | All] number
[Client] object
```

But looking at the source code, I saw this:
```js
_validateOptions(options = this.options) {
    if (typeof options.intents === 'undefined') {
      throw new TypeError('CLIENT_MISSING_INTENTS');
    } else {
        /// etc
    }
```

My intents are not undefined, so why am i getting that error?

**Comment by xAtsuUC** [comment]
Actually some idiot of my team re-declared a new client, I'm really sorry for all this, thanks for the help.
