### ISSUE TITLE
Discord.js pemissions do not work with API v8 permissions

### ISSUE THREAD

**Issue by tandpfun** [discordjs/discord.js#5496]
**Please describe the problem you are having in as much detail as possible:**
Creating a new `Discord.Permissions()` throws an error when using the new permissions bitfields from API v8 oauth. In API v7, the guild object looked like this:

```json
{
  id: '81384788765712384',
  name: 'Discord API',
  icon: 'a363a84e969bcbe1353eb2fdfb2e50e6',
  owner: false,
  permissions: 104189632,
  features: [
    'NEWS',
    'BANNER',
    'VIP_REGIONS',
    'INVITE_SPLASH',
    'WELCOME_SCREEN_ENABLED',
    'VANITY_URL',
    'COMMUNITY',
    'MEMBER_VERIFICATION_GATE_ENABLED',
    'PREVIEW_ENABLED',
    'ANIMATED_ICON'
  ],
  permissions_new: '4399156928'
}
```
With a working bitfield. In v8, the new permissions bitfield doesn't work when creating a `new Discord.Permissions()`:
```json
{ 
  id: '81384788765712384',
  name: 'Discord API',
  icon: 'a363a84e969bcbe1353eb2fdfb2e50e6',
  owner: false,
  permissions: '4399156928',
  features: [
    'INVITE_SPLASH',
    'NEWS',
    'PREVIEW_ENABLED',
    'ANIMATED_ICON',
    'COMMUNITY',
    'WELCOME_SCREEN_ENABLED',
    'BANNER',
    'MEMBER_VERIFICATION_GATE_ENABLED',
    'VIP_REGIONS',
    'VANITY_URL'
  ]
}
```

**Include a reproducible code sample here, if possible:**
Fetch `https://discord.com/api/v8/users/@me/guilds` with a bearer guilds token. Turn the permissions field into a permission:

```js
let perms = new Discord.Permissions(data.permissions)
// Throws an invalid bitfield error
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: v12.19.0
- Operating system: MacOS
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by advaith1** [comment]
try `let perms = new Discord.Permissions(BigInt(data.permissions))`

**Comment by tandpfun** [comment]
Same error

**Comment by advaith1** [comment]
oh you're on v12; update to v13 (get the latest master commit)

**Comment by tandpfun** [comment]
Looks like my nodejs version was outdated as well. I'll test on djs v13 in a bit.

**Comment by tandpfun** [comment]
Tested on djs v13 without bigint, got this:
`Invalid bitfield flag or number: 4399156928.`

**Comment by advaith1** [comment]
when you pass a string it assumes the string is a permission name

**Comment by xxxnewbotdevxxx** [comment]
@tandpfun @advaith1 stay with me at predio ter 2880 narain

**Comment by xxxnewbotdevxxx** [comment]
@tandpfun @advaith1

**Comment by xxxnewbotdevxxx** [comment]
the troll is not gone dat place
