### ISSUE TITLE
What format are audio streams?

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/discord.js#5509]
**Please describe the problem you are having in as much detail as possible:**
I have no clue what audio format the opus stream is from a voice channel. According to #2462, it's not valid opus, and I haven't been able to do anything with that, and I have no idea what to do with PCM data. I'd like to know what format this opus is in and why it won't work in an ogg file, or what I'm misunderstanding about opus and ogg. TL;DR: I just want to be able to get any web audio format but I have no idea how to work with these formats because PCM is really hard to use and Opus won't work.

**Include a reproducible code sample here, if possible:**

```js
// Code is executed when the !record command is run
      await message.member.voice.channel.join().then(connection => {
        const dispatcher = connection.play('beep.mp3');
        dispatcher.on('start', () => {
          console.log('beep.mp3 is now playing!');
        });
        dispatcher.on('finish', () => {
          console.log('beep.mp3 has finished playing!');
          const audio = connection.receiver.createStream(message.author.id, {
            mode: 'opus'
          });
          const stream = fs.createWriteStream('audio.ogg');
          audio.pipe(stream);
          audio.on('end', () => {
            stream.end();
            console.log('end');
          });
        });
      });
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 12.16.1
- Operating system: Repl.it Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: No clue

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by amishshah** [comment]
This can be a bit confusing, however the streams provided by a voice receiver _are_ valid Opus streams, in that each data item is a valid Opus packet. However, transporting this stream outside of your process requires it to be encapsulated in some container - the most common container is the Ogg container.

This is outside the scope of discord.js, however [prism-media](https://github.com/amishshah/prism-media/) is used by discord.js and is currently undergoing a rewrite in TypeScript. As part of this, the ability to encapsulate Opus streams in Ogg containers has recently been added ([see here](https://github.com/amishshah/prism-media/pull/70))

Until this is released, your only option is to convert this Opus stream into PCM (raw audio), then use something such as `ffmpeg` or `opusenc` to create an ogg opus stream.
