### ISSUE TITLE
message.author returned undefined

### ISSUE THREAD

**Issue by MrAdhit** [discordjs/discord.js#5512]
**Please describe the problem you are having in as much detail as possible:**
So I want to get the message author, but ``message.author`` just returned undefined
but when I logged the message function I can see that the author is not undefined
```js
    author: User {
      id: '405479178738204673',
      system: null,
      locale: null,
      flags: [UserFlags],
      username: 'MrAdhit',
      bot: false,
      discriminator: '1296',
      avatar: '4c061b04267c2aaaefa04f0cf45fc2e7',
      lastMessageID: null,
      lastMessageChannelID: null
    },
    pinned: false,
```
**Include a reproducible code sample here, if possible:**

```js
channel.messages.fetch().then((message) => {
            console.log(message)
            chanInfoJson.messages.push({
                id: message.id,
                content: message.content,
                author: {
                    id: message.author.id,
                    username: message.author.username,
                    isBot: message.author.bot
                }
            })
        });
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.16.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: idk

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by anandre** [comment]
message is a Collection of messages, and a Collection does not have an author property. You need to access the individual messages within the Collection.

The repo is for bug reports and problems with the library. For problems with your code, please come to the discord server.

**Comment by MrAdhit** [comment]
Oh sorry, I didn't realize
