### ISSUE TITLE
Direct messages are not receiving

### ISSUE THREAD

**Issue by pikokr** [discordjs/discord.js#5516]
```js
client.on('message', msg => {
  if (msg.channel.type === 'dm') {
    console.log(msg)
   // and this does not works
  }
})
```

**Further details:**

- discord.js version: from github
- Node.js version: v15.11.0
- Operating system: Ubuntu 20.10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
The v8 Discord API/gateway does not emit `CHANNEL_CREATE` for DM Channels. As a result, they don't exist in discord.js cache and messages won't emit.

Enabling the `CHANNEL` partial should fix the issue.

**Comment by BadgerCode** [comment]
Is this still the case? Or am I missing something.

Adding the `CHANNEL` partial to my bot fixes the issue where received DMs were not triggering the `messageCreate` event.

E.g.
```js
const client = new Client({
    intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES,
        Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
        Intents.FLAGS.GUILD_MESSAGE_TYPING,
        Intents.FLAGS.DIRECT_MESSAGES,
        Intents.FLAGS.DIRECT_MESSAGE_REACTIONS,
        Intents.FLAGS.DIRECT_MESSAGE_TYPING,
    ],
    partials: [
        'CHANNEL', // Required to receive DMs
    ]
});
```

This seems like very strange behaviour.
I couldn't find any documentation on this behaviour, and I wasn't familiar with partials.

**Comment by kyranet** [comment]
It is, we require a major version to fix that, and there are still some internal discussions about how to handle it so we don't need to define partials (or even, we could remove partials altogether in favor of a better system, to fix another issue).

**Comment by justekoro** [comment]
> It is, we require a major version to fix that, and there are still some internal discussions about how to handle it so we don't need to define partials (or even, we could remove partials altogether in favor of a better system, to fix another issue).

hi! any news? I have the same problem

**Comment by BadgerCode** [comment]
> > It is, we require a major version to fix that, and there are still some internal discussions about how to handle it so we don't need to define partials (or even, we could remove partials altogether in favor of a better system, to fix another issue).
> 
> hi! any news? I have the same problem

Did you try the code snippet I shared above?
I was able to fix the problem with it.

**Comment by ecker00** [comment]
Our bot received messages from some users, but not to others. After adding ` partials: ['CHANNEL'] ` to client config, it now receive messages from all users fine.

**Comment by MakerDZ** [comment]
> > > It is, we require a major version to fix that, and there are still some internal discussions about how to handle it so we don't need to define partials (or even, we could remove partials altogether in favor of a better system, to fix another issue).
> > 
> > 
> > hi! any news? I have the same problem
> 
> Did you try the code snippet I shared above? I was able to fix the problem with it.

I tried your code snippet but i got this error.

```
Intents.FLAGS.GUILDS,
        ^

ReferenceError: Intents is not defined
```

What should i do?

**Comment by MakerDZ** [comment]
> ```js
> client.on("messageCreate", msg => {
>     if (msg.partial) {
>         // Never triggers
>         console.log(`Received partial message- ${msg.id}`);
>         return;
>     }
> 
>     console.log(msg);
>     console.log("Message created")
> });
> ```

Finally it's work!! In discord.js v14, the Intents import does not exist. You instead, need to use GatewayIntentBits when declaring the intents in the client. An example would be something like this:

```
const { Client, GatewayIntentBits } = require('discord.js');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildMessageReactions,
    GatewayIntentBits.GuildMessageTyping,
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.DirectMessageReactions,
    GatewayIntentBits.DirectMessageTyping,
  ],
    partials: [
        'CHANNEL', // Required to receive DMs
    ]
})
```

**Comment by MakerDZ** [comment]
> > > > It is, we require a major version to fix that, and there are still some internal discussions about how to handle it so we don't need to define partials (or even, we could remove partials altogether in favor of a better system, to fix another issue).
> > > 
> > > 
> > > hi! any news? I have the same problem
> > 
> > 
> > Did you try the code snippet I shared above? I was able to fix the problem with it.
> 
> I tried your code snippet but i got this error.
> 
> ```
> Intents.FLAGS.GUILDS,
>         ^
> 
> ReferenceError: Intents is not defined
> ```
> 
> What should i do?

Finally it's work!! In discord.js v14, the Intents import does not exist. We instead, need to use GatewayIntentBits when declaring the intents in the client. An example would be something like this:

```
const { Client, GatewayIntentBits } = require('discord.js');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildMessageReactions,
    GatewayIntentBits.GuildMessageTyping,
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.DirectMessageReactions,
    GatewayIntentBits.DirectMessageTyping,
  ],
    partials: [
        'CHANNEL', // Required to receive DMs
    ]
})
```

**Comment by BierGarten100** [comment]
Doesn't work for me your fix.
```
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildMessageReactions,
    GatewayIntentBits.GuildMessageTyping,
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.DirectMessageReactions,
    GatewayIntentBits.DirectMessageTyping,
  ],
    partials: [
        'CHANNEL', // Required to receive DMs
    ]
})
```
It is the same code but the Bot ignore my dm's

**Comment by Jiralite** [comment]
Your code is sadly incorrect.

This issue is too old. You should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions). It's not particularly a good idea to bump old issues.
