### ISSUE TITLE
GuildMember#guild becomes undefined when extending GuildMember through Structures.extend

### ISSUE THREAD

**Issue by maisans-maid** [discordjs/discord.js#5519]
**Please describe the problem you are having in as much detail as possible:**

When checking the bot permissions on message event, i get the error `TypeError: Cannot read property 'roles' of undefined`. Logging the `message.guild.me`, the logs show that the guild property is undefined. However, when launching the bot without extending the GuildMember, the problem is not anymore present, which leads me to think that extending the class produces the error. 

![](https://cdn.discordapp.com/attachments/223867697312694272/830497302048538624/unknown.png)

**Include a reproducible code sample here, if possible:**

```js
Structures.extend('GuildMember', Member => {
  class GuildMember extends Member {
    constructor(client, data){
      super(client, data);

      this.somecoolvar = null;
    };
   };
   
   return GuildMember
  };
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: >=14
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by vladfrangu** [comment]
This isn't a bug with the library, but with your extension. As you can see, guild members take 3 arguments, not 2

https://github.com/discordjs/discord.js/blob/63ff6a07ebcba7e9134e3902e338e8dc6564ee63/src/structures/GuildMember.js#L22-L29
