### ISSUE TITLE
Use CategoryChannelResolvable for parent setting

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#5521]
**Is your feature request related to a problem? Please describe.**
During the setup of #5507 it came to attention that categories are currently typed as `ChannelResolvable` whenever we ask for a potential parent channel

- ⚠️ requires #5507, typedef/doc is introduced there, needs to be applied across other instances of parent* functionality

**Describe the ideal solution**
The type and documentation could be more specific by introducing a CategoryResolvable type

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Poly-Pixel** [comment]
I also think that a `CategoryResolvable` type would help work with categories since it is a little confusing having them as a channel This feature would definitely help clarify some things.
