### ISSUE TITLE
Wrongfully throwing error "Cannot send messages to this user"

### ISSUE THREAD

**Issue by Mouradif** [discordjs/discord.js#5523]
I noticed this issue with the version currently on npm (12.5.3): I want the bot to reply to DMs with instructions of how to use the bot like so:

```js
bot.on('message', (msg) => {
  if (msg.channel.type !== 'dm') return;
  if (!/^!(title|description|role)/.test(msg.content)) {
    msg.author.send(`Please send one of the following commands:
\`\`\`
!title <some-title>: the title of your project
!description <some-description>: the description of your project
!role <some-role>: Adds/Remove role
\`\`\`
`);
  }
});
```
The bot sends the message successfully but then it crashes with the trace :

```js
/path/to/bot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (/path/to/bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/path/to/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async ClientUser.createDM (/path/to/bot/node_modules/discord.js/src/structures/User.js:252:18) {
  method: 'post',
  path: '/users/831153441824309350/channels',
  code: 50007,
  httpStatus: 400
}
```

I fixed the crashing problem with an empty `.catch()` block but am I doing something wrong here ? It looks like a bug to me

**Further details:**

- discord.js version: 12.5.3 (from npm)
- Node.js version: 15.13.0
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: No priority seems like a small mistake easy to fix though

**Comment by SpaceEEC** [comment]
That error is correct, the bot is trying to dm itself and fails at creating a dm channel (as you can't create a dm channel with yourself).

You may want to add `if (msg.author.bot) return;` at the beginning of your event handler.

**Comment by Mouradif** [comment]
Thanks ! I get it now, the reply is sent to the user and since that answer is also a message that doesn't start with a command, the bot tries to reply to it too
