### ISSUE TITLE
New Stage channels are causing Discord.js to crash on v11.6.4

### ISSUE THREAD

**Issue by icanovi** [discordjs/discord.js#5526]
**Discord bots using Discord.js version 11.6.4 are throwing a "TypeError: Cannot read property 'id' of undefined" on line 81 of the ClientDataManager.js file. New Stage channels seems to be the cause of it.**

**Include a reproducible code sample here, if possible:**

```js
1|npm -- run start:node  | /app/discord-bot/node_modules/discord.js/src/client/ClientDataManager.js:81
1|npm -- run start:node  |         guild.channels.set(channel.id, channel);
1|npm -- run start:node  |                                    ^
1|npm -- run start:node  | TypeError: Cannot read property 'id' of undefined
1|npm -- run start:node  |     at ClientDataManager.newChannel (/app/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
1|npm -- run start:node  |     at Guild.setup (/app/node_modules/discord.js/src/structures/Guild.js:307:68)
1|npm -- run start:node  |     at GuildCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
1|npm -- run start:node  |     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
1|npm -- run start:node  |     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
1|npm -- run start:node  |     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
1|npm -- run start:node  |     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
1|npm -- run start:node  |     at emitOne (events.js:116:13)
1|npm -- run start:node  |     at WebSocket.emit (events.js:211:7)
1|npm -- run start:node  |     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20
```

**Further details:**

- discord.js version: v11.6.4
- Node.js version: v8.11.2
- Operating system: Ubuntu 16.04.2 LTS
- Priority this issue should have – please be realistic and elaborate if possible:Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by papaia** [comment]
Discord v11 is going out of support, this will not get help.
Update to v12.

**Comment by icanovi** [comment]
@papaia We're using node v8.11.2. We can't update to node v12 at the moment. If you confirm there's no other alternative that's ok, I just wanted to confirm that.  
Thanks

**Comment by iShibi** [comment]
Update to v12 of **discord.js**.

**Comment by icanovi** [comment]
@iShibi v12 of discord.js states that "Node.js 12.0.0 or newer is required." in the readme file.

**Comment by almostSouji** [comment]
v11 is no longer supported. we will not fix this.

**Comment by ajmeese7** [comment]
I found a fix, for anyone interested.

Step 1) Add `GUILD_STAGE_VOICE: 13,` to line 291 of  `node_modules\discord.js\src\util\Constants.js`.
Step 2) Add 
```
case Constants.ChannelTypes.GUILD_STAGE_VOICE:
    channel = new VoiceChannel(guild, data);
    break;
```
to line 79 of `node_modules\discord.js\src\client\ClientDataManager.js`.

This isn't a great workaround, so I'm going to host a modified v11 on my fork of the project that can be referenced for people who need a way around this issue. I'll try to push the changes to v11 of the main repository, but if maintainers don't want to merge you can feel free to use my fork.

Will come back and update once I've pushed the changes.

**Comment by almostSouji** [comment]
Or you can stop using outdated versions, we no longer support v11 and do not accept pull requests to outdated branches.

**Comment by ajmeese7** [comment]
Well as long as you refuse to allow selfbots we don't have much of a choice other than using the older versions :)

**Comment by iCrawl** [comment]
As long as selfbots are against ToS and get people banned, we will continue to refuse them. Good luck.
