### ISSUE TITLE
Constants Error

### ISSUE THREAD

**Issue by LeonidioJose** [discordjs/discord.js#5529]
```js
const bot = new Client({ws: {intents: Intents.ALL}})
```
![error](https://user-images.githubusercontent.com/66313178/114720088-160d3780-9d0e-11eb-82bd-27fdc455a78a.png)

**Further details:**

- discord.js version: latest
- Node.js version: 14,16.0
- Operating system: Win 10 64 bits
- Priority this issue should have – ws

**Relevant client options:**

- partials: none
- gateway intents: all
- other: none

**Comment by kyranet** [comment]
What is `latest`, and what are your imports?
