### ISSUE TITLE
Impossible to start my bot

### ISSUE THREAD

**Issue by HideakiAtsuyo** [discordjs/discord.js#5532]
**Please describe the problem you are having in as much detail as possible:**

I added all intentes and added the github ref to this discord.js version but nothing work

**Include a reproducible code sample here, if possible:**

package.json:
```json
{
  "name": "Boii",
  "version": "1.0.0",
  "description": "",
  "main": "Main.js",
  "dependencies": {
    "chalk": "^4.1.0",
    "discord.js": "github:/discordjs/discord.js"
  },
  "devDependencies": {},
  "scripts": {
    "test": "node Main.js"
  },
  "author": "HideakiAtsuyo",
  "license": "MIT"
}

```

Main.js:
```js
const Discord = require('discord.js');

const playboy = new Discord.Client({ intents: Discord.Intents.ALL });


playboy.on('ready',() => {
	console.log("playboy")
});

```
Result: https://i.imgur.com/cY44jgt.png

**Further details:**

- discord.js version: github:/discordjs/discord.js so, the last :)
- Node.js version: v14.15.4
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Medium
**Relevant client options:**

- partials: none
- gateway intents: yes => https://i.imgur.com/e2kJS1j.png
- other: none

Commit hash: [eb43ce4d4fb4d634696c5b0f026174dc0e435fe3](https://github.com/discordjs/discord.js/commit/eb43ce4d4fb4d634696c5b0f026174dc0e435fe3)

**Comment by zaida04** [comment]
In your code example, it doesn't look like you actually call login anywhere. 

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by HideakiAtsuyo** [comment]
> In your code example, it doesn't look like you actually call login anywhere.
> 
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

You are right it's been a long time that i don't have to deal with djs lol sorry !
