### ISSUE TITLE
guildMemberUpdate is not emitted for the first member update

### ISSUE THREAD

**Issue by JingleChannel** [discordjs/discord.js#5533]
guildMemberUpdate is not emitted for the first update of a regular member (i.e. change nickname, add/remove a role). guildMemberUpdate is emitted on the first update for a bot member and on all later changes for normal members, but not on the first change.

```js
client.on('guildMemberUpdate', (oldMember, newMember) => {
  // ! FIXME the first removal of a role from a user after bot restart does not fire this event
  console.log('FIRED');
});
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 12
- Operating system: macOS + Debian
- Priority this issue should have – please be realistic and elaborate if possible: high

**Comment by advaith1** [comment]
discord.js does not emit events for uncached structures unless you set partials: https://discord.js.org/#/docs/main/stable/topics/partials

**Comment by JingleChannel** [comment]
Thank you very much for the fast repsonse! I asked on your discord first, but nobody answered my question. :)

For anyone else coming across this, here is the code for opting in to partials for guild members:

`const client = new Discord.Client({ partials: ['GUILD_MEMBER'] });`
