### ISSUE TITLE
Ability to get the Author of a deleted invite

### ISSUE THREAD

**Issue by AKASGaming** [discordjs/discord.js#5534]
**Is your feature request related to a problem? Please describe.**
When `inviteDeleted` is emitted, `invite.author` is not available.

**Describe the ideal solution**
I found this as a good way to get the author of a deleted invite:

```
client.on('inviteDelete', async invite => { 
	const fetchedLogs = await invite.guild.fetchAuditLogs({ limit: 1, type: "INVITE_CREATE" });
	const inviteLog = fetchedLogs.entries.filter(inv => inv.changes[0].new === invite.code);
        inviteLog.map(l => l.executor)
})
```

**Describe alternatives you've considered**
None

**Additional context**
Used in embed here:
![image](https://user-images.githubusercontent.com/25405047/114944958-21478c80-9e0e-11eb-8ba2-3f50634b9c8f.png)

**Comment by monbrey** [comment]
Discord.js cannot emit any information that isn't provided by the event from Discord. In this case an INVITE_DELETE event only gives us channel_id, guild_id and the invite code.

As invites are also not cached by the library, there's no full invite (with author) that can be provided. If it's important to track invites in this way it's up to the user to implement.
