### ISSUE TITLE
Search method

### ISSUE THREAD

**Issue by dindin-glitch** [discordjs/discord.js#5537]
So basically, I have a problem where i need my bot to search a specific word in a specific channel, but that means that I have to loop many times and the thing is super slow...

So my idea is to add a guild.prototype.search(String) method that would act exactly like the search bar in the application

**Comment by almostSouji** [comment]
The message search endpoint is not available for bots as per API limitation. You can fetch 100 messages per request via [`<TextChannel>.messages.fetch(...)`](https://discord.js.org/#/docs/main/stable/class/MessageManager?scrollTo=fetch) and chain them with the respective query parameters.

Doing that indefinitely across the entire guild or even just a very busy channel is very much not recommended.
Providing the desired functionality on the library level is not feasible.

**Comment by almostSouji** [comment]
See upstream to track when this might be available in the future: https://github.com/discord/discord-api-docs/issues/663
