### ISSUE TITLE
Cannot read proprety 'type' of undefined when trying to resolve a Stage Channel

### ISSUE THREAD

**Issue by GeekCornerGH** [discordjs/discord.js#5540]
**Please describe the problem you are having in as much detail as possible:**
So, when I try to get type of a stage channel with channel.type proprety, I got the followig error:
```js
Type error: Cannot read proprety 'type' of undefined at WebSocketManager.<anonymous>
```

**Include a reproducible code sample here, if possible:**
Yes, I can provide you this. Enjoy 😋

```js
const channel = <client>.channels.cache.get(IdOfStageChannelHere);
if(!channel.type === 'voice') <message>.channel.send("Not a voice channel");
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.15.4
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: moderately urgent, I think

**Relevant client options:**

- partials: none (Never used this 🤔)
- gateway intents: Presence and members
- other: none (what do you mean by this? 🤔)

**Comment by OverseersMight** [comment]
You aren’t checking if the channel that you just got exists before trying to check it’s type.
```js
const channel = client.channels.cache.get(ID)
if (!channel) return;
if (channel.type === 'voice'){
  // code here
}
```
Try that.

I’m on mobile currently so sorry if formatted incorrectly.

**Comment by monbrey** [comment]
Stage Channels are not supported in 12.5.3.

**Comment by OverseersMight** [comment]
> Stage Channels are not supported in 12.5.3.

This too,
Completely forgot they aren’t supported yet, though my code will still prevent it from erroring I believe.

**Comment by GeekCornerGH** [comment]
> Stage Channels are not supported in 12.5.3.

Oh, I haven't noticed this sorry

**Comment by GeekCornerGH** [comment]
> You aren’t checking if the channel that you just got exists before trying to check it’s type.
> ```js
> const channel = client.channels.cache.get(ID)
> if (!channel) return;
> if (channel.type === 'voice'){
>   // code here
> }
> ```
> Try that.
> 
> I’m on mobile currently so sorry if formatted incorrectly.

Thank you, it does work perfectly 😃
