### ISSUE TITLE
High CPU usage by discord.js bot

### ISSUE THREAD

**Issue by FullLager** [discordjs/discord.js#5541]
**Please describe the problem you are having in as much detail as possible:**

Since few weeks with my bot use more and more CPU on my raspberry. I saw thaat with the top command. the node process actually use 30% of my CPU. I also searched on internet and github and found that I have to compress with ```zlib-sync```. So I installed this package in the bot directory but I don't know what I have to do to implement this module in my code. The wiki doesn't explain what I have to do and I'm lost. thank you for your help.

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.4.0
- Operating system: Debian 10 -> Buster

**Comment by uhKevinMC** [comment]
`zlib-sync` is used by the library, whenever it is present, to handle the WebSocket data compression and inflation, you don't need to do anything with it unless you plan to use it in your code. Considering you are running a bot with who knows however many guilds/users on a Raspberry Pi, 30% seems fairly close to what I would expect.

Where it would start being a problem is when you notice considerable performance degradation on the bot.

**Comment by FullLager** [comment]
I don't think so because Discord.js recommend to use the zlib-sync librarie. So we can think that the librarie is not used by the discord.js and we have to use it by our ownself but how ? How can I setup the librairie in my code. It's my question.

**Comment by iCrawl** [comment]
You do not need to do anything but install it.

Mind you that your CPU usage will not go down but go up if you add compression and decompression since those 2 are CPU intensive tasks. Not sure where you read that installing those is going to lower your CPU usage.
