### ISSUE TITLE
Embeds cant show imgs without extensions

### ISSUE THREAD

**Issue by AMTitan** [discordjs/discord.js#5546]
In an embed, I cant use an img that does not have an extension

(and don't questing the bot)
```js
const Embed = {
color: '#00ff00',
title: "Waifu",
url: "https://waifu.now.sh/sfw/waifu",
author: {
Name: 'AnimeBot',
icon_url: "",
url: '',
},
description: ``,
thumbnail: "",
fields: [
],
image: {
url: "https://waifu.now.sh/sfw/waifu"
},
fimestamp: new Date(),
footer: {
test: '',
icon_url: "",
},
}

message.channel.send({ embed: Embed });
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 15.14.0
- Operating system: Arch Linux x86_64
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
I'm pretty sure this is a Discord limitation, discord.js doesn't do any handling to control how Discord renders the image in an embed.

Nothing we can do in the library to correct this.

**Comment by AMTitan** [comment]
> I'm pretty sure this is a Discord limitation, discord.js doesn't do any handling to control how Discord renders the image in an embed.
> 
> Nothing we can do in the library to correct this.

rip

**Comment by BannerBomb** [comment]
I cannot reproduce, the url you are using "waifu.now.sh" redirects to "waifu.vercel.app". I don't think discord follows redirects which is why the image doesn't work. But using the redirected URL "waifu.vercel.app" works fine.
