### ISSUE TITLE
Npm Install Clipboard

### ISSUE THREAD

**Issue by MusabShakeel576** [discordjs/discord.js#5548]
It would be fast and efficient if "npm install discord.js" in Discord JS Org website has a copy to clipboard button.

**Comment by iShibi** [comment]
You're on the wrong repo. Ask for the feature request on the website's repository.

**Comment by MusabShakeel576** [comment]
Thanks iShibi, where is the website's repository?

**Comment by iShibi** [comment]
https://github.com/discordjs/website

**Comment by MusabShakeel576** [comment]
Thanks iShibi
