### ISSUE TITLE
"MessageEmbed field values may not be empty" but field value is not empty

### ISSUE THREAD

**Issue by Giuliopime** [discordjs/discord.js#5554]
It throws an empty field value error but the field value is not falsy, it sends the embed correctly too with all the content specified in the code, but it also throws the error.

```js
console.log(suggestionText) // Some text correctly logged (it's just message.content)
const response = new MessageEmbed()
      .setColor(message.guild.me.displayHexColor)
      .setTitle(message.member.user.username + '\'s Suggestion')
      .addField('Checkmark if you think that\'s a nice idea', suggestionText)
      .setFooter('Astro Suggestions handler')
      .setTimestamp()
```

Error:  
`RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values may not be empty.`

**Further details:**

- discord.js version: ^12.2.0 (should have latest installed)
- Node.js version: 12.19.1
- Operating system: MacOS Catalina
- Priority this issue should have – please be realistic and elaborate if possible: Moderate

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by almostSouji** [comment]
If it sends the embed then that's not the send call that fails. Keep in mind that embeds cause a `messageUpdate` event because embeds are "edited into" the message, which in turn does not have content (this becomes relevant in case you log message changes).

 ---
 
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by Giuliopime** [comment]
> If it sends the embed then that's not the send call that fails. Keep in mind that embeds cause a `messageUpdate` event because embeds are "edited into" the message, which in turn does not have content (this becomes relevant in case you log message changes).
> 
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

The error refers to that line of code: `addField`

**Comment by almostSouji** [comment]
This error prevents the embed from sending. If it sends, this is not the embed or äddField call this error originates from. There is no bug with the library but with how you handle one of your embeds, please join the discord server if you require more assistance, the GitHub repository is only used for bug reports and feature suggestions.

**Comment by Giuliopime** [comment]
I sent it in the Discord, but I still think it's a bug.
