### ISSUE TITLE
presenceUpdate not working for streaming (on Discord or Twitch)

### ISSUE THREAD

**Issue by LangkaWS** [discordjs/discord.js#5561]
**Please describe the problem you are having in as much detail as possible:**
I want to execute some code when the presence of a member change to `STREAMING`.

For now, just for testing, I use the `presenceUpdate` event and I just want to `console.log` the new presence, without any condition or filter.
```js
client.on('presenceUpdate', async (oldPresence, newPresence) => {
  console.log(newPresence);
});
```
When the member starts a game for example, the `presenceUpdate` event is triggered and I have the log in the console :
```
Presence {
  ...
  activities: [
    Activity {
      name: 'my game',
      type: 'PLAYING',
      ...
    }
  ]
}
```
When the member starts a stream on Discord or on Twitch, the `presenceUpdate` event is not triggered, and therefor doesn't log.

**Include a reproducible code sample here, if possible:**

```js
//.env file contains BOT_TOKEN
require('dotenv').config();

const { Client, Intents } = require('discord.js');
...
const intents = new Intents();
intents.add(Intents.ALL);

const client = new Client({
  partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'USER'],
  ws: {
    intents: intents //I tried with 'intents: [Intents.NON_PRIVILEGED, 'GUILD_PRESENCES', 'GUILD_MEMBERS']' too but doesn't work
  }
});

try {
  client.login(process.env.BOT_TOKEN);
  
  client.on('ready', () => {
    console.log('Hello');
    client.user.setActivity('!help', {type : 'LISTENING'});
  });

} catch (err) {
  console.log(err);
}

...

client.on('presenceUpdate', (oldPresence, newPresence) => {
  console.log(newPresence);
});
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.5
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Medium: it prevents one feature of my bot, and it is used inside a little community, but this bug (if it is from discord.js) could have effect on other bots.

**Relevant client options:**

- partials: 'MESSAGE', 'CHANNEL', 'REACTION', 'USER'
- gateway intents: Intents.ALL, Privileged Gateway Intents 'Presence Intent' and 'Server Members Intent' both active on Discord Devleper Portal
- other: none

**Comment by Susdevlmao** [comment]
Hey check out this video should help https://www.youtube.com/watch?v=xvFZjo5PgG0

**Comment by LangkaWS** [comment]
Ok, I solved the problem. It didn't come from discord.js or from my bot.
I had to set a stream title on Twitch... And now it works perfectly.

**Comment by andrewowen** [comment]
I opened a separate feature request [here](https://github.com/discordjs/discord.js/issues/6124), but I'd argue that this hasn't been fixed at least from the Discord Go Live setting. The STREAMING activity still doesn't fire. My code example mirrors the use case mentioned above
