### ISSUE TITLE
Changing channel permissions for everyone role

### ISSUE THREAD

**Issue by Bartek6772** [discordjs/discord.js#5569]
Tries to change the channel settings so that the role everyone cannot display it. However, something broke because the channel permissions for this role remain unchanged. The console is not reporting any errors to me.

The problem is definitely not with the chat variable, because changing the access for a given user works fine. Probably the problem lies in changing the permissions for the role.

```js
const chat = await server.channels.create(`${name}-chat`, { type: 'text' });
// ...
chat.overwritePermissions([
    {
        id: server.roles.everyone.id,
        deny: ['SEND_MESSAGES', 'VIEW_CHANNEL'],
    },
]);
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 12.18.2
- Operating system: Windows 10
- Priority this issue should have:
   I think the priority is so medium because it could be a problem with something on the discord side, or some simple code bug.

**Comment by thehairy** [comment]
I can't recreate this issue.
Are you sure the everyone role can still see the channel?

Did you check that using the "View server as role" feature?

**Comment by Bartek6772** [comment]
My point is to create a private text channel. I did this by creating a channel first and then changing the permissions for the role everyone. But this permission change doesn't work.

Regarding the question, the role of everyone sees this channel and the bot has administrator rights.
