### ISSUE TITLE
Missing permission error trace path

### ISSUE THREAD

**Issue by Jarco-dev** [discordjs/discord.js#5578]
**Is your feature request related to a problem? Please describe.**
When ever discord.js throws a Missing permission error it gives a trace path wich doesn't really lead to anything I'd need to do anything with and it can be quite hard at times to figure out where it was thrown from when it was running in production and you warn't actively working on the code when the error occured

**Describe the ideal solution**
The ideal sollution for me would to have the Missing permission error come with a path to the place in the code where the call that it didn't have permissions for

**Describe alternatives you've considered**
Not sure what could be a alternative tbh

**Additional context**
The current error message for missing permissions
![image](https://user-images.githubusercontent.com/77607225/116786740-9e2a6580-aaa0-11eb-938d-9b2ef615a1da.png)

**Comment by tipakA** [comment]
Since 12.4.0 discord.js does include better async stack traces, but it's limited to awaiting async calls and returns - basically, you are not going to see them when using `then` or `catch`. From my quick testing to validate that, running
```js
async function x() { message.channel.fetchWebhooks() }
async function y() { await message.channel.fetchWebhooks() }
x();
y();
```
on a bot without required permissions throws with this for `x()`:
```
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'get',
  path: '/channels/503245735941111809/webhooks',
  code: 50013,
  httpStatus: 403
}
```
and with this for `y()`:
```
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async y (eval at <anonymous> (/bot/index.js:201:22), <anonymous>:1:22)
    at async clean (/bot/index.js:67:62)
    at async Client.<anonymous> (/bot/index.js:202:17) {
  method: 'get',
  path: '/channels/503245735941111809/webhooks',
  code: 50013,
  httpStatus: 403
}
```
which clearly indicates entire call stack for that specific call

**Comment by kyranet** [comment]
For more information (and a lot more technical), see [V8's document on async stack traces](http://bit.ly/v8-zero-cost-async-stack-traces).

**Comment by Jarco-dev** [comment]
Thanks for the info then I'll try to use await more in that case altough that means I'll have to await in cases where it's completely uneccecairy just to make sure i get a usable error

Issue closed as it's obviously not a enhancement thats needed according to the first reply
