### ISSUE TITLE
Add support for API v9 and Threads

### ISSUE THREAD

**Issue by zeel01** [discordjs/discord.js#5579]
I noticed this gem in the Disord API docs popped up 19 hours ago:
https://github.com/discord/discord-api-docs/blob/master/docs/topics/Threads.md

> ## Threads
> Threads are a new Discord feature, only available in API v9. Bots that do not update to API v9 will not receive gateway events for threads, or things that happen in threads (such as Message Create). Threads can be thought of as temporary sub-channels inside an existing channel, to help better organize conversation in a busy channel.
> 
> Threads have been designed to be very similar to channel objects, and this topic aggregates all of the information about threads, which should all help to make migrating very straightforward.
> 
> ## Disclaimer
> Threads have not shipped yet, and so everything in this documentation is still subject to change. At a minimum additional status codes will be added for reaching certain limits, and we may implement additional features, especially around moderation tooling, but we don't expect any of those to be breaking changes for what is currently documented.
> [...]

**Describe the ideal solution**
Keep an eye on these specs with a goal of remaining ahead of the curve regarding these changes.

**Comment by vaporox** [comment]
#5570

**Comment by Susdevlmao** [comment]
Hey Check out this vid it should help https://www.youtube.com/watch?v=xvFZjo5PgG0
