### ISSUE TITLE
Clearing client activities invalidates session

### ISSUE THREAD

**Issue by pettinen** [discordjs/discord.js#5584]
**Please describe the problem you are having in as much detail as possible:**

It seems that the intended way to clear a bot user's activity is to call `ClientUser#setActivity` without arguments.
This causes `ClientPresence#set` to send `activities: null` in the packet, which invalidates the session:
`[WS => Shard 0] [INVALID SESSION] Resumable: false.`

I think `[]` should be passed instead of `null` at
https://github.com/discordjs/discord.js/blob/af00ec8970e77ea8a0afd21571eeeef9c554e1ec/src/structures/ClientUser.js#L164
and [`ClientPresence#_parse`](https://github.com/discordjs/discord.js/blob/af00ec8970e77ea8a0afd21571eeeef9c554e1ec/src/structures/ClientPresence.js#L31) updated accordingly. Could draft a pull request myself but I'm not sure if the lower half of `_parse` requires changes.

(Previously mentioned this in https://github.com/discordjs/discord.js/issues/5316#issuecomment-787690125. At that time the [Gateway documentation](https://discord.com/developers/docs/topics/gateway#update-presence-gateway-presence-update-structure) mentioned (seemingly incorrectly) `null` as a possible value for `activities`, but it's been corrected to require an array of activities.)

**Include a reproducible code sample here, if possible:**

```js
import { Client, Intents } from 'discord.js';

const client = new Client({ intents: Intents.NON_PRIVILEGED });

client.on('debug', info => { console.log(`[DEBUG] ${info}`); });
client.on('ready', () => {
  client.user.setActivity();
});
client.login();
```

**Further details:**
- discord.js version: master
- Node.js version: 16.0.0
- Operating system: arch

**Relevant client options:**
- partials: none
- gateway intents: probably not relevant, tested with Intents.NON_PRIVILEGED
- other: none
- I have also tested the issue on latest master, commit hash: af00ec8970e77ea8a0afd21571eeeef9c554e1ec

**Comment by lights0123** [comment]
As you sort of suggested, a workaround for this is to use `client.user.setPresence({ activities: [] })`.

**Comment by Protected** [comment]
Had a hell of a time figuring out what was causing this, since the bot is immediately kicked out of voice channels when this happens. I thought it was a dispatcher issue.
