### ISSUE TITLE
WS v8 Invalid bitfield flag or number

### ISSUE THREAD

**Issue by DaisyDogs07** [discordjs/discord.js#5587]
**Please describe the problem you are having in as much detail as possible:**
Whenever I try to login using ws version 8 it throws a LOT of impassable errors. I've tried everything to get passed them but nothing worked.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js'),
  client = new Discord.Client({
    ws: {
      version: 8,
      intents: Discord.Intents.NON_PRIVILEGED
    }
  });

client.login('token');
```

**Further details:**
- discord.js version: 12.5.3
- Node.js version: 12.16.1
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: maybe a little high idk

**Relevant client options:**

- partials: none
- gateway intents: all non privileged intents
- other: none

**Extra info:**
I have tried this on the master branch but there was a different error that was in the Collection class due to an unsupported Node.js feature.
Also I can't update Node.js since I am using a hosting site that has Node.js built in so it's up to them whether it will be updated.

**Comment by vladfrangu** [comment]
You cannot just change the ws version and expect things to work. There's breaking changes that will not work without internal changes in discord.js. If you cannot change the nodejs version (really, they don't support 14? its LTS for ages), I don't really know what else to suggest, maybe others do! (or.. create a fat bundle with something like rollup and turn the es version down to like 2019, but that's.. not recommended for many reasons)..
