### ISSUE TITLE
Cannot read property 'url' of null. discord.js/src/client/websocket/WebSocketShard.js:268

### ISSUE THREAD

**Issue by Pliexe** [discordjs/discord.js#5590]
Casually am randomly getting this error which am guessing is executed when the shard opens each time.

https://github.com/discordjs/discord.js/blob/af00ec8970e77ea8a0afd21571eeeef9c554e1ec/src/client/websocket/WebSocketShard.js#L268

![Screenshot_20](https://user-images.githubusercontent.com/42877326/117318658-e96eba80-ae8a-11eb-8709-d042bc2aed6f.png)

**Comment by nab138** [comment]
I get the same error and it happens a random amount of time after starting the bot

**Comment by meister03** [comment]
It can happen on a instable connection

**Comment by muhimur9049** [comment]
By any chance will this be fixed before v13 release? Just had 1 shard crash and restart last night because of it. Is there any way to error handle it manually ourselves for now?

**Comment by MagesticChicen** [comment]
I agree, this needs to be fixed quite urgently. My client seems to run into this error frequently and with no real means to fix it alot of us are just stranded waiting months for anything to change. Preventing an instable connection is easier said than done

**Comment by kyranet** [comment]
As announced, discord.js v13 (which includes a fix for this) is releasing by the mid-end of this month.

**Comment by muhimur9049** [comment]
> As announced, discord.js v13 (which includes a fix for this) is releasing by the mid-end of this month. If a fix is so urgent, feel free to use the `@dev` tag from npm to prepare your bots for v13 and check `#djs-at-dev` in the [official Discord server](https://discord.gg/djs) for any help.

Wait, so does the master branch already have a fix for this, or are you saying v13 will have a fix for this whenever it's released? Because I'm using the master branch right now, and that error still occurred. I'm assuming it's because I'm using an older commit that I installed with `npm i discordjs/discord.js` before. I will try installing with `npm i discord.js@dev` later if a newer commit indeed fixes this.
