### ISSUE TITLE
DiscordAPIError: Unknown application command permissions

### ISSUE THREAD

**Issue by JKLorenzo** [discordjs/discord.js#5621]
**Please describe the problem you are having in as much detail as possible:**

`ApplicationCommand.fetchPermissions()` throws `DiscordAPIError: Unknown application command permissions` when the `ApplicationCommand` doesn't have its permissions set.

It is important to note that the ApplicationCommands mentioned here are guild-specific (not global).

**Include a reproducible code sample here, if possible:**
```js
// When fetching permissions from the guild containing ApplicationCommands with and without permissions set
GuildApplicationCommandManager.fetchPermissions() // <--- 🟠 Returns an array of ApplicationCommandPermissions for those ApplicationCommands with permissions set.

// When ApplicationCommand has its permissions set
ApplicationCommand.fetchPermissions() // <-- 🟢 Returns an array of ApplicationCommandPermissions

// When ApplicationCommand doesn't have permissions
ApplicationCommand.fetchPermissions() // <-- 🔴 Throws DiscordAPIError: Unknown application command permissions
```

**Further details:**
- discord.js version: master
- Node.js version: v14.16.0
- Operating system: Windows 10 19042.985
- Priority this issue should have – please be realistic and elaborate if possible: medium
- I have also tested the issue on latest master, commit hash: `73f4114`

**Comment by monbrey** [comment]
ApplicationCommands (global's) do not have permissions - this is due to be fixed in a PR

**Comment by JKLorenzo** [comment]
> ApplicationCommands (global's) do not have permissions - this is due to be fixed in a PR

Yes, this issue does not cover global ApplicationCommands as stated in the description:
> It is important to note that the ApplicationCommands mentioned here are guild-specific (not global).

**Comment by JKLorenzo** [comment]
I might have to close this as this seemed to be an API issue.
