### ISSUE TITLE
I got banned from the Discord server a few months ago and Crawl still hasn’t accepted my friend request so I can appeal. Any way I can appeal?

### ISSUE THREAD

**Issue by heyseb4** [discordjs/discord.js#5628]
My username is BC#3348 and I would like to appeal. I was banned for not knowing JS and I recently took a class on JS and watched a video. I am very sorry for annoying staff in DMs about not knowing code and wasting their time. It will never happen again. Thank you for reading!

**Comment by vBread** [comment]
> The issue tracker is only for bug reports and enhancement suggestions. ~~If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.~~
