### ISSUE TITLE
[Interactions] Able to directly send MessageAttachment without content

### ISSUE THREAD

**Issue by manuel-di-iorio** [discordjs/discord.js#5629]
**Is your feature request related to a problem? Please describe.**
In the new interaction commands, the _CommandInteraction.reply()_ method is not retro-compatible with the _Message.reply()_ method. Specifically, it's not possible to send a MessageAttachment as first argument, since an error is thrown.

```
ERROR (DiscordAPIError): Invalid Form Body
data.content: This field is required
    DiscordAPIError: Invalid Form Body
    data.content: This field is required
```

**Describe the ideal solution**
```js
const attachment = new MessageAttachment(buffer, 'color.png')
interaction.reply(attachment)
```

Example result with `message.reply(attachment)`:

![image](https://user-images.githubusercontent.com/2255291/118240549-6c9b9c00-b49b-11eb-9030-25f1a2073c6c.png)
---

The closest alternative I found is the following, but as you can see the expected result is pretty different, since it requires a message content and the embed title/description, or errors are thrown.

```js
await interaction.reply("Color", {
      embeds: [new MessageEmbed({ title: "Color", files: [attachment] })]
    });
```

![image](https://user-images.githubusercontent.com/2255291/118241498-812c6400-b49c-11eb-98a5-13dadcf457e5.png)

**Comment by monbrey** [comment]
You're not wrong - but this isn't a Discord.js issue. As per the error you shared, the Discord API is what's responding saying content is required.

In fact, based on the [API docs for responses](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata) files are even supported at all.

**Comment by iShibi** [comment]
You can `defer` the interaction and then use `editReply` to get the exact same result:
```js
interaction.defer();
if (interaction.commandName === 'test') {
  const msgAttach = new MessageAttachment('path/to/image', 'img-name.jpg');
  return interaction.editReply(msgAttach);
}
```
The docs don't show `MessageAdditions` (which includes `MessageAttachment` too) as a type for `content` paramter for `<Interaction>.editReply`, I can open a PR to add it.

**Comment by manuel-di-iorio** [comment]
@iShibi It works by using the editReply 💯 
As you pointed about the interface, I temporarily added `@ts-expect-error` in my code, but yeah it works actually.
