### ISSUE TITLE
Editing a role can result in a Missing Permissions error even when just wanting to edit simple values (Like name or colour)

### ISSUE THREAD

**Issue by PoroUsedSnax** [discordjs/discord.js#5634]
**Is your feature request related to a problem? Please describe.**

When editing a role, such as directly through `Role#edit()` or with a method like `Role#setHoist()`, since they use the same `edit` method, if you want to edit something simple about that role, such as the name, colour, etc, the bot may end up returning a `Missing Permissions` error if the bot doesn't have *at least* the same permissions as the role it's trying to edit, since the `edit` method is sending the role's own permissions as part of the edit with no way to overwrite that functionality as far as I can tell.

**Describe the ideal solution**

- Solution 1. `edit` only sends the values that are necessary relative to the edit the developer (or a method using `edit`) wants to make.
- Solution 2. `edit` allows the developer to overwrite the permissions that the method internally sets, such as setting `permissions` to `null` to have it not specify anything for that field.
- Solution 3. `edit` sends everything but the `permissions` field unless specified when calling it, since the other fields don't need any special permission requirements to be edited.

**Describe alternatives you've considered**

- Alt. 1. If the functionality is used in a command (as it is in my case), it could be specified to the user that they need to give a role the bot has all the same permissions as the role they are trying to edit (Or maybe give the bot the same role whilst they are trying to edit it). These both seem like they would create more work for the user unnecessarily, and I have had one user choose not to use the relevant command because of the permissions requirement.
- Alt. 2. A request *could* be made directly to the API, but I'm sure this would be unrecommended and would likely cause issues for the library functionality too if not done correctly.

**Additional context**
N/A

**Comment by DumbGameMaker** [comment]
> the bot may end up returning a `Missing Permissions` error if the bot doesn't have at least the same permissions as the role it's trying to edit
could you clarify a little on that? i'm having a hard time understanding what you mean by this

**Comment by DumbGameMaker** [comment]
ok i think I understand now. so if the bot does not have the same or better permissions than the role that the bot is attempting to edit, then it will have a missing permissions error?

**Comment by PoroUsedSnax** [comment]
> ok i think I understand now. so if the bot does not have the same or better permissions than the role that the bot is attempting to edit, then it will have a missing permissions error?

Yes, say for example you have a role you want to edit which just has the ATTACH_FILES permission, and the bot editing it doesn't have that permission on any of its roles, then that will result in the error.
