### ISSUE TITLE
`GuildEmoji#author` returns `null`, rename key to `GuildEmoji#user`

### ISSUE THREAD

**Issue by iamfabio** [discordjs/discord.js#5637]
**Please describe the problem you are having in as much detail as possible:**

The property `GuildEmoji#author` returns `null` in every case. It seems Discord has changed their API to use the `user` key instead of the `author` key. I can get all the data directly through the API (there is no `author` key, only a `user` key) but not through the `GuildEmoji` object itself. [This is also documented in the official Discord API docs](https://discord.com/developers/docs/resources/emoji#emoji-object-emoji-structure).

**Include a reproducible code sample here, if possible:**

```js
// Will print `null` for every existing emoji.
guild.emojis.cache.forEach(emoji => {
    console.log(emoji.author);
});
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.16.1
- Operating system: Windows 10 19042.985
- Priority this issue should have: Medium
- I have also tested the issue on latest master, commit hash: `ab82cafcde0ee259a32ef14303c1b4a64dea8fae`

**Comment by BannerBomb** [comment]
You can fetch the emojis author using [GuildEmoji#fetchAuthor](https://discord.js.org/#/docs/main/stable/class/GuildEmoji?scrollTo=fetchAuthor)

**Comment by iamfabio** [comment]
Thanks for the response. I have completely missed the `GuildEmoji#fetchAuthor` method for some reason. Closing this since this is clearly not a bug.
