### ISSUE TITLE
Expose Client.api.interactions(id, token) as developer friendly API

### ISSUE THREAD

**Issue by Noah-Huppert** [discordjs/discord.js#5647]
**Is your feature request related to a problem? Please describe.**
The HTTP interaction API allows clients to call slash command interaction endpoints using the interaction ID and token. These two pieces of state are all that is required to invoke with the interactions API (*not including stuff like API authentication, ect).

This is convenient because the program that receives a new interaction doesn't necessarily have to be the program responding to the interaction. As the receiving program can always share the interaction ID and token, and let someone else take care of it.

The problem is that the Discord JavaScript API does not allow this pattern, and is way less flexible. In the Discord.js API you can only interact with the interactions API if you have the `CommandInteraction` instance which is provided as an argument to your `on("interaction", ...)` handler. 

*This means that the interaction has to be responded to within the exact same JavaScript process which it was received.*

The reason is because you as a user cannot construct a `CommandInteraction` instance. The current constructor takes a Discord client (not a problem) and the raw packet data of the interaction (a problem, the user never has access to this).

**Describe the ideal solution**
I saw that internally Discord uses a method to create a Discord slash commands interactions client using only the interaction ID and token:

https://github.com/discordjs/discord.js/blob/68b40dd91df70593c8271bd455fd0b3c6d19d334/src/structures/CommandInteraction.js#L121

If Discord.Js could expose a developer friendly JavaScript API which allows interaction endpoints to be called only knowing the interaction ID and token that would be ideal.

**Describe alternatives you've considered**
Right now the only way to do this is to not use Discord.Js. But instead call the Discord interactions HTTP API directly.

**Additional context**
N/A

**Comment by Noah-Huppert** [comment]
https://github.com/discordjs/discord.js/blob/master/src/structures/CommandInteraction.js#L121

Kind of like how the internal API works. Unfortunately this field is private. Perhaps a better ideal solution is just to expose this.

**Comment by ckohen** [comment]
>This is convenient because the program that receives a new interaction doesn't necessarily have to be the program responding to the interaction. As the receiving program can always share the interaction ID and token, and let someone else take care of it.

The reply and defer options must be called within 3 seconds of receiving the interaction which means sending the id and token to another program makes it exponentially more likely to expire, and these are the only methods that use the code you have linked.

If you are handing off handling to a different process, doesn't it need more than just the id and token, such as what options were passed? And sharding does affect which process interactions go to, so it is already designed to be scalable.

The majority of the interaction API can be consumed via a WebhookClient (which is actually what it does internally anyways) which can be constructed using the application (client in most cases) id and the token.

Client#api is intentionally private, and I believe that is highly unlikely to change.

Side note: Storing interaction ids and tokens in a database seems like a waste to me, they are only valid for 15 minutes anyways.

**Comment by Noah-Huppert** [comment]
> > This is convenient because the program that receives a new interaction doesn't necessarily have to be the program responding to the interaction. As the receiving program can always share the interaction ID and token, and let someone else take care of it.
> 
> The reply and defer options must be called within 3 seconds of receiving the interaction which means sending the id and token to another program makes it exponentially more likely to expire, and these are the only methods that use the code you have linked.
> 
> If you are handing off handling to a different process, doesn't it need more than just the id and token, such as what options were passed? And sharding does affect which process interactions go to, so it is already designed to be scalable.
> 
> The majority of the interaction API can be consumed via a WebhookClient (which is actually what it does internally anyways) which can be constructed using the application (client in most cases) id and the token.
> 
> Client#api is intentionally private, and I believe that is highly unlikely to change.
> 
> Side note: Storing interaction ids and tokens in a database seems like a waste to me, they are only valid for 15 minutes anyways.

Thanks for your reply.

I think your comment addresses the question of: if splitting the receiving and replying processes is a good idea. I'm happy to make a case for why this might be necessary and the correct decision in an application design (as it is in the one I am building) but I think that would distract from the feature I am requesting (Checkout the first edit version of my issue request, I tried addressing this but ending up removing it in order to get straight to the point).

I think one of the main points I was trying to make with this feature request is that the HTTP API for interactions allows you to do this, and only requires that a caller have the ID and token. But the current Discord.Js API does not allow the API to be used like this, and I think it would be very helpful if it did.

As for the point about needing to respond or defer within 3 seconds. This is fine, for my cases I send an initial reply saying "loading..." and then when the background work is complete I update the interaction by editing my reply. So the handoff between the two processes doesn't have to occur within 3 seconds, but instead within the normal 15 minute window.

Sure `Client#api` might be private, but I think an ideal solution would be to make a public wrapper around this private field (Very similar to how `CommandInteraction` is a wrapper around `Client#api`). `Client#api` being private is not a reason to never expose any functionality which `Client#api` provides via other helpers. If this was the case then nothing in the Discord.Js would be able to function.

**Comment by Noah-Huppert** [comment]
> I think one of the main points I was trying to make with this feature request is that the HTTP API for interactions allows you to invoke it only knowing the interaction ID and token. But the current Discord.Js API does not allow the API to be used like this, and I think it would be very helpful if it did.

Just elaborating a bit here. The Discord.Js SDK is great because I never have to interact with the Discord HTTP directly. However due to a feature gap (which would be fullfilled by this feature request) it is not possible to send a followup or edit an existing reply if you only have the interaction ID and token. So you have to make a direct HTTP call instead of using the Discord.Js SDK. Whether the designers of the HTTP interactions API intended this to allow bots to split work up across processes or not, having this ability in the Discord.Js SDK would be nice.

**Comment by ckohen** [comment]
Great, so your application replies with a loading state (you should probably use defer) which means that this point I made:
> The majority of the interaction API can be consumed via a WebhookClient (which is actually what it does internally anyways) which can be constructed using the application (client in most cases) id and the token.

already covers your use case.

> Sure Client#api might be private, but I think an ideal solution would be to make a public wrapper around this private field (Very similar to how CommandInteraction is a wrapper around Client#api). Client#api being private is not a reason to never expose any functionality which Client#api provides via other helpers. If this was the case then nothing in the Discord.Js would be able to function.

The majority of the library is a wrapper around this, (the rest is a wrapper around a websocket) that's sort of the point.

**Comment by Noah-Huppert** [comment]
> The majority of the interaction API can be consumed via a WebhookClient (which is actually what it does internally anyways) which can be constructed using the application (client in most cases) id and the token.

Oh cool. Sorry this point must have been lost on me. Apologies on my part there. This sounds perfectly ideal, and I agree about your point with the whole Discord.Js SDK being one big wrapper for the private API client.

>  (you should probably use defer) 

dude... please we all have our reasons to do different things. Is it really worth trying to flame me for this? If you must know it's because I'm interacting with other 3rd party services in my interaction and my loading message shows the current state of that resource, which is a better loading message than 3 spinning dots.

**Comment by Noah-Huppert** [comment]
It sounds like the need for this sort of feature is already filled by the WebsocketClient.

**Comment by ckohen** [comment]
It was a suggestion (hence probably), not trying to flame you for it, you have a valid reason not to use it. Sorry if it came off a little strong.

Glad to be of help
