### ISSUE TITLE
<Guild.shard> is undefined

### ISSUE THREAD

**Issue by inhydrox** [discordjs/discord.js#5648]
Hey from the past few days I have noticed that `<Guild>.shard` is undefined on few servers of my bot, sometimes it got fixed when the bot was kicked and invited again, but on some servers, this thing is not working, the <Guild>.shardID is defined but not <Guild>.shard

- discord.js version: 12.5.1
- Node.js version: 12.16.1
- Operating system: Ubuntu 18.04
- Priority this issue should have – very high

**Relevant client options:**

```js
      partials: [
        'MESSAGE',
        'USER',
        'GUILD_MEMBER',
        'REACTION',
        'CHANNEL'
        ],
        ws: {
          intents: [
            'GUILDS',
            'GUILD_MEMBERS',
            'GUILD_VOICE_STATES',
            'GUILD_MESSAGES',
            'GUILD_MESSAGE_REACTIONS',
            ],
          },
```

**Comment by monbrey** [comment]
Are you manually fetching guilds anywhere by any chance? `guild.shard` is only populated when the guild data is received via websocket, not from the API

**Comment by inhydrox** [comment]
Nvm it was my sharding issue
