### ISSUE TITLE
Add two "!" to a bot status on mobile

### ISSUE THREAD

**Issue by zechaos031** [discordjs/discord.js#5650]
Hello, I noticed that my bot had a bug on its status discord

Indeed no matter the status I put it it adds two "!" at the beginning of the status, I notice that this bug on phone and that on my bot. Anyone have an idea where this could come from

I don't really know where to post the porblem, I made a ticket to discord support too

```js
//On event Handler
module.exports =  async (client) => {
    await client.user.setPresence({
        activity: {
            name: `${client.config.prefix}help `,
            type: "LISTENING"
        }
    }).then(() => client.logger.info(`[${client.user.username}] Status set !`));
};
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 14.15.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by zechaos031** [comment]
<img src="https://cdn.discordapp.com/attachments/505075043815129090/844502880278151198/Screenshot_2021-05-19-10-55-10-603_com.discord.jpg" width="352" height="650"></img>

<img src="https://cdn.discordapp.com/attachments/721412864686030898/844508361445474304/unknown.png"></img>

**Comment by adrifcastr** [comment]
That is a bug in an old version of the android client. Does not have anything to do with the lib. Update your client.

**Comment by zechaos031** [comment]
I just updated the client and I still have the bug

**Comment by vladfrangu** [comment]
We do not alter what you pass in as the activity name anywhere. The extra prefix/suffix of `!!` is related to Discord's way of doing i18n. Nothing we can do about this at the library level, you should report it on https://dis.gd/bugreport or on the [Discord Testers](https://discord.gg/discord-testers). If you see the `!!` in the presence data discord.js gives you, please mention this here and we'll reopen the issue for you! :D
