### ISSUE TITLE
Collection#find() not being a thing

### ISSUE THREAD

**Issue by xAtsuUC** [discordjs/discord.js#5652]
![image](https://user-images.githubusercontent.com/67171928/118915278-0bdceb00-b903-11eb-8e35-625ee7b220e8.png)

**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

Sample 1:
```js
Structures.extend("GuildMember", GuildMember => {
    class ArkaMember extends GuildMember {
        constructor(client, data, guild) {
            super(client, data, guild)
        }
        isDJ(message: Message):boolean {
            return (this.roles.cache.find(r => r.name === 'DJ')) ? true : message.member.permissions.has("MANAGE_CHANNELS", true)
        }
    }
    return ArkaMember;
})
```

Sample 2:
Error: Property 'first' does not exist on type 'Collection<string, MessageReaction>'.
```js
m.awaitReactions((reaction, user) => (reaction.emoji.name === '❌' || reaction.emoji.name === '✅') && user.id === message.member.id, { time: 15000, errors: ['time'], max: 1 }).then(async collected => {
            if(collected?.first().emoji.name === '❌') return message.channel.send(new MessageEmbed().setDescription('❌ Comando cancelado'))
            if(collected?.first().emoji.name === '✅') { 
                const suc = await message.channel.send(new MessageEmbed().setDescription('En progreso...'))
```

**Further details:**

- discord.js version: master/c8d20a456b635ce6081ed8ad17315a9a0c0244bc
- Node.js version: v14.15.3
- Operating system: Microsoft Windows 10 Home Single Language 10.0.19042
- Priority this issue should have – please be realistic and elaborate if possible: Medium, this issue wont really affect JavaScript users but won't let compile TypeScript users

**Relevant client options:**

- partials: ["USER", "CHANNEL", "GUILD_MEMBER", "MESSAGE", "REACTION"]
- gateway intents: Discord.Intents.ALL
- other: I don't think this is really relevant, but yeah

Remove the comment and fill out the commit hash if this applies to you:
(While it's not a requirement to test your issue on the master branch, it would make fixing the problem a lot easier for us, so please do so if possible.)

- I have also tested the issue on latest master, commit hash: `c8d20a456b635ce6081ed8ad17315a9a0c0244bc`

**Comment by SpaceEEC** [comment]
I don't see why this would be happening.
Can you check what version of `@discordjs/collection` you have installed?
What does the file `node_modules/@discordjs/collection/dist/index.d.ts` look like?
The declaration for the `find` method should be in there.

**Comment by xAtsuUC** [comment]
Yeah, when I was looking the collection files i found out that there was no files (only license, package and readme) kinda weird, but I just re-installed it and now it works, thanks!
