### ISSUE TITLE
Message: integrate multiple reactions for Message#react

### ISSUE THREAD

**Issue by khiromoshito** [discordjs/discord.js#5653]
**Is your feature request related to a problem? Please describe.**
No, but this is an initiative to make message reacting general for either single or multiple reactions.
This is the draft I wrote in `Message.js`:

![image](https://user-images.githubusercontent.com/66996948/118921368-a0c6ff00-b96a-11eb-815b-1c3c976e195c.png)

The original `Message#react` for single reaction has been renamed to `Message#_react` (perhaps made private since this change supports 1 or more arguments).

Hope this makes to the cut : )

**Comment by tipakA** [comment]
#4752 seems related here (specifically [this comment](https://github.com/discordjs/discord.js/issues/4752#issuecomment-682444480))

**Comment by khiromoshito** [comment]
> #4752 seems related here (specifically [this comment](https://github.com/discordjs/discord.js/issues/4752#issuecomment-682444480))

I see, thanks for the reference.
