### ISSUE TITLE
Reaction roles BuG

### ISSUE THREAD

**Issue by Nigelrex** [discordjs/discord.js#5654]
##Use Discord for questions: https://discord.gg/bRCvFy9
your discord server doesn't even help me they keep saying not related to discord.js or they say i cannot spoon feed or blah blah
**Please describe the problem you are having in as much detail as possible:**
The code is exactly correct from all the tutorials i have seen but the client doesn't even see that and if i react to the message i don't get the roles
**Include a reproducible code sample here, if possible:**

```js
const config = require("../../config.json");

module.exports = {
  async execute(message, args, client) {
    client.on("messageReactionAdd", async (reaction, user) => {
      if (reaction.message.partials) await reaction.message.fetch();
      if (reaction.partial) await reaction.fetch();
      if (user.bot) return;
      if (!reaction.message.guild) return;

      const rchannel = config.rulesChannel;
      const membersrole = config.memberrole;
      const tickemoji = "✅";

      if (reaction.message.channel.id === rchannel) {
        console.log("Logging Something");
        if (reaction.emoji.name === tickemoji) {
          await reaction.message.guild.members.cache
            .get(user.id)
            .roles.add(membersrole);
        }
      } else {
        return;
      }
    });
  },
};

```

**Further details:**

- discord.js version: v12
- Node.js version: v13.14.0
- Operating system: Windows 7
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: ALL
- gateway intents: ALL
- other: none

**Comment by vBread** [comment]
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by Nigelrex** [comment]
Wtf your discord server help channel is a trash and the members are a total trash they are just being soo lazy to help people
