### ISSUE TITLE
Discordjs logic in fetchRecommendedShards doesn't account for large bot sharding when not using the default 1000 servers per shard

### ISSUE THREAD

**Issue by scottbucher** [discordjs/discord.js#5672]
**Please describe the problem you are having in as much detail as possible:**
Essentially, Util.fetchRecommendedShards doesn't take into account large bot sharding. 

![image](https://user-images.githubusercontent.com/47844014/119564851-3ac9e580-bd77-11eb-90f5-74adcbd8982d.png)
[Link to code](https://github.com/discordjs/discord.js/blob/3ac6d550caf1a3490f648899f112488ee3a7095b/src/util/Util.js#L250)

For large bots (over 150,000 servers) discord requires the number of shards to be a multiple of 16, so, when fetching the recommended shard count, discord.js doesn't account for this. It *happens* to work if you leave the guildsPerShard at the default 1000 because discord is auto-rounding to the nearest 16, but if you choose something other than 1000 per shard, discord.js's logic doesn't account for it.

For instance, with my bot, Birthday Bot, I have roughly 167,000 servers, and when doing 2,500 servers per shard I fetch the recommended shard count and receive back 71, however, when I use this, discord sends back that it is invalid sharding settings since 71 isn't a multiple of 16. If I default to the 1000 servers per shard it will return 176, which is a multiple of 16, and thus, works.

**Include a reproducible code sample here, if possible:**

```js
let recommendedShards = await Util.fetchRecommendedShards(MY_BOT_TOKEN, 2500);
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 15.5.1
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by meister03** [comment]
@scottbucher | Encountered the same issue. Why dont you divide the recommended Shards with 2?
Then you have the Shard Count for 2000 guilds

**Comment by KevinNovak** [comment]
Recommended Shards would be rounded to a multiple of 16 for large bots, so dividing by 2 could potentially NOT be a multiple of 16.

Ex: discord recommends 48 (3 x 16) shards. 48 / 2 = 24. 24 is not a multiple of 16 and then the bot would not be able to start.

**Comment by vladfrangu** [comment]
Sadly, we cannot detect the bot's guild cound beforehand, to account for the multiple of 16 limit for shards. We can *guesstimate* it by checking if it's >= 150, and then have other logic around it, which is probably what we'll do 👍

**Comment by scottbucher** [comment]
> Sadly, we cannot detect the bot's guild cound beforehand, to account for the multiple of 16 limit for shards. We can _guesstimate_ it by checking if it's >= 150, and then have other logic around it, which is probably what we'll do 👍

I was thinking maybe just add an optional value to fetchRecommendedShards for the user to decide. 
For instance:
fetchRecommendedShards(token, guildsPerShard, useLargeBotSharding)

Either that or through a ShardingOptions object like:
```
{
  guildsPerShard: number,
  largeBotSharding: boolean
}
```
Which would change it to `fetchRecommendedShards(token, options)` with options defaulting to 1000 guilds per shard and false for large bot sharding.

**Comment by DraftProducts** [comment]
I don't see any PR for this stuff, is it being considered or just waiting for someone to do it?

**Comment by kyranet** [comment]
Waiting for someone to do it, feel free to reach us at `#library-discussion` and propose your approach.

**Comment by scottbucher** [comment]
Sorry I've been busy, going to work on this today.

**Comment by DraftProducts** [comment]
Okay, nice!
