### ISSUE TITLE
button label bug on discord.js master

### ISSUE THREAD

**Issue by BliiTzZ** [discordjs/discord.js#5675]
Hello, there is a problem with the button labels. Normally, the label of a button is not obligatory and one is not obliged to fill the label, in order to have an empty button. Except that on Discord.js the label is required and causes an error "data.components [0] .components [0] .label: This field is required" if we don't put a label when it shouldn't.

This therefore creates a bug when you want to put a custom emoji in the button without putting a label.

```js
client.ws.on('INTERACTION_CREATE', async interaction => {
  client.api.interactions(interaction.id, interaction.token).callback.post({
    data: {
      type: 4,
      data: {
      flags: 64,
      content: "Hello",
        components: [{
	  type: 1
	  components: [{ type: 2, custom_id: 1, style: 1, emoji: { name: "emoji_name", id: "emoji_id" } }]
        }]
      }
    }
  });
});
```

**Further details:**

- discord.js version: Master branch
- Priority: average

**Comment by iCrawl** [comment]
`client.api` is private and not supported.

**Comment by Keke27210** [comment]
Buttons are not out yet, and you are sending raw data to Discord.
The error comes from Discord, not discord.js.
Also no support is provided for `Client#api` as this is a private set of methods you shouldn't be using.
Wait for the official buttons implementation.

**Comment by BliiTzZ** [comment]
Alright I didn't know, excuse me

**Comment by BliiTzZ** [comment]
However he put me an error in discord.js like here:
https://media.discordapp.net/attachments/832641085980409929/847067498728652850/unknown.png

that's why I thought it was a discord.js problemdiscord.js
