### ISSUE TITLE
TypeScript project fails compiling with discord.js master

### ISSUE THREAD

**Issue by KevinNovak** [discordjs/discord.js#5680]
**Please describe the problem you are having in as much detail as possible:**
Using the latest discord.js master (#840ad0a), with a barebones bot setup (just a ping/pong, like the example on the library home page), when I run `tsc` to compile the project with the TypeScript compiler, I get the following error:

> Cannot find module 'discord-api-types/v8' or its corresponding type declarations.

![image](https://user-images.githubusercontent.com/11231402/119740082-425dbd00-be51-11eb-96b2-8ca366b49d2f.png)

Looking at discord.js's index.d.ts file, the following is underlined:
![image](https://user-images.githubusercontent.com/11231402/119740166-691bf380-be51-11eb-929a-13ae155f3ae1.png)

This does not happen with the stable branch (12.5.3).

**Include a reproducible code sample here, if possible:**

I just used essentially the same example on the homepage:

```typescript
import Discord from "discord.js";
const client = new Discord.Client({
    intents: ["GUILDS", "GUILD_MESSAGES"],
});

client.on("ready", () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.on("message", (msg) => {
    if (msg.content === "ping") {
        msg.reply("Pong!");
    }
});

client.login("MY_BOT_TOKEN");
```

With the following discord.js package:
`"discord.js": "github:discordjs/discord.js#840ad0a"`

**Further details:**

- discord.js version: master, github:discordjs/discord.js#840ad0a
- Node.js version: 15.12.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium, this might affect any typescript bot.

**Comment by vladfrangu** [comment]
Not a bug; enable `skipLibCheck` in your tsconfig or install the dependency yourself. 😁

**Comment by KevinNovak** [comment]
> Not a bug; enable `skipLibCheck` in your tsconfig or install the dependency yourself. 😁

Thank you!
