### ISSUE TITLE
Typings issue

### ISSUE THREAD

**Issue by callumok2004** [discordjs/discord.js#5684]
**Details:**

- discord.js version: 12.5.3
- Priority this issue should have: Low
- Issue: Image Below
- ![image](https://user-images.githubusercontent.com/35779365/119860547-56b3bf80-bf0e-11eb-9265-fa8fd553d39d.png)

**Comment by iCrawl** [comment]
Cannot reproduce.

**Comment by muhimur9049** [comment]
> Cannot reproduce.

I was able to reproduce this. I saw this in the past too but I wasn't too sure if this was the same thing or not, but here:
![image](https://user-images.githubusercontent.com/52611945/120416240-d4226a00-c32a-11eb-8dad-27efff4aac19.png)
![image](https://user-images.githubusercontent.com/52611945/120416255-dc7aa500-c32a-11eb-8821-4164bd4a85c3.png)

**Comment by iShibi** [comment]
That's coming from `deepscan`
