### ISSUE TITLE
guildMemberUpdate not fired for uncached members

### ISSUE THREAD

**Issue by nathanctech** [discordjs/discord.js#5685]
**Please describe the problem you are having in as much detail as possible:**

When the bot first starts up, the first update to a guild member (which should fire `guildMemberUpdate`) does not happen. Subsequent updates do trigger the event. 

Reproduction steps:

1) Start the bot
2) Change a role of a member and observe the event not being fired
3) Change another role, observe the event being fired successfully

The event will also fire if the user sends a message or otherwise takes an action that causes the member to be known to the bot and cached.

**Include a reproducible code sample here, if possible:**

```js
client.on("guildMemberUpdate", async function(oldMember, newMember) {
    console.log(`Hello, event was fired!`);
})
```

**Further details:**

- discord.js version: 13.0.0#b90b0c3cfa2278caa38d1ff41eef2ccf4428b99e
- Node.js version: 16.2.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Unsure if intentional or not, but if intentional this is changed behavior from v12 and should be noted.

**Relevant client options:**

- partials: MESSAGE, CHANNEL, REACTION
- gateway intents: GUILD_MEMBERS
- other: none

- I have also tested the issue on latest master, commit hash: `b90b0c3cfa2278caa38d1ff41eef2ccf4428b99e`

**Comment by nathanctech** [comment]
So I feel kind of silly for missing this, but you just need the `GUILD_MEMBER` partial when initializing the client. This is likely just a documentation issue more than anything else.

**Comment by iCrawl** [comment]
Such things are usually handled within the guide.
