### ISSUE TITLE
I get a typescript type error when updating the permissions of a role

### ISSUE THREAD

**Issue by kaname-png** [discordjs/discord.js#5686]
**Please describe the problem you are having in as much detail as possible:**
I can't update role permissions because the typing is wrong

**Include a reproducible code sample here, if possible:**
```js
await (channel as TextChannel).updateOverwrite(role, { deny: ['SEND_MESSAGES', 'ADD_REACTIONS'], allow: [], id: role }).catch(() => null);
```

> Error
```bash
[27/5/2021] » BOT ×  ERROR     ⨯ Unable to compile TypeScript:
src/bot/commands/public/moderation/mute.command.ts:144:68 - error TS2345: Argument of type '{ deny: string[]; allow: undefined[]; id: Role; }' is not assignable to parameter of type 'PermissionOverwriteOptions'.
  Object literal may only specify known properties, and 'deny' does not exist in type 'PermissionOverwriteOptions'.

144             await (channel as TextChannel).updateOverwrite(role, { deny: ['SEND_MESSAGES', 'ADD_REACTIONS'], allow: [], id: role }).catch(() => null);
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

> No typing errors in vs code

![image](https://user-images.githubusercontent.com/56084970/119885582-40e2d200-beef-11eb-9b1b-c01807be0a23.png)

**Further details:**

- discord.js version: master
- Node.js version: 14.17.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Normal

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by almostSouji** [comment]
Not a bug, you don't provide what's expected, as per the error<https://discord.js.org/#/docs/main/master/typedef/PermissionOverwriteOptions>

<https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=updateOverwrite>
<https://discord.js.org/#/docs/main/master/typedef/PermissionOverwriteOptions>

**Comment by kaname-png** [comment]
> Not a bug, you don't provide what's expected, as per the error, see:
> 
> https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=updateOverwrite
> https://discord.js.org/#/docs/main/master/typedef/PermissionOverwriteOptions
> 
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

I cannot do it this way because the `deny`, `allow` and `id` fields are mandatory according to the typescript types.

![image](https://user-images.githubusercontent.com/56084970/119886628-64f2e300-bef0-11eb-9385-30061d2d4a88.png)

```bash
An argument of type "{ SEND_MESSAGES: false; ADD_REACTIONS: false; }" cannot be assigned to the parameter of type "PermissionOverwriteOptions".
  The type "{ SEND_MESSAGES: false; ADD_REACTIONS: false; }" is missing the following properties of the type "PermissionOverwriteOptions": allow, deny, id
```

**Comment by almostSouji** [comment]
I'm not too sure what you are doing here, I can not reproduce this issue at all on b90b0c3cfa2278caa38d1ff41eef2ccf4428b99e

```ts
if (message.channel.type !== 'text') return;
message.channel.updateOverwrite('123', { SEND_MESSAGES: false, VIEW_CHANNEL: true }, { reason: 'needed to be changed' }).catch(() => null);
```

**Comment by monbrey** [comment]
Resolved in the server - the error was coming from a third-party package with discord.js as a dependency, likely installing an outdated version with clashing typings.
