### ISSUE TITLE
[v13] DMs not being emitted by the message event (w/intents)

### ISSUE THREAD

**Issue by tandpfun** [discordjs/discord.js#5687]
**Please describe the problem you are having in as much detail as possible:**
In v13, DMs aren't emitting the message event even with the `DIRECT_MESSAGES` intent.

**Include a reproducible code sample here, if possible:**

```js
const intents = [
    'GUILDS',
    'GUILD_MEMBERS',
    'GUILD_VOICE_STATES',
    'GUILD_MESSAGES',
    'GUILD_MESSAGE_REACTIONS',
    'GUILD_WEBHOOKS',
    'GUILD_EMOJIS',
    'DIRECT_MESSAGES',
  ],

const client = new Discord.Client(
  {
    allowedMentions: { parse: ['users'] },
    intents: intents,
  },
);

client.on('message', (message) => {
console.log(message.channel.type) // Doesn't log when DMed
})

// Login and do all that stuff
```

**Further details:**

- discord.js version: 13.0.0-dev
- Node.js version: v14.16.1
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents:  'GUILDS', 'GUILD_MEMBERS', 'GUILD_VOICE_STATES', 'GUILD_MESSAGES', 'GUILD_MESSAGE_REACTIONS' 'GUILD_WEBHOOKS', 'GUILD_EMOJIS', 'DIRECT_MESSAGES',
- other: none

**Comment by adrifcastr** [comment]
Gateway v8 does not emit `CHANNEL_CREATE` for DMs anymore, you are required to set the `CHANNEL` partial in your ClientOptions.

**Comment by tandpfun** [comment]
Thank you!
