### ISSUE TITLE
Unable to ephemerally reply with a MessageEmbed to a CommandInteraction

### ISSUE THREAD

**Issue by XECortex** [discordjs/discord.js#5703]
I wanted that my bot replies with an ephemeral embed that contains an error message when a member used a slash command incorrectly. But instead of an embed, the bot literally replied with `[object Object]`. So I wondered if I was doing anything wrong, but after playing around a bit, I came to following conclusion:
```js
const embed = new Discord.MessageEmbed().setTitle("I am an embed!");

// This does work, of course
interaction.reply("Hello everyone!");
interaction.reply("Hello user!", { ephemeral: true });

// This does work aswell
interaction.reply(embed);

// This does NOT work
// -> Results in an ephemeral reply with content "[object Object]"
interaction.reply(embed, { ephemeral: true });

// Workaround I use right now
interaction.defer({ ephemeral: true });
interaction.editReply(embed); 
```

I don't know if this is a bug inside discord.js or a Discord API bug / limitation

**Further details:**
- discord.js version: **master**
- Node.js version: **16.2.0**
- Operating system: **Artix Linux**
- Priority this issue should have: **medium**

**Comment by adrifcastr** [comment]
This is merely related to you not reading the documentation. (embed, options) is not a valid overload. Either (content, options) or just (options).

You pass your array of embeds to the `embeds` option, and also specify the `ephemeral` option if you want to make it ephemeral.

**Comment by XECortex** [comment]
Sorry, I didn't look at the docs before writing this issue, they got updated just two hours erlier
