### ISSUE TITLE
`client.user.setStatus();` kills the bot (INVALID SESSION)

### ISSUE THREAD

**Issue by XECortex** [discordjs/discord.js#5706]
**Please describe the problem you are having in as much detail as possible:**
Whenever I use `client.user.setStatus('idle');` (idle for example), the bot **stops responding and goes offline** after a minute. The console does **not log any errors:**

![image](https://user-images.githubusercontent.com/57626963/120113128-92e25c80-c168-11eb-8e4f-5e30beb5255e.png)

Code of the command:
```js
case "status":
	const status = interaction.options[0].options[0].value; 

	client.user.setStatus(status);
	interaction.reply(`Status was set to **${status}**`, { ephemeral: true });
	break;
```

**Further details:**
- discord.js version: #03256bd9
- Node.js version: **16.2.0**
- Operating system: **Artix Linux**

**Relevant client options:**
- gateway intents: **GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS**

**Comment by XECortex** [comment]
Trycatch wouldn't work btw because `.setStatus()` returns a `Presence`-Object, not a `Promise`

**Comment by SpaceEEC** [comment]
What's the output you are seeing when logging the debug event? `client.on('debug', console.log);`

**Comment by XECortex** [comment]
```
Client logged in as USER#1234
CORTƎX#6890 used command "presence"
```
_10 seconds of nothing..._
`[WS => Shard 0] [INVALID SESSION] Resumable: false.`

**Comment by XECortex** [comment]
Looks like #5584 is the same bug

**Comment by XECortex** [comment]
`setPresence({ status: 'online' })` causes the same problem
