### ISSUE TITLE
option for interaction type MESSAGE_COMPONENT

### ISSUE THREAD

**Issue by MarzonDark** [discordjs/discord.js#5709]
Hello. I would like you to add **.options** to **<MESSAGE_INTERACTION>.message.interaction**

Thanks.

**Comment by XECortex** [comment]
There are already PRs for the new “Message Components“ (#5674 and #5692)

**Comment by MarzonDark** [comment]
@XECortex I mean, I would like there to be that property because that way I can get the command arguments
