### ISSUE TITLE
Find out if a user moves another channel user

### ISSUE THREAD

**Issue by jaovito** [discordjs/discord.js#5715]
Add a function to find out if a user moves another channel user, I want to check these users and ban them if they move other users on other channels too many times.

I search in documentation but not find how.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
