### ISSUE TITLE
Ratelimit

### ISSUE THREAD

**Issue by jc-discdev** [discordjs/discord.js#5719]
Hi, I would like to know if it's possible to make my bot restart if it hits ratelimit, I mean, stay 5 minutes off and then start again. Can someone send me how? Thanks. Also I would like to log when it does that.

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.**
