### ISSUE TITLE
Invalid Form Body

### ISSUE THREAD

**Issue by thunder-19** [discordjs/discord.js#5724]
```js
DiscordAPIError: Invalid Form Body
embed.author.url: Scheme "88000" is not supported. Scheme must be one of ('http', 'https').
```

I get this issue when I try to play something on my bot.

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
