### ISSUE TITLE
Both

### ISSUE THREAD

**Issue by Mshary99** [discordjs/discord.js#5728]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Mshary99** [comment]
Token= ODQ5MTQ3NjgxNDMwNTY4OTYx.YLW8Zw.q1jK8tSmrHX1Ed7gQ6r1IoPw9xo

**Comment by vBread** [comment]
Please do not share your token. Regenerate it in the dev portal.

---

> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
