### ISSUE TITLE
About Status

### ISSUE THREAD

**Issue by BorakanTunaboyu** [discordjs/discord.js#5735]
When you start the bot and set the bot's status on start, it deletes in 1-2 days but bot still works as normal. When you reset the bot, it came back again.

**Comment by tipakA** [comment]
Disappearing of status after a long while is normal due how how discord handles long lasting connections. You can mitigate that by periodically setting the status again.

**Comment by almostSouji** [comment]
This has to do with how discord handles presence updates in their infrastructure, nothing we can change as a library (I suppose we could start interval-setting, however would much prefer to leave that decision to the developer instead)
