### ISSUE TITLE
Adding the ability to use the class as a string

### ISSUE THREAD

**Issue by Syjalo** [discordjs/discord.js#5743]
**Is your feature request related to a problem? Please describe.**
I can't use a class that has the `toString()` prototype as a string.

**Describe the ideal solution**
I want to ask to add the ability to use classes that has the `toString()` prototype as a string

**Additional context**
This is additional feature to the `verifyString` function (#4880)

**Comment by Syjalo** [comment]
For example:
If I use the `GuildMember` class in the `MessageEmbed.setDescription()` function, I get an `RangeError: EMBED_DESCRIPTION` error.
```JS
const Discord = require('discord.js')
const embed = new Discord.MessageEmbed()
embed.setDescription(message.member)
message.channel.send(embed)
```

**Comment by Keke27210** [comment]
iirc, string enforcement (https://github.com/discordjs/discord.js/pull/4880) has been done to prevent ambiguities like these.
You've got to call `.toString()` yourself.

**Comment by killer069** [comment]
> For example:
> If I use the `GuildMember` class in the `MessageEmbed.setDescription()` function, I get `RangeError: EMBED_DESCRIPTION` error.
> 
> ```js
> const Discord = require('discord.js')
> const embed = new Discord.MessageEmbed()
> embed.setDescription(message.member)
> message.channel.send(embed)
> ```

Just change this 
```js
embed.setDescription(message.member)
```
TO
```js
embed.setDescription(`${message.member}`)
```

**Comment by monbrey** [comment]
The reason we don't want to do this is because you can stringify pretty much everything, which results in the `[object Object]` output you've probably seen.

**Comment by Syjalo** [comment]
Ok, thank you.
