### ISSUE TITLE
Interaction#componentType

### ISSUE THREAD

**Issue by ToasterSticks** [discordjs/discord.js#5751]
**Please describe the problem you are having in as much detail as possible:** The guide says to check `if (!interaction.isMessageComponent() && interaction.componentType !== 'BUTTON') return;` while listening for buttons, however there are no typings for `Interaction#componentType`

**Include a reproducible code sample here, if possible:** ![image](https://user-images.githubusercontent.com/64027609/120864751-b5a2b580-c55a-11eb-946f-0c9587cddcfd.png)

```js
// Place your code here
```

**Further details:**

- discord.js version: Dev Branch cbd7f2b9aa44a9240947ed716d0e72257ac499f7 
- Node.js version: 14.0
- Operating system: Ubuntu 20
- Priority this issue should have – please be realistic and elaborate if possible: Medium, as it may be required to distinguish between buttons and (?)

**Relevant client options:**

- partials: All
- gateway intents: All
- other: none

 cbd7f2b9aa44a9240947ed716d0e72257ac499f7

**Comment by monbrey** [comment]
Fixed in #5692

**Comment by ImRodry** [comment]
@monbrey that PR will still take a long time to be merged, shouldn't this be fixed in a separate, smaller, PR?

**Comment by monbrey** [comment]
There is only one component type that can be interacted with until the next PR, but since this is fixed now anyway all good.

**Comment by ImRodry** [comment]
Aren't there 2? BUTTON and ACTION_ROW?

**Comment by monbrey** [comment]
Two components yes, but only one you can receive interactions from.
