### ISSUE TITLE
MessageButton#emoji throws invalid form body error

### ISSUE THREAD

**Issue by letterjm** [discordjs/discord.js#5753]
**Please describe the problem you are having in as much detail as possible:**
While passing in options directly when creating a new button, including an emoji value throws an 'Invalid form body error' (full error provided below). Tested against both a Unicode emoji and a valid guild emoji identifier string.

Using .setEmoji() instead with the same input works just fine.

**Include a reproducible code sample here, if possible:**

```js
 const row = new Discord.MessageActionRow()
            .addComponents([
                new Discord.MessageButton({
                    customID: 'test',
                    emoji: '🥟',
                    style: 'SECONDARY'
                })
            ])

        message.channel.send('test', {
            components: [row]
        })
```

Error:
```
DiscordAPIError: Invalid Form Body
components[0].components[0].emoji: Only dictionaries may be used in a ModelType
    at RequestHandler.execute (C:\Users\me\Documents\Visual Studio Code\test_bot\node_modules\discord.js\src\rest\RequestHandler.js:243:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (C:\Users\me\Documents\Visual Studio Code\test_bot\node_modules\discord.js\src\rest\RequestHandler.js:49:14)
```

**Further details:**

- discord.js version: master - commit #5674
- Node.js version: 14.17.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Moderate/low, since this caters to a very specific use case and the method outlined in the draft guide works just fine.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
MessageButtonOptions#emoji does not accept a string. The correct way to pass this in the constructor would be `emoji: { name: '🥟' }`

`#setEmoji` will do resolution as you pointed out.

**Comment by letterjm** [comment]
Oh alright, that makes sense! In the docs it does say that the MessageButton#emoji can be an Emoji or a string. Could this maybe be clarified?

**Comment by almostSouji** [comment]
well, that's the return value of the attribute, not the constructor parameter, which builds from "raw" data

**Comment by monbrey** [comment]
> well, that's the return value of the attribute, not the constructor parameter, which builds from "rawish" data

Yes, but technically still incorrect, should never be a string.

**Comment by GravityCollision** [comment]
For anyone who is having this issue, please Copy / Paste Emoji's into the IDE.
https://getemoji.com/

**Comment by grassehh** [comment]
I think Discord API shouldn't throw an error when emoji is invalid, but instead just put no emoji.
