### ISSUE TITLE
Typing issue: MessageComponentInteraction#defer

### ISSUE THREAD

**Issue by nununoisy** [discordjs/discord.js#5759]
**Please describe the problem you are having in as much detail as possible:**
The typings for `MessageComponentInteraction#defer` are incorrect.

**Include a reproducible code sample here, if possible:**

```ts
// Typing (`typings/index.d.ts:1336`):
public defer(ephemeral?: boolean | undefined) : Promise<void>;
// Calling like this does not result in an ephemeral reply:
let interaction: MessageComponentInteraction; // ...
interaction.defer(true);
// But this does:
//@ts-ignore
interaction.defer({ephemeral: true});
// Possible alternate typing that matches the API:
public defer(options?: InteractionDeferOptions) : Promise<void>;
// I would open a PR but I am not sure if this is the correct typing, it just works for me
```

**Further details:**

- discord.js version: discord.js master branch
- Node.js version: 14.17.0
- Operating system: Debian GNU/Linux
- Priority this issue should have – please be realistic and elaborate if possible:
Low, it is not a huge issue but it requires a typing override or `//@ts-ignore` on typescript

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none
- I have also tested the issue on latest master, commit hash: `f7e420b`

**Comment by iShibi** [comment]
yup, you're correct. The typings should be just like `CommandInteraction#defer`. You can open a PR and fix it 👍
