### ISSUE TITLE
Discord error when calling msg.edit

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [discordjs/discord.js#5772]
When calling message.edit,it returns the error "cannot edit messages sent by another user - api error, when it should just edit the bots last message

```js
msg.channel.send('hi') 
msg.edit('e')
```

- discord.js version: 12.5.2
- Node.js version: 12 
- Operating system: Linux x86 
- Priority this issue should have – please be realistic and elaborate if possible: medium 

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- I have also tested the issue on latest master, commit hash: `I tested on 12.5.2`

**Comment by vladfrangu** [comment]
**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
