### ISSUE TITLE
Use Template String Literal Type for `ApplicationCommandData.name`

### ISSUE THREAD

**Issue by suneettipirneni** [discordjs/discord.js#5814]
**Is your feature request related to a problem? Please describe.**

The discord API outlines the requirements of slash command names:
> **Command names must be lower-case** and match the regular expression `^[\w-]{1,32}$`. Commands (including sub-commands) with upper- or mixed- case names will be rejected by the API with a HTTP 400 (Bad Request) response.

It would be nice if this was type checked beforehand, to prevent invalid request errors later.

**Describe the ideal solution**

Template string literals could be used to enforce the format of the string.

**Describe alternatives you've considered**

Runtime regex assertions, but that's runtime.

**Comment by monbrey** [comment]
I don't believe TypeScript supports regular expression type literals yet, so I'm not sure how we could achieve this.

**Comment by suneettipirneni** [comment]
yeah it looks you're correct they a discussion about it [here](https://github.com/microsoft/TypeScript/issues/6579), but nothing has come of it.

**Comment by iCrawl** [comment]
As we currently cannot really do anything about this, I will close this issue. 

We can revisit this whenever there is a possible way of doing this.
