### ISSUE TITLE
Not working in browser/client-side?

### ISSUE THREAD

**Issue by valyok999** [discordjs/discord.js#5827]
Hello, I'm trying to get the bot to run through browser/client side rather than on my backend. I am using the exact same code as when I ran it on my backend, and imported all dependencies with browserify. The bot just simply never initializes. 

The strange behavior with this is that if I enter an invalid token, the bot will alert me of an invalid token, so I know the script is at least working to some degree and this isn't a dependency error, as when a valid token is entered there is no error being thrown. I checked this by add a .catch to the client.login() method. Everything else simply does not work. It throws no errors at all, just the bot never initializes.

I have tried asking this in the Discord, but was unable to find a solution.

**Comment by anandre** [comment]
Discord has dropped support for webpacks, so you can't run it through a browser.

**Comment by kyranet** [comment]
^ + this caused by Discord changing the CORS of their endpoints, which made everything that queries them from a browser, break.
