### ISSUE TITLE
Properties and methods missing for ButtonInteraction

### ISSUE THREAD

**Issue by Bluenix2** [discordjs/discord.js#5833]
**Please describe the problem you are having in as much detail as possible:**
![image](https://user-images.githubusercontent.com/38372706/121772851-6ec74800-cb78-11eb-9505-62bcfa04cf8e.png)

**Include a reproducible code sample here, if possible:**
Visit [ButtonInteraction | discord.js](https://discord.js.org/#/docs/main/master/class/ButtonInteraction).

**Comment by monbrey** [comment]
Thanks - this should say it `extends MessageComponentInteraction` but due to a typo that isn't appearing. I'll PR a fix now,
