### ISSUE TITLE
Make UserManager.resolve() work with string mentions

### ISSUE THREAD

**Issue by beni69** [discordjs/discord.js#5839]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to parse a user mention from the contents of a message into the user object. When a user mentions someone, the message content string looks like `<@1234567890>` or `<@!1234567890>`. However, for some reason `UserManager.resolve()` does not support these types of strings, only the snowflake. *By the way this also applies to channel mentions, I'm hoping that gets fixed too*

**Describe the ideal solution**
The `resolve()` function should be able to detect this type of mention and well, *resolve* it into a user object.

**Describe alternatives you've considered**
So what I've been doing is something like `UserManager.resolve(userMention.replace(/regex for <, >, @, !, etc/,""))`, but I'm sure it would be more elegant if a solution would be baked right into djs.

**Additional context**
I'd be happy to add this feature myself if the idea gets approved.
Also, does anyone know what the `!` in `<@!123..> means? I've always found that a bit confusing...

**Comment by vBread** [comment]
In regards to
> Also, does anyone know what the ! in `<@!123..> means? I've always found that a bit confusing...

The `!` signifies the user has a nickname.

**Comment by kyranet** [comment]
After internal discussion with other members of the team, the consensus is to not add support for this for the following reasons:

- This feature would have a large impact in the library's performance, as `Manager#resolve` methods are being more and more used.
- This feature can cause unexpected bugs to arise, as it blurs the line between snowflakes and non-snowflakes.
  - Say, for example, getting a user from a mention using `users.resolve`, and then using said string over `user.id`.
- You can easily unwrap mention strings on your own using a function, for example `possibleID = removeMention(possibleID)`.
  - If anything, we could make an utility and expose it, to strip mentions, so you just do `users.resolve(Util.resolveUserMention(string))`.
  - Additionally, frameworks, and in general anything that supports parsing strings into objects from Discord, support mentions and do an unwrap step. This change would cause this unwrap to happen twice.
- This feature can also create unintended edge cases, such as treating data that should be invalid as valid.
