### ISSUE TITLE
Webhook removal

### ISSUE THREAD

**Issue by KazzyAPI** [discordjs/discord.js#5842]
**Please describe the problem you are having in as much detail as possible:**

Essentially you are able to delete anyones webhook by just doing webhook.delete(); Im not sure if this is intentional however thought i would report it anyways.

**Include a reproducible code sample here, if possible:**

```js
        const webhookClient = new Discord.WebhookClient(id, token);
        webhookClient.delete();
```

**Further details:**

- discord.js version:12.5.3
- Node.js version:v13.13.0
- Operating system:win10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by advaith1** [comment]
if you have the webhook id token you can delete it, that is an intentional Discord feature
https://discord.com/developers/docs/resources/webhook#delete-webhook-with-token

you cannot delete "anyones webhook" since you need the token; if you have the token then it is essentially your webhook
