### ISSUE TITLE
Change Interaction#user to Interaction#author

### ISSUE THREAD

**Issue by jaydamani** [discordjs/discord.js#5844]
**Is your feature request related to a problem? Please describe.**
This is just a small change but 
When when you want the author of a command, it's Message#author for message and Interaction#User for interactions.

**Describe the ideal solution**
rename Interaction#user to Interaction#author.

**Describe alternatives you've considered**
you can check the type, if it's a message or interaction

**Comment by iShibi** [comment]
It's how discord have named them in the api.

**Comment by almostSouji** [comment]
thanks, but we're sticking with API naming as per usual
