### ISSUE TITLE
client.shard.shardIDforGuildID is not a function

### ISSUE THREAD

**Issue by milanmdev** [discordjs/discord.js#5850]
When running the `shardIDforGuildID()` function, the client returns with the error `TypeError: client.shard.shardIDforGuildID is not a function`.

**What I am running:**

```js
client.shard.shardIDforGuildID("702604965343920168", client.shard.ids.length)

// Replace the guildID with a guild that your bot is in.
```

**Further details:**

- discord.js version: Discord.js 12.5.3
- Node.js version: v14.17.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium/Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SpaceEEC** [comment]
That's a static method, you need to call it on the class itself, not an instance:
`Discord.ShardClientUtil.shardIDForGuildID("id", count);`
