### ISSUE TITLE
Fetching bans made a bad gateway error today...

### ISSUE THREAD

**Issue by sayantan300** [discordjs/discord.js#5865]
**Please describe the problem you are having in as much detail as possible:**
I was getting banned lists and there was no problem before, but just today I got an error about gateway error.
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
publicbot.guilds.cache.get("602906543356379156").fetchBans().then(list => {
  globalThis.BannedList = list;
 }); //Publicbot is the client, and I am caching banned list globally. Don't ask me why.
```

**Further details:**

- discord.js version: v12.5.3
- Node.js version: v16
- Operating system: ubuntu 20 (heroku)
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

![](https://cdn.discordapp.com/attachments/381889950666457088/854579293030711346/Screenshot_20210616-0740582.jpg)
^ the sentry error shown above.

**Comment by kyranet** [comment]
This is a 5XX error, meaning it's on Discord's side, so there's nothing we can do to fix it.
