### ISSUE TITLE
events not triggering

### ISSUE THREAD

**Issue by PineAppleGrits** [discordjs/discord.js#5873]
I'm trying to get reaction event but im not getting it, and im not getting it with 'raw' event neither. 
I'm using commando framework but i dont think that's affecting the intents.
I tried to use the partials to see if it solves it, but it doesnt. I just dont get that event. My bot is in just one guild so it should work. 

```js
const Discord = require('discord.js');                                                                                  
const Commando = require('discord.js-commando');  
const client = new Commando.Client({
 partials: ['USER', 'GUILD_MEMBER', 'CHANNEL', 'MESSAGE', 'REACTION'],
    owner: clientOwner,
    commandPrefix: clientPrefix,
    disableEveryone: true,
    unknownCommandResponse: false
})  
client.on('messageReactionAdd', (reaction, user) => {
 console.log(reaction)
});
client.on('messageReactionRemove', (reaction, user) => {
console.log(reaction) 
})                           
```
Is there something that im missing? It should work. As i said, in raw event it doesnt triggers it neither with a recent message.
**Further details:**
- discord.js version: 12.5.3 (latest)
- Node.js version:  14.17.1
- Operating system: Linux Ubuntu 20.04

**Relevant client options:**

- partials:  ['USER', 'GUILD_MEMBER', 'CHANNEL', 'MESSAGE', 'REACTION']
- gateway intents: none

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this issue (without using commando).

If you can only reproduce this while using commando, you want to head over to [commando's issue tracker](https://github.com/discordjs/Commando/issues).

**Comment by PineAppleGrits** [comment]
Thank you i will try that. If it persist ill re-open.
