### ISSUE TITLE
Roles.Set not consistently changing roles to new members.

### ISSUE THREAD

**Issue by Matiquiel** [discordjs/discord.js#5874]
Hi there! Asked several times on discord with no luck so here I am!

I have created a bot that receives new users to my guild, and then asks to react on a message with a thumbsup (the bot itself reacts first so you just have to click on the already placed down thumbs up).

Once the member clicks on it, the bot welcomes him witt a small message, and then switches his roles from Unverified to User.

This works 95% of the times. However, sometimes the member remains Unverified. 
I added lots of console logs to check on pm2 logs if the code was being called, if there were any errors, etc. and nothing, basically the code runs as succesful, however the member remains "stuck" in the verification process.

I don't think this is a race condition because sometimes the members react over and over (you can see the bot welcom message several times sent to that same member) and still he remains Unverified.

Something I noticed is that I found (sometimes) in the audit log the bot changing the roles aparently correctly to the user, however he remains unverified.

It feels like that something remains wrong with specific users even after days, or after kicking them of the server and them trying again, once this happen with a certain member it's like that member remains "cursed"

line    console.log('assignuserrole being executed! user:', user); is logged
line           console.log('roles.set executed, ', member)   is also logged

I do the assignuserrole with a two seconds timeout just so the user can read the message before the role is switched and looses access to the channel where the "you are now verified" message is sent.

```js
function CreateReactionInVerificationHandler(client) {
    client.on("messageReactionAdd", (reaction, user) => {
        if (user.bot) return;

        if (reaction.message.channel != VERIFICATION_CHANNEL) return;

        if (reaction.emoji.name === "👍") {
            reaction.message.channel.send(
                `♦️♥️♦️♥️ Welcome to Server ${user.username}♦️♥️♦️♥️
            ✅ You've now been verified!`
            );

            console.log('assignuserrole about to be called, user:', user);
            setTimeout(() => {
                AssignUserRole(user);
            }, 2000);
        }
    });
}

function AssignUserRole(user) {
    console.log('assignuserrole being executed! user:', user);

    if (!user)
        console.log('user null in assignrole');

    GUILD.members.fetch()
        .then((members) => {

            let member = members.find(x => x.user.username == user.username);
            if (member) {
                changeRoles(member);
            } else {
                console.log('MEMBER NOT FOUND IN FIND!')
            }
        }).catch((err) => {
            console.log("ERROR ASSIGNING ROLE, couldnt fetch: \n", err);
        });
}

function changeRoles(member) {
    try {
        //  var roles = [USER_ROLE];
        // member.roles.add(USER_ROLE).catch(console.error);
        // member.roles.remove(UNVERIFIED_ROLE).catch(console.error);
        member
            .roles
            .set([USER_ROLE]).then((member) => {
                console.log('roles.set executed, ', member)
            }).catch((err) => {
                console.log('error executing roles.set, error:', err);
            });
    } catch (error) {
        console.log("Error granting role: \n", error);
    }
}
```

**Further details:**

- discord.js version:  12.5.3

**Comment by SpaceEEC** [comment]
Can you try fetching the user directly instead of populating the entire member cache and the looking them up by username?
e.g. `GUILD.members.fetch(user).then(member => /* ... */)`

Usernames are not unique and your bot might be finding another user that is already verified. (Also populating the entire member cache for one member you know by id is not necessary.)

---

Otherwise, just taking a guess here, but:
If audit logs state that the member's role have been correctly updated, everything should be fine. Another user (or bot) might have accidentally reverted the roles again for some reason (race condition?).

**Comment by Matiquiel** [comment]
Thanks for your reply, I will try that, can you please specify how the user is passed as a parameter? I dont see that in the documentation, i see it passed within braces with a "force" bool parameter:
// Fetch a single member without checking cache
guild.members.fetch({ user, force: true })

// Fetch a single member without caching
guild.members.fetch({ user, cache: false })

I'm not quite sure i understand what force is doing in these scenarios, but anyways, maybe i can directly pass a user object without any braces or force param as you showed in your code snippet? (I would simply try it but its kinda complicated to test this since it involves joining a server that I have created)

Cheers!

**Comment by nimit2801** [comment]
1. Also adding to this please send the message to the user after the role is assigned, this would make more sense to the user and he/she/they won't be confused why they got a message and still don't have the `verified roles.`
2. Also try to make the encapsulate `AssignUserRole()` and `changeRoles()` in `one function`,
3. [Optionally] if possible try to `return a promise `from your function to the main call, which we would ensure that the role was assigned or not. 
4. One more thing would be you can check the role of the user after this `roleAssignment()` is done, if he still doesn't have the role you can manually add one more callback function to add a verified role!

Hope this helps! @Matiquiel
