### ISSUE TITLE
Cannot compile TypeScript when using discord.js.

### ISSUE THREAD

**Issue by LaterIdiot** [discordjs/discord.js#5882]
**Please describe the problem you are having in as much detail as possible:**
When compiling my TypeScript code for my discord bot I get a compilation error because of Line 149 in ./typings/index.d.ts:
https://github.com/discordjs/discord.js/blob/807ea2d3c197c7c6556bd1c894114932f6657d49/typings/index.d.ts#L149
Error:
```txt
node_modules/discord.js/typings/index.d.ts:149:85 - error TS2307: Cannot find module '@discordjs/voice' or its corresponding type declarations.

149   import { DiscordGatewayAdapterCreator, DiscordGatewayAdapterLibraryMethods } from '@discordjs/voice';
```

**Include a reproducible code sample here, if possible:**

```ts
import "dotenv/config";
import { Client } from "discord.js";

// generates client for the bot
const client = new Client({
    intents: [
        "DIRECT_MESSAGES",
        "DIRECT_MESSAGE_REACTIONS",
        "DIRECT_MESSAGE_TYPING",
        "GUILDS",
        "GUILD_BANS",
        "GUILD_EMOJIS",
        "GUILD_INTEGRATIONS",
        "GUILD_INVITES",
        "GUILD_MEMBERS",
        "GUILD_MESSAGES",
        "GUILD_MESSAGE_REACTIONS",
        "GUILD_MESSAGE_TYPING",
        "GUILD_PRESENCES",
        "GUILD_WEBHOOKS",
    ],
});

client.once("ready", () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.login(process.env.BOT_TOKEN);
```

**Further details:**

- discord.js version: 13.0.0-dev.807ea2d3c197c7c6556bd1c894114932f6657d49
- Node.js version: 14.17.1
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Medium - Low

**Relevant client options:**

- partials: none
- gateway intents: `"DIRECT_MESSAGES",
        "DIRECT_MESSAGE_REACTIONS",
        "DIRECT_MESSAGE_TYPING",
        "GUILDS",
        "GUILD_BANS",
        "GUILD_EMOJIS",
        "GUILD_INTEGRATIONS",
        "GUILD_INVITES",
        "GUILD_MEMBERS",
        "GUILD_MESSAGES",
        "GUILD_MESSAGE_REACTIONS",
        "GUILD_MESSAGE_TYPING",
        "GUILD_PRESENCES", and
        "GUILD_WEBHOOKS"`
- other: none

**Comment by iCrawl** [comment]
`"skipLibCheck": true` in your tsconfig.json
