### ISSUE TITLE
Process crashing when bot is added to a new guild

### ISSUE THREAD

**Issue by GamingGeek** [discordjs/discord.js#5884]
**Please describe the problem you are having in as much detail as possible:**
When the bot is added to a new guild, the process exits due to a TypeError coming from `src/structures/Guild.js` (https://sentry.io/share/issue/0092f9e524054d2e84378f1a5e3eb16a/)

**Include a reproducible code sample here, if possible:**

```ts
import { Client } from "discord.js";

const client = new Client({ intents: 1 })

client.login();

// Wait for bot to be ready then add it to a new guild
```

**Further details:**

- discord.js version: 13.0.0-dev
- Node.js version: 15.14.0 & 14.15.1
- Operating system: KDE Neon 5.22.1 & Ubuntu Server 18.04.5 LTS
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: GUILD_MEMBER, REACTION, MESSAGE, CHANNEL, USER
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_BANS, GUILD_INVITES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_WEBHOOKS, DIRECT_MESSAGES
- I have also tested the issue on latest master, commit hash: `1f8f3ab0f8dbd346154bbfa14a98726b8df25d57`, issue was introduced in `44e2ee7b20dbec79c993dbc1f30ddb643d943347` (#5490)

**Comment by monbrey** [comment]
This is likely due to the way you extended the structure, not discord.js

A real error stack would be much more helpful if we're supposed to debug this.

**Comment by GamingGeek** [comment]
This isn't due to my extension, it's because AnonymousGuild calls this._patch immediately after super() which means Guild calls this._patch immediately after super() but not all properties that are expected to exist actually exist yet.

Downgrading to 807ea2d3c197c7c6556bd1c894114932f6657d49 resolves the issue

You can click raw here to view the normal stacktrace or full to expand sentry's viewer
![Screenshot_20210620_045857.jpg](https://user-images.githubusercontent.com/29981918/122661645-5365c980-d184-11eb-9838-606725e76823.jpg)
