### ISSUE TITLE
GuildMemberManager not getting a complete member list

### ISSUE THREAD

**Issue by maxime-lep** [discordjs/discord.js#5887]
**Please describe the problem you are having in as much detail as possible:**

I'm coding a bot which must give a role to a user upon a certain interaction (I'm currently using discord-buttons (https://www.npmjs.com/package/discord-buttons)) but when I ask for the guild member manager I only get the bot and the users who interact with the server during the bot online time(if a user interact prior to the bot launch with the server he will not appear).

**Include a reproducible code sample here, if possible:**

```js
client.on('clickButton', (button) => {
if (button.id === 'rules') {

console.log('Bot\'s server list', client.guilds);
client.guilds.fetch(config.guildID).then(server =>{
console.log(`Button's server ${server}`);
console.log('Sever\'s members ', server.members);
server.members.fetch(button.clicker.user.id).then(user =>{
console.log(`Button's user ${user}`);
user.roles.add(config.Rrole);
});
});

button.defer();
}
});
```
when I log the GuildMemberManager I got this :
![image](https://user-images.githubusercontent.com/45443359/122666979-b40afb80-d1b0-11eb-86fc-d462ebf2b543.png)

And obvously I got an error because the bot is unable to find the user who interact with the button in the GuildMemberManager.
![image](https://user-images.githubusercontent.com/45443359/122667043-1237de80-d1b1-11eb-9461-598ac547a619.png)

**Further details:**

- discord.js version: 12.5.3
- discord-buttons version: 3.2.1
- Node.js version: 14.16.0.
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: I don't care ('cause it could be an error on my side) but if this problem is encountered by others it could be pretty important.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Keke27210** [comment]
`discord-buttons` is not a part of discord.js and therefore no support is given (whether here or on the Discord server) for anything that sits on it.
discord.js already implements buttons in its development branch, and soon in v13.

**Comment by maxime-lep** [comment]
Thanks for your quick reply and sorry for disturbing you. I gonna eagerly wait for V13 instead of using shady unsupported Lib 👍.

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
