### ISSUE TITLE
Structures

### ISSUE THREAD

**Issue by xHyroM** [discordjs/discord.js#5890]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

guild.js
```js
const { Structures } = require("discord.js")

module.exports = Structures.extend('Guild', Guild => {
    /**
     * The GuildStructure structure
     * @class
    */

    class GCommandsGuild extends Guild {
        constructor(...args) {
            super(...args)
        }

        /**
         * Method to getCommandPrefix
         * @returns {Promise}
        */
        async getCommandPrefix() {
			return this.client.dispatcher.getGuildPrefix(this.id);
        }

        /**
         * Method to setCommandPrefix
         * @returns {Boolean}
        */
		async setCommandPrefix(prefix) {
			this.client.dispatcher.setGuildPrefix(prefix, this.id);
			this.client.emit('commandPrefixChange', this, this._commandPrefix);
		}
    }

    return GCommandsGuild;
})
```

index.js
```js
const Discord = require("discord.js");
require("./slash cmd/src/structures/guild")
const client = new Discord.Client({intents: ["GUILDS"]});
```

**Further details:**

- discord.js version: 13.0.0-dev
- Node.js version: 16
- Operating system: Windows 10 Home 26390
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- intents: "GUILDS"

My structure extend doesnt working in djs v13 | v12 works
I have it defined before `new Client()` + i have `GUILDS` intents in `new Client()`

**Comment by VoltrexMaster** [comment]
The description of your issue is not very informative, do you get any errors? What's the expected result? What's the unexpected result? Please elaborate on your issue.

**Comment by xHyroM** [comment]
in djs v12 <message>.guild return `GCommandsGuild` and in djs v13 its return `Guild`

**Comment by xHyroM** [comment]
As long as I put the structure in the index and don't use require() it works.

**Comment by SpaceEEC** [comment]
Can you create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), as I am unable to reproduce this?

**Comment by xHyroM** [comment]
okay

**Comment by xHyroM** [comment]
- I was using discord.js v12 and wanted to add my own stuff to the guild object to simplify the code and make everything work well. When I put `<guild>.getCommandPrefix()` it printed the prefix.

- I wanted stage channel support so I downloaded discord.js v13 and on startup the bot threw me an error that `<guild>.getCommandPrefix()` is not a function and I didn't know what to do so I wrote here.

When I tried in djs v13 not to use `require("./slash cmd/src/structures/guild")` and put that structure directly in index.js after the defined `discord.js` it worked fine.

My structure code is:
```js
const { Structures } = require("discord.js")

module.exports = Structures.extend('Guild', Guild => {
    /**
     * The GuildStructure structure
     * @class
    */

    class GCommandsGuild extends Guild {
        constructor(...args) {
            super(...args)
        }

        /**
         * Method to getCommandPrefix
         * @returns {Promise}
        */
        async getCommandPrefix() {
			return this.client.dispatcher.getGuildPrefix(this.id);
        }

        /**
         * Method to setCommandPrefix
         * @returns {Boolean}
        */
		async setCommandPrefix(prefix) {
			this.client.dispatcher.setGuildPrefix(prefix, this.id);
			this.client.emit('commandPrefixChange', this, this._commandPrefix);
		}
    }

    return GCommandsGuild;
})
```

and in index.js I have:
```js
const Discord = require("discord.js");
require("./slash cmd/src/structures/guild")
const client = new Discord.Client({ intents: ["GUILDS"]});
```

**Comment by SpaceEEC** [comment]
This is working fine for me on `13.0.0-dev.c850ae10270076c4b2e10b130dd8f88eed4ed201`.

**Comment by xHyroM** [comment]
I just downloaded discord.js v13 via `npm i discordjs/discord.js` and it throws me this error. Multiple people have complained to me about this in my npm plugin gcommands.

**Comment by DTrombett** [comment]
I think you should use `npm i discord.js@dev` to install the master branch correctly. However I don't know if this is the problem...

**Comment by xHyroM** [comment]
Okay i go try

**Comment by xHyroM** [comment]
Thx! It's works!!!
