### ISSUE TITLE
Unable to send MessageEmbeds when using TypeScript

### ISSUE THREAD

**Issue by abitofevrything** [discordjs/discord.js#5891]
When attempting to send a `MessageEmbed` to a `TextBasedChannel` while using TypeScript, the following error occurs:
```
src/main.ts:66:26 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(options: string | APIMessage | (MessageOptions & { split?: false | undefined; })): Promise<Message>', gave the following error.
    Argument of type 'MessageEmbed' is not assignable to parameter of type 'string | APIMessage | (MessageOptions & { split?: false | undefined; })'.
      Type 'MessageEmbed' is not assignable to type 'string'.
  Overload 2 of 2, '(options: APIMessage | (MessageOptions & { split: true | SplitOptions; })): Promise<Message[]>', gave the following error.
    Argument of type 'MessageEmbed' is not assignable to parameter of type 'APIMessage | (MessageOptions & { split: true | SplitOptions; })'.
      Type 'MessageEmbed' is not assignable to type 'MessageOptions & { split: true | SplitOptions; }'.
        Type 'MessageEmbed' is not assignable to type '{ split: true | SplitOptions; }'.
```

**To reproduce the issue:**

```ts
client.on('message', message => {
    message.channel.send(new MessageEmbed().setTitle('Test').setDescription('Test'));
});
```

**Further details:**

- discord.js version: latest master
- Node.js version: v14.15.4
- TypeScript version: typescript@4.3.4
- Operating system: Windows 10
- Priority this issue should have – Moderate - embeds are an important part of Discord but this only applies to TypeScript developers.

**Relevant client options:**

- partials: none
- gateway intents: `Intents.ALL`
- other: none

- I have also tested the issue on latest master, commit hash: `c850ae10270076c4b2e10b130dd8f88eed4ed201`

**Comment by DTrombett** [comment]
v13 changes how sending/editing and replying to messages works. All of these methods now only accept _**one**_ parameter:

`​``diff
- channel.send(embed);
+ channel.send({ embeds: [embed, embed2] });

- channel.send('Hello!', { embed });
+ channel.send({ content: 'Hello!', embeds: [embed, embed2] });
`​``

See <https://deploy-preview-680--discordjs-guide.netlify.app/additional-info/changes-in-v13> for a full migration guide.

**Comment by adrifcastr** [comment]
As the typescript compiler tells you, .send(embed) is not valid overload.

It also tells you that the options object is the only valid overload now besides a content string.

This is entirely you not reading the TS err properly.

If you want to send an embed send it within an options object. { embeds: [embed]  }
