### ISSUE TITLE
Interaction.member doesn't have the correct type definition.

### ISSUE THREAD

**Issue by LaterIdiot** [discordjs/discord.js#5907]
**Please describe the problem you are having in as much detail as possible:**

I am using TypeScript and when I try to see if the user has a certain permission from an `Interaction` it doesn't let me use `Interaction.member.permissions.has(PermissionString)`. I am suspecting this is due to wrong typing for the `member` property in  the `Interaction` class.
https://github.com/discordjs/discord.js/blob/edf6f0ca7012b6b678367a1b5d716d0b85e23ba3/typings/index.d.ts#L1156
I think the typing of `member` property in `Interaction` class is meant to be the following according to [`Interaction.member`](https://discord.js.org/#/docs/main/master/class/Interaction?scrollTo=member) though I am not sure if I am right, so that's why this could be a possible bug from my judgement:
```ts
    public member: GuildMember | null;
```

I tried manually switching the type of the `member` property to the type above and surprisingly typescript compiled correctly and the bot also worked properly.

**Include a reproducible code sample here, if possible:**

```ts
import { Client } from "discord.js";

const client = new Client({
    intents: ["DIRECT_MESSAGES", "GUILDS", "GUILD_MESSAGES"],
});

async function interactionMethod(
    client: Client,
    interaction: Interaction
) {
    // This should work but it doesn't.
    console.log(interaction.member.permissions.has("ADMINISTRATOR"));
};

client.login("Your Bot Token");
```

**Further details:**

- discord.js version: [`13.0.0-dev.edf6f0ca7012b6b678367a1b5d716d0b85e23ba3`](https://github.com/discordjs/discord.js/commit/edf6f0ca7012b6b678367a1b5d716d0b85e23ba3)
- Node.js version: [`14.17.1`](https://nodejs.org/dist/v14.17.1/)
- Operating system: [Windows 10 Home](https://www.microsoft.com/en-us/d/windows-10-home/d76qx4bznwk4?activetab=pivot%3aoverviewtab)
- Priority this issue should have – please be realistic and elaborate if possible: Low - Medium

**Relevant client options:**

- partials: none
- gateway intents: `"DIRECT_MESSAGES", "GUILDS", and "GUILD_MESSAGES"`
- other: none

**Comment by monbrey** [comment]
Your proposed solution makes no sense - it's still a union type, and you'd still have a very similar issue of `permissions` not existing on Object, in the same way `has` isn't a function of `RawInteractionGuildMember#permissions`.

You simply need to determine which type of the possible union types you've received first (or blindly hardcode it `as GuildMember`)

**Comment by LaterIdiot** [comment]
> Your proposed solution makes no sense - it's still a union type, and you'd still have a very similar issue of `permissions` not existing on Object, in the same way `has` isn't a function of `RawInteractionGuildMember#permissions`.
> 
> You simply need to determine which type of the possible union types you've received first (or blindly hardcode it `as GuildMember`)

Yea Idk why I typed that in.

**Comment by LaterIdiot** [comment]
Then what is `RawInteractionGuildMember` for, I just don't get it?

**Comment by monbrey** [comment]
Using slash commands doesn't require you to have a bot user in the guild - in which case you just receive raw API data.

**Comment by LaterIdiot** [comment]
I see I thought it would return null, since there is no guildmember when the slash command is called from a dm.

**Comment by monbrey** [comment]
At no point did I mention DMs.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by LaterIdiot** [comment]
Thanks for the help anyways!
