### ISSUE TITLE
Missing feature: delete @original interaction reply. (v13)

### ISSUE THREAD

**Issue by NorteX-dev** [discordjs/discord.js#5924]
**Is your feature request related to a problem? Please describe.**
Problem arrived whilst trying to delete the original response of an interaction. While methods like followUp(), deleteReply(), update() etc. are present, a function to delete the original response is missing.

**Describe the ideal solution**
A method added such as InteractionResponse#delete() or InteractionResponse#deleteOriginal() (for the endpoint: https://discord.com/developers/docs/interactions/slash-commands#delete-original-interaction-response). 
Since InteractionResponse#update() exists, which edits the original response, why not a method to delete it as well? 

**Describe alternatives you've considered**
No alternatives since this is a missing feature that I feel like should exist.

**Additional context**
Tested with preview versions of Discord.js version 13.
Requesting the endpoint manually (with a library like fetch or axios) does delete the message as should.

**Comment by NorteX-dev** [comment]
Edit: I know some methods are included with the Webhook class, but it still doesn't seem to work.

**Comment by ckohen** [comment]
The method described does exist, you actually said it in your post: `deleteReply()`.

The `update()` method is not meant to be used to edit the original response, it is for use strictly on component interactions to update the pre-existing message (which also sets that message to be @original so you can continue to edit it).

There are 2 different sets of methods to remember here,
| Action | Interaction Response | After initial response |
|--------|-------------------------|-------------|
| Send Message  | `reply()`                        | `followUp()` |
| Defer Send Message | `defer()` | N/A |
| Edit Message | `update()` * | `editReply()` |
| Defer Edit Message | `deferUpdate()` * | N/A |
| Get Message | N/A | `fetchReply()` |
| Delete Message | N/A | `deleteReply()` |

\* only applies to component interactions

As you noted, the webhook also lets you do this and is actually what all of the `After initial response` column uses internally, however the names are very different in that class.
