### ISSUE TITLE
Discord JavaScript V12 RADIO BOT

### ISSUE THREAD

**Issue by iFraiski** [discordjs/discord.js#5931]
Diffuse broadcast stop it stops and when it rejoins it reactivates with the sound, that with only 1 person joining, if a second person joins it does not matter.

```js
const connection = await message.member.voice.channel.join()
const dispatcher = connection.play(stream);
connection.play(stream);
```

*I did this, but at random times the radio broadcast stops*

**Comment by kyranet** [comment]
discord.js v12's voice is not longer maintained and does not receive any updates for bugfixes or any other. Please consider using [`@discordjs/voice`](https://github.com/discordjs/voice), which is a newer voice module for discord.js with better stability and performance.
