### ISSUE TITLE
MessageOptions「split」not working

### ISSUE THREAD

**Issue by waki285** [discordjs/discord.js#5938]
I used the split option because I wanted to post a sentence longer than 2000 characters. But it doesn't work due to an error.

Code:
```js
const text = "(Sentence of 2000 characters or more)"

client.on('message', async message => {
  if (message.content === "!sentence") {
    message.channel.send(text, { split: true});
  }
});
```

Error: 
```xl
DiscordAPIError:Cannot send an empty message
```
**Further details:**

- discord.js version:12.5.3
- Node.js version:12.2.1
- Operating system:Replit
- Priority this issue should have – please be realistic and elaborate if possible:low(This is not a major feature of bots)

**Relevant client options:**

- partials: message, channel, reaction
- gateway intents: all
- other: none

**Comment by monbrey** [comment]
The split option has been removed from v13, and v12 won't be getting any patches.

**Comment by nokoko09q** [comment]
What do this function ?

**Comment by kyranet** [comment]
Please, see #5918.
