### ISSUE TITLE
Potential to receive unhandled partials from resolving interaction options

### ISSUE THREAD

**Issue by monbrey** [discordjs/discord.js#5960]
**Please describe the problem you are having in as much detail as possible:**
Channels resolved from CommandInteraction options may not contain all properties as documented, if they were initially uncached. The data received with an interaction includes "resolved" channels, a structure which looks as follows:
```js
{
  type: 11,
  permissions: '137438953471',
  name: 'Test thread',
  id: '859273371379826698'
}
```

This is missing a lot of what would normally be received in a CHANNEL_CREATE. This data is internally handled into a Channel object of the appropriate type by using the `ChannelManager#add` method. In most situations this would find the existing channel and patch it - this is fine because _patch will ignore the missing properties (except threads). However if the channel is not cached, several properties of the channel will be missing in the created structure.

Discord.js does not currently have a Partial suitable for handling this.

Currently, selecting a ThreadChannel will cause a crash as the `ThreadChannel#_patch` method does not check for the existence of properties before patching, causing an error.

This doesn't appear to apply to roles, for which a more complete object is received.

**Further details:**

- discord.js version: master
- Node.js version: 16.0.0
- Operating system: Windows 11
- Priority this issue should have – please be realistic and elaborate if possible: generally low, high for threads

**Relevant client options:**
- partials: none
- gateway intents: ["GUILDS","GUILD_MESSAGES"]
- other: none

**Comment by didinele** [comment]
According to Jira, 
> When threads came out, interactions from threads didn't send the full data. They do these days, especially even more so with channel objects being sent across more recently

This is no longer relevant.
