### ISSUE TITLE
Sometimes voiceStateUpdate events are not received

### ISSUE THREAD

**Issue by zakuciael** [discordjs/discord.js#5985]
**Please describe the problem you are having in as much detail as possible:**
I've recently noticed that if I let my bot run for some time (like 1-2days) it will occasionally not receive `voiceStateUpdate` events. It's also worth noting that when this behavior happens it likes to be persistent for a particular user. Meaning that that particular user would often not trigger the event.  

I naturally first tested my code and after I've added a logline at the beginning of the callback method I've realized that this is not an issue created by my code. So I started digging into the source code of the lib and found what I thought is a potential bug but as it turns out it's not that (for context I'm talking about this [line]( https://github.com/discordjs/discord.js/blob/stable/src/client/actions/VoiceStateUpdate.js#L11)). Right now I'm trying to check if maybe some code in between that `if statement` is an error. But since it will take some time before I will see that behavior again I've decided to create this issue to hopefully get an answer.

**Include a reproducible code sample here, if possible:**

```js
const bot = new Client();

bot.on("voiceStateUpdate", async (oldState, newState) => {
  console.log(JSON.stringify(oldState));
  console.log(JSON.stringify(newState));
});

await bot.login("<token>");
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 12
- Operating system: Linux (Docker)
- Priority this issue should have: **MEDIUM**
This bug is very impactful for bots that heavily rely on the `voiceStateUpdate` event to work.

**Relevant client options:**

- partials: GUILD_MEMBER
- gateway intents: GUILDS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES
- other: none

**Comment by kyranet** [comment]
Are you able to reproduce this bug with discord.js v12.5.3? v12.5.1 and v12.5.2 have critical bugs that cause an internal crash with stage channels.

Also, this bug is most likely fixed with the `@next` branch, you can learn and ask support for it in the `#djs-at-dev` channel from the [official server](https://discord.gg/djs).

**Comment by zakuciael** [comment]
Okay, so I've updated the bot to v12.5.3, but like I've said it's going to take some time before I can see if it helped.

**Comment by zakuciael** [comment]
Okey, it's been sometime and I didn't noticed any missing events so I guess we can say that it's fixed. If later one i notice any missing events I will simply re-open the issue again, but for now we can close it.
