### ISSUE TITLE
Util.splitMessage can't split when char is Array

### ISSUE THREAD

**Issue by mome0320** [discordjs/discord.js#6006]
**Please describe the problem you are having in as much detail as possible:**
When Using Util.splitMessage if char is array, it not splited. it's like join ','

**Include a reproducible code sample here, if possible:**

```js
> Discord.Util.splitMessage(`${'a'.repeat('10')}\n${"b".repeat('10')}`,{maxLength: 10, char: '\n'})
[ 'aaaaaaaaaa', 'bbbbbbbbbb' ] // OK
> Discord.Util.splitMessage(`${'a'.repeat('10')}\n${"b".repeat('10')}`,{maxLength: 10, char: ['\n']})
[ 'aaaaaaaaaa,bbbbbbbbbb' ] // ??

```

**Further details:**

- discord.js version: master
- Node.js version: 14.17.1
- Operating system: Ubuntu 20.04.2
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DTrombett** [comment]
Mmh looks like it was splitted and then stringified.

**Comment by DTrombett** [comment]
I think I've found the error but it's very weird. When passing an array as char it uses a map method on an array like `[text]` and it splits the text but this will means that the new array will be `[[chunk1, chunk2]]` (`string[][]`) and then it uses it like an array of strings (`string[]`), which is not.

**Comment by DTrombett** [comment]
Ok I (hope to have) solved this problem. I'll make a PR to fix.
