### ISSUE TITLE
Included typings for @discordjs/voice break the voice lib typings

### ISSUE THREAD

**Issue by beni69** [discordjs/discord.js#6009]
***yes, i know this issue is technically voice related but im submitting it here because i believe the code that needs to be fixed is in this repo***

**Please describe the problem you are having in as much detail as possible:**
Since #5941 the typings for `@discordjs/voice` are included in the main `discord.js` package. This breaks typescript support for the actual voice library, because typescript just picks up the exports that are declared in the main package. Since this is just a typings problem, regular javascript users seem to be unaffected.

**To others struggling with this, there is a workaround, just do this:**
```ts
import { } from "@discordjs/voice/dist"
```

**Include a reproducible code sample here, if possible:**

```ts
import { AudioPlayer } from "@discordjs/voice"; // you can import anything else, and it won't work
// Module '"@discordjs/voice"' has no exported member 'AudioPlayer'
```

**Further details:**

- discord.js version: `13.0.0-dev.fe6cc0c.1625227356`
- Node.js version: `14.17.0`
- Operating system: `windows 10`
- Priority this issue should have – please be realistic and elaborate if possible: `high` because it breaks the voice library for everyone using typescript

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kyranet** [comment]
Fixed by https://github.com/discordjs/voice/pull/149
