### ISSUE TITLE
ClientUser properties shardID says it is nullable

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#6020]
**Please describe the problem you are having in as much detail as possible:**

In the ClientUser file the shardID properties say they are nullable in various jsdocs however in the typings file it does not.
The below jsdocs say it is nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L100-L107
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L130-L138

However, these in the same file say it cannot be nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L143-L150
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L168-L173

As well as in the typings file says they cannot be nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L516-L527
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L4074-L4079
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L2774-L2779
The above ActivityOptions interface also has readonly assigned to the number array while all the other typings for shardID number array do not.

I couldn't find anything in the discord documentation about it and didn't know whether it being nullable was correct or non-nullable so I made a bug report about it.

**Include a reproducible code sample here, if possible:** N/A

**Further details:**

- discord.js version: 13.0.0-dev (master)
- Node.js version: N/A
- Operating system: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- I have also tested the issue on latest master, commit hash: `374c779`

**Comment by DTrombett** [comment]
`shardId` shouldn't be nullable but optional. Opened a PR to fix it. #6072
