### ISSUE TITLE
permissionOverwrites.delete() got Error 404

### ISSUE THREAD

**Issue by iDrunK65** [discordjs/discord.js#6025]
**Please describe the problem you are having in as much detail as possible:**

When trying to remove a user's permissions from a channel, the api returns a 404 error.

![image](https://user-images.githubusercontent.com/25486774/124368096-bd3ea280-dc5d-11eb-9968-c601c27b7ce8.png)

**Include a reproducible code sample here, if possible:**

```js
let channel = bot.channels.cache.get("channel_id");
channel.permissionOverwrites.delete("user_id");
```

**Further details:**

- discord.js version: 13.0.0-dev.7e30011.1625338909
- Node.js version: v14.17.1
- Operating system: Windows 10 Pro 
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_VOICE_STATES
- other: none

**Comment by monbrey** [comment]
This is the expected behaviour from the API when there are no permissions overwrites found to delete.

**Comment by iDrunK65** [comment]
I agree but currently I'm trying to remove the permissions of a user from a channel (the user has the following permissions: VIEW_CHANNEL and CONNECT) but the api returns a 404.
![image](https://user-images.githubusercontent.com/25486774/124368331-8918b100-dc60-11eb-86ae-3685d258e612.png)

I just tested with Postman, the api returned 204 as expected.
![image](https://user-images.githubusercontent.com/25486774/124368461-85395e80-dc61-11eb-91cd-17ec97153df5.png)
![image](https://user-images.githubusercontent.com/25486774/124368477-a9953b00-dc61-11eb-98e7-aff4e1cbf1c0.png)
