### ISSUE TITLE
[bug]: TypeError: newParent.permissionOverwrites.map is not a function

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [discordjs/discord.js#6030]
**Please describe the problem you are having in as much detail as possible:**

TypeError: newParent.permissionOverwrites.map is not a function error when calling the `<Channel>.setParent` function

**Steps to reproduce**

1. Create a new channel
2. Try updating the parent (\<Channel\>.setParent())

**Include a reproducible code sample here, if possible:**

```ts
import { OverwriteResolvable, Permissions, Snowflake } from "discord.js";

const DEFAULT_PERMS: OverwriteResolvable[] = [
        {
          id: message.author.id,
          allow: [Permissions.FLAGS.VIEW_CHANNEL, Permissions.FLAGS.SEND_MESSAGES],
        },
        {
          id: this.bot.user.id,
          allow: [Permissions.FLAGS.VIEW_CHANNEL, Permissions.FLAGS.SEND_MESSAGES],
        },
  		{
          id: message.guild?.roles.everyone.id!,
          deny: [Permissions.FLAGS.VIEW_CHANNEL],
        },
];

const channel = await message.guild?.channels.create(
        "ticket",
        {
          type: "text",
          nsfw: false,
          permissionOverwrites: DEFAULT_PERMS,
        },
      );

	/**
    ERROR here: 
    
    TypeError: newParent.permissionOverwrites.map is not a function
    at TextChannel.edit (/home/casper/Projects/personal/ghostybot/node_modules/discord.js/src/structures/GuildChannel.js:313:66)
    at TextChannel.setParent (/home/casper/Projects/personal/ghostybot/node_modules/discord.js/src/structures/GuildChannel.js:375:17)
    */
      if (dbGuild.ticket_data.parent_id !== null) {
        channel.setParent(guild.ticket_data.parent_id as Snowflake);
      }
```

**Further details:**

Full error:

```bash
TypeError: newParent.permissionOverwrites.map is not a function
    at TextChannel.edit (/home/casper/Projects/personal/ghostybot/node_modules/discord.js/src/structures/GuildChannel.js:313:66)
    at TextChannel.setParent (/home/casper/Projects/personal/ghostybot/node_modules/discord.js/src/structures/GuildChannel.js:375:17)
    at CreateTicketCommand.execute (/home/casper/Projects/personal/ghostybot/src/commands/ticket/createticket.ts:83:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

[Full command here](https://github.com/Dev-CasperTheGhost/ghostybot/blob/main/src/commands/ticket/createticket.ts)

Error stack leads to: https://github.com/discordjs/discord.js/blob/610b0b4dd6b6e66c05c22eb852d2a752b99d07ba/src/structures/GuildChannel.js#L313

- discord.js version: v13-dev, `610b0b4dd6b6e66c05c22eb852d2a752b99d07ba`
- Node.js version: v16.3.0
- Operating system: Windows (WSL2)
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials:
	- GUILD_MEMBER
	- MESSAGE
	- USER
	- REACTION
	- CHANNEL

- gateway intents: 
	- GUILDS
	- GUILD_MESSAGES
	- GUILD_BANS
	- GUILD_EMOJIS
	- GUILD_INTEGRATIONS
	- GUILD_INVITES
	- GUILD_MEMBERS
	- GUILD_MESSAGE_REACTIONS
	- GUILD_MESSAGE_TYPING
	- GUILD_VOICE_STATES
	- GUILD_WEBHOOKS

**Comment by SpaceEEC** [comment]
This very valid bug report aside:
[`GuildChannel#edit`](https://discord.js.org/#/docs/main/stable/class/GuildChannel?scrollTo=edit) allows a `parentID` as part of the [`ChannelData`](https://discord.js.org/#/docs/main/stable/typedef/ChannelData), making the call to `GuildChannel#setParent` a superfluous API request.

**Comment by Dev-CasperTheGhost** [comment]
oh right. Thanks!
