### ISSUE TITLE
message.channel.send and message.reply Unhandled Promise Rejection

### ISSUE THREAD

**Issue by thanpolas** [discordjs/discord.js#6033]
## Please describe the problem you are having in as much detail as possible:

I created an invalid embed message, where I tried to include a link on the title of a field. That apparently is illegal and both `message.reply()` and `message.channel.send()` errored from the API.

The problem was that this error was uncaught despite having them wrapped in a try-catch statement.

The error should bubble up instead of being uncaught.

## Include a reproducible code sample here, if possible:

```js
async function respondWithEmbed(message) {
  const embedMessage = new MessageEmbed();
  const link = `[Exchange](https://google.com 'Google')`;
  embedMessage.addField(`Network - ${link}`,'the value', true);

  try {
    await message.reply(embedMessage);
  } catch(ex) {
    console.log('never here');
  }
}
```

## Further details:

The error:

```
      "name": "DiscordAPIError",
      "message": "Invalid Form Body\nembed.fields[1].name: Must be 256 or fewer in length.\nembed.fields[5].name: Must be 256 or fewer in length.\nembed.fields[9].name: Must be 256 or fewer in length.\nembed.fields[13].name: Must be 256 or fewer in length.\nembeds[0].fields[1].name: Must be 256 or fewer in length.\nembeds[0].fields[5].name: Must be 256 or fewer in length.\nembeds[0].fields[9].name: Must be 256 or fewer in length.\nembeds[0].fields[13].name: Must be 256 or fewer in length.",
      "backtrace": "DiscordAPIError: Invalid Form Body\nembed.fields[1].name: Must be 256 or fewer in length.\nembed.fields[5].name: Must be 256 or fewer in length.\nembed.fields[9].name: Must be 256 or fewer in length.\nembed.fields[13].name: Must be 256 or fewer in length.\nembeds[0].fields[1].name: Must be 256 or fewer in length.\nembeds[0].fields[5].name: Must be 256 or fewer in length.\nembeds[0].fields[9].name: Must be 256 or fewer in length.\nembeds[0].fields[13].name: Must be 256 or fewer in length.\n    at RequestHandler.execute (/Users/thanpolas/Projects/labs/callit/node_modules/discord.js/src/rest/RequestHandler.js:154:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async RequestHandler.push (/Users/thanpolas/Projects/labs/callit/node_modules/discord.js/src/rest/RequestHandler.js:39:14)"
```

- discord.js version: 12.5.3
- Node.js version: 14.15.5
- Operating system: MacOS 11.4
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Megatank58** [comment]
Hello! I wasn't able to reproduce this one master branch latest commit, can you try this on master branch once?

**Comment by monbrey** [comment]
Your code snippet doesn't seem to align with the error provided.

Under normal circumstances the API would not error if you attempted to put masked link markdown in an embed field title - I just wouldn't render as a masked link.

Your error instead says that fields 1, 5, 9 and 13 failed Discord's validation because they were over 256 characters in length, a seemingly unrelated error. I also don't see any indication that this rejection was unhandled.

**Comment by thanpolas** [comment]
Apologies, the issue was that I forgot to add the `await` in front of the `message.reply()` and thus, that's why the error was unhandled. 

All good now.
