### ISSUE TITLE
Typo in discord.js source code file shardClientUtil.js

### ISSUE THREAD

**Issue by Hubbsy** [discordjs/discord.js#6061]
I have recently installed discord.js via npm for a production level project.  After installing discord.js and starting up server for first time, I get below error in terminal. 

`node_modules/discord.js/src/sharding/ShardClientUtil.js:237
    const shard = Number(BigInt(guildID) >> 22n) % shardCount;
                                            ^^

SyntaxError: Invalid or unexpected token`

When I remove the n from the equation at "22n", The error is corrected and the library works as expected.  Is this a known issue or is there something else going on?  I have installed and re-installed discord.js multiple times and always get the same error.  

Thanks for the information. 

- discord.js version: 12
- Node.js version: 10.2.1
- Operating system: Mac OS

**Comment by iCrawl** [comment]
> Node.js version: 10.2.1

Heres your problem. For v12 we require at least Node.js version 14+
