### ISSUE TITLE
interaction.options.get() returns undefined 

### ISSUE THREAD

**Issue by juanhdev** [discordjs/discord.js#6080]
**Please describe the problem you are having in as much detail as possible:**
`interaction.options.get('optionname')` returns undefined, but when I do `console.log(interaction.options)` it is perfectly printed out, name, value, type...

**Include a reproducible code sample here, if possible:**
```js
client.on('interactionCreate', async (interaction) => {
        if (!client.application?.owner) await client.application?.fetch();
        if ( message.content.toLowerCase() === '!deploy' &&
            message.author.id === client.application?.owner.id) {
            const data = [
                {
                    name: 'test',
                    description: 'Testing',
                    options: [
                        {
                            name: 'testing',
                            description: 'type something',
                            required: true,
                            type: 'STRING', // string
                        },
                    ],
                },
            }
        }
        ...
        if (!interaction.isCommand) return;

        if (interaction.commandName === 'test') {
                console.log(interaction.options); //prints out the options normally
                const { name, optionValue } = interaction.options.get('testing');
                console.log(optionValue); //undefined
```

**Further details:**
It shouldn't be undefined

- discord.js version: 13.0.0
- Node.js version: 14.17.0
- Operating system: Windows 10 21H1
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
