### ISSUE TITLE
Discord.Intents unexpected error - discord.js@dev

### ISSUE THREAD

**Issue by GR1ND3RJS** [discordjs/discord.js#6101]
**I have just moved into discord.js@dev, and in this version it is required to use intents unlike the other version. While using the 
intents, I got this error:** 

>TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

This error is not only crashing the bot, but not allowing the bot to login.

NEW CODE:
```js
const Discord = require('discord.js')
const { Client, Intents } = Discord
const client = new Client({
    partials: ["REACTION", "MESSAGE"],
    intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_MEMBERS", "GUILD_INVITES", "GUILD_MESSAGE_REACTIONS"]
});
```

OLDER ONE:
```js
const client = new Client({ intents: [ Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILDS ] })
```

- discord.js version: discord.js@dev
- Node.js version: 15.5.1
- Operating system: Windows 10
- Priority this issue should have : High (Breaks client before the client can login)

**Relevant client options:**

- partials: ["REACTION", "MESSAGE"],
- intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_MEMBERS", "GUILD_INVITES", "GUILD_MESSAGE_REACTIONS"]

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
