### ISSUE TITLE
Add the ability to change bot's guild avatar

### ISSUE THREAD

**Issue by hanatic** [discordjs/discord.js#6103]
**Please describe your feature request.**
Discord is adding the Guild Avatars feature to have different profile images in different guilds. There is already a PR to add it to retrieve the guild avatar from a GuildMember (#5696) but I think it should be possible for the client itself to change avatars in different guilds. I'm not aware if this is implemented in the API yet, I can't find it in the official docs page where it would be (https://discord.com/developers/docs/resources/guild#guild-member-object), but I think it might be added soon. 

**Describe the ideal solution**
The ability to change the guild avatar of a Client by, for example, doing this:
```js
const Discord = require('discord.js');
const client = new Discord.Client({ /* intents go here */}):

client.on('ready', ready => {
     client.user.setGuildAvatar({ guild: "<id_of_your_guild>", url: "<url_of_the_image>" });
});

client.login('<token>');
```

**Describe alternatives you've considered**
Alternatively you could directly pass the URL and Guild ID into the GuildMember.setGuildAvatar() method as two strings instead of as an object.

**Comment by iCrawl** [comment]
We like to keep our Issue Tracker empty of useless issues.

Currently there is no plans as I see it to implement this for bots, so reopen when it is actaully planned/docuemnted in their docs.

**Comment by masterjanic** [comment]
I know this issue has already aged quite some time, but I actually need this feature for one of my projects. Is there a possibility to do this by now? I did not find anything in the docs.

**Comment by Jiralite** [comment]
Still no. The best place to ask this would be Discord themselves - join their Discord server over at https://discord.gg/discord-developers.

**Comment by masterjanic** [comment]
Even though it is not documented the endpoint exists and may be usable for bots: 
**PATCH** - `https://discord.com/api/v9/guilds/<guild id>/members/@me`.

With payload `{ "avatar": "image data..." }`

I will do some testing whether this endpoint is available for bots and whether `@me` could be replaced with a member id to change their server profile.
