### ISSUE TITLE
Has no exported member errors

### ISSUE THREAD

**Issue by NMW03** [discordjs/discord.js#6108]
**Please describe the problem you are having in as much detail as possible:**

* I really don't know why but I receive these errors even though I'm on the latest version.
![error](https://user-images.githubusercontent.com/50991261/125383103-f38bc880-e3a7-11eb-80c8-b5af1ea36f04.png)
* My discord.js version:
![image](https://user-images.githubusercontent.com/50991261/125383432-71e86a80-e3a8-11eb-8fcc-ae100ecf6da7.png)

I tried cleaning cache, but it didn't work.

**Include a reproducible code sample here, if possible:**

```js
import { CommandInteraction, MessageActionRow, Interaction, MessageComponentInteraction, InteractionReplyOptions } from "discord.js";
```
- discord.js version: 13.0.0-dev.1dcad05.1626134620
- Node.js version: v14.17.3
- TypeScript version: 4.3.5
- Operating system: Windows 10

**Comment by DTrombett** [comment]
Use npm instead of yarn or clear yarn cache, then reinstall djs dev.

> **The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
