### ISSUE TITLE
Error from discord.js

### ISSUE THREAD

**Issue by XG-2580** [discordjs/discord.js#6115]
D:\Bot discord\XG-up-timer\node_modules\discord.js\src\rest\RequestHandler.js:15
4
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (D:\Bot discord\XG-up-timer\node_modules\discord.j
s\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Bot discord\XG-up-timer\node_modules\discor
d.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/861582900759232523/messages',
  code: 50006,
  httpStatus: 400
}

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
