### ISSUE TITLE
Simpler Slash Commands

### ISSUE THREAD

**Issue by TechPro424** [discordjs/discord.js#6121]
I know that a similar request has already been created, but my suggested implementation is a bit different.

The current method of making slash commands is a bit complicated (especially for beginners)
Maybe make slash commands a bit simpler.

For example, in the WOKCommands command handler, slash commands are extremely simple: You just specify `slash: true` in the command properties, along with `name`, `description`, etc.

Here is the documentation for that command handler (for reference):
https://docs.wornoffkeys.com/commands/slash-commands

**Comment by vladfrangu** [comment]
Perhaps this will be easier for you once https://github.com/discordjs/builders/pull/3 is landed 😄

**Comment by xHyroM** [comment]
> I know that a similar request has already been created, but my suggested implementation is a bit different.
> 
> The current method of making slash commands is a bit complicated (especially for beginners)
> Maybe make slash commands a bit simpler.
> 
> For example, in the WOKCommands command handler, slash commands are extremely simple: You just specify `slash: true` in the command properties, along with `name`, `description`, etc.
> 
> Here is the documentation for that command handler (for reference):
> https://docs.wornoffkeys.com/commands/slash-commands

WOKCommands is a command handler that makes it easy to create slash/normal commands. Djs is a library and it is therefore logical that there is no built-in handler. Discord.js has its own handler like (Commando) which is planned to be deprecated and replaced by sapphire. Djs are going to @discordjs/builders which will make it easier to create a slash command but it won't be the same as WOKCommands. Then we might start to get annoyed here that why do we have to have a message event and it's not like with WOKCommands. Djs is a wrapper and WOKCommands is a framework.

**Comment by vladfrangu** [comment]
A release for builders is coming soon! Alongside that, discord.js won't come with a command handler included (that's on you to code, or use a framework 😉), so this is outside the scope of this library.

**Comment by TechPro424** [comment]
> Perhaps this will be easier for you once [discordjs/builders#3](https://github.com/discordjs/builders/pull/3) is landed 😄

Thanks a lot! :)
