### ISSUE TITLE
Interactions related events triggers two times

### ISSUE THREAD

**Issue by darkiiii** [discordjs/discord.js#6123]
**Problem:**
collector.on('collect') and client.on('interactionCreate') always triggers two times, when i use a command on my server discord, the message sent in the console is sent two times and the second time the bot crashes for 'Unknown Interaction' when replying.
**Code sample:**
`bot.ts`
```ts
import { CommandInteraction, InteractionCollector } from "discord.js";
const commandHandler = new InteractionCollector(bot, { interactionType: "APPLICATION_COMMAND" });
commandHandler.on('collect', async (interaction: CommandInteraction) => {
    if (!bot.commands.has(interaction.commandName)) return;
    try {
        await bot.commands.get(interaction.commandName).execute(interaction);
        console.info(`${Date.now()} : ${interaction.user} used command ${interaction.commandName}`)
    } catch (error) {
        await interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });
        console.error(`${Date.now()} : ${interaction.user} failed to use command ${interaction.commandName}\nError : ${error}`)
    }
});
```
`commands/ping.ts`
```ts
import { CommandInteraction } from "discord.js";

module.exports = {
    name: 'ping',
    description: 'pong',
    execute(interaction: CommandInteraction) {
        interaction.reply({ content: `Pong`, fetchReply: true }).catch(err => {});
    }
}
```

**Further details:**
- discord.js version: discord.js@dev
- Node.js version: v16.2.0
- Operating system: Windows 10
- Priority this issue should have: Important but not crucial, for now using .catch on the interaction.reply make the bot not crashing

**Relevant client options:**
- partials: all
- gateway intents: all guild intents
- other: none

**Comment by almostSouji** [comment]
- A Collector is a temporary event listener, which emits "collected" elements, if they pass the provided filter and ends when it's end criteria is hit, if any. Naturally it listens to a subset of the global event instances
- The client listener listens to all events of the specified type. The two listeners don't know of the existence of one another and perform their specific task independently. Any instance that emits from the collector will always also hit the global event and emit on client listeners for said specified event.

I'm not too sure what you expect here, but this is working as intended. We do not dedupe these events between listeners. Choose which of the two listed behaviors you want to apply to your use case. If you want to generally listen to things forever and under any circumstance use the client listener. Temporary limited collection is easier done via collectors.

**Comment by darkiiii** [comment]
i don't use the colector and the listener at the same time, i tried both (one at the time) and it fire the event two times
