### ISSUE TITLE
Add Go Live / Screen Sharing meta data to User | Voice State | Activities

### ISSUE THREAD

**Issue by andrewowen** [discordjs/discord.js#6124]
**Describe the ideal solution**
It would be great if we could add Go Live / Screen Sharing to the list of Activity Types and show meta data related to the stream. The STREAMING type doesn't seem to cover this.

**Describe alternatives you've considered**
The STREAMING type doesn't seem to cover this and though I can get whether the user is streaming, I can't get any information about the stream / screen share itself

**Comment by SpaceEEC** [comment]
Since Go Live / Screen Sharing is not actually an activity, we can't really document it as such.

Further I don't think Discord is exposing anything more than `self_stream` (`VoiceState#streaming`) to bots.
At least on a quick glance I didn't see anything more in the received dispatches.

**Comment by advaith1** [comment]
iirc the stream metadata Discord displays will just be from PLAYING/other activities that the user has (except for the stream preview image, which bots cannot access)
