### ISSUE TITLE
`inGuild()` typeguard marks other interactions as `never`

### ISSUE THREAD

**Issue by papsavas** [discordjs/discord.js#6126]
**Please describe the problem you are having in as much detail as possible:**
As of #6094, `<interaction>#inGuild()` marks interactions that are not in guild as `never` for typescript users, ignoring DM interactions for example.

**Include a reproducible code sample here, if possible:**

```ts
client.on('interactionCreate', interaction => {
    if (interaction.isCommand()) {
        if (interaction.inGuild()) {
        //normal behaviour
        }
        else{
        //interaction type is "never"
        }
    }
}        
```

**Further details:**

- discord.js version: discord.js@13.0.0-dev.f200f14.1626436969

**Comment by vaporox** [comment]
This only happens when you have `"strict"` disabled in your `tsconfig.json`/`jsconfig.json` file. In this case, the `guildId` and `member` properties will never show up as null, so tsc thinks that the `inGuild()` method always returns true and the code in the `else` block will never run.

**Comment by LaterIdiot** [comment]
I had the same exact problem and then I enabled strict mode and it worked just fine.

**Comment by shinotheshino** [comment]
Should the requirement/suggestion for strict mode in ts projects be documented somewhere?
