### ISSUE TITLE
Ready event never emitted

### ISSUE THREAD

**Issue by n-e-o-n-s** [discordjs/discord.js#6133]
**Please describe the problem you are having in as much detail as possible:**
So i have a weird issue as to where my discord bot is working perfectly and out of no where it "hangs" meaning commands stopped working, its unresponsive but its still online. I am currently using it with socket.io and mongoose, at first i thought perhaps this is whats causing it to hang but that is not the case. After the bot gets stuck i restart my ubuntu server, i restart the process, and this is when it just stops working completely. When the discord bot is stuck in the ubuntu server, it works perfectly fine on my Windows pc. I then went ahead and removed all the code and just simply have it log in, and again the "ready" event just wont emit. Until waiting for a bit it just randomly starts working again. I am a bit confused because there is no errors or anything. I am currently logging any exception and nothing is wrong per say. This happens randomly through out the day. I run the discord bot with pm2 using command "pm2 start index.js --name DiscordBot". Ive also tried just running it with out the pm2 and same thing happens.

```js
const Discord = require('discord.js');
const client = new Discord.Client();
let token = "" // token
client.once('ready', () => {
	console.log('Ready!');
});

client.login(token);
```

**Further details:**
- discord.js version: 12.5.3
- Node.js version: v14.17.3
- Operating system: AWS Ubuntu 18.04

**Comment by vBread** [comment]
The issue template exists for a reason, please use it.

**Comment by SpaceEEC** [comment]
Can you log the debug event and show what is being logged there?
e.g. `client.on('debug', console.log);`

**Comment by n-e-o-n-s** [comment]
> Can you log the debug event and show what is being logged there?
> 
> e.g. `client.on('debug', console.log);`

Yeah just added it to my code, everything is working fine now, but just need to wait for it to happen again and ill post it

**Comment by n-e-o-n-s** [comment]
> Can you log the debug event and show what is being logged there?
> e.g. `client.on('debug', console.log);`

So it started happening again and i keep getting "429 hit on route /gateway/bot", I am not spamming log in, or anything. My Discord Bot is in One server only.

**Comment by advaith1** [comment]
are you using a shared host such as replit? the IP is probably blocked

**Comment by n-e-o-n-s** [comment]
> are you using a shared host such as replit? the IP is probably blocked

I am currently using AWS EC2 instance, dont think it shares an ip

**Comment by Poly-Pixel** [comment]
Maybe try regenerating your bot token and use it?
