### ISSUE TITLE
Message.awaitReactions not collecting anything

### ISSUE THREAD

**Issue by EasyXploit** [discordjs/discord.js#6134]
**Please describe the problem you are having in as much detail as possible:**
I have an embed that is navigable through reactions, and after updating to the Master branch of Discord.js, the navigation through reactions has stopped working.

As described in [the latest version of the documentation](https://discord.js.org/#/docs/main/master/class/Message?scrollTo=awaitReactions), I have moved the filter into the collector options, but execution does not continue and the code after `awaitReactions` statement is not executed, as if the collector had not collected anything.

I have also tried with the example code that appears in the documentation, but after reacting, the console displays the message indicating that 0 reactions have been collected:
```js
let helpEmbed = new discord.MessageEmbed()
    .setColor('FEB526')
    .setTitle('Test embed');

await message.channel.send({ embeds: [helpEmbed] }).then(async (msg) => {

    await msg.react('👌');

    const filter = (reaction, user) => reaction.emoji.name === '👌' && user.id === message.author.id;

    message.awaitReactions({ filter, time: 8000 })
        .then(collected => console.log(`Collected ${collected.size} reactions`))
        .catch(console.error);
});
```

**Include a reproducible code sample here, if possible:**
In contrast to the code example above, where I use the code provided by the documentation example, here I am attaching a sample of the code from my bot, which works correctly in version 12 of Discord.js, before I added the filter to collector options.
```js
let helpEmbed = new discord.MessageEmbed()
  .setColor('FEB526')
  .setTitle('Help embed')
  .addField('🤖', 'Help option 1.')
  .addField('🎖', 'Help option 2.');

await message.channel.send({ embeds: [helpEmbed] }).then(async (msg) => {

    await msg.react('🤖');
    await msg.react('🎖');

    const filter = (reaction, user) => {
        return ['🤖', '🎖'].includes(reaction.emoji.name) && user.id === message.author.id;
    };

    msg.awaitReactions({ filter, max: 1, time: 5000, errors: ['time'] })
        .then(async collected => {

            const reaction = collected.first();

            if (reaction.emoji.name === '🤖') {
                console.log('🤖');
            } else if (reaction.emoji.name === '🎖') {
                console.log('🎖');
            };
        })
        .catch(() => {
            return;
        });
});
```

**Further details:**

- discord.js version: discord.js#master
- Node.js version: v14.17.3
- Operating system: Windows 10 21H1 - 19043.1110
- Priority this issue should have – please be realistic and elaborate if possible: Not too much, due to the recent release of buttons, but may be needed for bots that don't want to use buttons yet or bots that don't need them.

**Relevant client options:**

- partials: none
- gateway intents: `Intents.FLAGS.GUILDS` and `Intents.FLAGS.GUILD_MESSAGES`
- other: none

**Comment by kyranet** [comment]
You need to specify the `GUILD_MESSAGE_REACTIONS` intent to receive reactions. See the available intents in the [docs](https://discord.js.org/#/docs/main/master/class/Intents?scrollTo=s-FLAGS).

**Comment by EasyXploit** [comment]
Thanks a lot @kyranet! After several conversations on the official Discord, I could not reach a conclusion, but the need for that attempt was really obvious and I did not realize it. It worked like a charm!
