### ISSUE TITLE
option to not transform data received from the api

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/discord.js#6136]
**Is your feature request related to a problem? Please describe.**

With [discord-api-types](https://github.com/discordjs/discord-api-types) there isn't really a reason to modify values received from the api anymore. Obviously object keys should still be modified (guild_id -> guildId, ...) but channel types (for example) should not be transformed from numbers -> strings.

**Describe the ideal solution**
For example:
```ts
import { ChannelType } from 'discord-api-types';
declare const channel: import('discord.js').GuildChannel;

// current method
if (channel.type === 'TEXT') { ... }

// proposed
if (channel.type === ChannelType.GUILD_TEXT) { ... }
```

**Describe alternatives you've considered**
N/A

**Additional context**

It could also be an option passed to the client? For instance:
```ts
const client = new Client({ ..., transform: false }); // transform defaults to true
```
this way it wouldn't be a breaking change

The benefits of doing this would be less maintenance burden (and the bugs that come with it), for example:
https://github.com/discordjs/discord.js/pull/5251/files

(there are others, just an example)

**Comment by Nolovehere** [comment]
Enhancement

**Comment by Nolovehere** [comment]
Baby am going to ur parents and am going to tell them everything ur going through n plz don't deny it ok am going full force ur not alone I love u n Alison be strong te amo

**Comment by Tohgloam** [comment]
ผมดัดแปลงส่วนนั้นเพื่อล้อให้ (กลุ่มเป้าหมาย) ที่แฮกเข้ามาในเครื่องผมแค่นั้นครับ อีกอย่างผมก็ไม่ได้โพสลง พื้นที่สาธารณะ

ส่งจาก iPhone ของฉัน

เมื่อ 19 ก.ค. 2564 เวลา 12:07 เขียนโดย Nolovehere ***@***.***>:

﻿

Enhancement

**Comment by iShibi** [comment]
You can import the `ChannelTypes` "enum" from `discord.js` and pass it the string that djs have for types to get the respective number for it.

**Comment by KhafraDev** [comment]
that was 1 example just showing why transforming the data isn't necessarily needed anymore, I believe interaction data types are also transformed (and probably other properties) that would also fall under this change

**Comment by iShibi** [comment]
The reason djs converts types from numbers to strings is because it makes debugging easier. When logging an object, it is better to have a descriptive string for a type than a number that will make you open the docs everytime you see it. Also, all the transformations from `numbers` -> `string` are done using the enum for that specific type. You can import it and use it to get the number back by passing it the string.

What I'm not able to understand is "why". `channel.type === 'GUILD_TEXT'`, should give you the same amount of type safety without doing any of the above stuff.

**Comment by DraftProducts** [comment]
I don't think that adding a transform option is needed, it would make it just more difficult to understand how it works.

> It could also be an option passed to the client? this way it wouldn't be a breaking change
There are already so many breaking changes in v13, another one would not make the difference.

Would it be a good idea to just make the types more digestible? Is there a reason to follow the names of the API?

**Comment by shinotheshino** [comment]
To be honest, I don't think this is needed for v13. I think this would be a good edition for the TS rewrite as I assume that would be using enums for such properties and could comply with the API much more closely.
