### ISSUE TITLE
`message.reference` should return a `message` promise

### ISSUE THREAD

**Issue by boehs** [discordjs/discord.js#6141]
**Is your feature request related to a problem? Please describe.**

When you call `message.reference` it does not return a `message` promise like most things do, but rather a `MessageReference` object. This makes doing anything useful significantly harder, as shown here `await message.channel.messages.fetch(message.reference.messageID)`

**Describe the ideal solution**

Instead of using an `MessageReference` object, it should instead return a `message` promise

**Comment by monbrey** [comment]
This has been addressed in master/v13 with the `Message#fetchReference` method.
https://discord.js.org/#/docs/main/master/class/Message?scrollTo=fetchReference

**Comment by boehs** [comment]
> This has been addressed in master/v13 with the `Message#fetchReference` method.
> https://discord.js.org/#/docs/main/master/class/Message?scrollTo=fetchReference

Should reference be deprecated?

**Comment by GoldenAngel2** [comment]
> > This has been addressed in master/v13 with the `Message#fetchReference` method.
> > https://discord.js.org/#/docs/main/master/class/Message?scrollTo=fetchReference
> 
> Should reference be deprecated?

no, as the `Message#fetchReference` function relies on `Message#reference` 
> [as seen here](https://github.com/discordjs/discord.js/blob/master/src/structures/Message.js#L541)
