### ISSUE TITLE
Bug with the (threadUpdate) event. 

### ISSUE THREAD

**Issue by GoldenAngel2** [discordjs/discord.js#6151]
**Please describe the problem you are having in as much detail as possible:**
When a thread's `rateLimitPerUser` is updated to "Off" (0) it doesn't update the property, providing the event with the wrong data.

**Include a reproducible code sample here, if possible:**

```js
const { Client, Intents: { FLAGS } } = require("discord.js");
const client = new Client({ 
    intents: [
        FLAGS.GUILD_MESSAGES,
        FLAGS.GUILD_MEMBERS,
        FLAGS.GUILD_INVITES,
        FLAGS.GUILD_EMOJIS_AND_STICKERS,
        FLAGS.GUILD_BANS,
        FLAGS.GUILDS,
        FLAGS.GUILD_VOICE_STATES,
        FLAGS.GUILD_MESSAGE_REACTIONS,
        FLAGS.GUILD_PRESENCES
    ] 
});

client.on("threadUpdate", (oldThread, thread) => {
    console.log(`Before: ${oldThread.rateLimitPerUser}\nAfter: ${thread.rateLimitPerUser}`);
});

client.login("--TOKEN--");
```

**Further details:**

- discord.js version: 13.0.0-dev (latest master branch commit)
- Node.js version: v16.4.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: `GUILD_MESSAGES, GUILD_MEMBERS, GUILD_INVITES, GUILD_EMOJIS_AND_STICKERS, GUILD_BANS, GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGE_REACTIONS, GUILD_PRESENCES`
- other: none

**Comment by SpaceEEC** [comment]
Looks like Discord is saving 23 bytes by not sending `rate_limit_per_user` when it's `0`. (But not the 30 bytes that could be saved by omitting `locked` and `archived` when they are `false`)

This could be solved by checking for another property in the payload (maybe `thread_metadata`?) to not erroneously overwrite `rateLimitPerUser` when the channel is patched with partial data.

**Comment by GoldenAngel2** [comment]
I've opened an issue on the discord-api-docs repo about the field not being included for `THREAD_UPDATE`
https://github.com/discord/discord-api-docs/issues/3486

**Comment by GoldenAngel2** [comment]
Staff reply: https://github.com/discord/discord-api-docs/issues/3486#issuecomment-884524394
