### ISSUE TITLE
Undocumented `fetchReply` option across the `Interaction` methods

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6157]
**Please describe the problem you are having in as much detail as possible:**
Hi hi!

For one of my applications, I need to be able to fetch the message I replied with (from an interaction). `<CommandInteraction>.defer()` returns `Promise<<Message> | void>` which I thought was strange since I never really got a `Message` from that?

Upon looking into the source code of [`InteractionResponses`](https://github.com/discordjs/discord.js/blob/master/src/structures/interfaces/InteractionResponses.js), the options there allow for a `fetchReply` property which returns the `Message` sent. This is really nifty! Just asking if this was undocumented for a reason or is it yet to be added in?

Thank you!

**Comment by Apokalypt** [comment]
I mentioned this error some time ago on the Discord server ( https://discord.com/channels/222078108977594368/682166281826598932/866602326176563270 ) but, yet, there is no pull request to add documentation on it. It's just an oversight...
If you know how to do it don't hesitate to make a pull request 👍
