### ISSUE TITLE
`MessageCommandInteraction#deferUpdate()` not deferring updates properly.

### ISSUE THREAD

**Issue by suneettipirneni** [discordjs/discord.js#6159]
**Please describe the problem you are having in as much detail as possible:**

When using `MessageCommandInteraction#deferUpdate()`, the component interaction should be deferred for 15min to allow for a later update, however if `deferUpdate()` is called, It seems to think that the message is replied to already, which it shouldn't do.

For example using a button component collector:
```ts
const collector = message.createMessageComponentCollector({ componentType: 'BUTTON' });
collector.on('collect', async (i) => {
  await i.deferUpdate();
  await i.update('foobar');
});
```

Causes this error shortly after the button is clicked:
```
/home/suneet/Lancelot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:193
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^
Error [INTERACTION_ALREADY_REPLIED]: This interaction has already been deferred or replied to.
    at ButtonInteraction.update (/home/suneet/Lancelot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:193:46)
    at InteractionCollector.<anonymous> (/home/suneet/Lancelot/src/commands/cat.ts:52:15)
```

**Further details:**

- discord.js version: 13.0.0-dev.77784ac.1626696170
- Node.js version: 15.14.0
- Operating system: Ubuntu 20.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_PRESENCES
- other: none

**Comment by monbrey** [comment]
This isn't a bug - if this check wasn't done internally, you would receive an API error instead.

You can either `deferUpdate` or `update` the button initially - both these methods send an acknowledgement of the interaction to Discord. You can only acknowledge once. If you `deferUpdate`, future edits must be made using `editReply`.

**Comment by suneettipirneni** [comment]
Ok thank you for the clarification.
