### ISSUE TITLE
WebhookClient creation with url

### ISSUE THREAD

**Issue by AlexanderGipp** [discordjs/discord.js#6164]
**Is your feature request related to a problem? Please describe.**
Having to provide the webhook id and token instead of just an url can result in more and less clean code which can be quite annoying.

**Describe the ideal solution**
A method overload that allows users to pass the whole webhook url:
```js
  const webhookClient = new Discord.WebhookClient("https://discord.com/api/webhooks/12334567890/asddgsjhjhshfsjhefhshjfhsjfjehsjhf_ashdjhadjhwhja");
```

**Describe alternatives you've considered**
Using regex to filter out the id and token

**Additional context**
![grafik](https://user-images.githubusercontent.com/33844665/126556604-e2cc6742-3641-4d60-93fe-3b59fc0e3589.png)

**Comment by AlexanderGipp** [comment]
I would love to try to implement this if this gets accepted as a good addition to discordjs.
(And if no one else wants to add it)

**Comment by BannerBomb** [comment]
I'm not saying you can't make a PR for this as I don't know what the maintainers would want. But you could also just store the URL somewhere in your code and parse the ID and token from the string to pass as arguments to the constructor instead of having to make the library handle it for the users.

**Comment by AlexanderGipp** [comment]
>  But you could also just store the URL somewhere in your code and parse the ID and token from the string to pass as arguments to the constructor instead of having to make the library handle it for the users.

I know that there a numerous options to solve this problem however I think that this small addition would make the life of a bunch of people notably easier. I also don't see a reason not to implement it.
