### ISSUE TITLE
GuildMemberRoleManager assumes Everyone role is always cached, but it might not be

### ISSUE THREAD

**Issue by Zuzuesque** [discordjs/discord.js#6181]
**Please describe the problem you are having in as much detail as possible:**
Can't fetch members by role since `member.roles.cache` throws an UnhandledPromiseRejectionWarning. The get cache getter in GuildMemberRoleManager tries to load the everyone role from cache although it might not be present, resulting in a consecutive TypeError.

```
(node:24824) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at GuildMemberRoleManager.get cache [as cache] ([...]\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:36:101)
```

This happens because the RoleManager doesn't check if the role is in the cache before returning it:
```js
  //RoleManager.js
  /**
   * The `@everyone` role of the guild
   * @type {Role}
   * @readonly
   */
  get everyone() {
    return this.cache.get(this.guild.id);
  }
```

And the GuildMemberRoleManager assumes it always gets the everyone role from the getter, thus accessing `everyone.id` even when everyone is undefined:

```js
  //GuildMemberRoleManager.js
  /**
   * The roles of this member
   * @type {Collection<Snowflake, Role>}
   * @readonly
   */
  get cache() {
    const everyone = this.guild.roles.everyone;
    return this.guild.roles.cache.filter(role => this.member._roles.includes(role.id)).set(everyone.id, everyone);
  }
```

**Include a reproducible code sample here, if possible:**

1. Create a new discord Project from dev branch
2. Create a new role
2. Post code below and filter for the newly created role

```js
const { Client, Intents } = require('discord.js');

const client = new Client({
  intents: [Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGES],
  partials: ['MESSAGE'],
  allowedMentions: { parse: ['users', 'roles', 'everyone'], repliedUser: true },
});

client.on('ready', async () => {
  // I actually call this from an interaction and use interaction.guild, but for
  // reproduceability I moved it to the index
  const guild = await client.guilds.fetch('111222333444555666'); // add legid server ID

  // Commenting in the following line solves the issue, as everyone role is now cached
  // await guild.roles.fetch();

  const guildMembers = await guild.members.fetch();
  const roleMembers = guildMembers
    .filter((member) => member.roles.cache.has('111222333444555666')); // add legid role ID that's not the Everyone ID
});
```

**Further details:**

- discord.js version: 13.0.0-dev.4886ae2.1627128182 (today)
- Node.js version: v14.17.3
- Operating system: Windows 10
- Priority: Medium -- there is a (none obvious) workaround fetching the everyone role of a guild by hand, but it feels unintuitive and `member.roles.cache` shouldn't fail when just accessing it.

**Relevant client options:**

- partials: MESSAGE
- gateway intents: GUILD_MEMBERS, GUILD_MESSAGES
- other: allowedMentions: users, roles, everyone

**Comment by ImRodry** [comment]
Why are you filtering the guild members that have the `@everyone` role if everyone has that role? Anyway I used that code and couldn't reproduce this issue

**Comment by Zuzuesque** [comment]
I am not filtering for the everyone role. I am filtering for other roles. If I filter for everyone it **does** work.

The issue is not with the roles a member has, but the roles cached in the guild itself.

**Comment by Jiralite** [comment]
I'm not sure this is a bug.

Without the `GUILDS` intent specified, the gateway doesn't send any `GUILD_CREATE` packets. This means that guilds are only sent to us in the form of an id on the `READY` packet, which means we straight away don't know anything. We cannot really create anything in this case. Perhaps we could add in the `RoleManager#cache` the id of the `@everyone` role, but we would know pretty much nothing about it.

You could force a fetch to Discord's API when you fetch a guild though:
```JavaScript
const guild = await client.guilds.fetch({
  force: true,
  guild: '111222333444555666'
});
```
This should cache the roles. But because you were fetching them from the cache when discord.js knew nothing about them, it of course had pretty much everything unknown.

**Comment by Zuzuesque** [comment]
It just feels uninutive. I have the GUILD_MEMBERS intent and I am trying to filter _guild members_ based on their _roles_. It is non-obvious to me, as a developer, that to filter the roles of members, I would need to fetch the everyone role for the guild just for the code not to throw an exception.

If the everyone role is unavailable if I don't have the GUILD intent, then it should at least work for the other roles (since as IMRody noted, filtering for Everyone would make little sense anyway). 

The above code did work without having to fetch the everyone role for the guild in v12 and judging from the answers people get on discord about filtering members by role, no one else is aware that fetching the guild roles is required now, either.

**Comment by Jiralite** [comment]
> The above code did work without having to fetch the everyone role for the guild in v12 and judging from the answers people get on discord about filtering members by role, no one else is aware that fetching the guild roles is required now, either.

That's odd, I'm actually getting the same error on 12.5.3 (stable):
```
/Users/jiralite/Documents/GitHub/DTT/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:32
    return this.guild.roles.cache.filter(role => this.member._roles.includes(role.id)).set(everyone.id, everyone);
                                                                                                    ^

TypeError: Cannot read property 'id' of undefined
```

The errors in both versions stem from the fact that the discord.js has an empty `Collection` about the guild's roles, because the `GUILDS` intent was not specified. Both versions actually use the `RoleManager` when you're accessing `GuildMemberRoleManager`. So I... don't believe it actually ever worked? It couldn't have?

Anyway, I see your issue: when you're fetching the guild's members, an array of role ids is supplied to them and you want to filter through the role ids of the guild's members. I'm unsure what the approach would be here, as if you wanted to do anything with the roles, you'd ultimately need to fetch the roles first...

**Comment by iCrawl** [comment]
> It just feels uninutive. I have the GUILD_MEMBERS intent and I am trying to filter guild members based on their roles. It is non-obvious to me, as a developer, that to filter the roles of members, I would need to fetch the everyone role for the guild just for the code not to throw an exception.

Nothing about this unintuitive. No guild packet = No roles. Roles don't exist outside of a guild. Specifying GUILD_MEMBERS means you get the members with the applied roles, but no information about the roles itself (which is needed here).

This is behaviour is also something we can't really change; it is how Discord functions starting from gateway version 8+

If you don't want information about the guild, which in most cases everyone who builds a bot and doesn't do any microservice architecture (apart from the fact that if you do that you would know not specifying certain intents requires you to fetch a lot more stuff), you will end up needing to fetch like other people mentiond already.
