### ISSUE TITLE
v13's expected release time is at least once all `semver-major` PRs (besides API v9 + Threads) have been merged.

### ISSUE THREAD

**Issue by qpn6ph9q** [discordjs/discord.js#6183]
v13's expected release time is at least once all `semver-major` PRs (besides API v9 + Threads) have been merged.

You can check said PRs easily by using the [`is:pr is:open label:"semver: major"`](https://github.com/discordjs/discord.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22semver%3A+major%22+) filter.

_Originally posted by @kyranet in https://github.com/discordjs/discord.js/discussions/5631#discussioncomment-739413_

**Comment by qpn6ph9q** [comment]
I notice all the PRs linked above are complete. Is there an update on the timeframe for v13?

**Comment by SuperchupuDev** [comment]
they are waiting for discord to fully release threads iirc
