### ISSUE TITLE
Status always appears as Offline for users but bots not

### ISSUE THREAD

**Issue by SolDevelop** [discordjs/discord.js#6185]
**Please describe the problem you are having in as much detail as possible:**
if i try to get the user status as online or dnd or idle or offline it always gives offline for users
**Include a reproducible code sample here, if possible:**
```js
const user = message.mentions.users.first() || message.author;
console.log(user.presence.status);
```

**Further details:**

- discord.js version: 12
- Node.js version: 16.5
- Operating system: windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by almostSouji** [comment]
This is an issue when your bot does not have the required intents enabled to receive member presences

https://discordjs.guide/popular-topics/intents.html#problems-in-version-12
> All members appear to be offline
