### ISSUE TITLE
Bug report: npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)

### ISSUE THREAD

**Issue by PuneetGopinath** [discordjs/discord.js#6196]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// The bug report is not for code
```

**Further details:**

- discord.js version: 13.0.0-dev.fe6cc0c.1625227356
- Node.js version: v14
- Operating system: Cloud platform
- Priority this issue should have – please be realistic and elaborate if possible: Everytime my app is been built, I get `npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)` in the console, I think you have to update the version in your package.json

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DTrombett** [comment]
You're using an old commit. Update using `npm i discord.js@dev`

**Comment by almostSouji** [comment]
It's a warning, not a bug
Development has moved on in both the types package and the API, thus old versions are deprecated with a notice that new ones are available. You can keep using this, as it's not an install error thar prevents anything from working.

**Comment by AustrianDev** [comment]
You should update this anyways
https://github.com/discordjs/discord.js/blob/5e433b599522265f7257bdd6b58f69dd23311b79/package.json#L54

**Comment by PuneetGopinath** [comment]
> You should update this anyways (?)
> https://github.com/discordjs/discord.js/blob/5e433b599522265f7257bdd6b58f69dd23311b79/package.json#L54

I don't know if there are other changes I should implement, also the new version is a minor version bump (0.20.2)
