### ISSUE TITLE
Bug : Can't get user.locale always null

### ISSUE THREAD

**Issue by mrsolarius** [discordjs/discord.js#6197]
I want to know the user language to send a response with my bot in his native language. I have found in the documentation that it is possible to do that with locale property: https://discord.js.org/#/docs/main/stable/class/User?scrollTo=locale

 I know that could be null. Even though I have set my language parameters, I still get a null response from the API.

```js
client.on('message', async msg => {
    if (msg.content.startsWith('!testlang')){
        console.log(msg.author.locale)
        msg.reply("local : "+msg.author.locale)
    }
});
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v14.15.1
- Operating system: Windows 7
- Priority: Not a big priority but I really like to see this solve rapidly :smile: 

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
Simply not possible - this data about users is not provided to bots and have been removed completely in v13

**Comment by mrsolarius** [comment]
I's pity :frowning: . Have you an idea to automatically adapt the language with discord js ?

**Comment by iCrawl** [comment]
You ask users to tell you and save it in a DB.

**Comment by GeniusTimo** [comment]
You could use the [preferredLocale](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=preferredLocale) of community guilds and English as default language (for private guilds or dircet messages)

**Comment by mrsolarius** [comment]
> You could use the [preferredLocale](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=preferredLocale) of community guilds and English as default language (for private guilds or dircet messages)

Thanks that exactly what's I need 😁
