### ISSUE TITLE
Incorrect permission flag for using slash commands

### ISSUE THREAD

**Issue by KifoPL** [discordjs/discord.js#6200]
**Please describe the problem you are having in as much detail as possible:**

In the official API Documentation, there is [`USE_SLASH_COMMANDS`](https://discord.com/developers/docs/topics/permissions) permission. However, in djs v13.0 it is listed as [`USE_APPLICATION_COMMANDS`](https://discord.js.org/?source=post_page---------------------------#/docs/main/master/class/Permissions?scrollTo=s-FLAGS). With the library's intention to reflect Discord API as close as possible, that doesn't seem like an intended change.

**Further details:**

- discord.js version: discord.js@13.0.0-dev.30a58dc.1627430624
- Node.js version: v16.4.0
- Operating system: *n/a*
- Priority this issue should have – please be realistic and elaborate if possible: *low*

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by vladfrangu** [comment]
I don't even remember why the documentation on Discord's side got it merged as `USE_SLASH_COMMANDS` when the client code itself calls it `USE_APPLICATION_COMMANDS`...

**Comment by SuperchupuDev** [comment]
It's USE_APPLICATION_COMMANDS internally iirc
