### ISSUE TITLE
Activity Status Dissapeares after the bot has been running for some time

### ISSUE THREAD

**Issue by gjoedev** [discordjs/discord.js#6205]
I have noticed recently that the activity status on my bot has been suddenly disappearing. Im not entirely sure why this is, but I've noticed it seems to disappear around 24 hours after the client logs in. Here is the code Im using to generate the Activity status:
```
client.once('ready', () =>{
    client.user.setActivity("The time...", {
        type: "WATCHING"
    });
})
```
Which from what I have read, is the correct way to do it.
The Bot is running the following
- NodeJS version 14.7.0
- Discord.JS version 12.5.3
- Ubuntu version 20.04

The machine is a Digital Ocean VM consisting of
- 1GB of RAM
- 1vCPU
- 25GB SSD

This isn't an urgent issue for me, but may be for others.

**Comment by SuperchupuDev** [comment]
happened to me too, but very rarely (like every 4 or 5 months) and it's fixed by restarting

**Comment by MZPL** [comment]
Longer time ago, I saw someone putting it in 2 min interval. I'm not sure if it was related to this issue, but if restarting fixes it, then it should too.

**Comment by gjoedev** [comment]
Yeah I've noticed restarting it works, Its just somewhat annoying, although its only a cosmetic issue, Its still a small inconvenience.

**Comment by almostSouji** [comment]
This is API behavior (has to do with how presences work) and we cannot change it. You should refresh your presence in an appropriate interval instead.
