### ISSUE TITLE
Ability to force gifs in every icon or avatar

### ISSUE THREAD

**Issue by MZPL** [discordjs/discord.js#6209]
**Is your feature request related to a problem? Please describe.**
When working with embeds, I need to repeat `dynamic: true` in every `avatarURL()`, `displayAvatarURL()`, `iconURL()` etc to make gifs work
**Describe the ideal solution**
It could be adding a new property to ClientOptions which would allow anyone to override this behavior
**Describe alternatives you've considered**
Simply, changing default value to true, but it'll make every icon, avatar etc animate, which some people may dislike.

**Comment by iCrawl** [comment]
This won't be happening.

It won't kill you to repeat that or make a helper function yourself that does that.

**Comment by MZPL** [comment]
Okay, thanks for info.
