### ISSUE TITLE
Timeout when calling fetch members for a guild

### ISSUE THREAD

**Issue by calundra** [discordjs/discord.js#6225]
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
When calling GuildMemberManager.fetch()

```js
let members = await guild.members.fetch({ force: true });
```
OR
```js
let members = await guild.members.fetch();
```

Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /home/www/discordbot/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16
    at Timeout._onTimeout (/home/www/discordbot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Further details:**

- discord.js version: v12.5.1
- Node.js version: v12.21.0
- Operating system: linux

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

I'd be happy with a work around for the issue if it is quicker.

**Comment by SuperchupuDev** [comment]
pretty sure you need `GUILD_MEMBERS` intent

**Comment by almostSouji** [comment]
More on privileged intents: <https://discordjs.guide/popular-topics/intents.html#problems-in-version-12>
In v12 you need to enable them in the dev dashboard (or request them during or after verification, if your bot is of the respective size), providing them to the constructor is not necessary, but recommended.
