### ISSUE TITLE
Outdated links in Client-Object

### ISSUE THREAD

**Issue by Chr1s70ph** [discordjs/discord.js#6226]
**Please describe the problem you are having in as much detail as possible:**
Outdated links in the Client-Object

```js
 http: {
       version: 9,
       api: 'https://discord.com/api',
       cdn: 'https://cdn.discordapp.com',
       invite: 'https://discord.gg',
       template: 'https://discord.new'
     }
```

I'm not sure what links would be the right links foir `api` and `cdn`.
But `invite` leads to [discord.com](https://discord.com/) and `api` and `cdn` just lead to Error pages

**Include a reproducible code sample here, if possible:**
```js
const discord = require("./node_modules/discord.js")
const client = new discord.Client({
	intents: [
		discord.Intents.FLAGS.GUILDS,
		discord.Intents.FLAGS.GUILD_MEMBERS,
		discord.Intents.FLAGS.GUILD_EMOJIS_AND_STICKERS,
		discord.Intents.FLAGS.GUILD_PRESENCES,
		discord.Intents.FLAGS.GUILD_MESSAGES
	]
})

client.login(TOKEN)

client.on("ready", () => {
	foo(client)

	console.log(client.options.http)
})
```

**Further details:**

- discord.js version: 13.0.0dev
- Node.js version: v16.5.0
- Operating system: Ubuntu 21.04 x86_64
- Priority: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by vBread** [comment]
Those are the correct links. They're base URLs, meaning they're supposed to be used with other routes, e.g., `https://discord.gg/djs`.

**Comment by Chr1s70ph** [comment]
Can you give me an example for api and cdn? I have never seen them being used

**Comment by vBread** [comment]
<https://discord.com/developers/docs/reference#api-reference-base-url>
<https://discord.com/developers/docs/reference#image-formatting>
