### ISSUE TITLE
Return invite code from which the user joined the server

### ISSUE THREAD

**Issue by SourceCipher** [discordjs/discord.js#6227]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
There is no way to track the invitations currently. It gives the number of times the invite was used only.. But that could be just users joining the server and leaving in 1s. 

I am looking for the proper invite tracking bot and could not find it. 

All I am looking is for the member obj returned from the `guildMemberAdd ` and `guildMemberRemove` events to include the joined invite code.

**Describe alternatives you've considered**
The only way to check which invitation was used is to loop through all the active invites and check which one changed in count. Thats useless since with 2 instantaneous joins will not work. 

**Additional context**
This is the only limitation to track the users actual active invited members. 

For example if the server announces some event and the winner who invites 100 members wins, then that user can invite 100 members from which 97 leaves after 10s. Currently its impossible to track which users left from what invite link they joined.

**Comment by JDJGInc** [comment]
The Current way for us to track invites right now is to use a Database and checking the invites to see which invite was used.
Which isn't a good way to handle this, a better idea is to pass this if the bot can see the invite urls and usages that way not all invite urls will be used, and this will also allow two people joining at once to work, etc

**Comment by noftaly** [comment]
I believe what you are asking for is a limitation of the Discord API, which does not provide the used invite. See this discussion https://github.com/discord/discord-api-docs/issues/448

**Comment by monbrey** [comment]
This has been answered several times previously in this issue tracker - Discord does not provide any information about the invite to the `GUILD_MEMBER_ADD` event. Discord.js can only implement functionality provided by Discord.
