### ISSUE TITLE
Option to change the number of slash commands on Discord servers

### ISSUE THREAD

**Issue by xyligan-gp** [discordjs/discord.js#6229]
Let's imagine a situation. We have a Discord bot that doesn't have access to the `Message Intent`. Ordinary commands cannot work accordingly. The only good way out of this situation is with a slash from the Discord command. It seems that everything is fine, but what if the bot developer needs to register all commands by servers, and not globally, for example, so that the command descriptions are adjusted to the server language of the bot itself. So that let's say on American servers there was a description in English, on Russian servers in Russian, etc. There is no way to do this by registering commands globally. There would be 100 of these commands, but let's say there are about 150 of them. So what should a developer do? It does not have access to the `Message Intent`, and all slots for the command slash are already occupied. As a result, 50 commands will simply have to be removed from the bot, which will obviously not be very good.

**My implementation proposal:**

1. In the Discord client options, make a separate option that will be responsible for this. And of course, to make sure that the developer can choose the required number of teams himself.
```JS
new Discord.Client({
    slashCommandsLimit: 150
});
```

2. Just increase the limit to 200, this should be enough for 99.9% of developers.

**P.S. This is just a suggestion, in no case should you put an extra load on the Discord API, but this problem can really affect all of us soon.**

**Comment by vladfrangu** [comment]
I don't really understand your suggestion, and if anything, this isn't something we control or can alter! Suggestions related to the command limit should be mentioned in the [Discord API Docs repository](../../../../discord/discord-api-docs)

**Comment by xyligan-gp** [comment]
I thought that the library itself sets this limit. It turns out this is the limit of the Discord API itself. It's a pity. It's just that for me personally, this will be a very serious problem, tk. my bot has 142 commands and it is not known if I will have access to the `Message Intent`. I have been unable to access `GUILD_PRESENCES` for almost a year now, and here's a new intent (
