### ISSUE TITLE
error from Collection util

### ISSUE THREAD

**Issue by temar96** [discordjs/discord.js#6236]
data:    index.js:18319 - /home/debian/tembot/node_modules/discord.js/src/util/Collection.js:6
data:    index.js:18319 - class Collection extends BaseCollection {
data:    index.js:18319 -                          ^
data:    index.js:18319 - TypeError: Class extends value undefined is not a constructor or null
data:    index.js:18319 -     at Object.<anonymous> (/home/debian/tembot/node_modules/discord.js/src/util/Collection.js:6:26)

I believe this maybe because of https://github.com/discordjs/discord.js/commit/dbb59ba1b29b2f75dd8faab5c3004ade51598abc

**Comment by ckohen** [comment]
The commit referenced updates the Collection dependency, please make sure to update your dependencies!
