### ISSUE TITLE
FinalizationRegistry

### ISSUE THREAD

**Issue by Consoli0** [discordjs/discord.js#6240]
**Please describe the problem you are having in as much detail as possible:**

An error is thrown about missing FinalizationRegistry type

**Include a reproducible code sample here, if possible:**

```ts
const client = new Discord.Client({
  intents: [
    Discord.Intents.FLAGS.GUILDS,
    Discord.Intents.FLAGS.GUILD_MEMBERS,
    Discord.Intents.FLAGS.DIRECT_MESSAGES,
    Discord.Intents.FLAGS.GUILD_MESSAGES,
  ],
});
```

**Further details:**

- discord.js version: 13.0.0-dev, github master branch
- Node.js version: 14
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: shown in code
- other: none

- I have also tested the issue on latest master, commit hash: `dbb59ba1b29b2f75dd8faab5c3004ade51598abc`

_I would ask on the Discord but my ban appeal sent to Crawl over 3 months ago was never replied to in any form_

**Comment by ckohen** [comment]
discord.js v13 now requires node v14.6.0 or greater due to the use of FinalizationRegistry, which was added in that version. Please update your version of node and see if the issue persists.

**Comment by Consoli0** [comment]
ahh 14.6, got it, thanks
