### ISSUE TITLE
topic and setTopic are in GuildChannel instead of TextChannel

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#6254]
**Please describe the problem you are having in as much detail as possible:**
The topic property and setTopic function are both located in the GuildChannel class, despite them only existing in text-based channels like TextChannel and NewsChannel. I would open a PR to move these, however, there are functions in GuildChannel that depend on the topic and I'm not sure how to handle those.

Since this can't _really_ be reproduced with code I have removed that part of the template.

**Further details:**

- discord.js version: https://github.com/discordjs/discord.js/commit/a25e16599a2b3d82aabebcaeaef663680f2982a8
- Priority this issue should have – please be realistic and elaborate if possible: Medium - only affects the docs and typings but should be fixed before v13 comes out to prevent future semver major changes

**Comment by Jiralite** [comment]
Seems like a duplicate of #4831?

**Comment by ImRodry** [comment]
Yeah seems like it is :/ Would really like to see that get some more attention before v13 is out.
