### ISSUE TITLE
Allow bots to edit messages sent via webhooks

### ISSUE THREAD

**Issue by vico93** [discordjs/discord.js#6255]
Seems this feature, [mentioned in Discord developer portal](https://discord.com/developers/docs/resources/webhook#edit-webhook-message), still is missing from discordjs.

A usecase of this is [Tedicross](https://github.com/TediCross/TediCross/) (Telegram <> Discord relay) putting Telegram user avatars and names as webhooks to prettify the relay on Discord side.

Relevant issue on Tedicross repo: https://github.com/TediCross/TediCross/issues/172 (they can't support send Telegram messages to Discord as webhooks because of this).

**Comment by Jiralite** [comment]
This was already added several months ago in #5223, or did you mean something else?

**Comment by vico93** [comment]
> This was already added several months ago in #5223, or did you mean something else?

My bad. I find that Tedicross request and tried to found something new on the documentation, can't find anything.

If that ability was really added, i will close the issue. Sorry.
