### ISSUE TITLE
client.application.owner returns null

### ISSUE THREAD

**Issue by KintonHiryuu** [discordjs/discord.js#6260]
**Please describe the problem you are having in as much detail as possible:**
I want to use the ClientApplication.owner property for permissions check on my bot, problem : on fresh bot as on old, team-managed bot, it always seem to return "null"

**Include a reproducible code sample here, if possible:**

```js
const DISCORD = require("discord.js")
const client = new DISCORD.Client() // in my actual code there was intents declared
client.login(token)

console.log(client.application.owner) // expected output : {?user|team} || outputs i got : null
```

When i click the doc to go in discord.js's code, here is where it brings me :
https://github.com/discordjs/discord.js/blob/master/src/structures/ClientApplication.js#L60

**Further details:**

- discord.js version: 13.0.0-dev.t1627778678.74fc23b
- Node.js version: 16.5.0
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: `DISCORD.Intents.FLAGS.GUILDS, DISCORD.Intents.FLAGS.GUILD_MESSAGES, DISCORD.Intents.FLAGS.GUILD_MESSAGE_REACTIONS`
- gateway intents: none
- other: Tried with fresh user owned bot AND 3 years old team owned bot

- I have only tested the issue on latest master, commit hash: `dev.t1627778678.74fc23b`

**Comment by BannerBomb** [comment]
To get the team data you need to use the [ClientApplication#fetch](https://discord.js.org/#/docs/main/master/class/ClientApplication?scrollTo=fetch) method since the gateway doesn't automatically send all the data.

**Comment by Megatank58** [comment]
Client.application.owner can return null as the docs say `{?User | Team}` (meaning either of those or null) and the line which you mentioned also has null

**Comment by KintonHiryuu** [comment]
oh ok then i missunderstood this, i'm gonna try with fetch then. thx

**Comment by KintonHiryuu** [comment]
Tests done, it worked, sorry for bothering you and thanks for the quick answer.
