### ISSUE TITLE
slash command permissions v13 error

### ISSUE THREAD

**Issue by VoIcanis** [discordjs/discord.js#6264]
**Please describe the problem you are having in as much detail as possible:**
While creating a slash command like ~~in v12~~ when v13 first included them and then setting the permissions I receive an error back (although no error appears to occur).

The permissions actually work as intended however it does return the following error:
```console
TypeError [INVALID_TYPE]: Supplied permissions is not an Array of ApplicationCommandPermissionData.
    at ApplicationCommandPermissionsManager.set (/redacted/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:165:15)
    at /redacted/chathandlers/tempSlashCommands.js:130:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/redacted/chathandlers/tempSlashCommands.js:83:32) {
  [Symbol(code)]: 'INVALID_TYPE'
}
```
**Include a reproducible code sample here, if possible:**

```js
const commandSetLanguage = await client.guilds.cache.get(serverID).commands.create({
  name: 'set-ticket-language',
  description: 'Staff only ability to set the language of a ticket',
  defaultPermission: false,
  options: [{
  name: 'language',
  type: 'STRING',
  description: 'Choose a language!',
  required: true,
  choices: [
	  { name: 'English', value: 'english', },
	  { name: 'Bulgarian', value: 'bulgarian', },
	  { name: 'Chinese', value: 'chinese', },
	  { name: 'Dutch', value: 'dutch', },
	  { name: 'French', value: 'french', },
	  { name: 'German', value: 'german', },
	  { name: 'Hindi', value: 'hindi', },
	  { name: 'Italian', value: 'italian', },
	  { name: 'Japanese', value: 'japanese', },
	  { name: 'Korean', value: 'korean', },
	  { name: 'Polish', value: 'polish', },
	  { name: 'Portugese', value: 'portuguese', },
	  { name: 'Russian', value: 'russian', },
	  { name: 'Spanish', value: 'spanish', },
	  { name: 'Tagalog', value: 'tagalog', },
  ],
  }],
  }).then(async e=>{
          let langPerms = [
              {
                  id: adminRole,
                  type: 'ROLE',
                  permission: true,
              },
          ];
  
  await e.permissions.set(langPerms).catch(e => console.log(e));
      });
```

**Further details:**

- discord.js version: @dev 
- Node.js version: 14.17.0
- Operating system: ubuntu 20.04
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SuperchupuDev** [comment]
> While creating a slash command like in v12

You can't create commands in v12

**Comment by VoIcanis** [comment]
> > While creating a slash command like in v12
> 
> You can't create slash commands in v12

sorry, you are right I was mistaken about the version number, must have been the moment v13 added them is what I was referring to

**Comment by ImRodry** [comment]
In order to set a command's permissions, you must provide an object where the array of permissions is in the `permissions` parameter and you must also supply a guildId. This error should be fixed once you do so

**Comment by SpaceEEC** [comment]
Small correction: If the `ApplicationCommandPermissionsManager` belongs to a guild application command bot the `guild` and `command` options are ignored and only `permissions` is required here.
