### ISSUE TITLE
Codefactor issues

### ISSUE THREAD

**Issue by xHyroM** [discordjs/discord.js#6266]
Fix issues from [Codefactor](https://www.codefactor.io/repository/github/discordjs/discord.js/issues/master)

**Comment by xHyroM** [comment]
Why?

**Comment by iCrawl** [comment]
Because we don't need some 3rd party with arbitrary and opinionated rules evaluating our code.

**Comment by xHyroM** [comment]
So why do you have eslint checks in github actions

**Comment by iCrawl** [comment]
Because we define the rules ourselves, thats why.

**Comment by xHyroM** [comment]
> Because we don't need some 3rd party with arbitrary and opinionated rules evaluating our code.
> 
> Not to speak of the fact that it conflicts with our prettier rules (using an outdated version themselves) and will mess up our CI.

So why do you have eslint checky in github actions

And where are your rules?

**Comment by xHyroM** [comment]
https://github.com/discordjs/discord.js/blob/master/.eslintrc.json ?

> > Because we don't need some 3rd party with arbitrary and opinionated rules evaluating our code.
> > Not to speak of the fact that it conflicts with our prettier rules (using an outdated version themselves) and will mess up our CI.
> 
> And where are your rules?

**Comment by iCrawl** [comment]
Where eslint rules usually reside, in the `.eslintrc.json`

**Comment by xHyroM** [comment]
Okay
