### ISSUE TITLE
Permissions#missing returns all permissions in v13

### ISSUE THREAD

**Issue by Asaduji** [discordjs/discord.js#6267]
**Please describe the problem you are having in as much detail as possible:**

In v13, Permissions#missing returns all permissions, not only the provided ones.

**Include a reproducible code sample here, if possible:**

```js
guild.me.permissions.missing(Permissions.FLAGS.ADMINISTRATOR)
```
This should only return the `ADMINISTRATOR` permission, since it's the only one passed as argument, in v12 works as intended but v13 seems to return all permissions, i'm not sure if those are all of them but it returns permissions that the bot actually has.

v12 returns:
![image](https://user-images.githubusercontent.com/39374509/127788554-764ea5e9-dc81-473f-a008-3deb6e5b8852.png)

v13 returns:
![image](https://user-images.githubusercontent.com/39374509/127788530-7ab8df42-b17c-4a0d-9ce2-55f28631613c.png)

This also happens if you provide an array as the argument.

**Further details:**

- discord.js version: `13.0.0-dev.t1627831263.774f5b7`
- Node.js version: `14.17.3`
- Operating system: `Windows 10`
- Priority this issue should have – please be realistic and elaborate if possible: `Low`

**Relevant client options:**

- partials: none
- gateway intents: `GUILD_MEMBERS, GUILD_MESSAGES, GUILDS`
- other: none

**Comment by Asaduji** [comment]
It seems like it only happens with the administrator permission 🤔

**Comment by ImRodry** [comment]
Seems like this happens because if you have a permission bitfield of 8n (ADMINISTRATOR) and call .toArray() on it, it will resolve into all permissions which seems counter intuitive. Can you check if this behavior also happens on v12?

**Comment by SpaceEEC** [comment]
You may be interested in the `checkAdmin` parameter, e.g.
```js
guild.me.permissions.missing(Permissions.FLAGS.ADMINISTRATOR, false)
```

**Comment by ImRodry** [comment]
While that does return the behavior from v12 I feel like it's confusing to get all permission flags when only providing one, do you think that's intentional behavior?

**Comment by Asaduji** [comment]
> Seems like this happens because if you have a permission bitfield of 8n (ADMINISTRATOR) and call .toArray() on it, it will resolve into all permissions which seems counter intuitive. Can you check if this behavior also happens on v12?

calling .toArray() gives the same output in both v12 and v13

> You may be interested in the `checkAdmin` parameter, e.g.
> 
> ```js
> guild.me.permissions.missing(Permissions.FLAGS.ADMINISTRATOR, false)
> ```

This indeed fixes de issue, but as @ImRodry says, is this the intended behavior? Doesn't seem like that to me, i don't see any usage of getting all permissions when checking for ADMINISTRATOR and can be confusing

**Comment by SpaceEEC** [comment]
I suppose the common use case would be to have `checkAdmin=true` for `this`, but `checkAdmin=false` for `bits`.
So that:
`[admin].missing(manage_webhooks) => []` admin means everything here
`[manage_webhooks].missing(admin) => [admin]` admin only means admin here, _not_ everything

So 2 parameters with probably these defaults?
Now a descriptive docstring for these would be nice. 🤔

**Comment by Asaduji** [comment]
> I suppose the common use case would be to have `checkAdmin=true` for `this`, but `checkAdmin=false` for `bits`.
> So that:
> `[admin].missing(manage_webhooks) => []` admin means everything here
> `[manage_webhooks].missing(admin) => [admin]` admin only means admin here, _not_ everything
> 
> So 2 parameters with probably these defaults?
> Now a descriptive docstring for these would be nice. 🤔

This makes sense, but the thing is currently .missing without checkAdmin flag set to false, returns an array with all existing permissions, doesn't matter if the bitfield has them or not

**Comment by SpaceEEC** [comment]
Yes, that's because it's allowing the administrator flag in your provided bits to act as what administrator usually does: All permissions.

**Comment by ImRodry** [comment]
> I suppose the common use case would be to have `checkAdmin=true` for `this`, but `checkAdmin=false` for `bits`.
> So that:
> `[admin].missing(manage_webhooks) => []` admin means everything here
> `[manage_webhooks].missing(admin) => [admin]` admin only means admin here, _not_ everything
> 
> So 2 parameters with probably these defaults?
> Now a descriptive docstring for these would be nice. 🤔

I believe this isn’t the way to go. The fact that `[admin].toArray` (Where [admin] is the a Permissions class with the 8n bitfield) returns all permission flags still seems like a pretty big issue to me because you can still give permissions to a role with admin, even if they don’t change anything. Since .missing relies on .toArray too this should probably be looked into.
