### ISSUE TITLE
channel.setParent not doing anything and returns no errors

### ISSUE THREAD

**Issue by ItsKodas** [discordjs/discord.js#6275]
I've spent about 5 hours updating my code to work with v13 from v12 and I got to a point where I physically can't move any further.
I've spent at least 2 hours trying to get it to work and I'm just getting no where, `channel.setParent()` is doing absolutely nothing, no error and the channel doesn't move into a diff category.

```
client.on('messageCreate', async message => {    
        if (message.content.toLowerCase() === '!test') {
            var guild = client.guilds.cache.get('847246917654151168')
            var channel = guild.channels.cache.get('871801544004235356')
            var log = await channel.setParent('847246918220251160', { lockPermissions: false })
            console.log(log)
        }
    })
```

**Further details:**

- discord.js version: 13.0.0-dev.t1627906063.6e0ea02
- Node.js version: v14.17.4
- Operating system: Windows 11 - 10.0.22000 Build 22000
- Priority this issue should have – please be realistic and elaborate if possible: It's high for me but I wouldn't know about everyone else, anyone with a ticket system that changes the parent wouldn't function.

**Relevant client options:**

- partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'USER', 'GUILD_MEMBER']
- gateway intents: ALL
- other: none

**Comment by Jiralite** [comment]
This is a bug.

This happened because #6210 reverted what #6232 implemented...

**Comment by ItsKodas** [comment]
I'm glad I didn't do some silly mess up with my own code haha, any eta on a fix?

**Comment by NotSugden** [comment]
> This is a bug.
> 
> This happened because #6210 reverted what #6232 implemented...

oopsies, must've got lost in the rebase :sweat:

**Comment by ItsKodas** [comment]
Thanks @NotSugden I'll use that as a temporary fix 😄

**Comment by ImRodry** [comment]
It should be parentId though, parent doesn't make much sense...

**Comment by ItsKodas** [comment]
@ImRodry I believe it making parent makes sense as it can be either an object or snowflake :)

**Comment by Jiralite** [comment]
> It should be parentId though, parent doesn't make much sense...

Well it won't make much sense right now due to this issue but it should accept `parent` which takes a `CategoryChannelResolvable`, which is not just the id of the channel, but also a `CategoryChannel`.

**Comment by ItsKodas** [comment]
> > This is a bug.
> > This happened because #6210 reverted what #6232 implemented...
> 
> oopsies, must've got lost in the rebase 😓
> 
> `<GuildChannel>.edit({ parent: ... });` should work though!

Your fix works nicely, thanks :D
