### ISSUE TITLE
Interaction.reply with embed and ephemeral prevent images showing

### ISSUE THREAD

**Issue by SylvainSimon** [discordjs/discord.js#6277]
Hello everyone,

Everything is in the title. It is reproducible with the current master version, which I pulled 2 hours ago. I don't have a specific commit number, it doesn't seem very important.

Replying interacts with an embed message that contains images, while being ephemeral, prevents the images from being displayed. Proof in the following capture with and without ephemeral.

```js
let messageEmbed = new MessageEmbed();

messageEmbed.setAuthor('Extension pour navigateurs', "attachment://logo-rond-32.png", 'https://extension.locklear.fr');
messageEmbed.setThumbnail('attachment://thumbnail-extension.png');
messageEmbed.setImage('attachment://image-extension.webp');
messageEmbed.setDescription("Avec l'extension Locklear soyez informés dès qu'un stream est lancé ou qu'une vidéo sort ! L'extension centralise toutes les informations dont vous avez besoin pour suivre l'activité de votre idiot préféré.\nhttps://extension.locklear.fr");

await interaction.reply({
	embeds: [messageEmbed],
	files: [
		new MessageAttachment('./img/logo-rond-32.png', 'logo-rond-32.png'),
		new MessageAttachment('./img/thumbnail-extension.png', 'thumbnail-extension.png'),
		new MessageAttachment('./img/image-extension.webp', 'image-extension.webp')
	],
	ephemeral: true /*(try with true/false here)*/,
	fetchReply: false
});
```

![image](https://user-images.githubusercontent.com/11244274/127914859-5ca607c6-202b-4ccf-80eb-2154fc190294.png)

**Further details:**

- discord.js version: master (13.x)
- Node.js version: 14.15
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Before release if possible

**Comment by monbrey** [comment]
Discord doesn't allow files to be attached to ephemeral messages. discord.js is unable to do anything about this.
