### ISSUE TITLE
Deprecate/Remove MessageEmbed#addField

### ISSUE THREAD

**Issue by SlipperySpelunky** [discordjs/discord.js#6283]
**Is your feature request related to a problem? Please describe.**
It appears inconsistent to still have MessageEmbed#addField within the Discord.js API as we have MessageEmbed#addFields

**Describe the ideal solution**
I suggest deprecating or removing MessageEmbed#addField().

**Comment by iCrawl** [comment]
I don't even want to relive the last time we did that, I think that's enough PTSD for a lifetime.

**Comment by SlipperySpelunky** [comment]
What about this syntax?

```js
// name, value, inline

embed.addFields([
  ['Amount', '0', false]
])
```

**Comment by monbrey** [comment]
We did this once before. It was one of the most hated changes we ever made.

We know it's pointless when `addFields` exists, we're just not going to remove it.
