### ISSUE TITLE
Collection.array() is not a function

### ISSUE THREAD

**Issue by Mr-KayJayDee** [discordjs/discord.js#6285]
As described in the title, this error summons randomly, everything was working fine, and after I reinstall everything I get this error on every collection I have.
Even guilds cache and members cache get the same bug.

I can't use any of the collection function neither.

I define them like this

```js
let databaseCache = new Discord.Collection()
```

**Further details:**

- discord.js version: discord.js dev version of [this commit](https://github.com/discordjs/discord.js/commit/35fa3b3103998f93253a97ad1769212d60307b61)
- Node.js version: 16.5.0
- Operating system: Windows 10

I have guild and members intent enabled.

Also tried to use discordjs/collection but it didn't work.

**Comment by GoldenAngel2** [comment]
`Collection#array` was removed. [pr for the removal](https://github.com/discordjs/collection/pull/34)
iirc use: `[ ...databaseCache.keys() ]` to get the array.
