### ISSUE TITLE
Client is not receiving 'interactionCreate' and 'messageCreate' events

### ISSUE THREAD

**Issue by zakhildev** [discordjs/discord.js#6288]
**Please describe the problem you are having in as much detail as possible:**
My Discord Bot is not receiving 'interactionCreate' and 'messageCreate' events. I have latest version of discord.js installed (version number below). The 'message' event is working fine. My command is registered correctly and is visible in Discord.

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js');
const { token } = require('./config.json');

const client = new Discord.Client({ 
	intents: [
		Discord.Intents.FLAGS.GUILDS, 
		Discord.Intents.FLAGS.GUILD_MESSAGES
	] 
});

client.on('ready', () => {
  	console.log(`Logged in as ${client.user.tag}!`);
});

client.on('interactionCreate', async interaction => {
	console.log(interaction)
	if (!interaction.isCommand()) return;

	if (interaction.commandName === 'ping') {
		await interaction.reply('Pong!');
	}
});

client.on('messageCreate', (message) => {
	console.log(message.content);
});

client.login(token);
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v16.6.1
- npm version: 7.20.3
- Operating system: Windows 11 (21H2)
- Issue priority: High

**Relevant client options:**

- gateway intents: GUILDS, GUILD_MESSAGES

**Comment by Jiralite** [comment]
Your discord.js version doesn't have these events. They belong to version 13!

**Comment by jhankim** [comment]
I'm having the same issue as well, following the guide here - https://discordjs.guide/interactions/registering-slash-commands.html

@Jiralite  the latest tag is 12.5.3 per https://github.com/discordjs/discord.js/tags, and the documentation includes instructions to use `messageCreate` and `interactionCreate`. Where does one source v13.x.x? [NPM registry](https://www.npmjs.com/package/discord.js) notes 12.5.3 as latest as well.

**Comment by Costpap** [comment]
At this point in time, the guide is meant to be used for creating v13 bots. v13 hasn't been completely released yet, you may install a pre-release by using `npm install discord.js@dev`. The guide for v12 is accessible at https://v12.discordjs.guide, however, it is advised to start making your bots compatible with v13 as early as possible, and this includes creating new ones.

**Comment by Notekunn** [comment]
I have same problem with you
**Further details:**

discord.js version: 13.2.0-dev.1628813079.f1d5ffc
node.js version: v16.6.2
npm version: 7.20.3

**Comment by ellisormatt** [comment]
I am having the same issue:

discord.js version: 13.1.0
node.js version: v16.7.0
npm version: 7.20.3

**Comment by monbrey** [comment]
The original issue was v12.5.3, where these events didn't exist.

Issues on v13 or higher are not related and should not be posted here. Please open a new issue, with a reproducible code sample, if you encounter this on v13.

**Comment by RavenDuffy** [comment]
Just so everyone is aware. The issue on v13 is actually a fault of the [tutorial](https://discordjs.guide/creating-your-bot/adding-more-commands.html#server-info-command). In the tutorial, the code ([directly from the repo](https://github.com/discordjs/guide/blob/main/code-samples/creating-your-bot/adding-more-commands/index.js)) doesn't provide the correct intents.

If you change the client initialisation to the code below, it will work:
```typescript
const client = new Client({
  intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES],
})
```

**Comment by DTrombett** [comment]
You don't need the message intent. The guide only covers slash commands, which doesn't require that intent, because chat commands are discouraged by discord and the message intent will become privileged in the next year.

**Comment by RavenDuffy** [comment]
Okay, I suppose that is true. However, neither `Intents.FLAGS.GUILDS` doesn't seem to give access to slash commands either (i.e. they aren't read). I've followed the tutorial, linked above, exactly and that flag doesn't react to any commands

**Comment by ItsJasperHere** [comment]
Sorry if this is a dead thread, but I am still having the same issue,
I have checked
- correct permissions (Administrator)
- correct scope (bot + applications.commands)
- code follows the discordjs guide repo, exception of ./config.json to .env file
- correct intents (guilds + guild messages)
Same issue, no error and doesn't seem to be reacting to interactionCreate

**Comment by T-Damer** [comment]
Try using `interaction` intead of `interactionCreate`, worked for me:
```TS
client.on('interaction', (interaction) => {
  console.log(interaction)
})
```

**Comment by vladfrangu** [comment]
Because they are deprecated, and will be removed in a major version 😄

**Comment by iaforek** [comment]
This is a bit annoying as I checked two guides and in both of them there is:

```
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
```
and also:
```
client.on('interactionCreate', async interaction => {
```

I'm able to register slash command correctly but I keep getting: `This interaction failed` when I use, for example `/ping`

After reading this thread I added:

```
const client = new Client({
  intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES],
})
```

and also was trying to use:
```
client.on('interaction', (interaction) => {
```

but that didn't help.

I have node `v16.13.0` and discordjs: `13.5.1`

**Comment by xiyu1984** [comment]
I solved this problem just now. I have the same problem but maybe for a different reason. It's nothing about the code in my situation.

Before I use discord.js, I use the original API [here](https://discord.com/developers/docs/interactions/application-commands). And I set the INTERACTIONS ENDPOINT URL as the tutorial described 
![official tutorial](https://i.stack.imgur.com/7LCJj.png)

Then I started to use discord.js. But `interactionCreate` cannot work.

I re-set `INTERACTIONS ENDPOINT URL` to be nothing. Everything is OK now.

I hope this will help you~

**Comment by darsdev** [comment]
I am _still_ having the same issue.

discord-js - v13.7.1
node.js - v18.15.0
using the correct intents
never filled anything in interaction endpoint url

my bot is over 1k lines of code so I cannot re-write in v14 just yet. it would take a good amount of time.

please help my bot is very important

**Comment by Jiralite** [comment]
If you are already using version 13, this issue is not relevant to you. That being said, version 13.7.1 does not exist. You should seek help in the [Discord server](https://discord.com/invite/djs).

**Comment by DanielSpindler** [comment]
Guys let me tell u something... i had the exact same problem interactionCreate didnt work for me.. then i copied it form the browser copy pasted it in ... and it worked. Maybe Mac os is using some other "code" in the background for the same String. 

Also i tested it multiple times.
