### ISSUE TITLE
D.JS 13 Issue // Logging in w/ Token

### ISSUE THREAD

**Issue by voidx999** [discordjs/discord.js#6300]
**Please describe the problem you are having in as much detail as possible:**
The issue is im getting
```bash
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
``` 
which i'm very confused about.
**Include a reproducible code sample here, if possible:**

```js
client.login(process.env['TOKEN']);
```

**Further details:**

- discord.js version: 13 Dev
- Node.js version: 14
- Operating system: REPLIT
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by isotrop** [comment]
Same issue.

**Comment by Megatank58** [comment]
Make sure your node version in 14, this occurs on 12 and below

**Comment by voidx999** [comment]
> Make sure your node version is 14, this occurs on 12 and below

Alright, i'll double check that because I am running node 14. But, i'll take a look into that.

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
