### ISSUE TITLE
An error not documented

### ISSUE THREAD

**Issue by ThumusLive** [discordjs/discord.js#6301]
**Please describe the problem you are having in as much detail as possible:**

(It's more a request than a bug sorry)

I got an error from this code.
![image](https://user-images.githubusercontent.com/42680097/128292587-d9ed124a-9e16-47de-89c6-d4d924c8b5fd.png)

I think discord.js should reply something else

**Include a reproducible code sample here, if possible:**

```js
<Client>.on("ready", () => {
  <Client>.guilds.cache.get("Id of a guild").commands.create();
});
```

**Further details:**

- discord.js version: 13.0.0-dev.t1628124537.3eb4140
- Node.js version: 16.5.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: Not really important in my opinion

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
The `create()` method expects you to pass in an actual command to create.

We should not have to validate that you use methods correctly.
