### ISSUE TITLE
Removing a user's reaction doesn't remove from user from cache

### ISSUE THREAD

**Issue by hellos3b** [discordjs/discord.js#6302]
**Please describe the problem you are having in as much detail as possible:**
When removing a user reaction from a `MessageReaction`, when accessing the cache afterwards it still has the user in it.

Issue in a real world example: I have an embed with an *either* one or other option, and if a user clicks option B I remove their reaction to option A, and re-render the embed with an updated list. This bug is causing the user to show up under both A and B, because I am using the cache for user list

**Include a reproducible code sample here, if possible:**

```ts
// from <message>.reactions.cache.get(id)
declare const reaction: MessageReaction;

(async function() {
  // remove user's reaction, and wait for it to resolve
  await reaction.users.remove(userId);
  // fetch the user from the cache
  const user = reaction.users.cache.find (u => u.id === userId);
  console.log ('Found in cache:', Boolean (user));
  // logged: Found in cache: true
})();
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 12.13.1
- Operating system: macOS Catalina 10.15.7
- Priority this issue should have: low

**Relevant client options:**

- partials: 'USER', 'MESSAGE', 'CHANNEL', 'REACTION'
- gateway intents: none
- other: none

**Comment by DraftProducts** [comment]
Hi @hellos3b cache is not updated when the [`<ReactionUserManager>.remove()`](https://github.com/discordjs/discord.js/blob/main/src/managers/ReactionUserManager.js#L60) method is called, your Client remove it when Discord API send you the `messageReactionRemove` event ([here exactly](https://github.com/discordjs/discord.js/blob/main/src/client/actions/MessageReactionRemove.js#L32)).

The promises of each method of DJs are resolved once the request is sent.
It's not a bug, just that your cache isn't already updated when you're checking it.
