### ISSUE TITLE
Firefox Couldn't load the documentation data. 

### ISSUE THREAD

**Issue by hsiangfeng** [discordjs/discord.js#6303]
i use firefox can't look discord document.

firefox: 90.0.2

<img width="1361" alt="圖片" src="https://user-images.githubusercontent.com/19990752/128322971-61dd126e-7a6f-43e5-a5e1-787238477bf1.png">

but chrome can look document.

![圖片](https://user-images.githubusercontent.com/19990752/128322832-485bb291-a559-430b-a9c5-7361e71f1524.png)

**Comment by muhimur9049** [comment]
Hmm... It seems to load fine for me with Firefox `90.0.2` 🤔

**Comment by hsiangfeng** [comment]
oh...i try firefox clear cache and close all firefox plugin,now is wokring!

so maybe plugin bug. omg.

now i close this issues. thx @muhimur9049  : )
