### ISSUE TITLE
Improvement of DX with message components

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#6317]
**Is your feature request related to a problem? Please describe.**

Actually using buttons and selectors is boring and brings you to write a lot of code for something witch can be simple, mostly when you just need one or two buttons/selectors.

The action row system hasn't any specific features or options but it's a needed component if you want to work with buttons stuff.
```js
<TextBasedChannel>.send({
  content: 'Interact with my beautiful buttons',
  components: [
    new MessageActionRow({
      components: [
        new MessageButton({ ... }),
        new MessageButton({ ... }),
      ]
    })
  ]
});

<TextBasedChannel>.send({
  content: 'Interact with my beautiful buttons',
  components: [
    {
      type: 'ACTION_ROW'
      components: [
        { type: 'BUTTON', ... },
        { type: 'BUTTON', ... },
      ]
    })
  ]
});
```

**Describe the ideal solution**
I think that it would be nice to add a shortcut to add buttons/selectors.
It would not bring breaking changes, just a way to write a beautiful and smaller code when the goal is just to add a simple button.

Some thing like that: 
```js
<TextBasedChannel>.send({
  content: 'Interact with my beautiful buttons',
  components: [
    new MessageButton({ ... }),
    new MessageButton({ ... }),
  ]
});
```
or something like that when we need more that the 5 components limit:
```js
<TextBasedChannel>.send({
  content: 'Interact with my beautiful buttons',
  components: [
    [
      new MessageButton({ ... }),
      new MessageButton({ ... }),
      new MessageButton({ ... }),
      new MessageButton({ ... }),
      new MessageButton({ ... }),
    ],
    [
      new MessageButton({ ... }),
      new MessageButton({ ... }),
    ],
  ]
});
```

**Comment by iCrawl** [comment]
Been there done that, decided against it because removing MessageActionRows is not feasible since they might change in the future and it will require a breaking change on our side to support that new usage.

**Comment by DraftProducts** [comment]
I already thought about it before opening the issue.
The options that Discord could add would not have any impact on this because it's a simple shortcut for simples usage (most of the cases when you use components).
If the developer needs those new features (that Discord could add in the future) he can use the "complicated method" to implement them.
Also (assumption): when you see the roadmap of the planned features for messages components of Discord, these are only optional additions to make more complete the functionalities already present or add some new components.
I don't think that it would be problematic.

**Comment by iCrawl** [comment]
That goes against what we removed in v13, specifically allowing "simplification".

Remember the whole `send(embed)` but once you need content you have to do `send({ content: '', embed })`. Same spiel here.

**Comment by DraftProducts** [comment]
Yep, I understand. It is surely better like that, it would be illogical to make this move.
Thank you for taking the time to answer me.
Nice work for this v13 🚀
Good evening!
