### ISSUE TITLE
Possibility to edit MessageAttachments

### ISSUE THREAD

**Issue by ySnoopyDogy** [discordjs/discord.js#6323]
**Is your feature request related to a problem? Please describe.**
I need to change an embed image often, so what i do is when editing the message, use like 
```js
edit({embeds: [embed], files: [attachment]})
``` 
What this do its to set the message embeds to the array of embeds i pass, and ADD to the attachments the files that i pass. 
```js
edit({content: 'Something Amazing!', embed: [], files: []})
```
This remove all embeds from the image, and does nothing to the files.

**Describe the ideal solution**

What i want is to set the embed image to the new attachment, and set the message Attachments to the array of files that i pass, so
```js
edit({embeds: [embed], files: [attachment]})
```
this would SET all attachments from the image
```js
edit({content: 'Something Amazing!', embed: [], files: []})
```
This would remove all files from the message, like the embeds do.

**Describe alternatives you've considered**
Looking to the API docs, i found that in the edit message route, the `attachments` array is for `attached files to keep`, so if the edit methods send a empty array, all attachments will delete.

I looked to the edit method from Discord.js, and it always resolve the `files` from the message, so if it has some files there, when the edit method occurs. all old files are resolved .

**Additional context**
__LINKS:__
[API edit route](https://discord.com/developers/docs/resources/channel#edit-message)
[Todays edit function](https://github.com/discordjs/discord.js/blob/main/src/managers/MessageManager.js#L121)

**Comment by SpaceEEC** [comment]
I am not sure I understand you, but https://github.com/discordjs/discord.js/pull/5557 added `attachments` as an option when editing messages.

You can combine it with `files` too to replace earlier attached files:
```js
await message.edit({ files: [newFile], attachments: [] });
```

**Comment by ySnoopyDogy** [comment]
> I am not sure I understand you, but #5557 added `attachments` as an option when editing messages.
> 
> You can combine it with `files` too to replace earlier attached files:
> 
> ```js
> await message.edit({ files: [newFile], attachments: [] });
> ```

If i pass an MessageAttachment to the attachments array, it will add the attachment to the message or it will set all attachments from the message with the array?

**Comment by SpaceEEC** [comment]
The docstring in [`MessageEditOptions`](https://discord.js.org/#/docs/main/stable/typedef/MessageEditOptions) seems to be pretty self explanatory: "An array of attachments to keep, all attachments will be kept if omitted"

**Comment by ldd** [comment]
I would never comment on closed issues, but having to pass an empty array to attachments when editing a message to delete old attachments is not at all intuitive.

I tried googling around, and it only finally found a solution once I started searching in this project's issues.

Maybe it can be included in the guide? The guide is great btw.
