### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CodeGuy92** [discordjs/discord.js#6334]
```
/home/runner/fdsiifsudiyhfsdsfd/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
```
Uhh... i am on nodejs 16, help

**Comment by PenPow** [comment]
That error says otherwise.

The issue tracker is for bug reports and feature requests, ask on the discord server if you require support, as you won't be given it on here.

**Comment by almostSouji** [comment]
The server can be found at https://discord.gg/djs
However, updating Node.js is really something you need to figure out on your own. That error clearly shows that you do not use node 16 for this process.
