### ISSUE TITLE
No way to check if an inline reply had the ping turned on or not

### ISSUE THREAD

**Issue by chandler05** [discordjs/discord.js#6336]
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to make a feature of a bot that allows the bot to delete and resend an inline reply as the bot, and I'd like it to conserve the ping option of the initial reply. However, there currently seems to be no way to check this.

**Describe the ideal solution**
A property of the reply message with a boolean for whether or not it was a ping.

**Describe alternatives you've considered**
Message#reference gets the reply message but not the ping status.

**Additional context**
None

**Comment by SpaceEEC** [comment]
Discord is using [`Message#mentions`](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=mentions)'s to determine whether the author was mentioned, so you can check [`MessageMentions#users`](https://discord.js.org/#/docs/main/stable/class/MessageMentions?scrollTo=users) for that.

**Comment by monbrey** [comment]
https://discord.js.org/#/docs/main/stable/class/MessageMentions?scrollTo=repliedUser
