### ISSUE TITLE
Feature to add a default intent of an empty array instead of throwing an error

### ISSUE THREAD

**Issue by apollyon600** [discordjs/discord.js#6341]
It would be more user friendly for new people who are getting into djsv13 or updating to it to have a default intent of []

```js
const { Client } = require('discord.js');
const client = new Client({intents:[]});
```

```js
const { Client } = require('discord.js');
const client = new Client(); // Default would have: intents:[] instead of throwing an error.
```

Thrown Error:
```js
Z:\Project\node_modules\discord.js\src\client\Client.js:544
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at new Client (Z:\SaveMoneyAIO\node_modules\discord.js\src\client\Client.js:73:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
```

If it is really necessary to have to throw an error, it would be best to throw a warning instead.

Further details:

- discord.js version: 13.0.0
- TypeScript version: 4.1.3
- Node.js version: 16.6.1
- Operating system: Windows 10 build 1709
- Priority this issue should have: MEDIUM

**Comment by kyranet** [comment]
discord.js requires at least `GUILDS` to work, blindly setting it to an empty array would just make your bot completely unoperative, aka doing absolutely nothing, which is a worse behaviour than throwing.

**Comment by apollyon600** [comment]
> discord.js requires at least `GUILDS` to work, blindly setting it to an empty array would just make your bot completely unoperative, aka doing absolutely nothing, which is a worse behaviour than throwing.

That pretty stupid imo, but then a default would be `intents: ["GUILDS"]`
I fail to see how an empty intents would want an empty intents in that case.

**Comment by kyranet** [comment]
`GUILD_MEMBERS` is privileged, and `GUILD_MESSAGES` will in 9 months. GUILDS by itself alone is useless for many bots until they switch completely to slash commands.

**Comment by monbrey** [comment]
The whole purpose of intents is for developers to think about and choose which intents they need.

A default isn't going to be set, least of all one that includes a privileged intent the developer might not have enabled.

**Comment by apollyon600** [comment]
Alright, fair enough
