### ISSUE TITLE
.deleted and .deletable flags on Message do not update

### ISSUE THREAD

**Issue by da-the-dev** [discordjs/discord.js#6348]
**Please describe the problem you are having in as much detail as possible:**
I had encounter a problem with messages, so Message has properties .deleted and .deletable, I suspected that these properties don't update at all so I've conducted an simple experiment

**Include a reproducible code sample here, if possible:**
Here's the code
```js
// Receiving the message and everything before this
console.log(msg.deleted, msg.deletable)
await msg.delete()
console.log(msg.deleted, msg.deletable)
```
the results are:
```sh
false true
false true
```
i expect them to be
```sh
false true
true false
```
which means that these properties either don't update or I'm doing something wrong

**Further details:**

- discord.js version: v13
- Node.js version: v16.6.1
- Operating system: macOS Big Sur v11.4
- Priority this issue should have: I don't know what levels of priorities are defined for this project, but on my scale it's really inconvenient and has been going since v12 (I've proposed a small fix, but it was rejected because it wasn't good)

**Relevant client options:**

- partials: none
- gateway intents: GUILD_MESSAGES, GUILDS
- other: none

**Comment by LProgead** [comment]
Hi !
That's not a bug : the `msg` shouldn't be updated if you don't update this variable explicitly. 

Your second `console.log()` calls the same variable as the first one.

**Comment by kyranet** [comment]
What's happening here is that the `.deleted` field isn't set by the method, but by the WS Action:

https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/client/actions/MessageDelete.js#L15

Both methods in the REST call send it without any mutation:

https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/structures/Message.js#L708-L711
https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/managers/MessageManager.js#L201-L206

---

In Discord, WS events are emitted *after* REST events, so this is basically a case of an unfixable racecondition, which can also happen in the middle of a call, not just after it.

**Comment by da-the-dev** [comment]
> What's happening here is that the `.deleted` field isn't set by the method, but by the WS Action:
> 
> https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/client/actions/MessageDelete.js#L15
> 
> Both methods in the REST call send it without any mutation:
> 
> https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/structures/Message.js#L708-L711
> 
> https://github.com/discordjs/discord.js/blob/622f398f4b36b00d0a347b548f63524703c2d395/src/managers/MessageManager.js#L201-L206
> 
> In Discord, WS events are emitted _after_ REST events, so this is basically a case of an unfixable racecondition, which can also happen in the middle of a call, not just after it.

Well if that's the case then I think that since these flags don't update, a solution would be fetching the message with `.fetch()`
