### ISSUE TITLE
TypeError: Class constructor Client cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Mnigos** [discordjs/discord.js#6349]
Got a `TypeError: Class constructor Client cannot be invoked without 'new'` error when i try to run bot.

```ts
import { Client, Collection } from 'discord.js'
import { readdirSync } from 'fs'
import { connect } from 'mongoose'
import { Config } from '../config'
import { Command } from '../interfaces/command'

import path = require('path')

export default class Bot extends Client {
  public commands: Collection<string, Command> = new Collection()
  public events: Collection<string, Event> = new Collection()
  public aliases: Collection<string, Command> = new Collection()

  public readonly config = new Config()

  public async init() {
    connect(this.config.mongoURI, {
      useUnifiedTopology: true,
      useFindAndModify: true,
      useNewUrlParser: true,
    })
    this.loadCommands()
    this.loadEvents()
    this.login(this.config.token)
  }

  private loadCommands() {
    const commandPath = path.join(__dirname, '..', 'commands')

    readdirSync(commandPath).forEach(dir => {
      const commands = readdirSync(`${commandPath}/${dir}`).filter(
        file => file.endsWith('.ts') && !file.endsWith('.spec.ts')
      )
      console.log(commands)

      commands.forEach(file => {
        const { command } = require(`${commandPath}/${dir}/${file}`)
        this.commands.set(command.name, command)

        if (command?.aliases.length !== 0) {
          command.aliases.forEach(alias => {
            this.aliases.set(alias, command)
          })
        }
      })
    })
  }

  private loadEvents() {
    const eventPath = path.join(__dirname, '..', 'events')

    readdirSync(eventPath).forEach(async file => {
      const { event } = await import(`${eventPath}/${file}`)
      this.events.set(event.name, event)

      console.log(`EventLoader: ${event} has been loaded`)

      this.on(event.name, event.run.bind(null, this))
    })
  }
}

```

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Windows 10 Pro

**Comment by kyranet** [comment]
As the error says, you need to replace `const client = Client();` with `const client = new Client();`.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.**

**Comment by Mnigos** [comment]
I got that in my main.ts file 
```ts
import { Intents } from 'discord.js'
import Client from './client'

const intents = new Intents(32767)

new Client({
  intents,
}).init()

```

**Comment by LProgead** [comment]
@Mnigos, it's definitely not a big witch Discord.JS...
Did you read any documentation ?

You just have to replace your imports by : 

```ts
import { Client, Intents } from 'discord.js'
```

**Comment by Mnigos** [comment]
> @Mnigos, it's definitely not a bug with Discord.JS...
> Did you read any documentation ?
> 
> You just have to replace your imports by :
> 
> ```ts
> import { Client, Intents } from 'discord.js'
> ```

No? I importing My Bot class as Client class

**Comment by vaporox** [comment]
It might be possible that your `tsconfig.json` target version is too low, since discord.js requires node 16 anyway you can safely set it to ES2020

**Comment by LProgead** [comment]
> > @Mnigos, it's definitely not a bug with Discord.JS...
> 
> > Did you read any documentation ?
> 
> > 
> 
> > You just have to replace your imports by :
> 
> > 
> 
> > ```ts
> 
> > import { Client, Intents } from 'discord.js'
> 
> > ```
> 
> 
> 
> No? I importing My Bot class as Client class

Oh ! My bad ! I didn't read that it was your `main.ts` file.
