### ISSUE TITLE
Node.js error

### ISSUE THREAD

**Issue by bco2135** [discordjs/discord.js#6352]
I was just doing my thing making a discord bot then I try to run it with Node.js and this error always pops up

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (C:\Users\ellio\Desktop\Discord-Bot\index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'

I dont know why this error pops up here is the code

const Discord = require('discord.js');
const client = new Discord.Client();

client.on("ready", () => {
console.log(`Logged in as ${client.user.tag}`)
})

client.login(################)

**Comment by blackopss** [comment]
v13?

**Comment by bco2135** [comment]
> v13?

No I was using V16.6.1

**Comment by blackopss** [comment]
> I was just doing my thing making a discord bot then I try to run it with Node.js and this error always pops up
> 
> TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
> at Client._validateOptions (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:544:13)
> at new Client (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:73:10)
> at Object. (C:\Users\ellio\Desktop\Discord-Bot\index.js:2:16)
> at Module._compile (node:internal/modules/cjs/loader:1101:14)
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> at Module.load (node:internal/modules/cjs/loader:981:32)
> at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
> at node:internal/main/run_main_module:17:47 {
> [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
> 
> I dont know why this error pops up here is the code
> 
> const Discord = require('discord.js');
> const client = new Discord.Client();
> 
> client.on("ready", () => {
> console.log(`Logged in as ${client.user.tag}`)
> })
> 
> client.login(################)

try use

const Discord = require('discord.js')
const client = new Discord.Client(
  { intents: 32767 }
);
client.on("ready", () => {
console.log(Logged in as ${client.user.tag})
})
client.login(################)

**Comment by bco2135** [comment]
Okay 

> > I was just doing my thing making a discord bot then I try to run it with Node.js and this error always pops up
> > TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
> > at Client._validateOptions (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:544:13)
> > at new Client (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:73:10)
> > at Object. (C:\Users\ellio\Desktop\Discord-Bot\index.js:2:16)
> > at Module._compile (node:internal/modules/cjs/loader:1101:14)
> > at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> > at Module.load (node:internal/modules/cjs/loader:981:32)
> > at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> > at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
> > at node:internal/main/run_main_module:17:47 {
> > [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
> > I dont know why this error pops up here is the code
> > const Discord = require('discord.js');
> > const client = new Discord.Client();
> > client.on("ready", () => {
> > console.log(`Logged in as ${client.user.tag}`)
> > })
> > client.login(################)
> 
> try use
> 
> const Discord = require('discord.js')
> const client = new Discord.Client(
> { intents: 32767 }
> );
> client.on("ready", () => {
> console.log(Logged in as ${client.user.tag})
> })
> client.login(################)

Okay ill try

**Comment by bco2135** [comment]
Thanks that helped a lot @blackopss :D

**Comment by SuperchupuDev** [comment]
> > I was just doing my thing making a discord bot then I try to run it with Node.js and this error always pops up
> > TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
> > at Client._validateOptions (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:544:13)
> > at new Client (C:\Users\ellio\Desktop\Discord-Bot\node_modules\discord.js\src\client\Client.js:73:10)
> > at Object. (C:\Users\ellio\Desktop\Discord-Bot\index.js:2:16)
> > at Module._compile (node:internal/modules/cjs/loader:1101:14)
> > at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> > at Module.load (node:internal/modules/cjs/loader:981:32)
> > at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> > at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
> > at node:internal/main/run_main_module:17:47 {
> > [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
> > I dont know why this error pops up here is the code
> > const Discord = require('discord.js');
> > const client = new Discord.Client();
> > client.on("ready", () => {
> > console.log(`Logged in as ${client.user.tag}`)
> > })
> > client.login(################)
> 
> try use
> 
> const Discord = require('discord.js')
> const client = new Discord.Client(
> { intents: 32767 }
> );
> client.on("ready", () => {
> console.log(Logged in as ${client.user.tag})
> })
> client.login(################)

using all intents is a bad practice, just read [the guide](https://discordjs.guide/popular-topics/intents.html#gateway-intents) and use only the intents you know you need
