### ISSUE TITLE
const token = this.client.token ?? this.client.accessToken;       ^  SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by Fardinator** [discordjs/discord.js#6357]
everytime i try to Run the bot 

it shows this error : 

const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'

my coding is good no errors i even try to research but no results of fixing this please fix this

**Comment by iCrawl** [comment]
Update to Node 16.
