### ISSUE TITLE
Can't send MessageAttachment, no errors given

### ISSUE THREAD

**Issue by GingkathFox** [discordjs/discord.js#6359]
**Please describe the problem you are having in as much detail as possible:**
I can't send a image as a file. I can send text as a file though.

**Include a reproducible code sample here, if possible:**

```js
// This wont work, even if i write the buffer to a file and try to directly pass the file path to D.JS like so:
/// fs.writeFileSync('./file.png', canvas.toBuffer())
/// message.channel.send({files: [./file.png]})
// Or if i pass the buffer directly to D.JS.
const canvas = Canvas.createCanvas(len * 30, 50)
            const ctx = canvas.getContext('2d')
            ctx.font = '35px Fira Code'
            ctx.fillStyle = '#ffffff'
            ctx.fillText("Test String", 5, canvas.height / 1.25)
            const attachment = new Discord.MessageAttachment(canvas.toBuffer(), 'test.png')
            message.channel.send(`This won't work...`, {files: [attachment]})
```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: v16.6.1
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible: Medium to High, seeing as MessageAttachment is a important class

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
https://discordjs.guide/additional-info/changes-in-v13.html#sending-messages-embeds-files-etc

**Comment by GingkathFox** [comment]
never-fucking-mind im stupid

**Comment by GingkathFox** [comment]
thanks @monbrey, this v13 change got me all over the place
