### ISSUE TITLE
v13 - Node.js LTS support?

### ISSUE THREAD

**Issue by osiris-plus** [discordjs/discord.js#6360]
**Is your feature request related to a problem? Please describe.**
I've been using unstable discord.js on 14.17.4 LTS Node.js version with no problems, but I can't install stable release because of the strict version requirement.

**Describe the ideal solution**
Node engine version requirements being revised.

**Describe alternatives you've considered**
nvm - too hacky
containers, virtual machines - too clumsy to operate

**Additional context**
```
yarn add discord.js
yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error discord.js@13.0.1: The engine "node" is incompatible with this module. Expected version ">=16.6.0". Got "14.16.0"
error Found incompatible module.
```

**Comment by monbrey** [comment]
Why can't you upgrade to 16.6?

Node 16 will be LTS in a couple of months, we decided to set the version requirement now in preparation, so we don't have to release a v14 to use it's features.

**Comment by osiris-plus** [comment]
Okay, you're right.
