### ISSUE TITLE
Route.applicationGuildCommands changes CLIENT_ID and GUILD_ID

### ISSUE THREAD

**Issue by supraaxdd** [discordjs/discord.js#6362]
**Please describe the problem you are having in as much detail as possible:**

I have been trying to connect to the API to register the basic slash commands using the sample code on the discord.js.org. (ref. pastebin below), however, when I start the bot up, the bot itself logs in fine, however, it says that my application is unknown. I recognised that the method changes my inputted IDs. My CLIENT_ID and GUILD_ID are 603340037056102453 and 593830690777333770 respectively but they are changed to 603340037056102400 and 593830690777333800. I will provide the full error below.

**Include a reproducible code sample here, if possible:**
https://pastebin.com/zEcZjP3n

**Further details:**
Error: https://cdn.discordapp.com/attachments/824411059443204127/873999286172532796/unknown.png

- discord.js version: discord.js@13.0.1
- Node.js version: v16.6.1
- Operating system: Windows 10 Pro

- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents: All privileged intents and using Intents.FLAGS.GUILDS in code.
- other: none

Any help is greatly appreciated!

Regards,
Supra

**Comment by supraaxdd** [comment]
Forgot to add that I also use @discordjs/rest@0.1.0-canary.0

**Comment by monbrey** [comment]
You seem to be storing them as numbers instead of strings - Javascript cant handle numbers that large and is truncating them.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by supraaxdd** [comment]
I'll try parse them as string instead so, I remember something in guide that discord.js doesn't parse numbers as string automatically anymore. Thanks for pointing that out!

**Comment by supraaxdd** [comment]
Looks like that fixed the issue, thank you so much!
