### ISSUE TITLE
Is the type supposed to be "CacheWithLimitsOptions" or "LimitedCollectionOptions"?

### ISSUE THREAD

**Issue by mrjackyliang** [discordjs/discord.js#6363]
**Please describe the problem you are having in as much detail as possible:**
Trying to upgrade to the new `CacheFactory`, but the code editor is noting that I am not typing the correct format. The error is:
```
Argument type {MessageManager: {sweepFilter: SweepFilter<unknown, unknown>, sweepInterval: number}} is not assignable to parameter type CacheWithLimitsOptions | undefined
```

**Include a reproducible code sample here, if possible:**

```js
Options.cacheWithLimits({
  MessageManager: {
    sweepInterval: 300,
    sweepFilter: LimitedCollection.filterByLifetime({
      lifetime: 1800,
      getComparisonTimestamp: e => e.editedTimestamp ?? e.createdTimestamp,
    }),
  },
});
```

**Further details:**

- discord.js version: v13.0.1
- Node.js version: v16.6.1
- Operating system: macOS Big Sur (11.5.1)
- Priority this issue should have – please be realistic and elaborate if possible: low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by mrjackyliang** [comment]
```
export interface Caches {
  ApplicationCommandManager: [manager: typeof ApplicationCommandManager, holds: typeof ApplicationCommand];
  BaseGuildEmojiManager: [manager: typeof BaseGuildEmojiManager, holds: typeof GuildEmoji];
  // TODO: ChannelManager: [manager: typeof ChannelManager, holds: typeof Channel];
  // TODO: GuildChannelManager: [manager: typeof GuildChannelManager, holds: typeof GuildChannel];
  // TODO: GuildManager: [manager: typeof GuildManager, holds: typeof Guild];
  GuildMemberManager: [manager: typeof GuildMemberManager, holds: typeof GuildMember];
  GuildBanManager: [manager: typeof GuildBanManager, holds: typeof GuildBan];
  GuildInviteManager: [manager: typeof GuildInviteManager, holds: typeof Invite];
  GuildStickerManager: [manager: typeof GuildStickerManager, holds: typeof Sticker];
  MessageManager: [manager: typeof MessageManager, holds: typeof Message];
  // TODO: PermissionOverwriteManager: [manager: typeof PermissionOverwriteManager, holds: typeof PermissionOverwrites];
  PresenceManager: [manager: typeof PresenceManager, holds: typeof Presence];
  ReactionManager: [manager: typeof ReactionManager, holds: typeof MessageReaction];
  ReactionUserManager: [manager: typeof ReactionUserManager, holds: typeof User];
  // TODO: RoleManager: [manager: typeof RoleManager, holds: typeof Role];
  StageInstanceManager: [manager: typeof StageInstanceManager, holds: typeof StageInstance];
  ThreadManager: [manager: typeof ThreadManager, holds: typeof ThreadChannel];
  ThreadMemberManager: [manager: typeof ThreadMemberManager, holds: typeof ThreadMember];
  UserManager: [manager: typeof UserManager, holds: typeof User];
  VoiceStateManager: [manager: typeof VoiceStateManager, holds: typeof VoiceState];
}
```

**Comment by mrjackyliang** [comment]
Aren't these supposed to be marked optional?

**Comment by ckohen** [comment]
The types are correct, it is saying the entire object is not assignable to CacheWithLimitsOptions, there should be a nested error that tells you why.
Here it is though, `SweepFilter<unknown, unknown>` isn't assignable to `SweepFilter<string, Message>`

**Comment by mrjackyliang** [comment]
> The types are correct, it is saying the entire object is not assignable to CacheWithLimitsOptions, there should be a nested error that tells you why.
> 
> Here it is though, `SweepFilter<unknown, unknown>` isn't assignable to `SweepFilter<string, Message>`

The example is copied from the documentation, which is weird. Does this have to do with my code editor?

**Comment by ckohen** [comment]
Are you still experiencing this, as I cannot reproduce it, I get no errors with the exact same code.

**Comment by mrjackyliang** [comment]
I upgraded my bot to use TypeScript, and the error no longer appears. I assume it's just the lack of type understanding with IDEs.
