### ISSUE TITLE
React with custom emoji fail

### ISSUE THREAD

**Issue by Xbirdfr** [discordjs/discord.js#6366]
Hi, 
I want to add a custom emoji as a reaction on a message

with unicode emoji, it work, but with custom it won't

this is the code :

```
//element contain the id of the emoji, on my test : '806586883240230913'

console.log(message.guild.emojis.cache.get(element));
message.react(message.guild.emojis.cache.get(element)).catch(console.error); 
```
I got this :

```js
GuildEmoji {
  animated: false,
  name: 'xbirdSga',
  id: '806586883240230913',
  deleted: false,
[...]
  requiresColons: false,
  managed: true,
  available: true,
  _roles: [],
  author: null
}
DiscordAPIError: Unknown Emoji
    at RequestHandler.execute ([...]/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push ([...]/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager.react ([...]/node_modules/discord.js/src/managers/MessageManager.js:193:5)
    at async Message.react ([...]/node_modules/discord.js/src/structures/Message.js:690:5) {
  method: 'put',
  path: '/channels/874332350975197224/messages/874363015594639460/reactions/xbirdSga%3A806586883240230913/@me',
  code: 10014,
  httpStatus: 400,
  requestData: { json: undefined, files: [] }
}
```

on the console.log, I got the emoji, but when I set this emoji on the react() function, I got a ' DiscordAPIError: Unknown Emoji '

**Further details:**

- discord.js version: 13.0.1
- Node.js version: v16.6.1
- Operating system: windows 10, using ubuntu on wsl into vscode for terminal
- Priority this issue should have – please be realistic and elaborate if possible: light

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Fyko** [comment]
I cannot reproduce this. My only guess is that the emoji is not accessible to the client.

**Comment by Xbirdfr** [comment]
> 
> 
> I cannot reproduce this. My only guess is that the emoji is not accessible to the client (the client is not in the server the emoji is from).

Hi, actually the bot is on the same server as the emoji :/

**Comment by DTrombett** [comment]
Did you try to fetch the emoji instead? Maybe the name is outdated or it was deleted.

**Comment by Xbirdfr** [comment]
> 
> 
> Did you try to fetch the emoji instead? Maybe the name is outdated or it was deleted.
> Also I see that the emoji is managed by an external service (`managed` property is true), so maybe the bot can't use it.

Managed was the key, this emoji come from twitch, so it can't be used by the bot

thanks a lot !
