### ISSUE TITLE
Unable to get reactions on previously sent messages

### ISSUE THREAD

**Issue by Aviation-7111** [discordjs/discord.js#6368]
**Please describe the problem you are having in as much detail as possible:**
When I try getting the reactions of a message from `<Message>.reactions.cache`, I'm left with an empty collection. I was told in the support server to open an issue if I could make it reproducible.

**Include a reproducible code sample here, if possible:**

```js
//Import Modules
const { Client, Intents, Collection } = require('discord.js');

//Create the Client
const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

//Message event
client.on('messageCreate', message => {
    //Check command
    if (message.content == "-run") {
        //Reply
        message.reply("Please react to this message with reactions I should react with.\n\nWhen you're done, say `done`.").then(emojiMessage => {
            //Collector Setup
            let filter = (m) => m.author.id == message.author.id
            collector = message.channel.createMessageCollector({ filter, time: 120 * 1000 })

            //On collect
            collector.on('collect', msg => {

                //Check content
                if (msg.content == "done") {
                    //Final reply
                    message.channel.send("Here's the reactions you sent earlier!").then(m => {
                        //Get the reactions from the message
                        let tempArray = Array.from(emojiMessage.reactions.cache.values())

                        //Prep
                        let reactionArray = []

                        //Import reactions based on name and id
                        for (let i = 0; i < tempArray.length; i++) {
                            //Check if string is emoji or not

                            //ID
                            if (containsEmojis(tempArray[i]["_emoji"].name) == false) {
                                reactionArray.push(tempArray[i]["_emoji"].id)

                                // EMOJI
                            } else {
                                reactionArray.push(tempArray[i]["_emoji"].name)
                            }
                        }

                        //React
                        for (let i = 0; i < reactionArray.length; i++) {
                            m.react(reactionArray[i])
                        }

                        console.log(reactionArray)
                        console.log(emojiMessage.reactions.cache)
                    })
                }
            })
        })
    }
})

client.login("TOKEN")
```

**Further details:**

- discord.js version: ^13.0.1
- Node.js version: v16.6.1
- Operating system: Windows 10 (64 bit) and Ubuntu Server (20.04)
- Priority this issue should have: Somewhat low, as most people get reactions via a collector, and I can modify the code to do so as well.

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS
- other: none

**Comment by elijaholmos** [comment]
I encountered this problem as well. Before I transitioned to `v13`, `Message.reactions.cache` always contained the real-time reaction data. After my transition to `v13`, however, it is not as reliable (consistently returning an empty Collection). I was able to fix the problem by fetching the message before checking the `reactions` cache. I haven't tested your code, but the principle behind the solution that worked for me would look like this:
```js
 // ...
 message.channel.send("Here's the reactions you sent earlier!").then(async m => {
 
     // solution: re-fetch the message before checking cache (note how this callback is now async)
     emojiMessage = await emojiMessage.fetch()
     
     //Get the reactions from the message
     let tempArray = Array.from(emojiMessage.reactions.cache.values())
     // ...
```

Hopefully this helps point you in the right direction. Ideally this is only a temporary solution, because it would be great to have the pre-`v13` functionality of real-time reaction caches.

**Comment by Aviation-7111** [comment]
That works perfectly with my code sample provided above.

I guess in a sense it wouldn't technically change to pre-`v13` functionality due to what caching is for. By always getting new emojis whenever requested from the cache, it would make it useless to have caching at all. Instead a method should be implemented to fetch/update emojis.

**Comment by Aviation-7111** [comment]
That works perfectly with my code sample provided above.

I guess in a sense it wouldn't technically change to pre-`v13` functionality due to what caching is for. By always getting new reactions whenever requested from the cache, it would make it useless to have caching at all. Instead a method should be implemented to fetch/update reactions, though I don't know if the only way of doing so is by fetching/updating the message in the Discord API. Perhaps you're meant to do the `fetch()` method on the message with the reactions to get the up-to-date data.
