### ISSUE TITLE
client.application returns null

### ISSUE THREAD

**Issue by moiteno** [discordjs/discord.js#6369]
**Please describe the problem you are having in as much detail as possible:**

I'm trying to set slash commands into my application but when I `console.log` client.application it returns null.

**Further details:**

- discord.js version: 13.0.0
- Node.js version: 16.6.1
- Operating system: Linux x64

**Relevant client options:**

- gateway intents: GUILDS, GUILD_MESSAGES

**Comment by almostSouji** [comment]
That is the reason for the `if (!client.application?.owner) await client.application?.fetch();` in this guide <https://discordjs.guide/interactions/registering-slash-commands.html> using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to early-return if application is not available.
