### ISSUE TITLE
Type Error with GuildMemberRoleManager

### ISSUE THREAD

**Issue by tobiO0310** [discordjs/discord.js#6372]
**Please describe the problem you are having in as much detail as possible:**
When using a GuildMemberRoleManager.cache it returns this error:
![image](https://user-images.githubusercontent.com/59401633/128843232-d06c2fac-3861-465b-b482-93bfa3ef3bcc.png)

I've tried reinstalling all packages (deleting node_modules and package-lock.json
I've already tried the code on multiple computers, the same result.

*Please tell me if it's something with my computers*

**Include a reproducible code sample here, if possible:**

```js
import Discord from "discord.js"
const client = new Discord.Client({ intents: [] })

client.on("ready", async () => {
  var guild = await client.guilds.fetch("646973646753103875")
  var me = await guild.members.fetch("328485995437883393")
  console.log(me.roles.cache)
})

client.login("WORKING_TOKEN")
```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Small, since it could be an issue with my computer
 
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Keke27210** [comment]
> **Please describe the problem you are having in as much detail as possible:**
> When using a GuildMemberRoleManager.cache it returns this error:
> ![image](https://user-images.githubusercontent.com/59401633/128843232-d06c2fac-3861-465b-b482-93bfa3ef3bcc.png)
> 
> I've tried reinstalling all packages (deleting node_modules and package-lock.json
> I've already tried the code on multiple computers, the same result.
> 
> _Please tell me if it's something with my computers_
> 
> **Include a reproducible code sample here, if possible:**
> 
> ```js
> import Discord from "discord.js"
> const client = new Discord.Client({ intents: [] })
> 
> client.on("ready", async () => {
>   var guild = await client.guilds.fetch("646973646753103875")
>   var me = await guild.members.fetch("328485995437883393")
>   console.log(me.roles.cache)
> })
> 
> client.login("WORKING_TOKEN")
> ```
> 
> **Further details:**
> 
> * discord.js version: 13.0.1
> * Node.js version: 16.6.1
> * Operating system: Windows 10
> * Priority this issue should have – please be realistic and elaborate if possible: Small, since it could be an issue with my computer
> 
> **Relevant client options:**
> 
> * partials: none
> * gateway intents: none
> * other: none

`GUILDS` intent expected for this to work - please use the Discord server for those questions in the future.
