### ISSUE TITLE
Randomly Disconnecting From Discord With No Error

### ISSUE THREAD

**Issue by TheTurkeyDev** [discordjs/discord.js#6391]
**Please describe the problem you are having in as much detail as possible:**

Since upgrading to Discord v13, my bot Just disconnects from Discord randomly. I am seeing no errors or warning and after turning on the debug log I notice the Heartbeat just stops with no further messages. This issue is pretty frequent happening multiple times a day. When this happens, the Systemd service is still running and nothing is crashed or frozen, just the bot has disconnected from Discord. I don't really have any logs or anything to show because there's no errors or anything to show besides the Heartbeat timer just stopping. Let me know if there is anything further I can do to help provide more info as I know there is really nothing to go off of here. I'm just as lost and confused as you.

Log example:
[WS => Shard 0] Heartbeat acknowledged, latency of 111ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 116ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 111ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 111ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 110ms.
* Log stops here and nothing logs after this until I restart the service

**Include a reproducible code sample here, if possible:**
https://github.com/TheTurkeyDev/Discord-Games That's the repo that holds my code for all of this. The live version uses a fork of that though to add in a DB connection, but beyond that is the same. No idea what is causing this issue though

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Linux (Ubuntu 16.04.6)
- Priority this issue should have – please be realistic and elaborate if possible: I mean for me kinda high, but this seems to not be a common thing, so probably low.

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS
- other: none

**Comment by TheTurkeyDev** [comment]
This happens multiple times a day at this point. I've updated to v13.1 and it still occurs. Dug through the Discord JS code some and I don't see anything wrong. It's as if [this setInterval](https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/client/websocket/WebSocketShard.js#L534) just stops executing its self. I don't see any other path that stops it.

**Comment by vladfrangu** [comment]
That usually means your code is hanging somewhere... Even in a hypothetical case where we'd stop sending heartbeats, Discord would kill the ws, we'd notice and reconnect... Try inspecting your process CPU usage and see if you can find what causes it to hang! If you can repro this with just a discord.js basic bot, let us know too!

**Comment by TheTurkeyDev** [comment]
I think I have traced it down to an infinite loop on my end that is indeed causing the issue. Thank you for your help!
