### ISSUE TITLE
Add ability to send single embeds “old way” (Backward Compatibility with v12)

### ISSUE THREAD

**Issue by Vista1nik** [discordjs/discord.js#6393]
**Is your feature request related to a problem? Please describe.**
My bot have 100+ commands and every command have `message.channel.send({embed: {/* embed here */}})`. 

After upgrade to discord.js v13, I need to replace every single `message.channel.send` to make embeds work again.

**Describe the ideal solution**
I want to return old `embed` property to `message.channel.send` to enable backward compatibility with v12 code.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by DTrombett** [comment]
This will not readded. A reason can be that bots can send multiple embeds in a message so it can't be replaced. Adding the embed property (keeping the embeds one) might cause problems, like if we use `message.channel.send({ embed: embed1, embeds: [embed2, embed3] })`

**Comment by Vista1nik** [comment]
> This will not readded. A reason can be that bots can send multiple embeds in a message so it can't be replaced. Adding the embed property (keeping the embeds one) might cause problems, like if we use `message.channel.send({ embed: embed1, embeds: [embed2, embed3] })`

DiscordJS can throw an error when both `embed` and `embeds` properties in use.

**Comment by vladfrangu** [comment]
Please read this issue for more information. https://github.com/discordjs/discord.js/issues/5771

There is no function overload in JS 🙂

**Comment by iCrawl** [comment]
Won't happen.
