### ISSUE TITLE
Slash Command Builder doesnt set the Type correctly on Subcommand

### ISSUE THREAD

**Issue by eliteSchwein** [discordjs/discord.js#6397]
**Please describe the problem you are having in as much detail as possible:**
The Slash Command Builder doesnt set Type
**Include a reproducible code sample here, if possible:**
Its the Admin Command
https://img.eliteschw31n.de/PEBE2/JOxeKAgo42.png
https://img.eliteschw31n.de/PEBE2/fUXiFEDO37.png

```js
// Place your code here
```

**Further details:**

- discord.js version:13.0.1
- Node.js version:16.6.1
- Operating system:raspbian
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by eliteSchwein** [comment]
return command.toJSON fixed it

**Comment by vladfrangu** [comment]
Can you open an issue about this in /builders? I thought toJSON was called recursively when stringifying a class with it but I was wrong.. ideally you shouldn't have to call toJSON()..
