### ISSUE TITLE
GuildMemberRoleManager.js this.member._roles.includes is not a function

### ISSUE THREAD

**Issue by dahool** [discordjs/discord.js#6423]
**Please describe the problem you are having in as much detail as possible:**

```
....\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:36
    return this.guild.roles.cache.filter(role => this.member._roles.includes(role.id)).set(everyone.id, everyone);
                                                                    ^

TypeError: this.member._roles.includes is not a function
    at d:\workspace\maiabot\app\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:36:69
    at Map.filter (d:\workspace\maiabot\app\node_modules\@discordjs\collection\dist\index.js:159:17)
    at GuildMemberRoleManager.get cache [as cache] (d:\workspace\maiabot\app\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:36:35)
    at GuildMember.get permissions [as permissions] (d:\workspace\maiabot\app\node_modules\discord.js\src\structures\GuildMember.js:185:39)
    at BotCommander.invokeCommand (.....\app\botclient.js:315:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Include a reproducible code sample here, if possible:**

```js
member.permissions.has(['ADMINISTRATOR','MANAGE_GUILD','MANAGE_ROLES'])
```

where member is an instance of ```GuildMember```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Win 10
- Priority this issue should have – please be realistic and elaborate if possible: HIGH

**Relevant client options:**

- partials: CHANNEL
- gateway intents: 	Intents.FLAGS.GUILDS,
	Intents.FLAGS.GUILD_PRESENCES,
	Intents.FLAGS.GUILD_MEMBERS,
	Intents.FLAGS.GUILD_MESSAGES,
	Intents.FLAGS.GUILD_WEBHOOKS,
	Intents.FLAGS.DIRECT_MESSAGES
- other: none

**Comment by dahool** [comment]
To add more info, looks like roles don't work either, same error while executing `console.log(member.roles.cache)`;

**Comment by VoltrexMaster** [comment]
Cannot reproduce, seems like an instance of the `GuildMember` class was instantiated without any role data. You should try logging `member._roles` and see what it actually returns and continue debugging from there, if you're actually creating a new instance of the `GuildMember` class, you should pass valid data.

**Comment by dahool** [comment]
my bad. I was migrating an interaction from v12 and it seems v13 handle interaction.member differently. It's solved now. Sorry for the missleading report.

**Comment by Mouradif** [comment]
I'm having this issue on v14.1.2, using `member._roles` seems to do the trick for now

**Comment by Jiralite** [comment]
Then make a new issue. This is far too old.
