### ISSUE TITLE
Using broadcastEval in v13 can no longer accept outside variables

### ISSUE THREAD

**Issue by KevinNovak** [discordjs/discord.js#6424]
**Please describe the problem you are having in as much detail as possible:**
In v12 of discord.js, you used to be able to call the `broadcastEval` method, while providing outside variables like so:

```js
let myStatus = "idle";

shardManager.broadcastEval(
    `this.user.setStatus(${myStatus});`
);
```

Now with v13, `broadcastEval` takes a function instead, so the above code could be refactored like so:
```js
let myStatus = "idle";

shardManager.broadcastEval((client) => {
    client.user.setStatus(myStatus);
});
```

However the above code does not work as expected. When running, the following error occurs:
`Error [ReferenceError]: myStatus is not defined`

From what I've seen, the function inside `broadcastEval` cannot contain any outside variables. I suspect this has to do with how scope works in javascript, but I've yet to find a way around this.

I'm also not the only one to run into this issue, I found a couple other unsolved posts in the djs-help channels:
![image](https://user-images.githubusercontent.com/11231402/129431117-d6394bdb-ff87-49c5-b1a7-1d2f8e5fd271.png)
![image](https://user-images.githubusercontent.com/11231402/129431120-8c18e636-6be7-403a-ac25-2b51973336e9.png)
![image](https://user-images.githubusercontent.com/11231402/129431121-f60b1907-76a3-4c37-b276-0a0a59b1963f.png)

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by Keke27210** [comment]
That's completly expected and normal, and this is why the method allows you to pass context variables in its option.
Please use `options.context` to pass all the data that you need for your function to work.
<https://discord.js.org/#/docs/main/stable/class/ShardingManager?scrollTo=broadcastEval>
And please use the Discord server for those kind of questions in the future, as this is not a bug in itself.

**Comment by KevinNovak** [comment]
Thank you for the response, I didn't see that there was a context option, sorry about that.
