### ISSUE TITLE
deferReply() not listed in Docs @CommandInteraction

### ISSUE THREAD

**Issue by Taelyn** [discordjs/discord.js#6428]
deferReply() isnt listed in the CommandInteraction Docs. 
Its listed in the ButtonInteraction Docs

**Further details:**

- discord.js version: v13.1
- Node.js version: 16.6.1
- Operating system: Windows 10 x64

**Comment by Jiralite** [comment]
This is fixed in main already via #6412!

**Comment by Taelyn** [comment]
Thanks! Missed that, then ill close this report :)
