### ISSUE TITLE
Messages lose their reaction manager when another message references them

### ISSUE THREAD

**Issue by Sergiovan** [discordjs/discord.js#6431]
**Please describe the problem you are having in as much detail as possible:**
When a message "X" with reactions is referenced by a different message (e.g. via reply or via fetching an old reply) , message "X" has its reaction manager overwritten and will lose access to reactions from before that point.

**Include a reproducible code sample here, if possible:**

```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

client.on('messageCreate', async message => {
    if (message.content == "?test") {
        
        /* Add 2 reactions, check they're there */
        await message.react('❤️');
        await message.react('💙');
        let reacts = message.reactions.resolve('❤️');
        console.log(reacts.me); // true
        console.log(message.reactions.cache); // Collection(2) [Map] { ❤️ and 💙 reactions }

        /* Reply to reacted-to message */
        await message.reply("This is a reply :)");

        /* Check reactions, they've disappeared. After a restart the reactions will be visible again */
        reacts = message.reactions.resolve('❤️');
        console.log(reacts?.me ?? 'Nope'); // 'Nope'
        console.log(message.reactions.cache); // Collection(0) [Map] {}

        /* React "again", this updates the reactions */
        await message.react('❤️');
        reacts = message.reactions.resolve('❤️');
        console.log(reacts.me); // true
        console.log(message.reactions.cache); // Collection(1) [Map] { ❤️ reaction }
    }
});

client.login("DISCORD_TOKEN");
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.1
- Operating system: Manjaro Linux [x86_64] (5.10.56-1-MANJARO)
- Priority this issue should have – please be realistic and elaborate if possible: Low-Medium

**Relevant client options:**

- partials: none
- gateway intents: Same as in code snippet (`GUILDS`, `GUILD_MESSAGES`, `GUILD_MESSAGE_REACTIONS`)
- other: none
- I have also tested the issue on latest main; Commit hash: `71fdf6fae0457bc5f2900a37cc2d28c587e7e54a`

**Comment by SpaceEEC** [comment]
Looks like this bug was introduced in #6071.

Some relevant code paths:
Incoming message referenced
https://github.com/discordjs/discord.js/blob/71fdf6fae0457bc5f2900a37cc2d28c587e7e54a/src/structures/Message.js#L306-L308
Patched through here
https://github.com/discordjs/discord.js/blob/71fdf6fae0457bc5f2900a37cc2d28c587e7e54a/src/managers/CachedManager.js#L48
Incorrectly overwrites reactions here
https://github.com/discordjs/discord.js/blob/71fdf6fae0457bc5f2900a37cc2d28c587e7e54a/src/structures/Message.js#L192-L197
