### ISSUE TITLE
Interaction.fetchReply()'s returned message doesn't include a createMessageComponentCollector method

### ISSUE THREAD

**Issue by TSLARoadster** [discordjs/discord.js#6440]
**Please describe the problem you are having in as much detail as possible:**

When attempting to start a messageComponentCollector from a message fetched using interaction.fetchReply(), it won't work in DMs (but it WILL work in any other text channel that I've tested it in).

**Include a reproducible code sample here, if possible:**

```js
// interaction.isCommand() = true
// context is asynchronous

const msg = await interaction.fetchReply()

const filter = i => i.user.id === interaction.user.id
const collector = msg.createMessageComponentCollector({ filter })
// in a text channel, collector and it's emitted events will work

// in a dm channel: TypeError: msg.createMessageComponentCollector is not a function
// any sent interactions will fail
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.1
- Operating system: Windows
- Priority this issue should have: Medium
- Reason for this priority: I believe that using collectors/events for buttons/other message components is a decently "popular" way to do so in a bot, and the fact that it only works in text channels and not DMs for no apparent reason makes it a somewhat high priority

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, DIRECT_MESSAGES
- other: none

- I have also tested the issue on latest main; Commit hash: `71fdf6fae0457bc5f2900a37cc2d28c587e7e54a`

**Comment by monbrey** [comment]
Since you've specified no intents and no partials, and the issue is only in DMs, I'm going to guess that you need the `CHANNEL` partial so it can create a Message in that channels cache instead of emitting a raw object.

**Comment by TSLARoadster** [comment]
> Since you've specified no intents and no partials, and the issue is only in DMs, I'm going to guess that you need the `CHANNEL` partial so it can create a Message in that channels cache instead of emitting a raw object.

My bad for forgetting about intents! I updated the original message, but when i get back to my bot I’ll try it with the `CHANNEL` partial

**Comment by TSLARoadster** [comment]
Yep, enabling the `CHANNEL` partial was able to solve the issue, thanks for the assistance!
