### ISSUE TITLE
Missing Permissions on channel update after all needed tests

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#6446]
**Please describe the problem you are having in as much detail as possible:**

I catch a **Missing Permissions** error on a channel edit when all needed checks are done.
 - `<GuildChannel>.manageable` is tested
 - `<Role>.editable` is not tested but we know that we have the `MANAGE_ROLES` permission because we create a role. The target role has just be created so under the position of the bot.
 
Here is a sentry report error: https://sentry.draftbot.fr/share/issue/1309451c008c4269bd2e4a3a85294a31/

**Include a reproducible code sample here, if possible:**

```js
const role = await member.guild.roles.create({
  name: 'Not verified',
  reason: 'Role required for members who have not completed the captcha.',
});

for (const channel of member.guild.channels.cache.array()) {
    if(!channel.manageable) continue;
    await channel.updateOverwrite(role, { VIEW_CHANNEL: false }, {
        type: 0,
        reason: 'Update of the channel for the implementation of the captcha.',
    });
}
```

**Further details:**

- discord.js version: **v13.0.0-dev** [this commit](https://github.com/discordjs/discord.js/commit/e980948de55e91e59c9e3293ac76bc645a058a53)
- Node.js version: **v14**
- Operating system: **Debian GNU/Linux 10 (buster)**
- Priority this issue should have – please be realistic and elaborate if possible: **Not priority**

**Relevant client options:**

- partials: MESSAGE, REACTION, GUILD_MEMBER
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS
- other: none

- Its a production error have only tested the issue on v13 version; Commit hash: `e980948de55e91e59c9e3293ac76bc645a058a53`

**Comment by NotSugden** [comment]
seems there is a missing `this.viewable` check for voice channels
https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/structures/GuildChannel.js#L514-L518 the bot needs to have the permission that its trying to overwrite

**Comment by DraftProducts** [comment]
🤔 Yeah, ok, it's coming from voice channels 👍 
I make a PR now !
