### ISSUE TITLE
Filter .addChannelOption

### ISSUE THREAD

**Issue by HypaCNH** [discordjs/discord.js#6457]
**Is your feature request related to a problem? Please describe.**
So, I need the option .addChannelOption for a sub command. But I only need all 'GUILD_TEXT' channels. Nothing else. But I am not able, to filter all channels for only 'GUILD_TEXT' channels, so the user is only able to choose them and is not able to choose any other channel type.

**Describe the ideal solution**
.addChannelOption((option) => option.filter(blablabla))

![image](https://user-images.githubusercontent.com/72663865/129613667-b09074fd-267c-4c4c-a794-23b7d930bc54.png)

I would be happy, if your able to filter the channels, BEFORE the interaction was used.

**Comment by Dev-CasperTheGhost** [comment]
[Discord has plans to make an option for channel types](https://github.com/discord/discord-api-docs/discussions/3581). Till then, there most likely won't be an option built into Discord.js

**Comment by HypaCNH** [comment]
@Dev-CasperTheGhost Ah, thank you!

**Comment by ImRodry** [comment]
For now you will have to filter these yourself with `channel.isText()` until Discord adds the feature that Casper mentioned above which will probably be a new option type that will be supported by the library once it arrives. This can then be closed since it will be added anyway
