### ISSUE TITLE
ReactionCollector filter is called twice

### ISSUE THREAD

**Issue by elijaholmos** [discordjs/discord.js#6461]
**Please describe the problem you are having in as much detail as possible:**
Upon adding a new reaction to a message with a `ReactionCollector` on it, the collector's filter function is called twice. This issue began with `v13.0.0`. I've checked the source code and found that the filter is called once to determine whether the `create` event should be emitted...
https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/ReactionCollector.js#L104-L106
...and again in a parent method, before emitting the `collect` event
https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/interfaces/Collector.js#L100-L108

As a user of the library, it would be ideal if the filter function is only called once per reaction creation. In my situation, I call a third-party API in my collector's filter. The call is only intended to be placed once per reaction collection, not twice.

**Include a reproducible code sample here, if possible:**
```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

client.on('messageCreate', (msg) => {
    msg.createReactionCollector({
        filter: function(r, u) {
            console.log('in filter');   //should appear twice
            return false;
        },
    });
});

client.login("DISCORD_TOKEN");
```

**Further details:**

- discord.js version: `13.1.0`
- Node.js version: `16.6.1`
- Operating system: Windows 10 Version 21H1
- Priority this issue should have – please be realistic and elaborate if possible: Low, is not a critical problem

**Relevant client options:**

- partials: none
- gateway intents: Same as in code snippet (`GUILDS`, `GUILD_MESSAGES`, `GUILD_MESSAGE_REACTIONS`)
- other: none

**Comment by alperb** [comment]
As far as I've understood, filter check in [Collector#L100](https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/interfaces/Collector.js#L100-L108)  is not necessary however if we want to remove this check, we must do some changes in the [ReactionController#L108](https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/ReactionCollector.js#L108). Something like this may work I guess:

```js
if (reaction.count === 1 && (await this.filter(reaction, user, this.collected))) {
      this.emit('create', reaction, user);
      return ReactionCollector.key(reaction);
}   
```

So, `ReactionCollector.collect()` will return `undefined` if reaction is not valid and Collector.handleCollect will get `undefined` from `const collect = await this.collect(...args);`

Correct me if I'm wrong.
