### ISSUE TITLE
Cannot followUp() with ephemeral true if initial deferReply() used ephemeral false

### ISSUE THREAD

**Issue by arepp23** [discordjs/discord.js#6465]
The basic premise is that if you deferReply() on an interaction, you cannot then followUp using the "opposite" ephemeral flag. That is- if you call `deferReply({ephermeral:true})` , using `followUp({ephemeral: false}) `will still only show the followup to the interacting user. This is the same in the opposite direction false -> true. 

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: n/a
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by muchnameless** [comment]
It is not possible to change the ephemeral state of a message (https://github.com/discord/discord-api-docs/issues/2735#issuecomment-813705608) and `followUp` directly after a `deferReply` has the same effect as `editReply`

**Comment by arepp23** [comment]
That is rather unfortunate but thanks for the info.

**Comment by ImRodry** [comment]
If you want to followUp with a non ephemeral reply you need to edit the original one first. Also please close your issues after they're resolved
