### ISSUE TITLE
`<Interaction>.followUp()`  returns a message but methods won't work if it's ephemeral

### ISSUE THREAD

**Issue by fasterplayer** [discordjs/discord.js#6467]
When using `.followUp()` on an interaction, a message is returned. This message isn't identified as an interactrion (message.interaction = null). So later, if i want to edit this message, i'm not able to except if i do a `interaction.update()`.

**Please describe the problem you are having in as much detail as possible:**

I'm creating a collector on the `.followUp()` returned Promise<Message>. Collector is working fine but if the message is deleted (ephemeral reply in my case), the value `message.deleted` is still false on the Message object and calling a `.edit()` on this message returns a `DiscordAPIError: Unknown Message` as the message is actually a Interaction Ephemeral reply. Maybe needs a new message type `InteractionMessage`  so we can't use standard message method or adding an ephemeral property to messages? Because we can't edit ephemeral messages except doing it through the `interaction.update()`

I think that the major part of this issue is that it's ephemeral.

**Include a reproducible code sample here, if possible:**
interaction.deferReply({ephemeral: true})
  const confirmationMessage: Message = await interaction.followUp({content: 'test',components: [row(false, false, false)], ephemeral: true})
  const confirmationCollector = confirmationMessage.createMessageComponentCollector({componentType: 'BUTTON', time: 6000, max: 2})

Below is the Message object returned from `confirmationMessage`.

```js
<ref *1> Message {
  channelId: '877310098429599744',
  guildId: '744929326058700821',
  deleted: false,
  id: '877313338571378789',
  type: 'REPLY',
  system: false,
  content: 'test',
  author: ClientUser {
    id: '820477368044879913',
    bot: true,
    system: false,
    flags: UserFlags { bitfield: 0 },
    username: 'Caprice Dev',
    discriminator: '4277',
    avatar: '730f58043d3464f7ab985b6b4b759610',
    verified: true,
    mfaEnabled: true
  },
  pinned: false,
  tts: false,
  nonce: '877313339414282240',
  embeds: [],
  components: [ MessageActionRow { type: 'ACTION_ROW', components: [Array] } ],
  attachments: Collection(0) [Map] {},
  stickers: Collection(0) [Map] {},
  createdTimestamp: 1629238199609,
  editedTimestamp: null,
  reactions: ReactionManager { message: [Circular *1] },
  mentions: MessageMentions {
    everyone: false,
    users: Collection(0) [Map] {},
    roles: Collection(0) [Map] {},
    _members: null,
    _channels: Collection(0) [Map] {},
    crosspostedChannels: Collection(0) [Map] {},
    repliedUser: null
  },
  webhookId: '820477368044879913',
  groupActivityApplication: null,
  applicationId: '820477368044879913',
  activity: null,
  flags: MessageFlags { bitfield: 64 },
  reference: {
    channelId: '877310098429599744',
    guildId: '744929326058700821',
    messageId: '877310103815077999'
  },
  interaction: null
}
```

**Further details:**

- discord.js version: 13.2.0-dev.1629202082.9a833b1
- Node.js version: 16.6.1
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: ['CHANNEL', 'GUILD_MEMBER', 'MESSAGE', 'REACTION', 'USER']
- gateway intents: ['DIRECT_MESSAGES', 'GUILDS', 'GUILD_INTEGRATIONS', 'GUILD_MESSAGES', 'GUILD_WEBHOOKS']
- other: none

**Comment by monbrey** [comment]
This is entirely expected - ephemeral followUps cannot be edited or deleted. You also don't receive any event when dismissed, so we can't mark them as deleted either.

We could include ephemeral checking in `message.edit()` however you're still going to have an error thrown - it would just be by discord.js rather than by the Discord API.

Regarding an "ephemeral property", it's a flag. `message.flags.has(MessageFlags.EPHEMERAL)`

**Comment by fasterplayer** [comment]
> This is entirely expected - ephemeral followUps cannot be edited or deleted. You also don't receive any event when dismissed, so we can't mark them as deleted either.
> 
> We could include ephemeral checking in `message.edit()` however you're still going to have an error thrown - it would just be by discord.js rather than by the Discord API.
> 
> Regarding an "ephemeral property", it's a flag. `message.flags.has(MessageFlags.FLAGS.EPHEMERAL)`

Thanks for the clarification. The advantage of making a check is that it would prevent sending request to the discord API knowing that we can't do this action. 

But in my case, the interaction should be fullfilled with the interaction details as it's an interaction related message? 

As mentionned here: https://discord.js.org/#/docs/main/stable/typedef/MessageInteraction
The message is a reply to an interaction so it should have the interaction details that it's related to.

**Comment by fasterplayer** [comment]
I also noticed that the difference between a standard Message and an interaction reply is that there is a webhook id attached to it. Can't we use this to turn the `<Message>.edit()` into an `<Interaction>.update()` or something like this?

**Comment by monbrey** [comment]
`followUp` is not always a direct reply to an interaction though - if you defer first it does edit that message, but anything else is essentially a new one. If `Message#interaction` is null, it's because the API didn't provide that data, suggesting the API doesn't consider it a reply.

You also cant use `<Interaction>.update()` to edit any existing replies - that's purely for the first-response to a Button or SelectMenu interaction.

**Comment by fasterplayer** [comment]
> `followUp` is not always a direct reply to an interaction though - if you defer first it does edit that message, but anything else is essentially a new one. If `Message#interaction` is null, it's because the API didn't provide that data, suggesting the API doesn't consider it a reply to one.
> 
> You also cant use `<Interaction>.update()` to edit any existing replies - that's purely for the first-response to a Button or SelectMenu interaction.

I came into this issue when trying to edit the messageCollector message. I will go with an `interaction.update()` instead.

Thanks!
