### ISSUE TITLE
Disabling the GUILD_PRESENCES intent doesn't cache members on startup

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#6475]
**Please describe the problem you are having in as much detail as possible:**
I noticed that if you have the GUILD_PRESENCES intent and try to access the cache of members of any of your guilds, you will have every member in it available, however, once you remove this intent, you only have the client user on that guild's cache before fetching its members

**Include a reproducible code sample here, if possible:**
```ts
import Discord from "discord.js"
const Client = new Discord.Client({
	intents: [
		Discord.Intents.FLAGS.GUILDS
	]
})

client.on("ready", () => {
	const guild = client.guilds.cache.get("your guild id here")
	console.log(guild.members.cache.size) //Expected output: 1
})
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low since there is a relatively easy workaround, it's just a minor inconvenience

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, [GUILD_PRESENCES]
- other: none
- I have also tested the issue on latest main; Commit hash: `d6e6244336ccdcdac9a06ab453debe76b13c9bde`

**Comment by monbrey** [comment]
This is the expected gateway behaviour. Without the intent, Discord does not provide any guild members in the initial payload.

**Comment by ImRodry** [comment]
Really? Shouldn’t GUILD_MEMBERS be the intent that gives us the guild member data?

**Comment by advaith1** [comment]
the members who can be sent in the initial list depends on their presence, so it does make sense

although both Rodry and monbrey have said incorrect things here.

> I noticed that if you have the GUILD_PRESENCES intent and try to access the cache of members of any of your guilds, you will have every member in it available

this is only true if the guild has under 50/large_threshold members

> Without the intent, Discord does not provide any guild members in the initial payload.

no, it will provide some members

---

The docs explain which members will be sent in different scenarios: https://discord.com/developers/docs/topics/gateway#request-guild-members

**Comment by ImRodry** [comment]
I just described the issue as I observed it but that explanation does make sense, just a minor inconvenience now that I’m choosing not to use this intent but thank you for your explanation. I’ll close this since the “bug” is not related to the library
