### ISSUE TITLE
Bot does not appear to be receiving interactionCreate events

### ISSUE THREAD

**Issue by ellisormatt** [discordjs/discord.js#6479]
**Please describe the problem you are having in as much detail as possible:**

- When setting up a new bot, it does not appear that the bot is seeing any commands in a server that I have added the bot to
- The bot does not console.log anything that I am inputting into chat channels that the bot is present in
- after running the application, I see the `Ready!` message get logged to the console
- I followed all steps on the discordjs.guide up to [this point](https://discordjs.guide/creating-your-bot/#resulting-code)

These are the permissions I used when adding the bot to the server:
![image](https://user-images.githubusercontent.com/54109533/130265090-2c9bb040-1c87-45eb-865a-c899919651dd.png)
![image](https://user-images.githubusercontent.com/54109533/130265102-0000002c-15fa-4bfc-9d78-7425cb33bceb.png)

**Code sample::**

```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('interactionCreate', interaction => {
	console.log(interaction);
});

client.login('token');
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.7.0
- Operating system: tested on Ubuntu and Windows
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DTrombett** [comment]
Do you already have slash commands for your bot? At that point of the guide slash commands aren't covered yet.

**Comment by ellisormatt** [comment]
I do not, I don't have any commands configured. I would think that with the code in the state that it is in as shown above, I would at least see some output logged to the console when typing anything in a chat channel that the bot is present in. Is this not the case?

**Comment by Jiralite** [comment]
That would fire the `messageCreate` event - a message. Interactions (slash commands, context menus, buttons, select menu) will fire the `interactionCreate` event,

**Comment by ellisormatt** [comment]
Here is my updated code:
```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('interactionCreate', interaction => {
	console.log(interaction);
});

client.on('messageCreate', message => {
	console.log(message);
});

client.login('token');
```

I still do not see anything logged to the console when typing messages in a chat channel with the bot. If I just have an incomplete understanding of how the bot works, I might need to finish walking all the way through the guide. I stopped[ at this point](https://discordjs.guide/creating-your-bot/adding-more-commands.html#server-info-command) because I was not getting any kind of feedback in the console last night when I was working on setting this up.

**Comment by xMooddyy** [comment]
You need the `GUILD_MESSAGES` intent to receive message events.

**Comment by ellisormatt** [comment]
> You need the `GUILD_MESSAGES` intent to receive message events.

This fixed the issue, the bot is now logging information to the console. I believe this means the documentation should be updated, unless I am alone in coming across this problem. It was not clear to me that I needed to add this intent to the client config and the documentation seemed to imply that I should be getting info logged to the console with the code in the state it is as shown [here](https://discordjs.guide/creating-your-bot/#listening-for-interactions). The documentation specifically directs the reader to test out a command to see that information gets logged to the console.

**Comment by ellisormatt** [comment]
Here is the complete code after I added the `GUILD_MESSAGES` intent that caused the bot to start receiving message events. The only thing that was added was the intent.

```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('interactionCreate', async interaction => {
	console.log(interaction);
});

client.login('token');
```

**Comment by xMooddyy** [comment]
Registering slash commands is covered later in the guide [here](https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands). Intents is also covered in the guide [here](https://discordjs.guide/popular-topics/intents.html#privileged-intents).

**Comment by ellisormatt** [comment]
Thanks for the info.
