### ISSUE TITLE
Threads with discord.js

### ISSUE THREAD

**Issue by Randomuser8181** [discordjs/discord.js#6480]
**Please describe the problem you are having in as much detail as possible:**

Threads can execute commands, for example if a new thread is named "!help" and a bot has that command, it will respond, now if someone uses !ban or other command it will also respond regardless of the permissions of the person who made the thread.

**Include a reproducible code sample here, if possible:**

```js
// No code
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.7.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: High, since regardless of the author's perms it will execute the command.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by wakfi** [comment]
I can repro, only when the thread is started on an un-cached message.

**Comment by Sniped** [comment]
I can reproduce something to this effect, where whenever a thread is created both the `threadCreate` event and `messageCreate` events are emitted. The message object in the `messageCreate` event seems to have a content string that is the same as the name of the thread created. [This repo](https://github.com/Sniped/thread-test) reproduces what appears to be causing this bug. 

It looks like whenever you thread on a cached message, a message event is emitted with no content, and whenever you thread on an uncached message, two message events are emitted. One of these message events has no content, or an empty string, and the other has the thread name as its content.

**Comment by ImRodry** [comment]
When a thread is created, a message of type THREAD_CREATED is sent so this behavior is expected. You have to run your own checks to prevent this from happening. Please send all future questions on the [Discord server](https://discord.gg/djs) in the future so as to not clog the issue tracker
