### ISSUE TITLE
Button's or select menu's animated property can be more specific

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6483]
**Please describe the problem you are having in as much detail as possible:**
The `.animated` property is only sent across if it is actually animated. Right now, if it is not sent across, it will be `undefined`. This could default to `false` instead.

Under the hood, it looks like they call this utility method:
https://github.com/discordjs/discord.js/blob/d6e6244336ccdcdac9a06ab453debe76b13c9bde/src/util/Util.js#L301-L313
Since `animated` there was `undefined`, it shows as such. But for components, this can be specified as `false`.

**Include a reproducible code sample here, if possible:**
```JavaScript
<Client>.channels.resolve("channel_id").send({
  content: "content",
  components: [
    {
      type: "ACTION_ROW",
      components: [
        {
          type: "BUTTON",
          style: "PRIMARY",
          label: "label",
          customId: "customId",
          emoji: "non_animated_emoji",
          disabled: false
        }
      ]
    }
  ]
}).then(message => console.log(message.components[0].components[0]));
```
<details>
<summary>Response</summary>

```JavaScript
MessageButton {
  type: 'BUTTON',
  label: 'label',
  customId: 'customId',
  style: 'PRIMARY',
  emoji: { id: 'id', name: 'name', animated: undefined },
  url: null,
  disabled: false
}
```
</details>

**Further details:**
- discord.js version: 13.2.0-dev
- Node.js version: 16.6.1
- Operating system: macOS 11.5.1
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**
- partials: none
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS
- other: none
- I have also tested the issue on latest main; Commit hash: d6e6244336ccdcdac9a06ab453debe76b13c9bde

**Comment by ImRodry** [comment]
Why not just make a PR then

**Comment by Jiralite** [comment]
I am not sure what the right approach would be!

**Comment by ImRodry** [comment]
I mean it would probably be semver major but if you know how to do it there is no reason not to
