### ISSUE TITLE
Bot Responded to Threads Name as commands

### ISSUE THREAD

**Issue by Alixy-Mizuki** [discordjs/discord.js#6487]
![image](https://user-images.githubusercontent.com/86276165/130315250-fa22ef02-5ee0-4688-82dc-732d421df043.png)
Like the picture shown above it responded to `?help` as like it a message instead of channel. and if the code uses `message.reply` 
as replies it'll send this on console and the bot crash 
```js
DiscordAPIError: Invalid Form Body
message_reference: Cannot reply to a system message
```

**Further details:**
- discord.js version: v13.0.1
- Node.js version: v16.6.1
- Operating system: I use replit but i think it x64

**Relevant client options:**

- partials: none
- gateway intents: GUILD, GUILD_MESSAGES
- other: none

**Comment by SuperchupuDev** [comment]
check for the message type, not a discord.js issue, next time try to ask in the discord server

**Comment by DTrombett** [comment]
I think this is expected.
You can only reply to "normal" messages so messages with type `DEFAULT` or `REPLY`.
Discord sends system messages in channels, like the one you showed in the picture. In that case, the type of the message is `THREAD_CREATED`, which is a system message and cannot be replied to.

**Comment by Alixy-Mizuki** [comment]
oh okay
