### ISSUE TITLE
Commands and interactions dont register

### ISSUE THREAD

**Issue by erdemozturkfun** [discordjs/discord.js#6489]
**Please describe the problem you are having in as much detail as possible:**
Im having issue with registering commands or interactions.
The code runs without errors but /ping command doesnt show up in / commands.

**Include a reproducible code sample here, if possible:**

```js
// index.js
const {Client, Intents} = require('discord.js');
const { token } = require('./config.json');


const client = new Client({
	intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES],
});

client.once('ready', () => {
	console.log('Ready!');
});

client.on('interactionCreate', async interaction => {
	if (!interaction.isCommand()) return;

	if (interaction.commandName === 'ping') {
		await interaction.reply('Pong!');
	}
});

client.login(token);
```

**Further details:**

- discord.js version: ^13.1.0
- Node.js version: v16.7.0
- Operating system: Windows 10 20H2
- Priority this issue should have – please be realistic and elaborate if possible: answering why commands dont register(and interactions).

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by GoldenAngel2** [comment]
You need to register slash commands: https://discordjs.guide/interactions/registering-slash-commands.html
Gives you examples for that. 

> Note: Global slash commands can take up to 1 hour to show up in all servers, guild slash commands is instant

> For coding questions/support use the server: https://discord.gg/djs

**Comment by erdemozturkfun** [comment]
Thanks it works now!
