### ISSUE TITLE
applicationCommandCreate doesnt fire

### ISSUE THREAD

**Issue by Taelyn** [discordjs/discord.js#6491]
applicationCommandCreate doesnt fire when Guild Command is created
Havent tried Delete and Update but my guess is the same issue

According to Docs and Discord Developer it should fire for both Guild and Client Command Applications

```js
client.on('applicationCommandCreate', async command => {
    console.log(command)
});
```

**Further details:**

- discord.js version: 13.1
- Node.js version: 16.6.2
- Operating system: x64 win 10

**Comment by Jiralite** [comment]
This is not a bug: see https://github.com/discord/discord-api-docs/issues/3690#issuecomment-902915187.

On this note, we should remove them too.
