### ISSUE TITLE
Problem getting the members of a Role (Role Members Cache)

### ISSUE THREAD

**Issue by bastianmarin** [discordjs/discord.js#6495]
I'm trying to move my bot from v12 to v13 but I have some issues that I really don't know if it's a bug or something I don't understand.

I try to retrieve the collection of members of a role from its cache but in v13 it does not return all of them unlike v12 which returns all the members.

Use Client.guilds.cache.get(...).roles.fetch(...).members

![Screenshot_1](https://user-images.githubusercontent.com/55340002/130335344-a085b4d4-c3f6-48fa-b316-1e45c67df1f2.png)

in version 12 I get a collection with 36 entries
but in version 13 I only get 4 entries

Is this due to a bug or mishandling of my code? 

![Screenshot_2](https://user-images.githubusercontent.com/55340002/130335372-fe4eac7c-976c-44ae-b649-f5d779cef75d.png)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
