### ISSUE TITLE
User banner/accent color

### ISSUE THREAD

**Issue by loidnoir** [discordjs/discord.js#6498]
**Is your feature request related to a problem? Please describe.**
I wanna create user information command and cant get banner/accent color

**Describe the ideal solution**
Add banner and accent color property for users

**Describe alternatives you've considered**
No alternative solutions

**Additional context**
```ts
const banner = <user>.bannerURL
const accentcolor = <user>.accentColor
```

**Comment by vBread** [comment]
#6117
