### ISSUE TITLE
Client Shard Timeour Error

### ISSUE THREAD

**Issue by BlackKnight683** [discordjs/discord.js#6503]
**Please describe the problem you are having in as much detail as possible:**
My discord bot keeps getting timed our randomly, i have no idea why. Its a lavalink music bot running along another bot of mine which does not crash. the vps is given 4gb ram and 2vCore CPU
![image](https://user-images.githubusercontent.com/75422863/130357088-75f014b4-5d5d-4bea-b011-793c6c5a3bc8.png)

**Include a reproducible code sample here, if possible:**

```js
const app = express();
const port = 2003 
app.get('/', (req, res) => {
  res.redirect('https://jamjar.solonodes.xyz')
});

app.listen(port, () => {
  const stringlength = 69;
  console.log(`[Webserver] Started on port: ${port}`.bold.brightGreen)
});


const client = new Discord.Client({
  restTimeOffset: 0,
  restWsBridgetimeout: 100,
  disableEveryone: true,
  partials: ['MESSAGE', 'CHANNEL', 'REACTION'],
  presence: {
    afk: false,
    status : "dnd",
    activity: {
      name: `to music`,
      type: 'LISTENING',
    },
  }
});

client.on("debug", function(info) { console.log(`[Debug] ${info}`.blue) });

client.login(process.env.token)
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:
i'd say moderate as i did some googling and found a few more people have this
**Relevant client options:**

- partials: ['MESSAGE', 'CHANNEL', 'REACTION']
- gateway intents: none
- other: see code above

**Comment by ImRodry** [comment]
The issue tracker is not for asking questions. The issue you are facing is not a problem with the library so please ask on the [Discord server](https://discord.gg/djs) and close this

**Comment by BlackKnight683** [comment]
Alrighty
