### ISSUE TITLE
GuildMember.identity

### ISSUE THREAD

**Issue by Medallyon** [discordjs/discord.js#6506]
**Is your feature request related to a problem? Please describe.**
I noticed that d.js doesn't implement Guild-specific Identities. `User.displayAvatarURL()` only retrieves the user's default avatar. Discord's newest feature, **Server Identities**, allows people to change their nickname and avatar for specific Guilds.

**Describe the ideal solution**
I think d.js could implement `GuildMember.identity`, where `identity` is of type `GuildMemberIdentity`, thereby also moving `GuildMember.nickname` to the new class:

```json
{
  "nickname": "string",
  "avatar": "hash",
  "avatarURL": "string"
}
```

Of course, I'm not sure if this is possible on the discord-api side of things. I browsed through the Discord API docs and there doesn't seem to be a mention of a "Server Identity" anywhere. If this can't be implemented now, I propose to keep this issue open until it is possible.

**Comment by vBread** [comment]
#5696

**Comment by Medallyon** [comment]
OH. I looked for "identity" in issues & PRs and couldn't find any duplicates. Thanks =)
