### ISSUE TITLE
TextChannel Webhooks methods don't resolve

### ISSUE THREAD

**Issue by jkcoxson** [discordjs/discord.js#6507]
**Please describe the problem you are having in as much detail as possible:**
A bot is able to create a Webhook just fine, but the promise for creating a Webhook and the promise for fetching a Webhook is never resolved or rejected.
**Include a reproducible code sample here, if possible:**

```ts
client.on('ready', () => {
    console.log('ready');
    const channel = <Discord.TextChannel>client.channels.cache.get('123');
    channel.createWebhook('MyFancyWebhook').catch(err => {
        console.log(err);
    }).then(() => {
        console.log('Created webhook');
    });
    channel.fetchWebhooks().then(something => {
        console.log(something);
    }).catch(err => {
        console.log(err);
    });

});
```

Console output
```
ready
```
[Image](https://imgur.com/a/99DXIQd)

**Further details:**

- discord.js version: 13.2.0
- Node.js version: 16.1.0
- Operating system: Ubuntu 20
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: MESSAGE, CHANNEL, REACTION
- gateway intents: GUILD, GUILD_MESSAGES, GUILD_MEMBERS, GUILD_WEBHOOKS
- other: none

- I have also tested the issue on latest main; Commit hash: `8601eb3dbbff3e49475c766b6d93276f99f9f7af`

**Comment by SpaceEEC** [comment]
I can't reproduce this one 70cc0295f833cd988ea627b37d20536f73e21630, both promises resolve fine for me.
The commit you specified doesn't exist on our repo (seems to be a commit from #6482).

You could try logging the debug event, maybe you are rate limited:
`client.on("debug", console.log);` and `client.on("rateLimit", console.log);`
