### ISSUE TITLE
Channels glitching when deleted

### ISSUE THREAD

**Issue by GkqqNkKC** [discordjs/discord.js#6512]
After deleting a channel using the bot, the desktop client (windows) still shows the channel in the side panel, but the channel was deleted, so it can't be accessed

Refreshing the client gets rid of the problem. I thought it was a problem on the client's side, but now that it passed years and the problem is still there, it signals me that there's something else

Recently I encountered this problem for voice channels, though probably it happens to text ones too. I have to mention that I create the channels in a category by setting `parent`

Here's the code of creating and destroying the channels:

```js
let permissions = [{id: "863186781934190642", deny: discord.Permissions.FLAGS.VIEW_CHANNEL}];
this.promise = discord_guild.channels.create(id, {parent: "879090492967649300", permissionOverwrites: permissions}).then(channel => {
  this.txt = channel;
  return discord_guild.channels.create(id, {type: "GUILD_VOICE", parent: "879090492967649300", permissionOverwrites: permissions});
}).then(channel => this.voice = channel);
```
```js
this.txt.delete();
this.voice.delete();
```

I can assure the deleting happens when the channels are fully created. I remember back then this problem was happening in the browser too

**Further details:**

- discord.js version: latest release
- Node.js version: latest release
- Operating system: win 10 x64

**Comment by SpaceEEC** [comment]
This reads very much like a client bug: The channel is actually gone and the client still shows it until reloading it.

You can report those in the [Discord Testers Discord Server](https://discord.gg/discord-testers) (I don't know if they are open again), or though the [Bug form](https://dis.gd/bugreport).
If it's an api bug, you can report it here: [discord/discord-api-docs#api-bug-report](https://github.com/discord/discord-api-docs/issues/new?assignees=&labels=bug&template=api-bug-report.md)

**Comment by GkqqNkKC** [comment]
Unfortunately I won't submit any bug on their end as I don't have enough knowledge with the API to reproduce the problem; and I don't plan looking into it too soon, that's why I'm using Discord.js in the first place

My guess is that other bot programmers found some workaround

**Comment by DTrombett** [comment]
This problem is totally unrelated to discord.js and bots (and probably to the API too), it seems just a bug with the Discord client (app).

**Comment by ImRodry** [comment]
Since it is a bug with the client you will have to report it using the support link that Space gave you above because DT is currently under some sort of maintenance until the beginning of September. You don’t need much knowledge about the API, just explain you deleted the channel through the library and that it didn’t get properly deleted on the client.
