### ISSUE TITLE
webhook.editMessage gives out TypeError: webhook.editMessage is not a function

### ISSUE THREAD

**Issue by code9855** [discordjs/discord.js#6517]
I am trying to get a webhook to send a message and then to edit it later on, when I try ```console.log(webhook)```  before the edit, I do get the ```webhook```. But when it comes to the ```editMessage```, I get 
'TypeError: webhook.editMessage is not a function'.
```js
client.on('ready', async () => {
  const channel = client.channels.cache.get("ID");
    const webhook = await channel.createWebhook(channel.guild.name, {
      avatar: channel.guild.iconURL()
    })
    const embed = new discord.MessageEmbed().setAuthor(`BEFORE EDIT`).setColor('#e9ba04')
    await webhook.send(embeds = [embed]).then(async (result) => {
          const embed1 = new discord.MessageEmbed().setAuthor(`AFTER EDIT!`).setColor('#e9ba04')
          console.log(webhook) 
          webhook.editMessage(result.id, {
              embeds: [embed1]
            });
    });
  })
```

**Further details:**

- discord.js version: v. 12.5.3
- Node.js version: v. 14.17.5
- Documentation: https://discordjs.guide/popular-topics/webhooks.html#editing-messages

**Comment by Jiralite** [comment]
You are viewing the guide in version 13 - the current stable version. You are on version 12.5.3 - these methods do not exist on your version. See the version 12 guide at https://v12.discordjs.guide/!
