### ISSUE TITLE
SyntaxError when used on Repl.it

### ISSUE THREAD

**Issue by elifanous** [discordjs/discord.js#6519]
**Please describe the problem you are having in as much detail as possible:**
When I run my code on Repl.it, using Node.js (with discord.js installed), I am given a Syntax Error saying the following:
/home/runner/Encourage-Bot-JavaScript/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                                       ^

SyntaxError: Unexpected token '?'

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```const Discord = require("discord.js")
const client = new Discord.Client()

client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`)
})

client.on("message", msg => {
  if (msg.content === "ping") {
    msg.reply("pong")
  }
})

client.login(process.env.TOKEN)
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 12.16.1
- Operating system: Windows 10, Chrome browser, Website: replit.com, direct link to code: https://replit.com/@EliFanous/Encourage-Bot-JavaScript#index.js
- Priority this issue should have – please be realistic and elaborate if possible: Medium-High, as far as I know, I could be the only person with this problem, but it completely inhibits me from running my code until it's fixed.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by xMooddyy** [comment]
You need Node v16.6+ to use v13, which repl.it doesn't support.

**Comment by elifanous** [comment]
Okay, thanks for letting me know, I guess I'll figure something else out
