### ISSUE TITLE
node Error .js

### ISSUE THREAD

**Issue by IKaszz** [discordjs/discord.js#6547]
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'discord,js'
Require stack:
- C:\node\index.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:997:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:92:18)←[39m
    at Object.<anonymous> (C:\node\index.js:1:17)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1108:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:973:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\node\\index.js'←[39m ]

I am new to this and I do not know what happens, can someone help me?

**Comment by kerfuzzle** [comment]
When you require discord.js you’ve spelt it as “discord,js” with a comma when it should be “discord.js” with a period.
