### ISSUE TITLE
Whenever I create, delete or edit a webhook, it always logs `WEBHOOK_CREATE` as action type

### ISSUE THREAD

**Issue by MrYogi360** [discordjs/discord.js#6548]
Whenever I create, delete or edit a webhook, bot always log `WEBHOOK_CREATE` as action type!
Code: ```const action = await channel.guild.fetchAuditLogs({ type: "WEBHOOK_CREATE" }).then(async (audit) => audit.entries.first());
console.log(action)```

This always shows 
![image](https://user-images.githubusercontent.com/76902806/131241910-ce6c84bf-9df5-414c-b5ab-34f4e64a9551.png)

discord.js Version: `^13.1.0`
nodejs version: `16.1.0`

**Comment by SpaceEEC** [comment]
You are explicitly only fetching entries of created webhooks: `.fetchAuditLogs({ type: "WEBHOOK_CREATE" })`
You can use `WEBHOOK_UPDATE` and `WEBHOOK_DELETE` for the other types. (Or simply omit `type` to fetch all kind of entries, not just webhook ones however)

**Comment by MrYogi360** [comment]
> You are explicitly only fetching entries of created webhooks: `.fetchAuditLogs({ type: "WEBHOOK_CREATE" })`
> You can use `WEBHOOK_UPDATE` and `WEBHOOK_DELETE` for the other types. (Or simply omit `type` to fetch all kind of entries, not just webhook ones however)

I only want entries of `WEBHOOK_CREATE` that's why I added `type: "WEBHOOK_CREATE"` options, but bot is giving all entries related webhooks (`WEBHOOK_CREATE`, `WEBHOOK_DELETE` And `WEBHOOK_UPDATE`)

**Comment by SpaceEEC** [comment]
I'm unable to reproduce that: I only get actual webhook create entries.
