### ISSUE TITLE
Bot Crashes every 1-5 Minutes

### ISSUE THREAD

**Issue by Tomato6966** [discordjs/discord.js#6552]
My Bot sends a Heartbeat
(That's normal ik)
But once it doesnt receive a responde, which happesn once every 1-5 Minutes
Then it crashes and relogsin
Idk why this is a thing
i wanna raise the limit to like 5 until it relogs
Cause my bot then doesnt responde to cmds within the re logging in
Which results in bad ping (15000 for api and 7000 for Bot)

Any1 PLEASE HELP ME I AM HAVING THIS PROBLEM OVER 8 DIFFERENT OS, AND OVER 30 DIFFERENT BOTS FOR MONTHS NOW!

Reference Images: 
![image](https://user-images.githubusercontent.com/68145571/131255204-ec608d87-d859-4e57-b6e3-f6283c08cee1.png)
![image](https://user-images.githubusercontent.com/68145571/131255205-7382c293-9e74-4106-bd7f-8c57760268f2.png)
![image](https://user-images.githubusercontent.com/68145571/131255210-44b610aa-74a5-4c8d-a6fd-2d1950e8d524.png)
![image](https://user-images.githubusercontent.com/68145571/131255218-482f1746-f60d-4fdf-8b61-0e311be2790f.png)
![image](https://user-images.githubusercontent.com/68145571/131255220-3a8d2407-9da2-4bf4-809c-5c228e72c7ac.png)

**Comment by Tomato6966** [comment]
After 4 hours it still occurs:

Ram: 1gb/24gb 
CPU: 5%/100% (8 CORES)
50gb SSD
DEBIAN 9

Download: 800mb/s
Upload: 400mb/s
https://cdn.discordapp.com/attachments/824411059443204127/881610918612570212/unknown.png

**Comment by monbrey** [comment]
Please don't ignore the issue template - provide information such as your discord.js version, node version and which intents you're using.

**Comment by WaviestBalloon** [comment]
> Please don't ignore the issue template - provide information such as your discord.js version, node version and which intents you're using.

You can easily find your node version via the ```node -v``` command

**Comment by Tomato6966** [comment]
TESTED in:
Discord.js v12. 5.3
Nodejs v16. 6

Tested in:
Discord.js v13. 1.0
Nodejs v16. 6

Tested in:
Discord. Js @ dev
Nodejs v16


Tested on:
4 different german hoster in frankfurt
Oxide hosting and zap hosting


On every single Situation etc. The bot is doing the same

It is restaring over 274 times in 30mins
Ik that cause my sessionlimit was right now on 742
And it resets to 1k every full hour

**Comment by Tomato6966** [comment]
I am using every internt expect voice Staates and dms

**Comment by Tomato6966** [comment]
now that i switched to v13 it still happens but without relogging in like that: 
![image](https://user-images.githubusercontent.com/68145571/131343815-9459dc7d-e89d-4a0d-9542-a5af04813046.png)
the ws goes up to 10k+ ping

**Comment by KurokuTetsuya** [comment]
probably my bot have same issue, discord always regenerate my token because spamming login endpoint, imma try enable debug event

**Comment by mzrtamp** [comment]
> probably my bot have same issue, discord always regenerate my token because spamming login endpoint, imma try enable debug event

this happens 3 times

**Comment by Tomato6966** [comment]
I fixxed it, it was not a djs problem i had to many sync. tasks running at the same time
