### ISSUE TITLE
Typings for creating select values with emoji incorrect, blocking creation of dropdown menus with emoji

### ISSUE THREAD

**Issue by Nephrited** [discordjs/discord.js#6555]
**Please describe the problem you are having in as much detail as possible:**
When attempting to create a select dropdown with an emoji, the TS enforces a full emoji object of type `EmojiIdentifierResolvable`, when the Discord API requires only [a partial Emoji object consisiting of at most the `id`, `name` and `animated` fields.](https://canary.discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure)

**Include a reproducible code sample here, if possible:**

```typescript
const actionRow = new MessageActionRow().addComponents(
	new MessageSelectMenu()
		.setCustomId('exampleSelect')
		.setPlaceholder('Nothing selected')
		.addOptions([
			{
				label: 'Label',
				description: 'A description',
				value: 'value-1',
				emoji: {
					name: "♥",
					//id: "1234", // optional field for custom emoji
					//animated: false, // optional field for custom emoji
				}
			},
		])
);

await interaction.reply({
	content: 'This is a test',
	components: [actionRow],
});
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.7.0
- Operating system: Ubuntu 20.04.2 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Low. It's annoying but hardly a mission critical feature for bots, and can be worked around, but still should be fixed.

**Workaround**
```typescript
emoji: {
	name: "♥",
} as any
```

**Relevant client options:**

N/A

**Comment by Jiralite** [comment]
Odd? [This method](https://discord.js.org/#/docs/main/main/class/MessageSelectMenu?scrollTo=addOptions) accepts [this type definition](https://discord.js.org/#/docs/main/main/typedef/MessageSelectOptionData) for which the `emoji` property is ultimately this:

```TypeScript
export type EmojiIdentifierResolvable = string | EmojiResolvable;
export type EmojiResolvable = Snowflake | GuildEmoji | ReactionEmoji;
```

I fail to see how this could even occur. It looks like you're passing a [`RawEmoji`](https://discord.js.org/#/docs/main/main/typedef/RawEmoji) instead, which isn't docuemtned nor typed to be sent across?

**Comment by Nephrited** [comment]
`RawEmoji` looks to be exactly what the DiscordAPI accepts for this call, [as documented here](https://canary.discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure)

**Comment by Jiralite** [comment]
This is a library, so things can be altered! If you have a custom emoji, just pass the id. If you want to use a default emoji, just pass the Unicode variant. Under-the-hood, this is transformed to the necessary payload (`RawEmoji`) to be sent across. Simply specifying an id or the Unicode variant is a convenience here.

> TS enforces a full emoji object of type EmojiIdentifierResolvable

This can be a string or an id, so it's not always an object!

**Comment by Nephrited** [comment]
Makes total sense to me. I'll close this out, hopefully anyone with a similar problem will run into it!

**Comment by monbrey** [comment]
Arguably this is just a typings issue then, and `RawEmoji` could be added to resolvable items.
