### ISSUE TITLE
Incorrect type for Message#awaitMessageComponent

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#6561]
**Please describe the problem you are having in as much detail as possible:**
After #6476 was merged, Message#awaitMessageComponent no longer works because for some unknown reason it returns a Collector instead of an interaction. Unfortunately these types are too complex and I do not know how to fix this while keeping the feature the PR meant to introduce, so I'm opening this and tagging @suneettipirneni so that them or someone else can take a look.

**Include a reproducible code sample here, if possible:**

```ts
client.on("messageCreate", message => {
	const interaction = await message.awaitMessageComponent({time: 60_000})
	console.log (interaction.customId) //Throws an error: Property 'customId' does not exist on type 'InteractionCollector<ButtonInteraction>'.
})
```

**Further details:**

- discord.js version: https://github.com/discordjs/discord.js/commit/34024f5ef6192fa0da5b7d6aa7e2d219066ad9b0
- Node.js version: 16.8.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: highest, a version cannot be published with this issue

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES
- other: none

**Comment by suneettipirneni** [comment]
Thanks for bringing this up I'll investigate this.

**Comment by ImRodry** [comment]
Thanks! Are you on the discord server? Would be easier to talk there if you are
