### ISSUE TITLE
TypeError: this.iconURL is not a function

### ISSUE THREAD

**Issue by PuneetGopinath** [discordjs/discord.js#6565]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
const { Client, Collection, Intents } = require("discord.js");
const client = new Client({
    intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES,
    ],
});
client.on("messageCreate", (message) => {
    console.log(message.guild.toJSON());
});
client.login("TOKEN HERE");
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.x
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:
Error:
```js
TypeError: this.iconURL is not a function
    at Guild.toJSON (/src/user/app/node_modules/discord.js/src/structures/Guild.js:1275:25)
    at eval (eval at <anonymous> (/src/user/app/src/commands/owner/eval.js:39:57), <anonymous>:1:15)
    at /src/user/app/src/commands/owner/eval.js:39:57
    at new Promise (<anonymous>)
    at CMD.execute (/src/user/app/src/commands/owner/eval.js:39:24)
    at module.exports (/src/user/app/src/functions/execute.js:223:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
```

**Relevant client options:**

- partials: channel
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, GUILD_VOICE_STATES
- other: none

**Comment by PuneetGopinath** [comment]
Closing this issue. I thought of testing it with the latest dev version, and it's working

**Comment by PuneetGopinath** [comment]
Hi
Sorry. But I don't know what happened but it's not working again

**Comment by PuneetGopinath** [comment]
In the latest dev version

**Comment by PuneetGopinath** [comment]
Output of npm ls discord.js
```js
welcome-bot@​2.0.0-dev.6972af1 /src/user/app
+-- discord-backup@​3.0.1
| `​-- discord.js@​13.1.0
`​-- discord.js@​13.2.0-dev.1630281876.29d5fd1 
```

**Comment by SpaceEEC** [comment]
Can you create a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) without any other modules besides discord.js installed?

**Comment by PuneetGopinath** [comment]
> Can you create a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) without any other modules besides discord.js installed?

Ok done, I hv updated the comment. And after starting the bot just send some message in discord where that bot is in

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this error.

**Comment by PuneetGopinath** [comment]
> I'm unable to reproduce this error.

Hmm. Yea, same happend when I tested this code. But when I use it in my code it doesn't work

**Comment by PuneetGopinath** [comment]
I can give you my code

**Comment by PuneetGopinath** [comment]
https://github.com/Welcome-Bot/welcome-bot/blob/2f88d898748082903de3f7ddc85db2130898c902/src/dashboard/utils.js#L29

**Comment by PuneetGopinath** [comment]
userData is a data I modified which is given by discord from Oauth2

**Comment by ImRodry** [comment]
You say the issue is with iconURL but I only see toJSON in your code 🤔

**Comment by Jiralite** [comment]
> > I'm unable to reproduce this error.
> 
> Hmm. Yea, same happend when I tested this code. But when I use it in my code it doesn't work

...Part of providing a reproducible samplemeans that it's reproducible.

This looks suspicious, however:
https://github.com/Welcome-Bot/welcome-bot/blob/2f88d898748082903de3f7ddc85db2130898c902/src/dashboard/utils.js#L33-L35

It seems you're modifying discord.js's internal structures. In which case you should take it upon yourself to debug your code. Test it out, throw `console.log()`s everywhere until you find your issue - we can't really do much other than guesstimate at this point,

**Comment by almostSouji** [comment]
Manually overwriting library properties or functions is not a supported use case, so this is not a bug with the library. If you require more assistance with using discord.js without modifications, please visit the [Discord server](https://discord.gg/djs)
