### ISSUE TITLE
Bug: createdAt field missing from client.user

### ISSUE THREAD

**Issue by Sant268** [discordjs/discord.js#6570]
### Issue description

console.log(client.user.createdAt) fetches no result,
client.user has no read-only attributes present
```
ClientUser {
  id: '',
  bot: true,
  system: false,
  flags: null,
  username: '',
  discriminator: '',
  avatar: '',
  banner: 
  accentColor: ,
  verified: true,
  mfaEnabled: 
}
```
only these fields are present

### Codesample

```typescript
client.on('ready', () => {
console.log(client.user);
});
```

### discord.js version

13.2.0-dev

### Node.js version

16.8.0

### Operating system

Ubuntu 20.04.2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES

### I have tested this issue on a development release

13.2.0-dev.1630325279.581921f

**Comment by almostSouji** [comment]
Logging a structure will not log getters

https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/structures/User.js#L120-L122

The timestamp and date of user creation are derived from the user ID

https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/structures/User.js#L111-L113

**Comment by Sant268** [comment]
Oh okay I see it. Initially I was adding it as a field value to an embed,which worked well enough in earlier versions but 
`client.user.createdAt` returned me a `EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.` 
hence I tried to log it.
""+client.user.createdAt works for embed values now. Not directly.

**Comment by almostSouji** [comment]
You are forced to provide a non-empty string, #createdAt does not return a string, so that is expected.
The Date structure has various methods to resolve the object to a string, like [`Date#toUTCString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString), to name one.
