### ISSUE TITLE
Bug: Property 'options' does not exist on type 'Interaction'.

### ISSUE THREAD

**Issue by zal1000** [discordjs/discord.js#6572]
### Issue description

When I try to get the interaction options, typescript will throw this error at me: `Property 'options' does not exist on type 'Interaction'.` 
When I compile the code it's working

### Codesample

```typescript
const url = interaction.options.getString('url') as string // i get the same error without the 'as string'
```

### discord.js version

v13.1.0

### Node.js version

v16.8.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILDS

**Comment by Dev-CasperTheGhost** [comment]
`options` only exists on [`CommandInteraction`](https://github.com/discordjs/discord.js/blob/main/typings/index.d.ts#L554) and [`ContextMenuInteraction`](https://github.com/discordjs/discord.js/blob/main/typings/index.d.ts#L614)

**Comment by almostSouji** [comment]
[`Interaction`](https://discord.js.org/#/docs/main/stable/class/Interaction) has `is*` methods to check for certain types of interactions, you need to narrow before accessing options (and other type-dependent attributes).

**Comment by j-dogcoder** [comment]
I am having this issue as well...
