### ISSUE TITLE
Bug: Slah Command api not working

### ISSUE THREAD

**Issue by TimyIsCool** [discordjs/discord.js#6577]
### Issue description

1. Copy My code and add your own bot token, guildid and clientid
2. install packages. npm install discord.js @discordjs/rest discord-api-types

![image](https://user-images.githubusercontent.com/74112751/131701382-4ca953e4-7bef-430a-963f-a4ffd4e1a163.png)

### Codesample

```typescript
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');

const commands = [{
  name: 'ping',
  description: 'Replies with Pong!'
}]; 

const rest = new REST({ version: '9' }).setToken('token');

(async () => {
  try {
    console.log('Started refreshing application (/) commands.');

    await rest.put(
      Routes.applicationGuildCommands(CLIENT_ID, GUILD_ID),
      { body: commands },
    );

    console.log('Successfully reloaded application (/) commands.');
  } catch (error) {
    console.error(error);
  }
})();
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

GUILD_MEMBER

### Which gateway intents are you subscribing to?

GUILDS

**Comment by SuperchupuDev** [comment]
You put the wrong application ID, not a d.js issue, next time ask in the discord server since this bug tracker is only for issues and feature requests

**Comment by Wumpuspro** [comment]
Kick your bot and invite with application.commands

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
