### ISSUE TITLE
Bug: V13 VoiceStateUpdate

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#6579]
### Issue description

In V13, when I put my bot in sound, it keeps falling off the sound, looping it, but it still drops, please fix this problem setInterval doesn't even work anymore

### Codesample

```typescript
function voiceConnect(channel) {
  const connection = joinVoiceChannel({
    channelId: channel.id,
		guildId: channel.guild.id,
		adapterCreator: channel.guild.voiceAdapterCreator,
	});
  try {
		return connection;
	} catch (error) {
		throw error;
	}
}


	  let count = 0;
  let interval = setInterval(async function(){
    count += 1;
    
    if(count === 20){
      clearInterval(interval);
    }
    
    let Guild = client.guilds.cache.get(Settings.Server.Id);
    if(!Guild) return;
    let Channel = Guild.channels.cache.get(Settings.Server.VoiceId);
    if(Channel) return await voiceConnect(Channel);
  }, 4000);
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILD_VOICE_STATES

**Comment by ImRodry** [comment]
13.x isn't really a version but shouldn't this go on @discordjs/voice?

**Comment by wioniqle-q** [comment]
> 13.x isn't really a version but shouldn't this go on @discordjs/voice?

Dude, when I say use your head 13.x, I mean the latest version of discord.

**Comment by ImRodry** [comment]
> > 13.x isn't really a version but shouldn't this go on @discordjs/voice?
> 
> Dude, when I say use your head 13.x, I mean the latest version of discord.
> ![image](https://user-images.githubusercontent.com/69215407/131840057-67cc7327-5f31-4588-a59e-bd4cd640ed2e.png)

The latest version can change at any time, that’s why you should say what version it actually is

**Comment by wioniqle-q** [comment]
> > > 13.x isn't really a version but shouldn't this go on @discordjs/voice?
> > 
> > 
> > Dude, when I say use your head 13.x, I mean the latest version of discord.
> > ![image](https://user-images.githubusercontent.com/69215407/131840057-67cc7327-5f31-4588-a59e-bd4cd640ed2e.png)
> 
> The latest version can change at any time, that’s why you should say what version it actually is

If you make any sense, you'll know it's the latest version.

**Comment by ImRodry** [comment]
Always a great attitude to have when reporting a bug

**Comment by wioniqle-q** [comment]
> Always a great attitude to have when reporting a bug

If you're not going to help me with my problem and you don't know anything about it, don't keep this place busy.

**Comment by AviDoesDev** [comment]
Having a similar issue...
VoiceStateUpdate event is firing, but the cache isn't updating.

**Comment by wioniqle-q** [comment]
> Having a similar issue...
> VoiceStateUpdate event is firing, but the cache isn't updating.

So?

**Comment by wioniqle-q** [comment]
name... name... name... pff brut

**Comment by wioniqle-q** [comment]
name... name... name... pff brut
