### ISSUE TITLE
Bug: <Client>.users is not working

### ISSUE THREAD

**Issue by arthurvanl** [discordjs/discord.js#6588]
### Issue description

When i try to get a user from client.users it return with undefined

### Codesample

```typescript
const user = client.users.cache.get("SOME_USER_ID");
console.log(user);
//returns undefined
```

### discord.js version

13.1.0

### Node.js version

16.6.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_MESSAGES

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by almostSouji** [comment]
It's working, it's just not cached at the point in time you are trying to retrieve it.

**Comment by arthurvanl** [comment]
> It's working, it's just not cached at the point in time you are trying to retrieve it.

How can i retrieve it then in a ready event
