### ISSUE TITLE
Feature request: Make `MessageComponentInteraction#channelId` non-nullable

### ISSUE THREAD

**Issue by GrapeColor** [discordjs/discord.js#6591]
### Feature

Currently `MessageComponentInteraction#channelId` is nullable.

However, the Discord API documentation states that it is
> For Message Components it includes identifying information about the component that was used. It will also include some metadata about how the interaction was triggered: the `guild_id`, `channel_id`, `member` and other fields. You can find all the values in our data models.
> -from: https://discord.com/developers/docs/interactions/receiving-and-responding#interactions

From this, `MessageComponentInteraction#channelId` can be non-nullable.

### Ideal solution or implementation

Make `MessageComponentInteraction#channelId` non-nullable.

**Comment by ImRodry** [comment]
Probably related to #6481 but it would be semver:major wouldn’t it?

**Comment by almeidx** [comment]
> Probably related to #6481 but it would be semver:major wouldn’t it?

No. The runtime behaviour will not change, just the documentation/typings

**Comment by ImRodry** [comment]
Then someone can open the PR

**Comment by Megatank58** [comment]
Not sure but the documentation [just below](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure) those lines indicate the channel_id can be null in the interaction object, in the library MessageComponentInteraction extends Interaction and it's nullable in Interaction object so it's nullable in MessageComponentInteraction as well

**Comment by suneettipirneni** [comment]
> Not sure but the documentation [just below](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure) those lines indicate the channel_id can be null in the interaction object, in the library MessageComponentInteraction extends Interaction and it's nullable in Interaction object so it's nullable in MessageComponentInteraction as well

The properties are represented as optional on the base interaction because they aren't available on all interaction variants. In this case they are never null on the `MessageComponentInteraction` variant so the subtype should represent that.
