### ISSUE TITLE
Bug: `Webhook.editMessage()` into a thread doesn't work

### ISSUE THREAD

**Issue by Pifpok** [discordjs/discord.js#6592]
### Issue description

With a webhook (created by the client) I send a message in a thread -> Everything is fine
```javascript
webhook.send({content: firstContent, threadId: id});
```

But later I come to edit this message -> Everything is bad :sweat_smile: 

```javascript
let msg = channel.messages.fetch(msgId)
webhook.editMessage(msg, {content: newContent});
```

But it works if the message is not in a thread and I did not find anything in the discord.js doc for this "problem"
![image](https://user-images.githubusercontent.com/45263928/132101477-a9feee2e-c307-4235-95d5-ff76d2debd24.png)

### Codesample

```typescript
function sendMsg(message, threadId)
{
	let hook = message.channel.fetchWebhooks().first()
	hook.send({content: message.content, threadId: threadId})
}

async function editMsg(message, messageOldId)
{
	let msgOld = await message.channel.messages.fetch(messageOldId);
	let hook = await msgOld.fetchWebhook()
	hook.editMessage(msgOld, {content: message.content});
}
```

### discord.js version

13.0.1

### Node.js version

16.6+

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

**Comment by almostSouji** [comment]
Can reproduce this exact behavior on 08edc0b1db52992b2a2f8f6012a6001fb4336f38 .
I'm currently not sure if this might be a discord bug, the endpoint is documented [`PATCH/webhooks/{webhook.id}/{webhook.token}/messages/{message.id}`](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) which is exactly what we call (as evident in the logged error).

I can't find any caveats regarding this (needing to supply something else, for example). Even the [webhook section of threads](https://discord.com/developers/docs/topics/threads#webhooks) does not explicitly deny the ability to edit messages in threads, however also only mentions that messages can be sent (edit is not mentioned):

> Webhooks can send messages to threads by using the thread_id query parameter. See the execute webhook docs for more details.

**Comment by GoldenAngel2** [comment]
It's an API bug.
https://github.com/discord/discord-api-docs/issues/3519 it's been reported

**Comment by awder2000** [comment]
H

**Comment by Jiralite** [comment]
> Its an API bug.
> [discord/discord-api-docs#3519](https://github.com/discord/discord-api-docs/issues/3519)

This is fixed, but discord.js does not supply a thread id parameter to fetch, edit or delete a message ([view source code](https://github.com/discordjs/discord.js/blob/main/src/structures/Webhook.js)) which means the sending of a message into a thread is only supported.

To elaborate on what should be done, this is an example fix for the `Webhook#fetchMessage` method:
```JavaScript
async fetchMessage(message, { cache = true, threadId } = {}) {
  if (!this.token) throw new Error('WEBHOOK_TOKEN_UNAVAILABLE');

  const data = await this.client.api.webhooks(this.id, this.token).messages(message).get({
    query: {
      thread_id: threadId
    }
  });
  return this.client.channels?.cache.get(data.channel_id)?.messages._add(data, cache) ?? data;
}
```

The `thread_id` must be passed as a query parameter. As @almostSouji said, this is not for some reason documented (or just not documented well enough), but this call will fail otherwise.
