### ISSUE TITLE
Bug: interaction.member.permissions.has("ADMINISTRATOR") return true but user without permissions

### ISSUE THREAD

**Issue by FabriSoftware** [discordjs/discord.js#6594]
### Issue description

I just realized this and I'm a little scared

the bug is the following ...

when I check if the user has an administrator with <Member>.permissions.has ("ADMINISTRATOR") this returns true even if the user does not have an administrator

How do I solve this?

### Codesample

```typescript
if(interaction.member.permissions.has("ADMINISTRATOR")){
  console.log(true)
}else{
  console.log(false)
}
// output true
```

### discord.js version

discord.js@13.1.0

### Node.js version

v16.6.1

### Operating system

Linux (Ubuntu)

### Priority this issue should have

Medium (should be fixed soon)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING

**Comment by ImRodry** [comment]
Can you also show us the permission bitfield of that member, as well as the result of permissions.toArray()?

**Comment by SpaceEEC** [comment]
Additionally to the above: Does this also happen in a new channel outside of categories or a new guild/server?

**Comment by Tyrone5693** [comment]
Check change log this is old code

**Comment by FabriSoftware** [comment]
> Can you also show us the permission bitfield of that member, as well as the result of permissions.toArray()?

this is what I get... and the user does not have these permissions

```js
Permissions { bitfield: 420369399759n }

[
  'CREATE_INSTANT_INVITE',
  'KICK_MEMBERS',
  'BAN_MEMBERS',
  'ADMINISTRATOR',
  'MANAGE_CHANNELS',
  'MANAGE_GUILD',
  'ADD_REACTIONS',
  'VIEW_AUDIT_LOG',
  'PRIORITY_SPEAKER',
  'STREAM',
  'VIEW_CHANNEL',
  'SEND_MESSAGES',
  'SEND_TTS_MESSAGES',
  'MANAGE_MESSAGES',
  'EMBED_LINKS',
  'ATTACH_FILES',
  'READ_MESSAGE_HISTORY',
  'MENTION_EVERYONE',
  'USE_EXTERNAL_EMOJIS',
  'VIEW_GUILD_INSIGHTS',
  'CONNECT',
  'SPEAK',
  'MUTE_MEMBERS',
  'DEAFEN_MEMBERS',
  'MOVE_MEMBERS',
  'USE_VAD',
  'CHANGE_NICKNAME',
  'MANAGE_NICKNAMES',
  'MANAGE_ROLES',
  'MANAGE_WEBHOOKS',
  'MANAGE_EMOJIS_AND_STICKERS',
  'USE_APPLICATION_COMMANDS',
  'REQUEST_TO_SPEAK',
  'MANAGE_THREADS',
  'USE_PUBLIC_THREADS',
  'USE_PRIVATE_THREADS',
  'USE_EXTERNAL_STICKERS'
]
```

**Comment by FabriSoftware** [comment]
> Additionally to the above: Does this also happen in a new channel outside of categories or a new guild/server?

no, this happened on a server where the bot was already

**Comment by FabriSoftware** [comment]
> Check change log this is old code

you mean `interaction.member.permissions.has(Discord.Permissions.FLAGS.ADMINISTRATOR)`? this didn't work either

psdt: Tried this on an old code of mine from version 12 and this works fine

**Comment by Tyrone5693** [comment]
![IMG_20210905_170951.jpg](https://user-images.githubusercontent.com/84444757/132129987-82d2f88f-a8ea-4c19-ab61-6393a3116052.jpg)
I am using v13 and it works for me

**Comment by ImRodry** [comment]
> > Check change log this is old code
> 
> you mean `interaction.member.permissions.has(Discord.Permissions.FLAGS.ADMINISTRATOR)`? this didn't work either
> 
> psdt: Tried this on an old code of mine from version 12 and this works fine

That is the exact same thing, it’s not outdated code dw

**Comment by FabriSoftware** [comment]
I just solved this ... turns out the server owner gave admin to the xd user role xd

thanks for your time and sorry for the inconvenience
