### ISSUE TITLE
Bug: guild.name is undefined

### ISSUE THREAD

**Issue by PuneetGopinath** [discordjs/discord.js#6595]
### Issue description

Guild#name is undefined and Guild#id is always `880150602204713060` no matter what the guild Is. I got the guild object from the guildDelete event
Steps to reproduce:
- Copy the sample code
- Kick the bot from a guild

### Codesample

```typescript
const { Client, Intents } = require("discord.js");
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
client.on("guildDelete", (guild) => {
    console.log("guildDelete event triggered", guild.name, guild.id);
});
```

### discord.js version

13.2.0-dev.1630800304.08edc0b

### Node.js version

v16.8.0 

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this, I am seeing the expected name and ID just fine.

**Comment by PuneetGopinath** [comment]
> I'm unable to reproduce this, I am seeing the expected name and ID just fine.

Sometimes it is working for me too. Sometimes it doesn't work 
![Screenshot_20210905-114827_Discord-Canary~2](https://user-images.githubusercontent.com/76863199/132117540-a526fc45-3a09-4008-a8ed-23ef4c46186c.jpg)

**Comment by PuneetGopinath** [comment]
Idk what to do. I want it to work always

**Comment by Palm2570Playz** [comment]
Try fetching the guild with `force` option true

**Comment by Palm2570Playz** [comment]
Try fetching the guild with `force` option `true` to use force fetch and receive data directly from Discord API, don't know if this will help though.
 
```js
client.on("guildDelete", async (g) => {
   const guild = await client.guilds.fetch({ guild: g.id, force: true })
   // Code
})```

**Comment by kyranet** [comment]
The only way for a guild to have empty data, is to have an unavailable guild.

Please check [`Guild#available`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=available).

**Comment by CodeSpent** [comment]
Are we positive there wasn't regression here? I'm seeing this behavior in many servers. They also have `available` set to `false` where using the API directly, we do not see this as the case indicative of an issue with the discord.js library, not the servers or data coming from the API.
