### ISSUE TITLE
Bug: Client keeps reconnecting 

### ISSUE THREAD

**Issue by Larsundso** [discordjs/discord.js#6597]
### Issue description

This has been happening ever since I've started the steps below.
(I don't know if it has to be a different Member for every request, I've been using it that way, patching roles of 300k Members  over the course of 8 days to never hit any rate-limits)

1. Log Shard and debug events
2. Have a Guild with enough Members to test it on
3. Send Member Role "patch" Methods every 3 Seconds across multiple days.
4. Observe
5. After a few days the Client becomes unusable until restarted

Attachment: Console Output showing the Log that should occur.
[Console.txt](https://github.com/discordjs/discord.js/files/7112285/Console.txt)

### Codesample

```typescript
const { Client, Intents } = require("discord.js");
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
client.connect('TOKEN')

const rolesToAdd = ['ID', 'ID'];
const rolesToRemove = ['ID', 'ID'];

client.once('ready', async () => {
 const guild = client.guilds.cache.get('GUILD ID');
 await guild.members.fetch();
 guild.members.cache.map(o => o).forEach((member, index) => {
  setTimeout(async () => {
   await member.roles.add(rolesToAdd)
   await member.roles.remove(rolesToRemove)
  }, 3000*index)
 });
});
```

### discord.js version

13.1.0

### Node.js version

v16.8.0

### Operating system

Windows 10 64-Bit (10.0.19041)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by DTrombett** [comment]
That's API spam... Why would you add and remove roles to 300k members? It's totally normal that you receive a rate limit error.

**Comment by Larsundso** [comment]
> That's API spam... Why would you add and remove roles to 300k members? It's totally normal that you receive a rate limit error.

it is not 
Ratelimit would like this: 
```Discord Client was RateLimited Timeout: 1595
Limit: 10
Method: patch
Path: /guilds/{guild ID}/members/{user ID}
Route: /guilds/{guild ID}/members/:id
```

I am talking about, for example, everything from attachment log Line 28401 to 28538

**Comment by monbrey** [comment]
> Ratelimit would look like this:

That's exactly what I see on line 28379, right before the lines you indicated. I also see frequent hits of the message sending rate limit, and a truly ridiculous amount of guild member fetching packets that are being dropped due to the closed websocket connection.

It would not surprise me at all if it's Discord kicking your bot off the websocket for this sort of activity.

**Comment by Larsundso** [comment]
🤔 well that's at least an answer I can work with, thanks.
