### ISSUE TITLE
Bug: member.voice.channel is not updated

### ISSUE THREAD

**Issue by Ztrohub** [discordjs/discord.js#6598]
### Issue description

I'm pretty sure it's already asked but I still can't find the solution.
I want to check if a user is in a voice channel or not.

If a user is already in a voice channel and I start the bot, it will work perfectly. But when the user disconnects from the voice channel, the bot still think that the user is still in the same voice channel and will return an error:

DiscordAPIError: Target user is not connected to voice.

If I reboot the bot it will say the user is not in a voice channel, but when the user connects to a voice channel, it will keep saying the user is not in the voice channel.

### Codesample

```typescript
let user = mgs.mentions.members.first()

if (!user.voice.channel){
  // User is not in voice channel
} else {
  // User is in voice channel
}
```

### discord.js version

13.1.0

### Node.js version

16.6.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILD_VOICE_STATES

**Comment by almostSouji** [comment]
We gate VOICE_STATE_UPDATE by having the guild available that the state belongs to. This is a caveat in the library that we won't be able to solve in v13, One of the goals for future versions is to support all or almost all combinations of intents.

https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/client/actions/VoiceStateUpdate.js#L7-L12

Accordingly this should resolve itself if you also provide the `GUILDS` intent

**Comment by Ztrohub** [comment]
> We gate VOICE_STATE_UPDATE by having the guild cached that the state belongs to. This is a caveat in the library that we won't be able to solve in v13, One of the goals for future versions is to support all or almost all combinations of intents.
> 
> https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/client/actions/VoiceStateUpdate.js#L7-L12
> 
> Accordingly the channel updating should resolve itself if you also provide the `GUILDS` intent
> 
> > DiscordAPIError: Target user is not connected to voice.
> 
> This however is a bit more of a conundrum, because this is a direct API error by discord. This suggests you are trying to patch the wrong member (maybe an invalid member even, or the right member that simply is not connected or in a in-between limbo state. Former could be a library issue, though I'm presently unsure how)

Thankyou for your respond. DiscordAPIError: Target user is not connected to voice is an error that appears in the next process because I failed to check whether the user is on the voice channel or not. The code is like this:

user.voice.setMute(true, reason);

Do you have a temporary solution to this problem?

**Comment by almostSouji** [comment]
Well, the solution would be to include a check for a user to be connected in said code and:

> Accordingly the channel updating should resolve itself if you also provide the `GUILDS` intent

**Comment by ImRodry** [comment]
I don’t think this should be closed though 🤔

**Comment by Ztrohub** [comment]
I found the solution, I put GUILD_VOICE_STATES intent and it updated correctly.

**Comment by ImRodry** [comment]
Well that part was obvious but what souji said led me to believe there was something to potentially fix here
