### ISSUE TITLE
Feature request: list of reactions on messageReactionRemoveAll

### ISSUE THREAD

**Issue by SethCohen** [discordjs/discord.js#6599]
### Feature

When I try to call messages.reactions.cache inside the messageReactionRemoveAll event, the reactions are already long gone.
The user should be able to get the list of emojis that were removed from a message, just like it would on messageReactionRemove.

### Ideal solution or implementation

messageReactionRemoveAll(message) into messageReactionRemoveAll(message, removedReactions)

```
@param message (Message) – The message that had its reactions cleared.
@param removedReactions (List[Reaction]) – The reactions that were removed.
```

**Comment by shinotheshino** [comment]
It seems strange to pass in an array by-reference to get the list of reactions. If this were implemented I think it would need to be a return value, if anything.

**Comment by SethCohen** [comment]
Simply just returning the `message.reactiosn.cache` collection before it gets cleared would be fine as well.

For [MessageReactionRemoveAll.js](https://github.com/discordjs/discord.js/blob/main/src/client/actions/MessageReactionRemoveAll.js)
```js
'use strict';

const Action = require('./Action');
const { Events, VoiceBasedChannelTypes } = require('../../util/Constants');

class MessageReactionRemoveAll extends Action {
  handle(data) {
    // Verify channel
    const channel = this.getChannel(data);
    if (!channel || VoiceBasedChannelTypes.includes(channel.type)) return false;

    // Verify message
    const message = this.getMessage(data, channel);
    if (!message) return false;

    // The important bit/proposed change:
    const removedReactions = message.reactions.cache; 

    message.reactions.cache.clear();
    this.client.emit(Events.MESSAGE_REACTION_REMOVE_ALL, message);

    return { message, removedReactions };
  }
}

/**
 * Emitted whenever all reactions are removed from a cached message.
 * @event Client#messageReactionRemoveAll
 * @param {Message} message The message the reactions were removed from
 * @param {Collection} removedReactions The collection of removed reactions
 */

module.exports = MessageReactionRemoveAll;
```

**Comment by monbrey** [comment]
This wouldn't work because you aren't cloning the cache, so the next line is still going to clear it. You also aren't providing it to the event.
