### ISSUE TITLE
Bug: Bot runs on 2 instances when I shard

### ISSUE THREAD

**Issue by PasinduDushan** [discordjs/discord.js#6601]
### Issue description

I sharded the bot exactly like it is in the discord.js documentation and after sharding bot started to run on 2 instances. That means when I do a command bot reply 2 times. I logged the guild values on each shard and output was `[2756, 2756]` . When I remove the shard code it works fine. 
Steps to reproduce:
- Make a new file called `index.js` and rename the existing index.js file to `bot.js`
- Copy the sample code and paste it in the `index.js`
- Start the bot
- Run a command in Discord

### Codesample

```typescript
const config = require("./botconfig/config.json");

const { ShardingManager } = require('discord.js');

const manager = new ShardingManager('./bot.js', { token: config.token });

manager.on('shardCreate', shard => console.log(`\nLaunched shard ${shard.id}`));

manager.spawn({ timeout: -1 });
```

### discord.js version

13.1.0

### Node.js version

16.7.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by vladfrangu** [comment]
What client options are you using? That is very important to know too

**Comment by PasinduDushan** [comment]
> What client options are you using? That is very important to know too

```javascript
const client = new Discord.Client({
  intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MESSAGES,
    Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
    Intents.FLAGS.GUILD_VOICE_STATES
  ],
  allowedMentions: { parse: ['users', 'roles'], repliedUser: true },
  presence: {
    status: "online",
    activities: [{
      name: "gr!play",
      type: "LISTENING"
    }]
  },
  fetchAllMembers: false,
  restTimeOffset: 0,
  shards: "auto",
  restWsBridgetimeout: 100,
  disableEveryone: true,
  partials: ['MESSAGE', 'CHANNEL', 'REACTION']
});
```

**Comment by vladfrangu** [comment]
Remove `shards: 'auto'` and try again. You cannot overwrite that property if you use the sharding manager

**Comment by PasinduDushan** [comment]
> Remove `shards: 'auto'` and try again. You cannot overwrite that property if you use the sharding manager

It's worked when I removed `shards` client option. Thank you so much @vladfrangu
