### ISSUE TITLE
Bug: Deleted channels staying cached

### ISSUE THREAD

**Issue by tmantti** [discordjs/discord.js#6602]
### Issue description

When clearing text channels by cloning and deleting, sometimes the deleted channel stays in cache even though it no longer exists. This causes methods like Channel.delete() to fail with DiscordAPIError Unknown Channel. Properties like Channel.name are still accessible from the cache.

### Codesample

```typescript
// TextChannel must have permissions synced with category
// permissionOverwrites.create must change the overwrites
TextChannel.delete()
.then(TextChannel.parent.permissionOverwrites.create(TextChannel.guild.roles.everyone, {VIEW_CHANNEL: false}))
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Priority this issue should have

High (immediate attention needed)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES

**Comment by tmantti** [comment]
I think I found the underlying issue. This might actually be caused by permission overwrite changes to the CategoryChannel, which are done shortly after the cloning and deleting.

I assume Discord API then sends channel updates as overwrites are synced to the children channels, and also sends one for the already deleted channel, causing it to get cached again by both the bot and clients. The channel also appears as a "ghost channel" on Discord clients.

I was unable to reproduce this without the overwrite changes which suggests that cloning and deleting alone isn't the issue.

**Comment by Jiralite** [comment]
> causing it to get cached again by both the bot and clients. The channel also appears as a "ghost channel" on Discord clients.

If this is the case then this issue doesn't seem related to this library and is a Discord bug?

**Comment by vladfrangu** [comment]
> > causing it to get cached again by both the bot and clients. The channel also appears as a "ghost channel" on Discord clients.
> 
> If this is the case then this issue doesn't seem related to this library and is a Discord bug?

Pretty sure its a race condition in both cases, unless the channel that was deleted STILL exists in the eyes of the API, in which case it's an API bug

**Comment by tmantti** [comment]
I updated the codesample on the original comment.

I'm fairly sure this is related to [eventual consistency](https://discord.com/developers/docs/reference#consistency).

Is there a way for discord.js to mitigate this or is it out of scope for libraries to do? Currently the ghost channel, which no longer exists in API, gets stuck in the cache indefinitely. Removing the channel from cache if a method on it results in DiscordAPIError: Unknown Channel would prevent that.

**Comment by Jiralite** [comment]
I would argue that this is out of scope to address. It's viewable in your client because data is present, and it's sent over from the websocket. You delete it in the client and it throws an unknown channel, and that's the same from the API via your bot. It's a Discord issue rather than discord.js.

**Comment by tmantti** [comment]
I agree as the behavior is same on the Discord client.
