### ISSUE TITLE
Bug: Not connect

### ISSUE THREAD

**Issue by Gorniaky** [discordjs/discord.js#6609]
### Issue description

just trying to start the bot...

(node:14304) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (F:\Botdiscord\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (F:\Botdiscord\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at async WebSocketManager.connect (F:\Botdiscord\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (F:\Botdiscord\node_modules\discord.js\src\client\Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Codesample

```typescript
const { Client, Intents } = require('discord.js');
const { token } = require('./config.json');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
	console.log('Ready!');
});

client.login(token);
```

### discord.js version

13.1.0

### Node.js version

14.17.6

### Operating system

Windows 10 Pro 21H1

### Priority this issue should have

High (immediate attention needed)

### Which gateway intents are you subscribing to?

GUILDS

**Comment by vBread** [comment]
#5119

**Comment by SinisterDeveloper** [comment]
You need Node js version **16.6.1+** to use Discord.js version 13
