### ISSUE TITLE
Bug: Cloning of store channels is documented and typed

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6610]
### Issue description

A [`StoreChannel`](https://discord.js.org/#/docs/main/main/class/StoreChannel) possesses the `.clone()` method, but this is not possible to execute. The relevant method, typings and documentation should ideally be removed.

### Codesample

```typescript
const client = new (require("discord.js").Client)({
  intents: [
    "GUILDS"
  ]
});

client.on("ready", () => {
  const channel = client.channels.resolve("id"); // id of a store channel
  channel.clone().catch(console.log);
});

client.login("token");
```

<details>
<summary>Response</summary>

```
DiscordAPIError: Invalid Form Body
sku_id: Store (and only) channels need an associated SKU
    at RequestHandler.execute (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async GuildChannelManager.create (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/managers/GuildChannelManager.js:141:18) {
  method: 'post',
  path: '/guilds/699958129798021170/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: 'rip no icon',
      topic: undefined,
      type: 6,
      nsfw: false,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: '839669589540470815',
      position: 0,
      permission_overwrites: [],
      rate_limit_per_user: undefined
    },
    files: []
  }
}
```
</details>

### discord.js version

13.2.0-dev

### Node.js version

16.6.1

### Operating system

macOS Big Sur 11.5.2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

None.

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

discord.js@13.2.0-dev.1631059454.f57791c

**Comment by SpaceEEC** [comment]
As far as I see are we using three approaches to deal with these kind of things:
- Overwrite the method (and probably docs too) to throw an explicit error (`PartialGroupDMChannel#delete` / `#fetch`). [We could "deprecate" it in the typings to make this unsupported operation less hidden]
- Move clone to something like `ClonableGuildChannel extends GuildChannel` and have everything except `StoreChannel` that is currently extending `GuildChannel` retarget. (Our `_Guild` classes 😀 ) [Won't really work as soon as there is something different that applies differently to guild channels, e.g. below)
- Duplicate clone into all subclasses except `StoreChannel`. (We did that with invites in this inheritance tree already, except that was for not-`CategoryChannel`s)

I probably tend a bit more to the first one, as that creates the least complexity, but that doesn't really translate nicely into the typings (as your example will still compile just fine).

**Comment by MidSpike** [comment]
This issue won't exist too much longer as Store Channels have been [deprecated and marked for removal](https://support-dev.discord.com/hc/en-us/articles/4414590563479) on March 1, 2022.  
> Store channels and the ability to sell game SKUs on Discord will be removed on March 1, 2022.

**Comment by kyranet** [comment]
Since store channels have been deprecated and marked for removal, I have submitted a PR to deprecate them in the typings. I didn't consider the overload to emit a deprecation warning because they always throw (as per this PR's description, I can't test if it still does), and any other action for something that's being removed anyways is a bit overkill for something that will be removed in a few months.
