### ISSUE TITLE
Bug: bot need CONNECT permission to edit Channel

### ISSUE THREAD

**Issue by Xbirdfr** [discordjs/discord.js#6617]
### Issue description

with the bot :
1) create a private category, allow bot's group to view, but remove the CONNECT permission
2) create channel into a category
`category.guild.channels.create()`
3) copy permissions
`channelcreated.lockPermissions()`

and you get a DiscordAPIError: Missing Access

restore the CONNECT permission, no error.

same thing for deleting, missing Access

but on discord api doc, they say the bot need 

MANAGE_CHANNELS

https://discord.com/developers/docs/resources/channel#modify-channel

### discord.js version

discord.js@13.1.0

### Node.js version

discord.js@13.1.0

### Operating system

WSL1 on windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by almostSouji** [comment]
This is not a bug and expected API behavior. The `CONNECT` (for voice channels) or `VIEW_CHANNEL` (for non-voice channels) permission implicitly prevents any action on these channels. Your step 3) is not merely copying permissions, but syncing the permissions with the parent category, thus modifying the child's permissions, which is gated by the implicit `CONNECT` requirement.
