### ISSUE TITLE
Bug: Discord slash command list shows commands that are not coded in

### ISSUE THREAD

**Issue by c0ntxt** [discordjs/discord.js#6620]
### Issue description

The Discord slash list shows commands that are not coded in.

Command List: https://i.imgur.com/ONSTyYE.png
My commands: https://i.imgur.com/k9MZBk2.png

I already waited a few days in case Discord needs to update the command list.

Added my command handler in the Codesample.

### Codesample

```typescript
const { glob } = require('glob');
const { promisify } = require('util');
const globPromise = promisify(glob);

module.exports = async (client) => {
    const commandFiles = await globPromise(`${process.cwd()}/Commands/*/*.js`);

    commandsArry = [];

    commandFiles.map(async (commandFile) => {
        const command = await require(commandFile);

        if(!command.name) return;
        if(command.Perms) command.defaultPermission = false;

        const C = commandFile.split("/");
        console.log(`✅ Loaded ` + command.name.toUpperCase() + ` From ${C[C.length - 2]}`);

        await client.commands.set(command.name, command);
        commandsArry.push(command);
    });

    client.on("ready", async () => {
        const MainGuild = await client.guilds.cache.get("883098999370956890");

        MainGuild.commands.set(commandsArry).then((command) => {
            const Roles = (commandName) => {
                const cmdPerms = commandsArry.find((c) => c.name === commandName).Perms;

                if(!cmdPerms) return null;

                return MainGuild.roles.cache.filter((r) => r.permissions.has(cmdPerms) && !r.managed);
            };
            
            const fullPermissions = command.reduce((accumulator, x) => {
                const roles = Roles(x.name);
                if (!roles) return accumulator;

                const permissions = roles.reduce((a, v) => {
                    return [...a, {id: v.id, type: "ROLE", permission: true}]
                }, []);

                return [...accumulator, {id: x.id, permissions}]
            }, []);

            MainGuild.commands.permissions.set({ fullPermissions });
        });
    });
};
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Operating system

Windows 10 + Linux Debian 10

### Priority this issue should have

Medium (should be fixed soon)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by c0ntxt** [comment]
I get this error when I try to run of the commands that are not coded in

https://hastebin.com/wafuzezere.less

**Comment by DoctorCo** [comment]
Obviously, they need some code to run, discord api wont work if doesn't have any code in it

**Comment by c0ntxt** [comment]
> Obviously, they need some code to run, discord api wont work if doesn't have any code in it

Have you even read my issue report? I don't have the commands coded in. But they still show up in my command list which doesn't make any sense.

**Comment by DoctorCo** [comment]
oh wait is the whole file empty?

**Comment by c0ntxt** [comment]
There is no file for these command. I don't have anywhere in my code the command /embed or /hello.

**Comment by DoctorCo** [comment]
have you added slash commands to the same bot before?

**Comment by c0ntxt** [comment]
I used to have the embed command before but without a slash command handler (!embed)
But I never had a "hello" command

**Comment by ImRodry** [comment]
You likely had these for testing and forgot to remove them. You can remove commands by obtaining their ApplicationCommand object and calling .delete() on it. The issue tracker is for issues with the library, please visit the support server for questions

**Comment by DoctorCo** [comment]
> You likely had these for testing and forgot to remove them. You can remove commands by obtaining their ApplicationCommand object and calling .delete() on it. The issue tracker is for issues with the library, please visit the support server for questions

exactly, this has happened to me alot of times

**Comment by c0ntxt** [comment]
I deleted the whole bot from the Discord developer page and created a new one. The commands are now gone. I still don't know what the issue was.
