### ISSUE TITLE
Bug: MessageEmbed not accepting a date string even though it would be possible to do so

### ISSUE THREAD

**Issue by oof2win2** [discordjs/discord.js#6627]
### Issue description

1. Create an object that has a type of `APIEmbed` from `discord-api-types`
2. Supply it to the `MessageEmbed` constructor
3. Observe TypeScript error

This issue could easily be fixed by making the setup function accept strings too, but throw an error if the input is not a valid date string. I would gladly write it in.

### Codesample

```typescript
import {MessageEmbed} from "discord.js"
import {APIEmbed} from "discord-api-types"

const API = <APIEmbed>{} // this is wrong, but it still throws the same TS error
const Embed = new MessageEmbed(API)
```

### discord.js version

13.1.0

### Node.js version

16.6.2

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which gateway intents are you subscribing to?

None, this doesn't relate to gateway intents

**Comment by ImRodry** [comment]
This seems like a slight oversight as the code already supports the API embed type. Will open a PR with this fix.
