### ISSUE TITLE
Bug: message not work

### ISSUE THREAD

**Issue by Gorniaky** [discordjs/discord.js#6628]
### Issue description

send any message to a text channel in discord but discord.js does not catch this message

### Codesample

```typescript
//index.js
const fs = require('fs');
const { Client, Intents } = require('discord.js');
const { token } = require('./config.json');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

const eventFiles = fs.readdirSync('./events').filter(file => file.endsWith('.js'));

for (const file of eventFiles) {
    const event = require(`./events/${file}`);
    
    if (event.once) {
        client.once(event.name, (...args) => event.execute(...args));
    } else {
        client.on(event.name, (...args) => event.execute(...args));
    }
}

client.login(token);

//events/messageCreate.js
module.exports = {
	name: 'messageCreate',
	async execute(message) {
		consonle.log(message)
    }
};
```

### discord.js version

13.1.0

### Node.js version

16.9.0

### Operating system

Windows 10 Pro 21H1

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

MESSAGE

**Comment by Megatank58** [comment]
In the sample code you didn't include the GUILD_MESSAGES intent

**Comment by Gorniaky** [comment]
> In the sample code you didn't include the GUILD_MESSAGES intent

ok, this is true, but message does not work, What can I do?

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
