### ISSUE TITLE
Bug: Sometimes discord.js doesn't reply to interactions quickly enough.

### ISSUE THREAD

**Issue by LaterIdiot** [discordjs/discord.js#6634]
### Issue description

1. Create a `Message` while replying to a `CommandInteraction`.
2. Create a `ButtonInteraction` from `Message`
3. Collect it in a `InteractionCollector`
4. Invoke a `collect` method during collection
5. Edit the `Message` created earlier to change some state
6. Disable buttons from `Message`
7. `deferUpdate` to remove the interaction failed discord system error message from `ButtonInteraction` (this step is what causes the error from looking at the Stack trace)

I believe this error gets thrown because it takes too long to initially reply to the `ButtonInteraction` (takes more than 3 seconds sometimes).

### Codesample

```typescript
import { ButtonInteraction, Client, Intents, Message, MessageActionRow, MessageButton } from 'discord.js';
const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });

client.on('ready', async client => {
  console.log(`Logged in as ${client.user.tag}!`);

  client.application.commands.set(
    [
      {
        name: 'somecommand',
        description: 'Some description',
      },
    ],
    '854531817561128961',
  );
});

client.on('interactionCreate', async interaction => {
  if (interaction.isCommand()) {
    if (interaction.commandName === 'somecommand') {
      const message = (await interaction.reply({
        content: 'Message',
        components: [
          new MessageActionRow({
            components: [new MessageButton({ style: 'PRIMARY', label: 'Button', customId: '0' })],
          }),
        ],
        fetchReply: true,
      })) as Message;

      const collector = message.createMessageComponentCollector<ButtonInteraction>({
        componentType: 'BUTTON',
        interactionType: 'MESSAGE_COMPONENT',
        time: 30000,
      });

      collector.on('collect', async buttonInter => {
        await message.edit({
          components: [
            new MessageActionRow({
              components: [new MessageButton({ style: 'PRIMARY', label: 'Button', customId: '0', disabled: true })],
            }),
          ],
        });

        // there is nothing in between here in the actual code, so no delay in between

        // this is where the code breaks
        await buttonInter.deferUpdate().catch(console.error);

        // some delay in between
        // I am editing the message second time because it sometimes takes too long to make an initial reply to buttonInter
        await message.edit({
          components: [
            new MessageActionRow({
              components: [new MessageButton({ style: 'PRIMARY', label: 'Button', customId: '0' })],
            }),
          ],
        });

        collector.resetTimer();
      });
    }
  }
});

client.login('ODU0ODYxNDA5NTY4Njg2MDkx.YMqFug.BlgJfvtSUICX_MoUajXkUfcFIq8');
```

### discord.js version

13.1.0

### Node.js version

16.9.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which gateway intents are you subscribing to?

GUILDS

**Comment by monbrey** [comment]
This isn't a timing issue - you're using `message.edit` and breaking the interaction entirely.
You should use `buttonInter.update()` if you wish to edit the message the button is in, and `buttonInter.editReply()` for any additional changes.

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
