### ISSUE TITLE
Bug: Typescript: Property 'commands' does not exist on type 'Client<boolean>'.

### ISSUE THREAD

**Issue by itsravenous** [discordjs/discord.js#6638]
### Issue description

I'm following the code sample in the guide for reading in commands from separate files, rather than using big if statements: https://discordjs.guide/creating-your-bot/command-handling.html#reading-command-files.

This works great in JS, but when I migrated it to TypeScript, I got the following compile error every time I tried to access `client.commands`:

```
Typescript: Property 'commands' does not exist on type 'Client<boolean>'.
```

As it works in JS (and in TS if I chuck in a cheeky `// @ts-ignore`, I'm sure the typings are just slightly incorrect, although looking at [the source for Client](https://github.com/discordjs/discord.js/blob/main/src/client/Client.js) (and [BaseClient](https://github.com/discordjs/discord.js/blob/be8912a4219d1c1aa59a8060707973e567b7b5a3/src/client/BaseClient.js#L12)) I can't see a property or getter/setter for `client.commands`.

I then thought maybe I needed to narrow the type to a more specific kind of client, but I can't see anything in [the typings](https://github.com/discordjs/discord.js/blob/main/typings/index.d.ts) to support that.

For now, I'm slapping a `// @ts-ignore` on it and not worrying too much about it, but I thought you guys would want to know! Hope it's helpful. If you need any more information, just let me know. I'm using TypeScript 4.4.3 if that's of any relevance.

### Codesample

```typescript
Essentially the code sample from the guide, as mentioned above, but here's the full deal I'm working with:


import fs from "fs";
import path from "path";
import { Client, Collection, Intents } from "discord.js";
const { TOKEN: token } = process.env;

if (!token) {
	console.log("Discord token missing - please provide via TOKEN env var");
	process.exit(1);
}

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.commands = new Collection();
const commandFiles = fs
	.readdirSync(path.join(__dirname, "commands"))
	.filter((file: any) => file.endsWith(".ts"));

for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	// @ts-ignore
	client.commands.set(command.data.name, command);
}

client.once("ready", () => {
	console.log("Ready!");
});

client.on("interactionCreate", async (interaction: any) => {
	console.log("interaction created");
	if (!interaction.isCommand()) return;

	// @ts-ignore
	const command = client.commands.get(interaction.commandName);

	if (!command) return;

	try {
		await command.execute(interaction);
	} catch (error) {
		console.error(error);
		return interaction.reply({
			content: "There was an error while executing this command!",
			ephemeral: true,
		});
	}
});

client.login(token);
```

### discord.js version

13.1.0

### Node.js version

16.6.2

### Operating system

Ubuntu 20.04

### Priority this issue should have

Low (slightly annoying)

### Which gateway intents are you subscribing to?

GUILDS

**Comment by ImRodry** [comment]
client.commands is something the guide advises you to create and does not actually exist on the discord Client class. There are 2 alternatives to this:
1. Creating a new class that extends client where you define commands as whatever you want (probably a collection). The issue with this is that you would have to export your client and import it every time you need to use client.commands, or any custom property for that manner
2. Declaring discord.js again and putting commands on the Client class. This is a more hacky way and I personally don’t know if it works fully well but I’ve seen people do it. You can achieve this by doing the following:
```ts
declare module "discord.js" {
    class Client {
        commands: Collection<string, ApplicationCommand> // this is just an example, you can make the type whatever you want
    }
}
```

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.

**Comment by itsravenous** [comment]
> client.commands is something the guide advises you to create and does not actually exist on the discord Client class.

Gotcha! Thanks for taking the time to clarify - much appreciated. I think I'll open a PR on the guide repo, as I think it should be clear that you're just adding a custom property onto an instance of a class you don't own (I can totally see _why_ it's useful to do that, and I'm definitely going to do that in my app for convenience, but to me personally it's not something I'm used to doing).

**Comment by Pukimaa** [comment]
How would the code of the first solution look like @ImRodry ?

**Comment by ImRodry** [comment]
```ts
import { Client, Collection } from “discord.js”

export class CustomClient extends Client {
    commands: Collection<string, ApplicationCommandData> = new Collection()
}

**Comment by Pukimaa** [comment]
Thanks a lot!

**Comment by Pukimaa** [comment]
> Something like this
> 
> ```ts
> import { Client, Collection } from “discord.js”
> 
> export class CustomClient extends Client {
>     commands: Collection<string, ApplicationCommandData> = new Collection()
> }
> ```
Actually I tried it out and for some reason I still experience the error...Am I missing something?

**Comment by suneettipirneni** [comment]
Please join the discord if you need assistance with this, an issue ticket is not for assistance with setting up your code.

**Comment by Pukimaa** [comment]
Ok
