### ISSUE TITLE
Bug: Button - CustomID and URL

### ISSUE THREAD

**Issue by fl3xice** [discordjs/discord.js#6639]
### Issue description

When trying to send a message back to a user with a button that has a link, the following error appears

**Screenshots**
![](https://user-images.githubusercontent.com/52685852/133339116-4697bb5a-8e45-48da-8690-ab1b7425fc53.png)
![](https://user-images.githubusercontent.com/52685852/133339363-4d05abc8-ca35-4fe7-947c-8aee09ed829f.png)

If you try to install a link without custom_id, it tells you that custom_id is required

### Codesample

```typescript
const button = new MessageButton().setStyle("PRIMARY").setLabel("Pong!!!").setCustomId('pongbutton').setURL("https://example.com/");

interaction.reply({
                    content: "Pong!",
                    components: [
                        new MessageActionRow().addComponents(
                            this.button
                        )
                    ],
                    ephemeral: true
                });
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which gateway intents are you subscribing to?

GUILD_MESSAGES

**Comment by Jiralite** [comment]
This is a lack of understanding on your end. As the error already states, you cannot have both a custom id and a URL specified. Only `LINK` buttons can have URLs. This is not a bug.

If you have a general question, ask it in the [Discord server](https://discord.com/invite/djs)!

**Comment by fl3xice** [comment]
> This is a lack of understanding on your end. As the error already states, you cannot have both a custom id and a URL specified. Only `LINK` buttons can have URLs. This is not a bug.
> 
> If you have a general question, ask it in the [Discord server](https://discord.com/invite/djs)!

Oh... Thank you, I just sat in a misunderstanding for a long time and googled it without finding anything.
