### ISSUE TITLE
Bug: ThreadChannel.setName() cannot trim name

### ISSUE THREAD

**Issue by KintonHiryuu** [discordjs/discord.js#6643]
### Issue description

Fetch the ThreadChannel
Try changing the name using `ThreadChannel.setName({name:"here goes your name", reason:"the reason"})`

here's the logs i got :
```
 TypeError: (data.name ?? this.name).trim is not a function
    at ThreadChannel.edit (/myBot/node_modules/discord.js/src/structures/ThreadChannel.js:304:40)
    at ThreadChannel.setName (/myBot/node_modules/discord.js/src/structures/ThreadChannel.js:390:17)
    at /myBot/commands/command.js:125:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Codesample

```typescript
const token = '' //bot token
const channelID = '' //channel ID where the thread message is in
const messageID = '' //message from which the thread was created


const client = new DISCORD.Client({ intents: [DISCORD.Intents.FLAGS.GUILDS, DISCORD.Intents.FLAGS.GUILD_MESSAGES, DISCORD.Intents.FLAGS.GUILD_MESSAGE_REACTIONS] })

client.login(token)

client.once('ready', () => {
console.log('ready')
client.channels.fetch(channelID).then(async c => {
                c.messages.fetch(messageID).then(m => {
                    m.thread.setName({ name: `New Name`, reason: `Bug Reported.` })
                })
            })
})
```

### discord.js version

discord.js@13.2.0-dev.1631664285.88e2622

### Node.js version

v16.9.1

### Operating system

Debian 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

### I have tested this issue on a development release

88e2622

**Comment by monbrey** [comment]
`<ThreadChannel>.setName()` does not accept an object. `name` and `reason` are separate strings.

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
