### ISSUE TITLE
Bug: GuildMemberManager.list doesn't respond with correct data

### ISSUE THREAD

**Issue by LorenzoGala** [discordjs/discord.js#6650]
### Issue description

Goal: acquiring the list of members of the guild related to an interaction and their current voice channel id (if exists)
Starting point: 
`interaction.guild?.members.list({ limit: 1000 })` this, according to the [documentation ](https://discord.js.org/#/docs/main/stable/class/GuildMemberManager?scrollTo=list) should return a _Promise <Collection <Snowflake, GuildMember>>_. 
The issue is that the GuildMember object seems to lack some properties that should have according to the documentation. For example it doesn't have the property "voice" and in order to acquire that you have to extract the user.id from it and do the classic guild.members.cache.get(user.id). 

### Codesample

```typescript
interaction.guild?.members.list({ limit: 1000 }).then(memberList => {
   memberList.each(async (member) => {
       /*
         member here should have the voice property but if you do 
         member.voice.channelId is always undefined. If you console.log(member)
         you are able to see his properties
       */
  )
})
```

### discord.js version

13.1.0

### Node.js version

16.9.0

### Operating system

My application is hosted on Heroku 

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by almostSouji** [comment]
Voice state is not included in [guild member payloads](https://discord.com/developers/docs/resources/guild#guild-member-object) as received by [`GET /guilds/{guild.id}/members`](https://discord.com/developers/docs/resources/guild#guild-member-object)
