### ISSUE TITLE
Bug: Massive ratelimit on changing thread names?

### ISSUE THREAD

**Issue by MarcusOtter** [discordjs/discord.js#6651]
### Issue description

Steps to reproduce:
1. Create a new thread in Discord (doesn't matter if you start it on a message or not).
2. Invoke a slash command that invokes [`await ThreadChannel.setName(string)`](https://discord.js.org/#/docs/main/stable/class/ThreadChannel?scrollTo=setName).
3. The title of the thread should change both the first and the second time the command is invoked.
4. The third time the command is invoked, nothing will happen. No exception is thrown, the execution just waits at `await ThreadChannel.setName(string)`.
5. Wait 10 minutes.
6. The title will change.
   ![image](https://user-images.githubusercontent.com/35617441/133715912-38ef4566-05fa-413a-abf1-5eeaeca23aa4.png)

Other observations:
- The rate limit seems to be bound to each thread. It's possible to create 10 threads in a minute and rename them all twice each without any problems.
- Restarting the bot does not help.
- Changing the thread titles manually in the client works just fine at least 10 times per minute.
   ![image](https://user-images.githubusercontent.com/35617441/133716043-b4201f13-4c7d-4009-a7d9-a838938ae20a.png)

This is half bug report half question. Is this heavy rate limit imposed by discord or is this something arbitrarily done by DJS? Changing it manually in the client works fine as many times as you want, so I don't see why it shouldn't work for bots. 

### Codesample

```typescript
// Example command that you can execute. Remove typescript types if necessary.
async execute(interaction: CommandInteraction): Promise<void> {
    const channel = interaction.channel;
    if (!channel?.isThread()) {
        return interaction.reply("You can only use this command inside a thread.");
    }

    const newThreadName = interaction.options.getString("value");
    if (!newThreadName) {
        return interaction.reply("You need to provide a new thread name when writing the command");
    }

    await interaction.reply(`Attempting to change title to \`${newThreadName}\`.`);

    try {
        await channel.setName(newThreadName);
    }
    catch(err) {
        console.error(err); // Never happens
    }

    await interaction.reply(`Successfully changed title to \`${newThreadName}\`.`);
}
```

### discord.js version

13.1.0

### Node.js version

16.7.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

**Comment by Jiralite** [comment]
This is a rate limit by Discord.

**Comment by monbrey** [comment]
Like all channels, the rate limit on changing names is 2/10mins. I don't see how this is a "bug".

**Comment by MarcusOtter** [comment]
> Changing the thread titles manually in the client works just fine at least 10 times per minute.
And bots can only do this twice per 10 minutes? That seems very off to me?

**Comment by MarcusOtter** [comment]
Don't get me wrong, if it's imposed by Discord I understand there's nothing you can do, so feel free to close if so.

**Comment by MarcusOtter** [comment]
@monbrey I couldn't find this 2/10 rule documented anywhere:
- https://discord.com/developers/docs/topics/rate-limits
- https://discordjs.guide/#before-you-begin

Am I looking in the wrong places?

**Comment by monbrey** [comment]
Discord doesn't document their rate limits. Neither do we.

Discord documents how to have your library listen to and respond to rate limits, which discord.js does.

**Comment by MarcusOtter** [comment]
> Yes, the rate limit is imposed on bots and not users. Bots have different access to APIs compared to users (desktop clients)

Gotcha, thanks for the clarification.


> Discord documents how to have your library listen to and respond to rate limits, which discord.js does.

Found [`Client.rateLimit`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-rateLimit) now by searching the API Docs, didn't find any discussion on rate limits on https://discordjs.guide/ so I'm guessing that event is what you're referring to. I can work with that, thanks.
