### ISSUE TITLE
Bug: `ClientApplication.fetch()` does not work when client application is on Discord Development Portal Team

### ISSUE THREAD

**Issue by SCRplayer2403theDev** [discordjs/discord.js#6653]
### Issue description

1. Create an application in a team (or shift an existing application to a team) and add a bot in the “Bot” tab
2. Do the initials (creating files, etc.)
3. Use the following code in the index.js file.
4. Run the client from the terminal and the `!test` command from a channel the client has access to.

Note: I have used plain text commands here to avoid wasting any time on registering slash commands.

### Codesample

```javascript
// index.js
const Discord = require(‘discord.js’);
const client = new Discord.Client({ intents: [“GUILDS”, “GUILD_MESSAGES”] });

client.on(‘ready’, () => {
   console.log(`Successfully started as ${client.user.tag}`);
});

// We would be using the normal text commands here.
client.on(‘message’, async message => {
   if(message.author.bot) return;
   if (!client.application?.owner) await client.application?.fetch();
   if (message.content === ‘!test’) {
      message.reply(‘Test ran successfully!’);
}
});

client.login(“token here”);
```

### discord.js version

13.1.0

### Node.js version

16.9.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS
GUILD_MESSAGES

**Comment by vladfrangu** [comment]
What's the error you're receiving?

**Comment by SCRplayer2403theDev** [comment]
> What's the error you're receiving?

I am receiving no response. But the application still runs

**Comment by DTrombett** [comment]
> I am receiving no response.

Do you mean the promise is not resolving so the code get stuck at the `await`?

**Comment by DTrombett** [comment]
Also, you're code sample can't work as you're not subscribed to the `GUILD_MESSAGES` intent.

**Comment by SCRplayer2403theDev** [comment]
> Also, your code sample can't work as you're not subscribed to the `GUILD_MESSAGES` intent.
> Retry with intents `['GUILDS', 'GUILD_MESSAGES']` and see if it works.

Added the GUILD_MESSAGES intent it still doesn’t work.

**Comment by SCRplayer2403theDev** [comment]
> > I am receiving no response.
> 
> Do you mean the promise is not resolving so the code get stuck at the `await`?

Well, it works when the Client Application is not in a team. It stops working when the Client Application gets transferred to the team. I receive no response neither in the terminal nor in the form of a message.

**Comment by almostSouji** [comment]
I cannot reproduce the described behavior. 
```js
console.log(client.application?.owner);
if (!client.application?.owner) await client.application?.fetch();
```
Does nothing unexpected here. On the first received message after boot it logs `null` (accordingly fetches the application) and on the second message
```
<ref *1> Team {
  id: '746701571558998127',
  name: 'discord.js testing',
  icon: '848e72d8d515e29ea9bf28f16106d116',
  ownerId: '83886770768314368',
  members: Collection(1) [Map] {
    '83886770768314368' => TeamMember {
      team: [Circular *1],
      permissions: [Array],
      membershipState: 'ACCEPTED',
      user: [User]
    }
  }
}
```
tested on `13.1.0`

**Comment by SCRplayer2403theDev** [comment]
Yeah it works now. Thanks anyways.
