### ISSUE TITLE
Bug: TS InteractionReplyOptions | ReplyMessageOptions typings not consistent with documentation.

### ISSUE THREAD

**Issue by TERRORW0LF** [discordjs/discord.js#6655]
### Issue description

use ts.
1. Create an Embed with the EmbedBuilder and call .toJSON()
2. Try passing it into CommandInteraction.reply()
3. Typescript complains about incompatible types.
4. This also happens when trying to pass an APIEmbed into the MessageEmbed constructor, message.reply(), or any other Interaction.
![Screenshot 2021-09-17 163403](https://user-images.githubusercontent.com/61637480/133800231-eaf56e2c-8659-4e5b-b948-a4f296158ddc.png)

### Codesample

```typescript
import { Embed } from '@discordjs/builders';
import { CommandInteraction } from 'discord.js';

let interaction: CommandInteraction;
const embed = new Embed().setDescription('idk, man. Typings, I guess').toJSON();

interaction.reply({ embeds: [embed] });
```

### discord.js version

13.2.0-dev.1631059454.f57791c

### Node.js version

16.8.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

f57791c

**Comment by TERRORW0LF** [comment]
And I forgot the title...
Should I close and reopen?

**Comment by ImRodry** [comment]
Guess I forgot this in #6629, will PR

**Comment by TERRORW0LF** [comment]
Thank you
