### ISSUE TITLE
Bug: Audit Log type 26 and 27 returning a null target.

### ISSUE THREAD

**Issue by braxtongpoll** [discordjs/discord.js#6657]
### Issue description

1. Join voice channel.
2. Be disconnect or moved.

### Codesample

```typescript
// Disconnect test
let fetchedLogs = await newM.guild.fetchAuditLogs({
    limit: 1,
    type: 27,
});
let disconnect = fetchedLogs.entries.first();
console.log(disconnect);
// Move test
let fetchedLogs = await newM.guild.fetchAuditLogs({
    limit: 1,
    type: 26,
});
let move = fetchedLogs.entries.first();
console.log(move);
```

### discord.js version

13.1.0

### Node.js version

16.6.1

### Operating system

Windows and Linux Ubuntu

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by SpaceEEC** [comment]
I don't think Discord provides a target for these types, does it?

**Comment by ImRodry** [comment]
> I don't think Discord provides a target for these types, does it?

Indeed target_id is null in the response from Discord’s API. If anything this should be reported to them as I believe it would be useful to have this info

**Comment by braxtongpoll** [comment]
> > I don't think Discord provides a target for these types, does it?
> 
> Indeed target_id is null in the response from Discord’s API. If anything this should be reported to them as I believe it would be useful to have this info
> 
> **Edit**: I believe this is intentional as the client does not show what user(s) was(were) moved, only how many they were

Could catch. I didn't actually quit see that until just now looking at it, I am going to go ahead and close this issue and move it over to Discord and see if in a future release they will add this into the API as it would be extremally useful information.
