### ISSUE TITLE
Bug: Ephemeral embeds do not load image attachments properly

### ISSUE THREAD

**Issue by thedjchi** [discordjs/discord.js#6664]
### Issue description

For ephemeral interaction replies, images loaded through MessageAttachments do not display properly. The images are displayed properly if ephemeral is set to false.

Steps to reproduce:
1. Create a bot application and add it to a server with `bot`, `application.commands`, `view channels`, and `send messages` permissions
2. Copy the code sample below into a new js file
3. Open a terminal window in the project folder and run `node index.js`
4. Type `test` in the Discord server. An ephemeral embed should come up but the image doesn't load

### Codesample

```typescript
const { Client, Intents, MessageAttachment, MessageEmbed } = require('discord.js');
const { SlashCommandBuilder } = require('@discordjs/builders');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

const token = 'TOKEN HERE';
const guildId = 'GUILD ID HERE';
const clientId = 'CLIENT ID HERE';

const command = new SlashCommandBuilder().setName('test').setDescription('test').toJSON()
const rest = new REST({ version: '9' }).setToken(token);
(async () => {
	await rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: [command] });
})();

client.on('interactionCreate', async interaction => {
	if (!interaction.isCommand()) return;
	const { commandName } = interaction;

	if (commandName === 'test') {
		const icon = new MessageAttachment('https://i.ibb.co/YkRLWG8/down.png', 'icon.png')
		const embed = new MessageEmbed()
			.setTitle('Test')
			.setImage('attachment://icon.png')
		await interaction.reply({ embeds: [embed], files: [icon], ephemeral: true });
	}
});

client.login(token);
```

### discord.js version

13.1.0

### Node.js version

16.8.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

92f6471

**Comment by SpaceEEC** [comment]
I can reproduce this, this seems to be a Discord bug however: The embed is using the incorrect URL for the attachment.

**Comment by suneettipirneni** [comment]
This seems to have been addressed: https://github.com/discord/discord-api-docs/issues/3842#issuecomment-923249437

**Comment by SpaceEEC** [comment]
Thanks for the info, this seems to be working now! 🎉
