### ISSUE TITLE
Bug: cache fetch option not working as intended

### ISSUE THREAD

**Issue by KokoNeot** [discordjs/discord.js#6667]
### Issue description

1. Fetch all invites for specific guild
2. Use some of the invites from the guild
3. get the old invites from the cache, fetch the guild invites again after joining with invites.fetch({ cache: false }) 
4. see that the new fetch returns what is already in the cache but not the newly fetched data/invites

### Codesample

```typescript
const { Client, Collection } = require('Discord.js')
const bot = new Client({ intents: ["GUILD_INVITES", "GUILD_MEMBERS"] })

const inviteCache = new Collection()

bot.on('inviteCreate', async inv => {
    inviteCache.set(inv.guild.id, await inv.guild.invites.fetch())
})

bot.on('guildMemberAdd', async member => {
    const cachedInvites = bot.invites.get(member.guild.id)

    console.log(cachedInvites.get('invCode').uses) //If new invite then expected = 0, recieved = 0

    member.guild.invites.fetch({ cache: false }).then(newInvites => {
        console.log(cachedInvites.get('invCode').uses) //expected = 0, recieved = 1
        console.log(newInvites.get('invCode').uses)  //expected = 1, recieved = 1
    })
})
```

### discord.js version

13.1.0

### Node.js version

16.6.1

### Operating system

Windows 10 pro

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

### I have tested this issue on a development release

I did not test as I dont know how :(

**Comment by KokoNeot** [comment]
I'm not familiar with this new bug form so I'm gonna add here additional information

on this line it returns whatever is in the cache and not the new data. Because if cache is set to false the new data wont be stored in the cache so its not returned and it returns the old data which are already in the cache.
https://github.com/discordjs/discord.js/blob/d0bc4d7ff037035d4f315a0286b06f0a1ade29c1/src/managers/CachedManager.js#L49

and if this is really a bug then it might be with other fetch methods which accept cache option

**Comment by vladfrangu** [comment]
`cache` represents if we should save the data we get from the API or not. What you are looking for is the `force` parameter. Try that and come back if there's any issues (force: true makes it always fetch from the API, without checking cache)

**Comment by KokoNeot** [comment]
The thing is there is no (or missing) force option in fetchInvitesOption (invites plural) https://discord.js.org/#/docs/main/stable/typedef/FetchInvitesOptions
I need to fetch all invites, and even with cache set to false, I dont think it should return the cached data but it still should return the newly fetched ones.

**Comment by KokoNeot** [comment]
Just checked the source code and there is only force used in _fetchSingle method not in _fetchMany

**Comment by KokoNeot** [comment]
Any update please? I'm still pretty sure this is a bug. Either way force should be added to the fetch all guild invites. And cache should return the newly fetched data not the cached ones.

**Comment by KokoNeot** [comment]
Thank you for the fix, but another question: will there be the force option for fetch all invites?

And ass you can see, I'm not here to cause any harm so I'm peacefully asking if I could get unblocked from this repository on my main github account /DaliborTrampota, where I got blocked for stupid joke for which I many times apologized.
