### ISSUE TITLE
Bug: <title>Emojis dont always show with slash commnads 

### ISSUE THREAD

**Issue by DepressedBunnys** [discordjs/discord.js#6669]
### Issue description

![1](https://user-images.githubusercontent.com/78443317/134076993-39204be0-6aff-4887-ac11-d9b8f236d567.PNG)
![2](https://user-images.githubusercontent.com/78443317/134077010-1a01bab4-30d1-4500-bc4b-62a7a9fb94d7.PNG)

 Emojis don't always show, they show in some servers but not in some

### Codesample

```typescript
https://sourceb.in/y8jDMbXkVC
//Code for the slash command
https://sourceb.in/VNEMKDPXkg
//Code for the normal one (messageCreate)
```

### discord.js version

13.1.0

### Node.js version

16.9.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILD_EMOJIS_AND_STICKERS, GUILD_MESSAGE_REACTIONS

### I have tested this issue on a development release

I have not

**Comment by almostSouji** [comment]
Slash commands use the same technical basis as webhooks, as such they have the same limitations. At the time the "use emojis from other servers" permission needs to be enabled for the default role, `@everyone` for the slash interaction to be able and use it.
Last developer Q&A they have voiced that this is planned to be changed, so slash commands have global emojis without that restriction. After all, people arguably want bots to display their "UI" if they invite them.

Please check if this permission discrepancy is the case here (looks like different servers?). If it is: nothing we can do about it, have to wait for discord to change this behavior.

**Comment by DepressedBunnys** [comment]
The bot has admin perms in the server where the emojis don't show so its not a permission issue

**Comment by almostSouji** [comment]
Might want to re-read the answer, the permissions of the bot itself don't matter, `@everyone` needs the permission. (Webhook limitation, command interactions are webhooks)

**Comment by kyranet** [comment]
Closing this as it's a Discord issue and not a discord.js one.
