### ISSUE TITLE
Bug: Sending Stickers

### ISSUE THREAD

**Issue by Chr1s70ph** [discordjs/discord.js#6670]
### Issue description

I am trying to forward messages sent to my bot via DM. Everything works, except sending the stickers.

Every time I try to send the a message with a sticker, I just get an Error `DiscordAPIError: Cannot use this sticker`.

The code is triggered when a message is sent only in the DMs.

In the [Docs](https://discord.js.org/#/docs/main/stable/typedef/BaseMessageOptions) about sending stickers, it just says it has to be an Array either a [Sticker](https://discord.js.org/#/docs/main/stable/class/Sticker)-Object or a [Snowflake](https://discord.js.org/#/docs/main/stable/typedef/Snowflake). Since I am fetching the sticker Object, I assumed that just grabbing it and passing it into my `messagePayload` would do the job, but somehow the API does not accept it.

### Codesample

```typescript
let userMessage = new discord.MessageEmbed().setDescription(message.content || "᲼")
let messageAttachment =
    message.attachments.size > 0 ? message.attachments.first().url : null
userMessage.setImage(messageAttachment)

let messagePayload = {
    content: null,
    embeds: [],
    stickers: null
}

messagePayload.content = `User <@${message.author.id}> said:`
messagePayload.embeds.push(userMessage)
messagePayload.stickers = message.stickers?.size > 0 ? [message.stickers.first()] : null
client.users.fetch(config.ids.me, false).then((user) => {
    user.send(messagePayload)
})
```

The messagePayload looks like this:
```js
{
  content: 'User <@USERID> said:',
  embeds: [
    MessageEmbed {
      type: 'rich',
      title: null,
      description: '᲼',
      url: null,
      color: null,
      timestamp: null,
      fields: [],
      thumbnail: null,
      image: [Object],
      video: null,
      author: null,
      provider: null,
      footer: null
    }
  ],
  stickers: [
    Sticker {
      id: '749054660769218631',
      description: null,
      type: null,
      format: 'LOTTIE',
      name: 'Wave',
      packId: null,
      tags: null,
      available: null,
      guildId: null,
      user: null,
      sortValue: null
    }
  ]
}

```

### discord.js version

discord.js@13.2.0-dev.1632139402.92f6471

### Node.js version

v16.9.1

### Operating system

Ubuntu 21.04 x86_64

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

discord.js@13.2.0-dev.1632139402.92f6471

**Comment by Jiralite** [comment]
This isn't a discord.js issue. You're trying to send a sticker that doesn't belong to a guild outside of the said guild.
