### ISSUE TITLE
Bug: Error: Cannot find module 'discord.js'

### ISSUE THREAD

**Issue by iQuickGaming** [discordjs/discord.js#6678]
### Issue description

Whenever i try to run my script it throws an error saying Error: Cannot find module 'discord.js'
i ran the command sudo npm install discord.js multiple times, even tried uninstalling and installing it again, even with different versions but it does not seem to work

### discord.js version

13.1.0

### Node.js version

v16.9.1 and v16.6.0

### Operating system

Linux Raspbian 32bit (Debian)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by almeidx** [comment]
Use Discord for questions: https://discord.gg/djs
