### ISSUE TITLE
Bug: Webpack cant find the Module

### ISSUE THREAD

**Issue by eliteSchwein** [discordjs/discord.js#6680]
### Issue description

1. code basic bot in typescript
2. use webpack

### Codesample

```typescript
import * as Discord from 'discord.js'

console.log(new Discord.Client({intents: []}))
```

### discord.js version

13.1.0

### Node.js version

16.6.2

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by iCrawl** [comment]
We don't really support webpack and neither would a bot be able to be run in a browser.

**Comment by eliteSchwein** [comment]
i use webpack to compress it, i dont run it via browser
