### ISSUE TITLE
Bug: Bot doesn't message

### ISSUE THREAD

**Issue by Simonek-loki** [discordjs/discord.js#6687]
### Issue description

Hello, so I was working on my bot on replit.com, and when I run the bot, he works fine but doesnt respond to commands, is there any fix???

### Codesample

```typescript
require("dotenv").config();
const fs = require("fs");
const Discord = require("discord.js");
const keepAlive = require("./server.js");
const { Client, Intents, Permissions } = require("discord.js");
const prefix = ".";

const client = new Discord.Client({ intents: [Intents.FLAGS.GUILDS] });

client.on('message', message => {
	if (message.content === prefix + "sus"){
    message.channel.send("ur sussy here :flushed:");
  }
});

keepAlive();
client.login(process.env.DISCORD_TOKEN);
```

### discord.js version

13x

### Node.js version

v12.22.6

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

839974c

**Comment by SpaceEEC** [comment]
You seem to be missing the `GUILD_MESSAGES` and/or `DIRECT_MESSAGES` intent.

**Comment by Simonek-loki** [comment]
Still doesn't work

**Comment by KokoNeot** [comment]
Also the event should be messageCreate  but that shouldnt affect it yet since its back compatible and youre running old node version. v13 requires v16

**Comment by Simonek-loki** [comment]
How do I upgrade node version in Replit???

**Comment by latitud-dev** [comment]
npm install node@16
npx node

**Comment by Simonek-loki** [comment]
THX VERY MUCH

**Comment by latitud-dev** [comment]
ur welcome ñññ
