### ISSUE TITLE
Bug: My bot doesn't respond

### ISSUE THREAD

**Issue by RodCg** [discordjs/discord.js#6690]
### Issue description

Hello.
I was trying to make a discord bot, but I can't get it to respond, any help?

### Codesample

```typescript
const Discord = require('discord.js')
const config = require('./config.json')

const bot = new Discord.Client({
    intents: [
        Discord.Intents.FLAGS.GUILDS,
        Discord.Intents.FLAGS.GUILD_MESSAGES
    ]
})

bot.on('messageCreate', (message) => {
    if(message.author.bot) return;
    if(message.channel.type !== 'text') return;
    let prefix = '!';
    // hello there ['hello', 'there']
    // !ban user reason ['!ban', 'user', 'reason']
    let MessageArray = message.content.split(' ');
    let cmd = MessageArray[0].slice(prefix.length)
    let args = MessageArray.slice(1)

    if(!message.content.startsWith(prefix)) return;

    if(cmd == 'h') {
        message.channel.send('hello');
    }
})

bot.login(config.token)
```

### discord.js version

13.1.0

### Node.js version

16.10.0

### Operating system

Win10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILD_MESSAGES

**Comment by almostSouji** [comment]
That check for a channel type can't ever be successful. <https://discord.js.org/#/docs/main/stable/typedef/ChannelType>

**Comment by RodCg** [comment]
> That check for a channel type can't ever be successful. https://discord.js.org/#/docs/main/stable/typedef/ChannelType

What you mean? Sorry, I am new at this ://

**Comment by ImRodry** [comment]
> > That check for a channel type can't ever be successful. [discord.js.org/#/docs/main/stable/typedef/ChannelType](https://discord.js.org/#/docs/main/stable/typedef/ChannelType)
> 
> What do you mean? Sorry, I am new at this ://

he means that text is not a valid channel type and linked you all the valid ones

**Comment by RodCg** [comment]
> > > That check for a channel type can't ever be successful. [discord.js.org/#/docs/main/stable/typedef/ChannelType](https://discord.js.org/#/docs/main/stable/typedef/ChannelType)
> > 
> > 
> > What do you mean? Sorry, I am new at this ://
> 
> he means that `text` is not a valid channel type and linked you all the valid ones

ohhhhh, okayyy, thank you
