### ISSUE TITLE
Bug: Embed doesnt work!

### ISSUE THREAD

**Issue by Simonek-loki** [discordjs/discord.js#6691]
### Issue description

Hello, So i was working on meme command and I used embeds, but they dont seem to work, it always crashes bot when I run the command.

### Codesample

```typescript
const fetch = import("node-fetch");

module.exports = {
  name: "meme",
  description: "get some of the spicy funni meme",
  async execute(message, args, Discord, client){
    let data = await fetch("http://meme-api.herokuapp.com/gimme/memes").then(res => res.json);

    const embed = new Discord.MessageEmbed()
    embed.setTitle(data.title)
    embed.setURL(data.postLink)
    embed.setColor("#00ff00")
    embed.setFooter(data.ups + " Upvotes")
    embed.setTimestamp()
    
    message.channel.send(embed);
    

  }
}
```

### discord.js version

13x

### Node.js version

16.6x

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

839974c

**Comment by Jiralite** [comment]
Read [this](https://discordjs.guide/additional-info/changes-in-v13.html#sending-messages-embeds-files-etc) guide.

<hr>

If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.

**Comment by Simonek-loki** [comment]
I tried all of these but embed still doesnt show up.

**Comment by ImRodry** [comment]
> I tried all of these but embed still doesnt show up.

what *exactly* did you try?

**Comment by Simonek-loki** [comment]
Yes I did!

**Comment by Simonek-loki** [comment]
I tried {embeds: [embed]}

**Comment by ImRodry** [comment]
Please close this issue and send your question on the discord server, with the code and full stack trace. The issue tracker is **not** for questions like this

**Comment by Simonek-loki** [comment]
Oh ok...
