### ISSUE TITLE
Bug: Messages duplicates (channel.send) under 100% server CPU load

### ISSUE THREAD

**Issue by driver-by** [discordjs/discord.js#6692]
### Issue description

I have an issue with messages duplication under high server CPU load. It happens not every time, hardly reproducible on my servers (reproduced once) but users of my bot report about 2-3-4 messages duplicates.
I checked plenty of things in my bot and think about some discord.js issue (or good thing went wrong), because I log related `channel.send` usage and in my logs, I get the message only once (I checked specifically cases when it was duplicated).
So the discord.js somehow sends more messages with one `channel.send` and it happens only when CPU is close to 100%.

I was on v12 and migrated to v13, the same story.
Current code:
`channel.send({content: msg, embeds: embed ? [embed] : null})`
in v12 it was
`channel.send(msg, embed)`

Additional info: I use `retryLimit: 5` in the Client constructor. However, from my understanding, it applies to cases when the bot gets 5xx errors and retries it. So it shouldn't be related to the issue.

### discord.js version

13.1.0

### Node.js version

16.9.1

### Operating system

Ubuntu 20.04.2 LTS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILD_MESSAGES

**Comment by JMTK** [comment]
What I've found usually happens is that the socket will disconnect and if you have retries on after it reconnects, it probably re-sends it. You might be able to easily replicate it by putting a breakpoint in a debugger for your code and stepping over the `send` call, waiting for 30 seconds and seeing if it sends multiple

**Comment by driver-by** [comment]
@JMTK thanks for your input. I can't reproduce it with the debugger breakpoint, but trying to run my bot without the `retryLimit`. Will update if it helps.
@JMTK from your understanding of how it works. If I remove the `retryLimit`, I'll prevent duplicates but might have missed messages (because of my 100% CPU load), right?

**Comment by driver-by** [comment]
I have to add that removing `retryLimit: 5` didn't help.

**Comment by driver-by** [comment]
@kyranet thx for the detailed description :+1: It helps me to understand what's happening.
From my side, I'm doing a rework to create a microservice for a heavy job of my app. And want to run it on a separate server (or servers later) to keep a bot itself in peace to interact with the discord smoothly. When ready I can try to run it in a separate thread on the same server at least. I didn't think about your point #2, thx.

In general, I just wanted to understand if I can prevent it from happening while it's being reworked. However. it seems that it will be unreliable in any case. Will do the temp solution, running my heavy job not so often.

It's not really a bug, so the issue could be closed.
