### ISSUE TITLE
Feature request: determine whether an endpoint is rate-limited

### ISSUE THREAD

**Issue by thetracepro** [discordjs/discord.js#6697]
### Feature

We create a bot to change the voice channel's name using the `/name` slash command. As far as I know, there is a rate limit for changing one voice channel's name. (something like two times per 10 minutes, Am I right?). Everything is fine, and we can do this using discord.js just fine. The first and second commands go just fine but in the third one, the user gets this message: `This interaction failed`.

The problem is that discord.js automatically queue this request for the subsequent available request and because we are using `await`, the user gets this error. But we need an option to know if there is an available request or are rate limited? We need to check if we can't change the name of the voice channel, tell that to the user and avoid spamming commands from the user.

### Ideal solution or implementation

I guess a function to get if we are rate-limited for this action or anything to avoid rate limit and error for the users.

**Comment by almostSouji** [comment]
Slash commands have to be responded to within 3 seconds. If you need more time you should defer the response (then it's a matter of how long the webhook interaction token will hold (15 minutes).

"avoid rate limit" is a bit of a misnomer here, you don't really need to avoid rate limits, you just need to stop if you hit it (which discord.js does). What you are hinting at here can probably be done with the `"rateLimit"` event (keep a timestamp of last command use + backoff (this is much harder for less straightforward limits)), though we generally recommend the event to only be used for information purposes.
