### ISSUE TITLE
Feature Request: Control welcome/rules agreement screen appearance

### ISSUE THREAD

**Issue by ItsAquaa** [discordjs/discord.js#6714]
### Feature

**IDEA**
> I've been thinking recently about making a cool warn/mute system if a certain user doesn't read the rules and decides to break them the bot immediately either mutes or warn the user. I was wondering if its possible to control the appearance of the welcome screen where if the user breaks a rule the bot can make immediately make the rules agreement screen pop-up as if he's a new member that didn't accept the rules.

### Ideal solution or implementation

**Here an example:**
```
const { Screens } = require("discord.js")

const userscreen = Screens({
      type: 'Rules',
      userID: message.author.id,
})

userscreen.appear()
```

### Alternative solutions or implementations

N/A

### Other context

it could also be implemented into the guild method and also requested to multiple users in one request.
**here's an example:**
```
//normal client event
message.guild.screens({
     type: 'Welcome',
     userid: [args[0], args[1], args[2]] //arguments as if member or user.
})
```

**Comment by ImRodry** [comment]
I don’t see how this could be done without updating the welcome screen for all users and thus causing quite a lot of API spam

**Comment by ItsAquaa** [comment]
> I don’t see how this could be done without updating the welcome screen for all users and thus causing quite a lot of API spam

I mean.. there could be a possible way to lower the amount of spam. you just have to think about it for a while.

**Comment by almostSouji** [comment]
The bot API does not give you control over the viewing client so you can pop up the welcome screen modal. We can only implement the features the Discord API offers.
