### ISSUE TITLE
bot's banner

### ISSUE THREAD

**Issue by MohaDev-69** [discordjs/discord.js#6716]
### Feature

allow to the bots to change banner color / set image as banner

### Ideal solution or implementation

add a function allow to the bots to change default banner color to another color / add image as banner like discord nitro users .

**Comment by SpaceEEC** [comment]
It doesn't seem to be possible for bots to set their accent colors like users can. (It's simply ignored.)

We can only implement what Discord offers, you can open a request for that over here: <https://github.com/discord/discord-api-docs/discussions>
