### ISSUE TITLE
Get raw data of user input in slash command

### ISSUE THREAD

**Issue by eyal282** [discordjs/discord.js#6728]
### Feature

I have an infinite argument slash command. I cannot swap to message intent deprication slash commands until I can make an infinite argument command where it splits into pairs of two arguments: role and number. Since it's infinite argument I used one string option, but mentioning a role like <@&374948> parses it when the interaction gets to me to the role's name.

### Ideal solution or implementation

Anything that lets me stop the parsing from ruining the <> format into a role name, literally name it I will take it as long as I don't force users to use ``` ``` in their commands.

### Other context

https://github.com/eyal282/Chess-ELO-Discord-Bot

**Comment by ImRodry** [comment]
Not sure if I understood correctly but discord.js already provides resolved role, user and channel data in the CommandInteractionOptionResolver#resolved property so you can use that to retrieve all the mentioned users and roles. Let me know if that helps or if I misunderstood the request

**Comment by Choooks22** [comment]
We've discussed and done some testing on another server, seems like the issue occurs when copy pasting the **entire slash command with its options**, where the user copy pasting `/command option: <@&role-id>` leads to the interaction accepting `option`, but returning the `@role-name` instead of `<@&role-id>`

Not entirely sure if this is from discordjs or discord itself

**Comment by eyal282** [comment]
> We've discussed and done some testing on another server, seems like the issue occurs when copy pasting the **entire slash command with its options**, where the user copy pasting `/command option: <@&role-id>` leads to the interaction accepting `option`, but returning the `@role-name` instead of `<@&role-id>`
> 
> Not entirely sure if this is from discordjs or discord itself

I closed the issue just for not having a mood at even imagining how to describe this. Thank you.

**Comment by ImRodry** [comment]
That’s obviously the user’s fault, if they don’t mention a role Discord can’t possibly resolve it

**Comment by eyal282** [comment]
> That’s obviously the user’s fault, if they don’t mention a role Discord can’t possibly resolve it

"Can't possibly resolve it"

Is converting <@&23573453945> into @Name of the Role not resolving? Why does it resolve it is my question. Again, this happens only if you copy paste the entire slash command, like I told my users to do in this example file:
[Pain.md](https://github.com/discordjs/discord.js/files/7267292/Pain.md)

**Comment by ImRodry** [comment]
When you copy paste a previous command with role or user mentions they will turn into `@Name` because this is the more user friendly way. If anything you should request this improvement to Discord themselves, neither Discord.js nor the api can resolve a role if there is no role to resolve

**Comment by eyal282** [comment]
> When you copy paste a previous command with role or user mentions they will turn into `@Name` because this is the more user friendly way. If anything you should request this improvement to Discord themselves, neither Discord.js nor the api can resolve a role if there is no role to resolve

How to do that?

**Comment by advaith1** [comment]
Pasting commands generally doesn't work anyway and is very unreliable, but you can report issues at https://github.com/discord/discord-api-docs/issues
