### ISSUE TITLE
Get user directly in the VoiceStateUpdate event

### ISSUE THREAD

**Issue by Mathie01** [discordjs/discord.js#6736]
### Feature

In the VoiceStateUpdate event, the User object should be accessed directly.
Why ? Because when a user joins a stage channel via Stage Discovery, we can't get the user object via `state.member.user`.

### Ideal solution or implementation

Be able to access the {User} object directly by doing: `state.user`.

**Comment by SpaceEEC** [comment]
You can access the id of the user through `VoiceState#id` which you can use to fetch it through `UserManager#fetch` (found on `Client#users`).

Discord doesn't document a user directly available on the object so there is unfortunately nothing to cache.

**Comment by Jiralite** [comment]
Additionally, Stage Discovery is actually being sunsetted: https://discord.com/blog/whats-next-for-communities-at-discord

**Comment by Mathie01** [comment]
Thanks!

**Comment by ralphstone1** [comment]
> You can access the id of the user through `VoiceState#id` which you can use to fetch it through `UserManager#fetch` (found on `Client#users`).
> 
> 
> 
> Discord doesn't document a user directly available on the object so there is unfortunately nothing to cache.
