### ISSUE TITLE
sendTyping() giving undefined code error

### ISSUE THREAD

**Issue by Zoro-6191** [discordjs/discord.js#6758]
### Issue description

First of all, the same code worked absolutely fine until few hours ago

Second of all, as soon as I comment `msg.channel.sendTyping()`, bot works just fine again.

Bot had permission integer 8 (administrator) and Bot has all permissions in the channel.
I'm fairly certain I did not mess anything up.

![image](https://user-images.githubusercontent.com/52291201/135892929-f48f3bad-0e3f-4c7f-ae29-c8fb66e35e30.png)

Here's the error
![image](https://user-images.githubusercontent.com/52291201/135892825-288ba881-aa47-4590-96e9-24641fe4a204.png)

If I don't do `.catch()` with `.sendTyping`, it completely crashes the bot.

### Code sample

```typescript
async function commandHandler( msg )
{
    var content = msg.content

    if( !content.length || !content.startsWith(prefix) || msg.author.bot )
        return

    content = content.trim()

    let tokens = content.split(/ +/)

    const cmd = tokens[0].toLowerCase().substring(prefix.length)    // remove prefix

    // create args
    tokens.shift()
    var args = tokens

    if( !cmd.length || bypassedcommands.includes(cmd) )
        return

    msg.channel.sendTyping()
        .catch( console.error )

    // forward to module
    console.log(`Command: ${content} by ${msg.author.tag}`)
    require.main.require(`./commands/${cmd}`).callback( msg, args, result[0] )

    eventhandler.bot.emit( 'command', cmd, args )
}
```

### discord.js version

13.1.0

### Node.js version

16.10.0

### Operating system

Ubuntu 16.04

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by SpaceEEC** [comment]
This is probably related to https://discordstatus.com/incidents/k8jpm6gqr9kx

**Comment by ImRodry** [comment]
This is what the response currently looks like, and there's no way for the client to retrieve this info
![image](https://user-images.githubusercontent.com/38259440/135900745-eb331916-9fad-4090-9904-bfc414bb24a0.png)

**Comment by DiabolusGX** [comment]
> Typing indicators have been re-enabled, and the `/typing` endpoint should no longer return unexpected errors (`403`). All Discord services are operating normally.
