### ISSUE TITLE
followUp feature for normal  message

### ISSUE THREAD

**Issue by losier** [discordjs/discord.js#6766]
### Feature

`message.channel.send` & `message.reply` feel kinda old so a addition of followUp in normal message would be amazing

### Ideal solution or implementation

then only iden soln i can think of is a addition of followUp function for normal message like `message.followUp`

**Comment by almostSouji** [comment]
I'm not too sure what you're requesting here.  A "follow-up" in Discord is an approach to send additional messages with an interaction token after the initial response.

In regular message context that doesn't make a whole lot of sense, as you can just #send more messages.

**Comment by losier** [comment]
> I'm not too sure what you're requesting here.  A "follow-up" in Discord is an approach to send additional messages with an interaction token after the initial response, referencing said response.
> 
> In regular message context that doesn't make a whole lot of sense, as you can just #send more messages.
> A visual approximation would be
> 
> ```js
> msg.channel.send("hello").then(m => m.reply("world"))
> ```
> 
> ![image](https://user-images.githubusercontent.com/26532370/136073759-09c25af0-a278-407b-8268-281e286ad7be.png)
> 
> 

But it will be better for those messages which dont have any args or any context after command nams

**Comment by almostSouji** [comment]
What "will be better"? I don't understand what you want to be implemented.

**Comment by losier** [comment]
I'm just requesting for a followUp feature in message context cuz
1. `message.channel.send` and `message.reply` increase the number of messages in channel
2. It looks kinda messy 
3. We can use followUp feature with interaction but atlast you wil end up having too many interaction commands 

```
Hope it makes sense this time xD
```

**Comment by almostSouji** [comment]
Follow-up on interactions also increases the number of messages in a channel.
Do you mean ephemeral messages, that can just be read by the user using the command?
If so: that's only available for slash command responses

**Comment by losier** [comment]
No i mean that followUp function which is there in interaction yeah it increases the number of message but its better to have one message insted of 2 i mean like if u have a ping command so in normal message context you'll get 2 message in channel 1st by you which trigger the command and second which reply by bot but if you have a `followUp` function then you wont see that trigger message

**Comment by hellobafu** [comment]
I'm not sure if I follow, but are you sure you're not looking for `message.edit`?

**Comment by almostSouji** [comment]
To clarify:
![image](https://user-images.githubusercontent.com/26532370/136078001-098c9f30-a52f-44f8-9413-1d0ede9b5aa2.png)
Do you mean that the command being used is shown above the response (screenshot)?

That's only possible via interactions (slash commands, button presses, selects, etc.). This isn't possible with message-content-based commands. We can only implement features Discord actually provides.

**Comment by losier** [comment]
Then sorry souji for wasting your time i was unaware of that xd
