### ISSUE TITLE
Type error on registering slash commands

### ISSUE THREAD

**Issue by FraWolf** [discordjs/discord.js#6774]
### Issue description

When I try to register slash commands with the REST library (`@discordjs/rest`) it gives me an type error saying that:
Argument of type '`/applications/${string}/guilds/${string}/commands`' is not assignable to parameter of type '`/${string}`'

### Code sample

```typescript
const registerCommand = await rest.put(
      Routes.applicationGuildCommands(APPLICATION_ID!, DEFAULT_GUILD_ID!),
      {
        body: slashCommands,
      }
    );
```

### discord.js version

13.2.0

### Node.js version

Node.js: 16.6.2 | TypeScript: 4.4.3

### Operating system

Windows 10 Pro

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INTEGRATIONS, GUILD_INVITES, GUILD_MESSAGES

**Comment by iShibi** [comment]
What version of `@discordjs/rest` & `discord-api-types` are you on? Can you share your `tsconfig` too 👀

**Comment by cifer1337** [comment]
I'm having the same error but with different a different type. 
```Argument of type 'string' is not assignable to parameter of type '`${bigint}`'.```

This is my function call:
```js
import { Routes } from "discord-api-types/v9";
...
rest
  .put(Routes.applicationGuildCommands(config.applicationId, config.guildId), {
    body: commands,
  })
```
Both applicationId and guildId are Snowflakes, changing them to strings or numbers doesn't help.


I'm using the following versions

- @discordjs/rest@0.1.0-canary.0
- discord-api-types@0.20.2

The tsconfig is from this package `@tsconfig/recommended@1.0.1`
```
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Recommended"
}
```

**Comment by Extacy** [comment]
Updating to the latest typescript version (4.4.3) fixed this issue for me.
