### ISSUE TITLE
Webhook Messages not seen by Client#messageCreate

### ISSUE THREAD

**Issue by MelodicAlbuild** [discordjs/discord.js#6791]
### Issue description
When a webhook sends a message in a channel, the bot doesn't pick it up in the messageCreate event, it prevents the triggering of events when a webhook runs.

1. Create Basic Bot with a messageCreate event trigger.
2. Have a webhook send a message in the server.
3. Watch the bot not pickup the message.

### Code sample

```typescript
const {Client, Intents} = require('discord.js');
const client = new Client({ intents: [Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_WEBHOOKS]})

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}`);
});

client.on('messageCreate', (message) => {
    console.log(message);
})

client.login('example');
```

### discord.js version

13.2.0

### Node.js version

16.10.0

### Operating system

Ubuntu 20.04

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_BANS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MEMBERS, GUILD_PRESENCES

**Comment by monbrey** [comment]
You'll also need the `GUILDS` intent in order to receive messages properly - many Discord.js features rely on the Guild and Channel objects being cached, including messages.

**Comment by MelodicAlbuild** [comment]
@monbrey I updated my intents and still don't get a response, the complete list of updated intents is updated above

**Comment by mcurrao** [comment]
Can also replicate. In my case, following these steps:
1. I send a DM to the Bot directly (not in a guild). 
2. `MessageCreateAction` calls `const channel = this.getChannel(data);`
3. `data` DOES contain the channel ID as `channel_id`.
4. `Action.getChannel(data)` (the implementation) returns `undefined`, despite being a private DM (so should not require a guild intent).
5. `MessageCreateAction` does NOT emmit an event if no channel is available. So the event is just ignored.

**Comment by mcurrao** [comment]
Oh, I see. As @MelodicAlbuild specified no partials configured, I thought it may be the same issue. 
So partials are required for DMs, and GUILD_MESSAGES intent is required for channels. Will give it a try, thanks. 👍
