### ISSUE TITLE
messageDelete not dealing with embeds properly

### ISSUE THREAD

**Issue by N1GHTR4NG3R** [discordjs/discord.js#6792]
### Issue description

Discord ignoring if author is a bot when deleting embeds

1. Run a command that sends an embed
2. Delete the embed on the discord client.
3. Bot errors with `if (!allowEmpty && data.length === 0) throw new error(errorMessage);
                                                ^
RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.`

Here is the full messageDelete code:
`const { MessageEmbed } = require("discord.js");

module.exports = async (bot, message) => {
  // Partial messages do not contain content so skip them.
  if (message.partial) {
    await message.fetch();
  }

  // Get Logs channel
  const modlogs = message.guild.channels.cache.find(
    (ch) => ch.name === bot.defLogs[message.guild.id]
  );

  // Define an empty user to use later
  let userDel;

  // Get who deleted the message
  const deleter = message.guild
    .fetchAuditLogs({ type: "MESSAGE_DELETE" })
    .then((audit) => audit.entries.first());

  // Define the message
  let msg = message.content;
  // Get the attachment URL for images
  let msgAttachment = message.attachments;

  // Check channel and if message author deleted it
  if (
    deleter.channel === message.channel.id &&
    deleter.target.id === message.author.id &&
    // Check time and count
    deleter.createdTimestamp > Date.now() - 5000 &&
    deleter.extra.count >= 1
  ) {
    userDel = deleter.executor.username;
  } else {
    // If checks above fail the deleter is the author
    userDel = message.author.username;
  }

  // Create the embed
  const delMsg = new MessageEmbed()
    .setColor("#CC9010")
    .setTitle("Message Deleted")
    .addFields(
      { name: "__Author:__", value: `${userDel}`, inline: true },
      {
        name: "__Channel:__",
        value: `${message.channel.name}`,
        inline: true,
      },
      { name: "__Deleted Message:__", value: `${msg}` }
    )
    .setThumbnail(message.author.displayAvatarURL())
    .setTimestamp()
    .setFooter(`©️ ` + `${bot.user.tag} 2020`);

  const delMsgDef = new MessageEmbed()
    .setColor("#CC9010")
    .setTitle("Message Deleted")
    .addFields(
      { name: "__Author:__", value: `${userDel}`, inline: true },
      {
        name: "__Channel:__",
        value: `${message.channel.name}`,
        inline: true,
      },
      {
        name: "__Deleted Message:__",
        value: `Embed, System message or message content was too long `,
      }
    )
    .setThumbnail(message.author.displayAvatarURL())
    .setTimestamp()
    .setFooter(`©️ ` + `${bot.user.tag} 2020`);

  // Check it's not a command or a message from the bot then send the log
  // This is to ensure the bot doesn't log commands.
  if (message.author.bot || msg.startsWith(bot.prefix[message.guild.id])) {
    console.log("test");
    return;
  }

  // Check attachments and length
  if (
    msg.length < 1024 &&
    !msgAttachment.first() &&
    message.embeds.length === 0
  ) {
    modlogs.send({ embeds: [delMsg] }).catch(console.error);
  } else if (
    msg.length < 1024 &&
    msgAttachment.first() &&
    message.embeds.length === 0
  ) {
    delMsg.addField("Image URL: ", msgAttachment.first().proxyURL);
    modlogs.send({ embeds: [delMsg] }).catch(console.error);
  } else {
    // Default message if an embed, system message or longer string output.
    modlogs.send({ embeds: [delMsgDef] }).catch(console.error);
  }
};`

If the bot outputs a regular string message the above code works and returns when it should, If it outputs an embed, It continues to ignore if the author is a bot and tries to send an embed which results in an error killing the bot, due to `message.content` being empty

### discord.js version

v13.1.0

### Node.js version

16.10.0

### Operating system

Windows(dev)/Linux(prod)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
