### ISSUE TITLE
Are users supposed to be removed immediately from client.users.cache when they leave a guild?

### ISSUE THREAD

**Issue by Abstract-Programming** [discordjs/discord.js#6794]
### Issue description

When a user leaves a guild, they are still in  `client.users.cache`, and thus their user obj can still be accessed.

This has caused a few bugs to surface in my bot, which users interactions (buttons) to manage users' submitted requests.
If a guild moderator clicks accept/reject on a request, the bot checks to see if the user that submitted the request is in the cache, if they are then the bot attempts to send the user a DM telling them whether their request was accepted/rejected.

Since a user can leave the server, and they're still in cache, an error is thrown as the bot can't send them a DM.

Personally, it makes sense to me they would be removed from the cache if they leave the guild the bot is in (or if the bot is in multiple servers, if they leave all the guilds they share with the bot).

Steps to produce (assuming the guild they join is the only guild they will share with the bot):
1. User joins a guild, a role is given to the user.
2. Check `client.users.cache`, the user is in the cache.
3. User leaves the guild.
4. Check `client.users.cache`, the user is still in the cache yet is not in any guilds with the bot.

The fix:
See the code sample.

### Code sample

```typescript
const {Client} = require('discord.js');
const client = new Client({
    intents: ['GUILDS', 'GUILD_MESSAGES', 'DIRECT_MESSAGES', 'GUILD_MEMBERS'],
    partials: ['CHANNEL']
});
client.on('guildMemberAdd', async member => {
    //give the member a role
});
client.on('guildMemberRemove', async member => {
    console.log(client.users.cache);
    //client.users.cache.delete(member.id);//You need this line to remove them from cache. This line  fixes the issue.
});
```

### discord.js version

13.2.0

### Node.js version

16.10.0

### Operating system

Debian GNU/Linux 10 (buster)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by ImRodry** [comment]
I don’t see why we even need to remove users from the cache though since having these checks in place is more expensive than keeping a few users there until the next restart, in which they’d be removed

**Comment by Abstract-Programming** [comment]
> that could be anywhere up to 2500 `guild.members.cache.has` checks on a single shard

That's a very good point, I had not considered that.
