### ISSUE TITLE
BITFIELD_INVALID discord.js

### ISSUE THREAD

**Issue by Ko1174** [discordjs/discord.js#6805]
So Always When I started my Project i was Missing Intents but after i Added Them I always got the BITFIELD_INVALID Error

Output:

/home/runner/abot/node_modules/discord.js/src/util/BitField.js:152
    throw new RangeError('BITFIELD_INVALID', bit);
    ^

RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: undefined.
    at Function.resolve (/home/runner/abot/node_modules/discord.js/src/util/BitField.js:152:11)
    at /home/runner/abot/node_modules/discord.js/src/util/BitField.js:147:54
    at Array.map (<anonymous>)
    at Function.resolve (/home/runner/abot/node_modules/discord.js/src/util/BitField.js:147:40)
    at Client._validateOptions (/home/runner/abot/node_modules/discord.js/src/client/Client.js:546:33)
    at new Client (/home/runner/abot/node_modules/discord.js/src/client/Client.js:73:10)
    at Object.<anonymous> (/home/runner/abot/index.js:4:14)

### Code sample

```typescript
console.log(process.version + "!\n")

const { Client, Intents } = require('discord.js');
let client = new Client({ intents: [Intents.FLAGS.MESSAGE_CREATE,Intents.FLAGS.GUILD_MESSAGES,Intents.FLAGS.GUILD_MEMBERS] });

const activities_list = 
 [
 "Hello",
 "Hi"
 ];

client.on('ready', () => 
{

})


client.login(process.env['token'])
```

### discord.js version

13.2.0

### Node.js version

16.10.0

### Operating system

Replit

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

USER, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILD_MESSAGES

**Comment by Ko1174** [comment]
It kinda worked i get the error `/home/runner/abot/node_modules/discord.js/src/util/BitField.js:152
    throw new RangeError('BITFIELD_INVALID', bit);` now

**Comment by ImRodry** [comment]
That's still the same error, please use the Discord server like I told you to

**Comment by Ko1174** [comment]
ok
