### ISSUE TITLE
Problem with the website's theme toggler

### ISSUE THREAD

**Issue by Prashoon123** [discordjs/discord.js#6806]
## When the website is in dark mode -
![image](https://user-images.githubusercontent.com/64588766/136694015-127cba7b-9687-4c00-af36-bbb53678f336.png)

## When the website is in light mode -
![image](https://user-images.githubusercontent.com/64588766/136694027-0c8146a1-ea85-4b7b-9010-6c04c988a674.png)

### Ideal solution or implementation

When the website is in dark mode show the sun and when the website is in light mode show the moon.

**Comment by Prashoon123** [comment]
I can work on this issue btw.

**Comment by ImRodry** [comment]
This should probably be transferred to https://github.com/discordjs/website
