### ISSUE TITLE
How do i get the value that the user has input in an option of a command?

### ISSUE THREAD

**Issue by hemfreitas11** [discordjs/discord.js#6813]
### Issue description

Before discord.js implemented slash commands I used the DiscordAPI for this feature, and the way I retrieved the value of an option was `interaction.data.options[0].value` to get the value of the first option of the command for example.
But now that I'm using discord.js for this, I can't seem to figure out how to get the value that the user has set for the option.
![image](https://user-images.githubusercontent.com/67705052/136726409-a38770e1-bf7b-4e53-a4da-89a0646d5a4f.png)

### discord.js version

discord.js@13.2.0

### Node.js version

v16.11.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

### I have tested this issue on a development release

bfb89de

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by almostSouji** [comment]
For future search purposes: Here is a guide on slash commands: <https://discordjs.guide/interactions/replying-to-slash-commands.html#parsing-options>
