### ISSUE TITLE
Slash Command reply() does not return message Object

### ISSUE THREAD

**Issue by saeho** [discordjs/discord.js#6816]
### Issue description

When doing interaction.reply(..) to a Slash command, it does not return a Message object. It returns undefined instead.

i.e. When you do message.reply(..) from a regular chat, it returns a Message object that I can use to either react to my bot's own message, or delete the message etc.

But because the Slash command reply(..) does not return a valid Message object, I cannot do those things mentioned above.

### discord.js version

13

### Node.js version

16.10.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES

**Comment by Jiralite** [comment]
As stated [here](https://discord.js.org/#/docs/main/stable/class/CommandInteraction?scrollTo=reply), a possible return value for this is `void` (`undefined` in your case) and you received it as documented. Also as stated, you need to use the `fetchReply` option to get the bot's reply message. This is not a bug. If you need help, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions).

**Comment by ImRodry** [comment]
Yeah as expected and documented, what’s the issue here?
