### ISSUE TITLE
deletion detection under collectors

### ISSUE THREAD

**Issue by romain22222** [discordjs/discord.js#6830]
### Issue description

hi djs devs, our team might have found a little bug in the latest version of djs (13.2.0)

When i await the deletion of a message in a collector (in the 'collect' part), it does delete it, but i cant collect the information right after (message.deleted) in the 'end' part.

The same is happening about another part of the code, but its about messages edited from a list of message.
if needed, i can share the part of the code where the bug occurs

btw, the code is currently working under 12.X.X, so it must come from 13.X.X

### Code sample

```typescript
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/tree/2.2.2
src/commands/player/FightCommand.js
src/core/fights/Fight.js
src/core/fights/Fighter.js
src/core/fights/FightActionResult.js
```

When you install the bot, it's the !f command :

  - First, when you launch the bot, be with another tester, then both of you enter the command "!test lvl 10", then one of you enter "!f"

  - If you accept the fight, and proceed casually, the history of the fight will not update properly, and the fight will end instantly. The fight ending instantly is due to the fact that we check the deletion of the embedded message when you do an attack. The history is, however, not updating properly because information received by the stored data aren't updated properly, and so it thinks the text from the history message is still blank. It can be shown by updating the content manually.

### discord.js version

13.2.0

### Node.js version

16.11.0, typescript@4.3.2

### Operating system

any, but here, i'm on windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by romain22222** [comment]
well after further digging, the fact is that the doc isnt fully opened about all the changes needed to make about when merging to v13 : when you use message informations after updating the message, before it was crystal clear, but now, you must fetch the message before trying to read their infos

**Comment by romain22222** [comment]
I mean, i really never coded with a minimal djs config, so i think i am not the one to make that MRE, but i can try to pseudo code the bug, so that you can at least find what could go wrong ?

**Comment by SpaceEEC** [comment]
MRE just means that it should focus only on what's necessary to reproduce the reported behavior.
If you can write code using d.js then you can write the MRE just fine.

**Comment by kyranet** [comment]
Bump @romain22222, I tried to check your bot's code, but between the high code complexity and the fact you have two collectors (and did not indicate which one), it is not possible to work with this.

If it helps you making a MRE, you can try [debugging Node.js with VSCode](https://code.visualstudio.com/docs/nodejs/nodejs-debugging) and go step by step, see what fails. You can also check whether or not it's an issue in your code or an issue in the library with this tool.

**Comment by almostSouji** [comment]
If you can provide a reproducible code sample (see instructions above) that still surfaces the issue on the latest stable release (13.6.0 at the point of writing this), feel free to re-open the issue.
