### ISSUE TITLE
On Bot Restart, it returns null for reaction count

### ISSUE THREAD

**Issue by SeenIsHere** [discordjs/discord.js#6848]
### Issue description

1. React to a message
2. Restart your bot
3. Run the code to retrieve how many reactions of a specific emoji there are

### Code sample

```typescript
const { Client, Intents } = require("discord.js")
const client = new Discord.Client({ intents: ['GUILD_MESSAGES', 'GUILD_MESSAGE_REACTIONS'], partials:["MESSAGE", "CHANNEL", "REACTION"] })

client.on('messageReactionAdd', async (reaction, user) =>{
	console.log(reaction.message.reactions.cache.first().count)
})
```

### discord.js version

13.2.0

### Node.js version

16.6.2

### Operating system

RaspbianOS 32bit

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

### I have tested this issue on a development release

7eec061

**Comment by GodderE2D** [comment]
This might not be the actual issue, but you never defined `Discord`, meaning that `Discord.Client` would be undefined.

**Comment by ImRodry** [comment]
This event emits a partial messagereaction object, which means that you must fetch it in order to get all its properties. This is intended behavior

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
