### ISSUE TITLE
Add ban option "delete_message_days"

### ISSUE THREAD

**Issue by Default-01** [discordjs/discord.js#6860]
### Feature

Add ban option "delete_message_days" to remove all messages from a banned member.

### Ideal solution or implementation

Here is a link to the Developer Portal page: 

https://discord.com/developers/docs/resources/guild#create-guild-ban-json-params

### Other context

![image](https://user-images.githubusercontent.com/55616945/137903628-17e32e13-9595-4847-bfd3-41c950ec4ebb.png)

**Comment by SpaceEEC** [comment]
This is already part of the [`BanOptions`](https://discord.js.org/#/docs/main/stable/typedef/BanOptions) as `days`.

Compare with the source here: https://github.com/discordjs/discord.js/blob/26340acad946989e9a8825966b76c506d82fc641/src/managers/GuildBanManager.js#L149
