### ISSUE TITLE
GuildBan unresolved user id

### ISSUE THREAD

**Issue by rilysh** [discordjs/discord.js#6863]
### Issue description

# Issue Description
When I've trying to ban a user who isn't in the same guild by their user ID, `<Message>.guild.members.ban` and when trying to apply it throwing Couldn't resolve user id. I've tried with multiple users user ID but same. And when the same code (a little changes) I used in older version of discord.js (v12) it works fine, by resolving the user ID, but doesn't able to resolve on v13.

# How to reproduce
1. Open any code editor.
2. Paste the line of code `message.guild.members.ban(user_id)`. You may try to v13 and v12 to make sure it able to resolving ID on older version discord.js

### discord.js version

13.2

### Node.js version

17.0.0

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

USER, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_INTEGRATIONS, GUILD_VOICE_STATES, GUILD_MESSAGES

**Comment by thehackerboi69github** [comment]
I can't reproduce, banning members by id works fine for me on v12 and v13
