### ISSUE TITLE
createReactionCollector bugs, and filter not work

### ISSUE THREAD

**Issue by Walkoud** [discordjs/discord.js#6869]
### Issue description

# Introduction

The code was working fine in v12, now I switched to v13 but I saw some inconsistencies and I have a bug.
Here I want to use "createReactionCollector" but I have the impression that the filters do not work.
The bot detect my reaction in multiple collector, idk why.

## First

I will show you an inconsistency: 

![image](https://user-images.githubusercontent.com/38588921/138170765-b4397252-c144-448d-b2ab-092889ced4e9.png)

But when I look in the module files:

![image](https://user-images.githubusercontent.com/38588921/138170911-d79d4311-0cb1-460f-bbf4-a46bb6863ce7.png)

Here, I have the impression that it is the same as the v12

## My bug

![image](https://user-images.githubusercontent.com/38588921/138171099-a3f3edb8-643e-4b6e-b8f7-8d8601531c67.png)

I have the impression that the filter is part of the options and not of "Filter".

## small screen of my project

![image](https://user-images.githubusercontent.com/38588921/138171351-b205f769-fa34-4600-ad62-4273834ca5ea.png)

### Code sample

```typescript
msg.react("⬅️").then(() => {
            msg.react("⏯️")
            msg.react("➡️")
            msg.react('🔉')
            msg.react('🔊')

            const backF = (reaction, user) => {
                //
                return reaction.emoji.name === '⬅️' && user.bot !== true && (user.id === message.author.id || message.guild.members.cache.get(user.id).permissions.has("ADMINISTRATOR") || message.guild.members.cache.get(user.id).roles.cache.some(role => role.id === db.get('channels').find({
                    guildid: message.guild.id
                }).get('djroleid').value()));

            };
            const ForF = (reaction, user) => {

                return reaction.emoji.name === '➡️' && user.bot !== true && (user.id === message.author.id || message.guild.members.cache.get(user.id).permissions.has("ADMINISTRATOR") || message.guild.members.cache.get(user.id).roles.cache.some(role => role.id === db.get('channels').find({
                    guildid: message.guild.id
                }).get('djroleid').value()));
            };

            const back = msg.createReactionCollector({
                backF,
                time: 300000
            });
            const For = msg.createReactionCollector({
                ForF,
                time: 300000
            });


            back.on('collect', (r, user) => {
                console.log(back)
                if (user.bot === true) return

                msg.reactions.resolve("⬅️").users.remove(user.id).catch((err) => {
                    message.reply('Missing permission to remove reaction')
                })
                if (page === 1) return
                page--;
                changeradio(page)
            });



            For.on('collect', (r, user) => {

                if (user.bot === true) return

                msg.reactions.resolve("➡️").users.remove(user.id).catch((err) => {
                    message.reply('Missing permission to remove reaction')
                })
                // blabla etc
            });
```

### discord.js version

13.2.0

### Node.js version

16.11.1

### Operating system

Windows 10 family

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

### I have tested this issue on a development release

579569a

**Comment by nickcognito** [comment]
I believe I am having a relevant issue. I documented the behaviors I am observing in the code snippets themselves. 
I have also tried both of these ways of instantiating the reaction collector object still experiencing the same issues
```
message.createReactionCollector({ filter, time: 15000, max: 1 });
message.createReactionCollector(filter, { time: 15000, max: 1 });
```
Code:
```
client.on('messageCreate', async message => {
    if (message.author.bot) return;

    let filter = reaction => {
        //reaction is not logged
        console.log(reaction)
        return reaction.emoji.name === 'bell';
    };
    
    let collector = message.createReactionCollector({ filter: filter, time: 15000, max: 1 });

    //collector is logged
    console.log(collector);
    
    collector.on('collect', (reaction, user) => {
        //nothing happens here
        console.log(`Collected ${reaction.emoji.name} from ${user.tag}`);
    });
    
    collector.on('end', collected => {
        //this is executed as expected with collector arguments
        console.log(`Collected ${collected.size} items`);
    });


})
client.login(TOKEN)


```
This was initially wrapped in client on ready method, but I read scrolling through forums that someone encountered an error with collector collect events not firing inside of client ready event. Still have the same outputs regardless, really stumped.

**Comment by nickcognito** [comment]
My intents were not correct

Was using
`intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES
 ]`
 
Correct
 `intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES,
        Intents.FLAGS.GUILD_MESSAGE_REACTIONS
  ]`

> I believe I am having a relevant issue. I documented the behaviors I am observing in the code snippets themselves. I have also tried both of these ways of instantiating the reaction collector object still experiencing the same issues
> 
> ```
> message.createReactionCollector({ filter, time: 15000, max: 1 });
> message.createReactionCollector(filter, { time: 15000, max: 1 });
> ```
> 
> Code:
> 
> ```
> client.on('messageCreate', async message => {
>     if (message.author.bot) return;
> 
>     let filter = reaction => {
>         //reaction is not logged
>         console.log(reaction)
>         return reaction.emoji.name === 'bell';
>     };
>     
>     let collector = message.createReactionCollector({ filter: filter, time: 15000, max: 1 });
> 
>     //collector is logged
>     console.log(collector);
>     
>     collector.on('collect', (reaction, user) => {
>         //nothing happens here
>         console.log(`Collected ${reaction.emoji.name} from ${user.tag}`);
>     });
>     
>     collector.on('end', collected => {
>         //this is executed as expected with collector arguments
>         console.log(`Collected ${collected.size} items`);
>     });
> 
> 
> })
> client.login(TOKEN)
> ```
> 
> This was initially wrapped in client on ready method, but I read scrolling through forums that someone encountered an error with collector collect events not firing inside of client ready event. Still have the same outputs regardless, really stumped.
