### ISSUE TITLE
Cannot detect channel or channelId of deleted/updated message

### ISSUE THREAD

**Issue by ev3commander** [discordjs/discord.js#6923]
### Issue description

Messages emitted by events `messageDelete` and `messageUpdate` do not have a defined `channel` property, and their `channelId` is `false`.
1. Add a listener for `messageDelete` that attempts to access the deleted message's channel (as seen in the code)
2. Delete a message
3. Expected behavior: console should properly show the `channel` and `channelId`; actual behavior: `message.channel` is `null` while `message.channelId` is `false`

This appears to have been working at least 2 days ago and probably yesterday, for the purpose of regression testing.

### Code sample

```typescript
client.on("messageDelete", async (message) => { console.log(message.channel); console.log(message.channelId); })
```

### discord.js version

13.3.0

### Node.js version

16.6

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by ev3commander** [comment]
It appears this does not work for either message in the parameters of messageUpdate either.

**Comment by Jiralite** [comment]
I cannot reproduce this on partial or non-partial messages.

Your best bet is to update your code sample to an actual [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and work from there.

**Comment by ev3commander** [comment]
My apologies for not being diligent, after some investigation, I realized the issue is probably with my own code rather than discord.js, because when I reverted to an earlier version of my bot it worked again. Again, I'm deeply sorry for that and will close this issue.
