### ISSUE TITLE
Missing a flag in 'Permissions.FLAGS'

### ISSUE THREAD

**Issue by BryenDaco** [discordjs/discord.js#6924]
### Feature

# Missing a flag in 'Permissions.FLAGS'
I wanted to allow a member to **Manage Permissions** flag in a channel but I could not find that flag. I asked a few developers about this, but they never noticed this.

![Error Image](https://media.discordapp.net/attachments/761200027242594336/903919008263307324/unknown.png)

### Ideal solution or implementation

- Add the _'Manage Permissions'_ flag for **Permissions.FLAGS**.

**Comment by advaith1** [comment]
https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags

> Note that these internal permission names may be referred to differently by the Discord client. For example, **"Manage Permissions" refers to MANAGE_ROLES** and "Use Voice Activity" refers to USE_VAD.
