### ISSUE TITLE
Client has the wrong server count

### ISSUE THREAD

**Issue by Toffee1347** [discordjs/discord.js#6928]
### Issue description

When my bot tries to access its server count using `client.guilds.cache.size`, it always returns a number that's 6 less than the invite link shows it to have (it started off with a difference of one and has slowly increased).

# Example:
The Client side:
![image](https://user-images.githubusercontent.com/67344225/139598561-5b0018e5-5a59-4331-a5c8-3cb02acfbdb5.png)
Discord's side:
![image](https://user-images.githubusercontent.com/67344225/139598568-3c539e07-6ce5-4441-abed-6a0b8a615e0e.png)

One thing that may have caused this is that at one point, the bot joined three servers which all had `undefined` names and member counts. This issue could also be originating from Discord's side, but we believe to be more likely to be on Discordjs's side hence this report.

### discord.js version

13.3.0

### Node.js version

17.0.1

### Operating system

Ubuntu 18.04.5 LTS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by ImRodry** [comment]
> One thing that may have caused this is that at one point, the bot joined three servers which all had undefined names and member counts.
This likely means that these guilds are unavailable to the bot due to a temporary outage. I believe there's nothing we can do to fix it, and you'll simply have to wait for them to come back online

**Comment by Toffee1347** [comment]
> This likely means that these guilds are unavailable to the bot due to a temporary outage. I believe there's nothing we can do to fix it, and you'll simply have to wait for them to come back online

We've been having this issue for over a week now and surely wouldn't Discord have fixed an outage within that time?

**Comment by ImRodry** [comment]
It's possible that those 6 guilds or so are always different ones because some Guilds may always be unavailable at any time, even if no outages are reported on Discord's side

**Comment by vladfrangu** [comment]
One of the things that might happen is that Discord's "Used in x servers" is estimated and not accurate, and I don't know how often they update it. Usually what we get in the cache is all available guilds, as Rodry said, but I, too, doubt there would be outages for so long. However, for your sanity, you can query `https://discord.com/api/v9/users/@me/guilds?after=${lastGuildId}` with your bot token, where `lastGuildId` starts at 0 and is set to the id of the last element in the returned body, and counting how many guilds you actually have. The endpoint returns it in chunks of 200, so in your case 4 requests should be all. If you need help with that let me know on Discord @ Vladdy#0002 👍
