### ISSUE TITLE
RequestHandler error

### ISSUE THREAD

**Issue by Aiko-Dev** [discordjs/discord.js#6932]
### Issue description

I don't know how to reproduce the error, because it is done with one client and not with the other if I change the token. Actually, this error occurs when starting the bot.

### Code sample

```typescript
/Users/aiko/Desktop/Yuzuru/Yuzuru_dev/Yuzuru-Bot/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Form Body
user_id: Value "undefined" is not snowflake.
    at RequestHandler.execute (/Users/aiko/Desktop/Yuzuru/Yuzuru_dev/Yuzuru-Bot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/aiko/Desktop/Yuzuru/Yuzuru_dev/Yuzuru-Bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async UserManager.fetch (/Users/aiko/Desktop/Yuzuru/Yuzuru_dev/Yuzuru-Bot/node_modules/discord.js/src/managers/UserManager.js:70:18) {
  method: 'get',
  path: '/users/undefined',
  code: 50035,
  httpStatus: 400,
  requestData: { json: undefined, files: [] }
}
```

### discord.js version

13.3.1

### Node.js version

16.6.1

### Operating system

MacOSX El Capitan

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, DIRECT_MESSAGES

**Comment by SpaceEEC** [comment]
You seem to be passing `undefined` to `UserManager#fetch` (probably `client.users.fetch(...)` in your code) and not `await`ing the result (as you would have a more useful stacktrace then).

**Comment by Aiko-Dev** [comment]
Hello ^^
Thank you for your quick response.
After research, indeed client.users.fetch were not preceded by "await" but despite correction, no change.
Also, these two client.users.fetch were in the guildCreate and guildDelete events, which are not emitted on startup.

`await client.users.fetch(String(guild.ownerId)).then(...
`

**Comment by Aiko-Dev** [comment]
The bot works! The problem came from the guild Delete event which did not verify that client.isReady () and guild.available returned true

**Comment by SpaceEEC** [comment]
The `guild.available` part is the catch here, your bot was removed from a guild that you did not fully receive yet for whatever reason.
