### ISSUE TITLE
ChannelManager has wrong type parameter

### ISSUE THREAD

**Issue by isaiahtaylor** [discordjs/discord.js#6935]
### Issue description

The `holds` parameter (`Channel`) in the following snippet is wrong:

```ts
export class ChannelManager extends CachedManager<Snowflake, Channel, ChannelResolvable> {
  private constructor(client: Client, iterable: Iterable<RawChannelData>);
  public fetch(id: Snowflake, options?: FetchChannelOptions): Promise<Channel | null>;
}
```

I am aware of the explanations given in #3622, #4708, and #4357. However, these explanations do not seem to be aware of unions.

https://github.com/discordjs/discord.js/issues/3622#issuecomment-565526740
>And that is completely correct. Here are the docs.
Since CategoryChannel, TextChannel, VoiceChannel and other types extend GuildChannel, which itself extends Channel, there is no way there will be send for all of them. You can't send messages to voice channels nor categories.

The issue is that the Cache Manager doesn't hold / yield instances of the super class `Channel`, it holds instances of child classes. We need to interact with those children as their own unique signatures, like `send` or on the other hand voice-specific properties.

https://github.com/discordjs/discord.js/issues/3622#issuecomment-565526742
>The Channel class does not have a send method, because categories and voice channels are also a child classes of the Channel class. When you're certain you have a text channel you can cast it to a TextChannel

The statement "because categories and voice channels are also child classes of the Channel class" is not a good argument for why there shouldn't just be a correct type, like a union. If you need to specify the _ingress_ side of the cache manager to be able to support `Channel` at a minimum, you can use a Generic for that:

```ts
export type ChannelManager = MetaChannelManager<TextChannel | VoiceChannel | CategoryChannel | NewsChannel | StoreChannel | StageChannel | WhateverOtherTypes>;

export class MetaChannelManager<T extends Channel> extends CachedManager<Snowflake, T, ChannelResolvable> {
  private constructor(client: Client, iterable: Iterable<RawChannelData>);
  public fetch(id: Snowflake, options?: FetchChannelOptions): Promise<Channel | null>;
}
```

Also, why be "certain" when you can just check?

```ts
if (channel.type === "GUILD_TEXT") {
  // channel becomes a TextChannel in this block
  channel.send("cats are cool");
} else {
  Debug("Hey, you've got the wrong channel ID! This isn't a text channel!");
}
```

https://github.com/discordjs/discord.js/issues/3622#issuecomment-565547568
>And no, it's not a hack. You need to tell TypeScript what exactly is the thing you want to work on. Since literally every channel type is a Channel, it resolves to that as a default, and it will always be true. This is how you specify type of something.

Yes, it is a hack. See this from the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions):

>Sometimes you will have information about the type of a value that TypeScript can’t know about. ... In this situation, you can use a type assertion to specify a more specific type. ... Reminder: Because type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or null generated if the type assertion is wrong.

Type assertions are for when TypeScript **can't know**. That is not the case here. Each child type at the most granular level has a `.type` member, telling TS exactly which type it is from the union.

Here's a snippet from [Google's TypeScript Style Guide](https://google.github.io/styleguide/tsguide.html#type-and-non-nullability-assertions): 

>Type assertions (x as SomeType) and non-nullability assertions (y!) are unsafe. Both only silence the TypeScript compiler, but do not insert any runtime checks to match these assertions, so they can cause your program to crash at runtime.
Because of this, you should not use type and non-nullability assertions without an obvious or explicit reason for doing so.
When you want to assert a type or non-nullability the best answer is to explicitly write a runtime check that performs that check.

See the if statement above for an example of a runtime check.

If you're not convinced yet, here's a great blog post on the topic: [There is no point using TypeScript if you don’t care about types](https://javascript.plainenglish.io/there-is-no-point-to-use-typescript-in-your-project-if-you-dont-care-about-types-68131deeb43a).

https://github.com/discordjs/discord.js/issues/3622#issuecomment-565703600
>so anyway, if you think you have a solution feel free to PR, but spoiler alert, there's nothing you can do about it, that isnt "hacky", so for that blessed get method you'll simply have to use as all the time.

https://github.com/discordjs/discord.js/issues/3622#issuecomment-565703600
>No, there isn't a way, we have a map, the element returned cannot be determined inside of the typings.

There is a way, using type unions and the `.type` property which exists on every channel child. Here's a non-comprehensive example:

```ts
export class ChannelManager extends CachedManager<Snowflake, TextChannel | VoiceChannel | CategoryChannel | NewsChannel | StoreChannel | StageChannel, ChannelResolvable> {
  private constructor(client: Client, iterable: Iterable<RawChannelData>);
  public fetch(id: Snowflake, options?: FetchChannelOptions): Promise<Channel | null>;
}
```

In my code:

```ts
import { Client, Intents } from "discord.js";

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
    console.log('ready')
    const channel = client.channels.cache.get("<id>");
    if (channel?.type === "GUILD_TEXT") {
        channel.send("cats are cool")
    }
});

client.login(process.env.DISCORD_TOKEN);
```

This works great on latest version. Like I said it's not comprehensive. I would be happy to take a whack at a PR. It should be pretty simple. This logic is already being used here:

```ts
export class GuildChannelManager extends CachedManager<
  Snowflake,
  GuildChannel | ThreadChannel,
  GuildChannelResolvable
> { ... }
```

Thank you.

### Code sample

```typescript
import { Client, Intents } from "discord.js";

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
    console.log('ready')
    const channel = client.channels.cache.get("<id>");
    channel?.send("")
});

client.login(process.env.DISCORD_TOKEN);
```

### discord.js version

13.3.1

### Node.js version

16.13.

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by suneettipirneni** [comment]
Types `Channel` and `Snowflake` have no common ancestry, they are completely different objects. However if we put them into a union it allows us to accept either of them as a type, thus proving its use. 

Now let's take a look at your proposed solution:

`type AllChannels = TextChannel | VoiceChannel | CategoryChannel | NewsChannel | StoreChannel | StageChannel | ThreadChannel | DMChannel | GuildTextChannel | GuildVoiceChannel`

I can't really see how this is beneficial over using the polymorphic type of `Channel`? None of the channels in the union have a completely different base class, in fact all of them are the same, so what exactly does the union improve on?

Furthermore, this type of setup requires more maintenance, than just using the base class. For example, if discord introduces a new channel type you'll create a class like this: 

```
class MyNewAwesomeChannelType extends Channel {}
```
And woohoo, we're done! But actually we aren't. What happened here was we forgot to include it in the `AllChannels` type union, so we now get type errors. If you just used `Channel`s instead, then we can avoid this situation entirely.


### Ok great but if we use `Channel` we can't properly narrow the type without type assertions

This part of the original issue ticket baffled me, since this functionality to narrow `Channel` types is already built-in:

```ts
const channel = client.channels.cache.get("<id>");

// Verify that this is a text channel
if (channel?.isText()) {
  channel?.send("this is a text channel");
}
```

**Comment by isaiahtaylor** [comment]
Ah, I did not see the `isText`, `isVoice`, `isThread` type guards. That's great. I would suggest adding that to those previous tickets in case people search for this in the future. Perhaps add it to the documentation as well.

Now, I still think that the type construction here is anti-pattern, I would suggest looking into it further. But I'm satisfied from a user perspective.

Further thoughts on the type for your internal benefit: You say that unions should be used for types of different ancestry. But actually unions are simply for when something can be 1 of n types. You ask "what does the union improve on?" It improves on accuracy. The type is not accurate. Like I said, it may be accurate enough for the _internal_ purposes of the Cache Manager; but if that's the case, you can just use Generics (see above).

I hear what you're saying about maintenance overhead, but your source code already has arrays and maps of all channel types.
https://github.com/discordjs/discord.js/blob/28688e27d53986478696a74fabd587268b1db5bf/src/util/Constants.js#L477

So you aren't done after declaring the class, you still have to go update some enums. However, this will be an obvious thing to do once `Channel` is that master union (see PR).

I went ahead and put up a PR as a starting point: #6939

**Comment by suneettipirneni** [comment]
> The type is not accurate. Like I said, it may be accurate enough for the internal purposes of the Cache Manager; but if that's the case, you can just use Generics (see above).

Why is this not accurate? `Channel` accepts the same types as the union would.

**Comment by isaiahtaylor** [comment]
This is getting into way into the weeds of manifestations of the [Expression Problem](https://en.wikipedia.org/wiki/Expression_problem), and at this point is mostly academic. However I would just say that this is a misapplication of the Composite Pattern because of the client use cases. From the [wiki](https://en.wikipedia.org/wiki/Composite_pattern) page:

>Composite should be used when clients ignore the difference between compositions of objects and individual objects. If programmers find that they are using multiple objects in the same way, and often have nearly identical code to handle each of them, then composite is a good choice; it is less complex in this situation to treat primitives and composites as homogeneous.

I would submit that the channels cannot be addressed by the client in aggregate, case in point the documentation on discord.js website that has users accessing channel.send.

However as I said this discussion is somewhat academic. I'm satisfied to close the issue.
