### ISSUE TITLE
Embedded images are not loading

### ISSUE THREAD

**Issue by jakeyzadeh** [discordjs/discord.js#6940]
### Issue description

When using `MessageEmbed`, the image added through `setImage` is sometimes not loading in discord. 
After sending the embed, the resultant message from `channel.send` does contain the correct image data which was set, but still, no image appears in discord. 

The image URLs I am using are 100% correct and valid. 
If I send the same image URL 50 times over the course of a day, of those results 40 may contain the image, but 10 still might be coming through without any image. 

I am seeing this behavior regardless of the image URL I use. Even if I take some arbitrary image from Google, the image still may not come through. 

Is there some restriction or expected format of image URLs in order for them to actually be rendered in the Discord client 100% of the time?

This is extremely odd behavior and am hoping for some guidance/resolution.

### Code sample

```typescript
const channel = ...
const embed = new MessageEmbed().setTitle('Some title').setImage('Valid Image URL')
const message = await channel.send({embeds: [embed]})
console.log(message.embeds[0].image) // <--- this is always giving the expected result, but still, image is not actually there
```

### discord.js version

discord.js@13.3.0

### Node.js version

node v17.0.1       typescript@4.4.4

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by monbrey** [comment]
If the images are entirely valid as you suggest, and are working some of the time, then this is a Discord issue, not anything related to discord.js

**Comment by jakeyzadeh** [comment]
Im assuming there is some issue with my implementation, as it seems nobody else is having or has reported this issue. 
Perhaps the success rate is higher for specific kinds of images or URL formats? For example if the URL is suffixed by the extension type eg `https://www.image.com/image.png` ?

**Comment by iShibi** [comment]
Yes, the image link should be a direct link. Make sure the failing one aren't page link that contains the actual image.

**Comment by almostSouji** [comment]
If this isn't even reproducible for yourself at all times, with the same URL, I can't see how it could be a bug with the library. We don't resolve links in any way but provide them to discord as-is. 

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.

**Comment by the-bird-is-the-word** [comment]
@jakes-git Have you found a solution? I have exactly the same problem. Sometimes an image shows, sometimes it does not.

**Comment by megatank58** [comment]
> @jakes-git Have you found a solution? I have exactly the same problem. Sometimes an image shows, sometimes it does not.

https://github.com/discord/discord-api-docs/issues/3002#issuecomment-852557908 As mentioned above this doesn't has anything to do with discord.js
