### ISSUE TITLE
BOT token is not legal http

### ISSUE THREAD

**Issue by Tyrone5693** [discordjs/discord.js#6947]
### Issue description

![Screenshot_2021-11-05-15-18-13-228_com discord](https://user-images.githubusercontent.com/84444757/140528829-c66f5c95-3885-44d9-b728-01cdb8c67146.jpg)
This is my error regenerating token didnt work using repl.it for host
Djs version 13.3.1
Node version 17.0.1

### discord.js version

13.3.1

### Node.js version

17.0.1

### Operating system

Replit linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by Jiralite** [comment]
You very likely have a carriage return or a line feed in your token string. This shouldn't be stripped from discord.js's side - one should not be providing it in the first place.

**Comment by Tyrone5693** [comment]
No i didnt a  mistake like that

**Comment by ImRodry** [comment]
I don’t know where you got that token from but that’s clearly not valid as all tokens have 2 periods

**Comment by kyranet** [comment]
As Rodry pointed out, that's not a valid Discord bot token, they always have 2 periods to represent the three parts they consist of, and the one you shared does not.

We also cannot work without code, but regardless of that, this is not a bug with the library, but in your code. Please ask in our support server at https://discord.gg/djs
