### ISSUE TITLE
CommandInteraction#url

### ISSUE THREAD

**Issue by kanetjuh** [discordjs/discord.js#6953]
### Feature

There is a way to get the url of a massage, but since I can't define that (messages) it would be a great addition to just be able to do ```interaction.url```.

### Ideal solution or implementation

That within the interaction function there will be an option called: `.url` through which I can get the Message Link of that interaction.

Below is an example of what this would be like.
```js
get url() {
    return `https://discord.com/channels/${this.guildId ?? '@me'}/${this.channelId}/${this.id}`;
  }
```
The code above shows how it already happened but for `message`

### Alternative solutions or implementations

You can of course do this manually for both `message` and `interaction`, but because of this you type the link in full (Which is not a problem, but it would be 100x nicer if you can make it work within 15 characters: `interaction.url` = 15 characters)
The code below shows how you could do it manually
```js
`https://discord.com/channels/${interaction.guild.id}/${interaction.channel.id}/${interaction.id}`
```

**Comment by ImRodry** [comment]
Interactions aren't messages and therefore this isn't viable. What you can do is reply to the interaction then get the URL of that message, which is already a thing (see [Message#url](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=url))

**Comment by kyranet** [comment]
Closing due to the reason Rodry mentioned.
