### ISSUE TITLE
voiceStatusUpdate not changing streaming state to false when streaming is concluded

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#6967]
### Issue description

Join a voice channel, begin streaming, and then stop streaming.
<img width="343" alt="Screen Shot 2021-11-10 at 3 16 43 AM" src="https://user-images.githubusercontent.com/54294685/141075693-8c071647-2fab-48c1-a8bb-4d030d9bce06.png">

### Code sample

```typescript
const Discord = require('discord.js');
const client = new Discord.Client({ partials: ['CHANNEL', 'USER', 'GUILD_MEMBER', 'MESSAGE', 'REACTION] });

client.once('ready', () => {
	console.log('Ready!');
});

client.on('voiceStateUpdate', async (oldState, newState) => {
      console.log(newState);
});
```

### discord.js version

13.3.1

### Node.js version

v16.13.0

### Operating system

Debian 10/Mac OS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by iShibi** [comment]
Seems like a Discord bug, the `self_stream` field remains true in the returned payload even after stopping the stream. The `self_video` field has the same issue.

**Comment by iShibi** [comment]
The issue from our side would be this:
https://github.com/discordjs/discord.js/blob/b256ae1fa6cc8350a573b3244c4681876fcd5b45/src/structures/VoiceState.js#L93

`self_stream` is an optional field and it won't be there if you follow the path: `start stream` -> `close stream` -> `start video`. The `streaming` property should be `null/false` but because of the above assignment it remains `true`.

**Comment by pkdev08** [comment]
it works fine on the previous 13-dev versions, not sure where/when it broke.

**Comment by pkdev08** [comment]
For example - Seems to work fine when you use this code instead: https://github.com/discordjs/discord.js/blob/f7eeccba4b7015496df811f10cc2da2b0fab0630/src/structures/VoiceState.js
