### ISSUE TITLE
Message.editable doesn't work in threads

### ISSUE THREAD

**Issue by Pjiesco** [discordjs/discord.js#6969]
### Issue description

Steps to reproduce:
1. register event for the `messageCreate` event.
2. Send a message in a thread
3. See how it fails.

Possible cause (I'm almost certain that this is the cause):
It tries to run `this.channel?.viewable` on the thread channel but thread channels do not have a `viewable` property resulting in null/false

```javascript
  get editable() {
    return Boolean(this.author.id === this.client.user.id && !this.deleted && (!this.guild || this.channel?.viewable));
  }
```
[Source](https://github.com/discordjs/discord.js/blob/3c857a63632ef11a1f7aae00c98e1f1b9909bc87/src/structures/Message.js#L554)

### Code sample

```typescript
client.on('messageCreate', (message) => {
    if (message.channel.type == ChannelType.GuildPublicThread) {
        if (message.editable) {
            message.edit("Edited message");
        }
    }
})
```

### discord.js version

13.3.1

### Node.js version

16.6.1

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING

**Comment by Jiralite** [comment]
> Possible cause (I'm almost certain that this is the cause):
> It tries to run `this.channel?.viewable` on the thread channel but thread channels do not have a `viewable` property resulting in null/false

Yep, that'll be the cause. Thread channels don't have this property, so this becomes `undefined`, so the expression becomes `true && true && (false || undefined)` which gets converted to `false`.
