### ISSUE TITLE
Mentions in interactions not parsing correctly

### ISSUE THREAD

**Issue by LukeHankey** [discordjs/discord.js#6974]
### Issue description

Mentions are not being parsed correctly when you defer a reply to an interaction.

The below image shows a context menu with the allowedMentions property set to parse roles which pings the role in the server. The second uses a slash command where the response is deferred. I even passed in the same allowedMentions property from the context menu to the slash command.

EDIT: The Context Menu no longer pings the role when used in another server, where the role name is exactly the same
```javascript
// Works in one server, but not another
const role = interaction.guild.roles.cache.find(role => role.name === 'Affiliate Events')
await interaction.reply({ content: role.toString(), allowedMentions: { parse: ['roles'] } })
```

![image](https://user-images.githubusercontent.com/68163698/141401079-e29e962b-26e2-43a3-98e5-fa49bc085a69.png)

Using `interaction.reply({ content: role.toString(), allowedMentions: { parse: ['roles'] } })` works, but not for deferring the reply.

I had also thought that mentions of any kind would be parsed without including the allowedMentions property considering DAPI docs have [examples](https://discord.com/developers/docs/resources/channel#allowed-mentions-object-allowed-mentions-reference) as such.

### Code sample

```typescript
const role = interaction.guild.roles.cache.find(role => role.name === 'Affiliate Events')

// With and without the allowedMentions object, there is no role ping.
await interaction.deferReply({ allowedMentions: { parse: ['roles'] } })
await interaction.editReply({ content: role.toString(), allowedMentions: { parse: ['roles'] } })
```

### discord.js version

13.3.1

### Node.js version

16.6.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

### I have tested this issue on a development release

5e0a7d5

**Comment by Jiralite** [comment]
Mentions only ping recipients when a message is sent - not edited. Also, the fact that you state it works in one server and not the other is simply the case of permissions.

Ultimately, your issue is not related to discord.js and if you want this to change, you should take this issue to Discord.

**Comment by LukeHankey** [comment]
> Mentions only ping recipients when a message is sent - not edited. Also, the fact that you state it works in one server and not the other is simply the case of permissions.
> 
> Ultimately, your issue is not related to discord.js and if you want this to change, you should take this issue to Discord.

Ok, the editing makes sense but in regards to the permissions. What sort of permissions would the bot need specifically to mention a role? I've tried turning on every permission there is for the bots managed role without success.

After looking into it more, it was the @everyone role that had the permission to mention @everyone, @here, and all roles. It seems strange that this is needed for interactions/webhook messages because as a normal message, this works fine for only specific roles to have that permission.

![image](https://user-images.githubusercontent.com/68163698/141466895-2514aee2-a8d6-441d-8ebf-1e7e67afb55f.png)

I will head on over to DAPI docs.
