### ISSUE TITLE
Unarchiving a thread causes `THREAD_UPDATE` to be invoked twice

### ISSUE THREAD

**Issue by suneettipirneni** [discordjs/discord.js#6985]
### Issue description

1. Create a thread
2. Archive the thread (prints "thread updated")
3. Unarchive the thread (prints "thread updated" twice)

When I anarchive the thread the `THREAD_UPDATE` event should be called only once, but instead it is called twice. When you archive a thread however, it's correctly called only once.

### Code sample

```typescript
client.on('threadUpdate', (oldThread, newThread) => {
    console.log('thread updated');
});
```

### discord.js version

13.4.0-beta

### Node.js version

16.6

### Operating system

macOS 12.01

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES

### I have tested this issue on a development release

5e0a7d5

**Comment by suneettipirneni** [comment]
This may or may not be an upstream issue, just wanna verify here first.

**Comment by Jiralite** [comment]
Just to be clear, this isn't really a discord.js issue. This happens when someone with manage threads permissions unarchives a locked thread. Discord first sends the change of the `archived` property then sends in another event the change of the `locked` property.

**Comment by suneettipirneni** [comment]
> Just to be clear, this isn't really a discord.js issue. This happens when someone with manage threads permissions unarchives a locked thread. Discord first sends the change of the `archived` property then sends in another event for the change of the `locked` property.

If this is the case, why does archiving a thread not cause two events even though it's changing the `locked` and the `archived` state?

**Comment by SpaceEEC** [comment]
Discord seems to actually dispatches two thread updates when unarchiving and unlocking a thread at the same time.
I don't think there is much discord.js can do about that, it seems like we forward the updated properties properly.
Although I also wonder why there are two updates dispatched here.
