### ISSUE TITLE
Members' voice-channel permissions don't update after role removal.

### ISSUE THREAD

**Issue by WilcoM** [discordjs/discord.js#6986]
### Issue description

Bot doesn't update voice channel permissions after a role has been removed from a user that grants these permissions.

Steps to reproduce:
1. Make sure you have your bot running and can run the code below on command, without restarting
2. Create a role with connect/speak permissions for a specific voice-channel.
3. Give yourself this role, and connect to this channel.
4. Run the code below, and see that the SPEAK/CONNECT permissions are logged.
5. Remove the role, but stay connected.
6. Run the code below again, and see that the SPEAK/CONNECT permissions are still listed.
7. Restart the bot, and run the code below again, and see that the SPEAK/CONNECT permissions are no longer there.

### Code sample

```typescript
const guild = await client.guilds.fetch('guild-id');

guild.members.fetch('user-snowflake').then(
    member => {
      console.log(member.voice.channel.permissionsFor(member,false).toArray());
    }
).catch(console.error);
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Ubuntu 18.04.5 LTS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES

**Comment by Jiralite** [comment]
Unless there was something amiss in your steps or my reproduction, I was not able to reproduce this issue: https://i.gyazo.com/5b0632b6d2f84790b3af0b1d170db5ea.mp4

On a new server, the `@everyone` role had no permissions (0n) and the test role had no permissions (0n). The voice channel had the test role to explicitly allow connecting and speaking. Upon running the above code sample, the two permissions were logged with the test role applied to the test account and were not logged upon removing the test role from the test account, all within the client being online.

**Comment by WilcoM** [comment]
> Unless there was something amiss in your steps or my reproduction, I was not able to reproduce this issue: https://i.gyazo.com/5b0632b6d2f84790b3af0b1d170db5ea.mp4
> 
> On a new server, the `@everyone` role had no permissions (0n) and the test role had no permissions (0n). The voice channel had the test role to explicitly allow connecting and speaking. Upon running the above code sample, the two permissions were logged with the test role applied to the test account and were not logged upon removing the test role from the test account, all within the client being online.

Do you grab the member / perms from `interaction.member`? That seems to work fine for me too. When I do it through guild members as above it won't..

**Comment by Jiralite** [comment]
> Do you grab the member / perms from `interaction.member`? That seems to work fine for me too. When I do it through guild members as above it won't..

If you saw the GIF, you would have your answer - there were no interactions.

I'm assuming this is an error on your side somewhere. Try to recreate your issue in a fresh, new server with discord.js alone as the sole dependency to ensure no other conflicts and see what happens.
