### ISSUE TITLE
Error login in 

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#6993]
### Issue description

![image](https://user-images.githubusercontent.com/69215407/142039066-3f614c98-b03a-48fe-a238-9b948ddeeedb.png)

### Code sample

```typescript
const { Client } = require("discord.js");
const client = global.Client = new Client({ intents: [32767] });

client.login(Config.Token).catch(console.error);
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Glitch

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING

**Comment by vladfrangu** [comment]
Discord's having issues right now, monitor it at https://discordstatus.com

**Comment by wioniqle-q** [comment]
> Discord's having issues right now, monitor it at

Okey, thank you for answering
