### ISSUE TITLE
Add Event support

### ISSUE THREAD

**Issue by waki285** [discordjs/discord.js#6995]
### Feature

Discord has recently added Bot support for Events.  
- https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-create
- https://discord.com/developers/docs/resources/guild-scheduled-event
- [discord/discord-api-docs#3586](https://github.com/discord/discord-api-docs/pull/3586)

### Ideal solution or implementation

Add these to the client events and
- guildScheduledEventCreate
- guildScheduledEventUpdate
- guildScheduledEventDelete
- guildScheduledEventUserAdd
- GuildScheduledEventUserRemove

Add `scheduledEvents` to the Guild object.

Then add the `Event` class and the `EventManager` class.

**Comment by Jiralite** [comment]
Already in progress! #6493

**Comment by waki285** [comment]
oh
