### ISSUE TITLE
Support Guild Scheduled Events apis

### ISSUE THREAD

**Issue by rhoiyds** [discordjs/discord.js#6996]
### Feature

Discord has recently released and published documentation on the [Guild Scheduled Events](https://discord.com/developers/docs/resources/guild-scheduled-event) feature.
Discord.js should cover interactions and typings for these new objects and endpoints.

### Ideal solution or implementation

Provide functions and typings for this new feature.

**Comment by Jiralite** [comment]
Already in progress! #6493

**Comment by rhoiyds** [comment]
@Jiralite Woah, apologies, I did a quick search in the current issues, but must've skipped over it. Closing the issue.
