### ISSUE TITLE
`Interaction.reply()` with the `fetchReply` option returns a message object with no Message prototype

### ISSUE THREAD

**Issue by ElectrifyPro** [discordjs/discord.js#7001]
### Issue description

When the `Interaction.reply()` method is used with the `fetchReply` option set to `true` (and the interaction being a `CommandInteraction`, I'm not sure if this occurs on the other `Interaction` classes) the returned object does not have the `Message` prototype on it when it should.

```js
// Assume that `inter` is a `CommandInteraction` received from the `interactionCreate` event.
const message = await inter.reply({ content: 'test', fetchReply: true });
console.log(message);
// {
//   id: 'some message ID',
//   type: 20,
//   content: 'test',
//  ...
```

Without the prototype, one cannot call methods defined on `Message` without adding the prototype back:

```js
const message = await inter.reply({ content: 'test', fetchReply: true });
message.delete();
// TypeError: Cannot read properties of undefined (reading 'delete')
```
```js
const {Message} = require('discord.js');
const message = new Message(inter.client, await inter.reply({ content: 'test', fetchReply: true }));
message.delete();
// message gets deleted
```

### Code sample

```typescript
// index.js
const {Client} = require('discord.js');
const client = new Client({intents: 4609});
client.login('something');
client.on('interactionCreate', async inter => {
    if (inter.isCommand()) {
        const message = await inter.reply({ content: 'test', fetchReply: true });
        message.delete(); // error!
    }
});
```

### discord.js version

13.2.0

### Node.js version

v16.10.0

### Operating system

Windows, Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by Jiralite** [comment]
[As documented](https://discord.js.org/#/docs/main/stable/class/CommandInteraction?scrollTo=reply), an `APIMessage` is a possible return value. This happens when you receive an interaction from a guild that the client is not in. This is not a bug.

**Comment by ElectrifyPro** [comment]
I see. But the client is indeed in the guild that the interaction came from.

**Comment by suneettipirneni** [comment]
> I see. But the client is indeed in the guild that the interaction came from.

Whats the output of `inter.inCachedGuild()`?

**Comment by ElectrifyPro** [comment]
It outputs `true`

**Comment by Jiralite** [comment]
The final decider of receiving a `Message` or `APIMessage` is if your client has a `ChannelManager` (which I assume it does) and if it has the relevant channel in the cache to add the message to. If you're sweeping channels, then the fallback there is an `APIMessage`. Is that what you're doing?

**Comment by ElectrifyPro** [comment]
> If you're sweeping channels, then the fallback there is an `APIMessage`. Is that what you're doing?

Ah, that makes sense; it's exactly what I'm doing. Thank you for clearing this up.
