### ISSUE TITLE
setOwner

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7004]
### Issue description

I don't know what it does, it says "Sets a new owner of the guild," but when I use it, nothing happens. Sets a new owner of the guild means changing the crown holder on the server. even if nothing happened, is the command containing bug or is my use incorrect

### Code sample

```typescript
Guard.on("messageCreate", async msg => {
  if (msg.content === "sa") {
    let memb = await Guard.users.fetch("");
    msg.guild.setOwner(memb)
  }
})
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Glitch

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by ImRodry** [comment]
In order to set a new owner on the guild, your bot must be the owner of said guild, it can’t change that otherwise

**Comment by wioniqle-q** [comment]
> In order to set a new owner on the guild, your bot must be the owner of said guild, it can’t change that otherwise

Then what's the point of that? If I'm going to make the boat crowned, why would I use it? the important thing is to change the owner of the server when the bot is not the crown owner

**Comment by wioniqle-q** [comment]
![image](https://user-images.githubusercontent.com/69215407/142489911-1dc274ed-6e56-4b4f-8d1c-ffb4ff622070.png)
also do not have a button to make the boot crown holder

**Comment by ImRodry** [comment]
The point of that is to be able to transfer the guild’s ownership to a different user when the owner is the bot. Only the owner of a guild can change who the owner is, so it doesn’t make sense for the bot to be able to do this if the bot isn’t the owner

**Comment by almeidx** [comment]
The bot must create the guild for it to be the owner

**Comment by wioniqle-q** [comment]
I'm going to take a look, thank you.
