### ISSUE TITLE
Sending embeds in specific channels doesn't work

### ISSUE THREAD

**Issue by Existential-nonce** [discordjs/discord.js#7010]
### Issue description

I'm trying to send an embed into a channel where it'll say the bot is online. The code that's provided here works well if I put `channel.send("some text")`, so I tried to create an embed and set that as the `channel.send()` argument but it doesn't work. The error message says: 

```
Argument of type 'MessageEmbed' is not assignable to parameter of type 'string | MessagePayload | MessageOptions'.
  Type 'MessageEmbed' is not assignable to type 'string'.ts(2345)
```

### Code sample

```typescript
client.on('ready', async (client) => {
   const embed = new MessageEmbed()
   .setDescription(`The bot is now online :white_check_mark:`)
   .setColor(`#27e462`)

   const channel: TextChannel = client.channels.cache.get("123456789") as TextChannel;
   await channel.send(embed);
});
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Fedora 34

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by ImRodry** [comment]
Reading the update guide helps https://discordjs.guide/additional-info/changes-in-v13.html

**Comment by Existential-nonce** [comment]
> Reading the update guide helps https://discordjs.guide/additional-info/changes-in-v13.html

Thanks! it works perfectly now.
