### ISSUE TITLE
Extends error

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7017]
### Issue description

Why having this error?

![image](https://user-images.githubusercontent.com/69215407/142761636-2b6ce6a8-8340-41b9-b2b5-738cd69d7b00.png)

### Code sample

```typescript
const { Structures } = require("discord.js");

Structures.extend("Guild", Guild => {
  return class MyGuild extends Guild {
    constructor(client, data) {
      super(client, data);
    }
    /**
    * @param {string} type
    */
    async find_entry(type) {
    }
  };
});
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Glitch

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by SpaceEEC** [comment]
Structures were removed with https://github.com/discordjs/discord.js/pull/6027, which was released with `13.0.0`.

Refer to the PR for what you should use instead.
