### ISSUE TITLE
ContextMenuInteraction does not return a message for message commands

### ISSUE THREAD

**Issue by dewinterjack** [discordjs/discord.js#7021]
### Issue description

The Discord [docs show](https://discord.com/developers/docs/interactions/application-commands#message-commands-example-interaction) that a message is returned in the interaction. Should ContextMenuInteraction not have the message on it? I am getting the targetId which I assume I can use to get the message however it feels like the message should be included in the response.

### Code sample

```typescript
client.on('interactionCreate', async interaction => {
	if (!interaction.isContextMenu()) return;
	console.log(interaction);
});
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

alpine

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

**Comment by ImRodry** [comment]
You should be reading the discord.js docs and not the discord docs. The message is available at interaction.options.getMessage(“message”)
