### ISSUE TITLE
MessageReactionAdd event triggered twice

### ISSUE THREAD

**Issue by Zeldash** [discordjs/discord.js#7025]
### Issue description

1. create a simple messageReactionAdd event, handled by an event handler (see code sample)
2. react to any message (as long as the bot has access to the channel)
3. two console ouputs instead of one expected
4. no errors, no crash, whole code still running

So i wanted to make a messagReactionAdd event that would react to the 👀 emoji, to reveal the content of a crypted message, etc.
And for that, i created the code below, to check if my code was properly working as i was a bit rusty with that event. 
And for some reasons, the event was being activated twice.

![2021-11-24 11_41_23-Webstorm– messageReactionAdd js](https://user-images.githubusercontent.com/64431032/143223660-ebc6a7ba-c23c-449c-b4cc-94e0f6414931.png)
![2021-11-24 11_42_32-Discord](https://user-images.githubusercontent.com/64431032/143223666-92de15e7-22d1-413c-bb3e-79c281fc8449.png)

### Code sample

```typescript
// index.js
const Discord = require('discord.js');
const config = require('./config.json');
const fs = require('fs');
// const allIntents = new Discord.Intents(32767);
const bot = new Discord.Client({
    intents: ['GUILDS', 'GUILD_MESSAGES', 'DIRECT_MESSAGES', 'GUILD_MESSAGE_REACTIONS'],
    partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER']
});

bot.login(config.token)

bot.commands = new Discord.Collection();

fs.readdirSync("./commandes/").forEach(dirs => {
    let commands = fs.readdirSync(`./commandes/${dirs}`).filter(files => files.endsWith('.js'))
    for(let file of commands) {
        let getFileName = require(`./commandes/${dirs}/${file}`)
        bot.commands.set(getFileName.help.name, getFileName)
    }
    console.log(`${commands.length} commandes chargés dans le dossier ${dirs}`);
});

fs.readdir('./events/', (error, f) => {
    if(error) console.log(error);
    console.log(`${f.length} events en marche`);

    f.forEach((f) => {
        const events = require(`./events/${f}`)
        const event = f.split(".")[0];

        bot.on(event, events.bind(null, bot));
    });
});

bot.login(config.token)

--

// messageReactionAdd.js
module.exports = async (bot, reaction, user) => {
    console.log('event working')
}
```

### discord.js version

13.2.1

### Node.js version

16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

### I have tested this issue on a development release

9f3bf29

**Comment by Zeldash** [comment]
note - i did many things to try to fix this issue, such as restarting my whole computer, reinstalling all the modules after deleting the npm cache, trying to install discord.js@13 instead of discord.js@13.2.1, made sure that i had only one instance running, made sure that i had only one messageReactionAdd.js file, etc etc...

**Comment by PalmDevs** [comment]
You are logging in calling `login` on `bot` 2 times, that might be the issue.
The first login is called on index.js line 10 and the second is line 35.
![image](https://user-images.githubusercontent.com/67689562/143434382-708bbb2f-06d9-4af7-8b83-dcfe99fe58f1.png)

**Comment by Zeldash** [comment]
Ah, thanks for that, i asked about 30 different people for help (mostly certified developpers) and none of them found that, so, big big thanks :)

I still wonder why bot.login() twice only triggers messageReactionAdd and messageReactionRemove twice tho...
