### ISSUE TITLE
Attaching a BufferResolvable while using a remote file in an embed will result in 403 HTTP error from GCP

### ISSUE THREAD

**Issue by ianeli1** [discordjs/discord.js#7031]
### Issue description

Using the example code below (nevermind the fact that it's gonna reply to itself), it'll be impossible to access the embed's main image but the thumbnail will be rendered just fine. 

Trying to access the embedded image URL will result in a HTTP 403 error from Discord's CDN: `Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.`

Reloading Discord using Ctrl + R will solve this issue.

Switching to using only MessageAttachment objects, as shown in the 2nd part of the example code below, will result in a successful operation every time.

Is this behavior intentional?

### Code sample

```typescript
import { Client, Intents, MessageEmbed, MessageAttachment } from "discord.js";
import { config } from "dotenv";
import jimp from "jimp";

function dummyImage() { //generates a buffer PNG
  return new jimp(100, 100, 0x0).getBufferAsync(jimp.MIME_PNG);
}

config();
const client = new Client({
  intents: [Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILDS],
});

client.once("ready", () => console.log("ready"));

client.on("messageCreate", (msg) => {
  const embed = new MessageEmbed();
  embed.setThumbnail(
    "<url here>crayon.png"
  );
  embed.setImage("attachment://bufferImage.png");
  dummyImage().then((buffer) => {
    msg.channel.send({
      embeds: [embed],
      files: [new MessageAttachment(buffer, "bufferImage.png")],
    });
  });
});

client.login(process.env.TOKEN);

// ** WORKING VERSION **

client.on("messageCreate", (msg) => {
  const embed = new MessageEmbed();
  embed.setThumbnail(
    "attachment://thumb.png"
  );
  embed.setImage("attachment://bufferImage.png");
  dummyImage().then((buffer) => {
    msg.channel.send({
      embeds: [embed],
      files: [
        new MessageAttachment(buffer, "bufferImage.png"),
        new MessageAttachment("<url here>crayon.png","thumb.png"),
      ],
    });
  });
});
```

### discord.js version

13.1.0

### Node.js version

16.13.0

### Operating system

Mac OS, Ubuntu, Docker

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

**Comment by vladfrangu** [comment]
That's because that's not how you reference attachments in your message. You use the attachment:// protocol instead

**Comment by ianeli1** [comment]
If that's the case, the information on MessageEmbed.setImage is a bit misleading... https://github.com/discordjs/discord.js/blob/5ec04e077bbbb9799f3ef135cade84b77346ef20/src/structures/MessageEmbed.js#L391-L395

The [embed constructor](https://discordjs.guide/popular-topics/embeds.html#using-the-embed-constructor) does take in URLs and the information about "attachment://" being used for attachments (such as the buffered image I'm creating) is also available, but using both at the same time was not considered.

**Comment by vladfrangu** [comment]
Oh wait, then I must've misread the issue (sorry, it was early morning)

If you're using an already existing CDN url, that should work, since we don't download the image, so if it breaks it's on Discord 😓

**Comment by kyranet** [comment]
This feels more like a Discord-side issue, and as the message above said, we do not download the images. In fact, we just pass the URL as JSON, and it's the Discord client what downloads the images.

Just so I can understand your issue better, you were getting an error in your client, and after a refresh, it started working?

If so, that's nothing we can fix, since that's on Discord :/

As a side note, I'd advise you to upgrade to latest version, 13.1.0 is a bit outdated and is missing a lot of patches.

**Comment by kyranet** [comment]
Closing this issue since it seems to be on Discord's side.
