### ISSUE TITLE
MessageSelectMenu stop working when I add more than 25 options

### ISSUE THREAD

**Issue by IzzyCap** [discordjs/discord.js#7038]
### Feature

It Will be nice If I am able to add more options on MessageSelectMenu, currently the element stops working when I add option number 26.

### Ideal solution or implementation

Let the developer decide the maximum options per MessageSelectMenu

### Alternative solutions or implementations

Increase the maximum options

**Comment by Jiralite** [comment]
But... why? A select menu cannot have more than 25 options?

**Comment by suneettipirneni** [comment]
This is not something that discord.js can address we are a wrapper for the API and the API doesn't allow more than 25 components.
