### ISSUE TITLE
The command 

### ISSUE THREAD

**Issue by Horia-bee** [discordjs/discord.js#7044]
### Issue description

Look what i do:
run:yarn add discord.js and have this error: bash: yarn: command not found

### discord.js version

13.3.1

### Node.js version

v10.24.1

### Operating system

Raspberry pi os/based on debian

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by SpaceEEC** [comment]
You have to install yarn in order to use it, you can find about that on https://yarnpkg.com/.
(You can also use npm, which you likely already have installed for this)

**Comment by vladfrangu** [comment]
This is not a discord.js issue, if you want to use yarn you need to have it installed. You can find out more here: https://yarnpkg.com/
Alternatively, you can keep using npm. That's up to you tho
