### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by abysxl** [discordjs/discord.js#7046]
### Issue description

```js
TypeError: Cannot read properties of undefined (reading 'type')
    at Function.create (/workspace/node_modules/discord.js/src/structures/BaseMessageComponent.js:62:21)
```
an error occurred while i am creating the MessageButton, looks like it just needs to handle a bit [here](https://github.com/discordjs/discord.js/blob/main/src/structures/BaseMessageComponent.js#L62)

### discord.js version

13.3.1

### Node.js version

17

### Operating system

Win 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES

**Comment by ImRodry** [comment]
That method expects some data to always be sent so you must've missed a parameter somewhere. It's impossible to know what happened without the full stack and a minimal reproducible example

**Comment by kyranet** [comment]
Please provide us a [MRE](https://stackoverflow.com/help/minimal-reproducible-example) so we know what's triggering that issue. Just that cut error is useless and does not tell us anything.
