### ISSUE TITLE
Add Message#awaitEmbeds method to get URL embeds in a message

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#7053]
### Feature

I would like to suggest the creation of a Message#awaitEmbeds method. This method can only be used for messages received in the messageCreate and messageUpdate (in case of content changes) events, but I still think it would be quite useful to have. It would work as a way to ensure that all the URLs on the message get embedded and that the message is updated accordingly so that we can retrieve data from those embeds.

### Ideal solution or implementation

This method would return a Promise with an array of all the embeds in the message. There are a few things to keep in mind however:

- Amount of non-escaped URLs in a message (the ones without <>) which should be equal (or lower) to the amount of embeds returned
- Whether the message has the SUPPRESS_EMBEDS flag, in which case the promise should reject
- Whether the client has the message content intent (after April 2022)
- Promise shouldn't take more than X seconds (I recommend 5 or 10) to resolve. If it doesn't, it should reject, meaning that whatever URL was on the message didn't get an embed.

### Alternative solutions or implementations

The only way to check for this at the moment is to listen to the messageUpdate event, however, having this method would help a lot. I realize it may be hard to create which is why I've created this issue to see if it's viable and to hopefully inspire someone to do it. I had no other ideas that could make this work but if you do, feel free to reply with them!

**Comment by monbrey** [comment]
Interesting concept, not sure I really see any viable way to implement it though.

As you pointed out, there isn't really any determinate way to know if a message is supposed to have embeds or not, which means even when an embed comes through, how do you confirm that the promise is ready to resolve? How many embeds is a success?

How are they being waited for? I'd assume a messageUpdate collector model, bound to the message id, checking for embed changes? 

Current collector flows are based on a model where a wait time is expected. The bot has already performed it's action, and is happy to wait 30 seconds for a button response or equivalent. I'm not sure introducing a 5 second delay in processing the body of a message is viable in many contexts.

**Comment by ImRodry** [comment]
Unless the message is edited by a bot to add more embeds than it had, whenever a message gets updated with extra embeds, these are always all URL embeds that should be going on the message (you can even see this behavior on the client).

the 5/10 second delay I suggested would only come into place in case you don’t get extra embeds. This means that if you start awaiting the embeds and get some, the promise resolves. If you don’t get any extra embeds during those 5 seconds then the promise resolves (or rejects) with the embeds that the message has at that point. There’s no way to determine if a url will get embedded, only if it gets hyperlinked (which is a requirement to get the embed) so that’s the only thing we can base ourselves off of when making this method

**Comment by ImRodry** [comment]
@iCrawl this was not implemented, can you please reopen the issue?

**Comment by iCrawl** [comment]
No plans to implement this.

**Comment by ImRodry** [comment]
Then close it properly, it wasn’t completed. Also may I know why?

**Comment by MarcusOtter** [comment]
I would actually really want this as well, but I understand that it would be challenging to implement. What a shame!

**Comment by MarcusOtter** [comment]
I did a dumb solution but it seems to work fine for my purposes. If there might be an embed on the message, wait for 2 seconds and then fetch the msg again:

```ts
if (this.mayContainEmbed(message) && message.embeds.length === 0) {
	await wait(2000);
	message = await message.fetch();
}
```
```ts
private mayContainEmbed(message: Message): boolean {
	const permissions = message.member?.permissionsIn(message.channelId);
	if (!permissions?.has(PermissionFlagsBits.EmbedLinks)) return false;
	if (!hasUrl(message.content)) return false;
	return true;
}
```
```ts
export function hasUrl(input: string): boolean {
	return (input.match(/\b(https?):\/\/[^\s]+\.[^\s]+/gim)?.length ?? 0) > 0;
}
```
