### ISSUE TITLE
Possibility to customize the defer message at deferReply

### ISSUE THREAD

**Issue by nftnoob** [discordjs/discord.js#7055]
### Feature

Possibility to customize the defer message at deferReply

### Ideal solution or implementation

additional field "message" at deferReply() options

**Comment by ImRodry** [comment]
This is something you have to ask Discord as the API currently does not allow this, and even then I doubt they’d add such a thing, but it’s worth trying if you give them convincing examples and use cases for that.

**Comment by almostSouji** [comment]
We can only implement features into discord.js that are supported by the Discord bot API.
