### ISSUE TITLE
channel.messages does not include guildID with request to api

### ISSUE THREAD

**Issue by Kief5555** [discordjs/discord.js#7061]
### Issue description

1. get the channel (object) By doing ```const channel = client.channels.cache.get("id here")```
2. Try to find a message in that channel by doing ```channel.messages.fetch(messageid)```
3. Error should present if self (at the bottem)
4. I think its trying ping discord for: ```https://www.discord.com/channels/916439976776990770/messages/736427050339926079```
but i need it to ping with the guildid ```https://www.discord.com/channels/736427049870426165/916439976776990770/messages/736427050339926079```

Error below.
```/Users/kieferlin/Projects/Tasklogger/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (/Users/kieferlin/Projects/Tasklogger/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/kieferlin/Projects/Tasklogger/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager._fetchId (/Users/kieferlin/Projects/Tasklogger/node_modules/discord.js/src/managers/MessageManager.js:219:18) {
  method: 'get',
  path: '/channels/916439976776990770/messages/736427050339926079',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}```

### Code sample

```typescript
const { Message, Client, MessageEmbed } = require("discord.js");

module.exports = {
    name: "completed",
    aliases: ['c'],
    /**
     *
     * @param {Client} client
     * @param {Message} message
     * @param {String[]} args
     */
    run: async(client, message, args) => {
        const guild1 = client.guilds.cache.find((g) => g.id === "736427049870426165")
        const channel = client.channels.cache.get("916439976776990770")
        const messageid = args[0]
        /*channel.messages.fetch(messageid)
        .then(message => console.log(message.content))
        .catch(console.error); */
        if (!messageid) return message.reply({ embeds: [new MessageEmbed()
            .setTitle('Error')
            .setDescription('Provide a messageID.')
            .setColor("RED")] })
        if (channel.messages.fetch(messageid)) {
            (message => console.log(message.content))
        } else {
            const embed = new MessageEmbed()
            .setTitle('Error')
            .setDescription('I could not find that assignment.')
            .setColor("RED")
            message.reply({embeds: [embed]})
            
        }
    },
};
```

### discord.js version

13.1.0 and @dev

### Node.js version

node v16^ djs 13^ npm 8^

### Operating system

Tested with MacOS monterey

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL, MESSAGE

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_PRESENCES

### I have tested this issue on a development release

discord.js@13.3.1 and @dev

**Comment by Nciklol** [comment]
According to the [dapi docs](https://discord.com/developers/docs/resources/channel#get-channel-message) the url schema is `/channels/:id/messages/:msgid`. I'm unsure where you're getting this guild ID schema?

**Comment by Kief5555** [comment]
> According to the [dapi docs](https://discord.com/developers/docs/resources/channel#get-channel-message) the url schema is `/channels/:id/messages/:msgid`. I'm unsure where you're getting this guild id schema?

Its responding with an error where I cant not find a message when it is present.

**Comment by Jiralite** [comment]
> > According to the [dapi docs](https://discord.com/developers/docs/resources/channel#get-channel-message) the url schema is `/channels/:id/messages/:msgid`. I'm unsure where you're getting this guild id schema?
> 
> Its responding with an error where it cant not find a message when it is present.

Is it?

The channel id "916439976776990770". The message that was being fetched is "736427050339926079". That's clearly an impossible API request - a message in a channel cannot be younger than the channel itself.

I'm not sure what the issue actually is here (I'm guessing you think the request path is wrong?) but it seems to be an error in your code.

**Comment by Kief5555** [comment]
Sorry my bad, I right clicked the message to copy the id, however, it copied something else for some reason.
