### ISSUE TITLE
Ready Event not executing after loading files 

### ISSUE THREAD

**Issue by DeshanXD** [discordjs/discord.js#7081]
### messageCreate Event is loading properly and I can execute and commands in guild but ready event is not executed what's so ever!
I can execute any command using this handler and it says loading successfully on terminal as well. but it says `

> [WS => Shard 0] Shard received all its guilds. Marking as fully ready`. on runtime

I uploaded all my code to github [here](https://github.com/DeshanXD/BetterStacy.Ts)

![code](https://user-images.githubusercontent.com/30923476/145246843-76d13364-73a1-4a51-ba03-d77f3780fe56.png)

### Code sample

```typescript
import { Event } from "../interfaces/Event";

export const event: Event = {
  name: "ready",
  run: (client) => {
    console.log(
      `${client.user.tag} is online on ${client.guilds.cache.size} servers!`
    );

    client.user.setActivity("!help | betterstacy.me", {
      type: "PLAYING",
    });
  },
};

// Above I defined my ready event

    const eventPath = path.join(__dirname, "events");
    readdirSync(eventPath).forEach(async (file) => {
      const { event } = require(`${eventPath}/${file}`);
      if (event.run) {
        console.log(`Loaded Event: ${event.name}`);
        this.on(event.name, event.run.bind(null, this));
      } else {
        console.log(`Loading failed Event: ${file}`);
      }
    });

// Above event loader into extended Class

 public events: Collection<string, Event> = new Collection();
// Collection in extended class

import { BetterStacy } from "../Bot";
import { ClientEvents } from "discord.js";

interface Run {
  (client: BetterStacy, ...args: any[]);
}

export interface Event {
  name: keyof ClientEvents;
  run: Run;
}
// Event Interface
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by SpaceEEC** [comment]
This is a race condition, you are loading the events after calling `Client#login`.
To ensure all events are being handled, login after ensuring all handlers were attached. (This includes having a sync callback, which you do not seem to have for no obvious reason.)
