### ISSUE TITLE
`MessageManager#fetch()` does not work as documented

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#7093]
### Issue description

There seems to be a bug in the documentation or the code itself for [`MessageManager#fetch()`](https://discord.js.org/#/docs/main/main/class/MessageManager?scrollTo=fetch).

Both parameters are listed as optional. I proceed to only make use of the `options` parameter as I don't care about specifying a message limit, but I _do_ care about caching them. TypeScript yells that the overload is not valid:

```TypeScript
<Client>.once(<Constants>.Events.CLIENT_READY, async () => {
  const channel = <Client>.channels.resolve("channel_id") as TextChannel;

  // error TS2769: No overload matches this call.
  await channel.messages.fetch({
    cache: false
  });

  console.log(channel.messages.cache.size); // 50
});
```

Upon executing the above code sample in JavaScript, 50 messages are fetched as expected as is the default but the returned messages are cached as not expected.

Either the internal code logic and typings are not correct here, or this isn't documented correctly. Personally, I'd lean towards supporting this because, why not?

### Code sample

```typescript
import { Client, Constants, Intents, TextChannel } from "discord.js";

const client = new Client({
  intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MESSAGES
  ]
});

client.once(Constants.Events.CLIENT_READY, async () => {
  const channel = client.channels.resolve("765676229478711366") as TextChannel;

  await channel.messages.fetch({
    cache: false
  });


  console.log(channel.messages.cache.size);
});

client.login();
```

### discord.js version

13.4.0-dev

### Node.js version

Node.js 16.13.0 & TypeScript 4.4.4

### Operating system

macOS Monterey 12.0.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

### I have tested this issue on a development release

6e57b65

**Comment by ImRodry** [comment]
Your own description of the issue seems to indicate that it does work as documented. The fact that both parameters are optional doesn’t mean they don’t have to follow an order and thus, if you want to specify an argument with BaseFetchOptions, you have to provide an empty object for ChannelLogsQueryOptions first. Perhaps this could be improved so that the latter supports cache as a property too but imo that sounds a bit messy

**Comment by Jiralite** [comment]
I'd like to draw your attention to [`ApplicationManager#fetch()`](https://discord.js.org/#/docs/main/main/class/ApplicationCommandManager?scrollTo=fetch) where both parameters are also optional there too. If one specifies only `BaseFetchOptions` which is the second parameter, it works as expected. Application commands are fetched and cached as desired. The functionality I'm describing in this issue already exists elsewhere.

**Comment by ImRodry** [comment]
I have never seen this sort of documentation and tbh it seems like an oversight to me. It’s nice that you can specify the options as the first parameter, but that should be documented, much like it already is on other methods. I guess that could work and the functionality could be implemented into the MessageManager as long as the documentation specifies that the id parameter (ideally called idOrOptions) can be either a Snowflake or the options typedef.
