### ISSUE TITLE
button on webhook not showing

### ISSUE THREAD

**Issue by XzFrosT** [discordjs/discord.js#7097]
### Issue description

when I try to send webhook with button the button not showing, the webhook was sent without button even though i add components in `send` options

there's no error showing, so I guess its bug or webhook can't have components?

Step to reproduce 
1. send webhook with button components

### Code sample

```typescript
const get_the_webhook = new WebhookClient({ id:..., token: ...});

if(get_the_webhook)
{
   const row = new MessageActionRow()
   .addComponents(
      new MessageButton()
        .setCustomId('primary')
	.setLabel('Primary')
	.setStyle('PRIMARY')
   );
   
   await get_the_webhook.send({ username: "report", content: "some text", components: [row] })
}
```

### discord.js version

13.3.1

### Node.js version

16.6

### Operating system

ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by Jiralite** [comment]
[Discord's documentation](https://discord.com/developers/docs/resources/webhook#execute-webhook) states you can only send components if it is an application-owned webhook. It's looking like yours is not.

**Comment by XzFrosT** [comment]
it does not log in as bot, it's just a WebhookClient

**Comment by SpaceEEC** [comment]
It's possible, you just need to use a webhook created by your bot (strictly speaking: application) and not one created by a user.
