### ISSUE TITLE
Collection link broken on v12 docs

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/discord.js#7101]
### Issue description

![image](https://user-images.githubusercontent.com/76178582/145706868-2c532734-3e7b-4024-8c97-e7f12097cb92.png)
When browsing old documentation, the Collection link takes you to the old branch master, instead of main, which results in this error message:
![image](https://user-images.githubusercontent.com/76178582/145706944-a6e71c15-1b57-4936-aad5-38d6852fc3d7.png)
This applies to all of version 12 docs.

### discord.js version

12.5.3

### Node.js version

N/A

### Operating system

N/A

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

N/A

**Comment by kyranet** [comment]
v12 is deprecated and will not receive any more updates. Please update to v13 at your earliest convenience.
