### ISSUE TITLE
There is no type safe way to send a message to a channel

### ISSUE THREAD

**Issue by vcarl** [discordjs/discord.js#7116]
### Issue description

[The guide](https://discordjs.guide/popular-topics/faq.html#how-do-i-send-a-message-to-a-specific-channel) recommends the following code to send a message to a channel:

```js
const channel = await client.channels.fetch('id');
channel.send('content');
```

Using Typescript, there is no way to accomplish this without casting. This means there is no way to use types to prevent bugs. #5280 recommends `isText()` but TS still errors when using that.

### Code sample

```typescript
const channel = await client.channels.fetch('id');

if (channel?.isText()) {
  // Property 'send' does not exist on type '(Channel & PartialDMChannel) | 
  // (Channel & DMChannel) | (Channel & TextChannel) | (Channel & NewsChannel) | 
  // (Channel & ThreadChannel)'.
  //  Property 'send' does not exist on type 'Channel & PartialDMChannel'.ts(2339)
  channel.send('blah');
}
if (channel instanceof TextChannel) {
  // Property 'send' does not exist on type 'Channel & TextChannel'.ts(2339)
  channel.send('blah');
}
```

### discord.js version

13.3.1

### Node.js version

v16.13.0 
(TS version v4.5.4)

### Operating system

Mac OS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

**Comment by vcarl** [comment]
Followup: casting doesn't work either. Unless I'm mistaken, there's no way to use TS to send a message without disabling the type checker entirely

```ts
const channel = await client.channels.fetch('id');

// Property 'send' does not exist on type 'TextChannel'.ts(2339)
(channel as unknown as TextChannel).send('blah');
```

**Comment by suneettipirneni** [comment]
You'll need to use a typeguard for type safety

```ts
const channel = await client.channels.fetch('id');
if (!channel.isText()) {
  return;
}

channel.send('content');
```

**Comment by vcarl** [comment]
That is an inverted conditional from my initial code sample, and produces the same type error
```ts
const channel = await client.channels.fetch(channelId);

if (!channel?.isText()) {
  return;
}

// Property 'send' does not exist on type '(Channel & PartialDMChannel) |
// (Channel & DMChannel) | (Channel & TextChannel) | (Channel &
// NewsChannel) | (Channel & ThreadChannel)'.
//   Property 'send' does not exist on type 'Channel & PartialDMChannel'.ts(2339)
channel.send("content");
```

**Comment by suneettipirneni** [comment]
I can't reproduce this the code you sent above works as expected on my end. Do you have `strict` enabled in your tsconfig?

**Comment by vcarl** [comment]
Hmmm I went to make a reproduction in code sandbox, and it's working there. It might be something weird in my environment, I'll close for now and reopen if I'm able unable to resolve. Sorry for noise here.

**Comment by jbis9051** [comment]
I am getting same issue
