### ISSUE TITLE
HTTPError [TypeError]: fetch is not a function

### ISSUE THREAD

**Issue by aw1875** [discordjs/discord.js#7121]
### Issue description

1. Use Typescript along with [webpack](https://github.com/timfish/webpack-asset-relocator-loader).
2. Attempt to send webhook.

Error returned:

```
HTTPError [TypeError]: fetch is not a function
    at RequestHandler.execute (\.webpack\main\index.js:15021:15)
    at RequestHandler.execute (\.webpack\main\index.js:15025:19)
    at RequestHandler.push (\.webpack\main\index.js:14871:25)
    at async WebhookClient.send (\.webpack\main\index.js:31286:15) {
  code: 500,
  method: 'post',
  path: '<hidden for privacy>',
  requestData: {
    json: {
      content: 'hello!',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

### Code sample

```typescript
import { WebhookClient } from 'discord.js';

// Instantiate webhook
const webhookClient = new WebhookClient({ url: webHook.url })

webhookClient.send('hello!').then((message) => console.log(message.content)).catch(console.error);
```

### discord.js version

13.3.1

### Node.js version

17.2.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILD_WEBHOOKS

**Comment by 200hash6955** [comment]
did you manage to fix it somehow?

**Comment by aw1875** [comment]
@200hash6955 I wasn't able to find any proper fix so I just manually send the request with fetch like this:
```javascript
fetch(<webhookURL>, {
    method: "POST",
    headers: {
        "content-type": "application/json",
    },
    body: JSON.stringify({
        username: <username>,
        avatar_url: <avatarURL>
        embeds: [embed],
    }),
}).catch((e: any) => {
    // Handle error
});
```

**Comment by kyranet** [comment]
I have no idea why are you using Webpack for a Discord.js bot but... I guess this fetch error comes from here:

https://github.com/discordjs/discord.js/blob/e07c3743375e2bf4470818f6d20c269edce7b7a1/packages/discord.js/src/rest/APIRequest.js#L73-L79

However, `fetch` is already defined:

https://github.com/discordjs/discord.js/blob/e07c3743375e2bf4470818f6d20c269edce7b7a1/packages/discord.js/src/rest/APIRequest.js#L6

You need to configure webpack to not replace `node-fetch` with the browser implementation, because it assumes `globalThis.fetch` exists, which doesn't in Node.js

**Comment by aw1875** [comment]
@kyranet I'm not using webpack for a discord.js bot. I'm using webpack for my Electron application that utilizes discord.js for sending webhook embeds since it is easy to create the embed format this way. I already tried configuring webpack to not replace node-fetch but regardless it's not a big deal for me as I have no issues manually sending the request like I do above.

**Comment by iCrawl** [comment]
This doesn't really have anything to do with us, but just a webpack configuration error.

Additionally discord.js also shouldn't be used in the renderer process of your electron application anyway.

**Comment by aw1875** [comment]
It was only related to discord.js which is why I posted it here in case other people have had similar issues and could help from experience. This is not in my renderer process i’m very aware it shouldn’t be in the renderer.
