### ISSUE TITLE
Invite delete api is not working

### ISSUE THREAD

**Issue by LiChangNan-Programmer** [discordjs/discord.js#7124]
### Issue description

Why my robot can delete the invitation link at first, but after a period of time, it can’t delete it. And `invite.delete()` did not give me any right or wrong feedback.

### Code sample

```typescript
invites.forEach(async (invite) => {
    try {
      const result = await invite.delete();
      console.log(result); // no output
    } catch (error) {
      console.log(error); // no output
    }
  });
```

### discord.js version

13.3.1

### Node.js version

16.13.1

### Operating system

macOs

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INVITES, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by Jiralite** [comment]
Deleting an invite will return the structure:

https://github.com/discordjs/discord.js/blob/5ec04e077bbbb9799f3ef135cade84b77346ef20/src/structures/Invite.js#L240-L243

So it seems impossible for it to not output anything. Looking at the code you provided, maybe `invites` is simply empty so the code isn't being run?

Can you update your code sample to a [minimal reproduction sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by almostSouji** [comment]
Alternatively, you might be doing this a lot for testing and are ratelimited?

**Comment by LiChangNan-Programmer** [comment]
> Deleting an invite will return the structure:
> 
> https://github.com/discordjs/discord.js/blob/5ec04e077bbbb9799f3ef135cade84b77346ef20/src/structures/Invite.js#L240-L243
> 
> So it seems impossible for it to not output anything. Looking at the code you provided, maybe `invites` is simply empty so the code isn't being run?
> 
> Can you update your code sample to a [minimal reproduction sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Maybe not, because my function is very simple, the core appeal is this code. Maybe like almostSouji said.

**Comment by LiChangNan-Programmer** [comment]
> Alternatively, you might be doing this a lot for testing and are ratelimited?
你想你可能是对的，我的机器人对这个接口的调用很频繁。但是无论有没有限制。它最起码应该告诉我这段代码的执行结果。然而并没有。

**Comment by LiChangNan-Programmer** [comment]
> Alternatively, you might be doing this a lot for testing and are ratelimited?
你想你可能是对的，我的机器人对这个接口的调用很频繁。但是无论有没有限制。它最起码应该告诉我这段代码的执行结果。然而并没有。

**Comment by LiChangNan-Programmer** [comment]
> Deleting an invite will return the structure:
> 
> https://github.com/discordjs/discord.js/blob/5ec04e077bbbb9799f3ef135cade84b77346ef20/src/structures/Invite.js#L240-L243
> 
> So it seems impossible for it to not output anything. Looking at the code you provided, maybe `invites` is simply empty so the code isn't being run?
> 
> Can you update your code sample to a [minimal reproduction sample](https://stackoverflow.com/help/minimal-reproducible-example)?


It may not be necessary, because my function is very simple. The core is to use this interface, it may really be like almostSouji said, but what makes me sad is that it did not give me any feedback.

**Comment by almostSouji** [comment]
If you are rate-limited on the respective endpoint we delay the call as specified by the API response. During this the state of the Promise will be pending, meaning it won't resolve until a success or fail state happened. The former will cause the Promise to resolve with the structure in question, as documented, the latter will cause the Promise to reject.

**Comment by LiChangNan-Programmer** [comment]
> 

I see. Thank you
