### ISSUE TITLE
Add support for GuildMember timeout

### ISSUE THREAD

**Issue by maikdevries** [discordjs/discord.js#7135]
### Feature

A `GuildMember` can now be timed out using the new [timeout](https://discord.com/developers/docs/resources/guild#modify-guild-member) field of the `PATCH /guilds/{guild.id}/members/{user.id}` endpoint. This issue does exactly that.

### Ideal solution or implementation

Add a field and the related methods to the `GuildMember` type which stores and handles the timing out of members.  There seems to be a new permission as well with the flag `MODERATE_MEMBERS` which allows one to manage time outs in a `Guild`, which is something that needs to be implemented too.

As the [Discord API states](https://discord.com/developers/docs/topics/permissions#permissions-for-timed-out-members):
> Timed out members will temporarily lose all permissions except `VIEW_CHANNEL` and `READ_MESSAGE_HISTORY`. Owners and admin users with `ADMINISTRATOR` permissions are exempt.

### Other context

[Discord API reference](https://discord.com/developers/docs/resources/guild#modify-guild-member) and the [Discord FAQ on timeouts](https://support.discord.com/hc/en-us/articles/4413305239191-Time-Out-FAQ).

Image of the client's preview of the new permission:
![image](https://user-images.githubusercontent.com/44983425/146911669-1c71e046-1cb6-43c1-bde4-c04859d5f169.png)

**Comment by SuperchupuDev** [comment]
There's a PR already #7104
