### ISSUE TITLE
Discord Timeout

### ISSUE THREAD

**Issue by DeshanXD** [discordjs/discord.js#7136]
### Feature

Discord recently added Timeouts as seen in below picure, I'm just wondering if you'd able to implement this. that would be really helpful for auto moderation bots and stuff. I've always use internal cache to temporary moderate members but this feature is game changer cuz I don't have to manage any internal state so 

![image](https://user-images.githubusercontent.com/30923476/146955809-18b4a3d6-b811-48f2-a576-47ab2c13814d.png)

### Ideal solution or implementation

**Adding Timeouts for Discord.JS**

**Comment by Jiralite** [comment]
Duplicate: #7135.
