### ISSUE TITLE
Components passed into action row are not the same as the components that are used in action row creation

### ISSUE THREAD

**Issue by PythonCoderAS** [discordjs/discord.js#7139]
### Issue description

Whenever I pass in a component to an action row, the original component ceases to manipulate the action row.

### Code sample

```typescript
const button = new MessageButton()
    .setCustomId("discard")
    .setStyle("DANGER")
    .setEmoji("922315496559349800");
const row = new MessageActionRow().addComponents(button);
button.setDisabled(true);
console.log(row.components[0].disabled) // Should be true, is false
```

### discord.js version

13.3.1

### Node.js version

17.2.0

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by ImRodry** [comment]
Once you add a component to the action row you need to modify its reference inside the action row, not the variable you used before

**Comment by PythonCoderAS** [comment]
> Once you add a component to the action row you need to modify its reference inside the action row, not the variable you used before

I can see that, but it makes no sense since is it mentioned nowhere. Also, I wouldn't expect the internal object to be different from the one that I provided.

**Comment by vladfrangu** [comment]
Unfortunately, this is a downside of the way we resolve the input you provide, where we re-create the component based om the data you provide... maybe we can short-circuit that in BaseMessageComponent#create...

**Comment by ImRodry** [comment]
Actually yeah my bad, I think we can easily check if the provided data is already a MessageButton (or any other component for that matter) and don't create a new instance if it is. Will try it out

**Comment by ImRodry** [comment]
Yeah this is a very easy fix, will PR!
