### ISSUE TITLE
Typescript import compile bug.

### ISSUE THREAD

**Issue by Scraayp** [discordjs/discord.js#7141]
### Issue description

1. Install ts-node-dev package.
2. Try to start the file with the ts-node-dev package

#### Sharding code
```typescript

import { ShardingManager } from 'discord.js';
import { client } from '../config/config';
import chalk from 'chalk';

const manager = new ShardingManager(__dirname + '/client.ts', { token: client.token });

manager.on('shardCreate', (shard) => console.log(chalk.magenta(`[SHARD MANAGER]`), `Launched shard ${shard.id}`));

manager.spawn();
```
#### The client.ts code
```typescript

import { Client as DiscordClient, Intents } from 'discord.js';
import { client } from '../config/config';

const Client = new DiscordClient({ intents: [Intents.FLAGS.GUILDS] });

Client.on('interactionCreate', (interaction) => {
  if (!interaction.isCommand()) return;

  const { commandName } = interaction;

  if (commandName === 'stats') {
    return Client.shard
      .fetchClientValues('guilds.cache.size')
      .then((results) => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return interaction.reply(`Server count: ${results.reduce((acc, guildCount) => acc + guildCount, 0)}`);
      })
      .catch(console.error);
  }
});

Client.login(client.token);
```

### discord.js version

13.3.1

### Node.js version

Node: 16.13.0 Typescript: 4.5.4

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by kyranet** [comment]
What is the compiler error?

**Comment by Scraayp** [comment]
/workspace/Hez/src/client/client.ts:1
import { Client as DiscordClient, Intents } from 'discord.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.nodeDevHook [as .js] (/workspace/Hez/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspace/Hez/node_modules/ts-node-dev/lib/wrap.js:104:1)
[ERROR] 14:53:19 SyntaxError: Cannot use import statement outside a module

**Comment by Scraayp** [comment]
Oh yeah. And the may needed tsconfig
```json
{
    "compileOnSave": true,
    "compilerOptions": {
      "declaration": true,
      "downlevelIteration": true,
      "esModuleInterop": true,
      "inlineSourceMap": true,
      "lib": [
        "ES2020"
      ],
      "noImplicitAny": false,
      "resolveJsonModule": true,
      "moduleResolution": "node",
      "outDir": "lib",
      "strict": true,
      "strictNullChecks": false,
      "target": "es2017",
      "module":"commonjs",
      "watch": true
    },
    "include": [
      "src"
    ]
  }
  ```

**Comment by HitmanPhoenix18** [comment]
Why thank you my friends (i think XD)!
I have only one question if one or both of you guys can answer. If you
think you can, please let me know on both of my emails!
Emails:
This one
***@***.***

WITH GREAT REGARDS
Jaiden McMickle
Hitman_Phoenix8

**Comment by Scraayp** [comment]
When using the ts compiler the issue was solved, it looks the issue belongs into the ts-node-dev part. Thank you for help!

**Comment by snoweuph** [comment]
I got the same problem, somehow it's kind of like the tsconfig isn't passed down. The interesting part is that for me, the same error also occurs when I compile the whole project.

```json
{
    "compilerOptions": {
        "module": "CommonJS",
        "target": "ESNext",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "removeComments": true,
        "outDir": "./build",
        "baseUrl": ".",
        "paths": {
            "@base/*": [
                "src/base/*"
            ],
            "@baseTypes/*": [
                "src/base/types/*"
            ],
            "@classes/*": [
                "src/base/classes/*"
            ],
            "@schema/*": [
                "src/base/schema/*"
            ],
            "@interactions/*": [
                "src/interactions/*"
            ],
            "@utils/*": [
                "src/utils/*"
            ],
            "@assets/*": [
                "src/assets/*"
            ],
        }
    },
    "tsc-alias": {
        "replacers": {
            "base-url": {
                "enabled": false
            }
        }
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules/**/*"
    ]
}
```
