### ISSUE TITLE
isTimeouted or Timeouted

### ISSUE THREAD

**Issue by rodycouto** [discordjs/discord.js#7145]
### Feature

whether the guild member is under timeout or not
it can be return a Boolean result

### Ideal solution or implementation

```js
if (<GuildMember>.timeouted) {
   return message.channel.send('This member is already muted.')
}
```

**Comment by ImRodry** [comment]
What’s the use case for this? Can’t you just check if communicationDisabledUntilTimestamp isn’t null? cc @iShibi

**Comment by iCrawl** [comment]
No because discord doesn't reset the value once the timeout is run out
