### ISSUE TITLE
INTERACTION_NOT_REPLIED error when interacting with button

### ISSUE THREAD

**Issue by aiko-chan-ai** [discordjs/discord.js#7148]
### Issue description

when i use followUp for ButtonInteraction , it get error

Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.
     at ButtonInteraction.followUp (C:\Users\Aiko\Desktop\Sagiri-v3\3.3\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:165:64)
     at InteractionCollector.<anonymous> (C:\Users\Aiko\Desktop\Sagiri-v3\3.3\Assets\distube.js:224:36)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
   [Symbol(code)]: 'INTERACTION_NOT_REPLIED'
}

I think it will be due to this update (#7129), because I did edit the source code, it ran successfully.

Sorry for my poor English

### discord.js version

13.4.0

### Node.js version

16.10

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by vladfrangu** [comment]
This is not a bug, you can only use followUp after you defer or reply to an interaction. Also please don't enable all intents if you don't need them. 👍
