### ISSUE TITLE
Error while turning on a bot on heroku

### ISSUE THREAD

**Issue by Catgithub768** [discordjs/discord.js#7155]
### Issue description

Well, i added a timeout command to my bot, and i tried to turn it on heroku.
When it finished building i get a error, but in my pc it turns on without any error.

Here is the error
![image](https://user-images.githubusercontent.com/79985497/147425099-b4145c98-5560-418f-b24b-1b1aadfd1631.png)

### discord.js version

13.4.0

### Node.js version

16.3.10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by iShibi** [comment]
- discordjs/discord.js#5111

**Comment by Catgithub768** [comment]
thanks!
