### ISSUE TITLE
interaction type narrowing left with never type

### ISSUE THREAD

**Issue by yi-fan-song** [discordjs/discord.js#7160]
### Issue description

When handling an interaction, if I narrow the type using `Interaction.inGuild()`, the type is narrowed to one such that further calls to `Interaction.inRawGuild()` or `Interaction.inCachedGuild()` will end up with the type `never`. 
My naive fix suggestion is to simply change the return type of `Interaction.inGuild()` from `this is Interaction<'present'>` to `this is Interaction<'cached' | 'raw'>`. This would fix my issue, but I don't know what the implications of this change are.
Hopefully I haven't misunderstood that `inGuild()` and `inCachedGuild()` are not mutually exclusive.

As a side note: 'present' is a bit weird of a name, I'm guessing that it means that it exists?

### Code sample

```typescript
import { CommandInteraction } from "discord.js";

const handleAsync = async (i: CommandInteraction) => {
    if (!i.inGuild()) {
        return;
    }
    // i is now CommandInteraction<"present"> & CommandInteraction<CacheType>

    if (i.inRawGuild()) {
        // i is never
        return;
    }

    if (i.inCachedGuild()) {
        // i is never
        return;
    }
}
```

### discord.js version

13.4.0

### Node.js version

16.13.1

### Operating system

WSL 2.0 on Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by Jiralite** [comment]
From looking at your code sample alone, the `never` types you are encountering are intentional.

The first `if` checks if an interaction came from a guild - cached or not. If it doesn't, you return out. Therefore, it is impossible for an interaction thereafter to be from a cached guild or an uncached guild. From that point onwards, you are handling interactions from direct messages.

**Comment by yi-fan-song** [comment]
Did I derp out? `!i.inGuild()`, so I'm only returning if it is in a DM.

**Comment by DTrombett** [comment]
Actually the only solution would be to use `this is Interaction<'cached' | 'raw'>` but this seems to bring another issue: `guildId` is `Snowflake | null` when using `inGuild()` instead of `Snowflake`

**Comment by yi-fan-song** [comment]
between djs 13.3.1 and 13.4.0, the type for `CacheTypeReducer` went from 
```ts
export type CacheTypeReducer<
  State extends CacheType,
  CachedType,
  RawType = CachedType,
  PresentType = CachedType | RawType,
  Fallback = PresentType | null,
> = State extends 'cached'
  ? CachedType
  : State extends 'raw'
  ? RawType
  : State extends 'present'
  ? PresentType
  : Fallback;
```
to
```ts
export type CacheTypeReducer<
  State extends CacheType,
  CachedType,
  RawType = CachedType,
  PresentType = CachedType | RawType,
  Fallback = PresentType | null,
> = [State] extends ['cached']
  ? CachedType
  : [State] extends ['raw']
  ? RawType
  : [State] extends ['present']
  ? PresentType
  : Fallback;
```
Reverting that fixes the `Snowflake | null` for me. But obviously that would also reintroduce the bug that it originally fixed. I would need a little more insight into this 'present' cache type. If it can be safely be represented by `'cache' | 'raw'`, then that will also work, this is definitely not easy to change without breaking types for anyone using `CacheTypeReducer` in their code.
