### ISSUE TITLE
Timeout communicationDisabledUntilTimestamp not turning 'null'

### ISSUE THREAD

**Issue by UnknownKID69** [discordjs/discord.js#7161]
### Issue description

After you timeout someone, the time is stored in `communicationDisabledUntilTimestamp` 
If you remove the timeout before time ends. It sets `communicationDisabledUntilTimestamp` to `null` 
But if user timeout is removed automatically when time ends . 
It doesn't set `communicationDisabledUntilTimestamp` to `null` and keeps the last timeout timestamp
Which on checking if user is timed out already or not .. it always return `true` even if user is not timed out.

### discord.js version

13.4.0

### Node.js version

16.11.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

**Comment by Jiralite** [comment]
This is not a bug, this is how Discord implemented it. We don't set it to `null` simply because Discord does not.

**Comment by DTrombett** [comment]
> Which on checking if user is timed out already or not .. it always return `true` even if user is not timed out.

With #7146 you should be able to do `member.isCommunicationDisabled()` to check if the user is timed out.
