### ISSUE TITLE
I provided a path to my image but it gave me an error when sending with the attachments option

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [discordjs/discord.js#7162]
### Issue description

1. Send an local image with the attachments option
The error:
```
DiscordAPIError: Invalid Form Body
attachments[0]: Only dictionaries may be used in a ModelType
```

### Code sample

```typescript
This is my code before

await sentMessage.edit({
 content: "some text",
 files: [ `./Images/hideandseek_success.jpg` ],
 components: []
})

And this is my code now

await sentMessage.edit({
 content: "some text",
 attachments: [ `./Images/hideandseek_success.jpg` ],
 components: []
})

It did not gave me any errors when I used the `files` option but when I changed it to `attachments` it gave me that error. I changed it from `files` to `attachments` because I want to replace the attachments in the sent message with new ones
```

### discord.js version

13.1.0

### Node.js version

17.1.0

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by imranbarbhuiya** [comment]
attachments takes array of [MessageAttachament](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) not file path you should use files instead.

**Comment by Ivan-Da-Dev** [comment]
> attachments takes array of [MessageAttachament](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) not file path you should use files instead.

But I want to replace the message's attachments with new ones. Meaning I want to remove the old ones

**Comment by imranbarbhuiya** [comment]
> > attachments takes array of [MessageAttachament](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) not file path you should use files instead.
> 
> But I want to replace the message's attachments with new ones. Meaning I want to remove the old ones

You can use 
```js
await message.edit({ files: [newFile], attachments: [] });
```

**Comment by Ivan-Da-Dev** [comment]
> > > attachments takes array of [MessageAttachament](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) not file path you should use files instead.
> > 
> > 
> > But I want to replace the message's attachments with new ones. Meaning I want to remove the old ones
> 
> You can use
> 
> ```js
> await message.edit({ files: [newFile], attachments: [] });
> ```
Can I provide a path in `files` or should I provide a message attachment?

**Comment by imranbarbhuiya** [comment]
> > > > attachments takes array of [MessageAttachament](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) not file path you should use files instead.
> > > 
> > > 
> > > But I want to replace the message's attachments with new ones. Meaning I want to remove the old ones
> > 
> > 
> > You can use
> > ```js
> > await message.edit({ files: [newFile], attachments: [] });
> > ```
> 
> Can I provide a path in `files` or should I provide a message attachment?

You can provide path in files, as you showed in the `before` example.

**Comment by kyranet** [comment]
Seems like it got resolved, thanks @imranbarbhuiya.

Closing this issue as a result.
