### ISSUE TITLE
Channel.edit() inconsistently stuck

### ISSUE THREAD

**Issue by WouterK12** [discordjs/discord.js#7171]
### Issue description

1. Attempt to update data of a channel.
2. Observe data sometimes not being updated.

The code below gives the following output:
![image](https://user-images.githubusercontent.com/34215333/147795811-72e4da09-a39d-41e1-a5aa-8fec17a6f26e.png)
But this output is very inconsistent. Sometimes everything works fine, sometimes the data does not get updated at all.

### Code sample

```typescript
const { Client, Intents } = require("discord.js");
const client = new Client({
  intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.DIRECT_MESSAGES],
  partials: ["MESSAGE", "CHANNEL"],
});

client.on("ready", () => {
  let counter = 0;

  setInterval(async () => {
    const channel = client.channels.cache.get("<channel-id>");

    console.log(`Current channel name: ${channel.name}`);
    console.log("Attempting to update channel name ...");

    await channel
      .setName(`test (${counter})`)
      .then((newChannel) => console.log(newChannel.name))
      .catch((error) => console.log(error));

    console.log("Updated channel name");

    counter++;
  }, 15 * 1000);
});

client.login("<token>");
```

### discord.js version

13.5.0

### Node.js version

16.10

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

780b7ed

**Comment by Jiralite** [comment]
You are in fact encountering a rate limit (if I remember correctly, it's 2 channel name edits per 10 minutes). The inconsistency in the edits you are noticing is when you cannot actually edit the channel due to the rate limit.

**Comment by WouterK12** [comment]
I am still investigating this issue, because it is weird that it doesn't throw any error.
The only event that shows the error is `debug`, but it only triggers once. It fires with this error: https://github.com/discordjs/discord.js/blob/780b7ed39f173a77fd9eae396133980826926906/src/rest/RequestHandler.js#L323
The `rateLimit` or `invalidRequestWarning` events do not fire.

`client.on("debug", (data) => console.log(data));`
`client.on("rateLimit", (data) => console.log(data));`
`client.on("invalidRequestWarning", (data) => console.log(data));`

It would be nice if when being rate-limited, or in this case, when editing a channel, the catch-block would catch a rate limit error. Because right now it just stops following code from executing, without throwing any errors.

`await channel`
`      .setName("new channel name")`
`      .then((newChannel) => console.log(newChannel.name))`
`      .catch((error) => console.log(error)); // <--- does not catch any errors, but prevents following code from executing`
