### ISSUE TITLE
Unable to post image in response to a bot splash command interaction: "DiscordAPIError: Unknown interaction"

### ISSUE THREAD

**Issue by alexeystrakh** [discordjs/discord.js#7172]
### Issue description

I'm implementing a Discord bot that can reply to a splash command. It works fine with regular text replies to interactions but fails to reply with an attached image.  I've tried multiple ways to post an image and failed to achieve this, I'm getting the following error:

```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (...\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (...\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (...\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
    at async Client.<anonymous> (...) {
  method: 'post',
  path: '/interactions/.../callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
```

### Code sample

```typescript
const embed = { 
    description: 'tournament table', 
    image: {
        url: 'https://pbs.twimg.com/profile_images/1455185376876826625/s1AjSxph_400x400.jpg'
    }
};

await interaction.reply('Here we go', { embeds: [ embed ] });
```
```


### discord.js version

13.1

### Node.js version

16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

_No response_

**Comment by imranbarbhuiya** [comment]
In djs v13, you need to use 

```js
await interaction.reply({content: " your content ", embeds:[embed]})
```

Like this.

**Comment by alexeystrakh** [comment]
Thanks for a quick reply. The proposed solution responds with the same error. Did I miss something?

```
const embed = { 
    description: 'tournament table', 
    image: {
        url: 'https://pbs.twimg.com/profile_images/1455185376876826625/s1AjSxph_400x400.jpg'
    }
};

await interaction.reply({
    content: "your content",
    embeds: [ embed ]
});
```

Where can I find `djs discord server` to post the question?

**Comment by ImRodry** [comment]
There is a link to the support server before you open an issue. The problem you're facing is usually because you took too long to respond to an interaction, so you have to use await and defer it if you think your code will take too long to execute

**Comment by alexeystrakh** [comment]
omg, you totally right, I was fighting image formatting issue and all kinds of possible related issues while the real issue was in a totally different place. The error is soooooooo unuseful, unfortunately. I wish it would just tell "you took too long to reply".

Thanks for the help!

For everyone to finds this topic later, use the following code, because fetching an image can take some time (especially if it's not just a static file but a server-generated image):

```
await interaction.deferReply();

const embed = { 
    description: 'tournament table', 
    image: {
        url: 'https://pbs.twimg.com/profile_images/1455185376876826625/s1AjSxph_400x400.jpg'
    }
};

await interaction.editReply({
    content: "your content",
    embeds: [ embed ]
});
```

https://discordjs.guide/interactions/replying-to-slash-commands.html#deferred-responses
