### ISSUE TITLE
`Message#content`: Possible discrepancy between Docs and Typings

### ISSUE THREAD

**Issue by joshuanianji** [discordjs/discord.js#7176]
### Issue description

The Discordjs documentation says [`Message#content` is type `?string`](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=content), but the `typings/` folder declares it as `string`.

Below is the snippet at version 13.5.0:

https://github.com/discordjs/discord.js/blob/f99b58cd2ab65aa155fe588bb30bd8a3afa11d3c/typings/index.d.ts#L1494

The same typing exists at the Dev release (780b7ed)
https://github.com/discordjs/discord.js/blob/780b7ed39f173a77fd9eae396133980826926906/typings/index.d.ts#L1494

---

The following image contains the logs of two instances: one where the message has content, so the content is printed out, and one that is an embed, so `Message#content` is an empty string. 

From the docs, I would have implied that the `Message#content` would be `null` under the second circumstance, but the types disallow that. Should the docs clarify that, and change the type from `?string` to `string`?

<details>
<summary>Image</summary>
<br>
<img width="759" alt="Screen Shot 2021-12-31 at 5 04 35 PM" src="https://user-images.githubusercontent.com/11809774/147841376-a9925fe3-e63a-4148-9302-1bb42fe60b1e.png">
</details>

### discord.js version

13.5.0

### Node.js version

16.13.1

### Operating system

MacOS 12.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials, CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

780b7ed

**Comment by DTrombett** [comment]
> From the docs, I would have implied that the `Message#content` would be `null` under the second circumstance

This is wrong, `content` is always present and can be an empty string.
It can be null only when the message is partial, which cannot happen on `messageCreate` so typings are correct. For other events like `messageUpdate` you may get a partial message, so typings will show you that `message.content` is of type `string | null`

**Comment by joshuanianji** [comment]
That makes sense, thanks for clarifying! Closing the issue.
