### ISSUE TITLE
API Error: Invalid Form Body when the message.reply() is fired on deleted message

### ISSUE THREAD

**Issue by AykutSarac** [discordjs/discord.js#7178]
### Issue description

The error occurs when the `message.reply()` function is fired but the message intended to be quoted is already deleted and returns `message_reference: unknown` from API. Solution for this problem could be ignoring the functionality of `.reply()` and directly sending the message to the channel. 

### discord.js version

13.5.0

### Node.js version

16.13.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

**Comment by ckohen** [comment]
This is intentional. Discord provided us a way to do what you want, and the parameter for doing so is documented here: https://discord.js.org/#/docs/main/stable/typedef/ReplyMessageOptions
