### ISSUE TITLE
WebhookClient url match missing discordapp

### ISSUE THREAD

**Issue by wailay** [discordjs/discord.js#7189]
### Issue description

Create a webhook on discord and copy link.

You will get something like this : https://discordapp.com/api/webhooks/92XXXXXXX/nRrKWxXXXXXXXXXX

Create a WebhookClient instance and pass it the link you just copied from discord

Try to send a message using the client and it will throw the following error

```
      if (!url || url.length <= 1) throw new Error('WEBHOOK_URL_INVALID');
                                   ^

Error [WEBHOOK_URL_INVALID]: The provided webhook URL is not valid.
```
The issue is that the regex in https://github.com/discordjs/discord.js/blob/main/src/client/WebhookClient.js#L33 is only looking for an URL with `discord.com` while the discord app gives you a webhook URL starting with `discordapp.com`. The regex should be updated to match the current implementation of the discord app.

### Code sample

```typescript
const { MessageEmbed, WebhookClient } = require('discord.js');

const webhookClient = new WebhookClient({
    // This URL is copied from the Integration settings tab in discord
    url: 'https://discordapp.com/api/webhooks/98797854/nRrKW',
});

const embed = new MessageEmbed().setTitle('Some Title').setColor('#0099ff');

webhookClient.send({
    content: 'Webhook test',
    username: 'some-username',
    avatarURL: 'https://i.imgur.com/AfFp7pu.png',
    embeds: [embed],
});
```

### discord.js version

discord.js@13.5.0

### Node.js version

node@v16.6.2 typescript@4.4.2

### Operating system

Linux Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILD_WEBHOOKS

**Comment by ckohen** [comment]
This match was intentionally removed a while after discord stopped using discordapp.com for the client. The client is not actually supposed to use this url anymore, but I've noticed sometimes the stable client can get into a very weird state where it reverts back to discordapp.com.

The way copying links work is it uses the current client base url, so when I copy links they always start https://canary.discord.com/api/webhooks/..., on ptb it would be htps://ptb.discord.com/api/webhooks/....

That means that your client currently uses discordapp.com to do everything!! Usually a restart fixes that.

**Comment by wailay** [comment]
I tried reinstalling discord, but still getting an url starting with `discordapp.com`. I am on Ubuntu 20.04.3 and downloaded the deb package through discord.com.

This is the discord version that was installed
`Stable 109190 (5ca1105) Host 0.0.16 Linux 64-Bit (5.11.0-43-Generic)`

**Comment by ckohen** [comment]
Very interesting. I still believe that discord.js should not accept this url as its deprecated for use in the api.

You should reach out to discord about your client still using discorapp.com
(A discord dev said you should check localstorage and if discordapp.com appears anywhere change it, so maybe check that out first)

**Comment by wailay** [comment]
Yes makes sense, I should have researched more before opening this issue. Thanks for your help! :)
