### ISSUE TITLE
Webhook MessageEmbed `.setAuthor()` throws error

### ISSUE THREAD

**Issue by Kruimeldief** [discordjs/discord.js#7192]
### Issue description

A bug that I can't reproduce intentionally but surfaces more often than not when merging or switching branches on Git.

The bug may be introduced in  #6966

1. Run the code using discord.js@13.5.0: it works.
2. Merge another branch into the current branch.
3. Run the code: throws error message (see below).
4. Execute PS command: `yarn add discord.js` to update, but already has discord.js@13.5.0
5. Run the code: it works again.

I can switch back to `setAuthor(name: string, iconURL?: string, url?: string)` but don't want to use deprecated functions because of run-time warnings. Furthermore, between step 3 and 4, I used the F12 short-cut in VS Code (go to definition) and it jumped to the `setField()` function with 3 parameters instead of an object. You could argue this may be caused by VS Code, yet the same problem surfaces when running the script.

The reason for opting for medium priority is because functions shouldn't cause fatal errors, though there's a depreciated back-up function.

```
D:\Dennis\Desktop\Sketchful\Sketchful bots\Sketchful_ModBot\node_modules\discord.js\src\util\Util.js:413
    if (typeof data !== 'string') throw new error(errorMessage);
                                        ^

RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (D:\Dennis\Desktop\Sketchful\Sketchful bots\Sketchful_ModBot\node_modules\discord.js\src\util\Util.js:413:41)
    at MessageEmbed.setAuthor (D:\Dennis\Desktop\Sketchful\Sketchful bots\Sketchful_ModBot\node_modules\discord.js\src\structures\MessageEmbed.js:356:32)       
    at file:///D:/Dennis/Desktop/Sketchful/Sketchful%20bots/Sketchful_ModBot/src/test.js:11:6
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  [Symbol(code)]: 'EMBED_AUTHOR_NAME'
}
```

Ps.
The bug report question `Which gateway intents are you subscribing to?` should have the option `none` because there's no intent necessary for webhooks.

### Code sample

```typescript
const WEBHOOK_CLIENT = new WebhookClient( {url: webhookURL} );

let embed = new MessageEmbed()
    .setTitle(title)
    .setDescription(description)
    .setAuthor({
        name: 'Imgur',
        url: 'https://imgur.com/',
        iconURL: 'https://i.imgur.com/hpiGU9U.jpeg'
    })
    .setTimestamp(time);
    
WEBHOOK_CLIENT.send({
    username: 'Imgur Bot',
    avatarURL: 'https://i.imgur.com/hpiGU9U.jpeg',
    embeds: [embed]
});
```

### discord.js version

13.5.0

### Node.js version

16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

DIRECT_MESSAGES

**Comment by Jiralite** [comment]
This is the method:

https://github.com/discordjs/discord.js/blob/ed0cfd91edc3a2b23a34a8ecd9db38baa12b52fa/packages/discord.js/src/structures/MessageEmbed.js#L393-L394

There's no way such a simple operation will randomly fail, especially a bug you cannot reproduce intentionally.

discord.js is throwing here because you're not providing a string as per the error. So I would advise you to debug your code to find out what you're supplying when this error is thrown _and_ think about cache issues of packages when you merge your branches.

**Comment by almostSouji** [comment]
Feel free to re-open this issue, if you can reproduce it on a clean install of the latest stable branch (13.6.0 as of writing).
