### ISSUE TITLE
guildMemberAdd event doesn't get GuildMember

### ISSUE THREAD

**Issue by mohaisrealrblx** [discordjs/discord.js#7193]
### Issue description

When I was checking how to do a Welcome System, I used the client event [guildMemberAdd](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-guildMemberAdd), that in it's parameter has a GuildMember as type, but when I try to execute it and use console.log it, doing ``console.log(member.constructor.name)``, it doesn't appear ``GuildMember``, it appear ``User``, while in the Documentation mentioned before, it says ``GuildMember``

I use ``Discord.JS v13.5.0``, and ``Node.JS 16.13.0`` and for command handler, I use ``WOKCommands 1.5.3``. The handler isn't necessary to say, but if you need, it, go ahead.

Thanks!

- MohaIsReal

### Code sample

```typescript
client.on('guildMemberAdd', member => {

    console.log(member.constructor.name)

    const row = new MessageActionRow()
      // (components)

    const em = new MessageEmbed()
      // (embed info)

    member.send({ content: ' ', embeds: [em], components: [row] })
  })
```

### discord.js version

13.5.0

### Node.js version

16.13.0

### Operating system

Ubuntu Linux LTS with Nix

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

### I have tested this issue on a development release

780b7ed

**Comment by imranbarbhuiya** [comment]
I'm not able to reproduce in `v13.5.0` 
![image](https://user-images.githubusercontent.com/74945038/148585923-0597fe46-ae3e-4f1e-9ae4-7096c9c892d0.png)
![image](https://user-images.githubusercontent.com/74945038/148585918-daa32e8a-325d-4786-b466-ad0b09348219.png)

**Comment by mohaisrealrblx** [comment]
> I'm not able to reproduce in `v13.5.0` ![image](https://user-images.githubusercontent.com/74945038/148585923-0597fe46-ae3e-4f1e-9ae4-7096c9c892d0.png) ![image](https://user-images.githubusercontent.com/74945038/148585918-daa32e8a-325d-4786-b466-ad0b09348219.png)

In my case, I do that, and look the output.

![image](https://media.discordapp.net/attachments/829673025175027772/929071635380719666/Screenshot_2022-01-07_18.55.28.png)

**Comment by imranbarbhuiya** [comment]
> > I'm not able to reproduce in `v13.5.0` ![image](https://user-images.githubusercontent.com/74945038/148585923-0597fe46-ae3e-4f1e-9ae4-7096c9c892d0.png) ![image](https://user-images.githubusercontent.com/74945038/148585918-daa32e8a-325d-4786-b466-ad0b09348219.png)
> 
> In my case, I do that, and look the output.
> 
> ![image](https://camo.githubusercontent.com/b8ce1bc2d93cdf3574a2595deef24928e490ac82234af964d718ca3caff90715/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3832393637333032353137353032373737322f3932393037313633353338303731393636362f53637265656e73686f745f323032322d30312d30375f31382e35352e32382e706e67)

Can u provide a minimal repro of your current project?

**Comment by SpaceEEC** [comment]
Can you still reproduce without anything except discord.js (and its dependencies) installed (since you mentioned WOKCommands)?
If so, can you also provide a stacktrace (`console.log(new Error());` from within the event handler?

**Comment by mohaisrealrblx** [comment]
> Can you still reproduce without anything except discord.js (and its dependencies) installed (since you mentioned WOKCommands)? If so, can you also provide a stacktrace (`console.log(new Error());` from within the event handler?

Yes, I have done this without that Command Handler, and testing with client.emit, and doing console.log of the constructor name, and appears the same.
![Screenshot 2022-01-09 10 47 11](https://user-images.githubusercontent.com/72509835/148677291-6914e035-be3f-49b2-8719-2d2008fcdba4.png)
![Screenshot 2022-01-09 10 49 33](https://user-images.githubusercontent.com/72509835/148677329-aa134459-39b6-49f8-aee0-9b09d4d820dc.png)
I'll provide a stacktrace from the event handler soon.

**Comment by SpaceEEC** [comment]
[`Message#author`](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=author) is a user, you may want to emit [`Message#member`](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=member) instead (after ensuring that it isn't `null`).

**Comment by mohaisrealrblx** [comment]
> [`Message#author`](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=author) is a user, you may want to emit [`Message#member`](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=member) instead (after ensuring that it isn't `null`).

Okay, now I get ``GuildMember``. If so, this is not a bug, and I'll close this. Thank you!
