### ISSUE TITLE
Retier error

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7214]
### Which package is this bug report for?

discord.js

### Issue description

Steps

### Code sample

```typescript
static async retrierObj(_key, _iterate, values = [], maxRetries = 5, valueMatch = null) {
    let err, result;
    for (let i = 0, n = maxRetries; i <= n; i++) {
      try {
        result = await Promise.resolve(_key.apply(_iterate, values));
      } catch (error) {
        err = error;
        continue;
      }
      if (typeof valueMatch === "function" && !valueMatch(result)) {
        err = new Error(null);
        continue;
      }
      return result;
    }
    throw err;
  }


await retrierObj(Member.roles.set, Member, ["<Some values>"], 3);
```

TypeError: Cannot read properties of undefined (reading 'edit')

### Package version

13.5.0

### Node.js version

16

### Operating system

Web  service

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION, GUILD_SCHEDULED_EVENT

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by kyranet** [comment]
```diff
- await retrierObj(Member.roles.set, Member, ["<Some values>"], 3);
+ await retrierObj(Member.roles.set.bind(Member.roles), Member, ["<Some values>"], 3);
```

**Comment by wioniqle-q** [comment]
> ```diff
> wait retrierObj(Member.roles.set.bind(Member.roles), Member, ["<Some values>"], 3);
> ```

TypeError: _data.roles.map is not a function

**Comment by wioniqle-q** [comment]
> You're passing the prototype method, which loses the `this` context, and as such, it can't do `this.edit`. The following code fixes it:
> 
> ```diff
> - await retrierObj(Member.roles.set, Member, ["<Some values>"], 3);
> + await retrierObj(Member.roles.set.bind(Member.roles), Member, ["<Some values>"], 3);
> ```

Thank you, it works :)
