### ISSUE TITLE
Incorrect typings for GuildMember.isCommunicationDisabled()

### ISSUE THREAD

**Issue by S222em** [discordjs/discord.js#7225]
### Which package is this bug report for?

discord.js

### Issue description

After calling `GuildMember.isCommunicationDisabled()` like below, the type of member becomes `never`.

### Code sample

```typescript
const {
  Client,
  Intents,
} = require('discord.js');

const client = new Client({
  intents: [Intents.FLAGS.GUILDS],
});

client.on('interactionCreate', (interaction) => {
  if (!interaction.inCachedGuild()) return;

  if (interaction.member.isCommunicationDisabled()) return;

  // Type of member is "never"
  console.log(interaction.member);
});
```

### Package version

14.0.0-dev

### Node.js version

v16.13.0

### Operating system

MacOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by iShibi** [comment]
If you're using TypeScript, set [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) to `true` in your `tsconfig.json`:
```json
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```
If you're using JavaScript: don't
