### ISSUE TITLE
Adding buttons to action row as JSON throws error

### ISSUE THREAD

**Issue by KokoNeot** [discordjs/discord.js#7228]
### Which package is this bug report for?

discord.js

### Issue description

1. Fetch message with action row
2. replace button using array index with newButton.toJSON()
3. send the edited action row

I updated from 13.2.0 to 13.5.0 (pain with the setAuthor and setFooter changes) and my code started giving errors. I guess what needs to be done is check whether its instance of MessageButton if so, call toJSON, otherwise just keep the object.

Also I'd like to ask for repo unban on my main account. I've done my sentence pretty please. New year new me https://github.com/DaliborTrampota

### Code sample

```typescript
const row = new MessageActionRow().addComponents([
   new Button({ label: 'test1', customId: 'test1' }),
   new Button({ label: 'test2', customId: 'test2' })
])
let message = await channel.send({ content: 'Test', components: [row] })

let newButton = new Button({ label: 'replacement', customId: 'replacement' }).toJSON()
message.components[0].components[1] = newButton

message.edit({ components: message.components }
```

### Package version

13.5.0

### Node.js version

v16.13.0   

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by imranbarbhuiya** [comment]
ig this is intentional bc `message.components` contain a builder but  you are directly assigning raw json in it. Use 
[MessageActionRow#spliceComponents](https://discord.js.org/#/docs/discord.js/stable/class/MessageActionRow?scrollTo=spliceComponents)
to change the button. You can pass both json and builder when using it.

**Comment by kyranet** [comment]
You're also **not** supposed to mutate Discord.js's objects, anything you do is up to your responsibility and we will not support it.

That being said, v14 is more resilient to this kind of thing, as it checks for `toJSON`'s existence before calling it.
