### ISSUE TITLE
message.author returning api user

### ISSUE THREAD

**Issue by oniiichannnn** [discordjs/discord.js#7247]
### Which package is this bug report for?

discord.js

### Issue description

1. log message.author

### Code sample

```typescript
client.on("messageCreate", message => {
 console.log(message.author)
})

/*
 result:

 User {
   id: '625305547629133825',
   bot: false,
   system: false,
   flags: UserFlags { bitfield: 128 },
   username: 'potsu',
   discriminator: '0002',
   avatar: '6f55437910f47a90aaabf4c9512440e0',
   banner: undefined,
   accentColor: undefined
 }
*/
```

### Package version

13.5.0

### Node.js version

17.1.0

### Operating system

windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_PRESENCES, GUILD_MESSAGES

**Comment by Jiralite** [comment]
That's... not an `APIUser`?

**Comment by xHyroM** [comment]
False issue lol

**Comment by vladfrangu** [comment]
As Jiralite said, this looks like a normal User object to us. Feel free to follow up with reproduction steps if you encounter an APIUser instead
