### ISSUE TITLE
Changing the bot's own nickname gives a Missing permissions error even though the bot has required permissions

### ISSUE THREAD

**Issue by shander3377** [discordjs/discord.js#7249]
### Which package is this bug report for?

discord.js

### Issue description

1. Try to change the nickname of the bot to anything (Bot must have ADMINISTRATOR or MANAGE_NICKNAMES permission)
2. See the error
![image](https://user-images.githubusercontent.com/65767417/148988244-8a7a33de-f178-48d1-8192-f1d253be866d.png)

### Code sample

```typescript
const Discord = require('discord.js');
const Intents = Discord.Intents
const bot = new Discord.Client({
    intents: [Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_BANS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Intents.FLAGS.DIRECT_MESSAGES]
})
const token = "bot_token
bot.on('messageCreate', async message => {
if(message.content === "!setNick"){
var member = await message.guild.members.fetch("626038642288099338").catch(error => console.log(error))
member.setNickname("just a test")
}
})

bot.login(token)
```

### Package version

^13.4.0

### Node.js version

16.6.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_MESSAGES, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by Jiralite** [comment]
Update to 13.5.0.
https://github.com/discordjs/discord.js/releases/tag/13.5.0
