### ISSUE TITLE
Export ApplicationCommandTypes or align it with discord-api-tyoes

### ISSUE THREAD

**Issue by ghostdevv** [discordjs/discord.js#7270]
### Which package is the feature request for?

discord.js

### Feature

I am writing a library for discord.js that heavily uses discord.js typings, primarily this api relys on `discord-api-types` but sometimes when the cross over between internal apis (using discord-api-types) and public ones (that the dev uses with discord.js) there is a typing conflict. One of the biggest current pains is that `ApplicationCommandTypes` is not exported from discord.js and you have to import it from `/typings/enums`.

### Ideal solution or implementation

Export `ApplicationCommandTypes`

### Alternative solutions or implementations

Align more with discord-api-types

**Comment by almeidx** [comment]
This was fixed by #7077
