### ISSUE TITLE
messageCreate event never fires

### ISSUE THREAD

**Issue by Aviation-7111** [discordjs/discord.js#7271]
### Which package is this bug report for?

discord.js

### Issue description

The messageCreate event doesn't fire when a message is sent within a guild or a direct message.

### Code sample

```typescript
const { Client, Intents } = require('discord.js')
const client = new Client({ intents: [Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.DIRECT_MESSAGES] })

client.once("ready", () =>{
    console.log("Started")
})

client.on("messageCreate", msg =>{
    console.log("Message Details:")
    console.log(msg)
})

client.login("Token")
```

### Package version

discord.js@13.6.0

### Node.js version

v16.13.2

### Operating system

Windows 10 Home (64 Bit)

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

MESSAGE

### Which gateway intents are you subscribing to?

GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

0b23b7f

**Comment by Jiralite** [comment]
You need the `GUILDS` intent for guilds and the `CHANNEL` partial for direct messages.

<hr>

If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
