### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ferretwithaberet** [discordjs/discord.js#7272]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://user-images.githubusercontent.com/46427158/149582712-28273934-3489-4897-aeda-a6f3f772fcff.png)

Documentation states that `MessageAttachment.setSpoiler`'s argument is an array with a single boolean.

### Package version

13.5.1

### Node.js version

16.13.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Unfortunately, that's not how one reads documentation. The square brackets there represent something that is optional.

**Comment by almostSouji** [comment]
Angle brackets `[]` denote optional parameters.
