### ISSUE TITLE
Error: Cannot find module 'node:events'

### ISSUE THREAD

**Issue by DestroyCom** [discordjs/discord.js#7274]
### Which package is this bug report for?

discord.js

### Issue description

Hello guys !
My discord bot crashing regularly so I wanted to change a library I was using but for that I had to update my version of NodeJS and DiscordJS and, after upgrading discord.js from version 12 to version 13 and moving from node v16.4.0 to node v16.13.2,
I've been trying to get my bot to start with the npm start command and I get this error:
![image](https://user-images.githubusercontent.com/37459465/149603545-88c978c1-0ff5-4138-bf7e-59b9c6b1b212.png)

I have tried uninstalling and reinstalling nodeJs (LTS) several times, delete node_modules and reinstall all package but nothing worked, I use [nvm-windows](https://github.com/coreybutler/nvm-windows) as node version manager.

Also everytime I execute the `npm start` command my terminal display : 
![image](https://user-images.githubusercontent.com/37459465/149603887-a178e30c-2833-47a5-935b-f53434736396.png)

There is my package.json file : 
![image](https://user-images.githubusercontent.com/37459465/149603951-b8441df2-1680-4ffa-a7e9-882647dd359a.png)

And you can find all the code on this [repository](https://github.com/DestroyCom/StroyCord/tree/v0.8)
I hope that you can help me ! :D 

### Code sample

```typescript
const Discord = require("discord.js");
//const { MessageEmbed } = require("discord.js");
const { createAudioResource } = require("@discordjs/voice");
const clientDiscord = new Discord.Client();
clientDiscord.once("ready", () => {
  console.log(`Logged in as ${clientDiscord.user.tag}!`);
});

...

clientDiscord.login(process.env.BOT_TOKEN);
```

### Package version

13.6.0

### Node.js version

16.13.2

### Operating system

windows 10 Family

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug), No Partials

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment]
That error points to an outdated node version. Just because you set the node version in the engines object of your package.json doesn’t mean you have that one installed. Make sure to run process.version when running node or node -v to double check your node version.

This is not an issue with the library and therefore should not be reported here. For questions like this, I advise you to seek help on the [Discord server](discord.gg/djs)
