### ISSUE TITLE
failIfDeferredOrReplied client option

### ISSUE THREAD

**Issue by KokoNeot** [discordjs/discord.js#7282]
### Which package is the feature request for?

discord.js

### Feature

Add failIfDeferredOrReplied similar to failIfNotExists but for interaction commands (possibly buttons)
Basically if interaction is deferred or replied and in complex code with many branches, lot of times I have to check if is replied or is deferred or not and send the same content. This would reduce host of those cases to one short line instead of checking conditions

### Ideal solution or implementation

Give us an option to specify in client constuctor if interactions should fail on reply when already replied or edit the reply instead of failing and throwing error.

### Alternative solutions or implementations

If this is not possible for some reason, what would be nice is single property which combines if is replied or deferred. Due to the structures being removed, I cant make my own getter for interaction class :(

### Other context

```js
//right now
let payload = { embeds: [embed], content: 'something', ephemeral: true }
if(interaction.replied || interaction.deferred) interaction.editReply(payload)
else interaction.reply(payload) 

//the proposal
interaction.reply({ embeds: [embed], content: 'something', ephemeral: true }) 

//alternative solution - canReply was only name that I could think of but if you can think of any better and relatively short sure
let payload = { embeds: [embed], content: 'something', ephemeral: true }
if(interaction.canReply) interaction.reply(payload) 
else interaction.editReply(payload) 
```

**Comment by almeidx** [comment]
[failIfNotExists](https://discord.com/developers/docs/resources/channel#message-reference-object) is a discord feature. Such a thing does not exist for interactions.

Sounds like you're looking something like https://github.com/discordjs/discord.js/issues/6545, which was denied

**Comment by KokoNeot** [comment]
Shame but understandable
