### ISSUE TITLE
Partially loaded files are sent corrupted if the 15 second timeout is reached as the file is fully loaded

### ISSUE THREAD

**Issue by soulus98** [discordjs/discord.js#7285]
### Which package is this bug report for?

discord.js

### Issue description

I have a script that gets an image from a DM and sends it in a channel
If the upload takes exactly 15 seconds, it posts a corrupted file and doesn't throw an error

Discord has a 15 second timeout for things like uploading files
The upload speed of my bot is ~0.91 Mbits/s, so in 15 seconds it can upload ~1.7 MBs
If I make my bot upload a file that is 1.6MB, there is no issue
If it uploads a file that is 1.8MB, it emits 2 "multipleResolves" events, 15 secs apart from each other and the start of the upload, and throws a HTTP 500 "userAbort" error message (which is vague, but intended, so oh well)

*But,* if I make it upload a file that is between 1.7 and 1.8MB, node will emit only 1 "multipleResolves" event, then DJS will send a corrupted file
The `.send()` will resolve, and (therefore) `.catch()` does not fire, the file that is sent is somewhere from 0.5-0.005 times the size (i.e. 63KB instead of 1.75MB as pictured) and the file wont be downloadable or viewable.
![image](https://user-images.githubusercontent.com/73259768/149715234-0a280d03-3862-43cc-902b-0b45134eb844.png)

Here is the multipleResolves event, but it is the same as the 500 error code for the 15sec timeout:
![image](https://user-images.githubusercontent.com/73259768/149715515-7402a35a-bf8a-4c15-8763-238f40269282.png)

I believe that this is medium priority (rather than low) as since there is no error fired, there is no easy way to handle if this has happened.
To handle it, I would have to wait for 15 seconds once it resolves, then check if 1 (and only 1) "multipleResolves" event has occurred since resolving. That seems very jank.

### Code sample

```typescript
client.on("messageCreate", message => {
 someChannel.send({files : message.attachments.first()}).catch((err) => console.error(err));
}
// The attachment must be the exact same size as your 15sec upload limit allows, if not slightly more
```

### Package version

13.6.0

### Node.js version

v17.0.1

### Operating system

win10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL, GUILD_MEMBER

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

**Comment by soulus98** [comment]
@iCrawl 

This isn't a voice thing, it is just sending files in channels...

**Comment by didinele** [comment]
> Package version
> 13.6.0

Things have changed a lot since then, if this is still an issue, please re-open.

That being said, I think there was legitimately nothing to be done here to begin with, this is just how Discord handles it.
