### ISSUE TITLE
Discord view problem

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7297]
### Which package is this bug report for?

discord.js

### Issue description

For example, let's call it a registration process. You mentioned one person in the registration process, then you registered and changed the name. His old name is "Alex" and the new name he's changed is "Jack." He doesn't appear to be Jack when the recording takes place, he appears as Alex, but when we look at the audit record, the name appears to be "Jack". what is the problem?

### Package version

13.6.0

### Node.js version

16

### Operating system

Web  service

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION, GUILD_SCHEDULED_EVENT

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by almostSouji** [comment]
Your issue is missing detailed steps and code to reproduce.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.

**Comment by wioniqle-q** [comment]
> 

```js
const { Command } = require("discord-akairo");

module.exports = class extends Command {
  constructor() {
    super("Boy", {
      aliases: ["man"],
      args: [
        {
          id: "member",
          type: "member"
        },
        {
          id: "name",
          type: 'string',
          match: 'rest'
        }
      ]
    });
  }

  async exec(ctx, args) {
    try {
      const { member, name } = args;
      await member.setNickname(name);
    } catch (error) {
      ctx.util.send("Getting some error!");
      console.error(error);
      return Promise.resolve(null);
    }
  }
}

```
