### ISSUE TITLE
Slash commands timing out bot responds with "The application did not respond"

### ISSUE THREAD

**Issue by faraz-b** [discordjs/discord.js#7301]
### Which package is this bug report for?

discord.js

### Issue description

Using node v16.13.2 and discord.js v13.6.0 and followed all the steps for registering slash commands. The commands deploy successfully but upon running the /ping command (or any other command) the bot seems to time out and respond with "The application did not respond".

Not sure what problem I am running into, as I am following the guide to the tee. Any help would be greatly appreciated.

### Code sample

```typescript
// ** deploy-commands.js **

const fs = require('fs');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const { clientId, guildId, token } = require('./config.json');

const commands = []
const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
    const command = require(`./commands/${file}`);
    commands.push(command.data.toJSON());
}

const rest = new REST({ version: '9' }).setToken(token);

(async () => {
	try {
		console.log('Started refreshing application (/) commands.');

		await rest.put(
			Routes.applicationGuildCommands(clientId, guildId),
			{ body: commands },
		);

		console.log('Successfully reloaded application (/) commands.');
	} catch (error) {
		console.error(error);
	}
})();

// ** ping.js **

const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('ping')
		.setDescription('Replies with Pong!'),
	async execute(interaction) {
		await interaction.reply('Pong!');
	},
};

```

### Package version

13.6.0

### Node.js version

16.13.2

### Operating system

Windows 10 Version 21H1 (OS Build 19043.1466)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by advaith1** [comment]
this is probably an issue in your command handling code (which doesn't seem to be shown, if it exists), but for support go to https://discord.gg/djs, this issue tracker is for bug reports

**Comment by faraz-b** [comment]
Thank you for the insight, silly mistake, the error was a typo within the client.commands.set() function.

**Comment by kosmoPAP** [comment]
Hello @faraz-b,

I have the exact same mistake and can't find the error,

what typo do you have in the client.commands.set()?thanks in advance

**Comment by faraz-b** [comment]
> 

`I had client.commands.set(command.name, command);` Which was correct for v12

But for v13, the change should be 

`client.commands.set(command.data.name, command);`

Hope this helps

**Comment by TonyPatinoZ** [comment]
> I had `client.commands.set(command.name, command);` Which was correct for v12
I'm just wondering what you mean? There isn't any mention of client.commands in your code? I'm having the same problem and want to know how to fix it.
