### ISSUE TITLE
DiscordJs throwing vulnerability errors for node-fetch

### ISSUE THREAD

**Issue by xicor333** [discordjs/discord.js#7323]
### Which package is this bug report for?

discord.js

### Issue description

Node-fetch <3.1.1 has been declared vulnerable.

Discord.js targets 2.6.7 and node,github are flagging it as vulnerable
Is there an easy fix we can do locally for this or is there a fix coming?

npm audit
# npm audit report

node-fetch  <3.1.1
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install undefined@undefined, which is a breaking change
node_modules/@discordjs/rest/node_modules/node-fetch
node_modules/discord.js/node_modules/node-fetch
  @discordjs/rest  *
  Depends on vulnerable versions of node-fetch
  node_modules/@discordjs/rest
  discord.js  >=12.0.0
  Depends on vulnerable versions of node-fetch
  node_modules/discord.js

3 high severity vulnerabilities

### Package version

discord.js@13.6.0

### Node.js version

v16.13.2

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Dev-CasperTheGhost** [comment]
Duplicate of https://github.com/discordjs/discord.js/issues/7319
