### ISSUE TITLE
dep node-fetch 2.6.6 introduce high severity

### ISSUE THREAD

**Issue by creharmony** [discordjs/discord.js#7328]
### Which package is the feature request for?

discord.js

### Feature

`discord.js` is using node-fetch `2.6.6` as dependency. 

```` 
├─┬ discord-webhook-node@1.1.8
│ └── node-fetch@2.6.7
├─┬ discord.js@13.6.0
│ └── node-fetch@2.6.6
```` 

### Ideal solution or implementation

It would be great to jump to a more recent version of node-fetch (eg.3.2)

### Alternative solutions or implementations

As workaround you could force nested dep using (package.json) :
```
(scripts:)
"preinstall": "npx force-resolutions",
(devDependencies:)
 "node-fetch": "^2.6.7",
(resolutions:)
    "node-fetch": "^2.6.7"
````

**Comment by iCrawl** [comment]
Check for duplicates first.

**Comment by creharmony** [comment]
sorry I missed that #7324 🙏

**Comment by ImRodry** [comment]
And #7326 and #7323
