### ISSUE TITLE
missing value in GuildBan

### ISSUE THREAD

**Issue by Bengeljo** [discordjs/discord.js#7329]
### Which package is this bug report for?

discord.js

### Issue description

I want to get the reason for a ban. 
I use the event 'guildBanAdd' bind it to the parameter ban.
So after the docs I should be able to get the reason for the ban with ban.reason, but I don't since it is undefined.
I looked then what ban logs when I console.log it. 
There is no data about the reason. 

### Code sample

```typescript
client.on('guildBanAdd', async (ban) => {
  console.log(ban)
  console.log("User is getting banned")
  console.log(ban.guild.id)
  console.log(ban.guild.name)
  console.log(ban.user.id)
  console.log(ban.user.tag)
  let reason = ban.reason
  console.log(reason || null)

  console.log ("-----------------------")
```

### Package version

v13.6.0

### Node.js version

v16.13.1

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GUILD_MEMBER

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS

**Comment by GoldenAngel2** [comment]
`reason` doesn't get sent over the gateway, so you would need [fetch the audit log](https://discord.js.org/#/docs/discord.js/stable/class/Guild?scrollTo=fetchAuditLogs) entry to get the reason for the ban

**Comment by Bengeljo** [comment]
> 

Oh okay thanks for the help.   
so it would be  "ban.guild.fetchAuditLogs()" in my code right ? Do I have to add anything to it or would that just work like this?

**Comment by almostSouji** [comment]
If you need more information on working with audit logs, you might find this guide article useful: <https://discordjs.guide/popular-topics/audit-logs.html>
