### ISSUE TITLE
Can't use setnickname with username

### ISSUE THREAD

**Issue by lulu5239** [discordjs/discord.js#7330]
### Which package is this bug report for?

discord.js

### Issue description

Normally, on Discord, it's possible to set someone's nickname to the person's username...
![image](https://user-images.githubusercontent.com/32999164/150691757-67c99ac7-a918-4d9c-bb9d-d8ead6e6a235.png)
But when I try to change this person's nickname to their exact username with my bot, it just removes the nickname.
![image](https://user-images.githubusercontent.com/32999164/150691807-72248e6f-e0fa-4107-b4b9-f8eac40a5eb5.png)

I've put this in low priority because it's not something every bot do, but I still need this to be fixed.

### Code sample

```typescript
message.guild.members.fetch("MEMBER ID").then(m=>{
  m.setNickname(m.user.username)
})
```

### Package version

13.2.0

### Node.js version

16.12.0

### Operating system

Glitch (glitch.com)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by ImRodry** [comment]
I believe this is intended behavior as I cannot change a user’s nickname to their username. Tried this using /nick and changing it on the profile editor and both just reset my nickname. Also off-topic but FYI, Glitch is not an OS and you should be using the latest version of the package

**Comment by lulu5239** [comment]
Ah yes, just noticed that. Probably a Discord bug... but I can still find people with the same nickname as their usernames on other servers.
![image](https://user-images.githubusercontent.com/32999164/150694242-068ab28b-e292-4ae7-a4af-b4544919e4a0.png)

**Comment by ImRodry** [comment]
That is likely because the user had a different username, nicked, and then changed their username to the nick, which doesn’t cause it to update
