### ISSUE TITLE
GuildMember.joinedAt returns Undefined

### ISSUE THREAD

**Issue by Dragonaere** [discordjs/discord.js#7334]
### Which package is this bug report for?

discord.js

### Issue description

I've tried creating a command which outputs an embed with a users info. I followed what people in the discord said and used GuildMember.joined at, but it returns undefined.

### Code sample

```typescript
const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed, GuildMember } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('user')
		.setDescription('Replies with user info!'),
		async execute(interaction) {
    		interaction.user.fetch(force = true)
        	let userTag=interaction.user.tag
        	let userAvatar=interaction.user.displayAvatarURL({dynamic: true})
        	const userEmbed = new MessageEmbed()
			.setTitle(userTag)
			.setThumbnail(userAvatar)
        	.addField('Account Created: ', `${interaction.user.createdAt}`)
        	.addField('Joined Server: ', `${GuildMember.joinedAt}`)
			.setTimestamp()
			await interaction.reply({embeds: [userEmbed]});
		},
};
```

### Package version

discord.js@13.6.0

### Node.js version

v16.13.2

### Operating system

Windows 11 Pro

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GUILD_MEMBER

### Which gateway intents are you subscribing to?

GUILDS

**Comment by ImRodry** [comment]
That is indeed not how you access a property from a class. I highly advise you to place these questions on the [Discord server](discord.gg/djs) first or even learn some JS before using the library. Also please close this as this is not an issue
