### ISSUE TITLE
`type` property in component constructors is required

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#7342]
### Which package is this bug report for?

builders

### Issue description

When passing a data object to the constructor of any component (aka ActionRow, ButtonComponent or SelectMenuComponent) the `type` parameter is required even though this isn't needed as it is set as a constant in the class and not read from the data passed to the constructor.

### Code sample

```typescript
const row = new ActionRow({
	components: [
		new ButtonComponent({
			style: 1,
			label: 'test',
			custom_id: 'test',
		}),
		new SelectMenuComponent({
			custom_id: 'test',
			options: [
				{
					label: 'test',
					value: 'test',
				}
			]
		})
	],
});
```

### Package version

0.12.0

### Node.js version

16.13.1

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Th1983** [comment]
ok
