### ISSUE TITLE
CommandInteraction.guild.roles does not fetch users while Message.guild.roles does?

### ISSUE THREAD

**Issue by PennyJim** [discordjs/discord.js#7347]
### Which package is this bug report for?

discord.js

### Issue description

When trying to find out how many members has each role when starting with CommandInteraction, it seems to only know of the users it has already cached. When the bot has just started this is only the client and the user interacting.
This does not happen when retrieving roles through a message.
![image](https://user-images.githubusercontent.com/40438818/151113053-f7aafd3d-f03f-48c1-9d49-877ca1ce9abd.png)
![image](https://user-images.githubusercontent.com/40438818/151113072-bcef5aaf-cb3e-4199-947a-1f0274553a16.png)

### Code sample

```typescript
client.on("interactionCreate", async interaction => {
    if (interaction.inGuild())
    {
        let roles = interaction.guild.roles;
        //await interaction.guild.members.fetch(); //To fix the issue
        (await roles.fetch()).forEach(role => {
            console.log(role.name, role.members.size);
        });
    }
}
```

### Package version

14.0.0

### Node.js version

v16.13.2

### Operating system

Pop OS (and Pi OS)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES

### I have tested this issue on a development release

b640272

**Comment by ImRodry** [comment]
`roles.fetch()` returns a promise that you have to await so that code sample is invalid. In order to fetch the members, however, you need to run `guild.members.fetch`. Not sure how this is related to interactions/messages but it likely isn’t

**Comment by PennyJim** [comment]
> `roles.fetch()` returns a promise that you have to await so that code sample is invalid. In order to fetch the members, however, you need to run `guild.members.fetch`. Not sure how this is related to interactions/messages but it likely isn’t

I understand what roles.fetch() returns. I have fixed the code sample, as all it was missing was the closing parenthesis that awaited the roles.fetch() before using the collection for the forEach loop.

**Comment by ImRodry** [comment]
That doesn’t change the fact that roles.fetch will not fetch the members with that role

**Comment by PennyJim** [comment]
But it does fetch the roles, which should contain the members that have that role

**Comment by ImRodry** [comment]
But it doesn’t, that’s not how the API works

**Comment by PennyJim** [comment]
Oh okay now I finally see the "cached guild members that have this role" in the documentation. I feel dumb now, but I feel like it might need to be emphasized as both me and my friend missed that.

**Comment by ImRodry** [comment]
I don’t see how it could be more emphasized than that warning but if you have an idea, feel free to PR

**Comment by PennyJim** [comment]
Oh I'm too tired to work on a pull request, and I'll probably forget it by tomorrow. My only suggestion would maybe italicize it. Either way thank you for the help and goodnight.
