### ISSUE TITLE
GuildMemberManager cannot read client

### ISSUE THREAD

**Issue by Bengeljo** [discordjs/discord.js#7351]
### Which package is this bug report for?

discord.js

### Issue description

If I try to run the code I get the following the error message. I tried to look it up only but the only solution was to define the Client with Discord.Client which I then did but it didn't helped. 

\node_modules\discord.js\src\managers\GuildMemberManager.js:20
    super(guild.client, GuildMember, iterable);
                ^

TypeError: Cannot read properties of undefined (reading 'client')
    at new GuildMemberManager \node_modules\discord.js\src\managers\GuildMemberManager.js:20:17)
    at Object.<anonymous> \test.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

### Code sample

```typescript
require('dotenv').config();
const Discord = require('discord.js')
const { Client, Collection, Interaction, Intents, GuildBan, MessageEmbed, GuildMemberManager, } = require("discord.js")
const client = new Discord.Client({intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_BANS, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGES]})
const mongoose = require("mongoose");
const { Console } = require('console');
const manager = new GuildMemberManager

client.on('ready', async () => {
    console.log(`Ready! Logged in as ${client.user.tag}! I'm on ${client.guilds.cache.size} servers`) //I'm on ${client.guilds.cache.size} servers
      client.user.setActivity({name: "people get banned", type: "WATCHING"})
  })


  client.on('messageCreate', async (message) => {
    if(message.author.bot) return
    if (message.content.toLowerCase().startsWith('?servercheck') ) {
        if(message.member.permissions.has('ADMINISTRATOR'||'BAN_MEMBERS')){
          
          const members = manager.fetch()
          console.log(members)
        }
      }
      else {message.channel.send('You do not have permission for this command')}
      })


  client.login(process.env.BOT_TOKEN)
```

### Package version

v13.6.0

### Node.js version

v16.13.1

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_MESSAGES

**Comment by Jiralite** [comment]
Unfortunately, this is not how you use discord.js's methods. If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
