### ISSUE TITLE
Fork installation

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#7360]
### Which package is this bug report for?

discord.js

### Issue description

After monorepo refactor (#7175) it's now difficult to install a fork as dependancy from GitHub.
I found this tool witch https://gitpkg.vercel.app/ helped me to install my discord.js fork.

Is there an easier way ?

### Package version

master

### Node.js version

v16.13.1 and typescript@4.5.5

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

**Comment by Koyamie** [comment]
I've been experiencing the same issue since I use a fork too.
My solution was to import the repo by specifying the package path.

Example:
```js
import {
  Client as DiscordClient,
  Collection,
  WebhookClient,
  MessageEmbed,
  MessageButton,
  MessageSelectMenu,
  MessageActionRow,
  Permissions,
  Util as DiscordUtil,
} from '@discordjs/discord.js/packages/discord.js/src/index.js';
```

It's a tricky way but it works, I am only importing it once and get all the classes I need.

**Comment by DraftProducts** [comment]
Not realy DX frendly 😬 
Also, it's a half-solution because you don't have access to typings with this way 🥺

**Comment by Koyamie** [comment]
Yeah obviously just sharing as a workaround.
And I'm not using typings so it doesn't bother me.

**Comment by kyranet** [comment]
You can do one of the following solutions:

1. Use `yarn link` inside the `packages/discord.js` directory and in your application's folder.
1. Run `yarn pack`, copy the contents of the `.tgz` file and drop them into your `node_modules`.

**Comment by DraftProducts** [comment]
I found some options that would require a repo change :
- https://stackoverflow.com/a/39195334
- https://stackoverflow.com/a/65105135

if that is not possible, it would be nice to add a part to the documentation to advise using https://gitpkg.vercel.app/ for fork use :man_shrugging:

**Comment by DraftProducts** [comment]
Yeah, either way, this should be documented somewhere.

> You can do one of the following solutions if you have the fork downloaded locally:
> 
> 1. Use `yarn link` inside the `packages/discord.js` directory and in your application's folder.
> 2. Run `yarn pack`, copy the contents of the `.tgz` file and drop them into your `node_modules`.

Yeah, we should document that somewhere 👍

**Comment by didinele** [comment]
There's not much we can do here. Tooling has probably improved a fair share in the meantime, though,
