### ISSUE TITLE
where is  the GuildBasedChannel 

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7361]
### Which package is this bug report for?

discord.js

### Issue description

where is the GuildBasedChannel

### Code sample

```typescript
where is the GuildBasedChannel
```

### Package version

13.6.0

### Node.js version

16

### Operating system

Web  service

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION, GUILD_SCHEDULED_EVENT

### Which gateway intents are you subscribing to?

GUILD_INVITES, GUILD_VOICE_STATES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by SpaceEEC** [comment]
It's right here: https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/typings/index.d.ts#L5586

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
