### ISSUE TITLE
Thread.setLocked(true) / Thread.setArchive(true) docs mistake

### ISSUE THREAD

**Issue by lytk4dev** [discordjs/discord.js#7367]
### Which package is this bug report for?

discord.js

### Issue description

I'm trying to close a branch with setLocked(true), the "unarchive" window pops up, but still anyone can write to that branch. 

### Code sample

```typescript
const thread = this.interaction.channel.threads.cache.find(x => x.name === `Thread n`);
      thread.setArchived(true).setLocked(true)
```

### Package version

13.6.0

### Node.js version

17.2.0

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by Jiralite** [comment]
That reproducible code same won't work which may be your issue, you're calling a method on a `Promise`.
