### ISSUE TITLE
Invite get not has found

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7370]
### Which package is this bug report for?

discord.js

### Issue description

1. I'm creating an invitation
2. I call this invitation from my side account
3. then, when I receive my account with this invitation, my bot finds the person it invites to my account.
4. automatically registers in collection when I create an invitation.

-- Problem :  the user invited to the server does not find it correctly which invitee came from.
-- For example, I invited him, but he shows it as being invited by someone else.
-- console.log(code); finds the wrong invitation link
-- he thinks the inviter is wrong.
-- There was no problem in discord.js v12

### Code sample

```typescript
const { Collection } = require("discord.js");
const Invites = global.Invites = new Collection();


// inviteCreate event :
client.on("inviteCreate", (invite) => {
  var Invite = global.Invites.get(invite.guild.id).set(invite.code, invite);
  global.Invites.set(invite.guild.id, Invite);
});

// guildMemberAdd event: 
client.on("guildMemberAdd", async (member) => {
    const Invite = global.Invites.get(member.guild.id).clone();
    
    let channel = member.guild.channels.cache.get("936620437474013254");
    
    await guild.invites.fetch().then(async (_invites) => {
      let code = _invites.find((_x) => Invite.has(_x.code));
      await global.Invites.set(member.guild.id, _invites);
      await channel.send(`${code.inviter.id ? code.inviter.id : "is not found!"}`);
    });
});
```

### Package version

13.6.0

### Node.js version

16

### Operating system

Web  service

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageMentions, DirectMessageTyping, GuildScheduledEvents

**Comment by thehairy** [comment]
Invite tracker are very unreliable, nor are the issues for support, but for serious issue, bug reports or feature requests.

**Comment by wioniqle-q** [comment]
If it works correctly in v12, then v13 has a problem

**Comment by wioniqle-q** [comment]
> Invite tracker are very unreliable, nor are the issues for support, but for serious issue, bug reports or feature requests.

[IfIf it works correctly in v12, then v13 has a problem it works correctly in v12, then v13 has a problem](https://github.com/discordjs/discord.js/issues/7370#issuecomment-1026322346)

**Comment by thehairy** [comment]
> If it works correctly in v12, then v13 has a problem

That doesn't change my answer, your code looks sketchy as hell and I doubt that would work at all.
Either you aren't providing the full code or thats simply... wrong.

The only way to "track" invites is to compare the uses, which can be wrong in many cases.

But that doesn't matter, as said, GitHub issues aren't for support, but for bug reports and feature requests.
Yours is neither.

Also what is "Web service", don't tell me you are using replit or similar 💀

**Comment by wioniqle-q** [comment]
The whole code is here, the answer to your question changes yes, it doesn't. same code version v12 is working properly and v13 the same code is not working properly which means there is a problem with v13

**Comment by wioniqle-q** [comment]
> > The whole code is here, the answer to your question changes yes, it doesn't. same code version v12 is working properly and v13 the same code is not working properly which means there is a problem with v13
> 
> V13 is a major version, so it's not necessary that v12 code should work in v13. Also, v13 was having a lot of breaking changes, so there is no way all v12 codes will work in v13.
> 
> Also as said earlier use discord server for support

it's ridiculous.
