### ISSUE TITLE
`User.flags.toArray()` return value always includes `None` flag.

### ISSUE THREAD

**Issue by N1ckPro** [discordjs/discord.js#7374]
### Which package is this bug report for?

discord.js

### Issue description

Use the code sample below on a user with any flags.
Logged array will include `None` even though the user has flags.

### Code sample

```typescript
const flags = await message.author.fetchFlags() // Message author needs to have any flags
console.log(flags.toArray())
```

### Package version

discord.js@14.0.0-dev.1643544396.388f535

### Node.js version

16.13.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

### I have tested this issue on a development release

388f535

**Comment by ImRodry** [comment]
Perhaps this could be transfered to discord-api-types so it can be closed with the linked PR?
