### ISSUE TITLE
Type `MappedInteractionTypes` Error

### ISSUE THREAD

**Issue by Didas-git** [discordjs/discord.js#7383]
### Which package is this bug report for?

discord.js

### Issue description

I havent tried to get an error with this but i found out while walking on the types for djs that there is an error on the collectors type.
I have no idea if this is intentional but it can cause problems to someone.
![image](https://user-images.githubusercontent.com/80978939/151972773-220a78b6-010e-4c59-845d-5b3058b73124.png)

The error is long thus i cant screenshot it all
![image](https://user-images.githubusercontent.com/80978939/151973428-8e607f86-5a2c-4957-9914-795717c4a26d.png)

### Package version

discord.js@14.0.0-dev.1643674011.803665

### Node.js version

Node: v17.4.0; TS: Version 4.5.4

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
We cannot reproduce this. This is probably an issue from your editor (and thus not the code). For example, you may be running a different TypeScript version in your editor than what discord.js is on.

**Comment by Didas-git** [comment]
> We cannot reproduce this. This is probably an issue from your editor (and thus not the code). For example, you may be running a different TypeScript version in your editor than what discord.js is on.

I rly don't know what is the issue here, at first i thought it was an issue with me being on my macbook but after restarting and even trying it on my windows machine i still have the same errors at the index.d.ts file from djs.
This is the package version im testing with (updated since yesterday): 14.0.0-dev.1643803384.883943
It rly seems weird that im having the same issues both on windows and mac with both machines having node v17.x and ts v4.5.x

**Comment by kyranet** [comment]
Do those errors also appear when building? Or only in VSCode?

**Comment by Didas-git** [comment]
> Do those errors also appear when building? Or only in VSCode?

I haven't gotten any errors yet, i only get thoose errors showing on vscode when i open the index.d.ts file to check the typings

**Comment by kyranet** [comment]
Hover on the `{}` next to `TypeScript` bottom right your VSCode, what does it show?
![image](https://user-images.githubusercontent.com/24852502/152218030-1e7d6ea3-4112-47f9-8196-208c989a17ee.png)

**Comment by Didas-git** [comment]
> Hover on the `{}` next to `TypeScript` bottom right your VSCode, what does it show? ![image](https://user-images.githubusercontent.com/24852502/152218030-1e7d6ea3-4112-47f9-8196-208c989a17ee.png)

![image](https://user-images.githubusercontent.com/80978939/152241951-1f6e9cad-fd70-4b13-a6b2-40c60c89c840.png)

**Comment by Hanashi** [comment]
@Didas-git how do you fixed this? I have the same issue.

**Comment by tyzoo** [comment]
> @Didas-git how do you fixed this? I have the same issue.

I added `"skipLibCheck": true,` to `complierOptions` in `tsconfig.json` to suppress this crap

**Comment by Jiralite** [comment]
Read the comments on #7924 to understand why this happens and how to avoid it.
