### ISSUE TITLE
Role create diffrent

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7394]
### Which package is the feature request for?

discord.js

### Feature

role create method needs to be edited. please review

### Ideal solution or implementation

role create method needs to be edited. please review

**Comment by monbrey** [comment]
> role create method needs to be edited. please review

Why?

**Comment by wioniqle-q** [comment]
> > role create method needs to be edited. please review
> 
> Why? How? What issues do you see with the current role create method that you believe require it to be edited?

I wish I could, all I ask is that you just review it
