### ISSUE TITLE
ColorResolvable RGB array does not work properly

### ISSUE THREAD

**Issue by TheFortex** [discordjs/discord.js#7405]
### Which package is this bug report for?

discord.js

### Issue description

https://discord.js.org/#/docs/discord.js/stable/typedef/ColorResolvable

I am making an embed with the color set to `[45, 151, 299]` but it shows the embed green when it should be blue
![image](https://user-images.githubusercontent.com/60301549/152635832-6bd1f829-8115-467f-82cf-acab1f598b6f.png)
![image](https://user-images.githubusercontent.com/60301549/152635792-335bd583-9f57-48d6-81d0-692d84b3e7a7.png)
![image](https://user-images.githubusercontent.com/60301549/152635798-b16c2349-17e6-410f-b0a2-efbb59867c04.png)

### Code sample

```typescript
client.on('messageCreate', (message) => {
	const embed = new MessageEmbed()
	embed.setDescription(message.content)
	embed.setColor([45, 151, 299])

	message.reply({embeds: [embed]})
})
```

### Package version

discordjs/rest@0.3.0 | discord.js@13.6.0

### Node.js version

v17.4.0

### Operating system

Windows 10

### Priority this issue should have

Low

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I haven't tested this issue on a development release

I tried but it just breaks my whole bot

**Comment by monbrey** [comment]
RGB values lie in the range 0-255. Your 299 value for blue is not valid and is therefore being ignored, which would create green.

That website you're using is trash.

**Comment by TheFortex** [comment]
I don't know how I never noticed that. Sorry for the issue.
