### ISSUE TITLE
Unknown Voice State error when making the bot a speaker in a stage

### ISSUE THREAD

**Issue by Avoxel284** [discordjs/discord.js#7407]
### Which package is this bug report for?

voice

### Issue description

After a bot joins a Discord Stage, attempting to make the bot a speaker via `setSuppressed(false)` fails with this error:
```
DiscordAPIError: Unknown Voice State
    at RequestHandler.execute (<my project path>/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (<my project path>/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async VoiceState.setRequestToSpeak (<my project path>/node_modules/discord.js/src/structures/VoiceState.js:222:5) {
  method: 'patch',
  path: '/guilds/939423361187078144/voice-states/@me',
  code: 10065,
  httpStatus: 404,
  requestData: {
    json: {
      channel_id: '939569537119055902',
      request_to_speak_timestamp: '2022-02-05T17:15:22.698Z'
    },
    files: []
  }
}
```

The bot otherwise works fine if I manually make the bot a speaker in the Discord client.
After observing the network traffic from my Discord client when I make myself a speaker in a stage, I saw the HTTPS request was `'/guilds/939423361187078144/voice-states/<my client id>'` rather than 
`'/guilds/939423361187078144/voice-states/@me'`, so I believe this is the issue.

### Code sample

```typescript
const connection = discordVoice.joinVoiceChannel({
    channelId: channel.id,
    guildId: guild.id,
    adapterCreator: msg.guild.voiceAdapterCreator,
});

msg.guild.me.voice.setSuppressed(false)
```

### Package version

0.8.0

### Node.js version

17.0.1

### Operating system

MacOS Big Sur

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages, GuildMessageReactions

**Comment by ImRodry** [comment]
I can't reproduce this issue with the given code sample and my bot having all permissions. Also, if anything, this is an issue with discord.js, **not voice**, so you should include your discord.js version

**Comment by Avoxel284** [comment]
Sorry my bad, there was an issue on my end.
