### ISSUE TITLE
Error fetching argument using options.getString and more

### ISSUE THREAD

**Issue by AnggaaIs** [discordjs/discord.js#7412]
### Which package is this bug report for?

discord.js

### Issue description

![IMG_20220206_132456](https://user-images.githubusercontent.com/84172981/152670051-3aac82a4-30ba-4fbd-ac38-f70daf10a44b.jpg)

### Code sample

```typescript
const value = ctx.interaction.options.getString("language")
```

### Package version

14.0.0-dev

### Node.js version

16.13.1

### Operating system

Android Arm64

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages

### I have tested this issue on a development release

d8184f9

**Comment by imranbarbhuiya** [comment]
Seems like you are using `getString` in user contextmenu command. User contextmenu command only have `getUser`, `getMember` methods.

**Comment by monbrey** [comment]
You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.

**Comment by AnggaaIs** [comment]
> You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.

Can you demo the code?

**Comment by imranbarbhuiya** [comment]
> > You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.
> 
> Can you demo the code?

```ts
if(!ctx.interaction.isChatInputCommand()) return
```

**Comment by AnggaaIs** [comment]
> > > You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.
> > 
> > Can you demo the code?
> 
> ```ts
> if(!ctx.interaction.isChatInputCommand()) return
> ```
> 

It doesn't solve my problem

**Comment by imranbarbhuiya** [comment]
> > > > You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.
> > > 
> > > 
> > > Can you demo the code?
> > 
> > 
> > ```ts
> > if(!ctx.interaction.isChatInputCommand()) return
> > ```
> 
> It doesn't solve my problem

u need to store `ctx.interection` then use the typeguerd

```ts
const interaction = ctx.interaction;
if(!interaction.isChatInputCommand()) return;
```

**Comment by AnggaaIs** [comment]
> > > > > You seem to have forcibly cast this as `CommandInteraction` rather than one of the more specific types. You should be using typeguards such as `.isChatInputCommand()` to correctly narrow this down.
> > > > 
> > > > 
> > > > Can you demo the code?
> > > 
> > > 
> > > ```ts
> > > if(!ctx.interaction.isChatInputCommand()) return
> > > ```
> > 
> > It doesn't solve my problem
> 
> u need to store `ctx.interection` then use the typeguerd
> 
> ```ts
> const interaction = ctx.interaction;
> if(!interaction.isChatInputCommand()) return;
> ```
> 
> 

Returns the same error

**Comment by imranbarbhuiya** [comment]
@AnggaaIs  after using the typeguerd you need to use `getString` in `interaction` and not `ctx.interaction`
```ts
const value = interaction.options.getString("language")
```
If it's not working then provide show what is ctx, from where it's coming

**Comment by AnggaaIs** [comment]
> @AnggaaIs after using the typeguerd you need to use `getString` in `interaction` and not `ctx.interaction`
> 
> ```ts
> const value = interaction.options.getString("language")
> ```
> 
> If it's not working then show what is ctx, from where it's coming

Ok, I will try it

**Comment by AnggaaIs** [comment]
> @AnggaaIs after using the typeguerd you need to use `getString` in `interaction` and not `ctx.interaction`
> 
> ```ts
> const value = interaction.options.getString("language")
> ```
> 
> If it's not working then show what is ctx, from where it's coming

Still not working, here's the ctx https://github.com/AnggaaIs/origami/blob/main/src/classes/CommandContext.ts

**Comment by monbrey** [comment]
I've unable to reproduce your issue with the code you've provided. I copied the CommandContext class across and did the following without any TypeScript errors:

![image](https://user-images.githubusercontent.com/5294381/152672326-188cdb27-eccd-450e-8044-ad8780e3944e.png)

It also works with an if not, return:

![image](https://user-images.githubusercontent.com/5294381/152672339-e60052d4-ce60-46ca-887d-cb6f7221ed5a.png)

**Comment by AnggaaIs** [comment]
> I've unable to reproduce your issue with the code you've provided. I copied the CommandContext class across and did the following without any TypeScript errors:
> 
> ![image](https://user-images.githubusercontent.com/5294381/152672326-188cdb27-eccd-450e-8044-ad8780e3944e.png)
> 
> It also works with an if not, return:
> 
> ![image](https://user-images.githubusercontent.com/5294381/152672339-e60052d4-ce60-46ca-887d-cb6f7221ed5a.png)
> 
> I did remove the locale dependency, but I don't see how that would impact this anyway.

Alright, I'm still getting an error, thank you for your cooperation
