### ISSUE TITLE
Add ability to limit slash command string option's length

### ISSUE THREAD

**Issue by ChaunceyHoover** [discordjs/discord.js#7419]
### Which package is the feature request for?

builders

### Feature

If you look at the methods available for `SlashCommandBuilder.addIntegerOption`, you'll see that it has two methods: `setMinValue` and `setMaxValue`. These prevent the user from using numbers below or above a specific range, respectively. 

I think it would be beneficial to have something similar with `addStringOption` to limit the length of what users can type. By adding two methods, `setMinLength` and `setMaxLength`, this will give bot creators much more control over string option values.

### Ideal solution or implementation

Add two methods to the `SlashCommandStringOption` class:

`setMinLength(int length)` - This will set the minimum amount of text required to enter a value for the option value

`setMaxLength(int length)` - This will set the maximum amount of text a user can enter for the option value

### Alternative solutions or implementations

It wouldn't have to be methods to set the limit. I'd also be open to adding the min and max length to the `addStringOption(input)` method. They can even be optional or default to certain values (ex: min = 0, max = 256. These are just arbitrary numbers - I'm okay with anything).

Another solution would be to give custom input validation functions to the user which can prevent the user from sending the command unless all the option values are "valid" according to whatever function the user passes for each option, if any. For example:

```js
new SlashCommandBuilder()
  .setName("example")
  .setDescription("An example command that requires you to pass a string value with at least 3 characters.")
  .addStringOption(option =>
    option.setName("input")
      .setDescription("A parameter that requires at least 3 letters.")
      .setRequired(true)
      .setValidator((optionValue) => { return optionValue.length < 3 }) // boolean determines if option is "valid"
```

This option is more generic and could be applied to any of the `add*Option` methods, but I'm not sure if there's functionality for that, either.

### Other context

I'm not sure if this is even something that's possible with the new Discord API. If it's not, please let me know so I can go open an issue and see elsewhere to see if it's something Discord would be willing to implement this idea so discord.js can properly implement their implementation.

**Comment by Jiralite** [comment]
Limiting string length is not possible. Limiting numbers is and that is why the relevant methods exist.

**Comment by ChaunceyHoover** [comment]
Is it possible to validate the string with a user-created function, like in my alternative solutions snippet of code?

**Comment by imranbarbhuiya** [comment]
> Is it possible to "validate" the string with a user-created function, like in my alternative solutions snippet of code? This could act as a string length limiter if so.

min_value and max_value are provided by discord only for `number` and `integer` option. There are no such options present for string. So how djs will limit the user input?

**Comment by ChaunceyHoover** [comment]
> I'm not sure if this is even something that's possible with the new Discord API. If it's not, please let me know so I can go open an issue and see elsewhere to see if it's something Discord would be willing to implement this idea so discord.js can properly implement their implementation.

Maybe just say it's not possible instead of being passive aggressive? This is an open source project, meaning anyone can come in and create issues. I'm still learning Discord's new API, so I wasn't sure if this was a feature or not. I'll try suggesting it in a more appropriate location and hopefully I can re-visit this issue if it gets added. Thanks.
