### ISSUE TITLE
embed thumbnail image not showing 

### ISSUE THREAD

**Issue by YinglunQ** [discordjs/discord.js#7420]
### Which package is this bug report for?

discord.js

### Issue description

tried this [image](https://msavatar1.nexon.net/Character/IOJMCGNODPCFANEIMFJOIPOKLHLDEILANJHNHFGKDDPEDHGCKEINFBGPEAOCBLJNIIHGMHIGLMAEMHFCDIFMCMMPPAONHGPEJEKNKBGKFEAMILLMALDIDPMFPGBDMPNDEMGGBPAGPEOOINFCFAJMMKFOPKLBGHBCPIFMEHKGIEIFGAKOCHPMMPKPHGOMGHIBPJOCMBDKEICIMFBPLLCADLGFHELPENIKBDNDONAOGGKLDCHBOEOGCBCOMKDELDMJ.png) using `MessageEmbed.setThumbnail()` and it doesn't seem to display in the embed message.

### Code sample

```typescript
const { MessageEmbed } = require('discord.js');

const embed = new MessageEmbed().setThumbnail("https://msavatar1.nexon.net/Character/IOJMCGNODPCFANEIMFJOIPOKLHLDEILANJHNHFGKDDPEDHGCKEINFBGPEAOCBLJNIIHGMHIGLMAEMHFCDIFMCMMPPAONHGPEJEKNKBGKFEAMILLMALDIDPMFPGBDMPNDEMGGBPAGPEOOINFCFAJMMKFOPKLBGHBCPIFMEHKGIEIFGAKOCHPMMPKPHGOMGHIBPJOCMBDKEICIMFBPLLCADLGFHELPENIKBDNDONAOGGKLDCHBOEOGCBCOMKDELDMJ.png");

message.channel.send({ embeds: [embed] });
```

### Package version

13.6.0

### Node.js version

17.4.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by telunc** [comment]
I have the same issue too!

**Comment by ImRodry** [comment]
While I can replicate this issue with that link, this is not an issue with discord.js as the library is not responsible for validating image URLs, all that is done on the API’s side, so maybe you should report this to them instead
