### ISSUE TITLE
Interface with Modify Current User endpoint

### ISSUE THREAD

**Issue by dark-fedora** [discordjs/discord.js#7425]
### Which package is the feature request for?

discord.js

### Feature

I attempted to have my bot change its own username today in a server I'm in to enforce a nickname policy (I didn't want to bug the owner) and found to my utter surprise that I did not have the permissions to do so, despite having Manage Nicknames, Change Nickname, Administrator, and the highest role on the server. I did a little bit of research and found out about the [Manage Current Member](https://discord.com/developers/docs/resources/guild#modify-current-member) endpoint, and realized DJS apparently had no implementation of this. I'd like to see this implemented with DJS.

Oddly enough, others did not appear to have the same issue, but I've double checked everything, and I could not implement a fix on my own.

I can confirm that I was getting an HTTP 403 with a 50013 `DiscordAPIError: Missing Permissions` every time I attempted to do this, and no other syntatical errors. I've ensured both the guild is correct and that the methods I'm using are accurate, hence why this is not listed as a bugfix.

### Ideal solution or implementation

A new method on the Guild class, setOwnNickname. Accepts a valid nickname as an argument, then uses the Modify Current Member endpoint to update the bot's username.

### Alternative solutions or implementations

Checking equivalence with the ClientUser when using GuildMember.setNickname. If they are the same, use the Modify Current Member endpoint. As it is, attempting to modify the bot's own nickname with this permission will always fail, as it has equivalent permissions/roles to itself.

### Other context

I used `<GuildManager>.fetch` to obtain the guild itself (but also tried using `<GuildManager>.cache.get`), and then `<Guild>.me.setNickname` to change the username. This seems like a very simple way to do it, so I have no clue what I can do from here. Others in the DJS server were also stumped.

**Comment by ckohen** [comment]
Discord.js does the handling of the different endpoints internally as can be seen in the source here (note this is code from main): https://github.com/discordjs/discord.js/blob/b936103395121cb21a8c616f669ddab1d2efb0f1/packages/discord.js/src/managers/GuildMemberManager.js#L282-L286

I thus suggest this is a bug, however, there is the question of whether this method should really be split out. I'm not sure why it was internally handled in the first place, but maybe it would be better to have them separate in v14 (would additionally help if more things are added to the endpoint in the future)

**Comment by SpaceEEC** [comment]
Splitting this route out into its own method would keep the quite surprising behavior of `GuildMember#edit` and `GuildMember#setNickname` throwing a "missing permissions" error.
Thus this route would become even more of a "gotcha" than it is now already.
(Discord, please allow changing your nickname through this route 🙏 )

I think this is something we, as a library, should abstract away, especially considering that this endpoint is solely used for nicknames (for bot users).

This however is something we would need to look into when Discord adds other uses for bots there.
