### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by HideakiAtsuyo** [discordjs/discord.js#7427]
### Which package is this bug report for?

discord.js

### Issue description

[Version Removed](https://github.com/discordjs/discord.js/commit/16390efe6e4f2035aa0fe365c8d593366beca7ce#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3)

### Package version

14.0.0-dev

### Node.js version

17.1.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by kyranet** [comment]
Not a bug, the monorepo's root isn't installable (nor should be). The actual package has the right version:

https://github.com/discordjs/discord.js/blob/b936103395121cb21a8c616f669ddab1d2efb0f1/packages/discord.js/package.json#L3
