### ISSUE TITLE
Bot exit date

### ISSUE THREAD

**Issue by bl0cknumber** [discordjs/discord.js#7432]
### Which package is the feature request for?

discord.js

### Feature

Is there any way to get exit date of a bot by passing bot ID and server ID parameters?

### Ideal solution or implementation

Is this related to discord functionality or could be implemented in this open source?

Feasible solution will be passing new function to retrieve the exit date

### Alternative solutions or implementations

External API

**Comment by almeidx** [comment]
Not something for the library. But yes, in theory, you could store the date when the bot leaves a guild via the [`Client#guildDelete`](https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-guildDelete) event.

**Comment by kyranet** [comment]
Discord does not provide this information, as such, you'll need to follow the suggestion by @almeidx to achieve a similar funcionality.

**Comment by bl0cknumber** [comment]
Awesome @almeidx
