### ISSUE TITLE
Channel "Types" Enum for Slash Command builders

### ISSUE THREAD

**Issue by MRDGH2821** [discordjs/discord.js#7434]
### Which package is the feature request for?

builders

### Feature

In this documentation [Add Channel Type](https://discord.js.org/#/docs/builders/stable/class/SlashCommandChannelOption?scrollTo=addChannelType), there is no clear telling what primitive type is the channel type.

The channel "types" are documented in [DAPI](https://discord.com/developers/docs/resources/channel#channel-object-channel-types) but there is no Enum or any structure/object to use them in DJS.

### Ideal solution or implementation

Just like there is 
```js
Intents.FLAGS.GUILDS,
Intents.FLAGS.GUILD_BANS,
Intents.FLAGS.GUILD_MEMBERS,
Intents.FLAGS.GUILD_WEBHOOKS,
Intents.FLAGS.DIRECT_MESSAGES
//etc etc 
```

We can have - 
```js
ChannelType.GUILD_TEXT,
ChannelType.DM,
ChannelType.GUILD_NEWS
// etc etc
```

### Other context

While using the .addChannelOption() function, it would help a lot in clearly specifying the channel type in .addChannelType()

Also the website docs will benefit as well.

**Comment by vladfrangu** [comment]
There already is that enum, both in -types and re-exported in discord.js 👀

**Comment by MRDGH2821** [comment]
For the website:
There are no hyper links or reference to DAPI which got me confused. There can be some "subtitle" text underneath to mention DAPI link.

like - `See more at https://discord.com/developers/docs/resources/channel#channel-object-channel-types`

For the DJS module or builders module:
How to actually use it? 
VS Code Intellisense is not able to pickup anything 🤔
