### ISSUE TITLE
Add MessageActionRow and MessageButton to index.d.ts please

### ISSUE THREAD

**Issue by Mimexe** [discordjs/discord.js#7435]
### Which package is the feature request for?

discord.js

### Feature

Adding MessageActionRow and MessageButton to index.d.ts else VSCode don't reconize.

### Ideal solution or implementation

VSCode propose Tab Completion

**Comment by BenjammingKirby** [comment]
what are you talking about? we don't have MessageButton anymore, we reexport ButtonComponent from builders now
