### ISSUE TITLE
Main branch is not installable

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#7443]
### Which package is this bug report for?

discord.js

### Issue description

After that commit https://github.com/discordjs/discord.js/commit/37c1cb4495bbfe0581602fe84fc97b03ebc0270a that use `workspace:^` as subpackages version, the discord.js dep is not installable anymore with npm.

```
➜  DraftBot git:(upgrade-discord.js) ✗ npm install 'https://gitpkg.now.sh/discordjs/discord.js/packages/discord.js?fe11ff5f6e85571a981e90eba5b9f3bda7a2cd04'
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/draftman/.npm/_logs/2022-02-10T12_55_28_216Z-debug.log
```

### How to reproduce :
1. Go to https://gitpkg.vercel.app/
2. Paste subdir commit path, for this example I used last commit: https://github.com/discordjs/discord.js/commit/fe11ff5f6e85571a981e90eba5b9f3bda7a2cd04 `https://github.com/discordjs/discord.js/tree/fe11ff5f6e85571a981e90eba5b9f3bda7a2cd04/packages/discord.js`
3. Copy the install cmd from npm
![image](https://user-images.githubusercontent.com/29425008/153413050-152ea5c6-6372-4b58-9910-d1eec34c4661.png)
4. Run the command: 
```sh
npm install 'https://gitpkg.now.sh/discordjs/discord.js/packages/discord.js?fe11ff5f6e85571a981e90eba5b9f3bda7a2cd04'
```

### Package version

main

### Node.js version

Node.js version v16.13.2

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### I have tested this issue on a development release

fe11ff5f6e85571a981e90eba5b9f3bda7a2cd04

**Comment by BenjammingKirby** [comment]
go to the root folder, then run `yarn build` first

**Comment by kyranet** [comment]
Just use the dev releases on npm, which you can install with `npm i discord.js@dev`. I don't get why the need to install specifically the main branch.

**Comment by DraftProducts** [comment]
I used the main branch to reproduce the bug installation, in my case i try to install the forked repo, do you have some tips for that 
@kyranet ?
