### ISSUE TITLE
No reconnect on session timeout error code [4009] and WebSocket readyState stuck at CLOSING

### ISSUE THREAD

**Issue by legendhimslef** [discordjs/discord.js#7450]
### Which package is this bug report for?

discord.js

### Issue description

It happened with the same shard twice, It never happened on DJs 13.5.0. Now I am on 13.6.0, Even after falling back to the older version it still won't reconnect if the shard has a zombie connection. I guess it should reconnect?

![image](https://user-images.githubusercontent.com/69213593/153708425-76f1492b-1ef9-4e1c-b6d5-a4c6c3856180.png)

### Package version

13.6.0

### Node.js version

16.6.1

### Operating system

Ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildEmojisAndStickers, GuildWebhooks, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by JMTK** [comment]
Possibly related to #4095

**Comment by legendhimslef** [comment]
> Possibly related to #4095

No...! The bot used to have 2 weeks of uptime. I don't know what is going wrong here. It just fails to resume the session or it doesn't even try to reconnect forget about the reconnect spam

**Comment by legendhimslef** [comment]
Can an event emitter leak cause the shard to timeout?
#7240 
When the bot had 2 weeks of uptime, I manually added my pr changes to the `node_modules` but the current version of the DJs doesn't have my event emitter leak fix

**Comment by legendhimslef** [comment]
> Your PR #7240 actually fixed the bot crash that i used to encounter on daily basis. 
> also using djs 13.6.0
> 
> Thanks for the fix @legendhimslef 

Np :)
and Yes, I have implemented the changes locally. Wrote a script that changes these files in `node_modules/discord.js/src/sharding/` since we cannot install this specific pr through any of the dev packages available. I got weeks of uptime.
Also I have requested @iCrawl to roll out my pr

**Comment by legendhimslef** [comment]
![image](https://user-images.githubusercontent.com/69213593/155990712-1b620ff2-2032-4792-9221-712d660cf637.png)
I have been trying to debug the WebSockets codes of discord.js and I found out few bugs.
1) here https://github.com/discordjs/discord.js/blob/stable/src/client/websocket/WebSocketShard.js#L741 we make `this.connection` to null without checking if the onClose event was ever emitted.

2) `onClose` is never emitted when the shard randomly hits the 4009 code. But when I try to recreate the zombie connection [4009] it reconnects without a sweat. Seems like there is something which is blocking the WebSocket to close properly and being stuck at ar CLOSING `readyState` and as we made `this. connection` to null, now there isn't a way to recheck if it ever closed. [this.connection.readyState]

3) I tried making `this.connection` to null in the `onClose` method, ie I moved from steps 2 - 4 to that onClose method. But the problem is it never emits the close event which would never invoke onClose method.
 @kyranet @vladfrangu @iCrawl @ckohen

**Comment by legendhimslef** [comment]
```js
if (closeCode === 4009) {
      setInterval(() => {
        this.debug(`WS State [Interval 5s]: ${CONNECTION_STATE[this.connection?.readyState]}`);
      }, 5000);
    }
 ```
 
I added this piece of code in destroy method to check if readyStates changes to `CLOSE` and it indefinitely stuck at `CLOSING`
I also added `handshakeTimeout` of 30s which according to an issue from websocket library should fix the connection being stuck at `CLOSING` but sadly it doesn't work for me. If I make the timeout to 10ms it does emit close [https://github.com/websockets/ws/blob/master/lib/websocket.js#L1021](url) and reconnects. But when I put it to production and then when it randomly hits 4009 it doesn't timeout, seems its was bug ??

**Comment by legendhimslef** [comment]
![image](https://user-images.githubusercontent.com/69213593/156081172-af215228-f1cc-4216-a90d-826848179cfa.png)
Made some changes to the `WebSocketShard.js` file and it works fine.. I'll make a pr tomorrow.
