### ISSUE TITLE
Wrong source link in stable Collection docs

### ISSUE THREAD

**Issue by Rapougnac** [discordjs/discord.js#7463]
### Which package is this bug report for?

collection

### Issue description

1. Go to <https://discord.js.org/#/docs/collection/stable/class/Collection>
2. Click on the "View Source" button at the top right corner
3. It'll redirect you on <https://github.com/discordjs/discord.js/blob/stable/src/index.ts#L25> instead of <https://github.com/discordjs/discord.js/blob/main/packages/collection/src/index.ts>.

This is likely caused by #7175 as it mess up the stable documentation.

### Package version

13.3.1

### Node.js version

16.13.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by iCrawl** [comment]
Known and already fixed in development.
