### ISSUE TITLE
publish dev ci is failing

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/discord.js#7467]
### Which package is this bug report for?

discord.js

### Issue description

https://github.com/discordjs/discord.js/actions/runs/1844184728

```
> Run yarn workspace discord.js version $(jq --raw-output '.version' packages/discord.js/package.json).$(date +%s).$(git rev-parse --short HEAD)
Usage Error: Invalid value for enumeration: "14.0.0-dev.1644883563.0034396" (expected one of "decline", "major", "minor", "patch", "prerelease")
```

### Package version

dev

### Node.js version

n/a

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by monospacedmagic** [comment]
For what it's worth I've seen other projects follow the second approach. Feels like it's the most convenient and least complicated approach. I'm a fan :)

**Comment by KhafraDev** [comment]
CI is passing once again but since the underlying issue hasn't been fixed I will keep this open
