### ISSUE TITLE
Footer not showing

### ISSUE THREAD

**Issue by Clauz07** [discordjs/discord.js#7469]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce:
Log in with your bot
Create any embed by manually building the object
Include a footer in the embed
Send the embed
Footer is not showing (it shows in v13)

### Code sample

```typescript
import * as Discord from 'discord.js'

const intents = [
Discord.GatewayIntentBits.Guilds,
Discord.GatewayIntentBits.GuildMessages,
]

const client = new Discord.Client({ intents: intents })

client.on('messageCreate', message => {
   if (message.content == '!embed') {
    const embed = {
    title: 'Some title',
    description: 'Some Description',
    footer: {
    text: 'Some text',
    icon_url: message.author.displayAvatarURL()
    }
}
   message.channel.send({embeds: [e]})
}    
})

client.login('token')
```

### Package version

discord.js@14.0.0-dev.1644797187.0dfdb2c

### Node.js version

17.4.0

### Operating system

Debian

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

### I have tested this issue on a development release

discord.js@14.0.0-dev.1644797187.0dfdb2c

**Comment by monbrey** [comment]
This will be fixed by #7464

**Comment by Clauz07** [comment]
Uhm sorry but using discord.js@14.0.0-dev.1645012998.7959a68 the issue is still occuring, is this normal?

**Comment by Jiralite** [comment]
That version does not have the fix. So yes, that is normal.

**Comment by Clauz07** [comment]
oh, so how do I install the fix from npm?

**Comment by ImRodry** [comment]
> oh, so how do I install the fix from npm?

Wait for the next release in about 5 and a half hours
