### ISSUE TITLE
Error code 50035

### ISSUE THREAD

**Issue by wioniqle-q** [discordjs/discord.js#7473]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://user-images.githubusercontent.com/69215407/154235753-2c187460-d2e6-44f6-9a29-7a464157cf7e.png)

### Code sample

```typescript
const member = await this.client.users.fetch("some value");
```

### Package version

13.6.0

### Node.js version

16

### Operating system

Web  service something like replit/heroku/glitch

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageMentions, DirectMessageTyping, GuildScheduledEvents

**Comment by SpaceEEC** [comment]
This is working as intented; the provided value is not a [`UserResolvable`](https://discord.js.org/#/docs/discord.js/stable/typedef/UserResolvable).
