### ISSUE TITLE
Message.delete(5000) deletes message instantly

### ISSUE THREAD

**Issue by andreasdc** [discordjs/discord.js#7483]
### Which package is this bug report for?

discord.js

### Issue description

As in the title

### Package version

-

### Node.js version

-

### Operating system

linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by monbrey** [comment]
`Message#delete` has not had a built in timeout since v12 and timers must be handled manually.

**Comment by andreasdc** [comment]
That explains a lot
