### ISSUE TITLE
[dev] Transformers.toSnakeCase method converts undefined values into empty objects.

### ISSUE THREAD

**Issue by IRONM00N** [discordjs/discord.js#7510]
### Which package is this bug report for?

discord.js

### Issue description

The Transformers.toSnakeCase method converts undefined values into empty objects.

### Code sample

```typescript
import {Options} from 'discord.js';

console.dir(Options.createDefault().jsonTransformer({snakeCaseKey:undefined}))
```

### Package version

@dev

### Node.js version

node v17.2.0

### Operating system

arch linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageMentions, DirectMessageTyping, GuildScheduledEvents

**Comment by almeidx** [comment]
Fixed by #7497
