### ISSUE TITLE
accentColor on force fetched User is still sometimes null

### ISSUE THREAD

**Issue by Larsundso** [discordjs/discord.js#7530]
### Which package is this bug report for?

discord.js

### Issue description

1. Force fetch a few Users
2. Some have accentColor `null`

(Side note:
in the Bug Report sheet, the option "Which gateway intents are you subscribing to?" includes a list of Gateway intents, one of these is titled `DirectMessageMentions`, this intent doesn't exist, `DirectMessageReactions` is missing, I think someone did a typo)

### Code sample

```typescript
const Discord = require("discord.js");

const client = new Discord.Client({
  shards: "auto",
  partials: ["MESSAGE", "REACTION", "CHANNEL", "USER", "GUILD_MEMBER"],
  intents: new Discord.Intents(14335),
});

client.login("TOKEN");

client.on("ready", async () => {
  console.log(await client.users.fetch(client.user.id, { force: true }));
});
```

### Package version

discord.js@13.6.0

### Node.js version

v17.5.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageMentions

### I have tested this issue on a development release

78aa36f

**Comment by Jiralite** [comment]
> Some have accentColor `null`

I'm assuming that isn't your desired output. Your reproducible code sample is expected to be `null` - do you have a user id where you are expecting a not-`null` response so we can test without discord.js to see if the value returned is correctly parsed by discord.js?

**Comment by Smidul** [comment]
Yea, if the user itself didn't set an accent color, the value will be null.

**Comment by Larsundso** [comment]
You're right, I sent an HTTP request to discord on a user who didn't have their Accent Color manually set and it doesn't even return the generated one. Which is quite sad...
Thanks and sorry in advance
