### ISSUE TITLE
Add .tag property to Api User.

### ISSUE THREAD

**Issue by Wiper-R** [discordjs/discord.js#7540]
### Which package is the feature request for?

discord.js

### Feature

I was using interaction commands with typescript and I have to do `(interaction.member?.user as User).tag` everytime. Which feels quite redundant.

### Ideal solution or implementation

I was using interaction commands with typescript and I have to do `(interaction.member?.user as User).tag` everytime. Which feels quite redundant.

**Comment by imranbarbhuiya** [comment]
Use `interaction.user` or 1st use typeguerd `interaction.inCachedGuild()` then use `interaction.member.user.tag`. It's bc interaction member can be a `GuildMember` or `APIGuildMember`

**Comment by monbrey** [comment]
The reason `tag` doesn't exist on APIUser is because it isn't a property, it's a getter method on the User class.

```js
get tag() {
  return typeof this.username === 'string' ? `${this.username}#${this.discriminator}` : null;
}```

APIUser on the other hand is not a class, just a type definition for a raw object. It doesn't support getters.

**Comment by almostSouji** [comment]
APIUser should reflect raw API data <https://discord.com/developers/docs/resources/user#user-object>
