### ISSUE TITLE
Promise call then and catch function with GuildMemberManager.unban()

### ISSUE THREAD

**Issue by StanByes** [discordjs/discord.js#7564]
### Which package is this bug report for?

discord.js

### Issue description

Hello, I make an unban command. 

But I have a problem with the Promise in the GuildMemberManager.unban() function. 
In a firt time I did : GuildMemberManager.unban(ID) with a then/catch and the Promise called the good function.

After, I modified the function to add a reason of unban, so I did : unban(ID, reason) and it's the source of the problem. When I add the reason in the params, the then response is call but the catch too.

### Code sample

```typescript
message.guild.members.unban(args[0], args.slice(1, args.length).join(" "))
            .then(() => {
                console.log("Unban");
            })
            .catch(() => {
                console.log("Error");
            })
```

### Package version

13

### Node.js version

16.7.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildMessages

**Comment by Jiralite** [comment]
What is the error?

**Comment by StanByes** [comment]
Sorry, I saw my error. With console.log the Promise calls the both function, but when I added code in then function, the catch was not call.
