### ISSUE TITLE
Adding shockwave option

### ISSUE THREAD

**Issue by Ciross** [discordjs/discord.js#7567]
### Which package is the feature request for?

discord.js

### Feature

It would be good if bot was able to make a shockwave at certain moment (I'm talking about the shockwave you have when you are trying to speak in a colldown channel, or try sending a slash command without required options filled).

### Ideal solution or implementation

Something like user.screenShock({ time: TIME_IN_MS }) (or without time) to make a shockwave on the screen of the user.

**Comment by almeidx** [comment]
Not something that discord.js can provide as it's not available through the API
