### ISSUE TITLE
My bot is executing guildDelete event of undefined server everytime it's logged in

### ISSUE THREAD

**Issue by pranshu05** [discordjs/discord.js#7571]
### Which package is this bug report for?

discord.js

### Issue description

Whenever my bot becomes online it executes guildDelete event

### Code sample

```typescript
client.on('guildDelete' , guild => {
    const embed = new MessageEmbed()
    .setColor("00FFFF")
    .setTitle("Guild Left")
    .setDescription(`Elpha has left the server ${guild.name}`)
    .addField('Members:' , `${guild.memberCount}`)
    .addField("Guild owner:", `> <@${guild.ownerId}> \`[${guild.ownerId}]\``)
    .addField('Total servers:', `${client.guilds.cache.size}`)
    .setThumbnail(guild.iconURL())
    .setTimestamp()
		client.channels.cache.get("919799899929841694").send(
				{
					 embeds: [embed]
			})	
})
```

### Package version

13.3.1

### Node.js version

17.3.1

### Operating system

Windows (win32 10.0.19043)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by BenjammingKirby** [comment]
iirc this was a bug that was already fixed, update djs 
and if that doesn't work, check if `client.isReady()`, if it's not, return
but i doubt it's still an issue

**Comment by sarcasternub** [comment]
same issue for me. like the bot shows everything undefined even if I removed it from my test server which consists of 35 members

**Comment by imranbarbhuiya** [comment]
> same issue for me. like the bot shows everything undefined even if I removed it from my test server which consists of 35 members

Can you check the `guild.available` property is true or false? @pranshu05

**Comment by sarcasternub** [comment]
> > same issue for me. like the bot shows everything undefined even if I removed it from my test server which consists of 35 members
> 
> Can you check the `guild.available` property is true or false? @pranshu05

Thanks a lot for the help, I just found out why does it happen. Like when a server is deleted there's no information about the server that can be fetched through any of the method. But, I just have a doubt that why does it emit `guildDelete` event for that deleted guild? Is it a djs bug

**Comment by ThunderBlox** [comment]
That's happening to me since today morning, Not sure what could be the reason.

**Comment by pranshu05** [comment]
> > same issue for me. like the bot shows everything undefined even if I removed it from my test server which consists of 35 members
> 
> Can you check the `guild.available` property is true or false? @pranshu05

Thanks....it worked!
