### ISSUE TITLE
guild.fetchOwner() is returning a collection of guild members

### ISSUE THREAD

**Issue by ajmas** [discordjs/discord.js#7574]
### Which package is this bug report for?

discord.js

### Issue description

Using Discord 13.6.0 I am trying to get the id of the guild, is not working for me.

Trying `guild.ownerId` returns undefined, but I was then directed to try `guild.fetchOwner()`, but this returns a list of members of the guild instead of a `GuildMember`.

Looking at the Discord source code suggests that if `guild.ownerId` is undefined, this will return all the members of the guild:

``js
fetchOwner(options) {
    return this.members.fetch({ ...options, user: this.ownerId });
}
```


### Code sample

```typescript
To get the guild:


  async getGuild (guildId?: string) {
    const client = await this.getClient();
    const guildResolvable = client.guilds.resolveId(guildId || this.guildId);

    const guild = client.guilds.resolve(guildResolvable);
    if (!guild) {
      throw new Error('Unable to access guild');
    }
    return guild;
  }


This returns a guild with `ownerId` being `undefined, but then calling `guild.fetchOwner()` returns a collection of form `Collection(11) [Map] { ... }`.
```

### Package version

13.6.0

### Node.js version

16.6.0

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers, GuildMessages

**Comment by Jiralite** [comment]
It seems you didn't specify the `GUILDS` intent though. Shouldn't you, if you wanting information from guilds?

**Comment by ajmas** [comment]
Yes, I just noticed through extra experimenting, though it wasn't clear from the documentation:

https://discord.js.org/#/docs/discord.js/stable/class/Guild?scrollTo=fetchOwner

Also, would be possible to have code provide clarity on this, such as:

```js
fetchOwner(options) {
    if (!this.ownerId) {
       throw new MissingIntent('GUILDS intent is required to use this');
    }
    return this.members.fetch({ ...options, user: this.ownerId });
}
```

Though, not sure if that fits with the API's philosophy?

**Comment by ajmas** [comment]
@ImRodry can you explain why you disagree with the suggestion?

**Comment by ImRodry** [comment]
Because the intents required to do X, Y or Z are managed by Discord themselves, not the library, so it would be hard to document and provide errors for every method and intent. Same reason why we don’t document API defaults, stuff can change at any time. Not only that but you need GUILDS for pretty much everything so unexpected behavior is bound to happen when you don’t provide that intent. Also CNR with the correct intents, and this also seems like odd behavior even if you didn’t have them

**Comment by ajmas** [comment]
Fair enough. This wasn't impacting me until I upgraded to DJS 13, hence assuming it was at the API level.

I'll close the ticket. Thanks

**Comment by monbrey** [comment]
Although I don't agree with this particular error message, I do think this method should reject if `guild.ownerId` isn't defined. It's designed to fetch a single GuildMember. If it cannot do so, it should reject.

The current behaviour where in an edge case it can return a Collection of GuildMembers is not the expected result and should be considered a bug.
