### ISSUE TITLE
Argument of type '"stateChange"' is not assignable to parameter of type 'VoiceConnectionStatus.Signalling'

### ISSUE THREAD

**Issue by kaaax0815** [discordjs/discord.js#7594]
### Which package is this bug report for?

voice

### Issue description

1. Copy this repo: https://github.com/kaaaxcreators/Discord-MusicBot/tree/develop
2. Then try to build it
3. Typescript Error: `Argument of type '"stateChange"' is not assignable to parameter of type 'VoiceConnectionStatus.Signalling'` here: https://github.com/kaaaxcreators/Discord-MusicBot/blob/f86381c6988348ca32d55ff1e383caf179d2e387/src/util/Music.ts#L61 and here https://github.com/kaaaxcreators/Discord-MusicBot/blob/f86381c6988348ca32d55ff1e383caf179d2e387/src/util/Music.ts#L122

### Code sample

```typescript
https://github.com/kaaaxcreators/Discord-MusicBot/blob/develop/src/util/Music.ts
(Its the discord/voice Music Bot example fitted to my needs)
```

### Package version

0.8.0

### Node.js version

16.13.2, 4.6.2

### Operating system

Windows 10 21H1

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildEmojisAndStickers, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions

**Comment by Zhincore** [comment]
I have similar issue
![Argument of type '"stateChange"' is not assignable to parameter of type 'AudioPlayerStatus.Idle'.](https://gcdnb.pbrd.co/images/Q7VlRJ3Pr17M.png?o=1)

The following snippet has the problem:
```ts
player.on("stateChange", (oldState, state) => {
  /*...*/
});
```

But this one doesn't throw any error:
```ts
player.on("stateChange", () => {
  /*...*/
});
```

The workaround is following:
``ts
player.on<"stateChange">("stateChange", (oldState, newState) => {
  /*...*/
});
```

I assume the parameters somehow infer different type than "stateChange".

**Comment by JMTK** [comment]
I believe it originates from upgrading to Typescript 4.6

**Comment by CatsMiaow** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/1300172/158315633-bdcc233d-ac8d-4ed8-996d-c9c4b2057609.png">
Yes I have this problem with TypeScript v4.6. v4.5 is fine.

**Comment by Crawron** [comment]
Happens to me as well. Issue seems to be on the second half of `AudioPlayerEvents` and `VoiceConnectionEvents`.

```ts
} & {
    [status in VoiceConnectionStatus]: (oldState: VoiceConnectionState, newState: VoiceConnectionState & {
        status: status;
    }) => Awaited<void>;
};
```

Changing the line `status: status;` on both `AudioPlayerEvents` and `VoiceConnectionEvents` to be a conditional type like below fixes the issue, as far as I can tell.

```ts
} & {
    [status in VoiceConnectionStatus]: (oldState: VoiceConnectionState, newState: VoiceConnectionState & {
        status: status extends VoiceConnectionStatus ? status : VoiceConnectionStatus;
    }) => Awaited<void>;
};
```

Should I PR this change?

**Comment by suneettipirneni** [comment]
Just a followup, does this still fail on typescript 4.7?
