### ISSUE TITLE
CommandInteractionOptionResolver does not behave as expected when given an AutocompleteInteraction

### ISSUE THREAD

**Issue by MidSpike** [discordjs/discord.js#7595]
### Which package is this bug report for?

discord.js

### Issue description

Are there any plans to fix (*improve*) the undocumented pitfalls of autocomplete interactions?

- `CommandInteractionOptionResolver.resolved` <https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/structures/CommandInteractionOptionResolver.js#L59-L65> should be marked as nullable (per discord docs <https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure> , see `resolved`)

- Assuming the following internal state in d.js:
  ```js
  [
    { name: 'for', type: 'USER', value: '163646957783482370' },
    { name: 'action', type: 'STRING', value: 'add' },
    { name: 'product_code', type: 'STRING', value: '', focused: true }
  ]
  ```
  Fetching an option using `getUser` on an autocomplete interaction does not behave as expected.
  ```js
  autocompleteInteraction.options.getString('action') // output: 'add'; behaves as expected
  autocompleteInteraction.options.get('for').type === 'USER' // output: true; behaves as expected
  autocompleteInteraction.options.get('for').value // output: '163646957783482370'; behaves as expected
  autocompleteInteraction.options.get('for').user // output: undefined; begin head scratching
  autocompleteInteraction.options.getUser('for') // output: null; does not behave as expected since 'user' is missing from the object, this is caused by `data.data.resolved` not existing in the response send by Discord for autocomplete interactions
  ```
  Although the `USER` type is present, `getUser` does not return the expected output b/c it it missing the resolved `user` field.
(this should really be documented, I had to look at d.js source to find out why it was returning `null`)
<https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/structures/CommandInteractionOptionResolver.js#L185-L194>
  I had assumed that d.js would resolve the user id into a user under the hood when `resolved` was not present.

A lot of the head scratchers here could be resolved (pun intended) by updating the documentation or by attempting to resolve the resolvable items when discord fails to send `data.data.resolved`.

### Package version

discord.js@13.6.0

### Node.js version

v16.13.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by EvolutionX-10** [comment]
I have faced the same issue recently
Easily reproducible by having an autocomplete string option after an option of `USER` type
CommandInteractionOptionResolver#getUser and CommandInteractionOptionResolver#getMember returns `null`

**Comment by monbrey** [comment]
I was discussing this internally the other day and meant to do a write-up before now, thanks for this.

Discord, as far as I know, never sends the resolved data for the other options on an autocomplete interaction. Resolving users ourselves probably wouldn't be very reliable either - someone using the slash command can pick anyone in the guild, and there's a pretty good chance they won't be in your bots cache. In that scenario it would still result in a null anyway.

I think the best options is to fix the docs and typings so that getUser doesn't exist on AutocompleteInteractions. As a developer, the better approach is to `.get('user')?.value` and fetch as required.
