### ISSUE TITLE
GatewayIntentBits not exported. Basic example from README.md not working

### ISSUE THREAD

**Issue by matthewoates** [discordjs/discord.js#7601]
### Which package is this bug report for?

discord.js

### Issue description

See below for clear repro steps. `GatewayIntentBits` isn't exported in the way that the `README` expects. I'm just trying to get my app working again after upgrading versions.

### Code sample

```typescript
/tmp/discord-bug ────────────────────────────────────────────────────────────────────────── ⬢ 16.14.0
❯ npm install discord.js

added 24 packages, and audited 25 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

/tmp/discord-bug ─────────────────────────────────────────────────────────────────────── 3s ⬢ 16.14.0
❯ node
Welcome to Node.js v16.14.0.
Type ".help" for more information.
> const { Client, GatewayIntentBits } = require('discord.js');
undefined
> GatewayIntentBits
undefined
> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 

/tmp/discord-bug ────────────────────────────────────────────────────────────────────── 17s ⬢ 16.14.0
❯ cat node_modules/discord.js/package.json | grep version
  "version": "13.6.0",
```

### Package version

13.6.0

### Node.js version

v16.14.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by BenjammingKirby** [comment]
`npm install discord.js` is installing version 13.6?
the example you're looking at is for v14 probably (currently in development)

**Comment by matthewoates** [comment]
Yep, just noticed that I should've looked at the readme for the v13 tag. It's rare that I need to do that so I didn't think of it earlier.

**Comment by GabiGrin** [comment]
+1 on this being unintuitive. The example is given right after a regular install command. Would expect either suggesting installing 14 from the README + linking to the 13 version, or the other way around.
I'd love to open a PR for that if the team is interested
