### ISSUE TITLE
Hide application commands [feature request]

### ISSUE THREAD

**Issue by AlexandrosGounis** [discordjs/discord.js#7609]
### Which package is the feature request for?

discord.js

### Feature

It is currently possible to disable application commands, given a role, or a user scope.

However, this only dims down and freezes the options, but the users are still able to see the commands listed.

### Ideal solution or implementation

As admin-only commands are really useful, would it be possible to completely hide (remove from the slash list) some commands from the users and make them available to admins, (in the same Discord server)?

**Comment by almostSouji** [comment]
You should really re-read the answer given in the discussion.

**Comment by AlexandrosGounis** [comment]
> You should really re-read the answer given in the discussion [here](https://github.com/discordjs/discord.js/discussions/7603#discussioncomment-2301258).

Thanks @almostSouji, I opened this issue one minute after this comment was posted, I was in the process of writing it up.
This is not a suggestion, though, it is a feature request and that is why I filed it here. Feel free to close this issue if you think the Discord team is aware of it

**Comment by almostSouji** [comment]
We are not Discord. We are Discord.js, an API wrapper. We can just implement features Discord has (though this one is an UI improvement we have to implement nothing for. This is all on Discord updating their client).

**Comment by AlexandrosGounis** [comment]
Interesting, I honestly thought that DiscordJs was part of the official Discord team, that compliments your work.
My apologies, @almostSouji
