### ISSUE TITLE
Server error while sending message in channel

### ISSUE THREAD

**Issue by MegaNoam** [discordjs/discord.js#7639]
### Which package is this bug report for?

discord.js

### Issue description

When you try to send a message in a Text Channel, you get an error through the Discord.js system
Attached is a log of the system at runtime until it crashes:

```
DiscordService     | /app/node_modules/discord.js/src/rest/RequestHandler.js:357
DiscordService     |         throw new HTTPError(res.statusText, res.constructor.name, res.status, request);
DiscordService     |               ^
DiscordService     |
DiscordService     | Response: Bad Gateway
DiscordService     |     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:357:15)
DiscordService     |     at runMicrotasks (<anonymous>)
DiscordService     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
DiscordService     |     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
DiscordService     |     at async TextChannel.send (/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15) {
DiscordService     |   code: 502,
DiscordService     |   method: 'post',
DiscordService     |   path: '/channels/%CENSORED_CHANNEL_ID%/messages',
DiscordService     |   requestData: {
DiscordService     |     json: {
DiscordService     |       content: '[DEBUG] MegaNoam#4555 → Test!',
DiscordService     |       tts: false,
DiscordService     |       nonce: undefined,
DiscordService     |       embeds: undefined,
DiscordService     |       components: undefined,
DiscordService     |       username: undefined,
DiscordService     |       avatar_url: undefined,
DiscordService     |       allowed_mentions: undefined,
DiscordService     |       flags: undefined,
DiscordService     |       message_reference: undefined,
DiscordService     |       attachments: undefined,
DiscordService     |       sticker_ids: undefined
DiscordService     |     },
DiscordService     |     files: []
DiscordService     |   }
DiscordService     | }
```

### Code sample

```typescript
module.exports = {
  sendMessage: function sendMessage(channel, message, _prefix = "[DEBUG]") {
    channel.send(`${_prefix} ${message}`);
    console.log(`${_prefix} ${message}`);
  },
};
```

### Package version

"discord.js": "13.6.0"

### Node.js version

v16.14.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates

**Comment by Jiralite** [comment]
This error isn't from discord.js. It's from Discord. It's not our issue.

**Comment by MegaNoam** [comment]
@Jiralite 

I can't ``.catch`` this problem if there is an error on the server side, Even if I put it into my own promise
It's your responsibility for this problem, I can't talk about it with Discord

**Comment by almostSouji** [comment]
I think you should research how errors and promise rejections bubble through the call stack. You need to handle the promise rejection gracefully, we reject the `TextChannel#send` call if we encounter an error response from the API (Promise rejections are by definition supposed to happen when the expected outcome (Message instance for the message you just sent) cannot be achieved). It is indeed your responsibility to handle the Promise rejection gracefully and not let it crash your entire app.

The best practice, in this case, would probably be to return the Promise from the `sendMessage` function, to handle it in calling scopes, and inform the user if the action was not successful, while also logging the error to your logging system of choice so you can look into it, should you need to (Other examples for promise rejections could, for example, be missing permissions, which you can prevent as a developer before the API call is made by checking for the appropriate permissions).

In select cases the message "informing the user" might also reject, which should still be handled gracefully, of course.

**Comment by MegaNoam** [comment]
@almostSouji 

Can you give an example please? What you are writing to me here sounds very vague
I used Promise and also tried to catch the error with catch (which of course as I wrote above does not work that I test it)
