### ISSUE TITLE
Mut

### ISSUE THREAD

**Issue by Edouard127** [discordjs/discord.js#7648]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce:

1. Create a slash command with the following code (Code 1)
2. Try to register the slash command
3. See this error: `Unhandled Rejection: S[50035]: Invalid Form Body
options[1][APPLICATION_COMMAND_OPTIONS_TYPE_INVALID]: Sub-command and sub-command group option types are mutually exclusive to all other types`

4. Use the second code (Code 2), and there is no errors

### Code sample

```typescript
Code 1:
        name: 'command',
	description: 'I am a command description',
	options: [
	{
	    name: 'value',
	    description: 'I am the value description',
	    type: 4,
	    required: false,
	},
        {
            name: 'summary',
            description: 'summary',
            type: 1,
            required: false,
        },
],




Code 2:


	options: [
        {
            name: 'summary',
            description: 'summary',
            type: 1,
            required: false,
        },
	{
	    name: 'value',
	    description: 'I am the value description',
	    type: 4,
	    required: false,
        },
```

### Package version

13.6.0

### Node.js version

16.13.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildInvites, GuildVoiceStates, GuildMessages

### I have tested this issue on a development release

dcd4797

**Comment by ImRodry** [comment]
The error says it all. You can't mix a sub command group with other kinds of options. This isn't a bug with the library
