### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by CeCeloz** [discordjs/discord.js#7655]
### Which package is the feature request for?

discord.js

### Feature

Being able to use clipboard inside Discord with a button
![image](https://user-images.githubusercontent.com/60020692/158087568-6e1fe3d4-9dc8-4068-b618-65bc12752ab6.png)

### Ideal solution or implementation

Then to discord i suggest provide an api to copy string, this would help a lot in the question of the user copying some kind of website from some server service

**Comment by Jiralite** [comment]
> I believe discord should provide an api to copy string

Then to Discord you suggest! (We are not Discord.)
