### ISSUE TITLE
Create `@discordjs/collector` package

### ISSUE THREAD

**Issue by Syjalo** [discordjs/discord.js#7659]
### Which package is the feature request for?

discord.js

### Feature

Create `@discordjs/collector` package, so that it can be used outside discord.js. That's very useful thing like `@discordjs/collection` and I would like to use it in my project in future.

### Ideal solution or implementation

Move `Collector` class from structures interfaces to its own package.

**Comment by MoonLGH** [comment]
are you looking for https://nodejs.org/api/events.html#class-eventemitter ?

**Comment by kyranet** [comment]
Specifically [`events.on`](https://nodejs.org/api/events.html#eventsonemitter-eventname-options) and [`events.once`](https://nodejs.org/api/events.html#eventsonceemitter-name-options).

Discord.js's collectors attach a lot of listeners for a variety of events, making each one of them completely specific for them, and not just one, so it's a bit useless to use them outside Discord.js as this requires a high coupling with the event emitter.

If you need something more complex, there's also [`@sapphire/event-iterator`](https://www.npmjs.com/package/@sapphire/event-iterator), which is `on` but more powerful.
