### ISSUE TITLE
Client error event

### ISSUE THREAD

**Issue by TechnoPhysics** [discordjs/discord.js#7663]
### Which package is the feature request for?

discord.js

### Feature

It is always frustrating when the bot crashes due to random errors and loses important data. Implementing a new event called `error` might help us fix this problem.

### Ideal solution or implementation

All errors should be emitted through the event

```js
const { Client, Intents } = require('discord.js');
const client = new Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('error', (error) => {
  throw error;
});

client.login('token');
```
### Alternative solutions or implementations

If this feature cannot be implemented, I recommend that errors should be logged and not thrown so the process doesn't exist

**Comment by imranbarbhuiya** [comment]
Client already have a event called error.

https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-error

Also for you can add listener to process events like `UnhandledRejection` to avoid crashing

**Comment by almostSouji** [comment]
Catching and aggregating errors is not something an API wrapper like discord.js should be doing. The "error" event already exists on Client <https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-error> and emits when the websocket connection encounters issues.

- Syntax and usage errors should be handled by your process management.
- Handling promise rejections (for example encountered on discord API errors) gracefully is on you and should ideally (if possible) also inform the user that their command did not resolve successfully.
- Process events like `"unhandledRejection"` can be used for quick debugging; using them as a production solution for any and all rejections is not something I'd personally recommend *(see above note about informing the user and graceful handling on a per-case basis)*.
