### ISSUE TITLE
It is not possible to output anything to the console using sharding

### ISSUE THREAD

**Issue by JoaoZanetti** [discordjs/discord.js#7664]
### Which package is this bug report for?

discord.js

### Issue description

Output to the console stopped working if using sharding. For example, if I try to write console.log('test') on shard 0, the console will remain empty. but if I do the same on the ShardingManager process, 'test' will appear in the console. the shards are launched and worked correctly.

#4703 

### Code sample

```typescript
//index.js
const { ShardingManager } = require('discord.js');
const manager = new ShardingManager('./bot.js', { token: 'yourtoken', respawn: true });

manager.on('shardCreate', shard => {
	console.log(`Launched shard ${shard.id}`);
});
manager.spawn();

// bot.js
const { Client } = require('discord.js')
const client = new Client()

console.log('some log...')

client.on('ready', () => console.log(`shard ready!`) )
client.login('token')
```

### Package version

"@discordjs/builders": "^0.12.0", "@discordjs/rest": "^0.3.0", "discord-api-types": "^0.29.0", "discord.js": "^13.6.0"

### Node.js version

v16.13.2

### Operating system

MacOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by JoaoZanetti** [comment]
#4703

**Comment by almeidx** [comment]
Cannot reproduce this in either 13.6.0, 13.11.0, or 14.5.0
