### ISSUE TITLE
[Idea] Member properties

### ISSUE THREAD

**Issue by DemonWayne** [discordjs/discord.js#7677]
### Which package is the feature request for?

discord.js

### Feature

I want to get 2 things for different purposes.

The first one is the total number of member messages for statistics, because to write information to the database that can be obtained in the usual way. Add to GuildMember propertie **messageCount**.

Second - Add the ability to **fetch member messages** on the server via propertie messages as in textChannel.
Fetching messages in all channels and getting their size is very tedious, given the maximum limit of 100 messages

### Ideal solution or implementation

Add 2 propereties to guildMember:
messageCount - The full amount of messages from member, Type: number 
messages - A manager of the messages sent from member, Type: MessageManager

**Comment by kyranet** [comment]
We're not Discord, discord.js is merely a wrapper around Discord's API, we support what they give us.

To suggest new ideas for Discord's API, suggest them at https://github.com/discord/discord-api-docs
