### ISSUE TITLE
`MessageButtonStyleResolvable` does not accept `ButtonStyle` of discord-api-types

### ISSUE THREAD

**Issue by night-lake** [discordjs/discord.js#7679]
### Which package is this bug report for?

discord.js

### Issue description

**Reproduction steps:**
1. Create a new message button
2. Set the style to an enum property of ButtonStyle

### Code sample

```typescript
new MessageButton()
    .setStyle(ButtonStyle.Primary)
    .setLabel('Something')
```

### Package version

13.6.0 with discord-api-types@0.26.1

### Node.js version

v17.6.0 with typescript@4.6.2

### Operating system

Arch Linux 5.10.60.1-microsoft-standard-WSL2 on Windows 10.0.22000 x86_64 

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildPresences, GuildMessages, GuildMessageReactions

**Comment by Syjalo** [comment]
Fixed in v14. Use `MessageButtonStyles` form `discord.js` for v13.

**Comment by night-lake** [comment]
Thanks.
