### ISSUE TITLE
guildMember.premiumSince and guildMember.premiumSinceTimestamp always null

### ISSUE THREAD

**Issue by iKingNinja** [discordjs/discord.js#7682]
### Which package is this bug report for?

discord.js

### Issue description

Reading `guildMember.premiumSince` and `guildMember.premiumSinceTimestamp` will always return null. I have boosted a server which also reached level 1 so i boosted twice too and those properties are null. There are not much more informations.

### Code sample

```typescript
const members = guild.members.cache;

for (let i of members) {
    if (serverSettings.checkMethod === '1') {
        if (i[1].nickname === username) {
            var isBooster = false;

            i[1].premiumSince ? isBooster = true : isBooster;

            return {
                isBooster: isBooster,
                boosterSince: i[1].premiumSince, //null
                boosterSinceTimeStamp: i[1].premiumSinceTimestamp //null
            };
        }
    }
}
```

### Package version

^13.6.0

### Node.js version

v17.5.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by ImRodry** [comment]
Can’t reproduce with the given partials, are you sure the member data is up to date and that the member is a booster?

**Comment by iKingNinja** [comment]
> Can’t reproduce with the given partials

There are no partials set in the client object.

> are you sure the member data is up to date and that the member is a booster?

Yes i am sure the member is a booster because it's me.
