### ISSUE TITLE
ThreadChannel.autoArchiveDuration might be string, docs list it as number only

### ISSUE THREAD

**Issue by MaksiRose** [discordjs/discord.js#7687]
### Which package is this bug report for?

discord.js

### Issue description

When looking up definitions with VS code, I stumbled upon something interesting. If you look up the definition for the property `autoArchiveDuration`, it is either null or the type `ThreadAutoArchiveDuration`, which itself is either 60,  1440, 4320, 10080 or "MAX". While I'm not sure if MAX could ever actually be the chosen value, if it does end up being chosen, it could lead to bugs especially when `autoArchiveDuration` is used to calculate something.

I hope I haven't missed or misunderstood anything here, and if so, I apologize for the inconvenience :)

### Package version

13.6.0

### Node.js version

17.5.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Thank you for this issue.

It's a bug: the API of course doesn't return `MAX` so this should not be typed as such.

**Comment by JakeElder** [comment]
Can confirm setting the value to 'MAX' breaks stuff
```
  TypeError: Cannot read properties of undefined (reading 'includes')

  - ThreadManager.js:125 ThreadManager.create
    [discord.js]/src/managers/ThreadManager.js:125:39
```

**Comment by Jiralite** [comment]
That suspiciously doesn't look like the same issue... Assuming you are on stable, the error states `Guild#features` is `undefined`.
