### ISSUE TITLE
joinVoiceChannel throws an error in Javascript but not in Typescript

### ISSUE THREAD

**Issue by Bendimester23** [discordjs/discord.js#7696]
### Which package is this bug report for?

voice

### Issue description

Steps to reproduce:
1) write a bot, that tries to join a voice channel

### Code sample

```typescript
joinVoiceChannel({
            channelId: channelId,
            guildId: guild.id,
            selfDeaf: true,
            adapterCreator: guild.voiceAdapterCreator
})
```

### Package version

13.6.0

### Node.js version

16.14.0

### Operating system

Artix Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, DirectMessages

**Comment by monbrey** [comment]
Could you please include the TypeScript error?

**Comment by Bendimester23** [comment]
in TypeScript, it runs without an error

**Comment by Bendimester23** [comment]
however in JavaScript it throws this: `
TypeError: o is not a function
    at new G (/home/bendi/Dokumentumok/muzsika-js/node_modules/@discordjs/voice/dist/index.js:8:7254)
    `

**Comment by kyranet** [comment]
Can you please run Node.js with the [`--enable-source-maps` option](https://nodejs.org/dist/latest-v17.x/docs/api/cli.html#--enable-source-maps)? You can either define it by doing `node --enable-source-maps .` or by setting the `NODE_OPTIONS` environment variable with it as a value.

Without source maps, it's hard to determine what is the code that is erroring.

**Comment by Bendimester23** [comment]
```
TypeError: o is not a function
    at null.G (/home/bendi/Dokumentumok/muzsika-js/node_modules/@discordjs/voice/src/VoiceConnection.ts:237:19)
    at new GuildAudioPlayer (/home/bendi/Dokumentumok/muzsika-js/player.js:74:27)
```
