### ISSUE TITLE
messageCreate not triggered on DM in main

### ISSUE THREAD

**Issue by renedx** [discordjs/discord.js#7699]
### Which package is this bug report for?

discord.js

### Issue description

- Listen in messageCreate
- provide proper intents (DirectMessages from gateway bits)
- send message to bot from private account
- event not triggered

### Code sample

```js
import { Client, GatewayIntentBits } from 'discord.js';
const client = new Client({
  'intents': [
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildPresences,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildBans,
    GatewayIntentBits.GuildMessages
  ],
  'partials': ['CHANNEL']
});

process.on('uncaughtException', (err) => {
  console.log('General error:', err.message);
  console.log(err);
});

client.on('messageCreate', async (m) => {
  console.log(m);
});

client.login('TOKEN');

```

### Package version

14.0.0-dev.1647259751.2297c2b
with https://github.com/discordjs/discord.js/pull/7649 apply'd

### Node.js version

v16.14.2

### Operating system

Debian

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildPresences, GuildMessages, DirectMessages

**Comment by renedx** [comment]
Im aware main could be broken and I already apply’d a PR to it for the message components bug it has. But I thought something like this should be on the radar for being broken.

if not, close it, no hard feelings. I just wanted to test ShowModal and be prepared to breaking changes on my bot. That’s why I’m testing v14 / main.

**Comment by monbrey** [comment]
DM channels don't fire the `channelCreate` event which means they don't get placed in the discord.js cache. As the channel is uncached, `messageCreate` events for it won't fire unless you enable the Channel partial also.

**Comment by renedx** [comment]
> DM channels don't fire the `channelCreate` event which means they don't get placed in the discord.js cache. As the channel is uncached, `messageCreate` events for it won't fire unless you enable the Channel partial also.

Thanks for the quick reply. The bot does work under `v13.6.0`. Its broken in `14.0.0-dev.1647259751.2297c2b`.
I've attached a quick test script & tested it just in case something else somewhere may break it.

**Comment by Jiralite** [comment]
Unfortunately, that's not how one applies partials. Import the partial like so:

```JavaScript
import { Partials } from "discord.js"
Partials.Channel; // 1
```

**Comment by renedx** [comment]
> Unfortunately, that's not how one applies partials. Import the partial like so:
> 
> ```js
> import { Partials } from "discord.js"
> Partials.Channel; // 1
> ```

Aha, thats changed too? Thanks. 

Works. Wow, I've found all bit changes, but this one overlooked.
Thanks for the amazingly quick reply. :)
