### ISSUE TITLE
awaitMessages and awaitReactions are not working 

### ISSUE THREAD

**Issue by yan-930521** [discordjs/discord.js#7700]
### Which package is this bug report for?

discord.js

### Issue description

```
// this isn't working
let filter = (m) => {
	......
}
await msg.channel.awaitMessages({
	filter,
	......
}).catch(err=>{});
```

```
// but this is fine
let filter = (m) => {
	......
}
await msg.channel.awaitMessages({
	filter: filter,
	......
}).catch(err=>{});
```
doc : `await msg.channel.awaitMessages({ filter, ....})`
( same as awaitReactions )

Is there anything wrong with the official doc?

### Package version

13.6.0

### Node.js version

17.7.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions

**Comment by imranbarbhuiya** [comment]
This is only possible if your filter name is different than `filter`. Can't repro with your provided codes. So make sure u r naming `filter` function as filter or if u r giving a name other than `filter` then use `{ filter: otherName }` when passing in collection options.

**Comment by yan-930521** [comment]
oh thanks.
btw it seems doesn't on doc( ?
