### ISSUE TITLE
ModalBuilder does not accept camel cases

### ISSUE THREAD

**Issue by skinmaker1345** [discordjs/discord.js#7702]
### Which package is this bug report for?

builders

### Issue description

Hi, I've heard that builders are expected to accept camel cases,
but I've noticed that ModalBuilder does not accept camel cases, while others(like TextInputBuilder) do.

### Code sample

```typescript
new ModalBuilder({
    customId: 'something' // will not work
    custom_id: 'something' // will work
})
```

### Package version

14.0.0-dev.1647259751.2297c2b

### Node.js version

16.14.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

72577c4

**Comment by BenjammingKirby** [comment]
unless i am mistaken
no, the "djs exported" xBuilder classes are meant to take in camelCase properties, not the ones directly from builder
the issue is with djs, not with the builders package, what is needed is exporting a new `ModalBuilder` from djs that extends the builders' ModalBuilder

**Comment by skinmaker1345** [comment]
> unless i am mistaken no, the "djs exported" xBuilder classes are meant to take in camelCase properties, not the ones directly from builder the issue is with djs, not with the builders package, what is needed is exporting a new `ModalBuilder` from djs that extends the builders' ModalBuilder

ooh okay, that's the reason why I was confused looking up the code between djs TextInputBuilder and ModalBuilder, they looked quite different.
okay for that, I wonder will djs make a new ModalBuilder which extends the existing ModalBuilder, making camelCase allowed, since TextInput or other builders are.
