### ISSUE TITLE
Discord custom status not working

### ISSUE THREAD

**Issue by kaeden-crypto** [discordjs/discord.js#7707]
### Which package is this bug report for?

discord.js

### Issue description

Discord says in there docs type 4 is a custom status meaning no playing, listening and what so ever but

No errors in the console

![image](https://user-images.githubusercontent.com/55254772/160023039-1f6fe086-c263-40f4-8de7-65836812ca36.png)
![image](https://user-images.githubusercontent.com/55254772/160023045-231adbdb-68a7-42bf-b84f-949cd8c95144.png)

![image](https://user-images.githubusercontent.com/55254772/160023049-2da3f658-6527-48c4-9a01-fa06a78c453e.png)

### Code sample

```typescript
Bot.user.setActivity(`in development`,{type: 4});
```

### Package version

13.6.0

### Node.js version

16.9

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by Smidul** [comment]
Bots don't support custom status

**Comment by kaeden-crypto** [comment]
Discord has it in their documentation lol and Ive seen bots have it

**Comment by ImRodry** [comment]
The documentation you linked is for all types of activities which can be received. A Custom activity can only be received from users, not bots. I can guarantee you've never seen a bot with a custom status

**Comment by RagnarLothbrok-Odin** [comment]
> Discord has it in their documentation lol and Ive seen bots have it

If you actually read the documentation, you would have seen that it says:

> Bots cannot set a CUSTOM activity type, it is only for custom statuses received from users
