### ISSUE TITLE
Slash Command localization

### ISSUE THREAD

**Issue by Chr1s70ph** [discordjs/discord.js#7710]
### Which package is the feature request for?

discord.js

### Feature

Discord recently announced, that slash-command localization is in beta.

### Ideal solution or implementation

Add translation options to slash-commands.

### Other context

The localization feature is documented [here](https://discord.com/developers/docs/interactions/application-commands#localization) in the Discord-API-Docs

PR: #7684

**Comment by imranbarbhuiya** [comment]
has pr https://github.com/discordjs/discord.js/pull/7684

**Comment by MRHACO** [comment]
lol
