### ISSUE TITLE
Fix discrepancy in meaning of tag between Discord.js and Discord/Discord API

### ISSUE THREAD

**Issue by Vidhin05** [discordjs/discord.js#7719]
### Which package is this bug report for?

discord.js

### Issue description

Discord Support docs and Discord API Documentation refers to tag as the 4-digit Discriminator in the username, whereas Discord.js refers it as Username+Discriminator.
Relevant Links:
https://discord.com/developers/docs/resources/user#user-object
https://support.discord.com/hc/en-us/articles/360000270351-Custom-Discord-Tags-with-Nitro
https://[discord.js](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=tag).org/#/docs/main/stable/class/User?scrollTo=tag

![image](https://user-images.githubusercontent.com/22542029/160277736-f7793f1c-e9d0-41a5-bde9-db1f88289741.png)
![image](https://user-images.githubusercontent.com/22542029/160277737-c7c17d3d-64d0-4295-b6d2-60fbe105b1aa.png)
![image](https://user-images.githubusercontent.com/22542029/160277745-f9a08e3b-f56f-4ce8-9979-a09224c9b971.png)

### Package version

13.6.0

### Node.js version

Not Applicable

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment]
The word tag is commonly used to refer to the username+discriminator combo. The 4 numbers after the # have always been called discriminator and that won’t change. Unless you have a better suggestion for what tag could be called I think this is just fine as it is

**Comment by vladfrangu** [comment]
Considering not even Discord is consistent about naming discriminators what they are... 😅 I doubt we'll change what its called

**Comment by Jiralite** [comment]
Don't forget this page!

![image](https://user-images.githubusercontent.com/33201955/160278337-cacc704b-55d3-47c8-b700-d1d494f7f964.jpeg)

Per this support article, discord.js is correct.

Basically, there's inconsistency everywhere. This likely won't change.

**Comment by Vidhin05** [comment]
Closing due to Discord inconsistencies for the term Tag.
