### ISSUE TITLE
`stageInstanceDelete` triggering twice.

### ISSUE THREAD

**Issue by muhitrhn** [discordjs/discord.js#7737]
### Which package is this bug report for?

discord.js

### Issue description

1. Put a console.log('anything') in `stageInstanceDelete` event.
2. Create scheduled event.
3. Start the event.
4. End it. 
![DAAF127B-CD4F-40A7-94BF-681A2238C01F](https://user-images.githubusercontent.com/36473811/161378351-f4e1dcb3-257c-4b47-a2d5-185ccd4fdc84.jpeg)

You will see `anything` will be logged twice.

**NOTE:** Doesn’t trigger twice if I directly start an event from the stage channel instead of  scheduling it.

### Package version

13.6.0

### Node.js version

16.14.2

### Operating system

Ubuntu 20.04

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by Jiralite** [comment]
Thank you for the bug report. I was able to reproduce this, but this is actually not a discord.js issue.

From debugging, Discord sends two `STAGE_INSTANCE_DELETE` events:

```JavaScript
{
  t: 'STAGE_INSTANCE_DELETE',
  s: 10,
  op: 0,
  d: {
    topic: 'reg',
    privacy_level: 2,
    invite_code: null,
    id: '959761080685576224',
    guild_scheduled_event_id: '959761024062488596',
    guild_id: '886323824801488996',
    discoverable_disabled: false,
    channel_id: '959760445252702218'
  }
} 0
StageInstance {
  id: '959761080685576224',
  guildId: '886323824801488996',
  channelId: '959760445252702218',
  topic: 'reg',
  privacyLevel: 2,
  discoverableDisabled: false,
  guildScheduledEventId: '959761024062488596'
}
{
  t: 'STAGE_INSTANCE_DELETE',
  s: 11,
  op: 0,
  d: {
    topic: 'reg',
    privacy_level: 2,
    invite_code: null,
    id: '959761080685576224',
    guild_scheduled_event_id: '959761024062488596',
    guild_id: '886323824801488996',
    discoverable_disabled: false,
    channel_id: '959760445252702218'
  }
} 0
StageInstance {
  id: '959761080685576224',
  guildId: '886323824801488996',
  channelId: '959760445252702218',
  topic: 'reg',
  privacyLevel: 2,
  discoverableDisabled: false,
  guildScheduledEventId: '959761024062488596'
}
```

discord.js is simply emitting the events received from Discord. It's not a bug on our side. I would ask Discord why this happens in the first place.

**Comment by muhitrhn** [comment]
Great! Please do.
