### ISSUE TITLE
readme.md should be updated

### ISSUE THREAD

**Issue by lmch6666** [discordjs/discord.js#7743]
### Which package is this bug report for?

discord.js

### Issue description

new Documentation is right code in Documentation ,  readme.md have a wrong

### Code sample

```typescript
//  old code readme
const { Client, GatewayIntentBits } = require('discord.js');
const client = new Client({ intents: [GatewayIntentBits.Guilds] });
//  new code Documentation stable
const { Client, Intents } = require('discord.js');
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
```

### Package version

12

### Node.js version

16.6

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

d23280c

**Comment by ImRodry** [comment]
The readme doesn’t “have a wrong”, you’re looking at the main branch which is for v14 development
