### ISSUE TITLE
`GuildMemberManager` timeout when fetching users with an array containing a non-snowflake string

### ISSUE THREAD

**Issue by sunny-zuo** [discordjs/discord.js#7754]
### Which package is this bug report for?

discord.js

### Issue description

When fetching members from GuildMemberManager using an array containing a non-snowflake string, `fetch` will timeout rather than exit early or provide an error notifying that the snowflake is invalid. I believe this issue happens anytime a "snowflake" that contains a letter(s) is provided.

This code:
```ts
await guild.members.fetch({ user: ['this is not a snowflake'] });
```

Leads to this error:
```
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at Timeout._onTimeout (C:\Users\micro\Desktop\Programming\djs-bug-repo\node_modules\discord.js\src\managers\GuildMemberManager.js:454:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
}
```

My expectation would be either a related error (behaviour when fetching a single user using an invalid snowflake), or that the invalid snowflake is ignored (behaviour when snowflakes are provided and no member matches when fetching multiple).

<details>
<summary>Error when fetching single user</summary>
<br>

Code:

```ts
await guild.members.fetch('not a snowflake')
```

Result:

```
DiscordAPIError: Invalid Form Body
    user_id: Value "not a snowflake" is not snowflake.
        at RequestHandler.execute (C:\Users\micro\Desktop\Programming\sir-goose-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async RequestHandler.push (C:\Users\micro\Desktop\Programming\sir-goose-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
        at async GuildMemberManager._fetchSingle (C:\Users\micro\Desktop\Programming\sir-goose-bot\node_modules\discord.js\src\managers\GuildMemberManager.js:407:18)
```
</details>

<details>
<summary>Invalid snowflake is ignored</summary>
<br>

Code: 
```ts
const members = await guild.members.fetch({ user: ['123', '100000000000000000000000001'] });
console.log(members.size);
```

Output:
```
0
```

</details>

### Code sample

```typescript
const { Client, Intents } = require("discord.js");

const client = new Client({
  intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MEMBERS,
    Intents.FLAGS.GUILD_MESSAGES,
  ],
});

client.on("messageCreate", async (message) => {
  if (message.content !== "!fetch") return;

  const guild = message.guild;

  const e1 = await guild.members.fetch({
    user: ["123", "10000000000000000000001", "<your own user id>"],
  });
  console.log(e1.size); // size is 1 assuming you're in the guild

  const e2 = await guild.members.fetch({ user: ["this is not a snowflake"] });
  console.log(e2.size); // timeout error before this is executed
});

client.login("token");
```

### Package version

13.6.0

### Node.js version

v16.14.2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

### I have tested this issue on a development release

402514f

**Comment by monbrey** [comment]
It doesn't really work like that because fetching guild members in bulk this way isn't an API endpoint, it's a gateway payload. discord.js sends the OPcode and additional parameters off, and waits for `guildMemberChunk` events in return.

If that data you provide is invalid, it just needs to keep waiting until the timeout is reached, because Discord will never send enough chunks in return.

**Comment by monbrey** [comment]
I was just reminded, thanks @almostSouji, that you can use the `guild.members.search()` method to execute similar functionality using the REST API

<https://discord.js.org/#/docs/discord.js/stable/class/GuildMemberManager?scrollTo=search>

**Comment by sunny-zuo** [comment]
Thanks! Somehow I missed that `search()` was a method. I feel like docs around this could be improved (perhaps a warning about fetching with non-snowflakes?) but it is a pretty niche use case.
