### ISSUE TITLE
interaction user.id returns false

### ISSUE THREAD

**Issue by YourN1ghtm4r3** [discordjs/discord.js#7758]
### Which package is this bug report for?

discord.js

### Issue description

Code: 
- Command handler : https://sourceb.in/LFMratpmRl
- command file: https://sourceb.in/VvVuCle9xg

The command sometimes works fine sometimes, but most of the times interaction.user.id returns false. 

![image](https://user-images.githubusercontent.com/103213436/162270454-da78a976-b081-4455-9df2-55fca62acae0.png)
![image](https://user-images.githubusercontent.com/103213436/162270467-3feda455-467c-4ed4-9e20-797564ca9dc0.png)

### Code sample

```typescript
const { SlashCommandBuilder } = require("@discordjs/builders")
require("dotenv").config()


module.exports = {
    data: new SlashCommandBuilder()
    .setName('toggle')
    .setDescription('toggle')
    .addSubcommand(scmd => scmd.setName('hints').setDescription('enable/disable hints ping'))
    .addSubcommand(scmd => scmd.setName('riddles').setDescription('enable/disable riddle pings')),
    async execute(interaction) {

        switch(interaction.options.getSubcommand()){
            
            case "hints" : {
                //process.env.hints is a string containing a role id
                console.log(interaction.user.id)
                await interaction.guild.members.fetch()
                await interaction.member.roles.add(process.env.hints) 
                interaction.reply({content: `Successfully added the <@&${process.env.hints}> role`, ephemeral: true})
                }
                break
            }
        }
    }
}
```

### Package version

13.6.0

### Node.js version

16.14.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, DirectMessages

**Comment by almostSouji** [comment]
Then you very likely overwrite that in some other part of your code.
Common issue is `if (user.id = "some id")`

**Comment by YourN1ghtm4r3** [comment]
> Then you very likely overwrite that in some other part of your code.

I provided the full source code in the source bin link. From my side I am not aware that I overwrote user.id anywhere.

**Comment by YourN1ghtm4r3** [comment]
@almostSouji Actually you were right! Thank you. 4 of us couldn't locate the issue before - I fugured it now tho.
