### ISSUE TITLE
Slash Command Localization(v13)

### ISSUE THREAD

**Issue by skinmaker1345** [discordjs/discord.js#7765]
### Which package is the feature request for?

discord.js

### Feature

Discord recently announced slash-command localization.

### Ideal solution or implementation

add support for translating command name, description, options

### Other context
the documentation of the slash command localizations is in [here](https://discord.com/developers/docs/interactions/application-commands#localization).

I am aware of the PR which is merged into v14,
but I couldn't find any of it for v13.
I would be happy if there's backport or implementation for v13.

I will close the issue if someone, or myself, confirms that there was a PR which I missed.

**Comment by monbrey** [comment]
Could you please provide a link to the announcement or documentation that you are referencing?

**Comment by skinmaker1345** [comment]
> Could you please provide a link to the announcement or documentation that you are referencing?
https://discord.com/developers/docs/interactions/application-commands#localization

**Comment by kyranet** [comment]
> I am aware of the PR which is merged into v14

I don't see that PR, we have one for builders, though: https://github.com/discordjs/discord.js/pull/7683, and it's not merged yet.

**Comment by skinmaker1345** [comment]
> > I am aware of the PR which is merged into v14
> 
> I don't see that PR, we have one for builders, though: #7683, and it's not merged yet.

#7684 seems to be the PR. And yes It wasn't merged.

**Comment by kyranet** [comment]
The linked PR has merged 7 days ago, and will be included in next release (v13.7.0).
