### ISSUE TITLE
DiscordAPIError: 404: Not Found

### ISSUE THREAD

**Issue by Shelly7w7** [discordjs/discord.js#7770]
### Which package is this bug report for?

discord.js

### Issue description

I am trying to delete a channel using `delete()`. But when I do, I receive the 404 error.

### Code sample

```typescript
const { Client, Intents } = require('discord.js');
const token = "token";

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });

client.once('ready', () => {
    console.log('Ready!');
});

client.on('messageCreate', message => {
    if (message.content === 'ping') {
        message.channel.delete();
    }
});

client.login(token);
```

### Package version

discord.js@13.6.0 (git+ssh://git@github.com/discordjs/discord.js.git#e1cdcfa9a6baed1d373cc5474630d32ce38db31e) (v13 Branch aka 13.7.0)

### Node.js version

v16.10.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Shelly7w7** [comment]
I came from the discord server. This is indeed an issue. Happening on v13.7.0, hence why I am reporting it. For clarification, this works fine on v13.6.0

**Comment by Amongsterdevil** [comment]
Have gone a treated  while you were trying to demonstrate on single lane put it in go with the flow

**Comment by SpaceEEC** [comment]
Since #7771 got merged, this issue has been resolved.
