### ISSUE TITLE
New Permission Handler

### ISSUE THREAD

**Issue by cit999** [discordjs/discord.js#7790]
### Which package is the feature request for?

discord.js

### Feature

Whenever I release my slash commands they only work in guilds and not in DM's because I want the commands to be greyed out for users with the invalid permissions. I was wondering if you could add a property in the <client>.application.commands that allows you to set the permissions for all guilds instead of doing a forEach() loop and still allow the commands to work in DM's.

### Ideal solution or implementation

Whenever I release my slash commands they only work in guilds and not in DM's because I want the commands to be greyed out for users with the invalid permissions. I was wondering if you could add a property in the <client>.application.commands that allows you to set the permissions for all guilds instead of doing a forEach() loop and still allow the commands to work in DM's.

**Comment by advaith1** [comment]
Discord has implemented this with Command Permissions v2 which is currently in [1% of community servers](https://rollouts.advaith.io/#2021-09_command_permissions_v2). discord.js has no control over the release of this Discord feature.

**Comment by kyranet** [comment]
After reading more closely, I realised this is more of a feature request for Discord itself than for us.

You may suggest new features for Discord in [their respective repository](https://github.com/discord/discord-api-docs).

If what you were looking for were Permissions v2 (which by the way, commands you cannot use aren't greyed out, but hidden completely), please take a look at #7856.
