### ISSUE TITLE
Accept `PS4` and `PS5` values for `ActivityPlatform` type.

### ISSUE THREAD

**Issue by Viriatto** [discordjs/discord.js#7803]
### Which package is this bug report for?

discord.js

### Issue description

`Activity` objects have been registered with a value of `PS4` and `PS5` for their `platform` property, whose type currently only accepts `xbox`, `desktop` or `samsung`.

### Package version

13.6.0

### Node.js version

16.6.2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Hmm. *intense thinking*

It seems these types were added with https://github.com/discordjs/discord.js/pull/4984. However, the upstream pull request does not document these types. I currently cannot find the types with the current documentation, either.

Perhaps we should just allow a string and not some predetermined types?

**Comment by ImRodry** [comment]
The types were on the upstream PR but were removed before merge so I'm guessing these shouldn't even be on discord.js: https://github.com/discord/discord-api-docs/pull/2219/commits/5822b0bc97fa8ad1f9e87d0426a309cbf680c5d3

**Comment by Viriatto** [comment]
> Hmm. _intense thinking_
> 
> It seems these types were added with #4984. However, the upstream pull request does not document these types. I currently cannot find the types with the current documentation, either.
> 
> Perhaps we should just allow a string and not some predetermined types?

Current documentation for `ActivityPlatform` type is here: https://discord.js.org/#/docs/discord.js/stable/typedef/ActivityPlatform

**Comment by ImRodry** [comment]
That's discord.js documentation, not Discord documentation
