### ISSUE TITLE
missing/wrong typings for thread auto archive duration

### ISSUE THREAD

**Issue by Kneemund** [discordjs/discord.js#7814]
### Which package is this bug report for?

discord.js

### Issue description

When creating (editing) a thread, the `autoArchiveDuration` field of `StartThreadOptions` (`ThreadEditData`) should accept `60 | 1440 | 4320 | 10080 | 'MAX'` according to the [current documentation](https://discord.js.org/#/docs/discord.js/main/typedef/ThreadAutoArchiveDuration). However, the current type of the field (`ThreadAutoArchiveDuration`) only expands to `60 | 1440 | 4320 | 10080`. `'MAX'` is missing. It should be added to the fields as a separate type, not to `ThreadAutoArchiveDuration`. The `'MAX'` option in the current documentation should be moved from `ThreadAutoArchiveDuration` to the individual fields.

Additionally, `Util.resolveAutoArchiveMaxLimit` currently has a return type of `number`, which prevents it from being assigned to `ThreadAutoArchiveDuration` unless you do unnecessary type checks. The return type should be changed to `ThreadAutoArchiveDuration`. 

If you decide to leave the typings as they are in the current documentation (i.e. include `'MAX'` in `ThreadAutoArchiveDuration`), then you should add a separate type for `Util.resolveAutoArchiveMaxLimit` which doesn't include `'MAX'`.

### Package version

discord.js@14.0.0-dev.1650240532-9ef7ffd

### Node.js version

v17.9.0 (typescript@4.6.3)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

9ef7ffd

**Comment by MarcusOtter** [comment]
Getting this problem in `13.7.0`, the "MAX" option has disappeared.
![image](https://user-images.githubusercontent.com/35617441/168491111-923a55ce-5107-4aa4-8e83-661202a72193.png)

But it still exists in the docs for `13.7.0`:
![image](https://user-images.githubusercontent.com/35617441/168491132-ccda8842-1da1-4c71-a633-f82070f20b8a.png)

Is the plan to release this fix for `14.0.0`? Should the docs be updated for this version?

**Comment by Jiralite** [comment]
> Edit: I slightly misunderstood the issue. I understand now that "MAX" should not be added to ThreadAutoArchiveDuration, but it would still be good if the docs confirmed that.

There is no point - the `MAX` option will disappear in the next major version as its use is obsolete.
