### ISSUE TITLE
Documentation doesn't reflect removal of singular option builder methods

### ISSUE THREAD

**Issue by erickbickler** [discordjs/discord.js#7821]
### Which package is this bug report for?

builders

### Issue description

In djs v13.0 builders documentation, there is the addChoice method for SlashCommandStringOption. This was removed in PR #7590.

### Package version

0.13.0

### Node.js version

16.14.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug), No Partials

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug), Guilds

**Comment by ImRodry** [comment]
That method does exist on v13

**Comment by imranbarbhuiya** [comment]
It'll be present in migration guide and not documentation.

**Comment by kevinlul** [comment]
Hello, I think documentation should be updated as Discord.js 13.7.0 incorporated builders 0.13.0.
