### ISSUE TITLE
set default `authPrefix` in REST's constructor 

### ISSUE THREAD

**Issue by davecaruso** [discordjs/discord.js#7823]
### Which package is the feature request for?

rest

### Feature

when using REST with Bearer tokens, i have to set `authPrefix` to `Bearer` on every request, while the actual bearer token is set right after constructing the object with `.setToken(...)`. it looks bad, and sometimes i forget to supply the parameter leading to errors and longer time to develop.

example of what this looks like in my code
```ts
const guilds = (await userDiscordRest.get(Routes.userGuilds(), {
    authPrefix: 'Bearer'
})) as APIGuild[];
```
prettier seems to want to wrap it to three lines which is anoying as well.

### Ideal solution or implementation

Allow the rest constructor to set the default `authPrefix`, reducing copied code when using the library.

```ts
const rest = new REST({ version: '10', authPrefix: "Bearer" });
```

### Alternative solutions or implementations

Something else we could implement instead is an extra option to setToken so it would look like `.setToken(token, { authPrefix: "Bearer" })` or `.setToken(token, "Bearer")` or something similar.

### Other context

It should be a simple change to this line in RequestManager https://github.com/discordjs/discord.js/blob/585169f2f097ffb1940d17f549e4290aa55acde2/packages/rest/src/lib/RequestManager.ts#L354, letting it use a property passed to the constructor.

**Comment by with-heart** [comment]
Came here to request exactly this and found your issue instead! Weird timing!
