### ISSUE TITLE
Guild channel name wrongly trimmed when editing

### ISSUE THREAD

**Issue by mainleau** [discordjs/discord.js#7831]
### Which package is the feature request for?

discord.js

### Feature

Guild channel name should not be trimmed for types that allow spaces like voice channels.

### Ideal solution or implementation

Check the channel type and trim name only if type does not allow spaces.
```js
const newData = await this.client.rest.patch(Routes.channel(channel.id), {
  body: {
    name: ['GUILD_VOICE', ...].includes(data.type) ? (data.name ?? channel.name) : (data.name ?? channel.name).trim(),
    ...
  }
}
```

**Comment by Jiralite** [comment]
Where is that in the source code? I cannot find it?

**Comment by Jiralite** [comment]
Just out of curiosity, can you provide an example channel name that is behaving unexpectedly here?
