### ISSUE TITLE
guildMember.presence returns null

### ISSUE THREAD

**Issue by battincik** [discordjs/discord.js#7837]
### Which package is this bug report for?

discord.js

### Issue description

I run into a problem when I want to fetch a member and check its status.
Presence object returns null if the member is offline

### Code sample

```typescript
cost member = await message.guild.members.fetch({ user: user.id, withPresences: true, force: true })
console.log(member.presence)

// presence object returns null if user is offline
// it might make more sense to return presence.status offline instead
```

### Package version

v13.6.0

### Node.js version

v17.4.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by almostSouji** [comment]
Offline members have no presence, I'm not too sure what you expect to happen

**Comment by battincik** [comment]
I get an error when I want to pull the user's status

**Comment by BenjammingKirby** [comment]
> Offline members have no presence, I'm not too sure what you expect to happen

to avoid the error, just deal with the presence being null, there's really nothing you can do

**Comment by xMooddyy** [comment]
You have a few ways to prevent that error, you could use an if statement or [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

Generally, offline members have no presence, so you could just display it as `offline` if presence is null.
