### ISSUE TITLE
message.content returns an empty string

### ISSUE THREAD

**Issue by Mateo-tem** [discordjs/discord.js#7840]
### Which package is this bug report for?

discord.js

### Issue description

On discord.js v14, I notice that on the `messageCreate` event, the content property of the `message` parameter always returns an empty string. I don't know if this is because of my intents, but I don't think so, because I tested it with different intents (all intents) but it doesn't work. 

I think that this is a Discord API problem because I checked the code of discord.js and the API data returns the message object with empty content.

I don't know if I'm the only person to whom this happens.

### Code sample

```typescript
const { Client, Partials } = require('discord.js');
const client = new Client({
  intents: [
    "DirectMessageReactions",
    "DirectMessageTyping",
    "DirectMessages",
    "GuildBans",
    "GuildEmojisAndStickers",
    "GuildIntegrations",
    "GuildInvites",
    "GuildMembers",
    "GuildMessageReactions",
    "GuildMessageTyping",
    "GuildMessages",
    "GuildPresences",
    "GuildScheduledEvents",
    "GuildVoiceStates",
    "GuildWebhooks",
    "Guilds",
  ],

  partials: [
    Partials.Channel,
    Partials.GuildMember,
    Partials.GuildScheduledEvent,
    Partials.Message,
    Partials.Reaction,
    Partials.ThreadMember,
    Partials.User,
  ],
});

client.on('messageCreate', (message) => {
  console.log(message.content) // this returns ''
});

client.login('token');
```

### Package version

14.0.0-dev.1650672498-3617093

### Node.js version

v16.14.2

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by kyranet** [comment]
That's because you're missing `MessageContent` intent. https://github.com/discordjs/discord-api-types/blob/main/gateway/v10.ts#L190

**Comment by Mateo-tem** [comment]
Oh ok, thank you so much
