### ISSUE TITLE
Missing guild feature `ANIMATED_BANNER`

### ISSUE THREAD

**Issue by tnthung** [discordjs/discord.js#7849]
### Which package is the feature request for?

discord.js

### Feature

The `ANIMATED_BANNER` feature does not exist under the type `GuildFeature`.

### Ideal solution or implementation

Add the `ANIMATED_BANNER` type along with v13.7.

### Alternative solutions or implementations

Use `"ANIMATED_BANNER" as any` to bypass type check

**Comment by Smidul** [comment]
There are many, many other missing guild features that are added all the time
I don't think this list will ever be up-to-date anyway

**Comment by tnthung** [comment]
OFC I know that new features can be added between each version of discordjs. And I'm not saying that it needs to be always up to date. Currently, discord has 23 variants of the features, and 22 for discordjs. There's only 1 missing item, that's why I open this issue. It can easily be added I believe.

**Comment by Smidul** [comment]
Yeah I know, what I was saying is there's a lot more missing features apart from `ANIMATED_BANNER`, but forgot that those aren't documented anyway, sorry lol

**Comment by tnthung** [comment]
Wait... There're some not doc-ed? Then how do you know if guild have them?

**Comment by Smidul** [comment]
They are still returned in Guild#features, just not documented nor listed

**Comment by tnthung** [comment]
But it still possible to add features now doc-ed in the next version right?
