### ISSUE TITLE
member is null in voiceStatusUpdate

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#7854]
### Which package is this bug report for?

discord.js

### Issue description

Occasionally getting the error: TypeError: Cannot read properties of null (reading 'roles') in voiceStatusUpdate.

Originally thought this might be because of partials, so I added in if (newState.member.partial) await newState.member.fetch(); although this errored and said TypeError: Cannot read properties of null (reading 'partial').

Have guild member partial enabled.

It seems the member is null, but I'm not sure why that is. It doesn't happen each time.

Steps to reproduce:
Do anything that would trigger the voiceStatusUpdate event. ( Although it happens occasionally )

### Code sample

```typescript
async run(_, newState, client) {
 const role = newState.member.roles.cache.has(someRole);
}
```

### Package version

discord.js@13.6.0

### Node.js version

v16.14.0

### Operating system

Debian

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by Syjalo** [comment]
The `member` is `null` because it isn't in the cache. Not all members are cached so you need to fetch it.
```js
await newState.guild.members.fetch(newState.id);
```

**Comment by pkdev08** [comment]
> The `member` is `null` because it isn't in the cache. Not all members are cached so you need to fetch it.
> 
> ```js
> await newState.guild.members.fetch(newState.id);
> ```

I'm not sure if this would cache the member in the same event run though.

**Comment by pkdev08** [comment]
Also, I just did another test on my dev bot. I noticed that even if a member is not in the cache, they will be cached as soon as they enter a voice channel. Maybe there is some race condition where they aren't getting cached fast enough in the event run.

**Comment by pkdev08** [comment]
Update: I found the issue. If a member is in a voice channel, and gets kicked from the server. It will error with TypeError: Cannot read properties of null (reading 'roles'). So that seems to be where it's happening. Is this expected behavior? or should the library be handling this situation?

**Comment by SpaceEEC** [comment]
What different behavior would you expect from the library here?

**Comment by pkdev08** [comment]
Well when the member is kicked, the member object is still there at the beginning of the event run, but later in the run it becomes null. I can put a check for this myself, jut wasn't sure how the member object goes to null in the same run.

**Comment by pkdev08** [comment]
Update:
async run(_, newState, client) {
    logger.debug('member 1', newState.member);
    const guildSettings = await settings.get('guilds', newState.guild.id);

    logger.debug('member 2', newState.member);
    }

member 1 the member object is present
member 2 the member is null after calling the guild settings

**Comment by pkdev08** [comment]
I can just return out. I just thought maybe there was some other issue within the library.
