### ISSUE TITLE
Command Permissions v2

### ISSUE THREAD

**Issue by SuperchupuDev** [discordjs/discord.js#7856]
### Which package is the feature request for?

discord.js

### Feature

Implement Discord's new permission system for Application Commands

- discord/discord-api-docs#4830

### Ideal solution or implementation

Implement them to the lib

**Comment by KNOXDEV** [comment]
Noting that Discord did indeed shut down the bulk permission editing endpoint less than 24 hours ago.
I got to experience this on a bot in production. 😕 

Adding part of my error message in case it helps people find this from Google:
```
error: 405: Method Not Allowed {"code":0,"httpStatus":405,"method":"put","name":"DiscordAPIError","path":"/applications/(appId)/guilds/(guildID)/commands/permissions","requestData":...
```

On Discord.js v13 if that helps.

The associated PR #7857 should make sure to remove `ApplicationCommandPermissionsManager.set()`, which currently errors with the above.

**Comment by druv5319** [comment]
running into this same error message. How do I update permissions for commands now?

**Comment by monbrey** [comment]
You don't, you let the users set the permissions for your commands.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by itsame-luigi** [comment]
You should be able to specify default permissions via bitmask now: https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-using-default-permissions

`SlashCommandBuilder.setDefaultPermissions` currently only accepts a boolean value.

**Comment by monbrey** [comment]
Yes, that's why this issue exists and why there is a linked PR to do the enhancement.

If you're using builders, which produce JSON to go into the /rest module, you can just add those properties to the JSON yourself before sending it.

**Comment by BauerPh** [comment]
you can edit the permissions in your Discord Client for each Command as a workaround:

https://discord.com/developers/docs/interactions/application-commands#syncing-and-unsyncing-permissions
