### ISSUE TITLE
Missing typings for User#toJSON

### ISSUE THREAD

**Issue by Adrastopoulos** [discordjs/discord.js#7858]
### Which package is this bug report for?

discord.js

### Issue description

Calling `.toJSON()` on a user object returns a result with an unknown type. I asked around on the discord support server and did not find any conclusive reason as to why this is.

Here is an example of a jsonified user:
![Code_jWd2lbJwkY](https://user-images.githubusercontent.com/76796897/165668624-5f203495-5cb2-42a1-a943-ff4eb5250d1a.png)

Can typings be added to this method?

### Package version

discord.js@14.0.0-dev.1650931749-df64d3e

### Node.js version

v16.14.0 | typescript@4.6.3

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

df64d3e

**Comment by Jiralite** [comment]
Closing in favour of #9432 which isn't specific to the user object.
