### ISSUE TITLE
Name localization for Application Command Subcommands and Option Choices not included in JSON

### ISSUE THREAD

**Issue by jeddai** [discordjs/discord.js#7859]
### Which package is this bug report for?

builders

### Issue description

Localization options do not seem to work for subcommand name (probably description as well, admittedly I haven't checked), and subcommand option choice names.

#### Reproduction Steps
1. Create a command and subcommand
2. Add a string command option to the subcommand
3. After defining the name, set or add the name localizations
4. Export the command to JSON

Expected: The name localizations are present on the application command subcommand and option choices
Actual: The name localizations are not present on the application command subcommand and option choices

[Link to one place I think changes might need to happen.](https://github.com/discordjs/discord.js/blob/main/packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts#L35-L44) I'm pretty sure for the example linked there `name_localizations` needs to be added to the choice destructuring and on the object that is pushed to the choices array.

#### JSON result of example code
```
{
   "name":"test",
   "name_localizations":{
      "en-GB":"test"
   },
   "description":"Schedules an event in this channel",
   "options":[
      {
         "type":1,
         "name":"subcommand",
         "description":"subcommand description",
         "options":[
            {
               "choices":[
                  {
                     "name":"choice",
                     "value":"1"
                  }
               ],
               "type":3,
               "name":"option",
               "name_localizations":{
                  "en-GB":"option"
               },
               "description":"option description",
               "required":false
            }
         ]
      }
   ]
}
```

### Code sample

```typescript
import { InteractiveCommand } from './command';
import { SlashCommandBuilder } from '@discordjs/builders';

export const Test: InteractiveCommand = {
    data: new SlashCommandBuilder()
        .setName('test')
        .setNameLocalization('en-GB', 'test')
        .setDescription('Schedules an event in this channel')
        .addSubcommand(subcommand =>
            subcommand.setName('subcommand')
                .setNameLocalization('en-GB', 'subcommand')
                .setDescription('subcommand description')
                .addStringOption(option =>
                    option.setName('option')
                        .setNameLocalization('en-GB', 'option')
                        .setDescription('option description')
                        .addChoices(...[{
                            name: 'choice',
                            name_localizations: {
                                'en-GB': 'choice'
                            },
                            value: '1'
                        }])
                )
        ),
    execute: async interaction => {},
    handleMessageComponentInteraction: async interaction => {}
}
```

### Package version

0.13.0

### Node.js version

16.14.0

### Operating system

WSL

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, Message

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

Not yet, I see how to install a `discord.js` dev release, is it the same for the builders package?

**Comment by jeddai** [comment]
@kyranet I took a look at the linked PR and while that should fix the subcommand name/description localization issue I don't think it will fix the subcommand option choice name localization issue.

**Comment by vladfrangu** [comment]
Found the issue, thanks for mentioning it

**Comment by vladfrangu** [comment]
Can you check again? [`b911980` (#7862)](https://github.com/discordjs/discord.js/pull/7862/commits/b911980d444aceb3c3387852c0b84246fe9c0198) should solve it

**Comment by jeddai** [comment]
That looks like it should cover it!

**Comment by jeddai** [comment]
Also thank you very much for the speedy fix! ❤️

**Comment by Technical-13** [comment]
<https://discord.js.org/#/docs/discord.js/main/typedef/ApplicationCommandOptionChoiceData> suggests that:
```JavaScript
.addChoices(
  { name: 'All logs', nameLocalizations: {
    de: 'Alle Protokolle'
  }, value: 'default' },
  { name: 'Requests to /react', nameLocalizations: {
    de: 'Anfragen zu /Reagieren'
  }, value: 'react' },
  { name: 'Requests to /reply', nameLocalizations: {
    de: 'Bitten um /Antwort'
  }, value: 'reply' },
  { name: 'Requests to /say', nameLocalizations: {
    de: 'Anfragen zu /sagen'
  }, value: 'say' }
)
```

Should work; however, `nameLocalizations` and `name_localizations` (I've tried both) do not seem to work.
To see full code, <https://github.com/Technical-13/ShoeBot/blob/main/deployCommands.js#L116-L165>

![image](https://user-images.githubusercontent.com/4294498/228827220-2dbb9caa-e73f-47f8-921e-42d242cb436d.png)
