### ISSUE TITLE
Add image field to GuildScheduledEvent model

### ISSUE THREAD

**Issue by lim0n3** [discordjs/discord.js#7860]
### Which package is the feature request for?

discord.js

### Feature

Hey there, I'm developing a Discord bot which listens to GuildScheduledEvent events of creation, update and deletion. However, it seems that _discord.js_ does not include the image field in the event received, even if the Discord interface allows me to upload a cover image for my event. 

Actually, I noticed that the official Discord REST API supports that field in the [GuildScheduledEvent docs](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object).

I'm wondering if that "image" field could be added, or if there's another way to obtain the cover image that one uploads.

Thank you!

### Ideal solution or implementation

Add the "image" field to the events fired when a GuildScheduledEvent is created or updated.

### Other context

[GuildScheduledEvent](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object) model on Discord official docs

**Comment by almeidx** [comment]
Done in #7337 (main branch) and #7613 (v13)

**Comment by almeidx** [comment]
No, you need to wait for the next stable release (13.7.0). Or use v14-dev
