### ISSUE TITLE
Fetching channel fails

### ISSUE THREAD

**Issue by 7heMech** [discordjs/discord.js#7866]
### Which package is this bug report for?

discord.js

### Issue description

I tried to fetch channel with id of **969697942212579348** using:
```js
client.channels.fetch(969697942212579348);
```
and the error returned was
```json
{
  "error": "DiscordAPIError: Unknown Channel",
  "method": "get",
  "path": "/channels/969697942212579300"
}
```
Why is the id in the path **969697942212579300** and not **969697942212579348**?

### Package version

13.6.0

### Node.js version

v17.7.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by Jiralite** [comment]
You are passing an invalid argument. An id is a string.

**Comment by megatank58** [comment]
Ids are always stored as strings, if they are stored as numbers they get rounded up which produces the inaccurate result here
