### ISSUE TITLE
Automoderation message log is being considered as author's message

### ISSUE THREAD

**Issue by eightless** [discordjs/discord.js#7867]
### Which package is this bug report for?

discord.js

### Issue description

1. Turn on brand new Discord feature - Automod
2. Turn on alarms (logs) to some channel
3. Have `messageCreate` event on
4. Send a message containing blocked content in a public channel (other than the logs channel)
<img width="517" alt="image" src="https://user-images.githubusercontent.com/80820477/166112723-203545c9-4843-4157-bdc8-fbaa40477468.png">

### Package version

v13.6.0

### Node.js version

v18.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by almostSouji** [comment]
this is expected behaviour
