### ISSUE TITLE
Receiving message from uncached channel

### ISSUE THREAD

**Issue by imranbarbhuiya** [discordjs/discord.js#7871]
### Which package is this bug report for?

discord.js

### Issue description

From the last few days sometimes I was getting message with channel null. But today I got this error 
```bash
[CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache!
```

### Package version

13.6.0 as well as current v13 branch

### Node.js version

16.14.2

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildVoiceStates, GuildMessages, GuildMessageReactions

**Comment by vladfrangu** [comment]
I'll be closing this as there are no code samples or concrete steps to reproduce this. Feel free to follow up with this information and I'll reopen your issue 👍

**Comment by imranbarbhuiya** [comment]
I didn't provided code sample as I think this error don't have anything to do with my code. Because getting the error `received a message from uncached channel` is coming from djs before reaching my `messageCreate` event. Also my client was initiated with these intents and partial and only a listener is added in messageCreate. 

```ts
import { Client, Intents } from 'discord.js';

const client = new Client({	intents: new Intents([		Intents.FLAGS.GUILDS,		Intents.FLAGS.GUILD_MEMBERS,		Intents.FLAGS.GUILD_MESSAGES,		Intents.FLAGS.GUILD_MESSAGE_REACTIONS,		Intents.FLAGS.GUILD_BANS,		Intents.FLAGS.GUILD_VOICE_STATES	]),	partials: ['MESSAGE', 'REACTION', 'CHANNEL'],	failIfNotExists: false});
```

I'm using a event handler and my messageCreate only contains 

```ts
if (message.author.bot || message.system || !message.inGuild() || !message.client.isReady()) {		return;	}
await automod(message)
```

The automod function isn't mutating anything so I believe it's not related to my code.

**Comment by vladfrangu** [comment]
Out of curiosity, where do you get those messages from? Can you tell me the channel type you see in Discord? Could they be coming from a forum channel?

**Comment by imranbarbhuiya** [comment]
> Out of curiosity, where do you get those messages from? Can you tell me the channel type you see in Discord? Could they be coming from a forum channel?

I've no idea as the bot is in production with 300+ servers

**Comment by pranshu05** [comment]
How can it receive message from uncached channel?

**Comment by imranbarbhuiya** [comment]
Closing as I'm no longer getting this error.

**Comment by Wazbat** [comment]
I just upgraded to discord.js `13.8.0` and I've started seeing this error fire
