### ISSUE TITLE
Slash commands API error 500 (method: get)

### ISSUE THREAD

**Issue by DevKilioZOfficiel** [discordjs/discord.js#7872]
### Which package is this bug report for?

rest

### Issue description

Hello,

I have been using the /slash commands for 5 months now, however, for the last 2/3 days I have been getting this error constantly.

```

/www/wwwroot/bot/node_modules/discord.js/src/rest/RequestHandler.js:201
        throw new HTTPError(error.message, error.constructor.name, error.status, request);
              ^

HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/www/wwwroot/bot/node_modules/discord.js/src/rest/RequestHandler.js:201:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/www/wwwroot/bot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ApplicationCommandManager.fetch (/www/wwwroot/bot/node_modules/discord.js/src/managers/ApplicationCommandManager.js:97:18)
    at async module.exports (/www/wwwroot/bot/node_modules/discord-sync-commands/index.js:12:29) {
  code: 500,
  method: 'get',
  path: '/applications/905544503258120272/commands',
  requestData: { json: undefined, files: [] }
}
```

So I don't know what to do, and there is no subject to help me with that.

Thank you,

### Code sample

```typescript


const Discord = require('discord.js');
const { SlashCommandBuilder } = require('@discordjs/builders');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const { encode } = require('html-entities');

client.commands_slashs = new Discord.Collection();

const synchronizeSlashCommands = require('discord-sync-commands');

fs.readdir("./commands/slash/", (_err, files) => {
    files.forEach((file) => {
        if (!file.endsWith(".js")) return;
        let props = require(`./commands/slash/${file}`);
        let commandName = file.split(".")[0];
        client.commands_slashs.set(commandName, {
            name: commandName,
            ...props
        });
        console.log(`👌 Command loaded: ${commandName}`);
    });
    synchronizeSlashCommands(client, client.commands_slashs.map((c) => ({
        name: c.name,
        description: c.description,
        options: c.options,
        type: 'CHAT_INPUT'
    })), {
        debug: false,
        clientId: "905544503258120272"
    });
});
```

### Package version

v13.6.0 latest

### Node.js version

16.14.2

### Operating system

Linux - Debian

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions

**Comment by S222em** [comment]
This is probably an issue with the library you use to sync the commands "discord-sync-commands", you should probably contact the author of that package.

**Comment by DevKilioZOfficiel** [comment]
Hi @S222em 
However, the moment I send this message, the api does not return any error as above and lets the bot "run".

**Comment by DevKilioZOfficiel** [comment]
If not, do you have an idea to convert the "discord-sync-commands" code via the discord.js feature?

**Comment by S222em** [comment]
> Hi @S222em 
> 
> However, the moment I send this message, the api does not return any error as above and lets the bot "run".

As the error says, the request was aborted. The library your using probably does that for some reason. The API does not actually return anything as the request is aborted

**Comment by S222em** [comment]
> If not, do you have an idea to convert the "discord-sync-commands" code via the discord.js feature?

https://discordjs.guide/creating-your-bot/creating-commands.html#registering-commands

**Comment by BubblyDisc** [comment]
Discord has some issues with there slash commands atm.

**Comment by DevKilioZOfficiel** [comment]
> Discord has some issues with there slash commands atm.

Yes, and I'm not the only one, I see a lot of developers yelling against Discord and their crappy API.

And I'm not even talking about the new restrictions added

**Comment by vladfrangu** [comment]
I don't think this is an issue with discord.js. If requests constantly time out, check out your networking. It could also very well be on Discord's side, in which case we cannot do much. Feel free to follow up if you think otherwise 👍

**Comment by DevKilioZOfficiel** [comment]
This is not my server, on the contrary, many Bot discord developers via Slash have this problem. It's a bug coming from Discord or Discord.js and not from the user. Especially since it's the Discord API that says shit in the rendering, not the developer's server, because otherwise it would be our server that would have said "timeout" or whatever.
