### ISSUE TITLE
Discord is not accepting my token through a DOTENV file.

### ISSUE THREAD

**Issue by OfflineWork** [discordjs/discord.js#7873]
### Which package is this bug report for?

discord.js

### Issue description

When trying to run the code the terminal in Visual Studio Code returns a TOKEN_INVALID error. I have to say though when debugging the code I run 'process.env' and I don't see the string BOT_TOKEN (the string name I gave to the string that holds the token) appear in the debug console. 

### Code sample

```typescript
require('dotenv'); // import dotenv


const { Client, Intents } = require('discord.js');

const myIntents = new Intents();

const client = new Client({ intents: myIntents });

client.on('ready', () => {
    console.log(`Login Complete. Welcome, ${client.user.tag}.`);
  });

 // client.on('messageCreate', msg => {
     // if (msg.content === 'Hi bob!') {
     //     msg.reply('Hello, user!')
     // }
 // })

  client.login(process.env.BOT_TOKEN); // bot token login
```

### Package version

discord.js@13.6.0

### Node.js version

v16.15.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by SuperchupuDev** [comment]
you need to `require('dotenv').config();`, the problem isn't related to discord.js

**Comment by OfflineWork** [comment]
> you need to `require('dotenv/config');` instead, the problem isn't related to discord.js

thanks
