### ISSUE TITLE
discordjs/voice TypeScript's definition "import" causes a TypeScript compilation error

### ISSUE THREAD

**Issue by DevPrice** [discordjs/discord.js#7877]
### Which package is this bug report for?

voice

### Issue description

This looks like a duplicate of [this ticket](https://github.com/discordjs/voice/issues/240) from the archived repository.

I just added a dependency on `"@discordjs/voice": "^0.9.0"` to my package.json and importing from that module.

Here is the error I get when clean building:
```
node_modules/@discordjs/voice/dist/index.d.ts(3,8): error TS1192: Module '"/home/appdir/node_modules/prism-media/typings/index"' has no default export.
node_modules/@discordjs/voice/dist/index.d.ts(4,8): error TS1259: Module '"/home/appdir/node_modules/@types/ws/index"' can only be default-imported using the 'esModuleInterop' flag
```

### Code sample

```typescript
import {
    createAudioPlayer,
    createAudioResource,
    DiscordGatewayAdapterCreator,
    entersState, getVoiceConnection,
    joinVoiceChannel,
    VoiceConnectionStatus
} from "@discordjs/voice"
```

### Package version

discord.js@13.6.0, @discordjs/voice@0.9.0

### Node.js version

node v16.15.0, typescript@4.6.4

### Operating system

Alpine

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by c43721** [comment]
You need to enable the `esModuleInterop` tsconfig flag. This is not a djs issue as I am able to build my code just fine with this flag enabled.

**Comment by DevPrice** [comment]
I see the same issue when I set that flag to true.

**Comment by S222em** [comment]
The first error is not a issue with discord.js

The second error you should be gone after you set the flag to true in your tsconfig
