### ISSUE TITLE
Slash Commands not visible

### ISSUE THREAD

**Issue by lkaesberg** [discordjs/discord.js#7878]
### Which package is this bug report for?

discord.js

### Issue description

Since yesterday, the slash commands aren't visible anymore. Discord server that used the bot for longer still have access to the commands, but new ones only see 1 of 15 commands, and they all have default permissions.  I didn't change anything in that time, and Discord announced that they changed something with the slash commands. All the commands show up in the new integrations tab and should be usable by anyone. But even the owner of the server cant even see them.

![image](https://user-images.githubusercontent.com/33939116/166455999-e7d39a98-3f0a-4655-be63-079e9e8bbb8b.png)

![image](https://user-images.githubusercontent.com/33939116/166456031-94600859-385b-46f2-88c3-5303cc67d34f.png)

### Code sample

```typescript
module.exports = {
    data: new SlashCommandBuilder().setDefaultPermission(true).setName('verify').setDescription('verify on the server'),
    async execute(interaction) {
        await sendVerifyMessage(interaction.guild, interaction.user, null, null, userGuilds, true)
        await interaction.reply({ content: '📝', ephemeral: true })
    }
}

bot.commands = new Discord.Collection();
const commandFiles = fs.readdirSync('./src/commands').filter(file => file.endsWith('.js'));
const commands = []

for (const file of commandFiles) {
    const command = require(`./commands/${file}`);
    bot.commands.set(command.data.name, command);
    commands.push(command.data.toJSON())
}

rest.put(Routes.applicationGuildCommands(clientId, guild.id), {body: commands})
        .then(() => console.log('Successfully registered application commands.'))
        .catch(async () => {})
```

### Package version

13.6

### Node.js version

16.15

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers, GuildMessages

**Comment by megatank58** [comment]
This seems to be currently an issue with guild commands and it's from discord's side, a workaround is to disable and re-enable the permission for one of the commands in the integration menu.
