### ISSUE TITLE
Race Condition when Adding Roles (Adding Roles becomes "Replace Roles" instead)

### ISSUE THREAD

**Issue by mrjackyliang** [discordjs/discord.js#7879]
### Which package is this bug report for?

discord.js

### Issue description

When adding a role, Discord.js **disregards additional roles added after** the current add role event is run and instead replaces them with the roles that were **current** at that time. Not sure how I can show code examples (because the issue involves two bots, one is DSB and the other one from Memberful, but I can show you what I see from my debugger, step by step.

To replicate this, you would need to have a Memberful Pro account (a non-paid version can be signed up to test) and that account needs to integrate with the Discord server you're about to test on. The Gold and Platinum plans are in **one plan family**.

**Bots Involved for Reference ONLY**
[DSB](https://github.com/mrjackyliang/discord-stonker-bot) (uses Discord.js)
[Memberful Bot](https://memberful.com/help/integrations/community/discord-integrate/)

**Roles Involved for Reference ONLY**
Basic - `841111442128371712`
Gold - `844316656582000680`
Platinum - `844286730583801858`
@ everyone - `840936982951886887`

### Step 1:
Start the user with a Gold role (`844316656582000680`). __The user should already be signed up to the Gold plan in Memberful.__

### Step 2:
Upgrade the user to Platinum in Memberful, where the Memberful bot removes the Gold role (`844316656582000680`).

### Step 3:
**This is where the race condition starts.** When the Gold role (`844316656582000680`) is removed, the user is left with no roles. Then an event starts from DSB to add the Basic role (`841111442128371712`). At this time, the cache only states that the user has the @ everyone (`840936982951886887`) role.

<img width="1830" alt="Screen Shot 2022-05-03 at 11 49 42 AM" src="https://user-images.githubusercontent.com/9779803/166489647-2e9e8e7a-148b-4100-96c6-4f060b0d4856.png">

### Step 4:
Memberful proceeds to add the Platinum role (`844286730583801858`) to the user.

<img width="678" alt="Screen Shot 2022-05-03 at 11 56 51 AM" src="https://user-images.githubusercontent.com/9779803/166489938-793c29b4-bcfa-4006-9c45-8dd2e76dd7ff.png">

### Step 5:
DSB runs the `add` method from `GuildMemberRoleManager` and proceeds to replace the role added in Step 4. Notice how there isn't a Platinum role (`844286730583801858`) in the `newRoles` constant?

<img width="1825" alt="Screen Shot 2022-05-03 at 11 59 43 AM" src="https://user-images.githubusercontent.com/9779803/166490738-03f2f0be-fc3c-44ff-9ac9-cd0677587d33.png">

### Package version

13.6.0

### Node.js version

16.13.2 (typescript 4.6.3)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by Jiralite** [comment]
It seems obvious what the issue is here. Two bots are trying to modify a guild member's roles upon an event, independent of each other. I don't see this as a discord.js issue at all, but a problem with the two bots instead.

**Comment by mrjackyliang** [comment]
So let's say in my instance since I write the code for DSB, how would I fix it on my side? Right now the role changes are based on events happening with role changes. I know that adding a timeout wouldn't solve the problem because the cached roles are still pulled in

**Comment by tipakA** [comment]
Implementing a timeout *would* actually solve it. The issue comes primarly from the fact that without any timeout, both bots act on current (equal) cache, each one adding a different role. Discord.js does update cache upon receiving events, which means that if you wait "long enough" to receive an event about member having roles updated by a different bot, calling `add` after that will not produce any issues, as the `add` will work with cache that already includes the role given by the other bot.

**Comment by mrjackyliang** [comment]
> Implementing a timeout *would* actually solve it. The issue comes primarly from the fact that without any timeout, both bots act on current (equal) cache, each one adding a different role. Discord.js does update cache upon receiving events, which means that if you wait "long enough" to receive an event about member having roles updated by a different bot, calling `add` after that will not produce any issues, as the `add` will work with cache that already includes the role given by the other bot.

I was thinking last night about this issue and timeouts solved it actually!

Here's were it get's confusing for me. If I pre-define the `GuildMemberRoleManager` before the timeouts, would that also set the `cache` that's inside it? It's nerve racking to think about it because I have code inside the callback that resolves the member and somehow I feel like it's so unnecessary and bulky.

**Comment by mrjackyliang** [comment]
> > If I pre-define the GuildMemberRoleManager before the timeouts, would that also set the cache that's inside it? It's nerve racking to think about it because I have code inside the callback that resolves the member and somehow I feel like it's so unnecessary and bulky.
> 
> As long as the member isn't removed from the cache, the cache belonging to the manager will remain updated. If I'm not wrong, members don't get uncached normally, only if you've used a `CacheFactory` to override the default cache

Wow, it does work. Hah! I removed all the bulky code, thanks everyone who chipped in to help!
