### ISSUE TITLE
One Command Registers Only

### ISSUE THREAD

**Issue by Lukas-Batema** [discordjs/discord.js#7881]
### Which package is this bug report for?

discord.js

### Issue description

First, create two (or more) command files, then try to deploy them (after adding all other necessary code and files), to a container hosting service, like Railway.app (where I am getting this error, have not tried anywhere else), You'll see only one out of however many commands you registered will show up, without any errors, and in my case, it logs successfully registered commands.

![Screenshot 2022-05-04 11 33 21 AM](https://user-images.githubusercontent.com/55695493/166717340-7e6d3ae3-0a45-46f5-916d-4f6961bb9c2e.png)

**server-info.js**
```js
const { SlashCommandBuilder } = require(`@discordjs/builders`);
const { MessageEmbed } = require(`discord.js`);

module.exports = {
  data: new SlashCommandBuilder()
    .setName(`server`)
    .setDescription(`Display info about this server!`),
  async execute(interaction) {
    const serverInfo = new MessageEmbed()
      .setColor(`BLACK`)
      .setTitle(`**Server Info**`)
      .addFields(
        { name: `Server name:`, value: `${interaction.guild.name}`, inline: true },
        { name: `Total members:`, value: `${interaction.guild.memberCount}`, inline: true },
      )
      .setThumbnail(interaction.guild.iconURL())
      .setFooter(`Bot Creator: BatemaDevelopment#0019 | BatemaDevelopment | Lukas Batema`)
      .setTimestamp();

    interaction.reply({ embeds: [serverInfo] });
  },
};
```

**user-info.js**
```js
const { SlashCommandBuilder } = require(`@discordjs/builders`);
const { MessageEmbed } = require(`discord.js`);

module.exports = {
  data: new SlashCommandBuilder()
    .setName(`user`)
    .setDescription(`Display info about yourself!`),
  async execute(interaction) {
    const userInfo = new MessageEmbed()
      .setColor(`BLACK`)
      .setTitle(`**User Info**`)
      .addFields(
        { name: `Your username:`, value: `${interaction.user.tag}`, inline: true },
        { name: `Your ID:`, value: `${interaction.user.id}`, inline: true },
      )
      .setThumbnail(interaction.user.displayAvatarURL())
      .setFooter(`Bot Creator: BatemaDevelopment#0019 | BatemaDevelopment | Lukas Batema`)
      .setTimestamp();

    interaction.reply({ embeds: [userInfo] });
  },
};
```

### Package version

v13.6.0

### Node.js version

v16.14.2

### Operating system

Dockerised Alpine 3.15

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by AimFlying** [comment]
Hi !
This is not a discord.js issue, but a Discord issue. I already reported it and it will be fixed soon ^-^
We have this beg since the new Applications Commands
Goodbye !

**Comment by Lukas-Batema** [comment]
bruh

**Comment by AimFlying** [comment]
I have it too. I just asked in discord-js and someone tell me that was a Discord issue, I just reported the bug

**Comment by Lukas-Batema** [comment]
Idc anyways, time to learn discord.py

**Comment by S222em** [comment]
This is the exact issue you are having: discord/discord-api-docs#4856 you should follow that issue and close this one.

**Comment by Lukas-Batema** [comment]
I think I already closed this issue bruh

**Comment by Lukas-Batema** [comment]
Thanks tho

**Comment by Lukas-Batema** [comment]
> This is the exact issue you are having: [discord/discord-api-docs#4856](https://github.com/discord/discord-api-docs/issues/4856) you should follow that issue and close this one.

It worked, thanks.
