### ISSUE TITLE
Proprety for the full contentent of a slash command on CommandInteraction

### ISSUE THREAD

**Issue by Confuze** [discordjs/discord.js#7903]
### Which package is the feature request for?

discord.js

### Feature

Let's say a bot has a ban slash command that accepts two parameters: the guild member to ban (mention) and a reason (string). A user could use it like that: `/ban @foo#1234 foo did bar`. Currently, it's very difficult to get the full content of a command as such - there is no property for that and you'll end up with a pile of unnecessary code where you first get the command name check for subcommand groups and subcommands and then loop through all the options and take their value.

### Ideal solution or implementation

I think a property or method that would return the whole content of a given command interaction as a string would be really useful. Just something that would give you the whole command (like `/ban @foo#1234 foo did bar` in the example).

**Comment by imranbarbhuiya** [comment]
I don't think that will be helpful at all. Also why using a loop. You can use `getUser` to get the user and `getString` to get the reason. U only need these 2 methods, no loop or subcmd is needed for your example cmd (`ban`).

**Comment by Jiralite** [comment]
[This already exists](https://discord.js.org/#/docs/discord.js/main/class/ChatInputCommandInteraction?scrollTo=toString).

**Comment by Confuze** [comment]
> [This already exists](https://discord.js.org/#/docs/discord.js/main/class/ChatInputCommandInteraction?scrollTo=toString).

Oh, thank you very much for that! When looking at the docs, I only checked the CommandInteraction class - my bad, thanks again.
