### ISSUE TITLE
FIx Typings in Channel.send options "embed" => "embeds"

### ISSUE THREAD

**Issue by Fanisus** [discordjs/discord.js#7927]
### Which package is this bug report for?

discord.js

### Issue description

message.channel.send({embed: []})   This typing are shown
message.channel.send({embeds: []}) Whereas that should be this

### Code sample

```typescript
Just a typo 
let embed = new discord.MessageEmbed().setTitle("This won't work lol")
message.channel.send({embed: [embed]}) // Doesn't work
message.channel.send({embeds: [embed]}) // Works
```

### Package version

Latest. I think v14

### Node.js version

16.13.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

**Comment by almeidx** [comment]
"Latest. I think v14" is, of course, *not* the output of "npm ls discord.js", as was requested in the bug issue template.

Regardless, cannot replicate in both `13.7.0` and `14.0.0-dev.1652573522-7ce641d`

**Comment by Fanisus** [comment]
Sorry it is v13.7.0
I didn't know v14 was dev

**Comment by almeidx** [comment]
The typings for 13.7.0:
https://github.com/discordjs/discord.js/blob/e3cbd45e7de069432818148b9dedda03f630f9f7/typings/index.d.ts#L5394

**Comment by Fanisus** [comment]
I meant in code

**Comment by Fanisus** [comment]
Weird. Please close 

Sorry
