### ISSUE TITLE
GuildInviteManager not updated with respect to ChannelDeleteAction/GuildChannelManager

### ISSUE THREAD

**Issue by g1xb17** [discordjs/discord.js#7930]
### Which package is this bug report for?

discord.js

### Issue description

Discord.js@13.2.0

Steps to reproduce:
Have access to see Invites broadly on a bot, make sure you're seeing the data change on the guild.

1. Create a channel
2. Create an invite on that channel
3. Note whether or not the invite registered in the guild.invites.cache (It should)
4. Delete the Channel
5. Check to see if guild.invites.cache is updated after the event

Its possible I'm doing something wrong, but, My thoughts are that if you were to fetch the invites the cache should update to remove the missing entries. 

### Code sample

```typescript
client.on('channelDelete', (channel) => {
    if (channel instanceof Discord.GuildChannel) {
      console.log("Before:", channel.guild.invites.cache.toJSON().map(invite => invite.code));
      channel.guild.invites.fetch().then(invites => {
        console.log("Fetched:", invites.toJSON().map(invite => invite.code))
        console.log("After:", channel.guild.invites.cache.toJSON().map(invite => invite.code))
      })
    }
  })
```

### Package version

13.2.0

### Node.js version

16.14.2

### Operating system

Windows And Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping

**Comment by Jiralite** [comment]
I am able to reproduce this. It seems obvious this is the case:

https://github.com/discordjs/discord.js/blob/7ce641d33a4af6586d5e7beffbe7d38619dcf1a2/packages/discord.js/src/client/actions/ChannelDelete.js#L11-L19

https://github.com/discordjs/discord.js/blob/7ce641d33a4af6586d5e7beffbe7d38619dcf1a2/packages/discord.js/src/managers/ChannelManager.js#L61-L66

I would say this is a bug and should be rectified.
