### ISSUE TITLE
Removfe Timeout & Timeout Members Permission Flag

### ISSUE THREAD

**Issue by HideakiAtsuyo** [discordjs/discord.js#7936]
### Which package is the feature request for?

discord.js

### Feature

[Timeout](https://discord.js.org/#/docs/discord.js/stable/class/GuildMember?scrollTo=timeout)

Well the timeout is there, but what about a option to REMOVE the timeout ? It would be good since Discord already provide it !

Like this we can make something like "untimeout" command (bad name lmao)

And also add a TIMEOUT_MEMBERS flag since it's not present

### Ideal solution or implementation

If a user is in timeout restrictions it should remove the user timeout.

**Comment by monbrey** [comment]
> Provide null to remove the timeout

Any developer can make their own "untimeout" command to do this

**Comment by HideakiAtsuyo** [comment]
> > Provide null to remove the timeout
> 
> Any developer can make their own "untimeout" command to do this
> 
> EDIT to address your edit: The flag is MODERATE_MEMBERS. That's what Discord called it.

Oh thanks for this answer :)

**Comment by HideakiAtsuyo** [comment]
> MODERATE_MEMBERS

Well I guess you completelly solved my problems lol thanks
