### ISSUE TITLE
has VIEW_GUILD_INSIGHTS permission been removed? "invalid permission(s) provided" when used

### ISSUE THREAD

**Issue by the-vampiire** [discordjs/discord.js#7944]
### Which package is this bug report for?

discord.js

### Issue description

> steps to reproduce

1. add the `VIEW_GUILD_INSIGHTS` permission
2. try installing the bot using the generated link
3. get invalid permission(s)

<img width="317" alt="image" src="https://user-images.githubusercontent.com/25523682/169105954-4acbff25-c68d-4c75-84bb-2d9c53590d47.png">

> info

this permission is also not available on discord dev portal 

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/25523682/169105903-028d6926-6ae3-4bd8-97b3-6301c364a37a.png">

> resolution

removing `VIEW_GUILD_INSIGHTS` permission fixes the install link

has this permission been removed? could not find anywhere in djs or discord official statements about it.

### Code sample

```typescript
import {
  Client,
  Intents,
  Interaction,
  InviteScope,
  Permissions,
} from "discord.js";

const { DISCORD_BOT_TOKEN } = process.env;

export const discordClient = new Client({ intents: new Intents("GUILDS") });

export const botScopes: InviteScope[] = ["bot", "applications.commands"];

export const minimumChannelPermissions = new Permissions().add([
  "VIEW_CHANNEL",
  "SEND_MESSAGES", // read messages/view channels
  "MANAGE_CHANNELS", // to control slow mode
  "EMBED_LINKS",
  "ATTACH_FILES",
  "ADD_REACTIONS",
  "USE_APPLICATION_COMMANDS", // use slash commands
]);

export const globalGuildPermissions = new Permissions()
  // NOTE: no longer available?
  .add("VIEW_GUILD_INSIGHTS") // view server insights
  .add(minimumChannelPermissions);

export const requiredInviteScopesAndPermissions = {
  scopes: botScopes,
  permissions: globalGuildPermissions,
};

discordClient
  .login(DISCORD_BOT_TOKEN)
  .then(() =>
    console.log(
      discordClient.generateInvite(requiredInviteScopesAndPermissions),
    ),
  );
```

### Package version

13.6.0

### Node.js version

v16.14.0

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by almostSouji** [comment]
Discord does no longer allow bots to request permissions that the bot has no use for.

**Comment by almostSouji** [comment]
The permission still exists and can be read from users, it's just that you cannot ask for it in the simplified bot invite oauth2; as you see, Discord rejects it. Discord.js just propagates the permission bitfield you construct. The `Permissions` bitfield wrapper is not just used for invites and still needs to support the flags.

**Comment by almostSouji** [comment]
I am not too sure how that "broke your deployment". If you mean that people cannot invite the bot with your provided link: the permissions you supply in the invite link are a mere suggestion, everyone can re-compute those permission bitfields and pass them into the URL as they wish (including `0` or any invalid bitfield including the invalid permissions).

While we could technically subtract the affected flags, I'm not sure how useful and maintainable of a change this is in the long run, if Discord adds more permissions or changes bot behavior again. These things are not really considered breaking API changes.
