### ISSUE TITLE
Messages typings in DM

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#7956]
### Which package is this bug report for?

discord.js

### Issue description

Actually, working with DM messages (that can not satisfy the condition `inCachedGuild()`) is a pain in the ass since we have all API*** typings (like APIMessage).

![image](https://user-images.githubusercontent.com/29425008/169628535-69d903a1-aec5-4338-a12a-84408a1fdfb9.png)

After multiple tests, I never got a raw message identical to the APIMessage interface, is it possible ?
*Looks like that the only way to have a APIMessage is to not have a cached dm channel*

It would be nice (if the APIMessage is a structure that we can get in DM) if we could have a method to exclude this type of Typing.

### Code sample

```typescript
import { Client, IntentsBitField, Interaction } from 'discord.js';
const client = new Client({
    intents: IntentsBitField.Flags.DirectMessages,
});
client.on('interactionCreate', async (interaction: Interaction) => {
    if (!interaction.isMessageComponent()) return;
    const message = interaction.message;
    if (message.deletable) await message.delete();
});
```

### Package version

main

### Node.js version

v16.13.2 (typescript v4.6.4)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by suneettipirneni** [comment]
You'll only receive `APIMessage`s when you only use an application for application commands and not a bot. This will most likely be added & addressed in #7917, where we'll always return `Message` instance regardless of the context.
