### ISSUE TITLE
not logging dm messages (not sure if bug or just isnt added)

### ISSUE THREAD

**Issue by adamblol** [discordjs/discord.js#7959]
### Which package is this bug report for?

discord.js

### Issue description

when i log messages and type in a dm it doesnt log 

### Code sample

```typescript
console.log(message.content)
```

### Package version

npm install discord.js-selfbot

### Node.js version

latest

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by MDCYT** [comment]
Have you tried putting this partial?
```javascript
const client = new Discord.Client({
    partials: ["CHANNEL"]
});
```

**Comment by adamblol** [comment]
i just tried and its still not logging dms

**Comment by adamblol** [comment]
i tried a few dms it only logged from 1 of them

**Comment by Raiden-Ei** [comment]
Selfbot is not supported and it's against Discord ToS
