### ISSUE TITLE
Discord Modal Function

### ISSUE THREAD

**Issue by mazk5145** [discordjs/discord.js#7960]
### Which package is the feature request for?

discord.js

### Feature

I have been working on Discord Bot and what I really would like is that Discord **Modals** could support Checkboxes or Selection Boxes. 

and well, it would give users a chance to select between questions where you don't want to have text boxes.

### Ideal solution or implementation

implementation for discord.js modals would be that the message actionrow could support checkboxes.

### Alternative solutions or implementations

I’ve already tried typing in a text box, but it would be a lot nicer and easier than you could just choose what you want.

### Other context

![example](https://user-images.githubusercontent.com/79049205/169713538-1eed416f-889d-40be-963d-68df9af612da.png)

**Comment by Jiralite** [comment]
discord.js cannot implement what doesn't exist. Suggest your idea over to https://github.com/discord/discord-api-docs.

**Comment by mazk5145** [comment]
> discord.js cannot implement what doesn't exist. Suggest your idea over to https://github.com/discord/discord-api-docs.

Okay thanks for the information, i have never used these feature requests before.
and i will do that.

I will hope that you will have an awesome day.

**Comment by vladfrangu** [comment]
Per @Jiralite's comment, I will be closing this. Follow up once/if Discord adds this feature :D
