### ISSUE TITLE
Unhandled 'error' event: "WebSocket was closed before the connection was established" when client was connected and network goes down

### ISSUE THREAD

**Issue by crycode-de** [discordjs/discord.js#7964]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce:
1. Create a very simple bot like the code sample below
2. Let the bot connect to discord
3. Destroy the network/internet connection of the machine running the script (e.g. unplug the (virtual) network cable)
4. Wait until the bot tries to reconnect
5. See the app crashes on an unhandled 'error' event
```
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/peter/tmp/node_modules/ws/lib/websocket.js:285:14)
    at WebSocketShard.destroy (/home/peter/tmp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:728:27)
    at Timeout.<anonymous> (/home/peter/tmp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:522:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/peter/tmp/node_modules/ws/lib/websocket.js:984:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Full log: [log.txt](https://github.com/discordjs/discord.js/files/8757431/log.txt)

There seams to be no way to handle the WebSocket error event.

Expected behavior would be, that discord.js keeps trying to reestablish the connection, or that there is some chance to handle the error.

Came up with this, as my internet connection was gone away and my application using discord.js crashed with the above error.

### Code sample

```typescript
const { Client, Intents } = require('discord.js');

const token = 'xxx';

async function main () {
  const client = new Client({
    intents: [
      Intents.FLAGS.GUILDS,
    ],
  });

  client.on('debug', console.debug);
  client.on('warn', console.warn);
  client.on('error', console.error);

  client.on('ready', () => console.log('ready'));

  await client.login(token);
}

main();
```

### Package version

13.7.0

### Node.js version

16.14.2

### Operating system

Debian 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by IxPrumxI** [comment]
i don't think you even replugged the network again as you didn't mention it, so why would this be a bug?

**Comment by kyranet** [comment]
I must ask, are you able to reproduce this with v14?

We are attaching [`ws.onerror`](https://github.com/discordjs/discord.js/blob/fdeac9d9fba06c532eca296ddd8479047bc732bf/packages/discord.js/src/client/websocket/WebSocketShard.js#L259-L263) along other events, but it seems that `ws` is doing a couple of extra steps:

- `emitErrorAndClose`: https://github.com/websockets/ws/blob/a690791df31cede48e7bcbce9d56411483309246/lib/websocket.js#L989
- `abortHandshake`: https://github.com/websockets/ws/blob/a690791df31cede48e7bcbce9d56411483309246/lib/websocket.js#L1050
- `close`: https://github.com/websockets/ws/blob/a690791df31cede48e7bcbce9d56411483309246/lib/websocket.js#L284-L285

And for reference, `onclose` should be all that's necessary:

- https://github.com/websockets/ws/blob/a690791df31cede48e7bcbce9d56411483309246/lib/websocket.js#L574-L603

**Comment by crycode-de** [comment]
Same error with v14 (14.0.0-dev.1653091711-fdeac9d)

Example code:
```js
const { Client, GatewayIntentBits  } = require('discord.js');

const token = 'xxx';

async function main () {
  const client = new Client({
    intents: [
      GatewayIntentBits.Guilds,
    ],
  });

  client.on('debug', console.debug);
  client.on('warn', console.warn);
  client.on('error', console.error);

  client.on('ready', () => console.log('ready'));

  await client.login(token);
}

main();
```

Log: [log-v14.txt](https://github.com/discordjs/discord.js/files/8760923/log-v14.txt)

**Comment by imranbarbhuiya** [comment]
ig it's remated to https://github.com/discordjs/discord.js/pull/7581

**Comment by legendhimslef** [comment]
> ig it's related to #7581

umm, I don't think so. Why? Because during close code 4009 it won't execute the else block, Since the above `if` statement is true.
I think cleaning up the during onClose event is better and should be removed from `destroy` method. Anyways my pr auto emits the onClose if the close frame wasn't received due to any issue so cleanup will happen.

**Comment by crycode-de** [comment]
Changing to `process.nextTick(() => this._cleanupConnection());` leads to an other error, since `this.connection` is `null` on the next tick:
<details>
<summary>Logs</summary>

```
[WS => Shard 0] [HeartbeatTimer] Didn't receive a heartbeat ack last time, assuming zombie connection. Destroying and reconnecting.
    Status          : READY
    Sequence        : 1
    Connection State: OPEN
[WS => Shard 0] [DESTROY]
    Close Code    : 4009
    Reset         : true
    Emit DESTROYED: true
[WS => Shard 0] Clearing the heartbeat interval.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] WS State: CLOSED
/home/peter/tmp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:769
    this.connection.onopen = this.connection.onclose = this.connection.onerror = this.connection.onmessage = null;
                                                                                                           ^

TypeError: Cannot set properties of null (setting 'onmessage')
    at WebSocketShard._cleanupConnection (/home/peter/tmp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:769:108)
    at /home/peter/tmp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:731:37
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
</details>


If I remove the call of `this._cleanupConnection()` it seams to work and tries reconnect every 5 seconds, but don't know if this might lead to other issues:
<details>
<summary>Logs</summary>

```
[WS => Shard 0] [HeartbeatTimer] Didn't receive a heartbeat ack last time, assuming zombie connection. Destroying and reconnecting.
    Status          : READY
    Sequence        : 1
    Connection State: OPEN
[WS => Shard 0] [DESTROY]
    Close Code    : 4009
    Reset         : true
    Emit DESTROYED: true
[WS => Shard 0] Clearing the heartbeat interval.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] WS State: CLOSED
[WS => Shard 0] Failed to connect to the gateway, requeueing...
[WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] WS State: CLOSED
[WS => Shard 0] Failed to connect to the gateway, requeueing...
[WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] WS State: CLOSED
[WS => Shard 0] Failed to connect to the gateway, requeueing...
[WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CLOSE]
    Event Code: 1006
    Clean     : false
    Reason    : 
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] WS State: CLOSED
[WS => Shard 0] Failed to connect to the gateway, requeueing...
[WS => Manager] Shard Queue Size: 1; continuing in 5 seconds...
[WS => Shard 0] [CONNECT]
```
</details>

**Comment by legendhimslef** [comment]
@crycode-de 
I tried to recreate this issue but I am failing to recreate the exact same thing. With djs v13.7.0 it reconnects perfectly fine after i plug/unplug. Also can you please try to replicate this issue using my pr?

You can download it from here
npm => `npm install github:legendhimslef/discord.js#v13`
yarn => `yarn install github:legendhimslef/discord.js#v13`

**Comment by crycode-de** [comment]
@legendhimslef 
Using your PR #7581 seams to work fine. The error then gets emitted as `shardError` and a reconnect is queued. 👍

**Comment by fredkilbourn** [comment]
I just had this same error today using discord.js 13.8.0:
```
Uncaught Exception:
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:285:14)
    at WebSocketShard.destroy (/home/vbot/srv/vbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:806:27)
    at WebSocketShard.onClose (/home/vbot/srv/vbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:370:12)
    at WebSocket.onClose (/home/vbot/srv/vbot/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:526:28)
    at WebSocket.emitClose (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:258:10)
    at Receiver.receiverOnFinish (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:1158:20)
    at Receiver.emit (node:events:526:28)
    at finish (node:internal/streams/writable:754:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by legendhimslef** [comment]
> I just had this same error today using discord.js 13.8.0:
> 
> ```
> Uncaught Exception:
> Error: WebSocket was closed before the connection was established
>     at WebSocket.close (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:285:14)
>     at WebSocketShard.destroy (/home/vbot/srv/vbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:806:27)
>     at WebSocketShard.onClose (/home/vbot/srv/vbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:370:12)
>     at WebSocket.onClose (/home/vbot/srv/vbot/node_modules/ws/lib/event-target.js:210:18)
>     at WebSocket.emit (node:events:526:28)
>     at WebSocket.emitClose (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:258:10)
>     at Receiver.receiverOnFinish (/home/vbot/srv/vbot/node_modules/ws/lib/websocket.js:1158:20)
>     at Receiver.emit (node:events:526:28)
>     at finish (node:internal/streams/writable:754:10)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```

This pr might help you: https://github.com/discordjs/discord.js/pull/8082
We might have this in 13.8.1

**Comment by fredkilbourn** [comment]
Thanks!

**Comment by wdfeww** [comment]
same on 13.8.1 :(

**Comment by legendhimslef** [comment]
> same on 13.8.1 :(
> 
> ```
> node:events:505
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: WebSocket was closed before the connection was established
>     at WebSocket.close (/root/fs-dc/node_modules/ws/lib/websocket.js:285:14)
>     at WebSocketShard.destroy (/root/fs-dc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:806:27)
>     at WebSocketShard.onClose (/root/fs-dc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:370:12)
>     at WebSocket.onClose (/root/fs-dc/node_modules/ws/lib/event-target.js:210:18)
>     at WebSocket.emit (node:events:527:28)
>     at WebSocket.emitClose (/root/fs-dc/node_modules/ws/lib/websocket.js:258:10)
>     at Receiver.receiverOnFinish (/root/fs-dc/node_modules/ws/lib/websocket.js:1158:20)
>     at Receiver.emit (node:events:527:28)
>     at finish (node:internal/streams/writable:754:10)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> Emitted 'error' event on WebSocket instance at:
>     at emitErrorAndClose (/root/fs-dc/node_modules/ws/lib/websocket.js:993:13)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```

steps to recreate?

**Comment by imranbarbhuiya** [comment]
https://github.com/discordjs/discord.js/pull/8164 will fix it

**Comment by legendhimslef** [comment]
> https://github.com/discordjs/discord.js/pull/8164 will fix it

wait whats the point of silencing errors. We already have issues with socket hangups.

**Comment by imranbarbhuiya** [comment]
u can read https://github.com/discordjs/discord.js/pull/8150 description

**Comment by ASHISHKUMAR2411** [comment]
```ConnectTimeoutError: Connect Timeout Error
at Timeout.onConnectTimeout [as _onTimeout] (D:\path\smart_contracts\node_modules\undici\lib\core\connect.js:108:24)
at listOnTimeout (node:internal/timers:559:11)
at processTimers (node:internal/timers:500:7) {
code: 'UND_ERR_CONNECT_TIMEOUT'
}```
I am trying to deploy my smart contract on alchemy using rinkeby testnet `npx hardhat verify --network rinkeby address`

**Comment by iCrawl** [comment]
@pedroricardo Do you have an error handler attached to your client?

```js
client.on('error', console.error);
```

**Comment by pedroricardo** [comment]
@iCrawl I do not have

**Comment by SpaceEEC** [comment]
The stacktrace suggests that you are running 13.4.0 (or even older): Please make sure you are actually running `13.9.2` where this issue should no longer occur.

**Comment by iCrawl** [comment]
@pedroricardo Additionally to the thing above, please also have an error handler like I showed.
