### ISSUE TITLE
userUpdate not emitted when profile is changed only when removed or set from a removed state.

### ISSUE THREAD

**Issue by mah51** [discordjs/discord.js#7967]
### Which package is this bug report for?

discord.js

### Issue description

1. Listen for userUpdate.
2. Change user profile -> No event emitted
3. remove profile -> Event emitted
4. add profile after removing -> event emitted

### Package version

13.7.0

### Node.js version

17.8.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages

**Comment by Jiralite** [comment]
This needs to be more specific. What are you changing in the user profile?

**Comment by mah51** [comment]
I am not doing anything, I am listening for the userUpdate event and the issue is it isn't emitted when the user changes their profile picture. Only when it is removed or added from a removed state.

**Comment by mah51** [comment]
I forgot to mention that this still ocurrs when I have the USER and GUILD_MEMBER partials allowed

**Comment by Jiralite** [comment]
> I am not doing anything, I am listening for the userUpdate event and the issue is it isn't emitted when a cached user changes their profile picture. Only when it is removed or added from a removed state.

I cannot reproduce this. A cached user changing their avatar icon emits the event for me logs fine for me on 13.x and 14.x:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/33201955/173033061-53d4239e-4995-4584-b7ba-b9697f42b70a.png">

> 1. Listen for userUpdate.
> 2. Change user profile -> No event emitted
> 3. remove profile -> Event emitted
> 4. add profile after removing -> event emitted

These steps seem to indicate you want to subscribe to partial events, but a latter comment states you have already tried this. In these steps, you will not get that initial event as the user was uncached. I am also unable to reproduce this. Basically, I am not able to reproduce anything here.
