### ISSUE TITLE
v13.7.0 Modals - console.log() issue

### ISSUE THREAD

**Issue by xkasprx** [discordjs/discord.js#7971]
### Which package is this bug report for?

discord.js

### Issue description

Inside `interactionCreate` event listener:

if (interaction.isModalSubmit()) {
    const modalID = interaction.customId;
    console.log(true);
    // this will not fail
    if (modalID === 'someCustomID') {
        console.log(false);
        // this will fail
    }
![image](https://user-images.githubusercontent.com/71482506/170426488-8e9d9b7e-9b83-4665-b175-02f759eb120c.png)

}

### Code sample

```typescript
if (interaction.isModalSubmit()) {
const modalID = interaction.customId;
console.log(true);
// this will not fail
if (modalID === 'someCustomID') {
console.log(false);
// this will fail
}
```

### Package version

13.7.0

### Node.js version

17.6.0

### Operating system

Windows and CentOS 7

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, GuildScheduledEvents

### I have tested this issue on a development release

68d5169

**Comment by monbrey** [comment]
Your code sample is nothing like the screenshot, in which you defined your own `console` variable which shadows the global console. Absolutely not related to discord.js

**Comment by xkasprx** [comment]
How did I define my own console variable?

**Comment by xkasprx** [comment]
OMG im an idiot
sorry

**Comment by xkasprx** [comment]
I did not even notice that lol
