### ISSUE TITLE
Fetch interaction by token

### ISSUE THREAD

**Issue by tnthung** [discordjs/discord.js#7972]
### Which package is the feature request for?

discord.js

### Feature

As Discord documented:
`GET/webhooks/<application.id>/<interaction.token>/messages/@original`

With this endpoint, we can fetch the original message of the interaction.
It would be nice to fetch interaction from the `Client` directly.

### Example
```ts
...

let token = "pre-stored value"

client.on("someEvent", async _ => {
  // fetch the interaction from token
  const inter = await client.fetchInteraction(token)

  ...
})
```

### Ideal solution or implementation

Add the `fetchInteraction` method under the `Client`

### Alternative solutions or implementations

Manually fetch thought API requests then construct `Interaction`.

**Comment by advaith1** [comment]
That endpoint returns an original interaction response message, **not** an interaction. The API does not have a way to fetch an interaction; interactions are only sent in the event when they happen.

**Comment by tnthung** [comment]
But with the token, supposedly we are able to modify, delete, etc the interaction.
So a wrapper can be created, isn't it? Maybe my example is not that accurate, but
it shows some hint about this I guess.

**Comment by monbrey** [comment]
You are fetching a message which was a response to an interaction. It's just terminology.

You can do this with the `InteractionWebhook` class already.
