### ISSUE TITLE
Discord bot 'interactionCreate' listener responded a few times, then quit responding without changes in the code

### ISSUE THREAD

**Issue by POsten040** [discordjs/discord.js#7975]
### Which package is this bug report for?

discord.js

### Issue description

* UPDATE: 
- using `require` syntax seems to work for importing event and command files as described in the tutorial. But using ES6 `import` syntax does not seem to register the slash commands properly. 5/31/22

OS Windows 11
#### Versions:
* Node.js : v16.13.0
* npm : 8.1.0
* discord.js : ^13.7.0
#### Scopes:
* applications.commands
* bot
#### Bot permission:
* administrator

I was able to register the slash commands and get the success message, then /ping the bot in my server and get a response. I committed and walked away, and now it is no longer responding to interactionCreate at all. I did not change any of the code for registering slash commands or adding commands to the client that I am aware of.  

### Code sample

```typescript
//the below code is deploys the commands and appears to run without errors
import dotenv from"dotenv";
import { pathToFileURL, fileURLToPath } from 'url';
import fs from 'node:fs';
import path from 'node:path';
import { REST } from '@discordjs/rest';
import { Routes } from 'discord-api-types/v9';

dotenv.config();
const clientId = process.env.clientId;//bot id
const guildId = process.env.guildId;//server id
const token = process.env.token;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.mjs'));

const register = async (commandsPath, commandFiles) => {
  const commands = [];
  for (const file of commandFiles) {
    const filePath = path.join(commandsPath, file);
    const command = await import(pathToFileURL(filePath).toString());
    commands.push(command.default.data.toJSON());
  }
  return commands;
}
const commands = register(commandsPath, commandFiles);

const rest = new REST({ version: '9' }).setToken(token);

rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
	.then((commands) => console.log(`Successfully registered application commands to ${guildId}.`))
//the below code adds commands to client 
client.commands = new Collection();
const setCommandsToClient = async () => {
  const commandsPath = path.join(__dirname, 'commands');
  const commandsFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.mjs'));
  for (const file of commandsFiles) {
    const getPath = path.join(commandsPath, file)
    const command = await import(pathToFileURL(getPath));
    client.commands.set(command.default.data.name, command.default);
  }
}
setCommandsToClient();

//the below code is not getting reached at all
client.on('interactionCreate', async interaction => {
	if (!interaction.isCommand()) return;
	const command = client.commands.get(interaction.commandName);
	if (!command) return;
	try {
		await command.execute(interaction);
	} catch (error) {
		console.error(error);
		await interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });
	}
});
```

[Link to github repo with full code](https://github.com/POsten040/bigg-bot)

### Package version

^13.7.0

### Node.js version

v16.13.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildEmojisAndStickers, GuildMessages

**Comment by POsten040** [comment]
This is the repo, I do have the login code as well as commands and all the related files. Sorry for not posting is initially 👍 

[link to bot repo](https://github.com/POsten040/bigg-bot)

**Comment by iCrawl** [comment]
This still doesn't have a reproducible code portion.

Please create a tiny reproducible example for this and re-open a new issue with more information.
