### ISSUE TITLE
Permissions.ALL - Invalid permissions string returned.

### ISSUE THREAD

**Issue by callumok2004** [discordjs/discord.js#7979]
### Which package is this bug report for?

discord.js

### Issue description

```ts
import { Permissions } from "discord.js";

Permissions.ALL // 2199023255551
```

![image](https://user-images.githubusercontent.com/35779365/170870433-2c63064b-c768-431d-8b85-b71ee5cf4b4f.png)

### Code sample

```typescript
import { Permissions } from "discord.js";

export = {
  name: "invite",
  description: "Add our bot to your discord server!",
  async execute(data, client) {
    const invite = client.generateInvite({
      scopes: ["bot", "applications.commands"],
      permissions: Permissions.ALL
    });

    data.reply({ content: `Add ${client.user.username} to your server with the following link!\n${invite}` });
  }
} as Command;
```

### Package version

v13.7.0

### Node.js version

v17.8.0

### Operating system

Windows 11 Insider Preview (Dev)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates

**Comment by vladfrangu** [comment]
1. This isn't a discord.js bug / a bug at all
2. You should only request the permissions you need for your bot to function
