### ISSUE TITLE
Add The Command's guild_id To The CommandInteraction Object

### ISSUE THREAD

**Issue by Rodentman87** [discordjs/discord.js#7984]
### Which package is the feature request for?

discord.js

### Feature

When receiving a command interaction, it's currently only possible to distinguish guild commands from global commands by either storing a map of ids or caching the commands. Most of the time the distinguishing isn't needed, however, if you have a guild command and a global command with the same name then it becomes ambiguous as to which one was run.

### Ideal solution or implementation

One possible implementation would be adding `commandGuildId` to the BaseCommandInteraction object to match `commandId` and `commandName`.

### Alternative solutions or implementations

Another possible solution would be adding support for partial ApplicationCommand objects in CommandInteractions.

**Comment by monbrey** [comment]
`CommandInteraction#guildId` exists

**Comment by vladfrangu** [comment]
This is asking for the command's guild id (useful for guild command interactions), not the interaction's guild id
