### ISSUE TITLE
Memory leak after login and did nothing

### ISSUE THREAD

**Issue by DanielBUBU** [discordjs/discord.js#7988]
### Which package is this bug report for?

discord.js

### Issue description

will it cause memory leak if I pass data through the client object?
Because my bot did leak after login and did nothing(about 4MB/hr in last test)
full codes here:https://github.com/DanielBUBU/PD_maid

### Code sample

```typescript
client.queue = [];
client.isloop = 2;
client.ytpl_continuation = undefined;
client.audio_stream = undefined;
client.ffmpeg_audio_stream = undefined;
client.audio_resauce = undefined;
client.audio_sub = undefined;
client.connection = undefined;
client.ytpl_limit = 2;
client.last_at_channel = null;
client.last_at_vc_channel = null;
client.last_interaction = null;
client.nowplaying = -1;
client.handling_vc_err = false;
client.hd;
```

### Package version

13.7.0

### Node.js version

16.15.0

### Operating system

windows,termux(Linux on Android)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages

**Comment by kyranet** [comment]
This does not seem like an issue from discord.js

Also, you shouldn't pass properties around by modifying `client` all the time, but by itself, that does not leak memory.

However, it's very likely that the memory leak is from your bot, rather than from discord.js. I recommend you use [`v8.writeHeapSnapshot()`](https://nodejs.org/dist/latest-v18.x/docs/api/v8.html#v8writeheapsnapshotfilename) and later load it via Chrome Dev Tools (under the "Memory" tab) to find out what's using so much memory.

**Comment by DanielBUBU** [comment]
> This does not seem like an issue from discord.js
> 
> Also, you shouldn't pass properties around by modifying `client` all the time, but by itself, that does not leak memory.
> 
> However, it's very likely that the memory leak is from your bot, rather than from discord.js. I recommend you use [`v8.writeHeapSnapshot()`](https://nodejs.org/dist/latest-v18.x/docs/api/v8.html#v8writeheapsnapshotfilename) and later load it via Chrome Dev Tools (under the "Memory" tab) to find out what's using so much memory.

so I changed my properties and functions into a class called `discord_music`, it store client infos when loading
I using a package called heapdump to output the logs, here's comparison and the heapdump logs (tokens are replaced by "My bo token")
![image](https://user-images.githubusercontent.com/54381631/172037171-9c0e02f3-f831-426f-8f86-aebe14911f44.png)
[PD_maid.zip](https://github.com/discordjs/discord.js/files/8839391/PD_maid.zip)

you can see these are the reasons of leaking, but IDK how to find which one is the exact part that cause the leak

**Comment by DanielBUBU** [comment]
and I did another test by commenting codes like this, still leaking
````

/*
const {
    discord_music,
} = require('./music_functions/music_func.js');
const dmobj = new discord_music(client);*/
const dmobj = 1;

console.log("Loading variables...");
//discordModals(client);
````

**Comment by iCrawl** [comment]
All of this is just too little info.

This needs to be a tiny bot, reproducible, making sure it's not members / channels / etc getting cached.

**Comment by DanielBUBU** [comment]
> All of this is just too little info.
> 
> This needs to be a tiny bot, reproducible, making sure it's not members / channels / etc getting cached.

ok, so here is the index.js looks like now
````

const { Client, Intents } = require('discord.js');
const { token, guildId } = require('./config.json');
const client = new Client({
    intents: [Intents.FLAGS.GUILDS,
        // Intents.FLAGS.GUILD_MEMBERS,
        Intents.FLAGS.GUILD_MESSAGES,
        Intents.FLAGS.GUILD_VOICE_STATES
    ],
    disableMentions: 'everyone',
})

//login
client.login(token);
````
no events loaded,no command is avaliable,just setting client and login
still leaking
I use Flame Chart Visualizer for JavaScript Profiles to create the snapshots because the commands are not working now
Here is how it looks like after 30 mins
![image](https://user-images.githubusercontent.com/54381631/172078663-65e6e9e4-6a4d-4d10-8ec5-e8324966e3df.png)

**Comment by iCrawl** [comment]
Whether you have events or not is not relevant here.

I'm asking you to make sure it's not caching.
Make a new bot, put it on a single server with only yourself.
Make a snapshot, then make one again after 24h and see if there's any dramatic difference. 
Afterwards, if you see a big difference, you can easily start investigating what it is.
