### ISSUE TITLE
Cannot use some options for a SUB_COMMAND with TypeScript

### ISSUE THREAD

**Issue by ZyXProFR** [discordjs/discord.js#7989]
### Which package is this bug report for?

discord.js

### Issue description

You have to use NUMBER options in SUB_COMMAND and try to use minValue or maxValue for example.

I don't know if it's a voluntary choice.

In any case, to solve this problem, I simply added in the ApplicationCommandSubCommand interface the possibility to use an option of type ApplicationCommandOption as below:

```js
export interface ApplicationCommandSubCommand extends Omit<BaseApplicationCommandOptionsData, 'required'> {
   type: 'SUB_COMMAND';
   options: (ApplicationCommandChoicesOption | ApplicationCommandNonOptions | ApplicationCommandChannelOption | ApplicationCommandOption)[];
}
```

### Package version

13.7.0

### Node.js version

18.2.0

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by kyranet** [comment]
Can you provide a code sample from which we can reproduce this bug?

**Comment by Jiralite** [comment]
> You have to use NUMBER options in SUB_COMMAND and try to use minValue or maxValue for example.

With no code sample, I assume this is what you meant @ZyXProFR:

```TypeScript
import { Constants, Guild } from "discord.js";

declare const guild: Guild;

guild.commands.create(({
  name: "test",
  description: "test",
  options: [
    {
      type: Constants.ApplicationCommandOptionTypes.SUB_COMMAND,
      name: "test",
      description: "test",
      options: [
        {
          type: Constants.ApplicationCommandOptionTypes.NUMBER,
          name: "test",
          description: "test",
          maxValue: 3
        }
      ]
    }
  ]
}));
```

This was done in discord.js 13.8.0 and I received no TypeScript errors. I also cannot reproduce the same on 14.x. Is this still an issue?
