### ISSUE TITLE
Interaction fetching reply bug

### ISSUE THREAD

**Issue by KokoNeot** [discordjs/discord.js#7993]
### Which package is this bug report for?

discord.js

### Issue description

seems like that fetching reply causes internal error
having fetchReply option when editing reply causes this error:
Unhandled Promise TypeError: Cannot read properties of undefined (reading '_add')
  at InteractionWebhook.send (/root/KokNut/node_modules/discord.js/src/structures/Webhook.js:201:67)
  

### Code sample

```typescript
await interaction.deferReply()
const embed = new Discord.MessageEmbed().setTimestamp().setColor('RANDOM')
let msg = await interaction.editReply({ embeds: [embed], fetchReply: true })
embed.setAuthor({ name: `edited` })
msg.edit({ embeds: [embed] })
```

### Package version

13.7.0

### Node.js version

v16.13.0

### Operating system

windows 10 

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions

**Comment by KokoNeot** [comment]
Okay I was warned that this is caused due to the voice channel chats and I tested it and it is correct but in discordjs server it is stated that v13.7.0 doesnt crash 
![image](https://user-images.githubusercontent.com/91064668/171685317-dc1e6711-70c3-4f50-be0f-8da65ae62751.png)

**Comment by ItsJackson** [comment]
Can reproduce.

**Comment by oceaann** [comment]
Same on webhooks messages in tiv

**Comment by oceaann** [comment]
> Okay I was warned that this is caused due to the voice channel chats and I tested it and it is correct but in discordjs server it is stated that v13.7.0 doesnt crash ![image](https://user-images.githubusercontent.com/91064668/171685317-dc1e6711-70c3-4f50-be0f-8da65ae62751.png)

Don't crash only on normal users messages :/
