### ISSUE TITLE
Can't handle text message in voice channel

### ISSUE THREAD

**Issue by Tolarion** [discordjs/discord.js#7996]
### Which package is this bug report for?

discord.js

### Issue description

1. Type something in chat of a voice channel
2. Got "Discord sent a typing packet to a GUILD_VOICE channel ...." in err log
3. Send text message in chat of a voice channel
4. Event channel.on messageCreate not triggered

### Code sample

```typescript
client.on('messageCreate', async (msg) => {
 console.log(msg);
})
```

### Package version

13.7.0

### Node.js version

16.15.0

### Operating system

Ubuntu 20.04.4 LTS

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessageReactions, DirectMessageTyping

**Comment by monbrey** [comment]
13.7 does not support text in voice. v14 does.

**Comment by txj-xyz** [comment]
Is there a temporary patch we can implement? I'm not wanting to recode almost my entire bot for v14 on a development branch for that matter.

**Comment by cheslin23t** [comment]
There should be a temporary patch..

**Comment by cheslin23t** [comment]
@everyone <@174371986741395457> imagine being a duck

**Comment by cheslin23t** [comment]
nigger
