### ISSUE TITLE
Following Channels

### ISSUE THREAD

**Issue by TypicalTropic** [discordjs/discord.js#8004]
### Which package is the feature request for?

discord.js

### Feature

Discord has a feature where you can follow a channel, and it will post updates from that channel into your own server. Is there currently a way to support this, it would be great for some small game communities to get their favorite games changelogs directly from the creators themselves if there is no API available.

Example:

The Minecraft discord server has a channel called changelogs where they post updates to, and you can follow it to get these updates.  The discord is often times full, so users will have to find other means to get updates.

### Ideal solution or implementation

Have an event be triggered when a post is created that your bot can see and push the update to a channel. I will be honest, I am not sure how this would be implemented.

**Comment by Raiden-Ei** [comment]
https://discord.js.org/#/docs/discord.js/stable/class/NewsChannel?scrollTo=addFollower

**Comment by TypicalTropic** [comment]
Oh I did not see that thanks much
