### ISSUE TITLE
Modal Type bug when sending

### ISSUE THREAD

**Issue by Sedorikku1949** [discordjs/discord.js#8006]
### Which package is this bug report for?

discord.js

### Issue description

Hey, i have an error that occured when a try to send a Modal:
```js
data.components[0].components[0]: The specified component type is invalid in this context
data.components[1].components[0]: The specified component type is invalid in this context
data.components[2].components[0]: The specified component type is invalid in this context
```

### Code sample

```typescript
const modal = new Modal().setCustomId('ISSUE').setTitle('ISSUE');

const first = (((new TextInputComponent()).setLabel('title').setStyle("SHORT")).setCustomId("TITLE").setPlaceholder("title").setRequired(true));
const second = (((new TextInputComponent()).setLabel('description').setStyle("PARAGRAPH")).setCustomId("DESC").setPlaceholder("desc").setRequired(false));
const third = (((new TextInputComponent()).setLabel('author').setStyle("PARAGRAPH")).setCustomId("AUTHOR").setPlaceholder("auth").setRequired(true));

const firstRow = (new MessageActionRow()).addComponents(first);
const secondRow = (new MessageActionRow()).addComponents(second);
const thirdRow = (new MessageActionRow()).addComponents(third);

modal.addComponents(firstRow, secondRow, thirdRow);

interaction.reply(modal);
```

### Package version

13.7.0

### Node.js version

v18.1.0

### Operating system

WINDOWS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildPresences, GuildMessages, DirectMessages

**Comment by Rian8337** [comment]
Don't you use `showModal` when you want to respond to an interaction with a modal?

**Comment by Jiralite** [comment]
Running that code in discord.js 13.7.0 is fine for me except at the end where you used `interaction.reply(modal);` instead of `interaction.showModal(modal);`. You should read the guide linked above and ask for help in the [Discord server](https://discord.com/invite/djs).
