### ISSUE TITLE
Attachment URL is undefined when using CommandInteractionOptionResolver.getAttachment()

### ISSUE THREAD

**Issue by Jochem-W** [discordjs/discord.js#8037]
### Which package is this bug report for?

discord.js

### Issue description

The url property is seemingly no longer set for Attachments when using the getAttachment method of CommandInteractionOptionResolver and also when retrieving a message.

Expected behaviour (14.0.0-dev.1654344262-a45bef4):
![image](https://user-images.githubusercontent.com/16637577/172486628-1b46c519-0699-4f71-97f4-073c8b30c559.png)

Current behaviour (14.0.0-dev.1654603515-ecc6600):
![image](https://user-images.githubusercontent.com/16637577/172486040-fea239a7-c96d-4c08-9eeb-2be620f21dc6.png)

### Code sample

```typescript
import {
    Client,
    IntentsBitField,
    RESTPutAPIApplicationGuildCommandsResult,
    Routes,
    SlashCommandAttachmentOption,
    SlashCommandBuilder,
} from "discord.js"
import {REST} from "@discordjs/rest"

const token = "TOKEN"
const guildId = "GUILD_ID"
const applicationId = "APP_ID"

const client = new Client({
    intents: [IntentsBitField.Flags.MessageContent, IntentsBitField.Flags.Guilds, IntentsBitField.Flags.GuildMessages],
})

const command = new SlashCommandBuilder()
    .setName("test")
    .setDescription("Test")
    .addAttachmentOption(new SlashCommandAttachmentOption()
        .setName("attachment")
        .setDescription("Attachment")
        .setRequired(true))

const rest = new REST({version: "10"}).setToken(token);

(async () => {
    const response = await rest.put(Routes.applicationGuildCommands(applicationId, guildId),
        {body: [command.toJSON()]}) as RESTPutAPIApplicationGuildCommandsResult

    client.on("ready", () => console.log("Ready"))
    client.on("interactionCreate", async (interaction) => {
        if (!interaction.isChatInputCommand() || interaction.commandId !== response[0]?.id) {
            return
        }

        console.log(interaction.options.getAttachment("attachment"))
        await interaction.reply("Check the console!")
    })
    client.on("messageCreate", (message) => console.log(message.attachments))
    await client.login(token)
})()
```

### Package version

14.0.0-dev.1654603515-ecc6600

### Node.js version

Node v18.3.0, TypeScript 4.7.3

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which gateway intents are you subscribing to?

MessageContent, Guilds, GuildMessages

### I have tested this issue on a development release

ecc6600

**Comment by Jiralite** [comment]
This may be because the URL is extracted from the `data` before being sent to `_patch()`:

https://github.com/discordjs/discord.js/blob/314d76e907c25ea646e71b6407fc77c3c9760ba9/packages/discord.js/src/structures/Attachment.js#L15-L24

**Comment by Jochem-W** [comment]
It also affects attachments on Messages and I have updated my issue to include a larger code sample.
