### ISSUE TITLE
Getting error "Integration requires code grant" while using client's generateInvite

### ISSUE THREAD

**Issue by vaibhav-d-simformsolutions** [discordjs/discord.js#8039]
### Which package is this bug report for?

discord.js

### Issue description

run below code with you bot token

### Code sample

```typescript
const { Client, Intents } = require('discord.js');

(async () => {
  const client = new Client({
    intents: [
      Intents.FLAGS.GUILDS,
      Intents.FLAGS.GUILD_MEMBERS,
      Intents.FLAGS.GUILD_MESSAGES,
    ],
  });
  client.login(
    'Bot <Token>'
  );
  client.once('ready', async () => {
    console.log('Bot is ready');
    console.log(
      client.generateInvite({
        scopes: ['bot', 'email', 'guilds', 'identify', 'guilds.join'],
        permissions: ['ADMINISTRATOR'],
      })
    );
  });
})();
```
### output of the above code

https://discord.com/api/oauth2/authorize?client_id=myClientId&scope=bot+email+guilds+identify+guilds.join&permissions=8

- replaced actual client id with myClientId keyword

### Package version

13.7.0

### Node.js version

16.15.0

### Operating system

ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
This is an issue with your bot and not the library. You have set your application to require a code grant hence the message. If you don't want that, disable it in your application's settings. Reading [this](https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links) may be of use.
