### ISSUE TITLE
Possibly incorrect types for `Attachment.toJSON()` and `AttachmentBuilder.toJSON()`

### ISSUE THREAD

**Issue by itsame-luigi** [discordjs/discord.js#8059]
### Which package is this bug report for?

discord.js

### Issue description

1. Define a `message` value of type `MessageOptions`.
2. Define an `attachment` value of type `AttachmentBuilder` (and possibly `Attachment` as well).
3. Attempt to set `message.attachments = [attachment]`.
4. Note the compiler error: `type AttachmentBuilder[] is not assignable to type JSONEncodable<AttachmentPayload>[]`.

There does not seem to be a type in `discord.js` that satisfies `JSONEncodable<AttachmentPayload>`, as both `AttachmentBuilder.toJSON()` and `Attachment.toJSON()` return `unknown`

### Code sample

```typescript
import { MessageOptions, Attachment, AttachmentBuilder } from "discord.js";

// NOTE: just using declares here because the actual values are unimportant.
declare const message: MessageOptions;
declare const attachment: Attachment;
declare const builder: AttachmentBuilder;

message.attachments = [attachment]; // error
message.attachments = [builder]; // error
```

### Package version

14.0.0-dev.1654776344-94bdcac

### Node.js version

16.15.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

94bdcac

**Comment by imranbarbhuiya** [comment]
You should use https://github.com/discordjs/discord.js/blob/2791c86cdf5ebdda29b89b350cbf4f922ebb6cca/packages/discord.js/typings/index.d.ts#L4817 `files` when sending a builder and not `attachments`.

**Comment by itsame-luigi** [comment]
> You should use [...] `files` when sending a builder and not `attachments`.

Fair, but there's still no valid value that satisfies the type for `attachments`.
