### ISSUE TITLE
`Collector.endReason` doesn't reflect `Collector.stop([reason])`

### ISSUE THREAD

**Issue by MaksiRose** [discordjs/discord.js#8070]
### Which package is this bug report for?

discord.js

### Issue description

When you end a collector via `Collector.stop([reason])` and put a string in place of [reason], it does successfully update the reason parameter oft the `Collector#end` event, but it does not update `Collector.endReason`. The docs state that it is only null if the collector hasn't ended, meaning that this is supposed to update when the collector is manually stopped.

### Code sample

```typescript
const collector = message.channel.createMessageComponentCollector({
  filter: i => i.user.id === message.author.id && i.message.id === botReply.id,
  time: 120_000,
});

Let's suppose you do the following collector:
collector.on('collect', async interaction => {

  collector.stop('win');
});

collector.on('end', async (interactions, reason) => {
  console.log(collector.ended, collector.endReason, reason);
});
```

### Package version

13.8.0

### Node.js version

17.5.0

### Operating system

Manjaro

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages

**Comment by almeidx** [comment]
Fixed in #7833

**Comment by MaksiRose** [comment]
@almeidx Where is it available then? Dev builds?

**Comment by almeidx** [comment]
v14-dev builds, yes

**Comment by MaksiRose** [comment]
Thanks!
