### ISSUE TITLE
createWebhook documentation is incorrect on dev

### ISSUE THREAD

**Issue by IanMitchell** [discordjs/discord.js#8080]
### Which package is this bug report for?

discord.js

### Issue description

The documentation for `createWebhook` still references the old discord.js version - https://discord.js.org/#/docs/discord.js/main/class/TextChannel?scrollTo=createWebhook 

You can see the differences in the type signature and the code sample. I imagine it should be updated to:

```ts
channel.createWebhook({
  name: 'Snek',
  avatar: 'https://i.imgur.com/mI8XcpG.jpg',
  reason: 'Needed a cool new Webhook'
})
```

### Code sample

```typescript
N/A
```

### Package version

dev

### Node.js version

N/A

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
Indeed this is an issue - an oversight from #8026.
