### ISSUE TITLE
displayAvatarURL() with size is forced to 256

### ISSUE THREAD

**Issue by akiyuee** [discordjs/discord.js#8093]
### Which package is this bug report for?

discord.js

### Issue description

Run displayAvatarURL() and open the link in a browser. It's only 256x256
![image](https://user-images.githubusercontent.com/67498765/173493667-f8b673a4-f872-4c33-98b0-be62dc5ce510.png)

![image](https://user-images.githubusercontent.com/67498765/173493692-a6f25282-281e-4fe7-bbaa-b51306204aea.png)

### Code sample

```typescript
console.log(client.user.displayAvatarURL({ size: 4096, format: 'png', dynamic: true }))
```

### Package version

13.8.0

### Node.js version

18.1.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, GuildMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by monbrey** [comment]
This has nothing to do with discord.js - the library correctly appends the size parameter to the URL.
Discord does not or have an image that large to provide for this avatar, or for whatever other reason is not providing one.
