### ISSUE TITLE
Module 'discord.js' has no exported member 'Routes'.

### ISSUE THREAD

**Issue by pedroleinar** [discordjs/discord.js#8102]
### Which package is this bug report for?

discord.js

### Issue description

Hi guys, i hope you are doing well.

I found a problem with types

![image](https://user-images.githubusercontent.com/62183312/174129515-ef017b42-7416-4306-bec7-c0159b1b0b26.png)

![image](https://user-images.githubusercontent.com/62183312/174129610-358c28c9-0f73-4694-aa79-935cfcf50e82.png)

### Code sample

```typescript
import { REST } from "@discordjs/rest";
import { Routes } from "discord.js";

const commands = [
   {
      name: "ping",
      description: "Replies with Pong!",
   },
];

const rest = new REST({ version: "10" }).setToken("token");

(async () => {
   try {
      console.log("Started refreshing application (/) commands.");

      await rest.put(Routes.applicationGuildCommands(CLIENT_ID, GUILD_ID), {
         body: commands,
      });

      console.log("Successfully reloaded application (/) commands.");
   } catch (error) {
      console.error(error);
   }
})();
```

### Package version

"discord.js": "^13.8.0"

### Node.js version

v16.15.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by imranbarbhuiya** [comment]
`Routes` is rexported from dapi-types in `v14`. If you want to use it in v13, then import it from `discord-api-types` and not `discord.js`.

**Comment by pedroleinar** [comment]
It would be interesting to put this in the example documentation

**Comment by Jiralite** [comment]
It is: https://discord.js.org/#/docs/discord.js/stable/general/welcome

**Comment by pedroleinar** [comment]
I meant, in the readme

**Comment by Jiralite** [comment]
It's here in the README.md: https://github.com/discordjs/discord.js/tree/v13#readme

You were probably looking at the main branch, where development is actively taking place and code is constantly changing. Feel free to consult the above link to read the documentation for your version!

**Comment by pedroleinar** [comment]
I just follow the main readme.

In the main readme you are showing an example that doesn't work, you know ? 

Sorry my english and thank you very much for the help
