### ISSUE TITLE
Add auto mod implementation

### ISSUE THREAD

**Issue by FlloooDev** [discordjs/discord.js#8103]
### Which package is the feature request for?

discord.js

### Feature

I would love to access the new discord auto moderation tool with discord.js which got released today.

### Ideal solution or implementation

Implement them to the library

### Other context

I would be interested in coding this.
Resources:
https://discord.com/developers/docs/resources/auto-moderation
https://discord.com/developers/docs/change-log#auto-moderation

**Comment by almeidx** [comment]
#7938

**Comment by Jiralite** [comment]
We can leave this open in case other people encounter a similar issue. It adds more visibility that way, I guess.
