### ISSUE TITLE
Enum is not applied for TextInputBuilder when style is set to "Short" or "Paragraph"

### ISSUE THREAD

**Issue by Oncryn** [discordjs/discord.js#8107]
### Which package is this bug report for?

builders

### Issue description

1) Create a modal with ModalBuilder and add a component containing a text input
2) Set the style to "Short" or "Paragraph"
3) Show the modal
4) `DiscordAPIError[50035]: Invalid Form Body`
`data.components[0].components[0].style[NUMBER_TYPE_COERCE]: Value "Short" is not int.`

### Code sample

```typescript
const Modal = new Discord.ModalBuilder()
	.setCustomId('Form')
	.setTitle('Form')
	.setComponents(
		new Discord.ActionRowBuilder().addComponents(
			new Discord.TextInputBuilder()
				.setCustomId('Custom')
				.setLabel('Guess')
				.setStyle('Short')
		)
	);
			
Interaction.showModal(Modal);
```

### Package version

discord.js@14.0.0-dev.1655381041-4df491c

### Node.js version

v16.14.2

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

discord.js@14.0.0-dev.1655381041-4df491c

**Comment by Oncryn** [comment]
@Jiralite @monbrey However, Discord.js supports the Enum value. Using an arbitrary value will throw a UnknownEnumValueError however using "Short" or "Paragraph" will be accepted it and send a request to Discord with "Short" or "Paragraph" as the style instead of an integer.

```
Expected the value to be one of the following enum values

value: 'Arbitrary Value Here',
  enumKeys: [ 'Short', 'Paragraph' ],
  enumMappings: Map(6) {
    'Short' => 1,
    1 => 1,
    '1' => 1,
    'Paragraph' => 2,
    2 => 2,
    '2' => 2
}

**Comment by ImRodry** [comment]
Did you test that? Last time I checked that would throw an error saying style must be an integer

**Comment by monbrey** [comment]
> one of the following **enum values**

Strings are not enum values

**Comment by vladfrangu** [comment]
This is actually a bug, the
