### ISSUE TITLE
Recorder example fails to run

### ISSUE THREAD

**Issue by ReFruity** [discordjs/discord.js#8112]
### Which package is this bug report for?

voice

### Issue description

I am using M1 Macbook Pro to test this

1. Clone the main repo
2. Bump `@discordjs/opus` to `^0.6.0` in `packages/voice/examples/recorder/package.json`
3. Run
```
$ yarn --immutable
$ yarn build

$ cd packages/voice/examples/recorder
$ npm install

# Set a bot token (see auth.example.json)
$ cp auth.example.json auth.json
$ nano auth.json

# Start the bot!
$ npm start
```

Logs before bumping `@discordjs/opus` version (fails at `npm install`): https://pastebin.com/1HXsn1ME
Logs after bumping to `^0.6.0` (fails at `npm start`): https://pastebin.com/89RHRhMx

I can rewrite the recorder using the latest versions of libraries and create a PR if it's considered necessary.

### Package version

0.11.0-dev

### Node.js version

node v16.14.2, typescript@4.7.3

### Operating system

Mac OS Big Sur v11.5.2

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Feel free to open a pull request to resolve this!

**Comment by Jiralite** [comment]
I was able to get this working now since https://github.com/discordjs/voice-examples/tree/main/recorder (the repository where our voice examples will now live), so I believe this issue is resolved now.
