### ISSUE TITLE
(typescript) Cannot ensure that channel has guild without type casting

### ISSUE THREAD

**Issue by MajesticString** [discordjs/discord.js#8158]
### Which package is this bug report for?

discord.js

### Issue description

Currently, in Typescript, when you fetch a channel like so:
```ts
client.channels.fetch('1234567890')
```
the type returned is `Promise<AnyChannel | null>`.

This particular type doesn't allow the `guild` property to be accessed without the Typescript compiler complaining that the `guild` property doesn't exist on the `DMChannel` type.

On the `Channel` type, there is a `isDMBased` method which can ensure that the guild exists.
However, this method doesn't exist on a DM channel.

Currently, the only solution is to use type-casting, which could be considered unsafe, and can be quite clunky.

### Code sample

```typescript
client.channels.fetch('1234567890').then((channel) => {
    channel.guild // Property 'guild' does not exist on type 'AnyChannel'. Property 'guild' does not exist on type 'DMChannel'.
    if (channel.isText()) channel.guild // Property 'guild' does not exist on type 'DMChannel | PartialDMChannel | NewsChannel | TextChannel | ThreadChannel | VoiceChannel'. Property 'guild' does not exist on type 'DMChannel'
    if (channel.isDMBased()) {} // Property 'isDMBased' does not exist on type 'DMChannel | PartialDMChannel | NewsChannel | TextChannel | ThreadChannel | VoiceChannel'. Property 'isDMBased' does not exist on type 'DMChannel'.
    (channel as TextChannel).guild // works
});
```

### Package version

discord.js 13.8.0

### Node.js version

Node 18.2.0, Typescript 4.7.3

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
> On the `Channel` type, there is a `isDMBased` method which can ensure that the guild exists.

There is not:

https://discord.js.org/#/docs/discord.js/13.8.0/class/Channel

https://github.com/discordjs/discord.js/blob/70450f6873bda4b41d7bd212990c8823b93b9db6/typings/index.d.ts#L554-L570

If you want to assure something is from a guild, why not access it from the `GuildChannelManager`?

Additionally, you can simply do `channel instanceof TextChannel`, no?

**Comment by MajesticString** [comment]
> 

I was looking at the main branch of the repo instead of v13. It appears this method does appear in v14: https://discord.js.org/#/docs/discord.js/main/class/Channel?scrollTo=isDMBased

I suppose it would be nice if this was back-ported to v13, but it's not really an issue if it's in v14.
