### ISSUE TITLE
DiscordAPIError: 404 on Client#fetchInvite() after Invite.INVITES_PATTERN#test()

### ISSUE THREAD

**Issue by Amgelo563** [discordjs/discord.js#8175]
### Which package is this bug report for?

discord.js

### Issue description

Client throws a DiscordAPIError: 404: Not Found error on a `Client.fetchInvite()` only after using it after a `Invites.INVITES_PATTERN.test(someString)`. Fetching before that indeed doesn't error, but for some reason that single regex check makes the whole thing stop working.

I'm marking this as High priority since it's a pretty breaking bug the fact that one cannot do an invite regex check and then fetch invites.

### Code sample

```typescript
// Censored actual invite code for obvious reasons

const { Client, Invite } = require('discord.js');

const inviteLink = 'https://discord.gg/someInviteCode';

async function run() {
    const client = new Client({ intents: ['GUILDS', 'GUILD_INVITES' ] });

    await client.login('TOKEN');
    
    const invite = await client.fetchInvite(inviteLink);
    console.log(invite);
    console.log('Check!');

    if (client.isReady() && Invite.INVITES_PATTERN.test(inviteLink)) {
        const inviteRegex = await client.fetchInvite(inviteLink);
        console.log(inviteRegex);
        console.log('Double check!');
    }
}

run();

/**
 * Console output:
 * 
 * Invite { guild: InviteGuild, code: 'someInviteCode', etc... }
 * Check!
 * 

D:\SRC\test\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: 404: Not Found
    at RequestHandler.execute (d:\SRC\test\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (d:\SRC\test\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async Client.fetchInvite (d:\SRC\test\node_modules\discord.js\src\client\Client.js:307:18)
    at async run (d:\SRC\test\index.js:15:29) {
  method: 'get',
  path: '/invites/https://discord.gg/someInviteCode?with_counts=true&with_expiration=true',
  code: 0,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
 */
```

### Package version

discord.js@13.8.1

### Node.js version

Node v16.14.0

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildInvites

**Comment by Syjalo** [comment]
https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results

**Comment by Amgelo563** [comment]
> https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results

Can confirm the issue is solved by setting the `lastIndex` to 0:
```diff
    if (client.isReady() && Invite.INVITES_PATTERN.test(inviteLink)) {
+       Invite.INVITES_PATTERN.lastIndex = 0;
        const inviteRegex = await client.fetchInvite(inviteLink);
        console.log(inviteRegex);
        console.log('Double check!');
    }
````
Not sure if this is intended behavior though so I'll wait for a d.js member to close the issue, but there's the solution, thanks!

**Comment by Jiralite** [comment]
No, it's not intended behaviour. For version 13, we'll have to modify the regular expression internally to not be global. For version 14, we'll likely remove global behaviour.
