### ISSUE TITLE
<guild>.members.prune is not working or being called

### ISSUE THREAD

**Issue by samehel** [discordjs/discord.js#8188]
### Which package is this bug report for?

discord.js

### Issue description

I'm trying to use the guild.members.prune function but it doesn't seem to be doing anything. There is no response, error or anything at all. I even tried logging in the console if at least it has entered the function but it hasn't. It just refuses to enter at all or return anything.

1. I set dry to true
2. Added 3 roles
3. days to 60

And i'm just not getting anything. There are no intents or partials required for the prune function to work, just that the user should have the KICK_MEMBERS permission, thats all. 

### Code sample

```typescript
message.guild.members.prune({dry: true, roles: ['XX', 'XX', 'XX'], days: 60}).then(pruned => {
            message.channel.send(`You are going to prune ${pruned} members`);
        }).catch(console.error);
```

### Package version

discord.js v13.8.1

### Node.js version

16.10

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MEMBERS, GUILD_PRESENCES, DIRECT_MESSAGES, DIRECT_MESSAGE_TYPING, GUILD_MESSAGE_TYPING

**Comment by Jiralite** [comment]
Why are you expecting this to work when you do not have the `GUILD_MESSAGES` intent to receive messages? It would perfectly align with "And i'm just not getting anything." as the code isn't even being run in the first place.

**Comment by samehel** [comment]
> Why are you expecting this to work when you do not have the `GUILD_MESSAGES` intent to receive messages? It would perfectly align with "And i'm just not getting anything." as the code isn't even being run in the first place.

I do have it added, and it is still not working, the only reason i didn't add it to the post is because I thought that was only referring to the prune function

**Comment by Jiralite** [comment]
> I do have it added, and it is still not working

Okay. The method will fail as 60 is not a valid option for `days`. After correcting this to a number the API will accept, I am not able to reproduce the issue:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/33201955/176320650-4496c9ad-8db5-4a71-8d00-60de8d677213.png">

**Comment by samehel** [comment]
> > I do have it added, and it is still not working
> 
> Okay. The method will fail as 60 is not a valid option for `days`. After correcting this to a number the API will accept, I am not able to reproduce the issue:
> 
> <img alt="image" width="847" src="https://user-images.githubusercontent.com/33201955/176320650-4496c9ad-8db5-4a71-8d00-60de8d677213.png">

Ahh, I see now, Thank you  very much for the help!
