### ISSUE TITLE
Bot goes offline without errors

### ISSUE THREAD

**Issue by f1oppa** [discordjs/discord.js#8193]
### Which package is this bug report for?

discord.js

### Issue description

So last time (https://github.com/discordjs/discord.js/issues/8172) I couldn't explain my problem properly, so now I'll try to explain this now as best I can.

When I opened discord I saw that my bot is offline and not responding to any commands, but when I looked at the console it seemed like its running perfectly and there were no errors. And when I restarted the bot, it went online again.

This happened again, and I made a video about it:

https://user-images.githubusercontent.com/69513672/176480229-19fc9f1c-d532-4124-af25-22a5adb6fef7.mp4

 

### Package version

13.6.0

### Node.js version

16.15.1

### Operating system

Ubuntu 22.04 LTS

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by ImRodry** [comment]
When you started your video your bot was already offline so it's kinda hard to tell what caused it that way. Either way if the process doesn't stop you probably got disconnected from the gateway. You need to listen to the debug event to know what's going on. This is **not** and issue with Discord.js and you should use the [Discord server](https://discord.gg/djs) for support

**Comment by f1oppa** [comment]
Okay, thank you
