### ISSUE TITLE
message.mentions.has ignoreRepliedUser bug

### ISSUE THREAD

**Issue by Krayon0** [discordjs/discord.js#8201]
### Which package is this bug report for?

discord.js

### Issue description

Reproduce -
1. Put in the code sample with the token and channel_id
2. Reply to the message from the bot
3. bot replies back even though ignoreRepliedUser is true

if ignoreDirect is true and ignoreRepliedUser is true then the bot WON'T reply
if ignoreRepliedUser is true then the bot WILL reply
if ignoreDirect is true then the bot WILL reply

### Code sample

```typescript
const client = new Client({ intents: 513 });

client.on('ready', function(client) {
    let channel = client.channels.cache.get(channel_id);
    channel.send({content: 'test'});
})

client.on('messageCreate', function(message) {
    if(message.mentions.has(message.client.user, {ignoreRepliedUser: true})) {
        message.reply({content: 'test'});
    }
})

client.login(BOT_TOKEN);
```

### Package version

discord.js@13.8.1

### Node.js version

16.13.2

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by Syjalo** [comment]
Replied user is also in the users collection so it works like this. We should remove the `ignoreRepliedUser` option or parse user mentions in the message content like channel ones.
