### ISSUE TITLE
ExperimentalWarning in Node.js v16.13.2.

### ISSUE THREAD

**Issue by gx1285** [discordjs/discord.js#8228]
### Which package is this bug report for?

discord.js

### Issue description

In Node.js v16.13.2, using discord.js 14 causes an ExperimentalWarning: stream/web is an experimental feature.
This did not occur in Node.js v18.4.0, so I think the minimum version needs to be increased.

### Code sample

```typescript
const { Client, GatewayIntentBits } = require('discord.js');
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('interactionCreate', async interaction => {
  if (!interaction.isChatInputCommand()) return;

  if (interaction.commandName === 'ping') {
    await interaction.reply('Pong!');
  }
});

client.login('token');
```

### Package version

discord.js@14.0.0-dev.1656864763-c7a205f

### Node.js version

v16.13.2

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds

**Comment by iCrawl** [comment]
It's a warning, nothing needs to be increased.

**Comment by ImRodry** [comment]
News flash: in djs v13 you also get an experimental warning when resolving an image
