### ISSUE TITLE
Auto creation MessageActionRows for buttons depending on their number

### ISSUE THREAD

**Issue by N3wSk1Y** [discordjs/discord.js#8232]
### Which package is the feature request for?

discord.js

### Feature

As you know, for creating more than 5 buttons in 1 message you should create more than 1 `MessageActionRow()`. But sometimes I don't actually know how many buttons I need (if I pull sth from db for example) and how many `MessageActionRow()`s I do.

And I would like discord.js to be added some class or function that converts buttons (from 1 to 25 in a message) to one especial Row.

### Ideal solution or implementation

Embedded function that would be able to create as many `MessageActionRow()`s as buttons need for normal working.

**Comment by imranbarbhuiya** [comment]
This is something you should do by yourself. It's basic js. Just do something like this

```ts
const rows = [new ActionRowBuilder()];
if (rows[rows.length - 1].components.length < 5) {
	rows[roleRows.length - 1].addComponents(component);
} else {
	rows.push(new ActionRowBuilder().setComponents(component));
}
```
