### ISSUE TITLE
Make rest#method generic

### ISSUE THREAD

**Issue by KagChi** [discordjs/discord.js#8233]
### Which package is the feature request for?

rest

### Feature

Make method generic types will be usefull for typescript users, for example

```ts
const message = await rest.get("...") as APIMessage
```

With generic types will be more easier
```ts
const message = await rest.get<APIMessage>("...")
```

### Ideal solution or implementation

-

### Alternative solutions or implementations

-

### Other context

-

**Comment by iCrawl** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36868#issuecomment-512989650

**Comment by ImRodry** [comment]
This was suggested in undici and was rejected because it gives users a false sense of safety. In other languages when using notation like that checks are being done to ensure the type is correct but that doesn’t happen in TS so it would end up being misleading
