### ISSUE TITLE
@discordjs/voice requires vulnerable version of @discordjs/opus via prism-media

### ISSUE THREAD

**Issue by suptower** [discordjs/discord.js#8240]
### Which package is this bug report for?

voice

### Issue description

![image](https://user-images.githubusercontent.com/70473844/177428595-267eb7bb-8600-4f17-aa97-c0e495c70721.png)

Trying to update via `npm update` didn't work for me and manually adjusting the version requirement in `node_modules/prism-media` will make the bot unable to start.

I've assigned medium priority since the severity is marked as high by GitHub.

### Code sample

```typescript
npm list output:
├── @discordjs/builders@0.8.2
├── @discordjs/rest@0.1.0-canary.0
├── @discordjs/voice@0.10.0
├── discord-api-types@0.20.2
├── discord.js@13.8.1
├── eslint@8.19.0
├── ffmpeg-static@4.4.1
├── libsodium-wrappers@0.7.10
└── npm@8.13.2

npm audit output:
# npm audit report

@discordjs/opus  <0.8.0
Severity: high
Uncontrolled Resource Consumption in @discordjs/opus - https://github.com/advisories/GHSA-rvgf-69j7-xh78
No fix available
node_modules/@discordjs/opus
  prism-media  1.2.0 - 1.3.2
  Depends on vulnerable versions of @discordjs/opus
  node_modules/prism-media
    @discordjs/voice  *
    Depends on vulnerable versions of prism-media
    node_modules/@discordjs/voice

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

### Package version

@discordjs/voice@0.10.0, discord.js@13.8.1

### Node.js version

16.15.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages

### I have tested this issue on a development release

(Issue not regarding discord.js)

**Comment by Jiralite** [comment]
This issue should have been opened to prism-media. If that package is using a vulnerable version, they should be told, no?

All we can do is consider using another package or wait for prism-media to update their dependency.

**Comment by fredkilbourn** [comment]
Opened issue here: https://github.com/amishshah/prism-media/issues/105
