### ISSUE TITLE
@sapphire/shapeshift update causing TS2344 error in @discordjs/builders

### ISSUE THREAD

**Issue by Senexis** [discordjs/discord.js#8244]
### Which package is this bug report for?

builders

### Issue description

After updating the packages of my project, I noticed a new type error blocking the build process:

```
error TS2344: Type '{ name: string; value: string; inline: boolean | undefined; }' does not satisfy the constraint 'unknown[]'.
```

After a bit of digging with pinning different dependencies on various versions, it seems that the culprit of this error is updating to `@sapphire/shapeshift` version [3.4.1](https://github.com/sapphiredev/shapeshift/releases/tag/v3.4.1). This occurs inside `@discordjs/builders/dist/index.d.ts` line 14, column 78.

The version of `@discordjs/builders` is 0.14.0. The version of `discord.js` is 13.8.1.

If this is an issue I should be reporting to `@sapphire/shapeshift` feel free to let me know. I've marked this issue as medium as it can quite trivially be resolved by pinning `@sapphire/shapeshift` to 3.4.0. For convenience, here's a compare link for [3.4.0 to 3.4.1](https://github.com/sapphiredev/shapeshift/compare/v3.4.0...v3.4.1).

_Yes, I know this can also be resolved by skipping lib checks in TS, just thought I'd report it. If additional information is required, don't hesitate to @ me. :-)_

### Package version

0.14.0

### Node.js version

18.1.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Thank you for the report. This issue appears to already be resolved in the development version. Therefore, there is nothing to do here (phew) except release a new stable version. Keep an eye out for it.

<hr>

If you wish to install the development version, you can do so via `npm install @discordjs/builders@dev`.
