### ISSUE TITLE
`GuildMemberManager.fetch()` Error

### ISSUE THREAD

**Issue by Steellgold** [discordjs/discord.js#8247]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://user-images.githubusercontent.com/51505384/177800344-bfb7bea3-2899-4171-a17e-fe0de5783a97.png)

### Package version

13.8.1

### Node.js version

16.15.1 (tsutils: 3.21.0, ts-node: 10.8.2)

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

GuildMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildIntegrations, GuildVoiceStates, GuildMessages, GuildMessageReactions

**Comment by Jiralite** [comment]
The only way this error is possible is if your client is not ready. This isn't a bug. Furthermore, please try to include a description of the problem and a reproducible code sample. Providing nothing is not helpful.
