### ISSUE TITLE
Error while using bun (new ⭐ blazingly fast JavaScript runtime), would be cool to fix this!

### ISSUE THREAD

**Issue by ismailfateen** [discordjs/discord.js#8248]
### Which package is this bug report for?

discord.js

### Issue description

# Error I'm getting:
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/80593162/177819314-f38a444c-0761-43d5-8040-05c6b7b6c260.png">

### Code sample

```typescript
import { Client, Intents } from "discord.js"

const client = new Client({
    intents: [Intents.FLAGS.GUILD_MESSAGES]
})


client.login(process.env.TOKEN)
```

### Package version

13.8.1

### Node.js version

Bun

### Operating system

macOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by Jiralite** [comment]
This isn't a issue with discord.js. Feel free to look at https://github.com/Jarred-Sumner/bun/issues/314.
