### ISSUE TITLE
max_concurrency support

### ISSUE THREAD

**Issue by lorenzo132** [discordjs/discord.js#8259]
### Which package is the feature request for?

discord.js

### Feature

automaticly using the max_concurreny would be a awesome feature to have in djs without having to build your own custom sharding manager

### Ideal solution or implementation

a option to pick your concurreny to use if available

### Alternative solutions or implementations

writing my own custom sharding manager

**Comment by lorenzo132** [comment]
apologies for my poor wording, im not the best at explaining

**Comment by JPBM135** [comment]
This would fit better @discord.js/sharder #7204

**Comment by kyranet** [comment]
We already support `max_concurrency` in `@discordjs/ws`, see [here](https://github.com/discordjs/discord.js/blob/3c231ae81a52b66940ba495f35fd59a76c65e306/packages/ws/src/utils/IdentifyThrottler.ts#L22).

`@discordjs/sharder` won't handle those, that's `@discordjs/ws`'s job. The sharder will have an independent system based on strategies, how it'll play out in the big picture is something we have yet to find out.

**Comment by JPBM135** [comment]
Got it, thanks
