### ISSUE TITLE
Slash Command Builder fails to run when type is set to module

### ISSUE THREAD

**Issue by flaxeneel2** [discordjs/discord.js#8263]
### Which package is this bug report for?

builders

### Issue description

1. Set up a basic project with @discordjs/builders as a dependency
2. Create a new slash command using the builder
3. Test to see if it works with commonjs
4. Set "type" to "module" in package.json
6. It will error with the error below.
![image](https://user-images.githubusercontent.com/60919292/178156466-ef1644cf-2696-4d28-bcc3-ba1271725caf.png)
(First run was me testing with commonjs, which does work)

### Code sample

```typescript
package.json:

{
  "name": "testarea",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
index.js:
```
import builder from "@discordjs/builders"

let cmd = new builder.SlashCommandBuilder()
        .setName("testcmd")
        .setDescription("test test")
        .addUserOption(option => option.setName("user").setDescription("The user to test").setRequired(true))

console.log(cmd.toJSON())
```
```


### Package version

@discordjs/builders@0.15.0

### Node.js version

18.5.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

_No response_

**Comment by imranbarbhuiya** [comment]
it's an issue with `shapeshift` please report it there. <https://github.com/sapphiredev/shapeshift>

**Comment by imranbarbhuiya** [comment]
https://github.com/sapphiredev/shapeshift/pull/155 will fix it

**Comment by flaxeneel2** [comment]
Ah okay. Thank you
