### ISSUE TITLE
throws error when sending an Attachment

### ISSUE THREAD

**Issue by ChrisSch-dev** [discordjs/discord.js#8268]
### Which package is this bug report for?

discord.js

### Issue description

Returns with an error whenever you try to send an Attachment file/Files

Error:
```
1|EternalGaius  | TypeError: Cannot read properties of undefined (reading 'path')
1|EternalGaius  |     at findName (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:241:17)
1|EternalGaius  |     at Function.resolveFile (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:255:31)
1|EternalGaius  |     at /home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:222:85
1|EternalGaius  |     at Array.map (<anonymous>)
1|EternalGaius  |     at MessagePayload.resolveFiles (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:222:56)
1|EternalGaius  |     at WebhookClient.send (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/Webhook.js:212:50)
1|EternalGaius  |     at WebhookManager.sendWebhook (/home/ghost/eternalgaius/src/Structures/Base/WebhookManager.js:20:23)
```

### Code sample

```
interaction.reply({
            files: [new Attachment(Buffer.from("ANYTHING_YOU_WANT"), 'eval_input.js', { content_type: "applcation/javascript" })]
        })
```

### Package version

14.0.0-dev.1657411900-f0b68d5

### Node.js version

v16.13.2

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildIntegrations, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

### I have tested this issue on a development release

f0b68d5

**Comment by Jiralite** [comment]
If you have found the fix, please make sure you post it for future people who stumble across this.

Anyway, `Attachment()` should not be constructed if you want to make an attachment. You are looking for the [`AttachmentBuilder`](https://discord.js.org/#/docs/discord.js/main/class/AttachmentBuilder).
