### ISSUE TITLE
GuildAuditLogsEntry Typings Bug

### ISSUE THREAD

**Issue by ObscuritySRL** [discordjs/discord.js#8275]
### Which package is this bug report for?

discord.js

### Issue description

Fetching audit log of type `'ALL' | undefined` then incorrectly assumes that `auditLogs.entries.actions` will only ever be `ALL`.

### Code sample

```typescript
const auditLogs = await guild.fetchAuditLogs();

auditLogs.entries.forEach((entry) => {
  switch(entry.action) {
    case 'GUILD_UPDATE': { // Type '"GUILD_UPDATE"' is not comparable to type '"ALL"'.
      // ...
    }
    case 'MESSAGE_DELETE': { // Type '"MESSAGE_DELETE"' is not comparable to type '"ALL"'.
      // ...
    }
  }
});
```

### Package version

13.8.1

### Node.js version

v18.4.0

### Operating system

WIndows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by NickantX** [comment]
A temporary workaround seems to be to type as `GuildAuditLogsEntry<GuildAuditLogsResolvable>`, but when attempting to `fetchAuditLogs`, the original error is still thrown due to the typings of `GuildAuditLogsFetchOptions` not passing `T` to `before`:

```ts
export interface GuildAuditLogsFetchOptions<T extends GuildAuditLogsResolvable> {
  before?: Snowflake | GuildAuditLogsEntry; // <-- HERE, should be GuildAuditLogsEntry<T>
  limit?: number;
  user?: UserResolvable;
  type?: T;
}
```
