### ISSUE TITLE
`GuildMemberRoleManager.set([])` method throws error DiscordAPI: Missing Permissions in SelectMenuInteraction Scenarios when setting ordinary members roles.

### ISSUE THREAD

**Issue by sum117** [discordjs/discord.js#8284]
### Which package is this bug report for?

discord.js

### Issue description

# How to reproduce
⚠️ _Make sure your bot has the highest role in the guild and to use the method in an ordinary member just to keep doubt tailing away._
 1. Copy/paste my code in a selectMenuInteraction event where the returned value is a role id.
 2.  Try to use `.add([...interaction.values])`, it works.
 3. Now try `.remove([...interaction.values])`, also works.
 4. If you try to `.set([])`, it doesn't. Shouldn't this do the same thing? 
 

>  "Add and Remove, turn Ids into a new thing for the internal set method. But set doesn't, so to use set, you have to get it perfect for the DAPI and I reckon whatever is going to it, is kicking off." —  @Yin117  | Yinoguns#8088 <@130170417519394816>

I can show this in real time. Just message me in the Discord.js support server : sum#0117 <@969062359442280548>
 
 Should return an error similar to this one: 
 
 ```
 DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\jvcal\Documents\Personal Codes\discord.js\Moniqueta-Discord.js\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\jvcal\Documents\Personal Codes\discord.js\Moniqueta-Discord.js\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildMemberManager.edit (C:\Users\jvcal\Documents\Personal Codes\discord.js\Moniqueta-Discord.js\node_modules\discord.js\src\managers\GuildMemberManager.js:279:15)
    at async Object.execute (file:///C:/Users/jvcal/Documents/Personal%20Codes/discord.js/Moniqueta-Discord.js/src/commands/interaction.selectRoles.js:22:5) {
  method: 'patch',
  path: '/guilds/976870103125733388/members/293067060877983744',
  code: 50013,
  httpStatus: 403,
  requestData: {
    json: { roles: [Array], communication_disabled_until: undefined },
    files: []
  }
}
``` 
 
 

### Code sample

```typescript
async execute(interaction) {
    if (
      interaction.channel.id !== channels.rolesChannel &&
      !interaction.isSelectMenu()
    )
      return;

    const possibleRoles = interaction.component.options.map(
      (option) => option.value,
    );
    const userRoles = interaction.message.member.roles.cache
      .map((role) => role.id)
      .filter((id) => !possibleRoles.includes(id));
    await interaction.member.roles.set([...userRoles, ...interaction.values]);
    await interaction.reply({
      ephemeral: true,
      content: `Roles updated for your ${
        interaction.component.placeholder
      }: ${interaction.values.map((role) => '<@&' + role + '>').join(', ')} role category.`,
    });
  }
```

### Package version

discord.js@13.8.1

### Node.js version

v17.7.1

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents

**Comment by Jiralite** [comment]
Look closely at your code:

> ```ts
> const userRoles = interaction.message.member.roles.cache
>       .map((role) => role.id)
>       .filter((id) => !possibleRoles.includes(id));
> ```

`interaction.message`? The message of the select menu? Would that not be authored by your bot? The highest role of your bot is in `userRoles` which will pass that filter. Then you proceed to give the guild member this role (or in fact, all roles the bot has that are not in the select menu).

This is not a bug.
