### ISSUE TITLE
DiscordAPIError[20012]: You are not authorized to perform this action on this application

### ISSUE THREAD

**Issue by LucasB25** [discordjs/discord.js#8286]
### Which package is this bug report for?

discord.js

### Issue description

DiscordAPIError[20012]: You are not authorized to perform this action on this application
    at SequentialHandler.runRequest (/home/pi/test/node_modules/@discordjs/rest/dist/index.js:753:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/pi/test/node_modules/@discordjs/rest/dist/index.js:565:14)
    at async REST.request (/home/pi/test/node_modules/@discordjs/rest/dist/index.js:999:22)
    at async MusicBot.<anonymous> (/home/pi/test/src/structures/Client.js:129:7) {
  rawError: {
    message: 'You are not authorized to perform this action on this application',
    code: 20012
  },
  code: 20012,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications/994261218430832680/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ]
  }
}

### Package version

13.8.1

### Node.js version

16

### Operating system

linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment]
Pasting an error stack isn’t all that useful, you need to give us more information but either way this doesn’t seem like a djs bug at all…

**Comment by LucasB25** [comment]
Well I don’t know, I can’t really give more information about it, I just relaunched my bot.
I can’t find any information about this error on the internet.
Yes this is a divisive mistake, but I don’t really see who to turn to with a quick answer

**Comment by ImRodry** [comment]
Well first off don’t make issues for questions you have. You should use the [Discord server](discord.gg/djs) for that. Now if I had to guess you’re probably setting application command permissions which was removed by discord a few weeks ago.

**Comment by LucasB25** [comment]
How do I know what was deleted?

**Comment by monbrey** [comment]
The client/application id provided doesn't match the token you've set

**Comment by LucasB25** [comment]
sorry for the inconvenience I really forgot this thx you
