### ISSUE TITLE
Incorrect type for CategoryChannelChildManager#cache

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#8287]
### Which package is this bug report for?

discord.js

### Issue description

The type for CategoryChannelChildManager#cache is wrong as it says it can include thread channels, which is not true. The type for Holds on the manager is currently NonCategoryGuildBasedChannel which simply removes CategoryChannel from GuildBasedChannel, it should instead remove thread channels too.

### Code sample

```typescript
const category = guild.channels.cache.get("ID_HERE") as CategoryChannel
for (const child of category.children.cache.values())
	child.setParent("PARENT_ID", { reason: "Moving this channel" }) // Error: Property 'setParent' does not exist on type 'NonCategoryGuildBasedChannel'. Property 'setParent' does not exist on type 'PublicThreadChannel'. ts(2339)
```

### Package version

14.0.0-dev.1657411900-f0b68d5

### Node.js version

18.5.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

f0b68d5

**Comment by jaw0r3k** [comment]
yea it takes GuildChannelResolvable as type

**Comment by ImRodry** [comment]
What

**Comment by jaw0r3k** [comment]
ah didnt see its fixed
