### ISSUE TITLE
Shapeshift breaking change in 3.5.0

### ISSUE THREAD

**Issue by ianw11** [discordjs/discord.js#8289]
### Which package is this bug report for?

builders

### Issue description

To reproduce:
Use Discord.js@13.8.1
delete package-lock.json (and node_modules too)
npm install and then tsc build

The build will result in an error in a builders file, caused by a breaking change from @sapphire/shapeshift. Shapeshift released 3.5.0 4 days ago

I was able to fix the issue (temporarily) by declaring a peerDependency on shapeshift@3.4.0

### Package version

discord.js@13.8.1 @discordjs/builders@0.14.0

### Node.js version

^16.9.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by earthiverse** [comment]
Thanks, I had this bug, too. `npm i @sapphire/shapeshift@3.4.0` is temporarily fixing the problem.
```
node_modules/@discordjs/builders/dist/index.d.ts:14:78 - error TS2344: Type '{ name: string; value: string; inline: boolean | undefined; }' does not satisfy the constraint 'unknown[]'.
  Type '{ name: string; value: string; inline: boolean | undefined; }' is missing the following properties from type 'unknown[]': length, pop, push, concat, and 29 more.

 14 declare const embedFieldsArrayPredicate: _sapphire_shapeshift.ArrayValidator<{
                                                                                 ~
 15     name: string;
    ~~~~~~~~~~~~~~~~~
...
 17     inline: boolean | undefined;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 18 }>;
    ~


Found 1 error in node_modules/@discordjs/builders/dist/index.d.ts:14
```

**Comment by Jiralite** [comment]
@discordjs/builders 0.16.0 and discord.js 13.9 have been released which has this issue resolved.
