### ISSUE TITLE
How to get blocked users?

### ISSUE THREAD

**Issue by akiyuee** [discordjs/discord.js#8299]
### Which package is this bug report for?

discord.js

### Issue description

In the documentation there exists a `BlockedManager` class but client.blocked returns null. Could you help me?

### Package version

lastest

### Node.js version

v16.15.1

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment]
discord.js is meant to be used with bots which cannot block users. Additionally there is no BlockedManager and client.blocked returns undefined, not null. Self-botting is not allowed so I’m not sure what you’re trying to achieve

**Comment by akiyuee** [comment]
Oh wait this is the wrong repo
