### ISSUE TITLE
getSubcommandGroup and getSubcommand can't be inferred

### ISSUE THREAD

**Issue by TheLegendarySpark** [discordjs/discord.js#8306]
### Which package is this bug report for?

discord.js

### Issue description

1. Enter this code
```js
// commandInt: CommandInteraction
commandInt.options.getSubcommandGroup(false)
commandInt.options.getSubcommand(false)
```

Typescript error:
```
Property 'getSubcommandGroup' does not exist on type 'Omit<CommandInteractionOptionResolver<CacheType>, "getMessage" | "getFocused" | "getMentionable" | "getRole" | "getAttachment" | ... 6 more ... | "getSubcommand">'.
Property 'getSubcommand' does not exist on type 'Omit<CommandInteractionOptionResolver<CacheType>, "getMessage" | "getFocused" | "getMentionable" | "getRole" | "getAttachment" | ... 6 more ... | "getSubcommand">'.
```

### Package version

14.0.1

### Node.js version

16.9+

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds

**Comment by monbrey** [comment]
`commandInt` should be `ChatInputCommandInteraction` - it was renamed in v14.

`CommandInteraction` is a union which includes ContextMenu commands.
