### ISSUE TITLE
Error while starting last version of discord.js

### ISSUE THREAD

**Issue by AxelAmbert** [discordjs/discord.js#8316]
### Which package is this bug report for?

discord.js

### Issue description

Hello,
I am using the last version of discord.js in a Docker container.

Today I got this error when starting my client:

```
TypeError: Cannot read properties of undefined (reading 'FLAGS')
     at Object.<anonymous> (/dictabot/project/src/main.js:16:47)
     at Module._compile (node:internal/modules/cjs/loader:1120:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
     at Module.load (node:internal/modules/cjs/loader:998:32)
     at Module._load (node:internal/modules/cjs/loader:839:12)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     at node:internal/main/run_main_module:17:47
```

The only way I found to make it works again was to downgrade discord.js version to 13.9.0

### Code sample

```typescript
const {Client, Intents} = require('discord.js');

const client = new Client({intents: [ Intents.FLAGS.GUILDS ]});

client.once('ready', () => {
    console.log('Client ready');
});
```

### Package version

14.0.2

### Node.js version

18.6.0

### Operating system

Debian GNU/Linux 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by almeidx** [comment]
You haven't adapted your code to work in v14. Checkout the [update guide](https://discordjs.guide/additional-info/changes-in-v14.html)

**Comment by intrepidOlivia** [comment]
Just FYI I got this same issue by following the documentation, seems like it needs an update: https://discordjs.guide/creating-your-bot/#creating-the-main-file

**Comment by isaacKenyon** [comment]
See [this issue](https://github.com/discordjs/guide/issues/1182), the docs simply haven't been updated yet.
