### ISSUE TITLE
Allow autocomplete interactions options access to restricted get* methods

### ISSUE THREAD

**Issue by PythonCoderAS** [discordjs/discord.js#8319]
### Which package is this bug report for?

discord.js

### Issue description

Certain methods are restricted for autocomplete interactions options, such as `getUser`, and a few others. These should be unrestricted because it is still possible to get the values for other fields of the correct type that aren't autocomplete based.

1. Get autocomplete interaction
2. Try to use `interaction.options.getUser` or another restricted method

### Package version

v14.0.2

### Node.js version

v18.6.0, typescript@4.7.4 

### Operating system

Ubuntu 22.04

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages

**Comment by monbrey** [comment]
> it is still possible to get the values for other fields of the correct type that aren't autocomplete based

No, it isn't. For autocompletes, Discord does not send any `resolved` data, so the User object is not included.

You can instead use the generic `<AutocompleteInteraction>.options.get("name").value` to get the id of the selected User/Role/etc

**Comment by PythonCoderAS** [comment]
> > it is still possible to get the values for other fields of the correct type that aren't autocomplete based
> 
> No, it isn't. For autocompletes, Discord does not send any `resolved` data, so the User object is not included.

I was previously using the code snippet in v13 and I never ran into any issues, so was this the library doing resolution with the cache?

**Comment by Jiralite** [comment]
Nothing has changed really in the command interaction option resolver. The behaviour is the same for me in version 13 as it is for version 14:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/33201955/179641341-b84a16f9-4386-4fa9-8bc1-a303bb2b49b1.png">

The second output is what Discord sends us.

The third is the output of `interaction.options.getUser()` which is `null`, as there is no user object sent to us by Discord (as clearly seen by the second output.

My only guess is that your code snippet (if you can even call it that) is not what you're wholly doing. The reason it was removed from the typings is as said above: Discord simply doesn't send us that data so those relevant methods were useless for autocomplete interactions.

**Comment by PythonCoderAS** [comment]
I see the issue here, I was accepting a `null` as a valid value so my autocomplete was never correct in the first place. Even if the value was valid it was resolving to null, and I simply never noticed.
