### ISSUE TITLE
isModalSubmit typeguard for BaseInteraction

### ISSUE THREAD

**Issue by sasha0552** [discordjs/discord.js#8321]
### Which package is the feature request for?

discord.js

### Feature

I suppose there should be a "isModalSubmit" type guard in the [BaseInteraction](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/BaseInteraction.js) class

### Ideal solution or implementation

```js
isModalSubmit() {
  return this.type === InteractionType.ModalSubmit;
}
```

**Comment by ImRodry** [comment]
The solution is as simple as you described it. These typeguards were removed because you can simply compare the type and they produce the same exact effect. I don't think this will be added back
