### ISSUE TITLE
Using timestamp with EmbedBuilder: RangeError: Invalid time value

### ISSUE THREAD

**Issue by roncli** [discordjs/discord.js#8323]
### Which package is this bug report for?

discord.js

### Issue description

I am passing a `Date` object into an `EmbedBuilder` constructor's `timestamp` field.  That results in the following error:

```
RangeError: Invalid time value
      at Date.toISOString (<anonymous>)
      at new EmbedBuilder (S:\dev\git\github\obs-webserver\node_modules\@discordjs\builders\dist\index.js:186:54)
      at new EmbedBuilder (S:\dev\git\github\obs-webserver\node_modules\discord.js\src\structures\EmbedBuilder.js:13:5)
```

A little digging shows that the `Date` object gets eaten and turned into an empty object `{}` by the function `toSnakeCase()` in EmbedBuilder.js.

Workaround is to either create the embed without the timestamp and then use `.setTimestamp()` with the `Date` object on the resulting embed object, or use `.toISOString()` on the date first.  Workaround was not required for versions earlier than v14.0 when this class was `MessageEmbed`.

### Code sample

```typescript
> const DiscordJs = require("discord.js")
undefined
> const embedBroken = new DiscordJs.EmbedBuilder({timestamp: new Date()})
Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at new EmbedBuilder (S:\dev\git\github\obs-webserver\node_modules\@discordjs\builders\dist\index.js:186:54)
    at new EmbedBuilder (S:\dev\git\github\obs-webserver\node_modules\discord.js\src\structures\EmbedBuilder.js:13:5)
> const embedWorkaround = new DiscordJs.EmbedBuilder({timestamp: new Date().toISOString()})
undefined
> embedWorkaround
EmbedBuilder { data: { timestamp: '2022-07-19T20:34:58.548Z' } }
> const embedWorkaround2 = new DiscordJs.EmbedBuilder()
undefined
> embedWorkaround2.setTimestamp(new Date())
EmbedBuilder { data: { timestamp: '2022-07-19T20:35:09.295Z' } }
>
```

### Package version

14.0.3

### Node.js version

18.6.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by ImRodry** [comment]
In the meantime you can (and should) be using Date.now() for the current timestamp or new Date().getTime() if you need a timestamp that isn't now, but yes this should be fixed

**Comment by roncli** [comment]
That workaround seems better, I will use that.  Thank you!

**Comment by RedGuy12** [comment]
I'm thinking maybe this shouldn't be fixed. The argument is typed as `APIEmbed`, which is for raw JSON data from the API. JSON can not have `Date` objects in it.

This bug comes from this line:
https://github.com/discordjs/discord.js/blob/359f6885558fcfb3151971ab589077a89ee71a01/packages/discord.js/src/util/Transformers.js#L13
Calling `Object.entries` on a `Date` returns `[]`.

**Comment by roncli** [comment]
> The argument is typed as `APIEmbed`

While `APIEmbed` is a _possible_ type for the argument, it is not the only one defined.  The typings defines the `EmbedBuilder` constructor as follows:

```
public constructor(data?: EmbedData | APIEmbed);
```

This should allow for either `APIEmbed` or `EmbedData`.  And then, `EmbedData` defines `timestamp` as follows:

```
timestamp?: string | number | Date;
```

`Date` is a possible type for the value here.

It is entirely possible that a breaking change was intended here, but it's not discussed in the v13 to v14 migration guide.  This leads me to believe that a Date was intended to be accepted here, but the change to the embeds broke this particular use case.
