### ISSUE TITLE
`TextChannel.send` function has wrong types for the `components` parameter

### ISSUE THREAD

**Issue by backmeupplz** [discordjs/discord.js#8329]
### Which package is this bug report for?

builders

### Issue description

Seems like the types are wrong and `send` doesn't accept `ActionRowBuilder` as a component. I know that the docs are outdated at the moment, maybe I'm doing something wrong? If I cast `row` to `any`, the code actually compiles and works as intended.

## Steps to reproduce:
1. Run the sample code through `tsc`
2. Get the compilation error

### Code sample

```typescript
function test(channel: TextChannel) {
  const row = new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId('approve')
      .setLabel('Approve')
      .setStyle(ButtonStyle.Success)
  )

  return channel.send({
    content: 'sample',
    components: [row],
  })
}
```

### Package version

14.0.3

### Node.js version

17.3.0

### Operating system

linux, mac os

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

GuildMessages

### I have tested this issue on a development release

96b62b6.0

**Comment by almeidx** [comment]
You have to pass `ButtonBuilder` (or whatever other build you are using) as the first generic param to `ActionRowBuilder`
e.g `new ActionRowBuilder<ButtonBuilder>()`

**Comment by backmeupplz** [comment]
@almeidx shouldn't this be implied?

**Comment by imranbarbhuiya** [comment]
https://github.com/discordjs/discord.js/pull/8271 but it was closed without specifying any reason.

**Comment by suneettipirneni** [comment]
> @almeidx shouldn't this be implied? I mean, we shouldn't need to pass the generic, it should be derived from the arguments.

Typescript can't infer class generic parameters after a class has been constructed. #8271 was closed because it would invalidate cases where the generic parameter was put explicitly.

**Comment by suneettipirneni** [comment]
The DX could be improved regardless by loosening the types in send().

**Comment by backmeupplz** [comment]
@suneettipirneni but it certainly can in other frameworks. Maybe the strict OOP approach is... limited? 👀

**Comment by backmeupplz** [comment]
@suneettipirneni please, don't loosen the types 😭 you might as well just do a plain JS framework

**Comment by suneettipirneni** [comment]
> @suneettipirneni but it certainly can in other frameworks. Maybe the strict OOP approach is... limited? 👀

Could you give an example?

**Comment by backmeupplz** [comment]
@suneettipirneni the best type inference I've ever seen can be found in https://grammy.dev — it's a Telegram Bot API framework but the way the type inference works is simply magical

**Comment by backmeupplz** [comment]
@suneettipirneni oh, yeah, you can't do this with classes in TS. This doesn't mean that the inference shouldn't be added another way (e.g. less OOP?) or that the typing should be loosened (never loosen the types, please).

There is an issue with extra code the users of this framework have to write for no reason but the inflexibility of the approach that was taken when the lib was developed.

If the developers think that it's ok to make the package's users write more code than required in this case, it's totally fine to ignore this issue, though

**Comment by suneettipirneni** [comment]
This can be remedied with a factory function instead of using the class constructor ie createActionRow<T>(). Dunno if the maintainers would want to include that in the library though.

**Comment by backmeupplz** [comment]
@suneettipirneni factory function actually sounds like a great idea. I hope that the maintainers would do something like this :)
