### ISSUE TITLE
Modals with Select Menu issue

### ISSUE THREAD

**Issue by Neurizinn** [discordjs/discord.js#8330]
### Which package is this bug report for?

discord.js

### Issue description

You can't use SelectMenu with Modals, because there is a problem in a transform components function. Let's see.
```
static transformComponent(rawComponent) {
  return {
    value: rawComponent.value,
    type: rawComponent.type,
    customId: rawComponent.custom_id,
    components: rawComponent.components?.map(c => this.transformComponent(c)),
  };
}
```
Just need to change ```"value"``` to ```"values"``` and the return will no longer be undefined.

### Code sample

```typescript
static transformComponent(rawComponent) {
  return {
    value: rawComponent.values,
    type: rawComponent.type,
    customId: rawComponent.custom_id,
    components: rawComponent.components?.map(c => this.transformComponent(c)),
  };
}
```

### Package version

14.0.2

### Node.js version

18.5.0

### Operating system

Windows 10 Pro

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions

### I have tested this issue on a development release

No.

**Comment by Syjalo** [comment]
Select in modal is not documented and released thing so it's not supported by discord.js.

**Comment by almeidx** [comment]
#7974

**Comment by HemendraKhatik** [comment]
@Jiralite any update?

**Comment by Jiralite** [comment]
I am the wrong person to ask. You need to ask Discord to add feature requests.
