### ISSUE TITLE
Can't filter member presence status, always returns 'undefined'

### ISSUE THREAD

**Issue by Noxxe-0001** [discordjs/discord.js#8331]
### Which package is this bug report for?

discord.js

### Issue description

Produce a command that tries to find the presence status of a user, no matter if i try to fetch the member as a guild member and try and recieve the status from there, it still returns undefined.

I have tried both, message.guild.members.cache.filter(u => u.presence.status).size and interaction.guild.members.cache.filter(u => u.presence.status).size.

But when i fetch the member using message.guild.members.cache.fetch('<MY_ID>').presence.status, it works perfectly fine.
¯\_(ツ)_/¯

### Code sample

```typescript
message.guild.members.cache.filter(u => u.presence.status).size || interaction.guild.members.cache.filter(u => u.presence.status)
```

### Package version

discord.js@14.0.1

### Node.js version

v18.2.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents

**Comment by SpaceEEC** [comment]
Can you elaborate on what you mean with "it still returns undefined."?
The size of a collection, inheriting from map, simply can't return you undefined.

**Comment by Noxxe-0001** [comment]
> Can you elaborate on what you mean with "it still returns undefined."? The size of a collection, inheriting from map, simply can't return you undefined.

Sorry, I worded that wrong!
I was meant to give an error, but because I was testing something else that returned undefined. I put 'undefined'.


When I use `message.guild.members.cache.filter(u => u.presence.status).size` it gives this error
`TypeError: Cannot read properties of null (reading 'status')`

Even though I was going off of Discord.JS Docs.
GuildMember -> presence -> status.

But still no avail

**Comment by Jiralite** [comment]
Presences aren't initially delivered to members who are not online. That is why you are encountering `null`. It isn't a bug. It's also [documented](https://discord.js.org/#/docs/discord.js/14.0.3/class/GuildMember?scrollTo=presence) as nullable.

**Comment by Noxxe-0001** [comment]
> Presences aren't initially delivered to members who are not online. That is why you are encountering `null`. It isn't a bug. It's also [documented](https://discord.js.org/#/docs/discord.js/14.0.3/class/GuildMember?scrollTo=presence) as nullable.

So would I just filter out the offline users?

**Comment by Jiralite** [comment]
Those that do not have a presence just yet. That is why it is `null`.
