### ISSUE TITLE
Setting a role object as field value in EmbedBuilder throws RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Mephisto5558** [discordjs/discord.js#8332]
### Which package is this bug report for?

discord.js

### Issue description

In earlyer versions of discord.js, this just set the value to the role mention.

Steps to reporoduce:
Run the code sample

### Code sample

```typescript
const {EmbedBuilder} = require('discord.js');
const embed = new EmbedBuilder({
 fields: [
  { name:'Name', value: message.guild.roles.cache.get('ROLE ID')}
 ]
});
```

### Package version

v14.0.3

### Node.js version

v16.14.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

**Comment by MrMythicalYT** [comment]
You need to use `Role#toString()`, since v13 it didn't automatically covert to string

**Comment by SpaceEEC** [comment]
That aside, the error is happening in the call to `toSnakeCase` in the constructor for `EmbedBuilder`.
Not sure what we should do here.

**Comment by imranbarbhuiya** [comment]
> That aside, the error is happening in the call to `toSnakeCase` in the constructor for `EmbedBuilder`. Not sure what we should do here.

Do we need to do anything here? because the user is providing an invalid value that even has circular. And ig the `Maximum call stack size exceeded` is coming because of the circular.
