### ISSUE TITLE
interaction.editReply() returns with "Invalid Webhook Token" Error

### ISSUE THREAD

**Issue by ChrisSch-dev** [discordjs/discord.js#8335]
### Which package is this bug report for?

discord.js

### Issue description

1|EternalGaius  | [Process 819192] [Cluster 0] [Error]  » DiscordAPIError[50027]: Invalid Webhook Token
1|EternalGaius  |     at SequentialHandler.runRequest (/home/ghost/eternalgaius/node_modules/@discordjs/rest/dist/index.js:749:15)
1|EternalGaius  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|EternalGaius  |     at async SequentialHandler.queueRequest (/home/ghost/eternalgaius/node_modules/@discordjs/rest/dist/index.js:561:14)
1|EternalGaius  |     at async REST.request (/home/ghost/eternalgaius/node_modules/@discordjs/rest/dist/index.js:1001:22)
1|EternalGaius  |     at async InteractionWebhook.editMessage (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/Webhook.js:324:15)
1|EternalGaius  |     at async ChatInputCommandInteraction.editReply (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:150:21)
1|EternalGaius  |     at async module.exports.execute (/home/ghost/eternalgaius/src/Commands/General/ping.js:31:9)

`interaction.editReply()` returns with Invalid Webhook Token,
### Code sample

```typescript
interaction.reply({ embeds: [embed1] })

interaction.editReply({ embeds: [embed2] })
```

### Package version

14.0.0, 14.0.1, 14.0.2, 14.0.3

### Node.js version

v16.13.2

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildWebhooks, GuildMessages, GuildMessageReactions, MessageContent

### I have tested this issue on a development release

74ec7be

**Comment by almostSouji** [comment]
Known upstream issue in Discord

**Comment by eth0izzle** [comment]
Same issue here. Was pulling my hair out for the past hour.

**Comment by kyranet** [comment]
Please read @almostSouji's message, I'll lock this issue so it doesn't get buried.
