### ISSUE TITLE
BaseCommandInteraction.deferReply cause invalid webhook token problem

### ISSUE THREAD

**Issue by Nekofoxmiu** [discordjs/discord.js#8339]
### Which package is this bug report for?

discord.js

### Issue description

I am using for deferReply for a while to make sure my reply won't be too late.
But few hours ago it suddently went wrong everytime when I call deferReply method and editReply.
When I call editReply function it throw error (DiscordAPIError: Invalid Webhook Token).

Also I am testing for a while, just normal reply then call editReply is ok, But
deferReply then editReply will go wrong.

Also even the interaction guide's example can't work.

Also: The bot has all permission without tts and edit channel to that channel.

![image](https://user-images.githubusercontent.com/76677660/180496340-60df6fad-61fb-4e69-ab94-d22e2e64af33.png)
![image](https://user-images.githubusercontent.com/76677660/180496455-505012e4-2b33-40fb-90c0-208e66eee796.png)

### Code sample

```typescript
function wait(ms) {
    return new Promise((resolve) => { setTimeout(() => resolve(`wait ${ms / 1000} seconds.`), ms); });
}
client.on('interactionCreate', async interaction => {
     if (!interaction.isCommand()) return;
        await interaction.deferReply();
        await wait(4000);
        await interaction.reply('Pong!');
});
```

### Package version

discord.js@13.9.0

### Node.js version

v17.3.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildWebhooks, GuildMessages, GuildMessageReactions, GuildMessageTyping

**Comment by almostSouji** [comment]
was an upstream issue with discord webhook token validation, fixed now
