### ISSUE TITLE
Create channel: DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by uncentered** [discordjs/discord.js#8342]
### Which package is this bug report for?

discord.js

### Issue description

run the code

### Code sample

```typescript
const client = require('..')
const { InteractionType, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');

client.on('interactionCreate', async interaction => {
	if (interaction.type !== InteractionType.ModalSubmit) return;
	if (interaction.customId === 'myModal') {

		const one = interaction.fields.getTextInputValue('nameoftheuser');
		const two = interaction.fields.getTextInputValue('reportreason');
		const three = interaction.fields.getTextInputValue('otherinfo');


		interaction.guild.channels.create(`ticket-${interaction.user.username}`, {
			parent: '1000116949805707284',
			topic: interaction.user.id,
			permissionOverwrites: [{
				id: interaction.user.id,
				allow: ['SEND_MESSAGES', 'VIEW_CHANNEL', 'READ_MESSAGE_HISTORY'],
			},
			{
				id: '1000360930644852786',
				allow: ['SEND_MESSAGES', 'VIEW_CHANNEL', 'READ_MESSAGE_HISTORY'],
			},
			{
				id: interaction.guild.roles.everyone,
				deny: ['VIEW_CHANNEL'],
			},
			],
			type: 'text',
		}).then(async c => {
			interaction.reply({
				content: `Ticket has ben created! <#${c.id}>`,
				ephemeral: true
			})
		})
	}
})
```

### Package version

14

### Node.js version

16.9

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

### I have tested this issue on a development release

5f667c0.0

**Comment by Jiralite** [comment]
Please browse the [update guide](https://discordjs.guide/additional-info/changes-in-v14.html) - specifically about consolidati.

**Comment by uncentered** [comment]
I still get this error..


throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[50035]: Invalid Form Body
name[BASE_TYPE_REQUIRED]: This field is required

**Comment by Jiralite** [comment]
You should ask in the [Discord server](https://discord.com/invite/djs) as this issue tracker is only for bug reports and enhancement suggestions.

**Comment by uncentered** [comment]
okay thanks
