### ISSUE TITLE
`SelectMenuOptionBuilder#setDescription` does not accept null or undefined values

### ISSUE THREAD

**Issue by Gorniaky** [discordjs/discord.js#8350]
### Which package is this bug report for?

builders

### Issue description

Like other constructors, making this one accept null or undefined.

Error:
![image](https://user-images.githubusercontent.com/30408913/180652650-d4093c67-ddbb-444f-bc88-c49d6b553c1f.png)

### Code sample

```typescript
import { SelectMenuOptionBuilder } from 'discord.js';

new SelectMenuOptionBuilder()
  .setDescription(null);
```

### Package version

discord.js@^14.0.3 - @discordjs/builders@^0.14.0

### Node.js version

18.6.0

### Operating system

Windows 10 IoT Enterprise LTSC 21H2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by almeidx** [comment]
This is also a problem with the other non-required property setters (also for the other components)

**Comment by Identity-labs** [comment]
Also SelectMenuBuilder don't have value submited when used in modal
Always undefined
We can't set label on it when used in modal

**Comment by monbrey** [comment]
> Also SelectMenuBuilder don't have value submited when used in modal Always undefined We can't set label on it when used in modal

SelectMenus are not supported in Modals. Discord has not announced or released the feature officially.

**Comment by didinele** [comment]
This is no longer relevant as of #10448
