### ISSUE TITLE
ActionRowBuilder missing required 'type' property from ActionRowData

### ISSUE THREAD

**Issue by GalaxyVinci05** [discordjs/discord.js#8366]
### Which package is this bug report for?

discord.js

### Issue description

Passing an action row as a component in an interaction reply gives the following error in VS Code:

```
No overload matches this call.
  Overload 1 of 2, '(options: InteractionReplyOptions & { fetchReply: true; }): Promise<Message<boolean>>', gave the following error.
    Type 'ActionRowBuilder<AnyComponentBuilder>' is not assignable to type 'APIActionRowComponent<APIMessageActionRowComponent> | JSONEncodable<APIActionRowComponent<APIMessageActionRowComponent>> | ActionRowData<...>'.
      Property 'type' is missing in type 'ActionRowBuilder<AnyComponentBuilder>' but required in type 'ActionRowData<MessageActionRowComponentBuilder | MessageActionRowComponentData>'.
  Overload 2 of 2, '(options: string | MessagePayload | InteractionReplyOptions): Promise<InteractionResponse<boolean>>', gave the following error.
    Type 'ActionRowBuilder<AnyComponentBuilder>' is not assignable to type 'APIActionRowComponent<APIMessageActionRowComponent> | JSONEncodable<APIActionRowComponent<APIMessageActionRowComponent>> | ActionRowData<...>'.ts(2769)
```
**Temporary workaround**: casting ActionRowBuilder type as any, at the cost of not having type checking
(adding 'type' as a parameter to the builder doesn't work)

### Code sample

```typescript
const row = new ActionRowBuilder()
    .addComponents(
	new ButtonBuilder()
	    .setCustomId('primary')
	    .setLabel('Primary')
	    .setStyle(ButtonStyle.Primary),
    );

await interaction.reply({ content: 'Pong!', components: [row] });
```

### Package version

discord.js@14.0.3

### Node.js version

v16.16.0 (typescript@4.7.4)

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildVoiceStates, GuildMessages, GuildMessageReactions

### I have tested this issue on a development release

34ba9d1.0

**Comment by MrMythicalYT** [comment]
In TypeScript, define the action row builder with `new ActionRowBuilder<ComponentType>()`, in your case, `new ActionRowBuilder<ButtonBuilder>()`

**Comment by GalaxyVinci05** [comment]
@MrMythicalYT  oh yeah that works, thanks. Sorry, guess I'm just dumb
