### ISSUE TITLE
Update collection entry

### ISSUE THREAD

**Issue by digimbyte** [discordjs/discord.js#8367]
### Which package is the feature request for?

collection

### Feature

I would love to see an update function that mutates entries without having to directly fetch and set per the following:
```
item = collectionReference.get(id);
item.prop = newVal;
collectionReference.set(id,item);
```

### Ideal solution or implementation

Allow collections to find an entry by key and update the value internally without requiring repeating code
optional third parameter to replace the existing item or merge with
```collectionReference.update(id, {prop:newVal},true)```

Should have a *has* health check, throw an error if value does not exist or use a set/merge optional parameter 

### Alternative solutions or implementations

Would be good to have a update or merge integration, emulating CRUD features is essential
```
class newCollection<K, V> extends Collection<K, V>{
    update(key, value, merge?: boolean) {
        if (this.has(key)) {
            this.set(key, { ... this.get(key), ...value })
        } else {
            if (merge) this.set(key, value)
            else throw new Error("No Key Value pair found");
        }
    }
}
```

### Other context

I use discord collections outside of DiscordJS because it is the best collection solution available. being able to interact and manage large collections of data on a regular basis for API requests and client apps makes it very easily a must have in any environment. 
I am working on a project that requires manipulating the data including nesting multiple collections
IE: 
```sessionsCollection.get(sessionID).Players.update(playerID,{afk:true},false)```

**Comment by kyranet** [comment]
I'll point out some stuff:

1. You can define a function that always throws, as seen below:
    ```typescript
    const throwError = () => throw new Error('Missing entry in collection');
    ```
    
    Using this function, you may use `.ensure` to make the call throw if the entry does not exist:
    ```typescript
    const item = collectionReference.ensure(id, throwError);
    ```
2. You don't need to `.set` a mutated object you retrieved from `.get`, you're updating a reference.
3. Updating can be tricky, what should we do, pull an external dependency to do deep merging, or do a shallow first-level merging? In case of the latter, you can achieve what you want (with a forced *has* health check) with the following code:
    ```typescript
    const throwError = () => throw new Error('Missing entry in collection');
    
    export function updateValue<K, V>(collection: Collection<K, V>, key: K, value: Partial<V>) {
      const item = collectionReference.ensure(id, throwError);
      Object.assign(item, value);
    }
    ```

If we *do* add an `.update`, it would take a callback, and it could either do nothing when a key doesn't exist (but still be able to return the updated value), return a boolean, or throw if the key does not exist. Do not confuse with `.upsert`, which inserts or updates.
