### ISSUE TITLE
Type 'ButtonStyle.Secondary' is not assignable to type 'ButtonStyle.Link'

### ISSUE THREAD

**Issue by RobotoSkunk** [discordjs/discord.js#8394]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce this bug is trying to use a variable as `InteractionReplyOptions` and then assign `ButtonStyle.Secondary` to a button.

![Screenshot 2022-07-29 144930](https://user-images.githubusercontent.com/49355293/181833715-e0aec3b2-7a02-42e2-a7e9-98fc02ee45c9.png)

This bug is only an error warning of TypeScript, but when you compile it and run your bot, it works normally.

![Screenshot 2022-07-29 145159](https://user-images.githubusercontent.com/49355293/181833819-18a37bf6-4254-4dd0-880c-3adf382333cf.png)

I don't know if this happen with other interfaces, but it happens with `InteractionReplyOptions`.

### Code sample

```typescript
const defaultEmbed: Discord.InteractionReplyOptions = {
	'content': 'Example',
	'components': [
		{
			'type': Discord.ComponentType.ActionRow,
			'components': [
				{
					'type': Discord.ComponentType.Button,
					'label': 'Claim',
					'custom_id': 'claim',
					'style': Discord.ButtonStyle.Secondary,
					'emoji': '<:Axiom:1002647954177404989>'
				}, {
					'type': Discord.ComponentType.Button,
					'label': 'Sell',
					'custom_id': 'sell',
					'style': Discord.ButtonStyle.Secondary,
					'emoji': '<:Price:992089355768315934>'
				}
			]
		}
	]
};

// This happen if you write your JSON directly in `interaction.reply` too.

await interaction.reply({
	'components': [
		{
			'type': Discord.ComponentType.ActionRow,
			'components': [
				{
					'type': Discord.ComponentType.Button,
					'label': 'Something',
					'custom_id': 'claim',
					'style': Discord.ButtonStyle.Secondary,
					'emoji': '<:Axiom:1002647954177404989>'
				}	
			]
		}
	]
});
```

### Package version

discord.js@14.1.1

### Node.js version

Node v16.14.2 --- TypeScript v4.7.4 

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, DirectMessages

**Comment by Jiralite** [comment]
When you use raw objects, you are using the raw API data. `emoji` needs to be an object here. You are providing a string.

**Comment by RobotoSkunk** [comment]
> When you use raw objects, you are using the raw API data. `emoji` needs to be an object here. You are providing a string.

Thank you very much, that solved the error problem, although it does not happen if you use another button style than Secondary or Link

**Comment by RobotoSkunk** [comment]
Thank you very much!, that solved the error problem.
