### ISSUE TITLE
No ready event after destroy and login

### ISSUE THREAD

**Issue by BannukDE** [discordjs/discord.js#8401]
### Which package is this bug report for?

discord.js

### Issue description

1. use Client destroy method
2. use Client login method
3. do not kill process

Expected: Ready Event to be fired
Actual behavior:  Bot executes events multiple times

Hello,
I have not builded a minimilzed version to exclude errors from my code completely, but I can not see a reason why the bot should respond multiple times to one message (9 was the maximum I reached) other then useing destroy and login of the Client class. I also can replicate the behavior any time.

![Screenshot 2022-07-30 234113](https://user-images.githubusercontent.com/31015872/181997004-9902be09-7818-4e9e-b003-49bf9f50ce58.png)

### Code sample

```typescript
bot.js:
'use strict'
import { Client, GatewayIntentBits } from 'discord.js'
class Bot extends Client {
  constructor() {
    super({ intents: Object.keys(GatewayIntentBits) })
    this.state = false
  }  
  async log(origintype, msg, detail) {
    console.log(`[${new Date().toLocaleTimeString()}] [${origintype}]: ${msg} ${detail ? detail : ''}`)
  }
  async start() {
    try {
      this.login({PUT_TOKEN_HERE})
      this.state = true
    } catch (err) {
      this.log(`Discord/ERROR`, `Unable to login.`, err)
    }
  }
  async stop() {
    if (this.state) {
      this.destroy()
      this.state = false
      this.log(`Discord/INFO`, `Stopped Discord Bot`)
    }
  }
export default Bot


index.js:

'use strict'
import Bot from './bot.js'
const bot = new Bot()
process.stdin.on('data', (chunk) => {
  const buffer = chunk.toString().trim()
  if (buffer === "stop") {
    bot.stop()
  } else if (buffer === "update") {
    bot.stop()
    bot.spawn.on("close", () => {
      bot.update()
    })
  } else if (buffer === "start") {
    bot.start()
  } else {
    bot.send(buffer)
  }
})
bot.start()

plus ready Event with log
```

### Package version

14.0.0

### Node.js version

16.16.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents

**Comment by almostSouji** [comment]
You should not attempt to log in on a destroyed client. Destroying without killing the process is mostly available to do cleanup work, if necessary.

**Comment by BannukDE** [comment]
If I understand correctly the clean way would be to kill the child in index and create a new instance of the class Bot/Client.
