### ISSUE TITLE
Calling reply method from variable

### ISSUE THREAD

**Issue by atlanf586** [discordjs/discord.js#8402]
### Which package is this bug report for?

discord.js

### Issue description

Calling a reply method dynamically from a variable produces an error, but works when used statically. Only slightly annoying, but it would cut down on a few lines of code if it worked as expected.

### Code sample

```typescript
client.on('interactionCreate', async interaction => {
    const replyMethod = interaction.update;
    await replyMethod('pong'); // TypeError: Cannot read properties of undefined (reading 'deferred')

    // but this works
    await interaction.update('pong');
});
```

### Package version

13.9.0

### Node.js version

16.13.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
The context of `this` in the method is lost in `const replyMethod = interaction.update;`.

**Comment by atlanf586** [comment]
> The context of `this` in the method is lost in `const replyMethod = interaction.update;`.

Ow, so it's impossible to do this in JS then?

**Comment by imranbarbhuiya** [comment]
> > The context of `this` in the method is lost in `const replyMethod = interaction.update;`.
> 
> Ow, so it's impossible to do this in JS then?

You can bind `interaction` to `replyMethod`.

```ts
client.on('interactionCreate', async interaction => {
    const replyMethod = interaction.update.bind(interaction)
    await replyMethod('pong'); // works
});
```

**Comment by atlanf586** [comment]
> > > The context of `this` in the method is lost in `const replyMethod = interaction.update;`.
> > 
> > 
> > Ow, so it's impossible to do this in JS then?
> 
> You can bind `interaction` to `replyMethod`.
> 
> ```ts
> client.on('interactionCreate', async interaction => {
>     const replyMethod = interaction.update.bind(interaction)
>     await replyMethod('pong'); // works
> });
> ```

Awesome. Thanks, friend!
