### ISSUE TITLE
interactionCreate should send _hoistedOptions in order

### ISSUE THREAD

**Issue by CocoaMix86** [discordjs/discord.js#8429]
### Which package is the feature request for?

discord.js

### Feature

Currently, if you input multiple options while using a slash command, it doesn't matter what order you specify them, _hoistedOptions will ALWAYS output the options in the same order you created them in the SlashCommandBuilder.

Example:  
- I have a command named `/create` with options `name`, `cost`, and `type`. Each of these is optional.
- I run the command `/create type:Food cost:45`
- Log the output of interaction.options._hoistedOptions
- Notice the `cost` option in the array shows up before `type` option, even though I "sent" `type` option first.

### Ideal solution or implementation

It would be ideal if `_hoistedOptions` kept the options in order specified from the user command, instead of the order specified from the SlashCommandBuilder.

### Other context

The above example is a small one. My actual use case has 19 options, and the order specified is actually critical, as I am constructing one long string out of the options a user inputs.

**Comment by Syjalo** [comment]
Firstly `_hoistedOptions` is private property and you shouldn't use it. Secondly the options come from the API, ask Discord for that.
<https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-application-command-data-structure>
