### ISSUE TITLE
ApplicationCommandOption union is missing ApplicationCommandBooleanOption

### ISSUE THREAD

**Issue by janparisek** [discordjs/discord.js#8433]
### Which package is this bug report for?

discord.js

### Issue description

(This is an issue with typings)

The union ApplicationCommandOption does not contain ApplicationCommandBooleanOption.

This is an issue I ran into while checking if the option of an already-registered command is of type Boolean.

### Code sample

```typescript
import { ApplicationCommandOption, ApplicationCommandOptionType } from 'discord.js'

let test: ApplicationCommandOption
if (test.type === ApplicationCommandOptionType.Boolean) {}

// tsc
```

### Package version

14.1.2

### Node.js version

node v16.13.2 + typescript 4.7.4

### Operating system

Microsoft Windows 10 Pro N 10.0.19044 Build 19044

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

discord.js@14.1.3-dev.1659614876-359f688.0

**Comment by Jiralite** [comment]
I am able to reproduce this.

To be specific, the currently allowed types are: 

- `ApplicationCommandOptionType.Subcommand`
- `ApplicationCommandOptionType.SubcommandGroup`
- `ApplicationCommandOptionType.String`
- `ApplicationCommandOptionType.Integer`
- `ApplicationCommandOptionType.Channel`
- `ApplicationCommandOptionType.Number`
- `ApplicationCommandOptionType.Attachment`

The rest are missing. Another example is `ApplicationCommandOptionType.Mentionable`.

**Comment by N1ckPro** [comment]
Looks like the issue is here:
https://github.com/discordjs/discord.js/blob/359f6885558fcfb3151971ab589077a89ee71a01/packages/discord.js/typings/index.d.ts#L3880
This just resolves to `never`

**Comment by janparisek** [comment]
Digging further, discord.js doesn't even seem to have a type called `ApplicationCommandBooleanOption` nor `ApplicationCommandBooleanOptionData`.
