### ISSUE TITLE
message.attachments.size always returns 0

### ISSUE THREAD

**Issue by DragosPV** [discordjs/discord.js#8435]
### Which package is this bug report for?

discord.js

### Issue description

`message.attachments.size` always returns 0, tryed with 1, 2 pictures and with a txt file and nothing

### Package version

14.1.2

### Node.js version

16.15.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages

**Comment by MrMythicalYT** [comment]
You need `MessageContent` intent to receive any of the message contents, including attachments

**Comment by DragosPV** [comment]
ohh, thanks
