### ISSUE TITLE
Add support for the @discordjs/rest package in browser environments

### ISSUE THREAD

**Issue by TheOnlyTails** [discordjs/discord.js#8436]
### Which package is the feature request for?

rest

### Feature

I started recently working on a web dashboard for one of my bots, and I was looking for a package to make requests to Discord API (which obviously are very common on a bot dashboard) easier than using the native fetch API.
I was delighted to see that this package exists, but was quite disappointed to see it doesn't support browser environments due to its use of big integer literals.

### Ideal solution or implementation

I would like the library to be compatible with browser environments.

**Comment by ckohen** [comment]
BigInt literals are supported in all modern browsers, this is not the problem with browser support for browser environments. The two major things are event emitter and undici.request over fetch (which is significantly faster for node)

**Comment by tomprince** [comment]
I'm interested in this, for running a bot in a cloudflare worker, using the interaction webhook.

**Comment by didinele** [comment]
once #9416 is merged and we move `REST` to async event emitter this will be resolved

**Comment by Jiralite** [comment]
This is supported as of 2.0.0 https://github.com/discordjs/discord.js/releases/tag/%40discordjs%2Frest%402.0.0.
