### ISSUE TITLE
deferUpdate exists in ModalSubmitInteraction, but not in typings

### ISSUE THREAD

**Issue by pikokr** [discordjs/discord.js#8441]
### Which package is this bug report for?

discord.js

### Issue description

how to reproduce
1. catch a modal submit interaction
2. use deferUpdate on the interaction -> cannot find deferUpdate on interaction

### Code sample

```typescript
// ...
interaction.deferUpdate()
```

### Package version

14.1.2

### Node.js version

v16.15.1

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
This is not a bug. Not all interactions of this kind can do this. You need to type guard appropriately via `ModalSubmitInteraction#isFromMessage()`.
