### ISSUE TITLE
Typings for member.voice afterwards doesn't exist

### ISSUE THREAD

**Issue by DamianBossPL** [discordjs/discord.js#8442]
### Which package is this bug report for?

discord.js

### Issue description

1. In vscode, access any `member`
2. Go into `voice` 
3. In `member.voice` there is no typings

### Code sample

```typescript
interaction.member.voice
```

### Package version

v14.1.1

### Node.js version

v16.15.0

### Operating system

Windows 11 21H2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
This is not a bug. You have not type guarded this to be a discord.js structure, so this property may not exist.
