### ISSUE TITLE
displayAvatarUrl is not returning requested format

### ISSUE THREAD

**Issue by ayan4m1** [discordjs/discord.js#8444]
### Which package is this bug report for?

discord.js

### Issue description

1. Attach handler to guildMemberAdd event of client
2. In handler, call `member.user.displayAvatarUrl({ format: 'jpg' })`
3. Expected URL should end in .jpg, but it ends in .webp

### Code sample

```typescript
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.GuildMembers
  ]
});

const handleJoin = async (member) => {
  const { displayName, guild } = member;
  const channel = guild.channels.cache.find(
    (chan) => chan.id === '123456'
  );
  const canvas = Canvas.createCanvas(748, 400);
  const ctx = canvas.getContext('2d');
  const background = await Canvas.loadImage('./images/bg.png');
  const avatar = await Canvas.loadImage(
    member.user.displayAvatarURL({ format: 'jpg' })
  );

  // draw background overlay
  ctx.drawImage(background, 0, 0, 748, 400);

  // draw a border around the image
  ctx.strokeStyle = '#74037b';
  ctx.strokeRect(0, 0, canvas.width, canvas.height);

  // draw the welcome text
  ctx.font = `24px Times New Roman`;
  ctx.fillStyle = '#fefefe';
  ctx.fillText(`Welcome, ${displayName}!`, 200, canvas.height / 2 + 30);

  // draw the user's avatar
  ctx.beginPath();
  ctx.arc(100, 200, 80, 0, Math.PI * 2, true);
  ctx.closePath();
  ctx.clip();
  ctx.drawImage(avatar, 20, 20, 160, 160);

  const attachment = new AttachmentBuilder(canvas.toBuffer(), {
    name: 'welcome.png'
  });

  channel.send({ files: [attachment] });
};

client.on('guildMemberAdd', handleJoin);
client.login('bot token');
```

### Package version

14.1.2

### Node.js version

16.13.2

### Operating system

Windows 10 Pro x64

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, DirectMessages

**Comment by Jiralite** [comment]
This is not a bug. This method is dynamic by default. If you want to force static avatar icons, you need to explicitly do that.

**Comment by ayan4m1** [comment]
I'm using [this documentation](https://discord.js.org/#/docs/discord.js/stable/class/User?scrollTo=displayAvatarURL) - can you explain or link me to docs that explain how to explicitly force static avatar icons.

What parameters are wrong in what method?

**Comment by ayan4m1** [comment]
Sorry, I have tried adding `forceStatic: true` to the options and I still get a webp back, can you elaborate at all on the issues you described, I don't see what I'm doing wrong according to the docs.

**Comment by lolollllo** [comment]
its `extension` not `format`
[docs](https://discord.js.org/#/docs/rest/main/typedef/ImageURLOptions)

**Comment by advaith1** [comment]
i think that was missed in the v14 change guide
