### ISSUE TITLE
TypeError: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by miduh** [discordjs/discord.js#8450]
### Which package is this bug report for?

discord.js

### Issue description

I tried everything. But when i instance the Client class it gives me this error.

i tried literally EVERYTHING to fix that.

I don't know what to do

### Package version

14.0.2

### Node.js version

16.8.0

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds

**Comment by almostSouji** [comment]
"everything" seemingly did not include looking it up here
<https://github.com/discordjs/discord.js/search?q=hasown&type=issues>

update node to 16.0.9 or later
