### ISSUE TITLE
Serialization (preferably through json)

### ISSUE THREAD

**Issue by parmleyhunt** [discordjs/discord.js#8451]
### Which package is the feature request for?

discord.js

### Feature

A way to serialize a reference class and rebuild it on the other side.

### Ideal solution or implementation

```javascript
someFunctionToPassThroughPipe(message.toJSON())
```
```javascript
messageRecieved = discord.Message.from(data)
```

### Alternative solutions or implementations

I could do it in my own use case, however I would rather just see it as an official feature rather than a hacky solution that could break on the next update.

### Other context

This should have been implemented well before v10.x.x, just saying. It's a rest api there is nothing critical about any of these data wrappers. Albeit makes it easier to work with in localized projects it gets more complicated when you can't send the real thing.

**Comment by monbrey** [comment]
Pretty sure this would be addressed by https://github.com/discordjs/discord.js/pull/8417

**Comment by parmleyhunt** [comment]
> Pretty sure this would be addressed by #8417

Not exactly structures seems to be adding new classes kind of hard to see the purpose as of yet. What I want would be an addition to the existing classes. If I get sometime I will take care of it.

**Comment by kyranet** [comment]
The new package, `@discordjs/structures` (implemented by #8417), will implement a way to get an approximate of Discord's raw data back in the `toJSON()` methods. I hope that addresses your request @parmleyhunt.

**Comment by parmleyhunt** [comment]
So since it will be an approximate and have no way of seeing previous can we see synchronous operations as well

**Comment by kyranet** [comment]
It'll be approximate because `1.0` becomes `1`, and `2022-08-10T14:11:23.529000+00:00` becomes `2022-08-10T14:11:23.529Z`.

Other than that, the data is completely valid and near-identical for both.
