### ISSUE TITLE
`getSubcommand` Omitted from type `CommandInteractionOptionResolver`

### ISSUE THREAD

**Issue by chexburger** [discordjs/discord.js#8459]
### Which package is this bug report for?

discord.js

### Issue description

When using TypeScript, the CommandInteractionOptionResolver has omitted valid function calls and thus results in an error.

From VSCode:
```
Property 'getSubcommand' does not exist on type 'Omit<CommandInteractionOptionResolver<CacheType>, "getMessage" | "getFocused" | "getMentionable" | "getRole" | "getAttachment" | ... 6 more ... | "getSubcommand">'.ts(2339)
```

### Code sample

```typescript
const option = interaction.options.getSubcommand();
```

### Package version

14.1.2

### Node.js version

v16.16.0, TS 4.7.4

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

### I have tested this issue on a development release

aac8aac.0

**Comment by Jiralite** [comment]
You have provided no context whatsoever. Until then, this bug report is not useful.

**Comment by chexburger** [comment]
> You have provided no context whatsoever. Until then, this bug report is not useful.

I have included the VSCode output when hovering.

**Comment by Jiralite** [comment]
It's still not enough information.

What is the type of `interaction`?

**Comment by chexburger** [comment]
> What is the type of `interaction`?

CommandInteraction

**Comment by Jiralite** [comment]
Then this is working as expected and is not a bug. Duplicate of #8306. See the comment - it may help you.

**Comment by chexburger** [comment]
Ended up being the same issue. My typings set interaction as `ChatInteraction` and I forgot to change that with everything else even though the function required `ChatInputCommandInteraction` to be passed for interaction. Simply missed a change which was overwriting what I was looking at.
