### ISSUE TITLE
EditReply throwing error Attachment

### ISSUE THREAD

**Issue by off1n3** [discordjs/discord.js#8475]
### Which package is this bug report for?

rest

### Issue description

Im trying to send a attachment created w canvacord, the bot sent the first time, but is crashed with the next error...

### Code sample

```typescript
(node:4023) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at new Blob (node:internal/blob:138:5)
    at _RequestManager.resolveRequest (~/node_modules/@discordjs/rest/dist/index.js:892:36) 
    at async _RequestManager.queueRequest (~/node_modules/@discordjs/rest/dist/index.js:848:35)
    at async REST.request (~/node_modules/@discordjs/rest/dist/index.js:1000:22)
    at async InteractionWebhook.editMessage (~/node_modules/discord.js/src/structures/Webhook.js:324:15)
    at async ChatInputCommandInteraction.editReply (~/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:150:21)
    at async ~/src/commands/tools/rank.js:49:9
    at async Object.execute (~/src/commands/tools/rank.js:45:7)
    at async Object.execute (~/src/events/client/interactionCreate.js:12:17)
```

### Package version

yarn list v1.22.19 ├─ @discordjs/builders@1.0.0 │  ├─ @sapphire/shapeshift@^3.5.1 │  ├─ discord-api-types@^0.36.2 │  ├─ fast-deep-equal@^3.1.3 │  ├─ ts-mixer@^6.0.1 │  └─ tslib@^2.4.0 ├─ @discordjs/collection@1.0.0 ├─ @discordjs/rest@1.0.0 │  ├─ @discordjs/collection@^1.0.0 │  ├─ @sapphire/async-queue@^1.3.2 │  ├─ @sapphire/snowflake@^3.2.2 │  ├─ discord-api-types@^0.36.2 │  ├─ file-type@^17.1.2 │  ├─ tslib@^2.4.0 │  └─ undici@^5.7.0 ├─ @napi-rs/canvas-android-arm64@0.1.25 ├─ @napi-rs/canvas-darwin-arm64@0.1.25 ├─ @napi-rs/canvas-darwin-x64@0.1.25 ├─ @napi-rs/canvas-linux-arm-gnueabihf@0.1.25 ├─ @napi-rs/canvas-linux-arm64-gnu@0.1.25 ├─ @napi-rs/canvas-linux-arm64-musl@0.1.25 ├─ @napi-rs/canvas-linux-x64-gnu@0.1.25 ├─ @napi-rs/canvas-linux-x64-musl@0.1.25 ├─ @napi-rs/canvas-win32-x64-msvc@0.1.25 ├─ @napi-rs/canvas@0.1.25 │  ├─ @napi-rs/canvas-android-arm64@0.1.25 │  ├─ @napi-rs/canvas-darwin-arm64@0.1.25 │  ├─ @napi-rs/canvas-darwin-x64@0.1.25 │  ├─ @napi-rs/canvas-linux-arm-gnueabihf@0.1.25 │  ├─ @napi-rs/canvas-linux-arm64-gnu@0.1.25 │  ├─ @napi-rs/canvas-linux-arm64-musl@0.1.25 │  ├─ @napi-rs/canvas-linux-x64-gnu@0.1.25 │  ├─ @napi-rs/canvas-linux-x64-musl@0.1.25 │  └─ @napi-rs/canvas-win32-x64-msvc@0.1.25 ├─ @sapphire/async-queue@1.3.2 ├─ @sapphire/shapeshift@3.5.1 │  ├─ fast-deep-equal@^3.1.3 │  └─ lodash.uniqwith@^4.5.0 ├─ @sapphire/snowflake@3.2.2 ├─ @skyra/gifenc@1.0.0 │  └─ tslib@^2.3.0 ├─ @tokenizer/token@0.3.0 ├─ @types/node@18.6.1 ├─ @types/webidl-conversions@6.1.1 ├─ @types/whatwg-url@8.2.2 │  ├─ @types/node@* │  └─ @types/webidl-conversions@* ├─ @types/ws@8.5.3 │  └─ @types/node@* ├─ abbrev@1.1.1 ├─ anymatch@3.1.2 │  ├─ normalize-path@^3.0.0 │  └─ picomatch@^2.0.4 ├─ balanced-match@1.0.2 ├─ base64-js@1.5.1 ├─ binary-extensions@2.2.0 ├─ brace-expansion@1.1.11 │  ├─ balanced-match@^1.0.0 │  └─ concat-map@0.0.1 ├─ braces@3.0.2 │  └─ fill-range@^7.0.1 ├─ bson@4.6.5 │  └─ buffer@^5.6.0 ├─ buffer@5.7.1 │  ├─ base64-js@^1.3.1 │  └─ ieee754@^1.1.13 ├─ canvacord@5.4.2 │  ├─ @napi-rs/canvas@^0.1.25 │  ├─ @skyra/gifenc@^1.0.0 │  ├─ chalk@^5.0.1 │  ├─ moment-duration-format@^2.3.2 │  ├─ moment@^2.29.4 │  └─ node-fetch@2.6.7 ├─ chalk@5.0.1 ├─ chokidar@3.5.3 │  ├─ anymatch@~3.1.2 │  ├─ braces@~3.0.2 │  ├─ fsevents@~2.3.2 │  ├─ glob-parent@~5.1.2 │  ├─ is-binary-path@~2.1.0 │  ├─ is-glob@~4.0.1 │  ├─ normalize-path@~3.0.0 │  └─ readdirp@~3.6.0 ├─ concat-map@0.0.1 ├─ debug@3.2.7 │  └─ ms@^2.1.1 ├─ denque@2.1.0 ├─ discord-api-types@0.36.3 ├─ discord.js@14.0.3 │  ├─ @discordjs/builders@^1.0.0 │  ├─ @discordjs/collection@^1.0.0 │  ├─ @discordjs/rest@^1.0.0 │  ├─ @sapphire/snowflake@^3.2.2 │  ├─ @types/ws@^8.5.3 │  ├─ discord-api-types@^0.36.2 │  ├─ fast-deep-equal@^3.1.3 │  ├─ lodash.snakecase@^4.1.1 │  ├─ tslib@^2.4.0 │  ├─ undici@^5.8.0 │  └─ ws@^8.8.1 ├─ dotenv@8.6.0 ├─ fast-deep-equal@3.1.3 ├─ file-type@17.1.3 │  ├─ readable-web-to-node-stream@^3.0.2 │  ├─ strtok3@^7.0.0-alpha.7 │  └─ token-types@^5.0.0-alpha.2 ├─ fill-range@7.0.1 │  └─ to-regex-range@^5.0.1 ├─ fs@0.0.1-security ├─ fsevents@2.3.2 ├─ glob-parent@5.1.2 │  └─ is-glob@^4.0.1 ├─ has-flag@3.0.0 ├─ ieee754@1.2.1 ├─ ignore-by-default@1.0.1 ├─ inherits@2.0.3 ├─ ip@2.0.0 ├─ is-binary-path@2.1.0 │  └─ binary-extensions@^2.0.0 ├─ is-extglob@2.1.1 ├─ is-glob@4.0.3 │  └─ is-extglob@^2.1.1 ├─ is-number@7.0.0 ├─ kareem@2.4.1 ├─ lodash.snakecase@4.1.1 ├─ lodash.uniqwith@4.5.0 ├─ memory-pager@1.5.0 ├─ minimatch@3.1.2 │  └─ brace-expansion@^1.1.7 ├─ moment-duration-format@2.3.2 ├─ moment@2.29.4 ├─ mongodb-connection-string-url@2.5.3 │  ├─ @types/whatwg-url@^8.2.1 │  ├─ tr46@3.0.0 │  │  └─ punycode@^2.1.1 │  ├─ webidl-conversions@7.0.0 │  ├─ whatwg-url@^11.0.0 │  └─ whatwg-url@11.0.0 │     ├─ tr46@^3.0.0 │     └─ webidl-conversions@^7.0.0 ├─ mongodb@4.7.0 │  ├─ bson@^4.6.3 │  ├─ denque@^2.0.1 │  ├─ mongodb-connection-string-url@^2.5.2 │  ├─ saslprep@^1.0.3 │  └─ socks@^2.6.2 ├─ mongoose@6.4.7 │  ├─ bson@^4.6.2 │  ├─ kareem@2.4.1 │  ├─ mongodb@4.7.0 │  ├─ mpath@0.9.0 │  ├─ mquery@4.0.3 │  ├─ ms@2.1.3 │  └─ sift@16.0.0 ├─ mpath@0.9.0 ├─ mquery@4.0.3 │  ├─ debug@4.3.4 │  │  └─ ms@2.1.2 │  ├─ debug@4.x │  └─ ms@2.1.2 ├─ ms@2.1.3 ├─ node-fetch@2.6.7 │  └─ whatwg-url@^5.0.0 ├─ nodemon@2.0.19 │  ├─ chokidar@^3.5.2 │  ├─ debug@^3.2.7 │  ├─ ignore-by-default@^1.0.1 │  ├─ minimatch@^3.0.4 │  ├─ pstree.remy@^1.1.8 │  ├─ semver@^5.7.1 │  ├─ simple-update-notifier@^1.0.7 │  ├─ supports-color@^5.5.0 │  ├─ touch@^3.1.0 │  └─ undefsafe@^2.0.5 ├─ nopt@1.0.10 │  └─ abbrev@1 ├─ normalize-path@3.0.0 ├─ path@0.12.7 │  ├─ process@^0.11.1 │  └─ util@^0.10.3 ├─ peek-readable@5.0.0-alpha.5 ├─ picomatch@2.3.1 ├─ process@0.11.10 ├─ pstree.remy@1.1.8 ├─ punycode@2.1.1 ├─ readable-stream@3.6.0 │  ├─ inherits@^2.0.3 │  ├─ inherits@2.0.4 │  ├─ string_decoder@^1.1.1 │  └─ util-deprecate@^1.0.1 ├─ readable-web-to-node-stream@3.0.2 │  └─ readable-stream@^3.6.0 ├─ readdirp@3.6.0 │  └─ picomatch@^2.2.1 ├─ safe-buffer@5.2.1 ├─ saslprep@1.0.3 │  └─ sparse-bitfield@^3.0.3 ├─ semver@5.7.1 ├─ sift@16.0.0 ├─ simple-update-notifier@1.0.7 │  ├─ semver@~7.0.0 │  └─ semver@7.0.0 ├─ smart-buffer@4.2.0 ├─ socks@2.7.0 │  ├─ ip@^2.0.0 │  └─ smart-buffer@^4.2.0 ├─ sparse-bitfield@3.0.3 │  └─ memory-pager@^1.0.2 ├─ string_decoder@1.3.0 │  └─ safe-buffer@~5.2.0 ├─ strtok3@7.0.0-alpha.8 │  ├─ @tokenizer/token@^0.3.0 │  └─ peek-readable@^5.0.0-alpha.5 ├─ supports-color@5.5.0 │  └─ has-flag@^3.0.0 ├─ to-regex-range@5.0.1 │  └─ is-number@^7.0.0 ├─ token-types@5.0.0-alpha.2 │  ├─ @tokenizer/token@^0.3.0 │  └─ ieee754@^1.2.1 ├─ touch@3.1.0 │  └─ nopt@~1.0.10 ├─ tr46@0.0.3 ├─ ts-mixer@6.0.1 ├─ tslib@2.4.0 ├─ undefsafe@2.0.5 ├─ undici@5.8.0 ├─ util-deprecate@1.0.2 ├─ util@0.10.4 │  └─ inherits@2.0.3 ├─ webidl-conversions@3.0.1 ├─ whatwg-url@5.0.0 │  ├─ tr46@~0.0.3 │  └─ webidl-conversions@^3.0.0 └─ ws@8.8.1

### Node.js version

Node.js 16.16.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by monbrey** [comment]
That is a warning, not an error.

**Comment by off1n3** [comment]
> That is a warning, not an error.

I know, but the bot is crashed, after that... :( throwing in discord The application did not respond...

**Comment by off1n3** [comment]
@monbrey Sorry, trying again, I saw a situation with the client, I'd some days trying to find the problem, but is about once and on. Sorry and thanks!
