### ISSUE TITLE
Application commands' non-subcommand options types `autocomplete` as `false | undefined`

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#8477]
### Which package is this bug report for?

discord.js

### Issue description

`autocomplete` is typed as `false | undefined` in an application command's option.

If we look at the typings:

https://github.com/discordjs/discord.js/blob/c97977a3e806bd5d8682bc7fb22ebec1a8ceecdc/packages/discord.js/typings/index.d.ts#L3921-L3947

`ApplicationCommandOptionData` contains `ApplicationCommandAutocompleteOption`, but there seems to be no equivalent for `ApplicationCommandOption`. This may be the cause of this issue.

For subcommand options, this will seemingly be fixed in #8476.

### Code sample

```typescript
import { ApplicationCommandManager, ApplicationCommandOptionType } from "discord.js";

declare const applicationCommandManager: ApplicationCommandManager;
const applicationCommand = await applicationCommandManager.fetch("123");

const option = applicationCommand.options[0]!;

if (option.type === ApplicationCommandOptionType.String) {
  if (option.autocomplete === true) {
    // never
  }
}
```

### Package version

main

### Node.js version

Node.js 16.14.0; TypeScript 4.7.4

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

c97977a3e806bd5d8682bc7fb22ebec1a8ceecdc

**Comment by reallyslimy** [comment]
Hi,
I was slightly annoyed by this issue as well.

I'm using:
**Typescript 4.7.4**
**Node 18.4.0**

And I've got the same problem as you.
So I've taken action on it, seems like discordjs have some "hard" typed values in the typings.

```
export interface BaseApplicationCommandOptionsData {
  name: string;
  nameLocalizations?: LocalizationMap;
  description: string;
  descriptionLocalizations?: LocalizationMap;
  required?: boolean;
  autocomplete?: never;
}
```
For example, with that TypeScript cannot assign a true | false, but only a never value into the code.
So changing this hard typings into booleans, seems to solve the issue as I tested.

![image](https://user-images.githubusercontent.com/36748666/184627374-6b16c96b-8b19-4d81-9a2e-c4798368a09d.png)

Here's my code:
```
 options: [
        {
            name: "play",
            type: ApplicationCommandOptionType.Subcommand,
            description: "Play a song in the vc channel.",
            options:[
                {
                    name: "query",
                    type: ApplicationCommandOptionType.String,
                    description: "Which song do you want to play?",
                    autocomplete: true
                }
            ]
        },
```

I'll try to put a PR into this issue as soon as I can, if not you can ask me how I done it and I'll respond you happily.
