### ISSUE TITLE
Collector#end does not emit

### ISSUE THREAD

**Issue by Tomato6966** [discordjs/discord.js#8488]
### Which package is this bug report for?

discord.js

### Issue description

It does not work to emit the #end on the collector, other have this bug too! see discord.jsv14 discord support chat channel

### Code sample

```typescript
const collector = msg.createMessageComponentCollector({ filter: (i) => i.user, idle: Millisecond.Second * 30 });
collector.on("collect", () => "works");
// does NOT work
collector.on("end", (collected, reason) => {
  console.log("STOPPIGN QUEUE CMD")
  if(!reason) msg.edit({ components: getDisabledComponents(msg.components) }).catch(console.warn);
})
```

### Package version

14.1.2

### Node.js version

16.16.0

### Operating system

ubuntu  20.04.4 LTS Focal

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents

**Comment by Tomato6966** [comment]
Note:
*The functionality of the Collector ends, but the listener for "end" does not execute the callback function*

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this on `14.1.2` and `14.2.0`, as well as bc06cc638d2f57ab5c600e8cdb6afc8eb2180166; The event is emitting fine for me.

**Comment by Tomato6966** [comment]
The collector is ending, but the event is not firing

**Comment by Jiralite** [comment]
> The collector is ending, but the event is not firing

I cannot reproduce this. Using the code sample you have provided on 14.2.0, the event is fired.

**Comment by Tomato6966** [comment]
Got it to work, by removing the makeCache
