### ISSUE TITLE
Random connection errors

### ISSUE THREAD

**Issue by virtual-designer** [discordjs/discord.js#8489]
### Which package is this bug report for?

discord.js

### Issue description

Random connection errors especially when using slash commands. I'm 100% sure my connection is strong enough. The error is given below:

```
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:131:24)
    at D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:78:46
    at Immediate._onImmediate (D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:117:33)
    at processImmediate (node:internal/timers:464:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
```

### Code sample

```typescript
// client = discord client
// this code might not always fail - for me the error was coming randomly

client.on('interactionCreate', async (interaction) => {
   if (interaction.isChatInputCommand()) {
      // do some stuff like bulk deleting messages or warning users

     await interaction.reply({ content: 'Done' });
   }
});
```

### Package version

v14.2.0

### Node.js version

v16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildInvites, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

**Comment by Jiralite** [comment]
Possibly relevant: https://github.com/nodejs/undici/issues/1531

**Comment by virtual-designer** [comment]
Update: v13 works fine for me, without any errors!

**Comment by Larsundso** [comment]
having the same issues, but it's undici acting up, not d.js

**Comment by eightless** [comment]
Having the same issue, but exceptionally on Ubuntu VPS, on Mac everything works properly.

**Comment by Raz-js** [comment]
I had a similar problem that only started occuring when i selfhosted but i have an idea now, ill get back to you

**Comment by EduApps-CDG** [comment]
reproducible here

**Comment by cwkhawand** [comment]
Can reproduce too. Happens randomly on an Ubuntu VPS.

**Comment by JPBM135** [comment]
I found two instances of requests from djs that uses fetch as it'srequest source:

> <https://github.com/discordjs/discord.js/blob/5d8bd030d60ef364de3ef5f9963da8bda5c4efd4/packages/discord.js/src/util/Util.js#L227>

> <https://github.com/discordjs/discord.js/blob/5b053cf82ec2f2b717a490485af052dc956fe3c9/packages/discord.js/src/util/DataResolver.js#L126>

My bet would be in the first one, since it's called on every bot start!!

**Comment by TheGalacticAce** [comment]
Hey, I'm experiencing this issue. How do I fix it?

**Comment by Jaxofw** [comment]
Has a fix been found for this yet? I'm experiencing the same issue on my Ubuntu server.

**Comment by Satindar31** [comment]
Did anyone find a fax?
