### ISSUE TITLE
Getting DiscordAPIError[50035] on creating an SlashCommand with a subCommand

### ISSUE THREAD

**Issue by Johannes7k75** [discordjs/discord.js#8500]
### Which package is this bug report for?

builders

### Issue description

Steps to reproduce the error:
1. Copy the code below but in your Guild and Token at line 2 and 3
2. Start the Bot 
3. Observer the error thrown in the terminal [error.log](https://github.com/discordjs/discord.js/files/9351787/error.log)

PS: I got it fixed. I had only to add th etypes in the [SlashCommandSubcommands.mjs](https://gist.github.com/Johannes7k75/57cb18c782969bdd8ee12cb257ec50b9) and [SlashCommandSubcommands.cjs](https://gist.github.com/Johannes7k75/255ab944c1b1177da950310080d47ea4) file.

### Code sample

```typescript
const { Client, SlashCommandBuilder, SlashCommandStringOption } = require("discord.js");
const token = "TOKEN"
const guild= "GUILDID"

class Command {
    constructor(data) {
        this.name = data.name;
        this.description = data.description;
        this.options = data.options;
    }
}
class SlashCommand extends Command{
    constructor() {
        super({
            ...new SlashCommandBuilder().setName("message").setDescription("Send a message as the bot")
            .addSubcommand(subCommand=>subCommand.addStringOption(new SlashCommandStringOption().setName("message").setDescription("The message to send").setRequired(true)).setName("message").setDescription("What message do you want to send?"))
        })
    }
}


class TestClient extends Client {
    constructor(options) {
        super({
            intents: ["Guilds"]
        })
        this.token = options.token
    }

    login() {
        return super.login(this.token)
    }
}

const client = new TestClient({
    token: token
})

client.on("ready", ()=>{
    client.guilds.cache.get(guild).commands.create(new SlashCommand())
})

client.login()
```

### Package version

@discordjs/builders@1.1.0

### Node.js version

18.7.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
This is not a discord.js issue (discord.js transforms the builder, not builders). You are losing the type because `.toJSON()` is not being called anywhere.
