### ISSUE TITLE
parseEmoji function is invalid

### ISSUE THREAD

**Issue by Tomato6966** [discordjs/discord.js#8509]
### Which package is this bug report for?

discord.js

### Issue description

When calling this function, it does not parse the Emoji right... 
parseEmoji("<:N:988907342735245392>");

However it's a valid emoji see:
![image](https://user-images.githubusercontent.com/68145571/185048476-307dfe79-bfd0-4e4a-abd7-22de9e5a22ba.png)

the regex for that function should be ...1,32... not ...2,32...

or use something like javascript:
```js
str = str.trim();
if(str.includes("<")) {
        const splitted = str.replace(">", "").replace("<", "").split(":").reverse().filter(Boolean);
        const [id, name, aData] = splitted[0];
        const animated = !!(aData && aData === "a")
        return { id, name, animated, str }
}
return { id: undefined, str, name: str, animated: false }
```

### Code sample

```typescript
parseEmoji("<:N:988907342735245392>");
```

### Package version

14.1.2

### Node.js version

16.16.0

### Operating system

ubuntu  20.04.4 LTS Focal

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Tomato6966** [comment]
Correct regex: (tested and works)

```js
function parseEmoji(text) {
  if (text.includes('%')) text = decodeURIComponent(text);
  if (!text.includes(':')) return { animated: false, name: text, id: undefined };
  const match = text.match(/<?(?:(a):)?(\w{1,32}):(\d{17,19})?>?/);
  return match && { animated: Boolean(match[1]), name: match[2], id: match[3] };
}
```

**Comment by ckohen** [comment]
That is in fact *not* a valid emoji. Emoji names have to be 2 or more characters. It just so happens that when rendering emoji discord doesn't actually care about the name (it'll change it when you're sending it from the client). It looks up the emoji by id only. If you can find the source guild of that emote and confirm that it does not actually have a different name, then there was an API bug at some point to allow that to happen.

**Comment by Tomato6966** [comment]
the emoji has 1 letter name, i created it.
![image](https://user-images.githubusercontent.com/68145571/185147646-cae87e39-b16a-41e2-b968-3ff326b97936.png)

**Comment by Tomato6966** [comment]
oh okay, but for me it doesnt show the _ anyways i changed it to No now, thanks

**Comment by ItsFranklinMyDudes** [comment]
> Correct regex: (tested and works)
> 
> ```js
> function parseEmoji(text) {
>   if (text.includes('%')) text = decodeURIComponent(text);
>   if (!text.includes(':')) return { animated: false, name: text, id: undefined };
>   const match = text.match(/<?(?:(a):)?(\w{1,32}):(\d{17,19})?>?/);
>   return match && { animated: Boolean(match[1]), name: match[2], id: match[3] };
> }
> ```

yo thx for this function, works like a charm
