### ISSUE TITLE
Discord.js don't detect game status

### ISSUE THREAD

**Issue by Duskley** [discordjs/discord.js#8525]
### Which package is this bug report for?

discord.js

### Issue description

1) Go to Discord settings and put an activity such as the VSC for example

![image](https://user-images.githubusercontent.com/65198558/185608191-fa38bba9-8649-40a6-97e1-82cd666151f6.png)
![image](https://user-images.githubusercontent.com/65198558/185608273-09ce8160-a5d5-45b9-b4b4-28519fe80705.png)

2) Go offline
3) Run the bot with presenceUpdate event
4) Go online
5) The bot will return an empty array for newPresenceActivity

### Code sample

```typescript
module.exports = {
	name: 'presenceUpdate',
	execute(oldPresence, newPresence) {
		console.log(oldPresence.activities)
		console.log(newPresence.activities)
	},
};
```

### Package version

discord.js@14.2.0

### Node.js version

v16.10.0

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildPresences

### I have tested this issue on a development release

discord.js@14.3.0-dev.1660867916-673262d.0

**Comment by Jiralite** [comment]
You are missing the `GUILDS` intent. If that is intentional, the guild is not cached.

**Comment by Duskley** [comment]
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildPresences] });

**Comment by Duskley** [comment]
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildPresences] });

**Comment by Duskley** [comment]
![image](https://user-images.githubusercontent.com/65198558/185611543-09bb4b87-0761-406e-90bd-43fb42ec2ace.png)

**Comment by Jiralite** [comment]
> const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildPresences] });
> 
> Am I missing an intent?

As seen in your original comment, you were missing the `GUILDS` intent. Now that you have added it, it ideally should work.

Keep in mind people may not want to share their activity status or not want to share it to a specific guild you are listening to. If it still does not emit, I cannot reproduce this as it works for me:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/33201955/185612235-c8e15a28-9cee-49b7-a15f-b9d287fcb521.png">

**Comment by Duskley** [comment]
I had forgotten to put it in the issue but it was there before. For your presence, did Discord add it automatically or did you add it manually? Our 2 codes are identical in the way of functioning but the result diverges however

**Comment by Jiralite** [comment]
> Our 2 codes are identical in the way of functioning but the result diverges however

I think this may answer your question. Looking at the raw packets Discord send:

```JavaScript
{
  t: 'PRESENCE_UPDATE',
  s: 6,
  op: 0,
  d: {
    user: {
      username: 'Jiralite',
      public_flags: 16640,
      id: '618976181026422814',
      discriminator: '1207',
      avatar: 'aca408fd7206f0903d1a2c055a4d1c48'
    },
    status: 'online',
    guild_id: '534940241002233896',
    client_status: { desktop: 'online' },
    activities: []
  }
}
{
  t: 'PRESENCE_UPDATE',
  s: 7,
  op: 0,
  d: {
    user: {
      username: 'Jiralite',
      public_flags: 16640,
      id: '618976181026422814',
      discriminator: '1207',
      avatar: 'aca408fd7206f0903d1a2c055a4d1c48'
    },
    status: 'online',
    guild_id: '886323824801488996',
    client_status: { desktop: 'online' },
    activities: [ [Object] ]
  }
}
```

When going offline to online in a large server (I tested there for now), Discord fires two `PRESENCE_UPDATE` events. In the first payload, we can see the `status` is "online". In the second payload, we can see the same but `activities` is populated.

So what's probably happening is you are receiving an empty array when a member comes online for the first time, _then_ Discord sends the activities over the gateway.

**Comment by Duskley** [comment]
hum ok I see I just wonder how I can test this now. What I can try is to put a custom status and then remove it. I was able to test precisely with a personalized status and I have the activity.

what class are you using to display the discord packets?

**Comment by Jiralite** [comment]
You can test this by listening to the raw events (`<Client>.on("raw", console.log);`). But as it stands, this does not seem to be an issue with discord.js as I get the activities fine with respect to how Discord sends them.

**Comment by Duskley** [comment]
ok I will test thank you anyway and yes it seems to come from my side :/. Thank you so much anyway !
