### ISSUE TITLE
Wrong type def in ApplicationCommandOptionChoiceData.value

### ISSUE THREAD

**Issue by kubahasek** [discordjs/discord.js#8528]
### Describe the bug

When I was writing my slash command today, I attempted to enter a value of a choice of 1, but then got an API error saying values can only be strings. The library allows to put numbers as well

### To Reproduce

1. Create a slash command
2. Add a choice where the value is a number.

### Device (please complete the following information)

macOS Monterrey
DiscordJS v14

**Comment by Jiralite** [comment]
Alright, so the confusion stemmed from making the issue in the wrong place. You're reporting a bug with the discord.js package, so this is the place to be.

**Comment by kubahasek** [comment]
Okay, my bad. Need anything else from me?
