### ISSUE TITLE
Discord Embed inline not working when setting image

### ISSUE THREAD

**Issue by HRK44** [discordjs/discord.js#8534]
### Which package is this bug report for?

discord.js

### Issue description

Without image : 

![image](https://user-images.githubusercontent.com/7391040/185780257-48a917e1-1884-4cf0-8fe1-ca731dcfd889.png)

After using `.setImage('https://yhublvzzeieaiowed7p5jg22jq3ef2sqstswj4kwcazm75dtb6gq.arweave.net/wegV1zkiCAQ6xB_f1JtaTDZC6lCU5WTxVhAyz_RzD40?ext=png')` : 

![image](https://user-images.githubusercontent.com/7391040/185780290-87b19357-ac84-4eae-8bc6-18f6ac4a67ce.png)

### Package version

14.2

### Node.js version

16.3

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by Jiralite** [comment]
> Discord Embed inline not working when setting image

It looks like it is working to me...?

**Comment by HRK44** [comment]
@Jiralite I added some red circles :D 

![image](https://user-images.githubusercontent.com/7391040/185780697-ca69c4c6-33af-4bd9-abb2-a616bf7bec11.png)

**Comment by Jiralite** [comment]
That's just how Discord works. It resizes to the image. It's not a bug.
