### ISSUE TITLE
Bot not connecting after update to 14.3.0

### ISSUE THREAD

**Issue by 7heMech** [discordjs/discord.js#8543]
### Which package is this bug report for?

discord.js

### Issue description

My bot is suddenly not connecting after update to 14.3.0.
I logged the debug event and all it gives is:
Provided token: MTAxMDI5MjI0MTUxMzg0NDc4Nw.GtWR2b.**************************************
Preparing to connect to the gateway...

### Package version

14.3.0

### Node.js version

v16.13.2

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by almostSouji** [comment]
Cannot reproduce on `14.3.0`, bot starts as it did pre-update on `14.2.0`
Please try to reproduce the issue with a minimal bot and post the code you can reproduce it with.

**Comment by DTrombett** [comment]
You're most probably getting rate-limited by Discord, that's why it's impossible to fetch gateway info.

I had the same problem (unrelated to the version) and I think an error or something should be logged to let the developer know.
