### ISSUE TITLE
GuildMemberRoleManager cache() throws an error in case @everyone role is missing

### ISSUE THREAD

**Issue by marko1010** [discordjs/discord.js#8552]
### Which package is this bug report for?

discord.js

### Issue description

GuildMemberRoleManager cache() getter throws an error in case @everyone role is missing

**TypeError: Cannot read properties of undefined (reading 'id')**

```
  get cache() {
    const everyone = this.guild.roles.everyone;
    return this.guild.roles.cache.filter(role => this.member._roles.includes(role.id)).set(everyone.id, everyone);
  }
```

### Code sample

```typescript
const guild = await discordClient.guilds.fetch("GUILD_ID");
// await guild.roles.fetch(); // uncommenting this line would be a workaround
const members = await guild.members.fetch();
await member[0].roles.add("ROLE_ID");
```

### Package version

14.3.0

### Node.js version

16.16.0

### Operating system

Windows Server 2022

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by Jiralite** [comment]
This would be classed as not a bug. To show you the roles of the guild member, we'd also need the `@everyone` role. That isn't present when fetching a guild member (only the role ids of every other role are) so we'd have to check in the `RoleManager`. The cache of that manager is empty though, so yes, you should do `await guild.roles.fetch();` to ensure you receive all the guild member roles. Or, use the `GUILDS` intent.

Additionally:

> ```JavaScript
> await member[0].roles.add("ROLE_ID");
> ```

This will cause your code to error as `member` is not defined.

**Comment by marko1010** [comment]
@Jiralite The intention of the code is to add a role, not show the roles the member has. Being required to fetch all roles before you can add/remove a role to the member seems like a bad design.

**Comment by Jiralite** [comment]
> Being required to fetch all roles before you can add/remove a role to/from a member seems like a bad design.

You don't, though. You don't even need to fetch guild members. It seems like you are unaware of how to do this. After fetching the guild, you may call [Guild#members#addRole](https://discord.js.org/#/docs/discord.js/main/class/GuildMemberManager?scrollTo=addRole).

**Comment by marko1010** [comment]
You just pointed out a different way to do the same thing which is not the
subject of this issue I opened. This is a bug.
