### ISSUE TITLE
SlashCommandChannelOption#setName does not accept null or undefined values

### ISSUE THREAD

**Issue by TsWin** [discordjs/discord.js#8553]
### Which package is this bug report for?

builders

### Issue description

I just created a slash command with a channel option and it gives me this error.
I think it's comming from `setName` being undefined
If I add `setNameLocalizations` or `setDescriptionLocalizations` I shouldn't need `setName` right ?
![Screenshot 2022-08-24 at 19 48 59](https://user-images.githubusercontent.com/57185227/186488321-2fc4246b-a82e-4672-8b73-4d1bc250d310.png)

_Sorry for bad issue description, it's my first one and I'm not sure if it's a real discord.js issue_
 

### Code sample

```typescript
const { SlashCommandBuilder } = require("discord.js");
const command = new SlashCommandBuilder()
.setNameLocalizations({"en-US": "say", "fr": "dire"})
.setDescriptionLocalizations({"en-US": "some description in en", "fr": "some description in fr"});
// some useless code between
command.addChannelOption((op) => 
op.setNameLocalizations({"en-US": "testen", "fr": "testfr"})
.setDescriptionLocalizations({"en-US": "description en", "fr": "description fr"})
.setRequired(false)
.runRequiredValidations());
```

### Package version

14.1.2

### Node.js version

16.16.0

### Operating system

Mac OS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

**Comment by DTrombett** [comment]
The name is still required. It is used as default

**Comment by Jiralite** [comment]
> I just created a slash command with a channel option and it gives me this error. I think it's comming from `setName` being undefined If I add `setNameLocalizations` or `setDescriptionLocalizations` I shouldn't need `setName` right ? 

This is an incorrect assumption. You need them.

> Sorry for bad issue description, it's my first one and I'm not sure if it's a real discord.js issue

If you are not sure if something is an issue, you should ask in the [discord.js](https://discord.gg/djs) Discord server where people can help you.

**Comment by Juknum** [comment]
It might be related to #8518?

**Comment by Jiralite** [comment]
No. Please see my comment.
