### ISSUE TITLE
npm install @discordjs/ws --- npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by adam-a** [discordjs/discord.js#8555]
### Which package is this bug report for?

ws

### Issue description

1. Install `discordjs/ws` via `npm install @discordjs/ws` ([as outlined by docs](https://www.npmjs.com/package/@discordjs/ws))

### Code sample

```typescript
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@discordjs%2fws - Not found
npm ERR! 404 
npm ERR! 404  '@discordjs/ws@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[me]/.npm/_logs/2022-08-25T06_38_31_908Z-debug-0.log
```
```


### Package version

14

### Node.js version

18.6.0

### Operating system

_No response_

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

**Comment by kyranet** [comment]
I cannot reproduce this with the given steps:
![image](https://user-images.githubusercontent.com/24852502/186593665-85600dcf-2174-4dcc-bd69-4c0f34e54940.png)

Are you sure you're not doing something else?

**Comment by imranbarbhuiya** [comment]
even the URL present in your log https://registry.npmjs.org/@discordjs%2fws returns valid package info. Maybe npm was having some issues when u were trying to download the package. Try again or try a different package manager.

**Comment by adam-a** [comment]
> I cannot reproduce this with the given steps: ![image](https://user-images.githubusercontent.com/24852502/186593665-85600dcf-2174-4dcc-bd69-4c0f34e54940.png)
> 
> Are you sure you're not doing something else, perhaps installing `@discord.js/ws` instead of [`@discordjs/ws`](https://www.npmjs.com/package/@discordjs/ws)?

Hi!

Here's what I'm running:

`[me]@[me]-MBP shared_services % npm install @discordjs/ws
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fdiscordjs - Not found
npm ERR! 404 
npm ERR! 404  '@types/discordjs@^14.3.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[me]/.npm/_logs/2022-08-25T16_17_57_891Z-debug-0.log
[me]@[me]-MBP shared_services % node -v`

**Comment by SpaceEEC** [comment]
This log looks like you are trying to install `@types/discordjs`, which does not exist.
discord.js ships with typings; You do not need to install them separately.

**Comment by adam-a** [comment]
> This log looks like you are trying to install `@types/discordjs`, which does not exist. discord.js ships with typings; You do not need to install them separately.

thanks! That was it -- I added those for some reason and it was causing this issue. Removed and re-ran install and it worked.
