### ISSUE TITLE
JS12 bot crashing with new voice channel text V12

### ISSUE THREAD

**Issue by aziz191546** [discordjs/discord.js#8578]
### Which package is this bug report for?

discord.js

### Issue description

JS12 bot crashing with new voice channel text V12
if send somthing in voice text bot crash

### Package version

v12

### Node.js version

v14.17.1

### Operating system

ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by Jiralite** [comment]
Version 12 is not supported. Update.

https://discordjs.guide/additional-info/changes-in-v13.html
https://discordjs.guide/additional-info/changes-in-v14.html
