### ISSUE TITLE
Add subcommand check to ChatInputInteractionOptions

### ISSUE THREAD

**Issue by Stefouch** [discordjs/discord.js#8581]
### Which package is the feature request for?

builders

### Feature

I would like to test if a command has a subcommand from an interaction.

But:

```js
 // Throws a TypeError if no subcommand
if ( interaction.options.getSubcommand() )

// Does work, but is not documented
// and flags a "ts(2551) Property '_subcommand' does not exist" error in my VS Code IDE
if ( interaction.options._subcommand != null ) 
```

### Ideal solution or implementation

Any of the following:
- Don't throw an error on using `getSubcommand()` on an command with no subcommand
- or, Document and allow the use of the `._subcommand` property
- or, Create a new method that can check if a command has subcommands.

**Comment by Jiralite** [comment]
Why don't you just do `getSubcommand(false)`?

**Comment by monbrey** [comment]
Or catch the error. Proper error handling is a perfectly valid checking mechanism.

**Comment by Stefouch** [comment]
> Why don't you just do `getSubcommand(false)`?

Damned, you're right. That should do the trick! Thank you, problem solved!
