### ISSUE TITLE
interaction.editReply() kills message contents with only emojis

### ISSUE THREAD

**Issue by Stefouch** [discordjs/discord.js#8588]
### Which package is this bug report for?

discord.js

### Issue description

1. I have a message, a reply to a slash command, with rolled dice.
2. The message content is only emojis and an embed + button components.
3. When the user clicks the button 'push', it edits the message (with `interaction.editReply()` content, embed and components with updated data (the roll change, and sometimes an extra emoji is added)
4. All the emojis are dead (see gif below)

![Discord_oOPG94KEiX](https://user-images.githubusercontent.com/47865544/188273144-7ba64d66-5afa-4925-a908-d6474946dc11.gif)

Note: editing any part of the message (like only the embed, or the components), kills the emojis.

Fun fact, if using `message.edit()` instead of `interaction.editReply()`, it does work as intended. See below:

![Discord_vCTaMYpfBF](https://user-images.githubusercontent.com/47865544/188273239-5a03a045-6dbd-4513-91bb-4b57dd04499a.gif)

### Code sample

```typescript
// ? "interaction" is the original interaction from the original message
// ? "i" is the button interation

const message = await interaction.fetchReply();

collector.on('collect', async i => {
  if (i.customId === 'push-button') {

    const messageData = {
      content: '<:alienb6:746320623436955691><:alienb6:746320623436955691><:alienb6:746320623436955691>', // Only emojis
      embeds: [embed], // Edited embed
      components: [], // Remove the buttons
    };

    // This method kills the emojis
    await interaction.editReply(messageData);

    // But this method works as expected
    await message.edit(messageData);
    // But doing this way, I must use this line or I'll get a "interaction failed" message in Discord
    await i.deferUpdate();
  }
  else if (i.customId === 'cancel-button') {
    collector.stop();
  }
});

collector.on('end', async () => {
  if (message.components.length) {

    // Removing the buttons with this methods also kills the emojis
    await interaction.editReply({ components: [] });

    // But this method works
    await message.edit({ components: [] });
  }
});
```

### Package version

14.3.0

### Node.js version

16.16.0

### Operating system

Win 10 Pro 21H2

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions

**Comment by Jiralite** [comment]
This isn't a discord.js issue. See https://github.com/discord/discord-api-docs/issues/5279.
