### ISSUE TITLE
EmbedBuilder#setAuthor and EmbedBuilder#setFooter doesn't show up the given url

### ISSUE THREAD

**Issue by NotAditya69** [discordjs/discord.js#8603]
### Which package is this bug report for?

discord.js

### Issue description

The setFooter and setAuthor url property won't display it's value in the embed, More information on the code sample

![image](https://user-images.githubusercontent.com/90441096/188909701-97eaf71f-0bc2-4298-97bd-46f2f157d8e5.png)

### Code sample

```typescript
const embed = client.embeds
    .generateEmbed()
    .setAuthor({ name: user.tag, url: `${user.displayAvatarURL()}` })
    .setDescription(
      `• Command Parameters: \`<>\` is strict & \`[]\` is optional\n• [Invite](${client.config.links.invite}) | [Support](${client.config.links.support}) | [Vote](${client.config.links.topgg})`
    )
    .setFooter({
      text: `Imagine a bot of your dreams 💖`,
      url: `${client.user.displayAvatarURL()}`,
    })
    .addFields({
      name: "__Modules__",
      value: `>>> ${cat.join("\n")}`,
      inline: false,
    });

/* here user is a function parameter taking in the User key from CommandInteraction
 But as it seems the url for footer and author doesn't work the methods generates the string with the cdn endpoint and the avatar hash but the issue is with the EmbedBuilder methods setFooter and setAuthor */
```

### Package version

14.3.0

### Node.js version

16.9.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
This code sample is not reproducible. What is `user`? What is `client.embeds`? What is `generateEmbeds()`?

**Comment by NotAditya69** [comment]
client.embeds is a constructor of my own embed manager class which extends to EmbedBuilder and i haven't overwritten anything just added a method generateEmbed() which does is creates a embed with a specific color and that's it and then we can chain more setters also user is `<CommandInteraction>.user`

**Comment by Jiralite** [comment]
> client.embeds is a constructor of my own embed manager class which extends to EmbedBuilder and i haven't overwritten anything

If you have not overwritten anything, then this is not a bug. In your screenshot, the `url` does exist and it does show up, by the way. It's a URL on the author's name. I'm assume you wanted the `iconURL` instead. For the footer, there is no `url`.
