### ISSUE TITLE
.setMessage() option for Embeds

### ISSUE THREAD

**Issue by DragosPV** [discordjs/discord.js#8610]
### Which package is the feature request for?

builders

### Feature

A `.setMessage('messageID')` option for Embeds, it would look like a blocked message by AutoMod inside the embed, here is an image with the message I am referring to, and the best place for it I think is after the description, if it works with attachments even better

![image](https://user-images.githubusercontent.com/98609931/189103764-9677b968-1c51-41ad-975f-f10caa5091ba.png)

### Ideal solution or implementation

.

**Comment by imranbarbhuiya** [comment]
1. builder will just build an embed it can't fetch the message with message id
2. discord doesn't allow sending this type of embed
3. if u want to send it as an attachment, you should do it yourself code as it's a single user's usecase
4. or request to discord to allow sending this type of embeds (which I don't think they'll allow)
