### ISSUE TITLE
USERS_PATTERN does not seem to accurately match a user mention correctly. 

### ISSUE THREAD

**Issue by Stark-program** [discordjs/discord.js#8620]
### Which package is this bug report for?

discord.js

### Issue description

To reproduce error just try and match a user tag utilizing the package:

const {
  MessageMentions: { USERS_PATTERN },
} = require("discord.js");

I split the string into single elements, allowing me to handle each word in the string respectively. 

In my best understanding of the documentation, the USERS_PATTERN should be able to pick up on a mention if it makes up the entire string, which split provides.

When matching with USERS_PATTERN, it does not seem to match the mention correctly. 

I may be misunderstanding its implementation but I have been referencing the discordJs documentation listed here: https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#using-regular-expressions

To provide further context. I also matched the mention with raw RegEx to show that matching is working. 

### Code sample

```typescript
Here is the function being called. 

    function spliceUserMention(mention: string) {
      const messageContent = mention.split(" ");
      const userMentions = messageContent.filter((word) => {
        const matched = word.match(/^<@!?(\d+)>$/);
        const matched2 = word.match(USERS_PATTERN);
        console.log("this is matchedWithRegex", matched);
        console.log("this is matchedWithUsers_Pattern", matched2);
      });
    }

Here is the log of both "matched" and "matched2"

this is matchedWithRegex [
  '<@537724618245537793>',
  '537724618245537793',
  index: 0,
  input: '<@537724618245537793>',
  groups: undefined
]
this is matchedWithUsers_Pattern [ '', index: 0, input: '<@537724618245537793>', groups: undefined ]
this is matchedWithRegex [
  '<@229126478137131008>',
  '229126478137131008',
  index: 0,
  input: '<@229126478137131008>',
  groups: undefined
]
this is matchedWithUsers_Pattern [ '', index: 0, input: '<@229126478137131008>', groups: undefined ]
this is matchedWithRegex [
  '<@127584859508965378>',
  '127584859508965378',
  index: 0,
  input: '<@127584859508965378>',
  groups: undefined
]
this is matchedWithUsers_Pattern [ '', index: 0, input: '<@127584859508965378>', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'are', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'we', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'getting', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'on', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'new', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'world', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'when', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'the', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'new', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'expansion', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'is', groups: undefined ]
this is matchedWithRegex null
this is matchedWithUsers_Pattern [ '', index: 0, input: 'out', groups: undefined ]
```

### Package version

14.0.3

### Node.js version

18.6

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by imranbarbhuiya** [comment]
https://github.com/discordjs/discord.js/blob/stable/src/structures/MessageMentions.js#L228 is a global regex so you won't be able to get the capture groups. U can use  `matchAll` as mentioned in https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#using-regular-expressions

**Comment by Jiralite** [comment]
Are you sure you're using version 14.0.3?

Either way, this is not a bug - see the above comment. The guide seems to be referencing version 13 code in your linked page - that is a separate issue.
