### ISSUE TITLE
types: overriding `events.once` type causes bad intellisense autocompletion elsewhere

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/discord.js#8634]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://user-images.githubusercontent.com/42794878/190916243-3e81a963-fedc-4685-90a5-5739497ec2ec.png)

### Code sample

```typescript
import { once } from 'events'
import { createServer } from 'http'
import { request } from 'undici'

const server = createServer(async (req, res) => {
	req.setEncoding('utf-8')
	for await (const chunk of req) console.log(chunk)
	
	res.end()
}).listen(0)

await once(server, '') // <-----

// @ts-ignore
await request(`http://localhost:${server.address().port}`, {
	body: new Uint8Array([65, 66, 67, 68])
})

server.close()
```

### Package version

14.3.0

### Node.js version

18.9.0

### Operating system

n/a

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by imranbarbhuiya** [comment]
https://github.com/discordjs/discord.js/pull/7986#discussion_r886333659

**Comment by KhafraDev** [comment]
>  It has no effect on the event emitter types for anything else

@suneettipirneni this seems like a bug as it shouldn't affect other, non-djs things?

**Comment by imranbarbhuiya** [comment]
> or is it because both node's http server and discord.js Client extend EventEmitter?

yeah because the type in djs is adding an overload to the `node:events` so you'll see all these event names + any other overload if exists + any string

**Comment by suneettipirneni** [comment]
> yeah because the type in djs is adding an overload to the node:events so you'll see all these event names + any other overload if exists + any string

I'm not entirely sure why this is the case since I expect overloads to match based on parameter type. Nonetheless I suppose this would need to be reverted.
