### ISSUE TITLE
Adding a string length property to embeds builders

### ISSUE THREAD

**Issue by robotzurg** [discordjs/discord.js#8647]
### Which package is the feature request for?

discord.js

### Feature

In v13 you used to be able to use .length to get the total text length of all the text in an embed (author, title, description, fields, etc.) but in v14 this was not added to the EmbedBuilder, and thus there doesn't appear to be a way to get this information now without doing it manually. From what I've heard it seems to be still returned from the API, so it doesn't seem like it'd be too hard to add back in.

### Ideal solution or implementation

When using .length on an EmbedBuilder, it should return the total text length of the entire embed from the API.

**Comment by imranbarbhuiya** [comment]
You can do it using https://discord.js.org/#/docs/builders/main/function/embedLength
