### ISSUE TITLE
Consider automatically using editReply for deferred interaction replies

### ISSUE THREAD

**Issue by gc** [discordjs/discord.js#8649]
### Which package is the feature request for?

discord.js

### Feature

If you call `interaction.reply("Hi!")` on an interaction which has been deferred, automatically edit the reply (`editReply`) instead of throwing an error.

It can be beneficial in larger code bases with many moving parts, e.g. middleware-type things, or interactive things which attach/fork off interactions - one of my specific use cases: I have a system for asking the user to confirm by clicking a button, mid-interaction/command, and the confirmation button system automatically defers the reply to the original interaction to "pause" that command while it waits for you to confirm in the side-interaction. This would make it basically impossible to rely on `interaction.reply` to work without erroring, without checking if the interaction has deferred every time, or never using .reply and having to use my own function like `replyInteraction(interaction, response)`. I had this functionality implemented in my own framework, but am now switching to d.js (only made my own framework because d.js interactions wasnt ready at the time)

## Example

Before
```ts
interaction.deferReply();
if (interaction.deferred) {
   interaction.editReply("Hello");
} else { 
   interaction.reply("Hello");
}
```

After
```ts
interaction.deferReply();
interaction.reply("Hello");
```

### Ideal solution or implementation

```ts
reply() {
    if (this.deferred) return this.editReply(replyOptions);
// ...rest is normal
```

**Comment by Jiralite** [comment]
This reminds me of #6545 - see that issue for context. Key points:

- https://github.com/discordjs/discord.js/issues/6545#issuecomment-907697162
- https://github.com/discordjs/discord.js/issues/6545#issuecomment-907729849

I personally do not want this and it might start an incentive to do this for other methods. discord.js isn't a framework - it is a wrapper around Discord's API. I'd expect when we reply to an interaction, we perform a specific API request - not varying API requests or even multiple.

**Comment by gc** [comment]
I agree with the sentiment on discord.js being/doing simple straightforward things and my suggestion (some convenient/DX magic) is more of a framework thing to do. Plus, it might be hard/impossible to add types for it depending on how its coded. Sucks because it is such a convenient thing. Closing because on second thoughts, I agree that just implementing my own `interactionReply(interaction, reply)` is better.
