### ISSUE TITLE
Dropping attachments in a different order in interactions links them to the wrong option

### ISSUE THREAD

**Issue by Verssesli** [discordjs/discord.js#8650]
### Which package is this bug report for?

discord.js

### Issue description

When interactions have more than one attachment option, dropping in the attachments in a different order than they were declared links them to the wrong interaction option.

With two interaction attachment options att1 and att2 declared in the following order:
`.addAttachmentOption(option => option.setName('att1').setDescription('Attachment 1'))`
`.addAttachmentOption(option => option.setName('att2').setDescription('Attachment 2'))`

Open both in the Discord client, but don't drop anything into them (emulating if someone just copied the slash command)
Then put a file into the 'Attachment 2' field, followed by the 'Attachment 1' field.

![Discord_M9uya6d2iR](https://user-images.githubusercontent.com/20058379/191431415-2ff2e14c-da2c-4bf7-b4c6-c4190d364f12.gif)
![image](https://user-images.githubusercontent.com/20058379/191418459-0050ba3e-ee19-4383-b0e4-0c55ee48a1dd.png)

When you `.getAttachment('att1')` you will get the file you put into 'Attachment 2' and vice versa. 

![image](https://user-images.githubusercontent.com/20058379/191419244-29f2bb85-f7e9-4a0a-917f-a2018524af1a.png)
![image](https://user-images.githubusercontent.com/20058379/191419293-37a2f929-d856-4185-a5ca-985281209035.png)

Putting them in the "correct" order (Attachment 1 then Attachment 2) yields the expected results.

I also realize this may be a discord api or client bug, but I am not knowledgeable enough to be able to tell the difference or submit it on their GitHub (I don't understand the API itself). Any help here will be greatly appreciated.

### Code sample

```typescript
const { SlashCommandBuilder } = require("discord.js")


module.exports = {
	data: new SlashCommandBuilder()
		.setName('attachment-test')
		.setDescription('Tests Attachments')
                .addAttachmentOption(option => option.setName('att1').setDescription('Attachment 1'))
                .addAttachmentOption(option => option.setName('att2').setDescription('Attachment 2')),

	async execute(interaction, client) {

                const att1 = await interaction.options.getAttachment('att1') || 'none'
                const att2 = await interaction.options.getAttachment('att2') || 'none'
                //Having await/async or not does not impact this issue.
          
                console.log("Attachment 1: " + att1.name)
                console.log("Attachment 2: " + att2.name)
                console.log(att1)
                console.log(att2)
                console.log("------------")
          
                interaction.reply("ran attachment test")

	},
};
```

### Package version

discord.js@14.3.0

### Node.js version

v16.13.2

### Operating system

Windows & Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildPresences, GuildMessages, DirectMessages, MessageContent

### I have tested this issue on a development release

discord.js@14.4.0-dev.1663719190-5048a3d.0

**Comment by Jiralite** [comment]
Thank you for the bug report.

I've reproduced the issue and here are my logs:

```xl
{
  type: 1,
  resolved: {
    attachments: {
      '1022082998105030676': {
        url: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082998105030676/PFBagueSansPro-Regular.woff2',
        size: 63908,
        proxy_url: 'https://media.discordapp.net/ephemeral-attachments/1022078447595569192/1022082998105030676/PFBagueSansPro-Regular.woff2',
        id: '1022082998105030676',
        filename: 'PFBagueSansPro-Regular.woff2',
        ephemeral: true
      },
      '1022082997119352892': {
        url: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082997119352892/pokemon_spawn_chances.json',
        size: 199322,
        proxy_url: 'https://media.discordapp.net/ephemeral-attachments/1022078447595569192/1022082997119352892/pokemon_spawn_chances.json',
        id: '1022082997119352892',
        filename: 'pokemon_spawn_chances.json',
        ephemeral: true,
        content_type: 'application/json; charset=utf-8'
      }
    }
  },
  options: [
    { value: '1022082997119352892', type: 11, name: '1' },
    { value: '1022082998105030676', type: 11, name: '2' },
    [length]: 2
  ],
  name: 'test',
  id: '1022078447595569192',
  guild_id: '886323824801488996'
}
Attachment 1: pokemon_spawn_chances.json
Attachment 2: PFBagueSansPro-Regular.woff2
Attachment {
  attachment: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082997119352892/pokemon_spawn_chances.json',
  name: 'pokemon_spawn_chances.json',
  id: '1022082997119352892',
  size: 199322,
  url: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082997119352892/pokemon_spawn_chances.json',
  proxyURL: 'https://media.discordapp.net/ephemeral-attachments/1022078447595569192/1022082997119352892/pokemon_spawn_chances.json',
  height: null,
  width: null,
  contentType: 'application/json; charset=utf-8',
  description: null,
  ephemeral: true
}
Attachment {
  attachment: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082998105030676/PFBagueSansPro-Regular.woff2',
  name: 'PFBagueSansPro-Regular.woff2',
  id: '1022082998105030676',
  size: 63908,
  url: 'https://cdn.discordapp.com/ephemeral-attachments/1022078447595569192/1022082998105030676/PFBagueSansPro-Regular.woff2',
  proxyURL: 'https://media.discordapp.net/ephemeral-attachments/1022078447595569192/1022082998105030676/PFBagueSansPro-Regular.woff2',
  height: null,
  width: null,
  contentType: null,
  description: null,
  ephemeral: true
}
------------
```

The extra first payload is the raw data received from Discord - the source of truth!

I have dragged into the second attachment option pokemon_spawn_chances.json and dragged into the first option PFBagueSansPro-Regular.woff2. Comparing the ids with the raw data received from Discord reveals that discord.js is not at fault. Take a look here:

```xl
options: [
  { value: '1022082997119352892', type: 11, name: '1' },
  { value: '1022082998105030676', type: 11, name: '2' },
  [length]: 2
]
  ```

The ids here are sent in the wrong order. My option name "2" possessed pokemon_spawn_chances.json, but this is moved to option 1 because as you suspected, it was filled out first.

Please open an issue over at [discord-api-docs](https://github.com/discord/discord-api-docs) about this.
