### ISSUE TITLE
`RepliableInteraction` type doesn't respect Cached generic

### ISSUE THREAD

**Issue by MaksiRose** [discordjs/discord.js#8652]
### Which package is this bug report for?

discord.js

### Issue description

this image says it all: interaction.guildId can't be null here. 

![image](https://user-images.githubusercontent.com/96802571/191512076-9c103b80-c683-4005-b389-027ccc3cd1d5.png)

The fix is simple,
`export type RepliableInteraction<Cached extends CacheType = CacheType> = Exclude<Interaction, AutocompleteInteraction>;`
must be changed to
`export type RepliableInteraction<Cached extends CacheType = CacheType> = Exclude<Interaction<Cached>, AutocompleteInteraction<Cached>>;`
in index.d.ts

### Package version

v14.4.0

### Node.js version

v17.5.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
> this image says it all

This may just be me, but it does not help. I don't see where `interaction` is previously defined and the method being called is not present?

Regardless, feel free to open a pull request.

**Comment by MaksiRose** [comment]
@Jiralite
```ts
client.on('interactionCreate', async interaction => {
  if (interaction.isRepliable() && interaction.inCachedGuild()) {
    const guildId = interaction.guildId
    /* This is of type string because ts treats interaction as type  
    ChatInputCommandInteraction<"cached"> | MessageContextMenuCommandInteraction<"cached"> |
    UserContextMenuCommandInteraction<"cached"> | SelectMenuInteraction<"cached"> |
    ButtonInteraction<"cached"> | ModalSubmitInteraction<"cached">  */

    await startResting(interaction)
  }
})
```

async function startResting(
  interaction: RepliableInteraction<'cached'> // This should be the same as the 6 Interaction Types mentioned above
) {
  const guildId = interaction.guildId // This type string | null. It does not get treated the same despite being the same. Means you have to type out all six types instead of combining it to RepliableInteraction
}
