### ISSUE TITLE
filter method doesn't guard correctly

### ISSUE THREAD

**Issue by MaksiRose** [discordjs/discord.js#8653]
### Which package is this bug report for?

collection

### Issue description

Let's say for example my Collection is of type `Collection<string, NonThreadGuildBasedChannel | null>`, and then i filter that collection with channel !== null, then the filter should return  `Collection<string, NonThreadGuildBasedChannel>`. It does not do that however.

### Code sample

```typescript
let updatesMenuOptions: RestOrArray<SelectMenuComponentOptionData> = (await interaction.guild.channels.fetch()).filter(c => c !== null && c.type === ChannelType.GuildText).map(channel => ({ label: channel.name, value: `serversettings_updates_${channel.id}` }));
```

### Package version

v14.4.0

### Node.js version

v17.5.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by didinele** [comment]
This isn't something that we can automatically infer, unfortunately.

Here's a way to accomplish this:
```ts
const coll = new Collection<string, number | string>;
coll.filter((e): e is number => typeof e === 'number');
```

**Comment by MaksiRose** [comment]
@didinele that's weird, I feel like this works perfectly with map filters and array filters. why not with collections?
