### ISSUE TITLE
ForumChannel is missing some methods and properties

### ISSUE THREAD

**Issue by Markus-Rost** [discordjs/discord.js#8654]
### Which package is this bug report for?

discord.js

### Issue description

The new [ForumChannel](https://discord.js.org/#/docs/discord.js/14.4.0/class/ForumChannel) added in 14.4.0 still seems to be missing some methods that other channels have and are possible on forum channels as well. This includes, but is probably not limited to:

* `.createInvite()`
* `.createWebhook()`
* `.fetchInvites()`
* `.fetchWebhooks()`
* `.setDefaultAutoArchiveDuration()`
* `.setNSFW()`
* `.setTopic()`
* `.defaultAutoArchiveDuration`
* `.nsfw`
* `.topic`

### Package version

v14.4.0

### Node.js version

v18.1.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions, MessageContent

**Comment by jaw0r3k** [comment]
Yeah these are the methods from TextBasedChannel
which it is not extending
