### ISSUE TITLE
types: SlashcommandBuilder#addChannelTypes

### ISSUE THREAD

**Issue by Gorniaky** [discordjs/discord.js#8657]
### Which package is this bug report for?

builders

### Issue description

[{
	"resource": "/e:/_RaccoonsCode/Konan/test.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'ChannelType.GuildVoice' is not assignable to parameter of type 'ChannelType.GuildText | ChannelType.GuildVoice | ChannelType.GuildCategory | ChannelType.GuildNews | ChannelType.GuildNewsThread | ChannelType.GuildPublicThread | ChannelType.GuildPrivateThread | ChannelType.GuildStageVoice'.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 22,
	"endLineNumber": 8,
	"endColumn": 44
}]

### Code sample

```typescript
import { ChannelType, SlashCommandBuilder } from 'discord.js';

const data = new SlashCommandBuilder()
  .setName('test')
  .setDescription('test')
  .addChannelOption(option => option.setName('channel')
    .setDescription('test channel')
    .addChannelTypes(ChannelType.GuildVoice));
```

### Package version

14.4.0

### Node.js version

18.9.0

### Operating system

Windows 10 IoT Enterprise LTSC 21H2

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by jaw0r3k** [comment]
I cant reproduce

**Comment by Jiralite** [comment]
This suspiciously looks like you have conflicting versions. Can you check?

**Comment by jaw0r3k** [comment]
probably 
can u chack your api-types version?

**Comment by Gorniaky** [comment]
The only dependency in my package is `discord.js@14.4.0`, but the lock file has `discord-api-types@0.36.3`, the problem was resolved by deleting the lock file and reinstalling the dependencies.
