### ISSUE TITLE
awaitMessages does not return content

### ISSUE THREAD

**Issue by KokeroO** [discordjs/discord.js#8673]
### Which package is this bug report for?

discord.js

### Issue description

In v14+API 9 or 10 it is not returning value in content in awaitMessages.
With v13 + API 9 version it is working normally.

### Code sample

```typescript
const filter = response => {
    return response.author.id === retWhiteList[0].user_id
};
interaction.channel.awaitMessages({
    filter: filter,
    max: 1,
    time: 60000,
    errors: ['time']
}).then(collected => {
    console.log(collected.first().content)
})
```

### Package version

14.4.0

### Node.js version

v16.14.0

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by Jiralite** [comment]
You are missing the `MESSAGE_CONTENT` intent. This is not a bug.
