### ISSUE TITLE
Fail to parse webhook url

### ISSUE THREAD

**Issue by Gorniaky** [discordjs/discord.js#8675]
### Which package is this bug report for?

discord.js

### Issue description

Webhook url too can have discordapp.com

https://github.com/discordjs/discord.js/blob/0126d9b810a156c4bf1b8b93f2121f3319855bac/packages/discord.js/src/util/Util.js#L529

Solution:
```js
/https?:\/\/(?:ptb\.|canary\.)?discord(?:app)?\.com\/api(?:\/v\d{1,2})?\/webhooks\/(\d{17,19})\/([\w-]{68})/i
```

### Package version

14.4.0

### Node.js version

18.9.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by almeidx** [comment]
Duplicate of #7189

**Comment by Gorniaky** [comment]
Sorry
