### ISSUE TITLE
ERR_UNKNOWN_BUILTIN_MODULE No such built-in module: node:timers/promises

### ISSUE THREAD

**Issue by IscoV** [discordjs/discord.js#8684]
### Which package is this bug report for?

discord.js

### Issue description

Well, as every week they release a new update, which makes the developer desperate because he has to implement changes day after day...

Until two days ago, my project implemented with Discord.js worked perfectly. As I don't understand why instead of fixing everything at once, they are dosing it day by day, I don't know why it shows me this error...

As I have said, my project was working correctly until I updated the library...

Attached image

![imagen](https://user-images.githubusercontent.com/53531688/192552512-ab7c4d3e-11c0-4a65-b336-73a8a4e12ab0.png)

### Code sample

```typescript
Just by establishing the necessary credentials and trying to login, the error is displayed...
```

### Package version

14.4.0

### Node.js version

v14.20.1

### Operating system

Ubuntu 18.04.6 LTS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

3c231ae.0

**Comment by IscoV** [comment]
And version 13 is allowed for NodeV14? Because until yesterday it was working correctly

**Comment by almeidx** [comment]
Version 13 of discord.js requires node.js 16.6.0 or newer
