### ISSUE TITLE
messageCreate does not trigger by reciving a DM

### ISSUE THREAD

**Issue by orenong** [discordjs/discord.js#8695]
### Which package is this bug report for?

discord.js

### Issue description

I set up a bot with the following simple code, using NodeJS. 

the "messageCreate" event will not trigger when a user sends a direct messege to the bot.

### Code sample

```typescript
const Discord = require('discord.js');
const { Client, GatewayIntentBits, ChannelType,Partials } = require('discord.js');


const bot = new Discord.Client({
    intents: [Discord.GatewayIntentBits.Guilds, Discord.GatewayIntentBits.GuildMessages, Discord.GatewayIntentBits.GuildMessageReactions, Discord.GatewayIntentBits.MessageContent, Discord.GatewayIntentBits.DirectMessages, Discord.GatewayIntentBits.DirectMessageTyping, GatewayIntentBits.GuildMessages ],
    Partials: [Partials.Message, Partials.Channel, Partials.Reaction]
});

bot.login(TOKEN);



bot.on("messageCreate", (msg) => {
    if (msg.author.id == BOT_ID){
        return;
    }
    if (msg.channel.type = ChannelType.DM ){

        let testTXT = "I got a DM from ";
        testTXT += msg.author.username;
        testTXT+= " saying "+msg.content
    }

    botsChannel.send("yes "+ msg.content);
    console.log("Tried to send test answer");
});
```

### Package version

latest

### Node.js version

v16.14.2

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

### I have tested this issue on a development release

no

**Comment by Jiralite** [comment]
> ```ts
> const bot = new Discord.Client({
>     intents: [Discord.GatewayIntentBits.Guilds, Discord.GatewayIntentBits.GuildMessages, Discord.GatewayIntentBits.GuildMessageReactions, Discord.GatewayIntentBits.MessageContent, Discord.GatewayIntentBits.DirectMessages, Discord.GatewayIntentBits.DirectMessageTyping, GatewayIntentBits.GuildMessages ],
>     Partials: [Partials.Message, Partials.Channel, Partials.Reaction]
> });
> ```

`Partials` does not exist. It's `partials`.
