### ISSUE TITLE
Programmatically set selected values in the Select Menu component

### ISSUE THREAD

**Issue by k-h-f** [discordjs/discord.js#8698]
### Which package is the feature request for?

discord.js

### Feature

A good addition would be to add the ability to pre-select values in the Select Menu component... I tried searching in the documentation/online and can't seem to find this feature.
So when the select menu is generated, the values would be preselected
![image](https://user-images.githubusercontent.com/47926269/193663845-3d363b78-5ecf-4205-b7e8-c5eac2c96e6a.png)

### Ideal solution or implementation

 Ideally it would be great to set it when creating the options, so something line this

```
const row = new ActionRowBuilder().addComponents(
  new SelectMenuBuilder()
    .setCustomId("select")
    .setPlaceholder("Nothing selected")
    .setMinValues(2)
    .setMaxValues(3)
    .addOptions([
      {
        label: "Select me",
        description: "This is a description",
        value: "first_option",
        selected: true,                             //new optional property suggestion
      },
      {
        label: "You can select me too",
        description: "This is also a description",
        value: "second_option",
        selected: true,                             //new optional property suggestion
      },
      {
        label: "I am also an option",
        description: "This is a description as well",
        value: "third_option",
      },
    ])
);

```

Would require a change in the contract for the Select Menu

**Comment by Jiralite** [comment]
This already exists.
https://discord-api-types.dev/api/discord-api-types-v10/interface/APISelectMenuOption#default

**Comment by k-h-f** [comment]
Thank you, I must have gotten confused with the naming. I assumed `default` meant as a placeholder rather than setting the value as selected. Sorry for making this issue
