### ISSUE TITLE
Vague description for UserContextMenuCommandInteraction properties description in Docs

### ISSUE THREAD

**Issue by vunsh** [discordjs/discord.js#8713]
### Which package is the feature request for?

discord.js

### Feature

Looking at the v14 documentation for [UserContextMenuCommandInteraction](https://discord.js.org/#/docs/discord.js/14.5.0/class/UserContextMenuCommandInteraction?scrollTo=targetUser), some of the properties have contradicting descriptions. With testing its clear what each property contains, but the documentation should be clear and concise on what the property actually is.

UserContextMenu#targetId currently has an [ideal description](https://discord.js.org/#/docs/discord.js/14.5.0/class/UserContextMenuCommandInteraction?scrollTo=targetId)

UserContextMenu#targetUser currently has a [vague description](https://discord.js.org/#/docs/discord.js/14.5.0/class/UserContextMenuCommandInteraction?scrollTo=targetUser) that makes it sound like it contains the user object of the person who originated the interaction.

UserContextMenu#targetMember has this [same format](https://discord.js.org/#/docs/discord.js/14.5.0/class/UserContextMenuCommandInteraction?scrollTo=targetMember).

### Ideal solution or implementation

The ideal solution would be to update the description for these properties

Ex.
UserContextMenu#targetUser
The user of the target for this interaction.

UserContextMenu#targetMember
The member of the target for this interaction.

### Other context

This has the same wording for the v13 [equivalent](https://discord.js.org/#/docs/discord.js/v13/class/UserContextMenuInteraction) of a UserContextMenu. If this gets considered, updating the v13 docs would be a good idea as well.

**Comment by Jiralite** [comment]
Looking at this too, I believe they _should_ change. I'd rather treat this as a bug than a feature request. If you look at `UserContextMenuCommandInteraction#user`, it's actually the same wording as `UserContextMenuCommandInteraction#targetUser`!
