### ISSUE TITLE
Error loading @discordjs/ws package on latest dev version

### ISSUE THREAD

**Issue by SammyWhamy** [discordjs/discord.js#8719]
### Which package is this bug report for?

ws

### Issue description

1. install `@discordjs/ws@0.3.1-dev.1665144455-9f68d73.0`
2. Import the package
3. Observe crash

### Code sample

```typescript
const ws = require("@discordjs/ws") // ESM Import has the same issue
```

### Package version

0.3.1-dev.1665144455-9f68d73.0

### Node.js version

16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

9f68d73

**Comment by Jiralite** [comment]
What's the crash?

**Comment by SammyWhamy** [comment]
Issue seems to originate from f79ccb4
Crash is:
```
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:\project\node_modules\@discordjs\package.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at file:///C:/project/node_modules/@discordjs/ws/dist/index.mjs:283:19
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\project\\node_modules\\@discordjs\\package.json'
}
```
