### ISSUE TITLE
IP Discovery failed

### ISSUE THREAD

**Issue by kyky775v2** [discordjs/discord.js#8728]
### Which package is this bug report for?

voice

### Issue description

hello. I upgraded the Discord module from v13 to v14.
And after installing the Voice module,
I ran the code to play the m4a file,
but after a few seconds after being connected
The connection is disconnected with the following error:
`Error: Cannot perform IP discovery - socket closed    at Socket.<anonymous> (/root/dbv13/node_modules/@discordjs/voice/dist/index.js:335:46)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at socketCloseNT (node:dgram:746:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on VoiceConnection instance at:
    at VoiceConnection.onNetworkingError (/root/dbv13/node_modules/@discordjs/voice/dist/index.js:1452:10)
    at Networking.emit (node:events:527:28)
    at /root/dbv13/node_modules/@discordjs/voice/dist/index.js:604:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

FYI, I'm using a VPS hosting service and have a firewall turned on.

### Code sample

```typescript
if(message.content == "v"){
var vch = message.member.voice.channel;
		
var vocon = dv.joinVoiceChannel({
channelId: vch.id,
guildId: message.guild.id,
adapterCreator: message.guild.voiceAdapterCreator
});

var ap = dv.createAudioPlayer();

const resource = dv.createAudioResource('./test.m4a');

ap.play(resource);

const ssp = vocon.subscribe(ap);
}
```

### Package version

latest (14.5.0)

### Node.js version

lts (16.15.0)

### Operating system

Ubuntu 20.04 LTS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildInvites, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
Is it this again?

https://github.com/discordjs/discord.js/issues/7708#issuecomment-1146874197

**Comment by kyky775v2** [comment]
sorry. It was a simple firewall error.
Discord voice chat uses udp ports between 45000 and 60000. But I was blocking this port.
Currently everything works fine. thank you
