### ISSUE TITLE
Voice package doesn't find libraries when using ES Modules

### ISSUE THREAD

**Issue by StarkRights** [discordjs/discord.js#8740]
### Which package is this bug report for?

voice

### Issue description

My issue is more/less identical to issue https://github.com/discordjs/voice/issues/227 from the old voice package.

It appears the fix applied to `tsup.config.js` in PR https://github.com/discordjs/voice/pull/229/  was lost in the transition to the monorepo. In modern versions, [discord.js/packages/voice/tsup.config.js](https://github.com/discordjs/discord.js/blob/main/packages/voice/tsup.config.js) just imports from the top level [discord.js/tsup.config.js](https://github.com/discordjs/discord.js/blob/main/tsup.config.js)- which does not have the fix,
```
banner: { js: 'import path from "path";\nimport { createRequire as topLevelCreateRequire } from "module";\nconst require = topLevelCreateRequire(path.resolve(import.meta.url));\n', },
```
included.

Issue persists on both `@discordjs/voice` and `@discordjs/voice@dev` builds. 

My original exploration into this can be found in [this forum thread](https://discord.com/channels/222078108977594368/1029242155274883092) in the discord if it's of any use- though I think I've included all necessary detail here. 

### Code sample

```typescript
/**
 * Dir Structure:
 * .
 * ├── node_modules/
 * ├── src/
 * │   ├── index_bad.js
   │   └── index_good.js
 * └── package.json
 */

/* ./package.json */
{
  "name": "bot",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "src/index_bad.js",
  "scripts": {
    "startgood": "node src/index_good.js ",
    "startbad": "node src/index_bad.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@discordjs/builders": "^0.13.0",
    "@discordjs/opus": "^0.8.0",
    "@discordjs/rest": "^0.4.1",
    "@discordjs/voice": "^0.13.0",
    "discord-api-types": "^0.32.0",
    "discord.js": "^14.6.0",
    "ffmpeg-static": "^5.1.0",
    "libsodium-wrappers": "^0.7.10",
    "prism-media": "^1.3.4"
  }
}

/* src/index_bad.js */
import { generateDependencyReport } from '@discordjs/voice'
console.log(generateDependencyReport())

/* src/index_good.js */
import {createRequire} from 'module';
const {generateDependencyReport} = createRequire(import.meta.url)('@discordjs/voice');
console.log(generateDependencyReport()); //fix from old package, in comments of issue #227


/*******************
 *     Outputs     *
 *******************/
//after npm install, running the following scripts yields

/* npm run startbad */
PS C:\Code\Repositories\ISSUETESTREPO> npm run startbad

> bot@1.0.0 startbad
> node src/index_bad.js

--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.13.0
- prism-media: not found

Opus Libraries
- @discordjs/opus: not found
- opusscript: not found

Encryption Libraries
- sodium-native: not found
- sodium: not found
- libsodium-wrappers: not found
- tweetnacl: not found

FFmpeg
- version: 5.0.1-essentials_build-www.gyan.dev
- libopus: yes
--------------------------------------------------


/* npm run startgood */
PS C:\Code\Repositories\ISSUETESTREPO> npm run startgood

> bot@1.0.0 startgood
> node src/index_good.js

--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.13.0
- prism-media: 1.3.4

Opus Libraries
- @discordjs/opus: 0.8.0
- opusscript: not found

Encryption Libraries
- sodium-native: not found
- sodium: not found
- libsodium-wrappers: 0.7.10
- tweetnacl: not found

FFmpeg
- version: 5.0.1-essentials_build-www.gyan.dev
- libopus: yes
--------------------------------------------------
```

### Package version

-- @discordjs/voice@0.13.0

### Node.js version

v18.0.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

f92be4f

**Comment by Qjuh** [comment]
Seems like the fix for this (calling scripts/postbuild.mjs in build script) got missed when merging #8324

**Comment by StarkRights** [comment]
Yeppers. Forked the repo and stuck it back where it was per an older commit. PR shortly.
