### ISSUE TITLE
Message delete reason not supported on <Message>.delete and <MessageManager>.delete

### ISSUE THREAD

**Issue by net-tech** [discordjs/discord.js#8746]
### Which package is this bug report for?

discord.js

### Issue description

Both `<Message>.delete` and `<MessageManager>.delete` do not support the `reason` option, which Discord API docs say can be added:
> This endpoint supports the `X-Audit-Log-Reason` header.
> *https://discord.com/developers/docs/resources/channel#delete-message*

The djs docs also don't mention a reason: 
- [Message.delete](https://discord.js.org/#/docs/discord.js/main/class/Message?scrollTo=delete)
 - [MessageManager.delete](https://discord.js.org/#/docs/discord.js/main/class/MessageManager?scrollTo=delete)

### Package version

v14.6.0

### Node.js version

v16.10.0

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by Jiralite** [comment]
It is in fact the other way around since messages deleted by bots do not generate audit log entries.
