### ISSUE TITLE
Add new component types for User, Role, Mentionable, and Channel Select

### ISSUE THREAD

**Issue by TrevorSayre** [discordjs/discord.js#8753]
### Which package is the feature request for?

discord.js

### Feature

Currently discord.js only supports Component Types 1 through 4: Action Row, Button, String Select, and Text Input. Discord added 4 more types, 5 through 8: User Select, Role Select, Mentionable Select, and Channel Select. They function nearly identically to String Select (Component Type 3), except they don't take options and they return not only a value but also a resolved object.

https://discord.com/developers/docs/interactions/message-components#component-object-component-types

https://discord.com/developers/docs/interactions/message-components#select-menu-types

### Ideal solution or implementation

Add the 4 new select menu types.

**Comment by TrevorSayre** [comment]
I should add, I don't use builders, so I'm primarily looking for TypeScript types support and interaction payload support.

**Comment by Jiralite** [comment]
That's all builders. discord.js just uses them.

**Comment by TrevorSayre** [comment]
Great, thank you for the clarification!

**Comment by RedGuy12** [comment]
@jaw0r3k and I are currently working on this.

**Comment by gamer0mega** [comment]
There is a workaround for now, you can use the `SelectMenuBuilder` and pass `{type: 5}` to its constructor, which should create a select menu for picking users, you can set other types to get different select menus. Passing a raw component will not work as the library does not recognize the component type yet.

**Comment by itsgox** [comment]
@gamer0mega I'm doing that aswell, but the "interactionCreate" event doesn't get triggered when I interact with the select menu 🤔

**Comment by SuperchupuDev** [comment]
@itsgox discord.js ignores unknown interaction types on the interactionCreate event, if you really want to respond to new component types before they're officially supported you should listen to the raw `client.ws.on('INTERACTION_CREATE', ...)` event

**Comment by itsgox** [comment]
@SuperchupuDev Thank you so much!!

**Comment by TrevorSayre** [comment]
> There is a workaround for now, you can use the `SelectMenuBuilder` and pass `{type: 5}` to its constructor, which should create a select menu for picking users, you can set other types to get different select menus. Passing a raw component will not work as the library does not recognize the component type yet.

Side note, this workaround will not work for a Channel Select component when you want to include the `channel_types` optional field.
