### ISSUE TITLE
Embed Images sometimes won't load

### ISSUE THREAD

**Issue by Be-njamin** [discordjs/discord.js#8758]
### Which package is this bug report for?

discord.js

### Issue description

I have a command that searches a json file for a string and adds that string as an image to the embed message that is returned. The image url ist set via `embedMessage.setImage(imageUrl);` (`const embedMessage = new EmbedBuilder();`). 

Sometimes when using the command the image is attached properly, but in some cases the image won't show up on the embed message. See the screenshot attached for more information:

![bot_images](https://user-images.githubusercontent.com/17416060/196032607-9aa7768a-d5b1-4698-9a80-6e7b64212d49.png)

Steps to reproduce
- Implement a command that embeds an image
- Use that command a few times

### Code sample

```typescript
const embedMessage = createEmbedMessage({
      title: `Survey | *${bestMatch.name}:*`,
      imageUrl: bestMatch.imageUrl,
      fields: bestMatch.dlc && [{ name: '**DLC:**', value: bestMatch.dlc }]
});

await interaction.reply({ embeds: [embedMessage] });
```

### Package version

14.2.0

### Node.js version

16.19.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by Jiralite** [comment]
If images are failing to load in the embed, the issue lies with Discord or perhaps wherever the image comes from does not have anything to unfurl. This cannot be a discord.js issue.
