### ISSUE TITLE
Means of distinguishing different `ContextMenuCommandBuilder` types

### ISSUE THREAD

**Issue by GrantGryczan** [discordjs/discord.js#8765]
### Which package is the feature request for?

builders

### Feature

I'm trying to develop a TypeScript library that adds more abstractions around common Discord.js patterns and boilerplates, but I've run into a problem when trying to do this for context menu commands, because TypeScript has access to no information about what type of context menu a `ContextMenuCommandBuilder` represents. This is despite that it has a `setType` method, which I believe should narrow the type to provide that information. I need my types to be able to know whether the resulting interaction will be a `UserContextMenuInteraction` or a `MessageContextMenuInteraction` based on what type of `ContextMenuCommandBuilder` it is. Without any such type information on `ContextMenuCommandBuilder`s, this is impossible.

### Ideal solution or implementation

I suggest that the `ContextMenuCommandBuilder`'s `setType` method return a narrower builder type to specify which `type` the builder is. I don't care how it's done, as long as it is convenient to distinguish using TypeScript.

One example could be that `.setType(type: T)` returns `ContextMenuCommandBuilder & {type: T}`, where `T extends ContextMenuCommandType`. Another could be that it returns a `ContextMenuCommandBuilder<T>`, and `T` would be used as the value of the `type` property to begin with, extending and defaulting to `ContextMenuCommandType`.

**Comment by CitTheDev** [comment]
I will open a pull request for this when I get home (+3 hours)

**Comment by didinele** [comment]
Resolved with #10448 (merged soon)
