### ISSUE TITLE
Invalid String Format on Builder's .setName()

### ISSUE THREAD

**Issue by Neodevils** [discordjs/discord.js#8781]
### Which package is this bug report for?

discord.js

### Issue description

1. Used "—" on context user menu builder.
2. Special chars occurs `ExpectedConstraintError: Invalid string format` error. 

### Code sample

```typescript
import { ContextMenuCommandBuilder, ApplicationCommandType } from "discord.js";

export default {
    data: new ContextMenuCommandBuilder().setName("— User Avatar").setType(ApplicationCommandType.User),
    run: async (client, interaction) => {
        const target = interaction.guild.members.cache.get(interaction.targetId);

        await interaction.reply({
            content: `>>> ${target.user.avatarURL({ dynamic: true, extension: "jpg", size: 4096 })}`,
            ephemeral: true,
        });
    },
};
```

### Package version

discord.js@14.6.0

### Node.js version

v18.8.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
Copied and pasted without builders and the command is successfully created.

**Comment by Neodevils** [comment]
> Copied and pasted without builders and the command is successfully created.

The problem is with builders. It's occuring error on builders.

**Comment by Jiralite** [comment]
Yes, I'm just stating that this is a bug.
