### ISSUE TITLE
Bug: guild.name and other attributes are `undefined` in every server I try.

### ISSUE THREAD

**Issue by CodeSpent** [discordjs/discord.js#8787]
### Which package is this bug report for?

discord.js

### Issue description

- Create a basic discord.js snippet.
- Invite bot to a server/guild.
- Access the `guild` key on the `client` object.
- Observe various fields being `undefined`.

I have looked across 4 different servers on 2 different OSes using the same version of discord.js and the result remains the same.

```json
 Guild {
  id: '0000000000000000000',
  name: undefined,
  icon: undefined,
  features: undefined,
  ...
  available: false
  ...
```

I've read other issues describing a change that had a resolution, but I believe this to have regressed. The initial server I used for testing is over 4 years old & as well I tried on a brand new server.

Please let me know what information would be useful to add.

### Code sample

```typescript
import { Client} from "discord.js";

const token = process.env.BOT_TOKEN;

const client = new Client({
  intents: []
});

console.log(client.guilds)

client.login(token)
```

### Package version

14.6.0

### Node.js version

16.13.1

### Operating system

Mac OS 12.6

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
Your client is not ready. This is not a bug. In addition, this is not correct usage of discord.js in the first place.

**Comment by CodeSpent** [comment]
So that's a mistake in the reproduction 'cause admittedly, I'm not great at taking the whole implementation & shoving it into a single snippet.

Below would produce exactly the same result in my guilds.

Take this example;
```javascript
export default (client: Client): void => {
  client.on("ready", async () => {
    if (!client.user || !client.application) {
      return;
    }
    console.info("Registering slash commands.")

    await client.application.commands.set(Commands)

    console.info(`${client.user.username} is ready and listening!`)
    console.log(client.guilds)
  })
}
```

**Comment by Jiralite** [comment]
You have also stated that you are not using intents. That would also cause that behaviour.
