### ISSUE TITLE
deferReply() throws 404 Unknown Interaction 

### ISSUE THREAD

**Issue by KONSTANTINOSKOUKOS** [discordjs/discord.js#8789]
### Which package is this bug report for?

discord.js

### Issue description

I have a test bot made in the dev portal by following these steps:
1. Make a new application with asimple name and description
2.  Added a bot and checked all 3 of the Priviledged Gateway Intents
3. Generated a URL with bot and application.commands scopes and checked Administrator permissions
4. Used the link and added the bot into a test server

After I try to use any slash command i.e /joke (one of the commands registered in my production bot) 99% of the time there is this error(in the other 1% it weirdly works perfectly):

![image](https://user-images.githubusercontent.com/85506368/198297599-0c2fffc1-04b1-419c-8cf1-cfb3e6c61acf.png)

I have tried multiple approaches but none seems to completely fix the issue. Any help would be greatly appreciated.

PS This is my first issue of this nature, so if I have omitted anything please let me know.

### Code sample

```typescript
const { Client, GatewayIntentBits, Events } = require('discord.js');

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });

client.once(Events.ClientReady, c => {
    console.log('ready');
});

client.on(Events.InteractionCreate, async interaction => {
    if (!interaction.isChatInputCommand()) return;

    await interaction.deferReply();
    await interaction.editReply('hi');
});

client.login('the bot's token');
```

### Package version

discord.js@14.6.0

### Node.js version

v16.15.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by Qjuh** [comment]
This looks like your internet connection is so slow that you take more than 3 seconds to reach (and send to the API) the deferReply call in 99% of the cases.

**Comment by JMTK** [comment]
Possibly related https://github.com/discord/discord-api-docs/issues/5558

**Comment by Jiralite** [comment]
Going to close in favour of https://github.com/discord/discord-api-docs/issues/5558.

**Comment by KONSTANTINOSKOUKOS** [comment]
Finally I fixed it! For anyone encountering the same problem the issue was related to my wifi connection as @Qjuh proposed so I tested it on repl.it and it worked perfectly
