### ISSUE TITLE
¿ Release @discordjs/voice@0.13.1 for ES6 Modules ?

### ISSUE THREAD

**Issue by DjesonPV** [discordjs/discord.js#8797]
### Which package is this bug report for?

voice

### Issue description

Can't use the library with ES6 Modules with version 0.13.0 has described by #8740 and fixed by #8741.

Yet there is no release since the implement of the bugfix,

### Package version

0.13.0

### Node.js version

v18.6.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by InfiniteMarcus** [comment]
This bug is really annoying. I had to downgrade to 0.11 awaiting for the fix

**Comment by MoustacheOff** [comment]
> This bug is really annoying. I had to downgrade to 0.11 awaiting for the fix

Yes, same. Can it be fixed anytime soon?

**Comment by mare135** [comment]
Same. On Ubuntu in wsl2

**Comment by Jiralite** [comment]
It's been released! The change log can be viewed [here](https://github.com/discordjs/discord.js/releases/tag/%40discordjs%2Fvoice%400.14.0).
