### ISSUE TITLE
Cannot import discord.js

### ISSUE THREAD

**Issue by Raiden-Ei** [discordjs/discord.js#8806]
### Which package is this bug report for?

discord.js

### Issue description

1. Install latest dev version of discord.js
2. Try to import it

### Code sample

```typescript
const Discord = require('discord.js');

/* Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/ubuntu/discord-bot/node_modules/discord.js/src/structures/ChannelSelectMenuBuilder.js:10:40) */
```

### Package version

discord.js@14.6.1-dev.1667434318-68c9cb3.0

### Node.js version

18.12.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

68c9cb3

**Comment by Jiralite** [comment]
For now, override builders to use the `@dev` version too.

**Comment by kyranet** [comment]
See [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) for npm or [`resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) for yarn. Alternatively, you can wait for next release.
