### ISSUE TITLE
Deprocated SelectMenuInteraction still being used for await Message Component

### ISSUE THREAD

**Issue by bytechase** [discordjs/discord.js#8809]
### Which package is this bug report for?

discord.js

### Issue description

Steps to Reproduce:
1. Create and Send Select Menu
2. After sending, create interaction.channel.awaitMessageComponent
3. After Interaction received, the returned object is SelectMenuInteraction Object

![Screenshot 2022-11-03 at 11 08 17 AM](https://user-images.githubusercontent.com/47930318/199758600-805e849c-e598-4b65-a44a-879e2fce008e.png)

![Screenshot 2022-11-03 at 11 08 44 AM](https://user-images.githubusercontent.com/47930318/199758699-668447db-c33e-4211-9adf-068e60bff1c2.png)

### Package version

14.6

### Node.js version

18.4

### Operating system

MacOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by bytechase** [comment]
> 

14.6

**Comment by Jiralite** [comment]
This is not even implemented on 14.6.
