### ISSUE TITLE
TypeScript errors with MappedInteractionTypes

### ISSUE THREAD

**Issue by geisterfurz007** [discordjs/discord.js#8816]
### Which package is this bug report for?

discord.js

### Issue description

Note: This is *not* a duplicate of #7924, `strictNullChecks` are enabled!

1. Create a new project using `yarn init -y`
2. Install discord.js using `yarn add discord.js`
3. Install typescript and node-types using `yarn add -D typescript @types/node`
4. Create `tsconfig.json` and `index.ts` from the codesample
5. Run `yarn tsc --noEmit`
6. Observe errors in discord.js/typings/index.d.ts

A workaround for this is using `skipLibCheck` but I'd rather not have to do that since I believe that including the libraries in typechecking is valuable to spot missing external dependencies (like polyfills for DOM API or WebSocket, etc).

---

One more note regarding the dev build (`yarn add discord.js@dev`, version number down below): That one does *not* show the errors mentioned above but a handful other ones regarding the new Builders.

### Code sample

```typescript
`tsconfig.json`

{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    /* Type Checking */
    "strict": true,
    "strictNullChecks": true,
    "skipLibCheck": false
  }
}
```

`index.ts`
```ts
import { Client } from "discord.js";

const client = new Client({ intents: [] });
client.login();
```

### Package version

discord.js@14.6.0

### Node.js version

Node: 16.13.1, TypeScript 4.8.4

### Operating system

Windows 10; 64-bit

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

ff85481

**Comment by imranbarbhuiya** [comment]
not sure if `strict` auto enables `strictNullChecks` but your `tsconfig` don't have `strictNullChecks`

**Comment by geisterfurz007** [comment]
`strict: true` enables all strict checks. Just to make sure, I added it explicitly and the result is the same. I updated the issue to avoid the confusion.

**Comment by Jiralite** [comment]
> One more note regarding the dev build (`yarn add discord.js@dev`, version number down below): That one does _not_ show the errors mentioned above but a handful other ones regarding the new Builders.

That's because this issue is already resolved.

**Comment by geisterfurz007** [comment]
Any estimates when a new version without library internal typeerrors is going to be released?

**Comment by mrjackyliang** [comment]
I'm actually having the same issue, and setting `skipLibCheck` to `true` isn't going to do for me in the long run.

But... I don't have a choice right now, so that will do. At the moment, all my types are just going to be linted and not checked by TypeScript.

**Comment by DevPrice** [comment]
Having the same issue with `strictNullChecks` enabled.

**Comment by Jiralite** [comment]
> Any estimates when a new version without library internal typeerrors is going to be released?

No ETA sadly.

> I'm actually having the same issue, and setting `skipLibCheck` to `true` isn't going to do for me in the long run.
> 
> But... I don't have a choice right now, so that will do. At the moment, all my types are just going to be linted and not checked by TypeScript.

> Having the same issue with `strictNullChecks` enabled.

`strictNullChecks` won't do anything and one does not need to set `skipLibCheck` to `true`. Simply override discord-api-types to 0.37.14 in your package.json:

```JSON
{
  "overrides": {
    "discord-api-types": "0.37.14"
  }
}
```

**Comment by mrjackyliang** [comment]
I downgraded the package and everything seems to work again! Thanks :)
