### ISSUE TITLE
SequentialHandler.runRequest throws a TimeoutOverflowWarning

### ISSUE THREAD

**Issue by velddev** [discordjs/discord.js#8830]
### Which package is this bug report for?

rest

### Issue description

Discord.JS seems to throw a TimeoutOverflowWarning whenever calling REST.request directly.

Node version: 16.17.0
Version: @discordjs/rest@1.3.0

```
(node:28) TimeoutOverflowWarning: 18446744073709548000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (node:internal/timers:171:15)
    at node:timers/promises:81:21
    at new Promise (<anonymous>)
    at Object.setTimeout (node:timers/promises:80:15)
    at SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:128:26)
    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/app/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22) <-- we call this
    at async sendDirectMessage (/app/src/utils/discordRestExtensions.js:6:21)
    at async ReminderService.pollForReminders (/app/src/services/reminderService.js:50:11)
```

### Package version

@discordjs/rest@1.3.0

### Node.js version

16.17.0

### Operating system

Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by squirrelboye** [comment]
This is a high priority issue IMO. Not sure what is causing it, but when it happens it spams my console with this error, logging the error at a rate of 4 GB per minute and shoots my instance CPU usage up 5x. It continues to spam until the bot is restarted.

This first started last night around 8pm ET. I restarted the bot and it has been fine until about an hour ago, where the issue has started once again.

**Comment by Koyamie** [comment]
Confirming the issue, it gets very noisy at scale because it spams the logs and disk space.
The ram usage and cpu also gets impacted by this.
This should be a high priority issue.

**Comment by Jiralite** [comment]
Adding some context before @ckohen chimes in!

It seems Discord is now using a new rate limit bucket implementation and have migrated some endpoints over to using them. `/channels/{channel.id}/messages` seems to have been recently migrated (for some bots, I believe).

I would guess that the `X-RateLimit-Reset-After` header is somehow, under some conditions, being sent as a large number, which we multiply by 1,000 to convert to milliseconds which goes over the 32-bit signed integer limit, causing a timeout overflow.

Not entirely sure this is discord.js related.

**Comment by Jiralite** [comment]
If you're in [Discord Developers](https://discord.gg/discord-developers), there seems to be a thread dedicated to it now: https://canary.discord.com/channels/613425648685547541/697489244649816084/1040066022172004432

**Comment by Jiralite** [comment]
Turns out this is indeed a Discord issue. I'll be closing this as there's nothing we can do library-side. Feel free to join the above server & thread for updates.
