### ISSUE TITLE
Gracefully handle the case of guilds going unavailable on the fly 

### ISSUE THREAD

**Issue by erkinalp** [discordjs/discord.js#8831]
### Which package is the feature request for?

discord.js

### Feature

Fosscord, an open source third party Discord server implementation, intends to utilise the fact that guilds can go unavailable to implement an IRC/XMPP-style master-slave federation across fosscord instances (when master instance goes down, the guild from that instance will appear unavailable in the slaves). Therefore clients need to be able to gracefully tolerate guilds going unavailable in the middle of a gateway connection.

### Ideal solution or implementation

Discord.js should gracefully tolerate guilds going unavailable in the middle of a connection.

### Other context

This feature should cause no problems when this library is used to connect to discord.com, as it is normally used.

**Comment by Jiralite** [comment]
This is already being handled.
