### ISSUE TITLE
EmbedBuilder().setColor wrong type

### ISSUE THREAD

**Issue by rwxmad** [discordjs/discord.js#8835]
### Which package is this bug report for?

discord.js

### Issue description

I'm trying to assign a color to an embed response but it throws an error:
  Argument of type 'ColorResolvable' is not assignable to parameter of type 'number | RGBTuple | null '

### Code sample

```typescript
// colors module
export default {
  info: '#2196f3',
  notice: '#ffcc00',
  warn: '#ff6666',
  yt: '#f40041',
};
// Embed message
import colors from './colors'
  const embed = new EmbedBuilder()
    .setTitle(songInfo.title)
    .setThumbnail(songInfo.author.avatar)
    .setAuthor({
      name: 'Now playing',
      iconURL: 'attachment://cd.gif',
      url: songInfo.video_url,
    })
    .setURL(songInfo.video_url)
    .setColor(colors.yt as ColorResolvable)
    .addFields(
      { name: 'Channel', value: songInfo.author.name },
      {
        name: 'Length',
        value: moment
          .utc(Number(songInfo.lengthSeconds) * 1000)
          .format('mm:ss')
          .toString(),
      },
      {
        name: 'Views',
        value: numberWithCommas(Number(songInfo.viewCount)),
        inline: true,
      },
      {
        name: 'Publish date',
        value: moment(songInfo.publishDate).format('LL'),
        inline: true,
      },
      { name: 'Video url', value: songInfo.video_url },
    )
    .setTimestamp()
    .setFooter({ text: bot.name, iconURL: bot.avatar });
```

### Package version

14.6.0

### Node.js version

18.7.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

ff85481

**Comment by imranbarbhuiya** [comment]
R u using `EmbedBuilder` from djs or from the builder?

**Comment by rwxmad** [comment]
> R u using `EmbedBuilder` from djs or from the builder?

```
import {
  AttachmentBuilder,
  ChatInputCommandInteraction,
  ColorResolvable,
} from 'discord.js';
import moment from 'moment';

import { EmbedBuilder, SlashCommandBuilder } from '@discordjs/builders';

import colors from '../../lib/colors';
import { numberWithCommas } from '../../lib/utils';

export const data = new SlashCommandBuilder()
  .setName('play')
  .setDescription('Play music')
  .addStringOption(option =>
    option.setName('song').setDescription('Url or song name').setRequired(true),
  );

export async function execute(interaction: ChatInputCommandInteraction) {
  const song = interaction.options.getString('song');
  if (!song) return;

  // Player class
  const player = interaction.client.player;

  await interaction.deferReply();

  // Fetch and validate song url for url or name
  const songUrl = await player
    .search(song)
    .catch((err: Error) => console.error(err));
  const songInfo = await player.fetchVideoInfo(songUrl);

  // Get channel where need to play music
  const member = interaction.guild?.members.cache.get(interaction.user.id);
  const voiceChannel = member?.voice.channel;

  // Return error if member not in voice channel
  if (!voiceChannel) {
    return interaction.editReply('**You need to be in a voice channel!**');
  }

  if (player.state === 'ready') {
    player.queue.add(songUrl, songInfo);
    player.play(voiceChannel, songUrl, songInfo);
  } else {
    player.queue.add(songUrl, songInfo);
    return interaction.editReply('**Added to queue**');
  }

  const bot = {
    name: interaction.client.user.username,
    avatar: interaction.client.user.displayAvatarURL(),
  };

  const cd = new AttachmentBuilder('src/assets/images/cd.gif');

  const embed = new EmbedBuilder()
    .setTitle(songInfo.title)
    .setThumbnail(songInfo.author.avatar)
    .setAuthor({
      name: 'Now playing',
      iconURL: 'attachment://cd.gif',
      url: songInfo.video_url,
    })
    .setURL(songInfo.video_url)
    .addFields(
      { name: 'Channel', value: songInfo.author.name },
      {
        name: 'Length',
        value: moment
          .utc(Number(songInfo.lengthSeconds) * 1000)
          .format('mm:ss')
          .toString(),
      },
      {
        name: 'Views',
        value: numberWithCommas(Number(songInfo.viewCount)),
        inline: true,
      },
      {
        name: 'Publish date',
        value: moment(songInfo.publishDate).format('LL'),
        inline: true,
      },
      { name: 'Video url', value: songInfo.video_url },
    )
    .setColor(colors.yt as ColorResolvable)
    .setTimestamp()
    .setFooter({ text: bot.name, iconURL: bot.avatar });

  return await interaction.editReply({
    embeds: [embed],
    files: [cd],
  });
}

```

**Comment by imranbarbhuiya** [comment]
Yeah that's the issue. Uninstall builder and import from djs instead
```diff
import {
  AttachmentBuilder,
  ChatInputCommandInteraction,
  ColorResolvable,
+ EmbedBuilder,
+ SlashCommandBuilder
} from 'discord.js';
import moment from 'moment';

- import { EmbedBuilder, SlashCommandBuilder } from '@discordjs/builders';
```

**Comment by rwxmad** [comment]
> Yeah that's the issue. Uninstall builder and import from djs instead
> 
> ```diff
> import {
>   AttachmentBuilder,
>   ChatInputCommandInteraction,
>   ColorResolvable,
> + EmbedBuilder,
> + SlashCommandBuilder
> } from 'discord.js';
> import moment from 'moment';
> 
> - import { EmbedBuilder, SlashCommandBuilder } from '@discordjs/builders';
> ```

Thanks a lot

**Comment by rwxmad** [comment]
But now it throws an error:

/Users/rwxmad/code/github/madbot/node_modules/discord.js/src/structures/ChannelSelectMenuBuilder.js:10
class ChannelSelectMenuBuilder extends BuildersChannelSelectMenu {
                                       ^
TypeError: Class extends value undefined is not a constructor or null

**Comment by rwxmad** [comment]
> Yeah that's the issue. Uninstall builder and import from djs instead
> 
> ```diff
> import {
>   AttachmentBuilder,
>   ChatInputCommandInteraction,
>   ColorResolvable,
> + EmbedBuilder,
> + SlashCommandBuilder
> } from 'discord.js';
> import moment from 'moment';
> 
> - import { EmbedBuilder, SlashCommandBuilder } from '@discordjs/builders';
> ```

class ChannelSelectMenuBuilder extends BuildersChannelSelectMenu {
                                       ^
TypeError: Class extends value undefined is not a constructor or null

**Comment by imranbarbhuiya** [comment]
r u using dev release?

**Comment by rwxmad** [comment]
> r u using dev release?

works the same on both versions :(

**Comment by imranbarbhuiya** [comment]
check https://github.com/discordjs/discord.js/issues/8806

**Comment by rwxmad** [comment]
> check #8806

Didn't help

**Comment by CitTheDev** [comment]
Uninstall `discord.js`, `@discordjs/builders` then install `discord.js` again. As of discord.js v14, the builders are exported by discord.js so you do not need to require `@discordjs/builders` to access those classes; you can do it directly from discord.js. This may help prevent your error as the `@discordjs/builders` package may have support for the new select menu types but the `discord.js` package does not as of right now.

**Comment by Jiralite** [comment]
If you need help, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions).
