### ISSUE TITLE
Error when removing role: TypeError [InvalidType]: Supplied user is not a UserResolvable.

### ISSUE THREAD

**Issue by HassHz** [discordjs/discord.js#8839]
### Which package is this bug report for?

discord.js

### Issue description

The following steps happen in a loop (around 8 runs max), and I get an error on the last step, sometimes for the first user, if that randomly ends up working, then fails on the second user, and so on. Believe it may be a caching issue, something related to this: https://github.com/discordjs/discord.js/issues/7474. If so, is there any workaround?

Steps run in a loop:
1. Fetch Guild Member by ID
2. Fetch / Create Roles
3. Remove roles from member

Error: 
```
TypeError [InvalidType]: Supplied user is not a UserResolvable.
    at GuildMemberManager.edit (.../node_modules/discord.js/src/managers/GuildMemberManager.js:294:20)
    at GuildMember.edit (.../node_modules/discord.js/src/structures/GuildMember.js:314:31)
    at GuildMemberRoleManager.set (.../node_modules/discord.js/src/managers/GuildMemberRoleManager.js:194:24)
    at GuildMemberRoleManager.remove (.../node_modules/discord.js/src/managers/GuildMemberRoleManager.js:157:19)
    at setNewRole (.../statUtils.js:21:29)
    at updateRoles (.../statUtils.js:44:15)
    at updateUsersRecord (.../statUtils.js:139:15)
    at async Object.execute (.../score.js:64:17)
    at async Client.<anonymous> (.../index.js:75:9) {
  code: 'InvalidType'
}
```

### Code sample

```typescript
for (const userID of userIDs) {
    const user = await message.guild.members.fetch(userID)

    const guildRoleCache = guild.roles.cache
    const role = guildRoleCache.find(role => role.name === 'role') || await guild.roles.create({ name: 'role', hoist: true })

    await user.roles.remove([role]) // Usually an array of roles
}
```

### Package version

14.6.0

### Node.js version

18.12.0

### Operating system

MacOS, Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
Please include your full error. Never omit it!

**Comment by HassHz** [comment]
> Please include your full error. Never omit it!
> 
> Also, what is `draftee`?

Sorry updated, `draftee` was supposed to be `user`. For the users that it fails, if I print out the member object, the `user` field looks like this:
```
user: User {
    id: false,
    bot: false,
    system: false,
    flags: UserFlagsBitField { bitfield: 64 },
    username: '...', (omitted)
    discriminator: '...', (omitted)
    avatar: '...', (omitted)
    banner: undefined,
    accentColor: undefined
  }
```

**Comment by Jiralite** [comment]
It seems the `id` is `false`. That seems impossible:

https://github.com/discordjs/discord.js/blob/c5d5840fef1f72540f9f76a9f22252f8665d1420/packages/discord.js/src/structures/User.js#L18-L22

The only way this can happen is if you're mutating it. This seems to be an issue in your own code and not a library issue.

**Comment by HassHz** [comment]
> It seems the `id` is `false`. That seems impossible:
> 
> https://github.com/discordjs/discord.js/blob/c5d5840fef1f72540f9f76a9f22252f8665d1420/packages/discord.js/src/structures/User.js#L18-L22
> 
> The only way this can happen is if you're mutating it. This seems to be an issue in your own code and not a library issue.

For some reason it only seems to be happening for my user and the discord bot itself, have an idea of what could be going on? I don't believe I'm mutating it, can you give a sample of maybe some mutation?
