### ISSUE TITLE
Button Handler failing to run code

### ISSUE THREAD

**Issue by DragosPV** [discordjs/discord.js#8854]
### Which package is this bug report for?

discord.js

### Issue description

I don't really understand why is this button handler failing, I'm getting the error `Unknown Interaction`, I know that this error appears only when it took longer than 3 seconds to reply to the interaction but it doesn't make any sense, I have the exact same handler for my commands and it works just fine and I have more commands than buttons, the button that I'm testing it on doesn't do much so it doesn't have a lot of code for it to take longer than 3 senconds.
Also it works for the first 5-6 button interactions but after that it gets the error so it is very random.

### Code sample
Here I create the buttons collection and fill it with each button:
```javascript
client.buttons = new Collection()
const buttonFiles = fs.readdirSync('./buttons').filter(file => file.endsWith('.js'))
for(const file of buttonFiles){
  const button = require(`./buttons/${file}`)
  client.buttons.set(button.id, button)
}
```
Here is the handler:
```javascript
module.exports = {
    name: 'interactionCreate',
    
    async execute(interaction, client){
        if(!interaction.isButton()) return;
        const button = client.buttons.get(interaction.customId);
        if(!button) return;
        try{
            await button.execute(interaction, client);
        } catch(error){
            await interaction.reply({ content: 'Error', ephemeral: true });
            console.error(error);
        };
    }
};
```
A button file only exports the customId of the button (as `button.id`) and the function for that button (as `button.execute()`)
```


### Package version

14.6.0

### Node.js version

16.17.1

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

### I have tested this issue on a development release

_No response_

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) as this issue tracker is only for bug reports and enhancement suggestions.
