### ISSUE TITLE
Make ReactionManager.removeAll() accept cryteria

### ISSUE THREAD

**Issue by PolishKebab** [discordjs/discord.js#8867]
### Which package is the feature request for?

discord.js

### Feature

Make ReactionManager.removeAll() accept cryteria such as emoji name, user.

### Ideal solution or implementation

It removes all reactions with the emoji name or/and from user.

**Comment by kyranet** [comment]
This is not possible, we use 4 different endpoints to do 4 different things:

1. [`/channels/{channel.id}/messages/{message.id}/reactions/{emoji}/@me`](https://discord.com/developers/docs/resources/channel#delete-own-reaction) to delete own reaction.
2. [`/channels/{channel.id}/messages/{message.id}/reactions/{emoji}/{user.id}`](https://discord.com/developers/docs/resources/channel#delete-user-reaction) to delete somebody else's reaction.
3. [`/channels/{channel.id}/messages/{message.id}/reactions`](https://discord.com/developers/docs/resources/channel#delete-all-reactions) to delete all reactions.
4. [`/channels/{channel.id}/messages/{message.id}/reactions/{emoji}`](https://discord.com/developers/docs/resources/channel#delete-all-reactions-for-emoji) to delete all reactions for one emoji.

All 4 aforementioned endpoints are supported within discord.js.

Currently, Discord API allows to do one of the above 4 options, it does not let us remove all reactions from a user. You may suggest it at their API docs → https://github.com/discord/discord-api-docs/issues

Only once Discord implements this feature, we will implement it on Discord.js.
