### ISSUE TITLE
updating djs restarts all shards

### ISSUE THREAD

**Issue by imranbarbhuiya** [discordjs/discord.js#8871]
### Which package is this bug report for?

discord.js

### Issue description

Updating djs when the bot is running restarts all the shards. This happens for both `ShardingManager` as well as for auto shard. 

Steps to repro
- Start a bot
- Update djs

### Package version

Both v13 and v14 latest

### Node.js version

v18.x 

### Operating system

Windows and Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by vladfrangu** [comment]
Uhh, yeah that's impossible, especially with the 2 repro steps you've provided. If you're using something akin to pm2, nodemon, etc, that is outside of discord.js's realm and there's nothing we can do to "fix" what isn't even a bug.

Maybe there's more info you forgot to give us? Follow up if so

**Comment by imranbarbhuiya** [comment]
I'm using `pm2` but without watch mode (I haven't tried without pm2 yet) and it doesn't restart other projects, it only restarts djs bots with sharding (it doesn't restart if u arent sharding). I'll try to make a repro and also see if it restarts without pm2

**Comment by didinele** [comment]
Re-open if this still exists/you can provide more minimal repro steps.
