### ISSUE TITLE
Autocomplete - interaction.respond() no longer populates dropdown menu with results without additional input

### ISSUE THREAD

**Issue by Quoded** [discordjs/discord.js#8882]
### Which package is this bug report for?

discord.js

### Issue description

Autocomplete does not populate with options until the user enters input. (Video shows no options until I input a space into the prompt).

https://user-images.githubusercontent.com/96456208/204559958-b078e3c8-d2d3-4bd1-820e-55d0dbbb82fb.mp4

### Code sample

```typescript
const { SlashCommandBuilder } = require('discord.js')

exports.run = async (client, interaction) => {
  // Type 4 = Autocomplete Interactions
  if (interaction.type == 4) {
    let options = [
      { name: 'Option 1', value: '1' },
      { name: 'Option 2', value: '2' },
      { name: 'Option 3', value: '3' }
    ]
    await interaction.respond(options)
  // Run logic on selected option
  } else {
    let selectedOption = interaction.options.getString('option')
    await interaction.reply({ content: selectedOption, ephemeral: true })
  }
}

exports.conf = {
  enabled: true,
  guildOnly: true
}

exports.commandData = new SlashCommandBuilder()
  .setName('test').setDescription('Test the autocomplete command')
  .addStringOption(option => option.setName('option').setDescription('Autocomplete Command').setRequired(true).setAutocomplete(true))
```

### Package version

14.7.0

### Node.js version

18.4.0

### Operating system

Windows 10/11 64 Bit

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, DirectMessages, MessageContent

**Comment by Jiralite** [comment]
It looks to me like you are reporting a Discord bug. This is discord.js - not Discord.
