### ISSUE TITLE
The code keeps silently running but the bot goes offline and unresponsive

### ISSUE THREAD

**Issue by l1v0n1** [discordjs/discord.js#8899]
### Which package is this bug report for?

discord.js

### Issue description

I ran the bot on different servers, I even rewrote it from discord.PY to discord.JS to fix this problem, but it didn't work for me.

At first everything is fine, I start the bot, it works fine, no errors, but then, after N-th time, the bot simply stops being online and does not respond to commands, but the code execution still continues and shard continues sending heartbeat

### Code sample

```typescript
SHARD.JS

const config = require('./config.json');
const { ShardingManager } = require('discord.js')

const manager = new ShardingManager('./bot.js', {
    totalShards: 1, // or number e.g ( totalShards: 10 )
    token: config.token, // or token e.g ( token: "YOUR BOT TOKEN" )
    spawnTimeout: -1,
    respawn: true
});
manager.on('shardCreate', shard => console.log(`Launched shard ${shard.id}`));

manager.spawn(manager.totalShards, 5500, -1).catch(e => console.log(e))
```

### Package version

discord.js@14.7.1

### Node.js version

v18.12.1

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
> I even rewrote it from discord.PY to discord.JS to fix this problem

Would that not mean this is not a discord.js issue?

**Comment by l1v0n1** [comment]
> > I even rewrote it from discord.PY to discord.JS to fix this problem
> 
> Would that not mean this is not a discord.js issue?

hmm, and you're right, then where should I go?

**Comment by Jiralite** [comment]
For a start, you should probably head into the support channels in our [Discord support server](https://discord.gg/djs). You're spawning your manager incorrectly, as it only takes one parameter yet you provided three.
