### ISSUE TITLE
Really weird bug with interaction.member.id

### ISSUE THREAD

**Issue by hswudh** [discordjs/discord.js#8900]
### Which package is this bug report for?

discord.js

### Issue description

If I get the interaction.member.id at the first time i get the members id but if i go to a voice channel and then get the interaction.member.id i get the clients id

### Package version

discord.js v14

### Node.js version

16.9+

### Operating system

replit.com

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

### I have tested this issue on a development release

4e4cbb3

**Comment by Jiralite** [comment]
This is missing vital detail and a reproducible code sample. replit.com is also not an operating system. It is not clear to me what the problem even is. Until then, this issue is not useful, so I'll be closing this.
