### ISSUE TITLE
Found a Bug with interaction.member

### ISSUE THREAD

**Issue by hswudh** [discordjs/discord.js#8904]
### Which package is this bug report for?

discord.js

### Issue description

**If i go to a voice channel**

![Screenshot 2022-12-03 202748](https://user-images.githubusercontent.com/84588604/205458822-6c4e30d0-a757-4441-8edf-9f2b67a75cee.png)
![Screenshot 2022-12-03 202856](https://user-images.githubusercontent.com/84588604/205458825-b3905026-a45a-4c38-b476-305d72cacde0.png)

### Package version

discord.js v14

### Node.js version

16.9+

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

### I have tested this issue on a development release

4e4cbb3

**Comment by hswudh** [comment]
Sorry for the last one i hope it will help you better

**Comment by SpaceEEC** [comment]
You likely are overwriting the id of the user object somewhere in your code.

Try creating a [minimal, reproducible, sample](https://stackoverflow.com/help/minimal-reproducible-example), you either will make us able to fix this or find the issue on your end.

**Comment by hswudh** [comment]
@SpaceEEC I found the mistake, the id will be overwritten in VoiceStateUpdate now i can keep working on the Bot
Ty for your help <3
