### ISSUE TITLE
Type InternalDiscordGatewayAdapterCreator is no longer assignable to DiscordGatewayAdapterCreator

### ISSUE THREAD

**Issue by dzlandis** [discordjs/discord.js#8906]
### Which package is this bug report for?

voice

### Issue description

After updating from @discordjs/voice v0.11.0 to v0.14.0, it is no longer possible to assign type InternalDiscordGatewayAdapterCreator to type DiscordGatewayAdapterCreator (in typescript of course)

### Code sample

```typescript
const connection = joinVoiceChannel({
      channelId: voiceChannelId,
      guildId: interaction.guild.id,
      adapterCreator: interaction.guild.voiceAdapterCreator,
      selfDeaf: false
    });

// notice that a type error will occur on 'adapterCreator'


// **WORK AROUND FOR NOW**
const connection = joinVoiceChannel({
      channelId: voiceChannelId,
      guildId: interaction.guild.id,
      adapterCreator: interaction.guild.voiceAdapterCreator as DiscordGatewayAdapterCreator,
      selfDeaf: false
    });
```

### Package version

0.14.0

### Node.js version

18.12.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates

**Comment by Jiralite** [comment]
What is your discord.js version?

**Comment by dzlandis** [comment]
@Jiralite v14.6.0

**Comment by Jiralite** [comment]
The error you're receiving looks like a versioning conflict.

I'm not able to reproduce this error on 14.6.0 with 0.14.0 of @discordjs/voice installed. Looking at the dependencies, 0.14.0 is compatible with versions 14.6.0 and later. The only issue here I can think of is that your code is not using either versions you think it is.

**Comment by dzlandis** [comment]
This problem only occurred after I updated @discordjs/voice to v0.14.0. I am pretty confident that the correct version of both packages is being used, but I'll be sure to verify.

**Comment by RedGuy12** [comment]
I also had this problem after updating voice to 0.14.0, but it worked again once I updated mainlib to 14.7.0.

**Comment by dzlandis** [comment]
@RedGuy12 thanks for the tip, updating to 14.7.1 fixed the issue for me!
