### ISSUE TITLE
After 99 spoilers, following text is silently eaten in `.send(...)`

### ISSUE THREAD

**Issue by geometrian** [discordjs/discord.js#8908]
### Which package is this bug report for?

discord.js

### Issue description

Let's say you have a bunch of spoiler tags in the message. E.g. a grid of tiles to play minesweeper, or 'bubbles' that a certain kind of user can enjoy 'popping' like bubblewrap. It seems that if there are more than 99 of these, any following text in the message is silently eaten when you `.send(...)` it in a channel.

Note that this does not appear to be a Discord limitation. The number of characters can easily be less than 2000 with such a scheme, and anyway human posters have no trouble sending such a string.

### Code sample

```typescript
// Above should be clear, but just to be explicit, the following
// untested TypeScript code implementing a "bubblewrap" feature
// should reproduce the issue if a bot were built around it.

// String of 200 spoiler tags
let bubblestr:string = "";
for (let i=0;i<200;++i) bubblestr+="||pop||";

// Send to a text-based channel
channel.send(bubblestr);

// Expected (bad) result: only 99 spoilered "pop"s :C
```

### Package version

13.12.0

### Node.js version

v16.17.1

### Operating system

CloudLinux 7.9

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildWebhooks, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions

**Comment by imranbarbhuiya** [comment]
Can't reproduce the issue with the code you provided. It works fine for me. Also djs doesn't do any type of changes to your string before sending

**Comment by geometrian** [comment]
That's actually the intended repro. Notice that that's a 10 wide by 10 tall grid, and all but one is filled with a spoiler (i.e. 99 spoilers). However, the string itself contains a 10 wide by **18** tall grid, fully populated (i.e. 180 spoilers).

**Comment by imranbarbhuiya** [comment]
I see the issue now. But it's neither djs nor discord api bug I think. Because if u log the message, it shows the ending `💥` too. So djs is sending it and discord is returning too. It's an issue with the client which isn't rendering the emoji correctly

**Comment by geometrian** [comment]
Alright thank you and sorry for the noise. Please close this issue; I will report upstream to Discord.

**Comment by RedGuy12** [comment]
This is also how the so-called "spoiler hack" works - send 99 spoilers full of zero-width spaces or other invisible characters and then ping people or link things after the spoilers and the client won't display it.
