### ISSUE TITLE
Add .toString() method to ApplicationCommand

### ISSUE THREAD

**Issue by net-tech** [discordjs/discord.js#8912]
### Which package is the feature request for?

discord.js

### Feature

Since a few months ago, Discord has added support for mentioning slash commands. Slash command mentions, when clicked by an end-user, make the client automatically select the command. This feature is handy for things like help menus.

Developers can mention slash commands via `</NAME:COMMAND_ID>` and can also mention subcommands and subcommand groups by using `</NAME SUBCOMMAND:ID>` and `</NAME SUBCOMMAND_GROUP SUBCOMMAND:ID>` respectively.

### Ideal solution or implementation

To go in line with methods like [`<Role>.toString()`](https://discord.js.org/#/docs/discord.js/main/class/Role?scrollTo=toString) and [`<GuildMember>.toString()`](https://discord.js.org/#/docs/discord.js/main/class/Role?scrollTo=toString), it would be nice if there was an `<ApplicationCommand>.toString()` method which allowed developers to create slash command mentions quickly. 

### Other context

- [Discord Developer Website - Message Formatting Reference](https://discord.com/developers/docs/reference#message-formatting)
- [Discord Developer Website - Slash Command Mentions Changelog](https://discord.com/developers/docs/change-log#slash-command-mentions)

**Comment by almeidx** [comment]
#8818

**Comment by net-tech** [comment]
Ah, didn't see that, thanks.
