### ISSUE TITLE
Add way to get `icon` hash from user's presence activitiy

### ISSUE THREAD

**Issue by Sravdar** [discordjs/discord.js#8923]
### Which package is the feature request for?

discord.js

### Feature

While some games have rich presence assets others don't even they have a application icon. When working with presenceUpdate its impossible to get application icon hash from these activities. For example game "Project Zomboid" have application icon while having no rich presence assets (data given in context).

Structure: app-icons/application_id/icon.png
Icon link scooped from web discord: https://cdn.discordapp.com/app-icons/426526722322726912/6030c94c33dab692201194047f5e1a51.png

### Ideal solution or implementation

Add property or method to get `icon hash` from [activities](https://discord.js.org/#/docs/discord.js/main/class/Activity)

### Other context

Related doc: https://discord.com/developers/docs/reference#image-formatting

![image](https://user-images.githubusercontent.com/43544458/207027375-de443141-e3ef-454d-8635-b4997f0664f8.png)

**Project Zomboid activity data**
`Activity {
  name: 'Project Zomboid',
  type: 0,
  details: null,
  state: null,
  applicationId: '426526722322726912',
  timestamps: { start: 2022-12-12T10:22:05.703Z, end: null },
  party: null,
  assets: null,
  flags: ActivityFlagsBitField { bitfield: 0 },
  emoji: null,
  buttons: [],
  createdTimestamp: 1670840524562
}`

**Comment by Jiralite** [comment]
No hash is sent or documented on activity objects. What _is_ sent is [this](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-assets) which is already in discord.js. This feature request is invalid.
