### ISSUE TITLE
`EmbedBuilder.setColor` takes a value of type `RGBTuple | number | null` instead of `ColorResolvable`

### ISSUE THREAD

**Issue by TimJentzsch** [discordjs/discord.js#8926]
### Which package is this bug report for?

discord.js

### Issue description

The `EmbedBuilder.setColor` method seems to take values `RGBTuple | number | null` instead of `ColorResolvable` which is listed in the docs.

This means that I cannot set a string hex color.

The code below gives the following error:

```
error TS2345: Argument of type '"#123456"' is not assignable to parameter of type 'number | RGBTuple | null'.

3 const embed = new EmbedBuilder().setColor("#123456");
                                            ~~~~~~~~~
```

### Code sample

```typescript
import { EmbedBuilder } from "@discordjs/builders";

const embed = new EmbedBuilder().setColor("#123456");
```

### Package version

discord.js@14.7.1

### Node.js version

v18.4.0

### Operating system

Linux (Pop!_OS)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, MessageContent

**Comment by Syjalo** [comment]
`ColorResolvable` is a thing of `discord.js`. Import `EmbedBuilder` from `discord.js` and it will take `ColorResolvable`

**Comment by TimJentzsch** [comment]
Ahhh, thanks!
Sorry, not sure why VS Code imported it from the builders package instead.
