### ISSUE TITLE
Messate.toJSON() ignores embeds' author field

### ISSUE THREAD

**Issue by bitomic** [discordjs/discord.js#8929]
### Which package is this bug report for?

discord.js

### Issue description

If you fetch a message and then use the `#toJSON` method on it, it will produce an object that won't include the `author` field if any embed had it.

Using `console.log( message.embeds )` shows that the author field is there, so this looks like an issue related to the [flatten utility](https://github.com/discordjs/discord.js/blob/stable/src/util/Util.js#L26).

Make sure the message you're trying to fetch has an embed, and the embed also has the author field set.

### Code sample

```typescript
const guildId = '1', channelId = '2', messageId = '3'
const guild = await client.guilds.fetch( guildId )
const channel = await guild.channels.fetch( channelId )
const message = await channel.messages.fetch( messageId )
console.log( message.toJSON() )
```

### Package version

13.9.2

### Node.js version

18.5.0

### Operating system

WSL

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions

**Comment by Jiralite** [comment]
It would appear #7773 needs backporting, then.
