### ISSUE TITLE
Masked links not always working as intended.

### ISSUE THREAD

**Issue by Juojo** [discordjs/discord.js#8935]
### Which package is this bug report for?

discord.js

### Issue description

When i try to use **masked links** with `interaction.reply('[link](https://site.com)')` it works perfectly fine.

But when i use:
```
interaction.guild.channels.cache.get('CHANNEL_ID').send('[link](https://site.com)');
```
it send a message showing the contetn "literally" instead of the [link](https://site.com) as intended.

Here is a screenshoot of the problem:
![image](https://user-images.githubusercontent.com/80736129/208004833-21005527-8585-47bf-9653-45086dda63c4.png)

### Code sample

```typescript
interaction.guild.channels.cache.get('CHANNEL_ID').send('[link](https://site.com)');
```

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

MessageContent

**Comment by Jiralite** [comment]
This is not a bug. Masked links cannot be utilised by bots. They render fine via the interaction reply as they are webhooks.
