### ISSUE TITLE
cannot find node:event module

### ISSUE THREAD

**Issue by job-gut** [discordjs/discord.js#8947]
### Which package is this bug report for?

discord.js

### Issue description

1. just "const { EmbedBuilder, WebhookClient } = require( "discord.js" );" this code

Error: Cannot find module 'node:events'
   at require (internal/modules/cjs/helpers.js:22:7)
   at Anonymous function (D:\project\node_modules\discord.js\src\client\BaseClient.js:3:1)
   at require (internal/modules/cjs/helpers.js:22:7)
   at Anonymous function (D:\project\node_modules\discord.js\src\index.js:6:1)

### Code sample

```typescript
const { EmbedBuilder, WebhookClient } = require( "discord.js" );
```

### Package version

14.6.0

### Node.js version

18.12.1

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by jaw0r3k** [comment]
its not a bug 
but you that havent updated node to 16.9+

**Comment by job-gut** [comment]
No It's a bug.
Did u see my node version?

**Comment by job-gut** [comment]
Node.js version
18.12.1

**Comment by job-gut** [comment]
![image](https://user-images.githubusercontent.com/104257231/208307071-85a7ca9e-af69-4a29-91a4-7aeb8cc7c02c.png)

**Comment by job-gut** [comment]
see my screenshot

**Comment by almeidx** [comment]
High chance that is not the node version used in your bots process. Try `console.log(process.version)` *before* importing discord.js
