### ISSUE TITLE
Unable to access newMember.avatarURL() in guildMemberUpdate

### ISSUE THREAD

**Issue by dzlandis** [discordjs/discord.js#8955]
### Which package is this bug report for?

discord.js

### Issue description

* Cause the guildMemberUpdate event to trigger (i.e. change the bots nickname), your bot should have a profile picture.
* Observe that the newMember.user.avatarURL() logs the avatarURL correctly while newMember.avatarURL() doesn't.

It should be noted that the same outcome applies if you use oldMember instead of newMember.

### Code sample

```typescript
client.on('guildMemberUpdate', async (oldMember, newMember) => {
      console.log(newMember.user.avatarURL())
      console.log(newMember.avatarURL())
  })
```

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by Jiralite** [comment]
Bots do not have guild member avatar hashes.

**Comment by Syjalo** [comment]
Probably you're looking for `<GuildMember>.displayAvatarURL()`
https://discord.js.org/#/docs/discord.js/main/class/GuildMember?scrollTo=displayAvatarURL
