### ISSUE TITLE
ModalSubmitInteraction's types have deferUpdate

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#8958]
### Which package is this bug report for?

discord.js

### Issue description

The types for the ModalSubmitInteraction class have the deferUpdate method but not update. I believe it shouldn't have either as these methods should be exclusive to the ModalMessageModalSubmitInteraction class

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by MrMythicalYT** [comment]
#8455 says it's possible to `.deferUpdate()` even if it isn't from a message

**Comment by monbrey** [comment]
At the time I made that PR, that was correct.

Has this been retested and is no longer the case?

**Comment by Jiralite** [comment]
I just tested and I was able to use `deferUpdate()` on a `ModalSubmitInteraction` without error. This seems fine?

**Comment by ImRodry** [comment]
I didn't test it but it didn't seem very logical, what happens when you deferUpdate an interaction that isn't from a message?

**Comment by Jiralite** [comment]
Discord accepts it and there seems to be no visible message.
