### ISSUE TITLE
Expose ws shard metrics

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#8960]
### Which package is the feature request for?

ws

### Feature

Right now, the package lack any info accessible for the developer, eg: shard status, shard ping. It would be nice for us to have a way to access shard metrics. While this is doable in say, simple sharding strategy, the metrics are marked as private, and would not be possible to access without ts-ignore. It becomes more an issue with the worker sharding strategy, where the websocket shards are in a worker, and since it's in a worker, there is no way for me to get the shard info, specially when I track what is my shard statuses. 

This is also nice for those who plan to make a simple wrapper around the discord/ws, or even make it work with existing wrappers by ourselves

### Ideal solution or implementation

Some kind of a central function that just fetches info on all shards would be enough, you can however have a central accessible object where shards would just send data via an interval, but a function that gets shard status is enough, and that would leave it up to the user who use the package to deal with the data.

**Comment by didinele** [comment]
Yeah, on a surface level this should probably just be a manager method i.e. `fetchMetrics(shardId: number): Info` or `fetchMetrics(): Map<number, Info>`. We should probably have a clear list of things we want this to expose, though. cc @vladfrangu
