### ISSUE TITLE
Typing error for reactions

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#8968]
### Which package is this bug report for?

discord.js

### Issue description

In the #5717 PR were added some additional typings for MessageReactionResolvable.
![image](https://user-images.githubusercontent.com/29425008/209443427-f2ca5359-3f90-4d46-b650-a46d1f066f2b.png)

There is actually no code that can parse it in the [`MessageReactionManager>.resolve()`](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/managers/DataManager.js#L34-L43) (there is no override of the `<DataManager>.resolve()`).
A string is not an instance of MessageReaction, and those formulations are not indexes of Collection cached reactions (id or name). 

### Package version

dev

### Priority this issue should have

Medium (should be fixed soon)

### I have tested this issue on a development release

22e2bbb0d24e3f30516f262308d5786f2f666713

**Comment by Jiralite** [comment]
> A string is not an instance of MessageReaction

This is not correct. Unicode emojis!

It looks like `MessageReactionResolvable` is used by the reaction manager and nowhere else. It actually looks like `EmojiIdentifierResolvable` should have these string variants, but is loosely typed as a string.
