### ISSUE TITLE
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: GUILDS.

### ISSUE THREAD

**Issue by JeherillaJanwar** [discordjs/discord.js#8983]
### Which package is this bug report for?

discord.js

### Issue description

I am getting this error with the latest discord.js release (14.7.1).
![Screenshot 2022-12-26 6 45 19 PM](https://user-images.githubusercontent.com/111153791/209588830-4a14ce47-3d65-4bf7-b630-17b5c2136a70.png)

I thought it may be my code, but if I run it with the 12.5.3 version it runs just fine.

### Package version

14.7.1

### Node.js version

18.2.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
> I thought it may be my code

It is, hence the error. If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs).

**Comment by JeherillaJanwar** [comment]
How come it runs fine on the version (12.5.3) ?

**Comment by Syjalo** [comment]
> How come it runs fine on the version (12.5.3) ?

Because they are different major versions with braking changes.
(major.minor.patch)

**Comment by herzane52** [comment]
Hello, I got the same error, v 14.11 version gives the error if there is no role in the user

**Comment by Jiralite** [comment]
Ask in the [Discord server](https://discord.com/invite/djs) or read the [guide](https://discordjs.guide/).
