### ISSUE TITLE
PresenceUpdate event not firing when playing or streaming on twitch

### ISSUE THREAD

**Issue by SteeledSlagle13** [discordjs/discord.js#8995]
### Which package is this bug report for?

discord.js

### Issue description

PresencesUpdate event does not fire when a guildmember starts streaming on **twitch** or on **game status change**.
It does fire when manually changing status and adding custom status message.
When it does fire after manually changing status activities is an empty array even if you are playing a game.

1. change TOKEN to your token
2. run code
3. launch overwatch 2 or some game (presence update does not fire)
4. manually change status (presence update fires but activities is [] instead of containing the 'playing' and 'overwatch 2')

You can start streaming on twitch instead of playing a game and it's the same process and results.

Privileged Gateway Intents Enabled in Discord Developer Portal : PRESENCE INTENT, SERVER MEMBERS INTENT, MESSAGE CONTENT INTENT

### Code sample

```typescript
// Require the necessary discord.js classes
const { Client, Events, GatewayIntentBits } = require('discord.js');

// Create a new client instance
// Added all the intents here
// Privileged Gateway Intents - PRESENCE INTENT, SERVER MEMBERS INTENT, MESSAGE CONTENT INTENT are enabled in the discord developer portal
const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMembers,
        GatewayIntentBits.GuildBans,
        GatewayIntentBits.GuildEmojisAndStickers,
        GatewayIntentBits.GuildIntegrations,
        GatewayIntentBits.GuildWebhooks,
        GatewayIntentBits.GuildInvites,
        GatewayIntentBits.GuildVoiceStates,
        GatewayIntentBits.GuildPresences,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.GuildMessageReactions,
        GatewayIntentBits.GuildMessageTyping,
        GatewayIntentBits.DirectMessages,
        GatewayIntentBits.DirectMessageReactions,
        GatewayIntentBits.DirectMessageTyping,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildScheduledEvents,
        GatewayIntentBits.AutoModerationConfiguration,
        GatewayIntentBits.AutoModerationExecution,
    ]
});

// When the client is ready, run this code (only once)
// We use 'c' for the event parameter to keep it separate from the already defined 'client'
client.once(Events.ClientReady, c => {
    console.log(`Ready! Logged in as ${c.user.tag}`);
});

// should fire when going from just online to "Playing Overwatch 2" or going from online to streaming on twitch
// it does fire when i manually update my status. and it does get the custom status if i add that
client.on(Events.PresenceUpdate, (oldPresence, newPresence) => {
    console.log(oldPresence, newPresence);
    console.log('==============================================');
});


// Log in to Discord with your client's token
client.login(TOKEN); // replace with your token
```

### Package version

discord.js@14.7.1

### Node.js version

v16.16.0

### Operating system

Windows 10 and Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
Cannot reproduce with the provided code sample.

**Comment by Jiralite** [comment]
I tried to reproduce this issue again to no avail. I tried both streaming on Twitch and using a game status.

Keep in mind that Discord sometimes dislikes data sent via streaming and fails to emit anything (it's a common problem).
