### ISSUE TITLE
MissingPermissions errors despite permissions being correct

### ISSUE THREAD

**Issue by DumbassDev** [discordjs/discord.js#8998]
### Which package is this bug report for?

discord.js

### Issue description

Despite all my permissions being correct and the bot having a higher role than the members I am attempting to moderate, any moderation features (kick, ban, timeout, etc.) are giving "Missing Permissions" errors. I've already opened a question post in the Discord server and my permissions/role structure appear to be correct.

### Code sample

```typescript
const members = interaction.guild?.members
await members?.ban(user)
```

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Windows (dev) / Linux (VPS) [Issue persists on both]

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
This cannot be a discord.js bug as the id is required in the route. Your error is from Discord. In addition, your code sample is incorrect.
