### ISSUE TITLE
.send() method on Channel does not exist in type hinting, causes compiler error in TypeScript

### ISSUE THREAD

**Issue by JoshuaWeissTBS** [discordjs/discord.js#9002]
### Which package is this bug report for?

discord.js

### Issue description

1. Use TypeScript
2. Get a TextChannel using the client.channels.fetch() method
3. Attempt to run the .send() method on the channel
4. Results in compiler error:
```
Property 'send' does not exist on type 'Channel'.
  Property 'send' does not exist on type 'CategoryChannel'.

16    channel.send('bup');
```

Another potential issue, it seems it may be returning `CategoryChannel`, which should indeed not have a `.send()` method, but the ID I provided is of a `TextChannel`, and using `// @ts-ignore` to ignore the compiler error, allows the `.send()` method to be ran just fine.

### Code sample

```typescript
client.channels.fetch(TEXT_CHANNEL_ID).then(channel => {
	channel.send('bup');
});
```

### Package version

14.7.1

### Node.js version

18.11.0

### Operating system

Linux Manjaro

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

d3e9f2a.0

**Comment by Jiralite** [comment]
I think your error is very clear. Check the type or cast.
