### ISSUE TITLE
Bot unable to reply to an interaction within 3 seconds (impossible to reproduce)

### ISSUE THREAD

**Issue by TheYuriG** [discordjs/discord.js#9010]
### Which package is this bug report for?

discord.js

### Issue description

I'm going to start by saying that I'm not creating this issue to have it fixed because we have spent a lot of time trying to understand what's happening in the [D.JS forums](https://discord.com/channels/222078108977594368/1059163759547011092) and we really got nowhere to why does this happen. Similar, but reversed problem [here](https://discord.com/channels/222078108977594368/1060272307567870014).

I'm opening this issue solely so this can be registered. You guys can feel free to close it immediately and reference it in the future if necessary because I think this will happen to another random person as it happened to me out of nowhere. Most likely no one will know what causes it just like we couldn't figure out.

I have not changed any code since early December and starting January 1st, my bot turned completely unable to reply to interactions within the 3 required seconds. Keep in mind that I never had an issue with this and now EVERY SINGLE COMMAND fails to respond within 3 seconds.

If you look through the discord forum linked above, you will see that Qjuh suggested logging timestamps for everything and I did that. The events are still received instantly and my code runs just fine _until_ I need to reply to the interaction. Then it hangs up for over 5 seconds before returning me an 'interaction invalid' error. Once again I'll repeat myself and say that I have not done any code changes in the prior 3 weeks of this problem and this never happened before, now it happens 100% of the time.

What worked for me was deferring the interaction at the very top of the commands, then editing replies instead of replying. Instead of adding that to every file, I'm now deferring the interaction on the `interactionCreate` event instead and changing the code of all commands to use `editReply` instead of `reply`. The similar issue linked below mine had it completely in reverse, they can only use `reply` and no `deferReply` nor `editReply`, else they face the same issue as I do: inability to acknowledge the interaction in time.

### Package version

14.7.1

### Node.js version

16.9.0

### Operating system

Raspberry Pi OS (Raspberry Pi)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildIntegrations

**Comment by TheYuriG** [comment]
Dunno if related, but now my bot takes around 40 seconds to log in successfully and be ready to handle commands. This also never happened before, I had login times of 3~5 seconds after all commands were loaded.

I have restarted the raspberry multiple times and tried with multiple connections, wired and wireless alike, to no avail. It's not a network problem because when I changed my `interactionCreate` event to `deferReply()` or straight up `reply()`, the commands that I had not changed from `reply()` to `editReply()` were giving me instantaneous `interaction already replied` errors.

**Comment by Jiralite** [comment]
If you're sure this is a Discord issue then opening it here won't do you any good. Why don't you tell Discord instead?

You should also try reproducing without libraries to be sure.

**Comment by TheYuriG** [comment]
> If you're sure this is a Discord issue then opening it here won't do you any good.

> I'm opening this issue solely so this can be registered. You guys can feel free to close it immediately and reference it in the future if necessary because I think this will happen to another random person as it happened to me out of nowhere. Most likely no one will know what causes it just like we couldn't figure out.

There is a chance there is something wrong with the REST API you people implemented, also it's important that you people have awareness of this issue. I don't understand the hostility, did I fail to properly open an issue in some way that upset you?
