### ISSUE TITLE
EmbedBuilder does not allow for Canvas rendered image to be placed.

### ISSUE THREAD

**Issue by pgsleepy** [discordjs/discord.js#9061]
### Which package is this bug report for?

discord.js

### Issue description
For some reason, a rendered buffer image/png cannot be send through Embed as it will be placed outside of the Embed.
This issue does not persist when writing that buffer to a file and then including it.

1. Create a canvas as the [documentation ](https://discordjs.guide/popular-topics/canvas.html#setting-up-napi-rs-canvas)says through `@napi-rs/canvas`
2. Write that canvas into a 'image/png' buffer.
3.  Using the actual documentation on [attaching an image to an embed](https://discordjs.guide/popular-topics/embeds.html#attaching-images) to attach the image.
4. Outputs the image outside of the Embed when you include it to the attachment.

I quickly made a piece of code based on the documentations, and the output is 
![image](https://user-images.githubusercontent.com/97898191/212416591-a074cabc-9c12-4f35-a243-4ef9f8cc1c43.png)

### Code sample

```typescript
//Create Canvas
            const Canvas = require('@napi-rs/canvas')
            const c = Canvas.createCanvas(900, 560)
            const ctx = c.getContext('2d')

            //Add the text "Hello!"" at 50,50 at 24px size aligning it center.
            ctx.font = "100px"
            ctx.textAlign = 'center';
            ctx.fillText(`Hello!`, 450, 280)

            //Add this canvas to a image/png buffer.
            const buffer = c.toBuffer('image/png')

            //Making it into an attachment.
            const file = new AttachmentBuilder(buffer, 'discordjs.png');

            //Making the embed and placing the attachment in it
            const exampleEmbed = new EmbedBuilder()
            .setTitle('Some title')
            .setImage('attachment://discordjs.png');
            //Adding the file to the files[] array
            return interaction.editReply({ embeds: [exampleEmbed], files: [file] });
            //Outputs the picture outside of the embed.
```

### Package version

14.5.0

### Node.js version

v16.13.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, DirectMessageReactions, MessageContent

**Comment by almeidx** [comment]
[`AttachmentBuilder`s constructor](https://discord.js.org/#/docs/discord.js/main/class/AttachmentBuilder) takes an object as the second argument

```diff
-            const file = new AttachmentBuilder(buffer, 'discordjs.png');
+            const file = new AttachmentBuilder(buffer, { name: 'discordjs.png' });
```

**Comment by pgsleepy** [comment]
> [`AttachmentBuilder`s constructor](https://discord.js.org/#/docs/discord.js/main/class/AttachmentBuilder) takes an object as the second argument
> 
> ```diff
> -            const file = new AttachmentBuilder(buffer, 'discordjs.png');
> +            const file = new AttachmentBuilder(buffer, { name: 'discordjs.png' });
> ```

This did it, thank you!
The documentation is outdated it seems then.

**Comment by Jiralite** [comment]
> The documentation is outdated it seems then.

Your issue states you are using 14.5.0, so on https://discord.js.org/#/docs/discord.js/14.5.0/class/AttachmentBuilder you will see the second parameter takes an [`AttachmentData`](https://discord.js.org/#/docs/discord.js/14.5.0/typedef/AttachmentData), which is an object. Please select the version you are using here:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/33201955/212433375-33be6ce1-bf6f-4996-b464-71626fb9af91.png">
