### ISSUE TITLE
window.webkitStorageInfo is deprecated. Please use the standardized version navigator.storage instead.

### ISSUE THREAD

**Issue by PierreLGBT** [discordjs/discord.js#9063]
### Which package is this bug report for?

voice

### Issue description

JavaScript uses obsolete features

### Package version

14

### Node.js version

19

### Operating system

ChromeOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
What makes this a discord.js issue?

**Comment by PierreLGBT** [comment]
Actually I don't know how to get help but it concerns invisible.js... Sorry if it's out of subject...

**Comment by Jiralite** [comment]
Opening issues in random repositories is not going to get you the solutions you want. If you want help with "invisible.js", you should seek help from them. I see you already opened an issue there (https://github.com/invisiblejs/invisible/issues/57) so this is redundant.

**Comment by PierreLGBT** [comment]
Ok

**Comment by PierreLGBT** [comment]
I just point out that Discord uses invisible.js
