### ISSUE TITLE
Type definition error for CommandInteractionOptionResolver

### ISSUE THREAD

**Issue by tabarra** [discordjs/discord.js#9066]
### Which package is this bug report for?

discord.js

### Issue description

1. Create a chat input command interaction
2. Try to access `interaction.options.getSubcommand()`
3. Contemplate your life choices while you try to interpret the typescript error

Specifically, the `options` from `ChatInputCommandInteraction` now Omits `getSubcommand()` and many other for some reason.  
The documentation clearly states [that method exists](https://discord.js.org/#/docs/discord.js/main/class/CommandInteractionOptionResolver), but it is omitted.  
The code below works, although it shows typescript error.  
  
I git-blamed it to this pull request: https://github.com/discordjs/discord.js/pull/6672

### Code sample

```typescript
const whatever =  (interaction: ChatInputCommandInteraction) => {
    const subcommand = interaction.options.getSubcommand();
    //                                     /\/\ TS Error
    console.log(subcommand); //does print the subcommand
    //...
}
```

### Package version

14.7.1

### Node.js version

16.9+

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

13ce78a

**Comment by Jiralite** [comment]
Not only can I not reproduce this, it's not even possible:

https://github.com/discordjs/discord.js/blob/13ce78af6e3aedc793f53a099a6a615df44311f7/packages/discord.js/typings/index.d.ts#L1075-L1077

**Comment by tabarra** [comment]
Perhaps it is a bug within my vscode?  
I've restarted its TS Server, and then restarted VSCode itself.  
VSCode is correctly showing the type as `ChatInputCommandInteraction`, but when i ctrl+click it sends me to the definition of `CommandInteraction`, and i haven't noticed that before submitting this issue.

https://user-images.githubusercontent.com/1808295/212499982-5bf6d5e7-499b-40d1-b57e-e11087c4dcff.mp4  
  
BTW here's the issue:
```
Property 'getSubcommand' does not exist on type 'Omit<CommandInteractionOptionResolver<CacheType>, "getMessage" | "getFocused" | "getMentionable" | "getRole" | "getAttachment" | ... 6 more ... | "getSubcommand">'.ts(2339)
```

**Comment by Jiralite** [comment]
As you can see from the code excerpt above and your error, they do not match. This means your `ChatInputCommandInteraction` is not from discord.js, overwritten, etc. This is not a discord.js issue.
