### ISSUE TITLE
@discordjs/ws erlpack encoding support

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#9075]
### Which package is the feature request for?

ws

### Feature

Erlpack was not added on `@discordjs/ws` and the only encoding option is `json` with no support for `etf`

### Ideal solution or implementation

Implement erlpack encoding that is similar to the old websocket code, with the option to fallback to json for those who can't install it

### Other context

Been using erlpack for a long time now and using it gave me a lot of performance benefits over the years I used it. Would be nice to add support for it as well on `@discordjs/ws`

**Comment by Deivu** [comment]
> We've explicitly opted against implementing it due to concerns with the erlpack lib that Discord offers. If a better alternative were to arise, we're more than willing to implement it.

If that's the case, then should d.js just develop or fork their own erlpack and fix the concerns they have over the Discord provided erlpack lib? Since the performance increase on using erlpack is really noticeable and would help us to deploy less threads due to lower cpu usage on decoding / encoding

**Comment by didinele** [comment]
Not only do I think there's no one willing to do it, there's always the concern that if someone does it no one else will have a clue how to maintain it, making it dependant on that one person.

**Comment by timotejroiko** [comment]
> We've explicitly opted against implementing it due to concerns with the erlpack lib that Discord offers. If a better alternative were to arise, we're more than willing to implement it.

what would be those concerns and what would be the requirements for a better alternative? I have implemented an ETF encoder/decoder in pure js for my library, i wouldn't mind making it available as a separate package and, if need be, modifying it to comply with your requirements if you guys are interested.

**Comment by SuperchupuDev** [comment]
according to discord staff (ian 2) erlpack isn't really needed a anymore

![Screenshot_20230321-084829_Discord.jpg](https://user-images.githubusercontent.com/53496941/226556821-fe54a98b-752f-494b-8e7d-9c94db7f4295.jpg)

**Comment by vladfrangu** [comment]
Realistically, if you care about ws performance, installing the 3 recommended optional packages would give a noticeable performance increase! It's one of the main reason I leaned against implementing etf support when we (or well, DD made) /ws.

**Comment by didinele** [comment]
As stated, we don't intend to support erlpack in the near future.
