### ISSUE TITLE
Command localizations don't use camelcase when creating a command with slashcommand builder

### ISSUE THREAD

**Issue by schblondie** [discordjs/discord.js#9083]
### Which package is this bug report for?

builders

### Issue description

When creating a command with the slashcommand builder the localizations have the key names `description_localizations` and `name_localizations`.
This works when creating a command but is annoying when you want to compare those values with the values from using `GuildApplicationCommandManager.fetch({ withLocalizations: true })` as it returns those keys with the correct camelcase.

### Code sample returns:

```
SlashCommandBuilder {
  options: [],
  name: 'hello',
  name_localizations: { de: 'hallo' },
  description: 'Replies with Hello World!',
  description_localizations: { de: 'Antwortet mit Hallo Welt!' },
  default_permission: undefined,
  default_member_permissions: undefined,
  dm_permission: undefined
}
Collection(1) [Map] {
  '1067037449294983168' => <ref *1> ApplicationCommand {
    id: '1067037449294983168',
    applicationId: '824536235523047434',
    guild: Guild {
      id: '1000066569776402492',
      name: undefined,
      icon: undefined,
      features: undefined,
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      autoModerationRules: [AutoModerationRuleManager],
      available: false,
      shardId: 0
    },
    guildId: '1000066569776402492',
    permissions: ApplicationCommandPermissionsManager {
      manager: [Circular *1],
      guild: [Guild],
      guildId: '1000066569776402492',
      commandId: '1067037449294983168'
    },
    type: 1,
    name: 'hello',
    nameLocalizations: { de: 'hallo' },
    nameLocalized: null,
    description: 'Replies with Hello World!',
    descriptionLocalizations: { de: 'Antwortet mit Hallo Welt!' },
    descriptionLocalized: null,
    options: [],
    defaultMemberPermissions: null,
    dmPermission: null,
    version: '1067038402886770698'
  }
}
```

### Code sample

```typescript
const { Client, SlashCommandBuilder } = require('discord.js')
const { REST } = require('@discordjs/rest')
const { Routes } = require('discord-api-types/v10')
const client = new Client({ intents: 0 })
require('dotenv').config()
const command = new SlashCommandBuilder()
  .setName('hello')
  .setDescription('Replies with Hello World!')
  .setNameLocalizations({
    'de': 'hallo'
  })
  .setDescriptionLocalizations({
    'de': 'Antwortet mit Hallo Welt!'
  })
console.log(command)
async function start () {
  const rest = new REST({ version: '10' }).setToken(process.env.TOKEN)
  rest.put(Routes.applicationGuildCommands(process.env.CLIENT_ID, process.env.TEST_GUILD_ID), { body: [command] })
  await client.login(process.env.TOKEN)
  guild = client.guilds.cache.get(process.env.TEST_GUILD_ID)
  console.log(await guild.commands.fetch({ withLocalizations: true }))
}
start()
```

### Package version

v14.7.1

### Node.js version

v18.12.1

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
There doesn't seem to be a bug described here. Can you concisely elaborate what the goal is?

**Comment by schblondie** [comment]
See #9084

**Comment by Jiralite** [comment]
I'm not sure what the goal is here, but your understanding of it may be flawed, as presented by the pull request.

The API sends and receives snake_case properties, which is why the change to builders was incorrect. Builders is not solely used with discord.js. Until you can explain your issue in a better way that can be understood (I still have no idea what is wrong here), I don't think this can move forward.

**Comment by schblondie** [comment]
I justed used search & replace to replace those values, Discord API indeed returns non camel case values. When using the fetch method those localizations get returned in camel case. To ensure that those keys are the same in every method, the slash command builder data should also be in camel case. When setting the localizations, you also use `nameLocalizations` and `descriptionLocalizations` so why should it be `name-localizations` and `description-localizations` afterwards? When creating the commands without the slash command builder you can use non camel case and camel case. So there shouldn't be a problem in the REST module when using those.

**Comment by schblondie** [comment]
The goal is to get consistency in the values and keys as you can't use `isEqual()` from `lodash ` when the keys are different even when they contain the same values and they mean the same thing. This could be used to only create a `REST put` request when there are changes in the command config.

**Comment by schblondie** [comment]
In the [https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/managers/ApplicationCommandManager.js](ApplicationCommandManager) `camelCase` keys get converted to `snake_case` as required by the Discord API. Sure you can provide the JSON data in `snake_case` as required but the rest of the discord.js codebase uses `camelCase` in functions or return values.

**Comment by Jiralite** [comment]
It sounds like you just need [`ApplicationCommand#equals()`](https://discord.js.org/#/docs/discord.js/main/class/ApplicationCommand?scrollTo=equals), no?

```TypeScript
import { Guild, Locale, SlashCommandBuilder } from "discord.js";

declare const guild: Guild;

const slashCommandBuilder = new SlashCommandBuilder()
	.setName("test")
	.setDescription("test")
	.setNameLocalization(Locale.Bulgarian, "test")
	.setDescriptionLocalization(Locale.Bulgarian, "test");

// Create the command.
await guild.commands.create(slashCommandBuilder);

// Fetch all commands.
const command = await guild.commands
	.fetch({ withLocalizations: true })
	.then((a) => a.find((command) => command.name === "test")!);

console.log(command.equals(slashCommandBuilder.toJSON())); // true
slashCommandBuilder.setNameLocalization(Locale.ChineseCN, "test");
console.log(command.equals(slashCommandBuilder.toJSON())); // false
```
