### ISSUE TITLE
`Embed#equals()` will never equal `EmbedBuilder#data`

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#9095]
### Which package is this bug report for?

discord.js

### Issue description

Here is the definition for `Embed#equals()`:

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/structures/Embed.js#L207-L217

This may take an `APIEmbed`. Looking at `EmbedBuilder#data`:

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/builders/src/messages/embed/Embed.ts#L43-L47

We can see this is an `APIEmbed`. Therefore, these should be comparable. However, comparisons here will never be equal, as received embeds from Discord have a `type` property which is not present during construction.

The code sample contains a `console.log()`, of which the output is:

```xl
false { type: 'rich', description: 'test' } { description: 'test' }
```

The internally-called `isEqual()` method is derived from fast-deep-equal which compares the number of object keys, thus introducing this bug (view source code [here](https://github.com/epoberezkin/fast-deep-equal/blob/d807ffc5013e710deb1c63d463a03f729bcd144d/src/index.jst#L54-L56)).

An important mention here is that this is **not** limited to Discord's returned `type` property. Field `inline` values are optional whereas Discord will always return them, causing a mismatch of the length of keys. Additionally, what if Discord creates a new property on an embed? As soon as their API deployment is done, this method will begin failing despite no changes in discord.js. 

### Code sample

```typescript
import { Client, Events, GatewayIntentBits, EmbedBuilder } from "discord.js";
import { inspect } from "node:util";

const client = new Client({ intents: GatewayIntentBits.Guilds });
const embed = new EmbedBuilder().setDescription("test");

client.on(Events.ClientReady, async () => {
	const channel = client.channels.resolve("channel_id");
	const message = await channel.send({ embeds: [embed] });

	console.log(
		message.embeds[0].equals(embed.data),
		inspect(message.embeds[0].data, false, Number.POSITIVE_INFINITY, true),
		inspect(embed.data, false, Number.POSITIVE_INFINITY, true),
	);
});

client.login();
```

### Package version

14.7.2-dev

### Node.js version

Node.js 18.13.0 & typescript 4.9.4

### Operating system

macOS Ventura 13.1

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

8b70f497a1207e30edebdecd12b926c981c13d28

**Comment by theVJagrawal** [comment]
Can I work on this one? I am pretty new to this

**Comment by hampuskraft** [comment]
> Can I work on this one? I am pretty new to this

https://youtu.be/ZXsQAXx_ao0?t=44
