### ISSUE TITLE
Incorrect types for fetching guilds

### ISSUE THREAD

**Issue by fl3xice** [discordjs/discord.js#9105]
### Which package is this bug report for?

discord.js

### Issue description

When you are use client.guilds.fetch("snowflake") you are get one guild but it's not just Guild type, you are getting Collection of Guilds

![image](https://user-images.githubusercontent.com/52685852/216343193-364b3dd0-0160-405d-9ef1-190ae2f5ff91.png)
 
```ts
// It's correct but no
const guild: Guild = await client.guilds.fetch("GUILD_ID");
```

```ts
// Correct
const guild: Collection<Snowflake, OAuth2Guild> = await client.guilds.fetch("GUILD_ID");
```

This is spelled out in the documentation, but it is very strange, since the overload of methods in the type declaration file indicates that the method will return Promise<Guild> if you specify only Snowflake guilds in the parameters of the fetch method

https://discord.js.org/#/docs/discord.js/14.7.1/class/GuildManager?scrollTo=fetch
https://github.com/discordjs/discord.js/blob/14.7.1/packages/discord.js/src/managers/GuildManager.js#L264

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Linux Debian 11 XFCE

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by Jiralite** [comment]
I am not able to reproduce this behaviour (no intents to ensure no guild cached):

<img width="462" alt="image" src="https://user-images.githubusercontent.com/33201955/216346123-a2cb28c0-b23b-45e6-ba5d-a6ac32de6c00.png">

I also cannot see how this would happen:

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/managers/GuildManager.js#L266-L279

My only guess is you are not providing a guild id, which is contrary to what you have written.

**Comment by fl3xice** [comment]
No, I provided the guild identifier, this is an error as in d.ts types, or just not yet implemented functionality, I haven't figured out why myself yet.

![image](https://user-images.githubusercontent.com/52685852/216347075-e4b7416b-c10a-401b-8d0b-e35717c4d3cd.png)

**Comment by fl3xice** [comment]
> No, I provided the guild identifier, this is an error as in d.ts types, or just not yet implemented functionality, I haven't figured out why myself yet.
> 
> ![image](https://user-images.githubusercontent.com/52685852/216347075-e4b7416b-c10a-401b-8d0b-e35717c4d3cd.png)

![image](https://user-images.githubusercontent.com/52685852/216347256-c3c8c579-1ed1-49dc-bdf8-e7385f62eb74.png)

**Comment by Jiralite** [comment]
`useConfiguration().guildId` is `undefined`.

**Comment by fl3xice** [comment]
> `useConfiguration().guildId` is `undefined`.

![image](https://user-images.githubusercontent.com/52685852/216348046-5358e0d1-357e-4330-acbe-0c8ce7c35cef.png)
![image](https://user-images.githubusercontent.com/52685852/216348073-09c04602-dbe5-4347-b129-8b3ecff26295.png)

**Comment by almeidx** [comment]
Looks like a number, which cannot contain the value of a snowflake. You have to use strings

**Comment by fl3xice** [comment]
> Looks like a number, which cannot contain the value of a snowflake. You have to use strings

![image](https://user-images.githubusercontent.com/52685852/216348412-7764418a-bf72-423c-bd41-be48c4590a7a.png)
Snowflake is alias to string

**Comment by Jiralite** [comment]
To be blunt also, 639463787597922300 is not a guild id. To be honest, I would expect a developer to do at least some level of debugging to find an issue.

You can check it's an unknown guild here: https://discord.com/api/guilds/639463787597922300/widget.json

**Comment by fl3xice** [comment]
> To be blunt also, 639463787597922300 is not a guild id. To be honest, I would expect a developer to do at least some level of debugging to find an issue.
> 
> You can check it's an unknown guild here: https://discord.com/api/guilds/639463787597922300/widget.json

i'm off widget on this server

**Comment by Jiralite** [comment]
That doesn't matter.

**Comment by fl3xice** [comment]
> That doesn't matter.

But this guild exists, he even returned her name in that collection, in the first screenshots

**Comment by Jiralite** [comment]
Please look closely. They are different...

**Comment by fl3xice** [comment]
> Please look closely. They are different...

You're right, i'm so sorry, i understand
