### ISSUE TITLE
DiscordAPIError

### ISSUE THREAD

**Issue by meuntouchable** [discordjs/discord.js#9107]
Does anyone know this issue and how to fix?

### Which package is this bug report for?

discord.js

### Issue description

/opt/dd/node_modules/@discordjs/rest/dist/index.js:667
        throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/opt/dd/node_modules/@discordjs/rest/dist/index.js:667:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/opt/dd/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/opt/dd/node_modules/@discordjs/rest/dist/index.js:910:22)
    at async ChatInputCommandInteraction.deferReply (/opt/dd/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
    at async Object.execute (/opt/dd/Commands/bdsm.js:20:3)
    at async Query.<anonymous> (/opt/dd/doubled.js:379:8) {
  requestBody: { files: undefined, json: { type: 5, data: { flags: undefined } } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1070991239727566908/aW50ZXJhY3Rpb246MTA3MDk5MTIzOTcyNzU2NjkwODpYdmVpMU1iZ0ViNzdmNDZmSmpHQUlJYmR6WnltcFpNWklubzNpdmFBTjZMOE9rQ29tenJGUHB6QVZuQU0wVE1mYktZTkZxN0dqcWd1bXNsbmRzOE1LQ0drZnl2eFZLelNDRXNKTFlpOWV4S1BPWW03VWVJR3lKVjZ3dDFlTU1zQQ/callback'
}

### Code sample

```typescript
//Librarys
const {PermissionsBitField,EmbedBuilder,MessageAttachment,Permissions}=require('discord.js');
//Custom configs
const {BotVersion,ServerInvite}=require("../Configs/General.json");
const {NormalCooldown}=require("../Configs/Cooldowns.json");
const {BDSM}=require("../Configs/Counter.json");
const {GiveCooldown}=require("../Usefull/GiveStuff.js");
const {NSFWnotEnabled}=require("../Usefull/Other.js");
//Packages
const fs=require("fs");
const wait=require('util').promisify(setTimeout);

module.exports={
	name:"bdsm",
	description:"[NSFW] Get a random BDSM Picture (18+)",
	options:null,
	global:true,
	
	async execute(client,color,db,interaction){
		await interaction.deferReply();
		
		db.query("SELECT * FROM Serverdata WHERE ServerID=?",[interaction.guild.id],async(err,row)=>{
			if(err)throw err;
			
			db.query("SELECT * FROM UserTimeOuts WHERE UserID=?",[interaction.member.user.id],async(err1,row1)=>{
				if(err1)throw err1;
				
				if(!interaction.guild.members.me.permissions.has(PermissionsBitField.resolve(['SendMessages','EmbedLinks','AttachFiles']))){
					return interaction.member.send({content:"`SendMessages`,`EmbedLinks` or `AttachFiles` permission missing for this channel!"})
				}
				
				if(interaction.channel.nsfw){
					if(row1.length && ((Date.now()/1000)-row1[0].Normal)<NormalCooldown){
						await interaction.editReply({content:"Wait **"+Math.round(-((Date.now()/1000)-row1[0].Normal)+NormalCooldown)+"** seconds before getting typing this again.",ephemeral:true});
						return;
					}else{
						var phad="./Files/Pictures/NSFW/Everyone/BDSM/";
						var rdm=Math.floor(Math.random()*BDSM);
						
						if(fs.existsSync(phad+"Pic ("+rdm+").jpg")){
							const embed=new EmbedBuilder()
							embed.setColor(color)
							embed.setAuthor({name:"Here, take some bdsm.",iconURL:client.user.displayAvatarURL({format:"png",dynamic:true}),url:"https://discord.com/oauth2/authorize?client_id="+client.user.id+"&permissions=8&scope=bot%20applications.commands"})
							embed.setImage("attachment://Pic_"+rdm+".jpg")
							embed.setTimestamp()
							embed.setFooter({text:interaction.member.user.username+" • "+interaction.member.user.id+"\nVersion: "+BotVersion,iconURL:interaction.member.user.displayAvatarURL({format:"png",dynamic:true})});
							
							await GiveCooldown(interaction.member.user.id,interaction.guild.id,"General",db);
							
							await interaction.editReply({embeds:[embed],files:[phad+"Pic ("+rdm+").jpg"],ephemeral:false});
							return;
						}else{
							await interaction.editReply({content:"Image Number `"+rdm+"` not found! Please join our Support Server "+ServerInvite+" to report this error!",ephemeral:true})
							return;
						}
					}
				}else{
					return NSFWnotEnabled(client,interaction);
				}
			});
		});
	}
};
```

### Package version

14.7.1

### Node.js version

16.19.0

### Operating system

debian 11

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Nothing

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
