### ISSUE TITLE
Typing of AutoModerationActionMetadata incorrect

### ISSUE THREAD

**Issue by Larsundso** [discordjs/discord.js#9110]
### Which package is this bug report for?

discord.js

### Issue description

Typing says there should be `channelId` or `durationSeconds`
There actually is `channel_id` or `duration_seconds`
i.e. parameters not transformed or typing incorrect

1. Create Automoderation Rule with timeout or alert channel
2. listen to `autoModerationActionExecution` event
3. log `<Discord.AutoModerationActionExecution>.action.metadata` to console
4. trigger the auto moderation rule

### Code sample

```typescript
const Discord = require("discord.js");

const client = new Discord.Client({
  shards: "auto",
  intents: [Discord.IntentsBitField.Flags.AutoModerationExecution],
});

client.login(
  "TOKEN"
);

client.on("autoModerationActionExecution", (execution) => {
  console.log(execution.action.metadata);
});
```

### Package version

14.7.1

### Node.js version

17.8.0

### Operating system

Ubuntu 20.04

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

AutoModerationExecution

### I have tested this issue on a development release

405f940

**Comment by Jiralite** [comment]
Do you mind clarifying what's wrong? You haven't exactly said it yourself—just notified that something is wrong.

**Comment by Larsundso** [comment]
adjusted issue description

**Comment by Jiralite** [comment]
Thank you!
