### ISSUE TITLE
Property 'voice' does not exist on type 'GuildMember | APIInteractionGuildMember'.

### ISSUE THREAD

**Issue by fise002** [discordjs/discord.js#9112]
### Which package is this bug report for?

discord.js

### Issue description

Estou com esse problema usando typescript> discord
Property 'voice' does not exist on type 'GuildMember | APIInteractionGuildMember'.

### Code sample

```typescript
const channel = interaction.member?.voice.channel
```

### Package version

discord.js v14.7.1

### Node.js version

node js v18

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
