### ISSUE TITLE
Emoji name in console but DiscordAPIError[10014]: Unknown Emoji

### ISSUE THREAD

**Issue by TheHellTower** [discordjs/discord.js#9114]
### Which package is this bug report for?

discord.js

### Issue description

Just need to use the code Sample normally.

Output:
![](https://i.imgur.com/bzH2U5L.png)

### Code sample

```typescript
await message.guild.emojis.fetch().then((e) => console.log(e.size));
```

### Package version

17.6.0

### Node.js version

19.1.0

### Operating system

Windows 10 22H2 (Build 19045)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
Your code sample will not yield the error in your title. The result of the code sample is not abnormal with your output.

Unless you can clarify what is wrong, there is no information to do anything further.

**Comment by TheHellTower** [comment]
> Your code sample will not yield the error in your title. The result of the code sample is not abnormal with your output.
> 
> Unless you can clarify what is wrong, there is no information to do anything further.

Yeah sorry for some reasons when I was not using directly the emoji to delete it but doing it by `<message>.guild.emojis.delete` when the emoji was resolved I had the possibility to get the name and ID but not to delete it, sorry for this useless issue.
