### ISSUE TITLE
RoleSelectMenuBuilder is not working on mobile

### ISSUE THREAD

**Issue by Thorvarium** [discordjs/discord.js#9115]
### Which package is this bug report for?

discord.js

### Issue description

I am sending a RoleSelectMenuBuilder in a message and while it does let the user search and chose a role on desktop client it stopped working on android and IOS in the past few days.
On the mobile apps it just show a list with a few roles (15 to be exact) and does not let the person search.
The position where the search box was previously now is a label.

### Package version

14.7.1

### Node.js version

18.9

### Operating system

Ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
discord.js is an API wrapper—we are not Discord, which your bug report appears to be for.
