### ISSUE TITLE
Banner never retrieved

### ISSUE THREAD

**Issue by TheHellTower** [discordjs/discord.js#9117]
### Which package is this bug report for?

discord.js

### Issue description

Just need to fetch the user .

[japi.rest can retrieve it](https://japi.rest/discord/v1/user/1049676795399647334) but when I use discord.js to fetch the user it's always undefined

### Code sample

```typescript
Explained in issue description
```

### Package version

14.7.1

### Node.js version

19.1.0

### Operating system

Windows 10 22H2 (Build 19045)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
> Explained in issue description

This is not good enough. We need to know what you have been doing. Providing us with a needle in a haystack is as useful as not creating the issue.

**Comment by TheHellTower** [comment]
> > Explained in issue description
> 
> This is not good enough. We need to know what you have been doing. Providing us with a needle in a haystack is as useful as not creating the issue.

I only fetched my user and someone else user using `<client>.users.fetch(<User ID>)` and got the [User](https://discord.js.org/#/docs/discord.js/main/class/User) but banner was always undefined for some reasons even thought one of the account already had a banner for a while.

**Comment by Syjalo** [comment]
You need to force fetch the user.
```js
await client.users.fetch('id', { force: true });
// or
await user.fetch()
```

**Comment by TheHellTower** [comment]
> You need to force fetch the user.
> 
> ```js
> await client.users.fetch('id', { force: true });
> // or
> await user.fetch()
> ```

![](https://i.imgur.com/F6hSnti.png) 👍

**Comment by Syjalo** [comment]
The provided code doesn't show how do you log the user

**Comment by TheHellTower** [comment]
> The provided code doesn't show how do you log the user



> The provided code doesn't show how do you log the user

What do you mean ? I didn't create `console.log` and I don't know many other functions for it 🤔

**Comment by Syjalo** [comment]
So you have `console.log` somewhere else. This issue tracker is only for bug reports and enhancement suggestions. If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) for discord.js related questions.

**Comment by TheHellTower** [comment]
> So you have `console.log` somewhere else. This issue tracker is only for bug reports and enhancement suggestions. If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) for discord.js related questions.

The `console.log` is just after the fetch I just said that I didn't invent `console.log` or any other function to print in console, I even added a `console.log` showing object keys and values in [User Structure](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/User.js#L14) to see the data that was received and the banner was not there too so I assume it's a discord.js issue. So it's a bug report.

**Comment by TheHellTower** [comment]
The exact values list I get:
![](https://i.imgur.com/Y5AmHHp.png)

**Comment by SpaceEEC** [comment]
I'm unable to reproduce this.
Please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this.

**Comment by TheHellTower** [comment]
> I'm unable to reproduce this. Please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this.

No problem I will send it in the day

**Comment by jaw0r3k** [comment]
> You need to force fetch the user.
> 
> ```js
> await client.users.fetch('id', { force: true });
> // or
> await user.fetch()
> ```

actually you are wrong
fetch takes one param
```js
await client.users.fetch({ user: 'id', force: true });
```

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/blob/0e4224be36f6e64ccd8366f6cc86e6ce3f33eec5/packages/discord.js/src/managers/UserManager.js#L78-L84
