### ISSUE TITLE
A property function is not exist

### ISSUE THREAD

**Issue by tectoniumhub** [discordjs/discord.js#9125]
### Which package is this bug report for?

discord.js

### Issue description

Dear Developers,

I probleming in my project. Actually I tried to make echo command with **discord.js** module with **TypeScript** but when run my project the output say that "getString()" is not Exist in `interaction.options` but it was working on JavaScript version but it is not working on my **TypeScript** project. So, I hope you will add "getString()" function to fix this problem

### Code sample

```typescript
import Discord from "discord.js";
import { Command } from "../../Structures/Command";

export default new Command({
  name: "say",
  description: "description",
  options: [
    {
      name: "input",
      description: "value of prompt",
      type: 3,
      required: true
    }
  ],
  run: async function({ interaction }) {
    let field = interaction.options.getString("input");
    await interaction.reply({ content: `${field}` });
  }
});
```

### Package version

"discord.js": "^14.7.1"

### Node.js version

Node.JS version: 18.12.1

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by Syjalo** [comment]
Slash command interaction type is `ChatInputCommandInteraction`. `CommandInteraction` is for any type of commands.

**Comment by tectoniumhub** [comment]
> Slash command interaction type is `ChatInputCommandInteraction`. `CommandInteraction` is for any type of commands.

Did you I should use `ChatInputCommandInteraction` to solve this error?
