### ISSUE TITLE
GuildDelete Spam

### ISSUE THREAD

**Issue by Etoiledefeu** [discordjs/discord.js#9128]
### Which package is this bug report for?

discord.js

### Issue description

My bot is on an "unavailable" Guild, and each time it restarts, an "undefied" GuildDelete event was emitted.
Even though it slows the startup by 15 seconds, the real problem is that every now and then the GuildDelete undefiened event gets spammed (sometimes 30 in 5 minutes), and the bot disconnects and reconnects each time. There are no error logs on the console.
The only information I can get from this Guild is its id (before it became unavailable or via websocket). 
I added a line ```if(guild.unavailable) return console.log("GuildDelete undefied"``` in my GuildDelete évent to avoid this ![Screenshot_2023-01-28-10-13-52-165](https://user-images.githubusercontent.com/108147303/218455693-4e0dda13-9539-4964-ae95-dc971e683ddd.jpg)
but the bug continues.

### Package version

14.7.1

### Node.js version

Nodejs v 18.4.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, MessageContent

### I have tested this issue on a development release

No

**Comment by Syjalo** [comment]
Discord sends unavailable guilds in guildDelete. To filter check if the guild exist in the guilds cache. Unavailable guilds are in the cache, but removed aren't.

**Comment by Jiralite** [comment]
> I added a line `if(guild.unavailable) return console.log("GuildDelete undefied"` in my GuildDelete évent to avoid this but the bug continues.

It is [`Guild#available`](https://discord.js.org/#/docs/discord.js/14.7.1/class/Guild?scrollTo=available).

**Comment by Etoiledefeu** [comment]
> Discord sends unavailable guilds in guildDelete. To filter check if the guild exist in the guilds cache. Unavailable guilds are in the cache, but removed aren't.

Okay so there is just to modify the cache parameters of the client ?

**Comment by Syjalo** [comment]
You shouldn't modify caches. Just check if the guild is in the cache.
If it is, then the guild just unavailable.
Else the bot was removed from the guild.

**Comment by Etoiledefeu** [comment]
> You shouldn't modify caches. Just check if the guild is in the cache.
> If it is, then the guild just unavailable.
> Else the bot was removed from the guild.

Okay thanks !
I checked and no, the server does not seem to be in the cache. The only information I can get is its id with client.ws.on("GUILD_DELETE") console.log(guild).
This means that the bot has already left the server ?
