### ISSUE TITLE
Return type of ChannelManager.fetch is not correct

### ISSUE THREAD

**Issue by daniellwdb** [discordjs/discord.js#9129]
### Which package is this bug report for?

discord.js

### Issue description

`ChannelManager#fetch` has return type `Promise<Channel | null>` when it throws when fetching fails. This is not the case for `GuildManager#fetch` which does return `Promise<Guild>`

### Code sample

```typescript
import type { ChannelManager } from "discord.js"

declare const channelManager: ChannelManager

await channelManager.fetch() // Promise<Channel | null>
```

### Package version

14.7.1

### Node.js version

v18.12.1

### Operating system

Ubuntu

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/pull/8515#issuecomment-1218577301
