### ISSUE TITLE
PNPM causes an error when using GatewayIntentBits

### ISSUE THREAD

**Issue by tticehurst** [discordjs/discord.js#9130]
### Which package is this bug report for?

discord.js

### Issue description

Using latest version of raspbian and installing the discord.js package with npm I run into this issue. This does not happen with npm or yarn, or with pnpm on a Windows based environment.

![image](https://user-images.githubusercontent.com/46826453/218534476-505f43e9-e156-4ad7-bbc6-7ba475825ef7.png)

Steps to recreate
* Install `discord.js`, `typescript`, and `@types/node`
* Create an index.ts file with the lines in the image
* Error occurs

### Package version

14.7.1

### Node.js version

18.2.1

### Operating system

Raspbian

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
What happens when you compile with TypeScript?

**Comment by tticehurst** [comment]
I can't as it's an error it will not allow me to compile. However, I am assuming that it would run as normal as it turns into javascript without typechecking. I looked through the files to compare those downloaded with `npm` and `pnpm` and they appear to be the same.

**Comment by Jiralite** [comment]
> I can't as it's an error it will not allow me to compile. However, I am assuming that it would run as normal as it turns into javascript without typechecking

Are you saying you haven't tried?

I'm trying to see if it's only a problem with the IDE, which I suspect this is.

**Comment by tticehurst** [comment]
I have tried. But due to the tsconfig I'm using it will not compile due to an error being there. The text editor I'm using is VSC.

**Comment by tticehurst** [comment]
With a few modifications to my tsconfig I was able to create a build. I have attached a screenshot with the build file as well as the output of printing `GatewayIntentBits` to the console.

![image](https://user-images.githubusercontent.com/46826453/218543285-536831e4-80fa-437e-a69d-45be196fc457.png)
![image](https://user-images.githubusercontent.com/46826453/218543308-530fef17-0693-4f62-a58f-9e9b244b9ebd.png)

**Comment by tticehurst** [comment]
Manually installing this package seems to resolve the issue 
![image](https://user-images.githubusercontent.com/46826453/218544568-5ee67ed5-1033-47be-9c01-07949602b491.png)

**Comment by Jiralite** [comment]
Ultimately, it's not an issue with discord.js. It appears to be somewhat of an installation issue with TypeScript as it does not understand where re-exported types come from.

**Comment by tticehurst** [comment]
I'm assuming it's more an issue with pnpm due the way it uses links rather than actual folders for package installs. It may not know to import the types due to some reason.

**Comment by tticehurst** [comment]
I did, yes. Without installing that package the issue remains.

**Comment by Jiralite** [comment]
> I'm assuming it's more an issue with pnpm due the way it uses links rather than actual folders for package installs. It may not know to import the types due to some reason.

This looks like a compatibility issue somewhat with the OS. pnpm seems to work fine on Windows and macOS at the least from what I (and you) can test. I'm doubtful discord.js can do anything to fix this. I don't believe we are doing anything strange—it's a simple type export. If we are, we can resolve it, but I'm pretty confident this is out of our hands.
