### ISSUE TITLE
Wrong name of VoiceState property

### ISSUE THREAD

**Issue by PolishKebab** [discordjs/discord.js#9133]
### Which package is this bug report for?

discord.js

### Issue description

VoiceState.suppress sounds more like a function that suppresses a user, not returns bool value of whether the user is suppressed.

### Code sample

```typescript
- VoiceState.suppress
+ VoiceState.suppressed
```

### Package version

discord.js@14.6.0

### Node.js version

v18.7.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages

**Comment by almostSouji** [comment]
This follows API spec (as we usually do with field names)
