### ISSUE TITLE
TS: isTextBased() includes StageChannel

### ISSUE THREAD

**Issue by gausie** [discordjs/discord.js#9141]
### Which package is this bug report for?

discord.js

### Issue description

Code will fail because `isTextBased()` includes `StageChannel` but such channel types do not have `messages`, `send()` etc.

In the discord.js code the check is just looking for the existence of the `messages` key, so it's just that the typings are wrong.

https://github.com/discordjs/discord.js/blob/8a8d519c9c4c082370fc6935b56dafb525b873df/packages/discord.js/src/structures/BaseChannel.js#L130-L132

### Code sample

```typescript
function getChannelMessages(channel: Channel) {
  if (!channel.isTextBased()) return null;
  return channel.messages}
}
```

### Package version

14.7.1

### Node.js version

18.6.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Please see our [FAQ](https://discord.com/channels/222078108977594368/769862166131245066/1076213839990894604) on our [Discord server](https://discord.gg/djs)!

**Comment by Jiralite** [comment]
Since this is already fixed in main and a workaround exists (pinning discord-api-types) for stable versions, this'll be closed.
