### ISSUE TITLE
Typescript typings contains error

### ISSUE THREAD

**Issue by wraeth-eth** [discordjs/discord.js#9147]
### Which package is this bug report for?

discord.js

### Issue description

When importing discord.js in a typescript package, an error is thrown on compile:
```
node_modules/discord.js/typings/index.d.ts:37:8 - error TS1005: ',' expected.

37   type RestOrArray,
          ~~~~~~~~~~~


Found 1 error.
````

Upon examination, the index.d.ts contains this:
```
...
  type RestOrArray,
} from '@discordjs/builders';
```

Removing the `type` word fixes the compile issue

### Package version

14.7.1

### Node.js version

node v19.6.1 & typescript@4.4.3

### Operating system

macos

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

discord.js@14.8.0-dev.1676765484-c6f9c50.0

**Comment by imranbarbhuiya** [comment]
Uodate your typescript

**Comment by almeidx** [comment]
TypeScript 4.5 added support for type modifiers
