### ISSUE TITLE
Search box is malfunctioning

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#9149]
Interacting with the search bar yields no response. When summoned via <kbd>⌘</kbd> + <kbd>K</kbd> or <kbd>CTRL</kbd> + <kbd>K</kbd> and searching, the following error appears:

```xl
Uncaught (in promise) MeiliSearchApiError: Index `core-main` not found.
    at 5223-c93363d05ea080a3.js:1:15363
    at 5223-c93363d05ea080a3.js:1:13967
    at Object.next (5223-c93363d05ea080a3.js:1:14072)
    at u (5223-c93363d05ea080a3.js:1:12819)
```

**Comment by jaw0r3k** [comment]
to clarify it isnt working only on core, formatters and brokers so more likely newer packages

**Comment by Jiralite** [comment]
Resolved with the recent website commits.
