### ISSUE TITLE
MessageCreate.js crashes when text message is posted to a voice channel

### ISSUE THREAD

**Issue by KeiroD** [discordjs/discord.js#9152]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce: Post a message, any message, in a voice channel's associated text channel. It will immediately crash with something similar to the following:

```
2023-02-20T05:28:58.866Z warn: Received warn event from Discord Discord sent a typing packet to a voice channel 848707213451067392
/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at module.exports [as MESSAGE_CREATE] (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/usr/lib/node_modules/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/usr/lib/node_modules/discord-irc/node_modules/ws/lib/receiver.js:517:14)
```
Node.js v18.14.0 is in use on this server.

The version of `Discord.js` doesn't appear to matter, as checking directly against this repo's version of `MessageCreate.js` [here](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/client/actions/MessageCreate.js) still reproduces the issue, but here's the versions in use:

```
agnphbot@irc:~$ npm list discord.js
agnphbot@ /home/agnphbot
├─┬ discord-irc@2.9.0
│ └── discord.js@12.3.1
└── discord.js@14.7.1
```

Let me know if there's anything else you need to know. This is on Ubuntu Server 22.04, fwiw. I also checked to see if there were similar issues posted here, but I'm not entirely sure if there was one, I may have missed it, and if so, my apologies.

I'm also not a developer but I'll do my best to help with tracking down what's happening. Also, not entirely sure what options are applicable for this issue so, apologies for that.

### Package version

14.7.1

### Node.js version

18.14.0

### Operating system

Ubuntu 22.04

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Syjalo** [comment]
Not related to discord.js. discord-irc just use a deprecated version of discord.js.

**Comment by KeiroD** [comment]
> Not related to discord.js. discord-irc just use a deprecated version of discord.js.

Far as I can tell, I'm using the latest version of discord.js. If that's not correct, wouldn't installing via `npm install discord.js` install the latest version? That's what I did, and it's still reproducible via that.

**Comment by Syjalo** [comment]
You do, but discord-irc don't

**Comment by KeiroD** [comment]
> You do, but discord-irc doesn't

Understood, and that's fair. However, I don't think `discord-irc` using an outdated version of `discord.js` matters if it's still reproduced even with the latest version of `discord.js`, but that's my personal opinion, as the error fairly clearly points to `discord.js` throwing the error and not `discord-irc` itself.

Would this be correctable using the voice part of the discord.js library?

**Comment by Syjalo** [comment]
It's reproduced by using a deprecated version of discord.js in the discord-irc code. The version you're using in your code (specified in your package.json) can and isn't the same with the one of discord-irc (specified in [package.json](https://github.com/reactiflux/discord-irc/blob/b2e75985543cac7c445f01990a88c5f86ce90adc/package.json#L40) of discord-irc)

**Comment by monbrey** [comment]
The version of discord.js absolutely does matter here, there's no getting around that. Installing multiple version into your project will not fix this. Trying to make discord-irc use v14 will just break it in other ways.

No, it's not related to the voice part of the library.

v12 is well past being supported, and message support for text channels is only in v13 and v14.

Your only option is to find a newer version of discord-irc that uses at least v13, or a different dependency entirely.

**Comment by KeiroD** [comment]
Thanks for clarifying where exactly the issue is, @Syjalo and @monbrey. Appreciate it!
