### ISSUE TITLE
BaseInteraction checking this.commnadType

### ISSUE THREAD

**Issue by BoryaGames** [discordjs/discord.js#9161]
### Which package is this bug report for?

discord.js

### Issue description

`<BaseInteraction>.isChatInputCommand()` checking this.commandType, which is not present.

### Package version

14.7.1

### Node.js version

18.12.1

### Operating system

Linux Ubuntu

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

4e0e125

**Comment by Jiralite** [comment]
This is not a bug. It's for use in extended classes.
