### ISSUE TITLE
executor.bot shows `null` in auditLogEntry

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#9163]
### Which package is this bug report for?

discord.js

### Issue description

1) Make sure _guildAuditLogEntryCreate_ event is emitting.
3) console.log(auditLogEntry);
2) Start bot and have a bot give/remove role from a user.
3) Notice that executor.bot shows `null` instead of `true`

<img width="197" alt="djs" src="https://user-images.githubusercontent.com/54294685/220872402-37fe4285-a9fb-4ff5-985c-4432a474a502.png">

### Package version

13.13.1

### Node.js version

V18 (LTS)

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages

**Comment by Jiralite** [comment]
This is obviously a partial user. It is not possible to tell if a user id is a bot. Either remove your `USER` partial or fetch the user using `executorId`.

**Comment by Syjalo** [comment]
> This is obviously a partial user. It is not possible to tell if a user id is a bot. Either remove your `USER` partial or fetch the user using `executorId`.

`guildAuditLogEntryCreate` doesn't handle partials
https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/client/actions/GuildAuditLogEntryCreate.js

**Comment by Jiralite** [comment]
Partial handling wouldn't happen in that file but in the class itself.
