### ISSUE TITLE
Empty `message.content` only for system messages

### ISSUE THREAD

**Issue by haversnail** [discordjs/discord.js#9166]
### Which package is this bug report for?

discord.js

### Issue description

Even with the correct app settings and gateway intents/partials, the `message.content` field is empty for system messages, such as when a new user joins.

Steps to reproduce:
1. Create a client with the correct gateway intent bits (and Message Content app settings enabled)
2. Subscribe to the `MessageCreate` event and log any messages to the console
3. Trigger a system event (e.g. a new user joins: *"Welcome, __So-and-so__. We hope you brought pizza."*)
4. Assert that the `message.content` field is empty.
5. Send a regular message.
6. Assert that the `message.content` field is populated.
 

### Code sample

```typescript
import * as Discord from "discord.js";

const client = new Discord.Client({
  intents: [
    // see below - and yes, these are enabled in my app settings ;)
  ],
  partials: [
    // see below
  ],
});

client.on(Discord.Events.MessageCreate, (message) => {
  console.log(message);
});

// For system messages, the following is logged:
//
// <ref *1> Message {
//   channelId: '...',
//   guildId: '...',
//   id: '...',
//   createdTimestamp: 1677201700748,
//   type: 7,
//   system: true, // <---
//   content: '', // <---
//   author: User {
//     // ...
//   },
//   pinned: false,
//   tts: false,
//   nonce: null,
//   embeds: [],
//   components: [],
//   attachments: Collection(0) [Map] {},
//   stickers: Collection(0) [Map] {},
//   position: null,
//   editedTimestamp: null,
//   reactions: ReactionManager { message: [Circular *1] },
//   mentions: MessageMentions {
//     everyone: false,
//     users: Collection(0) [Map] {},
//     roles: Collection(0) [Map] {},
//     _members: null,
//     _channels: null,
//     _parsedUsers: null,
//     crosspostedChannels: Collection(0) [Map] {},
//     repliedUser: null
//   },
//   webhookId: null,
//   groupActivityApplication: null,
//   applicationId: null,
//   activity: null,
//   flags: MessageFlagsBitField { bitfield: 0 },
//   reference: null,
//   interaction: null
// }
```

### Package version

discord.js@14.7.1

### Node.js version

v18.14.2 (typescript@4.9.5)

### Operating system

Docker image (node:18)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
This is not a bug. There is no content sent.

**Comment by haversnail** [comment]
@Jiralite can you provide any clarification here? Is this in the Discord API docs somewhere?

**Comment by Jiralite** [comment]
The best way to get clarification is to test this yourself (which is ideally what should have happened first).

Monitor the raw data you receive. For example, receiving a `MESSAGE_CREATE` event with the message type this issue is about yields this:

```JavaScript
{
  t: 'MESSAGE_CREATE',
  s: 8,
  op: 0,
  d: {
    type: 7,
    tts: false,
    timestamp: '2023-02-24T01:54:04.054000+00:00',
    pinned: false,
    mentions: [],
    mention_roles: [],
    mention_everyone: false,
    member: {
      roles: [],
      premium_since: null,
      pending: false,
      nick: null,
      mute: false,
      joined_at: '2023-02-24T01:54:03.986908+00:00',
      flags: 1,
      deaf: false,
      communication_disabled_until: null,
      avatar: null
    },
    id: '1078494994068934787',
    flags: 0,
    embeds: [],
    edited_timestamp: null,
    content: '',
    components: [],
    channel_id: '886323825535496262',
    author: {
      username: '[redacted]',
      public_flags: 0,
      id: '[redacted]',
      display_name: null,
      discriminator: '[redacted]',
      avatar_decoration: null,
      avatar: '[redacted]'
    },
    attachments: [],
    guild_id: '886323824801488996'
  }
}
```

The message content received here is an empty string, so that is why you receive an empty string.

**Comment by haversnail** [comment]
> The best way to get clarification is to test this yourself (which is ideally what should have happened first).

Thanks for the info. No need to get spicy. 🌶️
