### ISSUE TITLE
Broken Webhook Names

### ISSUE THREAD

**Issue by plumpx** [discordjs/discord.js#9169]
### Which package is this bug report for?

discord.js

### Issue description

1. Create a web hook.
2. Send a message as that web hook make sure you define a username "John"
3. Send another message as the same web hook make sure you define the username "Smith"

The "John" message will be renamed to "Smith" and there will be 2 web hook messages from "Smith".
The profile pictures do not change just the usernames.

### Code sample

```typescript
No code required to test/reproduce.
```

### Package version

14.6.0

### Node.js version

18.13.0

### Operating system

Linux Ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by almostSouji** [comment]
Upstream Discord issue; nothing we can fix
