### ISSUE TITLE
Issue with embeds and forum posts

### ISSUE THREAD

**Issue by 1PV1** [discordjs/discord.js#9170]
### Which package is this bug report for?

discord.js

### Issue description

I'm not sure if this is a bug but it looks like it.

I have a command that creates a thread in a forum channel, then sends a message in that thread:
```js
const post = await channel.threads.create({
  name: `Loteria #1`,
  appliedTags: ['1076183494088200222'],
  message: { embeds: [embed], components: [row] }
});
const embed2 = new EmbedBuilder().setColor('#4f545c').setTitle(`Membri înscriși (0/5):`);
const row2 = new ActionRowBuilder().setComponents(new ButtonBuilder().setCustomId('lottery').setStyle('Secondary').setLabel('Înscrie-te').setEmoji('💰'));
post.send({ embeds: [embed2], components: [row2] });
```
The button from `row2` just shows a modal and after that modal is submitted the following code is runned (besides the other code I have):
```js
// My initial code was the one commented but I thought about testing it this way

// const embed2 = interaction.message.embeds[0];
const embed2 = EmbedBuilder.from(interaction.message.embeds[0].data);
if (!embed2.data.fields) {
  // embed2.data.fields = [{ name: '\u200b', value: `\`[${interaction.user.id}]\` ${name_mc}`, inline: false }];
  embed2.setFields({ name: '\u200b', value: `\`[${interaction.user.id}]\` ${name_mc}` })
} else if (embed2.data.fields.pop().value.split('\n').length < 20) {
  console.log(embed2.data.fields) // returns []
  embed2.data.fields.pop().value = embed2.data.fields.pop().value + `\n\`[${interaction.user.id}]\` ${name_mc}`;
} else {
  embed2.data.fields.push({ name: '\u200b', value: `\`[${interaction.user.id}]\` ${name_mc}`, inline: false });
};
interaction.message.edit({ embeds: [embed2], components: interaction.message.components });
```

### Just so you can understand the code better:

The last code I provided should check the following:
- if the embed doesn't have a field it will add a field with that user (`name_mc` is just what the user writes in the modal)
- if the embed already has a field and the last one doesn't have 20 users it will add the user to that field
- if the embed already has a field and the last one has 20 users, it will just make another field with that user

The format that is gonna be in the fields is like this:
`[449283723918311424]` My_Name
`[000000000000000000]` Someones_Name
and so on...

The issue is that the second time I press the button (with another user), `embed2.data.fields` is just an empty array (still, on discord I can clearly see the field)

### Package version

^14.7.1

### Node.js version

18.13.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, DirectMessages, MessageContent

**Comment by jaw0r3k** [comment]
Not releated to development of djs, please go to [djs support server](https://discord.gg/djs)

**Comment by 1PV1** [comment]
How is it not related.. on discord I can see the field but when I log the embed, `fields` is just an empty array, and I did ask on the discord server but nobody gave me an answear.

**Comment by Jiralite** [comment]
You mutate your embed in the `if` check. This is not a discord.js bug.
