### ISSUE TITLE
Enforcing Order of Options in Slash Commands

### ISSUE THREAD

**Issue by NuroC** [discordjs/discord.js#9181]
### Which package is this feature request for?

discord.js

### Feature

The current implementation of a slash command allows users to choose options in any order, even if my code requires each options value depending on the previously selected option. A new feature is requested to enforce the order of options, even if they are not required.

### Ideal solution or implementation

The ideal solution would be to provide an option to set the order of the options explicitly. This could be done by adding an "order" property to each option object, which would specify the position of the option in the command. This way, when the user enters the command, the options would be presented in the specified order.

### Alternative solutions or implementations

An alternative solution would be to use a custom validation function to enforce the order of the options. This function would check that each option's name is in the correct position and return an error message if it is not. However, this solution may not be ideal as it requires additional development effort and may be more prone to errors.

### Other context

No other context or file uploads were provided.

**Comment by monbrey** [comment]
We cannot provide any functionality that isn't in the API. You'll have to request this from Discord.

**Comment by NuroC** [comment]
Alright, thanks.  Where do I write a feature request to discord?

**Comment by Syjalo** [comment]
https://github.com/discord/discord-api-docs/discussions/new/choose

**Comment by NuroC** [comment]
Alright, thanks. Have a good day
