### ISSUE TITLE
Missing typing on ModalSubmitInteraction

### ISSUE THREAD

**Issue by Larsundso** [discordjs/discord.js#9186]
### Which package is this bug report for?

discord.js

### Issue description

`ModalSubmitInteraction` is missing Typing for method `update()` 

### Package version

14.7.1

### Node.js version

17.8.0

### Operating system

Ubuntu 20.04

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

dc142c4.0

**Comment by Jiralite** [comment]
It would be incorrect to place it on `ModalSubmitInteraction`. Use the `isFromMessage()` type guard.

**Comment by Larsundso** [comment]
> It would be incorrect to place it on `ModalSubmitInteraction`. Use the `isFromMessage()` type guard.

ah thank you, sorry for the false report then

**Comment by Jiralite** [comment]
No worries. To elaborate further, modal submit interactions can be received from non-component messages (not from a message), so it would be an incorrect assumption of TypeScript to allow `update()`. The type guard assures it's from a message, allowing the method to be present.
