### ISSUE TITLE
guildMemberUpdate | Role cache not working...

### ISSUE THREAD

**Issue by tim-it-ger** [discordjs/discord.js#9190]
### Which package is this bug report for?

discord.js

### Issue description

1. i needed a bot, to log adding and removing guild member roles.
2. i started coding
3. after i tested the function, its not working.
4. tried 3 types of codes but every code do not work.
5. tried on development version but anyways the code not working for me.

### Code sample

```typescript
first code:

client.on('guildMemberUpdate', (oldMember, newMember) => {
    const oldRoles = oldMember.roles.cache;
    const newRoles = newMember.roles.cache;
  
    const addedRoles = newRoles.filter(role => !oldRoles.has(role.id));
    const removedRoles = oldRoles.filter(role => !newRoles.has(role.id));
  
    if (addedRoles.size > 0 || removedRoles.size > 0) {
      console.log('Roles updated!')
    }
 });

second code:

client.on('guildMemberUpdate', (oldMember, newMember) => {
    if (!oldMember.roles.cache.equals(newMember.roles.cache)) {
        console.log("Roles updated!")
    }
});

third code:

client.on('guildMemberUpdate', (oldMember, newMember) => {
  if (oldMember.roles.cache !== newMember.roles.cache) {
        console.log("Roles updated!")
  }
});
```

### Package version

14.7.1

### Node.js version

v18.12.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, GuildMember, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, MessageContent

### I have tested this issue on a development release

dc142c4.0

**Comment by tim-it-ger** [comment]
There is only a Log by removing a Role*

but by adding a role, there is no reaction.

**Comment by jaw0r3k** [comment]
maybe it's partials fault
may you log old member?

**Comment by tim-it-ger** [comment]
there is no reaction if i add a role.
i tried some changes on the code, and fixed it already...

sry.
