### ISSUE TITLE
Implementation of Jitter in Heartbeat Interval is missing

### ISSUE THREAD

**Issue by DarkyEG** [discordjs/discord.js#9197]
### Which package is this bug report for?

ws

### Issue description

In the Discord API documentation for [Heartbeat Interval](https://discord.com/developers/docs/topics/gateway#heartbeat-interval), it is recommended that an application should wait for a random value between 0 and 1 multiplied by the `heartbeat_interval` before sending the next heartbeat signal. This random value is called "jitter". However, the implementation of this `jitter` is missing and needs to be added to the application's code.

### Package version

13.13.1

### Node.js version

Node.js 18.14.2

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by vladfrangu** [comment]
Technically, this is only needed for the first heartbeat the application sends from the moment a connection is sent. That said, not sending it is not an issue (or should not be one at least) since you can assume our jitter is hardcoded as `1`. Nevertheless @didinele this is on your terrain

**Comment by DarkyEG** [comment]
> Technically, this is only needed for the first heartbeat the application sends from the moment a connection is sent. That said, not sending it is not an issue (or should not be one at least) since you can assume our jitter is hardcoded as `1`. Nevertheless @didinele this is on your terrain

The purpose of this is to avoid sending all heartbeats at the same time. Therefore, if the Jitter is set to 1, the heartbeats will be sent at the same time, which is not recommended.

**Comment by DarkyEG** [comment]
> Technically, this is only needed for the first heartbeat the application sends from the moment a connection is sent. That said, not sending it is not an issue (or should not be one at least) since you can assume our jitter is hardcoded as `1`. Nevertheless @didinele this is on your terrain

I thought it was necessary to include the Jitter in every send.

Well, it may be better to include the Jitter in every send, as it can help if there is poor network connectivity and there is delay in sending the heartbeat.

**Comment by didinele** [comment]
Yeah seems like we should probably implement this for the first heartbeat. Will get to it sometime this coming week.

**Comment by didinele** [comment]
Pretty much as Vlad pointed out, our jitter is basically hardcoded to 1 at the moment, will refactor this to be more in-line with docs.
