### ISSUE TITLE
Bot Automatically becomes offline after 10mins

### ISSUE THREAD

**Issue by SaumilAgrawal** [discordjs/discord.js#9198]
### Which package is this bug report for?

discord.js

### Issue description

The bot automatically turns off after 10mins, I am running client.login() on cloud still the problem persists

### Package version

14.7.1

### Node.js version

16.16.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Qjuh** [comment]
Where do you host that bot? Could it be that the host simply doesn't support maintaining a WebSocket connection indefinitely?

**Comment by Miho1254** [comment]
i think this is OS problem, can you describe more infos about ur hosting?

**Comment by SaumilAgrawal** [comment]
I solved the issue, it was a issue on my hoster's side
