### ISSUE TITLE
`MessageReplyOptions` references non-existent type definition `BaseMessageCreateOptions`

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#9209]
### Which package is this bug report for?

discord.js

### Issue description

As seen over at [`MessageReplyOptions`](https://discord.js.org/#/docs/discord.js/main/typedef/MessageReplyOptions), this lists `BaseMessageCreateOptions` which does not appear to have a link to anything.

### Package version

N/A

### Node.js version

N/A

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

4367ab930227048868db3ed8437f6c4507ff32e1

**Comment by Sheikh-JamirAlam** [comment]
Is it supposed to be `BaseMessageOptions` ?

**Comment by Qjuh** [comment]
It is, yes.
