### ISSUE TITLE
No fetchWebhooks() on thread channel

### ISSUE THREAD

**Issue by Tweentyy** [discordjs/discord.js#9231]
### Which package is this bug report for?

discord.js

### Issue description

We cannot fetch webhooks from a Thread channel

### Code sample

```typescript
const channel = await message.guild.channels.create({
    name: "channel",
    type: ChannelType.GuildText
});
channel.threads.create({ name: "test" })
    .then((ch) => console.log(ch.fetchWebhooks()))
```

### Package version

14.8.0

### Node.js version

v18.12.1

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildMessages, GuildMessageReactions, MessageContent, AutoModerationConfiguration

**Comment by vladfrangu** [comment]
Threads themselves cannot have webhooks, their parent channel can! 👀

**Comment by Tweentyy** [comment]
Oh okaaay !! Thanks (:
