### ISSUE TITLE
interaction.client.commands.get doesn't exist for typescript

### ISSUE THREAD

**Issue by kiskesis** [discordjs/discord.js#9233]
### Which package is this bug report for?

discord.js

### Issue description

In the [guide](https://discordjs.guide/creating-your-bot/command-handling.html#executing-commands) we have an example:
`const command = interaction.client.commands.get(interaction.commandName);`

But when you try to use it you receive an error from typescript:
`error TS2339: Property 'commands' does not exist on type 'Client<true>'`

So as written [here](https://stackoverflow.com/questions/69500556/discord-js-guide-property-commands-does-not-exist-on-type-clientboolean) we just should extend Client class like that

`declare module "discord.js" {
  export interface Client {
    commands: Collection<unknown, any>
  }
}
`

### Code sample

```typescript
const command = interaction.client.commands.get(interaction.commandName);
```

### Package version

14.8.0

### Node.js version

18.13.0

### Operating system

MacOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by SuperchupuDev** [comment]
the guide mentions what to do in this case for typescript users

![image](https://user-images.githubusercontent.com/53496941/225078153-d5169807-6c3e-4974-b017-c9ed0958bc0c.png)

**Comment by kiskesis** [comment]
> the guide mentions what to do in this case for typescript users
> 
> ![image](https://user-images.githubusercontent.com/53496941/225078153-d5169807-6c3e-4974-b017-c9ed0958bc0c.png)

true, closing
