### ISSUE TITLE
Bot died out of nowhere

### ISSUE THREAD

**Issue by Mykiz136** [discordjs/discord.js#9258]
### Which package is this bug report for?

voice

### Issue description

Discord bot hosted roughly 24/7 always worked, yesterday after a reboot (no update had occured during said reboot) gives out this error:

21.03 08:57:48 [Bot] Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
21.03 08:57:48 [Bot] at VoiceConnection.authenticateFailed (/node_modules/discord.js/src/client/voice/VoiceConnection.js:303:26)
21.03 08:57:48 [Bot] at /node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
21.03 08:57:48 [Bot] at Timeout.<anonymous> (/node_modules/discord.js/src/client/BaseClient.js:83:7)
21.03 08:57:48 [Bot] at listOnTimeout (node:internal/timers:559:17)
21.03 08:57:48 [Bot] at processTimers (node:internal/timers:502:7) {
21.03 08:57:48 [Bot] [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
21.03 08:57:48 [Bot] }

The bot seems to join the vc but doesn't play anything (it's a music bot) and after 15 seconds it quits with this error on console.
PLEASE help, the problem now occurs both locally hosted and off-site.
I'm desperate! (The code DID NOT change, NOTHING changhed so wtf...?)

### Package version

`-- discord.js@12.5.3

### Node.js version

v18.14.0

### Operating system

doesn't matter (WIN 11 local)

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by vladfrangu** [comment]
Unfortunately, this is not something we can help you with. discord.js v12 has been deprecated for a *long while* now, and is not maintained anymore. Your best bet is to upgrade your bot to v13 (or v14 if you're daring of jumping two major versions) and also moving your voice setup to use our new voice module, `@discordjs/voice`. 

Also, even if it worked before, it not working now is more-so a fact that Discord did lots of changes in voice since then

**Comment by Mykiz136** [comment]
> Unfortunately, this is not something we can help you with. discord.js v12 has been deprecated for a _long while_ now, and is not maintained anymore. Your best bet is to upgrade your bot to v13 (or v14 if you're daring of jumping two major versions) and also moving your voice setup to use our new voice module, `@discordjs/voice`.
> 
> Also, even if it worked before, it not working now is more-so a fact that Discord did lots of changes in voice since then.
> 
> While I'm going to be closing this now, if you upgrade your bot and still encounter voice issues in the new system, feel free to follow-up here, or in a new issue




I am using the voice package

**Comment by Jiralite** [comment]
discord.js version 12 does not use the voice package and your stack trace does not point to it either.

**Comment by Mykiz136** [comment]
> discord.js version 12 does not use the voice package and your stack trace does not point to it either.

How do I switch to the new version?
Do I need to rewrite it entirely? (It's a huuuuuuuge project, it would be almost impossible to rewrite it, even partially + I'm not that good :(  )

**Comment by Qjuh** [comment]
https://v13.discordjs.guide/additional-info/changes-in-v13.html is the update guide for v12->v13.

**Comment by BenEight8** [comment]
> > discord.js version 12 does not use the voice package and your stack trace does not point to it either.
> 
> How do I switch to the new version? Do I need to rewrite it entirely? (It's a huuuuuuuge project, it would be almost impossible to rewrite it, even partially + I'm not that good :( )

good luck, with this completely broken system which forces all the developers to spend a lot of time modifying everything for the pleasure of these idiots who instead of improving discord.js, destroy it.
