### ISSUE TITLE
`RoleManager#fetch()` may return `null`, but this is inconsistent

### ISSUE THREAD

**Issue by Astronautilus14** [discordjs/discord.js#9260]
### Which package is this bug report for?

discord.js

### Issue description

There is an inconsistency with fetching roles with this manager compared to the majority of other managers in discord.js.

Discord's API does not provide a way to fetch a single role... but discord.js does. discord.js fetches all roles and attempts to resolve a role and if it fails, the method returns `null`.

This is inconsistent as the other managers naturally throw an error. The inconsistency here may lead to an unsuspecting encounter. It is proposed that either a custom discord.js error is thrown instead of returning `null` or stop the resolving of a singular role.

### Code sample

```typescript
const role = await guild.roles.fetch(roleId); // If the roleId does not exist, role is null

const member = await guild.members.fetch(memberId); // If the memberId does not exist, an error is thrown
```

### Package version

14.8.0

### Node.js version

16.18.0

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

### I have tested this issue on a development release

No

**Comment by Jiralite** [comment]
I wouldn't call this a bug as there is no unexpected or unintended behaviour... return values are documented, so this shouldn't be a surprise.
