### ISSUE TITLE
AutoMod MentionSpam Rule Error

### ISSUE THREAD

**Issue by CaptainPlantain** [discordjs/discord.js#9287]
### Which package is this bug report for?

discord.js

### Issue description

When attempting to modify the `MentionSpam` trigger type of `AutoModerationRule` (Block Mention Spam automod rule), methods are returning a 404 API error. All other trigger types for automod rules work without error.

```
Unhandled promise rejection: DiscordAPIError[0]: 404: Not Found
 {
  rawError: { message: '404: Not Found', code: 0 },
  code: 0,
  status: 404,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/guilds/1013542833334005791/auto-moderation/rules/1030554520465440818',
  requestBody: {
    files: undefined,
    json: {
      name: undefined,
      event_type: undefined,
      trigger_metadata: undefined,
      actions: undefined,
      enabled: false,
      exempt_roles: undefined,
      exempt_channels: undefined
    }
  }
}
```

### Code sample

```typescript
const automodRules = await interaction.guild.autoModerationRules.fetch();
const mentionSpamRule = automodRules
  .find((rule) => rule.triggerType === AutoModerationRuleTriggerType.MentionSpam);
await mentionSpamRule.setEnabled(false);
```

### Package version

14.8.0

### Node.js version

18.13.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Cannot reproduce. Provided code sample works perfectly fine. Tested both disabling and enabling on 14.8.0 and d1ebe4a52c1d8862a10b51e07429701f83759a50.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/33201955/228110065-98458aa4-320c-4fff-9e1c-ebd8d324947a.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/33201955/228110199-214af447-f1db-436d-bff8-89988b5102d1.png">

**Comment by CaptainPlantain** [comment]
The code sample is exactly what I'm using and it worked just fine for all other rule types.
Oddly, I just ran into a 404 error when messing with a MentionSpam rule in the discord client which makes me think this is a client-side issue and not a discord.js issue.

**Comment by Jiralite** [comment]
> I just ran into a 404 error when messing with a MentionSpam rule in the discord client which makes me think this is a client-side issue and not a discord.js issue.

Definitely not a client-side issue if the API is returning it! If that's the case, then Discord thinks you do not have one, which is odd...

What is the output of `mentionSpamRule` in your code sample?

**Comment by CaptainPlantain** [comment]
Looks normal to me. Still running into the error.

Here's `mentionSpamRule`
```
AutoModerationRule {
  id: '1030554520465440818',
  guild: Guild { ... }, 
  creatorId: '1008776202191634432',
  triggerType: 5,
  name: 'Block Mention Spam',
  eventType: 1,
  triggerMetadata: {
    keywordFilter: [],
    regexPatterns: [],
    presets: [],
    allowList: [],
    mentionTotalLimit: 20
  },
  actions: [ { type: 1, metadata: [Object] } ],
  enabled: true,
  exemptRoles: Collection(0) [Map] {},
  exemptChannels: Collection(0) [Map] {}
}
```

**Comment by Jiralite** [comment]
Honestly not sure at this point. If both the client and API can't do such an action, then it's not related to discord.js. Sounds more like a Discord issue.

I'd probably try deleting the rule and recreating it and see it that works.
