### ISSUE TITLE
channel.isTextBased is not a function

### ISSUE THREAD

**Issue by KirillSakharov** [discordjs/discord.js#9295]
### Which package is this bug report for?

discord.js

### Issue description

1. Set up a discord bot
2. Create a button
3. Click the button
4. Error:
```
...\node_modules\discord.js\src\client\actions\InteractionCreate.js:50
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
```

### Code sample

```typescript
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const fs = require('node:fs');
const { Client, Events, GatewayIntentBits, Partials } = require('discord.js');
const clientId = "your-clientid-here"
var commands = [];
const { SlashCommandBuilder } = require('@discordjs/builders');
const { ActionRowBuilder, ButtonBuilder, ButtonStyle} = require('discord.js');
const rest = new REST({ version: '9' }).setToken(token);
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessages], partials: [Partials.Channel] });
const guildId = "your-guildid-here";

const bug = new SlashCommandBuilder()
			.setName('bugbutton')
			.setDescription('give me a button');
commands.push(bug.toJSON());

client.on(Events.InteractionCreate, async interaction => {
	if (!interaction.isChatInputCommand()) return;

	if (interaction.commandName === 'bugbutton') {
		const row = new ActionRowBuilder()
			.addComponents(
				new ButtonBuilder()
					.setCustomId('primary')
					.setLabel('Click me!')
					.setStyle(ButtonStyle.Primary),
			);

		await interaction.reply({ content: 'I think you should,', components: [row] });
	}
});
(async () => { try { await rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands },);} catch (error) {console.error(error);}})();

client.login("your-token-here");
```

### Package version

+-- discord.js@14.7.1

### Node.js version

v19.6.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages

**Comment by jaw0r3k** [comment]
it was fixed by https://github.com/discordjs/discord.js/pull/9204
and this error should no longer be thrown anyway

**Comment by Jiralite** [comment]
Please make sure to report issues on the latest versions. The current latest version for the v14 line is 14.8.0. You just need to update.

**Comment by BoryaGames** [comment]
Same with latest 14.8.0 version.

**Comment by Jiralite** [comment]
That is simply not possible. You should ask in the [Discord server](https://discord.com/invite/djs) for aid with your problem.

**Comment by Avignus** [comment]
I'm having the same issue here when trying to answer a StringSelectMenuBuilder() intereaction. Is there any solution for that? Started to happend 2 hours ago. I believe it is related with Discord's api.

**Comment by Jiralite** [comment]
Are you... not reading? Update.

**Comment by Avignus** [comment]
I'm sorry, I haven't read the comment where the guy mentiones that it's an old problem. I've updated and it solved the bug. Thanks.

**Comment by mukesh1234399** [comment]
just uninstall discord.js package and install it.
npm i discord.js@13 (if v13) - isText()
npm i discord.js@14 (if v14) - isTextBased()

**Comment by Thomas-Gallusser** [comment]
> That is simply not possible. You should ask in the [Discord server](https://discord.com/invite/djs) for aid with your problem.

"Uncaught TypeError TypeError: channel.isTextBased is not a function"

>npm -v discord.js
9.3.1

"simply not possible" 🤣🤡👌
