### ISSUE TITLE
channel.isTextBased is not a function

### ISSUE THREAD

**Issue by Theiremi** [discordjs/discord.js#9296]
### Which package is this bug report for?

discord.js

### Issue description

The interaction constantly fail on my side with the error : `TypeError: channel.isTextBased is not a function`
The function in question is at the line 50 of [this file](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/client/actions/InteractionCreate.js#L50)

### Code sample

```typescript
//Only need to receive interactions from Discord for it to occur
import Discord from 'discord.js';
const client = new Discord.Client({
  intents: []
});
client.on('interactionCreate', async (interaction) => {});
client.login(TOKEN);
```

### Package version

14.7.1

### Node.js version

18.15.0

### Operating system

Ubuntu 22.10

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates

**Comment by Jiralite** [comment]
Duplicate: #9295.
