### ISSUE TITLE
`AutoModerationRuleManager` fetch returns incomplete `actions` properties

### ISSUE THREAD

**Issue by CaptainPlantain** [discordjs/discord.js#9305]
### Which package is this bug report for?

discord.js

### Issue description

When fetching existing **preset** automoderation rules, they are missing the necessary actions array elements to edit them. For example, the Block Suspected Spam rule requires both `AutoModerationActionType.BlockMessage` and `AutoModerationActionType.SendAlertMessage` objects. If I turn one of these off manually in discord, the fetched rule will not contain that object. If I attempt to set this rule's action based on the returned rule, I will receive the error `DiscordAPIError[50035]: Invalid Form Body`.

To fix this, the fetched rule's actions array will need to contain all the required objects, even if they have been deactivated.

### Code sample

```typescript
const automodRules = await interaction.guild.autoModerationRules.fetch();  
const spamRule = automodRules
    .find((rule) => rule.triggerType === AutoModerationRuleTriggerType.Spam);
await spamRule.setActions(spamRule.actions);
```

### Package version

14.8.0

### Node.js version

18.13.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by CaptainPlantain** [comment]
Update: This seems to only happen when the fetched Spam rule only has `AutoModerationActionType.SendAlertMessage` selected. It works just fine when only `AutoModerationActionType.BlockMessage` is selected.

**Comment by CaptainPlantain** [comment]
Looks like I've found the problem. The fetched rule is returning `.actions[0].metadata.channelId` instead of `actions[0].metadata.channel`

See [`AutoModerationActionMetadataOptions`](https://discord.js.org/#/docs/discord.js/main/typedef/AutoModerationActionMetadataOptions) 
vs. 
[`AutoModerationActionMetadata`](https://discord.js.org/#/docs/discord.js/main/typedef/AutoModerationActionMetadata)

**Comment by jaw0r3k** [comment]
Well some solution is just modifying it by your self
but yeah we should allow using both I think

**Comment by Jiralite** [comment]
Just wanted to point out some oddities you stated:

> the Block Suspected Spam rule requires both `AutoModerationActionType.BlockMessage` and `AutoModerationActionType.SendAlertMessage` objects.

It doesn't—it requires either one.

> If I turn one of these off manually in discord, the fetched rule will not contain that object.

Either checked action will be returned when disabled. This makes sense since updating a disabled state only... updates the disabled state. It does not remove the actions and I cannot reproduce this.

<hr>

Your investigation is correct, sending the `actions` of a returned auto moderation rule into a PATCH will return said error (by the way, you should not omit the full error). I am not convinced this is a bug, however. We can choose how to store our properties, and you are responsible for reading documentation and actually making sure what you are doing is what you should be doing.

**Comment by CaptainPlantain** [comment]
Yes, the oddities were the result of me continuing to investigate. 
    
If you'd prefer that I don't report unexpected experiences and property naming, I'm happy to save myself the time. You're free to store the properties however you like of course, no bother to me.
