### ISSUE TITLE
`ephermeral: true` not respected on `interaction.followUp()`

### ISSUE THREAD

**Issue by IslandRhythms** [discordjs/discord.js#9307]
### Which package is this bug report for?

discord.js

### Issue description

I have a help command on my discord bot that goes through the sub directories and and creates a string. As a result, I use the interaction.deferReply() so it doesn't time out. The issue is that everyone can see that command when a person uses it.

Me using it
![image](https://user-images.githubusercontent.com/39510674/229256747-79769071-97a3-435e-a61c-aa2647138386.png)
A buddy using it
![image](https://user-images.githubusercontent.com/39510674/229256777-3a2fc34b-15bb-4e1e-8519-13b57c5cebdf.png)

### Code sample

```typescript
const { SlashCommandBuilder } = require('discord.js');
const path = require('path');
const fs = require('fs');
module.exports = {
  data: new SlashCommandBuilder().setName('help').setDescription('Lists the commands of the bot'),
  async execute(interaction) {
    await interaction.deferReply();
    const commands = [];
    // Grab all the folders from the commands directory
    const commandDirectory = path.join(__dirname, '../');
    const commandFolders = fs.readdirSync(commandDirectory);
    // Grab the SlashCommandBuilder#toJSON() output of each command's data for deployment

    for (const folder of commandFolders) {
      const commandsPath = path.join(commandDirectory, folder);
      const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));
      for (const file of commandFiles) {
        const filePath = path.join(commandsPath, file);
        const command = require(filePath);
          command.data.category = folder;
          commands.push(command.data.toJSON());
      }
    }
    let str = `**${commands[0].category}**\n\n`;
    let cat = commands[0].category;
    for (let i = 0; i < commands.length; i++) {
      if (commands[i].category != cat) {
        cat = commands[i].category;
        str += `\n\n**${commands[i].category}**\n\n`
      }
      str += `/${commands[i].name} = ${commands[i].description}\n`;
    }
    return interaction.followUp({ content: str, ephemeral: true });
  }
}
```

### Package version

14.8

### Node.js version

16.13.2

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

GuildMember, Message, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
You do not defer ephemerally. At that point, the message is created, and following up cannot convert an existing message to an ephemeral one.
