### ISSUE TITLE
New site is missing some classes, types, etc...

### ISSUE THREAD

**Issue by TetieWasTaken** [discordjs/discord.js#9316]
### Which package is this bug report for?

discord.js

### Issue description

As discovered in #9313, some things are missing from the new website. Is this intentional, or is there something wrong with the docgen?

Steps to reproduce:
1. Head over to the old documentation @ https://old.discordjs.dev/#/docs/collection/main/class/Collection
2. See typedefs
3. See the new documentation @ https://discord.js.org/docs/packages/collection/main/
4. Observe missing types (`Comparator`, `CollectionConstructor`, `Keep`)

Note: Make sure you have the new site loaded by doing a hard reset or clearing your cache

Other examples are: `SelectMenuBuilder` and `JSONEncodable`

### Package version

Does not apply

### Node.js version

Does not apply

### Operating system

Chrome 111.0.5563.146

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by kyranet** [comment]
They're marked as `@internal`, which do not get exposed to the docs.

https://github.com/discordjs/discord.js/blob/8d345a041e6e81ba6e226cd8ed95df8c40a491a8/packages/collection/src/collection.ts#L834-L842

**Comment by TetieWasTaken** [comment]
Why doesn't `SelectMenuBuilder` show up then? It's not marked as internal but also doesn't show up on `https://discord.js.org/docs/packages/builders/main`.

https://github.com/discordjs/discord.js/blob/b2ec865765bf94181473864a627fb63ea8173fd3/packages/builders/src/components/selectMenu/SelectMenu.ts#L15-L18

**Comment by Jiralite** [comment]
That commit you are viewing is from ~7 months ago.

Why does it show up in the old website still? That's because the documentation stopped generating for them long ago _before_ the new builders.
