### ISSUE TITLE
Internal Server Error on /docs

### ISSUE THREAD

**Issue by twisttaan** [discordjs/discord.js#9317]
### Which package is this bug report for?

discord.js

### Issue description

1. go to https://discord.js.org/
2. click the enticing blurple docs button
3. cry yourself in ptsd from a next.js internal server error

https://user-images.githubusercontent.com/69066026/229348626-bf3b8cc0-b219-4e3e-adde-77f4f5f43ff3.mov

### Package version

n/a

### Node.js version

n/a

### Operating system

n/a

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
/builders is currently rebuilding from a release. It'll be back up momentarily.

**Comment by twisttaan** [comment]
> /builders is currently rebuilding from a release. It'll be back up momentarily.

I don't think this is friendly UX to just block out the whole site with a generic error message.

**Comment by Jiralite** [comment]
You can use https://discord.js.org/docs/packages for now.

**Comment by twisttaan** [comment]
Are potential first-time visitors aware of this?

## Scenario

User: I want to browse the documentation of this library
*user finds the discord.js website*
User: Ah, docs, let me in.
*internal server error because there was a "rebuilding" during the time of visiting*
User: Oh, that's unfortunate, guess their docs don't work.
*leaves website*

###### Yes, it sounds rare, but I just experienced that now.

I don't know how the website works, but instead of fetching docs that don't exist yet (which I assume it does) it should fallback to an older version. (bonus points, some UI indicator to say a new version just got released and is currently building, offsetting their attention to the release notes for the time being).

**Comment by iCrawl** [comment]
There was actually no rebuilding.

There were no docs available, which is a real error.
