### ISSUE TITLE
'cache' of undefined

### ISSUE THREAD

**Issue by ZeroRaven23** [discordjs/discord.js#9320]
### Which package is this bug report for?

discord.js

### Issue description

recently I had this error a few times, and just as it appeared without changing the code, it disappeared could you tell me what it could be?

### Code sample

```typescript
Wolf-Project\node_modules\discord.js\src\client\actions\MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read property 'cache' of undefined
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (Wolf-Project\node_modules\discord.js\src\client\voice\VoiceConnection.js:303:26)
    at Wolf-Project\node_modules\discord.js\src\client\voice\VoiceConnection.js:324:61
    at Timeout.<anonymous> (Wolf-Project\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT
```

### Package version

discord.js@12.5.3

### Node.js version

v16.9.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

GuildVoiceStates

**Comment by Jiralite** [comment]
Version 12 is not supported. Update to version 14, which is our current latest supported major.

[Version 12 to 13 guide](https://discordjs.guide/additional-info/changes-in-v13.html)
[Version 13 to 14 guide](https://discordjs.guide/additional-info/changes-in-v14.html)
