### ISSUE TITLE
`/rest`: [CONTENT_TYPE_INVALID]: when making post request to `Routes.userChannels()`

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#9321]
### Which package is this bug report for?

rest

### Issue description

1) make a post request to `Routes.userChannels()`

Error: [CONTENT_TYPE_INVALID]: Expected "Content-Type" header to be one of {'application/json'}

<img width="412" alt="image" src="https://user-images.githubusercontent.com/54294685/229391179-ead22a5a-bfa9-47b3-bf5b-8054f1fcb67e.png">

### Code sample

```typescript
import { REST } from '@discordjs/rest';
import { Routes } from 'discord-api-types/v10';

const rest = new REST({ version: '10' }).setToken('token');

const result = await rest.post(Routes.userChannels());
```

### Package version

1.6.0

### Node.js version

18 LTS

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by monbrey** [comment]
This seems like a documentation issue rather than a bug. A POST request to this endpoint should have a body containing a `recipient_id` of the User to open a DM channel with.

https://discord.com/developers/docs/resources/user#create-dm

**Comment by pkdev08** [comment]
> Your usage of this route is incorrect. A POST request to this endpoint should have a body containing a `recipient_id` of the User to open a DM channel with.
> 
> https://discord.com/developers/docs/resources/user#create-dm

https://github.com/discordjs/discord-api-types/blob/main/rest/v10/index.ts#L570 doesn't show that takes any parameters, but even with providing a user id the response is the same.

**Comment by pkdev08** [comment]
oh yeah, it seems like the api-types docs didn't include this. Thanks!

**Comment by monbrey** [comment]
The route doesn't take a parameter, but the body of the post request does. The api-type for the Route is correct.

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions!
