### ISSUE TITLE
Page does not load in Firefox private windows

### ISSUE THREAD

**Issue by FozzieHi** [discordjs/discord.js#9323]
When I try and load the website (https://discord.js.org/) in a Firefox Private Window I get an error that `navigator.serviceWorker` is undefined:
![image](https://user-images.githubusercontent.com/23139726/229589461-bad1ecc6-13f2-434c-8763-f3a8e8ce03b5.png)

I think this is because `navigator.serviceWorker` [may not be available in Private Windows](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker).
> The feature may not be available in private mode.

**Comment by Jiralite** [comment]
I was able to reproduce this on the new website, thank you for clearing that up!
