### ISSUE TITLE
Member.voice.channel outputs wrong voice channel

### ISSUE THREAD

**Issue by olikam0712** [discordjs/discord.js#9328]
### Which package is this bug report for?

discord.js

### Issue description

![image](https://user-images.githubusercontent.com/71721386/229875661-c73fccf1-090e-4258-b63f-5433fe13b252.png)
![image](https://user-images.githubusercontent.com/71721386/229875781-9adf89e8-8cad-46d6-9396-0499241e2fa4.png)

### Code sample

```typescript
client.on('interactionCreate', async (interaction) => {
    if (interaction.isChatInputCommand()) {
        switch (interaction.commandName) {
            case "example":
                let channel = await interaction.member.voice.channel;
                console.log(channel.name);
                interaction.reply({ content: 'bluh', ephemeral: true });
                break;
            default:
                interaction.reply('error');
                break;
        }
    }
});
```

### Package version

14.9.0

### Node.js version

18.15.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessageReactions, MessageContent

**Comment by olikam0712** [comment]
Sorry i forgot to add a VoiceState Intent

**Comment by Jiralite** [comment]
In the future, explain your problem. I was deeply confused reading this issue—we cannot read minds.
