### ISSUE TITLE
Automod delete reason isn't added

### ISSUE THREAD

**Issue by Ruben-Schadron** [discordjs/discord.js#9329]
### Which package is this bug report for?

discord.js

### Issue description

Wen i try to delete an automod rule with the bot. The bot removes the rule but the  reason isn't added

### Code sample

```typescript
const ruleId = interaction.options.getString('ruleid');
    var reason = interaction.options.getString('reason') || 'not proved';
    reason = `${interaction.user.tag} (${interaction.user.id}) \nreason: ${reason}`

    interaction.guild.autoModerationRules.delete(ruleId, reason)
```

### Package version

discord.js@14.9.0

### Node.js version

19.6.0

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

AutoModerationConfiguration

**Comment by Jiralite** [comment]
Cannot reproduce.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/33201955/230034532-7c6f67b5-fe3d-4b2d-8390-b62dcd8fa430.png">

**Comment by Jiralite** [comment]
The reporter was looking at the client rather than the API.[^1] Not a discord.js issue, but a Discord client issue that doesn't expose this property.

[^1]: https://canary.discord.com/channels/222078108977594368/824411059443204127/1093095256016298005
