### ISSUE TITLE
ApplicationCommand#edit doesn't unset defaultMemberPermission

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#9332]
### Which package is this bug report for?

discord.js

### Issue description

1. Create a command with a defaultMemberPermission set
2. Edit it by passing the entire command object again, but this time without the defaultMemberPermission property
3. Observe how it is still set on Discord

As a sidenote, I believe this issue would be fixed by initiating the default_member_permissions variable in ApplicationCommandManager.transformCommand as `null`, I just won't PR it as I'm not sure if that would have unwanted side-effects
https://github.com/discordjs/discord.js/blob/6912faa9b3852adbacc7d0b002aae81be041f529/packages/discord.js/src/managers/ApplicationCommandManager.js#L236

### Code sample

```typescript
const command = {
    name: "test",
    description: "A test command",
    defaultMemberPermissions: 8n
}

const discordCommand = await client.application.commands.create(command)

delete command.defaultMemberPermissions

await discordCommand.edit(command)

console.log(discordCommand.defaultMemberPermissions)
```

### Package version

14.9.0

### Node.js version

18.14.2

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Why would explicitly not updating a property not doing anything be a bug?

**Comment by ImRodry** [comment]
Notice how I'm passing the full object. That's how I expect the command to look like in Discord afterwards.
I, personally, check for differences between my commands locally and on Discord using the equals function and then edit them if changes are found, so if I delete a property, I expect it to be deleted on Discord as well.

**Comment by vladfrangu** [comment]
Unfortunately, an undefined property means `don't change it` when it comes to PATCH-ing anything. If you want it reset, you need to set it to null (0 has different meanings for this property which you can read on Discord's docs)

**Comment by ImRodry** [comment]
I understand that patching with undefined means to not change it, but I don't think that makes sense in this particular scenario. A lot of users have a workflow similar to mine where they have the raw JSON objects in their project and only change those to change the commands on Discord, so I think it would be safe to assume that if you're passing the full object (which you are when you reach transformCommand) that you'd want to delete any undefined properties. Could you reconsider for this scenario? It would be very annoying to have to get around that

**Comment by Jiralite** [comment]
This sounds like you should be setting commands—not editing them.

**Comment by ImRodry** [comment]
We're not talking about accidents here. We're talking about having it defined then purposedly deciding to remove it.
I want to avoid setting exactly because I'd need to overwrite every single command on every startup, which is sub-optimal.
At the time I made this system global commands used to take 1 hour to update which I believe they don't anymore, but that would still be sub-optimal. I truly believe it makes sense to do this in this scenario

**Comment by vladfrangu** [comment]
> We're talking about having it defined then purposedly deciding to remove it

Then set it to `null`? 😕 I fail to see how that's hard or an issue, or why we should break the assumption that `editing` *anything* means updating JUST what you pass in and not other fields (which would count as undefined behavior, and can cause more issues than it fixes)

**Comment by ImRodry** [comment]
I think you can understand that it's not at all practical to have to set every property we want to delete on Discord to null, as that would add unnecessary clutter to the file or would require unnecessary steps to remove it later on. I understand that wouldn't make sense in other scenarios, but application commands are often stored in JSON form in the file trees of each project so it would make sense to want that to be fully reflected on Discord's end

**Comment by almostSouji** [comment]
This is consistent behavior across the library; changing it for this specific instance is confusing and subverts user expectations.

**Comment by kyranet** [comment]
For absolute updates, you can also define a defaults object:

```typescript
const defaults = {
	defaultMemberPermission: null
	/* other fields */
} as const satisfies ApplicationCommandData;
```

And then spread it:

```typescript
command.edit({
	...defaults,
	...data
});
```

That way, if `data.defaultMemberPermission` is `undefined`, it'll default to `null` as it won't override the property from the `defaults` object.

**Comment by ImRodry** [comment]
Well yes I know, that's why I was saying that getting around that not being a thing in the library itself is annoying
As for this
> subverts user expectations

I think users like myself are way more likely to expect their command json to be fully reflected on Discord than partially reflected like it is the case now, so that's very subjective

**Comment by kyranet** [comment]
It should not be ambiguous at all, `edit` changes the properties you pass, it doesn't modify the ones you don't, for that it's not `set`.

Anything method that does a partial update (PATCH) request is named (or prefixed) `edit`, whereas any method that modifies all properties (POST) is named `set`.

We should not change the meaning of PATCH to match that of POST, plus it would break helper methods (imagine setting just the DM permissions, and then the member permissions get reset to `null`). You can see where I'm going now, and the implications of what you're suggesting.

**Comment by ImRodry** [comment]
Now that is a point I can agree with, which is why I mentioned there could be unwanted side-effects from this. A good way to get around that could be to change the way the resulting object that is sent to the api is obtained

**Comment by Syjalo** [comment]
The solution to this problem is to ask to add `PUT: /applications/:application-id/commands/:command-id` route or document it if it's already exists.
