### ISSUE TITLE
DiscordAPIError as an event

### ISSUE THREAD

**Issue by Johannes7k75** [discordjs/discord.js#9341]
### Which package is this feature request for?

discord.js

### Feature

I would like that the "DiscordAPIError" is instead of just bethrown in the console an event,
so i could get the error by `client.on("apiError", ()=>{})`

### Ideal solution or implementation

Add a event named "apiError"

That gets dispatched instead of being thrown or at the same time

**Comment by Jiralite** [comment]
discord.js already calls `captureRejections: true`:

https://github.com/discordjs/discord.js/blob/f195556b64cac11aa24d828cf7621d93c229279d/packages/discord.js/src/client/BaseClient.js#L15

I am fairly confident that all `DiscordAPIError`s are from `Promise`s. Therefore, you just need to add `if (error instanceof DiscordAPIError)` to the `error` event, and that's it.

**Comment by Johannes7k75** [comment]
> [...] you just need to add `if (error instanceof DiscordAPIError)` to the `error` event, and that's it

So this would just work fine?
```js
const { Client, IntentsBitField, DiscordAPIError } = require("discord.js");

const client = new Client({
	intents: [IntentsBitField.Flags.Guilds],
});

client.on("ready", () => {
	const channel = client.channels.cache.get("CHANNELID"); // The channel if of a channel where the bot has no "VIEW_CHANNEL" permission
	channel.messages.fetch();
});
client.on("error", (error) => {
	if (error instanceof DiscordAPIError) console.log(error)
});

client.login("TOKEN");

```

**Comment by Jiralite** [comment]
> Just do a check in the error event and await your `Promises`.

You need to resolve your `Promise`. Rejections emit the `error` event, where you can handle them appropriately.

**Comment by Johannes7k75** [comment]
a it has to be so 

```js
const { Client, IntentsBitField, DiscordAPIError } = require("discord.js");

const client = new Client({
	intents: [IntentsBitField.Flags.Guilds],
});

client.on("ready", async () => {
	const channel = client.channels.cache.get("CHANNELID"); // The channel if of a channel where the bot has no "VIEW_CHANNEL" permission
	await channel.messages.fetch();
});
client.on("error", (error) => {
	if (error instanceof DiscordAPIError) console.log(error)
});

client.login("TOKEN");
```

**Comment by Jiralite** [comment]
That's it.
