### ISSUE TITLE
Example for setActivity does not work 

### ISSUE THREAD

**Issue by Yeeeetus** [discordjs/discord.js#9349]
### Which package is this bug report for?

discord.js

### Issue description

create a discordjs client and login
try to use the example for client.user.Activity
it does not work 

### Code sample

```typescript
client.on("ready", () => {
    client.user.setActivity('discord.js', { type: 'WATCHING' });
})
```

### Package version

discord.js@14.9.0

### Node.js version

v17.4.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
Where did you obtain this example from?

**Comment by Yeeeetus** [comment]
from the discord.js docs 
https://discord.js.org/#/docs/discord.js/main/class/ClientUser?scrollTo=setActivity

**Comment by Jiralite** [comment]
Are you sure?

<img width="507" alt="image" src="https://user-images.githubusercontent.com/33201955/230739719-06b7dc95-2646-4048-b30f-32ab2ac50334.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/33201955/230739716-32e3b140-83aa-423d-b265-09cf6b0fd005.png">

**Comment by Yeeeetus** [comment]
no
