### ISSUE TITLE
BitField#toArray() returning the bitfield with the bitfield name

### ISSUE THREAD

**Issue by joeyk710** [discordjs/discord.js#9350]
### Which package is this bug report for?

discord.js

### Issue description

- When accessing the method [BitField#toArray()](https://old.discordjs.dev/#/docs/discord.js/main/class/BitField?scrollTo=toArray), this is suppose to return **only** the Array of BitField *names* based on the bit given. The actual result returns the bitfield itself as a string as well as the bitfield name, which is the expected result.

- The PR #9262, and the issue #9247 both attempt to address this issue, but does not occur on `v14.8.0` and is shown below. I am unsure why this change was necessary since I was not experiencing these issues at all in previous versions. 
https://github.com/discordjs/discord.js/blob/98420826bc2296fc392f17e8254cf4ad743ff5af/packages/discord.js/src/util/BitField.js#L166-L169

- On `v14.9.0`, this has line 167 moved to line 168 (shown below), which is indeed causing an issue with the bitfield and bitfield name showing together.
https://github.com/discordjs/discord.js/blob/1b9d07f941dc3edf20cd5e65c56b70d009880893/packages/discord.js/src/util/BitField.js#L166-L169

Here is the result I got on `v14.9.0` accessing [UserFlagsBitField#toArray()](https://old.discordjs.dev/#/docs/discord.js/main/class/UserFlagsBitField?scrollTo=toArray)

![image](https://user-images.githubusercontent.com/71621973/230742148-4c41177c-28d3-4998-96b8-be30206d6ac4.png)

This is the *temporary* workaround I made so the bitfield is removed from the array:
```ts
const flagStrings = message.author.flags.toArray().map((flagName) => flagName);

const flagSplice = flagStrings.splice(0, flagStrings.length / 2, ...flagStrings.splice(0, flagStrings.length / 2).reverse());
```
<img width="825" alt="image" src="https://user-images.githubusercontent.com/71621973/230742805-09078a18-bb42-41cb-8a4c-3fe536478868.png">

- It would appear that [PermissionsBitField#toArray()](https://old.discordjs.dev/#/docs/discord.js/main/class/PermissionsBitField?scrollTo=toArray) does not have this issue from testing, but other extended BitField classes do. This does show the expected result with the permission bitfield **name** only.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/71621973/230744032-25e8e763-2ed3-4230-aa56-da9ed84b42fe.png">

### Code sample

```typescript
Access the flags from a user with UserFlagsBitField#toArray() and the client's intents with IntentsBitField#toArray().

Tested code:
- message.author.flags.toArray()
- message.client.options.intents.toArray()
```

### Package version

v14.9.0

### Node.js version

v18.5.0

### Operating system

Linux arm64

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildPresences, GuildMessages, MessageContent

**Comment by jaw0r3k** [comment]
For me the issue comes from iterating over an enumeration
https://github.com/discordjs/discord.js/blob/b2eec5f9fcf37ebb3b7f87a67a6ee3160c182183/packages/discord.js/src/util/BitField.js#L142

As it has both: names and bits in it
