### ISSUE TITLE
TOKEN_INVALID Error

### ISSUE THREAD

**Issue by LimanGit** [discordjs/discord.js#9355]
### Which package is this bug report for?

ws

### Issue description

![E42A4334-1588-4FFB-A31E-F01F7B6861B6](https://user-images.githubusercontent.com/77584576/230769342-6e6f7e0b-fbed-46ac-b0c0-f90757a5cdf0.jpeg)

### Code sample

```typescript
const express = require('express');

const app = express();

app.get('/', (req, res) => {
  res.send('Hello Express app!')
});

app.listen(3000, () => {
  console.log('server started');
});

const { Client, RichPresence, DiscordRPCServer } = require('discord.js-selfbot-v13');

const client = new Client();

client.on('ready', () => {
  console.log('Client logged in')
})
client.login(process.env.token)
```

### Package version

1.13.2 v13

### Node.js version

18.12.1

### Operating system

Linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by vladfrangu** [comment]
We do not provide support for third party forks, especially those that break Discords terms of service.
