### ISSUE TITLE
Support for multiple attachments

### ISSUE THREAD

**Issue by uhWillem** [discordjs/discord.js#9393]
### Which package is this feature request for?

discord.js

### Feature

I am currently working on a feature that allows users to upload up to 15 .txt files. I would like to avoid having to use the .addAttachmentOption() method for each file individually. Even if I did do it like that, the files have to be dragged individually to every attachment option which is kind of a hassle

### Ideal solution or implementation

One approach is to allow users to select and drag up to x amount of files into Discord to attach them, and to set the maximum number of attachments using the .addAttachmentOption() method, which lets you choose how many files can be added. 

The .getAttachment method could return an array that has all the files which could then be iterated through.
`const attachments[] = interaction.options.getAttachment('files');`

### Alternative solutions or implementations

Another option is potentially a modal for uploading (multiple) files at a time.

**Comment by Jiralite** [comment]
We are a library that interacts with the Discord API. We are not Discord! We cannot do what Discord does not support.
