### ISSUE TITLE
`null` Value on Scheduled Events is userCount Property

### ISSUE THREAD

**Issue by Neodevils** [discordjs/discord.js#9394]
### Which package is this bug report for?

discord.js

### Issue description

1. Create an event.
2. Read the cache.
3. See the value of `userCount` property.

### Code sample

```typescript
client.guilds.scheduledEvent.cache.get("…") // .userCount
```

### Package version

v14.9.0

### Node.js version

v18.12.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildScheduledEvents

**Comment by Jiralite** [comment]
This is the correct behaviour as Discord does not send this property on creation.

**Comment by Neodevils** [comment]
> This is the correct behaviour as Discord does not send this property on creation.

So, Discord.JS has it even though it is known it is not supported *for now*?

**Comment by Jiralite** [comment]
I said that Discord does not send this property on creation. That should lead you to believe Discord sends it elsewhere, not that the property is present but unsupported. Fetching a scheduled event will yield the user count, for example.

You can ask further questions in the [Discord server](https://discord.com/invite/djs).
