### ISSUE TITLE
Unable to delete epemeral message from `ButtonInteraction`

### ISSUE THREAD

**Issue by Huntifer-RotMG** [discordjs/discord.js#9397]
### Which package is this bug report for?

discord.js

### Issue description

1. Receive a `ChatInputCommandInteraction`
2. Create an ephemeral reply with `interaction.reply({ embeds: [ /* embed */ ], ephemeral: true, components: [ /* buttons */ ])`
3. User clicks on a button
4. In toplevel `client.on('interactionCreate')` handler, receive `ButtonInteraction`
5. `buttonInteraction.message.delete()`
6. Receive error:
```
DiscordAPIError[10008]: Unknown Message
    at handleErrors (/home/huntifer/Projects/Bot/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/huntifer/Projects/Bot/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/huntifer/Projects/Bot/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/huntifer/Projects/Bot/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async MessageManager.delete (/home/huntifer/Projects/Bot/node_modules/discord.js/src/managers/MessageManager.js:255:5)
    at async Message.delete (/home/huntifer/Projects/Bot/node_modules/discord.js/src/structures/Message.js:816:5)
    at async /home/huntifer/Projects/Bot/index.js:56:16 {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Unknown Message', code: 10008 },
  code: 10008,
  status: 404,
  method: 'DELETE',
  url: 'https://discord.com/api/v10/channels/XXXXXXXXXXXXX/messages/XXXXXXXXXXXXXXX'
}
```

I am currently using a workaround by trying to reconstruct the `InteractionResponse` from an application level cache (storing `interaction.{token,webhook.id,commandId`) and then manually building the response object as follows:

```
const applicationCache = ...; /* Values from my application cache */
const interaction = ...; /* The ButtonInteraction */
const mockInteraction = new Discord.ChatInputCommandInteraction(client, {
            message: interaction.message.id,
            id: applicationCache.webhookId,
            application_id: interaction.applicationId,
            token: applicationCache.token,
            channel_id: interaction.channel.id,
            user: interaction.user,
            guild_id: interaction.guild.id,
            type: undefined, // TODO: Use the actual type
            data: {
                id: applicationCache.webhookId,
                name: applicationCache.command,
                type: undefined, // TODO: Use the actual type
                token: applicationCache.token,
            }
        })
        mockInteraction.replied = true;
        const response = new Discord.InteractionResponse(mockInteraction)
```

This works, but is very brittle and is very much a hack that I'd like to remove once this bug is resolved.

### Code sample

```typescript
const Discord = require('discord.js')

const client = new Discord.Client(...)

client.on('interactionCreate', async (interaction) => {
    if (interaction.isChatInputCommand()) {
        const buttons = new Discord.ActionRowBuilder()
                                        .addComponents(
                                            new Discord.ButtonBuilder()
                                                .setLabel('Delete')
                                                .setCustomId('delete')
                                                .setStyle(Discord.ButtonStyle.Danger)
                                        );
        const embed = new Discord.EmbedBuilder()
            .setDescription('This will be deleted when you click the button');
        await interaction.reply({embeds: [ embed ], ephemeral: true, components: [ buttons ]});
    } else if (interaction.isButton()) {
        await interaction.message.delete();
    }
})

client.login(...)
```

### Package version

14.8.0

### Node.js version

19.7.0

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildWebhooks, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
You are calling this method on the `Message` object, which does not perform any interaction route. This is not a bug.

**Comment by Huntifer-RotMG** [comment]
If this is an incorrect use of the library, at the very least this ought to be documented somewhere. It is highly unintutive that a `Message` returned by an interaction is different from `Message`s that is produced through any (?) other method.

Is there any way to work around this limitation? Or is my hack the intended way for `discord.js` users to accomplish this?

**Comment by Huntifer-RotMG** [comment]
It's also worth noting that if this is functioning as intended, there is no way for a library user to determine if a `Message` is safe to delete or not. `interaction.message.deletable` is _true_ for the `ButtonInteraction` message.

**Comment by monbrey** [comment]
> It is highly unintutive that a `Message` produced by an interaction is different from a `Message` that is produced through any (?) other method.

It's not because it's from an interaction, it's because it's ephemeral. It happens to be that you can only send ephemeral messages in response to an interaction.

The only way to delete an ephemeral message is via the interaction webhook that created it. If you still had the original interaction in scope, you could use `interaction.deleteReply()`. Otherwise, constructing a new `InteractionWebook` would be easier than a whole mock interaction.

**Comment by Huntifer-RotMG** [comment]
Thanks for the suggestion to just create an `InteractionWebhook`, that's a lot cleaner. Still not perfect, because this is a part of a refactor in which I want to have a drop-in replacement for `InteractionResponse` and `InteractionWebhook` is not quite API compatible (because of the *Message suffixes) but I can work around that.

`deleteReply()` unfortunately doesn't work, from what I understand that "reply" is referring to a reply to the button interaction, not a reply to the command interaction.

I agree, the `deletable` isn't quite that clear cut, the message itself is deletable but that particular `Message` object is not. Bit of a weird spot to be in :thinking: It seems to me like maybe this is more of an issue with discord API than with discord.js, but I'm no expert.

**Comment by monbrey** [comment]
> `deleteReply()` unfortunately doesn't work, from what I understand that "reply" is referring to a reply to the button interaction, not a reply to the command interaction.

Using `deferUpdate()` on the ButtonInteraction first *should* cause the reply to be bound to itself, if that makes sense, rather than creating a new message. The "reply" is a deferred update to itself, which can then be deleted (in theory).

I didn't test though, so you might be right that it won't work.

**Comment by Huntifer-RotMG** [comment]
I tested it, you're absolutely correct. I didn't expect the `deferReply()` to actually change what the "reply" was. In that case, maybe the cleanest patch would be monkey-patching over a few of the `ButtonInteraction` methods, although that will require a little more thought about the design on my end.

**Comment by Jiralite** [comment]
Just a note that you can provide a message id to [`ButtonInteraction#deleteReply()`](https://old.discordjs.dev/#/docs/discord.js/14.8.0/class/ButtonInteraction?scrollTo=deleteReply) to delete any valid response.
