### ISSUE TITLE
Getting random 401 Unauthorized errors while playing audio stream

### ISSUE THREAD

**Issue by eugabrielsilva** [discordjs/discord.js#9400]
### Which package is this bug report for?

voice

### Issue description

Recently I've been getting HTTP 401 Unauthorized errors randomly while trying to play audio streams through ytdl. Not sure if it’s related to the lib itself or with discord.js/voice.

Stack trace:

```
AudioPlayerError: Status code: 401
    at ClientRequest.<anonymous> (/home/ubuntu/mybot/node_modules/miniget/dist/index.js:206:27)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  resource: AudioResource {
    playStream: WebmDemuxer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _remainder: null,
      _length: 8193,
      _count: 8088,
      _skipUntil: null,
      _track: [Object],
      _incompleteTrack: {},
      _ebmlFound: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    edges: [],
    metadata: null,
    volume: undefined,
    encoder: undefined,
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [Array],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    playbackDuration: 940,
    started: true,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
```

### Package version

0.16.0

### Node.js version

18.14.2

### Operating system

Ubuntu

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

**Comment by TetieWasTaken** [comment]
We do not support ToS violations. Nor does this look `@discordjs/voice` related.

[Youtube's Terms of Service](https://www.youtube.com/static?template=terms) state that:
> 1. You are not allowed to:
access, reproduce, download, distribute, transmit, broadcast, display, sell, license, alter, modify or otherwise use any part of the Service or any Content except: (a) as specifically permitted by the Service;  (b) with prior written permission from YouTube and, if applicable, the respective rights holders; or (c) as permitted by applicable law;

> 3. access the Service using any automated means (such as robots, botnets or scrapers) except: (a) in the case of public search engines, in accordance with YouTube’s robots.txt file; (b) with YouTube’s prior written permission; or (c) as permitted by applicable law;

> 9. use the Service to view or listen to Content other than for personal, non-commercial use (for example, you may not publicly screen videos or stream music from the Service);

ytdl violates these terms.

**Comment by SpaceEEC** [comment]
`miniget` is a dependency of `ytdl-core`, which we don't support here.
