### ISSUE TITLE
Bot keeps on going zombie

### ISSUE THREAD

**Issue by sttrsttr** [discordjs/discord.js#9411]
### Which package is this bug report for?

discord.js

### Issue description

After x-hours my bot changes status in the discord app to offline, and stops responding to commands. In the console log all I can see is that last command that was executed, it stops sending hartbeats as well. No error codes, nothing. Even if I run it in "debug mode"

(I run the bot on node.js in a screen under Ubuntu Linux on a rented server)

After endless googling I found a tip for adding some "hartbeat reset code" that was supposed to fix zombie issues, but it just gave me a new type of issue it seems. Because today the bot have stopped with this as the last log:

`[WS => Shard 0] [RECONNECT] Discord asked us to reconnect
[WS => Shard 0] [DESTROY]
    Close Code    : 4000
    Reset         : false
    Emit DESTROYED: true
[WS => Shard 0] Clearing the heartbeat interval.`

### Code sample

```typescript
const fs = require('node:fs');
const path = require('node:path');
const { Client, Collection, Events, GatewayIntentBits } = require('discord.js');
const { token } = require('./config.json');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.commands = new Collection();
const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
        const filePath = path.join(commandsPath, file);
        const command = require(filePath);
        client.commands.set(command.data.name, command);
}

client.once(Events.ClientReady, () => {
        console.log('Ready!');
});

client.on(Events.InteractionCreate, async interaction => {
        if (!interaction.isChatInputCommand()) return;

        const command = client.commands.get(interaction.commandName);

        if (!command) return;

        try {
                await interaction.reply({ content: 'I am on it!', ephemeral: true });
                await command.execute(interaction);
        } catch (error) {
                console.error(error);
                await interaction.followUp({ content: 'There was an error while executing this command!', ephemeral: true });
        }
});

client.login(token);

// This last part here is to fix the zombie bug as far as I could tell from google
client.on('debug', async (debug) => {
    console.log;
    if (debug.includes("Clearing the heartbeat interval.")) {
        process.exit(0);
    }
})
```

### Package version

14.7.1

### Node.js version

v19.7.0

### Operating system

Ubuntu Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, Message, Reaction

### Which gateway intents are you subscribing to?

GuildMessages, DirectMessages

**Comment by Qjuh** [comment]
Update to 14.9.0, this is fixed in newer versions.
