### ISSUE TITLE
userAgentAppendix appended multiple times to REST user-agent header each time WebhookClient is instantiated

### ISSUE THREAD

**Issue by cycloptux** [discordjs/discord.js#9421]
### Which package is this bug report for?

discord.js

### Issue description

The PR [#9267](https://github.com/discordjs/discord.js/pull/9267) introduced an unexpected behavior when instantiating a new WebhookClient, which extends BaseClient, specifying the `userAgentAppendix`.

Specifically, this part of the BaseClient initiation:
https://github.com/discordjs/discord.js/blob/603446a692f1e3c8299abf47d47ae8e36a0a2488/packages/discord.js/src/client/BaseClient.js#L21-L25
edits the original `options.rest.userAgentAppendix` prepending `Options.userAgentAppendix`. This is fine when instantiating a single Client, but poses problems when instantiating multiple WebhookClients after the initial initiation since the `userAgentAppendix` value gets longer and longer each time a `new WebhookClient()` is called, to the point where Discord starts returning `400` errors when sending webhooks through any newly instantiated WebhookClient.

This could be solved by deep cloning `options` before running:
https://github.com/discordjs/discord.js/blob/603446a692f1e3c8299abf47d47ae8e36a0a2488/packages/discord.js/src/client/BaseClient.js#L27-L31
and then moving the above assignment after the deep clone, applied to `this.options`, but deep cloning though JSON.parse/JSON.stringify and structuredClone breaks complex properties of the `rest` object, e.g. a custom agent.

### Code sample

```typescript
const clientOptions = { rest: { userAgentAppendix: "loremIpsum/1.0.0" } };
while (true) {
    const webhookClient = new WebhookClient({ url: "https://discord.com/api/..." }, clientOptions);
    console.log(webhookClient.options.rest.userAgentAppendix);
    // userAgentAppendix - and consequently the "user-agent" header - will progressively get bigger: discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 [...] discord.js/14.9.0 Node.js/v18.16.0 loremIpsum/1.0.0
}
```

### Package version

14.9.0

### Node.js version

18.16.0

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
Hi, thank you for the report.

I copied your code sample and I am monitoring the requests via Undici:

```JavaScript
import diagnosticsChannel from "node:diagnostics_channel";
import { WebhookClient } from "discord.js";

diagnosticsChannel.channel("undici:request:create").subscribe(({ request }) => {
	console.log(request.headers); // Log the headers.
});

while (true) {
	const webhookClient = new WebhookClient(
		{ url: "https://discord.com/api/..." },
		{ rest: { userAgentAppendix: "loremIpsum/1.0.0" } },
	);

	await webhookClient.send("Hello there");
}
```

The diagnostics channel is reporting the same user agent for each request (on 14.9.0 and ecd1b5da11d16837e4daa17f18a876a6fb30b47b):

```xl
Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0

Content-Type: application/json
User-Agent: DiscordBot (https://discord.js.org, 1.7.0) discord.js/14.9.0 Node.js/v19.6.0 loremIpsum/1.0.0
```

I seem to not be able to reproduce this. Is there any other missing information, or perhaps the code sample was malformed?

**Comment by cycloptux** [comment]
You are right, the example code was malformed. The point of the bug is that the options object is edited on each iteration, passing a plain object created a clean situation each time.
Try again with the example in the first post and you should see it. You don't even have to send the message, you can just check the userAgentAppendix option.

**Comment by Jiralite** [comment]
I see the mutation crystal clear now. Thank you!

> Try again with the example in the first post and you should see it. You don't even have to send the message, you can just check the userAgentAppendix option.

I think you might need to move `clientOptions` outside of the `while()` loop!

**Comment by cycloptux** [comment]
Done and thanks!
