### ISSUE TITLE
Gracefully handle unknown guild feature names and object properties

### ISSUE THREAD

**Issue by erkinalp** [discordjs/discord.js#9431]
### Which package is this feature request for?

discord.js

### Feature

Spacebar, an open source clean room design third party Discord server reimplementation, has various additional guild feature strings to enable various features per-guild. Most cases of such features are partially backwards-compatible extensions of Discord features, such as unnamed channels or cross-channel replies. Similarly, user objects on Spacebar have an additional property called `rights`, which are instance-wide permissions. However, extensions are not limited to this.

### Ideal solution or implementation

If discord.js encounters an unknown guild feature, it should not throw a fatal error. Similarly, if it receives an additional field in a response, it should gracefully handle the case.

### Other context

Nothing in this FR means third party Discord servers should be fully supported, just that unknown data received from them should not be treated as fatal errors when the endpoints are set to such servers.

**Comment by Qjuh** [comment]
Did you verify this actually does happen with the current implementation? If so would you happen to have a stack trace of such a fatal error?

**Comment by almostSouji** [comment]
We do not plan to support inofficial, custom, Discord backend servers with our library. If you encounter issues with it due to custom properties and/or features, feel free to keep a fork of the library for this purpose.
