### ISSUE TITLE
addNumberOption.setMinValue / setMaxValue accepts commas, overlapping float values

### ISSUE THREAD

**Issue by menix1337** [discordjs/discord.js#9438]
### Which package is this bug report for?

builders

### Issue description

Noticed this upon creating a addNumberOption. Not sure if this is baseline JavaScript issue, or if its anything you guys can fix up with a bandaid (If confirmed not intentional).

1. Create SlashCommandBuilder
2. Have the option `addNumberOption`
3. Put in float values such as `.setMinValue(0.1)` & `.setMaxValue(1)`
4. Notice when using the command the input `0,0.5` or `0,1` or `0,1.0` would be accepted due to commas being ignored by parseFloat values, as a result it would return `0.5` or `1` or `1.0` instead of blocking out if a comma is present.

I suppose an expected result would be the Option locking out a use of Comma, if possible. 

**Expected Result(s):**
`0,0.5 => Option error due to ,`
`0.5 => Success`
`0,1 => Option error due to ,`
`1 => Success`
`0.60 => Success`

### Code sample

```typescript
.addNumberOption((option) =>
  option
   .setName('growth')
   .setDescription('Select Growth [0.1 - 1] • Remember a Decimal Point, if below growth 1. [Example: 0.45, 0.98, 1]')
   .setRequired(true)
   .setMinValue(0.1)
   .setMaxValue(1)
)

//Inside command:
console.log(growth) 
Input: 0,1 => console.log(growth) => 1
Expected: Error due to , in input.
```

### Package version

"discord.js": "^14.8.0",

### Node.js version

Node: v19.1.0 - TS: typescript@4.9.5

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

c6ca5a8.0

**Comment by monbrey** [comment]
discord.js has no ability to control what Discord accepts for option input. I recommend you raise this issue with Discord.

**Comment by menix1337** [comment]
> discord.js has no ability to control what Discord accepts for option input. I recommend you raise this issue with Discord.

Alright, cheers!
