### ISSUE TITLE
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.

### ISSUE THREAD

**Issue by qoskxr** [discordjs/discord.js#9443]
### Which package is this bug report for?

discord.js

### Issue description

C:\Users\qoskxr\Desktop\BotCantu>node index.js
C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\Client.js:232:7) {
  code: 'DisallowedIntents'
}

Node.js v18.16.0

C:\Users\qoskxr\Desktop\BotCantu>pause
Press any key to continue . . .
Terminate batch job (Y/N)?

### Code sample

```typescript
C:\Users\qoskxr\Desktop\BotCantu>node index.js
C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\qoskxr\Desktop\BotCantu\node_modules\discord.js\src\client\Client.js:232:7) {
  code: 'DisallowedIntents'
}

Node.js v18.16.0

C:\Users\qoskxr\Desktop\BotCantu>pause
Press any key to continue . . .
Terminate batch job (Y/N)?
```

### Package version

https://www.youtube.com/watch?v=qvwS0kiW9zU&t=17s&ab_channel=MixCommunity

### Node.js version

18.16.0

### Operating system

Win 10 64x (ggOs)

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by SpaceEEC** [comment]
You were trying to use an intent that isn't enabled for your app.
Fore more information see [Gateway Intents][1] in our guide.

[1]:https://discordjs.guide/popular-topics/intents.html#privileged-intents
