### ISSUE TITLE
GuildEmoji animated boolean property bug

### ISSUE THREAD

**Issue by AceAsin** [discordjs/discord.js#9472]
### Which package is this bug report for?

discord.js

### Issue description

The **GuildEmoji** `animated` boolean property is only returning as true. I have tested with both animated and non-animated emojis. This also causes invalid links because all URLs are forced to end with `.gif`.

I used **REST** to make a **GET** request to **Routes.guildEmojis**. It returns the correct `animated` boolean property for all emojis. This means that it's not an API v10 issue.

### Versions

Discord.js 14.9.0
Node.js 16.9.0

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
Cannot reproduce. You need to show what you're doing.

**Comment by AceAsin** [comment]
I've tried the following with non-animated emojis. They all return the animated boolean property as true instead of false.

```js
await interaction.guild.emojis.fetch(<string>)
interaction.guild.emojis.cache.get(<string>)
bot.emojis.cache.get(<string>)
```

This alternative that I'm using at the moment works at getting all of the emojis from a guild with correct properties.

```js
await bot.rest.get(`/guilds/${interaction.guild.id}/emojis`)
```

**Comment by Jiralite** [comment]
> This alternative that I'm using at the moment works at getting all of the emojis from a guild with correct properties.
> 
> ```js
> await bot.rest.get(`/guilds/${interaction.guild.id}/emojis`)
> ```

This is exactly what discord.js does:

https://github.com/discordjs/discord.js/blob/77191a2e7bb98399766237a1f39eba9d06ab9de6/packages/discord.js/src/managers/GuildEmojiManager.js#L106

If you follow the code, we add it to our cache:

https://github.com/discordjs/discord.js/blob/77191a2e7bb98399766237a1f39eba9d06ab9de6/packages/discord.js/src/managers/GuildEmojiManager.js#L107-L109

Depending on whether it already exists, we create or update:

https://github.com/discordjs/discord.js/blob/77191a2e7bb98399766237a1f39eba9d06ab9de6/packages/discord.js/src/managers/CachedManager.js#L39-L54

Then finally in our `Emoji` structure, we update the `animated` property which is what Discord sends.

https://github.com/discordjs/discord.js/blob/77191a2e7bb98399766237a1f39eba9d06ab9de6/packages/discord.js/src/structures/Emoji.js#L25

There is no modification of this property. I cannot reproduce and I fail to see how this is even possible. I would also expect a lot more issues about this, being as this code has been untouched for a long time.

Have you considered:

- You are using a modified version of discord.js?
- You have a corrupted installation (somehow)?
- You have unknowingly hardcoded this to always return `true` or alike?

**Comment by AceAsin** [comment]
I appreciate the help and have finally solved the issue. I had looked through my code before but couldn't find anything until now. I mistakenly hardcoded this when I was converting all of my prefix commands to slash commands. It explains why it works fine on the public bot, but not the private bot that I use for development, also explains why using REST worked. It led me to believe that it was probably a Discord.js issue, but it wasn't since you couldn't reproduce it.
