### ISSUE TITLE
Guide on how to use the core package

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord.js#9480]
### Which application or package is this feature request for?

Guide

### Feature

Show users some examples with usage of discordjs/core, to encourage people

### Ideal solution or implementation

Make a page with this content beautifully placed inside

**Comment by Qjuh** [comment]
Using `@discordjs/core` is only encouraged for people that know what they‘re doing. So making a guide for that is not what I‘d suggest. There will definitely be a guide on how to use the next version of discord.js that uses `@discordjs/core` internally once that exists though.
