### ISSUE TITLE
Error: Cannot find package 'file-type'

### ISSUE THREAD

**Issue by JustSxm** [discordjs/discord.js#9508]
### Which package is this bug report for?

discord.js/rest

### Issue description

When making a bot in CommonJS, dynamic imports of esm modules fails.

```
Error: Cannot find package 'file-type' imported from C:\snapshot\Bot\node_modules\@discordjs\rest\dist\index.js
Did you mean to import file-type/index.js?
at new NodeError (node:internal/errors:388:5)
at packageResolve (node:internal/modules/esm/resolve:910:9)
at moduleResolve (node:internal/modules/esm/resolve:959:20)
at defaultResolve (node:internal/modules/esm/resolve:1174:11)
 at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
 at ESMLoader.import (node:internal/modules/esm/loader:404:22)
at importModuleDynamically (node:internal/modules/cjs/loader:1050:29)
at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
at importModuleDynamically (node:vm:384:46)
```

1. Create a common js application
2. Send a message with a file attached to it
3. Observe

Will anything be done for this? 
Thanks

### Versions

Discord 14.9.0
Node 18.16.0
Typescript 5.0.3

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
Can you provide a code sample?

**Comment by JustSxm** [comment]
> Can you provide a code sample?

Not easily, no. but when I look in the compiled code given we see
`var getFileType = (0, import_util.lazy)(async () => import("file-type"));`

Which does not go through the functions at the top "__toESM" and "__toCommonJS" unlike those for example:
```
var import_node_process = __toESM(require("process"));
var import_v10 = require("discord-api-types/v10");
var import_undici = require("undici");

```
It uses import instead of require

Locally it works fine, it's just when I deploy it and package it with vercel/pkg that it stops functioning, and I don't know how I to reproduce it without it

**Comment by imranbarbhuiya** [comment]
> It uses import instead of require
it uses dynamic import to load only if needed.
> Locally it works fine, it's just when I deploy it and package it with vercel/pkg that it stops functioning, and I don't know how to reproduce it without it
maybe`vercel/pkg` thinks this package isn't getting used so it doesn't bundles it

**Comment by JustSxm** [comment]
1. npm install
2. Use a discord token an a channel id in Bot.ts
3. npm run package
4. execute the package of your os in exec/
[Sample.zip](https://github.com/discordjs/discord.js/files/11401415/Sample.zip)

**Comment by didinele** [comment]
Sorry, but our bundle is correct and the package correctly works with both cjs and mjs under regular environments, so this sounds like an issue with vercel pkg or your environment.

**Comment by SalSevenSix** [comment]
This problem occurs with nexe too.
v13 works fine for me.
