### ISSUE TITLE
Infinite loop of WebSocket reconnection

### ISSUE THREAD

**Issue by GrapeColor** [discordjs/discord.js#9510]
### Which package is this bug report for?

ws

### Issue description

This can be reproduced with the following steps:  
1. Run the code sample.
2. Disconnect the execution environment from the Internet.
3. Observe the output log.(WebSocket tries to reconnect with unusual frequency.)
  
When I observed it, I was getting an infinite loop like this:  
1. An exception occurs in the try syntax of `WebSocketShard#waitForEvent()`.
2. `WebSocketShard#destroy()` is called within the catch syntax.
5. `WebSocketShard#internalConnect()` is called in `destroy()`.
6. `WebSocketShard#waitForEvent()` is called in `internalConnect()`.
  
This bug consumes system resources and brings the system down.

### Code sample

```typescript
import { Client, Events } from 'discord.js';

const client = new Client({ intents: ['Guilds'] });

client.on(Events.Debug, (message) => console.log(message));

client.login('DISCORD_TOKEN')
  .catch(console.error);
```

### Versions

- discord.js 14.10.2
- Node.js v18.16.0

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

14.11.0-dev.1683201849-51d53f5.0

**Comment by didinele** [comment]
Seems it wasn't really a case of *actually* looping, the logic was correct, it's just that when your internet connection is completely cut off, an error event would immediately fire, causing us to start over.

In practice, things were going so fast and so many events were being fired at once (and sync I/O from all the logging) that the node.js process was just behind - the connection would eventually have recovered if you gave it long enough (and if it didn't crash from all the buffered stdout).

With #9517 we now wait a little before calling `internalConnect` again in `destroy`, which should hopefully fix issues like this:
```
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json&compress=zlib-stream
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json&compress=zlib-stream
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json&compress=zlib-stream
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json&compress=zlib-stream
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.2949543313320768; waiting 12166ms
[WS => Shard 0] Resuming session
        resume url: wss://gateway-us-east1-c.discord.gg
        sequence: 2
        shard id: 0
[WS => Shard 0] Resumed and replayed 1 events
[WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[WS => Shard 0] Heartbeat acknowledged, latency of 110ms.```
