### ISSUE TITLE
SSL Routines [wrong version number]

### ISSUE THREAD

**Issue by takeshicamilo** [discordjs/discord.js#9522]
### Which package is this bug report for?

discord.js

### Issue description

My bot its basically a music player multi tool
Steps to reproduce the error:
It happen randomly and it can appear 2 minutes after start my bot, sometimes it can happen when I play music in another channel but the most of the time works good

![image](https://user-images.githubusercontent.com/60365530/236597988-b09ae28f-561e-4466-bc1b-0feff71a3013.png)

### Versions

- discordjs lastest version 
- node 20

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by LilSherlock** [comment]
`node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: 40A8EFD0F17F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:358:
] {
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
`

**Comment by LilSherlock** [comment]
``node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: 40A8EFD0F17F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:358:
] {
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
``

**Comment by kevinlul** [comment]
I recommend adding an event handler on the bot client's "error" event to log these so they don't propagate and crash your process. I think these are probably issues when communicating with Discord as ours gets this sometimes as well. Last example from July 16:

```
[Error: C037A0F7997F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 40
] {
  library: 'SSL routines',
  reason: 'sslv3 alert handshake failure',
  code: 'ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE'
}

**Comment by Qjuh** [comment]
What source do you try to play audio from? Does this happen with local files too or just when streaming from somewhere else?

**Comment by didinele** [comment]
Considering the lack of response to the above and of concrete repro steps (not to mention this is likely an I/O thing), I'll be closing this. Feel free to re-open if it re-occurs and you have more information.
