### ISSUE TITLE
Missing documentation for type ImageURLOptions 

### ISSUE THREAD

**Issue by ggggg** [discordjs/discord.js#9526]
### Which application is this bug report for?

Documentation

### Issue description

Some functions have an optional parameter that specifies the size and type of the image returned, the docs state this type is `ImageURLOptions`, yet this is found nowhere in the docs.
This type does exist https://github.com/discordjs/discord.js/blob/fc5b9c523bcf72193b72f0e3adc7537d041782e7/packages/rest/src/lib/CDN.ts#L17-L28 but is just never referenced in the docs and any link to it directs to the home page.

### Steps to Reproduce

- Go to any page referencing `ImageURLOptions` for example [avatarURL](https://discord.js.org/#/docs/discord.js/main/class/User?scrollTo=avatarURL)
- Click on `ImageURLOptions`
- Instead of giving the documentation for `ImageURLOptions` the link leads to the homepage

### Versions

Google Chrome | 112.0.5615.138 (Official Build) (64-bit) (cohort: Stable)

### Issue priority

Low (slightly annoying)

**Comment by Jiralite** [comment]
Reset your browser cache.
