### ISSUE TITLE
User.banner is undefined

### ISSUE THREAD

**Issue by huseyineergin** [discordjs/discord.js#9547]
### Which package is this bug report for?

discord.js

### Issue description

User.banner is undefined, User.bannerURL() also returns undefined even though user has a banner. It is not just for this user, every user's banner comes as undefined.

![Screenshot_1](https://user-images.githubusercontent.com/100281013/236709454-704d162b-9e95-4462-bae7-7a7be77e9c1c.png)

![Screenshot_2](https://user-images.githubusercontent.com/100281013/236709517-1a09d5f9-3b2b-4bad-aa5a-1a15e00e87da.png)

### Code sample

```typescript
export const command = {
    data: new SlashCommandBuilder()
        .setName("userinfo")
        .setDescription("Shows a user's information.")
        .addUserOption(option =>
            option
                .setName("user")
                .setDescription("User whose information will be shown.")
                .setRequired(true)
        ),
    async execute(interaction) {
        const user = interaction.options.getUser("user")

        console.log(user)
    }
}
```

### Versions

- discord.js@14.10.2
- Node.js v18.6.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

### I have tested this issue on a development release

5b8d535

**Comment by Jiralite** [comment]
Cannot reproduce; provided user id returns a banner.

**Comment by imranbarbhuiya** [comment]
https://old.discordjs.dev/#/docs/discord.js/main/class/User?scrollTo=banner
> The user must be force fetched for this property to be present or be updated
