### ISSUE TITLE
guildMemberAdd not working even when intents enabled from developer portal and client intents as well

### ISSUE THREAD

**Issue by SaumilAgrawal** [discordjs/discord.js#9550]
### Which package is this bug report for?

discord.js

### Issue description

I have provided all the necessary intents from both the developer portal as well as in the code. Still the guildMemberAdd is not firing, I have refreshed the bot multiple times, I have testing in different servers with different users, still the issue persists, I have checked all other similar issues, but the fixes stated adding the intents, which I have already applied but still the issue persists.

Any help would be highly appreciated!

### Code sample

```typescript
const { Client, GatewayIntentBits, Collection } = require(`discord.js`);
const client = new Client({ intents: [GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMessageReactions, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildPresences] });

client.on('guildMemberAdd', (guildMember) => {
    console.log("A new member just joined some server!")
})
```

### Versions

- discord.js v14.11.0
- Node.js v16.9.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

**Comment by jaw0r3k** [comment]
"Not working" may you show some information?
Also its not too much related topic for github issue, i suggest going to djs support channel

**Comment by SaumilAgrawal** [comment]
The event does not fire
