### ISSUE TITLE
Cannot set channel topic more than twice

### ISSUE THREAD

**Issue by terryli0095** [discordjs/discord.js#9558]
### Which package is this bug report for?

discord.js

### Issue description

When trying to set the channel topic, you can only do it twice. Even after restarting the bot or trying in a separate interaction.

### Code sample

```typescript
channel.setTopic('test1').then(()=> {
		channel.setTopic('test2').then(() => {
			channel.setTopic('test3').
		})
	})
```

### Versions

discord.js - 14.7.1
node - 18

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by Jiralite** [comment]
You're being rate limited.

**Comment by terryli0095** [comment]
yep just realized thanks!
