### ISSUE TITLE
Fetching members by query issue

### ISSUE THREAD

**Issue by Cass-dev-web** [discordjs/discord.js#9560]
### Which package is this bug report for?

discord.js

### Issue description

Hello,

I was messing around with code when suddenly a bit of re-used code stopped working. This bit of reused code is the following (with line numbers):
```js
159; var guildMembers = await interaction.guild.members;
160; var memberMap = (await guildMembers.fetch({ query: TargetInfo.name, limit: 1 }));
161; var member = memberMap.map((memberMap) => memberMap);
```
When running this code I get:

![image](https://github.com/discordjs/discord.js/assets/60286224/a405170e-da7d-4d2e-88ed-c9f56ea5a74c)

I've tried re-installing discord.js but it won't fix it. I've tried my old version of my entire project, and that too stopped working.

I believe I'm missing some kind of intent on discord's side.

### Versions

- `discord.js@14.11.0`
- node `v19.7.0`
- Windows 10 Education

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, MessageContent

**Comment by Jiralite** [comment]
This method requests guild members over the gateway. You are not connected to the gateway. In simple terms, you did not log in, or have not logged in yet.

**Comment by Cass-dev-web** [comment]
> This method requests guild members over the gateway. You are not connected to the gateway. In simple terms, you did not log in or have not logged in yet.

I'm able to get interactions and send messages using other commands, so why would this piece of code not work, if the issue is that i'm not logged in?

**Comment by monbrey** [comment]
This can also happen if the guild wasn't populated via the gateway, such as if it was force-fetched or the cache was cleared.

Do you have the `Guilds` intent?

**Comment by Cass-dev-web** [comment]
> This can also happen if the guild wasn't populated via the gateway, such as if it was force-fetched or the cache was cleared.
> 
> 
> 
> Do you have the `Guilds` intent?

Yes I do.

**Comment by Qjuh** [comment]
That also happens when your bot is invited into a Guild without bot scope but only applications.commands

**Comment by Cass-dev-web** [comment]
> That also happens when your bot is invited into a Guild without bot scope but only applications.commands

Ah that may be the issue as I only checked the “bot” checkbox when generating invite URL on the discord developers portal website…

**Comment by Cass-dev-web** [comment]
Seems like even after re-inviting the bot using the `application.commands` scope, it still won't work.

**Comment by Syjalo** [comment]
Could you log this?
```js
console.log(interaction.guild.constructor?.name);
console.log(interaction.guild.shardId);
console.log([...interaction.client.ws.shards.keys()]);
```

**Comment by Cass-dev-web** [comment]
> ```js
> console.log(interaction.guild.constructor?.name);
> console.log(interaction.guild.shardId);
> console.log([...interaction.client.ws.shards.keys()]);
> ```

The following was printed:

![image](https://github.com/discordjs/discord.js/assets/60286224/7d096d29-eccb-47e3-a5a4-492da27346e9)

**Comment by Syjalo** [comment]
Could you show your client options?

**Comment by Cass-dev-web** [comment]
Fixed it because a part of my code was badly written. Thanks for all you guys' help.
