### ISSUE TITLE
THE FUCKING DOCUMENTATION

### ISSUE THREAD

**Issue by dizz-pfeffel** [discordjs/discord.js#9561]
### Which application or package is this feature request for?

Documentation

### Feature

the documentation is ass. please give examples of how it can be used and update the search function as that is not helpful at all

### Ideal solution or implementation

please give examples of how it can be used and update the search function

### Alternative solutions or implementations

no.

**Comment by iCrawl** [comment]
Use the guide for this type of stuff. The documentation is an API reference to look up methods and not a tutorial.

**Comment by dizz-pfeffel** [comment]
the guide is useless aswell

**Comment by iCrawl** [comment]
That's helpful.

If you don't state what exactly your problem is, because the guide is quite literally what you asked for "examples how to use stuff".

**Comment by dizz-pfeffel** [comment]
it is literally impossible to get a list of users in a guild. everything is undefined

**Comment by iCrawl** [comment]
What have you tried so far?

**Comment by dizz-pfeffel** [comment]
too many to list my brother. like literally my friend and I have tried so many methods and none of them work

**Comment by iCrawl** [comment]
Do you have any code to show at all? You might just be missing intents, that is explained in the guide.

**Comment by Syjalo** [comment]
You can use our [Discord server](https://discord.gg/djs) for support

**Comment by dizz-pfeffel** [comment]
banned
