### ISSUE TITLE
Error: Opening handshake has timed out

### ISSUE THREAD

**Issue by LaiBaoYuan** [discordjs/discord.js#9571]
### Which package is this bug report for?

discord.js

### Issue description

the bug describe: 
> start error {
  error: Error: Opening handshake has timed out
      at ClientRequest.<anonymous> (/home/www/application_backend/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:848:7)
my behaviour:
- my service is deploy on Linux Server，and i close all firewall and proxy my network(because I from china) but don't resolve this problem.
- when I think that the problem is due to dns server analysis in error, but `/etc/resolv.conf` file have two dns domains, `8.8.8.8`and `114.114.114.114`

In a word,appeal error is only happen on my server，it's run successfully on my local machine。
I urgently seek your help，hope that i can **receive offical team help**.

### Code sample

```typescript
import { Client, GatewayIntentBits } from 'discord.js'
import { ProxyAgent } from 'undici'
export const discord = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMessages
  ],
  rest: {
    agent: new ProxyAgent('http://127.0.0.1:7890')
  }
})
discord.on('ready', () => {
  console.log('discord服务器连接成功')
})
await discord.login(discordConfig.botToken);
```

### Versions

- Discord.js@^14.11.0
- Node.js@16.10.0
- Macos 13/Apple M1 MAX

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by didinele** [comment]
This is an issue with your network connection. The TCP connection isn't established on time. You can increase the timeout using [this config option](https://discordjs.dev/docs/packages/ws/main/OptionalWebSocketManagerOptions:Interface#handshakeTimeout).
