### ISSUE TITLE
interaction.reply returnes undefined

### ISSUE THREAD

**Issue by dev-pengi** [discordjs/discord.js#9577]
### Which package is this bug report for?

discord.js

### Issue description

```js
const reply = await interaction.reply({ embeds: [embed], components: [row] });
```
the output of reply variable is undefined, is that how its supposed to be or it's some kinda bug?

### Versions

- discord.js@13.14.0
- node v18.15.0
- windows 10

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Message

### Which gateway intents are you subscribing to?

GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
> the output of reply variable is undefined, is that how its supposed to be

Per the documentation, yes: https://old.discordjs.dev/#/docs/discord.js/v13/class/CommandInteraction?scrollTo=reply

<hr>

You should ask questons in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
