### ISSUE TITLE
channelTypes Sub Command option doesn't work

### ISSUE THREAD

**Issue by shalevc1098** [discordjs/discord.js#9589]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce with below code sample:
1. Create a new Slash Command with Channel option.
2. Add `channelTypes: [ChannelType.GuildText]` to the command.
3. Start the bot and you should see that the channel is not filtered by the types provided.

![image](https://github.com/discordjs/discord.js/assets/51709332/acff30d6-ff3e-43cc-97ff-a471771c55c7)

### Code sample

```typescript
data: {
    name: 'setchannel',
    description: 'This command allows you to set a specific channel where Leveled Up messages will 
                  be sent.',
    type: ApplicationCommandOptionType.Subcommand,
    options: [
        {
            name: 'channel',
            description: 'The channel where Leveled Up messages should be sent to',
            type: ApplicationCommandOptionType.Channel,
            required: false,
            channelTypes: [ChannelType.GuildText] <----
        }
    ]
}
```

### Versions

- discord.js ^14.10.2
- Node.js 18.12.1
- typescript ^4.8.4

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, AutoModerationConfiguration, AutoModerationExecution

**Comment by Idris1401** [comment]
it's `channel_types`

**Comment by shalevc1098** [comment]
> it's `channel_types`

Yes, just figured that out. it was
```
export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
  type: ApplicationCommandOptionType.Channel;
  channelTypes?: ApplicationCommandOptionAllowedChannelTypes[];
}
```
and i changed it to
```
export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
  type: ApplicationCommandOptionType.Channel;
  channel_types?: ApplicationCommandOptionAllowedChannelTypes[];
}
```

**Comment by Jiralite** [comment]
How are you deploying your commands?

**Comment by shalevc1098** [comment]
> How are you deploying your commands?

with rest

**Comment by Jiralite** [comment]
Then this is not a bug.

> Yes, just figured that out. it was
> 
> ```
> export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
>   type: ApplicationCommandOptionType.Channel;
>   channelTypes?: ApplicationCommandOptionAllowedChannelTypes[];
> }
> ```
> 
> and i changed it to
> 
> ```
> export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
>   type: ApplicationCommandOptionType.Channel;
>   channel_types?: ApplicationCommandOptionAllowedChannelTypes[];
> }
> ```

If you are using /rest, all of this is wrong. You should not be using discord.js's types. You should be using `RESTPostAPIApplicationCommandsJSONBody` from discord-api-types.

**Comment by shalevc1098** [comment]
> Then this is not a bug.
> 
> > Yes, just figured that out. it was
> > ```
> > export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
> >   type: ApplicationCommandOptionType.Channel;
> >   channelTypes?: ApplicationCommandOptionAllowedChannelTypes[];
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and i changed it to
> > ```
> > export interface ApplicationCommandChannelOption extends BaseApplicationCommandOptionsData {
> >   type: ApplicationCommandOptionType.Channel;
> >   channel_types?: ApplicationCommandOptionAllowedChannelTypes[];
> > }
> > ```
> 
> If you are using /rest, all of this is wrong. You should not be using discord.js's types. You should be using [`RESTPostAPIApplicationCommandsJSONBody`](https://discord-api-types.dev/api/discord-api-types-v10#RESTPostAPIApplicationCommandsJSONBody) from discord-api-types.

but i made the change and it worked too. is that wrong?

**Comment by Jiralite** [comment]
It means you are typing whatever incorrectly and it coincidentally works, hence the formation of this issue. Without context, a definite answer cannot be provided.

**Comment by shalevc1098** [comment]
> It means you are typing whatever incorrectly and it coincidentally works, hence the formation of this issue. Without context, a definite answer cannot be provided.

okay, thanks for the help

**Comment by Jiralite** [comment]
> Start the bot and you should see that the channel is not filtered by the types provided.

It appears you are not reporting a typings issue in the first place, so how could modifying a type suddenly allow this to happen with no code changes?

**Comment by shalevc1098** [comment]
> > Start the bot and you should see that the channel is not filtered by the types provided.
> 
> ~It appears you are not reporting a typings issue in the first place, so how could modifying a type suddenly allow this to happen with no code changes?~ Ah I see you changed it to `channel_types` and modified a type, that explains it.

yes. are there more like this that i need to change, otherwise they wouldn't work?
