### ISSUE TITLE
ModalSubmitInteraction does't have the method Update

### ISSUE THREAD

**Issue by ifanoxy** [discordjs/discord.js#9590]
### Which package is this bug report for?

discord.js

### Issue description

In typescript when we have an interaction with the type "ModalSubmitInteraction", we can't use the property "update" without place //@ts-ignore

### Code sample

```typescript
interaction1.awaitModalSubmit({
    time: 240 * 1000
}).then(interaction => {
   //@ts-ignore without him we has a TS Error
   interaction.update({
      embeds: [],
      components: [],
      fetchReply: true
   })
}
```

### Versions

- discord.js 14.9.0
- node js v19.0.0
- Typescript 5.0.4
- Windows 10

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
Please _always_ explain why you have closed your issue. IT would help people with the same issue that come across this issue.

Duplicate of #8325.
