### ISSUE TITLE
Module not found: Can't resolve 'zlib-sync'

### ISSUE THREAD

**Issue by Joeri38** [discordjs/discord.js#9592]
### Which package is this bug report for?

discord.js

### Issue description

I've installed discord.js and when I try to import the module, I get the error:

"./node_modules/@discordjs/ws/dist/index.mjs:522:36
Module not found: Can't resolve 'zlib-sync'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/discord.js/src/index.js
./src/app/promptsection.jsx
./src/app/page.tsx"

### Versions

- discord.js 14.11.0
- Node.js 18.16.0
- macOS Monterey 12.2

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by vladfrangu** [comment]
Hold on, are you trying to bring in djs into a web page? We do not support that use-case

**Comment by Joeri38** [comment]
Yes, I am trying to trigger the discord bot when I interact with it through a Next-js website. Is that impossible to do?

**Comment by iCrawl** [comment]
Triggering it is different from actually calling a node.js module inside your browser, which is what you do.

**Comment by rharkor** [comment]
For me it doesnt work, it says :
Module not found: Can't resolve './build/Release/zlib_sync.node'

**Comment by didinele** [comment]
This is a stale issue with a very specific setup and your comment provides no additional details that could help us diagnose your problem.

Please open a new issue instead.

**Comment by ScreamZ** [comment]
@didinele 

Just run a nextJS project, and inside a server action https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations try instantiating a 

```ts
const suggestionsWhClient = new WebhookClient({
```

you'll get the error in NextJS 14

@iCrawl It's not meant to be run inside a browser, as it's server-only server action

**Comment by Jiralite** [comment]
> Please open a new issue instead.
