### ISSUE TITLE
Support new markdown features

### ISSUE THREAD

**Issue by PanSzelescik** [discordjs/discord.js#9607]
### Which application or package is this feature request for?

formatters

### Feature

Discord added headers and lists, so we can support them in formatters:
https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

### Ideal solution or implementation

Add functions in formatters like inlineCode, bold or italic

### Alternative solutions or implementations

I can prepare PR, but I'm wondering about the function names:
- bigHeader
- header
- smallHeader
- listOption

We can also add support for indenting list, maybe by a second argument not required?

**Comment by Syjalo** [comment]
I would suggest 
`#` - `headingLevel1` or `headingLevelOne`
`##` - `headingLevel2` or `headingLevelTwo`
`###` - `headingLevel3` or `headingLevelThree`
`-` - `unorderedListElement`
` -` - `indentedUnorderedListElement`
`1.` - `orderedListElement`
` 1.` - `indentedOrderedListElement`
But I think lists should be built by a function that accepts an array of elements.
