### ISSUE TITLE
Rename `User#bot` to `User#isBot` or `User#isBotUser`

### ISSUE THREAD

**Issue by libewa** [discordjs/discord.js#9608]
### Which application or package is this feature request for?

discord.js

### Feature

A major target of programming languages like JavaScript and TypeScript is readability. A lot of languages have been designed to represent English as close as possible. A part of this is using the verb “is” in boolean variables, to make `if` and `while` statements sound more natural.

### Ideal solution or implementation

Rename boolean properties of objects to include the verb “is”, to more closely resemble human language.

### Other context

For example, checking if a user is a bot user could look like this:
```js
// normal command file
const target = interaction.options.getUser('target')
if (target.isBotUser) {
  interaction.reply('You cannot target a bot user!')
} else {
  interaction.reply(`Hello, <@${target.id}>!`
}
```
instead of this:
```js
const target = interaction.options.getUser('target')
if (target.bot) {
  interaction.reply('You cannot target a bot user!')
} else {
  interaction.reply(`Hello, <@${target.id}>!`
}
```

**Comment by almostSouji** [comment]
We generally prefer to stick to API naming conventions (or translate them into camelCase where appropriate).

**Comment by Jiralite** [comment]
I don't think we want this. If we ever want to add a type guard for `isBot`/`isBotUser`, we wouldn't be able to call it `isBot()`/`isBotUser()`. What would we call it then? `isABot()`/`isABotUser()`? It's fine the way it is, especially since we follow Discord's API naming conventions.
