### ISSUE TITLE
messageReactionRemoveAll and messageReactionRemove Never gets called

### ISSUE THREAD

**Issue by burgil** [discordjs/discord.js#9620]
### Which package is this bug report for?

discord.js

### Issue description

These events never fire, but within the same code, the messageCreate does fire.

Events that never fire:

messageReactionAdd
messageReactionRemove
messageReactionRemoveAll
messageReactionRemoveEmoji

Thats a real problem we still dont have logs for when people remove all reactions, people know that and specifically abuse that for the past 2 years, as can be clearly seen on discord forums when researching for it.

### Code sample

```typescript
client.on('messageReactionRemove', (reaction, user) => {
        console.log(`${user.username} unreacted ${reaction.emoji.name} on this message: ${reaction.message.content}`)
    });
    
    client.on('messageReactionRemoveAll', (message, reaction) => {
        console.log(message, reaction)
    });
```

### Versions

"discord.js": "^13.15.0",

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by burgil** [comment]
Ideally we should have the option to see who deleted all reactions. please.

**Comment by burgil** [comment]
Update: still having the same issue even after adding the missing intents:
Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Intents.FLAGS.DIRECT_MESSAGE_REACTIONS
```
const client = new Client({
    intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Intents.FLAGS.DIRECT_MESSAGE_REACTIONS]
});
```

**Comment by burgil** [comment]
was missing the partial intents

**Comment by burgil** [comment]
but fyi even when it works, it does not tell who did it, its like on purpose evil function please fix @everyone

**Comment by Syjalo** [comment]
That's not a bug. You just missed some [partials](https://discordjs.guide/popular-topics/reactions.html#listening-for-reactions-on-old-messages).

**Comment by Syjalo** [comment]
> but fyi even when it works, it does not tell who did it, its like on purpose evil function please fix @everyone

Discord doesn't send who deleted all reaction
