### ISSUE TITLE
Internal specs added to home page

### ISSUE THREAD

**Issue by basic-programmer-python** [discordjs/discord.js#9622]
### Which application or package is this feature request for?

discord.js

### Feature

The discord.js is a versatile and a diverse module to work with every video guide deprecates with time so its better to give some internal insight in the servers working 

### Ideal solution or implementation

I feel the working can be shown in the 
![image](https://github.com/discordjs/discord.js/assets/73605379/f4fcc246-85e8-4f5a-a9dd-5b234138eb7c)
following code snippet what it does is to to create what the usage is described but not the internal implementation

### Alternative solutions or implementations

It can be added on to the docs but it doesn't make sence as wrapper class is used to hide the complex implementations and just give a useable function 

### Other context

on addtion https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links
steps to invite the bot from creating a bot to the end are not clear so better to do it in a proper way from scratch

**Comment by Qjuh** [comment]
The guide you linked to (the full guide, not the particular page you linked) does what you ask for in great detail. The screenshot you show is from the `@discordjs/core` package which is meant for leightweight access without helper methods, not for  replacing the mainlib entirely.

**Comment by basic-programmer-python** [comment]
I just wanted to add some comments which would make the life simpler like intents and what the purpose of client !

**Comment by Qjuh** [comment]
And all of those exist in the guide.
