### ISSUE TITLE
DMChannel#fetch() does not work on partial channels

### ISSUE THREAD

**Issue by OIRNOIR** [discordjs/discord.js#9624]
### Which package is this bug report for?

discord.js

### Issue description

1. Enable the Channel partial for your client
2. Create a slash command that can work in DMs (I just had mine send a basic success embed)
3. In this slash command, attempt to fetch the DM channel (because it may be partial) with:
```js
if (interaction.channel.partial) await interaction.channel.fetch();
```
4. Log the channel before and after to confirm that it is no longer partial afterwards.
5. Use the slash command in your DM channel with the bot.

Expected behavior:
Bot sends success embed, and in the console you can see that the first time the channel is logged it is partial and the second is not.

Actual behavior:
Code throws error:
```
DiscordAPIError[50035]: Invalid Form Body
0[CHANNEL_RECIPIENT_REQUIRED]: At least one channel recipient is required.
    at handleErrors (/Users/oirnoir/Documents/Projects/Bots/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/Users/oirnoir/Documents/Projects/Bots/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/Users/oirnoir/Documents/Projects/Bots/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/Users/oirnoir/Documents/Projects/Bots/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async UserManager.createDM (/Users/oirnoir/Documents/Projects/Bots/node_modules/discord.js/src/managers/UserManager.js:60:18)
```

I believe this is because partial DM channels no longer include the DMChannel#recipientId property, which is used in the DMChannel#fetch() method when it calls createDM. I can work around this issue by instead fetching the channel by its ID:
```js
await client.channels.fetch(interaction.channelId);
```

### Code sample

```typescript
"use strict";

const Discord = require('discord.js');
const client = new Discord.Client({
	partials: [
		Discord.Partials.Channel
	],
	intents: [
		Discord.IntentsBitField.Flags.DirectMessages
	]
});

client.on('interactionCreate', async interaction => {
	if (!interaction.isChatInputCommand()) return;
	console.log(interaction.channel);
	if (interaction.channel.partial) await interaction.channel.fetch(); // This line fails
	console.log(interaction.channel);
	await interaction.reply({content: "Success!"});
});

client.login(process.env.DISCORD_TOKEN);
```

### Versions

- discord.js 14.11.0
- Node.js 18.16.0
- MacOS Ventura 13.4 (Dev env)
- Linux Mint 21 (Prod env)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

DirectMessages

### I have tested this issue on a development release

df8b6e9

**Comment by OIRNOIR** [comment]
I would try to fix this myself but I should leave this to someone who knows the library better than me

**Comment by Jiralite** [comment]
Interestingly, it looks like fetching a direct message channel actually creates one instead of fetching one:

https://github.com/discordjs/discord.js/blob/df8b6e9934af5b21aa2701ce54244c38a5f133e0/packages/discord.js/src/structures/DMChannel.js#L83-L90

It probably shouldn't do that.

**Comment by OIRNOIR** [comment]
Yeah, that's what I thought as well when looking at the code, but I'm not an expert in this library so I decided it wasn't up to me to decide that.

**Comment by Qjuh** [comment]
> Returns a [DM channel](https://discord.com/developers/docs/resources/channel#channel-object) object (if one already exists, it will be returned instead).
From the Discord API docs of that POST endpoint, so while the endpoint looks like it would only create one the result should be the existing one.

**Comment by OIRNOIR** [comment]
That is true. However, if a partial DM channel is received, we still do not have the recipient ID to create the DM channel with. How can we solve this problem so that fetching a partial DM channel returns the full channel?

It seems to me that if the channel is partial, it would have already been received from the API, therefore would already exist, and so should be fetched normally by its ID?

**Comment by OIRNOIR** [comment]
> Actually @OIRNOIR, it seemed Discord does send the `recipients` array, but discord.js does not handle that. See the linked pull request for a more in-depth reason!

Cool! Thanks for the hard work to everyone involved. I just got out of a surgery so I'm rather groggy
