### ISSUE TITLE
User global name

### ISSUE THREAD

**Issue by CichyCze** [discordjs/discord.js#9628]
### Which application or package is this feature request for?

discord.js

### Feature

Discord recently added user display names.
![image](https://github.com/discordjs/discord.js/assets/35575041/4ea3641f-c1a8-42d0-93a0-77eff8bc3408)
There is no way to get that with discord.js at the moment...

### Ideal solution or implementation

Implement global_name from Discord API (https://discord.com/developers/docs/resources/user#user-object).
![image](https://github.com/discordjs/discord.js/assets/35575041/73613a90-2162-44b2-aa26-520abcd86e95)

**Comment by jaw0r3k** [comment]
Already resolved by: #9512

**Comment by Jiralite** [comment]
This has already been implemented with #9512.
