### ISSUE TITLE
client.destroy() cannot make authorized requests

### ISSUE THREAD

**Issue by YoruNoKen** [discordjs/discord.js#9636]
### Which package is this bug report for?

discord.js

### Issue description

How to reproduce:
1: Initialize client
2: use `client.destroy()`
3: watch the logs spit out `Error: Expected token to be set for this request, but none was present`

### Code sample

```typescript
async function run(message, client) {
  if (message.author.id !== "372343076578131968") {
    return message.reply("You must be the owner to use this command.");
  }
  message.reply("Terminated instance.").then(() => client.destroy());
}

module.exports = {
  name: "avatar",
  aliases: ["avatar"],
  cooldown: 5000,
  run: async ({ message, client }) => {
    await run(message, client);
  },
};
```

### Versions

    "discord.js": "^14.11.0",
    node: v18.16.0
    windows 11

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildPresences, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
Never omit your stack trace. This is especially important, because this:

> 1: Initialize client
> 2: use `client.destroy()`
> 3: watch the logs spit out `Error: Expected token to be set for this request, but none was present`

Cannot be reproducible. This method does not use your token. Did you try?

```TypeScript
import { Client, Events } from "discord.js";

const client = new Client({ intents: 0 });

client.on(Events.ClientReady, () => {
	console.log("Ready!");
	client.destroy(); // No error.
});

client.login();
```

What most likely happened is that the function was executed as soon as it was being destroyed, causing it to perform an API request (`message.reply()`), but there was no token present.

**Comment by YoruNoKen** [comment]
ah, yes. That was the issue. doing `message.reply("Terminated.").then(() => client.destroy());` solved the issue. For some reason I thought it would be async.

**Comment by Jiralite** [comment]
Your solution seems to be what you've already detailed in the issue description... are you sure about that?

The real fix is to handle your errors. You are not catching the `Promise` rejections.

**Comment by YoruNoKen** [comment]
I had the same code without the `.then` somewhere else so it was picking up the code without the `.then` instead.
