### ISSUE TITLE
Corrupted main library file?

### ISSUE THREAD

**Issue by dooznvcs** [discordjs/discord.js#9640]
### Which package is this bug report for?

discord.js

### Issue description

I tried to make a very rudimentary Discord bot. As soon as I wanted to launch it, a particular error appeared. I first thought it was from my package installer, I deleted the cache and did its update. I also deleted the folder `node_modules`. I then did it again but the same error happened

1 - Install the version `14.11.0` of discord.js

2 - Try to make a very simple bot

3 - Try to start the main file

4 - Get this error
![image](https://github.com/discordjs/discord.js/assets/118217743/1c8c7125-b910-49c6-8559-d399cf71c7f5)
`index.js` file
![image](https://github.com/discordjs/discord.js/assets/118217743/a1c49181-9727-45b5-83d9-4b0f31179c7e)
 

### Code sample

```typescript
import { Client, IntentsBitField } from 'discord.js';

export class CoddiaClient extends Client {
    public logger : Logger;

    public constructor(options: ClientOptions) {
        super(options);
        this.logger = new Logger();
    }
}

const client = new CoddiaClient({
    intents: new IntentsBitField([ 
        'MessageContent',
        'Guilds', 'GuildMessages' 
    ])
});

(async () => {
    try {
        // Log the client to Discord
        client.login('TOKEN').then(() => client.logger.info('Client connected'));
    } catch(e) {}
})();
```

### Versions

- discord.js 14.11.0
- node.js 18.13.0
- typescript 5.1.3
- windows 10 22h2

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
What is your (default) encoding?

**Comment by dooznvcs** [comment]
Where I can find this, normally it must be utf-8

**Comment by Jiralite** [comment]
You can find it in settings and search for encoding.

**Comment by dooznvcs** [comment]
UTF-8

**Comment by dooznvcs** [comment]
I found the cause of the problem. My PNPM store had corrupted files because of my hard drive is dying. I tried to do a "pnpm install" on my main SSD and everything works fine!
