### ISSUE TITLE
Screenshare / stream testing ? 

### ISSUE THREAD

**Issue by yassbeno** [discordjs/discord.js#9642]
### Which application or package is this feature request for?

discord.js

### Feature

Basically there is an ongoing bug where everyone gets disconnected at once from watching a stream on discord, how to test this and figure out the issue ? 

### Ideal solution or implementation

A simulation stream ?

**Comment by Jiralite** [comment]
Are you reporting a Discord bug?

**Comment by yassbeno** [comment]
> Are you reporting a Discord bug?

also wondering if this is reproducable on discord.js

**Comment by Jiralite** [comment]
But... bots cannot stream?

**Comment by yassbeno** [comment]
> But... bots cannot stream?

hence the "Ideal solution or implementation
A simulation stream ?"
but very well !
