### ISSUE TITLE
<user>.tag returns username#0 if the user has the new username system

### ISSUE THREAD

**Issue by chocobearxo** [discordjs/discord.js#9644]
### Which package is this bug report for?

discord.js

### Issue description

Basically just have a user object as use the `tag`.
E.g. if your username is "bob" and you are migrated into the new username system, then if you try to use `<user>.tag` where `<user>` is your user object, it will return "bob#0".

I am not really sure whether or not this is a discord.js issue or Discord issue. If this isn't a discord.js issue, then please let me know so I can create a different bug report for Discord itself instead. :)

### Code sample

```typescript
<user>.tag
```

### Versions

discord.js 14.11.0
node.js 16.15.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages

**Comment by Jiralite** [comment]
Already resolved. Just needs a release.

**Comment by RedGuy12** [comment]
(#9512)

**Comment by NullDev** [comment]
Is there an ETA for the release? Currently handling displayName and globalName (if discriminator === "0") over ugly helper functions

**Comment by Syjalo** [comment]
discord.js never gave an eta

**Comment by Coder-Tavi** [comment]
Adding onto here, @chocobearxo, this is intentional behaviour from the Discord API. See https://support-dev.discord.com/hc/en-us/articles/13667755828631#h_01H26BDRT8ASH1YVKG6HMGZ1J2

![image](https://github.com/discordjs/discord.js/assets/66774833/bbd87660-acfa-4bd0-8ce8-f65c811a4706)
