### ISSUE TITLE
Use global WebSocket constructor if available

### ISSUE THREAD

**Issue by williamhorning** [discordjs/discord.js#9645]
### Which application or package is this feature request for?

ws

### Feature

Currently, Discord.js uses the `ws` module from npm, which works just fine in Node. However, this module causes issues on alternative JS runtimes like Deno.

### Ideal solution or implementation

Discord.js should check to see if the WebSocket constructor is available globally and use that instead of the `ws` module if it's available.

### Alternative solutions or implementations

- Discord.js could use [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws)
- Deno users could wait for https://github.com/denoland/deno/pull/19412, but that would exclude users of other runtimes

### Other context

The error thrown under Deno: ![terminal screenshot](https://github.com/discordjs/discord.js/assets/68466727/2701a9a6-8070-4790-8f81-ef6d0913986a)

**Comment by jaw0r3k** [comment]
We dont support deno for this moment,
Also it would require more changes

**Comment by williamhorning** [comment]
@jaw0r3k This wouldn't just impact Deno users, this would also allow Bun users to use its WebSocket implementation, which [they claim](https://bun.sh/docs/api/websockets) is faster than the `ws` module currently used by Discord.js. I'd be willing to try to do the work needed to make this happen if it isn't that high of a priority for Discord.js at the moment.

**Comment by imranbarbhuiya** [comment]
Vladdy worked on it few months ago but didn't completed ig https://github.com/discordjs/discord.js/tree/feat/no-de-no-de

**Comment by williamhorning** [comment]
fixed by #9683
