### ISSUE TITLE
Add Guild Member

### ISSUE THREAD

**Issue by zonaxer** [discordjs/discord.js#9646]
### Which application or package is this feature request for?

discord.js

### Feature

Good afternoon, I don't know if it's intentional or if no one has noticed, but the function to add a user to a guild is missing. There's the option to modify a user (PATCH), but not to add a user (PUT).

https://discord.com/developers/docs/resources/guild#add-guild-member

### Ideal solution or implementation

  /**
   * Edits a guild member
   *
   * @see {@link https://discord.com/developers/docs/resources/guild#add-guild-member}
   * @param guildId - The id of the guild
   * @param userId - The id of the user
   * @param body - The data to use when editing the guild member
   * @param options - The options for editing the guild member
   */
  async editMember(guildId, userId, body = {}, { reason, signal } = {}) {
    return this.rest.put(import_v103.Routes.guildMember(guildId, userId), {
      reason,
      body,
      signal
    });
  }

**Comment by Jiralite** [comment]
https://old.discordjs.dev/#/docs/discord.js/main/class/GuildMemberManager?scrollTo=add
