### ISSUE TITLE
Deprecated Warning was shown multiple Times

### ISSUE THREAD

**Issue by ipexadev** [discordjs/discord.js#9657]
### Which package is this bug report for?

discord.js

### Issue description

1: Get a Bot with some Intents
2: Have multiple Events
3: Get members/users and other event infos
4: Also important to use and access the .tag 

If you log / use it actively, the deprecated warning should spam multiple times

### Code sample

```typescript
little bit complicated to provide code, because i switched back to stable
```

### Versions

- newest discord.js @dev 

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

GuildMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions

### I have tested this issue on a development release

14.11.1-dev.1687003429-766be94.0

**Comment by Jiralite** [comment]
Cannot reproduce with this code sample:

```JavaScript
import { Events } from "discord.js";
import { Client, GatewayIntentBits } from "discord.js";

const client = new Client({ intents: GatewayIntentBits.Guilds });

client.on(Events.ClientReady, async () => {
	const [user1, user2] = await Promise.all([
		client.users.fetch("652616309628207104"),
		client.users.fetch("562385499969290271"),
	]);

	for (let index = 0; index < 5000; index++) {
		user1.tag; // Warning received once only
		user2.tag; // No warning as it was emitted already
	}
});

client.login();
```

The deprecation warning is emitted once.

> little bit complicated to provide code, because i switched back to stable

It's great that you're reporting a bug, but you should confirm you can reproduce the bug you are reporting.
