### ISSUE TITLE
AbortError: Request aborted on login

### ISSUE THREAD

**Issue by 7xa5h** [discordjs/discord.js#9666]
### Which package is this bug report for?

discord.js

### Issue description

My code is pretty minimal, it's just a starting point for me and those are all the files that exist, I've been getting the same error for about 3 days, I've restarted my WiFi, disabled my firewall, restarted my computer, and even updated Deno.
I do know that Discord.js "doesn't" support Deno but a couple of days ago when I was chatting in the official DJS Discord server (which I'm currently banned from) a contributor (I don't exactly remember their name) told me that the latest version of both Deno and DJS should work together.
The issue is pretty annoying as I've tried everything I could but it still wouldn't work, and yes I did increase the timeout limit - thing - up to 5 minutes but I still get the same error, thanks.

### Code sample

```typescript
// main.ts
import { Client, GatewayIntentBits, Partials } from "discord.js";
import config from "./config.json" assert { type: "json" };

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildMessages,
  ],
  partials: [
    Partials.Channel,
    Partials.GuildMember,
    Partials.Reaction,
    Partials.ThreadMember,
    Partials.User,
  ],
});

client.config = config;

client
  .login(config.token)
  .then(() => console.log(`🟩 [LOGIN] Client logged in.`))
  .catch((err) => console.error(`🟥 [LOGIN] ${err}`));


// deno.jsonc
{
  "imports": {
    "discord.js": "./deps.ts"
  }
}


// deps.ts
export * from "npm:discord.js"
```

### Versions

- Discord.js v14.11.0
- Deno v1.34.3

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Reaction, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by Jiralite** [comment]
A quick search yields:

- https://github.com/denoland/deno/issues/16684
- https://github.com/denoland/deno/issues/16710
- https://github.com/denoland/deno/issues/19532

If there are still problems with Undici (discord.js uses this), then it's not going to work.

**Comment by 7xa5h** [comment]
> A quick search yields:
> 
> * [AbortError: Request aborted with npm specifiers denoland/deno#16684](https://github.com/denoland/deno/issues/16684)
> * [Undici doesn't work with npm specifiers denoland/deno#16710](https://github.com/denoland/deno/issues/16710)
> * [npm:undici not working (Connect Timeout Error) denoland/deno#19532](https://github.com/denoland/deno/issues/19532)
> 
> If there are still problems with Undici (discord.js uses this), then it's not going to work.

hm what do i do now? all 3 issues didnt have any fix

**Comment by 7xa5h** [comment]
on a separate note, i just realised that ws: { properties: { browser: "test" } } } doesnt exist in deno?

**Comment by Jiralite** [comment]
> hm what do i do now? all 3 issues didnt have any fix

You can help contribute to Deno with a fix! Otherwise, nothing.

> on a separate note, i just realised that ws: { properties: { browser: "test" } } } doesnt exist in deno?

This is not specific to Deno. [As documented](https://discord.com/developers/docs/topics/gateway-events#identify-identify-connection-properties), this is the library name and as such, should not be modifiable by the end user.

**Comment by 7xa5h** [comment]
> > on a separate note, i just realised that ws: { properties: { browser: "test" } } } doesnt exist in deno?
> 
> This is not specific to Deno. [As documented](https://discord.com/developers/docs/topics/gateway-events#identify-identify-connection-properties), this is the library name and as such, should not be modifiable by the end user.

that makes no sense, in the documentation it says that they exist, but i cant find "properties" anymore

**Comment by Jiralite** [comment]
> in the documentation it says that they exist

[They do not](https://old.discordjs.dev/#/docs/discord.js/14.11.0/typedef/WebsocketOptions).

**Comment by 7xa5h** [comment]
> > in the documentation it says that they exist
> 
> [They do not](https://old.discordjs.dev/#/docs/discord.js/14.11.0/typedef/WebsocketOptions).

hm then how do i emulate my discord bot to think its using a phone like how bleed does

**Comment by Syjalo** [comment]
You don't. This should be considered a bug and you shouldn't use it.
