### ISSUE TITLE
Channel's positional properties are incoherent when a channel is relocated to a new parent and back using setParent()

### ISSUE THREAD

**Issue by ninbura** [discordjs/discord.js#9668]
### Which package is this bug report for?

discord.js

### Issue description

When a channel is moved from one parent to another parent and back/forth it seems to retain it's position form a previous state. Seemingly, this causes a channel object's positional properties to inconsistently misreport.

# Example 1
```
const guild = bot.guilds.cache.get(`1100538270263291904`),
  activeVoiceCategory = bot.channels.cache.get(`1100552765228458034`),
  room2 = guild.channels.cache.get(`1121985572538417164`),
  room1 = guild.channels.cache.get(`1121985276923875370`)

room2.setParent(activeVoiceCategory.id, { lockPermissions: true })

console.log(room2.rawPosition, room2.position)
console.log(room1.rawPosition, room1.position)

// result:
0 1
0 0

// expected result (approximate)
0 0
1 1
```
![image](https://github.com/discordjs/discord.js/assets/58058942/ee0346b9-869d-40be-a681-93e3e83f5519)
![image](https://github.com/discordjs/discord.js/assets/58058942/63366635-e116-41f2-acdd-9111c09a9894)

As can be seen here positional properties are misreporting their positions, additionally when room-2 was moved to active voice with `.setParent()` it relocated to the top of the category instead of to the bottom.

# Example 2
I decided to delete some channels as others couldn't reproduce my problem. Later, I found that channels were relocating to previously set positions in previously set parents.
```
  const guild = bot.guilds.cache.get(`1100538270263291904`),
    activeVoiceCategory = bot.channels.cache.get(`1100552765228458034`),
    inactiveVoiceCategory = bot.channels.cache.get(`1100552826280742993`),
    room1 = guild.channels.cache.get(`1121985276923875370`),
    room2 = guild.channels.cache.get(`1122640725562097715`),
    room3 = guild.channels.cache.get(`1122641250324062208`),
    afk = guild.channels.cache.get(`1100560364569104516`)

  console.log(room1.rawPosition, room1.position)
  console.log(room2.rawPosition, room2.position)
  console.log(room3.rawPosition, room3.position)
  console.log(afk.rawPosition, afk.position)

  await room2.setParent(activeVoiceCategory.id, { lockPermissions: true })
  await room3.setParent(activeVoiceCategory.id, { lockPermissions: true })

  console.log(room1.rawPosition, room1.position)
  console.log(room2.rawPosition, room2.position)
  console.log(room3.rawPosition, room3.position)
  console.log(afk.rawPosition, afk.position)
```
https://github.com/discordjs/discord.js/assets/58058942/e374d97e-5b47-4daa-8173-4d1ddbfd9a46

### Versions

- discord.js 14.11.0
- node.js 19.9.0
- windows 11 22h2 (22621.1848)
- wsl 1.2.5.0
- ubuntu 22.04.2

![image](https://github.com/discordjs/discord.js/assets/58058942/be7a8793-5f53-4fbc-a9c3-0bad80033c8b)
![image](https://github.com/discordjs/discord.js/assets/58058942/91d20f74-0de1-47ea-8955-34d8ab4d1709)
![image](https://github.com/discordjs/discord.js/assets/58058942/ad9e6074-1ba0-42ce-82fc-c1ada04826db)
![image](https://github.com/discordjs/discord.js/assets/58058942/938229a1-486f-413d-a0cb-10e87d3683c9)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions, MessageContent

**Comment by Jiralite** [comment]
This cannot be a discord.js bug. The channel's (previous) position is not taken into account in the REST call, especially since you did not specify `position`.

**Comment by ninbura** [comment]
> This cannot be a discord.js bug. The channel's (previous) position is not taken into account in the REST call, especially since you did not specify `position`.

Trying to understand. Are you asserting that this is a problem with my code? Or are you asserting that this is a Discord api issue? You cannot set the position when setting the parent, unless I'm missing something.

**Comment by Jiralite** [comment]
> Are you asserting that this is a problem with my code?

I do not believe so.

When you are setting the parent of a channel, discord.js does the following:

https://github.com/discordjs/discord.js/blob/75d91b52b3ff1ea5ec82b94d1c9c127d9eac3e55/packages/discord.js/src/structures/GuildChannel.js#L316-L322

https://github.com/discordjs/discord.js/blob/75d91b52b3ff1ea5ec82b94d1c9c127d9eac3e55/packages/discord.js/src/structures/GuildChannel.js#L279-L281

As you can see, this is a helper method for the actual implementation:

https://github.com/discordjs/discord.js/blob/75d91b52b3ff1ea5ec82b94d1c9c127d9eac3e55/packages/discord.js/src/managers/GuildChannelManager.js#L272-L326

You have specified the `parent` option, so discord.js resolves its channel id. You supplied `lockPermissions` too, but that just updates the permission overwrites.

Ultimately, there is nothing that influences the position of a channel, hence it cannot be a discord.js issue, whether it is actually an issue. It could be a Discord issue though, but you'd have to investigate further and bring it up to them, possibly in Discord Developers.

<hr>

> You cannot set the position when setting the parent, unless I'm missing something.

`setParent()` is a helper method: it only performs one aspect of editing. In the actual `edit()` method, you can [edit anything (within scope)](https://old.discordjs.dev/#/docs/discord.js/main/typedef/GuildChannelEditOptions).

**Comment by ninbura** [comment]
> Ultimately, there is nothing that influences the position of a channel, hence it cannot be a discord.js issue, whether it is actually an issue. It could be a Discord issue though, but you'd have to investigate further and bring it up to them, possibly in Discord Developers.

Changing a channels parent doesn't inherently change it's position? It's position by definition cannot stay the same as it's positionally relocated to a new parent in a different position. But I guess what you're saying is that DJS itself isn't updating the channels position directly. So it'd have to be an API issue?

It's not possible that this is still not a djs issue due to the fact that the `rawPosition` isn't updating in the cache? I was thinking that djs may not be properly updating its cache when a channel's parent is changed.
