### ISSUE TITLE
the time property in createMessageComponentCollector does not trigger end event

### ISSUE THREAD

**Issue by Majoramari** [discordjs/discord.js#9669]
### Which package is this bug report for?

discord.js

### Issue description

⚠️ First of all I asked on discord server and the members couldn't reproduce, so it would be an issue because I'm using bun but I'm opening an issue to just let you know!

The timer in `createMessageComponentCollector` is not triggering the `end` event

Note: someone told me "maybe" its an issue with `setTimeout()` in bun.sh, but I assure you `setTimeout()` working fine in bun.sh, in fact i'm using `setTimeout()` to work around this issue

### Code sample

```typescript
import { Client, GatewayIntentBits } from 'discord.js';

const client = new Client({
	intents: GatewayIntentBits.Guilds,
});

client.once('ready', () => {
	console.log('Ready to test');
});

client.on('interactionCreate', async (interaction) => {
	if (!interaction.isChatInputCommand()) return;

	const response = await interaction.reply({
		content: 'Hi',
	});

	const collector = response.createMessageComponentCollector({
		filter: (i) => i.user.id == interaction.user.id,
		time: 5000, // This will not
	});

	// setTimeout(() => collector.stop(), 15000); // <== This will trigger

	collector.on('end', () => {
		console.log('Ended');
	});
});

client.login(process.env.BOT_TOKEN);
```

### Versions

- discord.js: 14.11.0
- bun.sh (I know its not supported by djs): 0.6.9
- typescript: 5.1.3
- linux: debian 11

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

**Comment by monbrey** [comment]
Given that bun isn't supported and nobody has been able to replicate this issue in Node, I'm not sure what fix you expect from us here
