### ISSUE TITLE
Multiple dev versions are published under the same commit

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord.js#9670]
### Which package is this bug report for?

discord.js

### Issue description

Previously, the publish dev versions script would skip if there had been no new commits to main since the last release. This behavior was, for some reason, changed, and now, multiple versions are being published. This is problematic for projects with dependabot as it will catch these versions and PR an update when none is needed. Additionally, I'm not sure why there are 2 non-deprecated dev versions, but that doesn't look intentional to me
![image](https://github.com/discordjs/discord.js/assets/38259440/0db74949-b9c6-4881-a812-16accd314776)

### Versions

Happening now in the v14.11.1 dev versions (which should probably be 14.12.0 ?)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
If you scroll down the list, it has always been like this since the start (version 13). There has never been a duplicate check—you're just noticing it now.

> Additionally, I'm not sure why there are 2 non-deprecated dev versions

The script runs every 12 hours, but deprecations run daily. Maybe this could be tweaked?

**Comment by ImRodry** [comment]
Nope, I am absolutely sure it did use to skip duplicated versions back in v13, I can even recall seeing a PR that added that. Wasn’t like that since the very beginning but that was introduced quite early on

**Comment by ImRodry** [comment]
Here it is: #6879

**Comment by Jiralite** [comment]
Looks like https://github.com/discordjs/discord.js/commit/78d013f87ca980386b044e048084ee49b690ec36 removed it then.

**Comment by ImRodry** [comment]
Is there a reason why @iCrawl ?

**Comment by RedGuy12** [comment]
he originally called this change [pointless](https://github.com/discordjs/discord.js/pull/6872#issuecomment-948739076) but then he did merge #6879 anyways

**Comment by ImRodry** [comment]
Ah ye, but it’s not pointless, it fucks with dependabot and spams the version tree

**Comment by RedGuy12** [comment]
Bump, could we please get this change reverted or explained?
