### ISSUE TITLE
AutomoderationRule Create

### ISSUE THREAD

**Issue by Gotowka** [discordjs/discord.js#9674]
### Which package is this bug report for?

discord.js

### Issue description

triggerType is only reading if it's writing in function ({...})
Running code 1: error
Running code 2: working

Code 1:
```js
      const settings = {
        name: 'dawda',
        eventType: 'MESSAGE_SEND',
        triggerType: 'SPAM',
        enabled: true,
        actions: [{ type: "SEND_ALERT_MESSAGE", metadata: { channel: targetChannel } }, { type: "BLOCK_MESSAGE" }]
      };
      await interaction.guild.autoModerationRules.create(settings)
```
Code 2:
```js
await interaction.guild.autoModerationRules.create({ name: 'test', eventType: 1, triggerType: "SPAM", actions: [{ type: 1 }], enabled: true })
```
![image](https://github.com/discordjs/discord.js/assets/89851069/77948cd3-6deb-45a8-a9f3-6dfe5786c2bd)

### Versions

- discord.js: 13.16.0
- nodejs: 18.15.0

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

AutoModerationConfiguration

**Comment by jaw0r3k** [comment]
Are you sure that you are using v13?
Your code would be working then
But in v14 it wont

**Comment by Jiralite** [comment]
Cannot reproduce with your code sample on 13.16.0 (reported version):

```JavaScript
const settings = {
	name: "dawda",
	eventType: "MESSAGE_SEND",
	triggerType: "SPAM",
	enabled: true,
	actions: [{ type: "SEND_ALERT_MESSAGE", metadata: { channel } }, { type: "BLOCK_MESSAGE" }],
};

await channel?.guild.autoModerationRules.create(settings);
```

<img width="705" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/71a01e37-eb1a-4c25-913e-8fe5a17ef808">

**Comment by Gotowka** [comment]
Now it's working idk why but then I'm sure I used v13
