### ISSUE TITLE
ShardingManager doesnt work with .ts files

### ISSUE THREAD

**Issue by KevinWh0** [discordjs/discord.js#9675]
### Which package is this bug report for?

discord.js

### Issue description

Steps:
Setup a typescript discord.js project
Add sharding like seen below with a ts file.
You should see an error like TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\PATH\src\bot.ts

Here is my tsconfig
```json
{
    "compilerOptions": {
        "lib": ["ESNext"],
        "module": "ESNext",
        "moduleResolution": "node",
        "target": "ESNext",
        "outDir": "dist",
        "sourceMap": false,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "resolveJsonModule": true,
        "importHelpers": true
    },
    "include": ["src", "environment.d.ts"],
    "exclude": ["node_modules", "**/*.spec.ts"]
}
```

### Code sample

```typescript
const manager = new ShardingManager("./src/bot.ts", {
  totalShards: "auto",
  token,
});
```

### Versions

- discord.js 14.11.0
- Node.js v18.14.0
- Ts Version 5.1.5
- Windows 11 Home

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

75d91b5.0

**Comment by Syjalo** [comment]
You compile your `.ts` and run `.js` so you should use `.js`

**Comment by Jiralite** [comment]
As said above, you need to compile TypeScript to run it. This is a fundamental concept (the most) with plenty of guides for you to learn online.

**Comment by Trickyhuntero** [comment]
that worked for me because I ran the wrong script I thought I was compiling then running the app nut wasn't
@KevinWh0 I recommend installing "concurrently" and "nodemon" then add this script
`concurrently \"tsc -W\" \"nodemon ./build/shard.js\"`
