### ISSUE TITLE
@everyone role contains no members

### ISSUE THREAD

**Issue by GodderE2D** [discordjs/discord.js#9684]
### Which package is this bug report for?

discord.js

### Issue description

In `discord.js@dev`, the `@everyone` role contains no members.

To reproduce, simply run the code sample below and observe the number returned.

- Expected: Should return the guild's member count
- Actual result: No members are in the Collection, therefore 0 is returned

A simple workaround is to use `Guild.memberCount`, however this is still a bug and works in 14.11.0.

---

Could be related to:
- https://github.com/discordjs/discord.js/pull/9529

Also see: https://discord.com/channels/222078108977594368/937420598383108167/1125273078453256283

### Code sample

```typescript
// The @everyone role id is identical to the guild id
<RoleManager>.cache.get(message.guild.id).members.size
```

### Versions

- [`discord.js@14.11.1-dev.1688429484-75d91b5.0`](https://www.npmjs.com/package/discord.js/v/14.11.1-dev.1688429484-75d91b5.0)
- Node.js 18.16.1
- Ubuntu 22.04 LTS

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

75d91b5

**Comment by Syjalo** [comment]
Did you fetch members first?

**Comment by imranbarbhuiya** [comment]
did u fetch the members before checking cache size? maybe no members were cached so its showing 0. Also u should always use `guild.memberCount` instead of `<RoleManager>.cache.get(message.guild.id).members.size` or `message.members.cache.size` as these methods only shows cached members

**Comment by GodderE2D** [comment]
It still shouldn't show 0 as the bot member would be cached. But even after I fetch members it's still 0.
