### ISSUE TITLE
@discordjs/ws throttler wait for identify don't handle errors properly

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#9688]
### Which package is this bug report for?

ws

### Issue description

The [IIdentifyThrottler.ts](https://github.com/discordjs/discord.js/blob/main/packages/ws/src/throttling/IIdentifyThrottler.ts) waitForIdentify method errors is not being handled by the ws package. 

While this works in the SimpleIdentifyThrottler, this will introduce issues when you extend the IdentifyThrottler depending on your needs. You can't be sure that only the shard that sends an abort signal is the only thing that will error here, hence if you do nothing, your shard will be just left connected and heartbeating without any actual connection in it. 

To reproduce, just spawn 2 shards, let the first identify, then throw an error on the 2nd shard when it will identify, you will be left with a shard that didn't identify and a potential memory leak due to the promise not resolving and not being removed from map. This could be a big issue as this will make the bot offline in shards where it didn't identify 

A fix is to let the WebsocketShard class detect if something errored in waitForIdentify, and check if it's already closed. if not closed, destroy and reconnect.

### Versions

- ws: 0.8.3

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by didinele** [comment]
This is more of a feature request in actuality, as per this comment, this is intended behavior at this time:
https://github.com/discordjs/discord.js/blob/df40dcdb850c398642ebc5cd6e4c48034280f464/packages/ws/src/throttling/IIdentifyThrottler.ts#L7-L9

But indeed, it is less than ideal.
