### ISSUE TITLE
Nextjs + @discordjs/core - Module not found: Can't resolve 'zlib-sync'

### ISSUE THREAD

**Issue by yatsukiuwu** [discordjs/discord.js#9695]
### Which package is this bug report for?

discordjs/core

### Issue description

I am currently encountering what appears to be an issue with Next.js while running a project with its latest version. After placing the code within an API route and then executing "npm run dev", I'm experiencing a module not found error. 

Steps to reproduce are as follows:

1. Set up a Next.js project using the latest version.
2. Put the code within an API route.
3. Run the command "npm run dev".

Upon following these steps, the stated module not found error shows Interestingly, when i  do a manual installation of the package, webpack throws an additional error stating that it cannot compile. 

### Code sample

```typescript
import { NextRequest, NextResponse } from "next/server";
import { REST } from "@discordjs/rest";
import { API } from "@discordjs/core";
import { getServerSession } from "next-auth";

export async function GET(req: NextRequest) {
  const session = await getServerSession();

  if (!session) {
    return NextResponse.json({ error: "invalid session" }, { status: 401 });
  }

  const discordRest = new REST({ version: "10" }).setToken(process.env.DISCORD_TOKEN!);
  const discordApi = new API(discordRest);

  console.log(discordApi);

  return NextResponse.json({ session: session });
}
```

### Versions

"@discordjs/core": "^0.6.0",
"next": "13.4.9",

nodejs : v18.12.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by suneettipirneni** [comment]
Try importing from `@discordjs/core/http-only` and see if that works.

**Comment by yatsukiuwu** [comment]
> Try importing from `@discordjs/core/http-only` and see if that works.

![image](https://github.com/discordjs/discord.js/assets/72000809/9cb2bd76-cb0e-4d1a-88ae-30e6ce3130d9)
do i need to install a canary version or something ?

**Comment by suneettipirneni** [comment]
It might a typescript quirk, but if you’re on the latest version that import should work. Try ignoring the error and running it.

**Comment by vladfrangu** [comment]
Not a Typescript quirk, you'll need to set moduleResolution to node16 in your tsconfig.json

**Comment by yatsukiuwu** [comment]
> It might a typescript quirk, but if you’re on the latest version that import should work. Try ignoring the error and running it.

did a //@ts-ignore and it worked ! thanks
