### ISSUE TITLE
getVoiceConnection sometimes return wrong channel

### ISSUE THREAD

**Issue by AlexInCube** [discordjs/discord.js#9707]
### Which package is this bug report for?

voice

### Issue description

I'm trying to do a check to see if the person requesting the command is in a voice channel with the bot. But when I have the bot running for about ~20 hours, getVoiceConnection starts returning the channel the bot was once on a long time ago, not the channel it's currently on.

Steps to reproduce:
I don`t know how to reproduce. I can guess that this is due to packet loss at some point and the "map" where voiceConnection is stored is not cleared.

### Code sample

```typescript
export function checkBotInVoice(guild: Guild): VoiceConnection | undefined{
    return getVoiceConnection(guild.id)
}

export async function checkMemberInVoiceWithBot(member: GuildMember): Promise<{ errorMessage: string; channelTheSame: boolean }> {
    const response = {
        channelTheSame: false,
        errorMessage: "CheckingVoiceError"
    }

    const connection = checkBotInVoice(member.guild)
    if (connection) {
        if (member.voice.channel) {
            response.channelTheSame = connection.joinConfig.channelId === member.voice?.channel.id
            if (response.channelTheSame){
                return response
            }
        }else{
            response.errorMessage = i18next.t("commandshandlers:voice_join_in_any_channel")
            return response
        }

        await member.guild.client.channels.fetch(connection.joinConfig.channelId!).then(channel => {
            if (channel) {
                if (channel instanceof VoiceChannel) {
                    response.errorMessage = `${i18next.t("commandshandlers:voice_join_in_channel")} ${channel.name}`
                }
            }
        })
    }

    return response
}
```

### Versions

- discord.js 16.11.0
- node.js 20.2.0
- typescript 5.1.6

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, DirectMessages, DirectMessageTyping, MessageContent

**Comment by Qjuh** [comment]
The VoiceConnection is the right one. Your assumption of `<VoiceConnection>.joinConfig.channelId` being the channel the bot currently is in is wrong though. It‘s the channelId used to initially connect/join.
To find the channel the bot currently is in you‘d simply use `<Guild>.members.me.voice.channelId`.

**Comment by AlexInCube** [comment]
I've already realized that I have to go through members.me.voice.
