### ISSUE TITLE
Thread members are not handled correctly

### ISSUE THREAD

**Issue by mq1n** [discordjs/discord.js#9724]
### Which package is this bug report for?

discord.js

### Issue description

1) Create a handle to a thread
2) Get thread members collection from cache property
3) Some members does not exist in handled cache collection 

Thread from Discord UI;
https://i.imgur.com/QwrratK.png
Members collection result from debugger;
https://i.imgur.com/GGLreNo.png
https://i.imgur.com/oF1TlLf.png
REST result (working well);
https://i.imgur.com/jPOATgZ.png

### Code sample

```typescript
const channel = ...
const thread = await channel.threads.cache.find(x => x.name === `...`);
const members = [...thread.members.cache.values()];
```

### Versions

- discord.js 14.11.0
- Node.js 18.12.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

ThreadMember

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by Qjuh** [comment]
Like with any member cache you need to fetch the members to have all of them cached. By default only those that interacted with your bot in any way are cached because of the gateway events received containing their data.
