### ISSUE TITLE
`ButtonComponentData` fails type guard field check

### ISSUE THREAD

**Issue by hker9527** [discordjs/discord.js#9734]
### Which package is this bug report for?

discord.js

### Issue description

When using `.type` field to check for component type, the result will always include `ButtonComponentData` as it has no definition of `.type` which falls back to the base definition of `type: ComponentType`.

### Code sample

```typescript
import { ButtonComponentData, StringSelectMenuComponentData, UserSelectMenuComponentData } from "discord.js";

type Example1 = (
    | ButtonComponentData
    | StringSelectMenuComponentData
    | UserSelectMenuComponentData
);

type Example2 = (
    | StringSelectMenuComponentData
    | UserSelectMenuComponentData
);

const example1: Example1 = {} as any;
const example2: Example2 = {} as any;

if (example1.type === ComponentType.StringSelect) {
    // Type of example1: ButtonComponentData | StringSelectMenuComponentData
}

if (example2.type === ComponentType.StringSelect) {
    // Type of example2: StringSelectMenuComponentData
}
```

### Versions

- discord.js 14.11.1
- Node.js 18.16.0
- TypeScript 4.9.5

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
Why is this a discord.js bug though? Isn't this just a basic TypeScript issue?
