### ISSUE TITLE
Don't include dom types

### ISSUE THREAD

**Issue by leumasme** [discordjs/discord.js#9737]
### Which package is this bug report for?

discord.js

### Issue description

discord.js currently includes the dom types lib in its main types.d.ts
https://github.com/discordjs/discord.js/blob/8f4256db8a52ac08359d0b3436f41b641ac4e382/packages/discord.js/typings/index.d.ts#L1-L2
This leads to anyone importing discord.js into their project having dom types globally available (such as `document`, `window`, `HTMLDivElement`, ...)  
These types are of course false, since most discord.js projects will run in node and not in the browser.  
Looking at the comment ` // DOM types required for undici`, it seems to reference [the experimental `fetch` global](https://nodejs.org/api/globals.html#fetch) that was [recently added](https://github.com/nodejs/node/pull/41749) to nodejs.  
This fetch global internally uses `undici`, which is what that comment is likely referencing, since [the undici npm package](https://www.npmjs.com/package/undici) is properly typed out of the box.   

I could not find any references to the global fetch in the code from a very brief search, so I'm assuming a bit here - however since you already depend on undici anyway:
https://github.com/discordjs/discord.js/blob/8f4256db8a52ac08359d0b3436f41b641ac4e382/packages/discord.js/package.json#L65
using the global fetch would not make much sense. You are using an untyped experimental api that is only available in recent node versions, even though you have that same fetch function already installed as a dependency.

To clarify what difference this one line ` /// <reference lib="dom" />` makes, here are autocompletion suggestions when importing discord.js vs when not importing it:
![image](https://github.com/discordjs/discord.js/assets/29953391/51cf1b7b-0bda-47a1-bc5a-9953334ff0ac)
![image](https://github.com/discordjs/discord.js/assets/29953391/d642b150-fe58-4307-8853-5e422ef6c4f6)
As soon as discord.js is imported, typescript/vscode will start suggesting browser-only variables and classes. This makes this issue unavoidable, since it occours in your whole project as soon as you simply import discord.js, which is why I'd argue that this is not low priority.

Relevant:
https://github.com/discordjs/discord.js/commit/d0c82561b8a1765a1daa362ca903f3ffb3fa33ee by @favna introduced this issue
[[A](https://ptb.discord.com/channels/222078108977594368/1134145116844605531/1134145116844605531)] [[B](https://ptb.discord.com/channels/222078108977594368/937420598383108167/1131543523313848390)] Some brief conversation regarding this issue on the discord.js discord server

### Versions

- discord.js v14.11.0
- NodeJS v18.16.1
- Typescript v5.1.6

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by KhafraDev** [comment]
if this is an issue in undici i'd be glad to fix the types, why is this required?
