### ISSUE TITLE
Nickname is always null, bot has right permissions and intents

### ISSUE THREAD

**Issue by mgajic** [discordjs/discord.js#9749]
### Which package is this bug report for?

discord.js

### Issue description

1. Fetch a guild
2. Fetch a member inside guild
3. Username is not null, **but nickname is always null**
4. On update guild member event, nickname is present, but when fetching it from guild its not
5. Bot has all the permissions and intents, and it worked before

### Versions

-discord 13 & 14

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

GuildMember

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by Idris1401** [comment]
![image](https://github.com/discordjs/discord.js/assets/78701338/0071f1ff-0617-42a3-9da0-0c22e695d959)

**Comment by mgajic** [comment]
Hey, thanks for responding, is there any other way then interaction? 
So I want to trigger it by myself...want to iterate through all users and check for problematic nicknames?

**Comment by mgajic** [comment]
Hey thanks for replying. Is there any other way to fetch the nickname, without interaction?
My use case is to iterate through all users and check for problematic nicknames.

**Comment by SpaceEEC** [comment]
Could you provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) for this?

**Comment by mgajic** [comment]
let guild =   await client.guilds.fetch("someIDofTheguild");
    guild.members
        .fetch()
        .then((fetchedMembers) => {
            fetchedMembers.forEach(function (m) {
                if(m.id == "memberID"){
                    console.log('Nickname is null, and display name is null, but username is there');
                }

            });
        })

**Comment by Jiralite** [comment]
We are not able to reproduce this. We can reopen this with reproducible steps, but from the looks of it, perhaps they just don't have a nickname.
