### ISSUE TITLE
Object GuildEmoji for guildAuditLogEntryCreate event

### ISSUE THREAD

**Issue by GraVitYLuxurY** [discordjs/discord.js#9758]
### Which package is this bug report for?

discord.js

### Issue description

Hello !
For the guildAuditLogEntryCreate event, the GuildEmoji object in the `target` property is not assigned if the emoji is created, but if it is modified or deleted, the GuildEmoji object is in the `target` property.

### Code sample

```typescript
module.exports = async (client, auditLogEntry, guild) => {
if(auditLogEntry.action == 60) return console.log(auditLogEntry.target)
}
```

### Versions

- discord.js 14.12.1
- node.js 18.17.0
- Windows 10

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, MessageContent, AutoModerationExecution

**Comment by Jiralite** [comment]
You need the `GUILD_EMOJIS_AND_STICKERS` intent. This is not a bug.

**Comment by GraVitYLuxurY** [comment]
> You need the `GuildEmojisAndStickers` intent. This is not a bug.

Okay, I see, sorry, but in that case why does the GuildEmoji object still appear if we don't have the intent to modify and delete an emoji?

**Comment by Jiralite** [comment]
The structure did not appear to me when I created and deleted the emoji. You were likely doing something regarding it that caused discord.js to fetch it via REST. This is irrespective of the issue: to receive gateway events for emojis, you must specify the,

**Comment by GraVitYLuxurY** [comment]
> The structure did not appear to me when I created and deleted the emoji. You were likely doing something regarding it that caused discord.js to fetch it via REST. This is irrespective of the issue: to receive gateway events for emojis, you must specify them.

Okay, thank you for your reply and sorry, is it possible to completely remove my issue please?

**Comment by GraVitYLuxurY** [comment]
> 

? @Jiralite
