### ISSUE TITLE
Max messages in cache is not working

### ISSUE THREAD

**Issue by GuiguiBlocCraft** [discordjs/discord.js#9759]
### Which package is this bug report for?

discord.js

### Issue description

Max limit for messages is not limit, even if I don't have `makeCache` parameter in Client variable (or if I force `makeCache` to 200 messages, it's broken).

### Code sample

```typescript
const client = new Client({
    intents: config.intents,
    partials: [Partials.Channel]
})
```

### Versions

- discord.js 14.12.0
- Node.js 18.17.0
- Windows 10 x64

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers, GuildVoiceStates, GuildPresences, GuildMessages

**Comment by kevinlul** [comment]
After seeing the 14.13.0 update come out, we determined it was most likely this causing memory leaks in our bot.
