### ISSUE TITLE
Support Custom status on activity objects 

### ISSUE THREAD

**Issue by FabienBounoir** [discordjs/discord.js#9760]
### Which application or package is this feature request for?

discord.js

### Feature

Discord gave the possibility to accept custom status on the bot thanks to the "state" element in the object activity objects (https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-structure)

<img width="1097" alt="image" src="https://github.com/discordjs/discord.js/assets/71253960/65813d91-1edd-4996-83d9-d5eac0fdea9e">

### Ideal solution or implementation

Just add the state element in activity object 

### Other context

Change log:
https://discord.com/developers/docs/change-log#activity-state-for-bot-users

<img width="1097" alt="image" src="https://github.com/discordjs/discord.js/assets/71253960/143b93a8-28c9-4777-a429-5a7bd4ce0052">

**Comment by Jiralite** [comment]
I've linked the pull request that implements custom status. Be sure to search existing pull requests and issues! It could have saved you typing this up.
