### ISSUE TITLE
UnsupportedCacheOverwriteWarning when using TSX

### ISSUE THREAD

**Issue by SomeAspy** [discordjs/discord.js#9770]
### Which package is this bug report for?

discord.js

### Issue description

When using [TSX](https://github.com/esbuild-kit/tsx) as opposed to building with TSC or running with TS-Node, TSX renames the Collection class to `_Collection` which triggers the UnsupportedCacheOverwriteWarning warning.

This is reproducible by running TS code with  TSX
1. Use any discord TS bot.
2. Use TSX to run the code.
3. Warnings will manifest.

### Code sample

```typescript
import {
    Client,
    GatewayIntentBits,
    Events,
} from 'discord.js';
import credentials from './config/credentials.json' assert { type: 'json' };

// Create a new client instance
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

// When the client is ready, run this code (only once)
// We use 'c' for the event parameter to keep it separate from the already defined 'client'
client.once(Events.ClientReady, (c) => {
    console.log(`Ready! Logged in as ${c.user.tag}`);
    console.log(client.guilds.cache.constructor.name); // will log "_Collection" when using TSX
});

// Log in to Discord with your client's token
client.login(credentials.DiscordToken);
```

### Versions

- Node 20.5.0
- Discord.js 14.12.1
- TSX 3.12.7
- Arch linux

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

9ed1b59df

**Comment by Lemonaut** [comment]
i also use TSX and this warning only seems to have popped up today when i updated to discord.js v14.13

**Comment by filename24** [comment]
builded js file a same errors

**Comment by JadeMin** [comment]
+1 same here

**Comment by SuperchupuDev** [comment]
this does not happen to me anymore in tsx `3.12.8`

**Comment by SomeAspy** [comment]
This appears to be fixed- Thanks guys!
