### ISSUE TITLE
Syntax Error in index.d.ts

### ISSUE THREAD

**Issue by lnadi17** [discordjs/discord.js#9783]
### Which package is this bug report for?

discord.js

### Issue description

I have Syntax Error in `index.d.ts` file which prevents resolution of types for some functions. I am using WebStorm. This happens on these two lines:

```typescript
public getChannel<const T extends ChannelType = ChannelType>(
...
public getChannel<const T extends ChannelType = ChannelType>(
```

Removing `const` keyword fixes my issue but this requires changing module file.

### Versions

discord.js 14.13.0
node 19.9.0
typescript 5.1.6

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
This is not a syntax issue.

**Comment by StrangeGirlMurph** [comment]
Using ts version 5 and up fixed this for me

**Comment by Jiralite** [comment]
If you look closely, the blog post is announcing version 5. So yes, that will fix it.
