### ISSUE TITLE
Update to Node Requirement 16.11.0 Breaks previous releases of Discord.js

### ISSUE THREAD

**Issue by nathanjml** [discordjs/discord.js#9792]
### Which package is this bug report for?

discord.js

### Issue description

1. Initialize a fresh directory with a package.json file
2. Ensure environment is running an earlier version of Node (i.e., 16.9.1)
3. Install an earlier release of discord.js that should be compatible with earlier Node version (i.e., `yarn add discord.js@14.1.0`)

package manager cannot install packages because it is trying to install packages such as @discordjs/builders@1.6.5 which expects Node >=16.11.0.

I expect to be able to use an earlier release of Discord.js version 14 without needing to use Node >= 16.11.0. 

### Versions

- discord.js 14.x.x (up to latest release of 14.13.0)
- Node.js 16.9.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by robert4049** [comment]
I can confirm we're having the same issue.

**Comment by monbrey** [comment]
You can still do this, however you will need to override the dependencies to their earlier versions in package.json.

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by robert4049** [comment]
I did the following, and am experiencing the same issue, am I perhaps misunderstanding something?

`{
  "overrides": {
	"discord.js" : {
		"builders": "1.6.4",
		"formatters": "0.3.1",
		"util": "1.0.0",
		"rest": "2.0.0",
		"ws": "1.0.0",
		"collection": "1.5.2"
	}
  },
  "dependencies": {
	"discord.js": "14.12.1",
    "jsonc-parser": "^3.2.0",
    "node-fetch": ">=2.6.7 <3.0.0"
  }
}
`

**Comment by Jiralite** [comment]
You need to use the package names in that nested object—you've dropped the `@discordjs` prefix.

To explain, discord.js does not have a `builders` dependency. discord.js has a `@discordjs/builders` dependency. All but one of those overrides work—the one that does work is `ws`, which downgrades `ws` from ^8.13.0 to 1.0.0. Definitely bad!

**Comment by robert4049** [comment]
I tried with both variations with no success

`{
  "overrides": {
		"@discordjs/builders": "1.6.4",
		"@discordjs/formatters": "0.3.1",
		"@discordjs/util": "1.0.0",
		"@discordjs/rest": "2.0.0",
		"@discordjs/ws": "1.0.0",
		"@discordjs/collection": "1.5.2"
  },
  "dependencies": {
    "discord.js": "14.12.1",
    "jsonc-parser": "^3.2.0",
    "node-fetch": ">=2.6.7 <3.0.0"
  }
}`

`{
  "overrides": {
    "discord.js" : {
      "@discordjs/builders": "1.6.4",
      "@discordjs/formatters": "0.3.1",
      "@discordjs/util": "1.0.0",
      "@discordjs/rest": "2.0.0",
      "@discordjs/ws": "1.0.0",
      "@discordjs/collection": "1.5.2"
    }
  },
  "dependencies": {
    "discord.js": "14.12.1",
    "jsonc-parser": "^3.2.0",
    "node-fetch": ">=2.6.7 <3.0.0"
  }
}`

**Comment by robert4049** [comment]
Sorry newb to this type of development, i'm using yarn so i needed to change it to resolutions.

**Comment by Jiralite** [comment]
Here's a better question: why not update Node.js?

16.x isn't even active LTS. It's that old. It's in maintenance only. The current version is 20.x, and LTS is 18.x. In fact, it seems 16.13.0 was the first version of 16.x that became LTS back then. That means if you're using versions before this, they were never LTS.
