### ISSUE TITLE
create-discord-bot eslint bug

### ISSUE THREAD

**Issue by FlowSwift** [discordjs/discord.js#9807]
### Which package is this bug report for?

create-discord-bot

### Issue description

Seems like create-discord-bot is not working properly and eslint is being configured wrong from my understanding.
What I did:
Installed the eslint extension.
npx create-discord-bot . and installed the typescript version
I then get in vscode the following:
`Missing file extension "ts" for "./util/loaders.js"` for all the imports

### Versions

Everything is latest version on a linux 22.04

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by jaw0r3k** [comment]
Fixed by e1ae7b4d5779b4006e8769879713cc9382d37dbe
