### ISSUE TITLE
Running create-discord-bot yields a node:fs/promises cp error

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord.js#9810]
### Which package is this bug report for?

create-discord-bot

### Issue description

1. Build the create-discord-bot package
2. Run the dist file with deno
![image](https://github.com/discordjs/discord.js/assets/76836550/0b132ef4-2196-4fb4-b9dd-412968943a50)

### Versions

deno 1.36.2 (release, x86_64-pc-windows-msvc)
v8 11.7.439.1
typescript 5.1.6

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

7157748fe3a69265896adf0450cd3f37acbcf97b (Latest)

**Comment by didinele** [comment]
Does this still happen?

**Comment by jaw0r3k** [comment]
Well it shouldnt
But it do
![image](https://github.com/discordjs/discord.js/assets/76836550/047b718e-a7bd-4ec6-8a98-6eba2ad962b2)
But i have latest version and promises cp exists
![image](https://github.com/discordjs/discord.js/assets/76836550/f304ac70-ab69-4504-8e21-83b6f121d8db)

And the function was added to promises struct so maybe i am doing something wrong https://github.com/littledivy/deno/blob/20bb2c8daaba6b78710a24014828f3db90e4e807/ext/node/polyfills/fs.ts#L141

**Comment by jaw0r3k** [comment]
Well this works 
![image](https://github.com/discordjs/discord.js/assets/76836550/efe97e89-c668-4714-8688-ecb49db2a3a3)

**Comment by didinele** [comment]
Seems like a deno issue still? Should probably open another one on their end.

**Comment by Jiralite** [comment]
Does [1.40.4](https://github.com/denoland/deno/releases/tag/v1.40.4) still have this issue, as https://github.com/denoland/deno/pull/22263 was a part of it?

**Comment by jaw0r3k** [comment]
This error was fixed.
But there is a next strange one
<img src="https://github.com/discordjs/discord.js/assets/76836550/62b394ba-3870-45a6-bd70-7b1d4d4da4e6" height="60px" />

As the structure is created as:
<img src="https://github.com/discordjs/discord.js/assets/76836550/a61db354-1321-4fef-b6e4-e639867108c4" height="100px" /> 
So somehow is is created within Typescript folder

**Comment by Jiralite** [comment]
Since this was a Deno issue and not a discord.js issue, I'll be closing this.

> This error was fixed. But there is another strange one <img alt="" height="60px" src="https://private-user-images.githubusercontent.com/76836550/304757990-62b394ba-3870-45a6-bd70-7b1d4d4da4e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTE3NjYsIm5iZiI6MTcxNzk1MTQ2NiwicGF0aCI6Ii83NjgzNjU1MC8zMDQ3NTc5OTAtNjJiMzk0YmEtMzg3MC00NWE2LWJkNzAtN2IxZDRkNGRhNGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjQyMTI2OTA5NWUzODA0NzA1OWI4YWQ1YjY2MTkyNTAzZmI0OGZlNDY3MjUyY2VmYTM4ZTlmNWM0NDhmZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xVGNXlLxhGoqJqSBUxic1ZbXwgpdvs3POMuoG0VLOQ0">
> 
> As the structure is created as: <img alt="" height="100px" src="https://private-user-images.githubusercontent.com/76836550/304758469-a61db354-1321-4fef-b6e4-e639867108c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTE3NjYsIm5iZiI6MTcxNzk1MTQ2NiwicGF0aCI6Ii83NjgzNjU1MC8zMDQ3NTg0NjktYTYxZGIzNTQtMTMyMS00ZmVmLWI2ZTQtZTYzOTg2NzEwOGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjEwMDJiOTU3OWU2YTNkZjJlODczMjQwZGE2MGFlNTMxZjQ3MWE4YmYwNjFhM2I0ZjU1Y2QzNzkyZDA2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBAS4sobmNiK1tv2ejY7rp7t6BUZPKCYO1yL9HEe4G4"> So somehow it got created within Typescript/Javascript folder

This can be opened up as a new one.
