### ISSUE TITLE
Get member invite code

### ISSUE THREAD

**Issue by zxsleebu** [discordjs/discord.js#9813]
### Which application or package is this feature request for?

discord.js

### Feature

member.getInviteCode()

### Ideal solution or implementation

use `/guilds/${guild_id}/members/supplemental` endpoint, with a payload `{"user_ids": [...]}`

this endpoint returns data formatted like this
```
[
    {
        "user_id": "...",
        "source_invite_code": "..."
    }
]
```

**Comment by almostSouji** [comment]
```json
{
	"message": "Bots cannot use this endpoint.",
	"code": 20001
}
```

**Comment by TuskarMA** [comment]
Good idea, but it's invalid endpoint

Tried and got a working solution with this code

`global.newMemberSearch = async (guildId, userId) => {
		let req1 = await rest.post(`/guilds/${guildId}/members-search`, {
			body: {
				"or_query": {},
				"and_query": {
					"user_id": {
						"or_query": [userId]
					}
				},
				"limit": 1
			},
		}).catch((err) => {
			return { success: false, error: err };
		})
			return req1.members[0];
	}`

**Comment by monbrey** [comment]
> Good idea, but it's invalid endpoint
> 
> Tried and got a working solution with this code
> 
> ```js
> global.newMemberSearch = async (guildId, userId) => {
> 		let req1 = await rest.post(`/guilds/${guildId}/members-search`, {
> 			body: {
> 				"or_query": {},
> 				"and_query": {
> 					"user_id": {
> 						"or_query": [userId]
> 					}
> 				},
> 				"limit": 1
> 			},
> 		}).catch((err) => {
> 			return { success: false, error: err };
> 		})
> 			return req1.members[0];
> 	}
> ```

Other than the misuse of await/catch/return in this codeblock, the use of undocumented APIs is prone to changes and errors. If/when Discord documents this endpoint, discord.js will support it.
