### ISSUE TITLE
Add an event emitter to Collections

### ISSUE THREAD

**Issue by littleBitsman** [discordjs/discord.js#9821]
### Which application or package is this feature request for?

collection

### Feature

Something to add (that is good in my opinion) to the Collection class is a way to listen for events (e.g., `dataAdded`, `dataChanged`, etc.)

### Ideal solution or implementation

Ideally, you could create a private `eventStream` member of class Collection, where the type is the class EventEmitter (from `node:events`). Then, wherever there is an implementation of modifying the Collection, the corresponding event could be fired. For example, when doing `Collection.set()` with a new key (that does not already exist), the `dataAdded` event is fired (e.g., `this.eventStream.emit('dataAdded', key, value`).

**Comment by jaw0r3k** [comment]
Definitely not a good idea
But youbcan implement it by yourself in your own package

**Comment by iCrawl** [comment]
Some real janky pseudo code here:

```ts
export class EventCollection extends Mixin(Collection, EventEmitter) {
  public override set(bla bla) {
    this.emit(bla bla);
    return super.set(bla bla);
  }
}
```

Uses https://github.com/tannerntannern/ts-mixer to get around the multiple-inheritance problem.

If you don't want to use ts-mixer, you could always just instantiate an event emitter inside the constructor after extending just the Collection class.

**Comment by iCrawl** [comment]
Some real janky pseudo code here:

```ts
export class EventCollection extends Mixin(Collection, EventEmitter) {
  public override set(bla bla) {
    this.emit(bla bla);
    return super.set(bla bla);
  }
}
```

Uses https://github.com/tannerntannern/ts-mixer to get around the multiple-inheritance problem.

If you dont want to use ts-mixer, you could always just instantiate an event emitter inside the constructor after extending just the Collection class.
