### ISSUE TITLE
SlashCommandBuilder not in new API docs

### ISSUE THREAD

**Issue by kpdyer16** [discordjs/discord.js#9832]
### Which application is this bug report for?

Documentation

### Issue description

I tried searching for SlashCommandBuilder in the API docs, but the page doesn't seem to exist. I was able to find out that it's still on [the old docs](https://old.discordjs.dev/#/docs/builders/main/class/SlashCommandBuilder). 

Also of note: there's at least one broken link to SlashCommandBuilder in the guide.

### Steps to Reproduce

1. Go to [discord.js.org/docs](https://discord.js.org/docs/#/)
2. Navigate to Documentation
3. Search for SlashCommandBuilder

As for the Guide,
1. Go to the [Advanced command creation page](https://discordjs.guide/slash-commands/advanced-creation.html#choices) and scroll down to **Choices**
2. Click link to [SlashCommandBuilder#addStringOption()](https://discord.js.org/docs/packages/builders/stable/SlashCommandBuilder:Class#/addStringOption)

### Versions

- Firefox 117.0
- MacOS Ventura 13.2.1

### Issue priority

Low (slightly annoying)

**Comment by Jiralite** [comment]
https://discord.js.org/docs/packages/builders/main/SlashCommandBuilder:Class

**Comment by kpdyer16** [comment]
Thanks, @Jiralite. Sorry, I should have tried that
