### ISSUE TITLE
`<PermissionsBitField>.missing('ManageGuildExpressions')` returning `ManageEmojisAndStickers`

### ISSUE THREAD

**Issue by Yareaj** [discordjs/discord.js#9836]
### Which package is this bug report for?

discord.js

### Issue description

1. Take a defined PermissionsBitField that does not have the `Administrator` bit nor `ManageGuildExpressions`
2. Run `<PermissionsBitField>.missing('ManageGuildExpressions')`
3. You would expect it to return only `[ 'ManageGuildExpressions' ]` but it returns `[ 'ManageEmojisAndStickers', 'ManageGuildExpressions' ]`

### Code sample

```typescript
new PermissionsBitField().missing('ManageGuildExpressions')
```

### Versions

discord.js@14.13.0
Node v18.17.1
Windows 10 Home

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

**Comment by almostSouji** [comment]
That is to be expected since they are the same bit.

https://github.com/discordjs/discord-api-types/blob/1598baf0c38d449ca51f456173a3980eca2980db/deno/payloads/common.ts#L178-L192

**Comment by Jiralite** [comment]
I also don't think we can remove the deprecated one as that would be a breaking change.
