### ISSUE TITLE
user.accentColor / member.displayColor / member.displayHexColor Null on Nitro

### ISSUE THREAD

**Issue by Taelyn** [discordjs/discord.js#9841]
### Which package is this bug report for?

discord.js

### Issue description

user.accentColor
member.displayColor
member.displayHexColor

Seems to be null when user / member has nitro subscription
I seem to only get user.accentColor working on a user without Nitro

### Code sample

```typescript
const user = await interaction.user.fetch();
console.log(user.accentColor);

const member = await interaction.member.fetch();
console.log(member.displayColor);
```

### Versions

discord.js v14.13.0
Typescript v5.2.2
Node LTS v18.17.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
You don't appear to be force-fetching. Force-fetching is required for the property to be present or updated [as documented](https://old.discordjs.dev/#/docs/discord.js/main/class/User?scrollTo=accentColor).

**Comment by Taelyn** [comment]
As i said it does not work ;) force or not, it does not give the data on a Nitro User
Nitro users have 2 color options on there profile instead of one

**Comment by Jiralite** [comment]
I cannot reproduce this.

**Comment by Taelyn** [comment]
Iam perfectly aware what the properties do. If you look in your own code:
```
  get displayColor() {
    return this.roles.color?.color ?? 0;
  }

  /**
   * The displayed color of this member in hexadecimal
   * @type {string}
   * @readonly
   */
  get displayHexColor() {
    return this.roles.color?.hexColor ?? '#000000';
  }
```

GuildMember.displayColor and HexColor is giveing the role color of the role that the member has.
So your documentation is wrong or you asigned the wrong code. Since neither the 2 properties have anywhere explained it gives a role color


```     
        const _member = await interaction.member.fetch(true);
        console.log("_member.displayColor: " + _member.displayColor);
        console.log("_member.displayHexColor: " + _member.displayHexColor);

        const _user = await interaction.user.fetch(true);
        console.log("_user.accentColor: " + _user.accentColor);
``` 
        
Now the user.accentColor

on a non nitro user:

![2023-09-19 10_15_31-#general _ Taelyn Bot - Discord](https://github.com/discordjs/discord.js/assets/38536376/6c36fc65-fe17-4bac-be92-8f7a3112356d)
![2023-09-19 10_16_09-TaelynBot - Microsoft Visual Studio](https://github.com/discordjs/discord.js/assets/38536376/d9a47aec-d4f0-434b-8689-1db0c4770069)

As you see it works, it outputs the accentColor the user has, Dark Green
and displayColor, displayHexColor output the Role color what is yellow

on a Nitro User:
![2023-09-19 10_18_53-taelynbotcore](https://github.com/discordjs/discord.js/assets/38536376/5549c539-c4ff-4c34-a456-c5d011064513)
![2023-09-19 10_19_01-#general _ Taelyn Bot - Discord](https://github.com/discordjs/discord.js/assets/38536376/b95f9a60-7744-4ad9-b54b-1e8fbb3dd564)

As you accentColor is Null. Since my profile has 2 colors due to nitro.
displayColor and displayHexColor give again the role color what is yellow

**Comment by Jiralite** [comment]
These properties are working as intended!

Since updates to guild member profiles, I can see a change in documentation could be made to alleviate the confusion between the colours in a profile and the role colour, but there is no issue in code here.

**Comment by almostSouji** [comment]
I looked into the accent color a little bit and the behavior we see in the library is consistent with the behavior of the API (which is wholly scuffed), so here is the current theory:

fancy profiles := two colors, banner

- (Banner color (hex) is the same value as accent color (decimal) - I think this is reflected in API docs as well)
- The accent color is utterly disconnected from fancy profiles
- Non-nitro users do not have fancy profiles but can set a single, solid, accent color instead
- If non-nitro users do not manually set an accent color, the API will return `null` and the client will instead determine it based on the avatar
- If a user gets access to fancy profiles, this value persists, if it was set before
- The two colors used in fancy profiles are not exposed through the bot API

This would suggest, that you never set a manual, solid, banner (aka accent) color before you got access to fancy profiles, but instead relied on the auto-set one based on your avatar, hence the value is `null`.

_Fun fact: Guild banners are also not exposed at all, despite user banners being exposed - consistency._

**Comment by Taelyn** [comment]
Thanks both!
