### ISSUE TITLE
Update documentation to clearly differentiate role-based display color from fancy profile colors

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#9842]
Since updates to guild member profiles, I can see a change in documentation could be made to alleviate the confusion between the colours in a profile and the role colour, but there is no issue in code here.

_Originally posted by @Jiralite in https://github.com/discordjs/discord.js/issues/9841#issuecomment-1725014406_

**Comment by coding-agent** [comment]
Hi, I would like to work in this issue. Is there anyone working on it already?
