### ISSUE TITLE
Feature Request - Submit Voice Messages like on mobile

### ISSUE THREAD

**Issue by Ugleh** [discordjs/discord.js#9850]
### Which application or package is this feature request for?

discord.js

### Feature

Submit Voice Messages like on mobile

### Ideal solution or implementation

Not quite sure. I imagine it would be connected with TextBasedChannel#send

**Comment by Jiralite** [comment]
This needs to exist first in the API. You can submit feature requests over at [discord-api-docs](https://github.com/discord/discord-api-docs/discussions).
