### ISSUE TITLE
Add support for entitlement (App Subscriptions)

### ISSUE THREAD

**Issue by JMTK** [discordjs/discord.js#9856]
### Which application or package is this feature request for?

discord.js

### Feature

- https://github.com/discord/discord-api-docs/pull/6451

<hr>

#### New entitlement events:
https://discord.com/developers/docs/monetization/entitlements#gateway-events
> Fires when a user subscribes to a SKU. Contains an entitlement object.

#### PREMIUM_REQUIRED Interaction Response
https://discord.com/developers/docs/monetization/entitlements#using-entitlements-in-interactions
> If your app has monetization enabled, it will have access to a new [PREMIUM_REQUIRED interaction response (type: 10)](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type). This can be sent in response to any kind of interaction. It does not allow a content field.

#### Entitlements class/endpoints
https://discord.com/developers/docs/monetization/entitlements#entitlement-object
```js
{
    "id": "1019653849998299136",
    "sku_id": "1019475255913222144",
    "application_id": "1019370614521200640",
    "user_id": "771129655544643584",
    "promotion_id": null,
    "type": 8,
    "deleted": false,
    "gift_code_flags": 0,
    "consumed": false,
    "starts_at": "2022-09-14T17:00:18.704163+00:00",
    "ends_at": "2022-10-14T17:00:18.704163+00:00",
    "guild_id": "1015034326372454400",
    "subscription_id": "1019653835926409216"
}
```

### Ideal solution or implementation

```js
client
.on('entitlementCreate', () => {})
.on('entitlementUpdate', () => {})
.on('entitlementDelete', () => {})
```

**Comment by JMTK** [comment]
Is there any way to temporarily support this? I was trying to do something like:
```js
return interaction.reply({
    body: {
        type: 10,
        data: {}
    }
});
```

But in InteractionResponses.js, it hardcodes the body and type even if you pass it in:
```js
await this.client.rest.post(Routes.interactionCallback(this.id, this.token), {
  body: {
    type: InteractionResponseType.ChannelMessageWithSource,
    data,
  },
  files,
  auth: false,
});
```

**Comment by Renegade334** [comment]
dependency: discordjs/discord-api-types#833

**Comment by monbrey** [comment]
> Is there any way to temporarily support this?

The body is hard coded because each method is a specific response type. We don't support overwriting the body via these, but you're welcome to make the `client.rest.post` call yourself with any body you like.
