### ISSUE TITLE
Filter/choices for `SlashCommandChannelOption`

### ISSUE THREAD

**Issue by yyueniao** [discordjs/discord.js#9858]
### Which application or package is this feature request for?

discord.js

### Feature

Maybe duplicate of https://github.com/discordjs/discord.js/issues/6457

I really need some custom filter callback or choices to limit the channel option for one of my slash command. I understand we have `addChannelTypes` for `SlashCommandChannelOption` builder already, but I need some further filter (or even hardcoded choices) to limit the option of user.

Even further, can we add this `filter` callback for all possible `SlashCommandOption`? For example `SlashCommandChannelOption`, `SlashCommandRoleOption` etc.

### Ideal solution or implementation

Add a new `ApplicationCommandFilterableOption` abstract class and implement it for those "filterable" option.

### Alternative solutions or implementations

Implement `ApplicationCommandOptionWithChoicesAndAutocompleteMixin` for `SlashCommandChannelOption` and `SlashCommandRoleOption`.

**Comment by Jiralite** [comment]
> I need some further filter (or even hardcoded choices) to limit the option of user.

Are you talking about showing options to the user? If so, only Discord can control that—not discord.js.

> Even further, can we add this `filter` callback for all possible `SlashCommandOption`? For example `SlashCommandChannelOption`, `SlashCommandRoleOption` etc.

Are you talking about a runtime check? You can either do that yourself or use the third parameter in [`CommandInteractionOptionResolver#getChannel()`](https://old.discordjs.dev/#/docs/discord.js/14.13.0/class/CommandInteractionOptionResolver?scrollTo=getChannel).

Else, what do you mean?

**Comment by yyueniao** [comment]
> Are you talking about showing options to the user? If so, only Discord can control that—not discord.js.

Exactly, then I will close this issue, thanks for your reply!
