### ISSUE TITLE
MessageReaction.me is true even though Reaction was not triggered by bot

### ISSUE THREAD

**Issue by Ryce** [discordjs/discord.js#9884]
### Which package is this bug report for?

discord.js

### Issue description

1. Send a message reaction in discord to a message
2. check the `MessageReaction.me` variable
3. Its true even though the reaction was not created by the bot

Just some observations from my end, I noticed that this flag is set to false *IF* there was no prior message reaction set on a given message. So if the bot FIRST triggers a reaction for a specific emoji, any subsequent reaction hit by others will set the `.me` variable to true. However, if the bot never reacted to a given emoji, then the `me` variable correctly comes through as `false`

Since there is no other way to validate *who* the message reaction was sent from, I believe its a high priority issue and a blocker for us.

### Versions

discord.js 14.10.2
node v18.2.0
typescript 4.9.5
Tried on AWS Linux and macOS Sonoma & Catalina

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, GuildMessageReactions, GuildMessageTyping, MessageContent

**Comment by Jiralite** [comment]
Please provide a code sample.

**Comment by Ryce** [comment]
> Please provide a code sample.

What exactly do you need me to write in a code sample? I have tested the API and am seeing the variable coming through as true or false in the logs

If it makes you happy:

```
client.on('messageReactionAdd', (reaction) => {
  console.log(reaction.me);
})
```

**Comment by Jiralite** [comment]
A [code sample](https://stackoverflow.com/help/minimal-reproducible-example) is something people may copy & paste to see the problem manifest in a minimal way.

<hr>

I cannot reproduce the issue. I reacted to a message (1) and `reaction.me` is `false` (2). The bot did not create the reaction (3).

Could you revise your steps or elaborate?

**Comment by Qjuh** [comment]
That event emits with a second parameter, `user`, which you‘d probably want to use.

**Comment by aleccaputo** [comment]
Bringing this back up because i just ran into this and i'm not sure why although i know HOW. It seems to be happening when my bot programmatically removes a reaction with the following
```ts
            if (!valid) {
                const fullUser = await user.fetch();
                await reaction.users.remove(fullUser);
                return;
            }
```
Now if I (the human who's reaction was removed) try and react again, `reaction.me` is now true in my code
```ts
    client.on(Events.MessageReactionRemove, async (reaction, user) => {
            if (reaction.me) {
                return;
            }
```

Things to note...the bot will have already reacted with a base reaction (the same emoji). It does successfully respond to the event on the first reaction add and removes it as it should....but the next time it does not as it thinks it's `reaction.me` creating the manual response

@Jiralite have you seen anything like this before?

**Comment by RedGuy12** [comment]
I believe `reaction` is just generic information about the reaction, and `user` is the user who reacted and triggered the event. For instance, `reaction.users` contains all the users who've reacted with that emoji, not just the newest one. Therefore, `reaction.me` just returns whether or not the bot has added that emoji reaction to that message.

You probably want `user.id === user.client.id`. (`client` is a property on most Discord.JS classes that references the logged-in client)

**Comment by aleccaputo** [comment]
Ah! Thank you very much. It just must have been a side effect that I thought it was working the way i imagined in my head, but that makes sense now. Thanks for the response!
