### ISSUE TITLE
Update nodejs engine to 18

### ISSUE THREAD

**Issue by JMTK** [discordjs/discord.js#9886]
### Which application or package is this feature request for?

discord.js

### Feature

Nodejs 16 is now EOL as of September 11 2023 and 18 is now LTS https://nodejs.dev/en/about/releases/

### Ideal solution or implementation

Update all package engines to be 18+. 

Experimental fetch is now enabled by default and can probably replace any undici references.

**Comment by ckohen** [comment]
This will occur no earlier than the next major version (has already been done in many other packages).

Also of note, undici references will not be removed in discord.js. The main library is not intended to be used in browser environments, and undici request is more stable than fetch. Anything that can be used in browser / edge environments has already been updated to use global fetch when not in node (this includes in deno / bun).

**Comment by JMTK** [comment]
Seems like this issue can be closed: https://github.com/discordjs/discord.js/commit/ee2afb0aaed17648c46916220404d1fba1bd0147

**Comment by Syjalo** [comment]
discord.js is still on v16. As @ckohen said
> This will occur no earlier than the next major version
