### ISSUE TITLE
guildMembersRemoved not firing if first event

### ISSUE THREAD

**Issue by C0unterPo1nt** [discordjs/discord.js#9887]
### Which package is this bug report for?

discord.js

### Issue description

The guildMembersRemoved event on the Client class does not properly fire the first time that Client fires an event. If any other client event is fired first, guildMembersRemove will behave normally.

Repro steps:
- enable guild members privileged intent in dev portal
- run code sample
- be sure that no unwanted gateway traffic is occuring
- kick a user in the same server as the bot -> no console.log
- kick a second user in the same server as the bot -> console.log message activates this time

### Code sample

```typescript
const token = "token here"
const { Client, IntentsBitField } = require('discord.js');
const intents = new IntentsBitField(2);
const client = new Client({ intents: [intents] });

client.on("guildMemberRemove", (member) => {
  console.log(member + ' removed');
});

client.login(token);
```

### Versions

- discord.js 14.13.0
- npm: 8.19.3
- node: 16.19.0
- MacOS 14.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers

### I have tested this issue on a development release

7276e7c4b

**Comment by Jiralite** [comment]
You have no partials. https://discordjs.guide/popular-topics/partials.html
