### ISSUE TITLE
4 low severity vulnerabilities in discord.js

### ISSUE THREAD

**Issue by FunnyIvri** [discordjs/discord.js#9898]
### Which package is this bug report for?

discord.js

### Issue description

steps to reproduce:
 `npm i discord.js`
 `npm audit`

this will give you:
```
# npm audit report

undici  <5.26.2
Undici's cookie header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-wqq4-5wpv-mx2g
fix available via `npm audit fix --force`
Will install discord.js@14.12.1, which is a breaking change
node_modules/undici
  @discordjs/rest  >=2.0.1-dev.1690848847-1af7e5a0b.0
  Depends on vulnerable versions of undici
  node_modules/@discordjs/rest
    @discordjs/ws  >=1.0.1-dev.1690848792-1af7e5a0b.0
    Depends on vulnerable versions of @discordjs/rest
    node_modules/@discordjs/ws
    discord.js  14.0.0-dev.1640779371.9cdc448 - 14.0.0-dev.1657757514-fe34f48 || 14.12.2-dev.1690891477-7295a3a94.0 - 14.14.0-dev.1697457861-6a63c441f
    Depends on vulnerable versions of @discordjs/rest
    Depends on vulnerable versions of @discordjs/ws
    Depends on vulnerable versions of undici
    node_modules/discord.js

4 low severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

discord.js is the only package installed in my project and when I remove discord.js it goes away.
`npm audit fix`
and
`npm audit fix --force`
do nothing

### Code sample

```typescript
npm i discord.js
npm audit
```

### Versions

 I tested multiple versions of discord.js all gave me the error, this also happened in every one of my old V14 bots, that didn't have any issues before and I have not updated.

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable, No Intents

### I have tested this issue on a development release

discord.js@14.14.0-dev.1697457861-6a63c441f

**Comment by Jiralite** [comment]
Hey, thank you for this, but make sure you search for existing issues or pull requests first. It could save you time!

**Comment by FunnyIvri** [comment]
> Hey, thank you for this, but make sure you search for existing issues or pull requests first. It could save you time!

I checked couldn't find any.
 did you?

**Comment by Jiralite** [comment]
- #9892
- #9893
- #9894
- #9895
- #9896
- #9897
