### ISSUE TITLE
Generated scope in OAuth2 URL is invalid

### ISSUE THREAD

**Issue by RyanGarber** [discordjs/discord.js#9905]
### Which package is this bug report for?

core

### Issue description

`OAuth2API.generateAuthorizationURL()` joins scopes with a comma which isn't valid. The correct delimiter is any URL encoded form of a space (' ', '+', or '%20').

### Code sample

```typescript
OAuth2API.generateAuthorizationURL({scope: ["identify","guilds"]});
// OAuth2 URL is generated with "&scope=identify,guilds" which results in an error.
```

### Versions

@discordjs/core 1.0.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
`scopes` is a `string`.
