### ISSUE TITLE
Ability to customize the deferReply message

### ISSUE THREAD

**Issue by ByronBecker** [discordjs/discord.js#9912]
### Which application or package is this feature request for?

discord.js

### Feature

To provide a better user experience for my bot users, I'd like to be able to customize the deferred response experience of my bot's users when a specific command could take at least 2-4 seconds for a reply.

My current solution is to first reply to the user with a personalized message (I cycle through a random reply string out of 10 possible strings each time the user sends a command), and then once my async process is completed edit the original reply message.

While this solution works, the initial reply text UI in the frontend gives the user a "final" reply UX, whereas the deferred reply three dot animation signals to the user the deferred response UX.

### Ideal solution or implementation

Ideally, `deferReply` would take a `content` or `message` field of type string, and then respond with that custom text to the user while waiting for the `followUp` response.

**Comment by Jiralite** [comment]
Feature requests for the API go to https://github.com/discord/discord-api-docs/discussions/categories/api-feature-requests-ideas.
