### ISSUE TITLE
bug: Discord.js package search making not proper urls

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord.js#9931]
### Which application is this bug report for?

Documentation

### Issue description

Specifically the version part of the url is missing, which makes the url invalid 

Actual:
![image](https://github.com/discordjs/discord.js/assets/76836550/e80417ce-3780-4592-81a4-2adcdbfaecb6)
Search result: 
![image](https://github.com/discordjs/discord.js/assets/76836550/a85d864b-3b72-49f7-a31f-4bed965c5e2d)

Not mentioning that the only supported version is just main, so some other implementation of parser should be taken or allow current website to support djs one

### Steps to Reproduce

Use search in newly added djs package, and it will redirect you to 404 page

### Issue priority

Medium (should be fixed soon)

**Comment by iCrawl** [comment]
This is fixed now 👍
