### ISSUE TITLE
500 error when accesing some pages in the new main docs

### ISSUE THREAD

**Issue by kaytitulaer3820** [discordjs/discord.js#9936]
### Which application is this bug report for?

Documentation

### Issue description

When accesing some pages like
- https://discordjs.dev/docs/packages/discord.js/main/GuildAuditLogsEntryExtraField:Interface
- https://discordjs.dev/docs/packages/discord.js/main/Team:Class
- https://discordjs.dev/docs/packages/discord.js/main/TeamMember:Class

it returns a 500 error
<img width="1919" alt="image" src="https://github.com/discordjs/discord.js/assets/76474615/8fe74478-d8a1-4d54-aaf9-cc1d44f36d8e">

### Steps to Reproduce

Way 1:
- Visit https://discordjs.dev/docs/packages/discord.js/main/GuildAuditLogsEntry:Class
- Go to extra and click the reference
<img width="782" alt="image" src="https://github.com/discordjs/discord.js/assets/76474615/ddf83630-f84f-422a-adc0-fc9c46f93bee">

Way 2:
- Directly go to one of the following pages
- https://discordjs.dev/docs/packages/discord.js/main/GuildAuditLogsEntryExtraField:Interface
- https://discordjs.dev/docs/packages/discord.js/main/TeamMember:Class
- https://discordjs.dev/docs/packages/discord.js/main/Team:Class

There are probably more

### Versions

Google Chrome 118.0.5993.120 (Officiële build) (64-bits) (cohort: M119 Rollout) 
Windows 11 Version 22H2 (Build 23580.1000)

### Issue priority

Medium (should be fixed soon)

**Comment by RedGuy12** [comment]
I'm getting a 500 on https://discordjs.dev/docs/packages/discord.js too :thinking:

**Comment by kaytitulaer3820** [comment]
> I'm getting a 500 on https://discordjs.dev/docs/packages/discord.js too 🤔

seems like that page should list all versions as buttons to redirect to the docs of those verions
https://github.com/discordjs/discord.js/blob/main/apps/website/src/app/docs/packages/%5Bpackage%5D/page.tsx

**Comment by Jiralite** [comment]
These should be resolved now.
