### ISSUE TITLE
Calling client.destroy() doesn't make client.isReady() return false

### ISSUE THREAD

**Issue by axl89** [discordjs/discord.js#9941]
### Which package is this bug report for?

discord.js

### Issue description

1. Log in with a Client with the `login()` function.
2. Then call the `destroy()` function to this same client.
3. And check that the `isReady()` function still returns `true` even though the `client.ws.destroyed` property is `true`.

### Code sample

```typescript
const { Client, GatewayIntentBits } = require('discord.js');

const client = new Client({
	intents: [
		GatewayIntentBits.Guilds,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.MessageContent,
		GatewayIntentBits.GuildMessageReactions,
	],
});

const main = async () => {
	await client.login();
	console.log(client.isReady());
	console.log(client.ws.destroyed);
	await client.destroy();
	console.log(client.isReady());
	console.log(client.ws.destroyed);
};

main();
```

### Versions

- discord.js@14.13.0
- node v20.9.0
- Linux cursed 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, MessageContent

**Comment by Jiralite** [comment]
Hey, thank you for the report. Just a note that your code sample is logically incorrect since `await`ing `client.login()` will only return when the client has connected to the gateway and _not_ when discord.js is ready. Utilising the ready event is the proper reproduction.

**Comment by axl89** [comment]
Thanks @Jiralite, still learning my way through Javascript and this library! :smile:
