### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by wmslei** [discordjs/discord.js#9972]
### Which package is this bug report for?

discord.js

### Issue description

Send one file with AttachmentBuilder in a message, but sometimes two are displayed in discord. I'm not sure if this is a problem with discord UI or the discord.js SDK.

### Code sample

```typescript
await channel.send(
{
content: 'some message',
files: [new AttachmentBuilder(url, {name: 'filename.mp4'})],
components: [
new ActionRowBuilder().setComponents(
new ButtonBuilder().setStyle(ButtonStyle.Link).setURL(url).setLabel(name)
),
new ActionRowBuilder().setComponents(
new ButtonBuilder().setStyle(ButtonStyle.Secondary).setCustomId('custom_id').setEmoji('🔄');
),
],
}
)
```

### Versions

node v18.18.2
discord.js v14.13.0

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers

**Comment by Renegade334** [comment]
Sounds related to discord/discord-api-docs#6500

**Comment by Jiralite** [comment]
It does indeed sound related.

@wmslei, you should monitor your outgoing API requests. If they only contain one element in the `files` array, then it's not a discord.js issue.

**Comment by wmslei** [comment]
> Sounds related to [discord/discord-api-docs#6500](https://github.com/discord/discord-api-docs/issues/6500)

At the same time, I found that when two attachments were displayed, their download links were exactly the same。

**Comment by wmslei** [comment]
> It does indeed sound related.
> 
> @wmslei, you should monitor your outgoing API requests. If they only contain one element in the `files` array, then it's not a discord.js issue.

OK, I will monitor it.

**Comment by Renegade334** [comment]
A fix for the message element duplication bug was deployed about a week ago. @wmslei, have you had any issues since?

**Comment by Jiralite** [comment]
Discord implemented a mitigation. Feel free to reopen if you still encounter this.

**Comment by wmslei** [comment]
> A fix for the message element duplication bug was deployed about a week ago. @wmslei, have you had any issues since?

It hasn't happened again recently, thanks.

**Comment by wmslei** [comment]
> encounter

OK, thank you.

**Comment by wmslei** [comment]
> Discord implemented a mitigation. Feel free to reopen if you still encounter this.

Ok, thank you.
