### ISSUE TITLE
Add Property: CommandInteraction.commandFullName

### ISSUE THREAD

**Issue by EgizianoEG** [discordjs/discord.js#9979]
### Request for: 

discord.js

### Feature

It would be nice if we could have a command interaction property called `commandFullName` instead of manually defining it like the example below. It should have the base command name, sub-command group name (if it exists), sub-command name (also if it exists).

### Ideal solution or implementation

```ts
  const CommandName = Interaction.commandName;
  const FullCmdName = [
    CommandName,
    Interaction.options.getSubcommandGroup(false),
    Interaction.options.getSubcommand(false),
  ]
    .filter(Boolean)
    .join(" ");
```

### Alternative solutions or implementations

_N/A_

### Other context

_N/A_

**Comment by Jiralite** [comment]
This just looks like https://old.discordjs.dev/#/docs/discord.js/14.14.1/class/ChatInputCommandInteraction?scrollTo=toString, no?

**Comment by EgizianoEG** [comment]
> This just looks like https://old.discordjs.dev/#/docs/discord.js/14.14.1/class/ChatInputCommandInteraction?scrollTo=toString, no?

It looks similar but with the command options and an extra slash at the beginning.

**Comment by Jiralite** [comment]
What's the use case of this?

**Comment by EgizianoEG** [comment]
> What's the use case of this?

Currently for logging errors and such.
I guess that can be already replaced with your mentioned method `toString` (I haven't tried it until now).
