### ISSUE TITLE
Errors after building with tsup

### ISSUE THREAD

**Issue by nicoduesing** [discordjs/discord.js#9991]
### Which package is this bug report for?

discord.js

### Issue description

The following error is shown on running the index.ts after building with tsup:
```
/dist/index.js:43253
    var __name = (target, value) => __defProp2(target, "name", { value, configurable: true });
                                    ^

TypeError: Object.defineProperty called on non-object
    at defineProperty (<anonymous>)
    at __name (/dist/index.js:43253:37)
    at <static_initializer> (/dist/index.js:43322:9)
    at node_modules/@discordjs/ws/dist/index.js (/dist/index.js:43316:41)
    at __require (/dist/index.js:32:50)
    at node_modules/discord.js/src/client/websocket/WebSocketManager.js (/dist/index.js:45421:9)
    at __require (/dist/index.js:32:50)
    at node_modules/discord.js/src/client/Client.js (/dist/index.js:49105:28)
    at __require (/dist/index.js:32:50)
    at node_modules/discord.js/src/index.js (/dist/index.js:50144:23)

Node.js v20.8.0
```

To reproduce this bug, create a project like the following:
- project
  - `index.ts`
  - `package.json`

The content of the files is the following:
`index.ts`:
```typescript
import { Client, GatewayIntentBits } from "discord.js";
const client = new Client({ intents: [] });
```

`package.json`:
```json
{
  "name": "discordbug",
  "scripts": {
    "build": "tsup index.ts",
  },
  "dependencies": {
    "discord.js": "14.14.1"
  },
  "devDependencies": {
    "typescript": "5.2.2",
    "tsup": "6.2.1"
  }
}
```

Run the following commands:
1. `yarn install`
2. `yarn run build`
3. `node dist/index.js`

The last command returns the error above.

### Code sample

```typescript
import { Client, GatewayIntentBits } from "discord.js";
const client = new Client({ intents: [] });
```

### Versions

- discord.js: 14.14.1
- tsup: 6.2.1
- typescript: 5.2.2
- node: 20.9.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by Jiralite** [comment]
<details>
<summary>I cannot reproduce this issue.</summary>

```
$ tsup index.ts
CLI Building entry: index.ts
CLI tsup v6.2.1
CLI Target: node14
CJS Build start
CJS ⚡️ Build success in 13ms
CJS dist/index.js 113.00 B
✨  Done in 0.50s.
jiralite@Jiralites-MacBook-Pro test % node dist/index.js 
jiralite@Jiralites-MacBook-Pro test % 
```

<img width="1298" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/235de952-6e02-4730-8e41-e80913468540">
</details>

Also... tsup 6.2.1? tsup is on at least version 8 by now. At a first glance, this is probably an issue with a configuration of yours of tsup rather than this being a discord.js issue.

**Comment by nicoduesing** [comment]
Ah, sorry, I had an config in a parent directory, that was used. I found the problem. The error was caused by `target: "node20"` . I'm using tsup because newer versions changed something in the way it bundles the dependencies, so it is not allowing to bundle everything into a single file.
