### ISSUE TITLE
Module not found: Can't resolve 'zlib-sync' with pnpm

### ISSUE THREAD

**Issue by m1heng** [discordjs/discord.js#9993]
### Which package is this bug report for?

discord.js

### Issue description

Installed "discord.js" with pnpm in the nextjs project, and had below error
```
 ⨯ ../../node_modules/.pnpm/@discordjs+ws@1.0.2/node_modules/@discordjs/ws/dist/index.js:561:53
Module not found: Can't resolve 'zlib-sync'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/.pnpm/discord.js@14.14.1/node_modules/discord.js/src/index.js
```

### Versions

  "name": "@discordjs/ws" "version": "1.0.2",
  "name": "discord.js" "version": "14.14.1",

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Qjuh** [comment]
are you trying to run a bot with a persistent gateway connection (which discord.js is) in frontend code? That won't work *and* leak your token to anyone visiting that website.

**Comment by didinele** [comment]
Considering the lack of a response to the above or actual repro steps, I'm closing this.
